#include "..\headers\define.h"
#include "..\headers\command.h"

procedure start;
procedure wm_unfade;

procedure start begin
    if (metarule(22, 0)) then
        return;

    if (game_loaded) then
		register_hook_proc(HOOK_GAMEMODECHANGE, wm_unfade);

end

procedure wm_unfade begin
    if(in_world_map) then begin

        fadein(1);

        // Conditions for the lost Enclave patrol special encounter
        if (
            (global_var(GVAR_SPECIAL_ENCOUNTER_ENCLAVE) == 0) and
            (dude_skill(SKILL_OUTDOORSMAN) >= 100) and
            (dude_luck >= 8)
        ) then begin
            set_global_var(GVAR_SPECIAL_ENCOUNTER_ENCLAVE, 1);
        end

        // Conditions for the thunderbird special encounter
        if (
            (global_var(GVAR_SPECIAL_ENCOUNTER_THUNDERBIRD) == 0) and
            (dude_luck < 5)
        ) then begin
            set_global_var(GVAR_SPECIAL_ENCOUNTER_THUNDERBIRD, 1);
        end
    end
end
