/*******************************************************************************
        Name:        The Hanged Man
        Location:
        Description:

                       Created: 19/08/2020 23:23:13
            Updated:

*******************************************************************************/
//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        9 /* same as thief variable */

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\ModReact.h"
#include "..\headers\party.h"
#include "..\HEADERS\partybkg.h"
#include "..\HEADERS\footsteps.h"

/* Don't forget to change the NAME and TOWN_REP_VAR variables to match your new critter */
#define NAME                    SCRIPT_HANGDMAN
#define TOWN_REP_VAR            GVAR_TOWN_REP_FORT_ABANDON              // Need to specify global.h variable for town rep modifiers if used (replace "GVAR_TOWN_REP_" with actual global variable name)

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure push_p_proc;
procedure timed_event_p_proc;

/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

/*****************************************************************
Node001 is a dialogue node that includes a line asking to join the party.
Node002 has several game checks before joining with fail/pass responses.
*****************************************************************/
procedure Node001;
procedure Node002;

/*****************************************************************
Party Member pre-requisites
These lines are necessary for the critter to join the player
as a party member.
*****************************************************************/
procedure Join_Party;                                    // Party Join node
procedure Abandon_Party;                                 // Party Abandon node
procedure Node1000;                                      // Main party member node
procedure Node1001;                                      // heal yourself
procedure Node1002;                                      // wait here
procedure Node1003;                                      // put your weapon away
procedure Node1004;                                      // follow close
procedure Node1005;                                      // follow medium
procedure Node1006;                                      // follow far
procedure Node1007;                                      // change distance menu
procedure Node1008;                                      // look at gear menu
procedure Node1009;                                      // remove armor menu
procedure Node1010;                                      // weapon abilities
procedure Node1100;                                      // rejoin party


/* Change "Hanged_Man" to match the name of your new critter */
#define Hanged_Man_joins_party             party_add_self;                                                   \
                                               critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_PLAYER)
#define dude_has_free_slot_for_Hanged_Man  ((dude_at_max_party_size == false) and (Hanged_Man_In_Party == false))     // Need to declare Hanged_Man_In_Party in PARTY.H

/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_

      To have LVars work, open scripts.LST, scroll to your character's script name,
      and change the "LVars" setting to at least 8,
      Since there are 8 Local Variables used below.

      (LVAR_ 0 thru 3 are reserved for NPC Reaction Modifiers...
      ...will add more instructions when I learn how they work.)
*****************************************************************/
#define LVAR_Flags                      (4)
#define LVAR_WAITING                    (5)
#define LVAR_FOLLOW_DISTANCE            (6)
#define LVAR_TEAM                       (7)
#define LVAR_Joined_Player              (8)
#define LVAR_Caught_Thief               (9)

/*****************************************************************
      If you would rather use the LVAR_Hostile, LVAR_Herebefore, LVAR_Personal_Enemy
      variables instead of LVAR_Flags, uncomment the relevent lines and comment out
      lines with set_herebefore, set_hostile, if (hostile) and (self_can_see_dude).
*****************************************************************/
//#define LVAR_Hostile                    (9)
#define LVAR_Herebefore                 (10)
//#define LVAR_Personal_Enemy             (11)

#define PARTY_NODE_X                      Node1000

/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/

/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin

end

procedure map_enter_p_proc begin

   //party_member_map_enter;

   if (not(Hanged_Man_In_Party)) then begin
      critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_FORT_ABANDON);
   end

//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
   if(global_var(GVAR_FA_LEGION_GONE) == 2) then begin
      set_obj_visibility(self_obj, 0);
      add_timer_event(self_obj,game_ticks(random(1,3)),0);
   end else begin
      set_obj_visibility(self_obj, 1);
   end

   call critter_setup_footsteps_map_enter(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT);
end

procedure critter_p_proc begin
   /* Every heartbeat that the critter gets, this procedure will be called. Anything from
      Movement to attacking the player on sight can be placed in here.
      If the critter is mad at the player for any reason, it will attack and remember to attack
      the player should the game be saved and loaded repeatedly. Additionally, if any special
      actions need to be taken by the critter based on previous combat, the critter will remember
      this as well. */

//   if ((local_var(LVAR_Hostile) > 1) and (self_can_see_dude)) then begin
//      set_local_var(LVAR_Hostile,1);
   if (hostile) and (self_can_see_dude) then begin
      self_attack_dude; //Macro made by Tom to keep the critter fleeing.
   end

   /* This next script moves the new party member to follow the player after they've joined and
      when entering new maps. */
   if (Hanged_Man_In_Party) then begin
      if (party_is_waiting == false) then begin
         party_member_follow_dude
      end
   end

   /*
   -----   These are examples of common Abandon_Party calls, use...or don't...at your discretion   -----

   else if (Hanged_Man_In_Party) then begin
      if (global_var(GVAR_PLAYER_REPUTATION) < Hanged_Man_Bad_Karma) then begin
         call Abandon_Party;
         debug_msg("Hanged_Man Bad Player Rep");
      end
      else if (has_rep_childkiller) then begin
         call Abandon_Party;
         debug_msg("Hanged_Man: Child Killer");
      end
      else if (has_rep_berserker) then begin
         call Abandon_Party;
         debug_msg("Hanged_Man: Berserker");
      end
      else if (has_rep_slaver) then begin
         call Abandon_Party;
         debug_msg("Hanged_Man: Slaver Rep");
      end*/

end

procedure damage_p_proc begin
   /* Whenever the critter takes damage of any type, this procedure will be called. Things
      like setting ENEMY_ and LVAR_Personal_Enemy can be set here.
      If the player causes damage to this critter, then he will instantly consider the player
      his personal enemy. In Critter_Proc or through dialog, actions will be taken against
      the player for his evil acts. */

   if (obj_in_party(source_obj)) then begin
//       set_local_var(LVAR_Personal_Enemy, 1);
      set_personal_enemy;
   end

end

procedure pickup_p_proc begin
   /* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
      In here, various things can happen. The most common response is instant hostility which
      will be remembered. */

   if (source_obj == dude_obj) then begin
//      set_local_var(LVAR_Hostile, 2);
      set_hostile;
   end

end

procedure talk_p_proc begin
   /* These next two scripts are for recruiting a new character to your party,
      Node1000 in particular is necessary to connect to the generic party member inventory
      and combat settings.
      Open Party.h and create a new pointer for your new party member critter at the top of the #defines.
      Replace "Hanged_Man_Ptr" with the pointer for your new character created in Party.h */

   /* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
      written by designers are placed in here. Additionally, Reactions are generated and
      stored which affects player interactions. */
   Evil_Critter:=1;
   Slavery_Tolerant:=SLAVE_VERY_INTOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

   find_party_background;
   call set_idiot_savant_int;

   start_gdialog(NAME,self_obj,4,HEAD_HANGED_MAN,PartyMemberBackground);
   gSay_Start;
   if ((Hanged_Man_Ptr != 0) or (party_is_waiting)) then begin      //Hanged_Man_Ptr needs to be declared in Party.h with your own "Hanged_Man"
      call Node1000;
   end
   else begin
      call Node001;
   end

   gSay_End;
   end_dialogue;

   call restore_idiot_savant_int;

end

procedure destroy_p_proc begin
   /* This procedure gets called only on the death of this NPC. Special things like
       incrementing the death count for reputation purposes and Enemy Counters are placed
       in here. */

   /* Increment the aligned critter counter
        This counter affects your karma? */
   //inc_good_critter
   inc_evil_critter
   //inc_neutral_critter

   /* Set global_variable for Enemy status*/

end

procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

procedure push_p_proc begin
   if (random(1, 3) == 1) then begin
      floater(156);                               // Float response for being pushed by player
   end
end



procedure timed_event_p_proc begin
   if (fixed_param == 0) then begin
      variable critters, critter, ai, team;
      add_timer_event(self_obj,game_ticks(random(1,5)),0);

      if(obj_is_visible_flag(self_obj) and combat_is_initialized == false and ((critter_state(self_obj) bwand DAM_KNOCKED_OUT) == false)) then begin
         critters := objects_in_radius(self_tile, get_critter_base_stat(self_obj, STAT_pe), self_elevation, OBJ_TYPE_CRITTER);

         foreach (critter in critters) begin
            if(critter_attackable(critter)) then begin
               team := has_trait(TRAIT_OBJECT, critter, OBJECT_TEAM_NUM);
               ai := has_trait(TRAIT_OBJECT, critter, OBJECT_AI_PACKET);

               if(TEAM_CAESARS_LEGION == team) then begin
                  floater_bad(150);
                  self_attack_critter(critter);
                  break;
               end else if (AI_ARROYO_WARRIOR == ai or AI_ARROYO_ELDER == ai or AI_ARROYO_SHAMAN == ai) then begin
                  floater_bad(151);
                  self_attack_critter(critter);
                  break;
               end
            end
         end
      end
   end

   call critter_setup_footsteps_timed_event(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT, SFX_FOOTSTEP_SOFT_SHOE);
end

procedure Node001
begin
   if (Hanged_Man_In_Party == false) then begin
Reply(200);
NOption(201,Node002,4);
NOption(202,Node999,4);
NOption(203,Node002,-3);
NOption(204,Node999,-3);
   end else begin
      call Node1000;
   end
end

procedure Node002 begin
   /* This node checks for stuff before allowing NPC to join party.
       You can add other conditions for joining here. */
   if (dude_charisma <= 1) then begin
     NMessage(152);                                      // This NOption message(800) is a response if player has 1 Charisma or less (can't have party members because too ugly)
end else begin
   if (dude_at_max_party_size) then begin
   Reply(153);                                           // This line is for when the character does NOT join the player's party       (because too many followers)
      NOption(g_mstr(209),Node999,4);                            // This NOption message is Normal Int player response to NOT joining party    (because too many followers)
      NLowOption(g_mstr(301),Node999);                           // This NLowOption message is Low Int player response to NOT joining party    (because too many followers)

   end else if town_rep_is_hated then begin
   Reply(154);                                           // This line is for if the player is hated by the NPC's home town (hates player because TOWN_REPUTATION<=-15)
      BOption(g_mstr(350), Node998, 4);                          // This line is Normal Int response to being hated by the NPC's home town  (default points to combat Node998)
      NLowOption(g_mstr(350), Node998);                          // This line is Low Int response to being hated by town                    (default points to Combat Node998)

   end else begin
   Reply(230);                                           // This line is for when the character agrees to Join the player's party
      NOption(231, Join_Party, 4);                       // This NOption message(855) is Normal Int player response to joining party
      NLowOption(232, Join_Party);                       // This NLowOption message(860) is Low Int player response to joining party
   end
end

end

procedure Node003 begin
   Reply(290);
   NOption(g_mstr(209),Node999,4);
   NOption(g_mstr(301),Node999,-3);
end

procedure Node998 begin
   /* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
       this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
       he was once hostile towards the player.*/
//   set_local_var(LVAR_Hostile,2);
   set_hostile;

end


procedure Node999 begin
   //debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
   if (local_var(LVAR_Herebefore)==0) then
   begin
   set_local_var(LVAR_Herebefore,1);
   end
end



procedure Join_Party begin
   /* This node places the NPC in the player's party.
      Call this node any time you want an action from the player to result in the NPC joining their party. */

   Hanged_Man_joins_party;
   set_local_var(LVAR_Joined_Player,1);
   floater_bad(155);

end

procedure Abandon_Party begin

   //set_local_var(LVAR_never_again,1);
   //party_remove(self_obj);
   //leave party
   if (self_visible) then
   set_self_abandon_party;

end


   /* Node1000 and on are default dialogue nodes for a generic NPC joining the player's party. */

procedure Node1000 begin
   Reply(155);                                        // This reply is when the NPC is in your party and you talk to them
   NOption(261,Node003,4);
   NOption(262,Node003,-3);
   party_member_default_options;
end
procedure Node1001 begin
   // heal yourself
   obj_heal(self_obj)
   if (party_healed_max) then begin
      Reply(9900);                         // This reply is when your party member is healed to max
   end else if (party_healed_good) then begin
     Reply(9910);                                      // This reply message is for when the NPC is Barely Hurt (90% health or above)
   end else if (party_healed_hurt) then begin
      Reply(9915);                                     // This reply message is for when the NPC is Wounded (70%-90% health?)
   end else begin
      Reply(9920);                                     // This reply message is for Failures
   end
   party_member_default_options;
end
procedure Node1002 begin
   // wait here
   set_party_waiting;
   Reply(9930);                            // These reply messages are in response to wait request
   party_member_default_options;
end
procedure Node1003 begin
   // put your weapon away
   inven_unwield(self_obj);
   Reply(9940);                                        // Response to removing weapon
   party_member_default_options;
end
procedure Node1004 begin
   // follow close
   set_follow_close;
   Reply(9950);                            // Random responses for distance change
   party_member_default_options;
end
procedure Node1005 begin
   // follow medium
   set_follow_medium;
   Reply(9960);                            // Random responses for distance change
   party_member_default_options;
end
procedure Node1006 begin
   // follow far
   set_follow_far;
   Reply(9970);                            // Random responses for distance change
   party_member_default_options;
end
procedure Node1007 begin
   // distance
   //Reply("TEMP MESSAGE: DISTANCE");
   Reply(9980);                                        // Generic response to "Change follow distance" menu
   party_member_def_follow_options;
end
procedure Node1008 begin
   // gear
   //Reply("TEMP MESSAGE: GEAR");
   Reply(9985);                                        // Generic response to "Look at your gear"
   party_member_def_gear_options;
end
procedure Node1009 begin
   // remove armor
   //NEED TO FIND OUT WHY THIS DOESNT WORK!!! - NBK
   remove_armor(self_obj)
   //Reply("TEMP MESSAGE: REMOVE ARMOR");
   Reply(9990);                                        // Generic response to "Remove armor"
   party_member_default_options;
end
procedure Node1010 begin
   // weapons that can be used
   //Reply("TEMP MESSAGE: CAN USE...");
   Reply(9995);                                        // Specific reply, indicating what weapons the NPC can use.
   party_member_default_options;
end
procedure Node1100 begin                              // This node is for when the player is asking the NPC to re-join
   // join me
   if (dude_charisma <= 1) then begin
      set_self_abandon_party;
      Reply(152);                                     // NPC abandons party because Player Character is too ugly
      NOption(g_mstr(10007),Node999,001);             // Predefined generic messages in GENERIC.MSG
   end else if (dude_at_max_party_size) then begin
      set_self_abandon_party;
      Reply(153); //was 2000                          // Generic "Too many followers" reply
      NOption(g_mstr(10007),Node999,001);             // Predefined generic messages in GENERIC.MSG
   end else if (town_rep_is_hated) then begin
      set_self_abandon_party;
      Reply(154);                                     // Will abandon party if Town_Rep becomes Hated
      NOption(g_mstr(10007),Node999,001);             // Predefined generic messages in GENERIC.MSG
   end else begin
      end_party_waiting;
      Reply(9750);                         // Random dialogue greetings
      party_member_default_options;
   end
end
