
#
# Messages for Maps
#



#
# Map Names for (Automap) Descriptions
#	Note: This order must *NOT* change!
#
#	Note: The maximum description width is approximately:
#	  "Brotherhood of Steel (Lower Levels)" -- about 34 characters,
#	  but it's proportional, so you need to double-check it by
#	  going into mapper/game and going to the automap for that map.
#
#	Note: Descriptions *MUST* *NOT* be empty, and so temporary
#	  descriptions are just the map name itself (this also helps
#	  pinpoint unfinished ones when you go through here).
#
{100}{}{Desert}                           // DESERT1.MAP
{101}{}{Desert}                           // DESERT2.MAP
{102}{}{Desert}                           // DESERT3.MAP
{103}{}{Arroyo}                           // arcaves.MAP
{104}{}{Arroyo}                           // arvillag.MAP
{105}{}{Arroyo}                           // arbridge.MAP
{106}{}{Den}                              // denbus1.MAP
{107}{}{Den}                              // denbus2.MAP
{108}{}{Den}                              // denres1.MAP
{109}{}{Klamath}                          // .MAP  ;Downtown
{110}{}{Klamath}                          // .MAP  ;Mall
{111}{}{Klamath}                          // .MAP  ;Rat Caves
{112}{}{Klamath}                          // .MAP  ;Toxic Caves
{113}{}{Klamath}                          // .MAP  ;Trapping Caves
{114}{}{Klamath}                          // .MAP  ;Grazing Area
{115}{}{Vault City}                       // vctyctyd.MAP
{116}{}{Vault City}                       // vctydwtn.MAP
{117}{}{Vault City}                       // vctycocl.MAP
{118}{}{error:Map Name}                        // .MAP
{119}{}{City Ruins}                            // CITY1.MAP
{120}{}{Coast}                                 // COAST1.MAP
{121}{}{Coast}                                 // COAST2.MAP
{122}{}{Desert}                                // COLATRUK.MAP
{123}{}{Desert}                                // FSAUSER.MAP
{124}{}{error:Map Name}                              // RAIDERS.MAP
{125}{}{error:Map Name}                          // SHADYE.MAP
{126}{}{error:Map Name}                          // SHADYW.MAP
{127}{}{error:Map Name}                                 // GLOWENT.MAP
{128}{}{error:Map Name}                             // LAADYTUM.MAP
{129}{}{error:Map Name}                             // LAFOLLWR.MAP
{130}{}{error:Map Name}                        // MBENT.MAP
{131}{}{error:Map Name}                        // MBSTRG12.MAP
{132}{}{error:Map Name}                        // MBVATS12.MAP
{133}{}{error:Map Name}                        // MSTRLR12.MAP
{134}{}{error:Map Name}                        // MSTRLR34.MAP
{135}{}{error:Map Name}                             // V13ENT.MAP
{136}{}{error:Map Name}                                  // HUBENT.MAP
{137}{}{Hub}                                  // DETHCLAW.MAP
{138}{}{Hub}                                  // HUBDWNTN.MAP
{139}{}{Hub}                                  // HUBHEIGT.MAP
{140}{}{Hub}                                  // HUBOLDTN.MAP
{141}{}{Hub}                                  // HUBWATER.MAP
{142}{}{Glow}                                 // GLOW1.MAP
{143}{}{Glow}                                 // GLOW2.MAP
{144}{}{Boneyard}                             // LABLADES.MAP
{145}{}{Boneyard}                             // LARIPPER.MAP
{146}{}{Boneyard}                             // LAGUNRUN.MAP
{147}{}{Cathedral}                            // CHILDEAD.MAP
{148}{}{Military}                             // MBDEAD.MAP
{149}{}{Mountains}                            // MOUNTN1.MAP
{150}{}{Mountains}                            // MOUNTN2.MAP
{151}{}{Desert}                               // FOOT.MAP
{152}{}{Desert}                               // TARDIS.MAP
{153}{}{Desert}                               // TALKCOW.MAP
{154}{}{Desert}                               // USEDCAR.MAP
{155}{}{Brotherhood}                          // BRODEAD.MAP
{156}{}{Desert}                               // DESCRVN1.MAP
{157}{}{Desert}                               // DESCRVN2.MAP
{158}{}{Mountains}                            // MNTCRVN1.MAP
{159}{}{Mountains}                            // MNTCRVN2.MAP
{160}{}{Viper Camp}
{161}{}{Desert}
{162}{}{Mountains}
{163}{}{Desert}
{164}{}{Mountains}


#
# City elevation names -- AUTOMAP Names!
#
# Format: 3 (max elevations), by city
# Formula: (MAPS.TXT ID x 3) + 200
#
# 00: Desert, DESERT1.MAP
{200}{}{Desert}
{201}{}{}
{202}{}{}
# 01: Desert, DESERT2.MAP
{203}{}{Desert}
{204}{}{}
{205}{}{}
# 02: Desert, DESERT3.MAP
{206}{}{Desert}
{207}{}{}
{208}{}{}
# 03: Tibbets Cell Block 13, tbcb13.MAP
{209}{}{Cell Block 13}
{210}{}{}
{211}{}{}
# 04: Arroyo Village, .MAP
{212}{}{City}
{213}{}{}
{214}{}{}
# 05: Arroyo Bridge, .MAP
{215}{}{City}
{216}{}{}
{217}{}{}
# 06: Den, denbus1.MAP
{218}{}{Cell Block 14}
{219}{}{}
{220}{}{}
# 07: Den, denbus2.MAP
{221}{}{Cell Block 15}
{222}{}{}
{223}{}{}
# 08: Den, denres1.MAP
{224}{}{Cell Block 16}
{225}{}{}
{226}{}{}
# 09: , .MAP ;Klamath Downtown
{227}{}{Cell Block 17}
{228}{}{}
{229}{}{}
# 10: , .MAP ;Klamath Mall
{230}{}{Cell Block 18}
{231}{}{}
{232}{}{}
# 11: , .MAP ;Klamath Rat Caves
{233}{}{Security Hub}
{234}{}{}
{235}{}{}
# 12: , .MAP ;Klamath Toxic Caves
{236}{}{Service Level West}
{237}{}{}
{238}{}{}
# 13: , .MAP ;Klamath Trapping Caves
{239}{}{Service Level East}
{240}{}{}
{241}{}{}
# 14: , .MAP ;Klamath Grazing Area
{242}{}{Courtroom}
{243}{}{}
{244}{}{}
# 15: , .MAP ; Vault City Courtyard
{245}{}{Breach}
{246}{}{}
{247}{}{}
# 16: , .MAP ; Vault City Downtown
{248}{}{Breach}
{249}{}{}
{250}{}{}
# 17: , .MAP ; Vault City Council
{251}{}{Cell Block 19}
{252}{}{}
{253}{}{}
# 18: , .MAP ; Modoc Main Street
{254}{}{Cell Block 20}
{255}{}{}
{256}{}{}
# 19: , .MAP ; Modoc Bed & Breakfast
{257}{}{Cell Block 21}
{258}{}{}
{259}{}{}
# 20: , .MAP ; Modoc Brahmin Pastures
{260}{}{Cell Block 22}
{261}{}{}
{262}{}{}
# 21: , .MAP ; Modoc Farrel's Garden
{263}{}{Cell Block 23}
{264}{}{}
{265}{}{}
# 22: , .MAP ; Modoc Down the Shitter
{266}{}{Cell Block 24}
{267}{}{}
{268}{}{}
# 23: , .MAP ; Modoc Town Hall
{269}{}{Cell Block 25}
{270}{}{}
{271}{}{}
# 24: , .MAP ; Modoc Ghost Town: The Ghost Farm
{272}{}{Cell Block 26}
{273}{}{}
{274}{}{}
# 25: , .MAP ; Modoc Ghost Town: Main Cavern
{275}{}{Cell Block 27}
{276}{}{}
{277}{}{}
# 26: , .MAP ; Modoc Ghost Town: Underground Lake
{278}{}{Cell Block 28}
{279}{}{}
{280}{}{}
# 27: , .MAP ; Sierra Army Depot: The Battlefield
{281}{}{Cell Block 29}
{282}{}{}
{283}{}{}
# 28: , .MAP ; Sierra Army Depot: Levels 1-3
{284}{}{Cell Block 30}
{285}{}{}
{286}{}{}
# 29: , .MAP ; Sierra Army Depot: Level 4
{287}{}{Car Mart}
{288}{}{}
{289}{}{}
# 30: Vault City Vault, .MAP
{290}{}{Mountain}
{291}{}{Cavern}
{292}{}{}
# 31: Gecko Settlement
{293}{}{Bombed-Out City}
{294}{}{}
{295}{}{}
# 32: Gecko Power Plant, .MAP
{296}{}{Entrance}
{297}{}{Living Quarters}
{298}{}{Command Center}
# 33: Gecko Junkyard, .MAP
{299}{}{Medical Treatment Area}
{300}{}{}
{301}{}{}
# 34: Gecko Access Tunnels, .MAP
{302}{}{Asylum}
{303}{}{}
{304}{}{}
# 35: Arroyo Wilderness, .MAP
{305}{}{Underground Car Park}
{306}{}{}
{307}{}{}
# 36: Vault 15, .MAP
{308}{}{Mountain Entrance}
{309}{}{}
{310}{}{}
# 37: Vault 15, .MAP
{311}{}{Cavern}
{312}{}{Level 1}
{313}{}{Level 2}
# 38: Vault 15, .MAP
{314}{}{Labs}
{315}{}{}
{316}{}{}
# 39: Vault 15, .MAP
{317}{}{Genetic Sampling}
{318}{}{}
{319}{}{}
# 40: Vault 13, .MAP
{320}{}{Tram Station Mountain Entrance}
{321}{}{}
{322}{}{}
# 41: Vault 13, .MAP
{323}{}{Tibbets Tram Station}
{324}{}{}
{325}{}{}
# 42: NCR, .MAP
{326}{}{Asylum Tram Station}
{327}{}{}
{328}{}{}
# 43: NCR, .MAP
{329}{}{City Ruins}
{330}{}{}
{331}{}{}
# 44: NCR, .MAP
{332}{}{Morgue}
{333}{}{}
{334}{}{}
# 45: NCR, .MAP
{335}{}{Thunderbird's Nest}
{336}{}{}
{337}{}{}
# 46: NCR, .MAP
{338}{}{Desert}
{339}{}{}
{340}{}{}
# 47: NCR, .MAP
{341}{}{Desert}
{342}{}{}
{343}{}{}
# 48: Klamath, klacanyn.MAP
{344}{}{Pet Cemetery}
{345}{}{}
{346}{}{}
# 49: Military Base, mbase12.MAP
{347}{}{Coast}
{348}{}{}
{349}{}{}
# 50: Military Base, mbase34.MAP
{350}{}{Mountain}
{351}{}{}
{352}{}{}
# 51: Military Base, mbclose.MAP
{353}{}{Temple}
{354}{}{}
{355}{}{}
# 52: Den Slave Run dnslvrun.MAP
{356}{}{Desert}
{357}{}{Village}
{358}{}{Camp Site}
# 53: Car Desert out-of-gas, CarDesrt.MAP
{359}{}{Desert}
{360}{}{}
{361}{}{}
# 54: New Reno 1 newr1.MAP
{362}{}{Mountain}
{363}{}{}
{364}{}{}
# 55: New Reno 2 newr2.MAP
{365}{}{Parking Lot}
{366}{}{}
{367}{}{}
# 56: New Reno 3 newr3.MAP
{368}{}{Cliff}
{369}{}{}
{370}{}{}
# 57: New Reno 4 newr4.MAP
{371}{}{Maxson Bunker Entrance}
{372}{}{}
{373}{}{}
# 58: New Reno Chop Shop newrcs.MAP
{374}{}{Maxson Bunker Level 1}
{375}{}{Maxson Bunker Level 2}
{376}{}{Maxson Bunker Level 3}
# 59: New Reno GO newrgo.MAP
{377}{}{Maxson Bunker Level 4}
{378}{}{}
{379}{}{}
# 60: New Reno ST newrst.MAP
{380}{}{Hideout}
{381}{}{}
{382}{}{}
# 61: New Reno Boxing Arena newrba.MAP
{383}{}{Maxson Bunker Ruins}
{384}{}{}
{385}{}{}
# 62: Redding Wanamingo Mine Entrance  RedWame.Map
{386}{}{Courtyard}
{387}{}{}
{388}{}{}
# 63: Great Wanamingo Mine, Level 1 and 2  RedWan1.MAP
{389}{}{Abandoned Oil Refinery}
{390}{}{}
{391}{}{}
# 64: Redding Downtown  RedDown.MAP
{392}{}{Farm}
{393}{}{Cavern}
{394}{}{}
# 65: Redding Mine Entrance   RedMEnt.MAP
{395}{}{Parking Lot}
{396}{}{Ventilation Tunnels}
{397}{}{}
# 66: Redding Downtown Tunnels  RedDTun.MAP
{398}{}{Oil Refinery}
{399}{}{}
{400}{}{}
# 67: Redding Mine Entrance Tunnels
{401}{}{Front Gate}
{402}{}{}
{403}{}{}
# 68: Random Encounter City 1
{404}{}{City}
{405}{}{City}
{406}{}{City}
# 69: Random Encounter Cavern 0
{407}{}{Mountain}
{408}{}{Mountain}
{409}{}{Mountain}
# 70: Random Encounter Cavern 1
{410}{}{Caverns}
{411}{}{Cavern}
{412}{}{Cavern}
# 71: Random Encounter Cavern 2
{413}{}{Cavern}
{414}{}{Cavern}
{415}{}{Cavern}
# 72: Random Encounter Cavern 3
{416}{}{Cavern}
{417}{}{Cavern}
{418}{}{Cavern}
# 73: Random Encounter Cavern 4
{419}{}{Cavern}
{420}{}{Cavern}
{421}{}{Cavern}
# 74: Random Encounter Mountain 1
{422}{}{Mountain}
{423}{}{Mountain}
{424}{}{Mountain}
# 75: Random Encounter Mountain 2
{425}{}{Mountain}
{426}{}{Mountain}
{427}{}{Mountain}
# 76: Random Encounter Coast 1
{428}{}{Coast}
{429}{}{Coast}
{430}{}{Coast}
# 77: Random Encounter Coast 2
{431}{}{Coast}
{432}{}{Coast}
{433}{}{Coast}
# 78: Broken Hills 1  broken1.map
{434}{}{Trading Post}
{435}{}{}
{436}{}{}
# 79: Broken Hills 2 broken2.map
{437}{}{Desert}
{438}{}{}
{439}{}{}
# 80: Random Encounter Cavern 5
{440}{}{Cavern}
{441}{}{Cavern}
{442}{}{Cavern}
# 81: Random Encounter Desert 4
{443}{}{Desert}
{444}{}{Desert}
{445}{}{Desert}
# 82. Random Encounter Desert 5
{446}{}{Desert}
{447}{}{Desert}
{448}{}{Desert}
# 83. Random Encounter Desert 6
{449}{}{Desert}
{450}{}{Desert}
{451}{}{Desert}
# 84. Random Encounter Desert 7
{452}{}{Desert}
{453}{}{Desert}
{454}{}{Desert}
# 85. Random Encounter Coast 3
{455}{}{Coast}
{456}{}{Coast}
{457}{}{Coast}
# 86. Random Encounter Coast 4
{458}{}{Coast}
{459}{}{Coast}
{460}{}{Coast}
# 87. Random Encounter Coast 5
{461}{}{Coast}
{462}{}{Coast}
{463}{}{Coast}
# 88. Random Encounter Coast 6
{464}{}{Coast}
{465}{}{Coast}
{466}{}{Coast}
# 89. Random Encounter Coast 7
{467}{}{Coast}
{468}{}{Coast}
{469}{}{Coast}
# 90. Random Encounter Coast 8
{470}{}{Coast}
{471}{}{Coast}
{472}{}{Coast}
# 91. Random Encounter Coast 9
{473}{}{Coast}
{474}{}{Coast}
{475}{}{Coast}
# 92. Raiders Camp 1
{476}{}{Raider Camp}
{477}{}{Raider Camp}
{478}{}{Raider Camp}
# 93. Raider Camp 2
{479}{}{South Gate}
{480}{}{NCR HQ}
{481}{}{Lookout}
# 94. Broken Hills Random Encounter Desert
{482}{}{Desert}
{483}{}{Desert}
{484}{}{Desert}
# 95. Broken Hills Random Encounter Mountain
{485}{}{Mountain}
{486}{}{Mountain}
{487}{}{Mountain}
# 96. Special Encounter: Whale
{488}{}{Desert}
{489}{}{Desert}
{490}{}{Desert}
# 97. Special Encounter: Tin Woodsman
{491}{}{Desert}
{492}{}{Desert}
{493}{}{Desert}
# 98. Special Encounter: Talking Head
{494}{}{Canyon}
{495}{}{Canyon}
{496}{}{Cavern}
# 99. Special Encounter: Federation Shuttle
{497}{}{Desert}
{498}{}{Desert}
{499}{}{Desert}
# 100. Special Encounter: Unwashed Villagers
{500}{}{Desert}
{501}{}{Desert}
{502}{}{Desert}
# 101. Special Encounter: Bridge
{503}{}{Bridge of Death}
{504}{}{Bridge of Death}
{505}{}{Bridge of Death}
# 102. Special Encounter: Cafe of Broken Dreams
{506}{}{Cafe of Broken Dreams}
{507}{}{Cafe of Broken Dreams}
{508}{}{Cafe of Broken Dreams}
# 103. Special Encounter: Holy Hand Grenade 1
{509}{}{Desert}
{510}{}{Desert}
{511}{}{Desert}
# 104. Special Encounter: Holy Hand Grenade 2
{512}{}{Mountain}
{513}{}{Cavern}
{514}{}{Cavern}
# 105. Special Encounter: Guardian of Forever
{515}{}{Guardian}
{516}{}{Vault 13}
{517}{}{Vault 13}
# 106. Special Encounter: Toxic Waste Dump
{518}{}{Ruin}
{519}{}{}
{520}{}{}
# 107. Special Encounter: Pahiahs
{521}{}{Desert}
{522}{}{Desert}
{523}{}{Desert}
# 108. Special Encounter: Mad Brahmin
{524}{}{Desert}
{525}{}{Desert}
{526}{}{Desert}
# 109. Navarro Entrance
{527}{}{Gas Station}
{528}{}{Underground}
{529}{}{Vertibird Base}
# 110. Coast Encounter 10
{530}{}{Coastline}
{531}{}{Coastline}
{532}{}{Coastline}
# 111. Coast Encounter 11
{533}{}{Coastline}
{534}{}{Coastline}
{535}{}{Coastline}
# 112. Coast Encounter 12
{536}{}{Coastline}
{537}{}{Coastline}
{538}{}{Coastline}
# 113. Desert Encounter 8
{539}{}{Desert}
{540}{}{Desert}
{541}{}{Desert}
# 114. Desert Encounter 9
{542}{}{Desert}
{543}{}{Desert}
{544}{}{Desert}
# 115. Desert Encounter 10
{545}{}{Desert}
{546}{}{Desert}
{547}{}{Desert}
# 116. Desert Encounter 11
{548}{}{Desert}
{549}{}{Desert}
{550}{}{Desert}
# 117. Desert Encounter 12
{551}{}{Desert}
{552}{}{Desert}
{553}{}{Desert}
# 118. Cavern Encounter 5
{554}{}{Cavern}
{555}{}{Cavern}
{556}{}{Cavern}
# 119. Cavern Encounter 6
{557}{}{Cavern}
{558}{}{Cavern}
{559}{}{Cavern}
# 120. Cavern Encounter 7
{560}{}{Entrance}
{561}{}{Tunnel}
{562}{}{Parking Lot}
# 121. Mountain Encounter 3
{563}{}{Mountain}
{564}{}{Mountain}
{565}{}{Mountain}
# 122. Mountain Encounter 4
{566}{}{Mountain}
{567}{}{Mountain}
{568}{}{Mountain}
# 123. Mountain Encounter 5
{569}{}{Mountain}
{570}{}{Mountain}
{571}{}{Mountain}
# 124. Mountain Encounter 6
{572}{}{Mountain}
{573}{}{Mountain}
{574}{}{Mountain}
# 125. City Encounter
{575}{}{Abandoned City}
{576}{}{Ruined City}
{577}{}{Ruined City}
# 126. Arroyo Temple
{578}{}{Temple Entrance}
{579}{}{Temple Entrance}
{580}{}{Temple Entrance}
# 127. Destroyed Arroyo
{581}{}{Destroyed Bridge}
{582}{}{Destroyed Bridge}
{583}{}{Destroyed Bridge}
# [Map 128] lookup_name=BOMB-001
{584}{}{Living Quarters}
{585}{}{Space Walk}
{586}{}{Command Center}
# [Map 129] lookup_name=Enclave Dock
{587}{}{Dock}
{588}{}{Dock}
{589}{}{Dock}
# [Map 130] lookup_name=Enclave End Fight
{590}{}{Desert}
{591}{}{}
{592}{}{}
# [Map 131] lookup_name=Enclave Guard Barracks
{593}{}{Desert}
{594}{}{}
{595}{}{}
# [Map 132] lookup_name=Enclave Presidential
{596}{}{Presidential Area}
{597}{}{Presidential Area}
{598}{}{Presidential Area}
# [Map 133]
{599}{}{Desert}
{600}{}{}
{601}{}{}
# [Map 134] lookup_name=Enclave Trap Room
{602}{}{Access Corridor}
{603}{}{Access Corridor}
{604}{}{Access Corridor}
# [Map 135] lookup_name=San Fran Tanker
{605}{}{Oil Tanker}
{606}{}{Oil Tanker}
{607}{}{Oil Tanker}
# [Map 136] lookup_name=San Fran Dock
{608}{}{Tunnel}
{609}{}{}
{610}{}{}
# [Map 137] lookup_name=San Fran China
{611}{}{Chinatown}
{612}{}{Chinatown}
{613}{}{Chinatown}
# 138. Shuttle Exterior
{614}{}{Shuttle Dock}
{615}{}{Shuttle Dock}
{616}{}{Shuttle Dock}
# 139. Shuttle Interior
{617}{}{Shuttle Interior}
{618}{}{Shuttle Interior}
{619}{}{Shuttle Interior}
# 140. Hubologist Base
{620}{}{Hubologist Base}
{621}{}{Hubologist Base}
{622}{}{Hubologist Base}
# 141. City Encounter 3
{623}{}{Destroyed City}
{624}{}{Destroyed City}
{625}{}{Destroyed City}
# 142. City Encounter 4
{626}{}{Destroyed City}
{627}{}{Destroyed City}
{628}{}{Destroyed City}
# 143. City Encounter 5
{629}{}{Destroyed City}
{630}{}{Destroyed City}
{631}{}{Destroyed City}
# 144. City Encounter 6
{632}{}{Destroyed City}
{633}{}{Destroyed City}
{634}{}{Destroyed City}
# 145. City Encounter 7
{635}{}{Destroyed City}
{636}{}{Destroyed City}
{637}{}{Destroyed City}
# 146. City Encounter 8
{638}{}{Destroyed City}
{639}{}{Destroyed City}
{640}{}{Destroyed City}
# 147. New Reno VB  newrvb.MAP
{641}{}{Vertibird Area}
{642}{}{Vertibird Area}
{643}{}{Vertibird Area}
# 148. Shi Temple
{644}{}{The Rim}
{645}{}{}
{646}{}{}
# 149. In Game Movie
{647}{}{Desert}
{648}{}{Desert}
{649}{}{Desert}
# 150. RndBess
{650}{}{Desert}
{651}{}{Desert}
{652}{}{Desert}
# 151.
{653}{}{Desert}
{654}{}{Desert}
{655}{}{Desert}
# 152.
{656}{}{Desert}
{657}{}{Desert}
{658}{}{Desert}
# 153.
{659}{}{Canyon}
{660}{}{}
{661}{}{}
# 154.
{662}{}{Desert}
{663}{}{Desert}
{664}{}{Desert}
# 155.
{665}{}{Desert}
{666}{}{Desert}
{667}{}{Desert}

# 163.
{689}{}{Hounds of Hecate Camp}
{690}{}{}
{691}{}{}

# 164.
{692}{}{Canyon}
{693}{}{Canyon}
{694}{}{Canyon}

# 165.
{695}{}{Village East}
{696}{}{Kiva}
{697}{}{}

# 166.
{698}{}{Village Bridge}
{699}{}{}
{700}{}{}

# 167.
{701}{}{Village West}
{702}{}{}
{703}{}{}

# 168.
{704}{}{Village North}
{705}{}{Storage Cavern}
{706}{}{}

# 169.
{707}{}{Overgrown Bridge}
{708}{}{}
{709}{}{}

# 170.
{710}{}{Mesa Top}
{711}{}{}
{712}{}{}

# 171.
{713}{}{NCR Army Barracks}
{714}{}{}
{715}{}{}

# 173.
{719}{}{Canyon}
{720}{}{Canyon}
{721}{}{Canyon}

# 174.
{722}{}{Canyon}
{723}{}{Cavern}
{724}{}{}

# 206.
{818}{}{Ghost Town}
{819}{}{}
{820}{}{}

# 223.
{869}{}{Waste Disposal}
{870}{}{}
{871}{}{}

# 227.
{881}{}{Chemical Treatment Area}
{882}{}{}
{883}{}{}

# 228.
{884}{}{Mechanics Bay}
{885}{}{Arsenal}
{886}{}{Robot Maintenance Bay}

# 229.
{887}{}{Service and Vehicle Depot Areas West}
{888}{}{}
{889}{}{}

# 230.
{890}{}{Service and Vehicle Depot Areas Center}
{891}{}{}
{892}{}{}

# 231.
{893}{}{Service and Vehicle Depot Areas East}
{894}{}{}
{895}{}{}

# 232.
{896}{}{Service and Vehicle Depot Areas Cafe}
{897}{}{}
{898}{}{}

# 233.
{899}{}{}
{900}{}{}
{901}{}{}

# 234.
{902}{}{Defense Tunnels}
{903}{}{Cryogenic Cell Blocks}
{904}{}{}

# 235.
{905}{}{ODYSSEUS Computer Core}
{906}{}{}
{907}{}{}

# 236.
{908}{}{Train Station}
{909}{}{}
{910}{}{}

# 260.
{980}{}{Crater}
{981}{}{}
{982}{}{}

# 261.
{983}{}{Baseline}
{984}{}{}
{985}{}{}

# 262.
{986}{}{Scum Pits}
{987}{}{Scum Pits}
{988}{}{}

# 263.
{989}{}{Downtown Businesses}
{990}{}{}
{991}{}{}

# 264.
{992}{}{Downtown Residential}
{993}{}{}
{994}{}{}

# 265.
{995}{}{Downtown Engineering}
{996}{}{Elevator}
{997}{}{}

# 266.
{998}{}{Farming Crops}
{999}{}{}
{1000}{}{}

# 267.
{1001}{}{Farm}
{1002}{}{}
{1003}{}{}

# 270.
{1010}{}{Control Center South}
{1011}{}{}
{1012}{}{}

# 271.
{1013}{}{Control Center}
{1014}{}{}
{1015}{}{}

# 272.
{1016}{}{Runway}
{1017}{}{}
{1018}{}{}

# 273.
{1019}{}{}
{1020}{}{}
{1021}{}{}

# 274.
{1022}{}{Gas Station}
{1023}{}{}
{1024}{}{}

# 275.
{1025}{}{Launch Platform}
{1026}{}{Turret Control Computer Room}
{1027}{}{Recharging Bays}

# 276.
{1028}{}{}
{1029}{}{}
{1030}{}{}

# 277.
{1031}{}{Sub-Reactor Waste Disposal}
{1032}{}{Sub-Reactor}
{1033}{}{}

# 310.
{1130}{}{Crater}
{1131}{}{}
{1132}{}{}

# 311.
{1133}{}{}
{1134}{}{}
{1135}{}{}

# 312.
{1136}{}{}
{1137}{}{}
{1138}{}{}

# 313.
{1139}{}{}
{1140}{}{}
{1141}{}{}

# 314.
{1142}{}{Caverns}
{1143}{}{}
{1144}{}{}

# 315.
{1145}{}{}
{1146}{}{}
{1147}{}{}

# 316.
{1148}{}{Operations and Communications Building}
{1149}{}{Operations and Communications Building}
{1150}{}{}

# 317.
{1151}{}{}
{1152}{}{}
{1153}{}{}

# 318.
{1154}{}{Crater}
{1155}{}{}
{1156}{}{}

# 319.
{1157}{}{Crater}
{1158}{}{}
{1159}{}{}

# 320.
{1160}{}{New York Docks}
{1161}{}{}
{1162}{}{}

# 321.
{1163}{}{Scrapheap}
{1164}{}{}
{1165}{}{}

# 322.
{1166}{}{}
{1167}{}{}
{1168}{}{}

# 323.
{1169}{}{}
{1170}{}{}
{1171}{}{}

# 324.
{1172}{}{Fort Desolation}
{1173}{}{}
{1174}{}{}

# 331.
{1193}{}{Catwalk}
{1194}{}{}
{1195}{}{}

# 332.
{1196}{}{S1C}
{1197}{}{}
{1198}{}{}

# 333.
{1199}{}{NCR Army Gym}
{1200}{}{}
{1201}{}{}

# 351.
{1253}{}{North Gate}
{1254}{}{}
{1255}{}{}

# 352.
{1256}{}{Gas Station}
{1254}{}{}
{1255}{}{}

#
#	Short City names
#
{1500}{}{Tibbets}
{1501}{}{Boulder Dome}
{1502}{}{Dogtown}
{1503}{}{Circle Junction}
{1504}{}{Fort Abandon}
{1505}{}{Blackfoot}
{1506}{}{Mesa Verde}
{1507}{}{Twin Mothers}
{1508}{}{Brotherhood of Steel}
{1509}{}{Hoover Dam}
{1510}{}{Ouroboros}
{1511}{}{Reservation}
{1512}{}{Burham Springs}
{1513}{}{Nursery}
{1514}{}{Bloomfield Space Center}
{1515}{}{Grand Canyon}
{1516}{}{Jericho}
{1517}{}{New Canaan}
{1518}{}{Hangdogs}
{1519}{}{Bloomfield Space Center}
{1520}{}{Bike}
{1521}{}{Ride Outta Power}
{1522}{}{Crater}
{1523}{}{Dune Buggy}
{1524}{}{Slave Run}
{1525}{}{Moletown}
{1526}{}{Desert}
{1527}{}{Mountain}
{1528}{}{Ruined City}
{1529}{}{Coast}
{1530}{}{B.O.M.B.-001}
{1531}{}{Cop Car}
{1532}{}{Bicycle}
{1533}{}{Grove}
{1534}{}{Pulowskis}
{1535}{}{Drowned Temple}
{1536}{}{Blackfoot}
{1537}{}{Lone Street Lamp}
{1538}{}{Car Mart}
{1539}{}{Fort Desolation}
{1540}{}{Guardian of Forever}
{1541}{}{Den of Lost Luck}
{1542}{}{Hoover Dam}
{1543}{}{Escape Pod Landing Site}
{1544}{}{Truck}
{1545}{}{Parking Lot}
{1546}{}{Radspider Nest}
{1547}{}{Random Encounter}
{1548}{}{VACCS 8}
{1549}{}{Car}
{1550}{}{Postman}
{1551}{}{Pet Cemetery}
{1552}{}{Circle of Steel}
{1553}{}{Scaven-Picker Camp}
{1554}{}{Nether Realm}
{1555}{}{Gas Station}
{1556}{}{Tibbets}
{1557}{}{Hoover Dam}
{1558}{}{Dogtown}
{1559}{}{Circle Junction}
{1560}{}{Fort Abandon}
{1561}{}{Mesa Verde}
{1562}{}{Twin Mothers}
{1563}{}{Brotherhood of Steel}
{1564}{}{Ouroboros}
{1565}{}{Reservation}
{1566}{}{Burham Springs}
{1567}{}{Nursery}
{1568}{}{Jericho}
{1569}{}{New Canaan}
{1570}{}{Boulder Dome}
{1571}{}{Vault 69}
{1572}{}{Camp Site}
{1573}{}{Thunderbird's Nest}
{1574}{}{Mesa Verde}
