{100}{}{Burning Metal Barrel}
{101}{}{The barrel contains burning paper and other flaming refuse.}
{200}{}{Wooden Door}
{201}{}{A door, made from wood.}
{300}{}{Wooden Table}
{301}{}{A table, made from wood.}
{400}{}{Wooden Table}
{401}{}{A table, made from wood.}
{500}{}{Metal Barrel}
{501}{}{An old barrel, made from steel.}
{600}{}{Metal Barrel}
{601}{}{An old barrel, made from steel.}
{700}{}{Stack of Tires}
{701}{}{A stack of ancient rubber tires. They have vulcanized and hardened, probably due to the heat.}
{800}{}{Security Door}
{801}{}{This door looks very secure. It provides protection from the outside world elements and dangerous creatures.}
{900}{}{Computer}
{901}{}{A computer terminal, hooked into a mainframe computer.}
{1000}{}{Column}
{1001}{}{A support column, providing stress relief for the entire complex.}
{1100}{}{Computer}
{1101}{}{A computer terminal, hooked into a mainframe computer.}
{1200}{}{Computer}
{1201}{}{A computer terminal, hooked into a mainframe computer.}
{1300}{}{Monitor}
{1301}{}{A green-screen display monitor, showing various bits of data. A few bytes occasionally show up.}
{1400}{}{Monitor}
{1401}{}{A green-screen display monitor, showing various bits of data.}
{1500}{}{Holo Generator}
{1501}{}{A large-scale THT entertainment tape player. No new movies have been made in almost 180 years.}
{1600}{}{Screens}
{1601}{}{A series of three display monitors, showing various bits of data.}
{1700}{}{Screens}
{1701}{}{A set of three display monitors, showing various bits of data from around the Vault.}
{1800}{}{Door}
{1801}{}{It's still a door after closer examination.}
{1900}{}{Door}
{1901}{}{It's still a door after closer examination.}
{2000}{}{Vent}
{2001}{}{An air vent, supplying processed and cleaned air to the entire complex.}
{2100}{}{Vent}
{2101}{}{An air vent, supplying processed and cleaned air to the entire complex.}
{2200}{}{Vault 13 Door}
{2201}{}{A heavy door, constructed to survive all sorts of damage and trauma.}
{2300}{}{Vault 13 Door}
{2301}{}{A heavy door, constructed to survive all sorts of damage and trauma.}
{2400}{}{Pedestal}
{2401}{}{A hydraulic lift, designed to help provide support, power and communication lines to the platform.}
{2500}{}{Monitor}
{2501}{}{If you've seen one monitor, you've seen them all.}
{2600}{}{Monitor}
{2601}{}{A computer monitor, displaying various bits of data.}
{2700}{}{Grating}
{2701}{}{A floor grating.}
{2800}{}{Pipes}
{2801}{}{Some pipes. After closer examination, they are still pipes.}
{2900}{}{Vent}
{2901}{}{Standard Vault-Tec ventilation system.}
{3000}{}{Column}
{3001}{}{A standard Vault-Tec column support system.}
{3100}{}{Column}
{3101}{}{A standard Vault-Tec column support system.}
{3200}{}{Vent}
{3201}{}{Standard Vault-Tec ventilation system.}
{3300}{}{Vent}
{3301}{}{Standard Vault-Tec ventilation system.}
{3400}{}{Bed}
{3401}{}{A bed, it looks pretty comfortable after what you have been sleeping on.}
{3500}{}{Bed}
{3501}{}{A standard bed. Looks comfy.}
{3600}{}{Bed}
{3601}{}{A standard bed. Looks comfy.}
{3700}{}{Bed}
{3701}{}{A standard bed. Looks comfy.}
{3800}{}{Elevator}
{3801}{}{This is a maintenance elevator.}
{3900}{}{Chair}
{3901}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{4000}{}{Chair}
{4001}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{4100}{}{Chair}
{4101}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{4200}{}{Chair}
{4201}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{4300}{}{Monitor}
{4301}{}{A computer monitor, displaying various bits of data.}
{4400}{}{Monitor}
{4401}{}{A computer monitor, displaying various bits of data.}
{4500}{}{Monitor}
{4501}{}{A computer monitor, displaying various bits of data.}
{4600}{}{Monitor}
{4601}{}{A computer monitor, displaying various bits of data.}
{4700}{}{Monitor}
{4701}{}{A computer monitor, displaying various bits of data.}
{4800}{}{Monitor}
{4801}{}{A computer monitor, displaying various bits of data.}
{4900}{}{Exit Grid Map Marker}
{4901}{}{Exit Grid Map Marker}
{5000}{}{Air Processing Unit}
{5001}{}{An APU cleans the old air to provide new air for the complex.}
{5100}{}{Chair}
{5101}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{5200}{}{Chair}
{5201}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{5300}{}{Chair}
{5301}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{5400}{}{Chair}
{5401}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{5500}{}{VDU}
{5501}{}{This Video Display Unit has a variety of computer monitors and other screens. It looks very, very busy.}
{5600}{}{VDU}
{5601}{}{This Video Display Unit has a variety of computer monitors and other screens. It looks very, very busy.}
{5700}{}{Chair}
{5701}{}{It's a chair. It looks mighty comfortable.}
{5800}{}{Chair}
{5801}{}{It's a chair. It looks mighty comfortable.}
{5900}{}{Chair}
{5901}{}{It's a chair. It looks mighty comfortable.}
{6000}{}{Chair}
{6001}{}{It's a chair. It looks mighty comfortable.}
{6100}{}{Table}
{6101}{}{It's a table. Before tables, people had to keep their stuff on the floor.}
{6200}{}{Table}
{6201}{}{It's definitely a table.}
{6300}{}{Tumbleweed}
{6301}{}{It's a tumbleweed. Of course, you've never seen a real live tumbleweed before. You'd better keep a close eye on it.}
{6400}{}{Cactus}
{6401}{}{You see nothing special about this cactus.}
{6500}{}{Cactus}
{6501}{}{You see nothing important about this cactus.}
{6600}{}{Tree}
{6601}{}{A dead tree. Nothing grows well here.}
{6700}{}{Secret Blocking Hex}
{6701}{}{If you can see this, blame the technical designer.}
{6800}{}{Stairs}
{6801}{}{A set of stairs.}
{6900}{}{Stalagmite}
{6901}{}{A natural extension of the rock floor.}
{7000}{}{Stalagmite}
{7001}{}{A natural extension of the rock floor.}
{7100}{}{Blood Stain}
{7101}{}{There is nothing out of the ordinary with this bloody stain. Except, of course, that someone or something died here.}
{7200}{}{Rock Column}
{7201}{}{This thick column of rock extends from floor to ceiling.}
{7300}{}{Rock Column}
{7301}{}{This thin column of rock extends from floor to ceiling.}
{7400}{}{Rocks}
{7401}{}{You study the rocks for a while, but they never move.}
{7500}{}{Rocks}
{7501}{}{You keep a close eye on these rocks, in case they move to attack you.}
{7600}{}{Dune Buggy}
{7700}{}{Gate}
{7701}{}{A wooden gate.}
{7800}{}{Rocks}
{7801}{}{A large pile of rocks. They look indigenous to this region.}
{7900}{}{Rocks}
{7901}{}{A small pile of rocks.}
{8000}{}{Rocks}
{8001}{}{A small pile of rocks.}
{8100}{}{Rocks}
{8101}{}{A large pile of rocks.}
{8200}{}{Bones}
{8201}{}{A large pile of bleached animal bones. At least, you think all the bones are animal...}
{8300}{}{Bones}
{8301}{}{A large pile of bleached animal bones. At least, you think all the bones are animal...}
{8400}{}{Bones}
{8401}{}{A very large pile of bleached bones. You cannot determine the species of the dead critters.}
{8500}{}{Bones}
{8501}{}{You think these might be Horned Kangaroo bones, but you cannot be sure. They are too weathered to make a final determination.}
{8600}{}{Bones}
{8601}{}{You see the bones of a large, two-headed cow.}
{8700}{}{Gate}
{8701}{}{A wooden gate. It opens, and closes, and opens, and closes, and...}
{8800}{}{Gate}
{8801}{}{A wooden gate.}
{8900}{}{Gate}
{8901}{}{A wooden gate.}
{9000}{}{Rocks}
{9001}{}{A very large pile of rocks. They look dangerous just sitting there.}
{9100}{}{Rocks}
{9101}{}{A large pile of rocks. If you look closely, you can see the faces of little old men in the sides of the stones.}
{9200}{}{Rocks}
{9201}{}{Rocks, rocks, rocks! Everywhere you look, rocks!}
{9300}{}{Rocks}
{9301}{}{A small pile of rocks.}
{9400}{}{Bar}
{9401}{}{This bar has a collection of brewed beverages ready to pour.}
{9500}{}{Chair}
{9501}{}{A rotting old chair made out of an ancient car seat.}
{9600}{}{Chair}
{9601}{}{A smelly old chair that used be to a car seat. The springs have lost their spring.}
{9700}{}{Chair}
{9701}{}{A rotting, smelly old chair sitting on bricks for support. Looks pretty uncomfortable.}
{9800}{}{Chair}
{9801}{}{A rotting, smelly old chair sitting on bricks for support. Looks pretty uncomfortable.}
{9900}{}{Couch}
{9901}{}{A very uncomfortable looking sitting device, sometimes known as a couch.}
{10000}{}{Couch}
{10001}{}{A very uncomfortable looking sitting device, sometimes known as a couch.}
{10100}{}{Tire}
{10101}{}{An old rubber tire sitting in the middle of some weeds.}
{10200}{}{Scrub}
{10201}{}{Some sort of desert weed.}
{10300}{}{Scrub}
{10301}{}{Some sort of desert weed.}
{10400}{}{Scrub}
{10401}{}{Some sort of desert weed.}
{10500}{}{Scrub}
{10501}{}{Some sort of desert weed.}
{10600}{}{Junk}
{10601}{}{It's a rusted car door leaning on a rusted metal barrel. A whole lot of rust is going on.}
{10700}{}{Junk}
{10701}{}{A broken toilet, half-buried in the sand. Life's a pisser, then you die.}
{10800}{}{Weeds}
{10801}{}{Some sort of desert scrub. If it was growing in the recent past, it isn't now.}
{10900}{}{Junk}
{10901}{}{A car tire, buried in the sand. Some small pieces of wood are piled up around it.}
{11000}{}{Rocks}
{11001}{}{On closer examination, you think these might actually be pieces of petrified wood.}
{11100}{}{Dirt}
{11101}{}{A small pile of dirt, with a dead weed sticking out of it.}
{11200}{}{Dirt}
{11201}{}{A small pile of dirt.}
{11300}{}{Dirt}
{11301}{}{A small pile of dirt.}
{11400}{}{Dirt}
{11401}{}{A small pile of dirt.}
{11500}{}{Weed}
{11501}{}{A small pile of dirt, with a dry weed sticking out of it.}
{11600}{}{Junk}
{11601}{}{A twisted piece of rusted metal.}
{11700}{}{Junk}
{11701}{}{Some broken pieces of wood.}
{11800}{}{Junk}
{11801}{}{A small pile of random junk.}
{11900}{}{Dirt}
{11901}{}{A small pile of dirt.}
{12000}{}{Dirt}
{12001}{}{A small pile of dirt.}
{12100}{}{Dirt}
{12101}{}{A small pile of dirt.}
{12200}{}{Dirt}
{12201}{}{A small pile of dirt.}
{12300}{}{Dirt}
{12301}{}{A small pile of dirt.}
{12400}{}{Dirt}
{12401}{}{A small pile of dirt.}
{12500}{}{Weed}
{12501}{}{A generic desert weed.}
{12600}{}{Weed}
{12601}{}{A generic desert weed.}
{12700}{}{Weed}
{12701}{}{A generic desert weed.}
{12800}{}{Blocking Hex (NoLight)}
{12900}{}{Wall}
{13000}{}{Wall}
{13100}{}{Wall}
{13200}{}{Wall}
{13300}{}{Wall}
{13400}{}{Wall}
{13500}{}{Drain}
{13501}{}{There is some sort of rank, disgusting smell coming from this sewer drain. After a few moments, it doesn't smell as bad.}
{13600}{}{Drain}
{13601}{}{You can barely make out some movement behind the grate covering this drain. You can see small red eyes peering back at you. Rat eyes.}
{13700}{}{Drain}
{13701}{}{Gurgling water sounds come from this drain. So does a really vile stench.}
{13800}{}{Drain}
{13801}{}{Gurgling water sounds come from beyond this drain. So does a really vile smell.}
{13900}{}{Ladder}
{13901}{}{It's an old, fairly rickety ladder. It looks like it will barely support your weight.}
{14000}{}{Sewer Hole}
{14001}{}{It looks like an access hole for the sewer system.}
{14100}{}{Light Source}
{14200}{}{Door}
{14201}{}{This looks like a standard Vault door that has been damaged, perhaps burned. It is still functional, however.}
{14300}{}{Door}
{14301}{}{This looks like a standard Vault door that has been damaged, perhaps burned. It is still functional, however.}
{14400}{}{Cover}
{14401}{}{A heavy man-hole cover. It looks like it is in good shape, and that it was recently moved.}
{14500}{}{Hole}
{14501}{}{A large hole has been blasted through this door.}
{14600}{}{Hole}
{14601}{}{A large hole has been blasted through this door.}
{14700}{}{Bullet Proof Glass}
{14701}{}{Completely unbreakable glass. Don't even try.}
{14800}{}{Bullet Proof Glass}
{14801}{}{Completely unbreakable glass. Don't even try.}
{14900}{}{Bullet Proof Glass}
{14901}{}{Completely unbreakable glass. Don't even try.}
{15000}{}{Bullet Proof Glass}
{15001}{}{Completely unbreakable glass. Don't even try.}
{15100}{}{Door}
{15101}{}{This door is a piece of high-technology construction. It opens by dilating as it rotates the three pieces that make up the door.}
{15200}{}{Door}
{15201}{}{This door is a piece of high-technology construction. It opens by dilating as it rotates the three pieces that make up the door.}
{15300}{}{Door}
{15301}{}{This door is emblazoned with the Brotherhood of Steel symbol.}
{15400}{}{Door}
{15401}{}{This door is emblazoned with the Brotherhood of Steel symbol.}
{15500}{}{Elevator}
{15501}{}{This is the interior of a Brotherhood elevator. It is squeaky clean!}
{15600}{}{Elevator}
{15601}{}{This is the interior of a Brotherhood elevator. It is squeaky clean!}
{15700}{}{Marker}
{15701}{}{This is the symbol of the Brotherhood of Steel. This marker tells the wasteland that this is their area, and to leave immediately.}
{15800}{}{Monitor}
{15801}{}{You see a computer monitor. It is made from advanced technology.}
{15900}{}{Monitor}
{15901}{}{You see a computer monitor. It is made from advanced technology.}
{16000}{}{Computer}
{16001}{}{This is a computer memory databank. It is obviously advanced technology.}
{16100}{}{Computer}
{16101}{}{This is a computer memory databank. It is obviously advanced technology.}
{16200}{}{Computer}
{16201}{}{A high-tech computer, using modern reel-to-reel storage devices instead of the antiquated punch cards.}
{16300}{}{Computer}
{16301}{}{A high-tech computer, using modern reel-to-reel storage devices instead of the antiquated punch cards.}
{16400}{}{Monitor}
{16401}{}{You see a computer monitor. It is made from advanced technology.}
{16500}{}{Monitor}
{16501}{}{You see a computer monitor. It is made from advanced technology.}
{16600}{}{Wire}
{16601}{}{Some sort of computer wiring.}
{16700}{}{Wire}
{16701}{}{Some sort of computer wiring.}
{16800}{}{Wire}
{16801}{}{Some sort of computer wiring.}
{16900}{}{Column}
{16901}{}{A support column.}
{17000}{}{Column}
{17001}{}{A support column.}
{17100}{}{Door Entry Computer}
{17101}{}{This computer controls the large vault door. You have to enter a specific access code for the computer to work.}
{17200}{}{Casino Sign}
{17201}{}{It looks like an advertisement for Gizmo's Casino.}
{17300}{}{Vault Outer Door}
{17301}{}{This large door is the link between the vault and the outside world.}
{17400}{}{Vault Outer Door}
{17401}{}{This large door is the link between the vault and the outside world.}
{17500}{}{Casino Sign}
{17501}{}{This part of the sign contains an electric motor that is slowly spinning the attached neon sign.}
{17600}{}{Down Arrow}
{17700}{}{Up Arrow}
{17800}{}{Crate}
{17900}{}{Crate}
{18000}{}{Crate}
{18100}{}{Elevator Top}
{18101}{}{You are looking at a portion of an elevator.}
{18200}{}{Computer Console}
{18201}{}{This is a dumb terminal, hooked up by cable to a large computer. It is advanced technology.}
{18300}{}{Computer Console}
{18301}{}{This is a dumb terminal, hooked up by cable to a large computer. It is advanced technology.}
{18400}{}{Emblem}
{18401}{}{The symbol of the Brotherhood. The gears represent their engineering knowledge, the sword is their will to defend themselves and the wings are the uplifting hope.}
{18500}{}{Emblem}
{18501}{}{The symbol of the Brotherhood. The gears represent their engineering knowledge, the sword is their will to defend themselves and the wings are the uplifting hope.}
{18600}{}{Level 'One' Sign}
{18601}{}{You think this could mean that you are on level one.}
{18700}{}{Level 'Two' Sign}
{18701}{}{You are on level two.}
{18800}{}{Level 'Three' Sign}
{18801}{}{This must mean that you are on level three.}
{18900}{}{Level 'Four' Sign}
{18901}{}{You must be on level four.}
{19000}{}{Bunk Bed}
{19001}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{19100}{}{Bunk Bed}
{19101}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{19200}{}{Bunk Bed}
{19201}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{19300}{}{Crate}
{19400}{}{Nuka-Cola Machine}
{19401}{}{The advertising on the side of this machine promotes their popular soda.}
{19500}{}{Wall}
{19600}{}{Trapdoor}
{19601}{}{It looks like a perfectly good trapdoor.}
{19700}{}{Manhole}
{19701}{}{The ladder in this manhole leads down into the darkness below. Ohhh, scary.}
{19800}{}{Altar}
{19801}{}{This is an altar.}
{19900}{}{Pulpit}
{19901}{}{People stand behind this and talk. It looks like it has a little place to hold a prepared speech.}
{20000}{}{Pew}
{20001}{}{This looks just like you would expect it to. Nothing special about this pew.}
{20100}{}{Signpost}
{20101}{}{The sign on this post looks a little rusty.}
{20200}{}{Signpost}
{20201}{}{The sign on this post looks a little rusty.}
{20300}{}{Signpost}
{20301}{}{The sign on this post looks a little rusty.}
{20400}{}{Signpost}
{20401}{}{The sign on this post looks a little rusty.}
{20500}{}{Signpost}
{20501}{}{The sign on this post looks a little rusty.}
{20600}{}{Old Mattress}
{20601}{}{An old, beat-up mattress. You think you see some sort of small bug-like critter infesting it.}
{20700}{}{Old Mattress}
{20701}{}{Even if you were to sleep by yourself on this thing, you would not be sleeping alone.}
{20800}{}{Bed}
{20801}{}{A make-shift bed. The material was scavenged from some other source.}
{20900}{}{Bed}
{20901}{}{A make-shift bed. The material was scavenged from some other source.}
{21000}{}{Bed}
{21001}{}{This bed has seen better days (and probably nights, too.)}
{21100}{}{Bed}
{21101}{}{On closer examination, you determine that the sheets have not been changed in a very, very long time.}
{21200}{}{Bed}
{21201}{}{There are a couple of stains of dubious origin on this well-worn sleeping device.}
{21300}{}{Bed}
{21301}{}{This bed has seen a lot of use and wear. Something must have crawled between the mattresses and died, too.}
{21400}{}{Cop Car}
{21500}{}{Vent}
{21501}{}{A busted piece of machinery, perhaps a vent.}
{21600}{}{Barrel}
{21601}{}{This barrel contains some disguisting biological goo. The biohazard symbol gives a clue to what the goo might be.}
{21700}{}{Water}
{21800}{}{Water}
{21900}{}{Water}
{22000}{}{Boxes}
{22001}{}{These wooden boxes are falling apart from the weather.}
{22100}{}{Boxes}
{22101}{}{You find no details worth mentioning about these wooden boxes.}
{22200}{}{Boxes}
{22201}{}{You have a lot of time on your hands to be looking closely at this rotten junk.}
{22300}{}{Boxes}
{22301}{}{These wooden boxes are falling apart from the weather.}
{22400}{}{Car}
{22401}{}{This automobile is in terrible shape. You cannot think of a way to restore it.}
{22500}{}{Car}
{22501}{}{This rusted piece of scrap-metal cannot be restored.}
{22600}{}{Car}
{22601}{}{You determine that this vehicle will never drive again. Really.}
{22700}{}{Car}
{22701}{}{There is no way that this junkyard wannabe will ever drive again.}
{22800}{}{Car}
{22801}{}{If the Mechanic of the Year suddenly appeared next to you, both of you could not fix this rusty heap.}
{22900}{}{Chair}
{22901}{}{A comfy chair.}
{23000}{}{Chair}
{23001}{}{This chair looks like it has seen better years.}
{23100}{}{Chair}
{23101}{}{This chair is moldy and gross. As you can guess, it stinks, too.}
{23200}{}{Chair}
{23201}{}{This chair is falling apart. Quickly.}
{23300}{}{Chair}
{23301}{}{If someone paid you a lot of money, and you could use steel britches, you might consider sitting in this chair.}
{23400}{}{Chair}
{23401}{}{This looks like an old office chair, still in pretty good shape after all these years.}
{23500}{}{Chair}
{23501}{}{This is an old office chair. It might even support the weight of a person.}
{23600}{}{Chair}
{23601}{}{This office chair has seen better days. It's pretty much trash, now.}
{23700}{}{Chair}
{23701}{}{This looks like a chair you would see in a mortician's office - dead.}
{23800}{}{Water Crane}
{23801}{}{A gooseneck apparatus used for delivering a large volume of water into the tank.}
{23900}{}{Fountain}
{24000}{}{Sign}
{24001}{}{The faded sign reads: Entrance - Mesa Verde - National Park.}
{24100}{}{Salicornia}
{24101}{}{Some sort of weed that thrives in salt marshes.}
{24200}{}{Cave In}
{24201}{}{A large amount of rock, far more than could ever be moved easily.}
{24300}{}{Fire Hydrant}
{24301}{}{This is a fire hydrant. Without Vault ceiling sprinklers, you might need one of these to put out fires.}
{24400}{}{Lamp Post}
{24401}{}{This lamp post looks like it is still in working condition. Imagine that, something that works out here.}
{24500}{}{Lamp Post}
{24501}{}{This lamp post will never work again.}
{24600}{}{Lamp Post}
{24601}{}{This is a working lamp post. At night, it casts a pale, gentle light that reminds you of absolutely nothing.}
{24700}{}{Lamp Post}
{24701}{}{This is a broken lamp post. It cannot be fixed.}
{24800}{}{Lamp Post}
{24801}{}{This light fixture is operational.}
{24900}{}{Lamp Post}
{24901}{}{The light in this lamp post is shattered beyond repair.}
{25000}{}{Lamp Post}
{25001}{}{This is a functional lamp post.}
{25100}{}{Fence}
{25101}{}{The bars look very sturdy.}
{25200}{}{Junk}
{25201}{}{Definitely useless junk, no doubt about it.}
{25300}{}{Junk}
{25301}{}{Definitely useless junk, no doubt about it.}
{25400}{}{Junk}
{25401}{}{Definitely useless junk, no doubt about it.}
{25500}{}{Junk}
{25501}{}{Definitely useless junk, no doubt about it.}
{25600}{}{Junk}
{25601}{}{Definitely useless junk, no doubt about it.}
{25700}{}{Mailbox}
{25701}{}{The mailbox is empty. You get the feeling it's been that way for a while.}
{25800}{}{Door}
{25801}{}{A nicely crafted wooden door, in good condition.}
{25900}{}{Door}
{25901}{}{A nicely crafted wooden door, in good condition.}
{26000}{}{Door}
{26001}{}{A nicely crafted wooden door, in good condition.}
{26100}{}{Door}
{26101}{}{A nicely crafted wooden door, in good condition.}
{26200}{}{Pew}
{26201}{}{This wooden pew is slowly falling apart.}
{26300}{}{Pew}
{26301}{}{This pew has been neglected, and is showing signs of wear and tear.}
{26400}{}{Pew}
{26401}{}{A wooden pew that has succumbed to the effects of age and abuse.}
{26500}{}{Newspaper Machine}
{26501}{}{The newspaper machine is empty.}
{26600}{}{Newspaper Machine}
{26601}{}{The newspaper machine is empty.}
{26700}{}{Newspaper Machine}
{26701}{}{The newspaper machine is empty.}
{26800}{}{Newspaper Machine}
{26801}{}{The newspaper machine is empty.}
{26900}{}{Newspaper Machine}
{26901}{}{The newspaper machine is empty.}
{27000}{}{Newspaper Machine}
{27001}{}{The newspaper machine is empty. It looks like it once held adult magazines.}
{27100}{}{Junk}
{27101}{}{A bed mattress in terrible condition. Even the rats won't sleep in or on it.}
{27200}{}{Junk}
{27201}{}{A twin bed mattress that has seen many better days than this one.}
{27300}{}{Junk}
{27301}{}{A pile of rotted and weathered wood. Not worth it's weight in, well, anything.}
{27400}{}{Junk}
{27401}{}{A pile of wood, with some rusty useless nails imbedded deeply.}
{27500}{}{Boxes}
{27501}{}{A pile of old, cardboard boxes. You cannot believe that they have survived for this long.}
{27600}{}{Boxes}
{27601}{}{A pile of old, cardboard boxes.}
{27700}{}{Junk}
{27701}{}{Some junk that you think might have been a bed mattress before it was destroyed by the environment.}
{27800}{}{Rocks}
{27900}{}{Rocks}
{28000}{}{Rocks}
{28100}{}{Rubble}
{28101}{}{A small rubble of stones and rocks. Watch your step!}
{28200}{}{Sink}
{28201}{}{A porcelain sink that has long lost the ability to function.}
{28300}{}{Sink}
{28301}{}{A broken porcelain sink. There is small puddle of brown water in the basin, with a floating dead rat.}
{28400}{}{Sink}
{28401}{}{This sink is not functional. You can tell this from the large crack down the middle.}
{28500}{}{Sink}
{28501}{}{A broken porcelain sink. There is small puddle of brown water in the basin, with a floating dead rat.}
{28600}{}{Stop Sign}
{28601}{}{A red sign with the word STOP written in large block letters.}
{28700}{}{Stop Sign}
{28701}{}{A red sign with the word STOP written in large block letters. The large bullet hole was added after manufacturing.}
{28800}{}{Stop Light}
{28801}{}{This is an ancient automobile traffic control device.}
{28900}{}{Stop Light}
{28901}{}{This is an ancient automobile traffic control device.}
{29000}{}{Stop Light}
{29001}{}{This is an ancient automobile traffic control device.}
{29100}{}{Street Light}
{29101}{}{This street light provides illumination after night falls, or in darkened areas.}
{29200}{}{Street Light}
{29201}{}{This street light provides illumination after night falls, or in darkened areas.}
{29300}{}{Street Light}
{29301}{}{This street light provides illumination after night falls, or in darkened areas.}
{29400}{}{Street Light}
{29401}{}{This street light provides illumination after night falls, or in darkened areas.}
{29500}{}{Street Light}
{29501}{}{This street light could provide illumination in darkened areas, if it wasn't completely broken.}
{29600}{}{Street Light}
{29601}{}{This street light could provide illumination in darkened areas, if it wasn't completely broken.}
{29700}{}{Street Light}
{29701}{}{This street light could provide illumination in darkened areas, if it wasn't completely broken.}
{29800}{}{Signpost}
{29801}{}{This sign should mark what street it is on, but the letters have faded into obscurity.}
{29900}{}{Signpost}
{29901}{}{This sign should mark what street it is on, but the letters have faded into obscurity.}
{30000}{}{Table}
{30001}{}{A wooden table, in fair to middling condition.}
{30100}{}{Table}
{30101}{}{A wooden table, in fair to middling condition.}
{30200}{}{Table}
{30201}{}{A wooden table, in middling to poor condition.}
{30300}{}{Table}
{30301}{}{A wooden table, with plastic surface, that has been broken for a while.}
{30400}{}{Table}
{30401}{}{A wooden table, painted a puke green color, that is beyond repair.}
{30500}{}{Table}
{30501}{}{This looks like an old coffee table, low to the ground for those really short mutants.}
{30600}{}{Table}
{30601}{}{This looks like an old coffee table, low to the ground for those really short mutants.}
{30700}{}{Toilet}
{30701}{}{The sharpened edges around the seat make this a very uncomfortable place to sit.}
{30800}{}{Toilet}
{30801}{}{This toilet is broken.}
{30900}{}{Toilet}
{30901}{}{Yuck! Whoever used this last did not flush!}
{31000}{}{Toilet}
{31001}{}{This toilet is broken and definitely not useable if you're a woman.}
{31100}{}{Trash}
{31101}{}{Some busted pipes half-buried in the dirt. Nothing important to see here. Move along.}
{31200}{}{Trash}
{31201}{}{Some broken pieces of glass and other ruined pieces of junk.}
{31300}{}{Trash}
{31301}{}{Some broken pieces of glass and other ruined pieces of junk.}
{31400}{}{Trash}
{31401}{}{A pipe that has been snapped in half. It looks like it rusted until it collapsed under it's own weight.}
{31500}{}{Trash Can}
{31501}{}{A trash can. You can barely read the label: Keep your city streets clean!}
{31600}{}{Tree}
{31601}{}{It's a dead tree.}
{31700}{}{Tree}
{31701}{}{A stump. Nothing really exciting. In fact, this might be the least exciting thing you have ever laid your eyes on.}
{31800}{}{Tree}
{31801}{}{It's a dead tree.}
{31900}{}{Tree}
{32000}{}{Tree}
{32100}{}{Tree}
{32200}{}{Destroyed Entrance}
{32201}{}{The destroyed entrance leads down into Tibbets.}
{32300}{}{Truck}
{32301}{}{The ruined remains of a diesel truck. This hunk of metal will never move again.}
{32400}{}{Truck}
{32401}{}{This diesel truck is beyond help. Way beyond help.}
{32500}{}{Bath Tub}
{32501}{}{This bath tub is broken and cracked.}
{32600}{}{Bath Tub}
{32601}{}{On closer examination, you realize that you won't be taking your bath in this tub after all.}
{32700}{}{Urinal}
{32701}{}{It's just a urinal.}
{32800}{}{Urinal}
{32801}{}{It's just a urinal.}
{32900}{}{Urinal}
{32901}{}{It's just a urinal. Nothing special.}
{33000}{}{Urinal}
{33001}{}{It's just a urinal. Nothing special.}
{33100}{}{Water Tank}
{33101}{}{A large tank that holds liquids. In this case, you believe that it was designed to store water.}
{33200}{}{Door}
{33201}{}{A wooden door. Nothing extremely interesting about it.}
{33300}{}{Door}
{33301}{}{A wooden door. It provides an entrance and egress from this building.}
{33400}{}{Wall Lamp}
{33401}{}{This lamp looks it is in good working condition.}
{33500}{}{Wall Lamp}
{33501}{}{A broken lamp. It is not surprising that it does not work.}
{33600}{}{Wall Lamp}
{33601}{}{This lamp looks it is in good working condition.}
{33700}{}{Wall Lamp}
{33701}{}{A broken lamp. It is not surprising that it does not work.}
{33800}{}{Wall Lamp}
{33801}{}{This lamp looks it is in good working condition.}
{33900}{}{Wall Lamp}
{33901}{}{A broken lamp. It is not surprising that it does not work.}
{34000}{}{Wall Lamp}
{34001}{}{This lamp looks it is in good working condition.}
{34100}{}{Wall Lamp}
{34101}{}{A broken lamp. It is not surprising that it does not work.}
{34200}{}{Yield Sign}
{34201}{}{This was a sign to control the flow of traffic.}
{34300}{}{Yield Sign}
{34301}{}{The sign is faded, but you can make out the world YIELD.}
{34400}{}{Block Hex Auto Inviso}
{34401}{}{If you can see this, blame the technical designer.}
{34500}{}{Floor}
{34600}{}{Door}
{34601}{}{An ornate wooden door. It is obviously made from fine workmanship.}
{34700}{}{Pew}
{34701}{}{This seat is supported by large concrete bricks. That's not important, but you're the one who looked.}
{34800}{}{Staircase}
{34801}{}{This staircase leads up.}
{34900}{}{Ladder}
{34901}{}{It's an old, fairly rickety ladder.}
{35000}{}{Staircase}
{35001}{}{This staircase doesn't lead up.}
{35100}{}{Ladder}
{35101}{}{Quite narrow but that makes it sturdier.}
{35200}{}{Stand}
{35201}{}{A rusty stand.}
{35300}{}{Power Generator}
{35301}{}{A broken Wattz ElectroBox power generator. Fairly standard as back-up generators before the war.}
{35400}{}{Pipe}
{35401}{}{A wide pipe with big red control valve.}
{35500}{}{Tiles}
{35501}{}{A small pile of floor tiles.}
{35600}{}{Staircase}
{35601}{}{This staircase leads down.}
{35700}{}{Wall}
{35701}{}{You are looking at the outside of the Cathedral.}
{35800}{}{Wall}
{35801}{}{You are looking at the outside of the Cathedral.}
{35900}{}{Wall}
{35901}{}{You are looking at the outside of the Cathedral.}
{36000}{}{Wall}
{36001}{}{You are looking at the outside of the Cathedral.}
{36100}{}{Curtain}
{36101}{}{This curtain looks like it was created by primitive means, but it is very functional.}
{36200}{}{Curtain}
{36201}{}{This curtain looks like it was created by primitive means, but it is very functional.}
{36300}{}{Bowl}
{36301}{}{A finely crafted wooden bowl. This looks like it was designed to crush and separate grains.}
{36400}{}{Bowl}
{36401}{}{A finely crafted wooden bowl.}
{36500}{}{Pot}
{36501}{}{A finely crafted pot.}
{36600}{}{Plant}
{36601}{}{It looks like a mutated cabbage to you. It seems to be thriving in the warm weather.}
{36700}{}{Plant}
{36701}{}{It looks like a mutated cabbage to you. It seems to be thriving in the warm weather.}
{36800}{}{Cart}
{36801}{}{A crude, but effective, agricultural cart.}
{36900}{}{Plant}
{36901}{}{A mutated cornstalk. It seems to be thriving under these conditions.}
{37000}{}{Plant}
{37001}{}{A mutated cornstalk. It seems to be thriving under these conditions.}
{37100}{}{Plant}
{37101}{}{A mutated cornstalk. It seems to be thriving under these conditions.}
{37200}{}{Pot}
{37201}{}{A finely crafted clay pot.}
{37300}{}{Rake}
{37301}{}{This rake is the property of it's owners. You can't even conceive of a use for it.}
{37400}{}{Rake}
{37401}{}{This rake is the property of it's owners. You can't even conceive of a use for it.}
{37500}{}{Rake}
{37501}{}{This rake is the property of it's owners. You can't even conceive of a use for it.}
{37600}{}{Rug}
{37601}{}{A simple rug. The weaver was obviously very talented.}
{37700}{}{Rug}
{37701}{}{A simple rug. The weaver was obviously very talented.}
{37800}{}{Rug}
{37801}{}{A simple rug. The weaver was obviously very talented.}
{37900}{}{Door}
{38000}{}{TV Set}
{38001}{}{A working TV set. The label identifies the manufacturer as Radiation King.}
{38100}{}{TV Screen}
{38101}{}{The TV screen shows static image.}
{38200}{}{Vase}
{38201}{}{A very pretty clay vase.}
{38300}{}{Well}
{38301}{}{A typical well found in the wasteland.}
{38400}{}{Pole}
{38401}{}{This pole helps to support the yurt.}
{38500}{}{Pole}
{38501}{}{This pole helps to support the yurt.}
{38600}{}{Pole}
{38601}{}{This pole helps to support the yurt.}
{38700}{}{Pole}
{38701}{}{This pole helps to support the yurt.}
{38800}{}{Pole}
{38801}{}{This pole helps to support the yurt.}
{38900}{}{Pole}
{38901}{}{This pole helps to support the yurt.}
{39000}{}{Vault Door}
{39001}{}{This vault door is now just a heavy piece of scrap-metal.}
{39100}{}{Wall}
{39101}{}{The mechanism to open and close the heavy vault door has been damaged beyond repair.}
{39200}{}{Brace}
{39201}{}{This brace helps to support the defensive wall.}
{39300}{}{Brace}
{39301}{}{This brace helps to support the defensive wall.}
{39400}{}{Brace}
{39401}{}{This brace helps to support the defensive wall.}
{39500}{}{Brace}
{39501}{}{This brace helps to support the defensive wall.}
{39600}{}{Metal Barrel}
{39601}{}{A rusty metal barrel. It is empty.}
{39700}{}{Metal Barrel}
{39701}{}{This barrel is probably empty from the hollow sound.}
{39800}{}{Metal Barrels}
{39801}{}{These barrels are probably empty from their hollow sound.}
{39900}{}{Metal Barrels}
{39901}{}{These barrels are probably empty from their hollow sound.}
{40000}{}{Dome}
{40001}{}{You find a small label that reads: "Property of Area-51. Return if found."}
{40100}{}{Crate}
{40101}{}{A wooden crate. It doesn't look in that bad of shape.}
{40200}{}{Crate}
{40201}{}{A simple wooden crate. In fairly good condition.}
{40300}{}{Crate}
{40301}{}{This simple wooden crate has collapsed under it's own weight.}
{40400}{}{Desk}
{40401}{}{A simple desk with a computer.}
{40500}{}{Desk}
{40501}{}{A simple desk with a computer.}
{40600}{}{Door}
{40601}{}{A wooden door, in fair shape.}
{40700}{}{Cave In}
{40701}{}{A large amount of rock, far more than could ever be moved easily.}
{40800}{}{Car}
{40801}{}{This submerged car cannot be repaired.}
{40900}{}{Car}
{40901}{}{This car is a little wet, and cannot be repaired.}
{41000}{}{Car}
{41001}{}{This car has been poorly parked. Unfortunately, it is beyond repair.}
{41100}{}{Junk}
{41101}{}{This junk has been ruined by the contaminated seawater.}
{41200}{}{Junk}
{41201}{}{This junk has almost washed away.}
{41300}{}{Junk}
{41301}{}{A choice selection of useless junk.}
{41400}{}{Pipes}
{41401}{}{These pipes used to transfer fuel from an underground tank to the garage. They haven't been used in a long time.}
{41500}{}{Pipe}
{41501}{}{These pipes used to transfer fuel from an underground tank to the garage. They haven't been used in a long time.}
{41600}{}{Pipes}
{41601}{}{These pipes used to transfer fuel from an underground tank to the garage. They haven't been used in a long time.}
{41700}{}{Elevator Shaft}
{41701}{}{Part of an elevator system.}
{41800}{}{Elevator Shaft}
{41801}{}{An elevator shaft that stretches deep into the ground. It has been damaged.}
{41900}{}{Elevator}
{41901}{}{An elevator. Use it to go up and down between levels.}
{42000}{}{Elevator Shaft}
{42001}{}{An elevator shaft that stretches deep into the ground. It has been damaged.}
{42100}{}{Door}
{42200}{}{Pipe}
{42201}{}{A metal pipe. Further details are not important.}
{42300}{}{Dirt}
{42400}{}{Box}
{42500}{}{Box}
{42600}{}{Box}
{42700}{}{Box}
{42800}{}{Rocks}
{42801}{}{A pile of rocks. Not very interesting.}
{42900}{}{Rocks}
{42901}{}{A pile of rocks. Not very interesting.}
{43000}{}{Rocks}
{43001}{}{A small pile of rocks. Not in the least bit interesting to you.}
{43100}{}{Rocks}
{43101}{}{A very small pile of rocks.}
{43200}{}{Rocks}
{43201}{}{A very small pile of rocks.}
{43300}{}{Rocks}
{43301}{}{A very small pile of rocks.}
{43400}{}{Rocks}
{43401}{}{A very small pile of rocks.}
{43500}{}{Rocks}
{43501}{}{A very small pile of rocks.}
{43600}{}{Vault Door}
{43601}{}{This vault door is very similar to the one at Vault-13. The door mechanism has been disabled.}
{43700}{}{Door}
{43701}{}{A finely constructed wooden door, reinforced with ornate metal braces of an almost hypnotic design.}
{43800}{}{Door}
{43801}{}{A finely constructed wooden door, reinforced with ornate metal braces of an almost hypnotic design.}
{43900}{}{Vats}
{43901}{}{A complex of some sort. You are not sure, but you can see large vats of a greenish goo that looks vaguely important.}
{44000}{}{Vats}
{44001}{}{A complex of some sort. You are not sure, but you can see large vats of a greenish goo that looks vaguely important.}
{44100}{}{Vats}
{44101}{}{A complex of some sort. You are not sure, but you can see large vats of a greenish goo that looks vaguely important.}
{44200}{}{Vats}
{44201}{}{A complex of some sort. You are not sure, but you can see large vats of a greenish goo that looks vaguely important.}
{44300}{}{Vats}
{44301}{}{A complex of some sort. You are not sure, but you can see large vats of a greenish goo that looks vaguely important.}
{44400}{}{Vats}
{44401}{}{A complex of some sort. You are not sure, but you can see large vats of a greenish goo that looks vaguely important.}
{44500}{}{Vats}
{44501}{}{A complex of some sort. You are not sure, but you can see large vats of a greenish goo that looks vaguely important.}
{44600}{}{Vats}
{44601}{}{A complex of some sort. You are not sure, but you can see large vats of a greenish goo that looks vaguely important.}
{44700}{}{Wall}
{44800}{}{Door}
{44801}{}{A security door. Looks heavily armored.}
{44900}{}{Door}
{45000}{}{Well}
{45001}{}{A typical well found in the wasteland.}
{45100}{}{Craps Table}
{45101}{}{This is a gambling table.}
{45200}{}{Craps Table}
{45201}{}{This is a gambling table.}
{45300}{}{Craps Table}
{45301}{}{This is a gambling table.}
{45400}{}{Craps Table}
{45401}{}{This is a gambling table.}
{45500}{}{Craps Table}
{45501}{}{This is a gambling table.}
{45600}{}{Craps Table}
{45601}{}{This is a gambling table.}
{45700}{}{Craps Table}
{45701}{}{This is a gambling table.}
{45800}{}{Craps Table}
{45801}{}{This is a gambling table.}
{45900}{}{Craps Table}
{45901}{}{This is a gambling table.}
{46000}{}{Craps Table}
{46001}{}{This is a gambling table.}
{46100}{}{Rock}
{46101}{}{A small rock, completely uninteresting in the context of this story.}
{46200}{}{Rock}
{46300}{}{Rock}
{46400}{}{Rock}
{46500}{}{Slot Machine}
{46501}{}{This is a gambling machine.}
{46600}{}{Slot Machine}
{46601}{}{This is a gambling machine.}
{46700}{}{Doorway}
{46800}{}{Elevator}
{46900}{}{Elevator}
{47000}{}{Door}
{47100}{}{Window}
{47101}{}{Instead of glass, this window is using wax paper.}
{47200}{}{Window}
{47201}{}{Instead of glass, this window is using wax paper.}
{47300}{}{Window}
{47301}{}{Instead of glass, this window is using wax paper.}
{47400}{}{Window}
{47401}{}{Instead of glass, this window is using wax paper.}
{47500}{}{Door}
{47501}{}{This large metal roll-door has been jammed shut from the inside.}
{47600}{}{Door}
{47601}{}{This large metal roll-door has been jammed shut from the inside.}
{47700}{}{Door}
{47701}{}{This large metal roll-door has been jammed shut from the inside. It reads LOADING ONLY.}
{47800}{}{Door}
{47801}{}{This large metal roll-door has been jammed shut from the inside.}
{47900}{}{Door}
{47901}{}{This large metal roll-door has been jammed shut from the inside.}
{48000}{}{Door}
{48001}{}{This large metal roll-door has been jammed shut from the inside. It reads LOADING ONLY.}
{48100}{}{Door}
{48101}{}{This door looks suspiciously like the door you would find in a warehouse.}
{48200}{}{Door}
{48201}{}{This door looks suspiciously like the door you would find in a warehouse.}
{48300}{}{Weather Vane}
{48301}{}{This simple weather vane helps the people to study the weather.}
{48400}{}{Altar}
{48401}{}{A simple altar made from painted wood.}
{48500}{}{Podium}
{48501}{}{This is a normal podium for public speaking.}
{48600}{}{Altar}
{48700}{}{Monitor}
{48701}{}{A large monitor, black and white only. The reception is pretty good for being indoors without an antenna.}
{48800}{}{Monitor}
{48801}{}{A large monitor, black and white only. The robed figure is reciting something at a feverish pace but there is no sound coming out.}
{48900}{}{Forcefield}
{48901}{}{This is a powerful field of energy.}
{49000}{}{Forcefield}
{49001}{}{This is a powerful field of energy.}
{49100}{}{Forcefield}
{49101}{}{This is a powerful field of energy.}
{49200}{}{Forcefield}
{49201}{}{This is a powerful field of energy.}
{49300}{}{Table}
{49301}{}{A fairly ordinary wooden table.}
{49400}{}{Table}
{49401}{}{A fairly ordinary wooden table.}
{49500}{}{Table}
{49501}{}{A fairly ordinary wooden table.}
{49600}{}{Table}
{49601}{}{A fairly ordinary wooden table.}
{49700}{}{Table}
{49701}{}{A fairly ordinary wooden table.}
{49800}{}{Table}
{49801}{}{A fairly ordinary wooden table.}
{49900}{}{Door}
{50000}{}{Shelf}
{50100}{}{Shelf}
{50200}{}{Shelf}
{50300}{}{Shelf}
{50400}{}{Shelf}
{50500}{}{Altar}
{50501}{}{A simple altar made from painted wood.}
{50600}{}{Altar}
{50601}{}{A simple altar made from painted wood.}
{50700}{}{Altar}
{50701}{}{A simple altar made from painted wood.}
{50800}{}{Altar}
{50801}{}{A simple altar made from painted wood.}
{50900}{}{Rubble}
{50901}{}{A collapsed section of the roof has formed this pile of rubble. Your rope leads back to the surface.}
{51000}{}{Bookshelf}
{51100}{}{Bookshelf}
{51200}{}{Bookshelf}
{51300}{}{Bookshelf}
{51400}{}{Bookshelf}
{51500}{}{Bookshelf}
{51600}{}{Table}
{51601}{}{This large table looks important. Perhaps they hold meetings here?}
{51700}{}{Table}
{51701}{}{This large table looks important. Perhaps they hold meetings here?}
{51800}{}{Table}
{51801}{}{This large table looks important. Perhaps they hold meetings here?}
{51900}{}{Table}
{51901}{}{This large table looks important. Perhaps they hold meetings here?}
{52000}{}{Table}
{52001}{}{This large table looks important. Perhaps they hold meetings here?}
{52100}{}{Table}
{52101}{}{This large table looks important. Perhaps they hold meetings here?}
{52200}{}{Altar}
{52201}{}{An altar designed and used by the Brotherhood of Steel. Their symbol is brazenly shown.}
{52300}{}{Altar}
{52301}{}{An altar designed and used by the Brotherhood of Steel. Their symbol is brazenly shown.}
{52400}{}{Altar}
{52401}{}{An altar designed and used by the Brotherhood of Steel. Their symbol is brazenly shown.}
{52500}{}{Pew}
{52501}{}{A nicely fashioned, and mighty uncomfortable looking, pew.}
{52600}{}{Podium}
{52601}{}{A nice wooden podium. There is a tele-prompter screen built into it, facing the speaker.}
{52700}{}{Wagon}
{52701}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{52800}{}{Wagon}
{52801}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{52900}{}{Wagon}
{52901}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{53000}{}{Wagon}
{53001}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{53100}{}{Wagon}
{53101}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{53200}{}{Wagon}
{53201}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{53300}{}{Mat}
{53301}{}{A training mat.}
{53400}{}{Mat}
{53401}{}{A training mat.}
{53500}{}{Mat}
{53501}{}{A training mat.}
{53600}{}{Mat}
{53601}{}{A training mat.}
{53700}{}{Punching Bag}
{53701}{}{This is a StrongMan(tm) punching bag.}
{53800}{}{Stair Stepper}
{53801}{}{An exercise machine.}
{53900}{}{Stair Stepper}
{54000}{}{Treadmill}
{54001}{}{An exercise machine.}
{54100}{}{Treadmill}
{54101}{}{An exercise machine.}
{54200}{}{Bench Press}
{54201}{}{An exercise machine.}
{54300}{}{Bench Press}
{54301}{}{An exercise machine.}
{54400}{}{Wood Planks}
{54401}{}{These sturdy wooden planks have been firmly bound together.}
{54500}{}{Wood Planks}
{54501}{}{These sturdy wooden planks have been firmly bound together.}
{54600}{}{Roulette Table}
{54601}{}{This is a gambling table.}
{54700}{}{Roulette Table}
{54701}{}{This is a gambling table.}
{54800}{}{Roulette Table}
{54801}{}{This is a gambling table.}
{54900}{}{Roulette Table}
{54901}{}{This is a gambling table.}
{55000}{}{Roulette Table}
{55001}{}{This is a gambling table.}
{55100}{}{Barrel}
{55101}{}{This empty metal barrel has the nuclear trefoil symbol painted on the side in bright yellow paint.}
{55200}{}{Barrel}
{55201}{}{This barrel contains some green glowing goo. The nuclear trefoil symbol gives a clue to what the goo might be.}
{55300}{}{Computer}
{55301}{}{A very modern looking computer.}
{55400}{}{Computer}
{55401}{}{A very modern looking computer.}
{55500}{}{Suspension Tank}
{55501}{}{Some sort of medical or experimental apparatus, it looks as if it could contain a human or larger sized body.}
{55600}{}{Broken Suspension Tank}
{55601}{}{A broken piece of equipment. It is beyond repair.}
{55700}{}{Mainframe}
{55701}{}{A large super computer. Probably the fastest looking computer you've ever seen.}
{55800}{}{Support Platform}
{55801}{}{This platform supports the large super computer over the cooling tanks.}
{55900}{}{Don't use}
{56000}{}{Don't use}
{56100}{}{Bed}
{56101}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{56200}{}{Bed}
{56201}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{56300}{}{Bed}
{56301}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{56400}{}{Wire}
{56401}{}{It looks like a serial cable of some sort.}
{56500}{}{Wire}
{56501}{}{It looks like a serial cable of some sort.}
{56600}{}{Sign}
{56601}{}{The sign reads BAR. That should be pretty self-evident.}
{56700}{}{Beam}
{56701}{}{This strong beam is stationed over the hole.}
{56800}{}{Beam}
{56801}{}{There is a rope securely attached to the beam. It looks like you can climb down into the hole now.}
{56900}{}{Shelves}
{56901}{}{You see some very empty metal shelves.}
{57000}{}{Shelves}
{57001}{}{You see some very empty metal shelves.}
{57100}{}{Shelves}
{57101}{}{You see some very empty metal shelves.}
{57200}{}{Shelves}
{57201}{}{You see some very empty metal shelves.}
{57300}{}{Bush}
{57301}{}{A desert weed of some kind. Not important to this story.}
{57400}{}{Bush}
{57401}{}{A desert weed of some kind.}
{57500}{}{Bush}
{57501}{}{A desert weed of some kind.}
{57600}{}{Ground}
{57601}{}{A nice view of the wasteland from this level. You get a good feeling of just how high up in the sky you are.}
{57700}{}{Ground}
{57701}{}{A nice view of the wasteland from this level. You get a good feeling of just how high up in the sky you are.}
{57800}{}{Wall}
{57801}{}{A good view of the outside of the Cathedral.}
{57900}{}{Wall}
{57901}{}{A good view of the outside of the Cathedral.}
{58000}{}{Wall}
{58001}{}{A good view of the outside of the Cathedral.}
{58100}{}{Door}
{58101}{}{A door that looks perfectly at home in a cell.}
{58200}{}{Sign}
{58201}{}{This sign says this store is called Darkwater's.}
{58300}{}{Ladder}
{58301}{}{This ladder leads into the darkness below.}
{58400}{}{Ladder}
{58401}{}{This ladder leads into the darkness below.}
{58500}{}{Machinery}
{58501}{}{It looks like an old printing press or manufacturing doohickey.}
{58600}{}{Machinery}
{58601}{}{It looks like an old printing press or manufacturing doohickey.}
{58700}{}{Machinery}
{58701}{}{It looks like an old printing press or manufacturing doohickey.}
{58800}{}{Machinery}
{58801}{}{It looks like an old printing press or manufacturing doohickey.}
{58900}{}{Machinery}
{58901}{}{It looks like an old printing press or manufacturing doohickey.}
{59000}{}{Machinery}
{59001}{}{It looks like an old printing press or manufacturing doohickey.}
{59100}{}{Table}
{59101}{}{This metal table looks in good condition. There is a drain in the center of it.}
{59200}{}{Table}
{59201}{}{This metal table looks in good condition. There is a drain in the center of it.}
{59300}{}{Table}
{59301}{}{The metal table is covered by some kind of biomass.}
{59400}{}{Table}
{59401}{}{The metal table is covered by some kind of biomass.}
{59500}{}{Table}
{59501}{}{The metal table is covered by some kind of biomass.}
{59600}{}{Bulletin Board}
{59601}{}{Notices for employment are stapled to the board. It looks well used.}
{59700}{}{Guard Shack}
{59701}{}{This guard shack is over a hundred years old, but still in excellent condition.}
{59800}{}{Sign}
{59801}{}{This sign says: General Store.}
{59900}{}{Sign}
{59901}{}{This sign says: General Store.}
{60000}{}{Sign}
{60001}{}{This sign says: Market}
{60100}{}{Slime Pool}
{60101}{}{It looks very unhealthy. You might want to wear armored swim trunks before taking a dip.}
{60200}{}{Slime Pool}
{60201}{}{It looks very unhealthy. You might want to wear armored swim trunks before taking a dip.}
{60300}{}{Slime Pool}
{60301}{}{It looks very unhealthy. You might want to wear armored swim trunks before taking a dip.}
{60400}{}{Table}
{60401}{}{A nice looking metal table.}
{60500}{}{Table}
{60501}{}{A nice looking metal table.}
{60600}{}{Table}
{60601}{}{A nice looking metal table.}
{60700}{}{Table}
{60701}{}{A nice looking metal table.}
{60800}{}{Table}
{60801}{}{This metal table has not been treated well. The rust is very pervasive.}
{60900}{}{Table}
{60901}{}{A good looking metal table, except for the rust.}
{61000}{}{Table}
{61001}{}{A good looking metal table, except for the rust.}
{61100}{}{Table}
{61101}{}{A good looking metal table, except for the rust.}
{61200}{}{Fire Pit}
{61201}{}{The fire is burning.}
{61300}{}{Mirror}
{61301}{}{You look at yourself for a while.}
{61400}{}{Mirror}
{61401}{}{You stare at your image in the mirror for a while.}
{61500}{}{Sink}
{61501}{}{A fully functioning sink. Nice and clean, too.}
{61600}{}{Toilet}
{61601}{}{This toilet is very clean. It works, too.}
{61700}{}{Urinal}
{61701}{}{This urinal is functional.}
{61800}{}{Toilet}
{61801}{}{If you had a toilet fetish, then this would be a nice toilet.}
{61900}{}{Sink}
{61901}{}{This sink is in perfect condition.}
{62000}{}{Urinal}
{62001}{}{This urinal is in perfect condition.}
{62100}{}{Shower}
{62101}{}{A military-style shower. Not to be used by modest people.}
{62200}{}{Shower}
{62201}{}{A military-style shower. Not to be used by modest people.}
{62300}{}{Shower}
{62301}{}{A military-style shower. Not to be used by modest people.}
{62400}{}{Shower}
{62401}{}{A military-style shower. Not to be used by modest people.}
{62500}{}{Shower}
{62501}{}{A military-style shower. Not to be used by modest people.}
{62600}{}{Shower}
{62601}{}{A military-style shower. Not to be used by modest people.}
{62700}{}{Bed}
{62701}{}{A very comfortable looking bed.}
{62800}{}{Bed}
{62801}{}{A very comfortable looking bed.}
{62900}{}{Bed}
{62901}{}{A structurally-enhanced bunk bed.}
{63000}{}{Bed}
{63001}{}{A structurally-enhanced bunk bed.}
{63100}{}{Bed}
{63101}{}{A structurally-enhanced bunk bed.}
{63200}{}{Terminal}
{63300}{}{Terminal}
{63400}{}{Flag}
{63401}{}{This flag is the symbol of the Children of the Cathedral.}
{63500}{}{Flag}
{63501}{}{This flag is the symbol of the Children of the Cathedral.}
{63600}{}{Flag}
{63601}{}{This flag is the symbol of the Children of the Cathedral.}
{63700}{}{Computer}
{63701}{}{A large computer.}
{63800}{}{Computer}
{63801}{}{A large computer.}
{63900}{}{Computer}
{63901}{}{A large computer.}
{64000}{}{Terminal}
{64001}{}{The terminal to a large computer.}
{64100}{}{Dead Body}
{64101}{}{It looks as if this person died very painfully.}
{64200}{}{Dead Body}
{64201}{}{It looks as if this person died very painfully.}
{64300}{}{Dead Body}
{64301}{}{It looks as if this person died very painfully.}
{64400}{}{Dead Body}
{64401}{}{It looks as if this person died very painfully.}
{64500}{}{Door}
{64501}{}{This barred door works well as the door to a jail cell.}
{64600}{}{Terminal}
{64700}{}{Terminal}
{64800}{}{Forklift}
{64801}{}{The forklift is inoperable.}
{64900}{}{Forklift}
{64901}{}{The forklift is inoperable.}
{65000}{}{Equipment}
{65100}{}{Medical Table}
{65101}{}{This table is very rusty. The drain in the center of the table is clogged.}
{65200}{}{Medical Table}
{65201}{}{This table is very rusty.}
{65300}{}{Gate}
{65301}{}{This gate has a bar that raises and lowers.}
{65400}{}{Pipe}
{65500}{}{Pipe}
{65600}{}{Power Generator}
{65601}{}{A Wattz ElectroBox power generator. Fairly standard as back-up generators before the war.}
{65700}{}{Tank}
{65701}{}{A large water-tank. Looks well-maintained, which is probably a good thing.}
{65800}{}{Police Box}
{65801}{}{A police box from the UK, circa 1960.}
{65900}{}{Table}
{65901}{}{A nicely made table. Hand-made, but it looks much nicer than any table you've seen before.}
{66000}{}{Table}
{66001}{}{A nicely made table. Hand-made, but it looks much nicer than any table you've seen before.}
{66100}{}{Table}
{66101}{}{A nicely made table. Hand-made, but it looks much nicer than any table you've seen before.}
{66200}{}{Chair}
{66201}{}{A very nice looking chair.}
{66300}{}{Chair}
{66301}{}{A very nice looking chair.}
{66400}{}{Chair}
{66401}{}{A very nice looking chair.}
{66500}{}{Chair}
{66501}{}{A very nice looking chair.}
{66600}{}{Chair}
{66601}{}{A very nice looking chair.}
{66700}{}{Chair}
{66701}{}{A very nice looking chair.}
{66800}{}{Chair}
{66801}{}{A very nice looking chair.}
{66900}{}{Chair}
{66901}{}{A very nice looking chair.}
{67000}{}{Chair}
{67001}{}{A very nice looking chair.}
{67100}{}{Chair}
{67101}{}{A very nice looking chair.}
{67200}{}{Chair}
{67201}{}{A very nice looking chair.}
{67300}{}{Chair}
{67301}{}{A very nice looking chair.}
{67400}{}{Chair}
{67401}{}{A very nice looking chair.}
{67500}{}{Chair}
{67501}{}{A very nice looking chair.}
{67600}{}{Chair}
{67601}{}{A very nice looking chair.}
{67700}{}{Chair}
{67701}{}{A very nice looking chair.}
{67800}{}{Bed}
{67801}{}{A very nice looking bed.}
{67900}{}{Bed}
{67901}{}{A very nice looking bed.}
{68000}{}{Bed}
{68001}{}{A very nice looking bed.}
{68100}{}{Bed}
{68101}{}{A very nice looking bed.}
{68200}{}{Stove}
{68201}{}{A functional wood-burning stove.}
{68300}{}{Stove}
{68301}{}{A functional wood-burning stove.}
{68400}{}{Stove}
{68401}{}{A functional wood-burning stove.}
{68500}{}{Stove}
{68501}{}{A functional wood-burning stove.}
{68600}{}{Broken Post}
{68700}{}{Destroyed Entrance}
{68800}{}{Rocks}
{68801}{}{A large formation of rocks. This was not a natural occurrence.}
{68900}{}{Rocks}
{68901}{}{A large formation of rocks. This was not a natural occurrence.}
{69000}{}{Toilet}
{69001}{}{A crude, but effective, toilet. There are some leaves dropped into the hole to manage the odor.}
{69100}{}{Mountain}
{69101}{}{These mountain walls look very inaccessible.}
{69200}{}{Mountain}
{69201}{}{These mountain walls look very inaccessible.}
{69300}{}{Mountain}
{69301}{}{These mountain walls look very inaccessible.}
{69400}{}{Mountain}
{69401}{}{These mountain walls look very inaccessible.}
{69500}{}{Mountain}
{69501}{}{These mountain walls look very inaccessible.}
{69600}{}{Mountain}
{69601}{}{These mountain walls look very inaccessible.}
{69700}{}{Goo}
{69701}{}{You see some strange noxious biological goo.}
{69800}{}{Goo}
{69801}{}{You see some strange noxious biological goo.}
{69900}{}{Goo}
{69901}{}{You see some strange noxious biological goo.}
{70000}{}{Goo}
{70001}{}{You see some strange noxious biological goo.}
{70100}{}{Goo}
{70101}{}{You see some strange noxious biological goo.}
{70200}{}{Goo}
{70201}{}{You see some strange noxious biological goo.}
{70300}{}{Goo}
{70301}{}{You see some strange noxious biological goo.}
{70400}{}{Goo}
{70401}{}{You see some strange noxious biological goo.}
{70500}{}{Goo}
{70501}{}{You see some strange noxious biological goo.}
{70600}{}{Goo}
{70601}{}{You see some strange noxious biological goo.}
{70700}{}{Goo}
{70701}{}{You see some strange noxious biological goo.}
{70800}{}{Goo}
{70801}{}{You see some strange noxious biological goo.}
{70900}{}{Goo}
{70901}{}{You see some strange noxious biological goo.}
{71000}{}{Goo}
{71001}{}{You see some strange noxious biological goo.}
{71100}{}{Goo}
{71101}{}{You see some strange noxious biological goo.}
{71200}{}{Goo}
{71201}{}{You see some strange noxious biological goo.}
{71300}{}{Goo}
{71301}{}{You see some strange noxious biological goo.}
{71400}{}{Goo}
{71401}{}{You see some strange noxious biological goo.}
{71500}{}{Goo}
{71501}{}{You see some strange noxious biological goo.}
{71600}{}{Goo}
{71601}{}{You see some strange noxious biological goo.}
{71700}{}{Goo}
{71701}{}{You see some strange noxious biological goo.}
{71800}{}{Goo}
{71801}{}{You see some strange noxious biological goo.}
{71900}{}{Goo}
{71901}{}{You see some strange noxious biological goo.}
{72000}{}{Goo}
{72001}{}{You see some strange noxious biological goo.}
{72100}{}{Goo}
{72101}{}{You see some strange noxious biological goo.}
{72200}{}{Goo}
{72201}{}{You see some strange noxious biological goo.}
{72300}{}{Goo}
{72301}{}{You see some strange noxious biological goo.}
{72400}{}{Goo}
{72401}{}{You see some strange noxious biological goo.}
{72500}{}{Goo}
{72501}{}{You see some strange noxious biological goo.}
{72600}{}{Goo}
{72601}{}{You see some strange noxious biological goo.}
{72700}{}{Goo}
{72701}{}{You see some strange noxious biological goo.}
{72800}{}{Goo}
{72801}{}{You see some strange noxious biological goo.}
{72900}{}{Goo}
{72901}{}{You see some strange noxious biological goo.}
{73000}{}{Goo}
{73001}{}{You see some strange noxious biological goo.}
{73100}{}{Goo}
{73101}{}{You see some strange noxious biological goo.}
{73200}{}{Goo}
{73201}{}{You see some strange noxious biological goo.}
{73300}{}{Goo}
{73301}{}{You see some strange noxious biological goo.}
{73400}{}{Goo}
{73401}{}{You see some strange noxious biological goo.}
{73500}{}{Goo}
{73501}{}{You see some strange noxious biological goo.}
{73600}{}{Goo}
{73601}{}{You see some strange noxious biological goo.}
{73700}{}{Goo}
{73701}{}{You see some strange noxious biological goo.}
{73800}{}{Goo}
{73801}{}{You see some strange noxious biological goo.}
{73900}{}{Goo}
{73901}{}{You see some strange noxious biological goo.}
{74000}{}{Goo}
{74001}{}{You see some strange noxious biological goo.}
{74100}{}{Goo}
{74101}{}{You see some strange noxious biological goo.}
{74200}{}{Goo}
{74201}{}{You see some strange noxious biological goo.}
{74300}{}{Goo}
{74301}{}{You see some strange noxious biological goo.}
{74400}{}{Goo}
{74401}{}{You see some strange noxious biological goo.}
{74500}{}{Goo}
{74501}{}{You see some strange noxious biological goo.}
{74600}{}{Goo}
{74601}{}{You see some strange noxious biological goo.}
{74700}{}{Goo}
{74701}{}{You see some strange noxious biological goo.}
{74800}{}{Goo}
{74801}{}{You see some strange noxious biological goo.}
{74900}{}{Computer}
{74901}{}{The amount of goo on this computer makes it very difficult to access.}
{75000}{}{Computer}
{75001}{}{The amount of goo on this computer makes it very difficult to access.}
{75100}{}{Computer}
{75101}{}{The amount of goo on this computer makes it very difficult to access.}
{75200}{}{Computer}
{75201}{}{The amount of goo on this computer makes it very difficult to access.}
{75300}{}{Computer}
{75301}{}{The amount of goo on this computer makes it very difficult to access.}
{75400}{}{Computer}
{75401}{}{The amount of goo on this computer makes it very difficult to access.}
{75500}{}{Computer}
{75501}{}{The amount of goo on this computer makes it very difficult to access.}
{75600}{}{Computer}
{75601}{}{The amount of goo on this computer makes it very difficult to access.}
{75700}{}{Computer}
{75701}{}{The amount of goo on this computer makes it very difficult to access.}
{75800}{}{Computer}
{75801}{}{The amount of goo on this computer makes it very difficult to access.}
{75900}{}{Computer}
{75901}{}{The amount of goo on this computer makes it very difficult to access.}
{76000}{}{Computer}
{76001}{}{The amount of goo on this computer makes it very difficult to access.}
{76100}{}{Monitors}
{76101}{}{You cannot read anything on the monitor due to the amount of goo splashed across the screens.}
{76200}{}{Monitors}
{76201}{}{You cannot read anything on the monitor due to the amount of goo splashed across the screens.}
{76300}{}{Monitors}
{76301}{}{You cannot read anything on the monitor due to the amount of goo splashed across the screens.}
{76400}{}{Monitors}
{76401}{}{You cannot read anything on the monitor due to the amount of goo splashed across the screens.}
{76500}{}{Floor}
{76501}{}{You would swear that there is something moving on the floor.}
{76600}{}{Pedestal}
{76601}{}{The pedestal looks as if it were slowly breathing in and out.}
{76700}{}{Floor}
{76800}{}{Bomb}
{76801}{}{This is a nuclear bomb. It looks very dangerous just sitting there.}
{76900}{}{Support Base}
{76901}{}{This base cradles the nuclear bomb that is sitting on it.}
{77000}{}{Computer Console}
{77001}{}{This is a nuclear access computer. The computer looks very secure. There is a slot for a strangely shaped key.}
{77100}{}{Wires}
{77101}{}{These wires are connecting the bomb to the computer.}
{77200}{}{Chair}
{77201}{}{There is nothing unusual about this chair.}
{77300}{}{Chair}
{77301}{}{There is nothing unusual about this chair.}
{77400}{}{Chair}
{77401}{}{There is nothing unusual about this chair.}
{77500}{}{Chair}
{77501}{}{There is nothing unusual about this chair.}
{77600}{}{Chair}
{77601}{}{There is nothing unusual about this chair.}
{77700}{}{Chair}
{77701}{}{There is nothing unusual about this chair.}
{77800}{}{Chair}
{77801}{}{There is nothing unusual about this chair.}
{77900}{}{Chair}
{77901}{}{There is nothing unusual about this chair.}
{78000}{}{Pillar}
{78001}{}{A support pillar.}
{78100}{}{Pillar}
{78101}{}{A support pillar.}
{78200}{}{Pillar}
{78201}{}{A support pillar.}
{78300}{}{Pillar}
{78301}{}{A support pillar.}
{78400}{}{Bed}
{78401}{}{This bed is in wretched condition.}
{78500}{}{Bed}
{78501}{}{This bed is in very poor condition.}
{78600}{}{Bed}
{78601}{}{This bed is in poor condition.}
{78700}{}{Bed}
{78701}{}{This bed is in pretty bad condition.}
{78800}{}{Monitors}
{78801}{}{These monitors are broken and cannot function.}
{78900}{}{Monitors}
{78901}{}{These monitors are broken and cannot function.}
{79000}{}{Monitors}
{79001}{}{These monitors are broken and cannot function.}
{79100}{}{Monitors}
{79101}{}{These monitors are broken and cannot function.}
{79200}{}{Vent}
{79201}{}{Very little fresh air is coming from this vent.}
{79300}{}{Vent}
{79301}{}{Almost no fresh air is coming from this vent.}
{79400}{}{Vent}
{79401}{}{No fresh air is coming from this vent.}
{79500}{}{Vent}
{79501}{}{Just a tiny amount of fresh air is coming from this vent.}
{79600}{}{Table}
{79601}{}{There is nothing unusual about this table, except that it is almost destroyed.}
{79700}{}{Table}
{79701}{}{This table was badly damaged.}
{79800}{}{Table}
{79801}{}{This table is in very poor condition.}
{79900}{}{Table}
{79901}{}{There is no reason to search this table.}
{80000}{}{Monitors}
{80001}{}{The display screens in this bank of monitors have been destroyed.}
{80100}{}{Monitors}
{80101}{}{The display screens in this bank of monitors have been damaged beyond repair.}
{80200}{}{Monitor}
{80201}{}{The monitor screen is cracked and destroyed.}
{80300}{}{Monitor}
{80301}{}{This monitor is worthless with a broken display screen.}
{80400}{}{Computer}
{80401}{}{This computer is broken.}
{80500}{}{Computer}
{80501}{}{This computer is broken.}
{80600}{}{Computer}
{80601}{}{This computer is broken.}
{80700}{}{Chair}
{80701}{}{This chair is ruined.}
{80800}{}{Chair}
{80801}{}{This chair is ruined.}
{80900}{}{Chair}
{80901}{}{This chair is ruined.}
{81000}{}{Chair}
{81001}{}{This chair is ruined.}
{81100}{}{Vent}
{81101}{}{This vent has been damaged beyond repair.}
{81200}{}{Vent}
{81201}{}{This vent is very damaged, and cannot be repaired.}
{81300}{}{Vent}
{81301}{}{This vent is not functioning at all.}
{81400}{}{Computer}
{81401}{}{This computer looks like it is barely functional.}
{81500}{}{Computer}
{81501}{}{This computer looks like it is barely functional.}
{81600}{}{Monitor}
{81601}{}{The monitor is barely working.}
{81700}{}{Monitor}
{81701}{}{The monitor is barely working.}
{81800}{}{Computer}
{81801}{}{The computer is not functioning.}
{81900}{}{Computer}
{81901}{}{The computer is not functioning.}
{82000}{}{Monitor}
{82001}{}{The monitor is not functioning.}
{82100}{}{Monitor}
{82101}{}{The monitor is not functioning.}
{82200}{}{Doorway}
{82201}{}{It looks like a very nice doorway. It does the job of holding up a door very well.}
{82300}{}{Monitors}
{82301}{}{The monitors are in good condition.}
{82400}{}{Monitors}
{82401}{}{The monitors are in good condition.}
{82500}{}{Wall}
{82600}{}{Bank Door}
{82601}{}{A very sturdy bank vault door. The door looks very secure.}
{82700}{}{Light}
{82701}{}{A security light.}
{82800}{}{Light}
{82801}{}{A security light.}
{82900}{}{Pillar}
{82901}{}{This pillar is a replica of the one found in the NCR's capital, Shady Sands. It tells stories to remind the people of hope and peace.}
{83000}{}{Robot Receptacle}
{83001}{}{This is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83100}{}{Robot Receptacle}
{83101}{}{This is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83200}{}{Robot Receptacle}
{83201}{}{This is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83300}{}{Robot Receptacle}
{83301}{}{This is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83400}{}{Robot Receptacle}
{83401}{}{This is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83500}{}{Machine}
{83501}{}{This machine has something to do with the robot service bays. It does not look particular interesting.}
{83600}{}{Machine}
{83601}{}{This machine has something to do with the robot service bays. It does not look very interesting.}
{83700}{}{Stripe}
{83800}{}{Stripe}
{83900}{}{Stripe}
{84000}{}{Stripe}
{84100}{}{Stripe}
{84200}{}{Stripe}
{84300}{}{Stripe}
{84400}{}{Stripe}
{84500}{}{Stripe}
{84600}{}{Stripe}
{84700}{}{Stripe}
{84800}{}{Door}
{84801}{}{A very normal wooden door.}
{84900}{}{Door}
{84901}{}{A very normal wooden door.}
{85000}{}{Door}
{85001}{}{A very normal wooden door.}
{85100}{}{Sign}
{85101}{}{This sign stands for Friendly Lending Company.}
{85200}{}{Emblem}
{85201}{}{This appears to be a religious emblem.}
{85300}{}{Medical Table}
{85301}{}{This looks like a medical examination table.}
{85400}{}{Sign}
{85401}{}{This is a neon sign for the Maltese Falcon.}
{85500}{}{Graffiti}
{85600}{}{Graffiti}
{85700}{}{Graffiti}
{85800}{}{Graffiti}
{85900}{}{Graffiti}
{86000}{}{Graffiti}
{86100}{}{Graffiti}
{86200}{}{Graffiti}
{86300}{}{Graffiti}
{86400}{}{Graffiti}
{86500}{}{Graffiti}
{86600}{}{Graffiti}
{86700}{}{Graffiti}
{86800}{}{Graffiti}
{86900}{}{Sign}
{86901}{}{It says: GUNS. They might sell guns there.}
{87000}{}{Sign}
{87001}{}{The sign reads: Police.}
{87100}{}{Sign}
{87101}{}{This is the sign of the Far Go Traders.}
{87200}{}{Sign}
{87201}{}{This sign is labeled: Gunrunners.}
{87300}{}{Sign}
{87301}{}{This is the sign of the Crimson Caravan trading company.}
{87400}{}{Sign}
{87401}{}{This sign reads: Hospital. This might be a good thing.}
{87500}{}{Sign}
{87501}{}{This is the sign of Hock-it to Bob.}
{87600}{}{Sign}
{87601}{}{This very unlikely sign reads: Bob's Pre-Owned Car Mart.}
{87700}{}{Sign}
{87701}{}{This is the sign of the Water Merchants, a Hub trading company.}
{87800}{}{Egg Shell}
{87801}{}{Pieces of a broken egg shell.}
{87900}{}{Egg Shell}
{87901}{}{Pieces of a broken egg shell.}
{88000}{}{Egg Shell}
{88001}{}{Pieces of a broken egg shell.}
{88100}{}{Egg Shell}
{88101}{}{Pieces of a broken egg shell.}
{88200}{}{Egg Shell}
{88201}{}{Pieces of a broken egg shell.}
{88300}{}{Egg Shell}
{88301}{}{Pieces of a broken egg shell.}
{88400}{}{Egg Shell}
{88401}{}{Pieces of a broken egg shell.}
{88500}{}{Egg Shell}
{88501}{}{Pieces of a broken egg shell.}
{88600}{}{Lamp Post}
{88601}{}{A lamp post. It looks like it is in good working order.}
{88700}{}{Sign}
{88701}{}{The sign reads: Motel.}
{88800}{}{Table Planter}
{88801}{}{This table planter has been filled with dung, and some sort of vegetables or fungi are happily growing in it.}
{88900}{}{Table Planter}
{88901}{}{This table planter has been filled with dung, and some sort of vegetables or fungi are happily growing in it.}
{89000}{}{Skeleton}
{89100}{}{Sign}
{89101}{}{This sign reads: Jail.}
{89200}{}{Sign}
{89201}{}{Someone illiterate wrote this.}
{89300}{}{Sign}
{89301}{}{An advertisement for Blades-brand razor blades.}
{89400}{}{Shower}
{89401}{}{A fairly normal shower stall.}
{89500}{}{Shower}
{89501}{}{A fairly normal shower stall.}
{89600}{}{Sign}
{89601}{}{This is the sign of the Friendly Lending Company.}
{89700}{}{Sign}
{89701}{}{This is the sign of the Friendly Lending Company.}
{89800}{}{Poster}
{89801}{}{This is a movie poster for a horror film from pre-war days.}
{89900}{}{Poster}
{89901}{}{This is a movie poster for a horror film from pre-war days.}
{90000}{}{Bar}
{90001}{}{There is an urn sitting on this bar. The urn looks a little beat up, but might be valuable.}
{90100}{}{Elevator Shaft}
{90101}{}{The shaft has a rope hanging from above.}
{90200}{}{Elevator Shaft}
{90201}{}{The shaft has a rope hanging down from the edge.}
{90300}{}{Medical Bed}
{90301}{}{This bed has a built-in display for monitoring the patients progress.}
{90400}{}{Water Pump}
{90401}{}{This is a piece of machinery that pumps water up from below.}
{90500}{}{Medical Bed}
{90501}{}{This bed has a built-in display for monitoring the patients progress.}
{90600}{}{Power Armor Parts}
{90601}{}{These are parts to a suit of Power Armor.}
{90700}{}{Light}
{90701}{}{This security light is currently pulsating a bright red.}
{90800}{}{Light}
{90801}{}{This security light is currently pulsating a bright red.}
{90900}{}{Symbol}
{91000}{}{Symbol}
{91100}{}{Symbol}
{91200}{}{Symbol}
{91300}{}{Symbol}
{91400}{}{Symbol}
{91500}{}{Rope}
{91600}{}{Rope}
{91700}{}{Rope}
{91800}{}{Rope}
{91900}{}{Rope}
{92000}{}{Rope}
{92100}{}{Rope}
{92200}{}{Rope}
{92300}{}{Canyon}
{92301}{}{You can see hundreds of feet down into the valley floor.}
{92400}{}{Canyon}
{92401}{}{You can see hundreds of feet down into the valley floor.}
{92500}{}{Canyon}
{92501}{}{You can see hundreds of feet down into the valley floor.}
{92600}{}{Canyon}
{92601}{}{You can see hundreds of feet down into the valley floor.}
{92700}{}{Canyon}
{92701}{}{You can see hundreds of feet down into the valley floor.}
{92800}{}{Canyon}
{92801}{}{You can see hundreds of feet down into the valley floor.}
{92900}{}{Canyon}
{92901}{}{You can see hundreds of feet down into the valley floor.}
{93000}{}{Canyon}
{93001}{}{You can see hundreds of feet down into the valley floor.}
{93100}{}{Cave Floor}
{93200}{}{Wall}
{93201}{}{A tribal relief decorates the wall.}
{93300}{}{Destroyed Wall}
{93301}{}{The wall has been blown open.}
{93400}{}{Door}
{93401}{}{A door with an intricate lock.}
{93500}{}{Torch}
{93501}{}{A lit torch in a wall sconce.}
{93600}{}{Torch}
{93601}{}{A lit torch in a wall sconce.}
{93700}{}{Stone Monument}
{93800}{}{Stone Monument}
{93900}{}{Stone Monument}
{94000}{}{Skull Pole}
{94001}{}{A pole with human skulls attached.}
{94100}{}{Skull Pole}
{94101}{}{A pole with human skulls attached.}
{94200}{}{Skull Pole}
{94201}{}{A pole with human skulls attached.}
{94300}{}{Plant}
{94301}{}{}
{94400}{}{Plant}
{94500}{}{Tree}
{94600}{}{Tree}
{94700}{}{Tree}
{94800}{}{Bed}
{94900}{}{Bed}
{95000}{}{Hole}
{95001}{}{A suspicious hole in the wall.}
{95100}{}{Raised Stone Plate}
{95101}{}{A raised stone plate.}
{95200}{}{Disabled Stone Plate}
{95201}{}{A disabled stone plate.}
{95300}{}{Triggered Stone Plate}
{95301}{}{A triggered stone plate.}
{95400}{}{Door}
{95500}{}{Door}
{95600}{}{Door}
{95700}{}{Door}
{95800}{}{Door}
{95900}{}{Door}
{96000}{}{Door}
{96100}{}{Door}
{96200}{}{Door}
{96300}{}{Plant}
{96301}{}{A mutated cornstalk.}
{96400}{}{Plant}
{96401}{}{A mutated cornstalk.}
{96500}{}{Plant}
{96501}{}{A mutated cornstalk. This one is sick.}
{96600}{}{Plant}
{96601}{}{A mutated cornstalk.}
{96700}{}{Plant}
{96701}{}{A mutated cornstalk.}
{96800}{}{Plant}
{96801}{}{A mutated cornstalk.}
{96900}{}{Wood Support}
{97000}{}{Wood Support}
{97100}{}{Wood Support}
{97200}{}{Wood Support}
{97300}{}{Wood Support}
{97400}{}{Wood Support}
{97500}{}{Damaged Wood Support}
{97501}{}{This support looks like it could collapse if stressed.}
{97600}{}{Collapsed Floor}
{97601}{}{The stone floor has collapsed here into the lower level.}
{97700}{}{Ladder Down}
{97701}{}{A manmade hole with a ladder leading down.}
{97800}{}{Door}
{97900}{}{Wall}
{98000}{}{Reactor 5 Sign}
{98100}{}{Door}
{98200}{}{Door}
{98300}{}{Door}
{98400}{}{Door}
{98500}{}{Radioactive Goo}
{98600}{}{Radioactive Goo}
{98700}{}{Radioactive Goo}
{98800}{}{Radioactive Goo}
{98900}{}{Security Door}
{99000}{}{Vault Door}
{99100}{}{Utility Crane}
{99200}{}{Utility Crane}
{99300}{}{Well}
{99400}{}{Well}
{99500}{}{Outhouse}
{99600}{}{Hole}
{99601}{}{You can't see the bottom of this pit.}
{99700}{}{Floor Plate}
{99701}{}{You see a floor plate trap.}
{99800}{}{Disabled Floor Plate}
{99801}{}{This floor plate trap has been disabled.}
{99900}{}{Triggered Floor Plate}
{99901}{}{This floor plate trap has been triggered. Oops!}
{100000}{}{Still}
{100001}{}{This looks like a wood-burning alcohol still.}
{100100}{}{Rad Scorpion Parts}
{100101}{}{You see a large pile of radscorpion parts. They've been hollowed out and have straps attached to them.}
{100200}{}{Machinery}
{100201}{}{This is the Plutonium-Gamma Shield machine.}
{100300}{}{Machinery}
{100301}{}{This is the Jupiter Wave Compiler machine.}
{100400}{}{Machinery}
{100401}{}{This is the Uranium-Rod Driver machine.}
{100500}{}{Machinery}
{100501}{}{This is the Neptunium Impeller machine.}
{100600}{}{Machinery}
{100601}{}{This is the Saturn-Class Capacitor machine.}
{100700}{}{Pump Control}
{100701}{}{This is the coolant pumping machine.}
{100800}{}{Side of Brahmin}
{100900}{}{Car}
{101000}{}{Chrysalis Motors Car}
{101001}{}{This Chrysalis Motors Highwayman looks to be in pretty good shape for its age.}
{101100}{}{Car}
{101200}{}{Gravesite}
{101201}{}{A grave is located here.}
{101300}{}{Headstone}
{101301}{}{Headstone}
{101400}{}{Headstone}
{101401}{}{Headstone}
{101500}{}{Headstone}
{101501}{}{Headstone}
{101600}{}{Headstone}
{101601}{}{Headstone}
{101700}{}{Plow}
{101701}{}{This plow is designed to be dragged by a brahmin.}
{101800}{}{Plow}
{101801}{}{This plow is designed to be dragged by a brahmin.}
{101900}{}{Water}
{102000}{}{Sign}
{102001}{}{The entry sign for New Reno.}
{102100}{}{Sign}
{102101}{}{The entry sign for New Reno.}
{102200}{}{Sign}
{102201}{}{The entry sign for New Reno.}
{102300}{}{Sign}
{102301}{}{The entry sign for New Reno.}
{102400}{}{Sign}
{102401}{}{The entry sign for New Reno.}
{102500}{}{Sign}
{102501}{}{The entry sign for New Reno.}
{102600}{}{Shadow}
{102700}{}{Shadow}
{102800}{}{Shadow}
{102900}{}{Graffiti}
{103000}{}{Graffiti}
{103100}{}{Graffiti}
{103200}{}{Graffiti}
{103300}{}{Graffiti}
{103400}{}{Graffiti}
{103500}{}{Graffiti}
{103600}{}{Graffiti}
{103700}{}{Graffiti}
{103800}{}{Graffiti}
{103900}{}{Graffiti}
{104000}{}{Graffiti}
{104100}{}{Graffiti}
{104200}{}{Graffiti}
{104300}{}{Graffiti}
{104400}{}{Graffiti}
{104500}{}{Graffiti}
{104600}{}{Graffiti}
{104700}{}{Graffiti}
{104800}{}{Graffiti}
{104900}{}{Graffiti}
{105000}{}{Graffiti}
{105100}{}{Graffiti}
{105200}{}{Graffiti}
{105300}{}{Graffiti}
{105400}{}{Graffiti}
{105500}{}{Graffiti}
{105600}{}{Graffiti}
{105700}{}{Graffiti}
{105800}{}{Graffiti}
{105900}{}{Graffiti}
{106000}{}{Sign}
{106100}{}{Graffiti}
{106200}{}{Graffiti}
{106300}{}{Graffiti}
{106400}{}{Graffiti}
{106500}{}{Graffiti}
{106600}{}{Graffiti}
{106700}{}{Graffiti}
{106800}{}{Graffiti}
{106900}{}{Graffiti}
{107000}{}{Graffiti}
{107100}{}{Graffiti}
{107200}{}{Graffiti}
{107300}{}{Graffiti}
{107400}{}{Graffiti}
{107500}{}{Graffiti}
{107600}{}{Graffiti}
{107700}{}{Graffiti}
{107800}{}{Graffiti}
{107900}{}{Graffiti}
{108000}{}{Graffiti}
{108100}{}{Graffiti}
{108200}{}{Graffiti}
{108300}{}{Graffiti}
{108400}{}{Graffiti}
{108500}{}{Graffiti}
{108600}{}{Graffiti}
{108700}{}{Graffiti}
{108800}{}{Graffiti}
{108900}{}{Graffiti}
{109000}{}{Graffiti}
{109100}{}{Graffiti}
{109200}{}{Graffiti}
{109300}{}{Graffiti}
{109400}{}{Graffiti}
{109500}{}{Graffiti}
{109600}{}{Graffiti}
{109700}{}{Graffiti}
{109800}{}{Graffiti}
{109900}{}{Graffiti}
{110000}{}{Graffiti}
{110100}{}{Graffiti}
{110200}{}{Graffiti}
{110300}{}{Graffiti}
{110400}{}{Graffiti}
{110500}{}{Graffiti}
{110600}{}{Graffiti}
{110700}{}{Graffiti}
{110800}{}{Graffiti}
{110900}{}{Graffiti}
{111000}{}{Sign}
{111100}{}{Sign}
{111200}{}{Sign}
{111300}{}{Sign}
{111400}{}{Sign}
{111500}{}{Sign}
{111600}{}{Sign}
{111700}{}{Sign}
{111800}{}{Wallpaper}
{111900}{}{Wallpaper}
{112000}{}{Wallpaper}
{112100}{}{Wallpaper}
{112200}{}{Wallpaper}
{112300}{}{Wallpaper}
{112400}{}{Wallpaper}
{112500}{}{Wallpaper}
{112600}{}{Wallpaper}
{112700}{}{Wallpaper}
{112800}{}{Wallpaper}
{112900}{}{Wallpaper}
{113000}{}{Wallpaper}
{113100}{}{Wallpaper}
{113200}{}{Wallpaper}
{113300}{}{Wallpaper}
{113400}{}{Wallpaper}
{113500}{}{Wallpaper}
{113600}{}{Wallpaper}
{113700}{}{Wallpaper}
{113800}{}{Wallpaper}
{113900}{}{Wallpaper}
{114000}{}{Wallpaper}
{114100}{}{Movie Camera}
{114200}{}{Coffin}
{114300}{}{Coffin}
{114400}{}{Coffin}
{114500}{}{Coffin}
{114600}{}{Steel Bars}
{114700}{}{Steel Bars}
{114800}{}{Steel Window Cover}
{114900}{}{Steel Window Cover}
{115000}{}{Laser Tripwire}
{115100}{}{Laser Tripwire}
{115200}{}{Mining Cart}
{115300}{}{Mining Cart with Steel Pole}
{115400}{}{Mining Cart with Dynamite}
{115500}{}{"Out of Business" Sign}
{115600}{}{"Out of Business" Sign}
{115700}{}{Buckner House Sign}
{115800}{}{Vic's Sign}
{115900}{}{Wall}
{116000}{}{Wall}
{116100}{}{Retinal Scanner}
{116101}{}{This is a security device that scans a person's retinal pattern.}
{116200}{}{Control Room Sign}
{116300}{}{Control Room Sign}
{116400}{}{Control Room Sign}
{116500}{}{Construction Zone Sign}
{116600}{}{Construction Zone Sign}
{116700}{}{Machine}
{116701}{}{A non-functional machine.}
{116800}{}{Machine}
{116801}{}{A non-functional machine.}
{116900}{}{Door}
{117000}{}{Door}
{117100}{}{Pipes}
{117101}{}{A set of pipes going into the reactor.}
{117200}{}{Tank}
{117300}{}{Tanks}
{117400}{}{Tanks}
{117500}{}{Tanks}
{117600}{}{Vent}
{117700}{}{Vent}
{117800}{}{Harp Sign}
{117900}{}{Sawhorse}
{118000}{}{Sawhorse}
{118100}{}{Sawhorse}
{118200}{}{Vent}
{118300}{}{Vent}
{118400}{}{Machine Shop Sign}
{118500}{}{Manager's Office Sign}
{118600}{}{Supply Room Sign}
{118700}{}{Radiation Warning Sign}
{118800}{}{Steam}
{118900}{}{Machine}
{118901}{}{A miscellaneous piece of equipment for the power plant.}
{119000}{}{Tank}
{119100}{}{Fire}
{119200}{}{Water}
{119300}{}{Trapper Town Sign}
{119400}{}{Golden Gecko Sign}
{119500}{}{Bath House Sign}
{119600}{}{Cave Art}
{119700}{}{Cave Art}
{119800}{}{Cave Art}
{119900}{}{Cave Art}
{120000}{}{Firepit}
{120100}{}{Cave Wall}
{120200}{}{Cave Wall}
{120300}{}{Cave Wall}
{120400}{}{Cave Wall}
{120500}{}{Cave Wall}
{120600}{}{Cave Wall}
{120700}{}{Cave Wall}
{120800}{}{Cave Wall}
{120900}{}{Cave Wall}
{121000}{}{Cave Wall}
{121100}{}{Cave Wall}
{121200}{}{Cave Wall}
{121300}{}{Cave Wall}
{121400}{}{Cave Wall}
{121500}{}{Cave Wall}
{121600}{}{Stake}
{121601}{}{This stake appears to have a person impaled on the top!}
{121700}{}{Stake}
{121701}{}{This stake appears to have a person impaled on the top!}
{121800}{}{Stake}
{121801}{}{This stake appears to have a person impaled on the top!}
{121900}{}{Stake}
{121901}{}{This stake appears to have a person impaled on the top!}
{122000}{}{Stake}
{122001}{}{This stake appears to have a person impaled on the top!}
{122100}{}{Stake}
{122101}{}{This stake appears to have a person impaled on the top!}
{122200}{}{Stake}
{122201}{}{This stake appears to have a human skull placed on the top.}
{122300}{}{Stake}
{122301}{}{This stake appears to have a human skull placed on the top.}
{122400}{}{Stake}
{122401}{}{This empty stake looks ready for an unwilling victim.}
{122500}{}{Stake}
{122501}{}{This empty stake looks ready for an unwilling victim.}
{122600}{}{Stake}
{122601}{}{This empty stake looks ready for an unwilling victim.}
{122700}{}{Stake}
{122701}{}{This empty stake looks ready for an unwilling victim.}
{122800}{}{Wanted Sign}
{122801}{}{The picture on this sign looks oddly like you!}
{122900}{}{Floor}
{123000}{}{Deactivated Robobrain}
{123001}{}{An incomplete cybernetic body that is missing several parts.}
{123100}{}{Howitzer}
{123101}{}{This strange looking cannon looks like a relic from the pre-war days. You wonder how it ended up here.}
{123200}{}{Sign}
{123300}{}{Sign}
{123400}{}{Sign}
{123500}{}{Sign}
{123600}{}{Power Switch}
{123700}{}{Cross}
{123800}{}{Cross}
{123900}{}{Cross}
{124000}{}{Cross}
{124100}{}{Cross}
{124200}{}{Cross}
{124300}{}{Gas Pump}
{124400}{}{Gas Pump}
{124500}{}{Gas Pump}
{124600}{}{Pep Gas Sign}
{124700}{}{Sign Shadow}
{124800}{}{Haybed}
{124900}{}{Haybed}
{125000}{}{Haybed}
{125100}{}{Haybed}
{125200}{}{Haybed}
{125300}{}{Haybed}
{125400}{}{Dusty's Cantina Sign}
{125500}{}{Son of Bob's Store}
{125501}{}{A street vendor's stand.}
{125600}{}{Son of Bob's Store}
{125601}{}{A street vendor's stand.}
{125700}{}{Son of Bob's Store}
{125701}{}{A street vendor's stand.}
{125800}{}{Son of Bob's Store}
{125801}{}{A street vendor's stand.}
{125900}{}{NCR Sign}
{126000}{}{Hall of Congress Sign}
{126100}{}{Hall of Congress Sign}
{126200}{}{NCR Poster}
{126300}{}{NCR Poster}
{126400}{}{NCR Poster}
{126500}{}{NCR Poster}
{126600}{}{Rawhide Saloon Sign}
{126700}{}{Casino Sign}
{126800}{}{Casino Sign}
{126900}{}{Casino Sign}
{127000}{}{Casino Sign}
{127100}{}{Casino Sign}
{127200}{}{Casino Sign}
{127300}{}{Pile of Rocks}
{127301}{}{These rocks appear to be keeping something in.}
{127400}{}{Beam}
{127500}{}{Beam}
{127600}{}{Beam}
{127700}{}{Beam}
{127800}{}{Beam}
{127900}{}{Beam}
{128000}{}{Beam}
{128100}{}{Beam}
{128200}{}{Beam}
{128300}{}{Beam}
{128400}{}{Shadow}
{128500}{}{Shadow}
{128600}{}{Shadow}
{128700}{}{Shadow}
{128800}{}{Shadow}
{128900}{}{Shadow}
{129000}{}{Shadow}
{129100}{}{Shadow}
{129200}{}{Shadow}
{129300}{}{Elevator Stub}
{129400}{}{Gas Pump}
{129500}{}{Gas Pump}
{129600}{}{Gas Pump}
{129700}{}{Rope}
{129800}{}{Hole}
{129900}{}{Brahmin Meat}
{130000}{}{Brahmin Meat}
{130100}{}{Brahmin Meat}
{130200}{}{Brahmin Meat}
{130300}{}{Brahmin Meat}
{130400}{}{Brahmin Meat}
{130500}{}{Beam}
{130600}{}{Beam}
{130700}{}{Beam}
{130800}{}{Beam}
{130900}{}{Beam}
{131000}{}{Beam}
{131100}{}{Beam}
{131200}{}{Beam}
{131300}{}{Shadow}
{131400}{}{Shadow}
{131500}{}{Shadow}
{131600}{}{Shadow}
{131700}{}{Shadow}
{131800}{}{Shadow}
{131900}{}{Shadow}
{132000}{}{Shadow}
{132100}{}{Blood}
{132200}{}{Blood}
{132300}{}{Blood}
{132400}{}{Blood}
{132500}{}{Blood}
{132600}{}{Blood}
{132700}{}{Blood with Bones}
{132800}{}{Blood with Bones}
{132900}{}{Blood with Bones}
{133000}{}{Cave Mouth}
{133100}{}{Equipment Access}
{133200}{}{Equipment Access}
{133300}{}{Equipment Access}
{133400}{}{Equipment Access}
{133500}{}{Computer}
{133501}{}{A Vault computer terminal, hooked into the main Vault computer.}
{133600}{}{Computer}
{133601}{}{A Vault computer terminal, hooked into the main Vault computer.}
{133700}{}{Hoover Dam Gate}
{133800}{}{Hoover Dam Gate}
{133900}{}{Wall}
{134000}{}{Wall}
{134100}{}{Wall}
{134200}{}{Wall}
{134300}{}{Wall}
{134400}{}{Wall}
{134500}{}{Wall}
{134600}{}{Wall}
{134700}{}{Door}
{134800}{}{Blown Open Door}
{134900}{}{Door Debris}
{135000}{}{Building}
{135100}{}{Building}
{135200}{}{Building}
{135300}{}{Building}
{135400}{}{Building}
{135500}{}{Building}
{135600}{}{Building}
{135700}{}{Building}
{135800}{}{Door}
{135900}{}{Temple}
{136000}{}{Temple}
{136100}{}{Temple}
{136200}{}{Temple}
{136300}{}{Temple}
{136400}{}{Temple}
{136500}{}{Firepit}
{136600}{}{Firepit}
{136700}{}{Howitzer}
{136701}{}{This strange looking cannon looks like a relic from the pre-war days. You wonder how it ended up here.}
{136800}{}{Temple}
{136900}{}{Shadow}
{137000}{}{Mountain}
{137100}{}{Cavern}
{137200}{}{Door Track}
{137300}{}{Torch}
{137301}{}{A lit torch in a wall sconce.}
{137400}{}{Torch}
{137401}{}{A lit torch in a wall sconce.}
{137500}{}{Torch}
{137501}{}{A lit torch in a wall sconce.}
{137600}{}{Torch}
{137601}{}{A lit torch in a wall sconce.}
{137700}{}{Vertibird}
{137701}{}{NEED LONG DESCRIPTION.}
{137800}{}{Destroyed Door}
{137801}{}{The power station door is destroyed.}
{137900}{}{Destroyed Door}
{137901}{}{The power station door is destroyed.}
{138000}{}{Wall}
{138100}{}{Wall}
{138200}{}{Wall}
{138300}{}{Wall}
{138400}{}{Wall}
{138500}{}{Wall}
{138600}{}{Light}
{138700}{}{Door}
{138800}{}{Door}
{138900}{}{Door}
{139000}{}{Door}
{139100}{}{Door}
{139200}{}{Door}
{139300}{}{Banner}
{139400}{}{Post}
{139500}{}{Post}
{139600}{}{Banner}
{139700}{}{Banner}
{139800}{}{Post}
{139900}{}{Post}
{140000}{}{Banner}
{140100}{}{Shadow}
{140200}{}{Shadow}
{140300}{}{Banner}
{140400}{}{Banner}
{140500}{}{Banner}
{140600}{}{Banner}
{140700}{}{Cat's Paw Sign}
{140800}{}{Cat's Paw Sign}
{140900}{}{Sign}
{141000}{}{Jungle Gym Sign}
{141100}{}{Jungle Gym Sign}
{141200}{}{Jungle Gym Sign}
{141300}{}{Renesco's Pharmacy Sign}
{141400}{}{New Reno Arms Sign}
{141500}{}{Salvatore's Bar Sign}
{141600}{}{Statue}
{141700}{}{Warehouse Door}
{141800}{}{Warehouse Door}
{141900}{}{Doc Johnson Sign}
{142000}{}{Sheriff Sign}
{142100}{}{Malamute Saloon Sign}
{142200}{}{Morningstar Mine Sign}
{142300}{}{Kokowebe Mine Sign}
{142400}{}{Kokowebe Mine Sign}
{142500}{}{Kokowebe Mine Sign}
{142600}{}{Signpost}
{142601}{}{This wooden sign points towards New Reno and "Hell." You suspect the directions are reversed.}
{142700}{}{Number 1 Sign}
{142800}{}{Number 2 Sign}
{142900}{}{Number 3 Sign}
{143000}{}{Number 4 Sign}
{143100}{}{Number 5 Sign}
{143200}{}{Number 6 Sign}
{143300}{}{Rope}
{143301}{}{You can climb over the wall with this rope.}
{143400}{}{Door}
{143500}{}{Door}
{143600}{}{Window}
{143700}{}{Window}
{143800}{}{Window}
{143900}{}{Window}
{144000}{}{Window}
{144100}{}{Window}
{144200}{}{Window}
{144300}{}{Window}
{144400}{}{Window}
{144500}{}{Window}
{144600}{}{Window}
{144700}{}{Window}
{144800}{}{Pool Ladder}
{144900}{}{Door}
{145000}{}{Arch}
{145100}{}{Arch}
{145200}{}{Arch}
{145300}{}{Arch}
{145400}{}{Arch}
{145500}{}{Arch}
{145600}{}{Arch}
{145700}{}{Arch}
{145800}{}{Shadow}
{145900}{}{Shadow}
{146000}{}{Shadow}
{146100}{}{Arch}
{146200}{}{Arch}
{146300}{}{Arch}
{146400}{}{Shadow}
{146500}{}{Shadow}
{146600}{}{Fence Door}
{146700}{}{Fence Door}
{146800}{}{Command Seat}
{146801}{}{This is where the Overseer normally sits.}
{146900}{}{Chasm}
{146901}{}{You could descend but aren't exactly sure how. Maybe with some additional support and a thick rope.}
{147000}{}{Chasm}
{147001}{}{You could descend but aren't exactly sure how. Maybe with some additional support and a thick rope.}
{147100}{}{Chasm}
{147101}{}{You could descend but aren't exactly sure how. Maybe with some additional support and a thick rope.}
{147200}{}{Chasm}
{147201}{}{You could descend but aren't exactly sure how. Maybe with some additional support and a thick rope.}
{147300}{}{Casino Entrance}
{147400}{}{Casino Entrance}
{147500}{}{Carpet}
{147600}{}{Casino Entrance}
{147700}{}{Casino Entrance}
{147800}{}{Casino Entrance}
{147900}{}{Casino Door}
{148000}{}{Casino Door}
{148100}{}{Casino Entrance}
{148200}{}{Casino Entrance}
{148300}{}{Casino Entrance}
{148400}{}{Casino Entrance}
{148500}{}{Casino Entrance}
{148600}{}{Casino Entrance}
{148700}{}{Casino Entrance}
{148800}{}{Casino Entrance}
{148900}{}{Casino Entrance}
{149000}{}{Casino Entrance}
{149100}{}{Casino Door}
{149200}{}{Casino Door}
{149300}{}{Wall Light}
{149400}{}{Wall Light}
{149500}{}{Wall Light}
{149600}{}{Wall Light}
{149700}{}{Wall Light}
{149800}{}{Wall}
{149900}{}{Wall}
{150000}{}{Fan}
{150100}{}{Fan}
{150200}{}{Fire Ext.}
{150300}{}{Fire Ext.}
{150400}{}{Pipe}
{150500}{}{Power Distributor}
{150600}{}{Power Distributor}
{150700}{}{Wall}
{150800}{}{Wall}
{150900}{}{Wall}
{151000}{}{Wall}
{151100}{}{Wall}
{151200}{}{Wall}
{151300}{}{Wall}
{151400}{}{Wall}
{151500}{}{Wall}
{151600}{}{Wood Paneling}
{151700}{}{Wood Paneling}
{151800}{}{Pipe}
{151900}{}{Pipe}
{152000}{}{Pipe}
{152100}{}{Pipe}
{152200}{}{Pipe}
{152300}{}{Pipe}
{152400}{}{Pipe}
{152500}{}{Pipe}
{152600}{}{Pipe}
{152700}{}{Pipe}
{152800}{}{Pipe}
{152900}{}{Air Vent}
{153000}{}{Air Vent}
{153100}{}{Door}
{153200}{}{Door}
{153300}{}{Door}
{153400}{}{Door}
{153500}{}{Door}
{153600}{}{Door}
{153700}{}{Shower}
{153800}{}{Shuttle Wall}
{153900}{}{Shuttle Wall}
{154000}{}{Shuttle Wall}
{154100}{}{Shuttle Wall}
{154200}{}{Shuttle Wall}
{154300}{}{Shuttle Wall}
{154400}{}{Shuttle Wall}
{154500}{}{Shuttle Wall}
{154600}{}{Shuttle Wall}
{154700}{}{Shuttle Wall}
{154800}{}{Forcefield}
{154900}{}{Forcefield}
{155000}{}{Organ Extraction Unit}
{155001}{}{The latest model in Vault-Tec's "Do It Yourself" surgery series. Removes organs automatically with the press of a button.}
{155100}{}{Shuttle}
{155200}{}{Shuttle}
{155300}{}{Shuttle}
{155400}{}{Shuttle}
{155500}{}{Shuttle}
{155600}{}{Shuttle}
{155700}{}{Shuttle}
{155800}{}{Shuttle}
{155900}{}{Shuttle}
{156000}{}{Shuttle}
{156100}{}{Shuttle}
{156200}{}{Shuttle}
{156300}{}{Shuttle}
{156400}{}{Shuttle}
{156500}{}{Shuttle}
{156600}{}{Shadow}
{156700}{}{Shadow}
{156800}{}{Shadow}
{156900}{}{Shadow}
{157000}{}{Shadow}
{157100}{}{Shadow}
{157200}{}{Throne}
{157300}{}{Door}
{157400}{}{Door}
{157500}{}{Door}
{157600}{}{Door}
{157700}{}{Air Vent}
{157800}{}{Auto-Doc}
{157801}{}{This Auto-Doc is designed to heal illnesses and administer various drugs.}
{157900}{}{Statue}
{157901}{}{A small statue of the famous Vault Dweller.}
{158000}{}{Pile of Rocks}
{158100}{}{Forcefield}
{158101}{}{An energy field is blocking your path.}
{158200}{}{Forcefield}
{158201}{}{An energy field is blocking your path.}
{158300}{}{Forcefield}
{158301}{}{An energy field is blocking your path.}
{158400}{}{Forcefield}
{158401}{}{An energy field is blocking your path.}
{158500}{}{Tanker}
{158600}{}{Tanker}
{158700}{}{Tanker}
{158800}{}{Tanker}
{158900}{}{Tanker}
{159000}{}{Tanker}
{159100}{}{Tanker}
{159200}{}{Tanker}
{159300}{}{Tanker}
{159400}{}{Tanker}
{159500}{}{Tanker}
{159600}{}{Tanker}
{159700}{}{Tanker}
{159800}{}{Tanker}
{159900}{}{Tanker}
{160000}{}{Wall}
{160100}{}{Wall}
{160200}{}{Floor Depression}
{160300}{}{Stone Bench}
{160400}{}{Stone Bench}
{160500}{}{Incense Burner}
{160600}{}{Satellite Dish}
{160700}{}{Satellite Dish}
{160800}{}{Shadow}
{160900}{}{Dock Shadow}
{161000}{}{Dock Shadow}
{161100}{}{Dock Shadow}
{161200}{}{Dock Shadow}
{161300}{}{Beam}
{161400}{}{Beam}
{161500}{}{Dock Shadow}
{161600}{}{Dock Shadow}
{161700}{}{Dock Shadow}
{161800}{}{Dock Shadow}
{161900}{}{Stairs}
{162000}{}{Deactivated Cyberdog}
{162001}{}{You see a deactivated Cyberdog.}
{162100}{}{Destroyed Power Generator}
{162101}{}{You see a destroyed power generator.}
{162200}{}{Track}
{162300}{}{Track}
{162400}{}{Track}
{162500}{}{Mine Cart}
{162600}{}{Mine Cart with Steel Pole}
{162700}{}{Mine Cart with Dynamite}
{162800}{}{Destroyed Mine Cart}
{162900}{}{Mine Cart}
{163000}{}{Pool Table}
{163100}{}{Pool Table}
{163200}{}{Pool Table}
{163300}{}{Pool Table}
{163400}{}{Pool Table}
{163500}{}{Pool Table}
{163600}{}{Desk}
{163700}{}{Flag}
{163800}{}{Wall}
{163900}{}{Wall}
{164000}{}{Wall}
{164100}{}{Wall}
{164200}{}{Exhaust Port}
{164300}{}{Desk}
{164400}{}{Desk}
{164500}{}{Stairs Down}
{164600}{}{Stairs Up}
{164700}{}{Stairs Up}
{164800}{}{Stairs Up}
{164900}{}{Mainframe Computer}
{165000}{}{Mainframe Computer}
{165100}{}{Mainframe Computer}
{165200}{}{Caravan Office Sign}
{165300}{}{Coffin Table}
{165400}{}{Coffin Table}
{165500}{}{Mine Elevator}
{165600}{}{Mine Elevator}
{165700}{}{Flagpole}
{165800}{}{NCR Flag}
{165900}{}{Poseidon Gasoline Sign}
{166000}{}{Stairs Down}
{166100}{}{Clinic Sign}
{166200}{}{Corrections Center Sign}
{166300}{}{Customs Sign}
{166400}{}{Customs Sign}
{166500}{}{Greeting Office Sign}
{166600}{}{Happy Harry's Sign}
{166700}{}{The Hole Sign}
{166800}{}{Information Center Sign}
{166900}{}{Information Center Sign}
{167000}{}{Vault City Logo}
{167100}{}{Main Council Sign}
{167200}{}{Main Council Sign}
{167300}{}{Maintenance Center}
{167400}{}{Parlor Room Sign}
{167500}{}{Tap House Sign}
{167600}{}{Westin Ranch Sign}
{167700}{}{Amenities Sign}
{167800}{}{Building A Sign}
{167900}{}{Building B Sign}
{168000}{}{Servant Allocation Center}
{168100}{}{Servant Allocation Center}
{168200}{}{Amenities Office Sign}
{168300}{}{Amenities Office Sign}
{168400}{}{Mine Elevator}
{168500}{}{Mine Elevator}
{168600}{}{Mine Elevator}
{168700}{}{Mine Elevator}
{168800}{}{Vertibird}
{168801}{}{You've never seen an aircraft before. It scares you but also makes you wonder how it feels flying like a bird.}
{168900}{}{Vertibird}
{168901}{}{You've never seen an aircraft before. It scares you but also makes you wonder how it feels flying like a bird.}
{169000}{}{Vertibird}
{169001}{}{You've never seen an aircraft before. It scares you but also makes you wonder how it feels flying like a bird.}
{169100}{}{Vertibird}
{169101}{}{You've never seen an aircraft before. It scares you but also makes you wonder how it feels flying like a bird.}
{169200}{}{Vertibird}
{169201}{}{You've never seen an aircraft before. It scares you but also makes you wonder how it feels flying like a bird.}
{169300}{}{Shadow}
{169400}{}{Shadow}
{169500}{}{Shadow}
{169600}{}{Shadow}
{169700}{}{Vertibird Wreckage}
{169701}{}{You wonder why it was abandoned. There are no bodies or valuables inside the wreckage.}
{169800}{}{Vertibird Wreckage}
{169801}{}{You wonder why it was abandoned. There are no bodies or valuables inside the wreckage.}
{169900}{}{Vertibird Wreckage}
{169901}{}{You wonder why it was abandoned. There are no bodies or valuables inside the wreckage.}
{170000}{}{Vertibird Wreckage}
{170001}{}{You wonder why it was abandoned. There are no bodies or valuables inside the wreckage.}
{170100}{}{Vertibird Wreckage}
{170101}{}{You wonder why it was abandoned. There are no bodies or valuables inside the wreckage.}
{170200}{}{Vertibird Wreckage}
{170201}{}{You wonder why it was abandoned. There are no bodies or valuables inside the wreckage.}
{170300}{}{Shadow}
{170400}{}{Shadow}
{170500}{}{Shadow}
{170600}{}{Destroyed Bridge}
{170601}{}{You see what's left of the hanging bridge. There's no way back now.}
{170700}{}{Destroyed Bridge}
{170701}{}{You see what's left of the hanging bridge. There's no way back now.}
{170800}{}{Canyon}
{170900}{}{Door}
{171000}{}{Door}
{171100}{}{Wall}
{171200}{}{Wall}
{171300}{}{Wall}
{171400}{}{Wall}
{171500}{}{Wall}
{171600}{}{Wall}
{171700}{}{Wall}
{171800}{}{Wall}
{171900}{}{Air Vent}
{172000}{}{Air Vent}
{172100}{}{Bullet Proof Glass}
{172101}{}{Completely unbreakable glass. Don't even try.}
{172200}{}{Bullet Proof Glass}
{172201}{}{Completely unbreakable glass. Don't even try.}
{172300}{}{Bullet Proof Glass}
{172301}{}{Completely unbreakable glass. Don't even try.}
{172400}{}{Heavy Laser Turret}
{172500}{}{Heavy Laser Turret}
{172600}{}{Rocks}
{172700}{}{Rocks}
{172800}{}{Rocks}
{172900}{}{Rocks}
{173000}{}{Rocks}
{173100}{}{Rocks}
{173200}{}{Rocks}
{173300}{}{Rocks}
{173400}{}{Rocks}
{173500}{}{Rocks}
{173600}{}{Rocks}
{173700}{}{Becky's Casino Sign}
{173800}{}{Becky's Sign}
{173900}{}{Last Gasp Saloon Sign}
{174000}{}{Mom's Diner Sign}
{174100}{}{Slaver's Guild Sign}
{174200}{}{Survival/Gear Locker Sign}
{174300}{}{Tubby's Sign}
{174400}{}{Tubby's Sign}
{174500}{}{Mine Elevator Gate}
{174600}{}{Fan}
{174700}{}{Fan}
{174800}{}{President's Office Door}
{174900}{}{Eye Chart}
{175000}{}{Ruins}
{175100}{}{Guardian of Forever}
{175200}{}{Out of Order Sign}
{175300}{}{Collapsed Floor}
{175400}{}{Toilet}
{175500}{}{Cross}
{175600}{}{Wall}
{175700}{}{Wall}
{175800}{}{Wall}
{175900}{}{Wall}
{176000}{}{Wall}
{176100}{}{Wall}
{176200}{}{Wall}
{176300}{}{Wall}
{176400}{}{Building}
{176500}{}{Building}
{176600}{}{Building}
{176700}{}{Building}
{176800}{}{Building}
{176900}{}{Building}
{177000}{}{Steel Supports}
{177100}{}{Steel Supports}
{177200}{}{Steel Supports}
{177300}{}{Water}
{177400}{}{Water}
{177500}{}{Water}
{177600}{}{Water}
{177700}{}{Water}
{177800}{}{Water}
{177900}{}{Waterfall}
{178000}{}{Road}
{178100}{}{Road}
{178200}{}{Road}
{178300}{}{Road}
{178400}{}{Road}
{178500}{}{Road}
{178600}{}{Road}
{178700}{}{Bridge Support}
{178800}{}{Bridge Support}
{178900}{}{Bridge Support}
{179000}{}{Fence}
{179100}{}{Lamp}
{179200}{}{Lamp}
{179300}{}{Dead Whale}
{179301}{}{This whale appeared to have fallen from a great height.}
{179400}{}{Dead Whale}
{179401}{}{This whale appeared to have fallen from a great height.}
{179500}{}{Whale Fin}
{179501}{}{The fin of a dead whale.}
{179600}{}{Whale Eye}
{179601}{}{The eye of a dead whale.}
{179700}{}{Whale Chunk}
{179701}{}{A chunk of whale!}
{179800}{}{Whale Chunk}
{179801}{}{A chunk of whale!}
{179900}{}{Whale Chunk}
{179901}{}{A chunk of whale!}
{180000}{}{Whale Chunk}
{180001}{}{A chunk of whale!}
{180100}{}{Whale Chunk}
{180101}{}{A chunk of whale!}
{180200}{}{Boss Legs}
{180300}{}{Rocks}
{180400}{}{Rocks}
{180500}{}{Rocks}
{180600}{}{Rocks}
{180700}{}{Tannery Sign}
{180800}{}{Rose's B&B Sign}
{180900}{}{Vortis Holding Sign}
{181000}{}{Vortis Holding Sign}
{181100}{}{Great Wamamingo Mine Sign}
{181200}{}{Ascorti's Sign}
{181300}{}{Crashed Shuttle}
{181301}{}{A space vehicle of some kind. It looks like it crashed here recently.}
{181400}{}{Coffin}
{181500}{}{Stockman's Assoc. Sign}
{181600}{}{Slaughter-House Sign}
{181700}{}{Plank}
{181800}{}{Wood Door}
{181900}{}{Wood Door}
{182000}{}{Cola Fridge}
{182100}{}{Cola Fridge}
{182200}{}{Stove}
{182300}{}{Stove}
{182400}{}{Stove}
{182500}{}{Stove}
{182600}{}{Stuff}
{182700}{}{Stuff}
{182800}{}{Stuff}
{182900}{}{Stuff}
{183000}{}{Stuff}
{183100}{}{Stuff}
{183200}{}{Stuff}
{183300}{}{Stuff}
{183400}{}{Chair}
{183500}{}{Stairs}
{183600}{}{World Map}
{183700}{}{Situation Map}
{183800}{}{War Room Table}
{183900}{}{Council Room Table}
{184000}{}{Council Room Table}
{184100}{}{War Room Table}
{184200}{}{Tree}
{184300}{}{Tree}
{184400}{}{Ramp}
{184500}{}{Golden Globes Porn Sign}
{184600}{}{Ship Wheel}
{184700}{}{Ship Speed Control}
{184800}{}{Comm Station}
{184900}{}{Computer Console}
{185000}{}{Viewport Shutters}
{185100}{}{Steam}
{185200}{}{Nest}
{185300}{}{Army Truck}
{185400}{}{Sign}
{185500}{}{Army Truck}
{185600}{}{Stairs}
{185700}{}{Stairs}
{185800}{}{Stairs}
{185900}{}{Stairs}
{186000}{}{Stairs}
{186100}{}{Stairs}
{186200}{}{Stairs}
{186300}{}{Hotel Sign}
{186301}{}{You wonder what a "HOTEL" is.}
{186400}{}{Ladder}
{186401}{}{A short catwalk for ladder access and support.}
{186500}{}{Monitor}
{186600}{}{Brick}
{186601}{}{It's just a brick.}
{186700}{}{Fan}
{186701}{}{An old, noisy fan.}
{186800}{}{Bone}
{186801}{}{A bleached bone. You suspect that its owner could have been a human.}
{186900}{}{Bone}
{186901}{}{A bleached bone. You suspect that its owner could have been a human.}
{187000}{}{Bone}
{187001}{}{A bleached bone. You suspect that its owner could have been a human.}
{187100}{}{Bones}
{187101}{}{Bleached bones of some unfortunate soul.}
{187200}{}{Bones}
{187201}{}{Bleached bones of some unfortunate soul.}
{187300}{}{Bones}
{187301}{}{Bleached bones of some unfortunate soul.}
{187400}{}{Bones}
{187401}{}{Bleached bones of some unfortunate soul.}
{187500}{}{Bones}
{187501}{}{Bleached bones of some unfortunate soul.}
{187600}{}{Bones}
{187601}{}{Bleached bones of some unfortunate soul.}
{187700}{}{Bones}
{187701}{}{Bleached bones of some unfortunate soul.}
{187800}{}{Bones}
{187801}{}{Bleached bones of some unfortunate soul.}
{187900}{}{Bones}
{187901}{}{Bleached bones of some unfortunate soul.}
{188000}{}{Barrier}
{188001}{}{A concrete barrier.}
{188100}{}{Barrier}
{188101}{}{A concrete barrier.}
{188200}{}{Heap of Tires}
{188201}{}{A heap of ancient rubber tires. They have vulcanized and hardened, probably due to the heat.}
{188300}{}{Sign}
{188301}{}{There's still some life left in this old Poseidon Oil sign.}
{188400}{}{Tank}
{188401}{}{A tank filled with sinister looking green goo.}
{188500}{}{Vault Door}
{188501}{}{A heavy door, constructed to survive all sorts of damage and trauma.}
{188600}{}{Vault 8 Outer Door}
{188601}{}{This blast door is much, MUCH bigger than the standard. It seems that this Vault is special.}
{188700}{}{Power Generator}
{188800}{}{Power Generator}
{188900}{}{Vault Door}
{188901}{}{A heavy door, constructed to survive all sorts of damage and trauma.}
{189000}{}{Mountain}
{189100}{}{Mountain}
{189200}{}{Mountain}
{189300}{}{Mountain}
{189400}{}{Wall}
{189500}{}{Wall}
{189600}{}{Wall}
{189700}{}{Ladder}
{189701}{}{A short catwalk for ladder access and support.}
{189800}{}{Rock}
{189900}{}{Rock}
{190000}{}{Rock}
{190100}{}{Rock}
{190200}{}{Rock}
{190300}{}{Wall}
{190400}{}{Pipe}
{190401}{}{A pipe. You are certain that it is broken.}
{190500}{}{Hoop}
{190600}{}{Hoop}
{190700}{}{Electric Chair}
{190800}{}{Flies}
{190801}{}{You barely noticed the tiny flies.}
{190900}{}{Rubble}
{191000}{}{Rubble}
{191100}{}{Magik's Twin Stars Sign}
{191200}{}{Access Door? Air Intake Panel? You're not sure}
{191201}{}{It seems you could squeeze inside if you wanted to.}
{191300}{}{Security Door}
{191301}{}{This door looks very secure. It provides protection from the outside world elements and dangerous creatures.}
{191400}{}{Boot}
{191401}{}{This boot has really been worn out. Not that you would wear it or anything. You don't know where it's been.}
{191500}{}{Machine}
{191600}{}{Mr. Nixon Mascot}
{191601}{}{You see a mascot with a big red nose. For some reason, you don't trust this seemingly-innocent doll.}
{191700}{}{Benny the Mascot}
{191701}{}{It's Benny, the fastest delivery boy in town!}
{191800}{}{Belt}
{191801}{}{A deflated life-saving belt.}
{191900}{}{Bicycle}
{192000}{}{Vault Boy Mascot}
{192001}{}{You've seen this little fella before. It's Vault-Tec's mascot, Vault Boy.}
{192100}{}{Vault Boy Mascot}
{192101}{}{It's Vault Boy, Vault-Tec's mascot. This one has seen better days.}
{192200}{}{Vault Boy Mascot}
{192201}{}{It's Vault Boy, Vault-Tec's mascot. This one has seen better days.}
{192300}{}{Doll Head}
{192301}{}{This doll has a blonde hair.}
{192400}{}{Stool}
{192401}{}{A sturdy wooden stool.}
{192500}{}{Poster}
{192600}{}{Table}
{192601}{}{Somebody fixed the smashed door and turned it into a table.}
{192700}{}{Tank}
{192701}{}{A steel tank with "O2" written on it.}
{192800}{}{Banner}
{192900}{}{Banner}
{193000}{}{Engine}
{193100}{}{Sign}
{193101}{}{An ad for a pre-war TV series. Or so you think.}
{193200}{}{Sign}
{193201}{}{An ad for a pre-war TV series. Or so you think.}
{193300}{}{Wheel}
{193400}{}{Casino Table}
{193500}{}{Graffiti}
{193600}{}{Graffiti}
{193700}{}{Bowling Ball}
{193800}{}{Bowling Ball}
{193900}{}{Bowling Ball}
{194000}{}{Books}
{194100}{}{Books}
{194200}{}{Books}
{194300}{}{Drumkit}
{194301}{}{A set of semi-pro PowerBeat drums.}
{194400}{}{Flight Control Console}
{194500}{}{Sign}
{194501}{}{The sign reads: MINEFIELD. There could still be some mines nearby.}
{194600}{}{Sign}
{194700}{}{Plant}
{194800}{}{Phone}
{194900}{}{Plant}
{195000}{}{Plaque}
{195001}{}{The plaque reads "Obey our laws or leave immediately."}
{195100}{}{Sign}
{195101}{}{The old sign makes it absolutely clear - this is indeed a prison.}
{195200}{}{Radio}
{195300}{}{Radio}
{195400}{}{Slide}
{195500}{}{Stall}
{195600}{}{Punching Bag}
{195700}{}{Car}
{195800}{}{Truck}
{195801}{}{This was a truck once but now it can only be considered a big piece of junk.}
{195900}{}{Vault Outer Door}
{195901}{}{The mechanism to open and close the heavy vault door has been damaged beyond repair.}
{196000}{}{Vault Door}
{196001}{}{This vault door is now just a heavy piece of scrap-metal.}
{196100}{}{Police Car}
{196101}{}{A rusty shell of a pre-war police car with 6 wheels. You wonder how much horsepower it had in its heyday.}
{196200}{}{Lamp}
{196300}{}{Lamp}
{196400}{}{Heap}
{196500}{}{Tracks}
{196600}{}{Tracks}
{196700}{}{Tracks}
{196800}{}{Bucket}
{196900}{}{Bucket}
{197000}{}{Bucket}
{197100}{}{Monitor}
{197101}{}{If you've seen one monitor, you've seen them all.}
{197200}{}{Monitor}
{197201}{}{If you've seen one monitor, you've seen them all.}
{197300}{}{Water Cooler Dispenser}
{197301}{}{A touchless dispenser of hot and cold water, equipped with a built-in filtration system.}
{197400}{}{Antiseptic Shower}
{197401}{}{A shower with a built-in antiseptic dispenser.}
{197500}{}{Candy Machine}
{197600}{}{Candy Machine}
{197700}{}{Truck}
{197800}{}{Road Barrier}
{197900}{}{Anchor}
{198000}{}{Statue}
{198100}{}{Statue}
{198200}{}{Coil of Rope}
{198300}{}{Cacti}
{198301}{}{A cacti conglomerate.}
{198400}{}{Cooling System}
{198500}{}{Cooling System}
{198600}{}{Sign}
{198601}{}{The sign reads "Vet Pal."}
{198700}{}{Tricycle}
{198800}{}{Chalkboard}
{198900}{}{Construction Barrel}
{199000}{}{Armor}
{199100}{}{Billboard}
{199200}{}{Billboard}
{199300}{}{Billboard}
{199400}{}{Billboard}
{199500}{}{Sign}
{199600}{}{Sign}
{199700}{}{Sign}
{199800}{}{Security Door}
{199900}{}{Cacti}
{199901}{}{A cacti conglomerate.}
{200000}{}{Support Beam}
{200100}{}{Support Beam}
{200200}{}{Support Beam}
{200300}{}{Wires}
{200400}{}{Wires}
{200500}{}{Wires}
{200600}{}{Cylinder}
{200700}{}{Cylinder}
{200800}{}{Cylinder}
{200900}{}{Cylinder}
{201000}{}{Power Box}
{201100}{}{Power Box}
{201200}{}{Power Box}
{201300}{}{Power Box}
{201400}{}{Power Box}
{201500}{}{Power Box}
{201600}{}{Sign}
{201700}{}{Sign}
{201800}{}{Sign}
{201900}{}{Sign}
{202000}{}{Sign}
{202001}{}{There's a fallout shelter east of here.}
{202100}{}{Sign}
{202101}{}{There's a fallout shelter north of here.}
{202200}{}{Big Poster}
{202201}{}{An old Nuka-Cola ad featuring Nuka-Girl in a spacesuit. You wonder what's it like in outer space.}
{202300}{}{Energy Field}
{202301}{}{A powerful desynced forcefield.}
{202400}{}{Merry Go Round}
{202500}{}{Radiator}
{202501}{}{This used to heat up pre-war homes. Now it only serves as a frame for cobwebs.}
{202600}{}{Radiator}
{202601}{}{This used to heat up pre-war homes. Now it only serves as a frame for cobwebs.}
{202700}{}{Sign}
{202800}{}{Sign}
{202900}{}{Sign}
{203000}{}{Sign}
{203100}{}{Energy Field}
{203101}{}{A powerful desynced forcefield. You can feel the heat emanating from it.}
{203200}{}{Sign}
{203300}{}{Sign}
{203400}{}{World Map}
{203500}{}{Bollard}
{203600}{}{Mannequin Torso}
{203700}{}{Wagon}
{203800}{}{Shopping Cart}
{203900}{}{Graffiti}
{204000}{}{Poster}
{204001}{}{A poster for a pre-war horror movie. It seems fiction has become reality.}
{204100}{}{Poster}
{204200}{}{Poster}
{204300}{}{Poster}
{204400}{}{Poster}
{204500}{}{Poster}
{204600}{}{Poster}
{204700}{}{Poster}
{204800}{}{Poster}
{204900}{}{Parking Meter}
{205000}{}{Parking Meter}
{205100}{}{Parking Meter}
{205200}{}{Parking Meter}
{205300}{}{Treadmill}
{205301}{}{An exercise machine.}
{205400}{}{Stair Stepper}
{205401}{}{An exercise machine.}
{205500}{}{Poster}
{205600}{}{Doghouse}
{205700}{}{Rim}
{205800}{}{Poster}
{205900}{}{Poster}
{206000}{}{Poster}
{206100}{}{Poster}
{206200}{}{Poster}
{206300}{}{Poster}
{206400}{}{Altar}
{206500}{}{Altar}
{206600}{}{Altar}
{206700}{}{Altar}
{206800}{}{Altar}
{206900}{}{Pew}
{207000}{}{Podium}
{207001}{}{This is a normal podium for public speaking.}
{207100}{}{Truck}
{207200}{}{Slot Machine}
{207300}{}{Snow Globe}
{207400}{}{Pedestal}
{207500}{}{Armored Vehicle}
{207501}{}{This is the most powerful road vehicle you have ever seen. It is only a metal shell now as the interior was salvaged for parts long, long ago.}
{207600}{}{Armored Vehicle}
{207601}{}{This is the most powerful road vehicle you have ever seen. It is only a metal shell now as the interior was salvaged for parts long, long ago.}
{207700}{}{Car Battery}
{207800}{}{Car Battery}
{207900}{}{Graffiti}
{208000}{}{Graffiti}
{208100}{}{Statue}
{208200}{}{Garbage Bags}
{208300}{}{Garbage Bag}
{208400}{}{Garbage Bag}
{208500}{}{Garbage Bags}
{208600}{}{Bus Stop}
{208700}{}{Sign}
{208800}{}{Sign}
{208900}{}{Bones}
{208901}{}{Interesting bones of some mutated creature. The wasteland is populated with all sort of dangers...}
{209000}{}{Sign}
{209001}{}{The sign is faded, but you can make out the words "Buses Only."}
{209100}{}{Fireplace}
{209101}{}{Fire hasn't burned in this fireplace for a long, long time.}
{209200}{}{Fireplace}
{209201}{}{Fire hasn't burned in this fireplace for a long, long time.}
{209300}{}{Cactus}
{209301}{}{You see nothing special about this cactus.}
{209400}{}{Vent}
{209500}{}{Vent}
{209600}{}{Floor}
{209700}{}{Logo}
{209701}{}{A holographic projection of Med-Tek's logo.}
{209800}{}{Vault 8 Door}
{209900}{}{Sign}
{209901}{}{The sign reads BAR. That should be pretty self-evident.}
{210000}{}{Chasm}
{210100}{}{Chasm}
{210200}{}{Chasm}
{210300}{}{Chasm}
{210400}{}{Chasm}
{210500}{}{Chasm}
{210600}{}{Chasm}
{210700}{}{Chasm}
{210800}{}{Chasm}
{210900}{}{Chasm}
{211000}{}{Chasm}
{211100}{}{Chasm}
{211200}{}{Chasm}
{211300}{}{Chasm}
{211400}{}{Chasm}
{211500}{}{Chasm}
{211600}{}{Chasm}
{211700}{}{Chasm}
{211800}{}{Chasm}
{211900}{}{Chasm}
{212000}{}{Chasm}
{212100}{}{Chasm}
{212200}{}{Chasm}
{212300}{}{Chasm}
{212400}{}{Chasm}
{212500}{}{Chasm}
{212600}{}{Chasm}
{212700}{}{Chasm}
{212800}{}{Chasm}
{212900}{}{Chasm}
{213000}{}{Chasm}
{213100}{}{Chasm}
{213200}{}{Chasm}
{213300}{}{Chasm}
{213400}{}{Chasm}
{213500}{}{Chasm}
{213600}{}{Monument}
{213601}{}{This tall monument reminds Karlstown's residents where their roots lie. The bust seems somewhat intimidating.}
{213700}{}{Wall Light}
{213800}{}{Wall Light}
{213900}{}{Wall Light}
{214000}{}{Wall Light}
{214100}{}{Dirt}
{214200}{}{Dirt}
{214300}{}{Dirt}
{214400}{}{Dirt}
{214500}{}{Dirt}
{214600}{}{Sign}
{214700}{}{}
{214701}{}{}
{214800}{}{Sign}
{214900}{}{Golden Vein}
{215000}{}{Shadow}
{215100}{}{Train}
{215200}{}{Train}
{215300}{}{DJ mixer}
{215400}{}{Speaker}
{215500}{}{Stone Slab}
{215501}{}{A big slab made out of black stone.}
{215600}{}{Sign}
{215601}{}{A big sign forming the words CLUB BLACK.}
{215700}{}{Sign}
{215800}{}{Poster}
{215900}{}{Ladder}
{216000}{}{Poster}
{216100}{}{Pit}
{216200}{}{Exhaust Port}
{216300}{}{Floor}
{216400}{}{Monitor}
{216401}{}{A monitor screen that also reacts to touch. Interesting technology, you haven't seen that before.}
{216500}{}{Monitor}
{216501}{}{A monitor screen that also reacts to touch. Interesting technology, you haven't seen that before.}
{216600}{}{Door}
{216700}{}{Hologram}
{216701}{}{A holographic image of Earth.}
{216800}{}{Projector}
{216801}{}{This is a hologram projector.}
{216900}{}{Stool}
{216901}{}{A sturdy wooden stool.}
{217000}{}{Targeting Computer}
{217001}{}{This computer is used to program the targeting solutions. It has a console on each side.}
{217100}{}{Monitor}
{217101}{}{A big monitor. It's turned off.}
{217200}{}{Electro-Magnetic Ramp}
{217300}{}{Statue}
{217301}{}{A statue of a giant hand pulling the chain.}
{217400}{}{Statue}
{217401}{}{A statue of a giant hand pulling the chain.}
{217500}{}{Console}
{217501}{}{A large console built for robots. There's a row of unlabeled buttons on it.}
{217600}{}{Canister}
{217700}{}{Canister}
{217800}{}{Sign}
{217900}{}{Sign}
{218000}{}{Wall}
{218100}{}{Graffiti}
{218200}{}{Power Tool}
{218300}{}{Power Tool}
{218400}{}{Power Tool}
{218500}{}{Power Tool}
{218600}{}{Power Tool}
{218700}{}{Propeller}
{218800}{}{Sign}
{218801}{}{This looks like an advertisement for the Atom bar.}
{218900}{}{Stool}
{218901}{}{A sturdy wooden stool.}
{219000}{}{Stool}
{219001}{}{A sturdy wooden stool.}
{219100}{}{Stool}
{219101}{}{A sturdy wooden stool.}
{219200}{}{Couch}
{219300}{}{Couch}
{219400}{}{Table}
{219500}{}{Skull}
{219501}{}{A brahmin skull on a pole.}
{219600}{}{Skull}
{219601}{}{A brahmin skull on a pole. With a big bullet hole in the middle.}
{219700}{}{Cactus}
{219701}{}{You see nothing special about this cactus.}
{219800}{}{Cactus}
{219801}{}{You see nothing special about this cactus.}
{219900}{}{Tanks}
{220000}{}{Console}
{220001}{}{A large console built for robots. There's a row of unlabeled buttons on it.}
{220100}{}{Turbine}
{220101}{}{This is the biggest turbine you have ever seen. It's amazing how advanced this place is.}
{220200}{}{Turbine}
{220201}{}{This is the biggest turbine you have ever seen. It's amazing how advanced this place is.}
{220300}{}{Tank}
{220400}{}{Train}
{220401}{}{This is the fastest train you have ever seen. The faded label reveals its name as "John Henry."}
{220500}{}{ODYSSEUS Computer Core}
{220501}{}{ODYSSEUS Computer Core, once a technological marvel, now a tangled, fused, and rust-covered mass of wires and metal.}
{220600}{}{Stairs}
{220601}{}{}
{220700}{}{Barrier}
{220701}{}{A barrier with reflective lights.}
{220800}{}{Hole}
{220801}{}{Rust is eating its way up this deep hole's walls.}
{220900}{}{Broken Elevator}
{220901}{}{This elevator is broken.}
{221000}{}{Broken Elevator}
{221001}{}{This elevator is broken.}
{221100}{}{Altar of Shadows}
{221101}{}{This is Hecate's Altar of Shadows.}
{221200}{}{Crates}
{221300}{}{Crates}
{221400}{}{Crate}
{221500}{}{Crate}
{221600}{}{Turbine}
{221601}{}{This is the biggest turbine you have ever seen. It's amazing how advanced this place is.}
{221700}{}{Turbine}
{221701}{}{This is the biggest turbine you have ever seen. It's amazing how advanced this place is.}
{222000}{}{Grate}
{222100}{}{Grate}
{222200}{}{Grate}
{222300}{}{Grate}
{222400}{}{Grate}
{222401}{}{A heavy grate.}
{222500}{}{Doll Head}
{222600}{}{Doll Head}
{222700}{}{Doll Head}
{222800}{}{Doll Head}
{222900}{}{Doll Head}
{223000}{}{Doll Head}
{223100}{}{Doll Head}
{223200}{}{Doll Head}
{223201}{}{This doll head has green hair.}
{223300}{}{Doll Head}
{223400}{}{Painting}
{223500}{}{Energy Field}
{223501}{}{A powerful synced forcefield.}
{223600}{}{Machine}
{223601}{}{This machine occasionally produces a low, rumbling sound.}
{223700}{}{Machine}
{223701}{}{This machine occasionally produces a low, rumbling sound.}
{223800}{}{Machine}
{223801}{}{This weird machine makes you feel uneasy.}
{223900}{}{Machine}
{223901}{}{This weird machine makes you feel uneasy.}
{224000}{}{Machine}
{224001}{}{This weird machine makes you feel uneasy.}
{224100}{}{Machine}
{224101}{}{This weird machine makes you feel uneasy.}
{224200}{}{Metal Barrels}
{224201}{}{Metal barrels that aren't rusty. That's something you don't see every day.}
{224300}{}{Metal Barrels}
{224301}{}{Metal barrels that aren't rusty. That's something you don't see every day.}
{224400}{}{Metal Barrel}
{224401}{}{A metal barrel that isn't rusty. That's something you don't see every day.}
{224500}{}{Metal Barrel}
{224501}{}{A metal barrel that isn't rusty. That's something you don't see every day.}
{224600}{}{Machine}
{224601}{}{You're not sure what this machine does. Every now and then one panel glows slightly.}
{224700}{}{Shadow}
{224800}{}{Vent}
{224801}{}{Standard Vault-Tec ventilation system. Looks like it wasn't secured properly.}
{224900}{}{Monitor}
{224901}{}{A stern looking woman talking about Vaults.}
{225000}{}{Monitor}
{225001}{}{A warning video about the dangers of nuclear fallout. You wonder why would anyone air that here.}
{225100}{}{Monitor}
{225101}{}{A video feed of a trooper in an advanced armor.}
{225200}{}{Monitor}
{225201}{}{A video feed of an old man talking. There's a strange emblem behind him.}
{225300}{}{Monitor}
{225301}{}{Looks like some sort of a religious symbol.}
{225400}{}{Auto-Wall Lift}
{225401}{}{Seems this auto-wall lift is currently shut down.}
{225500}{}{Ancient Console}
{225501}{}{It's an ancient console with a working microphone.}
{225600}{}{Machine}
{225700}{}{Machine}
{225800}{}{Machine}
{225900}{}{Machine}
{226000}{}{Machine}
{226100}{}{Machine}
{226200}{}{Turbine}
{226300}{}{Machine}
{226400}{}{Computer}
{226500}{}{Computer}
{226600}{}{Turbine}
{226700}{}{Computer}
{226800}{}{Computer}
{226900}{}{Computer}
{227000}{}{Computer}
{227100}{}{Computer}
{227200}{}{Camera}
{227300}{}{Loudspeaker}
{227400}{}{SimTek 5000}
{227401}{}{This is an advanced simulation console brought to you by Vault-Tec (R). All right reserved. You can see an ancient $1,999,999 price tag attached to it.}
{227500}{}{Vent}
{227600}{}{Vent}
{227700}{}{Computers}
{227800}{}{Hole}
{227801}{}{A big explosion ripped through several levels.}
{227900}{}{Hole}
{227901}{}{A big explosion ripped through several levels.}
{228000}{}{Jammed Door}
{228001}{}{The door controls have been overridden.}
{228100}{}{Nuclear Nellie}
{228101}{}{A very large, Howitzer looking cannon. It could probably fire a shell at a target tens of miles away.}
{228200}{}{Bio-Tank}
{228300}{}{Bio-Tank}
{228400}{}{Computer}
{228500}{}{Computer}
{228600}{}{Computer}
{228700}{}{Turbine}
{228800}{}{Computer}
{228900}{}{Computer}
{229000}{}{Computer}
{229100}{}{Computer}
{229200}{}{Computer}
{229300}{}{}
{229301}{}{}
{229400}{}{Shadow}
{229600}{}{Vent}
{229700}{}{Vent}
{229900}{}{}
{230000}{}{}
{230100}{}{Cacti}
{230101}{}{A cacti conglomerate.}
{230200}{}{Cacti}
{230201}{}{A cacti conglomerate.}
{230300}{}{Cacti}
{230301}{}{A cacti conglomerate.}
{230400}{}{Cacti}
{230401}{}{A cacti conglomerate.}
{230500}{}{Cactus}
{230501}{}{It's a cactus. Those spines looks very sharp.}
{230600}{}{Cacti}
{230601}{}{A cacti conglomerate.}
{230700}{}{Cactus}
{230701}{}{It's a cactus. Those spines looks very sharp.}
{230800}{}{Cacti}
{230801}{}{A cacti conglomerate.}
{230900}{}{Power Transformer}
{231000}{}{Power Transformer}
{231100}{}{Mountain}
{231400}{}{Mountain}
{231600}{}{Junk}
{231601}{}{This was probably a robot once.}
{231700}{}{Electrical Fence}
{231701}{}{Sparks are dancing up and down the fence.}
{231800}{}{Electrical Fence}
{231801}{}{Sparks are dancing up and down the fence.}
{231900}{}{Electrical Fence}
{231901}{}{Sparks are dancing up and down the fence.}
{232000}{}{Electrical Fence}
{232001}{}{Sparks are dancing up and down the fence.}
{232100}{}{Tram}
{232101}{}{This tram looks old but still operational.}
{232200}{}{Tram}
{232201}{}{This tram looks old but still operational.}
{232300}{}{Tracks}
{232400}{}{Timetable}
{232401}{}{The tram timetable faded away but someone scribbled "HELL" over it.}
{232500}{}{Air Processing Unit}
{232501}{}{An APU cleans the old air to provide new air for the complex.}
{232600}{}{Bush}
{232700}{}{Statue}
{232800}{}{Shadow}
{232900}{}{Wall}
{233000}{}{Wall}
{233100}{}{Energy Field}
{233101}{}{A powerful desynced forcefield.}
{233200}{}{Statue}
{233201}{}{A statue of a strange animal.}
{233300}{}{Molech}
{233301}{}{You feel very lucky that this thing is lying dormant right now.}
{233400}{}{Standing Stone}
{233401}{}{Tribal etchings decorate this stone. The exact meaning of it is lost to you.}
{233500}{}{Lobotomite}
{233501}{}{It's resting. More likely dead. You can see its exposed brain.}
{233600}{}{Smoke}
{233700}{}{Cliff}
{233800}{}{Cliff}
{233801}{}{The steel bunker door is firmly shut with no apparent way of opening it. You see a cave further down the cliff to the east.}
{233900}{}{Cliff}
{233901}{}{The steel bunker door is firmly shut with no apparent way of opening it. You see a cave further down the cliff to the east.}
{234000}{}{Cliff}
{234100}{}{Cliff}
{234101}{}{The steel bunker door is firmly shut with no apparent way of opening it. You see a cave further down the cliff to the east.}
{234200}{}{Cliff}
{234201}{}{The steel bunker door is firmly shut with no apparent way of opening it. You see a cave further down the cliff to the east.}
{234300}{}{Cliff}
{234400}{}{Cliff}
{234500}{}{Cliff}
{234600}{}{Cliff}
{234700}{}{Cliff}
{234800}{}{Cliff}
{234900}{}{Cliff}
{235000}{}{Cliff}
{235100}{}{Auxiliary Light}
{235200}{}{Van}
{235201}{}{This piece of junk vaguely resembles a transportation van for Vault-Tec employees and Vault Dwellers back in the day.}
{235300}{}{Bush}
{235400}{}{Condenser}
{235401}{}{This advanced piece of pre-war machinery is able to take water out of the hot desert air and store it. It seems to serve as a transformer too.}
{235500}{}{Tank}
{235501}{}{You're not sure if this tank will ever see action again.}
{235600}{}{Vent}
{235700}{}{Well}
{235800}{}{Boat}
{235900}{}{Boat}
{236000}{}{Pillar}
{236100}{}{Pillar}
{236200}{}{NCR Flag}
{236201}{}{A framed flag of the New California Republic.}
{236300}{}{NCR Flag}
{236301}{}{A framed flag of the New California Republic.}
{236400}{}{NCR Flag}
{236401}{}{A framed flag of the New California Republic.}
{236500}{}{Stairs}
{236600}{}{Stairs}
{236700}{}{Stairs}
{236800}{}{Drainage}
{236900}{}{Hanged Woman}
{236901}{}{She's gone.}
{237000}{}{Tank}
{237100}{}{Door}
{237200}{}{Door}
{237300}{}{Thing}
{237301}{}{You have no idea what *that* is.}
{237400}{}{Junk}
{237500}{}{Junk}
{237600}{}{Tree}
{237700}{}{Tree}
{237800}{}{Road}
{237900}{}{Road}
{238000}{}{Road}
{238100}{}{Road}
{238200}{}{Road}
{238300}{}{Cliff}
{238400}{}{Cliff}
{238500}{}{Cliff}
{238600}{}{Rock}
{238700}{}{Rock}
{238800}{}{Rock}
{238900}{}{Sign}
{239000}{}{Sign}
{239100}{}{Shadow}
{239200}{}{Table}
{239300}{}{Table}
{239400}{}{Ramp}
{239500}{}{Water Maker}
{239501}{}{This advanced piece of pre-war machinery is able to take water out of the hot desert air and store it.}
{239600}{}{Raider Car}
{239700}{}{Forklift}
{239800}{}{Forklift}
{239900}{}{Tank}
{240000}{}{Tank}
{240100}{}{Tank}
{240200}{}{Tank}
{240300}{}{Painting}
{240400}{}{Jukebox}
{240401}{}{A Juke 'n Jive jukebox with chrome trims and dark red speaker grill.}
{240500}{}{Impaled Head}
{240600}{}{Tank}
{240601}{}{This huge water tower holds the heavily filtered irrigation water supply.}
{240700}{}{Tank}
{240701}{}{This huge water tower holds the heavily filtered irrigation water supply.}
{240800}{}{Tank}
{240801}{}{This huge water tower holds the heavily filtered irrigation water supply.}
{240900}{}{Wall}
{241000}{}{Wall}
{241100}{}{Tank}
{241101}{}{This huge water tower holds the heavily filtered irrigation water supply.}
{241200}{}{Tank}
{241201}{}{This huge water tower holds the heavily filtered irrigation water supply.}
{241300}{}{Tank}
{241400}{}{Tank}
{241500}{}{Tank}
{241600}{}{Water Tank}
{241601}{}{This is the Fort's only source of drinking water.}
{241700}{}{Hanged Man}
{241701}{}{He's gone.}
{241800}{}{Hanged Man}
{241801}{}{He's gone.}
{241900}{}{Crucified Man}
{241901}{}{He's gone.}
{242000}{}{Sticks}
{242100}{}{Junk}
{242200}{}{Boat}
{242300}{}{Buoy}
{242400}{}{Buoy}
{242500}{}{Buoy}
{242600}{}{Boat}
{242700}{}{Pipes}
{242800}{}{Pipes}
{242900}{}{Pipes}
{243000}{}{Campfire}
{243100}{}{Lab Table}
{243200}{}{Workshop Table}
{243300}{}{Corpse}
{243400}{}{Hanged Man}
{243401}{}{This hanged person is also badly burnt, but somehow, still alive.}
{243500}{}{Plant}
{243600}{}{Plant}
{243601}{}{It looks like a mutated yucca plant.}
{243700}{}{Bike}
{243701}{}{A rusty bike - this one has reached the end of the road.}
{243800}{}{Machine}
{243900}{}{Machine}
{244000}{}{Truck}
{244100}{}{Generator}
{244200}{}{Generator}
{244300}{}{Generator}
{244400}{}{Generator}
{244500}{}{Klaxon}
{244600}{}{Klaxon}
{244700}{}{Truck}
{244800}{}{Dirty Glass}
{244900}{}{Dirty Glass}
{245000}{}{Dirty Glass}
{245100}{}{Dirty Glass}
{245200}{}{Dirty Glass}
{245300}{}{Dirty Glass}
{245400}{}{Door}
{245500}{}{Door}
{245600}{}{Guard Shack}
{245601}{}{This guard shack is over a hundred years old, but still in excellent condition.}
{245700}{}{Guard Shack}
{245701}{}{This guard shack is over a hundred years old, but still in excellent condition.}
{245800}{}{Truck}
{245900}{}{Crashed Airplane}
{246000}{}{Crashed Airplane}
{246100}{}{Crashed Airplane}
{246200}{}{Crashed Airplane}
{246300}{}{Shadow}
{246400}{}{Shadow}
{246500}{}{Dirt}
{246600}{}{Shadow}
{246700}{}{Hangar}
{246800}{}{Hangar}
{246900}{}{Hangar}
{247000}{}{Hangar}
{247100}{}{Hangar}
{247200}{}{Door}
{247300}{}{Lighthouse Light}
{247301}{}{This light source produces a concentrated beam, efficiently traveling long distances through specialized lenses.}
{247400}{}{Lighthouse Light}
{247401}{}{This light source produces a concentrated beam, efficiently traveling long distances through specialized lenses.}
{247500}{}{Market Stand}
{247600}{}{Cables}
{247700}{}{Cables}
{247800}{}{Cables}
{247900}{}{Wires}
{248000}{}{Wires}
{248100}{}{Wires}
{248200}{}{Wires}
{248300}{}{Laser Cannon}
{248301}{}{A big laser death cannon, pointed right at the Hounds camp on the canyon floor.}
{248400}{}{Laser Cannon}
{248401}{}{A big laser death cannon, pointed right at the Hounds camp on the canyon floor.}
{248500}{}{Wheels}
{248600}{}{Wheels}
{248700}{}{Anvil}
{248800}{}{Anvil}
{248900}{}{Anvil}
{249000}{}{Desk}
{249200}{}{Sign}
{249300}{}{Corpse}
{249400}{}{Box}
{249500}{}{Box}
{249600}{}{Box}
{249700}{}{Box}
{249800}{}{Wagon}
{249900}{}{Wagon}
{250000}{}{Box}
{250100}{}{Airplane}
{250200}{}{Airplane Engine}
{250300}{}{Airplane Engine}
{250400}{}{Airplane Engine}
{250500}{}{Pipes}
{250600}{}{Airplane}
{250700}{}{Junk}
{250800}{}{Junk}
{250900}{}{Junk}
{251000}{}{Junk}
{251100}{}{Wheels}
{251200}{}{Wing}
{251300}{}{Wing}
{251400}{}{Wing}
{251500}{}{Wing}
{251600}{}{Propeller}
{251700}{}{Wing}
{251800}{}{Wing}
{251900}{}{Wing}
{252000}{}{Wing}
{252100}{}{Machine}
{252200}{}{Cables}
{252300}{}{Brainiator}
{252301}{}{This device is used for fitting brains into robobrains or extracting them from volunteers.}
{252400}{}{Cables}
{252500}{}{Machine}
{252600}{}{Engine}
{252700}{}{Engine}
{252800}{}{Engine}
{252900}{}{Engine}
{253000}{}{Engine}
{253100}{}{Engine}
{253200}{}{Engines}
{253300}{}{Engines}
{253400}{}{Container}
{253401}{}{There's an airplane engine inside.}
{253500}{}{Container}
{253501}{}{There's an airplane engine inside.}
{253600}{}{Container}
{253601}{}{There's nothing inside.}
{253700}{}{Engines}
{253800}{}{Engines}
{253900}{}{Container}
{254000}{}{Container}
{254100}{}{Container}
{254200}{}{Container}
{254300}{}{Container}
{254400}{}{Airplane}
{254500}{}{Airplane}
{254600}{}{Airplane}
{254700}{}{Airplane}
{254800}{}{Airplane}
{254900}{}{Airplane}
{255000}{}{Airplane}
{255100}{}{Airplane}
{255200}{}{Airplane}
{255300}{}{Airplane}
{255400}{}{Airplane}
{255500}{}{Airplane}
{255600}{}{Airplane}
{255700}{}{Airplane}
{255701}{}{The rusty remains of a military airplane, ready for the museum.}
{255800}{}{Airplane}
{255801}{}{The rusty remains of a military airplane, ready for the museum.}
{255900}{}{Airplane}
{255901}{}{The rusty remains of a military airplane, ready for the museum.}
{256000}{}{Airplane}
{256001}{}{The rusty remains of a military airplane, ready for the museum.}
{256100}{}{Airplane}
{256101}{}{The rusty remains of a military airplane, ready for the museum.}
{256200}{}{Airplane}
{256201}{}{The rusty remains of a military airplane, ready for the museum.}
{256300}{}{Airplane}
{256301}{}{The rusty remains of a military airplane, ready for the museum.}
{256400}{}{Airplane}
{256401}{}{The rusty remains of a military airplane, ready for the museum.}
{256500}{}{Airplane}
{256501}{}{The rusty remains of a military airplane, ready for the museum.}
{256600}{}{Airplane}
{256601}{}{The rusty remains of a military airplane, ready for the museum.}
{256700}{}{Airplane}
{256701}{}{The rusty remains of a military airplane, ready for the museum.}
{256800}{}{Airplane}
{256801}{}{The rusty remains of a military airplane, ready for the museum.}
{256900}{}{Airplane}
{256901}{}{The rusty remains of a military airplane, ready for the museum.}
{257000}{}{Airplane}
{257100}{}{Airplane}
{257200}{}{Airplane}
{257300}{}{Airplane}
{257400}{}{Airplane}
{257500}{}{Airplane}
{257600}{}{Airplane}
{257700}{}{Airplane}
{257800}{}{Airplane}
{257900}{}{Airplane}
{258000}{}{Airplane}
{258100}{}{Airplane}
{258200}{}{Seat}
{258300}{}{Seats}
{258400}{}{Seats}
{258500}{}{Seats}
{258600}{}{Seats}
{258700}{}{Seats}
{258800}{}{Golden Bars}
{258900}{}{Cabinet}
{259000}{}{Cabinet}
{259100}{}{Tower}
{259200}{}{Tower}
{259300}{}{Drain}
{259400}{}{Totem}
{259401}{}{A large number 15 is carved into the skin parchment. The human skulls are encircling it.}
{259500}{}{Table}
{259600}{}{Table}
{259700}{}{Table}
{259800}{}{Table}
{259801}{}{A person cut into pieces is gruesomely displayed on this table!}
{259900}{}{Table}
{259901}{}{A person cut into pieces is gruesomely displayed on this table!}
{260000}{}{Totem}
{260100}{}{Torch}
{260200}{}{Torch}
{260300}{}{Table}
{260301}{}{A wooden table with a skin parchment stretched on it.}
{260400}{}{Drain}
{260500}{}{Drain}
{260600}{}{Cloth}
{260700}{}{Cloth}
{260800}{}{Cloth}
{260900}{}{Cloth}
{261000}{}{Cloth}
{261100}{}{Power Line}
{261200}{}{Shadow}
{261300}{}{Wires}
{261400}{}{Power Line}
{261500}{}{Shadow}
{261600}{}{Wires}
{261700}{}{Shadow}
{261800}{}{Shadow}
{261900}{}{Wires}
{262000}{}{Wires}
{262100}{}{Wires}
{262200}{}{Power Line}
{262300}{}{Wooden Boards}
{262400}{}{Wooden Boards}
{262500}{}{Wooden Boards}
{262600}{}{Wooden Boards}
{262700}{}{Wooden Boards}
{262800}{}{Cargo}
{262900}{}{Books}
{262901}{}{These books will soon crumble into dust.}
{263000}{}{Books}
{263001}{}{These books will soon crumble into dust.}
{263100}{}{Papers}
{263101}{}{These papers will soon crumble into dust.}
{263200}{}{Papers}
{263201}{}{These papers will soon crumble into dust.}
{263300}{}{Books}
{263301}{}{These books will soon crumble into dust.}
{263400}{}{Books}
{263401}{}{These books will soon crumble into dust.}
{263500}{}{Books}
{263501}{}{These books will soon crumble into dust.}
{263600}{}{Books}
{263601}{}{These books will soon crumble into dust.}
{263700}{}{Airplane}
{263800}{}{Airplane}
{263900}{}{Car}
{263901}{}{Someone parked their car here.}
{264000}{}{Tanks}
{264100}{}{Advertising Board}
{264200}{}{Advertising Board}
{264300}{}{Advertising Board}
{264400}{}{Poster}
{264500}{}{Poster}
{264600}{}{Poster}
{264700}{}{Poster}
{264800}{}{Poster}
{264900}{}{Poster}
{265000}{}{Poster}
{265100}{}{Poster}
{265200}{}{Poster}
{265300}{}{Poster}
{265400}{}{Billboard}
{265500}{}{Billboard}
{265600}{}{Billboard}
{265700}{}{Billboard}
{265800}{}{Billboard}
{265900}{}{Billboard}
{266000}{}{Poster}
{266100}{}{Poster}
{266200}{}{Poster}
{266300}{}{Poster}
{266400}{}{Poster}
{266500}{}{Poster}
{266600}{}{Poster}
{266700}{}{Poster}
{266800}{}{Poster}
{266900}{}{Poster}
{267000}{}{Poster}
{267100}{}{Poster}
{267200}{}{Poster}
{267300}{}{Poster}
{267400}{}{Poster}
{267500}{}{Poster}
{267600}{}{Poster}
{267700}{}{Poster}
{267800}{}{Poster}
{267900}{}{Poster}
{268000}{}{Poster}
{268100}{}{Poster}
{268200}{}{Poster}
{268300}{}{Poster}
{268400}{}{Poster}
{268500}{}{Poster}
{268600}{}{Poster}
{268700}{}{Poster}
{268800}{}{Poster}
{268900}{}{Poster}
{269000}{}{Poster}
{269100}{}{Poster}
{269200}{}{Poster}
{269300}{}{Bones}
{269400}{}{Bones}
{269500}{}{Bones}
{269600}{}{Bones}
{269700}{}{Bones}
{269800}{}{Cannons}
{269801}{}{Anti-aircraft cannons.}
{269900}{}{Cannons}
{270000}{}{Steering Wheel}
{270100}{}{Boat}
{270200}{}{Table}
{270300}{}{Table}
{270400}{}{Table}
{270500}{}{Table}
{270600}{}{Outer Hull}
{270700}{}{Outer Hull}
{270800}{}{Outer Hull}
{270900}{}{Outer Hull}
{271000}{}{Outer Hull}
{271100}{}{Outer Hull}
{271200}{}{Outer Hull}
{272200}{}{Downstream Outlet Plates}
{272201}{}{These huge rusty plates belong to the downstream outlets of the hydropower penstocks.}
{272300}{}{Stairs}
{272400}{}{Stairs}
{272500}{}{Stairs}
{272600}{}{Stairs}
{272700}{}{Stairs}
{272800}{}{Stairs}
{272900}{}{Computer}
{273000}{}{Map}
{273100}{}{Table}
{273101}{}{A heavy table with integrated monitors.}
{273200}{}{Computer}
{273300}{}{Computer}
{273400}{}{Computer}
{273500}{}{Computer}
{273600}{}{Docks}
{273700}{}{Docks}
{273800}{}{Docks}
{273900}{}{Docks}
{274000}{}{Docks}
{274100}{}{Docks}
{274200}{}{Docks}
{274300}{}{Docks}
{274400}{}{Docks}
{274500}{}{Docks}
{274600}{}{Docks}
{274700}{}{Downstream Outlet Plates}
{274701}{}{These huge rusty plates belong to the downstream outlets of the hydropower penstocks.}
{274800}{}{Downstream Outlet Plates}
{274801}{}{These huge rusty plates belong to the downstream outlets of the hydropower penstocks.}
{275100}{}{Lamp}
{275200}{}{Water}
{275300}{}{Water}
{275400}{}{Water}
{275500}{}{Incinerator}
{275600}{}{Furnace}
{275700}{}{Furnace}
{276000}{}{Mega Rocket Launcher}
{276001}{}{This is the biggest rocket launcher you have ever seen. It seems to be an unfinished prototype.}
{276100}{}{Mega Rocket Launcher}
{276101}{}{This is the biggest rocket launcher you have ever seen. It seems to be an unfinished prototype.}
{276300}{}{Boat}
{276400}{}{Boat}
{276500}{}{Boat}
{276600}{}{Boat}
{277000}{}{Poster}
{277100}{}{Poster}
{277101}{}{A Nuka-Cola poster.}
{277200}{}{Tarp}
{277201}{}{A large sheet of plastic covering.}
{277300}{}{Tarp}
{277301}{}{A large sheet of plastic covering.}
{277400}{}{Tarp}
{277401}{}{A large sheet of plastic covering.}
{277500}{}{Tarp}
{277501}{}{A large sheet of plastic covering.}
{277600}{}{Tarp}
{277601}{}{A large sheet of plastic covering.}
{277700}{}{Tarp}
{277701}{}{A large sheet of plastic covering.}
{277800}{}{Tarp}
{277801}{}{A large sheet of plastic covering.}
{277900}{}{Tarp}
{277901}{}{A large sheet of plastic covering.}
{278000}{}{Cactus}
{278001}{}{You see nothing special about this cactus.}
{278100}{}{Cactus}
{278101}{}{You see nothing special about this cactus.}
{278200}{}{Cactus}
{278201}{}{You see nothing special about this cactus.}
{278300}{}{Car}
{278400}{}{Car}
{278500}{}{Car}
{278600}{}{Car}
{278700}{}{Car}
{278800}{}{Car}
{278900}{}{Car}
{279000}{}{Car}
{279100}{}{Car}
{279200}{}{Car}
{279300}{}{Car}
{279400}{}{Car}
{279500}{}{Car}
{279600}{}{Car}
{279700}{}{Car}
{279800}{}{Car}
{279900}{}{Car}
{280000}{}{Car}
{280100}{}{Car}
{280200}{}{Car}
{280300}{}{Car}
{280400}{}{Car}
{280500}{}{Car}
{280600}{}{Truck}
{280700}{}{Truck Trailer}
{280800}{}{Truck}
{280900}{}{Truck}
{281000}{}{Truck}
{281100}{}{Truck}
{281200}{}{Truck}
{281300}{}{Truck}
{281400}{}{Truck}
{281500}{}{Truck}
{281600}{}{Camp Trailer}
{281700}{}{Camp Trailer}
{281800}{}{Camp Trailer}
{281900}{}{Camp Trailer}
{282000}{}{Camp Trailer}
{282100}{}{Camp Trailer}
{282200}{}{Camp Trailer}
{282300}{}{Camp Trailer}
{282400}{}{Camp Trailer}
{282500}{}{Camp Trailer}
{282600}{}{Camp Trailer}
{282700}{}{Camp Trailer}
{282800}{}{Door}
{282900}{}{Door}
{283000}{}{Camp Trailer}
{283100}{}{Truck}
{283101}{}{A rusty truck lies half-buried in sand, slowly disappearing.}
{283200}{}{Car}
{283201}{}{A rusty car lies half-buried in sand, slowly disappearing.}
{283300}{}{Car}
{283301}{}{A rusty car lies half-buried in sand, slowly disappearing.}
{283400}{}{Car}
{283401}{}{A rusty car lies half-buried in sand, slowly disappearing.}
{283500}{}{Roadblock}
{283600}{}{Roadblock}
{283700}{}{Roadblock}
{283800}{}{Roadblock}
{283900}{}{Traffic Cone}
{284000}{}{Traffic Cone}
{284100}{}{Traffic Cone}
{284200}{}{Door}
{284300}{}{Poster}
{284400}{}{Door}
{284500}{}{Door}
{284600}{}{Door}
{284700}{}{Door}
{284800}{}{Door}
{284900}{}{Door}
{285000}{}{Door}
{285100}{}{Door}
{285200}{}{Door}
{285300}{}{Door}
{285400}{}{Door}
{285500}{}{Door}
{285600}{}{Door}
{285700}{}{Door}
{285800}{}{Door}
{285900}{}{Door}
{286000}{}{Door}
{286100}{}{Door}
{286200}{}{Poster}
{286300}{}{Roadblock}
{286400}{}{Roadblock}
{286500}{}{Barbed Wire}
{286600}{}{Barbed Wire}
{286700}{}{Barbed Wire}
{286800}{}{Sign}
{286900}{}{Statue}
{287000}{}{Power Node}
{287100}{}{Sign}
{287200}{}{Sign}
{287300}{}{Door}
{287400}{}{Fossil}
{287401}{}{The rusty plague beneath the scary fossil reads: "Behold the Tyrant Lizard King: Tyrannosaurus Rex"}
{287500}{}{Fossil}
{287501}{}{The rusty plague beneath the scary fossil reads: "Behold the Tyrant Lizard King: Tyrannosaurus Rex"}
{287600}{}{Statue}
{287700}{}{Totem}
{287800}{}{Lucky 17}
{287900}{}{Slots Machine}
{288000}{}{Slots Machine}
{288100}{}{Gambling Table}
{288200}{}{Gambling Table}
{288300}{}{Gambling Table}
{288400}{}{Gambling Table}
{288500}{}{Heavy Duty Trolley}
{288600}{}{Heavy Duty Trolley}
{288700}{}{Heavy Duty Trolley}
{288800}{}{Tank}
{288900}{}{Tank}
{289000}{}{Water Tower}
{289100}{}{Water Tower}
{289200}{}{Fan}
{289300}{}{Machine}
{289400}{}{Machine}
{289500}{}{File Cabinets}
{289600}{}{File Cabinets}
{289700}{}{File Cabinets}
{289800}{}{File Cabinets}
{289900}{}{Vent}
{290000}{}{Machine}
{290100}{}{Machine}
{290200}{}{Machine Parts}
{290300}{}{Powertools}
{290400}{}{The Box}
{290401}{}{You see a huge metal "box" big as a building.}
{290500}{}{The Box}
{290501}{}{You see a huge metal "box" big as a building.}
{290600}{}{The Box}
{290601}{}{You see a huge metal "box" big as a building.}
{290700}{}{The Box}
{290701}{}{You see a huge metal "box" big as a building.}
{290800}{}{The Box}
{290801}{}{You see a huge metal "box" big as a building.}
{290900}{}{The Box}
{290901}{}{You see a huge metal "box" big as a building.}
{291000}{}{The Box}
{291001}{}{You see a huge metal "box" big as a building.}
{291100}{}{Door}
{291200}{}{Pipes}
{291300}{}{Truck Trailer}
{291400}{}{Truck Trailer}
{291500}{}{Gate}
{291600}{}{Gate}
{291700}{}{Shadow}
{291800}{}{Gate}
{291900}{}{Gate}
{292000}{}{Shadow}
{292100}{}{Generator}
{292200}{}{Engine}
{292300}{}{Sign}
{292400}{}{Sign}
{292500}{}{Sign}
{292600}{}{Sign}
{292700}{}{Sign}
{292800}{}{Sign}
{292900}{}{Sign}
{293000}{}{Tank}
{293100}{}{Lamp Post}
{293200}{}{Lamp Post}
{294100}{}{Door}
{294200}{}{Bricks}
{294300}{}{Bricks}
{294400}{}{Bricks}
{294500}{}{Bricks}
{295000}{}{Chair}
{295001}{}{It seems this chair is occupied.}
{295100}{}{Shelf}
{295200}{}{Shelf}
{295300}{}{Wall}
{295400}{}{Wall}
{295500}{}{Wall}
{295600}{}{Altar}
{295700}{}{Church}
{295800}{}{Church}
{295900}{}{Church}
{296000}{}{Church}
{296100}{}{Church}
{296200}{}{Church}
{296300}{}{Church}
{296400}{}{Church}
{296500}{}{Church}
{296600}{}{Door}
{296800}{}{Desk}
{296900}{}{Desk}
{297000}{}{Meat}
{297100}{}{Medical Table}
{297200}{}{Medical Table}
{297300}{}{Mining Machine}
{297400}{}{Tunnel}
{297500}{}{Tunnel}
{297600}{}{Tunnel}
{297700}{}{Mine Light}
{297800}{}{Cables}
{297900}{}{Cables}
{298000}{}{Cables}
{298100}{}{Mine Light}
{298200}{}{Cables}
{298300}{}{Cables}
{298400}{}{Pile}
{298401}{}{A pile of some sort of ore or coal.}
{298500}{}{Pile}
{298501}{}{A pile of some sort of ore or coal.}
{298600}{}{Pile}
{298601}{}{A pile of some sort of ore or coal.}
{298700}{}{Charging Station}
{298800}{}{Mine Cart}
{298900}{}{Keys Panel}
{299000}{}{Guest Book}
{299100}{}{Column}
{299200}{}{Bike}
{300000}{}{Cliff}
{300100}{}{Cliff}
{300200}{}{Cliff}
{300300}{}{Cliff}
{300400}{}{Cliff}
{300500}{}{Cliff}
{300600}{}{Cliff}
{300700}{}{Cliff}
{300800}{}{Cliff}
{300900}{}{Cliff}
{301000}{}{Cliff}
{301100}{}{Cliff}
{301200}{}{Cliff}
{301300}{}{Cliff}
{301400}{}{Cliff}
{301500}{}{Grain Silo}
{301501}{}{This looks like a concrete batching plant repurposed to store grain.}
{301600}{}{Grain Silo}
{301601}{}{This looks like a concrete batching plant repurposed to store grain.}
{301700}{}{Grain Silo}
{301701}{}{This looks like a concrete batching plant repurposed to store grain.}
{301800}{}{Grain Silo}
{301801}{}{This looks like a concrete batching plant repurposed to store grain.}
{301900}{}{Grain Silo}
{301901}{}{This looks like a concrete batching plant repurposed to store grain.}
{302000}{}{Machine}
{302100}{}{Sign}
{302200}{}{Lil Chemist}
{302300}{}{Skyscraper}
{302301}{}{This is the tallest building you have ever seen.}
{302400}{}{Skyscraper}
{302401}{}{This is the tallest building you have ever seen.}
{302500}{}{Skyscraper}
{302501}{}{This is the tallest building you have ever seen.}
{302600}{}{Skyscraper}
{302601}{}{This is the tallest building you have ever seen.}
{302700}{}{Skyscraper}
{302701}{}{This is the tallest building you have ever seen.}
{302800}{}{Skyscraper}
{302801}{}{This is the tallest building you have ever seen.}
{302900}{}{Skyscraper}
{302901}{}{This is the tallest building you have ever seen.}
{303000}{}{Skyscraper}
{303001}{}{This is the tallest building you have ever seen.}
{303100}{}{Skyscraper}
{303101}{}{This is the tallest building you have ever seen.}
{303200}{}{Skyscraper}
{303201}{}{This is the tallest building you have ever seen.}
{303300}{}{Skyscraper}
{303301}{}{This is the tallest building you have ever seen.}
{303400}{}{Skyscraper}
{303401}{}{This is the tallest building you have ever seen.}
{303500}{}{Skyscraper}
{303501}{}{This is the tallest building you have ever seen.}
{303600}{}{Skyscraper}
{303601}{}{This is the tallest building you have ever seen.}
{303700}{}{Stuff}
{303800}{}{Desk}
{303900}{}{Desk}
{304000}{}{Desk}
{304100}{}{Desk}
{304200}{}{Desk}
{304300}{}{Painting}
{304400}{}{Painting}
{304500}{}{Statue}
{304501}{}{The plaque reads "Atlas, the Bearer of the Cosmos. Dedicated to the pioneers of space exploration and the tireless efforts of those who continue to expand the horizons of human understanding. Per Aspera Ad Astra. Through Suffering To the Stars."}
{304600}{}{Market Stand}
{304700}{}{Market Stand}
{304800}{}{Market Stand}
{304900}{}{Market Stand}
{305000}{}{Sign}
{305100}{}{Sign}
{305200}{}{Sign}
{305300}{}{Rubble}
{305400}{}{Rubble}
{305500}{}{Rubble}
{305600}{}{Rubble}
{305700}{}{Rubble}
{305800}{}{Wall}
{305900}{}{Wall}
{306000}{}{Wall}
{306100}{}{Broken Pipes}
{306200}{}{Pipes}
{306300}{}{Shooting Target}
{306400}{}{Sign}
{306500}{}{Sign}
{306600}{}{Sign}
{306700}{}{Sign}
{306800}{}{Microphone}
{306900}{}{Curtain}
{307000}{}{Stage}
{307100}{}{Curtain}
{307200}{}{Shelf}
{307300}{}{Menu Board}
{307301}{}{Looks like the iguanas are quite popular around here.}
{307400}{}{Wall}
{307500}{}{Wall}
{307600}{}{Wall}
{307700}{}{Wall}
{307800}{}{Wall}
{307900}{}{Wall}
{308000}{}{Wall}
{308100}{}{Wall}
{308200}{}{Wooden Pallets}
{308300}{}{Wooden Pallets}
{308400}{}{Wooden Pallets}
{308500}{}{Wooden Pallets}
{308600}{}{Fridge}
{308700}{}{Intercom}
{308900}{}{Flag Post}
{309000}{}{Flag Post}
{309100}{}{Flag Post}
{309200}{}{Flag Post}
{309300}{}{Broken Console}
{309400}{}{Console}
{309500}{}{Hole}
{309501}{}{A deep, shadowed hole.}
{309600}{}{Hole}
{309601}{}{A deep, shadowed hole with a sturdy log across its opening and a thick rope securely tied to it.}
{309700}{}{Table}
{309800}{}{Machine}
{309900}{}{Tank}
{310000}{}{Sign}
{310100}{}{Well}
{310200}{}{Cactus}
{310201}{}{You see nothing special about this cactus.}
{310300}{}{Mountain}
{310400}{}{Mountain}
{310500}{}{Mountain}
{310600}{}{Sign}
{310700}{}{Sign}
{310800}{}{Sign}
{310900}{}{Sign}
{311000}{}{Broken Door}
{311100}{}{Machine}
{311200}{}{Machine}
{311300}{}{Machine}
{311400}{}{Machine}
{311500}{}{Machine}
{311600}{}{Computer}
{311700}{}{Machine}
{311800}{}{Shadow}
{311900}{}{Door}
{312000}{}{Wall}
{312100}{}{Wall}
{312200}{}{Wall}
{312300}{}{Wall}
{312400}{}{Wall}
{312500}{}{Wall}
{312600}{}{Wall}
{312700}{}{Wall}
{312800}{}{Wall}
{312900}{}{Cliff}
{313000}{}{Cliff}
{313100}{}{Cliff}
{313200}{}{Wall}
{313300}{}{Radio Tower}
{313400}{}{Radio Tower}
{313500}{}{Radio Tower}
{313600}{}{Radio Tower}
{313700}{}{Radio Tower}
{313800}{}{Radios}
{313900}{}{Radio Tower}
{314000}{}{Dock}
{314100}{}{Crank}
{314200}{}{Raft}
{314300}{}{Table}
{314301}{}{There's a radio on the table.}
{314400}{}{Broken Table}
{314500}{}{Wall}
{314600}{}{Wall}
{314700}{}{Wall}
{314800}{}{Junk}
{314900}{}{Tank}
{315000}{}{Bollard}
{315100}{}{Bollard}
{315200}{}{Sign}
{315300}{}{Sign}
{315400}{}{Sign}
{315500}{}{Sign}
{315600}{}{Sign}
{315800}{}{Stairs}
{315900}{}{Wall}
{316000}{}{Missile Door Manual Crank}
{316001}{}{This manual crank can open, close, block or unblock the outer missile door using the hand wheel.}
{316100}{}{Missile Door Manual Crank}
{316101}{}{This manual crank can open, close, block or unblock the outer missile door using the hand wheel.}
{316200}{}{Spillway}
{316201}{}{This facility forms an integral part of the Hoover Dam, providing the means to control the flow of water from the lake into the river below.}
{316300}{}{Spillway}
{316301}{}{This facility forms an integral part of the Hoover Dam, providing the means to control the flow of water from the lake into the river below.}
{316400}{}{Spillway}
{316401}{}{This facility forms an integral part of the Hoover Dam, providing the means to control the flow of water from the lake into the river below.}
{316500}{}{Water Tower}
{316600}{}{Graffiti}
{316700}{}{Net}
{316800}{}{Net}
{316900}{}{Shadow}
{317000}{}{Stairs}
{317100}{}{Stairs}
{317200}{}{Stairs}
{318100}{}{Sign}
{318200}{}{Sign}
{318300}{}{Sign}
{318400}{}{Sign}
{318500}{}{Sign}
{318600}{}{Sign}
{318700}{}{Sign}
{318800}{}{Traffic Lights}
{318900}{}{Sign}
{319000}{}{Sign}
{319100}{}{Sign}
{319200}{}{Sign}
{319300}{}{Road Sign}
{319400}{}{Shadow}
{319500}{}{Sign}
{319600}{}{Shadow}
{319700}{}{Road Sign}
{319800}{}{Shadow}
{319900}{}{Road Sign}
{320000}{}{Shadow}
{320100}{}{Sign}
{320200}{}{Radiation Warning Sign}
{320300}{}{Radiation Warning Sign}
{320400}{}{Lamp}
{320500}{}{Lamp}
{320600}{}{Sign}
{320700}{}{Sign}
{320800}{}{Sign}
{320900}{}{Sign}
{321000}{}{Sign}
{321200}{}{Sign}
{321300}{}{Parking Meter}
{321400}{}{Parking Meter}
{321500}{}{Missiles}
{321600}{}{Sonar}
{321700}{}{Racks}
{321800}{}{Door}
{321900}{}{Tracks}
{322000}{}{Tracks}
{322100}{}{Tracks}
{322200}{}{Tracks}
{322300}{}{Bumper}
{322400}{}{Bear Trap}
{322500}{}{Bear Trap}
{322600}{}{Trap}
{322700}{}{Trap}
{322800}{}{Tires}
{322900}{}{Bricks}
{323000}{}{Bricks}
{323100}{}{Bricks}
{323200}{}{Tree}
{323300}{}{Tree}
{323400}{}{Palm}
{323500}{}{TV Set}
{323501}{}{A broken TV set. The label identifies the manufacturer as Radiation King.}
{323600}{}{TV Set}
{323601}{}{A broken TV set. The label identifies the manufacturer as Radiation King.}
{323700}{}{Broken Pot}
{323900}{}{Stool}
{324000}{}{Stool}
{324100}{}{Tub}
{324200}{}{Pottery Table}
{324500}{}{Shelf}
{324600}{}{Shelf}
{324700}{}{Shelf}
{324800}{}{Shelf}
{324900}{}{Shelf}
{325000}{}{Broken Shelf}
{325100}{}{Bags}
{325200}{}{Bags}
{325300}{}{Bags}
{325700}{}{Broken Wooden Boards}
{325800}{}{Broken Wooden Boards}
{325900}{}{Shelf}
{326000}{}{Shelf}
{326100}{}{Shelf}
{326200}{}{Bricks}
{326300}{}{Bricks}
{326400}{}{Bricks}
{326500}{}{Bucket}
{326600}{}{Rack}
{326700}{}{Bags}
{326800}{}{Bags}
{326900}{}{Bags}
{327000}{}{Corpse}
{327100}{}{Corpse}
{327200}{}{Corpse}
{327300}{}{Door}
{327400}{}{Door}
{327500}{}{Arch}
{327600}{}{Arch}
{327700}{}{Water Tower}
{327800}{}{Water Tower}
{327900}{}{Stairs}
{328000}{}{Stairs}
{328100}{}{Staircase}
{328200}{}{Ladder}
{328300}{}{Broken Ladder}
{328400}{}{Stairs}
{328500}{}{Bed}
{328600}{}{Bed}
{328700}{}{Bed}
{328800}{}{Table}
{328900}{}{Table}
{329000}{}{Monitor}
{329100}{}{Machine}
{329200}{}{Machine}
{329300}{}{Intercom}
{329400}{}{Intercom}
{329500}{}{Loudspeaker}
{329600}{}{Loudspeaker}
{329700}{}{Drawing Board}
{329800}{}{Drawing Board}
{329900}{}{Junk}
{330000}{}{Junk}
{330100}{}{Junk}
{330200}{}{Well}
{330300}{}{Broken Mirror}
{330400}{}{Broken Mirror}
{330500}{}{Broken Mirror}
{330600}{}{Broken Mirror}
{330700}{}{Mirror}
{330800}{}{Mirror}
{330900}{}{Desk}
{331100}{}{Door}
{331200}{}{Junk}
{331201}{}{A mountain of scrap metal.}
{331300}{}{Car}
{331400}{}{Wagon}
{331500}{}{Wagon}
{331600}{}{Wagon}
{331700}{}{Train}
{331800}{}{Tracks}
{331900}{}{Train}
{332000}{}{Wagon}
{332100}{}{Wagon}
{332200}{}{Wagon}
{332300}{}{Wagon}
{332400}{}{Train}
{332500}{}{Wagon}
{332600}{}{Wagon}
{332700}{}{Tent}
{332800}{}{Tent}
{332900}{}{Tent}
{333000}{}{Tent}
{333100}{}{Market Stand}
{333200}{}{Market Stand}
{333300}{}{Screen}
{333301}{}{A big screen showing some sort of a tactical map.}
{333400}{}{Traffic Cone}
{333500}{}{Traffic Cone}
{333600}{}{Traffic Cone}
{333700}{}{Traffic Cone}
{333800}{}{Traffic Cone}
{333900}{}{Traffic Cone}
{334000}{}{Traffic Cone}
{334100}{}{Traffic Cone}
{334200}{}{Hole}
{334300}{}{Hole}
{334400}{}{Hole}
{334500}{}{Hole}
{334600}{}{Hole}
{334700}{}{Hole}
{334900}{}{Campfire}
{335000}{}{Oil Barrel}
{335100}{}{Oil Barrel}
{335200}{}{Oil Barrels}
{335300}{}{Oil Barrels}
{335400}{}{Stone Panels}
{335500}{}{Stone Panels}
{335600}{}{Archway}
{335800}{}{Chains}
{335900}{}{Chains}
{336000}{}{Bed}
{336100}{}{Bed}
{336200}{}{Bed}
{336300}{}{Hose}
{336400}{}{Wall Light}
{336500}{}{Wall Light}
{336600}{}{Wall Light}
{337200}{}{Dirt}
{337300}{}{Dirt}
{337400}{}{Dirt}
{337500}{}{Dirt}
{337600}{}{Dirt}
{337700}{}{Sofa}
{337800}{}{Sofa}
{337900}{}{Tires}
{338000}{}{Tire}
{338100}{}{Tire}
{338200}{}{Tire}
{338300}{}{Wheel}
{338400}{}{Wheel}
{338500}{}{Wheel}
{338600}{}{Car}
{338700}{}{Market Stand}
{338800}{}{Car}
{338900}{}{Car}
{339000}{}{Propeller}
{339100}{}{Bike}
{339200}{}{Flag}
{339300}{}{Machine}
{339400}{}{Campfire}
{339500}{}{Cross}
{339600}{}{Cross}
{340100}{}{Microwave}
{340500}{}{Campfire}
{340600}{}{Torch}
{340700}{}{Lamp}
{340800}{}{Lamp}
{340900}{}{Lamp}
{341000}{}{Lamp}
{341100}{}{Sign}
{341200}{}{Conveyor Belt}
{341300}{}{Conveyor Belt}
{341400}{}{Stone Panels}
{341500}{}{Gravestone}
{341600}{}{Gravestone}
{341700}{}{Gravestone}
{341800}{}{Gravestone}
{342400}{}{Conveyor Belt}
{342500}{}{Conveyor Belt}
{342600}{}{Pipes}
{343200}{}{Vent}
{343300}{}{Vent}
{343400}{}{Barrel}
{343600}{}{Chair}
{343700}{}{Chair}
{343800}{}{Chair}
{343900}{}{Chair}
{344000}{}{Chair}
{344100}{}{Chair}
{344200}{}{Hole}
{344300}{}{Hole}
{344400}{}{Hole}
{344500}{}{Hole}
{344600}{}{Hole}
{344700}{}{Hole}
{344800}{}{Hole}
{344900}{}{Hole}
{345100}{}{Jukebox}
{345101}{}{A Juke 'n Jive jukebox.}
{345200}{}{Jukebox}
{345201}{}{A Juke 'n Jive jukebox.}
{345300}{}{Sign}
{345400}{}{Escape Pod}
{345500}{}{Sign}
{345600}{}{Bench}
{345700}{}{Vent}
{345800}{}{Conveyor Belt}
{345900}{}{Wagon}
{345901}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{346000}{}{Wagon}
{346001}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{346100}{}{Wagon}
{346101}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{346200}{}{Wagon}
{346201}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{346301}{}{Lamps}
{346400}{}{Dirt}
{346500}{}{Watchtower}
{346600}{}{Watchtower}
{346700}{}{Flag}
{346800}{}{Flag}
{346900}{}{Dirt}
{347000}{}{Pipes}
{347100}{}{Machine}
{347200}{}{Crack}
{347201}{}{Scary dark crack in the ground. You wonder how deep it is.}
{347300}{}{Vat}
{347400}{}{Chemical Goo}
{347401}{}{A vile-looking chemical goo.}
{347500}{}{Column}
{347600}{}{Sign}
{347601}{}{It's an Environmental Protection Agency sign.}
{347700}{}{Shadow}
{347800}{}{Sign}
{347801}{}{It's an Environmental Protection Agency sign.}
{347900}{}{Sign}
{347901}{}{It's an Environmental Protection Agency sign.}
{348000}{}{Sign}
{348001}{}{It's an Environmental Protection Agency sign.}
{348100}{}{Sign}
{348101}{}{It's an Environmental Protection Agency sign.}
{348300}{}{Broken Table}
{348400}{}{Stairs}
{348500}{}{Table}
{348600}{}{Chair}
{348700}{}{Chair}
{348800}{}{Chair}
{348900}{}{Chair}
{349000}{}{Chair}
{349100}{}{Chair}
{349200}{}{Chair}
{349300}{}{Chair}
{349400}{}{Chair}
{349500}{}{Chair}
{349600}{}{Chair}
{349700}{}{Chair}
{349800}{}{Chair}
{349900}{}{Chair}
{350000}{}{Chair}
{350100}{}{Antennae}
{350200}{}{Fence}
{350300}{}{Fence}
{350400}{}{Fence}
{350500}{}{Boat}
{350600}{}{Truck}
{350700}{}{Motorbike}
{350800}{}{Motorbike}
{350900}{}{Fence}
{351000}{}{Lamp Post}
{351100}{}{Lamp Post}
{351200}{}{Lamp Post}
{351300}{}{Lamp Post}
{351400}{}{Lamp Post}
{351500}{}{Lamp Post}
{351600}{}{Lamp Post}
{351700}{}{Rocks}
{351800}{}{Rocks}
{351900}{}{Rocks}
{352000}{}{Rocks}
{352100}{}{Rocks}
{352200}{}{Rocks}
{352300}{}{Rocks}
{352400}{}{Rocks}
{352500}{}{Rocks}
{352600}{}{Rocks}
{352700}{}{Rocks}
{352800}{}{Fence}
{352900}{}{Fence}
{353000}{}{Conveyor Belt}
{353100}{}{Table}
{353200}{}{Car}
{353300}{}{Tent}
{353400}{}{Tent}
{353600}{}{Truck}
{353700}{}{Truck}
{353800}{}{Table}
{353900}{}{Table}
{354000}{}{Bed}
{354100}{}{Bed}
{354200}{}{Bed}
{354300}{}{Bed}
{354400}{}{Door}
{354500}{}{Door}
{354600}{}{Door}
{354700}{}{Door}
{354800}{}{Warehouse Door}
{354900}{}{Warehouse Door}
{355200}{}{Campfire}
{355300}{}{Power Nodes}
{355400}{}{Generator}
{355500}{}{Fence}
{355600}{}{Fence}
{355700}{}{Truck}
{355800}{}{Truck}
{355900}{}{Truck}
{356000}{}{Truck}
{356100}{}{Truck}
{356200}{}{Truck}
{356300}{}{Campfire}
{356400}{}{Reactor}
{357000}{}{Car}
{357100}{}{Skull Pole}
{357200}{}{Skull Pole}
{357300}{}{Skull Pole}
{357400}{}{Skull Pole}
{357500}{}{Skull Pole}
{357600}{}{Skull Pole}
{357700}{}{Scarecrow}
{357701}{}{This scarecrow might have been fashioned in the likeness of Lynette, the First Citizen of Vault City.}
{357800}{}{Scarecrow}
{357801}{}{This scarecrow might have been fashioned in the likeness of Lynette, the First Citizen of Vault City.}
{357900}{}{Scarecrow}
{357901}{}{This scarecrow might have been fashioned in the likeness of Lynette, the First Citizen of Vault City.}
{358000}{}{Scarecrow}
{358001}{}{This scarecrow might have been fashioned in the likeness of Lynette, the First Citizen of Vault City.}
{358100}{}{Scarecrow}
{358101}{}{This scarecrow might have been fashioned in the likeness of Lynette, the First Citizen of Vault City.}
{358200}{}{Scarecrow}
{358201}{}{This scarecrow might have been fashioned in the likeness of Lynette, the First Citizen of Vault City.}
{358300}{}{Poster}
{358400}{}{Poster}
{358500}{}{Poster}
{358600}{}{Poster}
{358700}{}{Poster}
{358800}{}{Poster}
{358900}{}{Poster}
{359000}{}{Poster}
{359100}{}{Poster}
{359200}{}{Poster}
{359300}{}{Poster}
{359400}{}{Poster}
{359500}{}{Poster}
{359600}{}{Poster}
{359700}{}{Poster}
{359800}{}{Tent}
{359900}{}{Poster}
{360000}{}{Poster}
{360100}{}{Poster}
{360200}{}{Poster}
{360300}{}{Poster}
{360400}{}{Poster}
{360500}{}{Flag}
{360600}{}{Poster}
{360700}{}{Flag}
{360800}{}{Poster}
{360900}{}{Tent}
{361000}{}{Poster}
{361100}{}{Tires}
{361200}{}{Car}
{361300}{}{Chair}
{361400}{}{Sign}
{361500}{}{Pool Table}
{361600}{}{Pool Table}
{361700}{}{Monitors}
{361800}{}{Monitors}
{361900}{}{Chair}
{362000}{}{Poster}
{362100}{}{Poster}
{362200}{}{Flag}
{362300}{}{Poster}
{362400}{}{Forklift}
{362500}{}{Forklift}
{362600}{}{Shelf}
{362700}{}{Shelf}
{362800}{}{Table}
{362900}{}{Stool}
{363000}{}{Car}
{363100}{}{Painting}
{363200}{}{Painting}
{363300}{}{Fuzzy Painting}
{363301}{}{An image of a singer. Obviously, very old. The image has a felt coating that is still in good condition.}
{363400}{}{Car}
{363500}{}{Painting}
{363600}{}{Painting}
{363700}{}{Painting}
{363800}{}{Painting}
{363900}{}{Painting}
{364000}{}{Painting}
{364100}{}{Painting}
{364200}{}{Painting}
{364300}{}{Painting}
{364400}{}{Painting}
{364500}{}{Bed}
{364600}{}{Bed}
{364700}{}{Bed}
{364800}{}{Bed}
{364900}{}{Chair}
{365000}{}{Chair}
{365100}{}{Chair}
{365200}{}{Chair}
{365300}{}{Chair}
{365400}{}{Chair}
{365500}{}{Chair}
{365600}{}{Chair}
{365700}{}{Sofa}
{365800}{}{Sofa}
{365900}{}{Sofa}
{366000}{}{Sofa}
{366100}{}{Sofa}
{366200}{}{Sofa}
{366300}{}{Sofa}
{366400}{}{Sofa}
{366500}{}{Wagon}
{366600}{}{Wagon}
{366700}{}{Monument}
{366800}{}{Monument}
{366900}{}{Table}
{367000}{}{Table}
{367100}{}{Vent}
{367200}{}{Vent}
{367300}{}{Vent}
{367400}{}{Vent}
{367500}{}{Machine}
{367600}{}{Machine}
{367700}{}{Machine}
{367800}{}{Machine}
{367900}{}{Machine}
{368000}{}{Machine}
{368100}{}{Wall}
{368200}{}{Wall}
{368300}{}{Desk}
{368400}{}{Desk}
{368500}{}{Desk}
{368600}{}{Desk}
{368700}{}{Desk}
{368800}{}{Desk}
{368900}{}{Desk}
{369000}{}{Desk}
{369100}{}{Chair}
{369200}{}{Chair}
{369300}{}{Chair}
{369400}{}{Chair}
{369500}{}{Computer}
{369600}{}{Sofa}
{369700}{}{Sofa}
{369800}{}{Monitor}
{369900}{}{Monitor}
{370000}{}{Monitor}
{370100}{}{Table}
{370200}{}{Computer Processing Core}
{370300}{}{Main Computer Core}
{370301}{}{The Reservation's main computer core.}
{370400}{}{Main Computer Core}
{370500}{}{Monitor}
{370600}{}{Chair}
{370700}{}{Sofa}
{370800}{}{Sofa}
{370900}{}{Chair}
{371000}{}{Computer}
{371100}{}{Computer}
{371200}{}{Table}
{371300}{}{Computer}
{371400}{}{Computer}
{371500}{}{Computer}
{371600}{}{Computer}
{371700}{}{Computer}
{371800}{}{Computer}
{371900}{}{Totem}
{372000}{}{Totem}
{372200}{}{Totem}
{372300}{}{Totem}
{372400}{}{Totem}
{372500}{}{Totem}
{372800}{}{Monitor}
{373100}{}{Totem}
{373200}{}{Totem}
{373300}{}{Totem}
{373400}{}{Altar}
{373500}{}{Altar}
{373600}{}{Circle of Rocks}
{373700}{}{Circle of Rocks}
{373800}{}{Rock}
{373900}{}{Rock}
{374000}{}{Totem}
{374100}{}{Totem}
{374200}{}{Totem}
{374300}{}{Totem}
{374400}{}{Nest}
{374401}{}{This huge nest was probably built by giant wasps or cazadores. Gulp!}
{374500}{}{Tractor}
{374501}{}{The tractor sits there silently, its once-proud frame now disintegrated and its engine scavenged.}
{374600}{}{Tractor}
{374601}{}{The tractor sits there silently, its once-proud frame now disintegrated and its engine scavenged.}
{374700}{}{Screen}
{374701}{}{A big screen showing some sort of a strategic map.}
{374800}{}{Klaxon}
{374900}{}{Klaxon}
{375000}{}{Table}
{375100}{}{Eddie Galenski's Truck}
{375101}{}{An armored long-hauler.}
{375200}{}{Weights}
{375201}{}{These are some REALLY heavy weights.}
{375300}{}{Sign}
{375400}{}{Machine}
{375500}{}{Bench}
{375600}{}{Bench}
{375700}{}{Bed Frame}
{375800}{}{Bed Frame}
{375900}{}{Bed Frame}
{376000}{}{Bed Frame}
{376100}{}{Bed Frame}
{376200}{}{Bed Frame}
{376300}{}{Bed Frame}
{376400}{}{Bed Frame}
{376500}{}{Bed}
{376600}{}{Bed}
{376700}{}{Bed}
{376800}{}{Bed}
{376900}{}{Bed}
{377000}{}{Door Entry Computer}
{377001}{}{This computer allows you to communicate with those inside the bunker. There's no way to enter a specific access code and control the blast door from here.}
{377100}{}{Road}
{377200}{}{Road}
{377300}{}{Road}
{377400}{}{Road}
{377500}{}{Road}
{377600}{}{Cliff}
{377700}{}{Cliff}
{377800}{}{Cliff}
{377900}{}{Cliff}
{378000}{}{Rocks}
{378100}{}{Rocks}
{378200}{}{Rocks}
{378300}{}{Oil Refinery Reactor}
{378301}{}{It's shut down.}
{378400}{}{Army Truck}
{378401}{}{An old husk of a completely looted army truck.}
{378500}{}{APC}
{378501}{}{A husk of a completely looted APC. Doesn't look drivable.}
{378600}{}{Radar Dish}
{378601}{}{It points towards west. You wonder why.}
{378700}{}{Windmill}
{378701}{}{This windmill is an integral part of the transformer system that powers the nearby water makers' condenser. Without it, the Ciphers' main water source would disappear.}
{378800}{}{Hoover Dam}
{378801}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{378900}{}{Hoover Dam}
{378901}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{379000}{}{Hoover Dam}
{379001}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{379100}{}{Hoover Dam}
{379101}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{379200}{}{Hoover Dam}
{379201}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{379300}{}{Hoover Dam}
{379301}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{379400}{}{Hoover Dam}
{379401}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{379500}{}{Hoover Dam}
{379501}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{379600}{}{Hoover Dam}
{379601}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{379700}{}{Hoover Dam}
{379701}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{379800}{}{Hoover Dam}
{379801}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{379900}{}{Hoover Dam}
{379901}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{380000}{}{Hoover Dam}
{380001}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{380100}{}{Hoover Dam}
{380101}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{380200}{}{Hoover Dam}
{380201}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{380300}{}{Hoover Dam}
{380301}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{380400}{}{Hoover Dam}
{380401}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{380500}{}{Hoover Dam}
{380501}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{380600}{}{Hoover Dam}
{380601}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{380700}{}{Hoover Dam}
{380701}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{380800}{}{Hoover Dam}
{380801}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{380900}{}{Hoover Dam}
{380901}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{381000}{}{Hoover Dam}
{381001}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{381100}{}{Hoover Dam}
{381101}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{381200}{}{Hoover Dam}
{381201}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{381300}{}{Hoover Dam}
{381301}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{381400}{}{Hoover Dam}
{381401}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{381500}{}{Hoover Dam}
{381501}{}{This is probably the biggest structure made out of cement in the whole wide world.}
{381600}{}{Wall}
{381700}{}{InstaCrate}
{381701}{}{This collapsible crate can also recharge robots.}
{381800}{}{Cliff}
{381900}{}{Tires}
{382000}{}{Police Car}
{382100}{}{Rocks}
{382200}{}{Rocks}
{382300}{}{Rocks}
{382400}{}{Rocks}
{382500}{}{Rocks}
{382600}{}{Rocks}
{382700}{}{Rocks}
{382800}{}{Rocks}
{382900}{}{Rocks}
{383000}{}{Rocks}
{383100}{}{Leaves}
{383200}{}{Planks}
{383300}{}{Tail}
{383400}{}{Tail}
{383500}{}{Door}
{383600}{}{Sign}
{383700}{}{Bridge}
{383800}{}{Vent}
{383900}{}{Wall}
{384000}{}{Sign}
{384100}{}{Crates}
{384200}{}{Plant}
{384201}{}{Could be a mutated soybean plant. Maybe.}
{384300}{}{Vending Machine}
{384400}{}{Think-Tank}
{384500}{}{Wall Light}
{384600}{}{Wall Light}
{384700}{}{Graffiti}
{384800}{}{Poster}
{384900}{}{Graffiti}
{385000}{}{Map}
{385100}{}{Graffiti}
{385800}{}{Pipe}
{385900}{}{Stand}
{386000}{}{Stand}
{386100}{}{Stand}
{386200}{}{Shadow}
{386300}{}{Barrel}
{386400}{}{Window}
{386500}{}{Board}
{386600}{}{Mountain}
{386700}{}{Mountain}
{386800}{}{Mountain}
{386900}{}{Mountain}
{387000}{}{Mountain}
{387100}{}{Mountain}
{387200}{}{Mountain}
{387300}{}{Mountain}
{387400}{}{Mountain}
{387500}{}{Mountain}
{387600}{}{Mountain}
{387700}{}{Mountain}
{387800}{}{Mountain}
{387900}{}{Railroad Crossing Sign}
{388000}{}{Lamp Post}
{388100}{}{Lamp Post}
{388200}{}{Lamp Post}
{388300}{}{Lamp Post}
{388400}{}{Road Sign}
{388500}{}{Sign}
{388501}{}{Military installation warning sign.}
{388600}{}{Mutated Pile of Flesh}
{388601}{}{This could be a lair of some sort.}
{388700}{}{Mutated Pile of Flesh}
{388701}{}{This could be a lair of some sort.}
{388800}{}{Mutated Pile of Flesh}
{388801}{}{This could be a lair of some sort.}
{388900}{}{Shadow}
{389000}{}{Cliff}
{389100}{}{Cliff}
{389200}{}{Cliff}
{389300}{}{Cliff}
{389400}{}{Railroad Crossing Sign}
{389500}{}{Railroad Crossing Sign}
{389600}{}{Signs}
{389601}{}{Warning signs informing trespassers to leave.}
{389700}{}{Radar}
{389800}{}{Newspaper Machine}
{389900}{}{Intercom}
{390000}{}{Tent}
{390100}{}{Riot Shields}
{390200}{}{Riot Shields}
{390300}{}{Riot Shield}
{390400}{}{Riot Shield}
{390500}{}{Roadblock}
{390600}{}{Roadblock}
{390700}{}{Roadblock}
{390800}{}{Roadblock}
{390900}{}{Tunnel}
{391000}{}{Tunnel Gate}
{391001}{}{It has been welded shut.}
{391100}{}{Console}
{391200}{}{Technical Board}
{391300}{}{Chalkboard}
{391400}{}{Chalkboard}
{391500}{}{Technical Poster}
{391600}{}{Rocks}
{391700}{}{Antron}
{391701}{}{A small, cleaning robot.}
{391800}{}{Klaxon}
{391900}{}{Lamp Post}
{392000}{}{Support Beans}
{392100}{}{Sign}
{392101}{}{The sign reads DRUG store.}
{392200}{}{Gate}
{392300}{}{Monitoring Computer}
{392301}{}{This computer monitors the life signs of nearby people.}
{392400}{}{Power Node}
{392500}{}{Complex}
{392600}{}{Complex}
{392700}{}{Complex}
{392800}{}{Complex}
{392900}{}{Complex}
{393000}{}{Complex}
{393100}{}{Complex}
{393200}{}{Complex}
{393300}{}{Planks}
{393400}{}{Bridge}
{393500}{}{Tires}
{393600}{}{Tires}
{393700}{}{Tires}
{393800}{}{Tires}
{393900}{}{Tires}
{394000}{}{Tires}
{394100}{}{Tires}
{394200}{}{Tires}
{394300}{}{Tires}
{394400}{}{Pipes}
{394500}{}{Pipes}
{394600}{}{Cliffs}
{394700}{}{Plant}
{394800}{}{Plant}
{394900}{}{Motorbike}
{395000}{}{Table}
{395100}{}{Table}
{395200}{}{Water}
{395300}{}{Sign}
{395400}{}{Sign}
{395500}{}{Sign}
{395600}{}{Sign}
{395700}{}{Sign}
{395800}{}{Wall}
{395801}{}{The high wall appears to be constructed from repurposed advertisement boards.}
{395900}{}{Wall}
{395901}{}{The high wall appears to be constructed from repurposed advertisement boards.}
{396000}{}{Wall}
{396001}{}{The high wall appears to be constructed from repurposed advertisement boards.}
{396100}{}{Stuff}
{396200}{}{Piano}
{396300}{}{Sign}
{396400}{}{Sign}
{396500}{}{Sign}
{396600}{}{Technical Drawings}
{396700}{}{Land Mines Warning Sign}
{396800}{}{Land Mines Warning Sign}
{396900}{}{Radiation Warning Sign}
{397000}{}{Radiation Warning Sign}
{397100}{}{Lamp Post}
{397200}{}{Electrical Pole}
{397300}{}{Electrical Pole}
{397400}{}{Broken Beans}
{397500}{}{Broken Beans}
{397600}{}{Mechanical Elevator}
{397601}{}{This elevator connects the upper and lower parts of Hoover Dam.}
{397700}{}{Feeding Machine}
{397701}{}{You see a machine that feeds the prisoners using robotic arms.}
{397800}{}{Feeding Machine}
{397801}{}{You see a machine that feeds the prisoners using robotic arms.}
{397900}{}{Computer}
{398000}{}{Display}
{398100}{}{Movie}
{398101}{}{A very old Civil Defense movie.}
{398200}{}{Motorbike}
{398300}{}{Motorbike}
{398400}{}{Motorbike}
{398500}{}{Motorbike}
{398600}{}{Equipment}
{398601}{}{It could be a winch. You're not exactly sure.}
{398700}{}{Machine}
{398800}{}{Intercom}
{398900}{}{Pumpkin}
{398901}{}{Boo! Someone made a Halloween pumpkin.}
{399000}{}{Plant}
{399900}{}{Map}
{400000}{}{Sub-Reactor}
{400100}{}{Sub-Reactor}
{400200}{}{Bench}
{400300}{}{Bench}
{400400}{}{Bench}
{400500}{}{Bench}
{400600}{}{Bench}
{400700}{}{Fan}
{400800}{}{Fan}
{400900}{}{Drain}
{400901}{}{Exercise caution with your steps around here.}
{401000}{}{Corner}
{401100}{}{Corner}
{401200}{}{Corner}
{401300}{}{Corner}
{401400}{}{Corner}
{402500}{}{Sunken Building}
{402600}{}{Sunken Building}
{402700}{}{Sunken Building}
{402800}{}{Lamp Post}
{402900}{}{Lamp Post}
{403000}{}{Support Beans}
{403100}{}{Support Beans}
{403200}{}{Broken Pillar}
{403201}{}{A powerful blast broke this pillar into pieces.}
{403300}{}{Broken Pillar}
{403301}{}{The melted plague indicates that this ruin might have been a library or a museum.}
{403400}{}{Broken Pillar}
{403401}{}{The melted plague indicates that this ruin might have been a library or a museum.}
{403500}{}{Broken Pillar}
{403501}{}{The melted plague indicates that this ruin might have been a library or a museum.}
{403600}{}{Broken Pillar}
{403601}{}{A powerful blast broke this pillar into pieces.}
{403700}{}{Broken Pillar}
{403701}{}{A powerful blast broke this pillar into pieces.}
{403800}{}{Broken Pillar}
{403801}{}{The clock stopped at 9:47:51 A.M.}
{403900}{}{Frozen Cart}
{404000}{}{Display Shelf}
{404100}{}{Broken Display Shelf}
{404200}{}{Roadblock}
{404300}{}{Roadblock}
{404400}{}{Roadblock}
{404500}{}{Roadblock}
{404600}{}{Roadblock}
{404700}{}{Roadblock}
{404800}{}{Computer}
{404900}{}{Motorbike}
{405000}{}{Glowing Barrel}
{405001}{}{Some glowing green mushrooms are growing around this barrel.}
{405100}{}{"The Shortcut"}
{405101}{}{Air tram that connects Grand Canyon's South and North Rim.}
{405200}{}{Gas Tank}
{405201}{}{A small tank of volatile gas. Highly flammable.}
{405300}{}{Ladder}
{405400}{}{Ladder}
{405500}{}{Wheelbarrow}
{405600}{}{Campfire}
{405700}{}{Bucket}
{405800}{}{Vent}
{405900}{}{Door}
{406000}{}{Valkyrie}
{406001}{}{You've never seen a flying aircraft before. It's both scary and makes you wonder what it feels like to soar like a bird. The label reads "Valkyrie."}
{406100}{}{Targeting Computer Console}
{406101}{}{This console is used to access the targeting computer.}
{406200}{}{Escape Pod Hatch}
{406201}{}{This tunnel leads to an escape pod.}
{406300}{}{Goddess Diana}
{406400}{}{Generator Hole}
{406401}{}{You see an open hole where a generator used to be. Toxic goo bubbles and oozes from it.}
{406500}{}{Pole}
{406501}{}{This metal pole spans from floor to ceiling, yet it definitively isn't used for support.}
{406600}{}{Stripper}
{406601}{}{Oh. My. God.}
{406700}{}{Stripper}
{406701}{}{Oh. My. God.}
{406800}{}{Gate}
{406900}{}{Bike}
{407000}{}{Truck}
{407200}{}{Power Armor}
{407201}{}{A self-contained suit of advanced technology armor. Powered by a micro-fusion reactor, with enough fuel to last a hundred years.}
{407300}{}{Cryobed}
{407400}{}{Cryobed}
{407500}{}{Impaled Corpse}
{407600}{}{Impaled Corpse}
{407700}{}{Table}
{407800}{}{Tank}
{407900}{}{Bush}
{408000}{}{Bush}
{408100}{}{Bush}
{408200}{}{Bush}
{408300}{}{Bush}
{408400}{}{Bush}
{408500}{}{Bush}
{408600}{}{Bush}
{408700}{}{Bush}
