#
# Quest descriptons
#
# Please leave space between the areas (like 100 or so)
# Grammar pass done

#
# Tibbets Quests
#
{100}{}{Meet ODYSSEUS and attend your trial.}
{110}{}{Reach the entrance to the Vault.}
{120}{}{Search the red brick building for loot.}
{130}{}{Exit Tibbets.}
{140}{}{Restore life support systems.}
{141}{}{Repair the generator.}
{142}{}{Fix the floating eye bot.}
{143}{}{Liberate the Rainmakers.}
{144}{}{Investigate the "Trial by Dynamite."}
{145}{}{Locate the rare .50 Magnum Revolver.}
{146}{}{Find a new "home" for the Vault Boy hologram.}
{147}{}{Look into the disturbance in Service Level East.}
{148}{}{Provide an update on ODYSSEUS' status regarding the 13 unaccounted-for prisoners.}
{149}{}{Find Prisoner 31: Victor Presper.}
{150}{}{Find Prisoner 32: Sean Coleridge.}
{151}{}{Find Prisoner 34: Martin Pierce.}
{152}{}{Find Prisoner 35: Adam Davidson.}
{153}{}{Find Prisoner 33: Robert "Border" Briggs.}
{154}{}{Find Prisoner 634: Jean-Baptiste Cutting.}
{155}{}{Find Prisoner 9833: Jillian McKinley.}
{156}{}{Find Prisoner 7630: Chagas.}
{157}{}{Find Prisoner 21: Blackjack.}
{158}{}{Find Prisoner 97209: Daniel.}
{159}{}{Find Prisoner 31470: Mallet McBride.}
{160}{}{Find Prisoner 112: Ginger Flowers.}
{161}{}{Find Prisoner 404: Akeisha Moon.}

#
# Boulder Dome Quests
#
{200}{}{}


#
# Dogtown Quests
#
{300}{}{}


#
# Circle Junction Quests
#
{400}{}{}


#
# Fort Abandon Quests
#
{500}{}{Get rid of Caesar's Legion.}

#
# Blackfoot Quests
#
{600}{}{}


#
# Mesa Verde Quests
#
{700}{}{Deal with the Hounds of Hecate.}
{701}{}{Acquire the Ciphers' enriched uranium.}
{702}{}{Ask the Ciphers to process ZAX's raw data.}
{703}{}{Sabotage Mesa Verde's wind turbine.}
{704}{}{Forge an alliance between the Brotherhood and the Ciphers.}
{705}{}{Repair the computer so the Ciphers can access the old knowledge.}
{706}{}{Cure Radian's illness.}
{707}{}{Figure out what Denom did to the crops.}
{708}{}{Get more food to the Ciphers.}
{709}{}{Restore the crop fields with the Miracle Wheat.}
{710}{}{Rescue the captured Ciphers.}
{711}{}{Bring a G.E.C.K. to Isaac in exchange for his power armor.}
{712}{}{Resolve the Alexandra-Blackjack situation.}
{713}{}{Kill the weedlings.}
{714}{}{Build an alarm for Trig.}

#
# Twin Mothers Quests
#
{800}{}{}


#
# Brotherhood of Steel Quests
#
{900}{}{Administer treatment to the Commander.}
{901}{}{Identify the poisoner.}
{902}{}{Locate Devon's contacts.}
{903}{}{Search for the Circle of Steel.}
{904}{}{Undertake Operation Peacemaker: Bring an end to the Brotherhood-NCR war.}
{905}{}{Fix the malfunctioning forklift on Level 1.}
{906}{}{Repair the damaged vent on Level 1.}
{907}{}{Restore functionality to the faulty computer on Level 2.}
{908}{}{Fix the malfunctioning memory banks on Level 2.}
{909}{}{Repair the water chip on Level 2.}
{910}{}{Establish a trade route with one of Hoover Dam's caravans.}
{911}{}{Retrieve the lost armory codes.}

#
# Hoover Dam Quests
#
{1000}{}{Secure a meeting with Governor Dodge.}
{1001}{}{Successfully negotiate peace between the NCR and the Brotherhood.}
{1002}{}{Ensure City Council members attend City Hall meetings.}
{1003}{}{Join forces with the 3-Some Caravan Company.}
{1004}{}{Spy successfully on the Crimson Caravan for the 3-Some Caravan Company.}
{1005}{}{Infiltrate the Crimson Caravan as a spy for the 3-Some Caravan Company.}
{1006}{}{Successfully frame the 3-Some Caravan Company.}
{1007}{}{Extort money successfully from Ailis.}
{1008}{}{Expose the Crimson Caravan's activities.}
{1009}{}{Provide filtration schematics to engineers.}
{1010}{}{Increase school attendance.}
{1011}{}{Teach a survival class.}
{1012}{}{Eliminate hostile mutants in the Scum Pits.}
{1013}{}{Procure building materials for the hydroponics lab.}
{1014}{}{Discover the lost Sub-Level-1-Classified.}
{1015}{}{Discover the pre-war history of Hoover Dam and S1C.}
{1016}{}{Share Hoover Dam's pre-war history with Candice.}
{1017}{}{Get Mary-Jo to stop turning tricks.}
{1018}{}{Help Beatrice in a bar fight.}
{1019}{}{Take on Bob's bounty hunter assignment: Craig.}
{1020}{}{Eradicate hostile mutants in S1C.}
{1021}{}{Adjust the calibration of the two functioning generators.}
{1022}{}{Take on Bob's bounty hunter assignment: El Diablo.}
{1023}{}{Take on Bob's bounty hunter assignment: Nancy Haggard.}
{1024}{}{Take on Bob's bounty hunter assignment: Ingmar.}
{1025}{}{Take on Bob's bounty hunter assignment: Kyle the Hook.}
{1026}{}{Take on Bob's bounty hunter assignment: Ryan Mitchell.}
{1027}{}{Help Pablo with his supply issue.}
{1028}{}{Fix Dr. Yuri's Auto-Doc.}
{1029}{}{Help Dr. Yuri restock his medical supplies.}
{1030}{}{Meet with "C." at Fort Desolation.}
{1031}{}{Inform the Quartermaster about her shipment's arrival.}

#
# Ouroboros Quests
#
{1100}{}{}

#
# The Reservation Quests
#
{1200}{}{}

#
# Burham Springs Quests
#
{1300}{}{}

#
# The Nursery Quests
#
{1400}{}{}

#
# Bloomfield Space Center Quests
#
{1500}{}{Enhance the Sub-Reactor's efficiency to a range of 60% to 85%}
{1501}{}{Fly to B.O.M.B.-001 and confront Presper.}
{1502}{}{Enter valid Mission Control computer Access Codes.}
{1503}{}{Input Hermes-13's flight data.}
{1504}{}{Repair Hermes-13's engine fault.}
{1505}{}{Acquire rocket fuel for Hermes-13.}
{1506}{}{Input authentic Mission Control Launch Codes.}
{1507}{}{Repair Docking Clamp Control.}

#
# The Grand Canyon Quests
#
{1600}{}{}

#
# Jericho Quests
#
{1700}{}{}

#
# New Canaan Quests
#
{1800}{}{}

#
# Hangdogs Quests
#
{1900}{}{}

#
# EPA Quests
#
{2000}{}{}

#
# Ghost Town Quests
#
{2100}{}{}

#
# Car outta Gas Quests
#
{2200}{}{}

#
# Destroyed Arroyo Quests
#
{2300}{}{}

#
# Toxic Caves Quests
#
{2400}{}{}

#
# Den Slave Run Quests
#
{2500}{}{}

#
# Raiders Quests
#
{2600}{}{}

#
# Desert Encounter Quests
#
{2700}{}{}

#
# Mountain Encounter Quests
#
{2800}{}{}

#
# Ruined City Encounter Quests
#
{2900}{}{}

#
# Coast Encounter Quests
#
{3000}{}{}

#
# Golgotha Quests
#
{3100}{}{}


#
# Vault 15 Quests
#
{3200}{}{}

