/*

        Name:           Carib
        Location:       Radspider Caves
        Description:    Special Encounter

           Created: 21/07/2020 21:59:53

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_CARIB
#define OUTSIDE                 (20762)
#define MVAR_BOMB                     (0)

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (0)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\HEADERS\footsteps.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure push_p_proc;

procedure leave_player;
procedure leave_player_angry;
procedure CaribFollowPlayer;
procedure NodeBarter;

/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Follow_Dude                (8)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;
variable dtile;
variable dlev;
variable mytile;
variable mylev;
variable newtile;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   switch_team(self_obj,TEAM_CARIB)
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
   call new_plague_check(self_obj, LVAR_Herebefore);

      if (map_var(MVAR_BOMB) == 1) then begin
        //he is gone
        move_to(self_obj,0,0);
        set_obj_visibility(self_obj,1);
        destroy_object(self_obj);
      end
      else begin
         //he is here
        set_obj_visibility(self_obj, 0);
      end

      call critter_setup_footsteps_map_enter(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT);
end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and self_can_see_dude and obj_is_visible_flag(self_obj)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end
   else if (local_var(LVAR_Follow_Dude) == 1) then begin

   if ( ((tile_distance(self_tile, OUTSIDE)) < 5 ) and (self_elevation == 1) ) then begin
      call leave_player;
   end
   else if (dude_elevation != self_elevation) then begin
      call leave_player;
   end
   else begin
      if (tile_distance(self_tile,dude_tile) > 6) then begin
         newtile:=tile_num_in_direction(dude_tile, random(0,5), 1);
         animate_run_to_tile(newtile);
      end
   end
end//follow

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
       call leave_player_angry;
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
       call leave_player_angry;
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_VERY_INTOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

   if (local_var(LVAR_Follow_Dude) == 1) then begin
      floater_whisper(108);
   end
   else if (map_var(MVAR_BOMB) == 1) then begin
      floater_good(106);
   end
   else begin
       call set_idiot_savant_int;
       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;
       call Node001;
       gSay_End;
       end_dialogue;
       call restore_idiot_savant_int;
   end
end

procedure timed_event_p_proc begin
   call critter_setup_footsteps_timed_event(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT, SFX_FOOTSTEP_MEDIUM_SHOE);
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_good_critter

/* Set global_variable for Enemy status*/
end


procedure combat_p_proc begin
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
if (local_var(LVAR_Herebefore) == 0) then Reply(200); else Reply(199);
NOption(mstr(201)+dude_name+mstr(202),Node002,4);
if (obj_is_carrying_obj_pid(self_obj,PID_RAD_X)>0) then
NOption(203,Node003,4);
NOption(204,Node004,4);
if(not(has_fake_trait(TRAIT_pacifist))) then begin
NOption(205,Node009,4);
BOption(206,Node998,4);
end
NOption(207,Node999,4);
NOption(mstr(208)+dude_name+mstr(209),Node002,-3);
NOption(210,Node999,-3);
end

procedure Node002
begin
Reply(230);
NOption(231,Node010,4);
NOption(232,CaribFollowPlayer,4);
NOption(233,Node999,4);
NOption(234,CaribFollowPlayer,-3);
NOption(235,Node010,-3);
NOption(236,Node999,-3);
end

procedure Node003
begin
Reply(260);
NOption(261,NodeBarter,4);
NOption(262,Node010,4);
end

procedure Node004
begin
Reply(290);
NOption(291,Node005,4);
NOption(292,Node007,4);
NOption(293,Node005,-3);
NOption(294,Node007,-3);
end

procedure Node005
begin
if (not(dude_is_super_mutant)) then Reply(320); else
if (dude_is_super_mutant) then Reply(321);
NOption(322,Node015,4);
if(has_fake_trait(TRAIT_big_liar)) then
NOption(323,Node015,4);
if (dude_is_super_mutant) then begin
NOption(324,Node008,4);
NOption(325,Node008,-3);
end
NOption(326,Node006,1);
NOption(327,Node010,4);
NOption(328,Node010,-3);
end

procedure Node006
begin
fadeout(1);
game_time_advance(ONE_GAME_HOUR * 2);
fadein(1);
Reply(350);
NOption(351,Node009,4);
NOption(352,Node010,4);
NOption(353,Node010,4);
if (dude_is_super_mutant) then begin
NOption(354,Node016,4);
NOption(355,Node016,-3);
end
BOption(356,Node998,-3);
NOption(328,Node010,-3);
end

procedure Node007
begin
   set_global_var(GVAR_CARIB_MENTIONED_NCR_RANGERS, 1);

Reply(380);
NOption(381,Node011,4);
NOption(382,Node010,4);
NOption(383,Node009,-3);
NOption(384,Node011,-3);
end

procedure Node008
begin
Reply(410);
NOption(411,CaribFollowPlayer,4);
NOption(412,CaribFollowPlayer,-3);
NOption(413,Node010,4);
NOption(414,Node010,-3);
end

procedure Node009
begin
Reply(440);
NOption(441,Node010,4);
NOption(442,Node010,-3);
NOption(443,CaribFollowPlayer,1);
end

procedure Node010
begin
Reply(470);
NOption(471,Node003,4);
NOption(472,Node002,4);
NOption(473,Node011,4);
NOption(474,Node999,4);
NOption(475,CaribFollowPlayer,4);
BOption(476,Node998,4);
NOption(477,Node002,-3);
NOption(478,Node011,-3);
NOption(210,Node999,-3);
BOption(479,Node998,-3);
NOption(480,CaribFollowPlayer,-3);
end

procedure Node011
begin
Reply(500);
NOption(501,Node018,4);
NOption(502,Node014,4);
NOption(503,Node012,4);
NOption(504,Node004,4);
NOption(mstr(505)+dude_name+mstr(506),Node004,-3);
NOption(507,Node014,-3);
NOption(508,Node012,-3);
NOption(509,Node018,-3);
end

procedure Node012
begin
Reply(530);
BOption(531,Node998,1);
NOption(532,Node009,1);
if(not(has_fake_trait(TRAIT_soothsayer))) then
NOption(533,Node013,4);
NOption(534,Node013,-3);
end

procedure Node013
begin
Reply(560);
NOption(561,CaribFollowPlayer,4);
NOption(562,Node999,4);
NOption(563,CaribFollowPlayer,-3);
NOption(564,Node999,-3);
end

procedure Node014
begin
Reply(590);
NOption(591,Node999,4);
NOption(592,Node010,4);
NOption(593,Node999,-3);
NOption(594,Node010,-3);
end

procedure Node015
begin
Reply(620);
NOption(621,Node006,1);
end

procedure Node016
begin
Reply(650);
NOption(651,Node010,4);
NOption(652,CaribFollowPlayer,4);
NOption(653,Node999,4);
NOption(654,CaribFollowPlayer,-3);
NOption(655,Node999,-3);
NOption(656,Node010,-3);
end

procedure Node017
begin
Reply(680);
NOption(681,CaribFollowPlayer,4);
NOption(682,Node999,4);
NOption(683,Node010,4);
NOption(684,CaribFollowPlayer,-3);
NOption(685,Node999,-3);
NOption(686,Node010,-3);
end

procedure Node018
begin
Reply(710);
BOption(711,Node998,4);
NOption(712,Node014,4);
if(not(has_fake_trait(TRAIT_soothsayer))) then
   NOption(713,Node013,4);
   BOption(714,Node998,-3);
NOption(715,Node014,-3);
if(not(has_fake_trait(TRAIT_soothsayer))) then
   NOption(716,Node013,-3);
end


procedure leave_player begin
   variable cavein;
   if ( (local_var(LVAR_Follow_Dude) == 1) and (map_var(MVAR_BOMB) == 0) ) then begin
      set_local_var(LVAR_Follow_Dude, 0);
      set_map_var(MVAR_BOMB, 1);
      switch_team(self_obj,TEAM_CARIB)
      floater_good(105);
      fadeout(1);
      cavein := play_sfall_sound("data\\sound\\SFX\\cavein.wav", 0);
      fadein(1);
   end
end

procedure leave_player_angry begin
   if ( (local_var(LVAR_Follow_Dude) == 1)) then begin
      switch_team(self_obj,TEAM_CARIB)
      set_local_var(LVAR_Follow_Dude, 0);
   end

   floater_bad(109);
end

procedure CaribFollowPlayer begin
   set_local_var(LVAR_Follow_Dude, 1);
   switch_team(self_obj,TEAM_PLAYER)
   call Node999;
end

procedure NodeBarter begin
   gdialog_barter;
   call Node010;
end

procedure push_p_proc begin
   floater_bad(107);
end

//xxxxxxxxxxxxxxxxxxxx
