/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/*
        Name: Generic Lesser Rat
        Location: Arroyo
        Description: Generic lesser rat when you need a small, not very strong rat.

        Log:

           Created: December 02, 1997

           Updated:
*/

/* Include Files */

#include "..\headers\define.h"
//#include "..\headers\<TownName.h>"

#define NAME                    SCRIPT_ECNITECR

#include "..\headers\command.h"
//#include "..\headers\ModReact.h"
#include "..\headers\party.h"

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure combat_p_proc;
procedure map_exit_p_proc;

/* Local variables which do not need to be saved between map changes. */
variable pissed:=false;
variable starttile;

procedure start begin
end

procedure combat_p_proc begin
   if (fixed_param == COMBAT_SUBTYPE_HIT_SUCCEEDED) then begin
//       if (target_obj == dude_obj) then begin
           poison(target_obj,random(1,18));
  //     end
   end
end

procedure critter_p_proc begin
   // it attacks if it sees the player
   if (self_can_see_dude) then begin
         pissed := true;
         self_attack_dude;
   end

   if (not(anim_busy(self_obj)) and not(combat_is_initialized) and ((critter_state(self_obj) bwand DAM_KNOCKED_OUT) == FALSE)) then begin
      reg_anim_clear(self_obj);
      reg_anim_begin();
      animate_move_to_tile(tile_num_in_direction(starttile, Random(0, 5), Random(1, 3)));
      reg_anim_end();
   end
end

procedure destroy_p_proc begin
   inc_neutral_critter
end

procedure damage_p_proc begin
   if (pissed == false) then begin
      pissed := true;
      self_attack_dude;
   end
end

procedure look_at_p_proc begin
end

procedure description_p_proc begin
   call BeastlordPossess;
end

procedure use_obj_on_p_proc begin
end

procedure use_skill_on_p_proc begin
   if (action_being_used == SKILL_STEAL) then begin
      script_overrides;
   end
   call injure_with_skill;
end

procedure map_enter_p_proc begin
   variable item;
   starttile = self_tile;

   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_RND_NIGHTCRAWLERS);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_SPORE_PLANT);

   if (map_first_run) then begin
       item:=create_object(PID_NIGHTCRAWLER_SPITBALL,0,0);
       add_mult_objs_to_inven(self_obj,item,random(15,25));
   end
end

procedure map_exit_p_proc begin
   call BeastlordUnpossess(TEAM_RND_NIGHTCRAWLERS);
end
