/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/* Random Encounter scripts.
*/

procedure start;

#include "..\headers\define.h"

#define NAME                    SCRIPT_ECTHNBRD

#include "..\headers\command.h"
#include "..\headers\party.h"

procedure start;
procedure critter_p_proc;
procedure map_enter_p_proc;
procedure combat_p_proc;
procedure destroy_p_proc;
procedure timed_event_p_proc;
procedure use_skill_on_p_proc;

procedure start begin
end

procedure map_enter_p_proc begin
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_THUNDERBIRD);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_END_BOSS);
   add_timer_event(self_obj,game_ticks(random(5,15)),0);
end

procedure critter_p_proc begin
   if (self_can_see_dude) then begin
      self_attack_dude;
   end
end

procedure combat_p_proc begin
   if (fixed_param == COMBAT_SUBTYPE_HIT_SUCCEEDED) then begin
      if ((target_obj == dude_obj) and not(dude_immune_to_radiation)) then begin
         if (not(is_success(do_check(target_obj,STAT_lu,-1)))) then begin
            radiation_inc(target_obj,random(10,40));
         end
      end
   end
end

procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_neutral_critter

/* Set global_variable for Enemy status*/
end

procedure timed_event_p_proc begin
   if ((not(combat_is_initialized)) and ((critter_state(self_obj) bwand DAM_KNOCKED_OUT) == FALSE)) then begin
      reg_anim_clear(self_obj);
      reg_anim_begin();
      animate_move_to_tile(tile_num_in_direction(tile_num(self_obj),random(0,5),random(5,15)));
      reg_anim_end();
   end
   add_timer_event(self_obj,game_ticks(random(5,15)),0);
end

procedure use_skill_on_p_proc begin
   call injure_with_skill;
end
