/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/*
        Name: Generic Lesser Rat
        Location: Arroyo
        Description: Generic lesser rat when you need a small, not very strong rat.

        Log:

           Created: December 02, 1997

           Updated:
*/

/* Include Files */

#include "..\headers\define.h"
//#include "..\headers\<TownName.h>"

#define NAME                    SCRIPT_MILKY

#include "..\headers\command.h"
//#include "..\headers\ModReact.h"

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure combat_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;

/* Local variables which do not need to be saved between map changes. */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)

procedure start begin
end

procedure combat_p_proc begin
   if(cur_map_index == MAP_SPECIAL_RND_PET_CEMETERY) then
   script_overrides;
end


procedure timed_event_p_proc begin
   if (obj_is_visible_flag(self_obj) and (not(combat_is_initialized)) and ((critter_state(self_obj) bwand DAM_KNOCKED_OUT) == FALSE) and random(1,4) == 1) then begin
      reg_anim_clear(self_obj);
      reg_anim_begin();
         animate_move_to_tile(tile_num_in_direction(tile_num(self_obj),random(0,5),random(1,3)));
      reg_anim_end();
   end
   add_timer_event(self_obj,game_ticks(random(3,5)),0);
end

procedure critter_p_proc begin
    script_overrides;
      if (local_var(LVAR_Hostile) != 0 and cur_map_index == MAP_SPECIAL_RND_PET_CEMETERY) then begin
         set_local_var(LVAR_Hostile,0);
      end
end

procedure destroy_p_proc begin
end

procedure damage_p_proc begin
   if(cur_map_index == MAP_SPECIAL_RND_PET_CEMETERY) then
    script_overrides;
end

procedure look_at_p_proc begin
end

procedure description_p_proc begin
end

procedure use_obj_on_p_proc begin
end

procedure use_skill_on_p_proc begin
      script_overrides;
end
procedure map_exit_p_proc begin
   if (cur_map_index == MAP_SPECIAL_RND_PULOWSKIS) then
      destroy_object(self_obj);
 end
procedure map_enter_p_proc begin

   if(cur_map_index == MAP_SPECIAL_RND_PET_CEMETERY) then begin
      if(random(1,5) == 1) then begin
         set_obj_visibility(self_obj, 0);
      end else begin
         set_obj_visibility(self_obj, 1);
         return;
      end
   end
   if (cur_map_index == MAP_SPECIAL_RND_PULOWSKIS) then
      critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_KAZUMA);


   add_timer_event(self_obj,game_ticks(random(1,5)),0);
end
