/*

        Name:           Cranium Rat
        Location:
        Description:

           Created: 25/10/2020 13:50:21

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
#include "..\HEADERS\secrmap.h"

#define NAME                    SCRIPT_SECRARAT

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (0)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure combat_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure LeavePeace;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)

#define POISON_MIN              (1)
#define POISON_MAX              (4)
#define RAD_MIN                 (1)
#define RAD_MAX                 (4)


/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_CRANIUM_RATS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
   add_timer_event(self_obj, game_ticks(random(1,5)), 0);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin
/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if (self_can_see_dude or self_can_hear_dude) then begin
      if (local_var(LVAR_Hostile) != 0) then begin
         set_local_var(LVAR_Hostile,1);
          self_attack_dude;
          //Macro made by Tom to keep the critter fleeing.
      end else begin
         if(
            (map_var(MVAR_CRANIUM_RATS_TALKER) == 0) and
            self_can_speak
            ) then begin
            set_map_var(MVAR_CRANIUM_RATS_TALKER, 1);
            dialogue_system_enter;
         end
      end
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=1;
   Slavery_Tolerant:=SLAVE_PROUD;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;


if(map_var(MVAR_CRANIUM_RATS_LEAVE) == 1) then begin
      floater_whisper_rand(150, 155);
   end else begin
      call set_idiot_savant_int;
         start_gdialog(NAME,self_obj,4,-1,-1);
         gSay_Start;
         call Node001;
         gSay_End;
         end_dialogue;
      call restore_idiot_savant_int;
   end

end

procedure timed_event_p_proc begin

   if (fixed_param == 0) then begin

      if(self_tile == 19740) then begin
         set_obj_visibility(self_obj, 1);
         destroy_object(self_obj);
      end
      else if(map_var(MVAR_CRANIUM_RATS_LEAVE) == 1) then begin

         if(random(1, 40) == 1) then begin
            floater_whisper_rand(150, 155);
         end

         animate_move_to_tile(19740);
      end

      add_timer_event(self_obj, game_ticks(random(1,5)), 0);

   end

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_evil_critter

/* Set global_variable for Enemy status*/
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

procedure combat_p_proc begin
   if (fixed_param == COMBAT_SUBTYPE_HIT_SUCCEEDED) then begin
           poison(target_obj,random(POISON_MIN,POISON_MAX));
         if ((target_obj == dude_obj) and not(dude_immune_to_radiation)) then begin
           radiation_inc(target_obj,random(RAD_MIN,RAD_MAX));
         end
   end
end


/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
Reply(200);
GOption(201,Node003,4);
BOption(202,Node002,4);
GOption(203,Node003,-3);
BOption(204,Node002,-3);
end

procedure Node002
begin
Reply(230);
BOption(231,Node998,1);
end

procedure Node003
begin
Reply(260);
GOption(261,LeavePeace,4);
BOption(262,Node002,4);
GOption(263,LeavePeace,-3);
BOption(264,Node002,-3);
GOption(265,LeavePeace,1);
end

procedure LeavePeace begin
   set_map_var(MVAR_CRANIUM_RATS_LEAVE, 1);
   call Node999;
end

//xxxxxxxxxxxxxxxxxxxx
