/*

        Name:
        Location:
        Description:

           Created: 15.12.2023. 19:50:04

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_SEEDTRK2

import variable se_ed_truck_fixed;

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (0)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure talk_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure use_p_proc;
procedure use_obj_on_p_proc;

/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure DriveToBloomfield;
procedure StealTruck;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure use_p_proc begin
   if (source_obj == dude_obj) then
      dialogue_system_enter;
end

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   se_ed_truck_fixed := self_obj;

   if (cur_map_index == MAP_SPECIAL_RND_EDDIE) then begin
      if(global_var(GVAR_FIX_EDDIE_TRUCK) >= 1) then
         set_obj_visibility(self_obj, 0);
      else if(global_var(GVAR_STEAL_EDDIE_TRUCK) == 1) then
         set_obj_visibility(self_obj, 1);
      else if(global_var(GVAR_QUEST_15_HERMES13_FUEL) == 3) then
         set_obj_visibility(self_obj, 1);
      else
         set_obj_visibility(self_obj, 1);
   end
   else if (cur_map_index == MAP_BLOOMFIELD_FUEL_TANKS) then begin
      if(global_var(GVAR_QUEST_15_HERMES13_FUEL) >= 2) then
         set_obj_visibility(self_obj, 0);
      else
         set_obj_visibility(self_obj, 1);
   end

//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;
       call Node001;
       gSay_End;
       end_dialogue;

   call restore_idiot_savant_int;

   if (Only_Once == 1) then begin
      load_map("scfuel", 0);
   end

end

procedure timed_event_p_proc begin
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin

end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures




procedure use_obj_on_p_proc begin

   if (obj_pid(obj_being_used_with) == PID_TRUCK_KEY) then begin
      script_overrides;
      dialogue_system_enter;
   end

end

// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
Reply(200);
if (
   ((global_var(GVAR_QUEST_15_HERMES13_FUEL) == 1) or (global_var(GVAR_QUEST_15_HERMES13_FUEL) == 2 )) and
   cur_map_index == MAP_SPECIAL_RND_EDDIE
   ) then begin
   if ((global_var(GVAR_EDDIE_GALENSKI_DEAD) == 0) and (global_var(GVAR_QUEST_15_HERMES13_FUEL) == 2)) then
      NOption(201,DriveToBloomfield,1);
   if (dude_item_count(PID_TRUCK_KEY)>0) then
      NOption(202,StealTruck,1);
   if (has_skill(dude_obj,SKILL_REPAIR)>=50) then
      NOption(203,StealTruck,1);
end
NOption(204,Node999,1);
end

procedure DriveToBloomfield begin
   fadeout(1);
   // Two weeks operation
   game_time_advance(14 * ONE_GAME_DAY);
   // Some XP
   give_xp(1000);
   display_mstr(150);
   set_global_var(GVAR_QUEST_15_HERMES13_FUEL, 3);
   Only_Once = 1;
end

procedure StealTruck begin
   set_global_var(GVAR_STEAL_EDDIE_TRUCK, 1);
   call DriveToBloomfield;
end

//xxxxxxxxxxxxxxxxxxxx
