/*

        Name:           Jacob
        Location:
        Description:

           Created: 01/09/2020 23:37:50

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_SEJACOB

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (0)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node004a;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Robbed               (8)
#define LVAR_Healed               (9)
#define LVAR_Pissed               (10)

variable Only_Once:=0;


/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;

if(local_var(LVAR_Herebefore) >= 1) then begin
      set_obj_visibility(self_obj, 1);
      destroy_object(self_obj);
   end

   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_JACOB);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);

critter_injure(self_obj, DAM_CRIP_ARM_RIGHT);

set_global_var(GVAR_SPECIAL_ENCOUNTER_JACOB, 1);
call new_plague_check(self_obj, LVAR_Herebefore);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude) and obj_is_visible_flag(self_obj)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_INTOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

   if(local_var(LVAR_Robbed) == 1) then begin
      floater_afraid(105);
      return;
   end

 if(local_var(LVAR_Pissed) == 1) then begin
      floater_afraid(108);
      return;
   end

   if(local_var(LVAR_Healed) == 1) then begin
      if(dude_is_male) then begin
         floater_good(106);
      end else begin
         floater_good(107);
      end
      return;
   end


   call set_idiot_savant_int;
start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;
if (local_var(LVAR_Herebefore)==1) then begin
       call Node006;
end else begin
       call Node001;
end
       gSay_End;
       end_dialogue;


   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

procedure GiveAll begin

      transfer_pid_between_objs(self_obj, dude_obj, PID_10MM_PISTOL, 1)
      transfer_pid_between_objs(self_obj, dude_obj, PID_PUMP_PARTS, 1)
      transfer_pid_between_objs(self_obj, dude_obj, PID_SMALL_ENERGY_CELL, 1)
      transfer_pid_between_objs(self_obj, dude_obj, PID_BOX_OF_NOODLES, 1)
      transfer_pid_between_objs(self_obj, dude_obj, PID_BOTTLE_CAPS, 55)
      dec_general_rep(5);
      set_local_var(LVAR_Robbed, 1);
      call Node999;

end

procedure HealAll begin
   fadeout(1);
   game_time_advance(15 * ONE_GAME_MINUTE);
   critter_uninjure(self_obj, DAM_CRIP_ARM_RIGHT);
   if(obj_is_carrying_obj_pid(self_obj,PID_BOTTLE_CAPS)>0) then begin
      transfer_pid_between_objs(self_obj, dude_obj, PID_BOTTLE_CAPS, 55)
   end
   fadein(1);
end

procedure HealEnd begin
   set_local_var(LVAR_Healed, 1);
   give_xp(100);
   call Node999;
end

procedure HealEndGood begin
   dec_general_rep(5);
   transfer_pid_between_objs(dude_obj, self_obj, PID_BOTTLE_CAPS, 55)
   call HealEnd;
end

// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001 begin
if (dude_is_male) then Reply(200); else
if (dude_is_female) then Reply(201);
NOption(202,Node003,4);
NOption(203,Node002,4);
BOption(204,Node998,4);
NOption(205,Node003,-3);
NOption(206,Node002,-3);
BOption(207,Node998,-3);
end

procedure Node002 begin
Reply(230);
call GiveAll;
NOption(231,Node999,4);
NOption(232,Node999,-3);
end

procedure Node003
begin
Reply(260);
if (has_skill(dude_obj,SKILL_FIRST_AID)>=50) then
NOption(mstr(261)+dude_name+mstr(262),Node004,4);
if (obj_is_carrying_obj_pid(dude_obj,PID_STIMPAK)>0) then
NOption(mstr(263)+dude_name+mstr(264),Node004a,4);
NOption(265,Node010,4);
if (get_critter_stat(dude_obj,STAT_pe)>=6) or (has_skill(dude_obj,SKILL_SMALL_GUNS)>=50) then
NOption(mstr(263)+dude_name+mstr(266),Node007,4);
if (has_skill(dude_obj,SKILL_FIRST_AID)>=50) then
NOption(mstr(267)+dude_name+mstr(268),Node004,-3);
if (obj_is_carrying_obj_pid(dude_obj,PID_STIMPAK)>0) then
NOption(mstr(269)+dude_name+mstr(270),Node004a,-3);
NOption(271,Node010,-3);
if (has_skill(dude_obj,SKILL_SMALL_GUNS)>=50) or (get_critter_stat(dude_obj,STAT_pe)>=6) then
NOption(272,Node007,-3);
end

procedure Node004 begin
   call HealAll;
if (dude_is_male and (obj_is_carrying_obj_pid(self_obj,PID_BOTTLE_CAPS)<1)) then Reply(288); else
if (dude_is_female and (obj_is_carrying_obj_pid(self_obj,PID_BOTTLE_CAPS)<1)) then Reply(289);
if (dude_is_male and (obj_is_carrying_obj_pid(self_obj,PID_BOTTLE_CAPS)>0)) then Reply(290); else
if (dude_is_female and (obj_is_carrying_obj_pid(self_obj,PID_BOTTLE_CAPS)>0)) then Reply(291);
NOption(292,HealEnd,4);
NOption(293,Node005,4);
NOption(294,HealEnd,-3);
NOption(295,Node005,-3);
end

procedure Node005 begin
   call HealEndGood;
if (dude_is_male) then Reply(320); else
if (dude_is_female) then Reply(321);
NOption(322,Node999,4);
NOption(323,Node999,-3);
end

procedure Node006
begin
Reply(350);
NOption(351,Node003,4);
NOption(203,Node002,4);
BOption(204,Node998,4);
NOption(352,Node003,-3);
NOption(206,Node002,-3);
BOption(207,Node998,-3);
end

procedure Node007
begin
Reply(380);
NOption(381,Node008,4);
NOption(382,Node009,4);
NOption(383,Node008,-3);
NOption(384,Node009,-3);
end

procedure Node008
begin
Reply(410);
if (has_skill(dude_obj,SKILL_FIRST_AID)>=50) then
NOption(411,Node004,4);
if (obj_is_carrying_obj_pid(dude_obj,PID_STIMPAK)>0) then
NOption(412,Node004a,4);
NOption(265,Node010,4);
if (has_skill(dude_obj,SKILL_FIRST_AID)>=50) then
NOption(413,Node001,-3);
if (obj_is_carrying_obj_pid(dude_obj,PID_STIMPAK)>0) then
NOption(414,Node004a,-3);
NOption(271,Node010,-3);
end

procedure Node009 begin

give_xp(100);
display_mstr(109);

if (dude_is_male) then Reply(440); else
if (dude_is_female) then Reply(441);
NOption(442,Node010,4);
NOption(443,Node011,4);
NOption(444,Node010,-3);
NOption(445,Node011,-3);
end

procedure Node010
begin
   set_local_var(LVAR_Pissed, 1);
   dec_general_rep(5);
Reply(470);
NOption(471,Node999,1);
BOption(472,Node998,4);
NOption(473,Node999,4);
BOption(474,Node998,-3);
NOption(475,Node999,-3);
end

procedure Node011
begin
Reply(500);
NOption(501,Node008,1);
end

procedure Node004a begin
   remove_pid_qty(dude_obj, PID_STIMPAK, 1)
   call Node004;
end


//xxxxxxxxxxxxxxxxxxxx
