/*******************************************************************************
        Name:
        Location:
        Description: Maps template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\party.h"
#include "..\headers\updatmap.h"
#include "..\headers\vehicles.h"

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;


/* Defines */
#define NAME                  SCRIPT_BHBFVILL

#define LVAR_Replace_Store	                (0)

/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin
end

procedure map_enter_p_proc begin
   //21863
	variable init_obj;
	variable general_store_ptr;
	if (local_var(LVAR_Replace_Store) < 99) then begin
		init_obj := tile_contains_pid_obj(21863, dude_elevation, PID_HERO_PRIMITIVE_FEMALE);
		destroy_object(init_obj);
		set_local_var(LVAR_Replace_Store, 99);
		general_store_ptr = create_object_sid(PID_HERO_PRIMITIVE_FEMALE,21863,dude_elevation,SCRIPT_TMP501); //actual spot
		anim(general_store_ptr, 1000, 5); 
		arm_obj(general_store_ptr, PID_SLING, 1, 0, 0) 
	end

   call Check_Create_Vehicle;

   if (not(is_loading_game)) then begin
      override_map_start_hex(30098, 0, 5);
   end

   fadein(1);
   Lighting;

   ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_WIND_IN_THE_GRASS), 1);
end

procedure map_update_p_proc begin

   Lighting;

end

procedure map_exit_p_proc begin
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end
