/*******************************************************************************
        Name:
        Location:
        Description: Maps template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\party.h"
#include "..\headers\updatmap.h"
#include "..\headers\vehicles.h"

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;


/* Defines */
#define NAME                  SCRIPT_GCMACH
#define MVAR_CREATE_BICYCLE   (0)


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin
end

procedure map_enter_p_proc begin

   if (not(is_loading_game)) then begin
      // Create the unclaimed one
      if (not(dude_has_bicycle) and dude_is_stupid and not(dude_is_idiot_savant)) then begin
         if (map_var(MVAR_CREATE_BICYCLE) == 0) then begin
            set_map_var(MVAR_CREATE_BICYCLE, 1);
            display_mstr(100);
            play_sfx("pebble");
            play_sfx("BICLSTRT");
         end
         Create_Bicycle(BICYCLE_UNCLAIMED_HEX, 0)
     end
   end

   fadein(1);

   Shady_Lighting;

   ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_GRAND_CANYON), 1);

end

procedure map_update_p_proc begin
   if(dude_elevation >= 1) then begin
      Cavern_Lighting;
   end
   else begin
      Shady_Lighting;
   end
end

procedure map_exit_p_proc begin
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end
