/*******************************************************************************
        Name:
        Location:
        Description: Maps template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"

#include "..\headers\updatmap.h"
#include "..\headers\party.h"

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;

/* Defines */
#define NAME                  SCRIPT_HDDTNW


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/

/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/

variable track;

/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin
end

procedure map_enter_p_proc begin
   fadein(1);
   Shady_Lighting;
end

procedure map_update_p_proc begin


   if(dude_elevation == 0) then begin

      if (track != AMBIENT_SLUDGE) then begin
         stop_sfall_sound(ambient_sfx);
         track = AMBIENT_SLUDGE;
         ambient_sfx := play_sfall_sound(AmbientTrack(track), 1);
      end

      Shady_Lighting;
   end
   // Hoover Dam elevator
   else begin

      if (track != AMBIENT_ABANDONED_CRICKETS) then begin
         stop_sfall_sound(ambient_sfx);
         track = AMBIENT_ABANDONED_CRICKETS;
         ambient_sfx := play_sfall_sound(AmbientTrack(track), 1);
      end

      Darkness;
   end
end

procedure map_exit_p_proc begin
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end
