/*******************************************************************************
        Name:
        Location:
        Description: Maps template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"

#include "..\headers\updatmap.h"
#include "..\headers\party.h"
#include "..\headers\hddtse.h"

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;

/* Defines */
#define NAME                  SCRIPT_HDDTSE

#define MVAR_Replace_Store	                (1)


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/

/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin
end

procedure map_enter_p_proc begin
   //24351
   //260
	variable init_obj;
	variable general_store_ptr;
	if ((global_var(GVAR_ELISE_TEST) == QUEST_COMPLETED) and (map_var(MVAR_Replace_Store) < 99)) then begin
		init_obj := tile_contains_pid_obj(24351, dude_elevation, PID_MALE_NCR_RANGER);
		destroy_object(init_obj);
		set_map_var(MVAR_Replace_Store, 99);
		general_store_ptr = create_object_sid(PID_MALE_NCR_RANGER,24351,dude_elevation,SCRIPT_TMP502); //actual spot
		anim(general_store_ptr, 1000, 5); 
		arm_obj(general_store_ptr, PID_SUPER_SLEDGE, 1, 0, 0) 
	end

   if (not(is_loading_game) and map_first_run) then
      display_mstr(100);

   fadein(1);
   Shady_Lighting;
   ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_WASTELAND), 1);
end

procedure map_update_p_proc begin

   Shady_Lighting;

end

procedure map_exit_p_proc begin
   if (map_var(MVAR_SHADY_SANDS_TRACK_PLAYING) == 1) then begin
      set_map_music(MAP_HOOVER_DAM_DOWNTOWN_SOUTHEAST, "01HUB");
      set_map_var(MVAR_SHADY_SANDS_TRACK_PLAYING, 0);
   end
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end
