/*******************************************************************************
        Name:
        Location:
        Description: Maps template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"

#include "..\headers\updatmap.h"

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;


/* Defines */
#define NAME                  SCRIPT_HDNCRGYM


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/
export variable fighting_boxer_1_obj;
export variable fighting_boxer_2_obj;
export variable announcer_obj;
export variable ring_girl_obj;
export variable prize_fighter_obj;
export variable stuart_little_obj;
export variable mckneely_obj;
export variable hollyfeld_obj;
export variable help_me_obj;
export variable new_reno_generic_boxer_obj;
export variable generic_temp_box;
export variable frieda_obj;
export variable pablo_obj;
export variable enzo_obj;
export variable guido_obj;
export variable dusty_obj;
export variable ginger_obj;

/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin
end

procedure map_enter_p_proc begin
   fadein(1);

   Indoor_Lighting;

   if (map_first_run) then begin
      display_mstr(100);
   end

end

procedure map_update_p_proc begin

   Indoor_Lighting;

end

procedure map_exit_p_proc begin
   fadeout(1);
end
