
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\party.h"
#include "..\headers\updatmap.h"
#include "..\headers\vehicles.h"

procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;

#define NAME                  SCRIPT_MAXBENT

procedure start begin
end

procedure map_enter_p_proc begin
   call Check_Create_Vehicle;

   fadein(1);
   Lighting;

   if (map_first_run) then begin
      display_mstr(100);
   end

   ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_WIND_IN_THE_GRASS), 1);
end

procedure map_update_p_proc begin

   Lighting;

end

procedure map_exit_p_proc begin
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end
