/*******************************************************************************
        Name:
        Location:
        Description: Maps template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\updatmap.h"
#include "..\headers\mvcanyo3.h"

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;


/* Defines */
#define NAME                  SCRIPT_MVCANYO3


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/

/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/

variable track;

/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin
end

procedure map_enter_p_proc begin

   if (
      (global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF) == ALEXANDRA_BLACKJACK_CAVE_COLLAPSED) and
      (map_var(MVAR_Collapse_Cave) == 0)
   ) then begin
      set_map_var(MVAR_Collapse_Cave, 1);
      Create_Cave_In(22712, 0, PID_CAVE_IN_ROCKS_OUTDOOR)
   end

   fadein(1);
   Lighting;
end

procedure map_update_p_proc begin
   if(dude_elevation == 1) then begin

      if (track != AMBIENT_MOUNTAIN_CAVE_WIND) then begin
         stop_sfall_sound(ambient_sfx);
         track = AMBIENT_MOUNTAIN_CAVE_WIND;
         ambient_sfx := play_sfall_sound(AmbientTrack(track), 1);
      end

      Cavern_Lighting;
   end
   else begin

      if (track != AMBIENT_WIND_IN_THE_GRASS) then begin
         stop_sfall_sound(ambient_sfx);
         track = AMBIENT_WIND_IN_THE_GRASS;
         ambient_sfx := play_sfall_sound(AmbientTrack(track), 1);
      end

      Lighting;
   end
end

procedure map_exit_p_proc begin
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end
