#include "..\headers\define.h"
#include "..\headers\updatmap.h"

#define NAME                    SCRIPT_NETHERLM

#include "..\headers\command.h"

procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;

procedure start begin
end


procedure map_enter_p_proc begin
   fadein(1);
   Darkness;

   ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_MOUNTAIN_CAVE_WIND), 1);
end

procedure map_update_p_proc begin
   Darkness;
end


procedure map_exit_p_proc begin
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end
