/*******************************************************************************
        Name:
        Location:
        Description: Maps template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\updatmap.h"

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;

/* Defines */
#define NAME                  SCRIPT_NRSPILLW

procedure start begin
end

procedure map_enter_p_proc begin

   if (map_first_run and (not is_loading_game)) then begin
   end

   fadein(1);
   Cavern_Lighting;

   ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_SEWERS), 1);
end

procedure map_update_p_proc begin
    Cavern_Lighting;
end

procedure map_exit_p_proc begin
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end
