/*******************************************************************************
        Name:
        Location:
        Description: Maps template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\party.h"
#include "..\headers\updatmap.h"
#include "..\headers\vehicles.h"

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;


/* Defines */
#define NAME                  SCRIPT_SETENTC

/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin
end

procedure map_enter_p_proc begin
   set_global_var(GVAR_SPECIAL_ENCOUNTER_TENTACLES,1);
   if(not(is_loading_game)) then begin
    override_map_start_hex(19482, 0, 3);
   end

   call Check_Create_Vehicle;

   fadein(1);
   Lighting;

   ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_MUTANT_WATERS), 1);
end

procedure map_update_p_proc begin
   Lighting;
end

procedure map_exit_p_proc begin
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end
