/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/*
   Tibbets Waste Disposal
*/

#include "..\headers\define.h"
#include "..\headers\updatmap.h"

#define NAME                    SCRIPT_TBWASTE

#include "..\headers\command.h"

procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;

procedure start begin
end


procedure map_enter_p_proc begin

   if (map_first_run) then begin
      display_mstr(100);
   end

   fadein(1);
   Basement_Lighting;

   ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_SEWERS), 1);
end

procedure map_update_p_proc begin
   Basement_Lighting;
end


procedure map_exit_p_proc begin
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end
