call ..\p obj_dude
call ..\p footstep
call ..\p gl_aimedmisses
call ..\p gl_invenfilter
call ..\p gl_medtoolsmod
call ..\p gl_partyskillbooksmod
call ..\p gl_sneak_detection
call ..\p gl_statsrecalculation
call ..\p gl_stealing_mod
call ..\p gl_ammomod
call ..\p gl_animweed
call ..\p gl_armorreset
call ..\p gl_footprints
call ..\p gl_highlighting
call ..\p gl_k_alcohl
call ..\p gl_k_car
call ..\p gl_k_crippl
call ..\p gl_k_tragic
call ..\p gl_partycontrol
call ..\p gl_pipwake
call ..\p gl_rest_encounter
call ..\p gl_ride_tracker
call ..\p gl_stealthboy_auto_sneak
call ..\p gl_uihotkeys
call ..\p gl_weapons
call ..\p gl_wpn_drop
call ..\p gl_yzsecondaryattackmod
call ..\p gl_zregpoismod
call ..\p gl_ztraits_plus
call ..\p gl_zanticritical
call ..\p glbooze
call ..\p glperks
call ..\p gltraits
call ..\p glwm
call ..\p hangdman
call ..\p pip2000
call ..\p gl_car_cargo
call ..\p HCMARCUS

