/*******************************************************************************
        Name:
        Location:
        Description: Object template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\tibbets.h"

#define NAME                    SCRIPT_ELFENCE

/* Standard Script Procedures */
procedure start;
procedure description_p_proc;
procedure look_at_p_proc;
procedure use_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure timed_event_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure electrical_doom(variable o);

/* Defines */


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/

procedure look_at_p_proc begin

end

procedure description_p_proc begin

end

procedure start begin
end


procedure use_p_proc begin
   call electrical_doom(source_obj);
end

procedure map_enter_p_proc begin
   /*reg_anim_begin();
   reg_anim_animate_forever(self_obj, ANIM_stand);
   reg_anim_end();

   add_timer_event(self_obj, 1, 1);*/
end

procedure map_update_p_proc begin
/*   if (combat_is_initialized == 0) then begin
      if((map_var(MVAR_SecField_down) == 1) and obj_is_visible_flag(self_obj)) then begin
         set_obj_visibility(self_obj, 1);
         return;
      end

      reg_anim_begin();
      reg_anim_animate_forever(self_obj, ANIM_stand);
      reg_anim_end();
   end
   */
end

procedure timed_event_p_proc begin
 /* if (fixed_param == 1) then begin
      if ((anim_busy(self_obj) == false) and (combat_is_initialized == 0)) then begin

         if((map_var(MVAR_SecField_down) == 1) and obj_is_visible_flag(self_obj)) then begin
            set_obj_visibility(self_obj, 1);
            return;
         end else if ((map_var(MVAR_SecField_down) == 0) and obj_is_visible_flag(self_obj) == FALSE) then begin
            set_obj_visibility(self_obj, 0);
         end

         reg_anim_begin();
         reg_anim_animate_forever(self_obj, ANIM_stand);
         reg_anim_end();
      end
      add_timer_event(self_obj, 1, 1);
  end*/
end

procedure use_skill_on_p_proc begin
   if (
   action_being_used == SKILL_LOCKPICK or
   action_being_used == SKILL_TRAPS or
   action_being_used == SKILL_REPAIR or
   action_being_used == SKILL_SCIENCE
   ) then begin
       script_overrides;
       call electrical_doom(source_obj);
   end
end

procedure use_obj_on_p_proc begin
   variable tool := obj_pid(obj_being_used_with);

   if (
   tool == PID_LOCKPICKS or
   tool == PID_EXP_LOCKPICK_SET or
   tool == PID_MULTI_TOOL or
   tool == PID_SUPER_TOOL_KIT
   ) then begin
       script_overrides;
       call electrical_doom(source_obj);
   end
end


procedure electrical_doom(variable o) begin
   //if(map_var(MVAR_SecField_down) == 0) then begin
      critter_dmg(o, random(100, 200), DMG_electrical);
   //end
end
