/*

        Name:           Croz
        Location:
        Description:    Dialogue with one of the wasters outside the rat temple. He can be convinced to leave either through one of three methods. Threatining him, convincing him that the Temple has 'bad vibes' or convincing him that, if he bathes in radioactive goo, he will glow in the dark.

           Created: 05/10/2020 09:29:27

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBCROZ

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure Skill_Check_100_Speech;
procedure Skill_Check_001_Speech;
procedure Skill_Check_002_Speech;
procedure Skill_Check_007_Speech;
procedure Skill_Check_005_Unarmed_Combat;
procedure Skill_Check_006_Speech;


// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure StartT;
procedure Glowing;
procedure Listen;
procedure Chilling;
procedure NotLeave;
procedure ShowGlow;
procedure Crazy;
procedure Flee;
procedure Combat;
procedure Questions;
procedure LikeTemple;
procedure Hurt;
procedure Vibes;
procedure NoVibes;
procedure Name;
procedure Leave;
procedure RatTemple;
procedure Pain;
procedure NoPain;
procedure FullOfIt;
procedure StartT2;
procedure Back;
procedure CantStay;
procedure Goo;
procedure LookForGoo;
procedure Convert;
procedure Druggy;
procedure LeaveTemp;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Leave               (8)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
   add_timer_event(self_obj,game_ticks(random(1,5)),0);
   call new_plague_check(self_obj, LVAR_Herebefore);

   if(global_var(GVAR_ANGELA_DEAD) == 1) then begin
      destroy_object(self_obj);
   end

   if(not(obj_is_visible_flag(self_obj))) then
      set_obj_visibility(self_obj, 0);
end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude or self_can_hear_dude) and obj_is_visible_flag(self_obj)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_INTOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;
       if(local_var(LVAR_Herebefore) == 0) then
         call StartT;
       else
         call StartT2;
       gSay_End;
       end_dialogue;


   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin

   if(obj_is_visible_flag(self_obj)) then begin
      if (
      (random(0, 10) == 1) and
      (not(combat_is_initialized))
      ) then begin
         reg_anim_clear(self_obj);
         reg_anim_begin();
         reg_anim_animate(self_obj, ANIM_magic_hands_middle, -1);
         reg_anim_end();
      end

      if (random(0, 30) == 1) then begin
         floater_sick_rand(200, 211);
      end
   end

   add_timer_event(self_obj,game_ticks(random(3, 5)),0);

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_neutral_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
set_global_var(GVAR_KNOW_CROZ, 1);
end
end

// Skill checks and miscellaneous procedures

procedure Skill_Check_100_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -15);
if is_success(roll_temp) then
begin
call Flee;
end
else begin
call Combat;
 end
end

procedure Skill_Check_001_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -20);
if is_success(roll_temp) then
begin
call Vibes;
end
else begin
call NoVibes;
 end
end

procedure Skill_Check_002_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -20);
if is_success(roll_temp) then
begin
call Vibes;
end
else begin
call NoVibes;
 end
end

procedure Skill_Check_007_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, 0);
if is_success(roll_temp) then
begin
call Leave;
end
else begin
call NotLeave;
 end
end

procedure Skill_Check_005_Unarmed_Combat begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_UNARMED_COMBAT, 0);
if is_success(roll_temp) then
begin
call Pain;
end
else begin
call NoPain;
 end
end

procedure Skill_Check_006_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, 0);
if is_success(roll_temp) then
begin
call Flee;
end
else begin
call Combat;
 end
end



// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


// Node Waster1Floaters
//
// Notes:
//
// Floaters for waster 1.

procedure StartT
begin
Reply(260);
NOption(261,Glowing,4);
BOption(262,Listen,4);
NOption(263,Chilling,4);
NOption(264,NotLeave,4);
// NOTE: This is the dumb version for the player option 1 in node Start1
//Original line:
//Shut up and listen.
NOption(265,Druggy,-3);
end

// Node Glowing
//
// Notes:
//
// Done *

procedure Glowing
begin
Reply(290);
BOption(291,Listen,4);
NOption(292,Crazy,4);
NOption(293,ShowGlow,4);
NOption(294,Node999,4);
end

// Node Listen
//
// Notes:
//
// Done *

procedure Listen
begin
Reply(320);
NOption(321,NotLeave,4);
NOption(322,Skill_Check_100_Speech,4);
NOption(323,Questions,4);
end

// Node Chilling
//
// Notes:
//
// Done *

procedure Chilling
begin
Reply(350);
NOption(351,LikeTemple,4);
BOption(352,NotLeave,4);
NOption(353,Questions,4);
end

// Node NotLeave
//
// Notes:
//
// Done *

procedure NotLeave
begin
Reply(380);
BOption(381,Hurt,4);
NOption(382,Skill_Check_002_Speech,4);
NOption(383,Questions,4);
NOption(384,Node999,4);
end

procedure ShowGlow
begin
Reply(410);
if (has_skill(dude_obj,SKILL_CONVERSANT)>60) then
NOption(411,Skill_Check_007_Speech,5);
NOption(412,Questions,4);
NOption(413,Node999,4);
end

// Node Crazy
//
// Notes:
//
// Done *

procedure Crazy
begin
Reply(440);
GOption(441,Name,4);
BOption(442,Name,4);
BOption(443,NotLeave,4);
NOption(444,Node999,4);
end

procedure Flee
begin
Reply(470);
NOption(471,Node999,4);
end

procedure Combat
begin
Reply(500);
BOption(471,Node998,4);
end

procedure Questions
begin
Reply(530);
NOption(531,Glowing,4);
NOption(532,Name,4);
NOption(533,RatTemple,4);
NOption(534,Node999,4);
end

procedure LikeTemple
begin
Reply(560);
NOption(561,Skill_Check_001_Speech,4);
NOption(562,Questions,4);
NOption(563,Node999,4);
end

procedure Hurt
begin
Reply(590);
BOption(591,Skill_Check_005_Unarmed_Combat,4);
NOption(592,Skill_Check_006_Speech,4);
NOption(593,Questions,4);
NOption(594,Node999,4);
end

procedure Vibes
begin
Reply(620);
NOption(471,Node999,4);
end

procedure NoVibes
begin
Reply(650);
NOption(651,Hurt,4);
BOption(652,FullOfIt,4);
NOption(653,Questions,4);
NOption(654,Node999,4);
end

procedure Name
begin
Reply(680);
BOption(681,NotLeave,4);
NOption(682,Questions,4);
NOption(683,LikeTemple,4);
end

procedure Leave
begin
Reply(710);
NOption(471,LeaveTemp,4);
end

procedure RatTemple
begin
Reply(740);
NOption(741,LikeTemple,4);
NOption(742,NotLeave,4);
NOption(743,Node999,4);
end

procedure Pain
begin
Reply(770);
NOption(471,LeaveTemp,4);
end

procedure NoPain
begin
Reply(800);
BOption(471,Node998,4);
end

procedure FullOfIt
begin
Reply(830);
NOption(471,Node999,4);
end

procedure StartT2
begin
Reply(860);
if(local_var(LVAR_Leave) == 1) then begin
   NOption(861,Back,4);
   NOption(862,Flee,4);
end
NOption(863,Node999,4);
NOption(265,Druggy,-3);
end

procedure Back
begin
Reply(890);
NOption(891,CantStay,4);
// NOTE: This should only appear if the player told him to find some goo to take a bath in.
NOption(892,Goo,4);
NOption(893,Node999,4);
end

procedure CantStay
begin
Reply(920);
NOption(471,LeaveTemp,4);
end

procedure Goo
begin
Reply(950);
NOption(951,LookForGoo,4);
NOption(952,Flee,4);
end

procedure LookForGoo
begin
Reply(980);
NOption(471,Node999,4);
end

procedure Convert
begin
Reply(1010);
NOption(471,Node999,-3);
end

procedure Druggy
begin
Reply(1040);
NOption(1041,Convert,-3);
end

procedure LeaveTemp begin
   call Node999;
   fadeout(1);
set_local_var(LVAR_Leave, 1);
   set_obj_visibility(self_obj, 1);

   fadein(1);
end


//xxxxxxxxxxxxxxxxxxxx
