/*

        Name:           Danika
        Location:
        Description:

           Created: 06/10/2020 21:54:48

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBDANIKA

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\HEADERS\tbmed1.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending


// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure First;
procedure Subsequent;
procedure Guide;
procedure Journey;
procedure WantAD;
procedure MoreAD;
procedure ADTripQuestions;
procedure BecomeTripGuide;
procedure SpiritGuide;
procedure SpiritGuide2;
procedure AutoDoc;
procedure HowGuide;
procedure HowGuide2;
procedure Hallucination;
procedure TakeTrip;
procedure TripStart;
procedure Node020;
procedure ADFade;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_DOCTOR);
   call new_plague_check(self_obj, LVAR_Herebefore);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;
       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;

if (local_var(LVAR_Herebefore)==0) then begin
       call First;
end else if (local_var(LVAR_Herebefore)==1) then begin
       call Subsequent;
end

       gSay_End;
       end_dialogue;

   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
   set_global_var(GVAR_MET_DANIKA, 1);
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE

// Node First
//
// Notes:
//
// 2) only available if player has received 'find drug priest' quest

procedure First
begin
Reply(230);
NOption(231,Guide,4);
NOption(232,WantAD,4);
NOption(233,Node020,4);
NOption(234,Node999,4);
NOption(235,Guide,-3);
NOption(236,Node020,-3);
NOption(237,Node999,-3);
end

// Node Subsequent
//
// Notes:
//
// 2,3,7,8) only available after player has found out she is the trip guide\

procedure Subsequent
begin
Reply(260);
NOption(231,Guide,4);
NOption(261,TakeTrip,4);
NOption(262,ADTripQuestions,4);
NOption(232,WantAD,4);
NOption(233,Node020,4);
NOption(234,Node999,4);
NOption(235,Guide,-3);
NOption(263,TakeTrip,-3);
NOption(264,Node020,-3);
NOption(265,Node999,-3);
end

procedure Guide
begin
Reply(290);
NOption(291,Journey,1);
NOption(292,Node999,4);
NOption(293,Node999,-3);
end

procedure Journey
begin
Reply(320);
NOption(321,TakeTrip,4);
NOption(322,ADTripQuestions,4);
NOption(323,Node999,4);
NOption(324,TakeTrip,-3);
NOption(325,Node999,-3);
end

procedure WantAD
begin
Reply(350);
NOption(351,MoreAD,4);
NOption(352,ADTripQuestions,4);
NOption(353,Node999,4);
end

procedure MoreAD
begin
Reply(380);
NOption(381,ADTripQuestions,4);
NOption(382,Node999,4);
NOption(383,Node999,4);
end

// Node ADTripQuestions
//
// Notes:
//
// 2) available after speaking to dogmeat

procedure ADTripQuestions
begin
Reply(410);
NOption(261,TakeTrip,4);
NOption(411,HowGuide,4);
NOption(412,BecomeTripGuide,4);
NOption(413,Hallucination,4);
NOption(414,Node999,4);
end

procedure BecomeTripGuide
begin
Reply(440);
NOption(441,SpiritGuide,4);
NOption(442,ADTripQuestions,4);
NOption(443,Node999,4);
end

procedure SpiritGuide
begin
Reply(470);
NOption(471,SpiritGuide2,4);
NOption(442,ADTripQuestions,4);
NOption(472,Node999,4);
end

procedure SpiritGuide2
begin
Reply(500);
if (has_skill(dude_obj,SKILL_DOCTOR)>=100) and (has_skill(dude_obj,SKILL_REPAIR)>=75) and (has_skill(dude_obj,SKILL_CONVERSANT)>=50) then
NOption(501,AutoDoc,4);
NOption(502,ADTripQuestions,4);
NOption(503,Node999,4);
end

procedure AutoDoc
begin
   set_map_var(MVAR_AutoDoc, 1);
Reply(530);
NOption(531,ADTripQuestions,4);
NOption(532,Node999,4);
end

procedure HowGuide
begin
Reply(560);
NOption(441,SpiritGuide,4);
NOption(561,HowGuide2,4);
NOption(562,ADTripQuestions,4);
NOption(503,Node999,4);
end

procedure HowGuide2
begin
Reply(590);
NOption(502,ADTripQuestions,4);
NOption(503,Node999,4);
end

procedure Hallucination
begin
Reply(620);
NOption(621,ADTripQuestions,4);
NOption(622,Node999,4);
end

procedure TakeTrip
begin
Reply(650);
NOption(651,TripStart,1);
NOption(652,ADTripQuestions,4);
NOption(653,Node999,4);
NOption(654,Node999,-3);
end

// Node TripStart
//
// Notes:
//
// 1) starts the appropriate trip

procedure TripStart
begin
Reply(740);
NOption(741,ADFade,1);
end

procedure Node020
begin
Reply(770);
NOption(771,Subsequent,4);
NOption(772,Node999,4);
NOption(773,Subsequent,-3);
NOption(774,Node999,-3);
end

procedure ADFade begin
   call Node999;
   fadeout(1);

   game_time_advance(game_ticks((11 - dude_endurance) * ONE_GAME_HOUR));
      call HealParty;

   fadein(1);
end

//xxxxxxxxxxxxxxxxxxxx
