/*

        Name:           Eando
        Location:
        Description:

           Created: 05/10/2020 14:28:36

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBEANDO

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure GeneralWarehouse;
procedure GeneralBar;
procedure WarehouseClosed;
procedure Switcher;
procedure FirstBar;
procedure FirstCell;
procedure WhoIsWarehouse;
procedure WhatDoWarehouse;
procedure QuestionsWarehouse;
procedure SubsequentBar;
procedure SubsequentCell;
procedure OddSmell;
procedure TheStink;
procedure Meet;
procedure WhatDo;
procedure Hiring;
procedure Royce;
procedure Royce2;
procedure Women;
procedure Sure;
procedure Robbed;
procedure RobbedKilled;
procedure NoIdea;
procedure RefuseCompKill;
procedure RefuseCompRob;
procedure HiringStupid;
procedure RoyceStupid;
procedure MoneyStupid;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)

#define InBar    ((cur_map_index == MAP_TIBBETS_SERVICE_LEVEL_WEST) and (evening or night))
#define InCell   ((cur_map_index == MAP_TIBBETS_CELL_BLOCK_17) and (morning or day))

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
   add_timer_event(self_obj,game_ticks(random(1,5)),0);
   call new_plague_check(self_obj, LVAR_Herebefore);

   if(InBar or InCell) then begin
      set_obj_visibility(self_obj, 0);
   end else begin
      set_obj_visibility(self_obj, 1);
   end
end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude) and obj_is_visible_flag(self_obj)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;
       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;

if ((global_var(GVAR_EANDO_TALKED)==0) and InCell) then begin
       call FirstCell;
end else if ((global_var(GVAR_EANDO_TALKED)==1) and InCell) then begin
       call SubsequentCell;
end else if ((global_var(GVAR_EANDO_TALKED)==0) and InBar) then begin
       call FirstBar;
end else if ((global_var(GVAR_EANDO_TALKED)==1) and InBar) then begin
       call SubsequentBar;
end
       gSay_End;
       end_dialogue;

   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin

   add_timer_event(self_obj,game_ticks(random(3, 5)),0);

   if(obj_is_visible_flag(self_obj)) then begin
      if (random(0, 30) == 1) then begin
         if(InCell) then
            floater_rand(200, 204);
         else if(InBar) then
            floater_rand(230, 233);
      end
   end


end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_neutral_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (global_var(GVAR_EANDO_TALKED) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin

if (global_var(GVAR_EANDO_TALKED)==0) then
begin
set_global_var(GVAR_EANDO_TALKED,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


// Node GeneralWarehouse
//
// Notes:
//
// Boo is working in the warehouse

procedure GeneralWarehouse
begin
floater_rand(200,204);
end

// Node GeneralBar
//
// Notes:
//
// Boo is hanging out in the bar

procedure GeneralBar
begin
floater_rand(230,233);
end

// Node WarehouseClosed
//
// Notes:
//
// Royce is dead and the warehouse is shut down

procedure WarehouseClosed
begin
floater_rand(260,264);
end

procedure Switcher
begin
Reply(290);
NOption(291,FirstCell,1);
NOption(292,FirstBar,1);
NOption(293,SubsequentCell,1);
NOption(294,SubsequentBar,1);
NOption(295,Robbed,1);
NOption(296,RobbedKilled,1);
end

// Node FirstBar
//
// Notes:
//
// 1,5) if player has THE STINK, 2,6) if not

procedure FirstBar
begin
Reply(320);
if ((get_critter_stat(dude_obj,STAT_ch)<=4) or (has_trait(TRAIT_PERK,dude_obj,PERK_expert_excrement_expediter_perk))) then
NOption(321,TheStink,4);
if (get_critter_stat(dude_obj,STAT_ch)>=5) then
NOption(321,OddSmell,4);
NOption(mstr(322)+dude_name+mstr(323),Meet,4);
NOption(324,Node999,4);
if ((get_critter_stat(dude_obj,STAT_ch)<=4) or (has_trait(TRAIT_PERK,dude_obj,PERK_expert_excrement_expediter_perk))) then
NOption(325,TheStink,-3);
if (get_critter_stat(dude_obj,STAT_ch)>=5) then
NOption(325,OddSmell,-3);
NOption(mstr(326)+dude_name+mstr(327),Meet,-3);
NOption(328,Node999,-3);
end

procedure FirstCell
begin
Reply(350);
NOption(351,WhoIsWarehouse,4);
NOption(352,WhatDoWarehouse,4);
NOption(353,Node999,4);
NOption(354,WhoIsWarehouse,-3);
NOption(355,WhatDoWarehouse,-3);
NOption(356,Node999,-3);
end

procedure WhoIsWarehouse
begin
Reply(380);
NOption(381,Node999,4);
NOption(382,Node999,4);
NOption(383,Node999,-3);
NOption(384,Node999,-3);
end

procedure WhatDoWarehouse
begin
Reply(410);
NOption(411,QuestionsWarehouse,4);
NOption(412,Node999,4);
NOption(413,QuestionsWarehouse,-3);
NOption(414,Node999,-3);
end

procedure QuestionsWarehouse
begin
Reply(440);
NOption(441,Node999,4);
NOption(442,Node999,4);
NOption(443,Node999,-3);
NOption(444,Node999,-3);
end

// Node SubsequentBar
//
// Notes:
//
// 1,5) if player has THE STINK, 2,6) if not

procedure SubsequentBar
begin
Reply(470);
if ((get_critter_stat(dude_obj,STAT_ch)<=4) or (has_trait(TRAIT_PERK,dude_obj,PERK_expert_excrement_expediter_perk))) then
NOption(471,TheStink,4);
if (get_critter_stat(dude_obj,STAT_ch)>=5) then
NOption(471,OddSmell,4);
NOption(472,WhatDo,4);
NOption(473,Node999,4);
if ((get_critter_stat(dude_obj,STAT_ch)<=4) or (has_trait(TRAIT_PERK,dude_obj,PERK_expert_excrement_expediter_perk))) then
NOption(325,TheStink,-3);
if (get_critter_stat(dude_obj,STAT_ch)>=5) then
NOption(325,OddSmell,-3);
NOption(355,WhatDo,-3);
NOption(474,Node999,-3);
end

procedure SubsequentCell
begin
Reply(500);
NOption(501,WhatDoWarehouse,4);
NOption(502,QuestionsWarehouse,4);
NOption(503,Node999,4);
NOption(355,WhatDoWarehouse,-3);
NOption(413,QuestionsWarehouse,-3);
NOption(504,Node999,-3);
end

procedure OddSmell
begin
Reply(530);
NOption(531,WhatDo,4);
NOption(532,Royce,4);
NOption(533,Node999,4);
NOption(355,WhatDo,-3);
NOption(534,RoyceStupid,-3);
NOption(535,Node999,-3);
end

procedure TheStink
begin
Reply(560);
NOption(561,Royce,4);
NOption(562,Node999,4);
NOption(563,Node999,4);
NOption(564,RoyceStupid,-3);
NOption(565,Node999,-3);
NOption(566,Node999,-3);
end

procedure Meet
begin
Reply(mstr(590)+dude_name+mstr(591));
NOption(531,WhatDo,4);
NOption(592,Node999,4);
NOption(355,WhatDo,-3);
NOption(593,Node999,-3);
end

procedure WhatDo
begin
Reply(620);
NOption(621,Hiring,4);
NOption(532,Royce,4);
NOption(622,Node999,4);
NOption(623,HiringStupid,-3);
NOption(624,RoyceStupid,-3);
NOption(625,Node999,-3);
end

procedure Hiring
begin
   if (global_var(GVAR_KNOW_WASTE_DISPOSAL) == 0) then
      set_global_var(GVAR_KNOW_WASTE_DISPOSAL, 1);
Reply(650);
NOption(651,Royce,4);
NOption(652,Node999,4);
end

// Node Royce
//
// Notes:
//
// 2) available if PC does not have THE STINK

procedure Royce
begin
Reply(680);
NOption(681,Royce2,4);
NOption(682,Hiring,4);
NOption(683,Node999,4);
end

procedure Royce2
begin
Reply(710);
NOption(711,Women,4);
NOption(712,Node999,4);
end

procedure Women
begin
Reply(740);
NOption(741,Sure,4);
NOption(742,Node999,4);
end

procedure Sure
begin
   set_global_var(GVAR_KNOW_BAD_BEER, 1);
Reply(770);
NOption(771,Node999,4);
NOption(772,Node999,4);
end

procedure Robbed
begin
Reply(mstr(800)+dude_name+mstr(801));
NOption(802,NoIdea,4);
NOption(803,RefuseCompRob,4);
NOption(804,Node999,4);
NOption(805,NoIdea,-3);
NOption(806,RefuseCompRob,-3);
NOption(807,Node999,-3);
end

procedure RobbedKilled
begin
Reply(mstr(800)+dude_name+mstr(830));
NOption(802,NoIdea,4);
NOption(803,RefuseCompKill,4);
NOption(804,Node999,4);
NOption(805,NoIdea,-3);
NOption(806,RefuseCompKill,-3);
NOption(807,Node999,-3);
end

procedure NoIdea
begin
Reply(860);
NOption(861,Node999,4);
NOption(862,Node999,-3);
end

procedure RefuseCompKill
begin
Reply(890);
NOption(891,Node999,4);
NOption(504,Node999,-3);
end

procedure RefuseCompRob
begin
Reply(920);
NOption(891,Node999,4);
NOption(504,Node999,-3);
end

procedure HiringStupid
begin
   if (global_var(GVAR_KNOW_WASTE_DISPOSAL) == 0) then
      set_global_var(GVAR_KNOW_WASTE_DISPOSAL, 1);

if (dude_is_male) then Reply(mstr(950)+dude_name+mstr(951)); else
if (dude_is_female) then Reply(mstr(950)+dude_name+mstr(952));
NOption(953,RoyceStupid,-3);
NOption(954,Node999,-3);
end

// Node RoyceStupid
//
// Notes:
//
// 2) available if PC does not have THE STINK

procedure RoyceStupid
begin
Reply(980);
NOption(981,MoneyStupid,-3);
NOption(982,HiringStupid,-3);
NOption(983,Node999,-3);
end

procedure MoneyStupid
begin
Reply(1010);
NOption(1011,HiringStupid,-3);
NOption(1012,Node999,-3);
end

//xxxxxxxxxxxxxxxxxxxx
