/*

        Name:           Eugene
        Location:
        Description:

           Created: 29/09/2020 19:20:15

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBEUGENE

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure Skill_Check_001_Speech;
procedure Skill_Check_000_Barter;




// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure StartD;
procedure AA;
procedure B_Pass;
procedure II;
procedure JJ;
procedure B_Fail;
procedure GG;
procedure HH;
procedure ZZ;
procedure LL;
procedure KK;
procedure MM;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure ZZ_3000;
procedure OpenDoor;
procedure Node019;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Pissed               (8)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
call new_plague_check(self_obj, LVAR_Herebefore);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=1;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

   if(local_var(LVAR_Pissed) == 1) then begin
      floater_bad_rand(150, 152);

      reg_anim_clear(self_obj);
      reg_anim_begin();
      animate_move_obj_to_tile(
         self_obj,
         tile_num_in_direction(
            tile_num(self_obj),
            random(0, 5),
            random(3, 5)
         ),
         ANIMATE_WALK
      );
      reg_anim_end();


      return;
   end

   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,HEAD_EUGENE,BACKGROUND_HUB);
       gSay_Start;
       call StartD;
       gSay_End;
       end_dialogue;


   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_evil_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

procedure Skill_Check_001_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -10);
if is_success(roll_temp) then
begin
call B_Pass;
end
else begin
call B_Fail;
 end
end

procedure Skill_Check_000_Barter begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_BARTER, -10);
if is_success(roll_temp) then
begin
call KK;
end
else begin
call MM;
 end
end





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


// Node Start
//
// Notes:
//
// Option 1 should not appear if PC's PE is less than 6

procedure StartD
begin
Reply(200);
if (get_critter_stat(dude_obj,STAT_pe)>=6) then
NOption(201,AA,4);
// NOTE: if the player fails this check, it should lead to node B_Fail
if (has_skill(dude_obj,SKILL_CONVERSANT)>=75) then
NOption(202,Skill_Check_001_Speech,4);
NOption(203,II,4);
if (obj_is_carrying_obj_pid(dude_obj,PID_PASSWORD_PAPER_EUGENE)>0) then
NOption(204,ZZ,4);
if (get_critter_stat(dude_obj,STAT_pe)>=6) then
NOption(205,Node017,4);
NOption(206,Node999,4);
NOption(207,Node016,-3);
end

procedure AA
begin
Reply(230);
NOption(231,JJ,4);
NOption(232,Node999,4);
end

procedure B_Pass
begin
Reply(260);
NOption(261,GG,4);
NOption(262,HH,4);
end

procedure II
begin
if (dude_is_male) then Reply(290); else
if (dude_is_female) then Reply(291);
// NOTE: This should remove 3000 caps from the players inverntory.
if (item_caps_total(dude_obj)>=3000) then
NOption(292,ZZ_3000,4);
// NOTE: Failure on the check should lead to M
if (has_skill(dude_obj,SKILL_BARTER)>=65) then
NOption(293,Skill_Check_000_Barter,4);
NOption(294,Node999,4);
end

// Node JJ
//
// Notes:
//
// At this point, the sentry should start counting down from 10, one number per response.

procedure JJ
begin
Reply(320);
NOption(321,Node013,4);
NOption(322,Node013,4);
// NOTE: This option will result in the player correctly guessing the password after 4-6 clicks, assuming they pass the luck check.
if (get_critter_stat(dude_obj,STAT_lu)>8) then
NOption(323,LL,4);
NOption(324,II,4);
end

procedure B_Fail
begin
Reply(350);
NOption(351,Node999,4);
end

procedure GG
begin
Reply(380);
NOption(381,ZZ,4);
end

procedure HH
begin
Reply(410);
NOption(411,GG,4);
NOption(412,Node999,4);
end

// Node ZZ
//
// Notes:
//
// This should (Duh!) open the gate.

procedure ZZ
begin
Reply(440);
NOption(441,OpenDoor,4);
end

// Node LL
//
// Notes:
//
// This node can only be accessed if the player passes the luck check at option 3, node J.

procedure LL
begin
Reply(470);
NOption(471,ZZ,4);
end

procedure KK
begin
   item_caps_adjust(dude_obj, -2000);
   item_caps_adjust(self_obj, 2000);
Reply(500);
NOption(501,ZZ,4);
end

procedure MM
begin
Reply(530);
// NOTE: This should deduct 3000 bottlecaps from the PC.
NOption(531,ZZ_3000,4);
NOption(532,Node999,4);
end

procedure Node013
begin
Reply(560);

NOption(321,Node014,4);
NOption(322,Node014,4);
// NOTE: This option will result in the player correctly guessing the password after 4-6 clicks, assuming they pass the luck check.
if (get_critter_stat(dude_obj,STAT_lu)>8) then
NOption(323,LL,4);
NOption(324,II,4);

end

procedure Node014
begin
Reply(590);

NOption(321,Node015,4);
NOption(322,Node015,4);
// NOTE: This option will result in the player correctly guessing the password after 4-6 clicks, assuming they pass the luck check.
if (get_critter_stat(dude_obj,STAT_lu)>8) then
NOption(323,LL,4);
NOption(324,II,4);

end

procedure Node015
begin
   set_local_var(LVAR_Pissed, 1);
Reply(620);
NOption(621,Node999,4);
NOption(622,Node999,4);
end

procedure Node016
begin
Reply(650);
NOption(651,Node999,-3);
end

procedure Node017
begin
   set_local_var(LVAR_Pissed, 1);
Reply(680);
NOption(681,Node018,4);
end

procedure Node018
begin
Reply(710);
NOption(351,Node999,4);
end

procedure Node019
begin

set_global_var(GVAR_FERGIE_EASY_WOMAN, 1);

   if(global_var(GVAR_ANGELA_DEAD) == 1) then begin
      set_global_var(GVAR_EUGENE_ROBB, 1);
Reply(741);
NOption(742,Node999,4);
end else begin
Reply(740);
NOption(743,Node999,4);
end

end

procedure ZZ_3000 begin
   item_caps_adjust(dude_obj, -3000);
   item_caps_adjust(self_obj, 3000);
   call ZZ;

end

procedure OpenDoor begin
   variable door;

   fadeout(1);

   door := tile_contains_pid_obj(12887, 0, 33554628);

   obj_unlock(door);                                    // engine unlock door
   obj_open(door);

   fadein(1);

end

//xxxxxxxxxxxxxxxxxxxx
