/*
	Animate forever
*/


#include "..\headers\define.h"
#include "..\headers\command.h"

#define NAME                    SCRIPT_TBFFODY1

procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure timed_event_p_proc;
procedure animfrvr;

variable sfx;

procedure map_enter_p_proc begin

    if(global_var(GVAR_TIBBETS_COUNTDOWN) == 0) then begin
        set_obj_visibility(self_obj, 1);
     end

   call animfrvr;
   add_timer_event(self_obj, 1, 1);
end

procedure map_update_p_proc begin
   if (
      (not(combat_is_initialized)) and
      (self_elevation == dude_elevation)
   ) then
   begin
      call animfrvr;
   end
end

procedure timed_event_p_proc begin

   if(not(obj_is_visible_flag(self_obj)) and global_var(GVAR_TIBBETS_COUNTDOWN) != 0) then begin
      set_obj_visibility(self_obj, 0);
   end

  if (fixed_param == 1) then begin
      if (
         (not(anim_busy(self_obj))) and
         (not(combat_is_initialized)) and
         (self_elevation == dude_elevation)
         ) then begin
            call animfrvr;
      end
      add_timer_event(self_obj, 1, 1);
  end
end

procedure animfrvr begin
   reg_anim_begin();
   reg_anim_animate_forever(self_obj, ANIM_stand);
   reg_anim_end();
end
