/*

        Name:           Frank
        Location:       Tibbets
        Description:    Frank the Underseer

           Created: 01/08/2020 14:15:39

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBFRANK

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (0)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\Party.h"
#include "..\HEADERS\partybkg.h"
#include "..\HEADERS\vault8.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure GivePipBoy;
procedure GiveQuests;

/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node002a;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_GivePipBoy                (8)
#define LVAR_Overseer                  (9)
#define LVAR_GiveQuests                (10)
#define LVAR_Greet                      (11)


/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_VAULT8);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);

   if (local_var(LVAR_Greet) == 0) then begin
      add_timer_event(self_obj,game_ticks(1),0);
   end
end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and self_can_see_dude) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
call set_idiot_savant_int;

   start_gdialog(NAME,self_obj,4,HEAD_FRANK_THE_UNDERSEER,PartyMemberBackground);
   gSay_Start;

   if (
      (global_var(GVAR_QUEST_FIX_GENERATOR) == 2) and
      (global_var(GVAR_QUEST_ACTIVATE_LIFE_SUPPORT) == 2)
   ) then begin
      call Node009;
   end else if (local_var(LVAR_Herebefore)==0) then begin
      call Node001;
   end else if (local_var(LVAR_Herebefore)==1 and not(dude_is_stupid)) then begin
      call Node008;
   end else if (local_var(LVAR_Herebefore)==1 and dude_is_stupid) then begin
      call Node014;
   end

   gSay_End;
   end_dialogue;
call restore_idiot_savant_int;
end

procedure timed_event_p_proc begin

   if (fixed_param == 0 and (local_var(LVAR_Greet) == 0) and not(is_loading_game)) then begin
      if (self_can_see_dude and self_can_speak) then begin
         floater_bad(106);
         set_local_var(LVAR_Greet, 1);
      end
      else begin
         add_timer_event(self_obj,game_ticks(1),0);
      end
   end

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end

if (
   (global_var(GVAR_QUEST_ACTIVATE_LIFE_SUPPORT) == 1) and
   (map_var(MVAR_SIMTEK11) == 0)
) then begin
   set_map_var(MVAR_SIMTEK11, 1);
   play_sfx("SIMTEK11");
   display_msg(message_str(SCRIPT_VAULT8, 107));
end

end

// Skill checks and miscellaneous procedures

procedure GivePipBoy begin

   if(local_var(LVAR_Overseer) == 1) then begin
      call GiveQuests;
      call Node999;
   end

   if(local_var(LVAR_GivePipBoy) == 0) then begin
      call GiveQuests;
      call Node010;
   end
   else begin
      call Node999;
   end
end

procedure GiveQuests begin

      if((local_var(LVAR_GiveQuests) == 0) and not(dude_is_stupid)) then begin
         if(global_var(GVAR_QUEST_REPAIR_FEB) == 0) then begin
            set_global_var(GVAR_QUEST_REPAIR_FEB, 1);
         end
         if(global_var(GVAR_QUEST_FIX_GENERATOR) == 0) then begin
           set_global_var(GVAR_QUEST_FIX_GENERATOR, 1);
         end
         if(global_var(GVAR_QUEST_ACTIVATE_LIFE_SUPPORT) == 0) then begin
            set_global_var(GVAR_QUEST_ACTIVATE_LIFE_SUPPORT, 1);
         end
         set_local_var(LVAR_GiveQuests, 1);

      end

end

// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
Reply(200);
NOption(mstr(201)+dude_name+mstr(202),Node002,4);
if(has_fake_trait(TRAIT_big_liar) or (dude_charisma > 6) or (has_skill(dude_obj, SKILL_CONVERSANT) > 75)) then begin
NOption(203,Node012,4);
NOption(204,Node013,-3);
end
NOption(205,Node015,-3);
if(not(has_fake_trait(TRAIT_soothsayer))) then begin
NOption(206,Node015,-3);
NOption(207,Node002,4);
end

if(map_var(MVAR_MOREAU_DRUGS) == 1) then begin
   NOption(208,Node002a,4);
end

end

procedure Node002a begin
   give_xp(100);
   display_mstr(105);
Reply(229);
NOption(231,Node003,4);
end


procedure Node002 begin
Reply(230);
NOption(231,Node003,4);
end

procedure Node003
begin
Reply(260);
NOption(261,Node004,4);
end

procedure Node004
begin
Reply(290);
NOption(291,Node005,4);
NOption(292,Node006,4);
NOption(293,Node007,4);
NOption(294,GivePipBoy,4);
end

procedure Node005
begin
Reply(320);
NOption(292,Node006,4);
NOption(293,Node008,4);
NOption(294,GivePipBoy,4);
end

procedure Node006
begin
Reply(350);
NOption(291,Node005,4);
NOption(293,Node007,4);
NOption(294,GivePipBoy,4);
end

procedure Node007
begin
Reply(380);
NOption(291,Node005,4);
NOption(292,Node006,4);
NOption(294,GivePipBoy,4);
end

procedure Node008
begin
Reply(410);
NOption(291,Node005,4);
NOption(292,Node006,4);
NOption(293,Node007,4);
NOption(294,GivePipBoy,4);
end

procedure Node009
begin
Reply(440);
NOption(441,Node011,4);
NOption(442,Node999,4);
NOption(443,Node011,-3);
NOption(444,Node999,-3);
NOption(445,Node999,4);
end

procedure Node010 begin
   set_pipboy_available(1);
   set_local_var(LVAR_GivePipBoy, 1);
   give_pid_qty(dude_obj, PID_LIL_PIP_3000, 1)

Reply(470);
NOption(471,Node999,4);
NOption(472,Node999,-3);
end

procedure Node011 begin
Reply(500);
NOption(501,Node999,4);
NOption(294,Node999,4);
NOption(503,Node999,4);
NOption(502,Node999,-3);
end

procedure Node012
begin
   set_local_var(LVAR_Overseer, 1);
Reply(530);
NOption(531,Node003,4);
NOption(532,GivePipBoy,4);
end

procedure Node013
begin
Reply(560);
NOption(561,GivePipBoy,-3);
end

procedure Node014
begin
Reply(590);
NOption(591,Node999,-3);
end

procedure Node015
begin
Reply(620);
NOption(621,GivePipBoy,-3);
end


//xxxxxxxxxxxxxxxxxxxx
