/*

        Name:           Lowell
        Location:
        Description:

           Created: 05/10/2020 16:12:19

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBLOWELL

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending



// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure AA;
procedure BB;
procedure CC;
procedure DD;
procedure FF;
procedure GG;
procedure HH;
procedure II;
procedure JJ;
procedure KK;
procedure LL;
procedure MM;
procedure PP;
procedure QQ;
procedure RR;
procedure SS;
procedure TT;
procedure UU;
procedure VV;
procedure WW;
procedure XX;
procedure YY;
procedure ZZ;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
call new_plague_check(self_obj, LVAR_Herebefore);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;
       call AA;
       gSay_End;
       end_dialogue;


   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures



// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure AA
begin
Reply(200);
BOption(201,BB,4);
NOption(mstr(202)+dude_name+mstr(203),CC,4);
NOption(204,DD,4);
NOption(205,Node999,4);
end

procedure BB
begin
Reply(230);
NOption(231,GG,4);
GOption(mstr(232)+dude_name+mstr(203),CC,4);
NOption(233,Node999,4);
end

procedure CC
begin
Reply(260);
NOption(261,II,4);
NOption(262,FF,4);
NOption(263,GG,4);
BOption(264,HH,4);
NOption(265,Node999,4);
end

procedure DD
begin
Reply(290);
NOption(261,II,4);
NOption(262,FF,4);
NOption(263,GG,4);
BOption(264,HH,4);
NOption(265,Node999,4);
end

procedure FF
begin
Reply(320);
NOption(321,GG,4);
NOption(322,Node999,4);
end

procedure GG
begin
Reply(350);
NOption(351,JJ,4);
NOption(352,KK,4);
NOption(353,LL,4);
NOption(354,Node999,4);
end

procedure HH
begin
Reply(380);
NOption(381,Node999,4);
end

// Node II
//
// Notes:
//
// PC should now have location of FA in his/her Pipboy.

procedure II
begin
Reply(410);
NOption(411,GG,4);
NOption(412,Node999,4);
end

procedure JJ
begin
Reply(440);
NOption(441,PP,4);
NOption(442,GG,4);
NOption(443,Node999,4);
end

procedure KK
begin
Reply(470);
NOption(471,MM,4);
NOption(472,MM,4);
NOption(473,Node999,4);
end

procedure LL
begin
Reply(500);
NOption(501,RR,4);
GOption(502,SS,4);
NOption(503,GG,4);
NOption(504,Node999,4);
end

procedure MM
begin
Reply(530);
NOption(531,XX,4);
NOption(532,YY,4);
NOption(533,GG,4);
NOption(534,Node999,4);
end

procedure PP
begin
Reply(560);
NOption(561,QQ,4);
NOption(562,GG,4);
NOption(563,Node999,4);
end

procedure QQ
begin
if (dude_is_male) then Reply(590); else
if (dude_is_female) then Reply(591);
NOption(562,GG,4);
NOption(592,Node999,4);
end

procedure RR
begin
Reply(620);
NOption(621,TT,4);
NOption(622,TT,4);
NOption(623,GG,4);
NOption(624,Node999,4);
end

procedure SS
begin
Reply(650);
NOption(651,RR,4);
NOption(652,Node999,4);
NOption(653,AA,4);
end

procedure TT
begin
Reply(680);
if (global_var(GVAR_KNOW_RAKE) == 1) then
NOption(685,WW,4);
else
NOption(681,UU,4);
BOption(682,VV,4);
NOption(683,GG,4);
NOption(684,Node999,4);
end

procedure UU
begin
Reply(710);
NOption(562,GG,4);
NOption(711,WW,4);
end

procedure VV
begin
Reply(740);
NOption(741,GG,4);
NOption(742,Node999,4);
end

procedure WW
begin
Reply(770);
NOption(381,Node999,4);
end

procedure XX
begin
Reply(800);
NOption(801,YY,4);
GOption(802,ZZ,4);
NOption(562,GG,4);
NOption(803,Node999,4);
end

procedure YY
begin
Reply(830);
NOption(831,XX,4);
NOption(562,GG,4);
NOption(832,Node999,4);
end

// Node ZZ
//
// Notes:
//
// PC now has new quest "Find The Beast"

procedure ZZ
begin
Reply(860);
NOption(861,GG,4);
NOption(862,Node999,4);
end



//xxxxxxxxxxxxxxxxxxxx
