/*

        Name:           Father Maurice
        Location:       CB29
        Description:

           Created: 27/09/2020 11:29:55

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBMAURIC

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\HEADERS\tbcb29.h"

/* Helper macros */

variable temp;
import variable maurice_ptr;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure map_update_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure PersuadeLeave;

// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Floats;
procedure High;
procedure Switcher;
procedure First;
procedure Subsequent;
procedure ExposedFirst;
procedure DrugFirst;
procedure WhoIs;
procedure Questions;
procedure WhatDo;
procedure Accuse;
procedure Deny;
procedure Deny2;
procedure Sonia;
procedure Ini2;
procedure AskDJ;
procedure BetterHigh;
procedure Probably;
procedure DrugQuestion;
procedure ThatsNothing;
procedure PsychoBrag;
procedure BustedSonia;
procedure BustedIni;
procedure BustedTrick;
procedure BustedDrug;
procedure DoDrugs;
procedure DoDrugs2;
procedure DoDrugs3;
procedure HaveLeave;
procedure WillLeave;
procedure WontLeave;
procedure Threat;
procedure Intimidated;
procedure NotIntimidated;
procedure DrugsLeave;
procedure DrugsKill;
procedure DrugsThreat;
procedure DrugsIntimidate;
procedure DrugsNotIntimidate;
procedure BuyDrugs;
procedure DrugBuyDrugs;
procedure Leave;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Dealer                     (8)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
   maurice_ptr := self_obj;
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_MAURICE);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
   maurice_ptr := self_obj;
   add_timer_event(self_obj,game_ticks(random(1,5)),0);
   call new_plague_check(self_obj, LVAR_Herebefore);

   if((global_var(GVAR_TIPOFF_FATHER) == 2) or (map_var(MVAR_MAURICE_GONE) == 1)) then begin

      set_map_var(MVAR_MAURICE_GONE, 1);
      destroy_object(self_obj);

   end

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude) and obj_is_visible_flag(self_obj)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

procedure map_update_p_proc begin
   maurice_ptr = self_obj;
end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=1;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

   if(dude_is_stupid or dude_is_idiot_savant) then begin
      floater_bad_rand(260, 262);
      return;
   end

   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;

      if(local_var(LVAR_Dealer) == 1) then begin
         call ExposedFirst;
      end
      else if (local_var(LVAR_Dealer) == 2) then begin
         call DrugFirst;
      end
      else begin

         if (local_var(LVAR_Herebefore)==0) then begin
               call First;
         end else if (local_var(LVAR_Herebefore)==1) then begin
               call Subsequent;
         end

      end

       gSay_End;
       end_dialogue;


   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin
   add_timer_event(self_obj,game_ticks(random(1,5)),0);

   if(local_var(LVAR_Dealer) == 2) and (obj_is_visible_flag(self_obj)) then
      floater_high_rand(230,232);

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_evil_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

procedure PersuadeLeave begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -10);
if is_success(roll_temp) then
begin
call WillLeave;
end
else begin
call WontLeave;
 end
end



// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure First
begin
Reply(290);
NOption(291,WhoIs,4);
NOption(292,Node999,4);
end

procedure Subsequent
begin
Reply(320);
NOption(321,Questions,4);
NOption(322,Node999,4);
end

procedure ExposedFirst
begin
Reply(350);
NOption(351,HaveLeave,4);
NOption(352,Threat,4);
NOption(353,BuyDrugs,4);
NOption(354,Node999,4);
end

procedure DrugFirst
begin
Reply(380);
NOption(351,DrugsLeave,4);
NOption(352,DrugsThreat,4);
NOption(381,DrugBuyDrugs,4);
NOption(382,Node999,4);
end

procedure WhoIs
begin
Reply(410);
NOption(321,Questions,4);
NOption(411,Node999,4);
end

// Node Questions
//
// Notes:
//
// 3) available if either Sonia or Ini has fingered Maurice

procedure Questions
begin
Reply(440);
NOption(441,WhatDo,4);
NOption(442,AskDJ,4);
NOption(443,Accuse,4);
NOption(444,Node999,4);
end

procedure WhatDo
begin
Reply(470);
NOption(471,Accuse,4);
NOption(472,AskDJ,4);
NOption(473,Node999,4);
end

// Node Accuse
//
// Notes:
//
// 1) if Sonia has accused Maurice 2) if ini has accused Maurice

procedure Accuse
begin
Reply(500);
if (map_var(MVAR_ABE_HOLY_WATER)==1) then
NOption(501,Sonia,4);
NOption(502,Ini2,4);
NOption(503,Deny,4);
NOption(504,Node999,4);
end

procedure Deny
begin
Reply(530);
NOption(531,Deny2,4);
NOption(532,BetterHigh,4);
NOption(533,Node999,4);
end

procedure Deny2
begin
Reply(560);
if (obj_is_carrying_obj_pid(dude_obj,PID_MENTATS)>0) or (obj_is_carrying_obj_pid(dude_obj,PID_BUFFOUT)>0) or (obj_is_carrying_obj_pid(dude_obj,PID_PSYCHO)>0) or (obj_is_carrying_obj_pid(dude_obj,PID_JET)>0) then
NOption(561,BetterHigh,4);
NOption(562,Node999,4);
end

// Node Sonia
//
// Notes:
//
// 1) if ini has accused Maurice

procedure Sonia
begin
Reply(590);
NOption(591,Ini2,4);
NOption(592,Deny,4);
NOption(593,BustedSonia,4);
NOption(594,Node999,4);
end

// Node Ini
//
// Notes:
//
// 1) if Sonia has accused Maurice

procedure Ini2
begin
Reply(620);
if (map_var(MVAR_ABE_HOLY_WATER)==1) then
NOption(621,Sonia,4);
NOption(622,Deny,4);
NOption(623,BustedIni,4);
NOption(624,Node999,4);
end

// Node AskDJ
//
// Notes:
//
// 1) if ini has accused Maurice

procedure AskDJ
begin
Reply(650);
NOption(651,Ini2,4);
NOption(652,Deny,4);
NOption(653,Node999,4);
end

// Node BetterHigh
//
// Notes:
//
// 1) if the player has done hard drugs (psycho, mentats, buffout), or has some in his inventory

procedure BetterHigh
begin
Reply(680);
NOption(681,DrugQuestion,4);
NOption(682,Probably,4);
end

// Node Probably
//
// Notes:
//
// 1) if the player has done hard drugs (psycho, mentats, buffout), or has some in his inventory

procedure Probably
begin
Reply(710);
NOption(711,DrugQuestion,4);
NOption(712,Node999,4);
end

// Node DrugQuestion
//
// Notes:
//
// 1) only available if player has done psycho 2) only available if player has done buffout 3) only available if player has done mentats

procedure DrugQuestion
begin
Reply(740);
NOption(741,PsychoBrag,4);
NOption(742,ThatsNothing,4);
NOption(743,ThatsNothing,4);
end

procedure ThatsNothing
begin
Reply(770);
NOption(771,BustedTrick,4);
NOption(772,DoDrugs,4);
end

procedure PsychoBrag
begin
Reply(800);
NOption(771,BustedTrick,4);
NOption(801,DoDrugs,4);
end

// Node BustedSonia
//
// Notes:
//
// Maurice is exposed

procedure BustedSonia
begin
   set_local_var(LVAR_Dealer, 1);
   set_global_var(GVAR_TIPOFF_FATHER, 1);
   set_global_var(GVAR_TIBBETS_KNOW_JUNKIES, 1);
Reply(830);
NOption(831,HaveLeave,4);
NOption(832,Threat,4);
NOption(833,BuyDrugs,4);
NOption(834,Node999,4);
end

// Node BustedIni
//
// Notes:
//
// Maurice is exposed

procedure BustedIni
begin
   set_local_var(LVAR_Dealer, 1);
   set_global_var(GVAR_TIPOFF_FATHER, 1);
   set_global_var(GVAR_TIBBETS_KNOW_JUNKIES, 1);
Reply(860);
NOption(861,HaveLeave,4);
NOption(862,Threat,4);
NOption(833,BuyDrugs,4);
NOption(863,Node999,4);
end

// Node BustedTrick
//
// Notes:
//
// Maurice is exposed

procedure BustedTrick
begin
   set_local_var(LVAR_Dealer, 1);
   set_global_var(GVAR_TIPOFF_FATHER, 1);
   set_global_var(GVAR_TIBBETS_KNOW_JUNKIES, 1);
Reply(890);
NOption(891,HaveLeave,4);
NOption(892,Threat,4);
NOption(893,BuyDrugs,4);
NOption(894,Node999,4);
end

// Node BustedDrug
//
// Notes:
//
// Maurice is exposed

procedure BustedDrug
begin
   set_local_var(LVAR_Dealer, 1);
   set_global_var(GVAR_TIPOFF_FATHER, 1);
   set_global_var(GVAR_TIBBETS_KNOW_JUNKIES, 1);
Reply(920);
NOption(891,DrugsLeave,4);
NOption(921,DrugsThreat,4);
NOption(893,DrugBuyDrugs,4);
NOption(922,Node999,4);
end

procedure DoDrugs
begin
Reply(950);
NOption(951,DoDrugs2,4);
NOption(952,BustedTrick,4);
end

// Node DoDrugs2
//
// Notes:
//
// Maurice is now high on Psycho

procedure DoDrugs2
begin
   set_local_var(LVAR_Dealer, 2);
Reply(980);
NOption(981,DoDrugs3,4);
NOption(982,BustedDrug,4);
end

// Node DoDrugs3
//
// Notes:
//
// Player suffers the effects of Psycho.

procedure DoDrugs3
begin
Reply(1010);
NOption(1011,BustedDrug,4);
end

procedure HaveLeave
begin
Reply(1040);
NOption(1041,PersuadeLeave,4);
NOption(1042,Threat,4);
end

procedure WillLeave
begin
Reply(1070);
NOption(1071,Leave,4);
end

procedure WontLeave
begin
Reply(1100);
NOption(1101,Threat,4);
NOption(1102,Node999,4);
end

// Node Threat
//
// Notes:
//
// 1) go here if moderate intimidate check passed - 2) if check failed

procedure Threat
begin
Reply(1130);
if (get_critter_stat(dude_obj,STAT_ch)>=6) then
NOption(1131,Intimidated,4);
if (get_critter_stat(dude_obj,STAT_ch)<=5) then
NOption(1131,NotIntimidated,4);
BOption(1132,Node998,4);
end

procedure Intimidated
begin
Reply(1160);
NOption(1161,Leave,4);
end

procedure NotIntimidated
begin
Reply(1190);
BOption(1191,Node998,4);
NOption(1102,Node999,4);
end

procedure DrugsLeave
begin
Reply(1220);
NOption(1221,DrugsKill,4);
NOption(1222,DrugsThreat,4);
NOption(1223,Node999,4);
end

procedure DrugsKill
begin
if (dude_is_male) then Reply(1250); else
if (dude_is_female) then Reply(1251);
BOption(1252,Node998,4);
end

// Node DrugsThreat
//
// Notes:
//
// 1) if hard intimidate check passed (Maurice could take on the world at this point) 2) if check failed.

procedure DrugsThreat
begin
Reply(1280);
if (get_critter_stat(dude_obj,STAT_en)>=6) then
NOption(1281,DrugsIntimidate,4);
if (get_critter_stat(dude_obj,STAT_en)<=5) then
NOption(1281,DrugsNotIntimidate,4);
BOption(1282,Node998,4);
end

procedure DrugsIntimidate
begin
Reply(1310);
NOption(1311,Leave,4);
end

procedure DrugsNotIntimidate
begin
Reply(1340);
BOption(1252,Node998,4);
end

procedure BuyDrugs
begin
Reply(1370);
NOption(1371,HaveLeave,4);
NOption(1372,Threat,4);
NOption(1373,Node999,4);
end

procedure DrugBuyDrugs
begin
Reply(1400);
NOption(1401,DrugsLeave,4);
NOption(921,DrugsThreat,4);
NOption(1402,Node999,4);
end

procedure Leave begin
   call Node999;
   fadeout(1);
   set_obj_visibility(self_obj, 1);
   give_xp(350);
   display_mstr(150);
   inc_global_var_amt(GVAR_TOWN_REP_TIBBETS, 20);
   inc_general_rep(10);
   set_map_var(MVAR_MAURICE_GONE, 1);
   fadein(1);
end

//xxxxxxxxxxxxxxxxxxxx
