/*

        Name:           Rake
        Location:
        Description:    Gives the PC a pacifist mutant's perspective of the world.

           Created: 29/09/2020 10:54:59

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBRAKE

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Rake_1a_1;
procedure Rake_1a_2;
procedure Rake_1b;
procedure Rake_1c_1;
procedure Rake_1c_2;
procedure Rake_1D_a1;
procedure Rake_1D_a2;
procedure Rake_1D_b1;
procedure Rake_2_1;
procedure Rake_2_2;
procedure Rake_2_3;
procedure Rake_2_4a_1;
procedure Rake_2_4a_2;
procedure Rake_2_4b;
procedure Rake_2_4BA;
procedure Rake_3_1;
procedure Rake_4_1;
procedure Rake_4_2;
procedure Rake_5_0;
procedure Rake_5_1;
procedure Rake_5_2a;
procedure Rake_5_2B;
procedure Rake_9;
procedure Rake_9_t;
procedure Rake_9_D;
procedure Rake_B1;
procedure Rake_B2;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Rake_B1_b;
procedure Rake_4_2_b;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Temper                     (8)


/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);

   add_timer_event(self_obj, game_ticks(random(3, 5)), 0);

   call new_plague_check(self_obj, LVAR_Herebefore);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and self_can_see_dude) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

   if (local_var(LVAR_Herebefore)==1 and dude_is_super_mutant) then begin
      floater_rand(200, 203);
 end
 else begin

   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,1,HEAD_RAKE,BACKGROUND_ENCLAVE);
       gSay_Start;

   if(local_var(LVAR_Temper) < 0) then begin
      call Rake_1c_1;
   end
   else if(dude_is_super_mutant) then begin
      if (local_var(LVAR_Herebefore)==0) then begin
         call Node028;
      end
   end else begin

      if (local_var(LVAR_Herebefore)==0) then begin
                  if(dude_is_stupid or dude_is_idiot_savant) then begin
            call Rake_1D_a1;
                  end else begin
            call Rake_1a_1;
                  end
      end else if (local_var(LVAR_Herebefore)==1) then begin
         if(dude_is_stupid or dude_is_idiot_savant) then begin
            call Rake_1D_b1;
         end else begin
            call Rake_1b;
         end
      end
   end

       gSay_End;
       end_dialogue;

   call restore_idiot_savant_int;

   end

end

procedure timed_event_p_proc begin

   add_timer_event(self_obj, game_ticks(random(3, 5)), 0);

    if (random(1, 30) == 1) then begin
       if(local_var(LVAR_Temper) < 0) then
         floater_bad_rand(230, 233);
       else
         floater_rand(260, 266);
   end

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
set_global_var(GVAR_KNOW_RAKE, 1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE

procedure Rake_1a_1
begin
Reply(320);
NOption(321,Rake_2_1,4);
// NOTE: First impressions count. Add 1 to the local variable Rake_Temper. (Which is a good thing).
GOption(mstr(322)+dude_name+mstr(323),Rake_1a_2,4);
if (not(dude_is_super_mutant)) then
NOption(324,Rake_3_1,4);
NOption(325,Rake_5_0,4);
end

procedure Rake_1a_2
begin
   inc_local_var_amt(LVAR_Temper, 1);
Reply(350);
NOption(351,Rake_2_2,4);
NOption(321,Rake_2_1,4);
if (not(dude_is_super_mutant)) then
NOption(324,Rake_3_1,4);
NOption(325,Rake_5_0,4);
end

procedure Rake_1b
begin
Reply(380);
NOption(321,Rake_2_1,4);
GOption(381,Rake_9_t,4);
NOption(382,Node999,4);
end

// Node Rake_1c_1
//
// Notes:
//
// This option begins the dialogue if the local variable Rake_Temper < 0. (ie: the PC has pissed Rake off).

procedure Rake_1c_1
begin
Reply(mstr(410)+dude_name+mstr(411));
// NOTE: Helps mend relations for the next time the PC speaks to the mutant. Add 1 to the local variable Rake_Temper. (Which is a good thing).
GOption(412,Rake_1c_2,4);
BOption(413,Rake_B2,4);
NOption(414,Node999,1);
end

procedure Rake_1c_2
begin
      inc_local_var_amt(LVAR_Temper, 1);

Reply(440);
NOption(414,Node999,4);
BOption(413,Rake_B2,4);
end

procedure Rake_1D_a1
begin
Reply(320);
GOption(mstr(470)+dude_name+mstr(471),Rake_1D_a2,-3);
NOption(472,Rake_2_1,-3);
NOption(473,Rake_3_1,-3);
end

procedure Rake_1D_a2
begin
Reply(mstr(500)+dude_name+mstr(501));
NOption(472,Rake_2_1,-3);
NOption(502,Rake_3_1,-3);
end

procedure Rake_1D_b1
begin
Reply(530);
NOption(472,Rake_2_1,-3);
NOption(531,Rake_3_1,-3);
NOption(532,Rake_9_D,-3);
end

// Node Rake_2_1
//
// Notes:
//
// The Rake_2_* path is where the PC can find out what Rake knows about his past.

procedure Rake_2_1
begin
Reply(560);
NOption(561,Rake_2_2,4);
NOption(562,Rake_2_3,4);
NOption(563,Rake_2_3,-3);
NOption(414,Node999,-3);
end

procedure Rake_2_2
begin
Reply(590);
NOption(591,Rake_2_3,4);
NOption(592,Rake_5_1,4);
NOption(593,Node999,4);
NOption(563,Rake_2_3,-3);
end

procedure Rake_2_3
begin
Reply(620);
NOption(621,Rake_2_4a_1,4);
NOption(622,Rake_2_4b,4);
// NOTE: Decrement the local variable Rake_Temper by 1.
BOption(623,Rake_2_4BA,4);
NOption(592,Rake_5_1,4);
NOption(624,Node999,4);
NOption(625,Rake_2_4a_1,-3);
NOption(626,Rake_9_D,-3);
NOption(627,Node999,-3);
end

procedure Rake_2_4a_1
begin
Reply(650);
// NOTE: Decrement the local variable Rake_Temper by 1.
NOption(651,Rake_2_4a_2,4);
NOption(622,Rake_2_4b,4);
NOption(652,Rake_9,4);
NOption(653,Node999,4);
NOption(654,Rake_9_D,-3);
NOption(627,Node999,-3);
end

procedure Rake_2_4a_2
begin
      dec_local_var_amt(LVAR_Temper, 1);

Reply(680);
NOption(681,Rake_B1,4);
NOption(682,Rake_9,4);
NOption(683,Node999,4);
end

procedure Rake_2_4b
begin
Reply(710);
NOption(711,Rake_2_4a_1,4);
NOption(712,Rake_9,4);
NOption(713,Node999,4);
end

procedure Rake_2_4BA
begin
      dec_local_var_amt(LVAR_Temper, 1);

Reply(740);
BOption(741,Rake_B1,4);
NOption(742,Rake_2_4a_1,4);
NOption(743,Node999,4);
end

// Node Rake_3_1
//
// Notes:
//
// The Rake_3_* path is available if the PC has spoken to Austin in Crossroads and heard his story about the 'big green men'.

procedure Rake_3_1
begin
Reply(770);
NOption(771,Rake_5_1,4);
NOption(772,Rake_2_2,4);
NOption(773,Rake_B2,4);
NOption(774,Rake_9,4);
NOption(775,Node999,4);
NOption(776,Rake_2_2,-3);
NOption(777,Rake_9_D,-3);
NOption(627,Node999,-3);
end

// Node Rake_4_1
//
// Notes:
//
// The Rake_4_* path is where the PC can ask about the problems Rake says he is having with rats.

procedure Rake_4_1
begin
Reply(800);
NOption(801,Node999,4);
NOption(802,Rake_4_2,4);
NOption(803,Rake_9,4);
NOption(804,Rake_9_D,-3);
NOption(627,Node999,-3);
end

procedure Rake_4_2
begin
Reply(830);
// NOTE: Decrement the local variable Rake_Temper by 1.
BOption(831,Rake_B1_b,4);
NOption(652,Rake_9,4);
NOption(832,Node999,4);
end

procedure Rake_5_0
begin
Reply(860);
NOption(861,Rake_5_1,4);
if (not(dude_is_super_mutant)) then
NOption(324,Rake_3_1,4);
end

// Node Rake_5_1
//
// Notes:
//

procedure Rake_5_1
begin
Reply(890);
NOption(891,Rake_5_2a,4);
// NOTE: Decrement the local variable Rake_Temper by 1.
BOption(892,Rake_5_2B,4);
NOption(893,Rake_2_2,4);
NOption(894,Node999,4);
end

procedure Rake_5_2a
begin
Reply(920);
NOption(921,Rake_2_4b,4);
NOption(922,Rake_9,4);
NOption(923,Node999,4);
end

procedure Rake_5_2B
begin
      dec_local_var_amt(LVAR_Temper, 1);

Reply(950);
BOption(951,Rake_B1,4);
NOption(891,Rake_5_2a,4);
NOption(893,Rake_2_2,4);
NOption(952,Node999,4);
end

procedure Rake_9
begin
Reply(980);
NOption(981,Rake_2_1,4);
NOption(982,Rake_3_1,4);
NOption(983,Rake_4_1,4);
// NOTE: Decrement the local variable Rake_Temper by 1.
BOption(984,Rake_4_2_b,4);
NOption(985,Rake_5_1,4);
NOption(986,Node999,4);
end

procedure Rake_9_D
begin
Reply(1010);
NOption(472,Rake_2_1,-3);
NOption(1011,Rake_3_1,-3);
NOption(1012,Rake_4_1,-3);
NOption(1013,Node999,-3);
end

procedure Rake_B1
begin
Reply(mstr(1040)+dude_name+mstr(1041)+dude_name+mstr(1042));
NOption(1043,Node999,4);
BOption(1044,Rake_B2,4);
end

procedure Rake_B2
begin
Reply(1070);
BOption(1071,Node998,4);
end

procedure Node028
begin
Reply(dude_name+mstr(1100));
NOption(1101,Node029,1);
end

procedure Node029
begin
Reply(1130);
NOption(1131,Node030,4);
NOption(1132,Node030,-3);
end

procedure Node030
begin
Reply(1160);
NOption(1161,Node031,4);
NOption(1162,Node031,-3);
end

procedure Node031
begin
Reply(1190);
NOption(1191,Node999,4);
NOption(1192,Node999,4);
NOption(1193,Rake_B2,4);
NOption(1194,Rake_B2,-3);
end

procedure Rake_9_t begin
   inc_local_var_amt(LVAR_Temper, 1);
   call Rake_9;
end


procedure Rake_B1_b begin
   dec_local_var_amt(LVAR_Temper, 1);
   call Rake_B1;
end

procedure Rake_4_2_b begin
   dec_local_var_amt(LVAR_Temper, 1);
   call Rake_4_2;
end


//xxxxxxxxxxxxxxxxxxxx
