//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "##HEADERS_PATH##\<TownName.h>"

#define NAME                    SCRIPT_TBRAYZE

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (0)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\headers\footsteps.h"

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

/* User defined variables */

procedure rayze00;
procedure rayze01;
procedure rayze02;
procedure rayze03;
procedure rayze04;
procedure rayze05;
procedure rayze05a;
procedure rayze06;
procedure rayze07;
procedure rayze08;
procedure rayze09;
procedure rayze10;
procedure rayze10a;
procedure rayze10b;
procedure rayze11;
procedure rayze12;
procedure rayze13;
procedure rayze14;
procedure rayze15;
procedure rayze16;
procedure rayze17;
procedure rayze19;

import variable Scouted_Fools;

variable Crypt_Liar := 1;

import variable Is_Fool;
import variable Is_Crypt;
import variable Broken_Gen;
import variable Rock_Invite;
import variable Know_Fools;
import variable Know_Power;
import variable Crypt_Pointer;
import variable Fool_Pointer;
import variable Phrax_Pointer;
import variable Rock_Pointer;

import variable Fool_Taunt;
import variable Crypt_Taunt;
import variable Fool_counter;
import variable Crypt_counter;

// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
   if (Is_Crypt) then begin
      switch_team(self_obj,TEAM_PLAYER)
   end
   else begin
      switch_team(self_obj,TEAM_CRYPTS)
   end
   art_change_fid_num(self_obj, FID_NMLTHR);
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   switch_team(self_obj,TEAM_CRYPTS)
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
   call critter_setup_footsteps_map_enter(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT);
end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if (Fool_Taunt) then begin
      Fool_Taunt := 0;
      if (random(1, 5) == 1) then begin
         floater_bad_rand(200, 224);
      end
   end
   else begin
      if ((global_var(GVAR_GANG_WAR) == 1) and (self_tile != 20725)) then begin
         animate_move_to_tile(20725);
      end
      else begin
         if (self_tile == 20725) then begin
            add_timer_event(self_obj, game_ticks(2), 1);
         end
         else begin
            if (Broken_Gen and (self_tile != 27504)) then begin
               set_global_var(GVAR_GANG_WAR, 2);
               animate_move_to_tile(27504);
            end
            else begin
               if ((self_tile == 27504) and (global_var(GVAR_GANG_WAR) == 2)) then begin
                  set_obj_visibility(self_obj, 1);
                  Crypt_counter := Crypt_counter - 1;
               end
               else begin
                  if ((local_var(LVAR_Hostile) != 0) and self_can_see_dude) then begin
                     set_local_var(LVAR_Hostile,1);
                     self_attack_dude;
                     //Macro made by Tom to keep the critter fleeing.
                  end
               end
            end
         end
      end
   end
end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin
   Evil_Critter:=1;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

   if (Is_Fool) then begin
      call rayze00;
   end
   else begin
      if (local_var(LVAR_Herebefore) and not(Is_Crypt)) then begin
         call rayze09;
      end
      else begin
         if (Fool_counter == 0) then begin
            floater_good(144);
            add_timer_event(self_obj, game_ticks(4), 3);
         end
         else begin
            if (global_var(GVAR_GANG_WAR)) then begin
               call rayze19;
            end
            else begin
               start_gdialog(NAME, self_obj, 4, HEAD_RAYZE, BACKGROUND_JUNKTOWN);
               gSay_Start;
               if (Is_Crypt) then
                  call rayze10;
               else
                  call rayze01;
               gsay_End;
               end_dialogue;
            end
         end
      end
   end

   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin

   variable critters, critter, team;

   if (fixed_param == 1) then begin
      set_global_var(GVAR_GANG_WAR, 0);
      if (self_can_speak and (Crypt_Taunt == 0)) then begin
         Crypt_Taunt := 1;
         floater_bad_rand(200, 224);
      end
      add_timer_event(self_obj, 4, 2);
   end
   else if (fixed_param == 2) then begin
      if(self_can_speak) then begin
         critters := objects_in_radius(self_tile, get_critter_base_stat(self_obj, STAT_pe), self_elevation, OBJ_TYPE_CRITTER);

         foreach (critter in critters) begin
            if(critter_attackable(critter) and obj_can_see_obj(self_obj, critter)) then begin
               team := has_trait(TRAIT_OBJECT, critter, OBJECT_TEAM_NUM);

               if(TEAM_FOOLS == team) then begin
                  self_attack_critter(critter);
                  break;
               end
            end
         end
      end
   end
   else if (fixed_param == 3) then begin
      set_global_var(GVAR_VT_HOLOGRAM, 1);
      display_msg(message_str(SCRIPT_SCRPHEAP, 403));
      destroy_obj_inven(dude_obj);
      load_map("tbsrvc03", 0);
   end

   call critter_setup_footsteps_timed_event(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT, SFX_FOOTSTEP_SOFT_SHOE);
end


/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

   Crypt_counter := Crypt_counter - 1;
/* Increment the aligned critter counter*/
   inc_evil_critter
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   display_mstr(100);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin

end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures




// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE

procedure rayze00 begin
   floater_bad(101);
   call Node998;
end

procedure rayze01 begin
   Reply(102);
   if (Rock_Invite) then begin
      NOption(103, rayze02, 4);
      NOption(303, rayze02, -3);
   end
   NOption(104, rayze07, 4);
   NOption(304, rayze07, -3);

   if (Know_Fools) then begin
         NOption(105, rayze14, 4);
         NOption(305, rayze14, -3);
   end
   if (Know_Power) then begin
      NOption(106, rayze15, 4);
      NOption(306, rayze15, -3);
   end
end

procedure rayze02 begin
   Reply(107);
   NOption(108, rayze03, 4);
   NOption(109, rayze04, 4);
   NOption(308, rayze03, -3);
   NOption(309, rayze04, -3);
end

procedure rayze03 begin
   Reply(110);
   NOption(136, Node999, 1);
end

procedure rayze04 begin
   Reply(111);
   NOption(112, rayze05, 1);
   NOption(113, rayze06, 1);
end

procedure rayze05 begin
   Reply(114);
   NOption(115, rayze05a, 1);
   NOption(116, rayze06, 4);
   NOption(316, rayze06, -3);
end

procedure rayze05a begin
   Is_Crypt := 1;
   Scouted_Fools := 1;
   set_global_var(GVAR_FSCOUT_1, 1);
end

procedure rayze06 begin
   if (dude_is_male) then
      Reply(117);
   else
      Reply(146);
   NOption(136, Node999, 1);
end

procedure rayze07 begin
   Reply(118);
   NOption(119, rayze08, 4);
   NOption(319, rayze08, -3);
end

procedure rayze08 begin
   Reply(120);
   NOption(121, rayze05, 4);
   NOption(122, rayze06, 4);
   NOption(321, rayze05, -3);
   NOption(322, rayze06, -3);
end

procedure rayze09 begin
   floater_bad(123);
   call Node999;
end

procedure rayze10 begin
   Reply(124);
   NOption(125, rayze10a, 1);
   NOption(126, rayze10b, 1);
   NOption(127, rayze13, 4);
   NOption(327, rayze13, -3);
end

procedure rayze10a begin
   if (Scouted_Fools == 2) then begin
      call rayze11;
   end
   else begin
      if (Crypt_Liar) then begin
         call rayze17;
      end
      else begin
         call rayze16;
      end
   end
end

procedure rayze10b begin
   if (Scouted_Fools == 2) then begin
      call rayze12;
   end
   else begin
      if (Crypt_Liar) then begin
         call rayze17;
      end
      else begin
         call rayze16;
      end
   end
end

procedure rayze11 begin
   set_global_var(GVAR_GANG_WAR, 1);
   Reply(128);
   NOption(136, Node999, 1);
end

procedure rayze12 begin
   set_global_var(GVAR_GANG_WAR, 1);
   Reply(129);
   NOption(136, Node999, 1);
end

procedure rayze13 begin
   Reply(130);
   NOption(136, Node999, 1);
end

procedure rayze14 begin
   Reply(131);
   if (Rock_Invite) then begin
      NOption(132, rayze02, 4);
      NOption(303, rayze02, -3);
   end
   NOption(133, rayze07, 4);
   NOption(304, rayze07, -3);
   if (Know_Power) then begin
      NOption(134, rayze15, 4);
      NOption(306, rayze15, -3);
   end
end

procedure rayze15 begin
   Reply(135);
   NOption(136, Node999, 1);
end

procedure rayze16 begin
   Crypt_Liar := 1;
   Reply(142);
   NOption(136, Node999, 1);
end

procedure rayze17 begin
   Reply(143);
   BOption(136, Node998, 1);
end

procedure rayze19 begin
   Reply(145);
   NOption(136, Node999, 1);
end

//xxxxxxxxxxxxxxxxxxxx
