/*

        Fan Made Fallout NPC Script

        Name:           Cultist
        Location:
        Description:

           Created: 29/09/2020 12:02:55

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBRAINCL

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure push_p_proc;
/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





/* User defined variables */




// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin

end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);

   add_timer_event(self_obj, game_ticks(random(3, 5)), 0);
   call new_plague_check(self_obj, LVAR_Herebefore);


end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin
   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

// 0 = non-member, 1 = member, 2 = prophet, 3  = kicked out
   if(global_var(GVAR_RAINMAKERS_STATUS) == 1) then begin
         floater_good_rand(230, 238);
   end else if(global_var(GVAR_RAINMAKERS_STATUS) == 2) then begin
         floater_high_rand(260, 267);
   end else if(global_var(GVAR_RAINMAKERS_STATUS) == 3) then begin
         floater_bad_rand(290, 298);
   end else begin
         floater_bad_rand(200, 209);
   end

end

procedure timed_event_p_proc begin

variable mind, maxd, minf, maxf;

   // 0 = non-member, 1 = member, 2 = prophet, 3  = kicked out
   if(global_var(GVAR_RAINMAKERS_STATUS) == 1) then begin
      if(random(1, 30) == 1) then
         floater_good_rand(230, 238);
   end else if(global_var(GVAR_RAINMAKERS_STATUS) == 2) then begin
      if(random(1, 30) == 1) then
         floater_high_rand(260, 267);
   end
   if(global_var(GVAR_RAINMAKERS_STATUS) == 3) then begin
      if(random(1, 30) == 1) then
         floater_bad_rand(290, 298);
   end else begin
      if(random(1, 30) == 1) then
         floater_bad_rand(200, 209);
   end

   if (
   (random(0, 5) == 1) and
   (not(combat_is_initialized)) and
   (self_can_see_dude or self_can_hear_dude)
   ) then begin
      reg_anim_clear(self_obj);
      reg_anim_begin();
      animate_move_obj_to_tile(
         self_obj,
         tile_num_in_direction(
            tile_num(self_obj),
            random(0, 5),
            random(1, 10)
         ),
         pick_one(ANIMATE_RUN, ANIMATE_WALK)
      );
      reg_anim_end();
   end

   add_timer_event(self_obj, game_ticks(random(3, 5)), 0);


end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

if(global_var(GVAR_QUEST_KILL_PATIENTS) != 20) then
   inc_global_var(GVAR_QUEST_KILL_PATIENTS);

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

procedure push_p_proc begin
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures






// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


// Node Not_Member
//
// Notes:
//
// Player has not yet joined the Rainmaker Cult.

procedure Not_Member
begin
floater_rand(200,209);
end

// Node Member
//
// Notes:
//
// Player is a member of the Rainmakers

procedure Member
begin
floater_rand(230,238);
end

// Node Prophet
//
// Notes:
//
// Stupid PC is the prophet of the Troposphere

procedure Prophet
begin
floater_rand(260,267);
end

// Node Thrown_Out
//
// Notes:
//
// Player has been thrown out of the temple for sinning

procedure Thrown_Out
begin
floater_rand(290,298);
end



//xxxxxxxxxxxxxxxxxxxx
