/*******************************************************************************
        Name:
        Location:
        Description: Object template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"

#define NAME                    SCRIPT_TBRETSCN

/* Standard Script Procedures */
procedure start;
procedure look_at_p_proc;
procedure use_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;

/* Defines */

#define LVAR_hacked              (1)

/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/

procedure start begin
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if(global_var(GVAR_KNOW_VEHICLE_DEPOT) == 1) then
   display_mstr(110);
   else
   display_mstr(150);
end

procedure description_p_proc begin
    script_overrides;
    display_mstr(200);
end

procedure use_p_proc begin
   script_overrides;
    if(global_var(GVAR_KNOW_VEHICLE_DEPOT) == 1) then
    floater_good(300);
    else
    floater_bad(302);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   if(local_var(LVAR_hacked) == 0) then begin
      if (
         (action_being_used == SKILL_SCIENCE) and
         is_success(roll_vs_skill(source_obj, SKILL_SCIENCE, -99))
      ) then begin
         script_overrides;
         set_global_var(GVAR_KNOW_VEHICLE_DEPOT, 1);
         set_local_var(LVAR_hacked, 1);
         give_xp(2000);
         display_mstr(202);
      end else if (
         (action_being_used == SKILL_REPAIR) and
         is_success(roll_vs_skill(source_obj, SKILL_REPAIR, -99))
      ) then begin
         script_overrides;
         set_global_var(GVAR_KNOW_VEHICLE_DEPOT, 1);
         set_local_var(LVAR_hacked, 1);
         give_xp(2000);
         display_mstr(203);
      end
   end
end
