/*

        Name:           Officer Robb
        Location:
        Description:

           Created: 04/10/2020 22:10:35

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBROBB

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure Skill_Check_003_Speech;
procedure Skill_Check_002_Speech;
procedure Skill_Check_000_Speech;
procedure Skill_Check_001_Speech;

procedure Haxor;
procedure Intimidation001_Male;
procedure SexProc;
procedure Intimidation001_female;



// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Robb_1a;
procedure Robb_1a_2G;
procedure Robb_1a_2N;
procedure Robb_1b;
procedure Robb_1b_2B;
procedure Robb_1c_1;
procedure Robb_1c_2a;
procedure Robb_1c_2b;
procedure Robb_1d_1;
procedure Robb_1d_2a_1;
procedure Robb_1d_2a_2;
procedure Robb_1d_2B;
procedure Robb_1d_2D;
procedure Robb_2_1;
procedure Robb_2_1D_1;
procedure Robb_2_1D_2;
procedure Robb_2_1D_3;
procedure Robb_2_1D_4a;
procedure Robb_2_1D_4b;
procedure Robb_2_2a_1;
procedure Robb_2_2a_2a_1;
procedure Robb_2_2a_2a_2B;
procedure Robb_2_2a_2a_2G;
procedure Robb_2_2a_2a_3;
procedure Robb_2_2a_2B;
procedure Robb_2_2b_1;
procedure Robb_2_2b_2a_1;
procedure Robb_2_2b_2a_2;
procedure Robb_2_2b_2b;
procedure Robb_3_1;
procedure Robb_3_2_1;
procedure Robb_3_2_2a;
procedure Robb_3_2_2b_1;
procedure Robb_3_2_2b_2a_1;
procedure Robb_3_2_2b_2a_2;
procedure Robb_3_2_2b_2b_1;
procedure Robb_3_2_2b_2b_2;
procedure Robb_3_2_2b_2F_1;
procedure Robb_3_2_2b_2F_2a;
procedure Robb_3_2_2b_2F_2b;
procedure Robb_3_2_2c;
procedure Robb_4_1;
procedure Robb_4_2a_1;
procedure Robb_4_2a_2a_1;
procedure Robb_4_2a_2a_2a;
procedure Robb_4_2a_2a_2b;
procedure Robb_4_2a_2b_1;
procedure Robb_4_2a_2b_2;
procedure Robb_4_2a_2c;
procedure Robb_4_2a_2d_1;
procedure Robb_4_2a_2d_2a;
procedure Robb_4_2a_2d_2b;
procedure Robb_4_2a_2d_2c;
procedure Robb_4_2a_2d_2d;
procedure Robb_4_2a_2d_2e_1;
procedure Robb_4_2a_2d_2e_2;
procedure Robb_4_2a_2d_2f;
procedure Robb_4_2b_1;
procedure Robb_4_2b_2;
procedure Robb_4_2b_3;
procedure Robb_4_2c;
procedure Robb_4_9;
procedure Robb_5_1;
procedure Robb_5_2a_1;
procedure Robb_5_2a_2a_1;
procedure Robb_5_2a_2a_2;
procedure Robb_5_2a_2a_3;
procedure Robb_5_2a_2b;
procedure Robb_5_2a_2c_1;
procedure Robb_5_2a_2c_2;
procedure Robb_5_2a_2c_3;
procedure Robb_5_2a_2c_4;
procedure Robb_5_2b_1;
procedure Robb_5_2b_2;
procedure Robb_5_2c;
procedure Robb_5_2d_1;
procedure Robb_5_2d_2;
procedure Robb_5_2d_3;
procedure Robb_5_2d_4a;
procedure Robb_5_2d_4b;
procedure Robb_5_2e_1;
procedure Robb_5_2e_2;
procedure Robb_5_2f_1;
procedure Robb_5_2f_2;
procedure Robb_5_2f_3;
procedure Robb_9a;
procedure Robb_9b;
procedure Robb_B_1;
procedure Robb_B_2;
procedure Node091;
procedure Robb_4_2b_3_b;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Accused (8)
#define LVAR_Robb_Angela_Bag (9)
#define LVAR_Robb_Angela_Prisoner (10)
#define LVAR_Robb_Angela_Death (11)
#define LVAR_Robb_Angela_Rain (12)
#define LVAR_Robb_Angela_Shy (13)
#define LVAR_Robb_Grace_Sympathy (14)
#define LVAR_Robb_Temper (15)


/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
   add_timer_event(self_obj,game_ticks(random(1,5)),0);
   call new_plague_check(self_obj, LVAR_Herebefore);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,HEAD_ROBB,BACKGROUND_TIBBETS);
       gSay_Start;

      if(global_var(GVAR_ANGELA_DEAD) == 1) then
         call Robb_1d_1;
      else if (local_var(LVAR_Herebefore) == 1) then begin
         if(local_var(LVAR_Robb_Temper) <= -5) then
            call Robb_1c_1;
         else if (dude_is_stupid) then
            call Robb_1b_2B;
         else
            call Robb_1b;
      end else
         call Robb_1a;
       gSay_End;
       end_dialogue;


   call restore_idiot_savant_int;

end


procedure timed_event_p_proc begin

   add_timer_event(self_obj,game_ticks(random(3, 5)),0);

    if (random(0, 30) == 1) then begin
       if(global_var(GVAR_ANGELA_DEAD) == 1) then
          floater_sad_rand(290, 293);
       else if(global_var(GVAR_ANGELA_ROBOSLUT) == 1) then
          floater_sad_rand(230, 233);
       else if(global_var(GVAR_TIPOFF_ROBB) == 2) then
          floater_sad_rand(320, 325);
      else if(local_var(LVAR_Robb_Temper) <= -5) then
         floater_bad_rand(260, 263);
      else if(global_var(GVAR_ANGELA_ROBOSLUT) == 2) then
          floater_sad_rand(350, 355);
       else
         floater_rand(200,206);
   end


end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/

inc_evil_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end

if(global_var(GVAR_EUGENE_ROBB) == 1) and (global_var(GVAR_ANGELA_LATE) == 2) and (local_var(LVAR_Accused) == 1) then
set_global_var(GVAR_TIPOFF_ROBB, 1);

end

// Skill checks and miscellaneous procedures

procedure Skill_Check_003_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, 0);
if is_success(roll_temp) then
begin
call Robb_1c_2a;
end
else begin
call Robb_1c_2b;
 end
end

procedure Skill_Check_002_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -25);
if is_success(roll_temp) then
begin
call Robb_4_2a_2b_1;
end
else begin
call Robb_4_2a_2c;
 end
end

procedure Skill_Check_000_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -20);
if is_success(roll_temp) then
begin
call Robb_4_2a_2a_2a;
end
else begin
call Robb_4_2a_2a_2b;
 end
end

procedure Skill_Check_001_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -30);
if is_success(roll_temp) then
begin
call Robb_4_2a_2a_2a;
end
else begin
call Robb_4_2a_2a_2b;
 end
end


// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Robb_1a
begin
Reply(410);
GOption(mstr(411)+dude_name+mstr(412),Robb_1a_2G,4);
NOption(413,Robb_1a_2N,4);
BOption(414,Robb_B_1,4);
NOption(413,Robb_1a_2N,-3);
end

procedure Robb_1a_2G
begin
   inc_local_var_amt(LVAR_Robb_Temper, 1);
Reply(440);
NOption(441,Robb_2_1,4);
NOption(442,Node999,4);
NOption(443,Robb_2_1D_1,-3);
NOption(444,Node999,-3);
end

procedure Robb_1a_2N
begin
Reply(470);
GOption(mstr(411)+dude_name+mstr(412),Robb_1a_2G,4);
BOption(414,Robb_B_1,4);
NOption(mstr(471)+dude_name+mstr(412),Robb_1a_2G,-3);
end

procedure Robb_1b
begin
Reply(mstr(500)+dude_name+mstr(501));
NOption(502,Robb_4_1,4);
NOption(503,Robb_2_1,4);
BOption(414,Robb_1b_2B,4);
NOption(504,Node999,4);
end

procedure Robb_1b_2B
begin
Reply(530);
BOption(531,Robb_B_1,4);
NOption(532,Node999,4);
NOption(533,Robb_2_1D_2,-3);
NOption(444,Node999,4);
end

procedure Robb_1c_1
begin
Reply(560);
NOption(561,Skill_Check_003_Speech,4);
BOption(414,Robb_1b_2B,4);
NOption(504,Node999,4);
end

procedure Robb_1c_2a
begin
      inc_local_var_amt(LVAR_Robb_Temper, 1);
Reply(590);
NOption(502,Robb_4_1,4);
NOption(503,Robb_2_1,4);
BOption(414,Robb_1b_2B,4);
NOption(591,Node999,4);
end

procedure Robb_1c_2b
begin
Reply(620);
BOption(414,Robb_1b_2B,4);
NOption(444,Node999,4);
end

procedure Robb_1d_1
begin
Reply(650);
if (local_var(LVAR_Robb_Angela_Death)==0) then
NOption(651,Robb_1d_2a_1,4);
if (local_var(LVAR_Robb_Angela_Death)>0) then
NOption(652,Robb_5_1,4);
BOption(653,Robb_1d_2B,4);
NOption(654,Node999,4);
NOption(655,Robb_1d_2D,-3);
NOption(444,Node999,-3);
end

procedure Robb_1d_2a_1
begin
   set_local_var(LVAR_Robb_Angela_Death, 1);
Reply(680);
NOption(681,Robb_1d_2a_2,4);
NOption(652,Robb_5_1,4);
NOption(682,Node999,4);
end

procedure Robb_1d_2a_2
begin
Reply(710);
NOption(652,Robb_5_1,4);
NOption(682,Node999,4);
end

procedure Robb_1d_2B
begin
      dec_local_var_amt(LVAR_Robb_Temper, 1);

Reply(740);
BOption(741,Node998,4);
NOption(444,Node999,4);
end

procedure Robb_1d_2D
begin
Reply(770);
NOption(444,Node999,-3);
end

procedure Robb_2_1
begin
Reply(800);
NOption(801,Robb_2_2a_1,4);
NOption(802,Robb_2_2b_1,4);
NOption(803,Node999,4);
end

procedure Robb_2_1D_1
begin
Reply(830);
NOption(831,Robb_2_1D_2,-3);
NOption(444,Node999,-3);
end

procedure Robb_2_1D_2
begin
Reply(860);
NOption(861,Robb_2_1D_3,-3);
end

procedure Robb_2_1D_3
begin
Reply(890);
NOption(891,Robb_2_1D_4a,4);
NOption(892,Robb_2_1D_4b,4);
end

procedure Robb_2_1D_4a
begin
Reply(920);
NOption(921,Node999,-3);
NOption(444,Node999,-3);
end

procedure Robb_2_1D_4b
begin
Reply(950);
NOption(951,Node999,-3);
end

procedure Robb_2_2a_1
begin
Reply(980);
NOption(981,Robb_2_2a_2a_1,4);
BOption(982,Robb_2_2a_2B,4);
NOption(803,Node999,4);
end

procedure Robb_2_2a_2a_1
begin
Reply(1010);
if (local_var(LVAR_Robb_Grace_Sympathy)==0) then
GOption(1011,Robb_2_2a_2a_2G,4);
NOption(1012,Robb_2_2a_2a_3,4);
BOption(1013,Robb_2_2a_2a_2B,4);
NOption(1014,Robb_3_1,4);
NOption(803,Node999,4);
end

procedure Robb_2_2a_2a_2B
begin
      dec_local_var_amt(LVAR_Robb_Temper, 1);

Reply(1040);
NOption(1014,Robb_3_1,4);
NOption(1012,Robb_2_2a_2a_3,4);
NOption(803,Node999,4);
end

procedure Robb_2_2a_2a_2G
begin
      inc_local_var_amt(LVAR_Robb_Grace_Sympathy, 1);

Reply(1070);
NOption(1012,Robb_2_2a_2a_3,4);
NOption(803,Node999,4);
end

procedure Robb_2_2a_2a_3
begin
Reply(1100);
NOption(1014,Robb_3_1,4);
NOption(803,Node999,4);
end

procedure Robb_2_2a_2B
begin
      dec_local_var_amt(LVAR_Robb_Temper, 1);

Reply(1130);
NOption(1131,Robb_2_2a_2a_1,4);
NOption(981,Robb_2_2a_2a_1,4);
NOption(803,Node999,4);
end

procedure Robb_2_2b_1
begin
Reply(1160);
NOption(1161,Robb_2_2b_2a_1,4);
NOption(1162,Robb_2_2b_2b,4);
NOption(1163,Robb_9a,4);
NOption(803,Node999,4);
end

procedure Robb_2_2b_2a_1
begin
Reply(1190);
NOption(1191,Robb_2_2b_2a_2,4);
NOption(1192,Robb_2_2b_2a_2,4);
NOption(1163,Robb_9a,4);
NOption(803,Node999,4);
end

procedure Robb_2_2b_2a_2
begin
Reply(1220);
NOption(1163,Robb_9a,4);
NOption(803,Node999,4);
end

procedure Robb_2_2b_2b
begin
Reply(1250);
NOption(1161,Robb_2_2b_2a_1,4);
NOption(1163,Robb_9a,4);
NOption(803,Node999,4);
end

procedure Robb_3_1
begin
Reply(1280);
NOption(1281,Robb_3_2_1,4);
NOption(1282,Robb_9a,4);
NOption(803,Node999,4);
end

procedure Robb_3_2_1
begin
Reply(1310);
NOption(1311,Robb_3_2_2a,4);
NOption(1312,Robb_3_2_2b_1,4);
NOption(1282,Robb_9a,4);
NOption(803,Node999,4);
end

procedure Robb_3_2_2a
begin
if (dude_is_male) then Reply(1340); else
if (dude_is_female) then Reply(1341);
NOption(1342,Robb_3_2_2c,4);
NOption(1312,Robb_3_2_2b_1,4);
NOption(1282,Robb_9a,4);
NOption(803,Node999,4);
end

procedure Robb_3_2_2b_1
begin
Reply(1370);
if (dude_is_female) then
NOption(1371,Robb_3_2_2b_2F_1,4);
if (get_critter_stat(dude_obj,STAT_ch)>=6) and (dude_is_male) then
NOption(1372,Robb_3_2_2b_2a_1,4);
if (get_critter_stat(dude_obj,STAT_ch)<=5) and (dude_is_male) then
NOption(1372,Robb_3_2_2b_2b_1,4);
NOption(1282,Robb_9a,4);
NOption(1373,Node091,4);
NOption(803,Node999,4);
end

procedure Robb_3_2_2b_2a_1
begin
Reply(1400);
NOption(1401,Robb_3_2_2b_2a_2,4);
NOption(1282,Robb_9a,4);
NOption(803,Node999,4);
end

procedure Robb_3_2_2b_2a_2
begin
Reply(1430);
NOption(1342,Robb_3_2_2c,4);
NOption(1282,Robb_9a,4);
NOption(803,Node999,4);
end

procedure Robb_3_2_2b_2b_1
begin
Reply(1460);
NOption(1461,Robb_3_2_2b_2b_2,4);
NOption(1282,Robb_9a,4);
NOption(803,Node999,4);
end

procedure Robb_3_2_2b_2b_2
begin
Reply(1490);
NOption(1342,Robb_3_2_2c,4);
BOption(1491,Robb_B_1,4);
NOption(1282,Robb_9a,4);
NOption(1492,Node999,4);
end

procedure Robb_3_2_2b_2F_1
begin
Reply(1520);
GOption(1521,Robb_3_2_2b_2F_2a,4);
NOption(1522,Robb_3_2_2b_2F_2b,4);
NOption(1282,Robb_9a,4);
NOption(803,Node999,4);
end


procedure Robb_3_2_2b_2F_2a
begin

   inc_local_var_amt(LVAR_Robb_Temper, 1);
   set_global_var(GVAR_ANGELA_TIPS, 1);
   inc_general_rep(1);
   inc_tibbets_rep(3);

Reply(1550);
NOption(1342,Robb_3_2_2c,4);
NOption(1282,Robb_9a,4);
NOption(803,Node999,4);
end

procedure Robb_3_2_2b_2F_2b
begin
Reply(1580);
NOption(1282,Robb_9a,4);
NOption(803,Node999,4);
end

procedure Robb_3_2_2c
begin
Reply(1610);
NOption(1611,Robb_3_2_2b_1,4);
NOption(1282,Robb_9a,4);
NOption(803,Node999,4);
end


procedure Robb_4_1
begin
Reply(1640);
if(global_var(GVAR_ANGELA_ROBOSLUT) == 1) then
BOption(1641,Robb_4_2b_1,4);
NOption(1642,Robb_4_2a_1,4);
if (dude_is_male) then
NOption(1643,Robb_4_2c,4);
end

procedure Robb_4_2a_1
begin
Reply(1670);
if (local_var(LVAR_Robb_Angela_Shy)==0) then
NOption(1671,Robb_4_2a_2a_1,4);
if (local_var(LVAR_Robb_Angela_Rain)==0) then
NOption(1672,Skill_Check_002_Speech,4);
if (local_var(LVAR_Robb_Angela_Prisoner)==0) then
NOption(1673,Robb_4_2a_2d_1,4);
BOption(1641,Robb_4_2b_1,4);
if (dude_is_male) then
NOption(1643,Robb_4_2c,4);
NOption(1674,Robb_4_9,4);
NOption(1163,Robb_4_9,4);
end

procedure Robb_4_2a_2a_1
begin
Reply(1700);
NOption(1701,Skill_Check_001_Speech,4);
NOption(1702,Skill_Check_000_Speech,4);
if(global_var(GVAR_ANGELA_ROBOSLUT) == 1) then
BOption(1703,Robb_4_2b_1,4);
if (dude_is_male) then
NOption(1704,Robb_4_2c,4);
end

procedure Robb_4_2a_2a_2a
begin
Reply(1730);
NOption(1282,Robb_9a,4);
NOption(1731,Node999,4);
end

procedure Robb_4_2a_2a_2b
begin

   inc_local_var_amt(LVAR_Robb_Angela_Shy, 1);

Reply(1760);
if (local_var(LVAR_Robb_Angela_Rain)==0) then
NOption(1672,Robb_4_2a_2b_1,4);
if (local_var(LVAR_Robb_Angela_Prisoner)==0) then
NOption(1673,Robb_4_2a_2d_1,4);
BOption(1641,Robb_4_2b_1,4);
NOption(1163,Robb_4_9,4);
NOption(1761,Robb_4_9,4);
end

procedure Robb_4_2a_2b_1
begin
Reply(1790);
GOption(1791,Robb_4_2a_2b_2,4);
NOption(1792,Robb_4_2a_2b_2,4);
end

procedure Robb_4_2a_2b_2
begin
Reply(1820);
NOption(1163,Robb_9a,4);
NOption(1761,Node999,4);
end


procedure Robb_4_2a_2c
begin

   inc_local_var_amt(LVAR_Robb_Angela_Rain, 1);

Reply(1850);
if (local_var(LVAR_Robb_Angela_Shy)==0) then
NOption(1671,Robb_4_2a_2a_1,4);
if (local_var(LVAR_Robb_Angela_Prisoner)==0) then
NOption(1673,Robb_4_2a_2d_1,4);
BOption(1641,Robb_4_2b_1,4);
if (dude_is_male) then
NOption(1643,Robb_4_2c,4);
NOption(1282,Robb_4_9,4);
NOption(1761,Robb_4_9,4);
end

procedure Robb_4_2a_2d_1
begin
Reply(1880);
if(not(has_fake_trait(TRAIT_big_liar)) and global_var(GVAR_ANGELA_ROBOSLUT) == 1) then
BOption(1881,Robb_4_2b_1,4);
if(global_var(GVAR_KNOW_CROZ) == 1) then
NOption(1882,Robb_4_2a_2d_2a,4);
if(global_var(GVAR_KNOW_MAGIK) == 1) then
NOption(1883,Robb_4_2a_2d_2b,4);
if(global_var(GVAR_KNOW_ALDO) == 1) then
NOption(1884,Robb_4_2a_2d_2c,4);
if(not(has_fake_trait(TRAIT_soothsayer))) then begin
   NOption(1885,Robb_4_2a_2d_2d,4);
   if (get_critter_stat(dude_obj,STAT_ch)<=5) and (dude_is_male) then
   NOption(1886,Robb_4_2a_2d_2e_1,4);
   if (get_critter_stat(dude_obj,STAT_ch)>=6) and (dude_is_male) then
   NOption(1886,Robb_4_2a_2d_2f,4);
   if (dude_is_male) then
   NOption(1886,Robb_4_2c,4);
end
end

procedure Robb_4_2a_2d_2a
begin

inc_local_var_amt(LVAR_Robb_Angela_Prisoner, 1);

Reply(1910);
if (local_var(LVAR_Robb_Angela_Shy)==0) then
NOption(1671,Robb_4_2a_2a_1,4);
if (local_var(LVAR_Robb_Angela_Rain)==0) then
NOption(1672,Skill_Check_002_Speech,4);
BOption(1641,Robb_4_2b_1,4);
if (dude_is_female) then
NOption(1911,Robb_4_2c,4);
NOption(1282,Robb_4_9,4);
NOption(1761,Robb_4_9,4);
end

procedure Robb_4_2a_2d_2b
begin

inc_local_var_amt(LVAR_Robb_Angela_Prisoner, 1);

Reply(1940);
if (local_var(LVAR_Robb_Angela_Shy)==0) then
NOption(1671,Robb_4_2a_2a_1,4);
if (local_var(LVAR_Robb_Angela_Rain)==0) then
NOption(1672,Skill_Check_002_Speech,4);
BOption(1641,Robb_4_2b_1,4);
if (dude_is_female) then
NOption(1911,Robb_4_2c,4);
NOption(1282,Robb_4_9,4);
NOption(1761,Robb_4_9,4);
end

procedure Robb_4_2a_2d_2c
begin

inc_local_var_amt(LVAR_Robb_Angela_Prisoner, 1);


Reply(1970);
if (local_var(LVAR_Robb_Angela_Shy)==0) then
NOption(1671,Robb_4_2a_2a_1,4);
if (local_var(LVAR_Robb_Angela_Rain)==0) then
NOption(1672,Skill_Check_002_Speech,4);
BOption(1641,Robb_4_2b_1,4);
if (dude_is_female) then
NOption(1911,Robb_4_2c,4);
NOption(1282,Robb_4_9,4);
NOption(1761,Robb_4_9,4);
end

procedure Robb_4_2a_2d_2d
begin

inc_local_var_amt(LVAR_Robb_Angela_Prisoner, 1);


Reply(2000);
if (local_var(LVAR_Robb_Angela_Shy)==0) then
NOption(1671,Robb_4_2a_2a_1,4);
if (local_var(LVAR_Robb_Angela_Rain)==0) then
NOption(1672,Skill_Check_002_Speech,4);
BOption(1641,Robb_4_2b_1,4);
if (dude_is_female) then
NOption(1911,Robb_4_2c,4);
NOption(1282,Robb_4_9,4);
NOption(1761,Robb_4_9,4);
end


procedure Robb_4_2a_2d_2e_1
begin

inc_local_var_amt(LVAR_Robb_Angela_Prisoner, 1);

Reply(2030);
NOption(2031,Robb_4_2a_2d_2e_2,4);
if (local_var(LVAR_Robb_Angela_Shy)==0) then
NOption(1671,Robb_4_2a_2a_1,4);
if (local_var(LVAR_Robb_Angela_Rain)==0) then
NOption(1672,Skill_Check_002_Speech,4);
BOption(1641,Robb_4_2b_1,4);
NOption(1282,Robb_4_9,4);
NOption(1761,Robb_4_9,4);
end

procedure Robb_4_2a_2d_2e_2
begin

dec_local_var_amt(LVAR_Robb_Temper, 1);

Reply(2060);
BOption(2061,Robb_B_2,4);
if (local_var(LVAR_Robb_Angela_Shy)==0) then
NOption(1671,Robb_4_2a_2a_1,4);
if (local_var(LVAR_Robb_Angela_Rain)==0) then
NOption(1672,Skill_Check_002_Speech,4);
BOption(1641,Robb_4_2b_1,4);
NOption(1282,Robb_4_9,4);
NOption(1761,Robb_4_9,4);
end

procedure Robb_4_2a_2d_2f
begin

inc_local_var_amt(LVAR_Robb_Angela_Prisoner, 1);

Reply(2090);
if (local_var(LVAR_Robb_Angela_Shy)==0) then
NOption(1671,Robb_4_2a_2a_1,4);
if (local_var(LVAR_Robb_Angela_Rain)==0) then
NOption(1672,Skill_Check_002_Speech,4);
BOption(1641,Robb_4_2b_1,4);
NOption(1282,Robb_4_9,4);
NOption(1761,Robb_4_9,4);
end

procedure Robb_4_2b_1
begin

dec_local_var_amt(LVAR_Robb_Temper, 1);

Reply(2120);
BOption(2121,Robb_4_2b_2,4);
end

procedure Robb_4_2b_2
begin

dec_local_var_amt(LVAR_Robb_Temper, 1);

if (dude_is_male) then Reply(2150); else
if (dude_is_female) then Reply(2151);
BOption(2152,Robb_4_2b_3,4);
NOption(2153,Robb_4_2b_3,4);
end

procedure Robb_4_2b_3
begin

dec_local_var_amt(LVAR_Robb_Temper, 1);


Reply(2180);
NOption(2181,Node999,4);
BOption(2182,Node998,4);
end

procedure Robb_4_2c
begin
Reply(2210);
if(global_var(GVAR_ANGELA_ROBOSLUT) > 0) then begin
   BOption(2211,Robb_4_2b_1,4);
   NOption(2212,Robb_4_2b_1,4);
end
BOption(2213,Robb_4_2b_3_b,4);
end

procedure Robb_4_2b_3_b begin
   set_global_var(GVAR_ANGELA_ROBOSLUT, 2);
   call Robb_4_2b_3;
end

procedure Robb_4_9
begin
Reply(2240);
if (local_var(LVAR_Robb_Angela_Shy)==0) then
NOption(1671,Robb_4_2a_2a_1,4);
if (local_var(LVAR_Robb_Angela_Rain)==0) then
NOption(1672,Skill_Check_002_Speech,4);
if (local_var(LVAR_Robb_Angela_Prisoner)==0) then
NOption(1673,Robb_4_2a_2d_1,4);
BOption(1641,Robb_4_2b_1,4);
end

procedure Robb_5_1
begin
Reply(2270);
if(global_var(GVAR_ANGELA_LATE) > 1) then
NOption(2271,Robb_5_2a_1,4);
if (dude_item_count(PID_LAVANDER_FLOWER)>0) and (local_var(LVAR_Robb_Angela_Bag)==0) then
NOption(2272,Robb_5_2b_1,4);
if (dude_item_count(PID_LAVANDER_FLOWER)>0) and (local_var(LVAR_Robb_Angela_Bag)>0) then
NOption(2272,Robb_5_2c,4);
if(global_var(GVAR_EUGENE_ROBB) == 1) then
NOption(2273,Robb_5_2d_1,4);
NOption(2274,Robb_5_2e_1,4);
NOption(2275,Robb_5_2f_1,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2a_1
begin
Reply(2300);
NOption(2301,Robb_5_2a_2b,4);
NOption(2302,Robb_5_2a_2a_1,4);
NOption(2303,Robb_5_1,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2a_2a_1
begin
Reply(2330);
NOption(2331,Robb_5_2a_2a_2,4);
BOption(2332,Robb_5_2a_2c_1,4);
NOption(2303,Robb_5_1,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2a_2a_2
begin
Reply(2360);
NOption(2361,Robb_5_2a_2a_3,4);
BOption(2332,Robb_5_2a_2c_1,4);
NOption(2303,Robb_5_1,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2a_2a_3
begin
Reply(2390);
BOption(2391,Robb_5_2a_2c_1,4);
NOption(2303,Robb_5_1,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2a_2b
begin
Reply(2420);
BOption(2332,Robb_5_2a_2c_1,4);
NOption(2303,Robb_5_1,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2a_2c_1
begin

dec_local_var_amt(LVAR_Robb_Temper, 1);

Reply(2450);
BOption(2451,Robb_5_2a_2c_2,4);
NOption(2303,Robb_5_1,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2a_2c_2
begin

dec_local_var_amt(LVAR_Robb_Temper, 1);

Reply(2480);
BOption(2481,Robb_5_2a_2c_3,4);
NOption(2303,Robb_5_2a_2c_4,4);
NOption(1163,Robb_5_2a_2c_4,4);
NOption(682,Node999,4);
end

procedure Robb_5_2a_2c_3
begin

dec_local_var_amt(LVAR_Robb_Temper, 1);

if (dude_is_male) then Reply(2510); else
if (dude_is_female) then Reply(2511);
NOption(2303,Robb_5_2a_2c_4,4);
NOption(1163,Robb_5_2a_2c_4,4);
NOption(2512,Node999,4);
end

procedure Robb_5_2a_2c_4
begin
Reply(2540);
NOption(444,Node999,4);
end

procedure Robb_5_2b_1
begin

inc_local_var_amt(LVAR_Robb_Angela_Bag, 1);

Reply(2570);
NOption(2571,Robb_5_2b_2,4);
NOption(2274,Robb_5_2e_1,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2b_2
begin
Reply(2600);
NOption(2274,Robb_5_2e_1,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2c
begin

inc_local_var_amt(LVAR_Robb_Angela_Bag, 1);

Reply(2630);
NOption(2571,Robb_5_2b_2,4);
NOption(2274,Robb_5_2e_1,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2d_1
begin
Reply(2660);
if (get_critter_stat(dude_obj,STAT_pe)>=6) then
NOption(2661,Robb_5_2d_2,4);
if (get_critter_stat(dude_obj,STAT_pe)<=5) then
NOption(2661,Robb_5_2d_3,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2d_2
begin
Reply(2690);
NOption(861,Robb_5_2d_3,4);
end

procedure Robb_5_2d_3
begin
Reply(2720);
NOption(2721,Robb_5_2d_4a,4);
if (get_critter_stat(dude_obj,STAT_pe)>=6) then
NOption(2722,Robb_5_2d_4b,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2d_4a
begin
Reply(2750);
if (get_critter_stat(dude_obj,STAT_pe)>=6) then
NOption(2751,Robb_5_2d_4b,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2d_4b
begin
Reply(2780);
NOption(2781,Robb_5_2d_4a,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2e_1
begin
Reply(2810);
if(global_var(GVAR_ANGELA_LATE) == 2) then
NOption(2811,Robb_5_2e_2,4);
if(global_var(GVAR_ANGELA_LATE) > 1) then
NOption(2271,Robb_5_2a_1,4);
if (dude_item_count(PID_LAVANDER_FLOWER)>0) and (local_var(LVAR_Robb_Angela_Bag)==0) then
NOption(2812,Robb_5_2b_1,4);
if (dude_item_count(PID_LAVANDER_FLOWER)>0) and (local_var(LVAR_Robb_Angela_Bag)>0) then
NOption(2812,Robb_5_2c,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2e_2
begin
Reply(2840);
NOption(2275,Robb_5_2f_1,4);
if(global_var(GVAR_ANGELA_LATE) > 1) then
NOption(2271,Robb_5_2a_1,4);
if (dude_item_count(PID_LAVANDER_FLOWER)>0) and (local_var(LVAR_Robb_Angela_Bag)==0) then
NOption(2812,Robb_5_2b_1,4);
if (dude_item_count(PID_LAVANDER_FLOWER)>0) and (local_var(LVAR_Robb_Angela_Bag)>0) then
NOption(2812,Robb_5_2c,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2f_1
begin
Reply(2870);
NOption(2871,Robb_5_2f_2,4);
NOption(2872,Robb_9b,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_5_2f_2
begin

dec_local_var_amt(LVAR_Robb_Temper, 1);
set_local_var(LVAR_Accused, 1);
Reply(2900);
NOption(861,Robb_5_2f_3,4);
end

procedure Robb_5_2f_3
begin
Reply(2930);
BOption(2931,Robb_5_2a_2c_2,4);
NOption(2932,Robb_5_1,4);
NOption(1163,Robb_9b,4);
NOption(682,Node999,4);
end

procedure Robb_9a
begin
Reply(2960);
NOption(2961,Robb_2_1,4);
NOption(2962,Node999,4);
end

procedure Robb_9b
begin
Reply(2990);
NOption(2991,Robb_5_1,4);
NOption(444,Node999,4);
end

procedure Robb_B_1
begin
      dec_local_var_amt(LVAR_Robb_Temper, 1);

if (dude_is_male) then Reply(3020); else
if (dude_is_female) then Reply(3021);
BOption(3022,Robb_B_2,4);
NOption(444,Node999,4);
end

procedure Robb_B_2
begin
Reply(3050);
BOption(3051,Node998,4);
end

procedure Node091
begin
Reply(3080);
NOption(3081,Node999,4);
end



//xxxxxxxxxxxxxxxxxxxx
