/*

        Name:           Roberta
        Location:
        Description:

           Created: 07/10/2020 14:59:27

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBROBRTA

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Initial;
procedure no_jobs_1;
procedure no_jobs_2;
procedure no_jobs_3;
procedure no_jobs_4;
procedure no_jobs_5;
procedure no_jobs_6;
procedure no_jobs_7;
procedure no_jobs_8;
procedure no_jobs_9;
procedure no_jobs_10;
procedure no_jobs_11;
procedure TakeStuffAndRun;
procedure GiveCap;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Run_Away_With_Stuff        (8)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
call new_plague_check(self_obj, LVAR_Herebefore);


   if (local_var(LVAR_Run_Away_With_Stuff) == 1) then begin
      destroy_object(self_obj);
   end
end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=1;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;
       call Initial;
       gSay_End;
       end_dialogue;


   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_evil_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Initial
begin
Reply(200);
NOption(201,no_jobs_1,4);
NOption(202,Node999,4);
if(dude_caps > 0) then begin
   NOption(203,Node999,-3);
end
NOption(204,Node999,-3);
end

procedure no_jobs_1
begin
Reply(230);
NOption(231,no_jobs_2,4);
NOption(232,Node999,4);
end

procedure no_jobs_2
begin
Reply(260);
NOption(261,no_jobs_3,4);
NOption(262,Node999,4);
end

procedure no_jobs_3
begin
Reply(290);
NOption(291,no_jobs_4,4);
NOption(292,Node999,4);
NOption(293,no_jobs_8,4);
NOption(294,Node999,4);
BOption(295,Node998,4);
end

procedure no_jobs_4
begin
Reply(320);
NOption(321,no_jobs_5,4);
NOption(322,Node999,4);
end

procedure no_jobs_5
begin
Reply(350);
NOption(351,no_jobs_6,4);
NOption(352,Node999,4);
end

procedure no_jobs_6
begin
Reply(380);
NOption(381,no_jobs_7,4);
NOption(382,no_jobs_8,4);
BOption(383,Node998,4);
end

procedure no_jobs_7
begin
Reply(410);
NOption(411,no_jobs_9,4);
// NOTE: This option should only be visible if the PC has already been told of the tents.
NOption(412,no_jobs_10,4);
end

procedure no_jobs_8
begin
Reply(440);
BOption(441,Node998,4);
NOption(442,Node999,4);
end

procedure no_jobs_9
begin
Reply(470);
NOption(471,no_jobs_10,4);
NOption(472,Node999,4);
end

procedure no_jobs_10
begin
Reply(500);
NOption(501,no_jobs_11,4);
NOption(472,Node999,4);
end

procedure no_jobs_11
begin
Reply(530);
NOption(531,TakeStuffAndRun,4);
if (get_critter_stat(dude_obj,STAT_pe)>=8) or (has_fake_trait(TRAIT_detect_lie)) then begin
   NOption(532,no_jobs_8,4);
end
end

procedure TakeStuffAndRun begin
   fadeout(600); //Added fadeout
   set_obj_visibility(self_obj, 1);
   fadein(600);
   set_local_var(LVAR_Run_Away_With_Stuff, 1);
   move_obj_inven_to_obj(dude_obj, self_obj);
   display_mstr(150); //Added new display msg for her running away
   if (dude_perception >=7) or (dude_iq >= 7) then begin
      display_mstr(151); //Addendum msg for smart players realizing their mistake
   end
   call Node999;
end

procedure GiveCap begin
   item_caps_adjust(dude_obj, -1);
   inc_general_rep(1);
   inc_tibbets_rep(1);
end


//xxxxxxxxxxxxxxxxxxxx
