/*******************************************************************************
        Name:
        Location:
        Description: Object template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"

#define NAME                    SCRIPT_TBROPE3
#define MVAR_RopeAttached                     (0)

/* Standard Script Procedures */
procedure start;
procedure description_p_proc;
procedure look_at_p_proc;
procedure use_p_proc;
procedure timed_event_p_proc;
procedure use_obj_on_p_proc;

/* Defines */


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/

procedure look_at_p_proc begin

end

procedure description_p_proc begin

end

procedure start begin
   if (script_action == use_proc) then begin
		call use_p_proc;
	end else if (script_action == use_obj_on_proc) then begin
        call use_obj_on_p_proc;
    end
end


procedure use_p_proc begin

    if(dude_is_stupid) then begin
        floater_bad(101);
    end else begin
        floater_bad(100);
    end
end


procedure map_enter_p_proc begin
   add_timer_event(self_obj, 1, 1);
end



procedure timed_event_p_proc begin
  if (fixed_param == 1) then begin

         if(map_var(MVAR_RopeAttached) == 1) then begin
            set_obj_visibility(self_obj, 1);
            return;
         end

      add_timer_event(self_obj, 1, 1);
  end
end

procedure use_obj_on_p_proc begin
   variable tool := obj_pid(obj_being_used_with);

   if (
   tool == PID_ROPE) then begin
       script_overrides;
           fadeout(1);
               set_map_var(MVAR_RopeAttached, 1);
remove_pid_qty(dude_obj, PID_ROPE, 1)
    game_time_advance(ONE_GAME_MINUTE * 10);
    fadein(1);
   end
end
