/*******************************************************************************
        Name:
        Location:
        Description: Object template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"

#define NAME                    SCRIPT_TBROPE4
#define MVAR_RopeAttached                     (0)

/* Standard Script Procedures */
procedure start;
procedure description_p_proc;
procedure look_at_p_proc;
procedure timed_event_p_proc;

/* Defines */


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/

procedure look_at_p_proc begin

end

procedure description_p_proc begin

end

procedure start begin
   add_timer_event(self_obj, 1, 1);

end

procedure timed_event_p_proc begin
  if (fixed_param == 1) then begin

         if(map_var(MVAR_RopeAttached) == 1) then begin
            set_obj_visibility(self_obj, 0);
         end else
            set_obj_visibility(self_obj, 1);
  end

      add_timer_event(self_obj, 1, 1);
  end
