/*

        Name:           Tall-Sally
        Location:
        Description:

           Created: 05/10/2020 20:00:58

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBSALLY

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure badmouth1;
procedure badmouth2;
procedure Skill_Check_004_Speech;
procedure haggle1;
procedure haggle2;




// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure SoldMagik;
procedure IkeDead;
procedure PhilDead;
procedure FloatAllDead;
procedure Company;
procedure Switcher;
procedure First;
procedure Subsequent;
procedure FamilyDead;
procedure WhatDo;
procedure Business;
procedure Family;
procedure Family2;
procedure Phil;
procedure Ike;
procedure Pete;
procedure Pete2;
procedure Pete3;
procedure Pete4;
procedure Fulfilling;
procedure MeetJoe;
procedure Magik;
procedure MagikDead;
procedure MorePete;
procedure PeteDying;
procedure SonnyBlackAccepted;
procedure Noone;
procedure SellBusiness;
procedure BuyBusiness;
procedure BusinessMagik;
procedure WantFee;
procedure BusinessCost;
procedure BarterSuccess;
procedure BarterSuccess2;
procedure BarterFail;
procedure BarterFail2;
procedure BoughtCompany;
procedure BoughtCompany30000;
procedure BoughtCompany20000;
procedure BoughtCompany15000;
procedure Stupid;
procedure Stupid2;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Know_Magik                 (8)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
   add_timer_event(self_obj,game_ticks(random(1,5)),0);
   call new_plague_check(self_obj, LVAR_Herebefore);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

      if(global_var(GVAR_MAGIK_SHERIFF) == 1) then begin
          floater_rand(200, 203);
          return;
      end
      else if(global_var(GVAR_WARDEN) == 1) then begin
          floater_rand(320, 322);
          return;
      end



   call set_idiot_savant_int;
       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;

if(
   global_var(GVAR_CARMICHAEL_DEAD) == 1 and
   global_var(GVAR_SONNY_RED_DEAD) == 1 and
   global_var(GVAR_SONNY_BLACK_DEAD) == 1
) then begin
   call FamilyDead;
end else if (global_var(GVAR_SONNY_BLACK_ACCEPTED) == 1) then begin
   call SonnyBlackAccepted;
end else begin

   if (local_var(LVAR_Herebefore)==0) then begin
         call First;
   end else if (local_var(LVAR_Herebefore)==1) then begin
         call Subsequent;
   end
end
       gSay_End;
       end_dialogue;

   call restore_idiot_savant_int;

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

procedure badmouth1 begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, 0);
if is_success(roll_temp) then
begin
call Pete3;
end
else begin
call Pete2;
 end
end

procedure badmouth2 begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -10);
if is_success(roll_temp) then
begin
call Pete4;
end
else begin
call Pete2;
 end
end

procedure Skill_Check_004_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -20);
if is_success(roll_temp) then
begin
call Node035;
end
else begin
call Pete2;
 end
end

procedure haggle1 begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_BARTER, -20);
if is_success(roll_temp) then
begin
call BarterSuccess;
end
else begin
call BarterFail;
 end
end

procedure haggle2 begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_BARTER, -30);
if is_success(roll_temp) then
begin
call BarterSuccess2;
end
else begin
call BarterFail2;
 end
end





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


// Node SoldMagik
//
// Notes:
//
// Player sold the company to Magik

procedure SoldMagik
begin
floater_rand(200,203);
end

// Node IkeDead
//
// Notes:
//
// Ike has been killed

procedure IkeDead
begin
floater_rand(230,232);
end

// Node PhilDead
//
// Notes:
//
// Phil is dead

procedure PhilDead
begin
floater_rand(260,262);
end

// Node FloatAllDead
//
// Notes:
//
// Family have all been killed - note she will also float IkeDead and PhilDead at this point.

procedure FloatAllDead
begin
floater_rand(290,292);
end

// Node Company
//
// Notes:
//
// Player owns the company

procedure Company
begin
floater_rand(320,322);
end

// Node Switcher
//
// Notes:
//
// Floats cover all other instances of the Hogg situation

procedure Switcher
begin
Reply(350);
NOption(351,First,1);
NOption(352,Subsequent,1);
NOption(353,FamilyDead,1);
end

procedure First
begin
Reply(380);
NOption(mstr(381)+dude_name+mstr(382),WhatDo,4);
NOption(383,Node999,4);
NOption(384,Stupid,-3);
NOption(385,Node999,-3);
end

procedure Subsequent
begin
Reply(410);
NOption(411,WhatDo,4);
NOption(412,Business,4);
NOption(413,Family,4);
NOption(414,Node999,4);
NOption(415,Node999,-3);
end

procedure FamilyDead
begin
Reply(440);
NOption(441,Noone,4);
NOption(442,Node999,4);
end

procedure WhatDo
begin
Reply(470);
NOption(471,Fulfilling,4);
NOption(472,Business,4);
NOption(473,Family,4);
NOption(474,Node999,4);
end

procedure Business
begin
Reply(500);
NOption(501,Family,4);
NOption(502,Node999,4);
end

procedure Family
begin
Reply(530);
NOption(531,Pete,4);
NOption(532,Ike,4);
NOption(533,Phil,4);
NOption(534,Business,4);
NOption(535,Node999,4);
end

procedure Family2
begin
Reply(560);
NOption(561,Pete,4);
NOption(562,Ike,4);
NOption(563,Phil,4);
NOption(564,Business,4);
NOption(565,Node999,4);
end

procedure Phil
begin
Reply(590);
NOption(591,PeteDying,4);
NOption(473,Family2,4);
NOption(592,Business,4);
NOption(593,Node999,4);
end

procedure Ike
begin
Reply(620);
NOption(473,Family2,4);
NOption(621,Business,4);
NOption(593,Node999,4);
end

procedure Pete
begin
Reply(650);
NOption(651,PeteDying,4);
NOption(652,badmouth1,4);
NOption(653,MeetJoe,4);
NOption(654,Family2,4);
NOption(655,Business,4);
NOption(656,Node999,4);
end

procedure Pete2
begin
Reply(680);
NOption(681,MeetJoe,4);
NOption(682,Family2,4);
NOption(683,Node999,4);
end

procedure Pete3
begin
Reply(710);
NOption(711,badmouth2,4);
NOption(712,Family2,4);
NOption(502,Node999,4);
end

procedure Pete4
begin
Reply(740);
NOption(741,Family2,4);
NOption(651,PeteDying,4);
NOption(742,MeetJoe,4);
NOption(743,Skill_Check_004_Speech,4);
NOption(656,Node999,4);
end

procedure Fulfilling
begin
Reply(770);
NOption(771,Business,4);
NOption(772,Family,4);
NOption(773,Node999,4);
end

// Node MeetJoe
//
// Notes:
//
// 1) if Magik is alive 2) if Magik has been murdered

procedure MeetJoe
begin
   set_local_var(LVAR_Know_Magik, 1);

Reply(800);
if(local_var(LVAR_Know_Magik) == 1 and global_var(GVAR_MAGIK_DEAD) == 0) then
   NOption(801,Magik,4);
if(local_var(LVAR_Know_Magik) == 1 and global_var(GVAR_MAGIK_DEAD) == 1) then
   NOption(801,MagikDead,4);

NOption(802,MorePete,4);
NOption(803,Family2,4);
NOption(804,Business,4);
NOption(805,Node999,4);
end

procedure Magik
begin
Reply(830);
NOption(831,MorePete,4);
NOption(654,Family2,4);
NOption(592,Business,4);
NOption(832,Node999,4);
end

procedure MagikDead
begin
Reply(860);
NOption(831,MorePete,4);
NOption(654,Family2,4);
NOption(621,Business,4);
NOption(832,Node999,4);
end

// Node MorePete
//
// Notes:
//
// 2) if Magik is alive 3) if he's dead

procedure MorePete
begin
Reply(890);
NOption(891,badmouth1,4);
if (global_var(GVAR_MAGIK_DEAD) == 0) then
NOption(892,Magik,4);
if (global_var(GVAR_MAGIK_DEAD) == 1) then
NOption(892,MagikDead,4);
NOption(654,Family2,4);
NOption(592,Business,4);
NOption(893,Node999,4);
end

procedure PeteDying
begin
Reply(920);
NOption(921,MeetJoe,4);
NOption(922,Node999,4);
end

procedure SonnyBlackAccepted
begin
   set_global_var(GVAR_SONNY_BLACK_ACCEPTED, 2);
Reply(dude_name+mstr(950));
NOption(951,Node999,4);
NOption(952,WantFee,4);
end

procedure Noone
begin
Reply(980);
NOption(981,SellBusiness,4);
NOption(982,Node999,4);
NOption(983,Node999,4);
end

// Node SellBusiness
//
// Notes:
//
// 1) available if Magik is still alive

procedure SellBusiness
begin
Reply(1010);
if(local_var(LVAR_Know_Magik) == 1 and global_var(GVAR_MAGIK_DEAD) == 0) then
NOption(1011,BusinessMagik,4);
NOption(1012,BuyBusiness,4);
NOption(1013,Node038,4);
NOption(1014,Node999,4);
end

// Node BuyBusiness
//
// Notes:
//
// 3) available if Magik is alive

procedure BuyBusiness
begin
Reply(1040);
NOption(1041,BusinessCost,4);
NOption(1042,BusinessCost,4);
if(local_var(LVAR_Know_Magik) == 1 and global_var(GVAR_MAGIK_DEAD) == 0) then
NOption(1043,BusinessMagik,4);
NOption(1044,Node999,4);
end

procedure BusinessMagik
begin
Reply(1070);
NOption(1071,BuyBusiness,4);
NOption(1072,Node038,4);
NOption(1073,Node999,4);
end

procedure WantFee
begin
Reply(1100);
NOption(1101,Node999,4);
NOption(1102,Node999,4);
end

procedure BusinessCost
begin
Reply(1130);
// NOTE: -30,000 caps, add deed
if (item_caps_total(dude_obj)>=30000) then
NOption(1131,BoughtCompany30000,4);
NOption(1132,haggle1,4);
NOption(1133,Node999,4);
end

procedure BarterSuccess
begin
Reply(1160);
// NOTE: -20,000 caps, add deed
if (item_caps_total(dude_obj)>=20000) then
NOption(1161,BoughtCompany20000,4);
NOption(1162,haggle2,4);
NOption(1163,Node999,4);
end

procedure BarterSuccess2
begin
if (dude_is_male) then Reply(1190); else
if (dude_is_female) then Reply(1191);
// NOTE: -15,000 caps, add deed
if (item_caps_total(dude_obj)>=15000) then
NOption(1192,BoughtCompany15000,4);
NOption(1193,Node999,4);
NOption(1194,Node999,4);
end

procedure BarterFail
begin
Reply(mstr(1220)+dude_name+mstr(1221));
// NOTE: -30,000 caps, add deed
if (item_caps_total(dude_obj)>=30000) then
NOption(1222,BoughtCompany30000,4);
NOption(1223,Node999,4);
end

procedure BarterFail2
begin
Reply(1250);
// NOTE: -20,000 caps, add deed
if (item_caps_total(dude_obj)>=20000) then
NOption(1251,BoughtCompany20000,4);
NOption(1252,Node999,4);
end

procedure BoughtCompany begin
   set_global_var(GVAR_WARDEN, 1);
   give_pid_qty(dude_obj, PID_SHERIFF_BADGE, 1)
   give_xp(1000);
Reply(mstr(1280)+dude_name+mstr(1281));
NOption(1282,Node999,4);
NOption(1283,Node999,4);
end

procedure Stupid
begin
Reply(1310);
NOption(1311,Stupid2,-3);
NOption(1312,Node999,-3);
end

procedure Stupid2
begin
Reply(1340);
NOption(1341,Node999,-3);
end

procedure Node035
begin
Reply(1370);
NOption(1371,Node036,4);
NOption(1372,Node037,4);
end

procedure Node036
begin
   dec_general_rep(5);
Reply(1400);
NOption(1401,Node999,4);
end

procedure Node037
begin
   inc_general_rep(5);
Reply(1430);
NOption(1401,Node999,4);
end

procedure Node038
begin
Reply(1460);
NOption(1461,Node999,4);
NOption(1462,BuyBusiness,4);
if(local_var(LVAR_Know_Magik) == 1 and global_var(GVAR_MAGIK_DEAD) == 0) then
NOption(1463,BusinessMagik,4);
end

procedure BoughtCompany15000 begin
   item_caps_adjust(dude_obj, -15000);
   item_caps_adjust(self_obj, 15000);

   call BoughtCompany;
end

procedure BoughtCompany20000 begin
   item_caps_adjust(dude_obj, -20000);
   item_caps_adjust(self_obj, 20000);

   call BoughtCompany;
end

procedure BoughtCompany30000 begin
   item_caps_adjust(dude_obj, -30000);
   item_caps_adjust(self_obj, 30000);

   call BoughtCompany;
end

procedure timed_event_p_proc begin

   add_timer_event(self_obj,game_ticks(random(3, 5)),0);

      if(global_var(GVAR_MAGIK_SHERIFF) == 1) then
          floater_rand(200, 203);
      else if(global_var(GVAR_WARDEN) == 1) then
          floater_rand(320, 322);
    else if (random(0, 30) == 1) then begin
       if( global_var(GVAR_CARMICHAEL_DEAD) == 1 and
   global_var(GVAR_SONNY_RED_DEAD) == 1 and
   global_var(GVAR_SONNY_BLACK_DEAD) == 1) then begin
          floater_rand(290, 292);
   end
       else if(global_var(GVAR_SONNY_BLACK_DEAD) == 1) then
          floater_rand(230, 232);
       else if(global_var(GVAR_SONNY_RED_DEAD) == 1) then
          floater_rand(260, 262);
       else
          floater_rand(200, 203);
   end


end

//xxxxxxxxxxxxxxxxxxxx
