/*

        Name:           Sheriff Carmichael
        Location:
        Description:

           Created: 07/11/2020 19:13:27

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBSHERIF

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure A_better_way;
procedure AboutSalem;
procedure AboutMaurice;
procedure AboutSonia;
procedure Antiratquest;
procedure Askingtobuythings;
procedure Butchsname;
procedure comebackwhenneedhelp;
procedure continueoutline1;
procedure Dothisforme;
procedure Donttakeyourowndamntime;
procedure explaincont2;
procedure hellno;
procedure Idonotlikeit;
procedure Imnotsoft;
procedure insulthimhakeface;
procedure killingratswontstopthemcoming;
procedure tallsallymywife;
procedure money;
procedure Notomoney;
procedure NonotkillemLovers;
procedure NodeA;
procedure nodeA1;
procedure NodeA2;
procedure nodeaskingfordirections;
procedure NodeB;
procedure NodeC;
procedure NodeD;
procedure NodeE;
procedure NodeF;
procedure Notsure;
procedure Nottoowell;
procedure OfcourseIfeelstrongly;
procedure Ohmewatchmyself;
procedure outline3;
procedure outlinecont2;
procedure Outliningtheratsquest;
procedure Setdownsomekilltherest;
procedure sodoff;
procedure Sonicdevice;
procedure stillnotomoney;
procedure Sureamreadytokillrats;
procedure Surrenderedtwelve;
procedure Switcher;
procedure Thatsmorelikeit;
procedure Thengetthehellout;
procedure ThenIhavenothingforyou;
procedure time;
procedure whatabouttheratlovers;
procedure Whathewantsyoutodo;
procedure whatisthekicker;
procedure WhereIstand;
procedure WhyIhaterats;
procedure Whyyou;
procedure Yeahkillemall;
procedure Yestomoney;
procedure yesbanditsdoit;
procedure yestheydotakecarebut;
procedure Youseriousyouwanttohelp;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Pissed                     (8)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);

   add_timer_event(self_obj,game_ticks(random(1,5)),0);
   call new_plague_check(self_obj, LVAR_Herebefore);


end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and self_can_see_dude) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=1;
   Slavery_Tolerant:=SLAVE_INTOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

   if(local_var(LVAR_Pissed) == 1) then begin
      floater_bad(230);
      return;
   end

   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;

      if(global_var(GVAR_QUEST_CULL_CRIMINALS) == 2) then
         call NodeF;
      else if(global_var(GVAR_QUEST_KNOW_CODE) == 3) then
         call NodeE;
      else if(global_var(GVAR_QUEST_KNOW_CODE) == 2) then
         call NodeD;
      else if(global_var(GVAR_QUEST_CULL_CRIMINALS) == 1) then
         call NodeC;
      else if(local_var(LVAR_Herebefore) == 0) then
         call NodeA;
      else
         call NodeB;

       gSay_End;
       end_dialogue;

   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin

   add_timer_event(self_obj,game_ticks(random(3, 5)),0);

    if (random(0, 30) == 1) then begin
       if(global_var(GVAR_QUEST_CULL_CRIMINALS) < 2) then
         floater_bad_rand(200,202);
   end


end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_evil_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


// Node Whatever
//
// Notes:
//
// Quest is not solved.

procedure A_better_way
begin

Reply(230);
NOption(1611,Node999,4);
end

procedure AboutSalem
begin
Reply(260);
NOption(261,AboutSonia,4);
NOption(262,AboutMaurice,4);
NOption(263,Yeahkillemall,4);
NOption(264,money,4);
NOption(265,Node999,4);
end

procedure AboutMaurice
begin
Reply(290);
NOption(261,AboutSonia,4);
NOption(291,AboutSalem,4);
NOption(263,Yeahkillemall,4);
NOption(264,money,4);
NOption(265,Node999,4);
end

procedure AboutSonia
begin
Reply(320);
NOption(321,AboutSalem,4);
NOption(262,AboutMaurice,4);
NOption(263,Yeahkillemall,4);
NOption(264,money,4);
NOption(265,Node999,4);
end

// Node Antiratquest
//
// Notes:
//
// Let there be a check here to see if the PC is a rat priest, in which case Butch will tell him to go away (the node is called "sod off", included). If PC is not a rat priest, the conversation will continue.

procedure Antiratquest
begin
Reply(350);
if(global_var(GVAR_PLAYER_REPUTATION) < 0) then
   NOption(351,sodoff,4);
else
   NOption(351,Outliningtheratsquest,4);
end

procedure Askingtobuythings
begin
Reply(380);
NOption(381,nodeA1,4);
end

procedure Butchsname
begin
Reply(dude_name+mstr(410));
NOption(411,nodeaskingfordirections,4);
NOption(412,Antiratquest,4);
NOption(413,Askingtobuythings,4);
NOption(414,Node999,4);
end

procedure comebackwhenneedhelp
begin
   set_global_var(GVAR_QUEST_CULL_CRIMINALS, 1);
Reply(440);
NOption(441,Node999,4);
end

procedure continueoutline1
begin
Reply(470);
NOption(471,outlinecont2,4);
NOption(472,Whathewantsyoutodo,4);
NOption(473,nodeA1,4);
end

procedure Dothisforme
begin
Reply(500);
NOption(501,comebackwhenneedhelp,4);
NOption(502,Thengetthehellout,4);
end

procedure Donttakeyourowndamntime
begin
Reply(530);
NOption(531,Node999,4);
end

procedure explaincont2
begin
Reply(560);
NOption(561,outline3,4);
end

procedure hellno
begin
Reply(590);
NOption(591,Dothisforme,-3);
NOption(592,Thengetthehellout,4);
end

procedure Idonotlikeit
begin
Reply(620);
NOption(621,time,4);
NOption(622,Setdownsomekilltherest,4);
end

procedure Imnotsoft
begin
Reply(650);
NOption(651,nodeA1,4);
end

procedure insulthimhakeface
begin
Reply(680);
NOption(681,nodeA1,4);
NOption(682,Imnotsoft,4);
end

procedure killingratswontstopthemcoming
begin
Reply(710);
NOption(261,AboutSonia,4);
NOption(291,AboutSalem,4);
NOption(262,AboutMaurice,4);
NOption(263,Yeahkillemall,4);
NOption(264,money,4);
NOption(265,Node999,4);
end

procedure tallsallymywife
begin
Reply(740);
NOption(741,whatisthekicker,4);
end

procedure money
begin
Reply(770);
NOption(771,Yestomoney,4);
NOption(772,Notomoney,4);
end

procedure Notomoney
begin
Reply(800);
NOption(801,Yestomoney,4);
NOption(802,stillnotomoney,4);
end

procedure NonotkillemLovers
begin
Reply(830);
NOption(831,WhyIhaterats,4);
NOption(832,killingratswontstopthemcoming,4);
end

// Node NodeA
//
// Notes:
//
// This sequence is used only for when PC has not accepted rat purge quest.

procedure NodeA
begin
Reply(860);
NOption(861,nodeA1,4);
NOption(862,NodeA2,4);
NOption(mstr(863)+dude_name+mstr(864),Butchsname,4);
NOption(865,insulthimhakeface,4);
NOption(866,Node999,4);
NOption(867,hellno,-3);
NOption(868,hellno,-3);
end

procedure nodeA1
begin
Reply(890);
NOption(891,nodeaskingfordirections,4);
NOption(mstr(892)+dude_name+mstr(864),Butchsname,4);
NOption(893,Antiratquest,4);
end

procedure NodeA2
begin
Reply(920);
NOption(921,nodeaskingfordirections,4);
NOption(922,Antiratquest,4);
NOption(mstr(923)+dude_name+mstr(864),Butchsname,4);
NOption(924,insulthimhakeface,4);
end

procedure nodeaskingfordirections
begin
Reply(950);
NOption(951,Node999,4);
NOption(952,nodeA1,4);
end

procedure NodeB
begin
Reply(980);
NOption(981,Youseriousyouwanttohelp,4);
NOption(982,WhyIhaterats,4);
NOption(983,Node999,4);
end

procedure NodeC
begin
Reply(1010);
NOption(1011,Sureamreadytokillrats,4);
NOption(1012,Donttakeyourowndamntime,4);
NOption(1013,Notsure,4);
end

procedure NodeD
begin
Reply(1040);
NOption(1041,Nottoowell,4);
if (dude_item_count(PID_INFRASONIC_PIP_BOY_2000_CHIP)>0) then
NOption(1042,Sonicdevice,4);
NOption(1043,Node999,4);
end

// Node NodeE
//
// Notes:
//
// Fade out once PC answers.

procedure NodeE
begin
Reply(1070);
NOption(1071,Surrenderedtwelve,4);
end

procedure NodeF
begin
Reply(1100);
NOption(1101,Node999,4);
end

procedure Notsure
begin
Reply(1130);
NOption(1131,Ohmewatchmyself,4);
NOption(1132,Thatsmorelikeit,4);
NOption(1133,A_better_way,4);
end

procedure Nottoowell
begin
Reply(1160);
NOption(981,Youseriousyouwanttohelp,4);
NOption(414,Node999,4);
end

procedure OfcourseIfeelstrongly
begin
Reply(1190);
NOption(1191,tallsallymywife,4);
NOption(1192,Whathewantsyoutodo,4);
end

procedure Ohmewatchmyself
begin
Reply(1220);
NOption(1221,WhereIstand,4);
NOption(1222,Whyyou,4);
end

procedure outline3
begin
Reply(1250);
NOption(1251,Whathewantsyoutodo,4);
end

procedure outlinecont2
begin
Reply(1280);
NOption(1281,outline3,4);
NOption(1282,explaincont2,4);
NOption(472,Whathewantsyoutodo,4);
NOption(1283,Node999,4);
end

procedure Outliningtheratsquest
begin
Reply(1310);
NOption(1311,continueoutline1,4);
end

procedure Setdownsomekilltherest
begin
Reply(1340);
NOption(1341,Node999,4);
end

procedure sodoff
begin
Reply(1370);
NOption(1371,Node999,4);
end

procedure Sonicdevice
begin
Reply(1400);
NOption(1401,Idonotlikeit,4);
end

procedure stillnotomoney
begin
Reply(1430);
NOption(1431,Node999,4);
end

// Node Sureamreadytokillrats
//
// Notes:
//
// Leads to fade out, fade in to rat fighting

procedure Sureamreadytokillrats
begin
Reply(1460);
NOption(531,Node999,4);
end

// Node Surrenderedtwelve
//
// Notes:
//
// The rat cull quest is now solved.

procedure Surrenderedtwelve
begin
item_caps_adjust(dude_obj, 2000);
set_global_var(GVAR_QUEST_CULL_CRIMINALS, 2);
give_xp(2000);
Reply(1490);
NOption(1491,Node999,4);
end

procedure Thatsmorelikeit
begin
      set_global_var(GVAR_QUEST_CULL_CRIMINALS, 1);
Reply(1550);
NOption(1611,Node999,4);
end

procedure Thengetthehellout
begin
Reply(1580);
NOption(441,Node999,4);
end

procedure ThenIhavenothingforyou
begin
Reply(1610);
NOption(1611,Node999,4);
end

procedure time
begin
Reply(1640);
NOption(1641,Node999,4);
// NOTE: Option only available if PC has 12 or more sonic devices in his inventory.
if (dude_item_count(PID_INFRASONIC_PIP_BOY_2000_CHIP)>=12) then
NOption(1642,NodeE,4);
end

procedure whatabouttheratlovers
begin
Reply(1670);
NOption(1671,yestheydotakecarebut,4);
NOption(1672,Yeahkillemall,4);
NOption(1673,money,4);
end

procedure Whathewantsyoutodo
begin
Reply(1700);
NOption(1701,whatabouttheratlovers,4);
NOption(1702,Yeahkillemall,4);
NOption(1703,money,4);
NOption(1704,ThenIhavenothingforyou,4);
end

procedure whatisthekicker
begin
Reply(1730);
NOption(1731,killingratswontstopthemcoming,4);
NOption(1732,Yeahkillemall,4);
NOption(1733,money,4);
end

procedure WhereIstand
begin
Reply(1760);
NOption(1761,Whyyou,4);
NOption(1762,Node999,4);
NOption(1763,Node999,4);
end

procedure WhyIhaterats
begin
Reply(1790);
NOption(1791,yesbanditsdoit,4);
NOption(1792,OfcourseIfeelstrongly,4);
NOption(1793,Node999,4);
end

procedure Whyyou
begin
Reply(1820);
BOption(531,Node998,4);
end

procedure Yeahkillemall
begin
   set_global_var(GVAR_QUEST_CULL_CRIMINALS, 1);
Reply(1850);
NOption(1851,Node999,4);
end

procedure Yestomoney
begin
      set_global_var(GVAR_QUEST_CULL_CRIMINALS, 1);
Reply(1880);
NOption(1611,Node999,4);
end

procedure yesbanditsdoit
begin
Reply(1910);
NOption(1911,tallsallymywife,4);
NOption(1912,Node999,4);
NOption(1913,nodeA1,4);
end

procedure yestheydotakecarebut
begin
Reply(1940);
NOption(1941,WhyIhaterats,4);
NOption(1942,NonotkillemLovers,4);
end

procedure Youseriousyouwanttohelp
begin
Reply(1970);
NOption(1132,Thatsmorelikeit,4);
end



//xxxxxxxxxxxxxxxxxxxx
