//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"

#define NAME                    SCRIPT_TBSKIPPY

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (0)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\headers\footsteps.h"

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure push_p_proc;
/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

/* User defined variables */

variable Skippy_cutters;

procedure start;
procedure do_dialogue;
procedure Skippy00;
procedure Skippy01;
procedure Skippy02;
procedure Skippy03;
procedure Skippy04;
procedure Skippy04a;
procedure Skippy05;
procedure Skippy06;
procedure Skippy07;
procedure Skippy08;
procedure Skippy09;
procedure get_cutters;

import variable Fool_Counter;
import variable Crypt_Counter;

import variable is_crypt;
import variable is_fool;
import variable broken_gen;
import variable Fool_Pointer;
import variable Crypt_Pointer;
import variable Phrax_Pointer;
import variable Rock_Pointer;
import variable Skippy_Talk;

import variable Fool_Taunt;
import variable Crypt_Taunt;

// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)


/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
   if (is_fool) then begin
      switch_team(self_obj,TEAM_PLAYER)
   end
   else begin
      switch_team(self_obj,TEAM_FOOLS)
   end
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   switch_team(self_obj,TEAM_FOOLS)
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);

   if (not(Only_Once)) then begin
      if (self_item_count(PID_WIRE_CUTTERS) < 1) then begin
         Skippy_cutters := create_object(PID_WIRE_CUTTERS, 0, 0);
         add_obj_to_inven(self_obj, Skippy_cutters);
      end
      Only_Once := 1;
   end

   call critter_setup_footsteps_map_enter(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT);
end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if (Crypt_Taunt) then begin
      Crypt_Taunt := 0;
      if (random(1, 5) == 1) then begin
         floater_bad_rand(200, 219);
      end
   end
   else begin
      if ((global_var(GVAR_GANG_WAR) == 1) and (self_tile != 20725)) then begin
         animate_move_to_tile(20725);
      end
      else begin
         if (self_tile == 20725) then begin
            add_timer_event(self_obj, game_ticks(2), 1);
         end
         else begin
            if (broken_gen and (self_tile != 27504)) then begin
               set_global_var(GVAR_GANG_WAR, 2);
               animate_move_to_tile(27504);
            end
            else begin
               if ((self_tile == 27504) and (global_var(GVAR_GANG_WAR) == 2)) then begin
                  set_obj_visibility(self_obj, 1);
                  Fool_Counter := Fool_Counter - 1;
               end
               else begin
                  if ((local_var(LVAR_Hostile) != 0) and self_can_see_dude) then begin
                     set_local_var(LVAR_Hostile,1);
                     self_attack_dude;
                     //Macro made by Tom to keep the critter fleeing.
                  end
                  else begin
                     if ((Skippy_Talk == 1) and (self_can_see_dude or self_can_hear_dude)) then begin
                        Skippy_Talk = 0;
                        floater_bad(125);
                        animate_move_to_tile(tile_num_in_direction(dude_tile, 0, 1));
                        call Node998;
                     end
                     else
                     if (random(0, 21) == 1) then begin
                        animate_move_to_tile(tile_num_in_direction(self_tile, random(0, 5), 2));
                     end
                  end
               end
            end
         end
      end
   end
end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
       if (obj_is_carrying_obj_pid(dude_obj, obj_pid(Skippy_cutters))) then
         floater_bad(123);
       else
         floater_bad(122);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin
   Evil_Critter:=1;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

   start_gdialog(NAME, self_obj, 4, -1, -1);
   gSay_Start;
   if (is_crypt) then begin
      call Skippy07;
   end
   else begin
      if (is_fool) then begin
         call Skippy08;
      end
      else if (obj_is_carrying_obj_pid(self_obj, obj_pid(Skippy_cutters))) then begin
            call Skippy00;
      end
      else begin
         call Skippy09;
      end
   end
   gSay_End;
   end_dialogue;

   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin
   variable critters, critter, team;

   if (fixed_param == 1) then begin
      set_global_var(GVAR_GANG_WAR, 0);
      if (self_can_speak and (Fool_Taunt == 0)) then begin
         Fool_Taunt := 1;
         floater_bad_rand(200, 219);
      end
      add_timer_event(self_obj, 4, 2);
   end
   else begin
      if (fixed_param == 2) then begin
         if(combat_is_initialized == false and ((critter_state(self_obj) bwand DAM_KNOCKED_OUT) == false)) then begin
            critters := objects_in_radius(self_tile, get_critter_base_stat(self_obj, STAT_pe), self_elevation, OBJ_TYPE_CRITTER);

            foreach (critter in critters) begin
               if(critter_attackable(critter) and obj_can_see_obj(self_obj, critter)) then begin
                  team := has_trait(TRAIT_OBJECT, critter, OBJECT_TEAM_NUM);

                  if(TEAM_CRYPTS == team) then begin
                     self_attack_critter(critter);
                     break;
                  end
               end
            end
         end
      end
   end

   call critter_setup_footsteps_timed_event(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT, SFX_FOOTSTEP_MEDIUM_SHOE);
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin
   Fool_Counter := Fool_Counter - 1;
/* Increment the aligned critter counter*/
   inc_evil_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   if (obj_is_carrying_obj_pid(self_obj, obj_pid(Skippy_cutters))) then begin
      script_overrides;
      display_mstr(102);
   end
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

procedure push_p_proc begin
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures




// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE

procedure Skippy00 begin
   Reply(105);
   NOption(106, Skippy01, 4);
   NOption(107, Skippy06, 4);
   NOption(108, Skippy04, 4);
   NOption(306, Skippy01, -3);
   NOption(307, Skippy06, -3);
   NOption(308, Skippy04, -3);
end

procedure Skippy01 begin
   Reply(109);
   NOption(110, Skippy02, 4);
   NOption(111, Skippy03, 4);
   NOption(310, Skippy02, -3);
   NOption(311, Skippy03, -3);
end

procedure Skippy02 begin
   Reply(112);
   BOption(104, Node998, 1);
end

procedure Skippy03 begin
   Reply(113);
   NOption(114, Skippy04, 4);
   NOption(314, Skippy04, -3);
end

procedure Skippy04 begin
   Reply(115);
   NOption(116, Skippy04a, 4);
   NOption(316, Skippy04a, -3);
end

procedure Skippy04a begin
   if (is_success(do_check(dude_obj, STAT_ch, 0))) then begin
      call Skippy05;
   end
   else begin
      call Skippy06;
   end
end

procedure Skippy05 begin
   Reply(117);
   NOption(104, get_cutters, 1);
end

procedure Skippy06 begin
   Reply(118);
   BOption(104, Node998, 1);
end

procedure Skippy07 begin
   Reply(119);
   NOption(104, Node999, 1);
end

procedure Skippy08 begin
   Reply(120);
   NOption(104, Node999, 1);
end

procedure Skippy09 begin
   Reply(121);
   NOption(104, Node999, 1);
end

procedure get_cutters begin
   rm_obj_from_inven(self_obj, Skippy_cutters);
   add_obj_to_inven(dude_obj, Skippy_cutters);
   call Node999;
end

//xxxxxxxxxxxxxxxxxxxx
