/*

        Name:           Slappy
        Location:       Cutty Sark, CotC
        Description:    Slappy is the bartender in the Cutty Sark. He's involved in the 'Who killed Angela?' and 'Fix the jukebox' quests.

           Created: 07/10/2020 19:01:00

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBSLAPPY

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Slappy_1a;
procedure Slappy_1a_2a;
procedure Slappy_1a_2b;
procedure Slappy_1a_3B_1;
procedure Slappy_1a_3B_2a;
procedure Slappy_1a_3B_2b_1;
procedure Slappy_1a_3B_2b_2;
procedure Slappy_1a_3B_2b_3;
procedure Slappy_1a_3B_2c;
procedure Slappy_1b_a;
procedure Slappy_1b_b;
procedure Slappy_1c_1;
procedure Slappy_1c_2;
procedure Slappy_1c_3;
procedure Slappy_1d_a1;
procedure Slappy_1d_a2;
procedure Slappy_1d_a3;
procedure Slappy_1d_a4;
procedure Slappy_1d_b1;
procedure Slappy_1d_b2;
procedure Slappy_1d_b2_1a;
procedure Slappy_1d_b2_1b;
procedure Slappy_1d_c1;
procedure Slappy_1d_c2_B;
procedure Slappy_2_1;
procedure Slappy_2_2a_1;
procedure Slappy_2_2a_2;
procedure Slappy_2_2b_1;
procedure Slappy_2_2b_2;
procedure Slappy_2_2c_2;
procedure Slappy_2_2d_1;
procedure Slappy_2_2d_2a_1;
procedure Slappy_2_2d_2a_2a_1;
procedure Slappy_2_2d_2a_2a_2a;
procedure Slappy_2_2d_2a_2a_2b;
procedure Slappy_2_2d_2a_2b;
procedure Slappy_2_2d_2b_1;
procedure Slappy_2_2d_2b_2;
procedure Slappy_2_2e_1;
procedure Slappy_2_2e_2;
procedure Slappy_2_9a;
procedure Slappy_2_9b;
procedure Slappy_3_1;
procedure Slappy_3_1D_1;
procedure Slappy_3_1D_2;
procedure Slappy_3_2a;
procedure Slappy_3_2b_1;
procedure Slappy_3_2b_2a_1;
procedure Slappy_3_2b_2a_2;
procedure Slappy_3_2b_2b_1;
procedure Slappy_3_2b_2b_2;
procedure Slappy_3_2c_1;
procedure Slappy_3_2c_2a_1;
procedure Slappy_3_2c_2a_2;
procedure Slappy_3_2c_2a_3;
procedure Slappy_3_2c_2a_4a_1;
procedure Slappy_3_2c_2a_4a_2;
procedure Slappy_3_2c_2a_4b;
procedure Slappy_3_2c_2b_1;
procedure Slappy_3_2c_2b_2;
procedure Slappy_3_2c_2b_3;
procedure Slappy_3_2c_2b_4a;
procedure Slappy_3_2c_2b_4b;
procedure Slappy_3_2c_2b_5;
procedure Slappy_3_2c_2b_6;
procedure Slappy_3_2d_1;
procedure Slappy_3_2e_1;
procedure Slappy_3_2e_2;
procedure Slappy_3_2e_3;
procedure Slappy_3_2e_4;
procedure Slappy_3_2e_5a;
procedure Slappy_3_2e_5b;
procedure Slappy_3_2e_6a_1;
procedure Slappy_3_2e_6a_2;
procedure Slappy_3_2e_6a_3;
procedure Slappy_3_2e_6b_1;
procedure Slappy_3_2e_6b_2;
procedure Slappy_3_2f_1;
procedure Slappy_3_2f_2a;
procedure Slappy_3_2f_2b_1;
procedure Slappy_3_2f_2b_2B;
procedure Slappy_3_2f_2b_2G;
procedure Slappy_4_1;
procedure Slappy_4_2a;
procedure Slappy_4_2b_1;
procedure Slappy_4_2b_2a;
procedure Slappy_4_2b_2b_a1;
procedure Slappy_4_2b_2b_a2;
procedure Slappy_4_2b_2b_D1;
procedure Slappy_4_2b_2b_D2;
procedure Slappy_4_2b_2b_D3;
procedure Slappy_5_1;
procedure Slappy_5_2a_1a;
procedure Slappy_5_2a_1D;
procedure Slappy_5_2a_2;
procedure Slappy_5_2a_3;
procedure Slappy_5_2a_4a;
procedure Slappy_5_2a_4b;
procedure Slappy_5_2b;
procedure Slappy_6_1;
procedure Slappy_6_2a_1;
procedure Slappy_6_2a_2;
procedure Slappy_6_2b_1;
procedure Slappy_6_2b_2;
procedure Slappy_6_2c;
procedure Slappy_9;
procedure Node999_take;
procedure Node998_take;
procedure take;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)

#define LVAR_Slappy_Angela_Congrats (8)
#define LVAR_Slappy_Angela_Death (9)
#define LVAR_Slappy_Angela_Robo (10)
#define LVAR_Slappy_Angela_Maybe (11)
#define LVAR_Slappy_Angela_Sister (12)
#define LVAR_Slappy_Work_Alone (13)
#define LVAR_Slappy_Black_Widow (14)
#define LVAR_Slappy_Robbery_Failed (15)
#define LVAR_Slappy_Robbery_Succeed (16)
#define LVAR_Slappy_Robbery (17)


/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);

   add_timer_event(self_obj,game_ticks(random(1,5)),0);
   call new_plague_check(self_obj, LVAR_Herebefore);



end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;

if (global_var(GVAR_FIXED_FLOOR) == 1) then
       call Slappy_1c_1;
else if (global_var(GVAR_ANGELA_DEAD) == 1) and (global_var(GVAR_TIPOFF_CROZ) == 2) then
       call Slappy_1d_c1;
else if (global_var(GVAR_ANGELA_DEAD) == 1) and (global_var(GVAR_TIPOFF_ROBB) == 2) then
       call Slappy_1d_b1;
else if (global_var(GVAR_ANGELA_DEAD) == 1) then
       call Slappy_1d_a1;
else if (local_var(LVAR_Herebefore)==0) then
       call Slappy_1a;
else if (local_var(LVAR_Herebefore)==1) and (local_var(LVAR_Slappy_Robbery_Failed)==0) then
       call Slappy_1b_a;
else if (local_var(LVAR_Herebefore)==1) and (local_var(LVAR_Slappy_Robbery_Failed)>0) then
       call Slappy_1b_b;


       gSay_End;
       end_dialogue;


   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin

   add_timer_event(self_obj,game_ticks(random(3, 5)),0);

    if (random(0, 30) == 1) then begin
       if(local_var(LVAR_Slappy_Robbery_Succeed) == 1) then
          floater_rand(230, 235);
      else if (global_var(GVAR_ANGELA_DEAD) == 1) and (global_var(GVAR_TIPOFF_CROZ) == 2) then
          floater_rand(290, 295);
      else if (global_var(GVAR_ANGELA_DEAD) == 1) and (global_var(GVAR_TIPOFF_ROBB) == 2) then
          floater_rand(320, 325);
    else if (global_var(GVAR_ANGELA_DEAD) == 1) then
          floater_rand(260, 265);
   else
          floater_rand(200, 205);
   end

end


/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_neutral_critter

if(global_var(GVAR_QUEST_KILL_PATIENTS) != 20) then
   inc_global_var(GVAR_QUEST_KILL_PATIENTS);

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

procedure Skill_Check_001_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -30);
if is_success(roll_temp) then
begin
call Slappy_1a_3B_2b_1;
end
else begin
call Slappy_1a_3B_2a;
 end
end



// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Slappy_1a
begin
Reply(380);
GOption(mstr(381)+dude_name+mstr(382),Slappy_1a_2a,4);
NOption(383,Slappy_1a_2b,4);
NOption(384,Slappy_1a_2b,-3);
end

procedure Slappy_1a_2a
begin
Reply(410);
NOption(411,Slappy_2_1,4);
end

procedure Slappy_1a_2b
begin
Reply(440);
NOption(441,Slappy_2_1,4);
NOption(442,Slappy_1a_3B_1,4);
end

procedure Slappy_1a_3B_1
begin
Reply(470);
// NOTE: This needs a tough intimidation check. If failed, go to Slappy_1a_3B_2a. On success, go to Slappy_1a_3B_2b_1, instead.
if (local_var(LVAR_Slappy_Robbery)==0) then
NOption(471,Skill_Check_001_Speech,4);
if (local_var(LVAR_Slappy_Robbery)>0) then
NOption(471,Slappy_1a_3B_2c,4);
NOption(472,Slappy_2_1,4);
end

// Node Slappy_1a_3B_2a
//
// Notes:
//
// Increment the local variable Slappy_Robbery by 1.

procedure Slappy_1a_3B_2a
begin

inc_local_var_amt(LVAR_Slappy_Robbery, 1);


if (dude_is_male) then Reply(500); else
if (dude_is_female) then Reply(501);
BOption(502,Node998,4);
NOption(503,Node999,4);
end

procedure Slappy_1a_3B_2b_1
begin
Reply(530);
BOption(531,Slappy_1a_3B_2b_2,4);
end

procedure Slappy_1a_3B_2b_2
begin
Reply(560);
// NOTE: Increment the PC's caps by a certain amount, modified by the PC's Luck.
//Appropriate penalty to karma.
BOption(561,Node999_take,4);
// NOTE: Increment the PC's caps by a certain amount, modified by the PC's Luck.
//Appropriate penalty to karma.
BOption(562,Node998_take,4);
// NOTE: Appropriate penalty to karma, although obviously less than those for the other two player options.
BOption(563,Slappy_1a_3B_2b_3,4);
end

procedure take begin
   move_obj_inven_to_obj(self_obj, dude_obj);
   dec_general_rep(5);
   dec_tibbets_rep(-10);
end

procedure Node999_take begin
   call take;
   call Node999;
end

procedure Node998_take begin
   call take;
   call Node998;
end

procedure Slappy_1a_3B_2b_3
begin
   dec_general_rep(3);
Reply(590);
BOption(591,Node999,4);
BOption(592,Node999,4);
end

procedure Slappy_1a_3B_2c
begin
if (dude_is_male) then Reply(620); else
if (dude_is_female) then Reply(621);
BOption(502,Node998,4);
NOption(503,Node999,4);
end

procedure Slappy_1b_a
begin
Reply(650);
NOption(651,Slappy_2_1,4);
if (local_var(LVAR_Slappy_Angela_Death)>0) then
NOption(652,Slappy_3_1,4);
if(global_var(GVAR_FIXED_FLOOR) == 0) then
NOption(653,Slappy_4_1,4);
else
NOption(654,Slappy_5_1,4);
NOption(655,Slappy_6_1,4);
NOption(656,Node999,4);
NOption(657,Slappy_2_1,-3);
NOption(658,Slappy_3_1D_1,-3);
NOption(659,Slappy_4_1,-3);
NOption(660,Slappy_5_2a_1D,-3);
end

procedure Slappy_1b_b
begin
if (dude_is_male) then Reply(680); else
if (dude_is_female) then Reply(681);
NOption(651,Slappy_2_1,4);
if (local_var(LVAR_Slappy_Angela_Death)>0) then
NOption(652,Slappy_3_1,4);
if(global_var(GVAR_FIXED_FLOOR) == 0) then
NOption(653,Slappy_4_1,4);
else
NOption(654,Slappy_5_1,4);
NOption(655,Slappy_6_1,4);
NOption(656,Node999,4);
end

procedure Slappy_1c_1
begin
Reply(710);
NOption(711,Slappy_1c_2,4);
NOption(mstr(712)+dude_name+mstr(713),Slappy_1c_2,-3);
end

procedure Slappy_1c_2
begin
Reply(740);
NOption(741,Slappy_1c_3,4);
if(has_skill(dude_obj, SKILL_REPAIR) >= 50) then
NOption(742,Slappy_5_2a_1a,4);
NOption(743,Slappy_1c_3,-3);
if(has_skill(dude_obj, SKILL_REPAIR) >= 50) then
NOption(660,Slappy_5_2a_1D,-3);
end

// Node Slappy_1c_3
//
// Notes:
//
// This also doubles as a node where Slappy can congratulate the PC on bringing someone other than Robb to 'justice' for the murder of Angela.

procedure Slappy_1c_3
begin
Reply(770);
NOption(771,Slappy_2_2d_2a_1,4);
NOption(772,Slappy_9,4);
NOption(mstr(773)+dude_name+mstr(774),Slappy_2_2d_2a_1,-3);
NOption(mstr(775)+dude_name+mstr(776),Slappy_9,-3);
end

procedure Slappy_1d_a1
begin
Reply(800);
NOption(801,Slappy_1d_a2,4);
NOption(802,Node999,4);
NOption(803,Slappy_1d_a2,-3);
NOption(503,Node999,-3);
end

procedure Slappy_1d_a2
begin
Reply(830);
NOption(411,Slappy_2_1,4);
if (local_var(LVAR_Slappy_Angela_Death)==0) then
NOption(831,Slappy_1d_a3,4);
if (local_var(LVAR_Slappy_Angela_Death)>0) then
NOption(832,Slappy_3_1,4);
NOption(833,Node999,4);
NOption(834,Slappy_2_1,-3);
if (local_var(LVAR_Slappy_Angela_Death)==0) then
NOption(835,Slappy_1d_a3,-3);
if (local_var(LVAR_Slappy_Angela_Death)>0) then
NOption(658,Slappy_3_1D_1,-3);
NOption(503,Node999,-3);
end

// Node Slappy_1d_a3
//
// Notes:
//
// Increment the local variable Slappy_Angela_Death by 1.

procedure Slappy_1d_a3
begin

inc_local_var_amt(LVAR_Slappy_Angela_Death, 1);

Reply(860);
NOption(861,Slappy_1d_a4,4);
NOption(862,Slappy_3_2a,4);
NOption(863,Slappy_2_1,4);
NOption(864,Node999,4);
NOption(865,Slappy_3_2a,-3);
NOption(866,Slappy_2_1,-3);
NOption(503,Node999,-3);
end

procedure Slappy_1d_a4
begin
Reply(890);
NOption(862,Slappy_3_2a,4);
NOption(863,Slappy_2_1,4);
NOption(864,Node999,4);
end

procedure Slappy_1d_b1
begin
Reply(920);
NOption(411,Slappy_2_1,4);
NOption(921,Slappy_1d_b2,4);
NOption(833,Node999,4);
end

procedure Slappy_1d_b2
begin
Reply(950);
NOption(951,Slappy_1d_b2_1a,4);
NOption(952,Slappy_1d_b2_1b,4);
NOption(411,Slappy_2_1,4);
NOption(833,Node999,4);
end

procedure Slappy_1d_b2_1a
begin
Reply(980);
NOption(952,Slappy_1d_b2_1b,4);
NOption(411,Slappy_2_1,4);
NOption(833,Node999,4);
end

procedure Slappy_1d_b2_1b
begin
Reply(1010);
NOption(951,Slappy_1d_b2_1a,4);
NOption(411,Slappy_2_1,4);
NOption(833,Node999,4);
end

// Node Slappy_1d_c1
//
// Notes:
//
// Increment the local variable Slappy_Angela_Congrats by 1.

procedure Slappy_1d_c1
begin
   inc_local_var_amt(LVAR_Slappy_Angela_Congrats, 1);
Reply(1040);
GOption(1041,Slappy_1c_3,4);
NOption(1042,Slappy_1c_3,4);
BOption(1043,Slappy_1d_c2_B,4);
end

procedure Slappy_1d_c2_B
begin
Reply(1070);
NOption(411,Slappy_2_1,4);
NOption(1071,Slappy_9,4);
NOption(833,Node999,4);
end

// Node Slappy_2_1
//
// Notes:
//
// The Slappy_2_* path is where the PC can get a drink!

procedure Slappy_2_1
begin
Reply(1100);
NOption(1101,Slappy_2_2a_1,4);
NOption(1102,Slappy_2_2b_1,4);
NOption(1104,Slappy_2_2d_1,4);
NOption(1105,Slappy_2_2e_1,4);
NOption(1106,Slappy_9,4);
NOption(1107,Slappy_2_2a_1,-3);
NOption(1108,Slappy_2_2b_1,-3);
NOption(1110,Slappy_2_2d_1,-3);
NOption(1111,Slappy_9,-3);
end

procedure Slappy_2_2a_1
begin
Reply(1130);
if (item_caps_total(dude_obj)>=5) then
NOption(1131,Slappy_2_2a_2,4);
if (item_caps_total(dude_obj)<5) then
NOption(1132,Slappy_2_9b,4);
NOption(1106,Slappy_9,4);
if (item_caps_total(dude_obj)>=5) then
NOption(1131,Slappy_2_2a_2,-3);
if (item_caps_total(dude_obj)<5) then
NOption(1133,Slappy_2_9b,-3);
NOption(1134,Slappy_9,-3);
end

// Node Slappy_2_2a_2
//
// Notes:
//
// Deduct 5 from dude_caps. Put a beer in the PC's inventory.

procedure Slappy_2_2a_2
begin

item_caps_adjust(dude_obj, -5);
give_pid_qty(dude_obj, PID_BEER, 1)

Reply(1160);
NOption(1161,Slappy_2_9a,4);
NOption(1161,Slappy_2_9a,-3);
end

procedure Slappy_2_2b_1
begin
Reply(1190);
if (item_caps_total(dude_obj)>=10) then
NOption(1191,Slappy_2_2b_2,4);
if (item_caps_total(dude_obj)<10) then
NOption(1132,Slappy_2_9b,4);
NOption(1106,Slappy_9,4);
// NOTE: Transfer a bottle of booze to the PC's inventory.
if (item_caps_total(dude_obj)>=10) then
NOption(1191,Slappy_2_2b_2,4);
if (item_caps_total(dude_obj)<10) then
NOption(1133,Slappy_2_9b,-3);
NOption(1192,Slappy_9,-3);
end

// Node Slappy_2_2b_2
//
// Notes:
//
// Deduct 10 from dude_caps. Add a bottle of booze to the PC's inventory.

procedure Slappy_2_2b_2
begin

item_caps_adjust(dude_obj, -10);
give_pid_qty(dude_obj, PID_BOOZE, 1)

Reply(1220);
NOption(1221,Slappy_2_9a,4);
NOption(1221,Slappy_2_9a,-3);
end


procedure Slappy_2_2d_1
begin
if (dude_is_male) then Reply(1310); else
if (dude_is_female) then Reply(1311);
NOption(1312,Slappy_2_2d_2b_1,4);
// NOTE: Transfer a bottle of booze to the PC's inventory.
if (item_caps_total(dude_obj)>=10) then
NOption(1191,Slappy_2_2d_2a_1,4);
if (item_caps_total(dude_obj)<10) then
NOption(1132,Slappy_2_9b,4);
NOption(1106,Slappy_9,4);
if (item_caps_total(dude_obj)>=10) then
NOption(1191,Slappy_2_2d_2a_1,-3);
if (item_caps_total(dude_obj)<10) then
NOption(1133,Slappy_2_9a,4);
NOption(1111,Slappy_9,-3);
end

// Node Slappy_2_2d_2a_1
//
// Notes:
//
// Deduct 10 from dude_caps.

procedure Slappy_2_2d_2a_1
begin

item_caps_adjust(dude_obj, -10);

Reply(1340);
NOption(1341,Slappy_2_2d_2a_2a_1,4);
NOption(1342,Slappy_2_2d_2a_2b,4);
NOption(1106,Slappy_2_2d_2a_2b,4);
NOption(1341,Slappy_2_2d_2a_2a_1,-3);
NOption(1343,Slappy_2_2d_2a_2b,-3);
NOption(1344,Slappy_2_2d_2a_2b,-3);
end

// Node Slappy_2_2d_2a_2a_1
//
// Notes:
//
// Implement the effects of a beer upon the PC.

procedure Slappy_2_2d_2a_2a_1
begin
Reply(1370);
NOption(1371,Slappy_2_2d_2a_2a_2a,4);
NOption(1372,Slappy_2_2d_2a_2a_2b,4);
NOption(mstr(1373)+dude_name+mstr(1374),Slappy_2_2d_2a_2a_2a,-3);
NOption(1375,Slappy_2_2d_2a_2a_2b,-3);
end

procedure Slappy_2_2d_2a_2a_2a
begin
Reply(1400);
NOption(1401,Slappy_2_2d_1,4);
NOption(1402,Slappy_2_1,4);
NOption(1403,Slappy_9,4);
NOption(1404,Node999,4);
NOption(mstr(1405)+dude_name+mstr(1406),Slappy_2_2d_1,-3);
NOption(mstr(712)+dude_name+mstr(1407),Slappy_2_1,-3);
NOption(1408,Slappy_9,-3);
NOption(503,Node999,-3);
end

procedure Slappy_2_2d_2a_2a_2b
begin
Reply(1430);
NOption(1431,Slappy_2_2d_1,4);
NOption(1432,Slappy_2_1,4);
NOption(1433,Slappy_9,4);
NOption(864,Node999,4);
NOption(1434,Slappy_2_1,-3);
NOption(1435,Slappy_9,-3);
NOption(503,Node999,-3);
end

procedure Slappy_2_2d_2a_2b
begin
Reply(1460);
NOption(1341,Slappy_2_2d_2a_2a_1,4);
NOption(1461,Slappy_9,4);
NOption(503,Node999,4);
NOption(1341,Slappy_2_2d_2a_2a_1,-3);
NOption(1462,Slappy_9,-3);
NOption(503,Node999,-3);
end

procedure Slappy_2_2d_2b_1
begin
Reply(1490);
NOption(1491,Slappy_2_2d_2b_2,4);
// NOTE: Transfer a bottle of booze to the PC's inventory.
if (item_caps_total(dude_obj)>=10) then
NOption(1492,Slappy_2_2d_2a_1,4);
if (item_caps_total(dude_obj)<10) then
NOption(1132,Slappy_2_9b,4);
NOption(1106,Slappy_9,4);
end

procedure Slappy_2_2d_2b_2
begin
Reply(1520);
// NOTE: Transfer a bottle of booze to the PC's inventory.
if (item_caps_total(dude_obj)>=10) then
NOption(1521,Slappy_2_2d_2a_1,4);
NOption(1522,Slappy_2_2e_1,4);
if (item_caps_total(dude_obj)<10) then
NOption(1523,Slappy_2_9b,4);
NOption(1106,Slappy_9,4);
end

procedure Slappy_2_2e_1
begin
Reply(1550);
NOption(1551,Slappy_2_2e_2,4);
NOption(1104,Slappy_2_2d_1,4);
NOption(1101,Slappy_2_2a_1,4);
NOption(1102,Slappy_2_2b_1,4);
NOption(1106,Slappy_9,4);
end

procedure Slappy_2_2e_2
begin
Reply(1580);
NOption(1581,Slappy_2_2d_1,4);
NOption(1101,Slappy_2_2a_1,4);
NOption(1102,Slappy_2_2b_1,4);
NOption(1106,Slappy_9,4);
end

procedure Slappy_2_9a
begin
Reply(1610);
NOption(1611,Slappy_2_1,4);
NOption(1071,Slappy_9,4);
NOption(1612,Node999,4);
NOption(1613,Slappy_2_1,-3);
NOption(1614,Slappy_9,-3);
NOption(503,Node999,-3);
end

procedure Slappy_2_9b
begin
Reply(1640);
NOption(1641,Slappy_2_1,4);
NOption(1642,Slappy_9,4);
NOption(864,Node999,4);
end

// Node Slappy_3_1
//
// Notes:
//
// The Slappy_3_* path is where the PC can ask Slappy about what he knows about Angela's death.

procedure Slappy_3_1
begin
Reply(1670);
NOption(1671,Slappy_3_2a,4);
NOption(1672,Slappy_3_2b_1,4);
NOption(1673,Slappy_3_2c_1,4);
if (obj_is_carrying_obj_pid(dude_obj,PID_LAVANDER_FLOWER)>0) then
NOption(1674,Slappy_3_2e_1,4);
NOption(1675,Slappy_3_2f_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_1D_1
begin
Reply(1700);
NOption(mstr(712)+dude_name+mstr(1701),Slappy_3_1D_2,-3);
NOption(1702,Slappy_9,-3);
NOption(503,Node999,-3);
end

procedure Slappy_3_1D_2
begin
Reply(1730);
NOption(1702,Slappy_9,-3);
NOption(503,Node999,-3);
end

// Node Slappy_3_2a
//
// Notes:
//
// Increment the local variable Slappy_Angela_Sister by 1.

procedure Slappy_3_2a
begin
   inc_local_var_amt(LVAR_Slappy_Angela_Sister, 1);
Reply(1760);
NOption(1672,Slappy_3_2b_1,4);
NOption(1673,Slappy_3_2c_1,4);
if (obj_is_carrying_obj_pid(dude_obj,PID_LAVANDER_FLOWER)>0) then
NOption(1674,Slappy_3_2e_1,4);
NOption(1675,Slappy_3_2f_1,4);
NOption(1676,Slappy_9,4);
NOption(658,Slappy_3_1D_1,-3);
NOption(1761,Slappy_9,-3);
NOption(503,Node999,-3);
end

// Node Slappy_3_2b_1
//
// Notes:
//
// Increment the local variable Slappy_Angela_Dyke by 1.

procedure Slappy_3_2b_1
begin

inc_local_var_amt(LVAR_Slappy_Angela_Robo, 1);

Reply(1790);
NOption(1791,Slappy_3_2b_2a_1,4);
NOption(1792,Slappy_3_2b_2b_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2b_2a_1
begin
Reply(1820);
NOption(1821,Slappy_3_2b_2a_2,4);
end

procedure Slappy_3_2b_2a_2
begin
Reply(1850);
NOption(1851,Slappy_3_2f_1,4);
NOption(1852,Slappy_3_2b_2b_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2b_2b_1
begin
Reply(1880);
NOption(1881,Slappy_3_2b_2b_2,4);
NOption(1882,Slappy_3_2b_2a_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2b_2b_2
begin
Reply(1910);
NOption(1882,Slappy_3_2b_2a_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2c_1
begin
Reply(1940);
NOption(1941,Slappy_3_2c_2a_1,4);
NOption(1942,Slappy_3_2c_2b_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2c_2a_1
begin
Reply(1970);
NOption(1971,Slappy_3_2c_2a_2,4);
NOption(1942,Slappy_3_2c_2b_3,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2c_2a_2
begin
Reply(2000);
NOption(1821,Slappy_3_2c_2a_3,4);
end

procedure Slappy_3_2c_2a_3
begin
Reply(2030);
if (local_var(LVAR_Slappy_Black_Widow)==0) then
NOption(2031,Slappy_3_2c_2a_4a_1,4);
if (local_var(LVAR_Slappy_Black_Widow)>0) then
NOption(2031,Slappy_3_2c_2a_4b,4);
NOption(1942,Slappy_3_2c_2b_3,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2c_2a_4a_1
begin
inc_local_var_amt(LVAR_Slappy_Black_Widow, 1);

Reply(2060);
NOption(2061,Slappy_3_2c_2a_4a_2,4);
NOption(1942,Slappy_3_2c_2b_3,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2c_2a_4a_2
begin
Reply(2090);
NOption(1942,Slappy_3_2c_2b_3,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2c_2a_4b
begin
Reply(2120);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2c_2b_1
begin
Reply(2150);
NOption(1821,Slappy_3_2c_2b_2,4);
end

procedure Slappy_3_2c_2b_2
begin
Reply(2180);
NOption(2181,Slappy_3_2c_2b_3,4);
NOption(2182,Slappy_3_2c_2b_3,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2c_2b_3
begin
Reply(2210);
NOption(2211,Slappy_3_2c_2b_4a,4);
if(global_var(GVAR_KNOW_MAGIK) == 1) then
NOption(2212,Slappy_3_2c_2b_4b,4);
NOption(1941,Slappy_3_2c_2a_2,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2c_2b_4a
begin

set_global_var(GVAR_ANGELA_MAGIK_MARRY, 1);

Reply(2240);
NOption(2241,Slappy_3_2c_2b_5,4);
NOption(2242,Slappy_3_2c_2b_5,4);
if(global_var(GVAR_KNOW_MAGIK) == 1) then
NOption(2212,Slappy_3_2c_2b_4b,4);
NOption(1941,Slappy_3_2c_2a_2,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2c_2b_4b
begin
Reply(2270);
NOption(2271,Slappy_3_2c_2b_4a,4);
NOption(1941,Slappy_3_2c_2a_2,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2c_2b_5
begin
Reply(2300);
NOption(2301,Slappy_3_2c_2b_6,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2c_2b_6
begin
Reply(2330);
NOption(2331,Slappy_3_2d_1,4);
NOption(2332,Slappy_3_2c_2a_2,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2d_1
begin
Reply(2360);
NOption(1941,Slappy_3_2c_2a_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2e_1
begin
Reply(2390);
NOption(2391,Slappy_3_2e_2,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2e_2
begin
Reply(2420);
NOption(2421,Slappy_3_2e_3,4);
NOption(1675,Slappy_3_2f_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2e_3
begin
if (dude_is_male) then Reply(2450); else
if (dude_is_female) then Reply(2451);
NOption(2452,Slappy_3_2e_4,4);
NOption(1675,Slappy_3_2f_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2e_4
begin
Reply(2480);
NOption(2481,Slappy_3_2e_5a,4);
NOption(2482,Slappy_3_2e_5b,4);
NOption(1675,Slappy_3_2f_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2e_5a
begin
Reply(2510);
NOption(2511,Slappy_3_2e_5b,4);
NOption(1675,Slappy_3_2f_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2e_5b
begin
Reply(2540);
NOption(2541,Slappy_3_2e_6a_1,4);
NOption(2542,Slappy_3_2e_6b_1,4);
NOption(2481,Slappy_3_2e_5a,4);
NOption(1675,Slappy_3_2f_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2e_6a_1
begin
Reply(2570);
if (local_var(LVAR_Slappy_Angela_Sister)>0) then
NOption(2571,Slappy_3_2e_6a_2,4);
NOption(2572,Slappy_3_2e_6b_1,4);
NOption(2481,Slappy_3_2e_5a,4);
NOption(1675,Slappy_3_2f_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2e_6a_2
begin
Reply(2600);
if (local_var(LVAR_Slappy_Angela_Robo)>0) then
NOption(2601,Slappy_3_2e_6a_3,4);
NOption(2572,Slappy_3_2e_6b_1,4);
NOption(2481,Slappy_3_2e_5a,4);
NOption(1675,Slappy_3_2f_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2e_6a_3
begin
Reply(2630);
NOption(2572,Slappy_3_2e_6b_1,4);
NOption(2481,Slappy_3_2e_5a,4);
NOption(1675,Slappy_3_2f_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2e_6b_1
begin
Reply(2660);
if (local_var(LVAR_Slappy_Angela_Robo)>0) then
NOption(2661,Slappy_3_2e_6b_2,4);
NOption(2541,Slappy_3_2e_6a_1,4);
NOption(2481,Slappy_3_2e_5a,4);
NOption(1675,Slappy_3_2f_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2e_6b_2
begin
Reply(2690);
NOption(2691,Slappy_3_2e_6a_1,4);
NOption(2481,Slappy_3_2e_5a,4);
NOption(1675,Slappy_3_2f_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2f_1
begin
Reply(2720);
NOption(2721,Slappy_3_2f_2a,4);
NOption(2722,Slappy_3_2f_2b_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2f_2a
begin
Reply(2750);
NOption(2722,Slappy_3_2f_2b_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

procedure Slappy_3_2f_2b_1
begin
Reply(2780);
if (local_var(LVAR_Slappy_Angela_Maybe)==0) then
BOption(2781,Slappy_3_2f_2b_2B,4);
if (local_var(LVAR_Slappy_Angela_Maybe)==0) then
GOption(2782,Slappy_3_2f_2b_2G,4);
if (obj_is_carrying_obj_pid(dude_obj,PID_LAVANDER_FLOWER)>0) then
NOption(2783,Slappy_3_2e_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

// Node Slappy_3_2f_2b_2B
//
// Notes:
//
// Tiny karma penalty for the PC. Increment the local variable Slappy_Angela_Maybe by 1.

procedure Slappy_3_2f_2b_2B
begin
   inc_local_var_amt(LVAR_Slappy_Angela_Maybe, 1);
   dec_general_rep(1);
Reply(2810);
NOption(2811,Slappy_3_2e_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

// Node Slappy_3_2f_2b_2G
//
// Notes:
//
// Tiny karma boost for the PC. Increment the local variable Slappy_Angela_Maybe by 1.

procedure Slappy_3_2f_2b_2G
begin
   inc_local_var_amt(LVAR_Slappy_Angela_Maybe, 1);
   inc_general_rep(1);
Reply(2840);
NOption(2811,Slappy_3_2e_1,4);
NOption(1793,Slappy_3_1,4);
NOption(1676,Slappy_9,4);
end

// Node Slappy_4_1
//
// Notes:
//
// The Slappy_4_* path is where the PC can ask about the jukebox and get the 'Fix the jukebox' quest.

procedure Slappy_4_1
begin
Reply(2870);
NOption(2871,Slappy_4_2a,4);
NOption(2872,Slappy_4_2b_1,4);
NOption(2873,Slappy_9,4);
NOption(864,Node999,4);
NOption(2874,Slappy_4_2a,-3);
NOption(2875,Slappy_4_2b_1,-3);
NOption(2876,Slappy_9,-3);
NOption(503,Node999,4);
end

procedure Slappy_4_2a
begin
Reply(2900);
NOption(2872,Slappy_4_2b_1,4);
NOption(2873,Slappy_9,4);
NOption(864,Node999,4);
NOption(2875,Slappy_4_2b_1,-3);
NOption(2901,Slappy_9,-3);
NOption(503,Node999,-3);
end

procedure Slappy_4_2b_1
begin
Reply(2930);
NOption(2931,Slappy_4_2b_2a,4);
NOption(2932,Slappy_4_2b_2b_a1,4);
NOption(2933,Slappy_4_2a,4);
NOption(2873,Slappy_9,4);
NOption(864,Node999,4);
NOption(mstr(2934)+dude_name+mstr(2935),Slappy_4_2b_2b_D1,-3);
NOption(2936,Slappy_4_2a,-3);
NOption(2937,Slappy_9,-3);
NOption(503,Node999,-3);
end

procedure Slappy_4_2b_2a
begin
Reply(2960);
NOption(2932,Slappy_4_2b_2b_a1,4);
NOption(2873,Slappy_9,4);
NOption(864,Node999,4);
end

procedure Slappy_4_2b_2b_a1
begin
Reply(2990);
NOption(2991,Slappy_4_2b_2b_a2,4);
NOption(2873,Slappy_9,4);
end

procedure Slappy_4_2b_2b_a2
begin
Reply(3020);
NOption(3021,Node999,4);
NOption(3022,Node999,4);
end

procedure Slappy_4_2b_2b_D1
begin
Reply(3050);
NOption(mstr(3051)+dude_name+mstr(3052),Slappy_4_2b_2b_D2,-3);
NOption(3053,Slappy_9,-3);
NOption(503,Node999,-3);
end

procedure Slappy_4_2b_2b_D2
begin
Reply(mstr(3080)+dude_name+mstr(3081));
NOption(mstr(712)+dude_name+mstr(3082),Slappy_4_2b_2b_D3,-3);
NOption(3053,Slappy_9,-3);
NOption(503,Node999,-3);
end

procedure Slappy_4_2b_2b_D3
begin
Reply(3110);
NOption(3053,Slappy_9,-3);
NOption(503,Node999,-3);
end

// Node Slappy_5_1
//
// Notes:
//
// The Slappy_5_* path is where the PC can sell records for the jukebox to Slappy, assuming he's found any.

procedure Slappy_5_1
begin
Reply(3140);
if(has_skill(dude_obj, SKILL_REPAIR) >= 50) then
NOption(3141,Slappy_5_2a_1a,4);
NOption(3142,Slappy_5_2b,4);
NOption(3143,Slappy_9,4);
end

procedure Slappy_5_2a_1a
begin
Reply(3170);
// NOTE: There should be a FtBaB between this and the following node.
NOption(3171,Slappy_5_2a_2,4);
NOption(3172,Slappy_9,4);
end

procedure Slappy_5_2a_1D
begin
Reply(3200);
NOption(3201,Slappy_5_2a_2,-3);
NOption(mstr(3202)+dude_name+mstr(3203),Slappy_9,-3);
end

procedure Slappy_5_2a_2
begin
Reply(3230);
NOption(1821,Slappy_5_2a_3,4);
NOption(1821,Slappy_5_2a_3,-3);
end

procedure Slappy_5_2a_3
begin
Reply(3260);
NOption(3261,Slappy_5_2a_4a,4);
NOption(3262,Slappy_5_2a_4b,4);
NOption(743,Slappy_5_2a_4a,-3);
NOption(3263,Slappy_5_2a_4b,-3);
end

// Node Slappy_5_2a_4a
//
// Notes:
//
// Remove one of the Warlitzer LP records from the PC's inventory and increment his caps by 300.

procedure Slappy_5_2a_4a
begin
   item_caps_adjust(dude_obj, 300);
Reply(3290);
NOption(3292,Slappy_9,4);
NOption(864,Node999,4);
NOption(3294,Slappy_9,-3);
NOption(503,Node999,-3);
end

procedure Slappy_5_2a_4b
begin
   inc_general_rep(10);
Reply(3320);
NOption(3321,Slappy_9,4);
NOption(864,Node999,4);
NOption(1344,Slappy_9,-3);
NOption(503,Node999,-3);
end

procedure Slappy_5_2b
begin
Reply(3350);
if(has_skill(dude_obj, SKILL_REPAIR) >= 50) then
NOption(3141,Slappy_5_2a_1a,4);
NOption(3143,Slappy_9,4);
end

// Node Slappy_6_1
//
// Notes:
//
// The Slappy_6_* path is where the PC can find out who owns the bar and a little about its history.

procedure Slappy_6_1
begin
Reply(3380);
NOption(3381,Slappy_6_2a_1,4);
if (local_var(LVAR_Slappy_Work_Alone)==0) then
NOption(3382,Slappy_6_2b_1,4);
if (local_var(LVAR_Slappy_Work_Alone)>0) then
NOption(3382,Slappy_6_2c,4);
NOption(3383,Slappy_9,4);
NOption(3384,Node999,4);
end

procedure Slappy_6_2a_1
begin
Reply(3410);
NOption(1821,Slappy_6_2a_2,4);
if (local_var(LVAR_Slappy_Work_Alone)==0) then
NOption(3382,Slappy_6_2b_1,4);
if (local_var(LVAR_Slappy_Work_Alone)>0) then
NOption(3382,Slappy_6_2c,4);
NOption(3383,Slappy_9,4);
NOption(3384,Node999,4);
end

procedure Slappy_6_2a_2
begin
Reply(3440);
if (local_var(LVAR_Slappy_Work_Alone)==0) then
NOption(3382,Slappy_6_2b_1,4);
if (local_var(LVAR_Slappy_Work_Alone)>0) then
NOption(3382,Slappy_6_2c,4);
NOption(3383,Slappy_9,4);
NOption(3384,Node999,4);
end

procedure Slappy_6_2b_1
begin
   inc_local_var_amt(LVAR_Slappy_Work_Alone, 1);
Reply(3470);
NOption(3471,Slappy_6_2b_2,4);
NOption(3381,Slappy_6_2a_1,4);
NOption(3383,Slappy_9,4);
NOption(3384,Node999,4);
end

procedure Slappy_6_2b_2
begin
Reply(3500);
NOption(3381,Slappy_6_2a_1,4);
NOption(3383,Slappy_9,4);
NOption(3384,Node999,4);
end

procedure Slappy_6_2c
begin
Reply(3530);
NOption(3531,Slappy_6_2b_2,4);
NOption(3381,Slappy_6_2a_1,4);
NOption(3383,Slappy_9,4);
NOption(3384,Node999,4);
end

procedure Slappy_9
begin
Reply(3560);
NOption(3561,Slappy_2_1,4);
// NOTE: This option will not appear if anyone other than Moses has been arrested for Angela's murder.
if (global_var(GVAR_ANGELA_DEAD)>0) then
NOption(652,Slappy_3_1,4);
if (global_var(GVAR_FIXED_FLOOR)==0) then
NOption(653,Slappy_4_1,4);
if (global_var(GVAR_FIXED_FLOOR)==1) then
NOption(654,Slappy_5_1,4);
NOption(655,Slappy_6_1,4);
NOption(656,Node999,4);
NOption(866,Slappy_2_1,-3);
if (global_var(GVAR_ANGELA_DEAD)>0) then
NOption(658,Slappy_3_1D_1,-3);
NOption(3562,Slappy_4_1,-3);
NOption(660,Slappy_5_2a_1D,-3);
NOption(503,Node999,-3);
end



//xxxxxxxxxxxxxxxxxxxx
