/*

        Name:           Stu
        Location:
        Description:    She is spiritually lost and the drugs have not eased her soul.
She has a strength of 5, which has come from her repair work. To successfully intimidate her requires a male to have a strength of 8 (or melee of 130)  and a female to have strength of 7 (or melee of 120). To successfully convince her requires a minimum speech skill of 77.

           Created: 07/10/2020 18:04:10

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_C /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBSTU

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure SC_001_Speech;

/*procedure Intimidation001_Male;
procedure Intimidation001_female;*/



// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure SpaceAndTime;
procedure Intro01;
procedure Intro02;
procedure Intro03;
procedure IKnowU;
procedure urJoking;
procedure notConvinced;
procedure NewTricks;
procedure Leave;
procedure noPeace;
procedure gonnaCry;
procedure IntimidationFirst00;
procedure IntimidationFirst01;
procedure IntimidationFirst02;
procedure IntimidationFirst03;
procedure IntimidationFirst04;
procedure GottaGo;
procedure gotSkills;
procedure tooGood;
procedure BeenConvinced;
procedure BeenBeaten;
procedure IntimidationFinal00;
procedure IntimidationFinal01;
procedure IntimidationFinal02;
procedure IntimidationFinal03;
procedure LeaveBeaten;
procedure LeaveFight;
procedure LeaveForever;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Been_Convinced (8)
#define LVAR_Been_Threatened (9)


/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
   add_timer_event(self_obj,game_ticks(random(1,5)),0);
   call new_plague_check(self_obj, LVAR_Herebefore);

   if(local_var(LVAR_Been_Threatened) == 2) then
      destroy_object(self_obj);

   if(not(obj_is_visible_flag(self_obj))) then
      set_obj_visibility(self_obj, 0);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude) and obj_is_visible_flag(self_obj)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;
       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;
if (local_var(LVAR_Herebefore)==0) then begin
       call Intro01;
end else if (local_var(LVAR_Herebefore)==1) then begin
         if(local_var(LVAR_Been_Threatened) == 1) then
            call BeenBeaten;
         else
            call IKnowU;
end
       gSay_End;
       end_dialogue;

   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin

   if (fixed_param == 0) then begin
      add_timer_event(self_obj,game_ticks(random(3, 5)),0);

      if (random(0, 30) == 1 and self_can_speak) then begin
            floater_high_rand(200, 204);
      end
   end

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_neutral_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

procedure SC_001_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, 65);
if is_success(roll_temp) then
begin
call Leave;
end
else begin
call notConvinced;
 end
end



procedure Intimidation001_Male begin
if (critter_skill_level(dude_obj,SKILL_MELEE) >= 120 OR
   is_success(do_check(dude_obj,STAT_st,7))) then
   begin
      call intimidationFirst00;
   end
else
   begin
      call urJoking;
   end


end

procedure Intimidation001_female begin
if (critter_skill_level(dude_obj,SKILL_MELEE) >= 120 OR
   is_success(do_check(dude_obj,STAT_st,6))) then
   begin
      call intimidationFirst04;
   end
else
   begin
      call urJoking;
   end


end



// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


// Node Intro01
//
// Notes:
//
// If PC has never met/spoken with NPC goto Intro01\

procedure Intro01
begin
if (dude_is_male) then Reply(230); else
if (dude_is_female) then Reply(231);
NOption(232,Intro02,4);
NOption(233,Intro02,4);
NOption(234,Intro02,4);
NOption(235,Intro02,-3);
NOption(236,Intro02,-3);
end

procedure Intro02
begin
Reply(260);
NOption(261,Intro03,4);
NOption(262,Intro03,1);
end

procedure Intro03
begin
Reply(290);
// NOTE: Set LVAR_Herebefore = 1
NOption(291,SC_001_Speech,4);
// NOTE: Set LVAR_Herebefore = 1
NOption(292,SC_001_Speech,-3);
// NOTE: Set LVAR_Herebefore = 1
//Success or failure of this dialog option depends upon the procedure.
//If success goto IntimidationFirst00
//Else goto urJoking
if (dude_is_male) then
NOption(293,Intimidation001_Male,4);
// NOTE: Set LVAR_Herebefore = 1
//Success or failure of this dialog option depends upon the procedure.
//If success goto IntimidationFirst00
//Else goto urJoking
if (dude_is_male) then
NOption(294,Intimidation001_Male,-3);
// NOTE: Set LVAR_Herebefore = 1
//
if (dude_is_female) then
NOption(295,IntimidationFirst00,4);
// NOTE: Set LVAR_Herebefore = 1
//
if (dude_is_female) then
NOption(296,IntimidationFirst00,-3);
// NOTE: Set LVAR_Herebefore = 1
//Set LVAR_BeenBeaten = 1
//PC does not have to kill NPC and can exit combat. NPC will not remember (does not remain hostile after encounter ends). Otherwise if NPC is killed rewarded -100 Karma
BOption(297,LeaveFight,4);
// NOTE: Set LVAR_Herebefore = 1
//Set LVAR_BeenBeaten = 1
//PC does not have to kill NPC and can exit combat. NPC will not remember (does not remain hostile after encounter ends). Otherwise if NPC is killed Pc is rewarded -100 Karma
BOption(298,LeaveFight,-3);
NOption(299,Node999,4);
NOption(300,Node999,-3);
end

// Node IKnowU
//
// Notes:
//
// If PC has never met/spoken with NPC goto Intro01\

procedure IKnowU
begin
if (dude_is_male) then Reply(320); else
if (dude_is_female) then Reply(321);
// NOTE: Set LVAR_Herebefore = 1
NOption(291,SC_001_Speech,4);
// NOTE: Set LVAR_Herebefore = 1
NOption(292,SC_001_Speech,-3);
// NOTE: Set LVAR_Herebefore = 1
//Success or failure of this dialog option depends upon the procedure.
//If success goto IntimidationFirst00
//Else goto urJoking
if (dude_is_male) then
NOption(293,Intimidation001_Male,4);
// NOTE: Set LVAR_Herebefore = 1
//Success or failure of this dialog option depends upon the procedure.
//If success goto IntimidationFirst00
//Else goto urJoking
if (dude_is_male) then
NOption(322,Intimidation001_Male,-3);
// NOTE: Set LVAR_Herebefore = 1
//
if (dude_is_female) then
NOption(323,IntimidationFirst00,4);
// NOTE: Set LVAR_Herebefore = 1
if (dude_is_female) then
NOption(296,IntimidationFirst00,-3);
// NOTE: Set LVAR_Herebefore = 1
//Set LVAR_BeenBeaten = 1
//PC does not have to kill NPC and can exit combat. NPC will not remember (does not remain hostile after encounter ends). Otherwise if NPC is killed rewarded -100 Karma
BOption(297,LeaveFight,4);
BOption(298,LeaveFight,-3);
// NOTE: Set LVAR_Herebefore = 1
NOption(324,Node999,4);
// NOTE: Set LVAR_Herebefore = 1
NOption(300,Node999,-3);
end

procedure urJoking
begin
if (dude_is_male) then Reply(350); else
if (dude_is_female) then Reply(351);
if (dude_is_male) then
NOption(352,Node999,4);
if (dude_is_female) then
NOption(353,Node999,4);
end

procedure notConvinced
begin
Reply(380);
NOption(381,Node999,4);
end

procedure NewTricks
begin
if (dude_is_male) then Reply(410); else
if (dude_is_female) then Reply(411);
if (dude_is_male) then
BOption(412,Node999,4);
if (dude_is_female) then
BOption(413,Node999,4);
end

procedure Leave
begin
Reply(440);
NOption(441,noPeace,4);
if (dude_is_male) then
NOption(442,IntimidationFirst01,4);
if (dude_is_female) then
NOption(443,Intro01,4);
end

procedure noPeace
begin
Reply(470);
NOption(471,gonnaCry,4);
NOption(472,gotSkills,4);
end

procedure gonnaCry
begin
Reply(500);
NOption(501,tooGood,4);
end

procedure IntimidationFirst00
begin
if (dude_is_male) then Reply(530); else
if (dude_is_female) then Reply(531);
if (dude_is_male) then
BOption(532,IntimidationFirst01,4);
if (dude_is_male) then
BOption(533,IntimidationFirst01,-3);
if (dude_is_female) then
NOption(534,IntimidationFirst01,4);
if (dude_is_female) then
NOption(535,IntimidationFirst01,-3);
end

procedure IntimidationFirst01
begin
if (dude_is_male) then Reply(560); else
if (dude_is_female) then Reply(561);
if (dude_is_male) then
BOption(562,IntimidationFirst02,4);
if (dude_is_female) then
NOption(563,IntimidationFirst02,4);
if (dude_is_female) then
NOption(564,IntimidationFirst02,-3);
NOption(951,Node999,1);
end

procedure IntimidationFirst02
begin
if (dude_is_male) then Reply(590); else
if (dude_is_female) then Reply(591);
if (dude_is_male) then
BOption(592,IntimidationFirst03,4);
if (dude_is_female) then
NOption(593,IntimidationFirst03,4);
if (dude_is_female) then
BOption(594,IntimidationFirst03,-3);
NOption(951,Node999,1);
end

procedure IntimidationFirst03
begin
if (dude_is_male) then Reply(620); else
if (dude_is_female) then Reply(621);
// NOTE: Set Lvar Been_Beaten = 1.
//Fade out and NPC is gone.
BOption(622,LeaveBeaten,1);
// NOTE: Success or failure of this dialog option depends upon the procedure.
//If success goto IntimidationFirst04
//Else goto urJoking
if (dude_is_female) then
BOption(623,Intimidation001_female,1);
NOption(951,Node999,1);
end

procedure IntimidationFirst04
begin
Reply(651);
// NOTE: Set Lvar Been_Beaten = 1.
//Fade out and NPC is gone.
BOption(652,LeaveBeaten,1);
end

procedure GottaGo
begin
Reply(680);
// NOTE: Set local var. Been_Beaten
BOption(681,LeaveBeaten,4);
// NOTE: Set local var. Been_Beaten
BOption(682,LeaveBeaten,4);
end

procedure gotSkills
begin
Reply(710);
NOption(711,Node999,4);
end

procedure tooGood
begin
Reply(740);
NOption(711,Node999,4);
end

// Node BeenConvinced
//
// Notes:
//
// If PC has never met/spoken with NPC goto Intro01\

procedure BeenConvinced
begin
Reply(770);
NOption(711,Node999,4);
end

// Node BeenBeaten
//
// Notes:
//
// If PC has never met/spoken with NPC goto Intro01\

procedure BeenBeaten
begin
if (dude_is_male) then Reply(800); else
if (dude_is_female) then Reply(561);
// NOTE: This option must NOT be offered if the PC meets the successful intimidation conditions
if(get_critter_stat(dude_obj, STAT_st) < 8 OR has_skill(dude_obj, SKILL_MELEE) < 130) then begin
if (dude_is_male) then
BOption(801,NewTricks,4);
end
// NOTE: This option must NOT be offered if the PC meets the successful intimidation conditions
if(get_critter_stat(dude_obj, STAT_st) < 7 OR has_skill(dude_obj, SKILL_MELEE) < 120) then begin
if (dude_is_female) then
BOption(802,NewTricks,4);
end
// NOTE: This option is ONLY offered if the PC meets the successful intimidation conditions
if(get_critter_stat(dude_obj, STAT_st) >= 8 OR has_skill(dude_obj, SKILL_MELEE) >= 130) then begin
if (dude_is_male) then
BOption(803,IntimidationFinal00,4);
end
// NOTE: This option is ONLY offered if the PC meets the successful intimidation conditions
if(get_critter_stat(dude_obj, STAT_st) >= 8 OR has_skill(dude_obj, SKILL_MELEE) >= 130) then begin
if (dude_is_male) then
NOption(804,IntimidationFinal00,-3);
end
// NOTE: This option is ONLY offered if the PC meets the successful intimidation conditions
if(get_critter_stat(dude_obj, STAT_st) >= 7 OR has_skill(dude_obj, SKILL_MELEE) >= 120) then begin
if (dude_is_female) then
BOption(805,IntimidationFinal00,4);
end
// NOTE: This option is ONLY offered if the PC meets the successful intimidation conditions
if(get_critter_stat(dude_obj, STAT_st) >= 7 OR has_skill(dude_obj, SKILL_MELEE) >= 120) then begin
if (dude_is_female) then
BOption(806,IntimidationFinal00,-3);
end
end

procedure IntimidationFinal00
begin
if (dude_is_male) then Reply(830); else
if (dude_is_female) then Reply(831);
if (dude_is_male) then
BOption(832,IntimidationFinal01,4);
if (dude_is_female) then
BOption(833,IntimidationFinal01,4);
NOption(951,Node999,1);
end

procedure IntimidationFinal01
begin
if (dude_is_male) then begin
   dec_general_rep(1);
   dec_tibbets_rep(-1);
   Reply(860);
end else if (dude_is_female) then begin
   Reply(861);
end
// NOTE: Fade out? The NPC is now gone for good.
if (dude_is_male) then
BOption(862,LeaveForever,4);
// NOTE: Fade out? The NPC is now gone for good.
if (dude_is_male) then
BOption(863,LeaveForever,-3);
if (dude_is_female) then
BOption(864,IntimidationFinal02,4);
NOption(951,Node999,1);
end

procedure IntimidationFinal02
begin
Reply(891);
BOption(892,IntimidationFinal03,4);
NOption(951,Node999,1);
end

procedure IntimidationFinal03
begin
Reply(950);
NOption(711,Node999,4);
end

procedure LeaveBeaten begin
   call Node999;
   fadeout(1);
   set_obj_visibility(self_obj, 1);
   set_local_var(LVAR_Been_Threatened, 1);
   fadein(1);
end

procedure LeaveFight begin
   call Node998;
   set_local_var(LVAR_Been_Threatened, 1);
end

procedure LeaveForever begin
   call LeaveBeaten;
   set_local_var(LVAR_Been_Threatened, 2);
   give_xp(200);
   inc_tibbets_rep(10);
   display_mstr(150);
end


//xxxxxxxxxxxxxxxxxxxx
