/*

        Name:           Kid
        Location:       Tibbets
        Description:    Thief

           Created: 16/07/2020 21:07:47

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBSYD

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;

procedure DuckandCover;
procedure GiveKey;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Gave_Key                   (8)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
call new_plague_check(self_obj, LVAR_Herebefore);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and self_can_see_dude) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
       return;
   end

   if(global_var(GVAR_TIBBETS_BATTALION_ATTACK) == 1) then begin
      reg_anim_begin();
      reg_anim_animate(self_obj, ANIM_fall_front, -1);
      reg_anim_end();
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

   if(global_var(GVAR_TIBBETS_BATTALION_ATTACK) == 1) then begin
      floater_bad(105);
      return;
   end

call set_idiot_savant_int;

if (local_var(LVAR_Herebefore)==0) then begin
       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;
       call Node001;
       gSay_End;
       end_dialogue;
end else if (local_var(LVAR_Herebefore)==1) then begin
       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;
       call Node009;
       gSay_End;
       end_dialogue;
end
call restore_idiot_savant_int;
end

procedure timed_event_p_proc begin
   if(fixed_param == 1) then begin
      reg_anim_begin();
      reg_anim_animate(self_obj, ANIM_prone_to_standing, -1);
      reg_anim_end();
   end
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
if (dude_is_male) then Reply(200); else
if (dude_is_female) then Reply(201);
NOption(mstr(202)+dude_name+mstr(203),Node002,4);
if(has_fake_trait(TRAIT_big_liar)) then
NOption(204,Node003,4);
NOption(205,Node005,4);
NOption(206,Node006,4);
NOption(mstr(207)+dude_name+mstr(208),Node002,-3);
if(not(has_fake_trait(TRAIT_pacifist))) then
NOption(209,Node005,1);
NOption(210,Node005,4);
NOption(211,Node999,4);
NOption(212,Node999,-3);
end

procedure Node002
begin
Reply(230);
NOption(231,Node003,4);
NOption(206,Node006,4);
NOption(232,Node005,4);
NOption(233,Node003,-3);
NOption(234,Node006,-3);
NOption(235,Node999,-3);
end

procedure Node003
begin
Reply(260);
NOption(261,Node004,4);
NOption(262,DuckandCover,1);
NOption(206,Node006,4);
NOption(263,Node004,-3);
NOption(234,Node006,-3);
end

procedure Node004
begin
Reply(290);
NOption(291,GiveKey,4);
NOption(292,Node999,4);
NOption(293,GiveKey,-3);
NOption(294,Node999,-3);
end

procedure Node005
begin
Reply(320);
NOption(321,Node999,4);
if(not(has_fake_trait(TRAIT_pacifist))) then
BOption(322,Node998,4);
NOption(323,Node999,1);
if(not(has_fake_trait(TRAIT_pacifist))) then
BOption(324,Node998,-3);
end

procedure Node006
begin
Reply(350);
NOption(351,Node007,4);
NOption(352,Node008,4);
NOption(353,Node002,4);
NOption(mstr(354)+dude_name+mstr(355),Node999,4);
NOption(356,Node999,4);
NOption(357,Node007,-3);
NOption(358,Node008,-3);
NOption(359,Node999,-3);
end

procedure Node007
begin
Reply(380);
NOption(381,Node003,4);
NOption(382,Node999,4);
NOption(383,Node010,-3);
NOption(384,Node999,-3);
end

procedure Node008
begin
Reply(410);
NOption(351,Node007,4);
NOption(411,Node002,4);
NOption(412,Node999,4);
NOption(357,Node007,-3);
NOption(413,Node002,-3);
NOption(414,Node999,-3);
end

procedure Node009
begin
if (dude_is_male) then Reply(440); else
if (dude_is_female) then Reply(441);
NOption(442,Node002,4);
NOption(443,Node003,4);
NOption(205,Node005,4);
NOption(206,Node006,4);
NOption(444,Node002,-3);
NOption(209,Node005,1);
NOption(445,Node005,4);
NOption(211,Node999,4);
NOption(212,Node999,-3);
end

procedure Node010
begin
Reply(470);
NOption(471,Node999,-3);
NOption(472,Node003,-3);
end

procedure DuckandCover begin
   floater_good(105);
   reg_anim_begin();
   reg_anim_animate(self_obj, ANIM_fall_front, -1);
   reg_anim_end();

   add_timer_event(self_obj, game_ticks(6), 1);
end

procedure GiveKey begin
   call Node999;
   fadeout(3);
   game_time_advance(ONE_GAME_MINUTE * 20);
   fadein(3);

   if(local_var(LVAR_Gave_Key) == 1) then begin
      floater_sad(107);
      return;
   end else begin
      floater_good(106);
      give_pid_qty(dude_obj, PID_WCD_KEYCARD, 1)
      set_local_var(LVAR_Gave_Key, 1);
   end
end

//xxxxxxxxxxxxxxxxxxxx
