#include "..\headers\define.h"

#define NAME                    SCRIPT_TBV8COMP


#include "..\headers\command.h"

procedure start;
procedure description_p_proc;
procedure use_p_proc;
procedure use_skill_on_p_proc;

import variable vault_door_ptr;

procedure start begin
   if (script_action == description_proc) then begin
      call description_p_proc();
   end
   else begin
      if (script_action == use_proc) then begin
         call use_p_proc();
      end else if(script_action == use_skill_on_proc) then begin
         call use_skill_on_p_proc;
      end
   end
end

procedure description_p_proc begin
   display_mstr(101);
end

procedure use_p_proc begin
   script_overrides;
   if (not(obj_is_open(vault_door_ptr))) then begin
      use_obj(vault_door_ptr);
if (source_obj == dude_obj) then begin
         play_sfx("SLDOORSO");
      end

   end
end

procedure use_skill_on_p_proc begin
   if (action_being_used == SKILL_REPAIR) then begin
      display_mstr(102);
      floater_bad(100);
   end
end
