#include "..\headers\define.h"

#define NAME SCRIPT_TBV8RADI

#include "..\headers\command.h"
#include "..\headers\vault8.h"

procedure start;
procedure use_p_proc;

#define LVAR_Herebefore                 (4)


procedure start begin
end

procedure use_p_proc begin
   script_overrides;
   if(local_var(LVAR_Herebefore) == 0) then begin
       set_map_music(cur_map_index, "wellmeet");
       set_local_var(LVAR_Herebefore, 1);
       display_mstr(203);
       if(dude_is_stupid or dude_is_idiot_savant) then begin
           obj_floater_type(dude_obj, mstr(200), FLOAT_COLOR_BAD);
       end else begin
           obj_floater_type(dude_obj, mstr(201), FLOAT_COLOR_BAD);
       end
   end else begin
       fadeout(1);
       give_xp(500);
       display_mstr(202);
       load_map("tbcb13", 0);
   end
end
