/*

        Name:           Wastebot
        Location:
        Description:

           Created: 20.8.2023. 18:02:48

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBWASTEB

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure RepairBot;
procedure ShovelCrap;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Crap_Shoveled              (8)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_ROBOTS);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_REPAIR_BOT);
   //add_timer_event(self_obj,game_ticks(random(1,5)),0);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;
       call Node001;
       gSay_End;
       end_dialogue;

   call restore_idiot_savant_int;
end

procedure timed_event_p_proc begin

  /* if ((not(combat_is_initialized)) and ((critter_state(self_obj) bwand DAM_KNOCKED_OUT) == FALSE) and (random(1,2) == 1)) then begin
         reg_anim_clear(self_obj);
         reg_anim_begin();
            animate_move_to_tile(tile_num_in_direction(tile_num(self_obj),random(0,5),random(1,3)));
         reg_anim_end();
      end
      add_timer_event(self_obj,game_ticks(random(3,5)),0);*/
   end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_neutral_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   if (action_being_used == SKILL_SCIENCE) then begin
      script_overrides;

      if(skill_success(source_obj, SKILL_SCIENCE, -20)) then begin
         display_mstr(150);
      end else begin
         display_msg(mstr_skill(602));
      end
   end

   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
Reply(200);
NOption(201,Node002,4);
NOption(202,Node011,4);
NOption(203,Node999,4);
NOption(204,Node002,-3);
NOption(205,Node011,-3);
NOption(206,Node999,-3);
end

procedure Node002
begin
Reply(230);
NOption(231,Node003,4);
NOption(232,Node007,4);
NOption(233,Node004,4);
NOption(234,Node999,4);
NOption(235,Node003,-3);
NOption(236,Node007,-3);
NOption(237,Node004,-3);
NOption(238,Node999,-3);
end

procedure Node003
begin
Reply(260);
NOption(233,Node004,4);
NOption(237,Node004,-3);
end

procedure Node004
begin
Reply(290);
NOption(291,Node005,4);
NOption(292,Node009,4);
NOption(293,Node999,4);
NOption(294,Node005,-3);
NOption(295,Node009,-3);
NOption(296,Node999,-3);
end

procedure Node005
begin
Reply(320);
NOption(321,Node006,4);
NOption(322,Node006,-3);
end

procedure Node006
begin
Reply(350);
NOption(351,RepairBot,4);
NOption(352,RepairBot,-3);
end

procedure Node007
begin
Reply(380);
NOption(381,Node008,4);
NOption(382,Node008,-3);
end

procedure Node008
begin
Reply(410);
NOption(411,Node009,4);
NOption(412,Node999,4);
NOption(413,Node009,-3);
NOption(414,Node999,-3);
end

procedure Node009
begin
Reply(440);
NOption(441,Node010,4);
NOption(442,Node010,-3);
end

procedure Node010
begin
Reply(470);
NOption(471,ShovelCrap,4);
NOption(472,ShovelCrap,-3);
end

procedure Node011
begin
Reply(500);
NOption(501,Node002,4);
NOption(502,Node999,4);
NOption(503,Node002,-3);
NOption(504,Node999,-3);
end

procedure RepairBot begin
   fadeout(1);
   game_time_advance(ONE_GAME_DAY * random(2, 4));

   if(skill_success(dude_obj, SKILL_REPAIR, -50)) then begin
      display_mstr(151);
      if (dude_is_stupid) then begin
         give_pid_qty(dude_obj, PID_BOTTLE_CAPS, 10)
      end
      else begin
         give_pid_qty(dude_obj, PID_BOTTLE_CAPS, 20)
      end
   end else begin
      display_mstr(152);
   end

   fadein(1);
   call Node999;
end

procedure ShovelCrap begin
   fadeout(1);
   game_time_advance(ONE_GAME_DAY);

   inc_local_var( LVAR_Crap_Shoveled );
   if (dude_is_stupid) then begin
      give_pid_qty(dude_obj, PID_BOTTLE_CAPS, 2)
   end
   else begin
      give_pid_qty(dude_obj, PID_BOTTLE_CAPS, 5)
   end

   if( local_var( LVAR_Crap_Shoveled ) == 5 ) then begin
      display_mstr(105);
      give_xp( EXP_SHOVELED_ALL_CRAP );
      inc_tibbets_rep(REP_TOWN_SHOVELED_ALL_CRAP);
      critter_add_trait(dude_obj, TRAIT_PERK, PERK_expert_excrement_expediter_perk, 1);
   end

   fadein(1);
   call Node999;
end

//xxxxxxxxxxxxxxxxxxxx
