/*

        Name:           Welcoming Committee Director
        Location:       Tibbets
        Description:    Welcoming Committee Director in Tibbets

           Created: 05/07/2020 16:55:45

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"

#define NAME                    SCRIPT_TBWCD

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\Party.h"
#include "..\HEADERS\tbcb13.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004a;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure destroy_ff;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_PlayerSetup                (8)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;
variable ff;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_ROBOTS);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_REPAIR_BOT);

   if(global_var(GVAR_TIBBETS_BATTALION_ATTACK) > 0) then begin
      set_obj_visibility(self_obj, 1);
   end else begin
      set_obj_visibility(self_obj, 0);
   end

   if((local_var(LVAR_PlayerSetup) == 1) and (map_var(MVAR_CellIntro) == 2)) then begin
      set_local_var(LVAR_PlayerSetup, 2);
      set_obj_visibility(self_obj, 0);
      call destroy_ff;
   end
   else begin
      set_obj_visibility(self_obj, 1);
   end

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

   // This code HAS to run from critter_p_proc
   if(local_var(LVAR_PlayerSetup) == 0) then begin

      if(dude_is_super_mutant) then begin
         display_msg(g_mstr(613));

         set_pc_extra_stat(STAT_max_hp, get_pc_extra_stat(STAT_max_hp) + 10);
         set_pc_extra_stat(STAT_melee_dmg, get_pc_extra_stat(STAT_melee_dmg) + 1);

         call set_dude_attr(STAT_st, get_dude_attr(STAT_st) + 3);
         call set_dude_attr(STAT_en, get_dude_attr(STAT_en) + 2);
         call set_dude_attr(STAT_ch, get_dude_attr(STAT_ch) - 2);
         call set_dude_attr(STAT_iq, get_dude_attr(STAT_iq) - 2);
         call set_dude_attr(STAT_ag, get_dude_attr(STAT_ag) - 2);

         set_pc_base_stat(STAT_dmg_resist, get_pc_base_stat(STAT_dmg_resist) + 25);
         set_pc_extra_stat(STAT_rad_resist, get_pc_extra_stat(STAT_rad_resist) + 100);
         set_pc_extra_stat(STAT_poison_resist, get_pc_extra_stat(STAT_poison_resist) + 20);

         set_perk_freq(4 + has_trait(TRAIT_TRAIT, dude_obj, TRAIT_skilled));

      end
      else if(dude_is_ghoul) then begin
         display_msg(g_mstr(614));

         set_pc_extra_stat(STAT_max_hp, get_pc_extra_stat(STAT_max_hp) - 5);

         call set_dude_attr(STAT_st, get_dude_attr(STAT_st) - 2);
         call set_dude_attr(STAT_pe, get_dude_attr(STAT_pe) + 3);
         call set_dude_attr(STAT_iq, get_dude_attr(STAT_iq) + 3);
         call set_dude_attr(STAT_ag, get_dude_attr(STAT_ag) - 4);
         call set_dude_attr(STAT_lu, get_dude_attr(STAT_lu) + 3);

         set_pc_extra_stat(STAT_rad_resist, get_pc_extra_stat(STAT_rad_resist) + 100);
         set_pc_extra_stat(STAT_poison_resist, get_pc_extra_stat(STAT_poison_resist) + 10);

         set_perk_freq(4 + has_trait(TRAIT_TRAIT, dude_obj, TRAIT_skilled));
      end

      call HealParty;
      set_local_var(LVAR_PlayerSetup, 1);
   end
   else if(local_var(LVAR_PlayerSetup) == 2) then begin
      set_map_var(MVAR_CellIntro, 3);
      set_local_var(LVAR_PlayerSetup, 3);
      display_msg(g_mstr(608));
      play_sfx("pipwake");
      // once again for good measure
      call destroy_ff;
   end

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and self_can_see_dude and obj_is_visible_flag(self_obj)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin
   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

   if (local_var(LVAR_Herebefore) == 1) then begin
      floater_rand(110,120);
   end
   else begin
      call set_idiot_savant_int;
       start_gdialog(NAME,self_obj,4,HEAD_WCD,BACKGROUND_ENCLAVE);
       gSay_Start;
       call Node001;
       gSay_End;
       end_dialogue;
       call restore_idiot_savant_int;
   end

end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_neutral_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   if (action_being_used == SKILL_SCIENCE) then begin
      script_overrides;

      if(skill_success(source_obj, SKILL_SCIENCE, -20)) then begin
         display_mstr(105);
      end else begin
         display_msg(mstr_skill(602));
      end
   end

   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);

      set_global_var(GVAR_QUEST_ATTEND_TRIAL, 1);

reg_anim_clear(self_obj);
reg_anim_begin();
reg_anim_obj_move_to_tile(self_obj, 12058, -1);
reg_anim_end();

end
end

// Skill checks and miscellaneous procedures


// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
Reply(200);
NOption(441,Node010,4);
NOption(201,Node003,4);
NOption(203,Node011,4);
NOption(204,Node002,4);
if (dude_is_male) then
   NOption(205,Node007,4);
if (dude_is_female) then
   NOption(206,Node007,4);
if(not(has_fake_trait(TRAIT_pacifist))) then
   BOption(207,Node998,4);
NOption(208,Node002,-3);
NOption(209,Node012,-3);
NOption(210,Node015,6);
if(not(has_fake_trait(TRAIT_pacifist))) then begin
   BOption(211,Node998,-3);
end
NOption(212,Node003,4);
end

procedure Node002
begin
Reply(230);
NOption(201,Node003,4);
NOption(772,Node013,4);
if(not(has_fake_trait(TRAIT_pacifist))) then
BOption(207,Node998,4);
NOption(231,Node020,4);
NOption(232,Node012,-3);
end

procedure Node003
begin
Reply(260);
NOption(261,Node008,4);
NOption(262,Node004,4);
NOption(263,Node005,4);
NOption(264,Node007,-3);
NOption(265,Node004a,4);
end

procedure Node004a begin
Reply(280);
NOption(281,Node004,4);
end


procedure Node004
begin
Reply(290);
NOption(291,Node016,4);
end

procedure Node005
begin
Reply(320);
NOption(321,Node006,4);
NOption(322,Node020,-3);
end

procedure Node006
begin
Reply(350);
NOption(351,Node009,4);
NOption(352,Node010,4);
NOption(353,Node020,-3);
end

procedure Node007
begin
Reply(380);
NOption(381,Node010,4);
NOption(382,Node020,4);
NOption(383,Node020,-3);
NOption(384,Node009,-3);
NOption(385,Node028,4);
NOption(386,Node028,-3);
end

procedure Node008
begin
Reply(410);
NOption(411,Node004,4);
NOption(412,Node004,-3);
NOption(413,Node009,4);
end

procedure Node009
begin
Reply(440);
NOption(441,Node010,4);
NOption(442,Node021,4);
NOption(443,Node012,-3);
if(not(has_fake_trait(TRAIT_pacifist))) then
BOption(444,Node998,4);
end

procedure Node010
begin
Reply(470);
NOption(471,Node022,4);
NOption(442,Node021,4);
NOption(443,Node012,-3);
NOption(472,Node020,4);
NOption(383,Node020,-3);
end

procedure Node011
begin
Reply(500);
NOption(501,Node018,4);
NOption(502,Node003,4);
NOption(503,Node020,4);
end

procedure Node012
begin
Reply(530);
NOption(531,Node999,-3);
NOption(532,Node999,-3);
end

procedure Node013
begin
Reply(560);
NOption(561,Node010,4);
NOption(562,Node014,4);
end

procedure Node014
begin
Reply(590);
NOption(591,Node010,4);
if(not(has_fake_trait(TRAIT_pacifist))) then
BOption(592,Node998,4);
NOption(593,Node021,4);
end

procedure Node015
begin
Reply(620);
NOption(291,Node003,4);
end

procedure Node016
begin
Reply(650);
NOption(651,Node017,4);
NOption(652,Node018,4);
NOption(653,Node024,4);
end

procedure Node017
begin
Reply(680);
NOption(681,Node003,4);
NOption(682,Node025,4);
NOption(683,Node021,4);
end

procedure Node018
begin
Reply(710);
NOption(711,Node019,6);
NOption(712,Node010,4);
NOption(713,Node004,4);
end

procedure Node019
begin
Reply(740);
NOption(741,Node003,4);
NOption(742,Node020,4);
NOption(743,Node021,4);
end

procedure Node020
begin
Reply(770);
NOption(771,Node003,4);
NOption(772,Node013,4);
NOption(773,Node002,4);
NOption(774,Node009,4);
NOption(775,Node010,4);
NOption(776,Node016,4);
NOption(777,Node021,4);
end

procedure Node021
begin
Reply(800);
NOption(801,Node999,4);
if(not(has_fake_trait(TRAIT_pacifist))) then
BOption(802,Node998,4);
NOption(803,Node999,-3);
NOption(804,Node999,4);
end

procedure Node022
begin
Reply(830);
NOption(831,Node020,4);
NOption(832,Node021,4);
NOption(833,Node009,4);
end

procedure Node024
begin
Reply(860);
NOption(861,Node021,4);
NOption(862,Node009,4);
NOption(863,Node020,4);
end

procedure Node025
begin
Reply(890);
NOption(891,Node026,4);
if (has_skill(dude_obj,SKILL_SCIENCE)>=50) then
NOption(892,Node026,4);
NOption(893,Node020,4);
end

procedure Node026
begin
Reply(920);
NOption(921,Node027,6);
NOption(893,Node020,4);
end

procedure Node027
begin

set_global_var(GVAR_QUEST_KNOW_CODE, 1);

Reply(950);
NOption(951,Node009,7);
NOption(952,Node010,4);
end

procedure Node028
begin

   if (global_var(GVAR_DUDE_VIRGIN) == 1) then begin
      up_sex_status;
   end

Reply(980);
NOption(382,Node020,4);
NOption(383,Node020,-3);
end

procedure destroy_ff begin
   ff = tile_contains_pid_obj(10314, self_elevation, PID_TIBBETS_FORCE_FIELD);
   if (ff != 0) then begin
      set_obj_visibility(ff, 1);
      destroy_object(ff);
   end
end

//xxxxxxxxxxxxxxxxxxxx
