/*

        Name:           Wiggie
        Location:
        Description:

           Created: 09/11/2020 09:14:15

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBWIGGIE

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure Skill_Check_000_Speech;
procedure Skill_Check_001_Speech;
procedure Skill_Check_002_Speech;
procedure Skill_Check_003_Speech;

procedure giveMoney;
procedure giveMoney2;



// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;
procedure Node999_go;
procedure Node999_follow;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Clark (8)
#define LVAR_Follow (9)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_WIGGIE);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
call new_plague_check(self_obj, LVAR_Herebefore);

   if((not(obj_is_visible_flag(self_obj))) or (local_var(LVAR_Follow) == -1)) then
      destroy_object(self_obj);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude) and obj_is_visible_flag(self_obj)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

   if(local_var(LVAR_Follow) == -1) and not(anim_busy(self_obj)) and not(combat_is_initialized) then
      Flee_From_Dude
end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;
       if(local_var(LVAR_Herebefore) == 0) then
          call Node002;
       else begin
          if(local_var(LVAR_Follow) == 1) then begin
             if(random(0,1) == 1) then
               call Node035;
             else
               call Node036;
          end
         else if(local_var(LVAR_Clark) == 1) then
            call Node037;
         else
            call Node038;
       end
       gSay_End;
       end_dialogue;


   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_neutral_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

procedure Skill_Check_000_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -2);
if is_success(roll_temp) then
begin
call Node004;
end
else begin
call Node006;
 end
end

procedure Skill_Check_001_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -5);
if is_success(roll_temp) then
begin
call Node020;
end
else begin
call Node021;
 end
end

procedure Skill_Check_002_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -7);
if is_success(roll_temp) then
begin
call Node030;
end
else begin
call Node021;
 end
end

procedure Skill_Check_003_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -10);
if is_success(roll_temp) then
begin
call Node031;
end
else begin
call Node027;
 end
end


procedure giveMoney begin
item_caps_adjust(dude_obj,1000);
call Node014;

end

procedure giveMoney2 begin
item_caps_adjust(dude_obj,1000);
call Node015;

end



// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE

procedure Node002
begin
Reply(230);
NOption(231,Node003,4);
NOption(232,Skill_Check_000_Speech,4);
NOption(233,Node999,4);
end

procedure Node003
begin
Reply(260);
NOption(261,Node999,4);
end

procedure Node004
begin
Reply(290);
NOption(291,Node005,4);
NOption(292,Node011,4);
NOption(293,Node012,4);
NOption(294,Node999,4);
end

procedure Node005
begin
Reply(320);
NOption(321,Node009,4);
NOption(322,Node010,4);
NOption(323,Node013,4);
end

// Node Node006
//
// Notes:
//
// Set LVAR_Clark := 1

procedure Node006
begin
   set_local_var(LVAR_Clark, 1);
Reply(350);
if (get_critter_stat(dude_obj,STAT_iq)>5) then
NOption(351,Node007,4);
NOption(352,Node008,4);
end

procedure Node007
begin
Reply(380);
BOption(381,Node998,4);
NOption(382,Node022,4);
NOption(383,Node023,4);
NOption(384,Node008,4);
end

procedure Node008
begin
Reply(410);
NOption(411,Node999,4);
end

procedure Node009
begin
Reply(440);
// NOTE: Start the reciting now
NOption(441,Node999,4);
end

procedure Node010
begin
Reply(470);
NOption(471,Node013,4);
BOption(472,Node998,4);
end

procedure Node011
begin
Reply(500);
NOption(501,Node018,4);
NOption(502,Node019,4);
end

procedure Node012
begin
Reply(530);
NOption(531,Skill_Check_001_Speech,4);
NOption(532,Node005,4);
end

procedure Node013
begin
Reply(560);
BOption(561,Node998,4);
// NOTE: Gives 1k caps to the PC
NOption(562,giveMoney,4);
end

procedure Node014
begin
Reply(590);
NOption(591,Node017,4);
NOption(592,giveMoney2,4);
end

procedure Node015
begin
Reply(620);
NOption(591,Node017,4);
BOption(621,Node998,4);
end

procedure Node016
begin
Reply(650);
NOption(651,Node017,4);
BOption(652,Node998,4);
end

// Node Node017
//
// Notes:
//
// Wiggie flees from the scene. Set variable GVAR_agnes_quest_1 := 2\

procedure Node017
begin
   set_local_var(LVAR_Follow, -1);
Reply(680);
NOption(261,Node999,4);
end

procedure Node018
begin
Reply(710);
NOption(711,Node024,4);
NOption(502,Node019,4);
end

procedure Node019
begin
Reply(740);
NOption(741,Node025,4);
NOption(742,Node010,4);
end

procedure Node020
begin
Reply(770);
NOption(771,Skill_Check_002_Speech,4);
end

procedure Node021
begin
Reply(800);
NOption(801,Node026,4);
end

procedure Node022
begin
Reply(830);
NOption(831,Skill_Check_003_Speech,4);
NOption(832,Node032,4);
end

procedure Node023
begin
Reply(860);
NOption(861,Node028,4);
// NOTE: Wiggie will walk away, and disappear. Set GVAR_agnes_quest_1 := 3
NOption(862,Node999_go,4);
end

procedure Node024
begin
Reply(890);
NOption(891,Node025,4);
BOption(892,Node998,4);
end

// Node Node025
//
// Notes:
//
// Wiggie runs away, off the map. Unless the PC attacks him, that is... If he makes it, set GVAR_agnes_quest_1 := 2

procedure Node025
begin
      set_local_var(LVAR_Follow, -1);

Reply(920);
NOption(921,Node999,4);
end

procedure Node026
begin
Reply(950);
BOption(951,Node998,4);
NOption(952,Node999,4);
end

procedure Node027
begin
Reply(980);
NOption(981,Node034,4);
end

procedure Node028
begin
Reply(1010);
BOption(1011,Node998,4);
NOption(1012,Node999,4);
end

procedure Node029
begin
Reply(1040);
NOption(1041,Node026,4);
NOption(1042,Node005,4);
end

// Node Node030
//
// Notes:
//
// Wiggie becomes a temporary follower. If the PC leaves LS and go to a new map, Wiggie will initiate dialogue immediately -> Node036

procedure Node030
begin
Reply(1070);
NOption(1071,Node999_follow,4);
end

// Node Node031
//
// Notes:
//
// set LVAR_clarkCable := 0;\

procedure Node031
begin
   set_local_var(LVAR_Clark, 0);
Reply(1100);
NOption(1101,Node999,4);
end

procedure Node032
begin
Reply(1130);
NOption(1131,Node033,4);
NOption(1132,Node999,4);
end

procedure Node033
begin
Reply(1160);
BOption(1161,Node998,4);
NOption(1162,Node999,4);
end

procedure Node034
begin
Reply(1190);
NOption(261,Node999,4);
end

procedure Node035
begin
Reply(1220);
// NOTE: Only available if the PC is on a LS map
BOption(1221,Node998,4);
NOption(1222,Node999,4);
end

// Node Node036
//
// Notes:
//
// This node is for if the PC leaves LS with Wiggie.

procedure Node036
begin
Reply(1250);
BOption(1251,Node998,4);
end

procedure Node037
begin
Reply(1280);
NOption(1281,Node034,4);
NOption(1282,Node008,4);
NOption(1283,Node999,4);
end

procedure Node038
begin
Reply(1310);
NOption(1311,Node010,4);
NOption(1312,Node999,4);
end

procedure Node999_go begin
   fadeout(1);
   set_obj_visibility(self_obj, 1);
   call Node999;
   fadein(1);
   give_xp(100);
end

procedure Node999_follow begin
   fadeout(1);
   set_local_var(LVAR_Follow, 1);
   critter_attempt_placement(dude_obj, 19161, 0);
   critter_attempt_placement(self_obj, 19161, 0);
   call Node999;
   fadein(1);
   give_xp(100);
end


//xxxxxxxxxxxxxxxxxxxx
