/*

        Name:           Zeph
        Location:
        Description:

           Created: 06/10/2020 19:47:46

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBZEPH

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure Skill_Check_000_Speech;




// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure switcher;
procedure start;
procedure startT;
procedure dontMakeMeLeave;
procedure leaving;
procedure likeRat;
procedure second;
procedure thanks;
procedure fear;
procedure ratOut;
procedure letStay;
procedure But;
procedure Leaving2;
procedure wontRatOut;
procedure ratTemple;
procedure spirit;
procedure special;
procedure ohWell;
procedure cool;
procedure Converted;
procedure dumped;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
call new_plague_check(self_obj, LVAR_Herebefore);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude) and obj_is_visible_flag(self_obj)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;

if (local_var(LVAR_Herebefore)==0) then begin
       call startT;
end else if (local_var(LVAR_Herebefore)==1) then begin
       call second;
end

       gSay_End;
       end_dialogue;

   call restore_idiot_savant_int;

   if(obj_is_visible_flag(self_obj) == false) then begin
      destroy_object(self_obj);
   end

end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

procedure Skill_Check_000_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -10);
if is_success(roll_temp) then
begin
call Ratout;
end
else begin
call WontRatOut;
 end
end





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


// Node start
//
// Notes:
//
// This is the first node of the dialogue.\

procedure startT
begin
Reply(230);
NOption(231,ratTemple,4);
NOption(232,Node999,4);
NOption(233,spirit,-3);
// NOTE: This is only visible after the quest to get ride of the wasters is taken.
NOption(234,special,-3);
end

// Node dontMakeMeLeave
//
// Notes:
//
// This is what Zeph says first once the PC starts chasing away the wasters.

procedure dontMakeMeLeave
begin
Reply(260);
NOption(261,leaving,4);
NOption(262,likeRat,4);
end

procedure leaving
begin

fadeout(1);
set_obj_visibility(self_obj, 1);
fadein(1);

Reply(290);
// NOTE: This is for when the PC forces Zeph to leave. If this node is called, she runs away after the dialogue ends.
NOption(291,Node999,4);
end

procedure likeRat
begin
Reply(320);
// NOTE: -1 karma
NOption(321,Leaving2,4);
NOption(322,leaving,4);
// NOTE: If the player selects this Zeph stays in place and can be used to point out Jotham later.
NOption(323,Node999,4);
end

// Node second
//
// Notes:
//
// This node is where the dialogue starts when it is appearant that the waster keep coming back.

procedure second
begin
Reply(350);
NOption(351,thanks,4);
NOption(352,fear,4);
NOption(353,Skill_Check_000_Speech,4);
NOption(354,Node999,4);
end

procedure thanks
begin
Reply(380);
NOption(381,Node999,4);
NOption(382,Node999,4);
NOption(383,Node999,4);
end

procedure fear
begin
Reply(410);
NOption(411,leaving,4);
NOption(412,Node999,4);
end

procedure ratOut
begin
Reply(440);
NOption(441,thanks,4);
NOption(442,But,4);
end

procedure letStay
begin
Reply(470);
NOption(471,Node999,1);
end

procedure But
begin
Reply(500);
NOption(501,thanks,4);
// NOTE: - 4 karma
NOption(502,Leaving2,4);
end

// Node Leaving2
//
// Notes:
//
// Zeph should run from the screen after this node is called.

procedure Leaving2
begin
if (dude_is_male) then Reply(530); else
if (dude_is_female) then Reply(531);
NOption(532,Node999,4);
end

procedure wontRatOut
begin
Reply(560);
// NOTE: Zeph runs from the screen once this is called.
NOption(561,Node999,4);
// NOTE: With this option the player can try to intimidate Zeph again but the difficulty should increase.
NOption(562,Node999,4);
end

procedure ratTemple
begin
Reply(590);
NOption(591,ohWell,4);
NOption(592,cool,4);
NOption(593,dumped,4);
// NOTE: This should only be visible after the player takes the get ride of the wasters quest.
NOption(594,dontMakeMeLeave,4);
end

procedure spirit
begin
Reply(620);
NOption(532,Node999,4);
end

procedure special
begin
Reply(650);
NOption(651,Converted,4);
end

procedure ohWell
begin
Reply(680);
NOption(532,Node999,4);
end

procedure cool
begin
Reply(710);
NOption(711,Node999,4);
end

procedure Converted
begin
Reply(740);
NOption(741,Node999,-3);
end

procedure dumped
begin
Reply(770);
NOption(771,Node999,4);
end



//xxxxxxxxxxxxxxxxxxxx
