#include "..\HEADERS\define.h"
#include "..\HEADERS\global.h"

procedure start;
procedure map_enter_p_proc;
procedure use_skill_on_p_proc;

procedure start begin
end

procedure map_enter_p_proc begin
    if(global_var(GVAR_QUEST_GET_RID_OF_CAESARS_LEGION) > 0) then begin
        set_obj_visibility(self_obj, 1);
        destroy_object(self_obj);
     end
end


/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
   procedure use_skill_on_p_proc begin
    if (
        (action_being_used == SKILL_SCIENCE)
    ) then begin
        script_overrides;
        display_msg(mstr_skill(random(512, 514)));
    end
 end
