/*

        Name:           FA Rocket Fuel tanks
        Location:
        Description:

           Created: 14.12.2023. 20:05:58

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_FAFUEL

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (0)

#include "..\HEADERS\command.h"

/* Standard Script Procedures */
procedure start;
procedure description_p_proc;

/* User defined variables */


procedure start begin
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
   set_global_var(GVAR_KNOW_FA_ROCKET_FUEL, 1);
end

//xxxxxxxxxxxxxxxxxxxx
