# Message file for b1crank.ssl
# Number of nodes: 2

{150}{}{This is a manual crank that is able to operate the outer door for every nuclear missile chamber. It can be used to open or close the door and then block or unblock it from remote control.}
{151}{}{It's not broken but you'll need a hand wheel to crank it.}
{152}{}{Trapping it would take too long.}

# Node001
{200}{}{[The manual crank requires a hand wheel.]}
{201}{}{[END]}

# Node002
{230}{}{What would you like to do with the nuclear missile's outer door? It is currently }
{231}{}{[Close it.]}
{232}{}{[Open it.]}
{233}{}{[Block it from remote control.]}
{234}{}{[Unblock it from remote control.]}
{235}{}{[Leave the door alone.]}
