# Message file for bhchagas.ssl
# Number of nodes: 10

{100}{}{You see a proud tribal warrior.}
{101}{}{You see Chagas.}
{102}{}{His skin is covered with tribal tattoos.}

# Node001
{200}{}{You aren't with the NCR, are you?}
{201}{}{No, I'm not. Just a wanderer. Name's }
{202}{}{. And you?}
{203}{}{And what if I am?}
{204}{}{Ensiar? Ummm...}

# Node002
{230}{}{Chagas. Brother of Ramon. You might have heard of him. Once a proud leader of the Blackfoots, before... everything went to hell.}
{231}{}{I see you have a Pip-Boy. A Lil-Pip 3000 model no less. Interesting.}
{232}{}{So what's this beef you have with the NCR?}

# Node003
{260}{}{Yes, a parting gift from Tibbets. Their robots have been on my tail. Couldn't get a moment's peace until I made it back home.}
{261}{}{Listen, Chagas. If you return to Tibbets, those robots will stop hunting you. There's this nasty, unstoppable robot ARGOS, in case you didn't know. However, if you hand over that Pip-Boy, maybe, just maybe, you can find a way to avoid their and the NCR's wrath. The desert's vast, but not vast enough to hide forever from both.}

# Node004
{290}{}{Ramon always told me to fight, to never surrender. But what's the use if I'm always running?}
{291}{}{There's honor in knowing when to fight and when to make a strategic move. Handing over the Pip-Boy could be that move. Live to fight another day, and maybe protect your tribe in the process.}
{292}{}{I've had enough of this negotiating. I'll just take it by force!}

# Node005
{320}{}{My tribe... I can't put them in harm's way.}
{321}{}{It's your choice, Chagas. Hand over the Pip-Boy, and save your tribe, free from the shadows of the NCR and Tibbets.}

# Node006
{350}{}{[After a deep breath, he unstraps the Pip-Boy and hands it over.] Maybe you're right. I'll do what Ramon would want me to do. Put the tribe before myself.}
{351}{}{Wise choice, Chagas. Ramon would be proud.}
{352}{}{Thanks, Chagas.}

# Node007
{380}{}{Hello again.}
{381}{}{Nothing, sorry to bother you.}
{382}{}{Chaka Chaka!}

# Node008
{410}{}{I was captured by the NCR but managed to escape.}
{411}{}{How did you manage to escape?}

# Node009
{440}{}{Escaping wasn't my doing. I was captured by some NCR guys during a raid on one of their caravans. While we were shooting at each other, the robots from Tibbets surrounded us. We didn't stand a chance. I lived but I wasn't unscathed; I got infected with something nasty. I think it was one of the caravan guys, he looked very ill. Been coughing all the time since then.}
{441}{}{That can't be good.}

# Node010
{470}{}{That's right. But that won't stop me from fighting for our tribe.}
{471}{}{Spoken like a true leader. Goodbye, Chagas.}

#Node020
{520}{}{I need some protective gear to survive out here. Can you sell me some?}
{521}{}{Sell you gear? I am not a vendor, for us Blackfoot it's something you have to make for yourself. It's a matter of hunter's pride. You know what i could teach you but knowledge isn't free . As you can see, this sickness has me grounded. There's a cave to the east clear them out to prove yourself, and I'll teach you the art of skinning geckos.}
{522}{}{Consider that East cave cleared. I'll be back.}
{523}{}{Sounds like too much work. Forget it.}
{524}{}{I've done it! They are all dead!}
{525}{}{Well look at that... you actually survived. A deal's a deal. Watch closely, you slice along the belly, avoid the scent glands, and peel it back in one smooth motion....[You learned how to skin gecko]}
{526}{}{[end]}
{527}{}{Where can i find the best hides ?}
{528}{}{Well, every hunter has their secret spot, i'll let you find your own, but i can point you in the right direction...[Chagas adds the location on your pipboy]}
{529}{}{Thank you, Chagas. Take care of yourself.}