# Message file for ecbndoge.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see a janitor.}
{101}{}{You see bandithedoge.}
{102}{}{This guy could be another janitor.}

# Node 0 [Floats]
{200}{}{Have you seen my copy of Now That's What I Call Music 2253 Edition: Dark Ambient Sounds of New California?}
{201}{}{... <burp> ... KURWA! ...}
{202}{}{God is dead and no one cares.}
{203}{}{Sorry Richard, didn't mean to rip you off so much.}
{204}{}{My hearing is augmented.}
{205}{}{Could you repeat that? All those transients have taken a toll on my ears, y'know.}
{206}{}{It's not too loud, you're just too old.}
{207}{}{My soul is written in C and my heart is a void pointer.}
{208}{}{Guys, how do I compute an arcsine?}
{209}{}{This mod is genius and here's why.}
{210}{}{Did you just speak to me in 128kbps?}
{211}{}{Sorry, the Fallout 2 word filter is holding me back.}
{212}{}{God, I love beer so much.}
{213}{}{Forgive me if my speech is unclear or absurd.}
