# Message file for ecgoatby.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see a janitor.}
{101}{}{You see Goat_Boy.}
{102}{}{This guy could be another janitor.}

# Node 0 [Floats]
{200}{}{So: a Croatian, some Americans, a Brit, a Polish man AND an Italian enter a bar...}
{201}{}{I'm so tired sheep are counting me...}
{202}{}{Need. More. Coffee.}
{203}{}{I hate my nickname but I'm stuck with it.}
{204}{}{I was gonna make unique sprites for all of us here but... too much work.}
{205}{}{Can I join your party? -- Actually, scratch that, too much walking.}
{206}{}{Do you know I play the flute on one of the tracks? My neighbors loved it.}
{207}{}{Sorry for making you short, Alexandra. I only realized that at the end...}
{208}{}{Look Mum, I made it! I'm a special encounter!}
{209}{}{By the Master, by the Master, by the Master! It's the Prisoner! I can't believe it's you, standing here next to me.}
{210}{}{If you HAVE to click me at least buy me drink first.}
{211}{}{I am a patient boy. I wait, I wait, I wait, I wait...}
{212}{}{I don't even like the Talking Heads.}
