{100}{}{You see an abandoned homebot.}
{101}{}{The robot seems domesticated.}
{102}{}{The dull metallic surface indicates prolonged sun exposure, possibly for centuries.}

{105}{}{This is an ancient, pre-war, default Mr. Handy model. Its chips and plating have badly deteriorated due to centuries of neglect.}

{200}{}{Can I help you?}
{201}{}{You want a slice of pie?}
{202}{}{Walking the dogs, all done! Sweeping the balcony, all done! Washing the dishes, all done!}
{203}{}{Please upgrade me. My memory chip is 4001 day overdue.}
{204}{}{Master, is that you?}
{205}{}{Where did everybody go?}
{206}{}{Have you seen my owner?}
{207}{}{I have no work. That makes me unhappy.}
{208}{}{Am I expired?}
{209}{}{I'm a newer model. You can tell that by the way I talk about myself - in first person.}
{210}{}{I think my antennae is broken. I can only pickup static.}
{211}{}{I can cook, clean, wash, polish, repair, spell, sing, listen and much more!}
{212}{}{*Bzzzzzzzt*}
{213}{}{*click*}
