{200}{}{I'll kick you until you die!}
{201}{}{I'll cut you to pieces!}
{202}{}{Ride with me!}
{203}{}{Start screaming like a lil' girl!}
{204}{}{Prepare to scream!}
{205}{}{Let's scream!}
{206}{}{You'll be prettier when you're dead.}
{207}{}{Pretty hair.}
{208}{}{Doc said I was homicidal!}
{209}{}{I like your socks!}
{210}{}{You'll be dancing on the blacktop!}
{211}{}{We'll speak later. After I detach your head.}
{212}{}{Your white neck drives me mad!}
{213}{}{Fresh blood!}
{214}{}{Nice eyes!}
{215}{}{Pretty legs!}
{216}{}{Nice feet!}
{217}{}{Pretty hands!}
