# Message file for tbprsn.ssl
# Number of nodes: 1

{100}{}{You see an escaped Tibbets' prisoner.}
{101}{}{You see somebody enjoying their newfound freedom.}
{102}{}{You see somebody wearing a familiar jumpsuit.}

# Node 0 [Floats]

{200}{}{I regret nothing.}
{201}{}{I'm a free person now!}
{202}{}{I killed my number!}
{203}{}{Busted!}
{204}{}{I'm not catching cold from you!}
{205}{}{This is a bang!}
{206}{}{Goose and Duck!}
{207}{}{The prison ain't my home!}
{208}{}{I'm not going back to the house!}
{209}{}{Hit it!}
{210}{}{Come on now - one heat wave was enough for me!}
{211}{}{I'm not a number!}
{212}{}{It was a bum beef!}
{213}{}{I'll never be bitched again!}
{214}{}{I served my one hundred-year bit!}
{215}{}{I shared a cell with someone nuts.}
{216}{}{I shared a cell with someone who called me Little Grace.}
{217}{}{I hate prison food.}
{218}{}{My cell was so small.}
{219}{}{I hate prisons.}
{220}{}{You'll never take me alive!}
{221}{}{Jail is history for me. Wasteland is my future!}
{222}{}{I'm not going back!}
{223}{}{They'll never get me!}
{224}{}{Fucking robots.}
{225}{}{Freedom!}
{226}{}{Fuck ODYSSEUS! I'll beat his tin can ass back to the assembly line.}
{227}{}{I'm innocent!}
{228}{}{Where are we?}
{229}{}{Give me freedom or give me death!}
{230}{}{I never asked for this!}
