{100}{}{You see a dirty, unshaven man.}
{200}{}{You see a dirty, haggard woman.}
{101}{}{Trapper.}
{102}{}{Best not get too close. Some of the critters in his clothes might be looking for a cleaner home.}
{103}{}{Howdy. Don't come across people too often out here in trapper country. Whatcha want?}
{104}{}{Do you have any mantis guts for sale?}
{105}{}{Just passing through.}
{106}{}{Ug.}
{107}{}{Well, I reckon I might be able to sell ya my guts. It'll save me the trouble of going into town.}
{108}{}{What do you have?}
{109}{}{Never mind.}
{110}{}{Ug.}
{111}{}{Here's what I got: }
{112}{}{ mantis guts.}
{114}{}{I'll take all you got.}
{115}{}{Maybe next time. Bye.}
{116}{}{Nice doing business with ya. See you around.}
{117}{}{Bye.}
{118}{}{Seems you're short on cash. How about you give me five minutes with yer woman. I'll make it worth your while.}
{119}{}{Seems you're short on cash. How bout give'n me 5 minutes with yer man. You know what I mean. I can give you guts in trade.}
{120}{}{Seems you're short on cash. Tell you what, I've been in these wastes for a LONG time, if you catch my drift. I'll make it worth your while.}
{121}{}{Sure.}
{122}{}{Not a chance. Bye.}
{123}{}{[Your wife will forgive you... eventually. But on the positive side, the trapper gave you some guts.]}
{124}{}{[Your husband seems no worse for wear after the experience.]}
{125}{}{[You feel dirty in more than one sense of the word - but you got some mantis guts.]}
{126}{}{Bye.}
{127}{}{[He holds up his right hand and says] How. Me mighty trapper. Hunt mantis. Me no mean trespass on your land. Leave peacefully. [He hands you a mantis guts as a gift.]}
{128}{}{[END]}
{129}{}{I've got no more business with you.}
{130}{}{Yellow bellied sapsucker!}
{131}{}{This is my hunting territory. Leave!}
{132}{}{I'll skin you alive!}
{133}{}{I'm gonna use your head as a trophy.}

{134}{}{One mantis guts: $}

{136}{}{OK, warden. You win.}
{137}{}{Lucky for you, I have to go check my traps.}
{138}{}{I think I hear Mom callin' me.}

{141}{}{Looks like I have }
{142}{}{Sorry, looks like I'm all out of stock.}
