# Grammar pass done

{100}{}{A traveler.}
{101}{}{Hail, fellow traveler.}
{102}{}{I'm in need of directions. Can you help me out?}
{103}{}{Where are you headed?}
{104}{}{What do you do?}
{105}{}{Ugh.}
{106}{}{Well... I don't know. I'm pretty new to this area and I've only been to the following areas:}
{107}{}{Dogtown}
{108}{}{Blackfoot}
{109}{}{Ouroboros}
{110}{}{The Reservation}
{111}{}{Jericho}
{112}{}{Hoover Dam}
{113}{}{An abandoned mine.}
{114}{}{No, I've been there already. Thanks anyway.}
{115}{}{Dogtown - now that's a great place to go if you're into pre-war exploration. Here, let me show you where it is.}
{116}{}{Thanks.}
{117}{}{Blackfoot - now that's a tribe of morons. Say something against slavery and they treat you like some kind of freak. Never been inside, but I know where it is.}
{118}{}{Thanks.}
{119}{}{Ouroboros... I don't know much about it, other than there's a cult run by a living goddess or something.}
{120}{}{Thanks.}
{121}{}{I'd stay away from the Reservation if I were you. It's a magnet for lowlifes of the area. I'll show you where it is, but I don't recommend you go there.}
{122}{}{Thanks.}
{123}{}{Jericho. Now there's a nice place. I'd like to settle down and live there someday. Clean, nice people, and very well maintained. It's located right here on your map.}
{124}{}{Thanks.}
{125}{}{Hoover Dam... A big place, run by the NCR. Too bad about the war though. It's located on a lake's coast.}
{126}{}{Thanks.}
{127}{}{Yeah, a while back I came across an abandoned mining camp. Thought I'd rest there a day or two, but then noticed minefield signs. A shame, too; it looks like the miners left in a hurry. They probably left a lot of stuff behind. I'm not planning to go back, so I guess it's all right if I show you where it is.}
{128}{}{Thanks.}
{129}{}{Oh... it doesn't really matter. I just decided to travel one day and, well, here I am.}
{130}{}{Maybe you can help me. I need some directions.}
{131}{}{What do you do?}
{132}{}{Nice talking to you.}
{133}{}{I do odd jobs here and there to get by. But mostly I just travel.}
{134}{}{Maybe you can help me. I need some directions.}
{135}{}{Where you headed?}
{136}{}{Nice talking to you.}
{137}{}{I really should be going now. It was nice talking to you.}
{138}{}{Maybe we'll meet again.}
{139}{}{I want to make the next town by nightfall. I'd better go.}
{140}{}{I'd be going.}
{141}{}{Ambush!}
{142}{}{Can't trust anyone these days.}
{143}{}{You have broken the code of the traveler.}
{144}{}{Time to go.}
{145}{}{I've overstayed my welcome.}
{146}{}{I must depart.}
