# Message file for fac10.ssl
# Number of nodes: 2
# Grammar pass done

{100}{}{You see a menacing figure, radiating an aura of authority.}
{101}{}{You see Chief-of-Ten, a commanding officer of Caesar's Legion.}
{102}{}{His prominent upper incisors give him a rat-like appearance.}

# Node001
{200}{}{Ave Caesar, and fuck this wretched place! We're departing from here!}
{201}{}{If you insist.}
{202}{}{Hold your tongue, slaver scum. You won't escape justice for the crimes you've inflicted upon the citizens of the New California Republic. I'm here to ensure you pay the price.}
{203}{}{Farewell.}
{204}{}{Me hurt you like you hurt others.}

# Node002
{230}{}{Ah, we have a hero among us! Let us dance, boy. I shall personally present your severed head to Caesar on a platter.}
{231}{}{Ah, we have a hero among us! Let us dance, girl. I shall personally present your severed head to Caesar on a platter.}
{232}{}{I will dance upon *your* grave, rest assured.}
{233}{}{Me dance on *your* grave.}
