# Message file for fapaula.ssl
# Number of nodes: 9
# Grammar pass done

{100}{}{You see the leader of the bounty hunters.}
{101}{}{You see Paula, the bounty hunter.}
{102}{}{She's trembling occasionally. Something's not right.}

# Node001
{200}{}{Well, well, what do we have here? Another fool tempting fate?}
{201}{}{I could say the same about you.}
{202}{}{Oops, wrong room.}

# Node002
{230}{}{I assume you're not with those Legion fools. Things are about to get pretty ugly for them soon.}
{231}{}{You're going to fight the Legion?}
{232}{}{Legi?}

# Node003
{260}{}{No need to worry - they're neck deep in a shit pool of their own making. I'm Paula, by the way. We're bounty hunters from Hoover Dam, tracking these fools all the way from the Grand Canyon.}
{261}{}{Tell me more.}
{262}{}{Why were you tracking them?}

# Node004
{290}{}{It's simple. The Desert Rangers pay us well to hunt down any slaver scum, especially Legion scouts who get too close to Hoover Dam. We may not be rangers, but we'll gladly take down anyone for a good bag of caps.}

# Node005
{320}{}{We've tracked them back to the Fort. It wasn't too hard, just followed their tire tracks across the desert. You can see for yourself the brutality and carnage these bastards are capable of, but...}
{321}{}{But what?}

# Node006
{350}{}{[Her voice trembles] But we just lost Ziggy while he was out in the park disabling their vehicles. Look at him, torn in two like a ragdoll. It seems we weren't the only ones stalking those fools back from their little trip to the Grand Canyon.}
{351}{}{What could have done that to Ziggy?}

# Node007
{380}{}{You've heard about the deathclaw, right? Big, fast, and deadly. Now imagine one, but this one you can't see. It's a chameleon deathclaw, native to the Grand Canyon. The Legion must have done something really bad to have one of these stalking them. Judging by the state Ziggy ended up in, it's completely pissed off. Maybe they killed its mate or destroyed its nest... I don't know, and I don't intend to find out!}
{381}{}{A chameleon deathclaw?}

# Node008
{410}{}{That's the nightmare we're dealing with here, or rather, running away from. We don't have the experience or equipment to handle it. We'll give Ziggy a quick burial and head back to Hoover Dam pronto. Everyone is getting more nervous with each passing moment.}
{411}{}{Well, thanks for the warning. And where are the Legionnaires now?}

# Node009
{440}{}{They're holed up on a small farm west of here. We've heard their mongrels barking nearby too... Everyone, we're getting ready to move out. Good luck, stranger.}
{441}{}{Thanks.}
{442}{}{Hold on a second, I couldn't help but notice your impressive equipment. Hand over everything you've got, or else!}
