# Message file for fddelma.ssl
# Number of nodes: 7

{100}{}{You see a gate guard.}
{101}{}{You see Delma, a gate guard of Fort Desolation.}
{102}{}{She seems friendly enough. NCR Army dog tags with the name "Delma" are dangling around her neck.}

{105}{}{Please holster your weapon.}
{106}{}{Please don't point your weapon at me!}
{107}{}{Why are you sneaking around? Cease your actions immediately!}
{108}{}{I warned you, fool!}
{109}{}{I suspect you're up to something!}
{110}{}{Tincans are back!}

# Node 0 [AlreadyTalked]
{200}{}{Good day.}
{201}{}{Hi.}
{202}{}{Hello.}
{203}{}{How are you?}
{204}{}{Nice to see you.}
{205}{}{Good evening.}

# Node001
{230}{}{Welcome to Fort Desolation, stranger!}
{231}{}{Welcome to Fort Desolation, sir!}
{232}{}{Uh, thanks.}
{233}{}{What's the deal with this place?}
{234}{}{Hnnnh!}
{235}{}{Welcome to Fort Desolation, ma'am!}
{236}{}{I'm sorry, but the Fort's gate is closed at night for security reasons.}

# Node002
{260}{}{We are a fortified outpost of the NCR, watching over the ruins of a pre-war city. We saw lots of action fighting the Brotherhood here who also has interest in them. They even detonated an experimental bomb on the north side, taking down our wall. But we've held on and pushed them back. It's mostly quiet these days.}
{261}{}{How do you survive out here?}
{262}{}{Who's your leader?}
{263}{}{You no longer have a northern wall?!}
{264}{}{Thanks. Goodbye.}

# Node003
{290}{}{We get everything from Hoover Dam. Water, food, clothes, ammo. The rookies are rotating between the forts, coming and going as needed. We also have a merchant here and a few citizens that help us. We all work and share together like a true community.}
{291}{}{Tell me again, what's the deal with this place?}

# Node004
{320}{}{NCR Rangers serve as our current leaders, using their veteran experience to lead the Fort forward.}
{321}{}{[Flash your NCR Ranger pin.]}

# Node005
{350}{}{Sir! It's an honor to have you with us. Sir!}
{351}{}{Ma'am! It's an honor to have you with us. Ma'am!}

# Node006
{380}{}{Oh, we do. We used our military train as a replacement for it. That old hunk of metal eats Micro Fusion Cells like a thunderbird going through a brahmin herd, so it's best used as-is.}
{381}{}{Good thinking. I have to go now.}
