# Message file for tbbatt.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You come across a soldier clad in unfamiliar advanced armor.}
{101}{}{You spot a soldier in an enigmatic suit of advanced armor, adorned with an unfamiliar insignia on the breastplate.}
{102}{}{The combat armor they're donning boasts impressive features like gas and radiation filtration, along with enhanced night vision goggles.}

{103}{}{HOLSTER YOUR WEAPON IMMEDIATELY!}
{104}{}{Stop sneaking around!}
{105}{}{I warned you, idiot!}
{106}{}{Your shadiness doesn't sit well with me!}

# Node 0 [Floats]
{200}{}{You! It's your kind that brought ruin upon this once great nation.}
{201}{}{You've been expected.}
{202}{}{Captain Davidson is a badass.}
{203}{}{Got a light? Oh, never mind. I've got one.}
{204}{}{Who the--? *zzzztt*}
{205}{}{Apologies, no time for idle talk.}
{206}{}{Have you met the General yet?}
{207}{}{*zzzztt*}
{208}{}{Nothing personal, but I don't trust your face.}
{209}{}{When in doubt, just empty the magazine.}
{210}{}{We're not known for our tidiness.}
{211}{}{You can never have too much ammo.}
{212}{}{Even smart bombs have their bad days.}
{213}{}{Nothing that an airstrike couldn't solve.}
{214}{}{*zzzztt* Copy, over. *zzzztt*}
