{100}{}{You see a huge, aged figure, his pale face weathered by time, with hair and beard that seem to have tales of their own.}
{101}{}{You see a man, perhaps in his early fifties, half-naked, half-clad in humble attire that speaks of simpler times.}
{102}{}{You see Billy-Bob, a trog Pappy.}

{104}{}{Come bak when ya've grown ayy brayn.}
{105}{}{You've exiled Billy-Bob from Hoover Dam and prevented a bloodshed.}
{106}{}{It seems your actions have triggered a civil war between NCR and the trogs.}

{200}{}{Hello there, waste-walkuurr. What are y'all a-doin' in my home? Ay hope you nahwt ayy thief aw anything.}
{201}{}{I'm just a traveler. Who are you?}
{202}{}{Actually, I'm a low-down, gun-toting bandit. Prepare to die!}
{203}{}{I'm just passing through. I'll be going now.}
{204}{}{Why are you spreading hate propaganda?}
{205}{}{I'm here for the NCR.}

{206}{}{Hey again, waste-walkuurr. What are ya a-doin' on my preymises? Is there something ya've fawgotten?}
{207}{}{I see I'm not welcome here. Goodbye.}
{208}{}{I'm killing you, effective NOW!}
{209}{}{I'm trying to ascertain the reason you have been spreading racist pamphlets.}
{210}{}{I'm trying to find out why you have been making racist fliers.}

{211}{}{Ay'm Billy-Bob. Ay'm ayy Pappy.}
{212}{}{A Pappy?}
{213}{}{Pleased to meet you. I've got to be going.}
{214}{}{The NCR is very concerned about you, Billy-Bob.}

{215}{}{Sho' thang, ah come from a mighty long line o' Pappies. Mah great-great-great-great-granddaddy, Bob Billy-Bob, he was a mighty big shot 'round Hoover Dam. 'Cept for him, them trogs mighta never made it outta them caves and into the Dam.}
{216}{}{You must take pride in such a genealogy. Goodbye.}
{217}{}{Impressive. So what do *you* do for a living?}
{218}{}{Why spread the hate propaganda?}

{219}{}{Whut? Naw! Ah ain't neva been mixed up in no kinda hate crime!}
{220}{}{That's not what the NCR folks have told me.}
{221}{}{Really? Then I must have been mistaken. Bye.}
{222}{}{I get tired of your whining. Just die already.}
{223}{}{The fliers I found in your room seem to contradict the previous statement.}

{224}{}{The waste-walkuurrs? What 'bout 'em?}
{225}{}{They told me that you're spreading hate propaganda against them.}
{226}{}{They've asked me to silence you.}
{227}{}{You tell me, Billy-Bob. What about them?}
{228}{}{Absolutely nothing. Bye.}

{229}{}{Alright then, reckon ya caught me. We been fixin' them fliers, no denyin' that.}
{230}{}{Why?}
{231}{}{Do you realize it's a crime?}
{232}{}{I knew it. Time to die, racist scum.}
{233}{}{Great. I'll just take this to the police, then.}
{234}{}{Well, I'm just here to tell you, that you won't be doing so any more. I've got your fliers and I'm taking them to the authorities.}

{235}{}{If y'all ain't got no concrete proof of any crime I'm supposed to have done, kindly quit botherin' me.}
{236}{}{Fine. Bye.}
{237}{}{Argh, I'll just kill you and be over with it!}
{238}{}{How're the fliers in your room for evidence?}

{239}{}{Ain't much left fer me to do now. Ay'd lend a hand of my own with them generators, but seems like they already got them "specialists."}
{240}{}{You seem to have a grudge against them.}
{241}{}{So, you wouldn't be spreading any racist fliers, would you?}
{242}{}{I'll just leave you to your idleness.}
{243}{}{What a waste of air you are. Time to die, scum.}
{1244}{}{W'all trogs now on Otto's NCR leash.}
{1245}{}{W'all trogs now on Dianne's NCR leash.}
{1246}{}{But they still can't get the output up, heh.}
{1247}{}{What do you mean by "they can't get the output up?"}

{244}{}{Ya reckon ya surprised? Hirin' a waste-walkuurr fer such a vital job.}
{245}{}{Are you troubled because Otto and his team aren't trogs?}

{246}{}{Dang straight Ay'am. It ain't right puttin' waste-walkuurrs in charge of nothin'. In fact, they shouldn't even have the same rights as trogs, not by a long shot. Ay done reckon them thar waste-walkers dug 'emselves inna qute a hole. Now their shovels done busted an' 'bout as useful as a pair o' teats onna hag snake.}
{247}{}{The folks were right. You must be the one spreading hate propaganda.}
{248}{}{I agree with you completely. What should be done about them?}
{249}{}{This is of no concern to me. Goodbye.}

{250}{}{Them waste-walkuurr ought to be rounded up into camps at the very least. Or 'liminated. Why, y'all might ask yerself? 'Cause my youngest girl, Mary-Jo, done gone and took a job with Dusty. It's bad 'nuff she's strayed from the safety of the earth's belly, but mixin' with them waste-walkuurrs, that's a whole 'nother concern.}
{251}{}{I'd stick with elimination. Shall I "take care" of the problem?}
{252}{}{Well, I'll just let the trogs do the rounding up. I'm too lazy or disinterested to do it myself.}
{253}{}{Figures out you are a murderous sicko after all. What's to expect, a troglodyte living below the civilization and all. Time to meet your maker, scum.}
{254}{}{Hah! I just knew you were the kind of person that would be spreading hate propaganda!}

{255}{}{Ya'd slay them waste-walkuurrs? Well, Ay'd be downright pleased to see ya do it. Ay'd even be obliged if ya took this book of nuclear science - one signed by my grandpappy Bubba - as a token of gratitude. Also, 'ere's the key to Skum Pitts, for body ditchin', y'know.}
{256}{}{You've got yourself an assassin.}
{257}{}{I won't even trouble asking myself whether you've really been spreading racist fliers.}
{258}{}{I won't even take the trouble of enquiring whether you've veritably been popularizing anti-NCR propaganda.}
{259}{}{I changed my mind. It's you who needs to die.}

{260}{}{'Cause I reckon waste-walkuurrs are inferior. They shouldn't be granted any rights. It's us - trogs - who are the future, plain and simple.}
{261}{}{You're right. You are the future. But what of the present?}
{262}{}{The people on the surface didn't choose to be the way they are. Why do you think it's right to punish them?}
{263}{}{Do you know that active spreading racist content is a crime?}
{264}{}{Right now, you're dead meat.}
{265}{}{I guess you're entitled to your opinion.}

{266}{}{Whatcha mean by that?}
{267}{}{Well, the NCR surface-dwellers are here and they're not going away. Some of them are terribly mutated, yes, but in many ways they are different than what you think.}

{268}{}{Different? They're jest expendable scum that needs ditchin'.}
{269}{}{Hold on there. They've organized a powerful republic, they're making sure you trogs have the rights like everyone else, they are waging a war against the enemies that wants you dead. The Brotherhood only cares about humanity, everyone else is a practicing target for them. Same with the Legion, they're no friends of trogs. They'll enslave you. There will be no more trogs in the future if the NCR is gone.}

{270}{}{So... They ain't no threat... Trogs gonna come out on top, huh? Well... I reckon I might've been a tad too harsh. Thank ya, waste-walkuurr. Ya sure opened my eyes to some new reckonings.}
{271}{}{You're welcome.}
{272}{}{I still have to report you for your misdemeanor. But you'll probably be given a light sentence.}
{273}{}{Whatever. You still get to catch a bullet to the head.}

{274}{}{Ay ain't too keen on it neither. Ay jest wish them waste-walkuurrs hadn't come. There ain't no other solution to our trouble.}
{275}{}{You're right. I'll "help" you with the problem.}
{276}{}{There must be! Racial violence is not an answer!}
{277}{}{We should just wait it over. The NCR is "sterile" and they won't last forever. In due time, the problem will disappear on its own.}

{278}{}{Maybe not to you, but it is to me. Now, Ay gotta bid y'all goodbye.}
{279}{}{I'll just wash my hands. Goodbye.}
{280}{}{I'll report you to the guard!}
{281}{}{If you think violence is an answer, answer to this: DIE!}
{282}{}{You've convinced me. Do you want me to "take out" the NCR trash?}

{283}{}{Maybe so. So what's it to ya?}
{284}{}{In the name of the New California Republic, I find you guilty of hate crime and pronounce a death sentence on you, which shall now be executed.}
{285}{}{I'm taking you in. You're under arrest and have the right to remain silent.}
{286}{}{I'll have to report you to the police.}
{287}{}{I'll try to convince you that hate and violence isn't the answer.}
{288}{}{I'll let it slip, but you must swear that you'll leave Hoover Dam and never come back.}
{289}{}{Nothing. You're powerless, as I have already taken your fliers and will show them to the authorities. Bye.}

{290}{}{Alright then. Ay'll head into exile. Never did fancy this waste-walkuurr pisspot anyhow!}
{291}{}{Good riddance!}

{292}{}{Mary-Joe the escort?}

{293}{}{[His face turns dead serious.] What did ya say? Mary-Jo fornicatin' with them waste-walkuurrs? Prove it.}
{294}{}{She has a strange birthmark located on her inner thigh. It looks like letter V.}
{295}{}{Uhh, I can't. Go and see for yourself.}

{296}{}{[His eyes widen.] AND HOW DO YA KNOW THAT?!}
{297}{}{Well I've seen it myself.}
{298}{}{Umm.. A big guy called Mallet told me. He's a big guy, but not bigger than you Billy-Bob. You should go and interrogate him personally at Dusty's.}

{299}{}{[He calms down.] Ay don't believe ya. Get lost y'all.}

{300}{}{[His hands stretch out towards your neck.] AND NOW AY'LL KILL YA MYSELF, PUT YA ON A SPIT AND SLAP AN APPLE TO YA FILTHY MOUTH!}
{301}{}{Oh shi...}

{302}{}{[He storms out towards the catwalk.]}

{400}{}{The two workin' generators could perform better but no one's touchin' 'em without chief waste-walkuurr Dodge's blessin'. Well, reckon if y'all mess up, things might blow up harder than a radleech chasin' a mole rat. Got it locked down tighter than Mary-Jo's chastity belt, ya hear?}
{401}{}{Umm, that was very descriptive. Thanks, I got the picture. Then maybe I should go and talk to Dodge about it.}
