# Message file for hdbea.ssl
# Number of nodes: 24

{100}{}{You see a super mutant with a flower in her hair.}
{101}{}{You see Beatrice.}
{102}{}{She's big, bad, and about as smart as a bag of hammers.}

# Node001
{200}{}{Me Beatrice. Me keep bad people out. You good or bad?}
{201}{}{I'd like to think I'm good. Dusty said you're a great bouncer.}
{202}{}{I'd like to think I'm good.}
{203}{}{I'm as bad as they get, rotten to the core type of person.}
{204}{}{Ugh, I have to go.}

# Node002
{230}{}{Dusty nice. Dusty give Beatrice job. Beatrice protect Dusty.}
{231}{}{Sounds like you two have quite a bond.}
{232}{}{How did you end up here?}

# Node003
{260}{}{Beatrice not remember much. Wandered, fought, ate rats, lizards, humans... Then found this place. Found Dusty.}
{261}{}{Ever thought of doing something more, Beatrice?}

# Node004
{290}{}{Dusty different. Dusty nice. Beatrice like Dusty.}

# Node005
{320}{}{Beatrice good at bouncing. Beatrice protect. What more?}
{321}{}{Like being a bodyguard, perhaps?}
{322}{}{Forget it, I guess this is the only thing you can do. So long.}

# Node006
{350}{}{Body...guard? Beatrice protect person?}
{351}{}{Exactly. Someone who could use your help. Like me.}

# Node007
{380}{}{You... want Beatrice help? Beatrice protect you?}
{381}{}{Yes, Beatrice. I could use someone strong like you.}

# Node008
{410}{}{Beatrice strong. Beatrice help. But Beatrice not leave Dusty. Sorry.}
{411}{}{Too bad! Alright, if you change your mind let me know.}

# Node009
{440}{}{You help Beatrice. Beatrice help you. Beatrice travel and protect you. You talk to Dusty.}
{441}{}{Oh, so you changed your mind finally? Beatrice, you'll be helping me in my journey across the wasteland. You sure you're up for it?}
{442}{}{Sorry, it's not going to happen.}

# Node010
{470}{}{Beatrice strong. Beatrice ready.}
{471}{}{Alright Beatrice, I have good news. Dusty is willing to let you go travel with me.}
{472}{}{Alright Beatrice, I'll ask Dusty about the idea.}
{473}{}{Actually, I changed my mind. It's best if you continue working for Dusty.}

# Node011
{500}{}{What you want from Beatrice?}
{501}{}{Nothing.}

# Node012
{530}{}{Well Mr. Bad, you better be Mr. Good. Beatrice watch your goodness meter. Bye.}
{531}{}{Well Mrs. Bad, you better be Mrs. Good. Beatrice watch your goodness meter. Bye.}
{532}{}{[END]}

# Node013
{560}{}{You like Beatrice. Beatrice like you.}
{561}{}{You're like me or you "like" me? }

# Node014
{590}{}{Beatrice like you.}
{591}{}{Ah forget it.}

# Node015
{620}{}{Beatrice happy. Beatrice follow you. We kill and eat all bad ones.}
{621}{}{Alright, whatever makes you happy. Let's go.}
{622}{}{Oh boy.}
{623}{}{No Beatrice, we're civilized people. Cannibalism is strictly prohibited. You eat everything but people. 'K?}

# Node016
{650}{}{*Sigh* 'K.}
{651}{}{Alright, let's head out.}

# Node017
{680}{}{Beatrice strong. Beatrice protect and kick butt.}
{681}{}{So you still don't remember anything about your past?}
{682}{}{What do you think of Marcus?}
{683}{}{What do you think of Bear?}
{684}{}{I want you to leave.}
{685}{}{Good to see you're doing well. Let's go.}

# Node018
{710}{}{Beatrice not sure where home is. Somewhere else. Beatrice kill and eat bad ones.}
{711}{}{Yes, we know that part of the story. Is that all?}

# Node019
{740}{}{Beatrice remember army base with others like Beatrice. Nothing else.}
{741}{}{Alright, let me know if you can recall anything else later.}

# Node020
{770}{}{Beatrice sad. Bye-bye, friends.}

# Node021
{800}{}{Marcus like Beatrice. Beatrice like Marcus.}
{801}{}{You're like Marcus or you "like" Marcus? }

# Node022
{830}{}{Bear like Beatrice. Beatrice like Bear.}
{831}{}{You're like Bear or you "like" Bear? }

# Node023
{860}{}{Beatrice like Marcus.}

# Node024
{890}{}{Beatrice like Bear.}

# Node025
{920}{}{Your face looks like poo. Beatrice not travel with poo.}

# Node026
{950}{}{You have many friends. Return to Beatrice when they die.}

# Node027
{980}{}{You Bad! Beatrice told you be Good!}

{9750}{}{Beatrice happy. Beatrice follow you.}
{9900}{}{Beatrice good.}
{9910}{}{Beatrice 'K.}
{9915}{}{Beatrice hurt.}
{9920}{}{Hmmh.}
{9930}{}{Beatrice wait.}
{9940}{}{'K.}
{9950}{}{'K.}
{9960}{}{'K.}
{9970}{}{'K.}
{9980}{}{'K.}
{9985}{}{'K.}
{9990}{}{'K.}
{9995}{}{Beatrice smash!}
