# Message file for hddave.ssl
# Number of nodes: 14
# Grammar pass done

{100}{}{You see a farmer in charge of Downtown's agriculture.}
{101}{}{You see Farmer Dave.}
{102}{}{You see a tall, medium-built man in his late forties. }

# Node001
{200}{}{What can I do for you, stranger?}
{201}{}{What can I do for you, friend?}
{202}{}{I've done it! The Scum Pits are clear of danger, and I've gathered enough building materials from Dogtown to neutralize the toxic pools and start the hydroponics farm.}
{203}{}{What are you doing here?}
{204}{}{Who are you?}
{205}{}{Nothing. Bye.}
{206}{}{What happened to your farm?}

# Node002
{230}{}{Oh, you haven't heard about it, have you? I've been ordered by Dodge to produce more wheat and corn for consumption as well as trade. The problem is, even with the new, hardier version of wheat and corn that Pierre's engineers were able to create; there just is not enough room on top of the generator buildings to grow more.}
{231}{}{So what are you going to do about it?}

# Node003
{260}{}{The only solution is to build a hydroponics farm in the area known as the Scum Pits. The big problem there is that the Scum Pits are filled with all kinds of critters. Big, nasty, glowing ones that'd sooner eat you than look at you. Dodge tried sending some men to deal with them, but... it didn't end well. And at this point, he refuses to send any more of his men.}
{261}{}{It sounds like you could use some help.}

# Node004
{290}{}{That's an understatement. And if the critters are exterminated, then there is the problem of covering the toxic holes where the generators used to be and just building the farm. It's a mess, but if we can solve these problems, it would be a boon for Hoover. I don't suppose you'd be willing to lend a hand, would you?}
{291}{}{I'd be willing to give it a try. What would you need from me?}
{292}{}{What's in it for me?}
{293}{}{Sorry, it sounds like too much work. Good luck with your project.}

# Node005
{320}{}{Well, first off, we need to deal with those dangerous creatures in the Scum Pits. If we could clear them out, it would make things a whole lot easier.}
{321}{}{I'll see what I can do about them. Anything else?}

# Node006
{350}{}{Then there's the issue of the toxic pools. If we could find a way to neutralize the toxins or at least cover the pits, that would be a huge step forward.}
{351}{}{Hmm, I'll see what I can do.}

# Node007
{380}{}{Lastly, we need building materials. We can't create a hydroponics farm without the right supplies. Maybe there's a town out there that's willing to trade their building materials with us.}
{381}{}{Yeah, there might be. I'll keep an eye out for anything that might be useful.}

# Node008
{410}{}{I'd really appreciate it. This project could mean a lot for Hoover. Thanks for offering to help. Here's the key to the catwalk access ladder north of here that leads to Baseline. You'll need to go through it to reach the Scum Pits. But trogs will help you with that.}
{411}{}{No problem. I'll see what I can do.}
{412}{}{Trogs?}

# Node009
{440}{}{I'm Dave, in charge of Downtown's agriculture. It was a natural fit for me as I enjoy growing things.}
{441}{}{So what are you doing here?}
{442}{}{I see. Goodbye, Dave.}

# Node010
{470}{}{Trogs live in Baseline. They were here before the NCR arrived. No one argued with them, and when Dodge came to Hoover, he asked if they would help out Otto with the maintenance in exchange for food goods and water. The trogs accepted and have been content ever since to mosey around Baseline making sure every light was flashing correctly. They won't cause any trouble for you.}
{471}{}{Alright, good to know.}

# Node011
{500}{}{You... you did it? I can hardly believe my ears. That's incredible! Hoover will have an abundance of food thanks to you. You've done a great service to our community, my friend. I can't express my gratitude enough. This will make a huge difference for Hoover.}
{501}{}{It wasn't easy, but the Scum Pits are now ready for farming.}
{502}{}{Don't forget about our deal.}

# Node012
{530}{}{You should be proud of yourself. Your help will be remembered and celebrated. And if you ever need anything in the future, don't hesitate to ask, my friend.}
{531}{}{Thank you, Dave. I'll keep that in mind.}

# Node013
{560}{}{Well, I ain't got much to offer but caps, gratitude, and a share of the harvest. And let me tell you, nothing tastes better than food you've had a hand in growing. So, what do you say, stranger? Are you up to it?}
{561}{}{Sounds like too much work for nothing. Goodbye.}

# Node014
{590}{}{Of course not, of course not! Here's the caps I promised. And you'll get your share of the harvest as well, once we start getting crops in. Can't thank you enough, stranger. You've done a good thing here today.}
{591}{}{Thank you, Dave.}

# Node015
{620}{}{What happened? The Brotherhood, that's what happened. The war, my friend. [He points up towards the top of the river canyon above your heads.] They were shelling the South Gate, and some grenades hit my farm. It caught fire, and all my brahmin were killed in the blast. I lost hearing in my left ear. I've temporarily relocated to a house near Downtown Engineering. It's a nightmare, but I'm grateful to still be breathing. [Tears well up in his eyes, rendering him unable to continue speaking about it.]}
{621}{}{I'm sorry to hear that.}
{622}{}{I'll do whatever it takes to put an end to this damned war. Hang in there.}
{623}{}{Thanks to my efforts, the war is finally over. Take care of yourself. We'll rebuild from here.}
{624}{}{[Leave in silence.]}
