# Message file for hddianne.ssl
# Number of nodes: 14
# Grammar pass done

{100}{}{You see a young NCR engineer.}
{101}{}{You see Dianne.}
{102}{}{You see a young, attractive woman in her late twenties. A small badge identifies her as Dianne.}

#floats
{150}{}{Watch your step! Don't touch the wires.}
{151}{}{All systems operational, maintaining peak efficiency.}
{152}{}{Generator 3 online and humming smoothly.}
{153}{}{Generator 6 operational, powering the entire facility.}
{154}{}{Radiation contamination within acceptable parameters.}
{155}{}{Filtrator Unit running at full capacity.}
{156}{}{Operating at optimum capacity, maximizing resource utilization.}
{157}{}{Yeah, listen to her purr...}
{158}{}{Remember, hands off the controls. Safety first.}
{159}{}{Purifier Unit online. I think.}
{160}{}{Wishing you a safe and productive day ahead!}
{161}{}{Apologies, I'm tied up with urgent tasks at the moment.}
{162}{}{I'm rather swamped with work right now...}
{163}{}{Please wait until after the ongoing test concludes.}
{164}{}{It might be prudent to recalculate those factors...}
{165}{}{Keep an eye out for any rodents near the generators. We don't need any mishaps.}
{166}{}{Cleanser Unit's operational, maintaining pipeline cleanliness.}
{167}{}{Refiner Unit's churning away.}
{168}{}{Decontaminator Unit's fully functional.}
{169}{}{Sanitizer Unit's up and running, maintaining minimum water purity standards.}
{170}{}{Scrubber Unit's diligently performing its duty.}
{171}{}{Sterilizer Unit's operational.}
{172}{}{Purge Unit's engaged.}

# Node001
{200}{}{Can I help you with something?}
{201}{}{You promised to go on a date with me if I saved the world. Well, here I am, the savior of the world.}
{202}{}{What are you doing here?}
{203}{}{Would you be interested in going on a date with me?}
{204}{}{Please continue with your work. Goodbye.}
{205}{}{Do you know of a mechanic that could work on Pre-war Vehicles ?}

# Node002
{230}{}{Currently, I'm collaborating with Otto and Pierre on solving the water filtration problem. Our aim is to make filtered water drinkable.}
{231}{}{I've been Otto's assistant here at Downtown Engineering.}
{232}{}{How did you get involved in this project?}
{233}{}{What's your impression of working with Otto?}
{234}{}{Would you appreciate some assistance?}
{235}{}{I serve as the Chief Engineer here at Downtown Engineering.}

# Node003
{260}{}{Previously, I served as an NCR soldier with the 5th Engineering Company. After the incident at Burham Springs, I was assigned to assist Otto. I've learned a lot from him, but this water filtration problem is a tough nut to crack.}
{261}{}{How did you handle the transition from being a soldier to an engineer?}
{262}{}{The Burham Springs incident?}
{263}{}{Thank you for sharing.}

# Node004
{290}{}{The transition wasn't seamless. I was accustomed to following orders and completing objectives. Here, it's a different ball game. We're constantly problem-solving on the fly. It's demanding, but also rewarding. I enjoy my work.}
{291}{}{Understood. Farewell.}

# Node005
{320}{}{Yes, he's an odd character, but he's got a good heart. He's a walking toolset, and that's quite a sight to see. He's taught me a lot and I've been able to apply my organizational skills to benefit our work. But Otto's sometimes a bit of a slob, I guess it comes with the age.}
{321}{}{If Otto were to depart, would you be prepared to assume the role of Chief Engineer?}
{322}{}{Thank you for making time to answer my queries. Goodbye.}

# Node006
{350}{}{Absolutely. I've learned a great deal from him, and although it would be a challenge, I'm confident I could handle the responsibility.}
{351}{}{Appreciate your insight.}

# Node007
{380}{}{Certainly! Additional assistance would be greatly appreciated. Otto will be pleased to hear of this. Please discuss it with him.}
{381}{}{Acknowledged. Farewell.}

# Node008
{410}{}{Indeed, the Burham Springs debacle was a significant setback for the NCR Army. A bunch of things blew up and released fiery gas.}
{411}{}{Could you indicate Burham Springs' location on the map?}
{412}{}{The NCR seems to be experiencing a series of setbacks, each surpassing the last. How much further can it decline? So long, suckers.}
{413}{}{Wish I could see that in person. It must have been better than the pre-war fireworks. Anyways, I have to run.}

# Node009
{440}{}{Certainly, although I can't fathom why anyone would voluntarily venture there. It's akin to Hell on Earth, if not worse.}
{441}{}{I'm quite adaptable. I'll investigate personally.}

# Node010
{470}{}{Thank you for the offer, but I'm already involved with someone else.}
{471}{}{[Kneel down and beg her for a date.]}
{472}{}{Disappointing. The good ones always seem to be taken.}

# Node011
{500}{}{Sir, please refrain from kneeling. Maintain composure. My colleagues are observing. Your actions won't influence my decision regarding you.}
{501}{}{Ma'am, I implore you to stand. My colleagues are present. Your conduct won't affect my perception of you.}
{502}{}{OK, what *would* make you change your mind about me then?}
{503}{}{[Concede defeat, for now.]}

# Node012
{530}{}{[She briefly pauses.] Oh I don't know, maybe if you save the world. Yeah, that would make me go on a date with you. Save the world first and then come back for the girl.}
{531}{}{Hmph! Is there any other condition? [Retreat while retaining some dignity.]}
{532}{}{Marvelous, it's settled then! [Depart with a smug, turning back to blow a kiss.]}

# Node013
{560}{}{Oh dear, yes... about that. I made that remark to deter you permanently. I never imagined you'd *actually* save the world. Fate has a peculiar sense of humor, it seems.}
{561}{}{[Extend your hand.] Milady, shall we? I've arranged a table for us at Pablo's. }

# Node014
{590}{}{[Accepting your hand.] Certainly. My name's Dianne, by the way. }
{591}{}{[Walk into the night with your date.]}

# Node020
{650}{}{In a pinch, i could probably do something about it, then adding in some of our engineers, I have some Dean's Electronics in the backroom, just wait for a bit....}
{651}{}{[Continue]}

# Node021
{652}{}{Well it seems i could work on increasing the fuel efficiency, increasing the engine power, or its suspension... }
{653}{}{Fuel Efficiency?} # Readily available
{654}{}{Engine Power?} 	  # After Jericho Schematics Quest Complete and then Dodge
{655}{}{Suspension?}	  # 1 Upgrade readily available, 2 upgrade Jericho Schematics, 3 upgrade meet Dodge, 4 upgrade NCR Peace
{656}{}{I want all of the above.}  # NCR Peace 
{657}{}{You know what, forget about car upgrades.}

# Node021a
{680}{}{I can do this on my own, this wasnt a common need before the war but with resources diverted for the war effort, fuel became expensive for the individual household apparently, a fuel controller would drastically reduce the draw... according to the cost in material and the time expenditure i would say 4000 caps would do it}
{681}{}{Sold!}
{682}{}{You drive a hard bargain woman! I can't get it just now, i'll come back later.}


# Node021b
{720}{}{A more powerful engine would increase the speed of your vehicle consistently, i heard back then people drove them for leisure, can you imagine it ? Successive upgrades of 8000 and 12000 can be done.}
{721}{}{Deal!} # Car Blower
{722}{}{Deal!} # NR Car Upgrade
{723}{}{The cost is too steep.}
{724}{}{All our engineers are focused on the filtration system, as of right now its impossible}
{725}{}{[end]}


# Node021c
{760}{}{It's said that an efficient suspension can even increase the speed of your vehicles, people had car that like rode on air, i can't quite divert manpower for that. However improvement in suspension would increase the amount it can carry, successful upgrades of 6000, 8000 and 12000 caps what say you ?}
{761}{}{First Upgrade} # 6000 caps
{762}{}{Second Upgrade} # 8000 caps, first update done and Jericho Plans
{763}{}{Third Upgrade} # 12000 caps and Dodge access
{764}{}{What other update were you talking about?}

# Node021d
{800}{}{With war at an end, we can finally breath again, i heard it was mostly thanks to you, we will still ask you for wages, but all of our engineer are ready for one final upgrade, 20000 caps would do it.}
{801}{}{That'd be great!}
{802}{}{Don't have quite enough just yet.}


