# Grammar pass done

#look
{100}{}{You see a "big-boned" woman standing behind the bar, exuding charm and competence.}
{101}{}{You see Dusty, the owner and operator of Dusty's Desires Bar & Entertainment.}
{102}{}{With deft hands, she expertly crafts cocktails and mixed drinks.}
{103}{}{.}
{104}{}{Welcome to Dusty's Desires, darling, Hoover Dam's premier saloon. What'll it be for you?}
{105}{}{Well met, sugar. What can I rustle up for ya?}
{106}{}{What'll it be, }
{107}{}{?}
{108}{}{I'm more than just a darling; I'm }
{109}{}{Beer, please.}
{110}{}{Liquor, if you don't mind.}
{111}{}{Nuka-Cola, perhaps?}
{112}{}{Do you happen to have any snacks available?}
{113}{}{I'm after some information.}
{114}{}{Nothing for now, thanks.}
{115}{}{I'm curious about the mutant bouncer outside.}
{116}{}{You got an issue with Big Bea? Need me to referee?}
{117}{}{Yeah. I can't wait to bust her last tooth out.}
{118}{}{Whoa, easy there. Just wanted a drink.}
{119}{}{No issue, just wondering about her backstory.}
{120}{}{Sorry, no violence talk here. I'm weak and timid!}
{121}{}{Alright, let's keep it civil.}
{122}{}{Oh, thank you for saving my neck!}
{123}{}{[Attack now, catch 'em off guard!]}
{124}{}{Five caps, please.}
{125}{}{That'll be five caps, ma'am.}
{126}{}{Thank you. That's all for now.}
{127}{}{Thanks. By the way, I heard you're the go-to for local gossip. Mind sharing some tidbits?}
{128}{}{Maybe another time.}
{129}{}{Fifteen caps, please.}
{130}{}{That'll be fifteen caps, ma'am.}
{131}{}{Four caps, please.}
{132}{}{Four caps it is, ma'am.}
{133}{}{Sure thing. What can I rustle up for you from our vendors?}
{134}{}{An iguana on a stick, please.}
{135}{}{How about some meat jerky?}
{136}{}{I'll take some cookies, if you have any.}
{137}{}{Got any fruit handy?}
{138}{}{Actually, I'm more interested in some conversation...}
{139}{}{I don't suppose you have any lasagna?}
{140}{}{This ain't exactly a five-star joint, pal. This is a bar, a casino, and a whorehouse.}
{141}{}{Sorry, this ain't a fancy restaurant, miss. This is a bar, a casino, and a whorehouse.}
{142}{}{No worries. Farewell.}
{143}{}{Yeah, I understand. But let's chat about something else...}
{144}{}{One iguana coming right up.}
{145}{}{There you go.}
{146}{}{Thanks. Mind if I pick your brain about a few things?}
{147}{}{No problem. See you around.}
{148}{}{Meat jerky will be 10 caps, and don't worry, it's not made from mad brahmin.}
{149}{}{Feeling rough? That'll be 4 caps for the fruit.}
{150}{}{No, we don't have any of those.}
{151}{}{[MORE]}
{152}{}{We've got chocolate-chip biscuits. Interested?}
{153}{}{Let me at them! I'll take a package.}
{154}{}{The package is 50 caps.}
{155}{}{Thanks! Mhm, they're delicious. Yummy! I think I'll save one for later!}
{156}{}{[Munching on a cookie.] Fenhs. I whanted to ashk you about shomething. *Bite!*  *Chew!* *Gulp!* Ah, delightful. I think I'll save a cookie for later, by the way.}
{157}{}{Not *that* hungry, thanks.}
{158}{}{Sorry, no cookies left today.}
{159}{}{Ah, shame. Let's change the topic...}
{160}{}{Maybe I'll find something else to snack on.}
{161}{}{I'll try elsewhere. Farewell.}
{162}{}{Intrigued, huh? Beatrice came from the west, long before Dodge & Co. No love lost for her here, but I saw potential. Gave her a shot, and she's been loyal ever since.}
{163}{}{What made you take a chance on her?}
{164}{}{Great. Another redeemed killer mutant and a whore with a golden heart, huh? Boooring!}
{165}{}{Equality's all well and good, but let's not kid ourselves. Mutants, ghouls, and humans ain't cut from the same cloth. I don't know whether the Master was right, but I know one thing.}
{166}{}{What?}
{167}{}{Downtown's finest, huh? That's the only thing you know, because you're stupid, as all people in Downtown are. If you were smarter, you'd be living on the Rim but you're down here in the gutter.}
{168}{}{With all due respect, you're beginning to bore me.  Bye.}
{169}{}{Apologize, or things might get messy.}
{170}{}{[Grin, reaching for weapon.]}
{171}{}{Suit yourself. Later.}
{172}{}{Through my work here, I've not only entertained the denizens of this city but also contributed meaningfully, unlike the trivial chatter of others. I'm not just an entertainer; I'm a bar and casino owner, a madame, and I take pride in my achievements.}
{173}{}{Couldn't agree more, sister! Now, about those other things I wanted to ask...}
{174}{}{Fair enough. Farewell.}
{175}{}{Apologies. Let's continue our chat.}
{176}{}{Great. Now, about those questions I had...}
{177}{}{Just a beer, please.}
{178}{}{It's refreshing to meet someone open-minded. Take care!}
{179}{}{What do you want to know?}
{180}{}{What can you tell me about Beatrice?}

{181}{}{Got any news to share?}
{182}{}{Any must-see spots in town?}
{183}{}{That's all I need for now. Bye.}
{184}{}{When Beatrice arrived at Hoover Dam, it was just before Dodge and his crew claimed control. She faced a mixed reception from the settlers; some attacked her outright, while others kept their distance.}
{185}{}{For those who dared to confront Beatrice, well, let's just say they provided her with an unexpected snack. However, those who showed her kindness were met with reciprocation. One such individual was me, Dusty Heart.}
{186}{}{Recognizing the value of a friendly gesture, I extended a helping hand to Beatrice. While she initially expressed interest in becoming my personal bodyguard - though the term seemed unfamiliar to her - I offered her a different role. Thus, Beatrice became the bouncer for my new "saloon", Dusty's Desires. She embraced her new position with enthusiasm, and ever since, she has faithfully watched over our clients. She's perfect for bouncer duties.}
{187}{}{Fascinating. On to the next topic...}
{188}{}{Looking for gear? Frieda's Firearms and the Medical Facility have you covered.}
{189}{}{What else can you share?}
{190}{}{Thanks for the tips.}
{191}{}{Let's switch gears. I'm curious about something else.}
{192}{}{The Medical Facility, situated between the North and South Gates of the Rim, is overseen by the Followers of the Apocalypse. Whether you need patching up or seeking medicinal supplies, it's a valuable resource.}
{193}{}{Moving on, there's Downtown Engineering just to the west. While it may not seem like much, paying them a visit could prove enlightening. Plus, the entrance to the Baseline lies nearby.}
{194}{}{Speaking of which, the Baseline houses the only two functioning power generators in Hoover Dam, along with a group of reclusive individuals we affectionately refer to as "trogs" - short for troglodytes. They tend to keep to themselves in the dim, musty corridors.}
{195}{}{You'll find the Council Hall beyond the North Gate. It serves as the epicenter of administration, government, and military leadership.}
{196}{}{Venturing southwest of Downtown, you'll stumble upon the agricultural area. Here, Dave and his crew toil tirelessly to stave off hunger - a noble yet unglamorous task.}
{197}{}{Nearby, the NCR Army has established barracks, a testament to their ongoing conflicts driven by the politics of expansionism. While I avoid such places, I occasionally find myself there for boxing sponsorship matches.}
{198}{}{For those seeking adventure, "Hock-it to Bob" offers bounty hunting opportunities, while caravan companies on the Rim are perpetually on the lookout for intrepid travelers.}
{199}{}{Lastly, don't forget to pay a visit to Otto, the ghoul mechanic at Downtown Engineering. He's a master of his craft and might just have some special weaponry up his sleeve - assuming he's not indulging in a siesta.}
{200}{}{That's all I can think of. But yeah, go out and explore on your own. It'll take you some time to learn all there is about the city.}
{201}{}{Much appreciated. Have a good one!}
{202}{}{Looks like we've covered it. Let's talk about something else.}
{203}{}{Boy, this gab has made my mouth dry. Give me a beer. And have one on me, too.}
{204}{}{Generous offer. Here you go.}
{205}{}{Cheers! Now, about those other questions I had...}
{206}{}{Gotta dash. Catch you later!}
{207}{}{Nice chatting with you. Take care!}
{208}{}{Sad news about the Major. He passed away. The whole town is in mourning.}
{209}{}{It's a pity, yeah. Life's a bitch. Any lighter topics to share?}
{210}{}{May he rest in peace. Goodbye.}
{211}{}{Agreed. Let's steer to happier topics...}
{212}{}{You seem like a fighter. Ever thought about joining the boxing scene? Go see Stuart in the NCR Army HQ, he's always looking for new talents.}
{213}{}{You know, there's this fellow loitering around the South Gate, giving off that unmistakable military vibe. Seen my fair share of them wander through here. He appears rather eager to bid farewell to our fair city...}
{214}{}{Oh, you mean Mark? I've met him. Anyways, tell me more news.}
{215}{}{Bob's got his hands full, it seems. He's hunting someone who tried to assassinate our Governor twice! Talk about crazy...}
{216}{}{Down below, in the ancient pre-war passages beneath our very feet, dwell the trogs. We joke that's their way of dodging taxes or they're simply too ghastly to subject us surface-dwellers to their unsightly visage.}
{217}{}{You ain't winning a beauty contest neither. You've got a pretty face but loads of baggage, if you catch my drift.}
{218}{}{You know, there's a flurry of activity stirring up in the Council Hall. Seems the council members are grappling with some weighty issues concerning our city's governance and perhaps even the Constitution. Might be worth your while to pay them a visit and catch a glimpse of the action.}
{219}{}{On another note, it seems someone's been spreading vile hate propaganda around. A pal of mine stumbled upon a flier advocating for the execution of "waste-walkers," a derogatory trog term for us surface-dwellers. It reeks of an attempt to sow discord and incite conflict. But let them try to threaten my establishment; my trusty shotgun here has other plans. [She grins, gesturing proudly to her weapon.]}
{220}{}{Well, that's about all I've got for now. Swing by sometime later, and who knows? I might have some fresh tidbits of information for you.}

{221}{}{It's about Beatrice...}

{222}{}{Big Bea? What about her?}
{223}{}{Since I helped her in that nasty barfight, she's been very grateful. She would like to travel with me, act as my bodyguard.}

{224}{}{Hahaha! You, with Beatrice?! Now, ain't that a sight! You serious?}
{225}{}{Absolutely. She's strong, loyal... I could use someone like her.}

{226}{}{Well, that's a surprise. Bea's done good here, kept the riffraff out. But you ain't wrong, she's a solid rock in a scrap.}
{227}{}{So what do you say, Dusty?}

{228}{}{That so? Well, ain't you a sweetheart... Hmmm... not happy about it but she ain't no slave. But you gotta promise to take good care of my girl, you hear?}
{229}{}{I give you my word, Dusty.}

{230}{}{One more thing, darlin'. Prices may go up a tad around here for you.}
{231}{}{I understand, Dusty. A small price to pay for Big Bea.}

{232}{}{What the hell?! That son of a gun had a rifle pointed to my head! I couldn't do anything.}
{233}{}{Anyways, thanks for helping Big Bea put that trash into the garbage can.}
{234}{}{Poor Bea, she died protecting her family. [She starts sobbing.] And where's the hell is that incompetent "cop" Mitch when we need him?!}
{235}{}{This is how my standard night often looks like. Violence, tears and bad language. I'm just thankful for every new sunrise that I see. Take care.}
{236}{}{Oh well, life's a bitch. So long.}

{237}{}{I'm looking for some company.}
{238}{}{Dusty's Desires, as the name suggests, offers premium services that will make any "lonely" feelings disappear into thin air. Our girls, boys and dancers can help. Name your desire and Dusty shall see to it. 100 caps, payments are in advance. No refunds.}
{239}{}{I'm looking for some female companionship.}
{240}{}{I'm looking for some male companionship.}
{241}{}{I just want to watch a pole dance.}
{242}{}{Can you help personally?}
{243}{}{Uh... actually... Forget it. Bye!}

{244}{}{Follow me, darling.}
{245}{}{[Follow her to the backrooms.]}

{246}{}{I'm sorry, sugar, but no. You may watch but you can't touch. It's a bad business practice to get too close to your customers and we're professionals here. I had a few bad experiences with that in the past and I've learned my lesson. Besides, Mary-Jo and the boys are real sex bunnies, you won't be missing out on anything. So what, shall it be?}

{247}{}{You must have passed out because you woke up all alone in a big room. The air smells of testosterone and motor oil.}
{248}{}{You spent some quality time getting to know the lovely Mary-Jo better. She warned you not to say anything about your little encounter to her crazy dad, Billy-Bob.}

{249}{}{Shake it, baby!}
{250}{}{Oh yeah!}
{251}{}{Mmmmm, yes!}
{252}{}{Magnificent!}
{253}{}{::whistle::}
{254}{}{Awoooooooo!}
{255}{}{::clap-clap-clap::}

#dumb
{300}{}{Greetings and salutations. What's your poison?}
{301}{}{Poison? Me don't like. Feel bad after ate poison.}
{302}{}{Me no want. Goodbye!}
{303}{}{Oh, a slow one. Let me express myself more clearly: What do you need? A drink, a snack, a considerate person to "talk" to?}
{304}{}{Hi there, Slow One. What do you want from me today?}
{305}{}{Drink.}
{306}{}{Snack.}
{307}{}{Talk.}
{308}{}{Fresh air.}
{309}{}{Nuka-Cola, Beer or Booze?}
{310}{}{Cola.}
{311}{}{Beer.}
{312}{}{Booze.}
{313}{}{Uh... Me need some time to think.}
{314}{}{It'll cost you four caps. The shiny bottlecaps. You have them?}
{315}{}{Uh-huh}
{316}{}{Nuh-uh}
{317}{}{It'll cost you five caps. The shiny bottlecaps. You have them?}
{318}{}{It'll cost you fifteen' ugh' FIVE and FIVE and FIVE caps. The shiny bottlecaps. You have them?}
{319}{}{All right. We've got iguana and meat jerky, which do you like best?}
{320}{}{Uh... Ih-guh-an-a!}
{321}{}{Uh... Meat Jer-Kee!}
{322}{}{Me dunno. Try both!}
{323}{}{Me no want eat animal. Bye.}
{324}{}{It'd cost you twenty caps. But since that's probably too much for you to even imagine, I'll be a sport and ask only five. Deal?}
{325}{}{It'd cost you ten caps. But since that's probably too much for you to even imagine, I'll be a sport and ask only five. Deal?}
{326}{}{Ain't you a smart one. Both would cost thirty. Big number, thirty. I'll make it easier for you and make you only pay ten. That's how many fingers you've probably got. Do you have this kind of money?}
{327}{}{Right. You want to know what's in town? Too bad we don't have a school yet, because it'd be the first place I'd direct you.}
{328}{}{Tell me more!}
{329}{}{U bore me. Bye.}
{330}{}{Shops are located up on the Rim. If you buy anything, you need just take the elevator up.}
{331}{}{We don't have a hotel but we have "friend beds." It's like a normal place where you can rent a bed to sleep but someone pretty of your choice joins you and treats you very friendly. A clean, pleasant bed, I might add.}
{332}{}{Also there's the Council Hall and the Army barracks beyond the South Gate, though it beats me why would you want to go there unless for a boxing match.}
{333}{}{You might want to go visit Otto in the workshop west of here. He can make miracles with mechanics and widgets. Maybe he could train you to do something useful as well. You know, like an apprentice.}
{334}{}{Be careful if you go to the Baseline. With your wits, you'd probably just break something. Or get electrocuted.}
{335}{}{There are trogs living in the dark passages beneath us. If you find them, tell them 'Hello.'}
{336}{}{Yes! Me tell! You know more?}
{337}{}{That's all I wanted to tell you. Do you need anything else?}
{338}{}{Yes. Me want drink!}
{339}{}{Yes. Me want snack!}
{340}{}{No.}
{341}{}{Hi.}

#floats
{400}{}{~~~Beer, sweet beer, the elixir of life!~~~}
{401}{}{One "Ground Zero" coming right up!}
{402}{}{You alright, buddy? Need a doc?}
{403}{}{So, a Tincan walks into a bar...}
{404}{}{On the house for you!}
{405}{}{Thanks for the tip!}
{406}{}{Owner's always right. Disagree? Take it up with Big Bea.}
{407}{}{So, what's your story?}
