# Grammar pass done

# Male Only
{100}{}{You see a gate guard.}
{101}{}{You see a gate guard stationed at the Hoover Dam.}
{102}{}{You notice an NCR trooper on duty.}

{103}{}{Everything is safe and clear here, sir.}
{104}{}{Whenever you're around, I feel like I'm not needed anymore.}
{105}{}{Catch me later, and I'll buy you a beer!}
{106}{}{Great job!}
{107}{}{Do you think I could get my hands on some shiny Combat Armor?}
{108}{}{*glares at you with admiration*}
{109}{}{You're looking sharp, sir.}
{110}{}{Isn't it amazing, just standing here and watching the sun shine over the Dam?}
{111}{}{Sometimes I wonder why I'm here at all. The turrets would shred anyone who causes trouble, right?}
{112}{}{Alpha team, the gate is secured...}
{113}{}{I wish I was stationed closer to my home.}
{114}{}{How do I get out of this uniform?}
{115}{}{These new uniforms are really snappy, aren't they?}
{116}{}{Sir, I hope you're not carrying anything dangerous.}
{117}{}{Move along, sir.}
{118}{}{If you need any assistance, sir, please let us know.}
{119}{}{Sir, please remember to refrain from littering, using abusive language, committing arson, theft, employing weapons recklessly, or engaging in murder while in our city.}
{120}{}{I'm on duty, sir. I'm afraid I can't engage in conversation right now.}
{121}{}{Are you a spy for the tincans? I'd rather not have to shoot you.}

# Female
{122}{}{If you require assistance, madam, please don't hesitate to ask.}
{123}{}{Madam, please remember to refrain from littering, using abusive language, committing arson, theft, employing weapons recklessly, or engaging in murder while in our city.}
{124}{}{I'm on duty, madam. I'm afraid I can't engage in conversation right now.}
{125}{}{Everything is safe and clear here, madam.}
{126}{}{Ma'am, I hope you're not carrying anything dangerous.}
{127}{}{Are you spying for the tincans? I'd hate to have to shoot you.}
{128}{}{Move along, madam.}

{200}{}{Please don't point your weapon at me!}
{201}{}{Why are you sneaking around? Cease your actions immediately!}
{202}{}{I warned you, fool!}
{203}{}{I suspect you're up to something!}
{204}{}{Tincans contact! Fire at will! Defend the Republic!}
