{100}{}{You see an older man with greasy hair. He's covered in dust.}
{101}{}{You see Vinnie, the eldest of the Giordano triplets.}
{102}{}{A small pin featuring a monkey covering its mouth and the name "Iwazaru" below it catches your eye on his dusty attire.}

{103}{}{If you come by here again, it's just possible that you'll have an accident.}
{104}{}{You've been warned. Now get the hell out of here.}

{105}{}{Get them doggies moving!}
{106}{}{Uh, doggies? Okay, whatever. Let's go.}
{107}{}{Hello. I'm Guido Giordano. I run the caravans between Hoover Dam and Jericho. We can use an extra caravanner, if you're willing to leave right now.}
{108}{}{Hello. I'm Guido. I run the caravan between Hoover Dam and Jericho. Always looking for a reliable caravanner or two. We leave town on the 15th of every month. If you want to go with us, make sure you're here on the 15th.}
{109}{}{What d'ya want?}
{110}{}{Moo-moos?}
{111}{}{You need a caravanner, huh?}
{112}{}{What do you trade?}
{113}{}{Why are you waiting until the 15th?}
{114}{}{I don't think that's for me. Goodbye.}
{115}{}{They sure picked the wrong caravan to mess with.}
{116}{}{Fuck with my caravan, will they?}
{117}{}{Motherfuckers should know better than to try that with my caravan.}
{118}{}{Well, they're sleeping with the fishes now. Let's move out.}
{119}{}{More of those shit-heels all the time.}
{120}{}{You abandon my caravan, and then come back to beg for work? Get out of here.}
{121}{}{I said get out. Are you deaf as well as yellow?}
{122}{}{I respect thieves... but only good ones. You're nothing but a punk. Get out of here before I have to hurt you.}
{123}{}{A thief? I resemble that remark, you damn ingrate. I'm leaving. Goodbye.}
{124}{}{You'll regret crossing me. Goodbye.}
{125}{}{That was one of the worst caravans I've had in years. I'm not making money on it, so guess what? Neither are you. Get out of my sight.}
{126}{}{Yeah? I'd like to see you try that, you cheap bastard. Goodbye.}
{127}{}{Well, sometimes you just get luckier than others. This was one of the unlucky times. Goodbye.}
{128}{}{Fuck. My ass is really in a sling here. We lost so much stuff this run. I knew I shoulda' hired pros. Here's 500 caps for your time, you worthless sack of shit.}
{129}{}{Well, something is better than nothing, I guess. Goodbye.}
{130}{}{You lousy bastard! Nobody could have done a better job. Goodbye.}
{131}{}{That's the ticket. That run went smooth as shit through a goose. Here's your 1,500 caps, pal.}
{132}{}{I don't think I ever want to spend so much time looking at the ass-end of a brahmin again. Goodbye.}
{133}{}{Thanks. See you later. Goodbye.}
{134}{}{That's the way a caravan run should go. Smooth as a baby's silky bottom. Here's your 1,500 caps, and I'll even throw in an extra 200 caps for the smooth service.}
{135}{}{Nice to find someone who appreciates quality when he sees it. See you around, maybe. Goodbye.}
{136}{}{Thanks for the extra change, Guido. Goodbye.}
{137}{}{I'm not sure how long it's going to take these damn dirt-grubbers to get my gold shipment together. We'll be ready to go on the 15th, no matter what. Check back with me if you still want a job.}
{138}{}{Hey, I'm putting together a shipment of some delicate stuff. Stuff that takes time. Can't rush quality, ya' know. Should be ready to go on the 15th. Come back then if you still want a job.}
{139}{}{What do you usually transport?}
{140}{}{Let me ask you something else.}
{141}{}{Thanks, I'll do that. Goodbye.}
{142}{}{We're usually looking for caravanners, but we ain't ready to go just yet. We'll be ready to head out on the 15th. Come back then if you want a job.}
{143}{}{Why on the 15th?}
{144}{}{What does this caravan transport?}
{145}{}{OK, thanks. Goodbye.}
{146}{}{Hey, pal, you've gotta know when to say no. And *I* do. So NO!}
{147}{}{Oh, okay.}
{148}{}{Well, we pick up mostly drinking water in Jericho, and trade it to Hoover Dam for custom-made NCR assault rifles, armor, sometimes brahmin.}
{149}{}{That's interesting. You said you're looking for caravanners?}
{150}{}{Let me ask you something else.}
{151}{}{Oh, okay. Goodbye.}
{153}{}{You came along at a good time. We're ready to go right now. The job pays 1,500 caps. You'll be assisting the caravan master directly. Use all your experience in wasteland survival to ensure timely arrival at the destination, defend the caravan and provide healing to any wounded caravanners. Ready to join us?}
{152}{}{You came along at a good time. We're ready to go right now. The job pays 1,500 caps, but I'm only paying you for the job since I only need one more caravanner. You'll be assisting the caravan master directly. Use all your experience in wasteland survival to ensure timely arrival at the destination, defend the caravan and provide healing to any wounded caravanners. Ready to join us?}
{154}{}{Sounds great. I'm ready. Let's go.}
{155}{}{I don't think I want to be a caravanner. I'll see you around. Goodbye.}
{156}{}{You were an entertaining little monkey, but now I'm tired of you. Get out of here, you dumb-ass.}
{157}{}{Numb-ass? Bye bye.}
{158}{}{Grrr! Me kill!}
{159}{}{Can you shed some light on your history? I've caught wind of some intriguing tales about your group.}
{160}{}{Ah, we're known in the "joint" as the Fearsome Threesome. Triplets who got their start in the business during a stint at NCR for petty thievery. Behind bars, we earned a reputation for being the go-to guys, the ones who could procure anything for fellow inmates.}
{161}{}{Fascinating. Do continue.}
{162}{}{Operating with a sense of fairness, we ran a tight ship - well, as tight as it gets in the slammer. Folks paid up promptly for our services, or they'd face the wrath of our alter egos, the Fearsome Threesome. Those who didn't heed the warning often found themselves nursing a few extra bruises, if you catch my drift. [He winks knowingly.]}
{163}{}{Gulp!}
{164}{}{Upon our release, we ventured into the caravan trade, forming 3-Some Caravan. Business was sluggish in NCR, understandably wary of former convicts, but we managed to scrape by and gain a modest reputation. Our big break came when the NCR government enlisted us to join Dodge and his motley crew at Hoover Dam. Seemed like a fresh start, so we eagerly packed our bags and set out.}
{165}{}{Naturally.}
{166}{}{At Hoover Dam, we quickly ingratiated ourselves with the less savory characters, and business thrived. Our only real competition was the Crimson Caravan, but they always trailed behind, preferring to deal with a supposedly "higher" clientele.}
{167}{}{A missed opportunity for them.}
{168}{}{When the Brotherhood conflict flared up, business took a hit, though strangely, Crimson Caravan flourished. This sparked a sort of "cold war" between us, and we pulled out all the stops short of resorting to murder and extortion to uncover their secrets - who their suppliers were, how they were raking in the caps.}
{169}{}{Fascinating tale. Thank you for sharing your story with me.}

{200}{}{Vinnie will be avenged!}
{201}{}{I have no business with you. Talk to Enzo first.}
{202}{}{::Zzzzzz::}
{203}{}{Bring it on!}
