# Message file for hdmilko.ssl
# Number of nodes: 12

{100}{}{You see the midget owner and proprietor of the General Store.}
{101}{}{You see Milko, the store owner.}
{102}{}{He does not realize he is small.}

{150}{}{This store is closed for you. Get out before I get into my "super mutant mode."}

# Node001
{200}{}{Hello, traveler. I'm Milko the Giant and I run the General Store around here. A man of my stature needs to keep busy, you know. Do you see anything you fancy?}
{201}{}{Well, I could always use some extra supplies. Heard you're the best in town.}
{202}{}{You certainly do "stand tall", Milko. How did you end up in Hoover Dam?}
{203}{}{Of course. What's your perspective on the war?}
{204}{}{Let's see what you have in stock.}
{205}{}{You're no giant. You're barely 5 feet tall!}
{206}{}{I've got to go.}
{207}{}{Gugi!}

# Node002
{230}{}{Best in the wasteland, if I say so myself. I'm a big presence in the business. Literally.}

# Node003
{260}{}{Ah, I wandered in from New Reno years ago. Decided to settle down and contribute to this community with my considerable... presence.}
{261}{}{Indeed. So how did you get this "big?" I've heard some stories...}

# Node004
{290}{}{Well, a man of my size needs to keep hydrated, you know. That's what makes me the towering figure I am today. 6 feet 7 inches at a muscular 360 pounds.}
{291}{}{Yeah, but what *exactly* did you drink that made you like this?}

# Node005
{320}{}{Ah, more fighting. Not good for business, not good for the community. I may be big, but I'm a man of peace.}
{321}{}{I bet I can whoop your ass on any day of the week.}

# Node006
{350}{}{For a respectful customer like you, I can show you my special collection. You seem like someone who appreciates quality.}
{351}{}{Much appreciated, Milko.}

# Node007
{380}{}{See you around and remember, in Milko's store, the deals are as big as I am!}
{381}{}{[END]}

# Node008
{410}{}{I'll make you eat those words, buddy. I'll see you in the ring! Make sure to talk to my cousin Stuart Little in the NCR Army Gym. Hmph!}
{411}{}{I'll make you eat those words, missy. I'll see you in the ring! Make sure to talk to my cousin Stuart Little in the NCR Army Gym. Hmph!}
{412}{}{That's it, I'm done with you! Out!}

# Node009
{440}{}{Welcome back to Milko's store! How may we serve you today?}

# Node010
{470}{}{I might have had a bit too much of the local water when I first arrived. Some people died, but look at me. I thrived like a mutated cactus in the wasteland!}
{471}{}{Thanks for sharing that with me. I've got to go.}

# Node011
{500}{}{[His eyes widen as you step into the store.] Ah... it's you. Let's not speak of what happened in the ring so I can sleep better at night. You're here to buy something or what?}
{501}{}{Yeah.}
{502}{}{No.}

# Node012
{530}{}{Whoa! You're *almost* as big as me. Well, what can I see, there's only one Milko the Giant around these parts.}
