# Message file for hdmitch.ssl
# Number of nodes: 11
# Grammar pass done

{100}{}{You see a stout police officer.}
{101}{}{You see Police Captain Mitch.}
{102}{}{You see a police officer in a nice uniform. He seems to be in charge here.}

{150}{}{The NCR law states that any person found under the influence of alcohol or drugs will be arrested. Too bad for you that our prison is fully booked!}

# Node001
{200}{}{Hello there. I'm the person in command of security here.}
{201}{}{Hello, citizen. What can I do for you?}
{202}{}{What is this place?}
{203}{}{Why is security so tight here?}
{204}{}{If it's not too much to ask, I'd like to know more about your background.}
{205}{}{Goodbye.}
{206}{}{You again. What can Police Captain Mitch do for you?}
{207}{}{Hello once more, dear citizen. What can Police Captain Mitch do for you?}

# Node002
{230}{}{This is Downtown. Nearly all the power for Hoover Dam comes from here.}
{231}{}{How is the power generated?}
{232}{}{Why is security so tight here?}
{233}{}{Never mind.}

# Node003
{260}{}{This is a very important location for the eventual defense of Hoover Dam. All the vital systems in the city run on power from this facility.}
{261}{}{So in case of an attack, you're going to barricade here?}
{262}{}{What threats are you prepared for?}

# Node004
{290}{}{Old fashioned, water going through intake towers making the generators spin. Nothing fancy, just bigger than what you might have seen out there.}
{291}{}{So this is important, no wonder you're all on permanent alert status...}
{292}{}{Aren't you afraid of being near generators all the time?}

# Node005
{320}{}{Not exactly, but it is important that we hold our station. Damage to the facility could tip the balance in favor of the Brotherhood.}
{321}{}{We wouldn't want that. Tell me, what threats are you expecting?}
{322}{}{Aren't you afraid? I mean, gunfire... Those are electrical generators, after all.}

# Node006
{350}{}{Well, we're prepared all the time to hold the facility against a full-scale siege. Brotherhood and as of recent, Caesar's Legion are threats. If we got very desperate, we can even destroy the elevator so that no one gets here. Plus, there's other potential dangers - saboteurs, bombers, spies... [His eyes squint. You're not sure if he's suspicious of you or just constipated.]}
{351}{}{What are your defense procedures?}
{352}{}{What could be the results of a blackout at Hoover Dam?}
{353}{}{Good to know that power is in the right hands. Heh heh. Goodbye.}

# Node007
{380}{}{Hardly. Well-maintained electrical generators don't just explode. We trust our engineers. And I've got far more immediate threats to care about.}
{381}{}{What threats are you speaking of?}
{382}{}{I see. Well, I don't want to disrupt your attention any more. Bye.}

# Node008
{410}{}{I'm sorry, I can't divulge that information. But I can assure you, that we're well-prepared.}
{411}{}{I'd like to ask you a few questions about this place.}
{412}{}{If you say so. Goodbye.}

# Node009
{440}{}{I'm Mitch Stiller, the chief of security for this here facility. Before the Brotherhood attacked us, I was to become a Sheriff. The best of all officers. Since the start of the war and the loss of Shady Sands, I've been training selflessly to improve my abilities to better serve our people. I know all 'bout laser and plasma guns. In my position here I learned much about tech maintenance, but mainly in theory. And I'm a good negotiator, too. I'm also tough as nails.}
{441}{}{So, should I call you Mitch, or Mr. Stiller...?}
{442}{}{I have some more questions about this place.}
{443}{}{Now that's a success story. Goodbye.}

# Node010
{470}{}{You may call me Susan if it makes you feel better. Now, if you'd excuse me, I cannot be interrupted.}
{471}{}{Goodbye, Susan.}
{472}{}{Alright, sir.}

# Node011
{500}{}{You're not too bright, are you? Please leave before you break something.}
{501}{}{Ghud-bay!}
