{100}{}{You've entered the NCR Army Gym, where the NCR troopers appear to be enjoying themselves. Maybe a bit too much by military standards.}

{150}{}{[PREVIOUS]}
{151}{}{[MORE]}

# made man name
{300}{}{}
{301}{}{Whisper}
{302}{}{Spider}
{303}{}{Measle}
{304}{}{Teacher}
{305}{}{Mover}
{306}{}{Bull}
{307}{}{Skipper}
{308}{}{Shush}
{309}{}{Lefty}
{310}{}{Righty}
{311}{}{Eyebrows}
{312}{}{Tornado}
{313}{}{Moulty}
{314}{}{Monkey Boy}
{315}{}{Lumpy}
{316}{}{Mitts}
{317}{}{Gooch}
{318}{}{Meat Cleaver}
{319}{}{Brocco}
{320}{}{Two-Times}
{321}{}{Romeo}
{322}{}{Vinnie}
{323}{}{Rook}
{324}{}{Silencer}
{325}{}{Hammer}
{326}{}{Knuckles}
{327}{}{Bender}
{328}{}{Grocer}
{329}{}{Snake Eyes}
{330}{}{Wolf}
{331}{}{Hatchetman}
{332}{}{Smiley}
{333}{}{Fats}
{334}{}{Pearl}
{335}{}{Reno Jimmy}
{336}{}{Jade}
{337}{}{Scarface}
{338}{}{Diamond}
{339}{}{Ace}
{340}{}{One-Eyed Jack}
{341}{}{Nikki}
{342}{}{Iceman}
{343}{}{Sly}
{344}{}{Slick}
{345}{}{Charlie}
{346}{}{Opium}
{347}{}{Dagger}
{348}{}{Angel-Eyes}
{349}{}{Fixer}
{350}{}{Shark}
{351}{}{Hound}
{352}{}{Reverend}
{353}{}{Magnum}
{354}{}{Iceberg}
{355}{}{Gina}
{356}{}{Vicki}
{357}{}{Chase}
{358}{}{Guillotine}
{359}{}{Frost}
{360}{}{Valentino}
{361}{}{Coffinmaker}
{362}{}{Little Joe}
{363}{}{Ice Queen}
{364}{}{Switch}
{365}{}{Bucks}
{366}{}{Chips}
{367}{}{Lucky}
{368}{}{Saint}
{369}{}{Numbers}
{370}{}{Mantis}
{371}{}{Scorpio}
{372}{}{Fat Man}
{373}{}{Sam}
{374}{}{Blue Lou}
{375}{}{Tommy the Gun}
{376}{}{Crazy Jane}
{377}{}{Widow}
{378}{}{Trashman}
{379}{}{Nine Inch Nick}
{380}{}{Rainmaker}
{381}{}{King}
{382}{}{Killer}
{383}{}{Santana}
{384}{}{Joey}
{385}{}{Caesar}
{386}{}{Mickey}
{387}{}{Drifter}
{388}{}{Giuseppe}
{389}{}{Butcher}
{390}{}{Red}
{391}{}{Ruby}
{392}{}{X}
{393}{}{}

# prizefighter name

{400}{}{}
{401}{}{Jabby}
{402}{}{Spinning Jenny}
{403}{}{Piston}
{404}{}{Hurricane}
{405}{}{Big Bad Muthuh}
{406}{}{Chosen One}
{407}{}{Raging Bull}
{408}{}{LaMotta}
{409}{}{Sledge}
{410}{}{Glass Joe}
{411}{}{Hoover Dam Nancy}
{412}{}{Bald Bull}
{413}{}{Princess}
{414}{}{Duke}
{415}{}{Machoman}
{416}{}{Iron Maiden}
{417}{}{Ripper}
{418}{}{Valkyrie}
{419}{}{Hook}
{420}{}{Sidewinder}
{421}{}{Bad Grrrl}
{422}{}{Rockjaw}
{423}{}{Stonewall}
{424}{}{Chainsaw}
{425}{}{Ice Heels}
{426}{}{Tommy Gunn}
{427}{}{Black Widow}
{428}{}{Smash}
{429}{}{Delilah}
{430}{}{Lightning}
{431}{}{Jocco}
{432}{}{Sister Steel}
{433}{}{Super Sledge}
{434}{}{Apollo}
{435}{}{Scrapiron}
{436}{}{Tigress}
{437}{}{Mallet}
{438}{}{Lady J}
{439}{}{Dragos}
{440}{}{Clubber}
{441}{}{Duchess}
{442}{}{Bulldozer}
{443}{}{Grace}
{444}{}{Ironhand Luke}
{445}{}{Faith}
{446}{}{Doctor Fist}
{447}{}{Flying Nun}
{448}{}{Bobo}
{449}{}{Floyd Ray Willis}
{450}{}{Calamity Jane}
{451}{}{Cobra}
{452}{}{Bloody Murder}
{453}{}{Executioner}
{454}{}{Freight Train}
{455}{}{Super-Duper Vixen}
{456}{}{Hoover Dam Jim}
{457}{}{Crusher}
{458}{}{Rico}
{459}{}{Hammerhand}
{460}{}{Widowmaker}
{461}{}{Baliff}
{462}{}{Butch Coolidge}
{463}{}{Alley Cat}
{464}{}{Bad Mojo}
{465}{}{Tank}
{466}{}{Bruiser}
{467}{}{Mynx}
{468}{}{Scorpion}
{469}{}{Punchy}
{470}{}{Cheetah}
{471}{}{Verdict}
{472}{}{Judge Jury}
{473}{}{Piledriver}
{474}{}{Athena}
{475}{}{Mad Dog}
{476}{}{Prisoner}

# special stupid names
{496}{}{Big Stu}
{497}{}{Miami}
{498}{}{X}
{499}{}{Your Name}

# other boxer names
{700}{}{Mal Fisto}
{701}{}{Tony Gunn}
{702}{}{"Steel" Mark Torrance}
{703}{}{Xander "the Sure Thing" Fields}
{704}{}{Spider}
{705}{}{Slim}
{706}{}{Sweet Jones}
{707}{}{Il Roche}
{708}{}{Tito}
{709}{}{Rudy}
{710}{}{Big George}
{711}{}{Gooch}
{712}{}{Fat Johnny}
{713}{}{Nicki}
{714}{}{LaMotta}
{715}{}{Ivan}
{716}{}{Glass Joe}
{717}{}{Dragos}
{718}{}{Tommy Gunn}
{719}{}{Apollo}

{750}{}{Milko the Giant}
{751}{}{Captain Mitch}
{752}{}{Vinnie the Kikazaru}
{753}{}{Mallet McBride}

# BOXING LEVELS
{1400}{}{You have defeated your first challenger.}
{1401}{}{You have defeated your second challenger.}
{1402}{}{You have defeated your third challenger.}
{1403}{}{You have defeated Mallet McBride!}
{1404}{}{You have become the Heavyweight Champion of Hoover Dam.}
{1405}{}{You have defeated your last challenger!}

{1600}{}{In the heat of the fight, McBride tears your ear off.}
{1700}{}{Enraged, you tear McBride's ear off.}
