# Message file for hdquartr.ssl
# Number of nodes: 2

{100}{}{This person is responsible for administering barracks and looking after supplies.}
{101}{}{You see the Quartermaster.}
{102}{}{She seems busy.}

{105}{}{You delivered Frieda's message to the Quartermaster.}

# Node001
{200}{}{Apologies, but I'm busy right now. There's only so much the Quartermaster can do at once.}
{201}{}{Excuse me, Frieda Van Graff wants you to know that your shipment has arrived.}
{202}{}{Ummm... Frida tells ship is here.}

# Node002
{230}{}{Ah, excellent! Thank you for letting me know. I don't have anything to give you for your trouble except this old trinket. Perhaps it's worth something.}
{231}{}{Umm, thank you.}
{232}{}{Hyugh!}
