# Message file for hdralph.ssl
# Number of nodes: 22
# Grammar pass done

{100}{}{You see a man dressed in sturdy armor, armed to the teeth. He carries himself with authority and wears a "Hoover Dam Police Chief" badge.}
{101}{}{You see Ralph, the tough-as-nails Police Chief.}
{102}{}{You see a tall, somewhat lanky man with chiseled features and leathery, weather beaten skin.}

{150}{}{The NCR law states that any person found under the influence of alcohol or drugs will be arrested. Too bad for you that our prison is fully booked!}

# Node001
{200}{}{Hello and welcome. I'm Hoover Dam Police Chief, Ralph. What brings you here?}
{201}{}{Hoover Dam Police Chief?}
{202}{}{Could you tell me more about this place?}
{203}{}{I have some questions for you.}
{204}{}{I'm here to stir up some trouble...}
{205}{}{I have a crime to report!}
{206}{}{Nothing, just checking to see if you're on your toes. Goodbye.}
{207}{}{You're vewy hot!}
{208}{}{Hughn!}
{209}{}{Nuthin.}

# Node002
{230}{}{Hello again. What business do you have here this time?}
{231}{}{Tell me about the Hoover Dam Police.}
{232}{}{Tell me about this place.}

# Node003
{260}{}{We are the Hoover Dam Police, a group of dedicated individuals tasked with ensuring safety and order in our community.}
{261}{}{What is this building? Is it a police station?}
{262}{}{You think you're so tough? I could take on your pitiful rag-tag officers with one hand tied behind my back!}
{263}{}{I see. And who are you...?}
{264}{}{I wanted to discuss some matters with you...}
{265}{}{You're doing a great job. Goodbye.}

# Node004
{290}{}{This is our headquarters. We receive reports from our officers here. We also have a small armory, detention cells, and an office for citizens who have business with us.}
{291}{}{This is pathetic. You couldn't maintain order in a graveyard. Or a morgue.}
{292}{}{Sounds a lot like a police station...}
{293}{}{Nice, though a little bit claustrophobic. I think I'll just leave.}

# Node005
{320}{}{Sir, if you break the law, you'll be dealt with just like any other criminal! Carry on with your business and don't do anything stupid. Farewell!}
{321}{}{Ma'am, if you break the law, you'll be dealt with just like any other criminal! Carry on with your business and don't do anything stupid. Farewell!}
{322}{}{No need to get excited. I'll just leave you to your own macho problems.}
{323}{}{Whoa, easy there. I just wanted to ask you something.}
{324}{}{That's it, bitch. You just signed your death warrant.}

# Node006
{350}{}{What is it that you want to report?}
{351}{}{Nothing. It was just a misunderstanding.}
{352}{}{If I told you, they'd kill me. And maybe you too. I can't risk putting you in danger. I must go!}
{353}{}{Pierre is a Brotherhood of Steel spy!}
{354}{}{I think you're hot and intriguing!}

# Node007
{380}{}{Now listen here, we're as close as it gets to law and order in this dustbowl. Don't have all the training? Maybe, but not for long. The NCR's doing their damndest to whip us into shape. We're just a ragtag group of folks, see, citizens with a backbone, out here tryin' to uphold a semblance of law. We're the people. The people are us. You get that, and you get what we're trying to do here.}
{381}{}{I see. And who am I speaking to...?}
{382}{}{You still look like a fool to me, and I don't like fools...}
{383}{}{The NCR? What about them?}
{384}{}{What kind of training are you referring to?}
{385}{}{Respect for the law? It seems like a rather peaceful community...}
{386}{}{I think I've learned enough about the Hoover Dam Police for now. Goodbye.}

# Node008
{410}{}{I'm Hoover Dam Police Chief, Ralph Peoples. I oversee all the officers in Hoover Dam, except the NCR Rangers. [He stands at attention, then relaxes and extends his hand.] It's a pleasure to meet you.}
{411}{}{I'm }
{412}{}{. Pleased to make your acquaintance. I have some questions for you...}
{413}{}{, and I don't think that's important to you right now. What is important are my questions...}
{414}{}{, and I'm one rough and tough son-of-a-bitch!}
{415}{}{I'm known as the Prisoner, but I must be going.}
{416}{}{[Walk away, showing disrespect.]}

# Node009
{440}{}{I once knew a Vault Dweller who thought he could disarm a plasma grenade with a screwdriver. You make him look like a Brotherhood of Steel Scribe.}
{441}{}{Hah!}

# Node010
{470}{}{Why... thank you. It's always nice to receive a compliment, even from someone as special as you. Alright, now run along. If you get lost, just ask one of the officers for help.}
{471}{}{Gheh!}

# Node011
{500}{}{That's cute, but you're not my type. Besides, I'm on duty.}
{501}{}{Oh, darn...}

# Node012
{530}{}{Those NCR folks, they've been good for something, helping us sharpen up our shooting and throwing some light weapons our way. They've got this pipe dream, see, of making the wasteland something less than a hellhole, keeping the peace and all. But damn it, they're spread thinner than a coat of paint on a deathclaw. They're hunting for more boots on the ground, more warm bodies to carry a badge. Yet, they're tight-lipped, always playing their cards close to the vest. You'll find 'em holed up in City Hall, plotting and scheming in the shadows.}
{531}{}{I already know all about the NCR. I've been working with them while you were still eating sugar bombs for breakfast, lunch and dinner. Let me ask you something else.}
{532}{}{Let me ask you something else.}
{533}{}{I see. I'll go talk to them.}

# Node013
{560}{}{The NCR's been pretty handy, I'll give 'em that. They've beefed up our small arms know-how, even got us dancing the deadly tango of martial arts. Every one of my officers now can throw a punch that'd make a super mutant think twice.}
{561}{}{That kind of training. But I wanted to know something else...}
{562}{}{I'd like to know more about that. I'll seek him out.}

# Node014
{590}{}{Sure, the Hoover Dam's a picture of calm, but don't you believe for a second any place is rid of crime completely. We got our own piles of poor and plenty of pissed-off folks, cooking up their share of petty mischief. Then there're these greenhorns from out of town, always looking to stir up a hornet's nest. And let's not forget those damn Brotherhood patrols, always poking their noses where they ain't welcome. Thank the stars, the NCR's got our backs in giving them the old one-two.}
{591}{}{Let me ask something else...}
{592}{}{You make a valid point... But I still don't know who you are, sir...}
{593}{}{How sweet. You're just a puppet for the NCR. I'd like to see you try to push me around...}

# Node015
{620}{}{What else would you like to talk about?}
{621}{}{I'd like you to summarize your role once more.}
{622}{}{I'd like to ask about the NCR.}
{623}{}{I'd like to discuss officer training...}
{624}{}{Ralph, how did you end up here in Hoover Dam?}
{625}{}{Nothing, I suppose. Goodbye.}
{626}{}{I want to know how many bullets I can lodge in your brain before you die, you police swine!}
{627}{}{How do you feel about the war?}

# Node016
{650}{}{Thank you for reporting this. But I know Pierre well and he's not a former Brotherhood Scribe. He and the engineers are on our side. They did so much for the NCR. So there's nothing to worry about. But don't mention this to Major Fleming. Old wounds, you know. Thanks for doing your civic duty, }
{651}{}{.}
{652}{}{My mistake then. Let me ask you something else.}
{653}{}{Somehow, I feel like a fool now. Goodbye.}
{654}{}{But he admitted. And there's evidence on his computer!}

# Node017
{680}{}{Drifted from one hellhole to another. Thought I'd never find a place to rest my boots until Governor Dodge came along.}
{681}{}{It must've been tough out there on your own. How did you survive?}
{682}{}{Alright, I have to go now. So long.}

# Node018
{710}{}{In the wasteland, it's kill or be killed. You learn to shoot straight, or you don't live long.}
{711}{}{Is that why you agreed to be the police chief here?}
{712}{}{How insightful. Let us finish our discussion some other time.}

# Node019
{740}{}{Partly. Dodge saw potential in this place, and I saw potential in Dodge. He needed someone to keep order, and I know a thing or two about that.}
{741}{}{Tell me something else.}
{742}{}{Thanks for sharing your story with me, Ralph. Good luck.}

# Node020
{770}{}{War is good for no one, kid. Just a lot of people trying to prove they're right, without care for the damage they do. I worry it might rip this place apart one day.}
{771}{}{What will you do if the Hoover Dam community collapses?}
{772}{}{That's grim. So long.}

# Node021
{800}{}{I'll do what I always do. Keep moving, keep surviving. There's always scum out there needs dealing with. But let's hope it doesn't come to that, eh?}
{801}{}{We'll do what we can to prevent it, Ralph.}
{802}{}{Speaking of that, I better move on. Goodbye.}

# Node022
{830}{}{That's all anyone can ask, kid. But it ain't just about choosing sides. It's about protecting the home you've got. Keep that in mind, and you'll do alright.}
{831}{}{Thanks for that. Goodbye.}

# Node023
{860}{}{If you say so. Yeah, we'll investigate. Eventually.}
