{100}{}{You see an NCR trooper.}
{101}{}{You see an NCR trooper stationed at Hoover Dam.}
{102}{}{You see an New California Republic trooper.}

{103}{}{The Dam's chasm is deeper even than the Grand Canyon.}
{104}{}{Well, you sure found that out yesterday.}
{105}{}{You mean when you kicked my cattle prod down the Rim and I had to use the elevator to get it back?}
{106}{}{I didn't kick it, you dropped it. Get over it, butterfingers.}
{107}{}{How about I kick your cattle prod and you go down?}
{108}{}{I don't know. It looks pretty deep, and somehow I think you'd follow it.}
{109}{}{But you'd have to go down anyway. You couldn't just afford to lose your favorite prod.}
{110}{}{I'd make you go down for it.}
{111}{}{But then, you couldn't be certain if I brought it back?}
{112}{}{You're right. You'd probably get lost down there.}
{113}{}{I didn't get lost yesterday. Guess I'm the "swift learner" type.}
{114}{}{Well then, perhaps you should keep practicing. Hold your prod and stretch your arms in front of you...}
{115}{}{Don't even think about it. Trick me once, shame on you. Trick me twice, shame on me.}
{116}{}{Come on, I'm only trying to help you. A few more courses and you'll be a man!}
{117}{}{No thanks, I'm man enough already. I've got a prod...}
{118}{}{Oh yeah, and what'd you do without it if you were attacked?}
{119}{}{I'd manage. After all, I dispatched that rat yesterday...}
{120}{}{Oh yeah. And you nearly broke your arm while at it.}
{121}{}{That's one nearly too many. I'm doing just fine.}
{122}{}{Just like when you ate those poisonous roots? I thought you were going to kick the bucket!}
{123}{}{They looked just like those edible roots you had shown me earlier!}
{124}{}{Face it, you don't know the first thing about survival.}
{125}{}{That's because I lived in Shady Sands, you nitwit. I never even been out until I was 25.}
{126}{}{Then you don't know what you're missing. The sun, the wind, the glowing sand...}
{127}{}{At least I saw some electronic stuff. Like jukeboxes. Say, they look like the one you broke...}
{128}{}{I don't remember any jukeboxes.}
{129}{}{You know, the one you bought?}
{130}{}{I didn't break it. It was broken before that.}
{131}{}{Not before you pounded it with a hammer.}
{132}{}{Look, the salesman said it would make music. How else was I supposed to get any sound out of it?}
{133}{}{Well, you're supposed to plug it in and... oh, never mind...}
{134}{}{Yeah, whatever. Just keep an eye out for anyone suspicious and enjoy the view.}

#talk floats
{135}{}{Halt! Who goes there?}
{136}{}{Sir!}
{137}{}{It's a pleasure to meet you, sir.}
{138}{}{Sir, you may use the elevator. The area behind me is not accessible nor safe.}
{139}{}{We're guarding the debris, sir. From strangers. And saboteurs.}
{140}{}{Pssst! Don't pay attention to my companion, sir. A little retarded, that one is.}

#talk floats - female
{141}{}{Halt! Who goes there?}
{142}{}{Ma'am.}
{143}{}{It's a pleasure to meet you, ma'am.}
{144}{}{Ma'am, you may use the elevator. The area behind me is not accessible nor safe.}
{145}{}{We're guarding the debris, ma'am. From strangers. And saboteurs.}
{146}{}{Pssst! Don't pay attention to my companion, ma'am. A little retarded, that one is.}
