# Message file for hdvinnie.ssl
# Number of nodes: 11
# Grammar pass done

{100}{}{You see a towering figure in a sharp suit and fedora. His size makes you wonder if he's more mutant than man.}
{101}{}{You see Vinnie, the youngest of the Giordano triplets.}
{102}{}{A small pin featuring a monkey covering its ears and the name "Kikazaru" below it catches your eye on his attire.}
{103}{}{*snore*}

{150}{}{You piece of chicken shit! I'll break every bone in your body!}
{151}{}{You piece of shit!}
{152}{}{THIS is for trying to double-cross 3-Some Caravan!}
{153}{}{THIS is for trying to double-cross Enzo!}
{154}{}{THIS is for trying to double-cross Guido!}
{155}{}{And THIS is for trying to double-cross ME!}
{156}{}{Next time I see you around our office, you'll be FLYING off this very ledge.}

{160}{}{You fiefe of fhifken fhit! I'll bfeak efefy fone in youf fody!}
{161}{}{You fiefe of fhit!}
{162}{}{FHIS is fof tfying fo foufle-foff 3-Fome Fafafan!}
{163}{}{FHIS is fof tfying fo foufle-foff Enfo!}
{164}{}{FHIS is fof tfying fo foufle-foff Fuido!}
{165}{}{And FHIS is fof tfying to foufle-foff ME and FUFTING my feefh!}
{166}{}{Nef fime I fee you afound ouf offife, you'll be FLYING off fhif vefy fedge.}

{170}{}{What the hell is going on there? Is that Vinnie?}
{171}{}{Hmm, it seems you are still alive. Come visit me at my office if you're looking for work.}
{172}{}{Enemy of my enemy is my friend. Here's my business card. Get well soon.}

# Node001
{200}{}{Hey there. I'm Vinnie, your go-to guy for all things boxing. What's your name, and what brings you here?}
{201}{}{I'm }
{202}{}{, and I'm itching for a bout in the ring.}
{203}{}{Enzo suggested we stage a "fake" fight.}
{204}{}{I've got some questions.}
{205}{}{No business with you. Farewell.}

# Node002
{230}{}{Welcome back. Ready for a chat or a spar?}
{231}{}{I'm eager to try my luck in the ring.}
{232}{}{Neither. Catch you later.}

# Node003
{260}{}{Ah, that idea. Picture this: we head behind the office, throw some insults, exchange a few punches, with me showing you the dirt, face down. Ailis catches the whole show. What do you say?}
{261}{}{Alright, sounds like a plan. Let's do it.}
{262}{}{Is that the best you've got?}

# Node004
{290}{}{Come on, it's foolproof. Don't chicken out on me now.}
{291}{}{I'm no chicken, just don't break anything.}

# Node005
{320}{}{Chat with Stuart over at the NCR Army's gym. He'll set you up, and then we can throw some punches. I usually take bets, but not today.}
{321}{}{Alright, I'll talk to Stuart. So long.}

# Node006
{350}{}{Hi. My name is Finnie.. fait, I knof you fom the fing. You fusted out my feefh. Fhat did you fome here? I fon't fant any mofe fouble.}

# Node007
{380}{}{Hi fhamp. You fusted out my feefh. Fhat did you fome hefe? I fon't fant any mofe fouble.}

# Node008
{410}{}{Ah fhaf, yes, I fas fhinking of us foinf fehind fhe office, efchanfinf a few foud infulfs and funches, fith me ficfing youf ass of coufse and feafing you fying face fown to eaf some dift. Hof does fhaf sound? Fe'll do fhaf fhen Ailis fasses by so she can see it fifst fand.}
{411}{}{Ah, a revenge match for the previous boxing loss, huh?}

# Node009
{440}{}{Cofe on, if's foinf fo fofk. Fon't chicfen ouf on fe nof.}
{441}{}{I'm no chicken, just don't break anything. Or else!}

# Node010
{470}{}{Fantastic, but I'm not the one with answers. Talk to Guido about that, and avoid Enzo like the plague.}
{471}{}{Got it, Guido it is.}

# Node011
{500}{}{Fhaf's gfeat buf I don'f fave fhe ansfefs. Falk fo Guido afouf fhaf, fon't efen tfy fifh Enfo.}
