# Message file for mbandrea.ssl
# Number of nodes: 33
# Grammar pass done

{100}{}{You see a woman who appears extremely sick and frail.}
{101}{}{It's Elder Brixley, the Commander of Maxson Bunker. She seems unaware of your presence.}
{102}{}{You see a woman on the verge of death. Her eyes are sunken, and her skin clings tightly to her bones.}

{105}{}{Congratulations! You have advanced one rank in the Brotherhood of Steel.}
{106}{}{You returned the stolen Stealth Boys to the Brotherhood.}

{110}{}{You see a thin, weak woman.}
{111}{}{It's Elder Brixley, the Commander of Maxson Bunker. She greets you with a warm smile.}
{112}{}{You see Elder Brixley. She still appears frail, but there's a noticeable improvement in her health.}

# Elder is sick
{200}{}{*groan*}
{201}{}{*moan*}
{202}{}{End... please let it end...}
{203}{}{Glenn? Glenn, is that you?}
{204}{}{You left the beer out again, Jerry! It's going to get warm!}

# Elder is cured
{230}{}{I can't thank you enough.}
{231}{}{I feel so much better.}
{232}{}{How's it going, Doc?}

# TalkIll
{290}{}{[The woman groans in agony.] Who...?}
{291}{}{I'm here to help you, ma'am. Let's start by checking your memory. What's your name?}
{292}{}{[Administer a dose of Rad-Away as treatment.]}
{293}{}{[Administer a second dose of Rad-Away as treatment.]}
{294}{}{[Administer a third dose of Rad-Away as treatment.]}
{295}{}{[Administer a fourth dose of Rad-Away as treatment.]}
{296}{}{[Administer a fifth dose of Rad-Away as treatment.]}
{297}{}{Apologies for disturbing you. Goodbye.}

# Cured
{320}{}{If it isn't Doc }
{321}{}{! Can I help you with something? Just let me know.}
{322}{}{How are you feeling today?}
{323}{}{Nothing for now.}
{324}{}{Andrea, I have found the poisoner! It was Devon Hill, the quartermaster. He resisted arrest, so I had to eliminate him.}
{325}{}{Andrea, I have discovered the location of the Circle of Steel's hideout!}
{326}{}{Andrea, I have destroyed the Circle of Steel! Here are their Stealth Boys. They posed a significant threat, but they won't trouble the Brotherhood anymore.}
{327}{}{Andrea, I have destroyed the Circle of Steel! They posed a serious threat, but they won't trouble the Brotherhood anymore.}
{328}{}{I came across something you might be interested in. It's a pre-war facility, a dome full of high-tech equipment. I believe it could be beneficial for the Brotherhood.}
{329}{}{I see you've taken control of the dome. How is the situation?}
{330}{}{Found shiny old place. Big bubble full of smart stuff. Think we like it.}
{331}{}{You boss of bubble now. Every good?}
{332}{}{Andrea, I have destroyed Hoover Dam. The war is over!}
{333}{}{Me do BIG BADA BOOM on Huv-R! Now Huv-R sleep with big fishies.}
{334}{}{Andrea, with traitors Devon and Ailis out of the picture, I've laid the groundwork for peace negotiations with Governor Dodge. The end of the war is within sight!}
{335}{}{Devon gone. Ailis gone. We do peace with NCR. You end war!}
{336}{}{Are you interested in getting your hands on some enriched uranium?}
{337}{}{Me get you rich uran. You want?}

# WhoIs
{350}{}{I'm... Andrea... Brixley... Elder Paladin... General Commander... of... Maxson Bunker.}
{351}{}{Elder, Dr. Sarah asked me to assist you. I'm going to conduct a few tests to determine what's wrong.}
{352}{}{Well, I hope you recover soon, Elder. Goodbye.}

# OKDiagnose
{380}{}{It hurts... so much...}
{381}{}{[Attempt to diagnose the condition.]}

# TryLeave
{410}{}{[As you turn to leave, the Elder's frail hand grasps your arm with surprising strength. She looks at you with pleading eyes.] Please... the pain... make it stop...}
{411}{}{What do you mean?}
{412}{}{I'll do everything I can to help you. Hang on. Goodbye.}

# KillMe
{440}{}{Just... end it... make the pain go away... [She slumps back, exhausted, releasing your arm.]}
{441}{}{[END]}

# TestSuccess
{470}{}{[After conducting a series of tests with the limited resources available, you diagnose her with an extremely severe case of radiation poisoning.]}
{471}{}{[CONTINUE]}

# TestSuccess2
{500}{}{[However, the malignant tumors haven't irreversibly damaged her internal organs yet. Administering a combined dosage of 5 Rad-Aways as soon as possible may destroy the cancer and give the Elder a chance at recovery.]}

# TestFailure
{530}{}{[After exhausting all diagnostic techniques, you conclude that her radiation poisoning is fatal. The cancer has spread extensively, leaving no hope for recovery.]}

# RadAway5
{560}{}{[You administer a dose of Rad-Away. Four more doses are needed to complete the treatment.]}

# RadAway4
{590}{}{[You administer a dose of Rad-Away. Three more doses are needed to complete the treatment.]}

# RadAway3
{620}{}{[You administer a dose of Rad-Away. Two more doses are needed to complete the treatment.]}

# RadAway2
{650}{}{[You administer a dose of Rad-Away. One more dose is needed to complete the treatment.]}

# RadAway1
{680}{}{[You administer a dose of Rad-Away. The treatment is now complete.]}
{681}{}{[WAIT]}

# Treated
{710}{}{[After resting for a while, the Elder slips into a deep coma. Utilizing the Brotherhood's advanced medical equipment, you determine that your diagnosis and treatment were unsuccessful. Her internal organs show significant damage, and her prognosis is grim.]}
{711}{}{Elder, wake up! Andrea! Can you hear me?}

# Feelgreat
{740}{}{[She is unresponsive. She seems to be fading away, detached from the world.]}
{741}{}{[Collect yourself and quietly leave her quarters.]}

# Thanks
{770}{}{You're the Brother who helped me figure out what was wrong. You've cured me! I can't express how grateful I am.}
{771}{}{You're the Sister who helped me figure out what was wrong. You've cured me! I can't express how grateful I am.}
{772}{}{No thanks necessary. I'm just glad you're feeling better.}
{773}{}{Well, if you're looking for a way to show your gratitude, an advanced armor or a laser rifle would be quite impressive.}

# Goodbye
{800}{}{You're a remarkable person. It's rare to find someone like you in this world. You've given me another chance at life, and I intend to make the most of it. I can be independent again, not relying on others.}
{801}{}{That's great, but remember to take it easy and give yourself time to recover.}

# Poor
{829}{}{[She looks disheartened.] I'd love to reward you, but our quartermaster isn't generous with supplies. However, I can grant you access to our library archives on this floor.}
{830}{}{[She looks disheartened.] I'd love to reward you, but our quartermaster isn't generous with supplies. However, I can grant you access to our library archives on this floor. Here's the access key.}
{831}{}{Take it easy now. You're not out of danger yet.}
{832}{}{Well, I save your life and don't receive a single cap. See you around.}

# HowAreYou
{860}{}{Feeling great, Doc, just great. I can even walk on my own again. Some might say it's not much progress, but only time will heal my wounds now. Thank you for everything you did.}
{861}{}{No problem. Take care, Elder.}

# Node026
{890}{}{[She salutes you.]}
{891}{}{[Return the salute.]}

# Node027
{920}{}{Initiate }
{921}{}{, I've been contemplating how to properly thank you for saving my life. There's only one way: an immediate promotion to Senior Initiate. Congratulations! [She hands you your military dog tags.]}
{922}{}{Thank you, Commander!}
{923}{}{Thank, Comm!}

# Node028
{950}{}{Urrgh... the dog tags and all the formal ranks, they never appealed to me. From my perspective, you're the one who saved my life, so let's drop the official titles. You can call me Andrea. You're a man who gets things done. As you can see, a spy infiltrated our ranks! Doc }
{951}{}{, I'm ordering you to undertake another crucial mission: find the poisoner and bring them to justice.}
{952}{}{Urrgh... the dog tags and all the formal ranks, they never appealed to me. From my perspective, you're the one who saved my life, so let's drop the official titles. You can call me Andrea. You're a woman who gets things done. As you can see, a spy infiltrated our ranks! Doc }
{953}{}{Of course, Andrea. Once I get my hands on the traitorous little maggot scum, I'll... I'll... [Clench your fist.]}
{954}{}{Thank, Andre! Yes, Andre! Me hurt bad person bad... [Clench your fist.]}

# Node025
{980}{}{Devon?! I would have never suspected... [Sadness contorts her face.] Why, Devon? Did you uncover his motives?}
{981}{}{He shouted something about the Brotherhood going in the wrong direction and being replaced by the Circle of Steel. I don't know what that means exactly.}

# Node029
{1010}{}{The Circle of Steel? Intriguing... it sounds like something worth investigating. Devon couldn't have acted alone. Find his contacts and discover more about this Circle of Steel. If they pose a threat to the Brotherhood, you have the authority to eliminate them. We already have enough trouble with the NCR; we don't need another enemy right now.}
{1011}{}{Find Devon's contacts and uncover the secrets of the Circle of Steel? Understood.}

# Node030
{1040}{}{You have? Excellent work, Doc! Hmmm, let's not waste any time... I want you to launch a surprise attack on their hideout and eradicate them. We've had occasional clashes with deserters. This might put an end to it.}
{1041}{}{But that sounds like a suicide mission. Can someone from the Brotherhood accompany me?}
{1042}{}{You can count on me, Andrea.}

# Node031
{1070}{}{You already know the answer to that question, my dear Doc. We can't afford to lose any more Brothers and Sisters. Honestly, you're currently the best the Brotherhood has. I trust you'll return alive and victorious. Do it for the future generations, }
{1071}{}{. Don't let the Brotherhood perish.}
{1072}{}{I'll do my best, but I can't make any promises. We'll see how it goes.}

# Node032
{1100}{}{Good luck, Doc. May the divine light of knowledge guide your way back home.}
{1101}{}{[END]}

# Node033
{1130}{}{One more thing, }
{1131}{}{. Due to your continuous efforts and contributions to the Brotherhood, I'm promoting your rank to Apprentice. Congratulations!}
{1132}{}{Thank you. I'm honored.}

# Node034
{1160}{}{And you've returned unscathed to share the story... }
{1161}{}{, you're the best thing that has happened to the Brotherhood in a long, long time. There's nothing you can't accomplish. You embody hope for our future, }
{1162}{}{. I'm promoting your rank to Journeyman and have another critical mission for you. End the war with the NCR. Travel to Hoover Dam and find a way.}
{1163}{}{. I'm promoting your rank to Journeywoman and have another critical mission for you. End the war with the NCR. Travel to Hoover Dam and find a way.}
{1164}{}{One person to end a war? Stranger things have happened. I'll do it, Andrea.}
{1165}{}{Travel to Hoover Dam and end the war? If the opportunity arises, I'll do what I can.}

# Node035
{1190}{}{A pre-war facility, you say? Unclaimed and untouched? The Brotherhood has always been dedicated to preserving such relics. But we need to proceed with caution. Do we have the required expertise to handle this technology?}
{1191}{}{That's a concern. The facility is operated by an AI named ZAX. Without proper technical understanding, ZAX might fail. The Brotherhood lacks such expertise right now.}
{1192}{}{Bad stuff. Big brain robot ZAK in charge. No ZAK smarts, ZAK go boom. We no have big brain for this yet.}

# Node036
{1220}{}{An AI, you say? That is indeed a concern. However, this is an opportunity we cannot pass. The potential benefit is too great.}

# Node037
{1250}{}{We will prepare a team to secure the dome. We appreciate this information. It is our hope that this facility will prove beneficial to the Brotherhood.}
{1251}{}{Just remember to tread carefully. ZAX is critical to the facility's operation. Good luck, Commander.}
{1252}{}{Be smart, ZAK main boss! Gud luk, Comm.}

# Node038
{1280}{}{The dome is under Brotherhood control, and ZAX is still functioning, though it's been a challenge without proper tech personnel. However, your warning was invaluable. We're proceeding with the utmost care to ensure we can maintain the facility and learn from it. We are grateful for your assistance.}

# Node039
{1310}{}{[You notice a glimmer of emotion in her eye, possibly a tear forming.] My dear }
{1311}{}{, you've brought great honor to the Brotherhood. The long and unjust war that has plagued us is finally coming to an end. I will swiftly convene the council to commence peace negotiations with the NCR. As for you, nothing less than a promotion to Senior rank is fitting. Additionally, you shall be granted access to select any Brotherhood armor of your preference. Your name will be etched alongside the legends of our order, joining the esteemed ranks of individuals like Vree and Rhombus. Your actions will be remembered and revered by generations to come. Come now, follow me. We must honor your Senior rank properly.}
{1312}{}{Thank you, Andrea. It wasn't easy but I proved to be the right person for the job. And thank you for the generous reward, }
{1313}{}{I will take a Power Armor suit.}
{1314}{}{I will take a Brotherhood Combat Armor suit.}
{1315}{}{[She leans in, whispering.] But perhaps it's best if we keep your involvement in the Dam explosion between us, shall we?}

{1340}{}{, I have a vital task for you. Our bunker's supply situation has been dire for some time now. During the war, I even had to order our troops to ambush caravans... and I'm not just talking about NCR's caravans. [She takes a dramatic break, as if hesitating to speak further.] We are no longer receiving shipments from the Brotherhood in the west.}
{1341}{}{That's concerning news. Without those supplies, our operations here will be severely impacted.}

{1370}{}{Precisely. We cannot allow our resources to dwindle to the point of strategic defeat. We must find a solution, and quickly.}
{1371}{}{What do you propose we do?}

{1400}{}{We must establish a new trade route to ensure the bunker's survival. Hoover Dam's caravans are a potential source of the supplies we need. Your task is to negotiate a trade agreement with them.}
{1401}{}{Understood, Andrea. I'll make the necessary arrangements.}
{1402}{}{I'm really too busy now.}

{1430}{}{I have faith in your abilities, Senior. May the Brotherhood's wisdom guide you in Hoover Dam. [She salutes you.]}

{1460}{}{No, you're not.}
{1461}{}{No, I'm not.}

{1490}{}{There's no one more suited for this mission than you. Your Hoover Dam connections are the best we have.}
{1491}{}{True.}

{1520}{}{Absolutely! That sort of resource has a wide range of ultimate technological and military uses. Do you have it? We would be able to trade our rare ammunition for it.}
{1521}{}{Yes, I have it.}
{1522}{}{No, not yet.}
{1523}{}{Yep!}
{1524}{}{Nope.}

{1550}{}{Excellent! Thank you for your unwavering loyalty and contribution to the Brotherhood's holy mission.}
{1551}{}{You're welcome.}
{1552}{}{'K.}
