# Message file for mbdevon.ssl
# Number of nodes: 26
# Grammar pass done

{100}{}{You see the Brotherhood's quartermaster.}
{101}{}{You see Brother Devon, the quartermaster.}
{102}{}{You see a well-muscled, tattooed guard, looking intently ahead.}

# StopFirst
{230}{}{Hold it right there. You're not authorized to proceed any further.}
{231}{}{I have no intentions of stealing anything, friend.}
{232}{}{I go where I please, and a nobody like you won't stop me.}
{233}{}{Who are you?}
{234}{}{Alright, I'll leave.}
{235}{}{No go in?}

# StopAgain
{260}{}{I've told you before, pal. Step away from there.}
{261}{}{I've told you before, miss. Step away from there.}
{262}{}{Fine. Instead, let me ask you some questions.}
{263}{}{Yeah, you've told me before. This time, I'm warning you - back off before things get ugly.}
{264}{}{Fine. I'll leave.}
{265}{}{But wan' go in!}

# TalkFirst
{290}{}{Can I assist you with something?}
{291}{}{Devon Hill, I'm here on official business. You're under arrest for conspiring to assassinate Andrea Brixley, General Commander of Maxson Bunker and Elder Paladin of the Brotherhood of Steel. I have gathered all the evidence required. Game over, Devon.}
{292}{}{Yeah, who are you?}
{293}{}{Let me ask you a few questions.}
{294}{}{Not at the moment. Goodbye.}
{295}{}{Help, yeah! Me wan' help.}

# TalkAgain
{320}{}{You're back. Is there a problem?}
{321}{}{No problem - just have a few questions.}
{322}{}{No, just saying hi. See you around.}
{323}{}{Me prob'em? No... urrrr... hello!}

# Angry
{350}{}{Don't act like you weren't warned.}
{351}{}{Fuc-}

# Questions
{380}{}{I'm not here to chit-chat. Ask your question and stop bothering me.}
{381}{}{Who are you?}
{382}{}{What can you tell me about the Brotherhood?}
{383}{}{Is there any work for an Initiate around here?}
{384}{}{I need access to the armory.}
{385}{}{Actually, never mind. Goodbye.}

# Whois
{410}{}{I'm Devon Hill, the quartermaster. I guard the armory.}
{411}{}{You're a wealth of information. Tell me a bit more about yourself.}
{412}{}{Let me ask you about something else.}
{413}{}{Good to meet you, Devon. See you later.}

# MB
{440}{}{It's a home. The people here tend to be too soft. That's a major problem if you ask me. [He eyes you suspiciously.]}
{441}{}{Major problem? Does that mean there's something I can help with?}
{442}{}{Thanks. Goodbye.}

# Work
{470}{}{I'm not the person to talk to. Try Ed or General Brixley. They might have a job or two available.}
{471}{}{Tell me about Ed.}
{472}{}{Tell me about General Brixley.}

# GetPast
{500}{}{No entry, buddy. Move along.}
{501}{}{No entry, miss. Move along.}
{502}{}{I really need access to the supplies. It's a matter of life and death.}
{503}{}{How about if I make it worth your while? Fifty caps.}
{504}{}{Let me in, or I'll force my way through and take what I need!}
{505}{}{[Smile suggestively] What if I made it... worth your while? }
{506}{}{Ed sent me. I need to pick up some things for him.}
{507}{}{Fair enough. Can I ask you a question before I go?}
{508}{}{Right, right... I'm leaving.}

# MorePersonal
{530}{}{There's nothing else about me you need to know. Now move along.}
{531}{}{Hold on, I have another question for you.}
{532}{}{Silent type, huh? I can respect that. See you around.}
{533}{}{Fine, it's probably a boring story anyway. Goodbye.}

# Ed
{560}{}{He's the boss over at the motor pool. Damn fine mechanic. Decent guy. Treats you fair if you return the favor.}
{561}{}{Got another question for you.}

# Brixley
{590}{}{She's the woman in charge here. Doesn't do the best job, if you ask me. She's been having some troubles lately, but that's none of my business.}
{591}{}{Troubles? Like what?}

# Troubles
{620}{}{It's not your business either. I'm no gossip.}
{621}{}{Tell me about Ed instead.}
{622}{}{Let me ask you something else then.}
{623}{}{Fine. Goodbye.}

# LifeDeath
{650}{}{I don't care how urgent you think it is - nobody gets into the armory. Now move along.}
{651}{}{Come on! Just look the other way for a couple of minutes.}
{652}{}{Let's talk about something else.}

# Bribe
{680}{}{I don't take bribes. Now get out of here.}
{681}{}{A hundred?}
{682}{}{Surely there's some way you'll let me through?}

# BeatUp
{710}{}{[His eyes narrow] Get out of here. Now.}
{711}{}{No. You heard what I said. What are you gonna do about it?}
{712}{}{Okay, okay - I'm leaving.}

# Seduce
{740}{}{[His face remains impassive] Caps. Pussy. I don't take bribes. Move along, miss.}

# EdSent
{770}{}{Bullshit. He'll let me know when he wants something. Now get out of here.}
{771}{}{Come on! Surely there's some way you'll let me through.}

# Dumb
{800}{}{Not too bright, are you? No entry.}
{801}{}{Urrr... Okay!}
{802}{}{[Break into a run past the guard]}

# DumbAgain
{830}{}{Listen to me - you can't go in. Now clear off.}

# DumbTalk
{860}{}{Great, one of those. I can't help you, pal. Get out of here.}
{861}{}{Great, one of those. I can't help you, lady. Get out of here.}
{862}{}{[END]}

# DumbTalkAgain
{890}{}{This again. Get - out - of - here.}

# Node025
{920}{}{You're an idiot, an imbecile! We're losing the war, losing technology to the wastes, and our inept "commander" can't do a damn thing about it! Well, some of us have taken steps to recoup our losses!}
{921}{}{You've lost your mind, Devon. I'm escorting you down to the brig. The Commander will decide your fate.}

# Node026
{950}{}{Hahaha - our future is the Circle of Steel! The Brotherhood belongs to the past, along with all the morons supporting it. Die, traitor!}
{951}{}{[Defend yourself.]}
