# Message file for mbed.ssl
# Number of nodes: 11
# Grammar pass done

{100}{}{You see the Brotherhood's Mechanic.}
{101}{}{You see Ed the Mechanic.}
{102}{}{He appears to be busy.}

{105}{}{This doesn't seem right at all.}
{106}{}{That's the problem!}
{107}{}{I think I've isolated the issue.}
{108}{}{Damn it!}
{109}{}{Darn it!}
{110}{}{My fault!}
{111}{}{I'm fine.}
{112}{}{Okay, that hurt.}
{113}{}{I meant to do that.}
{114}{}{Why does that keep happening?}
{115}{}{My eyes!}
{116}{}{You're not a knight.}
{117}{}{I need to speak with a knight.}
{118}{}{I don't understand, the power cells keep shorting out.}
{119}{}{You should stand back; these can be dangerous.}
{120}{}{Please don't distract me.}
{121}{}{Watch where you're standing.}
{122}{}{Lost?}
{123}{}{Sorry, I can't talk right now.}
{124}{}{There we go.}
{125}{}{The firing mechanism keeps jamming.}
{126}{}{That's much better.}
{127}{}{Almost got it.}
{128}{}{This is going to take a while.}


# Node001
{200}{}{Welcome, newcomer. The name's Edward Whatley, but you can call me Ed. We've been swamped with tasks lately. How can I assist you?}
{201}{}{Whatley? Any relation to Sarah Whatley?}
{202}{}{Pleasure to meet you, Ed. I'm }
{203}{}{, and I was wondering if there's any work available here.}
{204}{}{What's that "thing" behind you? I've never seen anything like it before.}
{205}{}{Oops, wrong turn. Sorry about that.}
{206}{}{Hughi.}
{207}{}{Do you have any information about the Commander's illness?}

# Node002
{230}{}{Sarah's my big sister. If you need medical assistance, she's the one to see.}
{231}{}{How did both of you end up here?}
{232}{}{I see. What else can you tell me?}
{233}{}{Take care, Ed.}

# Node003
{260}{}{My career kicked off as a mechanic's apprentice in a small town near Hoover Dam. I had potential, but my mentor was a secretive old-timer. Sarah worked hard to raise money for my education in Hoover Dam. Her efforts paid off, and I became a master mechanic.}
{261}{}{Go on. I'm interested.}
{262}{}{Thanks for sharing. Farewell.}

# Node004
{290}{}{A Brotherhood recruiter, more of a spy, actually, discovered me and offered a place within the order. I agreed under one condition.}
{291}{}{And what condition was that?}

# Node005
{320}{}{I insisted that my sister be allowed to join as well. It was unheard of, but they couldn't afford to lose my skills.}
{321}{}{Sounds like a close bond you both share.}
{322}{}{Touching story. I'll let you get back to your duties.}

# Node006
{350}{}{I'm a simple man, content with my life. I love my sister dearly, and we look out for each other. Since our parents passed away, we've become inseparable.}
{351}{}{Best of luck to both of you. Take care, Ed.}
{352}{}{Thanks for sharing. Tell me more about yourself.}

# Node007
{380}{}{Work? We've got more than enough of that around here! With the ongoing war and our focus on resurrecting this tank, we've neglected some base maintenance. The order would appreciate it if you could lend a hand.}
{381}{}{No problem. Just provide me with a repair list, and I'll take care of it.}
{382}{}{Sounds like something I'm not skilled at. Maybe another time.}

# Node008
{410}{}{Fantastic! Here's the repair list. Load it into your Pip-Boy. As a bonus, I'll grant you exclusive access to Level 2. Good luck, buddy.}
{411}{}{Thanks. I'll get right on it.}

# Node009
{440}{}{That's a pre-war tank, an incredibly powerful machine. It was abandoned here in the bunker, and no one has been able to bring it back to life. But I won't give up. If we can make it operational, it will be a game-changer in our war against the NCR.}
{441}{}{Is there anything I can do to assist with the tank's restoration?}
{442}{}{Don't take it personally, but as an NCR spy, I'm afraid I have to eliminate you here and now.}
{443}{}{Impressive. Tell me more about the tank.}
{444}{}{I'll leave you to your war campaign then. Good luck.}

# Node010
{470}{}{We have a limited understanding, if any, of some of the tank's crucial components. If you come across any schematics or books related to pre-war machinery during your travels, bring them here. They might hold the key to unlocking its secrets.}
{471}{}{I'll keep an eye out for any relevant information. Goodbye for now.}
{472}{}{Interesting. Tell me something else about the Brotherhood.}

# Node011
{500}{}{How can I assist you, buddy?}
{501}{}{Is Sarah Whatley your relative?}
{502}{}{Are there any tasks available for me around here?}
{503}{}{Hua!}
{504}{}{I've completed the bunker maintenance. Everything's up and running smoothly!}

# Node012
{530}{}{I'm stuck here working all the time, and I barely know what's happening in other parts of the base. I'm hoping Sarah finds a cure soon. Losing her would be a devastating blow to the order.}

# Node013
{560}{}{[He gives you a hearty pat on the back.] Well done, Brother! Your efforts won't go unnoticed. I'll make sure to speak highly of you to the Elders.}
{561}{}{[He gives you a hearty pat on the back.] Well done, Sister! Your dedication doesn't go unnoticed. I'll make sure to speak highly of you to the Elders.}
{562}{}{Thank you, Brother Ed. Take care.}
{563}{}{Is that it? Just a pat on the back? Is there any reward for my achievements?}

# Node014
{590}{}{A productive Brother is a satisfied one. We all have our roles to fulfill, especially during these challenging times.}
{591}{}{A productive Sister is a satisfied one. We all have our duties to carry out, especially during these challenging times.}
{592}{}{If you say so. Farewell for now.}
{593}{}{Tell me something else then.}
