# Message file for mbed.ssl
# Number of nodes: 11
# Grammar pass done

{100}{}{You see the Brotherhood's Mechanic.}
{101}{}{You see Ed the Mechanic.}
{102}{}{He appears to be busy.}

{105}{}{This doesn't seem right at all.}
{106}{}{That's the problem!}
{107}{}{I think I've isolated the issue.}
{108}{}{Damn it!}
{109}{}{Darn it!}
{110}{}{My fault!}
{111}{}{I'm fine.}
{112}{}{Okay, that hurt.}
{113}{}{I meant to do that.}
{114}{}{Why does that keep happening?}
{115}{}{My eyes!}
{116}{}{You're not a knight.}
{117}{}{I need to speak with a knight.}
{118}{}{I don't understand, the power cells keep shorting out.}
{119}{}{You should stand back; these can be dangerous.}
{120}{}{Please don't distract me.}
{121}{}{Watch where you're standing.}
{122}{}{Lost?}
{123}{}{Sorry, I can't talk right now.}
{124}{}{There we go.}
{125}{}{The firing mechanism keeps jamming.}
{126}{}{That's much better.}
{127}{}{Almost got it.}
{128}{}{This is going to take a while.}


# Node001
{200}{}{Welcome, newcomer. The name's Edward Whatley, but you can call me Ed. We've been swamped with tasks lately. How can I assist you?}
{201}{}{Whatley? Any relation to Sarah Whatley?}
{202}{}{Pleasure to meet you, Ed. I'm }
{203}{}{, and I was wondering if there's any work available here.}
{204}{}{What's that "thing" behind you? I've never seen anything like it before.}
{205}{}{Oops, wrong turn. Sorry about that.}
{206}{}{Hughi.}
{207}{}{Do you have any information about the Commander's illness?}

# Node002
{230}{}{Sarah's my big sister. If you need medical assistance, she's the one to see.}
{231}{}{How did both of you end up here?}
{232}{}{I see. What else can you tell me?}
{233}{}{Take care, Ed.}

# Node003
{260}{}{My career kicked off as a mechanic's apprentice in a small town near Hoover Dam. I had potential, but my mentor was a secretive old-timer. Sarah worked hard to raise money for my education in Hoover Dam. Her efforts paid off, and I became a master mechanic.}
{261}{}{Go on. I'm interested.}
{262}{}{Thanks for sharing. Farewell.}

# Node004
{290}{}{A Brotherhood recruiter, more of a spy, actually, discovered me and offered a place within the order. I agreed under one condition.}
{291}{}{And what condition was that?}

# Node005
{320}{}{I insisted that my sister be allowed to join as well. It was unheard of, but they couldn't afford to lose my skills.}
{321}{}{Sounds like a close bond you both share.}
{322}{}{Touching story. I'll let you get back to your duties.}

# Node006
{350}{}{I'm a simple man, content with my life. I love my sister dearly, and we look out for each other. Since our parents passed away, we've become inseparable.}
{351}{}{Best of luck to both of you. Take care, Ed.}
{352}{}{Thanks for sharing. Tell me more about yourself.}

# Node007
{380}{}{Work? We've got more than enough of that around here! With the ongoing war and our focus on resurrecting this tank, we've neglected some base maintenance. The order would appreciate it if you could lend a hand.}
{381}{}{No problem. Just provide me with a repair list, and I'll take care of it.}
{382}{}{Sounds like something I'm not skilled at. Maybe another time.}

# Node008
{410}{}{Fantastic! Here's the repair list. Load it into your Pip-Boy. As a bonus, I'll grant you exclusive access to Level 2. Good luck, buddy.}
{411}{}{Thanks. I'll get right on it.}

# Node009
{440}{}{That's a pre-war tank, an incredibly powerful machine. It was abandoned here in the bunker, and no one has been able to bring it back to life. But I won't give up. If we can make it operational, it will be a game-changer in our war against the NCR.}
{441}{}{Is there anything I can do to assist with the tank's restoration?}
{442}{}{Don't take it personally, but as an NCR spy, I'm afraid I have to eliminate you here and now.}
{443}{}{Impressive. Tell me more about the tank.}
{444}{}{I'll leave you to your war campaign then. Good luck.}

# Node010
{470}{}{We have a limited understanding, if any, of some of the tank's crucial components. If you come across any schematics or books related to pre-war machinery during your travels, bring them here. They might hold the key to unlocking its secrets.}
{471}{}{I'll keep an eye out for any relevant information. Goodbye for now.}
{472}{}{Interesting. Tell me something else about the Brotherhood.}

# Node011
{500}{}{How can I assist you, buddy?}
{501}{}{Is Sarah Whatley your relative?}
{502}{}{Are there any tasks available for me around here?}
{503}{}{Hua!}
{504}{}{I've completed the bunker maintenance. Everything's up and running smoothly!}

# Node012
{530}{}{I'm stuck here working all the time, and I barely know what's happening in other parts of the base. I'm hoping Sarah finds a cure soon. Losing her would be a devastating blow to the order.}

# Node013
{560}{}{[He gives you a hearty pat on the back.] Well done, Brother! Your efforts won't go unnoticed. I'll make sure to speak highly of you to the Elders.}
{561}{}{[He gives you a hearty pat on the back.] Well done, Sister! Your dedication doesn't go unnoticed. I'll make sure to speak highly of you to the Elders.}
{562}{}{Thank you, Brother Ed. Take care.}
{563}{}{Is that it? Just a pat on the back? Is there any reward for my achievements?}

# Node014
{590}{}{A productive Brother is a satisfied one. We all have our roles to fulfill, especially during these challenging times.}
{591}{}{A productive Sister is a satisfied one. We all have our duties to carry out, especially during these challenging times.}
{592}{}{If you say so. Farewell for now.}
{593}{}{Tell me something else then.}

# Upgrades Nodes 23 - 49

{613}{}{I've got to go.}
{622}{}{Sure buddy. Anything. No charge, too. What do you have for Ed? A rifle, a pistol or revolver, an armor, a melee weapon, a heavy weapon?}
{623}{}{A rifle.}
{624}{}{A pistol or revolver.}
{625}{}{An armor.}
{626}{}{A melee weapon.}
{627}{}{A heavy weapon.}
{628}{}{Nothing right now.}
{629}{}{OK, what rifle would it be? What's your wish?}
{630}{}{Expand the magazine on my Assault Rifle.}
{631}{}{Put a laser sight on my FN FAL.}
{632}{}{Put a scope on my Hunting rifle.}
{633}{}{Amplify the capacitors on my Laser Rifle.}
{634}{}{Hotwire my Plasma Rifle.}
{635}{}{Saw off my Shotgun.}
{636}{}{OK, what pistol or revolver would it be? What's your wish?}
{637}{}{Expand the magazine on my Desert Eagle.}
{638}{}{Put a speed loader on my Magnum.}
{639}{}{Put a magnetic chamber on my Laser Pistol.}
{640}{}{Amplify the capacitors on my Plasma Glock.}
{641}{}{OK, what armor would it be? What's your wish?}
{642}{}{Brush up my Metal Armor.}
{643}{}{Upgrade my Combat Armor.}
{644}{}{Give a hardening treatment to my Powered Armor.}
{645}{}{OK, what melee weapon would it be? What's your wish?}
{646}{}{Uhm - could I have my Spear sharpened?}
{647}{}{Upgrade this cattle prod.}
{648}{}{Upgrade this Power Fist.}
{649}{}{OK, what heavy weapon would it be? What's your wish?}
{650}{}{I want you to give more punch to my flamethrower.}
{651}{}{Here you go. It will now carry a hundred slugs in one mag. Hope it's enough.}
{652}{}{Thanks! I'll try not to fire it all on one opponent.}
{653}{}{Here you go. It should be much easier to target enemies in the dark now.}
{654}{}{Thanks! Those tunnel rats better beware now.}
{655}{}{I done it. Remember, it'll only be useful at long range.}
{656}{}{Thanks! Hunting's never been so much fun.}
{657}{}{Here. I made it so it'll now carry twice the charge before you need to reload.}
{658}{}{Like a Vault Boy. Got it. Thanks!}
{659}{}{I given it some extra kick, the plasma ought to be hotter and more damaging now.}
{660}{}{Now they'll go down just like this: zap! Thanks.}
{661}{}{Here. It'll be more effective at close quarters, but sacrificing the power at long range.}
{662}{}{Whatever. It's the feel that counts. Thanks!}
{663}{}{All done. Holds 20 bullets now.}
{664}{}{There's never too many. Thanks!}
{665}{}{There. It'll be twice as fast to replenish the ammunition.}
{666}{}{It's feeling cool already. Thanks!}
{667}{}{Ed really don't see how this could be useful.}
{668}{}{It will come in handy, trust me. Bye.}
{669}{}{Here. I refitted those crude linkings and polished it up a little.}
{670}{}{Now that's what I call shiny. Thanks!}
{671}{}{Here. I fitted it with additional plates and dissipater layers. Like to see anything pierce through that!}
{672}{}{I know I wouldn't. Thanks!}
{673}{}{Sure. Why not?}
{674}{}{I don't know. It's a weapon. Thanks!}
{675}{}{You planning to start a ranch?}
{676}{}{Not at all. Thanks!}
{677}{}{No problem. Just don't get carried away using that.}
{678}{}{I'll be careful not to. Thanks!}
{679}{}{Here. It'll be as deadly as ever.}
{680}{}{I love the smell of kerosene in the morning. Thanks!}
{681}{}{Ed would do it, but you need to bring some extra stuff.}
{682}{}{I'll do it, what do you need?}
{683}{}{Forget it.}
{684}{}{A set of Chemistry Journals and a technical manual for the armor.}
{685}{}{I'm yet to find those. Maybe I'll give you something else to upgrade.}
{686}{}{I've got to go find them, then. Bye.}
{687}{}{I've yet to find the journals. Bye.}
{688}{}{I've got to find the manual. Bye.}
{689}{}{I've got both right here.}
{690}{}{Can you tinker with anything of mine?}
{691}{}{Me dunno. You pick.}

{732}{}{You do? You'll give it to Ed? Uhm... Listen, come back haben, Ed will give you a present too!}
{733}{}{Me want prezunt!}
{734}{}{You want me to upgrade something? What?}
{735}{}{Me dunno. You pick.}
{736}{}{I've upgraded your metal armor for you.}
{737}{}{I've upgraded your combat armor for you.}
{738}{}{I've sharpened your spear for you.}
{739}{}{I've mega-strengthened your Power Fist for you.}
{740}{}{I've hotwired that cattle prod for you.}
{741}{}{I've expanded the clip on your Desert Eagle for you.}
{742}{}{I've put a speed loader on your Magnum revolver for you.}
{743}{}{I've added a scope for your hunting rifle.}
{744}{}{I've put a night sight on your FN FAL.}
{745}{}{I've expanded the magazine of your AK-112 machinegun.}
{746}{}{I've given more power to your flamer.}
{747}{}{I've put a magnetic chamber on your Wattz Civilian Pistol.}
{748}{}{I've expanded the clip for your Plasma Pistol.}
{749}{}{I've expanded the clip for your Laser Rifle.}
{750}{}{I've refitted your regular Plasma into a Turbo Plasma.}
{751}{}{Thankuuuu!}
{752}{}{Sorry, I can do nothing for you, you've got nothing to upgrade.}

# Node020
{850}{}{In a pinch, i could probably do something about it, then adding in some of our engineers, I have some Dean's Electronics in the backroom, just wait for a bit....}
{851}{}{[Continue]}

# Node021
{852}{}{Well it seems i could work on increasing the fuel efficiency, increasing the engine power, or its suspension... }
{853}{}{Fuel Efficiency?} # Readily available
{854}{}{Engine Power?} 	  # After Jericho Schematics Quest Complete and then Dodge
{855}{}{Suspension?}	  # 1 Upgrade readily available, 2 upgrade Jericho Schematics, 3 upgrade meet Dodge, 4 upgrade NCR Peace
{856}{}{I want all of the above.}  # NCR Peace 
{857}{}{You know what, forget about car upgrades.}

# Node021a
{880}{}{I can do this on my own, this wasnt a common need before the war but with resources diverted for the war effort, fuel became expensive for the individual household apparently, a fuel controller would drastically reduce the draw... according to the cost in material and the time expenditure i would say 4000 caps would do it}
{881}{}{Sold!}
{882}{}{You drive a hard bargain woman! I can't get it just now, i'll come back later.}


# Node021b
{920}{}{A more powerful engine would increase the speed of your vehicle consistently, i heard back then people drove them for leisure, can you imagine it ? Successive upgrades of 8000 and 12000 can be done.}
{921}{}{Deal!} # Car Blower
{922}{}{Deal!} # NR Car Upgrade
{923}{}{The cost is too steep.}
{924}{}{All our engineers are focused on the filtration system, as of right now its impossible}
{925}{}{[end]}


# Node021c
{960}{}{It's said that an efficient suspension can even increase the speed of your vehicles, people had car that like rode on air, i can't quite divert manpower for that. However improvement in suspension would increase the amount it can carry, successful upgrades of 6000, 8000 and 12000 caps what say you ?}
{961}{}{First Upgrade} # 6000 caps
{962}{}{Second Upgrade} # 8000 caps, first update done and Jericho Plans
{963}{}{Third Upgrade} # 12000 caps and Dodge access
{964}{}{What other update were you talking about?}

# Node021d
{1000}{}{With war at an end, we can finally breath again, i heard it was mostly thanks to you, we will still ask you for wages, but all of our engineer are ready for one final upgrade, 20000 caps would do it.}
{1001}{}{That'd be great!}
{1002}{}{Don't have quite enough just yet.}
{1003}{}{Have you ever dealt with pre-war vehicles ?}

#Node022
{1030}{}{Can you refuel my vehicle?}
{1031}{}{Thanks!}