# Message file for mbjon.ssl
# Number of nodes: 40
# Grammar pass done

{100}{}{You see a cook happily nursing a bottle of beer.}
{101}{}{You see Jon, the cook, enjoying another beer.}
{102}{}{Many more empty bottles, similar to the half-full one he is holding, are grouped on the table in front of him.}

# Jon_1a_1
{230}{}{Hi there.}
{231}{}{Hello, my name's }
{232}{}{. And you?}
{233}{}{What's your story?}
{234}{}{Fuck off, drunk.}
{235}{}{Goodbye.}
{236}{}{Hello. You smell like beer.}
{237}{}{Me go.}

# Jon_1a_2a_1
{260}{}{Good to meet you, }
{261}{}{. I'm Jon Young. Give me ten caps and I'll get you a drink.}
{262}{}{Sure, here's ten caps. Beer me.}
{263}{}{Sure, here's ten caps. Get me something non-alcoholic.}
{264}{}{Actually, I'm more interested in your story.}
{265}{}{No, thanks. Goodbye.}

# Jon_1a_2a_2
{290}{}{Here you go, buddy. [He hands you your drink.]}
{291}{}{Here you go, miss. [He hands you your drink.]}
{292}{}{So, what's your story?}
{293}{}{Thanks, see you later.}

# Jon_1a_2b_1
{320}{}{I'm one of the two main cooks here. Just enjoying a few beers, that's my story.}
{321}{}{Has anything interesting happened to you recently?}
{322}{}{Alright then, I'll let you enjoy your drink.}

# Jon_1a_2b_2
{350}{}{Err... nope. Although the other day, a gecko took a bite at Devon's ass. It was hilarious watching him walk afterwards, funniest thing I've ever seen!}
{351}{}{Sounds like you guys have some interesting moments. Anyway, I should be on my way.}
{352}{}{By the way, can you tell me anything about the Commander?}
{353}{}{Alright, take care. Goodbye.}

# Jon_1a_D1
{380}{}{What?}
{381}{}{Me smell beer once but Mommy said me not allowed drink it.}
{382}{}{Me leave.}

# Jon_1a_D2
{410}{}{A damn retard, that's all I need.}
{411}{}{Me no reeeeee-tard. Me spec-ial. Mommy and Doc say so.}
{412}{}{You bad. Me go.}

# Jon_1a_D3
{440}{}{Doc? What the hell are you talking about, kid?}
{441}{}{Doc? What the hell are you talking about, miss?}
{442}{}{Doc let me in. Place where me come from mega giga prison where robots rule.}
{443}{}{Me go now.}

# Jon_1a_D4
{470}{}{Mega giga prison where robots rule? [He snorts a laugh, not sure whether to believe you.] You better not be messing with me, kid.}
{471}{}{Mega giga prison where robots rule? [He snorts a laugh, not sure whether to believe you.] You better not be messing with me, miss.}
{472}{}{Me no lie. Me tell truth.}
{473}{}{You mean. Bye mean man.}

# Jon_1a_D5_a1
{500}{}{Alright, kid, where is this prison of yours?}
{501}{}{[Point towards North.]}
{502}{}{[Point towards East.]}
{503}{}{[Point towards South.]}
{504}{}{[Point towards West.]}
{505}{}{[Shrug your shoulders and walk away.]}

# Jon_1a_D5_a2
{530}{}{Fancy that. [He turns away and takes a thoughtful swig from his beer bottle.] Fancy that.}
{531}{}{Bye.}

# Jon_1a_D5_b
{560}{}{[The man laughs again, and a few nearby Brotherhood members join in.] Look, kid, this is no place for children to be playing in. So get lost.}

# Jon_1b_1
{590}{}{Hello again. Fancy treating me to a drink this time? I'm broke as a mole rat's tooth.}
{591}{}{Here's ten caps. Get me something non-alcoholic and grab yourself one too.}
{592}{}{Here's ten caps. Get me a beer and one for yourself.}
{593}{}{Maybe another time. I have to go now.}

# Jon_1b_2
{620}{}{Thanks, pal. Here's your drink. [He hands you your drink.]}
{621}{}{Anything interesting happen since we last spoke?}
{622}{}{Oops, just remembered I need to be somewhere else. Gotta run.}

# Jon_1b_3
{650}{}{Yeah, I've been watching that spider build its web. [He points with the neck of his beer bottle at an intricate web strung in one of the corners.] Fascinating creatures, really.}
{651}{}{[Watch the spider.]}

# Jon_1b_4
{680}{}{[After a few minutes, the spider seems satisfied with its work. It scuttles into the center of the web and patiently awaits its first victim. Your drinking companion almost startles you when he speaks again.] Amazing creatures, aren't they?}
{681}{}{Yeah, they sure are.}

# Jon_1b_5
{710}{}{[He continues looking at the web with a glassy-eyed half-smile on his face.]}
{711}{}{[Continue watching the web.]}

# Jon_1b_6
{740}{}{[The spider sits completely motionless in the center of its web.]}
{741}{}{[Wait.]}

# Jon_1b_7a
{770}{}{[The spider continues to sit completely motionless in the center of its web. You start to wonder if it's still alive.]}
{771}{}{[Wait some more.]}

# Jon_1b_7b_1
{800}{}{[A fly, having fed upon the alcoholic liquid carelessly slopped on nearby tables, buzzes drunkenly near the web.]}
{801}{}{[Continue waiting.]}

# Jon_1b_7b_2a
{830}{}{[The fly flies away and out of the kitchen.]}

# Jon_1b_7b_2b_1
{860}{}{[The fly flies straight into the web. The spider leaps into action, scuttling across the strands to its victim in the blink of an eye. It closes its lethal mandibles over the hapless fly, whose buzzing struggles soon come to an end.]}

# Jon_1b_7b_2b_2
{890}{}{[The spider leaves its kill to feast upon later and returns to its place in the center of the web.]}

# Jon_1c_1
{920}{}{Hey, thanks for the drink, buddy. I could get a mug of the good stuff instead of that bottled crap. I didn't know Tamara was giving away the Commander's beer for free, though.}
{921}{}{Hey, thanks for the drink, miss. I could get a mug of the good stuff instead of that bottled rubbish. I didn't know Tamara was giving away the Commander's beer for free, though.}
{922}{}{For free? What do you mean?}
{923}{}{Neither did I. Well, goodbye then.}

# Jon_1c_2
{950}{}{Well, look at that. This here is craft beer, specially made for the Commander at her request. [He holds up the glass, admiring the beer's texture.]}
{951}{}{Can I have a taste?}
{952}{}{I'll ask Tamara what's up with that.}
{953}{}{Fancy that. Well, goodbye then.}

# Jon_1c_3a_1
{980}{}{Sure thing. Fork over twenty caps, and it's all yours.}
{981}{}{Here's your twenty caps.}
{982}{}{Twenty caps is too much. I'll give you ten for it.}
{983}{}{Just give me the beer before I pound your face into the floor.}
{984}{}{No deal. Well, goodbye then.}

# Jon_1c_3a_2a
{1010}{}{Grab some from the storage room. [He takes your money and gives you the key.]}
{1011}{}{Thanks. Well, goodbye then.}

# Jon_1c_3a_2b_a1
{1040}{}{Heh, you gotta admit it was worth a try. Alright, gimmie ten caps, and you can have the damn thing.}
{1041}{}{Here you go. [Offer him ten caps.]}

# Jon_1c_3a_2b_a2
{1070}{}{Grab some from the storage room. [He takes the caps and gives you the key. He balances the last one on the end of his thumb, flicks it into the air, catches it again, and puts it into his pocket.]}
{1071}{}{Nice doing business with you. Well, goodbye then.}

# Jon_1c_3a_2c
{1100}{}{No, I reckon you'll give me twenty for it.}
{1101}{}{Alright, here's your twenty caps.}
{1102}{}{Twenty caps is too much. Well, goodbye then.}

# Jon_1c_3b
{1130}{}{I sure as hell won't. I'll just enjoy it while I can. [He empties the glass and throws it over his shoulder.]}

# Jon_1c_3B_a1
{1160}{}{Hey, don't be so hasty! Take the damn thing from the storage room. [He gives you the key.]}
{1161}{}{There, that wasn't so bad, was it?}

# Jon_1c_3B_a2
{1190}{}{[He turns back to his drink, muttering.] I thought drunks were supposed to have GOOD luck...}
{1191}{}{[END]}

# Jon_1c_3B_b1
{1220}{}{[He gives you an exaggerated frown, and his voice rises through an octave of disbelief] What the HELL did you just say? [The others look around eagerly, hoping for a fight.]}
{1221}{}{Don't mess with me, pal. Just hand over the beer.}
{1222}{}{Okay, forget I mentioned it.}

# Jon_1c_3B_b2
{1250}{}{[You receive a chorus of chicken noises from the Brotherhood members as you back down.]}
{1251}{}{That does it. [Draw weapon.]}
{1252}{}{[Cringe and leave]}

# Jon_B1
{1280}{}{What did you just say, pal?}
{1281}{}{What did you just say, miss?}
{1282}{}{I told you to fuck off and called you a drunk. So fuck off, drunk.}
{1283}{}{I said, "My, doesn't time fly?" I've got to be going. Goodbye.}

# Jon_B2_a
{1310}{}{Geez, can't a guy enjoy his beer in peace? Alright, I won't bother you again.}
{1311}{}{Make sure you don't.}

# Jon_B2_b
{1340}{}{You're mixing it up with the wrong "drunk", pal. [He puts his glass down with a thump on the table. The others look around eagerly, hoping for a fight.]}
{1341}{}{You're mixing it up with the wrong "drunk", miss. I ain't above teaching a smart-mouthed bitch like you some manners. [He puts his glass down with a thump on the table. The others look around eagerly, hoping for a fight.]}
{1342}{}{Wait, you're not going to hit me, are you?}
{1343}{}{Let's see what you've got, asshole.}
{1344}{}{Sorry, didn't really mean to go all the way through.}

# Node040
{1370}{}{Not really. I don't see her at all. She never comes here. We prepare her meals here, and then they are delivered to her quarters.}
{1371}{}{Interesting. Thank you, Jon.}
