# Message file for tbprsn.ssl
# Number of nodes: 1

{102}{}{You see a Brotherhood of Steel member.}

{200}{}{I wonder what the old turbine engines were really like.}
{201}{}{I love working on new prototypes.}
{202}{}{When our supplies are limited it can really be a challenge to find a way to use what we've got.}
{203}{}{I can't figure out why my last prototype didn't work.}
{204}{}{I'd like to get my hands on those NCR bastards. Show them what we're made of.}
{205}{}{Now where did I put that file?}
{206}{}{Where's that schematic?}
{207}{}{Well, the computer says it should work. Now what did I do wrong?}
{208}{}{Boy, I wish we had an automobile.}
{209}{}{Did you know that man has been on the moon? Or, at least, I think that's what they said.}
{210}{}{Can you imagine what life would be like without technology? Well, I guess you've probably seen things pretty close to that.}
{211}{}{I can't find the file I need.}
{212}{}{I'll be a Paladin someday.}
{213}{}{Sister Traci is a skilled warrior. I would never want to have to go up against her.}
{214}{}{Brother Reggie is the best fighter in the Brotherhood. I bet he could kick Elder Jerry's butt.}

# directly spoken too extra lines
{215}{}{That's it... what? Oh, sorry. I can't talk right now.}
{216}{}{I wonder what would happen if I... huh? Oh, you made me lose my train of thought.}
{217}{}{Sorry, I can't talk right now.}
