# Message file for mblib.ssl
# Number of nodes: 2

{100}{}{}

# Node001
{200}{}{Maxson Bunker Network initialized. Welcome to the Brotherhood of Steel Library. For any inquiries, contact the Knights.}
{201}{}{[Download schematics for Magneto-Laser Pistol]}
{202}{}{[Download schematics for Laser Rifle (Ext. Cap.)]}
{203}{}{[Download schematics for Plasma Pistol (Ext. Cap.)]}
{204}{}{[Download schematics for XL70E3]}
{205}{}{[Download schematics for Tesla Armor]}
{206}{}{[Download schematics for Brotherhood Armor]}
{207}{}{[Download schematics for Hardened Power Armor]}
{208}{}{[EXIT]}

# Node002
{230}{}{[You download the schematic to your Pip-Boy]}
{231}{}{[BACK]}
