# Message file for mbtamara.ssl
# Number of nodes: 60
# Grammar pass done

{100}{}{You see a pretty young woman in her early twenties.}
{101}{}{It's Tamara, working tirelessly as one of the dedicated Brotherhood of Steel cooks.}
{102}{}{She appears exhausted as she struggles to keep up with the constant demands of the personnel.}

{150}{}{Jon!}
{151}{}{Guards! The thief is back!}

# Tamara's basic floats.
{200}{}{I think you've had enough, buddy.}
{201}{}{I'll need to get another crate soon.}
{202}{}{Can't wait for closing time.}
{203}{}{I wish the Scribes would invent an AutoCook.}
{204}{}{No, you can't have a tab, not even this time.}
{205}{}{You people could drink Hoover Dam dry.}

# These are the strings Tamara floats if the variable Tamara_Robbery>0, meaning that the PC has successfully robbed her.
{230}{}{I don't think the canteen will recover from this.}
{231}{}{I should have told Jon about the robbery.}
{232}{}{Fat lot you Paladins were when I was being robbed.}
{233}{}{I won't even be able to afford the next consignment of water.}
{234}{}{I can't handle this anymore!}
{235}{}{If that asshole robber shows up again, I'll shoot to kill!}

# Tamara_1a_1
{260}{}{[Looking up from her work.] Hey there, Brother. Welcome to Youngs' Canteen, run by Jon and me. What can I get you?}
{261}{}{[Looking up from her work.] Hey there, Sister. Welcome to Youngs' Canteen, run by Jon and me. What can I get you?}
{262}{}{You must be Tamara?}
{263}{}{What do you have available?}
{264}{}{I'd like to buy a round for the whole canteen.}
{265}{}{[In a hushed tone.] Just hand over your valuables, and nobody has to get hurt.}
{266}{}{Nothing for now, thanks.}
{267}{}{What do you have?}
{268}{}{[Leave.]}

# Tamara_1a_2
{290}{}{[She stares at you for a moment.] That's right. What can I get you?}

# Tamara_1a_2D_1
{320}{}{Well, what do you want? A drink? Something to eat?}
{321}{}{Me thirsty.}
{322}{}{Me want eat.}
{323}{}{Me no want those. [Leave.]}

# Tamara_1a_2D_2
{350}{}{[She looks at you thoughtfully for a moment.] I think it's best if you don't have any of the hard stuff. Would you like a Nuka-Cola or some water?}
{351}{}{Nukie-Cool.}
{352}{}{Walter.}

# Tamara_1b_1
{380}{}{Hello again. Are you thirsty?}
{381}{}{Could you remind me of what's on offer, please?}
{382}{}{I'm looking for some food. Do you have anything available?}
{383}{}{I'd like to buy everyone a drink. The tab's on me.}
{384}{}{No, I was just saying hello. Maybe next time. Goodbye.}
{385}{}{Me thirst?}
{386}{}{No. }
{387}{}{ go.}

# Tamara_2_1
{410}{}{[Tamara turns on the intercom so everyone in the canteen can hear her.] Drinks are on this generous gentleman here, Brothers and Sisters. Come and get 'em.}
{411}{}{[Tamara turns on the intercom so everyone in the canteen can hear her.] Drinks are on this generous lady here, Brothers and Sisters. Come and get 'em.}
{412}{}{[CONTINUE]}

# Tamara_2_2
{440}{}{[A ragged cheer erupts as the Brotherhood members swarm the bar.]}

# Tamara_2_3
{470}{}{[Tamara quickly takes orders from the members and then gets your attention amidst the noise.] That'll be fifty caps, Brother. Can you handle it?}
{471}{}{[Tamara quickly takes orders from the members and then gets your attention amidst the noise.] That'll be fifty caps, Sister. Can you handle it?}
{472}{}{No problem. Here you go. [Hand her the money.]}
{473}{}{Actually... I can't afford it.}

# Tamara_2_4a
{500}{}{[The Brotherhood members grab their drinks, give you friendly back-slaps, and return to their seats.] Care to have a drink yourself, Brother?}
{501}{}{[The Brotherhood members grab their drinks, give you friendly back-slaps, and return to their seats.] Care to have a drink yourself, Sister?}
{502}{}{No, thanks. Goodbye.}

# Tamara_2_4b_1
{530}{}{Ahh, for crying out loud. [She turns on the intercom again.] Sorry, folks, false alarm. The Beer Fairy here can't afford it.}

# Tamara_2_4b_2
{560}{}{[With a collective groan, the Brotherhood members disperse from the bar, muttering some choice insults as they go. Tamara gives you a reproachful look.]}
{561}{}{I could still use a drink.}
{562}{}{Do you have any food available?}
{563}{}{Goodbye.}

# Tamara_3_1
{590}{}{I have water, Nuka-Cola, beer, and liquor.}
{591}{}{I'll have water.}
{592}{}{I'll have a Nuka-Cola.}
{593}{}{I'll have a beer.}
{594}{}{Give me some liquor.}
{595}{}{I'll get one another time. Goodbye.}

# Tamara_3_2a_1
{620}{}{Yup.}
{621}{}{What's on the menu today?}
{622}{}{I'll come back later. Goodbye.}

# Tamara_3_2a_2
{650}{}{Today we have jerky and Iguana Shish-Kebab.}
{651}{}{How much is a portion of jerky?}
{652}{}{How much is an Iguana Shish-Kebab?}
{653}{}{I think I'll have a drink instead. What do you have?}
{654}{}{Gimmie jerk.}
{655}{}{Ig-wun Shish-bib!}
{656}{}{Want drink, not eat, now.}

# Tamara_3_2a_3a_1
{680}{}{A portion of jerky costs five caps.}
{681}{}{Here are five caps.}
{682}{}{I'm sorry, but I can't afford five caps.}
{683}{}{[Pay.]}
{684}{}{Me thirsty now. Not want eat.}
{685}{}{Gah! [Leave.]}

# Tamara_3_2a_3a_2a
{710}{}{Alright. Here's your jerky. Enjoy!}
{711}{}{By the way, what can you tell me about the Brotherhood of Steel?}
{712}{}{Actually, I could use a drink now.}
{713}{}{I might want to order more food. What else do you have?}
{714}{}{I have to be going now.}
{715}{}{Want drink, now.}
{716}{}{More food.}
{717}{}{Me go.}

# Tamara_3_2a_3a_2b
{740}{}{In that case, you probably won't be able to afford the Iguana Shish-Kebab either. Would you like a drink instead?}
{741}{}{Sure, what drinks do you have?}

# Tamara_3_2a_3b_1
{770}{}{The Iguana Shish-Kebab is priced at eight caps.}
{771}{}{Here are eight caps for one.}
{772}{}{I'm sorry, but I can't afford eight caps.}

# Tamara_3_2a_3b_2a
{800}{}{Alright. Here's your Iguana Shish-Kebab. Enjoy!}
{801}{}{I'd like to order more food.}
{802}{}{Actually, I've changed my mind. I'll have a drink instead.}

# Tamara_3_2a_3b_2b
{830}{}{Hmm, in that case, you might want to try the jerky instead.}
{831}{}{How much is that?}
{832}{}{Actually, I think I'd prefer a drink.}

# Tamara_3_2b_1
{860}{}{Water's two caps a mug.}
{861}{}{You want me to pay for water?}
{862}{}{Here's the two caps.}
{863}{}{Sorry, I can't even afford that.}
{864}{}{Actually, hold the drink. I have to be going.}

# Tamara_3_2b_2a_1
{890}{}{Of course. It used to be free, but then the business went downhill with the war, members deserting, and the water chip broke. You get the picture. Do you have two caps or not?}
{891}{}{Where did the water chip break?}

# Tamara_3_2b_2a_2
{920}{}{You don't know where our water recycling facility is? [She looks surprised.] Go ask Ed. He'll tell you all about it.}
{921}{}{Here's two caps for the water.}
{922}{}{Sorry, I can't even afford two caps for the water.}

# Tamara_3_2b_2b
{950}{}{Here you go. [She puts a mug filled with clean-looking water in front of you. You drink it.]}
{951}{}{I could use another drink.}
{952}{}{What do you have in the way of food?}
{953}{}{More drink.}
{954}{}{Food, now.}
{955}{}{*Burp* Hah! 'Bye.}

# Tamara_3_2b_2c
{980}{}{Ah, hell. I can't have you dying of thirst. Come on, this one's on me.}
{981}{}{Thanks!}
{982}{}{No, if water costs two caps, I'll go and earn them. Goodbye.}

# Tamara_3_2c_1
{1010}{}{Nuka Cola's three caps a bottle.}
{1011}{}{Here's the three caps.}
{1012}{}{Sorry, I can't afford that.}

# Tamara_3_2c_2a
{1040}{}{Here you go. [She gives you a bottle of the flavored soft drink.]}

# Tamara_3_2c_2b_1
{1070}{}{Only thing we've got cheaper than Nuka is water.}
{1071}{}{How much is that?}
{1072}{}{I might have something to eat instead.}

# Tamara_3_2c_2b_2
{1100}{}{Forget it. You wouldn't be able to afford anything on the menu.}
{1101}{}{What drinks do you have on offer, again?}
{1102}{}{I'd better be going, then.}

# Tamara_3_2d_1
{1130}{}{Beer's five caps a bottle.}

# Tamara_3_2d_2a
{1160}{}{Here you go. [She gives you a bottle of beer.]}

# Tamara_3_2d_2b
{1190}{}{Well, the only drinks we've got cheaper than beer are Nuka Cola or water.}
{1191}{}{How much is water?}
{1192}{}{How much is a Nuka Cola?}

# Tamara_3_2e_1
{1220}{}{Sure. Having a bad day, or something?}
{1221}{}{Not really, no. I just fancy something strong. How much is it?}
{1222}{}{You could say that.}

# Tamara_3_2e_2a_1
{1250}{}{The strong booze is ten caps a bottle.}
{1251}{}{Here's ten caps. Let's have it.}
{1252}{}{Sorry, I can't afford it.}

# Tamara_3_2e_2a_2a_1
{1280}{}{Here you go. [She gives you a bottle of strong liquor.] That'll do the job, if nothing else will.}

# Tamara_3_2e_2a_2a_2
{1310}{}{You still want more? [She looks at you in mild alarm.]}
{1311}{}{Yes. Keep them coming.}
{1312}{}{Actually, no, I'd better have something to eat. What do you have?}

# Tamara_3_2e_2a_2b
{1340}{}{How about a beer instead?}
{1341}{}{How much is a beer?}
{1342}{}{I might go for something to eat, actually. What's on the menu?}

# Tamara_3_2e_2b_1
{1370}{}{You want to talk about it?}
{1371}{}{I've got a lot of people depending on me. It's too much to bear at times.}
{1372}{}{Not really. How much was that drink, again?}

# Tamara_3_2e_2b_2
{1400}{}{Yeah, I know where you're coming from, buddy. [She looks around at the canteen's visitors wearily.]}
{1401}{}{Yeah, I know where you're coming from, sister. [She looks around at the canteen's visitors wearily.]}
{1402}{}{It's like everyone I know would die if I wasn't here.}
{1403}{}{Anyway, how much was that drink, again?}

# Tamara_3_2e_2b_3
{1430}{}{Amen to that! [She picks up a glass and begins polishing it with a towel.]}
{1431}{}{Sometimes I'd like to wander off and just leave them to fend for themselves, you know?}

# Tamara_3_2e_2b_4
{1460}{}{[Tamara flicks her towel and laughs.] You know, I wake up to that thought every morning.}

# Tamara_3_2e_2b_5
{1490}{}{Forget about it, buddy. This one's on me. Here you go.}
{1491}{}{Forget about it, sister. This one's on me. Here you go.}
{1492}{}{So what can you tell me about Maxson Bunker?}
{1493}{}{Thanks. I ought to be going, though.}

# Tamara_3_2e_2b_9
{1520}{}{It sure is a hard life. You still want that drink?}
{1521}{}{Yes, please. How much was it?}
{1522}{}{Actually, no. I have to be going.}

# Tamara_4_1
{1550}{}{The Bunker is a decent enough place to live. I grew up in a small wasteland town and, although not stupid, had no opportunity to improve my place in life. I feel safe here. And busy! There's plenty of hungry mouths around, so we're never short of business, although it had been better before the war. Bloody NCR. If you want the full low-down on the place, though, you should go and talk to the Elders. What they don't know about the Bunker ain't worth knowing.}
{1551}{}{Where can I find the Elders?}
{1552}{}{What are you serving in the way of food?}

# Tamara_4_2
{1580}{}{I think you will find them on the first and second levels. Unless they're meeting the Commander on the third one, but I doubt it. Since she has been sick, she's not meeting anyone except Sarah. I've even started selling her craft beer to others.}
{1581}{}{How come?}
{1582}{}{Okay. I'd better be going, then.}

# Tamara_B1_a1
{1610}{}{[Her expression does not change, but she looks like she might be reaching behind her back for something.]}
{1611}{}{Whatever it is, leave it, and put both your hands where I can see them.}
{1612}{}{[Draw weapon.]}

# Tamara_B1_a2
{1640}{}{Okay. [Tamara slowly puts her hands up, with her fingers spread. She swallows nervously.] You want the money, right?}
{1641}{}{That's right. Where is it?}
{1642}{}{Never mind. [Leave.]}

# Tamara_B1_a3
{1670}{}{Behind me, in the last fridge. [Without turning round, she indicates with a backward nod of her head.]}
{1671}{}{Go and get it. And don't try anything smart.}

# Tamara_B1_a4
{1700}{}{[Tamara goes to the fridge and unlocks it with a small key. Its door gives a complaining squeak as she opens it.]}

# Tamara_B1_a5_a1
{1730}{}{[She comes back to you and offers a sack full of bottle caps. You see tears running down her face.]}
{1731}{}{[Take the caps.]}
{1732}{}{[Leave without taking the caps.]}

# Tamara_B1_a5_a2
{1760}{}{[Having given you the sack of caps, Tamara screws her eyes up and turns away.]}
{1761}{}{This better be all of them, or I'm coming back.}

# Tamara_B1_a5_b1
{1790}{}{[Jon's attention is aroused by the squeak. He looks up and gives you a suspicious glance. With his eyes still on you, he speaks.] Everything okay, Tam? Baby?}
{1791}{}{[Fight.]}

# Tamara_B1_a5_b2_a1
{1820}{}{[Tamara is still facing away from both you and Jon.] Yeah, everything's fine, dear.}

# Tamara_B1_a5_b2_a2
{1850}{}{[Jon shrugs and looks away. Tamara comes back to you and offers a sack full of bottle caps. You see tears running down her face.]}
{1851}{}{You just saved your life and his life. Now, hand the caps over.}

# Tamara_B1_a5_b2_b
{1880}{}{[Tamara looks around at Jon with a tear-streaked face. He glances from Tamara to you quickly, sizing up the situation. After a few seconds, he picks up a knife from the table and starts walking towards you menacingly.] What the hell is going on here?}
{1881}{}{I was... that is to say... err...}

# Tamara_B1_b1
{1910}{}{[She pulls a laser pistol out and levels it at your belly.] Don't think I won't use this, mister. Get the hell out of my kitchen.}
{1911}{}{[She pulls a laser pistol out and levels it at your belly.] Don't think I won't use this, sister. Get the hell out of my kitchen.}
{1912}{}{Put that pea-shooter away. You don't want to be making trouble with me.}

# Tamara_B1_b2
{1940}{}{[Tamara pulls the laser pistol's trigger.]}

# Node058
{1970}{}{Her beer is usually stored in a container inside the storage room. Not sure if it was me or Jon, but the lid wasn't properly closed, so I had to get rid of it fast... before it became spoiled. I'm sure the Commander wouldn't mind.}
{1971}{}{Interesting. Thanks for the info, Tamara.}
