# Message file for mvhex.ssl 
# Number of nodes: 16

{100}{}{You see a young Cipher with long hair.}
{101}{}{You see Hex.}
{102}{}{He seems to be perpetually on duty.}

# Node001
{200}{}{Hey, you! Don't move or I'll shoot! Who are you?}
{201}{}{I'm }
{202}{}{. Who are you?}
{203}{}{Me }
{204}{}{. Who you?}
{205}{}{Shut up and die, tribal!}
{206}{}{You die!}

# Node002
{230}{}{Hey, I can't talk right now.}
{231}{}{Goodbye.}
{232}{}{'K.}

# Node003
{260}{}{Uh, I'm Hex. What are you doing here?}
{261}{}{I'm exploring. What is this place?}
{262}{}{Me exploring. What here?}
{263}{}{I'm looking for a particular electronic part, and I've heard the Ciphers might have what I'm looking for.}
{264}{}{Me need part. Me told it be here.}
{265}{}{I'm here to kill you all.}
{266}{}{Me kill you all!}

# Node004
{290}{}{This is Mesa Verde. How'd you get past the Hounds in the canyon?}
{291}{}{I killed them all.}
{292}{}{Me kill them.}
{293}{}{I snuck past them. So, can I come inside now?}
{294}{}{Me sneaky. Um, you in me way. Move.}
{295}{}{I flew over them, of course. It's the only way to travel.}

# Node005
{320}{}{You... you did? Well, uh, I guess you can come into the village, then.}
{321}{}{[END]}

# Node006
{350}{}{Uh, I'm not sure if I'm supposed to let you inside.}
{351}{}{You're the only guard I see, and you don't *know* if you can let me inside?}
{352}{}{Me not understand.}
{353}{}{Let me in right *now* or I'll take that crappy rifle of yours and shove it so far up your ass you'll be tasting gunpowder for weeks.}
{354}{}{Me go in *now* or me tear you arm off and beat you!}

# Node007
{380}{}{*gulp* Go right in, sir.}
{381}{}{*gulp* Go right in, ma'am.}

# Node008
{410}{}{Ha! If *that's* as scary as you can get, then I suppose I could handle you if you make trouble. Go on in.}

# Node009
{440}{}{Oh. You'd have to talk to Trig about that.}
{441}{}{All right, I will. So, are you going to let me in or what?}
{442}{}{Okay. Um, you still in me way.}

# Node010
{470}{}{Look, I may be young, but I'm not stupid. I know outsiders can't fly. Um, you can't... right?}
{471}{}{Yes, I was joking. Actually, I'm exploring. Are you going to let me in your village?}
{472}{}{I'm a mutant. All mutants fly. Therefore, I can fly.}

# Node011
{500}{}{I'm new! I was only told to watch out for the Hounds. Nobody ever said anything about other visitors.}
{501}{}{Well, let me talk with your leader. If he doesn't like me, he can have you throw me out. How's that sound?}

# Node012
{530}{}{It's just that... over, never mind. You can come in.}

# Node013
{560}{}{Wow! Can I see?}
{561}{}{Not right now. Are you going to let me in, or do I, uh, need to fly over you?}

# Node014
{590}{}{You're just making fun of me 'cause you think I'm still a kid.}
{591}{}{Sorry. Now, are you going to let in or what?}

# Node015
{620}{}{Yeah, sure. You have to come back and show me how you can fly, okay?}

# Node016
{650}{}{I guess that'll be okay. You can come in.}
