# Message file for nrakeish.ssl
# Number of nodes: 6
# Grammar pass done

{100}{}{You see a young tribal woman.}
{101}{}{You see Akeisha Moon.}
{102}{}{She's wearing clothes with a ringed cross symbol.}

# Node001
{200}{}{Hello, wanderer. My name is Akeisha Moon. And you are?}
{201}{}{Hi Akeisha, I'm }
{202}{}{ from Tibbets. What is that symbol on your clothes?}
{203}{}{Just a traveler. I noticed the symbol on your clothes - you're a Follower? What are you doing here?}
{204}{}{I'm the robber and this is a robbery!}
{205}{}{No one, really. Bye.}
{206}{}{Unh.}

# Node002
{230}{}{Yes, I'm a member of the Followers of the Apocalypse. I've spent most of my life searching for the vaults, trying to uncover the lost knowledge within them.}
{231}{}{Found any?}
{232}{}{ODYSSEUS has been looking for us since our escape. I suggest you return or at least hand over your Pip-Boy.}

# Node003
{260}{}{I've discovered two so far. But there are many more out there, hidden beneath the rubble of the old world.}
{261}{}{Well done. And now you ended up in this cave of all the places. Is there a vault here too?}

# Node004
{290}{}{It's a long story. I was researching a situation with a local tribe, their brahmin were mysteriously dying. But one night, the tribe was attacked. I was knocked unconscious.}
{291}{}{And then?}

# Node005
{320}{}{And then I woke up in a big prison. I was held captive for days. Then, there was this explosion. The forcefield of my cell shut down, and I ran.}
{321}{}{So you ended up here?}

# Node006
{350}{}{Exactly. I wandered for weeks, until I found this cave. It was the sound of running water that drew me in. And then... I found this. [She gestures around you.] The Nursery. A living, breathing oasis in the middle of a barren wasteland.}
{351}{}{[CONTINUE]}

# Node007
{380}{}{I've been invited to speak with the curator of the Nursery. There's so much to learn here. This place... it's a symbol of hope, of life. Exactly what the Followers are seeking.}
{381}{}{Good luck exploring the place. Who knows, I might check it out myself. So long.}
{382}{}{Alright, just one thing before you leave. ODYSSEUS has been looking for us since our escape. I suggest you return or at least hand over your Pip-Boy.}

# Node008
{410}{}{Hahaha! Why on earth would I want to go back to that hellhole? And this Pip-Boy saved my life more times than I can count. Your suggestions are a fantasy.}
{411}{}{I understand your hesitations. But returning might be in your best interest. ODYSSEUS is relentless and you'll always be looking over your shoulder. Why not investigate Tibbets, parts of it were built by Vault-Tec just like the vaults you are searching for.}

# Node009
{440}{}{Hmm. You're smart, trying to appeal to my sense of curiosity. But why should I trust you? What's in this for you?}
{441}{}{I just want ODYSSEUS to leave us alone. You escaping Tibbets and being on the run doesn't help that. I've seen the damage, the chaos. And the Pip-Boy? It's technology that belongs to Tibbets and it is used to track our movement. I'm just trying to retain our freedom.}

# Node010
{470}{}{Well, you have a point. As a member of the Followers of the Apocalypse, I have to keep moving and exploring. But the spying Pip-Boy, I can do without. Take it.}
{471}{}{Thanks, Akeisha.}

# Node011
{500}{}{Calm down, alright? I only have my Pip-Boy with me. Just take it, don't hurt me, OK?}
{501}{}{Well, that's better than nothing.}
{502}{}{I don't trust you. You're hiding something!}

# Node012
{530}{}{Oh, it's you again.}
{531}{}{I noticed the symbol on your clothes - you're a Follower? What are you doing here?}
{532}{}{I've come back to rob you! Hands high up in the air so I can see them!}
{533}{}{Oh, it's nothing.}
