{100}{}{Happy New Year's Day!}      # New years
{101}{}{Happy Valentine's Day!}     # Valentine's Day
{102}{}{Happy All Fool's Day!}      # April fools
{103}{}{Happy Ship Day!}            # Shipping day!
{104}{}{Happy Independence Day!}    # Independence day
{105}{}{Happy Halloween!}           # Halloween
{106}{}{Happy Thanksgiving Day!}    # Thanksgiving
{107}{}{Merry Christmas!}           # X-mas

{200}{}{Welcome to the RobCo Lil-Pip 3000.}
{201}{}{So long.}
{202}{}{Doo da doo da dum dee dee doodly doo dum dum dum doo da doo da doo da doo da doo da doo da doo}
{203}{}{"The spread of civilization may be likened to a fire; first, a feeble spark, next a flickering flame, then a mighty blaze, ever increasing in speed and power." -Nikola Tesla}
{204}{}{"I can calculate the motion of heavenly bodies, but not the madness of people." -Sir Isaac Newton}
{205}{}{Mr. Fixit! upgrade installed and ready to assist.}

{300}{}{Wake up.}
