# Message file for tbprsn.ssl
# Number of nodes: 1

{100}{}{You see a ghoul.}
{102}{}{It seems to have been human once, or at least descended from humans.}

# Node 0 [Floats]

{200}{}{Vete.}
{201}{}{¿Qué quieres?}
{202}{}{Déjame solo.}
{203}{}{¿Qué?}
{204}{}{No te metas en mis cosas.}
{205}{}{Hola.}
{206}{}{¿Crees que eres mejor que yo?}
{207}{}{Los necrófagos son el siguiente paso en la cadena evolutiva.}
{208}{}{No te metas conmigo.}

{300}{}{Go away.}
{301}{}{What do you want?}
{302}{}{Leave me alone.}
{303}{}{What?}
{304}{}{Don't mess with my stuff.}
{305}{}{Hello.}
{306}{}{Do you think you're better than me?}
{307}{}{Ghouls are the next step in the evolutionary chain.}
{308}{}{Don't mess with me.}
