{100}{}{This is our territory.}
{101}{}{You're not wanted here.}
{102}{}{I think you need to pay a toll.}
{103}{}{We don't usually scavenge off the living.}
{104}{}{That's some nice stuff you have there.}
{105}{}{You'll pay for this.}
{106}{}{Next time.}
{107}{}{Running's a bitch!}
{108}{}{You get to keep your stuff... this time.}

{200}{}{Thiis ote surrto riry.}
{201}{}{Yonowahe u'retrented.}
{202}{}{Ine thill payyou toa tonk ed.}
{203}{}{Weusscali n'tu dovenge offally theving.}
{204}{}{Thasonis tuyouhathe t's mece ffvere.}
{205}{}{Yopa u'lly foth ris.}
{206}{}{Neti xtme.}
{207}{}{Rubi anni ng'stch!}
{208}{}{Yogeto keyo stu thiti utep urff... sme.}
