# Message file for sclnccmp.ssl
# Number of nodes: 9

{102}{}{The faded label next to the monitor seems to read "Mission Control".}

{103}{}{The monitor displays a whimsical message: Don't forget your space suit, cowboy!}
{104}{}{The monitor flashes a message: **Docking Clamp Control CRITICAL FAILURE!** Manual diagnostics required at Launchpad 01. Please perform an onsite check immediately.}
{105}{}{You have entered legitimate Mission Control Launch Codes. You board the Hermes-XIII space rocket.}

# Node_002
{230}{}{Recovering from emergency shutdown... Performing hardware diagnostics... errors found.  Checking for local boot routine... found. Checking network connectivity... no connection found. Boot? Y/N}
{231}{}{[Yes]}
{232}{}{[No]}

# Node_003
{260}{}{The screen is just showing static. The power is off.}
{261}{}{[Leave and find a way to restore power]}

# Node_004
{290}{}{[The computer hums and grunts] ...Boot successful. Login?}
{291}{}{[Login as Dr. Willem Clark]}
{292}{}{[Administrator Override]}
{293}{}{[Login as Guest]}
{294}{}{[Hack the Mainframe]}
{295}{}{[Exit]}

# Node_004a
{320}{}{Login?}
{321}{}{[Login as Administrator]}

# Node_005
{350}{}{Welcome to Bloomfield Space Center Network. Command?}
{351}{}{[Workstation Details]}
{352}{}{[Enter Launch Codes]}
{353}{}{[Logoff]}
{354}{}{[Hack Launch Codes]}
{355}{}{[List Launch Details]}

# Node_006
{380}{}{Workstation ID: Mission Control Launch Codes}
{381}{}{[Back]}

# Node007
{440}{}{Access denied.}

# Node008
{470}{}{The list is empty.}

# Node009
{500}{}{[There's a record of Hermes-14 rocket taking off for B.O.M.B.-001 space station. The passenger list includes Dr. Victor Presper and his party among the others. It seems to have been a one-way trip.]}

# Node010
{530}{}{Launch requirements failure. Aborting! Please check with Mission Control Access.}

# Node_011
{410}{}{Guest login refused. This station is for registered use only. Last Login: 00PJ@BSCnet:HQ}
