# 0. QUICK LOOK
{100}{}{You see a member of Rusty Hooks.}

# 0. LOOK
{150}{}{You see a rugged looking gang member dressed in metal armor. Numerous scars and gunshot wounds cover his body. His armor and weapons, on the other hand, look well-maintained, almost new.}
{151}{}{You see a well-armed gang member. He is scanning the area and fingering his weapon.}

{152}{}{You see a rugged looking gang member dressed in metal armor. Numerous scars and gunshot wounds cover her body. Her armor and weapons, on the other hand, look well-maintained, almost new.}
{153}{}{You see a well-armed gang member. She is scanning the area and fingering her weapon.}

# 1. FLOAT DIALOGUE: INTRUDER (WTG)
{200}{}{Well, look at the brass balls on this son of a bitch...}
{201}{}{Contact!}
{202}{}{The base's been breached!}
{203}{}{Hooks, we got us an intruder!}
{204}{}{Scramble, Hooks, we got an intruder!}
{205}{}{Well, look who stopped in ta die...}
{206}{}{Damn! Somebody found us!}
{207}{}{You got some sand comin' in here...}
{208}{}{You just walked into the *wrong* place.}
{209}{}{Well, look at the swagger on this brahma dung...}
{210}{}{Gonna make you rust away!}
{211}{}{Fun ahead!}
{212}{}{Don't die too quickly.}
{213}{}{Nice you could stop by.}
{214}{}{You have gas?}
{215}{}{Time to raid you!}
{216}{}{*BANG* *BANG* *BANG*}
{217}{}{*BOOM* You're dead!}
{218}{}{You'll regret trespassin'.}
{219}{}{Die, worm!}
{220}{}{I raid, therefore I am.}
{221}{}{Die, city walker!}
{222}{}{Flee before me, puny one!}
{223}{}{Hooks of death! Attack!}
{224}{}{Rusty Hooks, get that dipshit!}
{225}{}{Hooks bring death.}
{226}{}{When you die, hooks take you away.}
{227}{}{Fly with us to the Moon.}
{228}{}{Target practice!}
{229}{}{Yeeeeeeeeeaaaaaaaah!}
{230}{}{You trespassin'. Now you dyin'!}

# 2. FLOAT DIALOGUE: NORMAL (WTG)
{250}{}{We went out drinking, and he called it "attitude adjustment hour," so we kicked his ass.}
{251}{}{We need to check those funny-lookin' guys by the launch pad...}
{252}{}{Almost time to do another check of the perimeter...}
{253}{}{Man, the tribals *stinks.* All their kind do.}
{254}{}{Damn turrets and security robots...}
{255}{}{Tired of polishing my gun...}
{256}{}{We found this place first, get it?}
{257}{}{Those Battalion people should be movin' out in a few days...}
{258}{}{Can't wait ta get back on the road. *'Specially* the raids.}
{259}{}{Them scorps are gettin' hungry again. Heard 'em clicking last night...*click* *clack* *click*}
{260}{}{Did you check the Sub-Reactor? Sid will appreciate *any* help.}
{261}{}{Kyle's breathing down my neck again cause I almost let that one merchant get away...}
{262}{}{I wonder how I can get out of this metal outfit.}
{263}{}{Jill's a good-looking woman. Well, in a aristocratic kind of way. Is that even a word... aristocratic?}
{264}{}{...so then *she* says, 'that's my belly button, dipshit!' Haw! That joke *always* kills me.}
{265}{}{Good to go.}
{266}{}{Wouldn't want to cross paths with Bear.}
{267}{}{I feel like I've been standing here forever, just waiting for somebody to show. Are you that somebody?}
{268}{}{Wish I had some other planet I could go to.}
{269}{}{I don't like your mug.}
{270}{}{I'm gonna rustle me up some possum stoo!}
{271}{}{Get away from me!}
{272}{}{I'll slap you so hard, your clothes will be outta style.}
{273}{}{I'll throw you in the outhouse, you wimpy hick...}
{274}{}{I wish you gave me a reason to kill you.}
{275}{}{You with Hooks now?}
{276}{}{I don't trust you.}
{277}{}{You'll end up as a coyote food anyway.}
{278}{}{I hope coyotes are hungry.}
{279}{}{Scram!}

{300}{}{Feeling so weak.}
{301}{}{Damn, you're worse than I thought.}
{302}{}{You're like a walking death.}
{303}{}{You won't be the doom of me.}
{304}{}{I'm sorry, 'K?}
{305}{}{I'm just not ready yet!}
{306}{}{It's not my time yet!}
{307}{}{I attacked you accidentally.}
{308}{}{Let me go and I'll put up a good word for you.}
{309}{}{I need to lie down a bit.}

{400}{}{You'll pay for stealing Kyle's precious dune buggy!}
