# Message file for scsubrec.ssl
# Number of nodes: 17

{100}{}{You see a Generator Control computer.}
{101}{}{It's still the Generator Control computer.}
{102}{}{You see a barely functional computer console. A plaque above the monitors reads: "Generator Control".}

{150}{}{You restored the Sub-Reactor's efficiency from 45% to 85%.}

# Node_001
{230}{}{The console is off. The monitors are blank.}
{231}{}{[Power up the console]}
{232}{}{[Walk away]}

# Node_002
{260}{}{WARNING: Auxiliary reserves low. Engage auxiliary generators? Y/N}
{261}{}{[Yes]}
{262}{}{[No]}

# Node_003
{290}{}{Auxiliary Generators online.}
{291}{}{[Continue]}

# Node_004
{320}{}{GENERATOR CONTROL: Command? >}
{321}{}{[Engage Primary Generators]}
{322}{}{[Disengage Primary Generators]}
{323}{}{[Engage Auxiliary Generators]}
{324}{}{[Disengage Auxiliary Generators]}
{325}{}{[Status Report]}
{326}{}{[Advanced Power Management]}
{327}{}{[Logoff]}

# Node_005
{350}{}{Access restricted. An emergency lockdown is in effect. Report to Security Control on Level 1.}
{351}{}{[Attempt to override the lockdown]}

# Node_006
{380}{}{Primary generators shutting down...}

# Node_007
{410}{}{Auxiliary generators disengaged. Hibernate? Y/N}

# Node_008
{440}{}{Executive override: Code 16. Primary generators engaged. A security robot has been dispatched to your location.}

# Node_009
{470}{}{Hibernating... [The monitor goes dark]}
{471}{}{[End]}

# Node_010
{500}{}{POWER MANAGEMENT: Command? >}
{501}{}{[Divert power from Habitation & Administration]}
{502}{}{[Divert power from Operations & Communications]}
{503}{}{[Divert power from Rocket Assembly]}
{504}{}{[Restore power to Sub-Reactor]}
{505}{}{[Generator Control]}

# Node_011
{530}{}{Diverting power from Level 1: Habitation & Administration...}

# Node_012
{560}{}{Diverting power from Level 2: Operations & Communications...}

# Node_013
{590}{}{Diverting power from Rocket Assembly...}

# Node_014
{620}{}{Restoring power to Sub-Reactor...}

# Node_020
{650}{}{Sub-Reactor: <!ERROR> Security Fields: <1/0> Security Robots: <1/0> Automated Systems: <1/0> Museum: <1/0>}
{651}{}{[Run diagnostics on the Sub-Reactor systems]}

# Node_021
{680}{}{Starting Diagnostics... failed. The system is not responding. Please contact maintenance.}
{681}{}{[Back to Status Report]}
