# Message file for sebob.ssl
# Number of nodes: 12
# Grammar pass done

{100}{}{You see a used car dealer.}
{101}{}{You see Bob, the dealer.}
{102}{}{He's an odd one.}

# Node 0 [Floats]
{200}{}{Hey there! I'm Bob.}
{201}{}{Feel free to take one of these beauties for a spin.}
{202}{}{Don't forget the rust preventive paint.}
{203}{}{How about an auto alarm to keep those wasteland bandits at bay?}
{204}{}{Sorry, on my coffee break. Come back later.}

# Node001
{230}{}{Greetings! Welcome to my previously owned car lot. Interested in any of these fine machines today?}
{231}{}{These cars look like they've been through hell and back.}
{232}{}{Nothing catches my eye, thanks.}
{233}{}{Silence, peasant. I'm }
{234}{}{, a new breed of wasteland royalty. Kneel before me and kiss my feet.}
{235}{}{Lug!}

# Node002
{260}{}{Apologies, but you don't seem like you can handle our financing rates.}
{261}{}{Gug!}

# Node003
{290}{}{But sir, these vehicles are in prime condition.}
{291}{}{Ma'am, these are top-notch rides.}
{292}{}{They can't be in working condition.}
{293}{}{Yeah, right. Okay. Bye.}

# Node004
{320}{}{Our cars undergo a rigorous 100-point service by our expert mechanics.}
{321}{}{Where's your service department located?}
{322}{}{You're out of your mind.}
{323}{}{Goodbye.}

# Node005
{350}{}{Just over there, sir. [The dealer points to nothing.]}
{351}{}{Just over there, ma'am. [The dealer points to nothing.]}
{352}{}{Where? I don't see anything.}
{353}{}{You're crazy.}

# Node006
{380}{}{What do you mean? They're working on a newly purchased '56 Corvega. A fantastic deal, if you ask me.}
{381}{}{Sure, whatever you say.}
{382}{}{You're delusional.}
{383}{}{Goodbye.}

# Node007
{410}{}{And we offer an excellent warranty. Plus, your first oil change is on the house. What do you think?}
{411}{}{Throw in a full tank of gas, and we have a deal.}
{412}{}{You need professional help.}
{413}{}{I'm leaving now.}

# Node008
{440}{}{Apologies, but we're fresh out of petrol. Maybe next time. Goodbye.}
{441}{}{What's the story with that silver car over there? It looks salvageable.}

# Node009
{470}{}{I'm offended. I don't have to tolerate that from a customer. Have a nice day.}
{471}{}{[END]}

# Node010
{500}{}{Chrysalis Motors Highwayman? Belonged to some tribal, now it's in rough shape.}
{501}{}{Can I try to fix it up?}
{502}{}{I see. Goodbye.}

# Node011
{530}{}{You seem like someone who'd cherish it. 5,000 caps, and it's yours, along with these... Hey, where are my tools? Thief!}
{531}{}{You seem like someone who'd cherish it. 5,000 caps, and it's yours, plus these tools. If you manage to restore the car, it's yours to drive off into the sunset.}
{532}{}{Thank you, Bob. I'll have it shining like new in no time!}
{533}{}{Crap! Out of caps. Catch you later, Bob.}
{534}{}{Oops!}
