# Message file for secrarat.ssl
# Number of nodes: 3
# Grammar pass done

{100}{}{Cranium Rat}
{102}{}{This mutated rat stands before you, its cranium enlarged and pulsating with an unnatural energy.}

{150}{}{*FEAR ME*}
{151}{}{*FEAR MY COMING*}
{152}{}{*WHAT OTHERS KNOW OF ME IS A MASK THAT HIDES MY TRUE MIGHT*}
{153}{}{*THEY THINK I AM VERMIN, THOSE RATS WHOSE BRAINS PULSATE WITH BILIOUS LIGHT*}
{154}{}{*THEY DO NOT KNOW I SEE THROUGH THE THOUSAND EYES OF MY BODY*}
{155}{}{*MY BODY LIVES AMONG THEM, AND THEY DO NOT SEE ME*}

# Node001
{200}{}{[As you step into an empty parking lot, a swarm of rats surrounds you. Their craniums are unusually enlarged, and a chorus of voices fills your mind, sharp and tiny like needles. Through some local mental force, you comprehend their alien language.] WE ARE THE EYES IN THE DARK PLACES. WE ARE THE MANY WHO THINK AS ONE. WE DO NOT ANSWER YOUR QUESTIONS. YOU WILL ANSWER OURS. WHAT ARE YOU DOING IN THIS PLACE, SO FAR FROM THE LIGHTED CORRIDORS OF BIPEDS? SPEAK YOUR MIND, AND REMEMBER THAT WE CAN HEAR YOUR LIES.}
{201}{}{I apologize for intruding. I became lost and meant no harm. I'll leave peacefully.}
{202}{}{Die mutants!}
{203}{}{Me lost. Me no harm ratsy.}
{204}{}{Die talky ratsy!}

# Node002
{230}{}{YOU DARE THREATEN US? BIPED, YOUR RECKLESSNESS SHALL BE YOUR UNDOING. PREPARE YOURSELF.}
{231}{}{[END]}

# Node003
{260}{}{LEAVE NOW, OR SUFFER THE CONSEQUENCES.}
{261}{}{Thank you, merciful beings. I will depart and never trouble you again.}
{262}{}{In truth, the world would be better off without your mutated presence.}
{263}{}{Thank, ratsy! Me go.}
{264}{}{Me change mind. Me kill talky ratsy.}
{265}{}{[Depart in silence.]}
