# Message file for seedtrk1.ssl
# Number of nodes: 1

{100}{}{The truck has broken down. Now, it stands as a landmark, no longer capable of serving as a functional vehicle.}
{101}{}{You replaced the tires and suspension, making the truck ready for off-road trips. As a bonus, you reinforced the truck's plating, just in case.}
{102}{}{You fail to repair the truck.}
{103}{}{This truck wasn't designed for off-road trips. The tires and suspension have given out, rendering it immobile.}
{104}{}{You replaced the tires and suspension, making the truck ready for off-road trips. As a bonus, you reinforced the truck's plating, just in case.}
{105}{}{You fail to repair the truck.}
