# Message file for selosten.ssl
# Number of nodes: 5

{100}{}{You see a confused man in a black combat armor.}
{101}{}{You see the leader of the lost Enclave patrol.}
{102}{}{He's wearing a suit of Enclave Combat Armor.}

# Node 0 [floats]
{200}{}{I have a feeling we're not in Kansas anymore.}
{201}{}{You know what they say, if you want to get somewhere fast, follow the Enclave! I get the joke now.}
{202}{}{I'm starting to think this is some conspiracy against us!}
{203}{}{Who needs a functioning compass when you have six "clever" Enclavers?}
{204}{}{You'd think after all our high-tech training, we could at least navigate better than a drunk gecko.}
{205}{}{Who needs reliable maps when you have our patented "follow-the-mental-institution" technique?}
{206}{}{They say getting lost builds character. Well, at this rate, we'll have more character than the entire wasteland!}
{207}{}{We're the ultimate paradox: highly trained soldiers with no clue where we're going. The wasteland's greatest comedy act.}
{208}{}{Not funny anymore, guys.}
{209}{}{We're almost like the Pied Piper, leading ourselves in circles with no rats in sight.}
{210}{}{If only we could trade our combat skills for a basic sense of direction. We'd be unstoppable!}
{211}{}{If we don't get ourselves out of this quickly, we'll be pushing daisies in no time.}
{212}{}{I hope MacArthur Army Base has a working compass. We clearly need it more than anyone else!}

# Node001
{230}{}{Excuse me, stranger. We seem to have lost our way. Do you know how to get to the MacArthur Army Base? We've been wandering around and getting more confused by the minute.}
{231}{}{MacArthur Army Base? I can lend a helping hand.}
{232}{}{Sorry, never heard of that place. Goodbye.}
{233}{}{Gugi!}

# Node002
{260}{}{Yeah, well... we seem to have taken a wrong turn somewhere. We have this old pre-war map and we've been arguing about whether we're in Utah, Colorado, or Kansas. It's become a bit of a mess.}
{261}{}{Don't worry, I'll give you some directions to get you back on track. But first, I have to ask, who are you and why are you all the way out here?}

# Node003
{290}{}{It's a long story. Let's just say that after the Oil Rig and Navarro were destroyed, we had some miscommunication and ended up on this wild goose chase. But hey, we're not ones to back down from a mission, even if it means wandering aimlessly through the wasteland.}
{291}{}{Enclave, huh? I have some unfinished business with you scum.}
{292}{}{Here, take a look at my Pip-Boy map. It'll guide you back to the right path.}

# Node004
{320}{}{Thanks, stranger. We appreciate the help. As a token of our gratitude, here's some "stuff" we've gathered on our journey. Maybe you'll find some use for it.}
{321}{}{Ah, more junk. Just what I've always wanted. Thanks anyway, I'll put them to good use.}
