{100}{}{You see a beautiful, redheaded woman.}

{150}{}{You murdered Fox!}
{151}{}{SURE! FINE! WHATEVER!}
{152}{}{You murdered the love of my life!}
{153}{}{You'll pay for what you did to Fox.}
{154}{}{You monster!}
{156}{}{You criminal scum!}
{157}{}{You murdering scum!}
{158}{}{Death is a just punishment for you!}
{159}{}{God never lets the Devil steal the show!}
{160}{}{Looking for extreme possibilities makes you blind!}
{161}{}{I want you to do me a favor. It's not negotiable.}
{162}{}{"Baby" me and you'll be peeing through a catheter.}

{200}{}{I want to remember how it was. I want to remember how it all was.}
{201}{}{Fox, I will avenge your death!}
{202}{}{The truth is out there, but so are lies!}
{203}{}{Nothing happens in contradiction to nature!}
{204}{}{I don't have time for your convenient ignorance!}
