# Message file for sulik.ssl
# Number of nodes: 14
# Grammar pass done

{100}{}{You see a tall man with facial tattoos and a large bone through his nose.}
{101}{}{You see a tough-as-nails tribal.}
{102}{}{You see a tall, muscular tribal with a bone through his nose, facial tattoos, and a confident, composed demeanor.}

# Node001
{199}{slk15a}{Evil spirit is possessing us, fren. Chunks of hair be falling out! Sis? Is that you? Help me!}

{200}{slk15a}{Evil spirit is possessing us, fren. Chunks of hair be falling out!}
{201}{}{What in the hell is that thing?!}
{202}{}{Sorry, dude. This seems way beyond my capabilities.}
{203}{}{Wut that?!}
{204}{}{Me run.}

# Node002
{230}{slk18a}{We and I've been in bad places before. This worse. The Winding Water tribe calls it Hydra, the Ancient God-Spirit. Others, the Molech. It lies dormant.}
{231}{}{Are you poisoned? Your speech is strange.}
{232}{}{Is there anything I can do to help?}
{233}{}{Poison?}
{234}{}{Need help?}
{235}{}{Apologies, but I don't want to end up in a bad situation too.}
{236}{}{Me no go bad place.}

# Node003
{260}{slk17b}{Grampy Bone say we should leave here.}
{261}{}{The temple is empty!}
{262}{}{Tell me about that creature trying to eat you.}
{263}{}{Are you poisoned? What's wrong with you?}
{264}{}{How can I assist you?}
{265}{}{Just making sure you're still alive.}
{266}{}{Temple empty!}
{267}{}{Big ugly thing!}
{268}{}{Sick?}
{269}{}{Me help!}
{270}{}{[Leave him to his fate.]}

# Node004
{290}{slk27sb}{Talons of death are close.}
{291}{}{[CONTINUE]}

# Node005
{320}{slk27sa}{An empty shell rests below those that rest.}
{321}{}{What are you trying to say?}
{322}{}{It seems the poison has taken its toll. Your mind is deteriorating rapidly.}
{323}{}{A riddle?}
{324}{}{You sick in body first then mind too.}

# Node006
{350}{slk27ja}{Spirits see two paths, joining others. Bad path goes to bad shadows in bright area. Good path goes to bright place that was born of shadows.}
{351}{}{I'm leaving now, but I'll return for you later. Maybe.}
{352}{}{Me go and me come back late. Maybe.}

# Node007
{380}{slk27ib}{The head isn't with the body.}
{381}{}{Here, drink the antidote.}
{382}{}{I don't have an antidote with me.}
{383}{}{Drink good water.}
{384}{}{No good water.}

# Node008
{410}{slk27ga}{Grampy Bone say things can be made good, but help needs come from outside. The Winding Water tribe hid spears of fire and eggs of hell inside the Drowned Temple.}
{411}{}{I'll figure something out. Don't die on me.}
{412}{}{Me think. You live.}

# Node009
{440}{slk32c}{We and my nose thanks you.}
{441}{}{I expect a reward for my efforts.}
{442}{}{Take care.}
{443}{}{Give prize!}
{444}{}{Be good.}

# Node010
{470}{slk28b}{Be needing some time off. A little smoke, a little think.}
{471}{}{[END]}

# Node011
{449}{slk41c}{What's ours is yours, fren. But we and I lost all of our stuff!}
{500}{slk41c}{What's ours is yours, fren. Take this torch gun. We and I like hammers better.}
{501}{}{A laser gun? Not bad, fren.}
{502}{}{Cutting gun kill good!}

# Node012
{530}{slk11a}{We be like a turtle, fren.}
{531}{}{Rest now.}
{532}{}{Rest.}

# Node013
{560}{slk8}{We and I thank you. Name's Sulik. How can we repay?}
{561}{}{Well, that was one hell of a fight. I wouldn't mind getting something in return.}
{562}{}{Thanks, Sulik. I'm good.}
{563}{}{Big fight! Big reward!}
{564}{}{Me good.}
{565}{}{You're name's Sulik? Your mom, Granny Spider, wants me to tell you that she thinks of you and your sister every day.}

# Node014
{590}{slk63m}{An act of kindness is rarely forgotten.}

# Node015
{620}{slk62h}{Seek a reflection of yourself. The pathway will open before you.}
{621}{}{She's been ill.}

# Node016
{650}{slk62f}{A flower opens its petals to the sun. Seek that which is like the flower.}
{651}{}{If you say so. About that repayment... Well, that was one hell of a fight. I wouldn't mind getting something in return.}
{652}{}{OK, Sulik. About that repayment... I'm good.}
