# Grammar pass done

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{You see a sickly man.}
{101}{}{You see Aldo, the Prison Greeter. You think you can smell his breath from here.}
{102}{}{He is dressed in a very dirty prison jumpsuit.}

#############################################################
#  The following lines are for the dialog which the NPC     #
#  says. This will be disorganized because of the Design    #
#  Tool.                                                    #
#############################################################

{200}{}{Hello there, I haven't seen you before. I'm Aldo, the prison greeter. *hic* It's my job to welcome newcomers and answer any questions about our little brig. *hic* Welcome to Tibbets! Who might you be?}
{201}{}{Uhh, I was born in Tibbets but thanks for the greeting. I'm just passing through.}
{202}{}{My name's }
{203}{}{. Thanks for the greeting.}
{204}{}{ the Big Bad Criminal. They call me Number 13.}
{205}{}{You don't need to know my name or anything else about me. Go away, you filthy drunkard.}
{206}{}{I doubt a state-of-the-art prison like Tibbets would have someone like you as an official Prison Greeter. Besides, what about the Welcoming Committee Director?}

{300}{}{The Big Bad Criminal. Oh mighty }
{301}{}{, you must be important and powerful. *hic* It's customary to tip the Prison Greeter. *urp*}
{302}{}{Here's a tip for you - lay off the booze for a while.}
{303}{}{I guess it's worth 5 caps to get you off my back.}
{304}{}{Well, I wouldn't want to go against custom. Will 5 caps suffice?}
{305}{}{You should give me a tip, or I might make your stay here less pleasant.}
{306}{}{Sorry, but the Big Bad Criminal have no use for money.}

{350}{}{Well, friend, }
{351}{}{, *hic* it's customary to tip the prison greeter before asking questions. *urp*}
{355}{}{Sorry, I can't spare any caps for you.}

{400}{}{Well stranger, you should *hic* know that it's customary to tip the prison greeter before asking questions. *urp*}

{450}{}{Thanks for the money, friend. *urp* I'll use it to get some medicine for my dry throat. Consider yourself greeted. Any questions about our fair *urp* penitentiary?}
{451}{}{No thanks.}
{452}{}{Actually, I have a few questions.}
{453}{}{Aldo, I'm looking for an exit.}

{500}{}{Ask away, oh benefactor of mine.}
{501}{}{Do any prisoners work here?}
{502}{}{Where can I trade or find healing?}
{503}{}{Tell me about the robots.}
{504}{}{Where do you buy your booze?}
{505}{}{Thanks, I think that's all I need to know for now.}
{506}{}{Do you know where I can find a gun?}

{550}{}{Thanks for nothing. I hope your stay in prison is long. *hic* Locals like you are all the same.}

{600}{}{Here in Tibbets, some prisoners work in factories, while others focus on education and raising families. *urp*}
{601}{}{What factories are there?}
{602}{}{Thanks, that's all I need to know.}
{603}{}{That's interesting. I have another question.}

{650}{}{There are a couple of factories down below. Run by Vault-Tec. They maintain the prison and produce goods. The Warden claims they sell the products, but I'm skeptical. *hic* The work is tough and dangerous, especially with the robot standards. I'd advise you to avoid it if you can.}
{651}{}{Thanks, that's all I need to know.}
{652}{}{Hmm, one more thing, Aldo.}

{700}{}{You can trade at cell block 14 or with anyone willing to trade. Some prisoners venture to a remote hospital using the old tram network for additional medicine. But be cautious.}
{701}{}{Thanks, that's helpful.}
{702}{}{A remote hospital? Interesting. I have another question.}

{750}{}{I understand you couldn't spare any caps earlier, but maybe *hic* this time you're feeling more generous to be greeted?}
{751}{}{I could spare 5 caps to keep you off my back.}
{752}{}{Something was missing. Here's 5 caps for the official greeting.}
{753}{}{No, thanks. I don't need your official greeting.}
{754}{}{I think I'd rather have your insides greet my blade.}

{800}{}{Hey there, friend. Can you spare some caps for my medicine? My throat is getting worse. I'll throw in a *urp* greeting.}
{801}{}{Sure, I can spare 5 caps for a friend's medicine.}
{802}{}{Sorry, I can't spare any right now.}
{803}{}{You should work and sweat that poison out of your system.}

{810}{}{Thanks for nothing. How can you be so cruel to someone as unwell as myself? Damn prisoners! [Aldo spits on the ground at your feet, dribbling a bit on his scruffy chin.]}

{820}{}{Your generosity *hic* will bring you good luck, my friend. I hope to see you again soon.}
{830}{}{I could really use some money for medicine. If you *cough, cough* can't spare any *cough*, I understand. Maybe next time, if I'm still *cough* around.}

{850}{}{You mean my much-needed medicine? *hic* I used to buy it at the Atom, but *urp* they won't sell it to me anymore. Doc said I have a serious *hic* alcohol problem. Luckily, I made my own medicine in the Labs. Ask Slappy; he'll *urp* sell you some.}
{851}{}{I'm glad you found a solution. That's all I need to know.}
{852}{}{Interesting. Where are these Labs?}
{853}{}{Thanks, Aldo. Tell me about something else.}

{860}{}{The Labs are located a level down from the Medical Treatment Area. *hic* Can't miss 'em.}
{861}{}{Thanks for the information, Aldo. That's all I need to know.}
{862}{}{Glad you found a solution. Uh, could you breathe a bit more downwind? By the way, I have another question.}

{870}{}{Hello there, friend. You look perplexed. What you need is a friend here in Tibbets. I'm Aldo, the prison greeter.}
{871}{}{Friend? Heh, heh, }
{872}{}{ like friend.}
{873}{}{Urk, *sniff, sniff* bad smell. Go away now.}

{880}{}{For 20 caps, I'll be your friend, and everyone else will be too. That's how it works.}
{881}{}{Toowa-eee-nty? Ook? Beeg Priiii-sn? Ook?}
{882}{}{Give man pretty cap now?}

{890}{}{A gun? Well, you might want to join the Sheriff's company if you want one. Look for them in cell block 30. But be careful; the robots will carve a big hole in your skull if you walk around packing heat without a good reason.}

{900}{}{A way out of here, huh? *urp* The only *hic* way out is by riding my rail baby, "Lucky 17." *hic*}
{901}{}{"Lucky 17?" Where can I find it?}

{910}{}{I haven't seen her for a while. *hic* I'm not sure *urp* where she might be, but I think she's somewhere in Tibbets. You should talk to *urp* the Warden; we were together when they brought me here. Me and "Lucky 17" were pretty *hic* thick. Heh, heh, heh. Get it? Oh my, I haven't lost my touch.}
{911}{}{It's nice to know that no matter how low you sink, you can't lose something you never had. Let me ask you something else.}
{912}{}{Thankfully, you're one-of-a-kind, Aldo. That's all I need to know.}

{920}{}{Hello again, friend. Do you have another 20 caps to spare to strengthen our friendship?}
{921}{}{Ook.}
{922}{}{Me no share. Bye-e.}
