# Message file for tbbart.ssl
# Number of nodes: 3
# Grammar pass done

{100}{}{You see a service bot attending to its duties.}
{101}{}{You see a service bot diligently working as a bartender in Atom.}
{102}{}{The service bot meticulously cleans a glass.}

{105}{}{Although overall design is that of a humanoid, the details reveal this robot wasn't built by a human. It was customized to act as a bartender.}

# Node001
{200}{}{Welcome, Number 13. Take a seat. What can I get you?}
{201}{}{Let me see what's on offer at this prison bar.}
{202}{}{You seem well-informed. There's plenty of gossip among prisoners here.}
{203}{}{Why does everyone seem to be singing the same tune?}
{204}{}{Nice establishment you have here. Cozy and with good company.}
{205}{}{What's the story behind this bar?}
{206}{}{What a dump! You know how I could improve it? By using your head as a cocktail shaker.}
{207}{}{I'm good for now. See you later.}
{208}{}{Kuzuu! Ku!}
{209}{}{[Shamble off]}

# Node002
{230}{}{Apologies, Number 13, but my primary function is to serve drinks, clean up messes like urine and vomit... you know, the usual. The Warden disabled my chat protocol for reasons I can't disclose. Now, what can I pour for you?}
{231}{}{You're useless, just like the Director. I can tell you share the same model type.}
{232}{}{Alright then, give me something to drink.}
{233}{}{I'm not thirsty. See you later.}
{234}{}{Can you at least explain why everyone is wearing jumpsuits with the same number? I thought 13 was reserved for my cell block.}
{235}{}{Do you happen to know when the last time Angela was seen here?}

# Node003
{260}{}{Hmph! Your CODE will never improve with such... criminal vocabulary. If you don't want a drink, bother someone else.}
{261}{}{My CODE?}
{262}{}{Whatever. I'm leaving.}

# Node004
{290}{}{Thank you. Hope to see you again, Number 13.}

# Node005
{320}{}{Ah, I can answer that question. You see, Number 13, almost 200 years ago, around the time of the Great War, our world was in a state of chaos. Vault-Tec mixed up jumpsuit shipments and sent many containers of both 13 and blank jumpsuits to Tibbets. We were in the midst of sorting it out when the bombs fell, and that was that. But now the Warden believes that 13 suits our prisoners well - those unfortunate enough to find themselves locked up.}
{321}{}{Interesting story, but I have to go now. Goodbye.}
{322}{}{That story made me thirsty.}
{323}{}{Sheeeeeesh - the Warden thinks the unlucky 13 suits us well? Now I see who *installed* your sense of humor!}

{349}{}{She was here the other night and left around 1 AM. Officers Croz and Robb were also present but left around 1:30 AM. Magik was here too and gave a bag of money to Croz earlier in the evening.}
{350}{}{She was here the other night and left around 1 AM. Magik was also here and gave a bag of money to Croz earlier in the evening.}
{351}{}{Hmm, interesting. Let me ask you something else about Angela...}
{352}{}{That's all for now. Thank you.}
