#############################################################
#  Message File: kchild.msg                                 #
#                                                           #
#       Body Type: CHILD                                    #
#       Combat AI: Flee                                     #
#       Weapons: None                                       #
#       HP: 20                                              #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: January 13, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{You see one of Tibbets' children.}
{101}{}{You see a blissful kid unaware of the situation.}
{102}{}{You see one of Tibbets' cool lil' prisoners.}

#############################################################
#  The following lines are floaters for children            #
#############################################################

{150}{}{Don't eat me!}
{151}{}{Eeeee! The boogy-monster!}
{152}{}{Daddy says you're a bad person.}
{153}{}{Aieeee! Run away!}
{154}{}{You're scaring me.}
{155}{}{Stop looking at me.}
{156}{}{I'm not supposed to talk to prisoners.}
{157}{}{You're just like the robots.}
{158}{}{My mom said you'll eat me if I'm bad.}
{159}{}{I'm not afraid of you!}
{160}{}{Help meee!}
{161}{}{It's after me!}
{162}{}{Please don't hurt me!}
{163}{}{Stay away from me!}
{164}{}{Eeeeeeeee!}
{165}{}{I hate you!}
{166}{}{Mommy, mommy, mommy!}
{167}{}{Leave me alone!}
{168}{}{You stink!}

{170}{}{Hello there.}
{171}{}{Want to play house?}
{172}{}{Are you really a bad person?}
{173}{}{How come you're so funny looking?}
{174}{}{My mom says you could be a childkiller.}
{175}{}{Has your tribe stopped eating people?}
{176}{}{Who dressed you so funny?}
{177}{}{I'll bet you're nicer than you look.}
{178}{}{Let's play tag. You're it.}
{179}{}{You don't smell that bad.}
{180}{}{Have you seen my invisible friend?}
{181}{}{I want to travel the world when I'm as old as you.}
{182}{}{You're a nice prisoner, not like the others.}
{183}{}{I bet you do to bathe.}
{184}{}{You're smarter than robots.}
{185}{}{Is that blade you have really sharp?}
{186}{}{I want to be just like you when I grow up.}
{187}{}{I wish I had a dog.}
{188}{}{I've got a shiny pebble.}
{189}{}{Have you met my friends?}

{190}{}{Can I join you?}
{191}{}{You're nice.}
{192}{}{You look funny.}
{193}{}{Whatcha wearing?}
{194}{}{I want to see a brahmin! And ride it too!}
{195}{}{Are you from far away?}
{196}{}{Weeee! Ha Ha Ha!}
{197}{}{Don't leave!}
{198}{}{Do you have some sweets?}
{199}{}{Am I bothering you?}
{200}{}{Where ya going?}
{201}{}{Can I come with you?}
{202}{}{How old are you?}
{203}{}{What's your name?}
{204}{}{Do you like kids?}
{205}{}{What is that?}
{206}{}{Do you wanna play a game?}
{207}{}{Whatcha doing?}
{208}{}{Have you seen any roaches?}
{209}{}{Where did you get that?}
{210}{}{Can I have that?}
{211}{}{What do you do?}
{212}{}{I can run fast. Wanna see?}
{213}{}{Watch me! Watch me!}
{214}{}{Mommy says I talk too much.}
{215}{}{Where is your home?}
{216}{}{Heeee! Heeee!}
{217}{}{Are you gonna stay here?}
{218}{}{Do you have friends? I can be your friend.}
{219}{}{Why did the robots lock you here?}
{220}{}{I like you.}
{221}{}{Do you like me?}
{222}{}{Are you married?}
{223}{}{One, two, three - weeeeEEEeeeeEEEeee!}
