# Message file for tbcole.ssl
# Number of nodes: 7
# Grammar pass done

{100}{}{You see a confident-looking man clad in unfamiliar combat armor.}
{101}{}{You see the leader of a secretive group of soldiers, which he referred to as the "Guardian Angels."}
{102}{}{A confident-looking man wearing unfamiliar combat armor catches your eye. He exudes an air of importance.}

{105}{}{What in the world...}
{106}{}{Don't disturb the general.}

# Node001
{200}{}{Hey kid, come over here. I want to have a word with you.}
{201}{}{Who are you?}
{202}{}{What's happening here?}
{203}{}{I don't have time for this.}
{204}{}{Die, invaders!}
{205}{}{Grrah!}
{206}{}{Di! Di! Diiiiiiiii! E!}
{207}{}{Why did you destroy the Director? It was the friendliest robot I knew.}
{208}{}{Director! Why smash?}
{209}{}{Your voice... it sounds familiar. Have we met before?}

{220}{}{I highly doubt it, kid. It's just the helmet. But who knows, maybe our paths will cross again someday, and then you'll know for sure who I am.}

# Node002
{230}{}{You mean this little operation? Me and the boys made an opening for you all to escape. You've been given a new lease on life today - without us, you'd have remained stuck in this wretched pit forever.}
{231}{}{I really must be on my way now.}
{232}{}{You attacked our prison! Now you'll pay with your life!}

# Node003
{259}{}{Does it really matter? Perhaps *it* attacked us... or maybe Follower Paul over there didn't approve of *its* creation by another machine. If you need something to grasp, consider us your guardian angels - a whole battalion of them. That's what this forsaken world needs right now.}
{260}{}{Does it really matter? If you need something to grasp, consider us your guardian angels - a whole battalion of them. That's what this forsaken world needs right now.}
{261}{}{[CONTINUE]}

# Node004
{290}{}{But we're men of action, not words. Take this to defend yourself and head towards a large place northeast of here. The locals call it the Howling City. You'll be safe there. Stay out of trouble, okay, kid?}
{291}{}{Okay.}
{292}{}{Oki!}
{293}{}{Thanks, I'm outta here!}
{294}{}{I'll do as I please. I don't really follow anyone's advice.}
{295}{}{Zani-zei!}
{296}{}{Thanks for the revolver. Now I can test it out on you.}
{297}{}{I... I'm not ready. I can't... [Kill yourself.]}
{298}{}{As a pacifist, I can't accept this. Thanks anyway, and farewell.}

# Node005
{320}{}{In a hurry, huh? Can't blame you.}

# Node006
{350}{}{Hah! An inbred! Why were you locked up down here... for your own good? [The other soldiers burst into laughter.]}
{351}{}{Haaaaaaai-ya!}
{352}{}{[Shrug]}

# Node007
{380}{}{I have something for you - a large, sharp knife. Do you know how to wield one, rookie? Take it and go now. Go before the bad robots return!}
{381}{}{Robo! Nggh!}
{382}{}{Me no kill! Me no like knife! Byeeeeeeee!}
{383}{}{Evil-yoooo! Smash!}
