# Message file for tbdavide.ssl
# Number of nodes: 89
# Grammar pass done

{100}{}{You see a man in his 60s.}
{101}{}{You see Dr. Carl Davide.}
{102}{}{He appears to be the one in charge of the hospital.}

# Gestalt1
{200}{}{What do you mean by "revolutionary progress"?}
{201}{}{You know, getting rid of it for good.}
{202}{}{Actually, nevermind that. Can I ask you some other questions?}

# Gestalt1a
{230}{}{Well, there is some progress on that. My work with Dr. Linder Kosh is in advanced stages.}
{231}{}{Interesting. What is it about?}
{232}{}{Ok, thanks. Can I ask you about some other things now?}
{233}{}{Where is Dr. Kosh?}
{234}{}{Thanks, but I could use some medical attention now.}
{235}{}{Thanks, I'll leave you to your work now.}

# Gestalt1a1
{260}{}{Hmm... it's a process of curing insanity by gestalt. Basically, we'll temporarily merge two damaged brains, effectively repairing each other's damaged neurons. Why are you asking?}
{261}{}{Well, I'm just curious.}

# Gestalt1a1a
{290}{}{Oh, and what do you think of our idea?}
{291}{}{I'm not entirely sure.}

# Gestalt1a1a1
{320}{}{Oh, well, if you think you can help at all, please let Dr. Linder know.}
{321}{}{I will, but for now, could I ask you some other questions?}
{322}{}{I will, but for now, I am in need of your services.}
{323}{}{I will, and thank you for offering. Now I'll leave you to your work.}
{324}{}{Ha! I'm not helping anyone, especially not some crazy doctors. I'm outta here.}

# Gestalt1a2
{350}{}{Okay, he's in the hospital. You can find him inside working on an Organ Extraction Unit... You know, an invention we both created.}
{351}{}{Thanks, but while I'm here, I could use some medical attention.}
{352}{}{Thanks, now I have a friend here who needs some help.}
{353}{}{Thanks, now can I ask you some questions about yourself?}
{354}{}{Thanks, Dr. Davide. I'm going to see him right now.}

# initial
{380}{}{Hello there. I'm Dr. Carl Davide, a psychiatrist and a general practitioner. I don't remember seeing you around the hospital before. What's your name?}
{381}{}{Hello there. My name is }
{382}{}{. It's a pleasure to meet you, Doctor.}
{383}{}{Oh, I'm glad I found you. My name is }
{384}{}{, and I need some medical attention.}
{385}{}{The name's }
{386}{}{. I... need help.}
{387}{}{I'm glad I found you, Doctor. I'm }
{388}{}{, and I have a friend here who needs your help.}
{389}{}{Oh, I'm sorry to have disturbed you. Goodbye.}
{390}{}{Ouchie.}
{391}{}{[Give the doctor a confused look]}
{392}{}{Dr. Nora mentioned a reward for helping destroy the radscorpion nest. Can you tell me more about it?}
{393}{}{Me kill scorpi! You give caps.}

# subsequent
{410}{}{Welcome back. How can I assist you today?}
{411}{}{I need some assistance.}
{412}{}{I have some more questions for you.}
{413}{}{Could you share your story about leaving your Vault again?}
{414}{}{One of my friends needs help.}
{415}{}{Just dropping by to say hello. I'll leave you be now.}
{416}{}{Have you encountered any patients with unusual symptoms?}
{417}{}{Ouchie!}
{418}{}{[Give the doctor a friendly smile]}

# davide1
{440}{}{How can I assist you?}
{441}{}{What can I do for you?}
{442}{}{Can I ask you some questions about yourself?}
{443}{}{Have you made any progress in treating mental illness?}
{444}{}{I'm just exploring. I'll return if I need help.}

# davide2
{470}{}{What seems to be the problem?}
{471}{}{I have a minor injury that needs treatment before it gets infected.}
{472}{}{[Show Dr. Davide your wound] It's painful and burning.}
{473}{}{I've been poisoned and need assistance.}
{474}{}{I'm feeling sick from radiation exposure.}

# davide3
{500}{}{You sound terrible. What's wrong?}
{501}{}{I've been poisoned, and it's making me sick.}
{502}{}{I've been exposed to radiation, and I'm not feeling well.}

# davide3a
{530}{}{I apologize for not noticing earlier. Let's move to the table, and I'll take care of that. The cost will be 50 caps. Do you have that amount?}
{531}{}{Yes, please heal me.}
{532}{}{I don't have enough caps. Will you accept what I have?}

# davide3a1
{560}{}{[Dr. Davide starts treating your wounds and applies healing ointments]}
{561}{}{[Wait patiently for him to finish]}

# davide3a1a
{590}{}{[After 2 hours] There, all done. Keep the wounds clean and dry for a few days, and you'll recover.}
{591}{}{Thank you, Dr. Davide. Now, can I ask you some questions?}
{592}{}{I still need some assistance.}
{593}{}{Thank you, Dr. Davide. I'll come back if I need help again.}

# davide3a2
{620}{}{Alright, that will work.}
{621}{}{Thank you, Dr. Davide.}

# davide3a2a
{650}{}{Alright then. Go to the procedure room and wait for me. I'll join you shortly after I log this in our database.}
{651}{}{[Go to the table]}

# davide3a2a1
{680}{}{[After what feels like hours, Dr. Davide finally approaches you]}
{681}{}{Finally! Let's get started.}

# davide3a3
{710}{}{I'm sorry, but I have a standard rate for my services. Charging less would be unsustainable for me.}
{711}{}{But I genuinely don't have enough caps. [Look at Dr. Davide with pleading eyes] Is there anything you can do?}
{712}{}{Alright, I understand. Can I ask you some questions instead?}
{713}{}{A true doctor wouldn't refuse help over a few caps. I'm leaving, and I might not come back.}

# davide3a3a
{740}{}{Alright, I'll make an exception this time. Just please don't spread the word. If everyone takes advantage of it, I'll be broke within a month.}
{741}{}{Thank you so much. I promise to keep it between us.}
{742}{}{Okay, I appreciate your assistance.}

# davide3a3b
{770}{}{I'm sorry, I really wish I could help, but I can't afford to provide my services for free.}
{771}{}{Alright, here's the money.}
{772}{}{Since I can't afford it, can I ask you something instead?}
{773}{}{Damn! I'll have to come back when I have more funds.}

# davide3b
{800}{}{Okay, come over to the table, and I'll prepare the anti-venom for you. It will cost 75 caps. Do you have enough?}
{801}{}{Here's the payment.}
{802}{}{Unfortunately, I don't have enough. Can you accept these caps instead?}

# davide3b1
{830}{}{Dr. Davide inserts a large needle into your arm, and a thick, yellow liquid starts flowing into your veins. You soon pass out.}
{831}{}{[Sleep it off]}

# davide3b1a
{860}{}{After 16 hours, you begin to wake up.}
{861}{}{Damn! It feels like someone was playing the drums on my head... with hammers.}
{862}{}{My head is pounding. What did you do to me? I need to leave.}

# davide3b1a1
{890}{}{Yeah, sorry about that. The band and I got carried away during our practice session. *Chuckle*}
{891}{}{That's funny, Dr. Davide. But seriously, why does my head hurt so much?}
{892}{}{Very funny, smartass. I'm leaving.}

# davide3b1a1a
{920}{}{It's just a temporary side effect of the anti-venom. The pain should wear off in a few hours or up to a day.}
{921}{}{Thanks for helping me out. Can I ask you some questions?}
{922}{}{Thanks for getting rid of the poison, but I need some more assistance.}
{923}{}{Thanks for your help, Dr. Davide, but I must be on my way now. I'll return if I encounter more trouble.}

# davide3c
{950}{}{I see. Please go over to the table, and I'll begin testing to determine the exact amount of radiation you've been exposed to.}
{951}{}{[Dr. Davide starts scanning your body with a Geiger counter]}

# davide3c1
{980}{}{It appears that your radiation levels have increased. To treat this, you'll need to rest in my office for a while, and the cost will be 100 caps. Are you still interested in being healed?}
{981}{}{Yes.}
{982}{}{No, I have to be somewhere soon. Can you provide anything to alleviate the symptoms?}
{983}{}{Yes, but I can't afford that price. Can you accept these caps?}

# davide3c1a
{1010}{}{Dr. Davide inserts a large needle into your arm, and a thick, orange liquid starts flowing into your veins. You soon pass out.}

# davide3c1a1
{1040}{}{After 12 hours, you begin to wake up.}

# davide3c1a1a
{1070}{}{Oh yeah, sorry about that. The band and I got carried away during our practice session. [He chuckles lightly]}

# davide3c1a1a1
{1100}{}{The pain is just a temporary side effect of the anti-radiation serum. It should subside in a few hours or up to a couple of days.}
{1101}{}{Thanks for getting rid of the radiation for me. Can I ask you some questions?}

# davide3c1b
{1130}{}{I have something that can help, but it works instantly and comes at a higher cost. It'll be 200 caps.}
{1131}{}{Okay. Here are the caps. Thanks, Dr. Davide.}
{1132}{}{Damn! I don't have enough.}

# davide3c1b1
{1160}{}{You're very welcome. Is there anything else I can assist you with?}
{1161}{}{Sure, can I ask you some questions?}
{1162}{}{No, I'm good now. Thanks. I'll be going. I'll return if I run into more trouble.}

# davide3c1b2
{1190}{}{Are you sure you can't stay here? It would be more cost-effective if you do.}
{1191}{}{Well, alright. I guess the other stuff will have to wait.}
{1192}{}{No, I really can't stay in one place for long. Thanks for the offer, though.}

# davide4
{1220}{}{Really? Well, let's have a look then.}
{1221}{}{It's my friend over there.}
{1222}{}{How much would it cost to heal all of them?}
{1223}{}{Actually, never mind. I'll deal with that later. Can I ask you some questions?}
{1224}{}{Actually, never mind. They'll be okay. I need to get going.}

# davide4a
{1250}{}{Alright, let's have a look. Hmm... That will be 100 caps.}
{1251}{}{Okay, here you go.}
{1252}{}{I don't have enough. Can you accept these caps? That's all I have.}

# davide4a1
{1280}{}{Alright then. [After 5 hours] There, your friend is all fixed up now.}
{1281}{}{Thanks, Dr. Davide. I have another friend who needs help too.}
{1282}{}{Thanks a lot, Dr. Davide. Can I ask you some questions?}
{1283}{}{Thanks, Dr. Davide, but we have to go now.}

# davide4a2
{1310}{}{I understand, I can't provide a discount. My prices are consistent for everyone.}
{1311}{}{Alright, I think I have enough.}
{1312}{}{Fine, my friend will have to wait. Can I ask you some questions?}
{1313}{}{Well, alright. I'll come back when I have more money.}

# davide4b
{1340}{}{Hmm... [He looks over your companions] It'll cost you 400 caps to fully heal all of them.}
{1341}{}{Sure, here you go.}
{1342}{}{I don't have that much. Can you accept these caps? That's all I have.}

# davide4b1
{1370}{}{Alright then. Let's all go back to the procedure room, and I'll start getting all of you fixed up.}
{1371}{}{[Wait]}

# davide4b1a
{1400}{}{[After a thorough 12-hour procedure, Dr. Davide and your companions emerge from the procedure room, looking relieved.] Whew! That was quite the job, but I'm glad to say they're all good to go now.}
{1401}{}{Thank you, Dr. Davide. Now, I could use some help myself.}
{1402}{}{Thanks a lot, Dr. Davide. Can I ask you a few more questions?}
{1403}{}{Thanks, Dr. Davide. We appreciate your assistance. We'll come back if we need further help.}

# davide4b2
{1430}{}{I'm sorry, but I can't offer a discount on this particular treatment.}
{1431}{}{Alright, here are the caps.}
{1432}{}{Oh no, that's unfortunate. I guess they'll have to wait. Can I ask you some questions?}
{1433}{}{I'll come back when I have enough caps. Thank you anyway.}

# AQ
{1460}{}{Of course. I'm a bit busy, so please keep it brief.}
{1461}{}{Where are you originally from? You seem different from most people I've met since leaving my hometown.}
{1462}{}{Have you always lived in Tibbets?}
{1463}{}{Where did you receive your medical training?}

# AQ1
{1490}{}{I'm actually from a Vault located west of Shady Sands.}
{1491}{}{Really? So am I. Which Vault did you come from?}
{1492}{}{Interesting. I've heard about those Vaults. Why did you leave?}

# AQ1a
{1520}{}{That's amazing! My Vault was Vault 13.}
{1521}{}{Was? Does that mean it no longer exists?}
{1522}{}{Where is your Vault located? I'm curious to visit.}

# AQ1a1
{1550}{}{That's correct. Vault 13 was dismantled and repurposed by the NCR a few years ago.}
{1551}{}{How did that happen?}

# AQ2
{1580}{}{I received my medical training back home.}
{1581}{}{And where exactly is your home located?}

# AQ2a
{1610}{}{My Vault is situated about six weeks northwest of Hoover Dam. It's quite a journey.}
{1611}{}{A Vault? I come from a Vault far to the northeast of the NCR.}
{1612}{}{A Vault? That's interesting, but right now, I have another concern.}
{1613}{}{A Vault, my ass! Yeah, right. I'm out of here.}

# AQ2a1
{1640}{}{Alright then, what do you need assistance with?}
{1641}{}{I require some medical attention myself.}
{1642}{}{Never mind, I've changed my mind. I need to continue on my way.}

# Vaultdeath1
{1670}{}{Well, it happened like this...}
{1671}{}{[Listen to his story]}

# Vaultdeath2
{1700}{}{It was located approximately six weeks northwest of Hoover Dam, but unfortunately, it was destroyed many years ago.}
{1701}{}{What led to its destruction?}

# Vaultdeath3
{1730}{}{I'm not entirely sure how or why, but the NCR government was unable to locate Vault 13's VACCS. The technicians extensively searched the database, but they never discovered what happened to VACCS 13.}
{1731}{}{VACCS? I'm not familiar with that term.}
{1732}{}{Fascinating. However, can I ask you some other questions?}

# Vaultdeath4
{1760}{}{VACCS stands for Vault-Tec Atomic City Construction Set. It's a highly secure warehouse filled with construction materials meant to be used in conjunction with a G.E.C.K., which stands for Garden of Eden Creation Kit.}
{1761}{}{I see. What occurred next?}

# Vaultdeath5
{1790}{}{So as the NCR expanded over the years, they needed advanced technology for their own needs. The Vaults had fulfilled their purpose, so it was only natural for them to repurpose them. President Tandi believed it was a way to settle an old score.}
{1791}{}{Settle the score? What do you mean?}
{1792}{}{That's an interesting perspective. Before we dive into that, can I ask you something else?}
{1793}{}{I'm sorry, but I should get going. Maybe we can talk later.}

# Vaultdeath6
{1820}{}{Yes, settle the score. President Tandi's father, Aradesh, the founder and first president of the NCR, died searching for Vault 13. President Tandi felt it was her right to claim the Vault and determine its destiny. This decision was not well-received by the people of Arroyo, who consider Vault 13 a sacred place. I actually lived with them for a year after the Enclave kidnapped us and the Chosen One saved us all.}
{1821}{}{Oh, I see. It must have been difficult for all of you to leave such a significant place behind.}
{1822}{}{That's quite a journey you've been on. Can you tell me more about it?}

# Vaultdeath7
{1850}{}{[Dr. Davide sighs heavily]}
{1851}{}{Dr. Davide, I'm sorry for what you and the others went through. What did you do after the Vault's destruction?}
{1852}{}{I'm a bit lost. Can you recap the story from the beginning?}
{1853}{}{That's enough for now. I have more questions, if you don't mind.}
{1854}{}{I understand. If you need anything, don't hesitate to ask. Goodbye.}

# migrate1
{1880}{}{After learning the truth about the Vault's fate, we, the former citizens of Vault 13, grew disillusioned with NCR politics. We realized we had lost our sense of belonging. After a heartfelt debate, we decided to split up into small groups and head in different directions.}
{1881}{}{Why did you choose to split up?}

# migrate2
{1910}{}{We knew that relying on a single town to support such a large group of refugees would be challenging. So we formed small groups of 10-20 people and headed in different directions.}
{1911}{}{How many people were in your group?}
{1912}{}{I missed part of that. Can you go over the last part again?}

# feud1
{1940}{}{In my group, there were fifteen of us. As we journeyed, hope and optimism soon turned into hopelessness and despair. A feud erupted between Jon and Robert. Jon wanted to settle near a stream we found, while Robert insisted on continuing our journey.}
{1941}{}{That must have been a difficult situation.  What happened as a result of the feud?}

# feud2
{1970}{}{The group was divided, and five of us chose to keep moving. The others decided to stay and established a settlement called New Hope.}
{1971}{}{Do you think those who stayed in New Hope could still be alive?}

# feud3
{2000}{}{Unfortunately, a few months after I arrived here, I heard that explorers discovered the remains of the settlement. All they found were bones and collapsed sheds. It seems they had water but no means to grow or obtain food. The explorers reported signs of cannibalism, suggesting they either turned to it or were attacked by cannibals.}
{2001}{}{That's tragic. What happened to the other five people in your group?}
{2002}{}{I'm sorry to hear that. Can you recap how the feud started?}

# starve1
{2030}{}{After the first week, our rations were nearly depleted, and we faced the daunting prospect of starvation.}
{2031}{}{That must have been incredibly challenging.}

# starve2
{2060}{}{Yes, the survival packs we brought from the NCR were never intended to sustain us indefinitely. Thankfully, our Overseer had the foresight to provide them, or none of us would have survived beyond a week.}
{2061}{}{That was fortunate. What happened next? It sounds like you were in dire straits.}

# starve3
{2090}{}{Indeed, hunger became a pressing concern. However, the situation quickly changed.}
{2091}{}{How did the situation change?}
{2092}{}{I may have missed something. Could you go over the last part again?}

# attack1
{2120}{}{During our journey, we encountered a group of men nearby. Initially, we hoped they could guide us to a nearby town. However, as they approached, it became evident that they were heavily armed soldiers, some even cloaked. They were led by a man who identified himself as Captain Pierce.}
{2121}{}{Cloaked soldiers? That's unexpected.}

# attack2
{2150}{}{Indeed, those soldiers turned hostile and attacked us. I managed to escape, but I fear that Robert, Adriana, and Alexia were captured, and Jim was killed. When I returned to the attack site days later, I found Jim's body, but there was no sign of the others.}
{2151}{}{So, your friends were likely taken captive?}

# attack3
{2180}{}{It's likely they were captured. At the time, I saw the soldiers surrounding my friends, and there was little chance of escape. I wished I could have done something to help them... [Tears start rolling down his cheeks] ...but it was impossible.}
{2181}{}{I'm sorry you had to go through that. Did you ever attempt to locate your captured friends?}

# attack4
{2210}{}{For a long time, fear prevented me from venturing back into the wasteland. By the time I mustered the courage to search, there was no trace of them. I asked around, but the caravans reported only raider attacks, with no mention of those soldiers. Eventually, I stopped seeking information. It's as if they vanished or perished...}
{2211}{}{If I encounter those soldiers, I'll make sure they pay for what they did to your friends.}
{2212}{}{Those soldiers sound like monsters. I hope I never cross paths with them.}
{2213}{}{I'm sorry, but I'm a bit confused. Could you explain the attack once more?}
{2214}{}{I understand. Can I ask you something else?}
{2215}{}{I'm sorry for what happened. Goodbye for now.}

# attack4a
{2240}{}{Ha! I'd appreciate that, but seriously, if you ever come across those guys, run. Run for your life and don't look back.}
{2241}{}{I think I could handle it, but let's drop that topic. By the way, how did you end up in Tibbets?}
{2242}{}{I think I can take them, but I've got to go now. I'll come back if I need anything. Take care.}

# attack4b
{2270}{}{They are. If you ever see any, run. Run for your life and don't look back.}
{2271}{}{Oh, I definitely will. Now, tell me, how did you get to Tibbets?}
{2272}{}{I appreciate the warning, but we've talked enough for now. I need to get going. I'll stop by if I need anything. Stay safe.}

# home1
{2300}{}{After the attack, I gathered the remaining rations that the others had dropped and continued traveling. But less than a week later, I was captured by robots and ended up in Tibbets.}
{2301}{}{So, did you eventually ask to run the hospital here?}

# home2
{2330}{}{Actually, it started differently. When I arrived here, I saw a man lying in a pool of his own vomit, screaming in pain. Recognizing the symptoms of poisoning, I quickly administered some anti-venom that I found in an emergency locker. After a few hours, he started feeling better, and within a day, he was completely fine.}
{2331}{}{Wow, it's fortunate you arrived in time to help him.}

# home3
{2360}{}{It turned out to be a turning point for both of us. Once the robots learned I was a doctor, they asked me to take care of everyone here. I even receive a weekly payment of 40 caps. Funny how things work out. I was just looking for a way out of the cell, and now I have this role. Anyway, I've shared enough of my past. I should get back to work. Take care.}
{2361}{}{Wait a second. Could you go over how you ended up in Tibbets one more time?}
{2362}{}{Can you briefly recap that again?}
{2363}{}{Thanks for sharing your story. I'll leave you alone now. Take care.}

# RedoHistory
{2390}{}{Sure, which part would you like me to repeat?}
{2391}{}{Could you tell me again about the disappearance of Vault 13?}
{2392}{}{Tell me more about your migration to Tibbets.}
{2393}{}{Could you remind me how the feud started?}
{2394}{}{When did your rations run out again?}
{2395}{}{Recount the details of the attack on your group once more.}
{2396}{}{I apologize, but when exactly did you arrive in Tibbets?}
{2397}{}{Actually, nevermind. I have another question.}

# Dumb_Hurt
{2420}{}{Uh-huh... Let me take a look at that.}

# Dumb_Hurt_1
{2450}{}{Oh, I see the wound now. Come on back, and I'll treat you. Follow me.}
{2451}{}{[Follow him]}

# Dumb_Hurt_2
{2480}{}{Alright then... What do we have here? Oh dear, looks like you've been poisoned. Come back with me, and I'll administer an antivenom.}

# Dumb_Hurt_3
{2510}{}{Hmm... Okay, let's do a quick Geiger sweep. [Dr. Davide scans your body with the Geiger counter] Just as I suspected, you've been exposed to radiation. Return to me, and I'll start a serum to help you heal.}

# Dumb_Hurt_4
{2540}{}{Hmm... I see the wounds now, but this spot here, [Dr. Davide points] it looks like an entry point for poison. Hmm... I better start an antivenom treatment as well. Come back, and I'll take care of you.}

# Dumb_Hurt_5
{2570}{}{Oh, I see the wound now, and it seems your hair is falling out in clumps. That's a sign of radiation sickness. Come back, and I'll start a serum to counter it. While it's running, I'll treat your wounds too.}

# Dumb_Hurt_6
{2600}{}{Hmm... I don't see any serious wounds, but wait... what's this? Oh, I see now. You've been poisoned. And you're also showing signs of radiation sickness. Come back, and I'll start an antivenom and serum treatment.}

# Dumb_Hurt_7
{2630}{}{Hmm... I see the wounds here, and it appears you've also been poisoned. Wait a second, is that your hair falling out? By the Chosen One, you're also showing signs of radiation exposure! Come with me back to the room now.}

# Dumb_healed
{2660}{}{There you go. You should be feeling better now.}
{2661}{}{Tankie!}

# Dumb_healed_payment
{2690}{}{Alright, it's time to settle your bill.}
{2691}{}{Bilie?}

# dumb_pay
{2720}{}{Yes, you'll need to pay me for the treatment. Let me calculate it... carry the two... divide by six... Alright, your total comes to 50 caps.}
{2721}{}{Umm... one, five, eleventy-thirtey...}

# dumb_pay_check
{2750}{}{Let me count them for you to make sure.}

# dumb_pay_check_fail
{2780}{}{Hmm... It seems you don't have enough caps. I suppose I'll have to accept what you do have. But please remember, if you need healing in the future, I can't afford to provide it if you can't pay my full fee. Goodbye.}
{2781}{}{[END]}

# Dumb_pay_check_success
{2810}{}{Alright, here's your change. [Dr. Davide takes his fee] You're all set now. Take care, and feel free to return if you need further assistance.}

# Dumb_unhurt
{2840}{}{I'm sorry, but if you're not here for treatment, I must ask you to leave and make room for those who require medical attention. Goodbye.}

{2870}{}{Ah, yes. I've heard about that from her. Thank you so much. Well deserved, well deserved.}
