# Grammar pass done

{100}{}{You come across a large, rugged dog with a wild appearance.}
{101}{}{A dusty and forlorn dog catches your eye, displaying a docile demeanor.}

{105}{}{*whimper*}

{110}{}{Grrrrrr. Woof! Woof! Grrrrrr...}
{111}{}{Woof, Arf, Arf?}
{112}{}{[Locking eyes with the dog] Grrrr! Arrrrrgh! Grrrrrrrr!}
{113}{}{Hmm, I bet you sound angry because you want something.}
{114}{}{Are you hungry, boy? Let me check if I have a tasty treat to offer you.}

{120}{}{Woof! [The dog leaps forward, teeth bared, and snatches the jerky from your outstretched hand, munching on it noisily.]}
{121}{}{Woof! [The mongrel happily snatches the yummy drymeat.]}
{122}{}{Mmm, jerky.}
{123}{}{Ah, poor thing, you must have been famished. [You pat the dog's head gently.]}

{130}{}{Grrr. Woof! Woof!}
{131}{}{Arf-arf, little doggy. Heh, heh.}
{132}{}{Bye, doggy.}
{133}{}{Apologies, no treats for you today, pup.}
{134}{}{Shoo! Get out of here, you darn mutt.}

{140}{}{Woof, woof. Woof-woof!}
{141}{}{Woof, woof? Eru?}
{142}{}{Good doggy, good boy.}
{143}{}{You're hungry, aren't you, boy? I bet you'd love some delicious snacks. Let me check if I have something for you.}

{200}{}{Woof! *pant, pant, pant -- slurp!*}
{201}{}{Woof-woof!}
{202}{}{Arf!}
{203}{}{Arf, arf, arf!}
{204}{}{[Stares at you lovingly]}
{205}{}{Woof!}
