# Message file for tbprsn.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see a Floating Eye Bot.}
{101}{}{You see the order-keeping bot of Tibbets.}
{102}{}{Presenting the Floating Eye Bot, a silent and vigilant security backup.}

{150}{}{This is an ancient, but well-maintained bot. Its upper portion houses the CPU, motivator and the sensors. The extending arm below is equipped with a low power energy prod.}

# Node 0 [Floats]
{200}{}{I'm not here for idle conversation.}
{201}{}{I'm not a service bot. I don't answer to you.}
{202}{}{Move along, Number 13.}
{203}{}{*bzzzzzzt*}
{204}{}{Please refrain from patting me or referring to me as cute.}
