# Grammar pass done

{100}{}{You see no apparent way to utilize the emitter.}
{101}{}{There doesn't seem to be any means to manipulate the forcefield.}
{102}{}{You're shocked by the weakened forcefield.}
{103}{}{ is shocked by the weakened forcefield.}
{107}{}{You're shocked by the forcefield.}
{108}{}{ is shocked by the forcefield.}
{109}{}{Your attempts to affect the forcefield prove unsuccessful.}
{110}{}{ fails in their attempt to lower the forcefield.}
{111}{}{A warning blares over the loudspeaker: "Security breach detected. Activate all defense systems. Alert ARGOS!"}
{112}{}{You successfully deactivate the forcefield.}
{113}{}{ successfully deactivates the forcefield.}
{114}{}{You activate the forcefield.}
{115}{}{ activates the forcefield.}
{116}{}{You obliterate the forcefield emitter.}
