# Message file for tbgamma.ssl
# Number of nodes: 11
# Grammar pass done

{100}{}{You see a confident-looking man.}
{101}{}{You see Gamma the Hun. Always exuding confidence.}
{102}{}{Upon closer inspection, you notice his constant state of alertness.}

{105}{}{Can't you see I'm busy here, kid?}

# Node001
{200}{}{Hey there, kid.}
{201}{}{The name's }
{202}{}{. And you are?}
{203}{}{Can you spot me?}
{204}{}{Hey there, old man.}
{205}{}{Gotta run!}
{206}{}{[Point at him.]}
{207}{}{Me go.}

# Node002
{230}{}{They call me Gamma the Hun.}
{231}{}{Gamma the Hun?}
{232}{}{Gum the Honey?}
{233}{}{I have a second name too, they call me Number 13 here.}
{234}{}{That's the most ridiculous name I've ever heard. Why not just call yourself Genghis Khan and be done with it?}

# Node003
{260}{}{I see you've never heard of the Huns, the great warriors of the past! But if you've encountered the Legion or even the Khans, then you've tasted some of that past glory. You know, we people are a cursed bunch. Our greatest flaw is that we forget. Look at us, we've forgotten about all the great things from our past and we're willing to kill our fellow men for a fistful of bottle caps. sigh It's our duty to remember and hold onto greatness. Wouldn't you agree, }
{261}{}{?}
{262}{}{I'm not much into books, history, or what life was like for our ancestors a million years ago. I'm living in the present, in reality.}
{263}{}{Absolutely, sir, I mean, sir Hun. Your wisdom is as vast as your deltoids.}
{264}{}{I couldn't agree more, Gamma. Luckily, my Pip-Boy never forgets.}

# Node004
{290}{}{Sure thing, kid. Do you know what you're doing?}
{291}{}{Watch this!}
{292}{}{Heh...}

# Node005
{320}{}{So, are you here to pump iron or just proudly display your ignorance of our nation's glorious history?}
{321}{}{I'll happily live and die in ignorance. What's in the past should stay there.}
{322}{}{Why the hell not? Can you spot me?}
{323}{}{[Leave without saying a word.]}

# Node006
{350}{}{Let me give you some advice since it seems nobody else has. Escaping won't be easy here. People have nothing to lose. It's better to be nice to others unless you want trouble.}
{351}{}{And what if I enjoy causing trouble and don't particularly like you?}
{352}{}{I apologize for being rude. Sometimes, it helps break the ice with new faces I meet.}

# Node007
{380}{}{Knowing that you don't like me will probably keep me up at night. What will I ever do?}
{381}{}{Well, maybe you shou--}
{382}{}{Whatever, I'm outta here.}

# Node008
{410}{}{What an idiot! Stop wasting my time. Get out of my sight.}
{411}{}{Me no idiot! Me angry!}
{412}{}{Yes.}
{413}{}{Okay.}
{414}{}{Make me.}

# Node009
{440}{}{[He whistles while pointing at you.] Hey Martin, it's barbecue time!}
{441}{}{Wha--}
{442}{}{Mmmmm... barb-q.}

# Node009b
{450}{}{Barbecue time!}

# Node010
{470}{}{That's what I thought. Just an ignorant, weak punk.}
{471}{}{You talk big. Let me teach you a lesson.}
{472}{}{[Just leave.]}

# Node011
{500}{}{As long as it doesn't break your bones. So, are you here to lift weights or just test my patience?}
{501}{}{Let's pump some iron!}
{502}{}{I'm good. See you around... old man.}
{503}{}{I'm good. See you around.}
