# Message file for tbgail.ssl
# Number of nodes: 5
# Grammar pass done

{100}{}{You see an older, attractive woman.}
{101}{}{You see Gail the Meat Cleaver.}
{102}{}{Her head is shaved, and she's wearing a blood-stained uniform.}

{150}{}{That will leave a nasty scar but hey, you feel better than ever!}

# A1
{230}{}{Hel- Ouch! Looks like you've gotten yourself into quite a mess. And those makeshift bandages... You must have a deathwish, my boy. You should have sought professional help ages ago! Sit down on the table right now!}
{231}{}{Hel- Ouch! Looks like you've gotten yourself into quite a mess. And those makeshift bandages... You must have a deathwish, my girl. You should have sought professional help ages ago! Sit down on the table right now!}
{232}{}{But... [Obey her.]}
{233}{}{I don't really need your help right now.}
{234}{}{Me good. Me go.}

# B1
{260}{}{Hi there, youngster. I see you're a new face in prison. Hope you're staying out of trouble. But if you've already found it, you've come to the right place. So, what can Gail do for you?}
{261}{}{Hi, I'm }
{262}{}{. I was just getting to know people in Tibbets. Maybe you could answer some questions for me?}
{263}{}{I just couldn't help but notice that you're looking quite good for your age.}
{264}{}{I doubt an old crone like you could be of any use to someone like me.}
{265}{}{Sorry, I mistook you for someone else. I'll be going now.}
{266}{}{[Drool a bit on the floor and then leave.]}

# C1
{290}{}{Ah, well, there's not much for me to say. I used to be a debt collector, but now I'm the Prodigal Surgeon, or Gail the Meat Cleaver, or Gail the Loose Cannon, depending on who you ask. Some of the scars you see on other prisoners are my handiwork. But if that's what it takes to save a life, then so be it.}
{291}{}{I see. Impressive work, by the way. I've seen some of it already.}
{292}{}{Wow, I've seen the scars you left on some of those poor souls! I can only imagine the pain they endured. Did you ever lose a patient?}
{293}{}{I suppose it's been a difficult path with little reward, I imagine. I believe in people helping each other if we want to rebuild our society from the ashes. You know what I mean?}
{294}{}{Alright then. I'll leave you to your work.}
{295}{}{Look, Gail, I think it's about time you reconsider your career. It's just not suited for someone with your... unique approach. Let's put it that way. Maybe it's time to put up a big, glowing ad that says: "Gail and The Soft Parts. They painfully bleed to death when she touches them."}

# D1
{320}{}{Nice to see you again, darlin'. And in one piece, no less. Are you here to chat or are you feeling worse than you look?}
{321}{}{I thought I'd stop by for a chat. I have some questions you might be able to answer.}
{322}{}{Um, I'm fine, thanks. Bye.}
{323}{}{Hey, I noticed something different about your hair. You look absolutely stunning today.}

{350}{}{[She blushes.] Well, thank you, darlin'. I'm flattered. Is there anything else you need?}
{351}{}{I'd like to get to know you better.}
{352}{}{No, nothing else. Have a great day, Gail.}
