# Grammar pass done

{100}{}{You see a loser.}
{101}{}{You see Lex.}
{102}{}{[CONTINUE]}
{103}{}{[END]}
{104}{}{[Lex whispers.] Best be careful. Rock doesn't always tell the truth.}
{105}{}{Why do you say that?}
{106}{}{Why should I trust you?}
{107}{}{Rock is a member of the Crypts, a gang. He tries to get strangers, like you, into trouble. If you listen to him, you might find yourself dead and buried.}
{108}{}{Who are you?}
{109}{}{Thanks for the info. Have a good day.}
{110}{}{I'm Lex. Scrapheap is my home, and I guess I speak for its people.}
{111}{}{Anyone else I should know about?}
{112}{}{Well, there are also the Fools. They would control Scrapheap, if the Crypts were gone. The two gangs are fighting over who controls this place. Currently, the Crypts are on top. Now that you are here, things might change.}
{113}{}{What makes you say that?}
{114}{}{If you could get rid of the gangs, we would be grateful. We don't have the numbers or the strength to drive them off, and few people care about this place. If you do care, we might be able to help you.}
{115}{}{What do you mean?}
{116}{}{I've heard of you. You're looking for the lost city of Necropolis. A grateful people could provide you with information on where to go.}
{117}{}{I'll consider it.}
{118}{}{We could ask for nothing more.}
{119}{}{Bye.}
{120}{}{I have some questions.}
{121}{}{Why shouldn't you? I have the best interests of my people at heart, and I would like to see you avoid harm.}
{122}{}{What do you mean?}
{123}{}{There are forces at work here in Scrapheap that would like to use you, and if that's not possible, to see you dead and buried. Choose your friends wisely, and choose your enemies with even more care. Good day.}
{124}{}{Yeah, good day.}
{125}{}{We thank you for getting rid of the Crypts and the Fools. Without the power generator, my people will have a hard life. Do you think you could fix it?}
{126}{}{Of course.}
{127}{}{Fix it yourself. I want my reward.}
{128}{}{Thank you.}
{129}{}{Very well, you shall have it. You have cast my people into a cold night, and then abandoned us to the wolves - but I understand that your quest is more important.}
{130}{}{The violence you have started may lead straight back to my people. Please finish it.}
{131}{}{Just like you cowards to lay the task of death on the shoulders of others.}
{132}{}{I'm working on it.}
{133}{}{If you need help, I will provide it, but don't ask my people. They are too weary of death and pain. I will join you, if that is what you wish.}
{134}{}{Yes, follow me, and attack when I do.}
{135}{}{No. I'm just making a social comment.}
{136}{}{Just as I suspected, you don't care about anything except your own needs. Join our enemies, bring fear to my people, and betray your own background.}
{137}{}{I'm going to kill you for saying that.}
{138}{}{It's a plan. I'm infiltrating this gang.}
{139}{}{Shut up.}
{140}{}{I thought you would, you worm.}
{141}{}{Perhaps, but actions speak louder than words.}
{142}{}{You'll see.}
{143}{}{What can I help you with?}
{144}{}{Tell me about the power generator.}
{145}{}{Tell me about the Crypts.}
{146}{}{Tell me about the Fools.}
{147}{}{Tell me about Scrapheap.}
{148}{}{Nothing else, thanks.}
{149}{}{Scrapheap is our town. It was our home. And hopefully, it will be again.}
{150}{}{The power generator supplies all the electricity in town. Without it, we would surely die. It is the most important thing in town. Whoever controls it, controls Scrapheap.}
{151}{}{The Crypts are a gang run by Rayze. He's an animal and has one of the largest guns I've ever seen. He lets Lenny live, cuz he takes care of the Brahmin, which provide fuel for the generator. The Crypts are in the big house.}
{152}{}{Baka leads the Fools. If she had any more men, she'd surely attack the Crypts and try to take back the power generator. You can tell the Crypts from the Fools by their armor. Fools wear metal, Crypts wear leather.}
{153}{}{We thank you for getting rid of the Crypts and the Fools.}
{154}{}{I want my reward.}
{155}{}{You are welcome, Lex. Good luck!}
{156}{}{Of course. Please accept this book. The information contained within will help you in your travels.}
{157}{}{Thanks, Lex. But I have to refuse. You probably need it more than I do.}
{158}{}{Thank you, Lex. I am sure I'll find it useful.}
{159}{}{A book? That blows. So long, losers.}

# Dumb lines

{205}{}{Why you say?}
{206}{}{Why me trust you?}
{208}{}{Who you?}
{209}{}{Thank. Gud day.}
{211}{}{Who else important?}
{213}{}{Why you think so?}
{215}{}{What you mean?}
{217}{}{Me think on it.}
{219}{}{By.}
{220}{}{Me asks.}
{222}{}{What you mean?}
{224}{}{Yeah, gud day.}
{226}{}{Sure.}
{227}{}{You fix. Me want reward.}
{231}{}{You scared, make others die.}
{232}{}{Me work on it.}
{234}{}{Yeah, follow. Attack when me do.}
{235}{}{No. Me just talk.}
{237}{}{Me kill you for say that.}
{238}{}{Plan good. Me join gang.}
{239}{}{Shut it.}
{242}{}{You see.}
{244}{}{Tell about power thing.}
{245}{}{Tell about Kraps.}
{246}{}{Tell about Fulls.}
{247}{}{Tell about Craphippie.}
{248}{}{No more, thank.}
{254}{}{Want reward.}
{255}{}{Welcome, Lex. Gud lack!}
{257}{}{Thank, Lex. But no. You need more.}
{258}{}{Thank, Lex. Me find useful.}
{259}{}{Toilet paper? Bad. Bye, loser.}

# Description - GoatBoy
{300}{}{Despite his meager appearance, he tries his best to exude an air of authority. Doesn't seem to be working though.}