# Message file for tblinder.ssl
# Number of nodes: 13
# Grammar pass done

{100}{}{You see a seasoned physician at the facility.}
{101}{}{You see Dr. Linder, a respected doctor with years of experience.}
{102}{}{A tag on his suit identifies him as Dr. Linder Kosh.}

{150}{}{You did well. Our volunteer is recovering well over at the Genetics Sampling.}

# linder1
{200}{}{Greetings, }
{201}{}{. I'm nearly done examining the Organ Extraction Unit. How can I assist you?}
{202}{}{Hello, Doctor. I'm not a patient, just a recently arrived prisoner visiting the facility.}
{203}{}{What seems to be the issue with the Organ Extraction Unit?}
{204}{}{Oops, wrong turn. My apologies.}
{205}{}{I go fix metal table.}
{206}{}{Where I?}

# linderA
{230}{}{Ah, I have your records, and I recognize you. So, you're not a new patient? Are you feeling mentally well?}
{231}{}{Yes, actually, I should be on my way.}
{232}{}{Yes, though I must admit, I feel a bit apprehensive being here.}

# linderB
{250}{}{Goodbye, }
{251}{}{. Take care.}

{260}{}{Before you leave, }
{261}{}{, I wanted to inform you that Dr. Davide and I are working on a cure for insanity. We need a volunteer. Could you ask around and see if any patients are interested? It would greatly aid our research.}
{262}{}{Of course, Doctor. I can do that.}
{263}{}{Is there anyone specific you had in mind?}
{264}{}{I'm afraid I have other objectives to focus on at the moment.}

# linderC
{290}{}{No need to worry. Just be yourself and avoid touching the electrical fence.}
{291}{}{Wait, are you saying I could get zapped?}
{292}{}{Understood, I'll make sure to steer clear of it.}
{293}{}{I'm still uncertain about the safety of this place.}

# linderD
{320}{}{Thank you, }
{321}{}{. I'll eagerly await your return.}
{322}{}{Goodbye. Take care.}

# linderE
{350}{}{No worries, don't let it bother you.}

# linderF
{380}{}{Believe me, }
{381}{}{ this place is the safest on the planet. We're nestled deep in the mountains, surrounded by cliffs and an electrical fence. We have a direct connection to Tibbets and thousands of robots. It's a forgotten sanctuary.}
{382}{}{You're right. I should be on my way now.}
{383}{}{You smart. Me go now.}

# linder1sci
{410}{}{The system hasn't been used in a long time, so some settings, like the time, need to be reset.}
{411}{}{Won't that affect the accuracy of the dates?}
{412}{}{That makes sense. Goodbye.}

# linder2sci
{430}{}{At least there's an easy solution. Goodbye, Doctor.}

{440}{}{Actually, the calendars repeat every 28 years, so as long as everyone keeps that in mind, the dates will be accurate.}
{441}{}{At least there's an easy solution.}
{442}{}{That's fortunate, but I need to be on my way now.}

# linder2
{460}{}{Me? Spec-ial? Thank. Bye!}

{470}{}{Oh, I see. You must be quite special to have found your way here.}
{471}{}{Me? Spec-ial?}
{472}{}{Me go.}

# linder3sci
{500}{}{Speaking of solutions, you seem like a resourceful person. While you're out, could you ask around and see if any patients are interested in volunteering for my and Dr. Davide's experiment? We're swamped with other tasks.}
{501}{}{What kind of volunteers are you looking for, Doctor?}
{502}{}{I think I can find someone for you, Doctor.}
{503}{}{I'm afraid I'll be too busy to help with that.}

# linder3
{530}{}{Yes, indeed. I have a special assignment for you. While you're outside, could you find an animal or a plant and bring it back to me?}
{531}{}{Me do for you.}
{532}{}{Me don't think me can.}

# linderquestion
{560}{}{Certainly, the volunteer should be someone with a mental illness. That's the only requirement we have.}
{561}{}{Alright, I'll ask around and see if anyone's interested.}
{562}{}{I'm sorry, I can't assist you with that.}

# linderagain
{590}{}{Hello again. If it's not urgent, it will have to wait.}
{591}{}{Um, I have this head here. Do you have the technology to extract information from it somehow?}
{592}{}{Sorry for the interruption. Goodbye.}
{593}{}{Me soooooory. Bye, Doc.}

{620}{}{A head?! A prisoner's head?}
{621}{}{Oh, no. This one was a traitor in the Brotherhood of Steel. He attempted to assassinate the Brotherhood's commander but refused to disclose any information before I killed him. Maybe in death, he'll talk more. What interests me is anything related to the so-called "Circle of Steel."}
{622}{}{Actually, I was only joking. Goodbye!}

{650}{}{Hmm, I see. This better not get me into any trouble with the Warden. Alright, for the sake of science and progress, we'll conduct the extraction free of charge. Leave the subject's head with me, and return in a week. We'll attempt to extract something valuable from his neurons. [His eyes light up with excitement in the dim light.]}
{651}{}{I can wait here for a week. I don't have any other pressing matters.}
{652}{}{Very well, Doctor. I'll return in a week.}

{680}{}{Welcome back! I have some exciting news to share. With Dr. Davide's assistance, we successfully extracted two valuable pieces of information regarding the "Circle of Steel." The late subject had contact with a caravan at Hoover Dam, and we also discovered the secret location of their hideout.}
{681}{}{Please, Doctor, spill the beans!}

{710}{}{Certainly! I've marked the exact location of the hideout on your Pip-Boy. According to your map data, it should be southeast of Tibbets, approximately a two-week journey on foot. Unfortunately, we couldn't retrieve any specific details about the caravan contact. The information was disintegrated beyond recovery.}
{711}{}{I see. Anything else? Did you find any information on how he got involved with the Circle of Steel? What about the Brotherhood armory codes?}

{740}{}{I'm sorry to say that we didn't find any armory codes. However, we did uncover some intriguing details about Devon Hill, the late subject.}
{741}{}{Please, Doctor, tell me everything. I'm eager to know.}
{742}{}{I'm not particularly interested in his story. Thank you for your assistance, Doctor.}

{770}{}{Devon Hill started his journey as a grunt within the Brotherhood of Steel. Over the years, he displayed unwavering dedication and exceptional combat skills, leading to several promotions and commendations.}
{771}{}{[CONTINUE]}

{800}{}{He was later chosen to join a covert stealth team that utilized experimental devices. Hill eagerly embraced this opportunity and excelled in his training. Throughout various assignments, he showcased his remarkable abilities. Unfortunately, due to the classified nature of his work, his achievements remained unrecognized by the public. Nevertheless, he understood the importance of his covert missions and accepted them wholeheartedly.}

{830}{}{Tragically, Hill became a victim of the very devices he used - the Stealth Boys. Prolonged exposure to these devices resulted in paranoia, delusions, and ultimately, schizophrenia. When this alarming development came to light, the devices were banned, and the team was disbanded. However, little did they know that the team had already begun experiencing the side effects of the Stealth Boys. Believing in a conspiracy, they decided to steal the remaining devices and form a new covert operation known as the Circle of Steel. Hill was left behind at the base as an undercover operative, tasked with concealing the theft of the Stealth Boys. That's the entire story we managed to extract.}
{831}{}{Thank you, Doctor. That was incredibly insightful.}
