# Message file for tbmgkman.ssl
# Number of nodes: 4
# Grammar pass done

{100}{}{You spot an individual donning a worn-out jumpsuit.}
{101}{}{One of Magik's underlings stands before you.}
{102}{}{He's putting on a tough act.}

# Node_Intro
{200}{}{Think twice before stepping foot in here. Magik doesn't welcome newcomers like yourself kindly.}
{201}{}{Think twice before stepping foot in here. Magik doesn't welcome newcomers like yourself kindly.}
{202}{}{Who is Magik?}
{203}{}{Can you provide some information about this cell block?}
{204}{}{Thanks for the heads-up.}
{205}{}{Huh?}
{206}{}{[Ignore him.]}

# Node_Royce
{230}{}{He's the one running the show around here. If you want to make a purchase, talk to him. Otherwise, it's best to leave him be. He's not known for his patience.}
{231}{}{What's your role here?}
{232}{}{Goodbye.}

# Node_Shop
{260}{}{This operation belongs to Magik. We offer support by buying all the surplus junk that other prisoners don't need and selling it.}
{261}{}{Tell me more about Magik.}

# Node_Dumb1
{290}{}{Never mind, you should be fine. Go talk to Magik; he'll give you a fair deal.}
{291}{}{Alright.}
