# Message file for tbprsn.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see a shady person.}
{101}{}{You see someone seemingly pondering the paths they've taken in life.}
{102}{}{You see an individual donning a jumpsuit emblazoned with the number 13, much like your own.}

# Node 0 [Floats]
{200}{}{*yawn*}
{201}{}{I wonder what old movies are on Holo-TV tonight?}
{202}{}{Gotta study for the exam.}
{203}{}{Where's my shiv?}
{204}{}{Fucking robots.}
{205}{}{Why am I here?}
{206}{}{Can't wait until the culinary classes start!}
{207}{}{When are they letting us out?}
{208}{}{My CODE needs to be higher or I'll never leave.}
{209}{}{Wish I had a stick of dynamite right now.}
{210}{}{Fuck the Warden!}
{211}{}{Freedom!}
{212}{}{Fuck ODYSSEUS! I'll beat his tin can ass back to the assembly line.}
{213}{}{I'm innocent!}
{214}{}{I regret nothing.}
{215}{}{Where are we?}
{216}{}{I feel safer here than outside.}
{217}{}{Can I get a different number for my jumpsuit?}
{218}{}{Cell block 21 is where all the fun is. Ummm.. the rumor has it.}
{219}{}{I wonder who's in Cell block 1?}
{220}{}{~One more kiss, dear, one more sigh~}
{221}{}{~Only this dear, is goodbye~}
{222}{}{~For our love is such pain and such pleasure~}
{223}{}{~That I'll treasure till I die~}
{224}{}{~So for now dear, Aurevoir, madame~}
{225}{}{~But I bow dear, not farewell~}
{226}{}{~For in time we may have a love's glory~}
{227}{}{~Our love story to tell~}
{228}{}{~Just as every autumn leaves fall from the tree~}
{229}{}{~Tumble to the ground and die~}
{230}{}{~So in the springtime like sweet memories~}
{231}{}{~They will return as will I~}
{232}{}{~Like the sun dear, upon high~}
{233}{}{~We'll return dear, to the sky~}
{234}{}{~And we'll banish the pain and the sorrow~}
{235}{}{~Until tomorrow, goodbye~}
{236}{}{Give me freedom or give me death!}
{237}{}{Hey you! Yes, you. The monitors aren't what they seem.}
{238}{}{Is there anything worse than prison food?}
{239}{}{I need an escape plan.}
{240}{}{I never asked for this.}
{241}{}{*burp*}
{242}{}{I ain't afraid of nobody!}
{243}{}{*cough*}
{244}{}{*sniff*}
{245}{}{This cough is going to kill me.}

{300}{}{What's happening?!}
{301}{}{Are we under attack?}
{302}{}{Something feels off.}
{303}{}{Soldiers are storming the prison!}
{304}{}{This might be my chance to escape!}
{305}{}{Run for it!}
{306}{}{Farewell, fools! I'm getting out of here.}
{307}{}{I heard gunfire.}
{308}{}{The noise came from the eastern hallway.}
{309}{}{We're all doomed!}
{310}{}{Earthquake!}
{311}{}{Where's my shiv?}
{312}{}{Fucking robots.}
{313}{}{Wish I had a stick of dynamite right about now.}
{314}{}{Freedom awaits!}
{315}{}{~Only this dear, is goodbye~}
{316}{}{~So for now dear, Aurevoir, madame~}
{317}{}{~Until tomorrow, goodbye~}
{318}{}{*cough*}
{319}{}{*sniffle*}
