# Message file for tbrobrta.ssl
# Number of nodes: 12
# Grammar pass done

{100}{}{You see a middle-aged woman, her once-dark hair now considerably gray.}
{101}{}{You see Roberta.}
{102}{}{A woman looks at you with a disturbing smirk on her face.}

#TakeStuffAndRun - Added Display Message for Roberta running away
{150}{}{Without a second thought, Roberta dashes out the room and disappears; the metallic *twang* of her footsteps quickly fading into nothingness.}
{151}{}{... You suddenly feel quite dumb.}

# Initial
{200}{}{Please! You must have some task I can do. I need caps to feed my children.}
{201}{}{What's your name?}
{202}{}{Leave me alone, peasant.}
{203}{}{[Give her a bottlecap.]}
{204}{}{Hughn! [Shrug your shoulders.]}

# no_jobs_1
{230}{}{My name's Roberta.}
{231}{}{Why don't you find a job, Roberta?}
{232}{}{Nice to meet you, Roberta. Goodbye.}

# no_jobs_2
{260}{}{There are no available jobs around here, at least none for me. I've tried countless times, but they're all too messed up.}
{261}{}{How have your children survived this long with you being broke? Aren't you provided with meals here like everyone else?}
{262}{}{I don't care. Leave me alone, you filthy beggar.}

# no_jobs_3
{290}{}{Well, not all of them survived, to be honest. And the portions here are smaller than in prison. I used to work as a caravan guard, but that's no longer an option, obviously. There was a prisoner named Martin who offered me 50 caps to take out my own daughter, but I quickly spent that money.}
{291}{}{Why not try something else?}
{292}{}{I don't care. Go sell your sad story to someone else and leave me alone.}
{293}{}{Excuse me? You did what?!}
{294}{}{[Back away slowly.]}
{295}{}{You monster! I'll make you pay for what you've done!}

# no_jobs_4
{320}{}{Well, I went on a few trips, and most were okay. But a couple of times, we were attacked by really aggressive tribes. I'm not good under fire - I froze up or ran and hid every time.}
{321}{}{Let me guess...}
{322}{}{I don't care. Get away from me, you bum.}

# no_jobs_5
{350}{}{After my last run with the Crimson Caravan, they told me not to bother signing up again because I was useless as a guard, and they wouldn't take me with them anymore.}
{351}{}{I could take you along with me. I'll pay you 20 caps for each of my enemies you kill.}
{352}{}{Boo hoo. Cry me a river. Speak to me again, and I'll kill you.}

# no_jobs_6
{380}{}{20 caps each, huh? Well, that sounds fair! But I can't leave my two children here all alone. Who would feed them? Maybe if I got rid of them too, like I did with the eldest.}
{381}{}{No, forget it. How else can you help me? I'm not staying here forever. I need to find a way out.}
{382}{}{I don't know, and I don't care.}
{383}{}{What the... Die, monster!}

# no_jobs_7
{410}{}{I can help you with that. You look like you have more important things to do than stand here all day talking. I can sell your belongings for you if you want.}
{411}{}{What are you talking about?}
{412}{}{Right. Belongings. How can I trust you not to run off with everything I own?}

# no_jobs_8
{440}{}{You're mean. I'll find someone else who can help me.}
{441}{}{You're not getting away with this!}
{442}{}{Whatever.}

# no_jobs_9
{470}{}{I'll stay here and sell your items for you, and you'll give me 10% of the profits. We both win. What do you say?}
{471}{}{How can I trust you not to run off with everything I own?}
{472}{}{No way. I don't trust you. Leave me alone.}

# no_jobs_10
{500}{}{You can trust me, I promise. I need a steady income for my children. If I run off with your belongings, sure, I'll have more money now, but in the long run, I'll only harm myself.}
{501}{}{Alright. It's a deal, Roberta.}

# no_jobs_11
{530}{}{Really? Thank you so much. I'll take these from you now and find buyers right away. You won't regret this. We'll both profit from it. I have to hurry home, cell block 12, and tell the kids that Mommy has a job!}
{531}{}{Sure thing. Just make sure not to damage the merchandise.}
{532}{}{Wait, stop. I haven't noticed any elevator in the Security Hub that leads to cell block 12. You're lying. The deal's off.}
