# Message file for tbsandy.ssl
# Number of nodes: 50
# Grammar pass done

{100}{}{You see a young, bearded man with a blissful smile on his face.}
{101}{}{You see Sandy Fats.}
{102}{}{His jumpsuit is frayed and patched, but he doesn't seem to care.}

# Member
{230}{}{Greetings, brother! Another glorious day, blessed by the Troposphere!}
{231}{}{Greetings, sister! Another glorious day, blessed by the Troposphere!}
{232}{}{Certainly! I'm here to ask you some questions.}
{233}{}{Brother? What does that mean?}
{234}{}{Sister? What does that mean?}
{235}{}{Alright, take care. Goodbye.}

# Questions
{260}{}{Of course. What would you like to know?}
{261}{}{Tell me about your religion's beliefs.}
{262}{}{What's your story?}
{263}{}{What do you do around here?}
{264}{}{How can I join the Rainmakers?}
{265}{}{Some of the prisoners are upset that robots won't let them leave. What are your thoughts on this?}
{266}{}{Actually, never mind. Goodbye.}

# FirstTime
{290}{}{Welcome, friend. I am Sandy Fats, a proud member of the Rainmakers. How can I assist you?}
{291}{}{Sandy Fats? What kind of name is that?}
{292}{}{I have some questions for you.}
{293}{}{Nothing for now. Goodbye.}
{294}{}{Hello!}

# Subsequent
{320}{}{Welcome back, friend. How can I assist you?}
{321}{}{Nothing for now.}

# BrotherSister
{350}{}{I heard the wonderful news that you have joined our religion, friend. You are now part of our family, along with all of Troposphere's children.}
{351}{}{Troposphere's children?}
{352}{}{That's great, Sandy. I have some questions for you.}
{353}{}{I'm not sure I want to be part of your family.}
{354}{}{Good to know. Take care.}

# ChildrenMember
{380}{}{We, the Enlightened, also known as the Washed Ones, believe that all the prisoners here are disciples of the great Troposphere. They are members of our church just like us. Let the Troposphere's rain of grace wash over us!}
{381}{}{So, I'm part of an exclusive club with all the nutcases in Tibbets?}
{382}{}{I'm glad I chose this religion. I have some questions for you.}
{383}{}{That's unsettling. Can I stop being a disciple of the great Troposphere?}

# Sandy
{410}{}{It is the name I adopted upon joining the Rainmakers. In the language of our religion, it means "open door."}
{411}{}{What does an open door have to do with anything? Your name sounds more like "fat sand" to me.}
{412}{}{Tell me about your religion.}
{413}{}{I want to know about something else.}

# TellStory
{440}{}{It will become clear when you hear the tale of how I found the grace and love of Troposphere. It's a story of tragedy, loss, and eventual redemption.}
{441}{}{I'm intrigued. Please, continue.}
{442}{}{Let me ask you about something else first.}
{443}{}{Maybe some other time. Goodbye.}

# Notfamily
{470}{}{[His smile falters for a moment, then returns.] Yes. You seem like an independent man. But even if you choose to leave, remember that the prayers of Troposphere's faithful go with you. Whether you accept it or not, you are our brother.}
{471}{}{[His smile falters for a moment, then returns.] Yes. You seem like an independent woman. But even if you choose to leave, remember that the prayers of Troposphere's faithful go with you. Whether you accept it or not, you are our sister.}
{472}{}{That's unsettling. I'm not sure I want to stay in this group.}
{473}{}{I appreciate it, Sandy. I have some questions for you.}
{474}{}{Alright then. Goodbye.}

# KilledCultist
{500}{}{Friend, I am truly saddened by your excommunication. I believed you could spread Troposphere's word to the rest of the wasteland. It's a pity, a pity.}
{501}{}{Yeah, it turned out I had a couple of brain cells left after all. Maybe you should use yours sometime.}
{502}{}{The rest of the wasteland has enough challenges without having to deal with your crazy religion.}
{503}{}{I'm sorry for disappointing you. Take care.}

# QuitReligion
{530}{}{[He looks shocked.] I can't understand why anyone who has found true Enlightenment would want to turn away from it.}
{531}{}{But let's say someone did. How would they go about leaving?}
{532}{}{You're right. I don't know why anyone would want to do that. I have other questions.}

# HowToQuit
{560}{}{If someone were to harm one of Troposphere's children, we would be forced to cast them out. But such an act would be unthinkable and impossible for a person of true faith!}
{561}{}{That sounds fair. I have other questions.}
{562}{}{I'll make sure not to harm anyone. Goodbye.}

# BrainCells
{590}{}{You may mock me now, but when you perish and are denied a Second Life in the service of Troposphere, you will see the folly of your blasphemy. I will pray for you to see the light and return to the fold someday.}
{591}{}{I wouldn't hold my breath.}

# RestWastes
{620}{}{*Sigh* Perhaps another missionary will appear one day to convince the masses of the True Faith. Nonetheless, I wish you good luck in your travels, despite your blasphemy. Maybe you will one day return to the embrace of Troposphere.}
{621}{}{Maybe. Goodbye.}
{622}{}{Yeah, right after my lobotomy. Farewell.}

# LifeStory
{650}{}{I was born in this very prison, in a cold cell. I have never ventured far from this place. My destiny, guided by the great Troposphere, is tied to Tibbets.}
{651}{}{Go on.}
{652}{}{That explains a lot. Spending decades here would drive anyone crazy.}
{653}{}{Tell me more about Troposphere.}
{654}{}{I have other questions.}

# Crazy
{680}{}{Perhaps it is you who has been driven insane by the relentless bleakness of these wastes. I was lost, but when I found faith, the fog cleared, and I saw the truth.}
{681}{}{It's possible. Continue with your story.}
{682}{}{Spare me the sermon. I want to ask about something else now.}

# LifeStory2
{710}{}{Growing up here was challenging, with many trials and hardships along the way. My father, a troubled man, left when I was just nine years old, and I had to work for Magik, the trader.}
{711}{}{That's tough. You must hold some resentment toward your father.}
{712}{}{Tell me more about working for Magik.}
{713}{}{I want to know about something else now.}

# AngryDad
{740}{}{That's true. Until I joined the Rainmakers, I harbored anger towards my father for abandoning me. But doesn't Supercell teach us, "Do not carry the fires of anger in your heart towards anyone, lest the rain extinguishes your being like a flame?"}
{741}{}{That is true. Preach on, Sandy Fats.}
{742}{}{But didn't he also say, "Do not allow anyone to deny you the drops of heaven on your forehead?"}
{743}{}{If you say so.}

# BadQuote
{770}{}{I confess, that is not a quote I am familiar with, and I consider myself a student of Troposphere. I think you might be mistaken, my friend.}
{771}{}{You're right, I'm not sure where that came from. Please continue with your story.}
{772}{}{You're clearly not as advanced within the religion as I am. I happen to hold a Level 8 Doctorate in Theology, so please show some respect.}

# Taunt
{800}{}{[He smiles broadly.] Ah, I see you're attempting to taunt me. This is common among unbelievers. I suggest you learn more about our religion, and perhaps you'll see the light.}
{801}{}{Sorry. Please continue the story you were telling.}
{802}{}{Alright, tell me about your religion.}
{803}{}{Not likely. Goodbye.}

# LifeStory3
{830}{}{For seven years, I worked in the filth of these corridors, cleaning cells, carrying bags of junk, and scrubbing floors. It was a series of humble and demeaning tasks. Magik is a profane man, and I doubt he will ever accept Troposphere as his Savior. He treated his employees poorly, and I've heard he still does.}
{831}{}{So, that's why you left?}
{832}{}{I have other questions now.}

# LifeStory4
{860}{}{Indeed, it was. But one day, Magik tripped over a bag I placed on the floor and injured himself. Despite my apologies, he refused to listen and cast me out from the job I had faithfully performed for all those years.}
{861}{}{That's tough. I have another question for you.}

# LifeStory5
{890}{}{It was a truly dark time for me. I had no friends and no purpose. I spent my nights drowning in cheap alcohol, a helpless, drunken wretch, lying in the filth of my cell. Then they transferred me to a special place in Tibbets, the only spot where you can see the clear sky. And there... who did I see?!}
{891}{}{Troposphere!}
{892}{}{The Welcoming Committee Director!}
{893}{}{I don't know!}

# LifeStory6
{920}{}{Exactly! The great Troposphere Himself appeared to me in all His glory! Descending from the sky, unfolding His majestic wings, surrounded by radiant light. A chorus of raindrops resounded as if lightning bolts sang His praises.}
{921}{}{Praise Troposphere! What happened next?}
{922}{}{Right. Sounds like a regular thunderstorm. And how much did you say you drank?}
{923}{}{That's terrifying. I don't want to hear any more. Tell me about something else.}

# LifeStory6b
{950}{}{No! It was the great Troposphere Himself who appeared to me in all His glory! Descending from the sky, unfolding His majestic wings, surrounded by radiant light. A chorus of raindrops resounded as if lightning bolts sang His praises.}

# LifeStory6c
{980}{}{I shall tell you! It was the great Troposphere Himself who appeared to me in all His glory! Descending from the sky, unfolding His majestic wings, surrounded by radiant light. A chorus of raindrops resounded as if lightning bolts sang His praises.}

# Alcohol
{1010}{}{I assure you, this was not a drunken hallucination. The Lord was as real to me as you are now.}
{1011}{}{Sorry, Sandy. Please continue with what happened next.}
{1012}{}{Alright, Sandy. I'm tired of this story. Tell me about something else.}

# LifeStory7
{1040}{}{Troposphere landed before me and spoke with a solemn voice. "Follow Me," He said. The door to my hospital room suddenly raised, and Lord Troposphere disappeared. After my initial fear subsided, I obeyed His commandment and joined the Rainmakers. I was given the name Sandy Fats, which means "open door," in honor of my divine vision.}
{1041}{}{That's an incredible story. A lost soul saved by Troposphere's grace. How can I join? I have sins that need cleansing.}
{1042}{}{Interesting. I have some other questions now.}
{1043}{}{What a load of crap. You're all clearly deranged. Goodbye.}

# Job
{1070}{}{I am an acolyte here at Tibbets - this is my fifth month. I work as a counselor, providing support to those who have departed the First Life. I also assist the robots in burying the deceased prisoners.}
{1071}{}{Why do you believe that life is only the "First Life"?}
{1072}{}{That sounds like a pretty crummy job.}

# Crummy
{1100}{}{Not at all! It allows me to be close to the prisoners and show them the respect they deserve as they pass into Troposphere's embrace. I find fulfillment in serving the Rainmakers while doing what I love. If only everyone could be as blessed.}
{1101}{}{If you say so. Let's talk about something else now.}
{1102}{}{Sounds great. Goodbye.}

# TempleQuestions
{1130}{}{I am here to spread the glad tidings of Troposphere, may His coat remain sleek and shiny. Feel free to ask your questions, and I will do my best to answer them.}
{1131}{}{Who is Troposphere?}
{1132}{}{What are the main beliefs of the religion?}
{1133}{}{How do you worship Troposphere?}
{1134}{}{Actually, I have another question.}

# Troposphere
{1160}{}{Troposphere is the great Sky Lord, praised be His name. He holds dominion over all water in the world and offers humanity a chance to be reborn into better lives, following His commandments, just like Supercell.}
{1161}{}{What makes Supercell so special?}
{1162}{}{I have another question about the religion.}
{1163}{}{Let's talk about something else.}

# CultGreat
{1190}{}{Supercell was on the brink of death, and Troposphere saved him, granting him another chance at life. Supercell was recreated in the image of Troposphere and freed from the trials and worries that burden us humans. He embodies the ideals of our earthly kingdom, and we aspire to live as he does.}
{1191}{}{Okay. I have another question about the religion.}
{1192}{}{Supercell is locked up in the asylum for a reason. He's considered one of the craziest individuals in the wasteland. You're all deluded. Goodbye.}

# Beliefs1
{1220}{}{Our main belief is that there are four stages of existence. The first is the current life, the one you and I are living now. It is a time filled with challenges, but we can transcend it by following Troposphere's commandments.}
{1221}{}{[CONTINUE]}

# Beliefs2
{1250}{}{Upon death, Troposphere will reincarnate us into new lives. These lives will be far more fulfilling as we take on the image of the Great One. Once this life comes to an end, we enter the Third Life, known as the Shapeless Cloud.}

# Beliefs3
{1280}{}{During the Shapeless Cloud, we will exist in harmony, seated at the right hand of our Lord. It is a time of anticipation, as we await the fulfillment of the prophecy of Paradise. Once the fourth and final life begins, the Embodied Cloud, Troposphere will walk the earth in a corporeal form, and all of humanity will be reborn as radiant divine beings. The world will be eternaly immersed in Troposphere's love.}

# Beliefs4
{1310}{}{However, there is one condition that must be met before Troposphere's glorious return. We must perfect our respect for nature so that one born in it can truly communicate with our Lord and declare that His time has come. We strive to achieve this ultimate connection, even if it takes generations to accomplish.}
{1311}{}{Thank you. I have another question about the religion.}
{1312}{}{I want to discuss something else.}
{1313}{}{This is all nonsense. I don't have time to talk to you fanatics anymore.}

# Worship
{1340}{}{We worship by venerating and respecting all clouds and rainfall, as instructed in the Holy Weather Channel TV Guide. We also partake in joyful dances and organize festivals in the open, which allow us to hear and understand Troposphere's commandments more clearly.}
{1341}{}{Festivals? Holy Weather Channel TV Guide? Where can I obtain those?}
{1342}{}{I have another question about the religion.}

# Tibbets
{1370}{}{I believe that robots and prisoners will eventually come to see the light and recognize Troposphere as their Savior. The rare occurrence of rainfall serves as an emissary sent by the Lord to hasten this joyous day.}
{1371}{}{Right. I had another question in mind...}
{1372}{}{This is absurd. Goodbye.}

# JoinUp
{1400}{}{You must go to see Supercell, the founder, inside the asylum. He will guide you on what needs to be done to join our ranks. I eagerly await the day I can call you my brother.}
{1401}{}{You must go to see Supercell, the founder, inside the asylum. He will guide you on what needs to be done to join our ranks. I eagerly await the day I can call you my sister.}
{1402}{}{Thank you. Goodbye.}

# Supercell
{1430}{}{Supercell, the founder, is the one who organizes our festivals and possesses the Holy Weather Channel TV Guide. However, one must become an acolyte of the Rainmakers to be deemed worthy of reading it.}
{1431}{}{Thank you. I have another question about the religion.}

# Blessed
{1460}{}{And you are truly blessed because of it! However, we must ensure that our religion remains inclusive. The love of Troposphere should be accessible to all who seek it.}
{1461}{}{Yes, I had some more questions for you...}
{1462}{}{You're a rather intimidating person, Sandy. Goodbye.}

# Stupid
{1490}{}{Well, greetings to you too!}
{1491}{}{You help me? Me lost.}
{1492}{}{Nope. Me fine.}
# StupidTroposphere
{1520}{}{I am not the one who can help you, my friend. It is a humongous benefactor in the sky named Troposphere. If He becomes your friend, when you die, you can become a cloud! Would you like that?}
{1521}{}{Cloud nice. Yeah, me cloud! Hehe!}
{1522}{}{No! Cloud stupid, boring, far away! Me hate clouds.}
{1523}{}{You stupid. Go now.}

# StupidCult
{1550}{}{Hahaha! You've got the right idea, my friend, but you must first die. Then, you can become a cloud.}
{1551}{}{You kill me? Then me die, be cloud.}
{1552}{}{Woooo, wooo! Wooo woo! Wo.}

# StupidKill
{1580}{}{Oh, no! Troposphere will come for you in due time. But when it happens, it will indeed be a joyous occasion.}
{1581}{}{Okay. Bye-bye.}

# StupidHate
{1610}{}{Come on now, clouds aren't that bad! Clouds provide us with water and wash away the dirt, don't they?}
{1611}{}{You right. Me forget, me like clouds really.}
{1612}{}{They bad. One shot big sparks at me. That very bad.}

# StupidFriend
{1640}{}{Well, just remember, Troposphere is now your friend. Keep that in mind.}

# StupidInsult
{1670}{}{Hahaha! My friend, that was just a cleansing storm. Troposphere and His clouds love you and want to be your friends.}
{1671}{}{No! Cloud was mean. Me not talk now. Stupid clouds.}
{1672}{}{Okay. Troposphere good. Clouds good too.}
