# Message file for tbseb.ssl
# Number of nodes: 26
# Grammar pass done

{100}{}{You see a young officer with a troubled expression.}
{101}{}{You see Officer Seb.}
{102}{}{You see a mid-twenties officer who seems worried about something, unable to hide her emotions well.}

{150}{}{Ah, a fresh face, eh? Don't sweat it, you'll fit right in. Just remember, avoid touching any shiny objects, alright?}
{151}{}{[Drool and walk away.]}

# FirstStart
{200}{}{Hey there, bud! Ya are new around these parts, ain't ya?}
{201}{}{Yes, I just arrived.}
{202}{}{No, I was born in Tibbets.}

# AFirstWelcome
{230}{}{Welcome, friend! I'm Chief Security Officer Seb. I report to Sheriff Carmichael on a monthly basis. What brings ya to our neck of the woods? Are ya a new patient or a keener?}
{231}{}{ , that's me. I'm a prisoner. I stumbled upon this place by chance and it's full of surprises!}
{232}{}{Well, I'm neither a patient nor keener. I'm just exploring Tibbets.}
{233}{}{Sheriff Carmichael's officer? That sounds brave! What do you do here? Ensure the safety of the bread?}

# BTrickOne
{260}{}{Oops, sorry about that, pal! I haven't seen ya around. Ya got me there, eh?}
{261}{}{Well, you asked a stupid question and got a stupid answer. I'm a new prisoner exploring Tibbets and getting to know my new home.}
{262}{}{No, seriously, I was born here! I work as a lab tech in the Labs.}

# CWKIDFY
{290}{}{Ah, right! I heard about a fella doing that. Now that the introductions are out of the way, how can I assist ya, eh? [Seb grins at her pun.]}
{291}{}{Ah, right! I heard about a gal doing that. Now that the introductions are out of the way, how can I assist ya, eh? [Seb grins at her pun.]}
{292}{}{Can you give me an overview of what's happening here?}
{293}{}{Is there anywhere I can find weapons in this place?}
{294}{}{Well, nothing really, thanks Seb. I better get going.}

# DSlang
{320}{}{Oh, sorry, bud! I forget that not everyone is familiar with northern lingo. A keener is a new prisoner who's usually a bit too keen about being here. Anyway, how can I help ya out?}
{321}{}{Can you teach me some more northern slang?}

# EHostile
{350}{}{[Seb's eyes narrow.] The Sheriff's crew sees more action than robots. We're here to stop folks like ya from hurting others and themselves, eh?}
{351}{}{Woah, take a chill pill! I was just kidding around.}
{352}{}{Seems like you didn't do a good job this time, did you?}
{353}{}{Really? Officers get attacked frequently?}

# FWKIDFY
{380}{}{Alright then. Give a shout if ya need anything, eh?}

# GTech
{410}{}{That's a bit odd. Normally, I'm good with faces. Anyway, I'm Chief Security Officer Seb, appointed by Sheriff Carmichael. And ya are..?}
{411}{}{Just messing with you! I'm actually a new prisoner exploring Tibbets.}
{412}{}{. If you ever visit the Labs, look me up, and we can grab a drink at the Atom or something.}
{413}{}{Clearly, smarter than you. [Under breath.] Moron.}

# HHostile
{440}{}{Whatever, bud. I know lab techs. Who the heck are ya really?}
{441}{}{I'm }
{442}{}{, a new prisoner. Sorry, I love tricking people.}

# IInfo
{470}{}{Things have been real busy of late. We recently had a group of cultists called the Rainmakers brought in by the bots. Though they're harmless, our hospital is packed to the rafters, so we can't take in anyone else. Tibbets is crammed with folks in need of our help.}
{471}{}{Do prisoners often lose their minds here?}
{472}{}{Sounds like a fun time for you. What about non-security matters?}

# JGauss
{500}{}{Well, this is a prison filled with criminals, and we don't just hand out firearms like candy, eh? If ya are genuinely interested in getting one, I suggest heading over to the Sheriff's cell block, number 30. They might consider offering ya a job as a security officer.}
{501}{}{Alright then, another question...}
{502}{}{Well, that sucks cock. I'm out of here.}

# KSlang
{530}{}{Well, that's about all I know, eh? I picked it up from my late grandpa, a true Canadian. [Smiles to herself.] If ya want to experience the best of northern lingo, go watch some old Dominion of Canada movies in the prison.}
{531}{}{Okay! I'll see if there are any available.}

# LGTFO
{560}{}{Get out of here, eh.}
{561}{}{[END]}

# MAttacks
{590}{}{Oh sure, it happens all the time, eh? Most folks aren't used to being cooped up with a bunch of wrong 'uns, no hope of seeing the sky again. It's kind of ironic how ya gotta lose your marbles first to get here and only then can ya catch a glimpse of the sky. Lately, things have been getting a bit rough, maybe 'cause of a flu bug the docs have been wrestling with. We've been squawking about it to the Warden, but we need some concrete proof before we can do anything, ya know?}

# NDrink
{620}{}{Alright then! Catch ya later.}

# OInfo
{650}{}{Well, not much really. Guys will be guys, and gals will be gals. *Sigh*}
{651}{}{Uh-oh. That sigh tells me you're having some boy trouble.}

# PInfo
{680}{}{Sure, go ahead and ask, eh?}

# QWomen
{710}{}{Heh, yeah. *Sigh* Why are bad boys so dang irresistible?}
{711}{}{Open up to me, Seb! I know men; I'm one of them!}
{712}{}{So, what's going on, Seb? I'm all ears.}
{713}{}{Oof, that sounds tough. But I have another question...}

# RWomen
{740}{}{Well, what would ya do if there was this gal ya really fancied, but ya were scared that asking her out would send her running?}
{741}{}{Well, what would ya do if there was this fella ya really fancied, but ya were scared that asking him out would send him running?}
{742}{}{Ask her out. If she's worth having, she'll say yes.}
{743}{}{Ask him out. If he's worth having, he'll say yes.}
{744}{}{Hmm, it seems like you encounter that problem often.}
{745}{}{Get my best friend to ask them out for me!}

# SWomen
{770}{}{But what if he doesn't? I reckon I'd be crushed if... uh, he turned me down.}
{771}{}{Well, you could get someone else to ask him out for you.}

# THostile
{800}{}{What?!}
{801}{}{Nothing.}
{802}{}{Your appearance might be a turn-off for men. Have you considered dating women?}

# UWomen
{830}{}{Yeah, I don't really want my mates to know that I'm scared to ask him out, ya know?}
{831}{}{Well, I can help. Your secret's safe with me!}

# VEmma
{860}{}{Would ya?}
{861}{}{Sure. It'd be my pleasure to help out.}
{862}{}{I'm a bit busy at the moment, but I'll get back to you.}
{863}{}{Maybe later. Hey, there's something else I'd like to know...}

# WEmma
{890}{}{Awesome! Thanks a ton! His name is Martin, and he's a prisoner. He usually hangs out in the Medical Treatment Area lounge. Just mention Seb Tremblay, and he'll know who I am. Thanks again, eh?}
{891}{}{Hey, I'm here to help.}

# SeenStart
{920}{}{Hi again! How can I assist ya, bud?}

# QuestStart
{950}{}{Hi again! How can I assist ya? Wait, did ya ask him out yet, eh?}
{951}{}{Not yet. I need to ask you something first...}
