# Message file for tbsimtek.ssl
# Number of nodes: 17
# Grammar pass done

# Node001
{200}{}{SIMTEK OPERATIONS SIMTEK 5000 BOOTING UP: 20% COMPLETE.}
{201}{}{[Wait patiently.]}
{202}{}{[Bypass the boot sequence by redirecting to the latest memory snapshot.]}
{203}{}{[Bypass the boot sequence by swapping the alpha holodisk for the beta holodisk containing the latest memory snapshot.]}
{204}{}{[Try tampering with some of its wires and components.]}
{205}{}{[Walk away.]}

# Node002
{230}{}{SIMTEK OPERATIONS SIMTEK 5000 BOOTING UP: 50% COMPLETE.}
{231}{}{[Give up and leave.]}

# Node003
{260}{}{SIMTEK OPERATIONS SIMTEK 5000 BOOTING UP: 30% COMPLETE.}
{261}{}{[Kick it in frustration.]}

# Node004
{290}{}{SIMTEK OPERATIONS SIMTEK 5000 BOOTING UP: 60% COMPLETE.}
{291}{}{[Continue waiting patiently...]}

# Node005 006
{320}{}{SIMTEK OPERATIONS SIMTEK 5000 BOOTING UP: 99% COMPLETE.}
{321}{}{[Wait a bit longer...]}

{350}{}{[Wait even more patiently...]}
{351}{}{[Kick the stubborn machine!]}

# Node007
{380}{}{SIMTEK OPERATIONS SIMTEK 5000 BOOTING UP: 100% COMPLETE. WELCOME TO SIMTEK 5000: BLACK & WHITE EDITION, YOUR GATEWAY TO A DIFFERENT REALITY.}
{381}{}{[Press a button.]}
{382}{}{At last! For fuck's sake...}
{383}{}{Fuk yeah!}

# Node008
{410}{}{The Warden asserts that, hypothetically speaking, many Prisoners will struggle with adapting to a lifetime of freedom in the outside world after being confined underground since birth. The SimTek 5000 offers a challenging simulation hologram of life in the wasteland based on the pre-recorded memories of a Vault Dweller, Max Stone, who entered Scrapheap on December 5th, 2161. Brace yourself for a detailed, hyper-realistic SimTek 5000 experience. Ending the simulation is as easy as walking back. Sit back and immerse yourself, Prisoner!}
{411}{}{Here we go...}
{412}{}{[Attempt to input the access codes provided by Vault Boy.]}
{413}{}{Gero! Nimo! OoOOooo!}
{414}{}{Perhaps, another day might be better.}
{415}{}{Me no go other world.}
{416}{}{[Attempt to download the complete Vault Boy data onto your Pip-Boy.]}
{417}{}{[Try to extract the entire Vault Boy THT tape and replicate it onto your Pip-Boy.]}

# Node009
{440}{}{ACCESSING BETA HOLODISK... ACCESS CODES CONFIRMED. WELCOME TO VAULT-TEC DOCUMENTATION DEPARTMENT ARCHIVE #1983. DISCLAIMER: This documentation contains information affecting the national defense of the United States under the amended Espionage Act, 50 U.S.C., 31 and 32. Unauthorized transmission or revelation of its contents is prohibited by law.}
{441}{}{[Vault Locations v34.129 Revision C (Western USA)]}
{442}{}{[Overseer Chip]}
{443}{}{[EXIT]}
{444}{}{[Survival Recipes]}
{445}{}{[Important Vault Statistics]}
{446}{}{[Nuclear Blast Effects]}
{447}{}{[Additional Publications]}

# Node010
{470}{}{On the display, a hollowed-out, black chip rotates. The description only states that it's a collaborative project between RobCo and Vault-Tec, intended solely for Overseers, as an upgrade for the Lil-Pip 3000.}

# Node011
{500}{}{You search extensively but fail to find anything resembling the chip's schematics.}

# Node012
{530}{}{It appears you've discovered promotional materials for a few Vaults to the west.}
{531}{}{[Download to your Lil-Pip 3000.]}
{532}{}{[Read now.]}

# Node013
{560}{}{DOWNLOADING DATA FROM DISK... COMPLETED.}

# Node014
{590}{}{Welcome to the latest edition of the Western United States Vault Location Pamphlet. We trust you'll find the pamphlet informative, and remember, Vaults aren't just for the privileged, but for everyone.}
{591}{}{[Vault 12]}
{592}{}{[Vault 13]}
{593}{}{[Vault 15]}

# Node015
{620}{}{Under the sprawling metropolis of Bakersfield, lies the technological magnificence of Vault 12. Built with every amenity in mind for the prospective Vault Dweller, Vault 12 was given the *Pressed Vault Suit* award for attention to preparedness. Buried far underground, the protection that Vault Dwellers will receive will be unprecedented. Much like all other Vaults, Vault 12 has been fitted with the newest in Vault Water Purification Systems. Able to take even the waste located in the sewers of Bakersfield, this system is able to deliver over 15,000 gallons of pure, refreshing drinking water every day.}

# Node016
{650}{}{Located in a scenic mountainous region northwest of Vault 12, this Vault offers an endless supply of pure water to the inhabitants. The rumors that the water table in the area could easily be contaminated in the event of a Nuclear War have been found by the Department of Water and Power to be completely unfounded. In the event that the water in the area were to become tainted, remote even though it may be, Vault 13 has been fitted with the government approved Vault Water Purification System. Rated to work without significant loss of output for over 250,000 hours, prospective Vault Dwellers should have nothing to fear.}

# Node017
{680}{}{Due east from Vault 13, construction on this Vault has gone extremely smoothly. Much work was done to reinforce the walls of the third level of this Vault, to make all the future Vault Dwellers more secure in the knowledge that in the event of even a major earthquake, the regulatory computers of the Vault would continue to function. Recent tours of the newly constructed Vault, have had many a potential Vault Dweller walking away with a new found awe of the improvements done to this already impressive Vault.}

# Node008
{710}{}{BAD SECTOR NUMBER 989,097,265,735,589 DETECTED ON ALPHA HOLODISK! PROCESS ABORTED!}
{711}{}{Worthless junk...}

{740}{}{This file is labeled *Survival Recipes.* Appears to be an appendix from the Vault Dwellers Survival Guide.}

{770}{}{This file is labeled *Important Vault Statistics.* It appears to detail certain Vault specifications.}

{800}{}{This file is labeled *Nuclear Blast Effects.* It provides an extensive amount of information on the impact of a nuclear weapon attack.}

{830}{}{This file is labeled *Additional Publications.* More releases from the Vault-Tec Documentation Department.}

{860}{}{FILE FOUND ON SYSTEM. DOWNLOAD ABORTED.}

{890}{}{[You manage to open the panel but struggle to remove the security lock securing the THT tape. Failure could result in permanent damage.]}

{920}{}{[You successfully open the panel and remove the security lock securing the THT tape]}
