# Message file for tbsmug.ssl
# Number of nodes: 4

{100}{}{You see a disheveled man with grimy hands.}
{101}{}{You spot a smuggler who operates in a factory.}
{102}{}{His hands are coated in thick, black grease.}

{103}{}{A powerful bomb went off somewhere down the corridor.}

{105}{}{*wink*}
{106}{}{Heh, she doesn't seem too worn out. Alright, it's a deal.}
{107}{}{Thanks, babe. I needed that. *wink*}
{108}{}{A thief stealing from a thief - what is this world coming to?! If I ever find out who did it, I'll... I'll... *clenches fist*}
{109}{}{*hrrngh* I think something's broken... *hrnngghhh*}
{110}{}{Phew! I'll never get rid of this stench.}

# Node001
{200}{}{Pssst! Champ, come here. I have something for you.}
{201}{}{Pssst! Darling, come here. I have something for you.}
{202}{}{Yes, what is it?}
{203}{}{Stop wasting my time. And keep those filthy hands away from me.}
{204}{}{Wut?}
{205}{}{Me no want.}
{206}{}{Do you have the solution for escaping this metallic tomb?}

# Node002
{230}{}{I work two levels below in the factory. Look what I found there - a *robotic self-destruct mechanism*. I'll gladly trade it with you.}
{231}{}{What's the cost?}
{232}{}{So, you *found* it there, huh? Is that a nice way of saying you stole it?}
{233}{}{I'm genuinely not interested.}
{234}{}{Caps?}
{235}{}{Thief!}
{236}{}{No!}

# Node003
{260}{}{1,000 caps. Or you can find me a beautiful lady - hehe.}
{261}{}{1,000 caps. Or you can keep me company in a cell room - hehe.}
{262}{}{Well, that doesn't sound too bad. However, you'll need to clean those hands first.}
{263}{}{I have a better idea. How about this *almost unused*, *almost brand new* sex doll?}
{264}{}{I'll figure something out.}
{265}{}{Oki. Me go naked.}
{266}{}{Sexy plastic woman!}
{267}{}{Alright, here's your 1,000 caps.}
{268}{}{Here one-zero-zero-zero caps.}

# Node004
{290}{}{Call it what you want. There are thousands of those down there; no one will notice one missing. I suppose.}
{291}{}{Alright, how much?}
{292}{}{I don't want to provoke the robots. Farewell, sucker.}
{293}{}{Robo hurt. No-no. Byeeeeee.}

# Node005
{320}{}{You tell me! Probably in a coffin.}
{321}{}{Hah! So, what do you have for me?}
{322}{}{Hmmm... I just need to fake my own death. Farewell and thanks for the idea!}
