# Message file for tbsonia.ssl
# Number of nodes: 42
# Grammar pass done

{100}{}{You see a woman stirring her water flask.}
{101}{}{You see Undersheriff Sonia Needles.}
{102}{}{You see a woman in the process of stirring a foul-smelling, viscous substance in her water flask.}

# random floats for Sonia
{200}{}{~Mmm hmmm mmm... arrested!~}
{201}{}{~Mhmmmm mmm hmmm...~}
{202}{}{~Hmmm mmmm hmmm hmm...~}
{203}{}{~Mmm mm... arrested! Hmm hmmmm mmm...~}
{204}{}{~Arrested!~}

# First
{260}{}{[The woman chants under her breath. Every so often, she sings the word "arrested!" then returns to her murmuring] }
{261}{}{Excuse me.}
{262}{}{Hey, I have some questions for you.}
{263}{}{ARRESTED!}
{264}{}{[Leave her alone]}

# Again
{290}{}{[Sonia is still chanting to herself - it seems to be the same prayer as last time]}
{291}{}{Sonia, I have more questions I want to ask.}
{292}{}{[Leave her alone]}

# Member
{320}{}{[She nods at you] Greetings to you, brother inmate. Have you come to observe the Holy Word of Law being born out of Heaven's womb?}
{321}{}{[He nods at you] Greetings to you, sister inmate. Have you come to observe the Holy Word of Law being weaved from heavenly heights?}
{322}{}{No, but I'd like to ask you some questions.}
{323}{}{May I have some of that "holy" water, Sonia?}
{324}{}{May I have some "holy" water, Sonia?}
{325}{}{Not right now. Goodbye.}

# NoResponse
{350}{}{[Sonia continues to chant. She seems not to notice you] }
{351}{}{Hey, I want to talk to you.}
{352}{}{Sonia, I'm sorry for what I said. I need to ask some questions.}
{353}{}{[Wait]}
{354}{}{[Shake her shoulder]}

# NoResponse2
{380}{}{[Sonia continues to chant. She seems not to notice you]}
{381}{}{Hey, I'm talking to you.}

# Kicked
{410}{}{An outcast. Returning to the source of lost enlightenment, hoping for forgiveness, finding none. What brings the heretic into my presence?}
{411}{}{I want to ask you some questions, Sonia.}
{412}{}{Outcast? Heretic? I'm glad to be out of your ridiculous cult. Shove your holier-than-thou sermon up your ass.}
{413}{}{Nothing. Goodbye.}

# Heretic
{440}{}{Questions must be asked of oneself constantly. Only through constant vigilance over our souls can we avoid committing sins against the Holy Law. You failed to question yourself before your desecration of our principles - thus, you have forfeited your right to ask questions of me.}
{441}{}{Fine.}
{442}{}{As if your babblings would make sense anyway.}

# Greetings
{470}{}{A visitor. Greetings, and may the blessing of the Holy Law be upon you. I am Sonia Needles, the Undersheriff and the one in charge of cell block 29.}
{471}{}{I wanted to ask you some questions.}
{472}{}{Good to meet you, Sonia. See you around.}

# RuderGreeting
{500}{}{An interruption. I am Sonia Needles, the Undersheriff - what is your purpose here?}
{501}{}{I said, I want to ask you some questions. Are you deaf?}
{502}{}{I'm sorry for the interruption. Can I ask you some questions?}
{503}{}{Forget it.}

# Deaf
{530}{}{A deaf, blind, dumb woman. Enraged, lashing out at her fellows, spurning their offers of help. Her home is in ruins, her possessions sundered, her friends fled in terror from her anger. What has she left? Only regrets, for aid refused may never be offered again.}
{531}{}{I see where you're going with this. I'm sorry - please can I ask some questions?}
{532}{}{So you're deaf and mad. I haven't got time for riddles - goodbye.}

# Questions
{560}{}{Questions. Are the answers in my soul, or yours, or lost in "holy" water? We shall find out.}
{561}{}{What do you do here?}
{562}{}{Tell me about yourself, Sonia.}
{563}{}{I want to talk about "holy" water.}
{564}{}{Never mind for now. Goodbye.}

# DreamJuice
{590}{}{"Holy" water... In this instance, it is I, not it, holding the answers you seek - for the Holy Law cannot define itself.}
{591}{}{What does it do?}
{592}{}{How is it made?}
{593}{}{How is it distributed in the prison?}
{594}{}{Can I have some?}
{595}{}{Are you giving anyone here more "holy" water than supposed to? I see lots of junkies here.}
{596}{}{I have other questions.}

# WhatDo
{620}{}{I create "holy" water, and Maurice makes sure all who need it, get it. I harvest, heat, mix, and brew from dawn until dusk. Heaven's Gate is found, and opened. Later, others shall open it too.}
{621}{}{Tell me more about "holy" water.}
{622}{}{Let's talk about something else.}

# LifeStory
{650}{}{Your demand betrays folly, for no woman truly knows herself. How, then, can she explain herself to another? I could tell you of my life's work, of my joys and my tragedies - but these tales would be mere reflections of my true self, ghostly and pale.}
{651}{}{Let me be more specific. Tell me about the main events in your life.}
{652}{}{I wasn't really all that interested, to be honest. Let's talk about something else.}

# LifeStory2
{680}{}{I am thirty-one years old. I joined the Sheriff at the age of ten. Three years ago, my predecessor Mihita ascended into Heaven, entrusting me with the responsibility of being the Undersheriff and creating "holy" water. Do you see? This information yields nothing useful, and no insights have been gained. Truly, a waste of time.}
{681}{}{I feel like I know you already. I have more questions.}
{682}{}{You got that right. See you around.}

# DreamJuiceDo
{710}{}{It is just that - a bit of water mixed with lots of holiness. In our daily lives, we cannot hear the Holy Word of Law save for the words of others. "Holy" water lifts the veil between this wounded world and sacred realms. Heaven speaks to us through our laws, and in knowing and adhering to those, we know ourselves more deeply. }
{711}{}{Interesting. Tell me more about "holy" water.}

# HowMade
{740}{}{It is not made, but born, and it would take a lifetime to truly learn the art of birthing it. I can tell you that "holy" water is always composed of Psycho, harvested from the sacred grounds of our Asylum. The Psycho must then be bonded with other sacred ingredients, so the product of the two may become a suitable vessel for Heaven's Gate.}
{741}{}{So the main ingredient is Psycho?}
{742}{}{Sounds like a simple recipe to me. Why all the ceremony?}
{743}{}{I want to ask you something else about "holy" water.}
{744}{}{I've got a question about something different.}

# WantDJ
{770}{}{A man traveling on an unfamiliar road must be guided. Only those prepared for spiritual revelation may take "holy" water - I suggest that you consult Father Maurice if you wish to take the next step in your journey towards the truth.}
{771}{}{A woman traveling on an unfamiliar road must be guided. Only those prepared for spiritual revelation may take the "holy" water - I suggest that you consult Father Maurice if you wish to take the next step in your journey towards the truth.}
{772}{}{There's something else I want to know about "holy" water.}
{773}{}{I want to ask about something else.}

# HowDistributed
{800}{}{A group of newborn laws is bestowed upon each Sheriff. Each one dispenses their laws as they see fit to the inmates in their care. We must remember that Heavens do not speak frivolously - therefore, new converts must only drink it when they stand on the cusp of further spiritual progression. Our sacred laws guide our lives, and we should not take them lightly.}
{801}{}{I want to know more about "holy" water.}
{802}{}{I have some other questions for you.}

# MoreThan
{830}{}{All people are equal, and all people are connected. Why should one person receive more blessings than their brother or sister? I create the "holy" water, and I see to it that each priest receives an equal share - we are as equal in the spiritual world as we are in the flesh.}
{831}{}{Well, what if someone's giving out more "holy" water than they should? There's a lot of junkies here.}
{832}{}{There's something else about "holy" water I wanted to know.}
{833}{}{I have more questions.}

# Extras
{860}{}{Nothing in this world is identical. Two grains of sand will vary by the tiniest amount. It is the same for laws - each is differentiated by the addition of these ingredients. I strive to make it more potent, and the voice of Heavens heard more clearly, by refining the recipe.}
{861}{}{What ingredients do you use?}
{862}{}{I want to know something else about "holy" water.}

# Respect
{890}{}{Our thoughts, our hopes, our fears, they are all expressed and made known to us when we follow the Holy Word of Law. We should treat each other with great respect - doubly so when Heavens speaks to us through each other.}
{891}{}{Right. I want to know more about "holy" water.}
{892}{}{Let's change the subject - I have some other questions.}

# Theft
{920}{}{It is a grave crime indeed to distribute it unequally. The heretic sees what is rightfully meant for another - a worshipper is deprived, the culprit is deceived. But the felon's transgression will be punished in its own time, without the interference of others. False believers will inevitably bring on their own tragedy.}
{921}{}{Sonia, if you know who's responsible for these addicts, you owe it to the "deprived worshippers" to tell me.}
{922}{}{Well, make sure you don't let any more disappear. Let me ask about something else.}

# Jotham
{950}{}{You are right. Perhaps I must accept help in this matter. Father Maurice has an odd aura about him - as if he visited Heavens too much in recent months and now cannot come back. If a priest is the culprit, it is likely to be him.}
{951}{}{Thanks, Sonia. If it is Maurice doing this, I'll put a stop to it.}
{952}{}{Interesting. I have other questions for you.}

# WontTell
{980}{}{No. What is a man if he does not carry out his duties himself? I shall redouble my vigilance over the supplies, but it would be best that you stay out of this matter. A well-meaning gesture can often have unfortunate consequences.}
{981}{}{I think you're making a mistake. Don't expect me to help next time you're in trouble.}
{982}{}{Fine. I have some other questions.}

# GiveDJ
{1010}{}{A wandering missionary, seeking guidance on his sacred pilgrimage. Take this flask, brother inmate - may they aid you on your journey.}
{1011}{}{A wandering missionary, seeking guidance on her sacred pilgrimage. Take this flask, sister inmate - may they aid you on your journey.}
{1012}{}{Thank you, Sonia. Goodbye.}

# Ingredients
{1040}{}{As an Undersheriff, I will use any weapon and adhere to any law to build and defend our home. And as a priestess, I too will use anything from our surroundings to flavor "holy" water. Let me give you an example - in this batch alone, there is dust, radscorpion innards, salt water, grain, urine, and mechanical oil.}
{1041}{}{Ugh, that sounds disgusting! It sounds more like "holy" shit!}
{1042}{}{Sounds interesting! Tell me more about "holy" water.}

# Vulgar
{1070}{}{A vulgar, belittling name. All the secretions from children of the paradise are sacred. Who are we to judge, with our primitive and dull senses, what should be pleasing to smell and taste, hmm?}
{1071}{}{Well, everyone has their own preferences. Let's move on to another topic.}
{1072}{}{That's disgusting! But what else can you tell me about "holy" water?}
{1073}{}{Let's change the subject. I have more questions.}

# Stu_Sanctified
{1100}{}{A simple, naive fool. Yet the feeble of mind may be among the most blessed by Heavens - their blasphemy unintentional, and their minds untainted by the twin poisons of science and logic.}
{1101}{}{Talky girl! Sing arrest song!}
{1102}{}{You make drink? Me want!}
{1103}{}{Bor-ring! Bye bye.}

# Stu_Drink
{1130}{}{An honest desire to drink of and experience the visions of Heaven. But desire alone cannot grant a man his dearest wishes - he must be worthy to claim them. I cannot accede - these flasks are not for you.}
{1131}{}{An honest desire to drink of and experience the visions of Heaven. But desire alone cannot grant a woman her dearest wishes - she must be worthy to claim them. I cannot accede - these flasks are not for you.}
{1132}{}{You no get it. Me thirsty, not dead. Me no go Heavens.}
{1133}{}{'K. Sing arrested song.}
{1134}{}{No fair. You sel-fish. Me go.}

# Stu_Sing
{1160}{}{'Arrested' is a word so effortlessly spoken. It is merely an exhalation, a motion of the tongue and jaw. Nevertheless, it should not be used lightly or for trivial amusement.}
{1161}{}{Sing!}
{1162}{}{'K, no sing. Me drink.}
{1163}{}{Words too long. Bye, talky girl.}

# Stu_Sing2
{1190}{}{Not a song but a hymn, not an act of pleasure but one of devotion. It seems you are incapable of heeding my words. I must return to my duties.}
{1191}{}{ARRESTED! ARRESTED! AAaaaAAAaaaAReESTEEEeEEEEEEeeeeEEEEeeeEEEeD!!}
{1192}{}{Bye bye, duty woman!}

# Stu_Sing3
{1220}{}{A puzzling encounter indeed - how the faithful and the ignorant utter the same words, yet with such different intentions. Not an irritation, this simpleton's visit, but another of Heavens' riddles. I shall meditate on this further.}
{1221}{}{You - so - boring! Me go.}
{1222}{}{Arrested, bye bye, arrested bye!}

# Stu_Thirsty
{1250}{}{This liquid is peculiar. It satiates the unending thirst for knowledge but neglects the basic physical needs of humankind. It is water that you require, simple one – the visions of Heaven only bring sorrow to those incapable of reaching them.}
{1251}{}{Okay. Bye bye.}
{1252}{}{You no give. Talky nasty woman. Me go.}

# Stu_Prophet
{1280}{}{A strange prophet indeed. The intelligent concern themselves with abstracts, and the wise ponder the impossible. Could it be that only the feeble have the directness of faith to commune with Heavens and hear the Holy Word of Law?}
{1281}{}{Me talk to Heavens! You give drink.}
{1282}{}{Me speak with Heavens. They no speak to you - you too stupid.}

# Stu_DreamJuice
{1309}{}{I would be honored to bestow "holy" water upon you, but unfortunately, I don't have any with me right now.}
{1310}{}{A man of faith and of destiny, seeking to commune with the Paradise. It is my honor to bestow this "holy" water to you - may it guide your path unerringly.}
{1311}{}{A woman of faith and of destiny, seeking to commune with the Paradise. It is my honor to bestow this "holy" water to you - may it guide your path unerringly.}
{1312}{}{Thanks, talky woman. Bye-bye.}

# Stu_SoniaStupid
{1340}{}{Each person has their own path. Yours has led directly to an audience with the Heavens. Mine winds and meanders, but our destinations are the same.}
{1341}{}{Me speak to Heavens. Give drink.}
{1342}{}{Bye, talky woman.}

# Stu_Antichrist
{1370}{}{This is a test of faith. Even a prophet among us succumbs to the evils and temptations of this world, forever exiled from the grace of Heaven. You have demonstrated that no one is immune to darkness. I express gratitude even as I harbor contempt for you.}
{1371}{}{You no likey?}
{1372}{}{Me no care, talky woman. Me go.}

# Stu_Like
{1400}{}{Words such as 'like', 'dislike', 'love', and 'hate' are merely used to describe superficial social interactions. The only thing of true importance, fallen one, is whether the Holy Word of Law resides in a person's heart. Regrettably, it has fled from yours, never to return.}
{1401}{}{Me no get drink?}
{1402}{}{Me not want Heavens. Me want Hells. Bye bye.}

# Stu_NoDrink
{1430}{}{There is a time for that, forsaken prophet, and yours has long passed.}
{1431}{}{Fine. Me go.}
{1432}{}{You stupid. Me go.}
