# Message file for tbstu.ssl
# Number of nodes: 26

{100}{}{You see someone occupying a shower.}
{101}{}{You see Stu.}
{102}{}{She seems confused.}

{150}{}{You got rid of Stu for good.}

# Node 0 [SpaceAndTime]
{200}{}{In an endless world of light a void of darkness exists...}
{201}{}{Twinkle, twinkle, little star... Hey, where's my pookie?}
{202}{}{When I was young I had a pet iguana. He went missing. I remember we had meat for dinner that night.}
{203}{}{My spirit guide is an undertaker. And a mantis. A big mantis!}
{204}{}{My sky is purple. What color is yours?}

# Intro01
{230}{}{Hey brother, my last caravan trip was to the Moon. I've been here for 10 hours now, the water is still hot. It's a miracle!}
{231}{}{Hey sister, my last caravan trip was to the Moon. I've been here for 10 hours now, the water is still hot. It's a miracle!}
{232}{}{You did caravan rounds?}
{233}{}{Uhm okay. Look you're gonna have to leave the shower. You can't use this a personal cell.}
{234}{}{You have to go and I'm gonna make it happen. Others want to use the shower too.}
{235}{}{Uhm you leave. The shower cell not sleep cell.}
{236}{}{You go and me force you to go. Others dirty too.}

# Intro02
{260}{}{Oh, I'm hungry, are you hungry? [You now notice she's been holding some fruit all this time]}
{261}{}{No, hey where did you get that?}
{262}{}{A little.}

# Intro03
{290}{}{Mmmph mmm. Nutrient paste. Gonna have to get more later. *Wink* [Whispering] The best time to get fruit is right after everyone leaves for their dinner. *Wink, wink* Want some?}
{291}{}{Not really. Look I'm here to ask you to leave.}
{292}{}{Yeah. You go.}
{293}{}{Yeah right. Look if you don't leave and never come back I'm going to hit you.}
{294}{}{Yeah, uh no. You go or me hit you.}
{295}{}{Right sister. [You take a step forward] You have to leave and I'm here to see that you do.}
{296}{}{Sure sis. [You take a step forward] You go and me gonna make you.}
{297}{}{You know I could try to persuade you to leave; I might even enjoy beating some sense into you, but I think I'd rather just end your miserable existence.}
{298}{}{Me no think me can talk u into go. Me beat u up and force u to go but it more fun just to kill u.}
{299}{}{Yeah, hi. Uh, look I have to go.}
{300}{}{Hi. Uh, me go.}

# IKnowU
{320}{}{Hey brother. Uhm. I know you right?}
{321}{}{Hey sister. Uhm. I know you right?}
{322}{}{Yeah. You go or me hit you.}
{323}{}{Right sister. [You take a step forward] You have to leave and I'm here to see that you do. }
{324}{}{Yeah, hi. Uh, look I have to go.}

# urJoking
{350}{}{Hahaha! You? You couldn't hit a rock; white eyes! [As you step forward she kicks you squarely in the junk with a metallic shampoo bottle]}
{351}{}{Brahmin. [She swerves and sweeps your foot out from under you causing you to loose you balance and your grip. As you attempt to break your fall she turns her back toward you and firmly plants her elbow in your midriff knocking the wind out of you] You should worry more about your own pretty little face.}
{352}{}{Uhnnnn. *Whimper*}
{353}{}{Uhng, gasp.}

# notConvinced
{380}{}{Where are we going? Hey do you have a caravan guide yet? Wouldn't it be cool if we tripped together? Just you and me and our caravan guides. [Her eyes go vacant for awhile as if lost in some dream] Oh, if you don't, that's okay too. We can just trip with my guide. Do you have any drugs? [Her eyes go vacant again]}
{381}{}{No.}

# NewTricks
{410}{}{My undertaker caravan guide taught me a few new tricks. [She strikes a defensive pose. You protect your junk. She blindingly slams a fist into your Adam's apple]}
{411}{}{My undertaker caravan guide taught me a few new tricks. [She strikes a defensive pose. You protect your belly. She twirls and plants her metallic shampoo bottle on your foot]}
{412}{}{*Gag!* *Choke!* *Stumble!*}
{413}{}{Ow ow ow ow ow! [You hop around a little]}

# Leave
{440}{}{Huh? Did you say leave? Why would I do that? Wait no. Why would you even ask? What do you mean anyway? Leave what, where?}
{441}{}{You've occupied the shower and are disturbing the peace of this cell block. This has gone on for far too long despite being warned by the others. They want you to move away from the shower and never return.}
{442}{}{Yes, leave the shower! As in go away, far far away. [You shove her] Now. [You shove her again]}
{443}{}{Yes, leave the shower and don't return. [You look at your long nails] It would be a shame if I broke a nail.}

# noPeace
{470}{}{What about my peace? They promised me peace. All I got was drugs.}
{471}{}{So you are searching for peace of mind? Then clearly this is not the place for you. You must find your peace elsewhere.}
{472}{}{And that's the problem; too much drugs. How do you pay for it anyway?}

# gonnaCry
{500}{}{*Sniff, sniff* But I don't have anywhere to go. *Sniff* I was doing so well for awhile. I was making something of myself.}
{501}{}{What happened?}

# IntimidationFirst00
{530}{}{Huh? What? [She shrugs and huffs] Where would I leave? This is a prison.}
{531}{}{Stop it! [She takes a step back] Besides, where would I leave?}
{532}{}{If you don't leave you're going to get hurt. [You clench your fist] Bad.}
{533}{}{If you don't go me hurt you. [You clench your fist]}
{534}{}{[You take a step forward] The other prisoners want you gone.}
{535}{}{The prison people want you go. [You take a step forward]}

# IntimidationFirst01
{560}{}{Wow. Stop it. I'll scream!}
{561}{}{What is the matter with you?}
{562}{}{You just don't get it do you? [You take a step forward]}
{563}{}{Such a pretty neck. [You step forward extending your arms towards her neck]}
{564}{}{Pretty nek. [You step forward extending your arms towards her neck]}

# IntimidationFirst02
{590}{}{Agh. *Whimper.* Please go away.}
{591}{}{Uhn.}
{592}{}{I'm going to hurt you unless you leave.}
{593}{}{You can leave of your own accord or I can force you to leave. I'd much rather force you.}
{594}{}{You go or me use force.}

# IntimidationFirst03
{620}{}{Uhmpf. *sob* Please stop with the threats, I'll leave.}
{621}{}{What do you mean threats?}
{622}{}{And don't come back. [You tighten your fist]}
{623}{}{[You grab the nearby shower hose hinting of what is to be if she doesn't comply]}

# IntimidationFirst04
{651}{}{Erhm. Ow. *Whimper* Okay I'll leave.}
{652}{}{See that you do. [An evil grin transforms your face]}

# GottaGo
{680}{}{I'll leave *Sniff* Just don't come near me any more.}
{681}{}{See that you do.}
{682}{}{Sigh, the fun had to end sometime.}

# gotSkills
{710}{}{Hey, I have means you know. I'm not just a hot babe. I'm proficient in bartering and sharpshooting. I did odd jobs to earn a few extra caps.}
{711}{}{[END]}

# tooGood
{740}{}{I was too good. The caravan trips just ran out. I had to start selling off my possessions until nothing was left. Then they took my freedom away too.}

# BeenConvinced
{770}{}{What?}

# BeenBeaten
{800}{}{[She covers in fear] Please don't hurt me.}
{801}{}{I told you to leave. Now I must start all over. [Clench your fist]}
{802}{}{Why are you still here, fool?}
{803}{}{I told you to leave yet here you are. This time I'm gonna teach you a lesson.}
{804}{}{Why are you here? Looks like I get to play some more.}
{805}{}{I guess my meaning wasn't clear. Why else would you still be here?}
{806}{}{Hello there. I'm going to enjoy this... *fool.*}

# IntimidationFinal00
{830}{}{No please, I'll leave, I promise!}
{831}{}{Wait...}
{832}{}{[You grab the nearby shower hose, taking a step forward and grinning wickedly]}
{833}{}{[You scream into her face] Even the devil was once an angel!}

# IntimidationFinal01
{860}{}{[She is sobbing]}
{861}{}{[She is shivering from fear]}
{862}{}{If I so much as see you again, I won't be as forgiving as I am now. [You place the hand on the nearby shower hose]}
{863}{}{Me see you again, me not forgive. [You place the hand on the nearby shower hose]}
{864}{}{Don't tempt me!}

# IntimidationFinal02
{890}{}{Ehrm. Umpf.}
{891}{}{I can keep this up all day, sugar.}

# IntimidationFinal03
{950}{}{*Whimper*}
{951}{}{[Stop and leave her alone]}

