# Message file for tbtobi.ssl
# Number of nodes: 14
# Grammar pass done

{100}{}{You see a young man tossing a bottlecap.}
{101}{}{You see Dr. Tobillo, the Wandering Doctor.}
{102}{}{He has an unusually bushy beard for a man of his age.}

# Node_001
{200}{}{Hey there, }
{201}{}{! I've been expecting our paths to cross. Your name has been popping up in our database lately. Are you feeling alright? You seem fine. Hmm, it might be a glitch in the old system. Anyways, I'm Dr. Tobillo, also known as the Wandering Doctor.}
{202}{}{What are you doing with that bottlecap?}
{203}{}{Why do they call you the Wandering Doctor?}
{204}{}{I'd like to trade, Doc.}
{205}{}{Me barter, Tobi.}
{206}{}{Bye.}

# Node_002
{230}{}{I'm playing a game with bottlecaps.}
{231}{}{How do you play that?}
{232}{}{Can I join in?}
{233}{}{I'll leave you to it.}

# Node_003
{260}{}{It's a simple game. You throw your bottlecap, and whoever gets closest to the wall wins all the bottlecaps.}
{261}{}{Sounds like fun. Can I play?}

# Node_004
{290}{}{Sure, you just need a bottlecap. We all throw at the wall, and the one who gets closest wins.}
{291}{}{Count me in.}
{292}{}{I changed my mind. I have to be somewhere else.}

# Node_005
{320}{}{Sure thing. But aren't you supposed to be somewhere?}
{321}{}{I've got time. Let's do this.}
{322}{}{You're right. I'll leave you to it.}

# Node_006
{350}{}{Unlucky, }
{351}{}{. It looks like I win this time.}
{352}{}{Let's play again.}
{353}{}{I've had enough. Goodbye.}

# Node_007
{380}{}{Take care, }
{381}{}{.}
{382}{}{[END]}

# Node_008
{410}{}{Nice shot! You win this round.}

# Node_009
{440}{}{Back for more, }
{441}{}{?}
{442}{}{Let's play again.}
{443}{}{Just passing through.}

# Node_010
{470}{}{Well met. How can I assist you?}
{471}{}{Nothing right now. Goodbye.}

# Node_011
{500}{}{Back for another round?}
{501}{}{Your money's mine, Doctor!}

# Node012
{530}{}{Because I'm always on the move. Unlike you, I wasn't born here but captured by the robots. My ancestors hailed from Vault 15, and I grew up in Shady Sands. During my career, I never settled in one place but decided to travel with caravans from Shady Sands to Hoover Dam and from there to Fort Aradesh. Since that's not practical anymore, I move around the prison a lot. My patients appreciate me meeting them in their own cells; it's less stressful for them. Luckily, you caught me before I depart.}
{531}{}{Can we trade?}
{532}{}{Can you show me these places on my Pip-Boy map? Maybe one day I'll get a chance to visit them.}
{533}{}{Interesting. Thanks for sharing your story. Goodbye.}

# Node013
{560}{}{Well, let's hope you won't ever need any medical assistance! If you do, please see Dr. Danika in the Medical Treatment Area. It's located two levels above us.}
{561}{}{Thanks. Goodbye.}

# Node014
{590}{}{No problem. Let me bring up the coordinates on my Pip-Boy... There you go, all set!}
{591}{}{Thank you, Doctor. Goodbye.}
