# Message file for tbprsn.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see a young individual.}
{101}{}{A youthful vault dweller catches your eye.}
{102}{}{A dweller of Vault 8 stands before you.}

{200}{}{Phew, it's scorching in here!}
{201}{}{Life support needs to be up and running ASAP.}

{202}{}{Hey there, welcome to our Vault!}
{203}{}{Greetings and salutations, my friend!}

{204}{}{No wonder they sealed off that room, the generator is causing a stench.}
{205}{}{I hope someone fixes that darn generator soon!}
{206}{}{I spotted smoke emanating from the generator room earlier.}
{207}{}{It's awfully dark in here!}

{208}{}{Thank goodness everything has been repaired!}
{209}{}{I'm relieved that everything is back in working order!}
{210}{}{Ahhhh... The sweet satisfaction of functional liquid fluorinated hydrocarbons.}
{211}{}{One of those insta-meals sounds tempting right about now.}
{212}{}{Welcome to the vault, my esteemed citizen. May your stay be enjoyable!}
{213}{}{I'm ready and willing to lend a hand, just say the word!}
{214}{}{The crisp, refreshing taste of purified water...there's nothing like it.}
{215}{}{We're dishing out the enigmatic 'mystery meat' again. I'd wager it's meat...of some sort.}
{216}{}{The fruits of hard work are sweet indeed!}
{217}{}{I'm feeling under the weather... something isn't right.}
{218}{}{Well, well, seems like the vault has become a sanctuary for the less fortunate.}
