# Message file for tbwiggie.ssl
# Number of nodes: 38
# Grammar pass done

{100}{}{You see a cautious-looking figure.}
{101}{}{You see Wiggie.}
{102}{}{He's got a well-groomed mustache and slicked-back hair.}

# Node002
{230}{}{Hey, what's up?}
{231}{}{Mind your own business!}
{232}{}{Are you Wiggie?}
{233}{}{Nevermind. Goodbye.}

# Node003
{260}{}{Okay, sorry.}
{261}{}{[END]}

# Node004
{290}{}{[He hesitates for a moment.] Yes, I am. Why?}
{291}{}{I have come to kill you, Wiggie.}
{292}{}{I have come to warn you, Wiggie. Your life is in danger!}
{293}{}{I bring you good news, Wiggie. The Mechanic has decided to free you from your debts.}
{294}{}{Oh, just curious. Goodbye.}

# Node005
{320}{}{I beg your pardon?}
{321}{}{Do you know the Holy Word of Law, Wiggie? I have this passage memorized by heart...}
{322}{}{You heard me. And once I've killed you, I'll toss you in the radscorpion nest.}
{323}{}{The Mechanic sent me. Now it's time for you to die.}

# Node006
{350}{}{Uhh... No! I'm, uh... Clark. Yeah, Clark, that's me.}
{351}{}{You're lying!}
{352}{}{Hmm, you haven't seen Wiggie, then?}

# Node007
{380}{}{No, it's true! Wiggie is my, uh... brother! Tell me what you want with him, and I'll let him know.}
{381}{}{I *said* you're lying! Die, Wiggie!}
{382}{}{I'm here to inform Wiggie that he is freed from his debts. All he needs to do is sign a paper.}
{383}{}{I'm here to warn him. The Mechanic has sent someone to make an example out of him.}
{384}{}{I have come to kill him. Tell me where he is!}

# Node008
{410}{}{Uh... I think he went that way. [He points to the tram station] He said he was in a hurry.}
{411}{}{Right, thank you.}

# Node009
{440}{}{The Holy Word of Law? What are you talking about? Why did you say you were going to kill me?}
{441}{}{[Begin reciting]}

# Node010
{470}{}{W-what? You're crazy!}
{471}{}{Spare the pleasantries and prepare to die.}
{472}{}{Hardly. I'm a homicidal maniac, but I'm not crazy in the traditional sense of the word. Now it's time for you to die.}

# Node011
{500}{}{What is this? Who are you?}
{501}{}{The Mechanic has sent someone to kill you. He wants to make an example out of you.}
{502}{}{I'm your executioner.}

# Node012
{530}{}{What do you think I look like, a moron? The Mechanic would never do such a thing!}
{531}{}{It's true! He's in a good mood for the first time in forever. He already dismissed three other debtors today.}
{532}{}{You're right. I'm here to kill you.}

# Node013
{560}{}{Wait! I can pay!}
{561}{}{Too late for that. Die!}
{562}{}{Then pay up!}

# Node014
{590}{}{[He fumbles in his bag] Here! Here's a thousand. I'll, uh... I'll give you the rest tomorrow, okay?}
{591}{}{Now I suggest you leave the hospital and never come back.}
{592}{}{Pay me in full, or you die!}

# Node015
{620}{}{Okay, okay! Here's another 1,000. That's all I've got. Please don't kill me!}
{621}{}{Thanks. Now prepare to die!}

# Node016
{650}{}{That's all I've got, I swear!}
{651}{}{Then I suggest you leave the hospital and never return.}
{652}{}{Then you shall die!}

# Node017
{680}{}{Thank you, thank you!}

# Node018
{710}{}{How do you know this?}
{711}{}{Do you really want to know?}

# Node019
{740}{}{Wh-... Bu-... Why are you telling me this?}
{741}{}{I have my reasons. If you want to live, I suggest you run. Now.}
{742}{}{I thought it would be fun to scare you a little before I killed you.}

# Node020
{770}{}{Really? So what are you suggesting?}
{771}{}{Come with me to his office and sign the papers. You'd better hurry before he changes his mind.}

# Node021
{800}{}{I don't like this one bit...}
{801}{}{Like it or not, you're coming with me!}

# Node022
{830}{}{What? No, you've got to be kidding - the Mechanic would never do such a thing.}
{831}{}{Well, he just did.}
{832}{}{Yeah, I'm just kidding. I'm actually here to kill him.}

# Node023
{860}{}{Is that so? Well, I'll go find Wiggie and tell him the news... Thank you, stranger.}
{861}{}{Not so fast, Clark. Or should I call you Wiggie?}
{862}{}{You go ahead and do that.}

# Node024
{890}{}{I... I guess not.}
{891}{}{If you want to live, I suggest you run. Now.}
{892}{}{I changed my mind. It's time for you to die, Wiggie.}

# Node025
{920}{}{Shit... [He runs away]}
{921}{}{Wait!}

# Node026
{950}{}{Over my dead body!}
{951}{}{That can be arranged.}
{952}{}{I'll be back.}

# Node027
{980}{}{I smell rats...}
{981}{}{[You sniff the air] Nope, no rats here. Tell your brother that he's wanted.}

# Node028
{1010}{}{I told you, Wiggie is my brother!}
{1011}{}{His brother is good enough for me. Time to die!}
{1012}{}{Oh yes, sorry. Well, you go ahead and tell your brother then.}

# Node029
{1040}{}{What? I need to sign papers to get rid of the debt? I smell rats...}
{1041}{}{You're coming with me, whether you like it or not.}
{1042}{}{Then I'm afraid I'll have to kill you.}

# Node030
{1070}{}{It's certainly not like him, but who am I to argue with the Mechanic? You lead the way.}
{1071}{}{All right, follow me.}

# Node031
{1100}{}{Hrrm... Actually, I *am* Wiggie. You can never be too careful these days. So, will you take me to the Mechanic?}
{1101}{}{Sure. Just follow me.}

# Node032
{1130}{}{[He chuckles, then stops as he realizes you weren't kidding] Well, umm... He's not here. Actually, I don't know where he is.}
{1131}{}{Oh, but I think you do, Clark. Or should I call you Wiggie?}
{1132}{}{Don't worry about it, I'll find him.}

# Node033
{1160}{}{Wait, I'm not Clark! I mean Wiggie! I just... I'm his brother, okay? Please don't kill me!}
{1161}{}{Just shut up and face the consequences!}
{1162}{}{Whatever. I'll be back.}

# Node034
{1190}{}{Okay, I'll do that.}

# Node035
{1220}{}{Hey, this isn't the Mechanic's office! Where are you taking me?}
{1221}{}{Closer to your grave, so I don't have to drag your fat body so far.}
{1222}{}{We're almost there, trust me.}

# Node036
{1250}{}{Where are you taking me?}
{1251}{}{Oh, just someplace where nobody will hear you scream.}

# Node037
{1280}{}{No, I haven't seen Wiggie since we last spoke. What do you want?}
{1281}{}{Well, go find him then!}
{1282}{}{Tell me where Wiggie is, or I'll kill you instead!}
{1283}{}{Nothing. Goodbye.}

# Node038
{1310}{}{What do you want now?}
{1311}{}{I want your scalp.}
{1312}{}{Nothing. Goodbye.}
