# Message file for tbzeph.ssl
# Number of nodes: 20
# Grammar pass done

{100}{}{You see a young girl.}
{101}{}{You see Zeph.}
{102}{}{Her pale skin catches your attention.}

# start
{230}{}{Dude, I so need to spill this - the Rainmakers are like, the absolute coolest group in the wasteland.}
{231}{}{What makes them so great?}
{232}{}{Sure, kid. Whatever you say. Goodbye.}
{233}{}{Bah ba.}
{234}{}{You do drugs. You bad.}

# dontMakeMeLeave
{260}{}{Please, don't make me go. I legit have nowhere else.}
{261}{}{You have ten seconds to leave before I do something I might regret.}
{262}{}{Your presence is disturbing other patients. Why should I let you stay?}

# leaving
{290}{}{Fine, I'm out! [She runs away, fighting back a torrent of tears.]}
{291}{}{Good.}

# likeRat
{320}{}{I can totally change. I swear I won't chat up other patients about the rain anymore. I honestly thought it was no biggie. Sometimes I'd play in the rain, and I kinda love the spiritual stuff too. The others were a bit out there, but they accepted me, you know? Is it so wrong to want to feel loved?}
{321}{}{If you want to feel loved, find healthier ways. Now leave!}
{322}{}{I don't trust your words. I won't fall for it. Leave!}
{323}{}{I'll think about it. In the meantime, remember, the Dune Police never sleeps.}

# second
{350}{}{Eek! So, like, are you letting me stay? I haven't been annoying any other patients, promise.}
{351}{}{I haven't received any more complaints about you, so I guess I'll let you stay. Keep up the good behavior.}
{352}{}{If you haven't done anything wrong, why are you stuttering so much?}
{353}{}{Let's make a deal: You tell me everything about this group of yours, and I'll consider letting you stay.}
{354}{}{I'm still undecided. You'll hear from me again soon.}

# thanks
{380}{}{Dude, thank you! [She hugs you before you even get the chance to react. After a moment, she steps back, looking a little embarrassed.]}
{381}{}{Um... well... see you around.}
{382}{}{Thanks for the hug.}
{383}{}{Don't do that again.}

# fear
{410}{}{I'm just freaking out about getting kicked out, that's all. I'm totally not hiding anything, pinky swear!}
{411}{}{Right, I'm tired of your lies. Get out of here!}
{412}{}{If you say so.}

# ratOut
{440}{}{Supercell, he's like, the founder and stuff, and only members know that secret. The robots found us when we were having our Troposphere party in the desert. We got separated after coming here, and I haven't seen them since. Can I stay now, pretty please?}
{441}{}{I guess. As long as you behave, you can stay.}
{442}{}{No, I wouldn't let a dirty little snake like you, who just sold out her only friends in the world, stay here.}

# letStay
{470}{}{Thank you, thank you, thank you! Praise Troposphere! I promise I'll be good to the patients and won't be a nuisance anymore.}
{471}{}{[END]}

# But
{500}{}{But you said that...}
{501}{}{You're right. As long as you behave, you may stay.}
{502}{}{I lied. If you're still here after I blink three more times, you'll regret it.}

# Leaving2
{530}{}{You... you... bastard! [She bursts into tears and runs away.]}
{531}{}{You... you... bitch! [She bursts into tears and runs away.]}
{532}{}{[END]}

# wontRatOut
{560}{}{No way, I can't do that. These people are my squad, they mean the world to me. I can't just betray them.}
{561}{}{Well, good luck out there in the dark hallways, filled with crazy criminals around every corner. You better start running.}
{562}{}{I should teach you a lesson, but I'll give you time to think it over.}

# ratTemple
{590}{}{It just is, you know? All you gotta do is chill out and worship Troposphere. Everything else just works out and peeps will be friends with you, even if you landed here with nada like me. [She shudders slightly.] And have you ever felt raindrops on your skin? It's epic.}
{591}{}{No, I haven't.}
{592}{}{Sometimes, yeah.}
{593}{}{I'm sorry to hear that you were abandoned. How did that happen?}
{594}{}{Guess what? I'm a member of the... umm... Dune Police! And that's just the information I needed. You're busted!}

# spirit
{620}{}{That's the spirit, kid.}

# special
{650}{}{W-What? How'd you know that?}
{651}{}{Me special.}

# ohWell
{680}{}{Well, whatever. You should totally try it if you ever get the chance. It's unforgettable. I mean, uh, never mind. Forget I said anything.}

# cool
{710}{}{Cool beans. Now you can join the Rainmakers. All you gotta do is hang out in the desert with us.}
{711}{}{I'm not sure if I want to do that. Goodbye.}

# Converted
{740}{}{You're special? Like, you can see into my soul or something? Yes! YES! I'll follow the way of the rain! Praise Troposphere!}
{741}{}{Tropo!}

# dumped
{770}{}{Long story short, my parents ditched me. But, like, I'm totally over it now. The Rainmakers are my new fam. I have loads of friends and a seriously bright future ahead. That's the tea.}
{771}{}{If you say so. Goodbye, Zeph.}
