# Message file for v13albrt.ssl
# Number of nodes: 8
# Grammar pass done

{100}{}{You see a powerful super mutant.}
{101}{}{You see a powerful, intelligent super mutant who exudes a commanding presence.}
{102}{}{The super mutant before you appears to possess great intellect while displaying an emotionless demeanor.}

{150}{}{Vault 13... Goodbye.}
{151}{}{The super mutant doesn't say anything.}

# Node001
{200}{}{Halt! Stay where you are! I am familiar with Vault 13 and its dwellers, and you are not a face I recognize. Yet you wear a Vault 13 jumpsuit. Hmm... Are you a looter?}
{201}{}{Yes, I'm just a lowly looter, scouring for abandoned treasures. A criminal, you might say. Pay me no mind, continue with your business of slaughter or whatever it is you're doing. Heh.}
{202}{}{Actually, no. I am a prisoner from a different time and place! You see, I stumbled upon a hollow rock in the desert, and then--}
{203}{}{Wait, were you once a resident of Vault 13?}
{204}{}{Perish, vile creature!}
{205}{}{Me looter.}
{206}{}{Me prisoner. Big doughnut send here.}
{207}{}{You Vaulty?}
{208}{}{[Flee.]}

# Node002
{230}{}{We have no interest in you. Move along.}
{231}{}{Thank goodness.}
{232}{}{[Say nothing.]}

# Node003
{260}{}{Halt in the name of the Unity! Oh, it's you, Zed. Don't startle me like that; you know I'm jumpy. Well, the area is clear. The Overseer refused to yield. Let's return to the base.}
{261}{}{Right, the base. I'll conduct another sweep, and then we can head back.}
{262}{}{I've finished here. Let's make our way back.}
{263}{}{Me look more!}
{264}{}{We go.}

# Node004
{290}{}{You're utterly deranged. Dipping you in the vats would only spawn another Lesser One.}
{291}{}{[CONTINUE]}

# Node005
{320}{}{Regardless, we have no concern for you.}

# Node006
{350}{}{Well, each of us was once someone else before the Master blessed us. That's your answer. However, your existence doesn't matter to us. Praise the Unity!}
{351}{}{Ah, yes, it's such a shame for me. The epitome of misfortune.}
{352}{}{Huh, me unlucky lucky.}

# Node007
{380}{}{Fine, I'll wait outside. Don't take too long. I'll check on you in 20 minutes. Keep your radio handy.}
{381}{}{Very well.}
{382}{}{'K.}

# Node008
{410}{}{Ugh! You're even uglier than I am. The scent of blood attracts all the wasteland vermin. So, are you here to feast or pilfer?}
{411}{}{Feast.}
{412}{}{Pilfer.}
{413}{}{Both.}
{414}{}{Die!}
{415}{}{Neither, really. I simply took a wrong turn.}
