#############################################################
#  Message File: ZCBrahmn.msg                               #
#                                                           #
#       Body Type:  Brahmin                                 #
#       Combat AI: None                                     #
#       Weapons: None                                       #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
# Grammar pass done
{100}{}{You see a typical domesticated brahmin.}
{101}{}{The unique characteristic of brahmin, with their two heads, is believed to be a result of early radiation exposure on what was once known as cows.}
{102}{}{At first glance, this brahmin appears to be quite ordinary.}
{103}{}{Brahmin aren't known for their conversational skills.}
{104}{}{Don't you have something more productive to do than chat with a two-headed cow?}
{105}{}{Behold, a magnificent two-headed mutant cow known as a brahmin. Brahmin are highly valuable as they provide meat, milk, leather, baby brahmin, bones, and even their droppings can be used as fuel for fires.}

{201}{}{Mooo...}
{202}{}{Mooo Mooo Mooo...}
{203}{}{Mooo...}
{204}{}{Moooooo...}
{205}{}{Mooooooooo...}
{206}{}{:: GRUNT ::}
