/*

        Name:           Prisoner
        Location:       Tibbets
        Description:

           Created: 20/06/2020 22:53:34

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"

#define NAME                    SCRIPT_TBCOMM

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (0)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\footsteps.h"
#include "..\HEADERS\v8ext.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending


// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   add_timer_event(self_obj,game_ticks(random(1,5)),0);
   call new_plague_check(self_obj, LVAR_Herebefore);

   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_RND_RAIDERS);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_BERSERKER);

   call critter_setup_footsteps_map_enter(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

   if(self_elevation == dude_elevation) then begin
   /* If the critter is mad at the player for any reason, it will attack and remember to attack
      the player should the game be saved and loaded repeatedly. Additionally, if any special
      actions need to be taken by the critter based on previous combat, the critter will remember
      this as well. */

      if (self_can_see_dude or self_can_hear_dude) then begin

         if (map_var(MVAR_SIMTEK3) == 0) then begin
            set_map_var(MVAR_SIMTEK3, 1);
            play_sfx("SIMTEK3");
            display_msg(message_str(SCRIPT_V8EXT, 106));
         end

         self_attack_dude;
         //Macro made by Tom to keep the critter fleeing.
      end
   end
end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin

end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

end

procedure timed_event_p_proc begin

   if (fixed_param == 0) then begin
      if (
      (random(0, 10) == 1) and
      (not(combat_is_initialized)) and
      (self_can_see_dude or self_can_hear_dude)
      ) then begin
         reg_anim_clear(self_obj);
         reg_anim_begin();
         animate_move_obj_to_tile(
            self_obj,
            tile_num_in_direction(
               tile_num(self_obj),
               random(0, 5),
               random(1, 3)
            ),
            ANIMATE_WALK
         );
         reg_anim_end();
      end
      add_timer_event(self_obj, game_ticks(random(3, 5)), 0);

      if ((random(0, 30) == 1) and self_can_speak) then begin
         floater_bad_rand(200, 228);
      end
   end

   call critter_setup_footsteps_timed_event(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT, SFX_FOOTSTEP_SOFT_SHOE);

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_neutral_critter
/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin

end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin

end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

// Skill checks and miscellaneous procedures

