/*******************************************************************************
        Name:
        Location:
        Description: Object template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\tibbets.h"

#define NAME                    SCRIPT_TBFFCONS

/* Standard Script Procedures */
procedure start;
procedure use_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure description_p_proc;

/* Defines */

/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/

#define LVAR_XP_Repair                 (1)
#define LVAR_XP_Science                (2)

/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/

procedure start begin
end

procedure description_p_proc begin
end

procedure use_p_proc begin
   script_overrides;

   if(map_var(MVAR_SecField_down) == 1) then begin
      display_msg(mstr_item(10));
   end else begin
      if(get_critter_stat(source_obj, STAT_lu) >= 6) then begin
         set_map_var(MVAR_SecField_down, 1);
         display_msg(mstr_stat(700));
      end
      else begin
         display_msg(mstr_stat(701));
      end
   end
end

procedure use_obj_on_p_proc begin
   if (obj_pid(obj_being_used_with) == PID_WCD_KEYCARD) then begin
      script_overrides;
      play_sfx("SWDKEYX1");

      if(map_var(MVAR_SecField_down) == 1) then begin
         set_map_var(MVAR_SecField_down, 0);
      end else begin
         set_map_var(MVAR_SecField_down, 1);
      end

   end
end

procedure use_skill_on_p_proc begin
   if(map_var(MVAR_SecField_down) == 0) then begin
      if (
         (action_being_used == SKILL_SCIENCE) and
         is_success(roll_vs_skill(source_obj, SKILL_SCIENCE, -20))
      ) then begin
         script_overrides;
         set_map_var(MVAR_SecField_down, 1);
         display_mstr(100);
         if (local_var(LVAR_XP_Science) == 0) then begin
            give_xp(10);
            set_local_var(LVAR_XP_Science, 1);
         end
      end else if (
         ((action_being_used == SKILL_REPAIR) and
         is_success(roll_vs_skill(source_obj, SKILL_REPAIR, -20))) or
         ((action_being_used == SKILL_TRAPS) and
         is_success(roll_vs_skill(source_obj, SKILL_TRAPS, -20)))
      ) then begin
         script_overrides;
         set_map_var(MVAR_SecField_down, 1);
         display_mstr(101);
         if (local_var(LVAR_XP_Repair) == 0) then begin
            give_xp(10);
            set_local_var(LVAR_XP_Repair, 1);
         end
      end
   end
end
