/*

        Name:
        Location:
        Description:

           Created: 07/10/2020 20:46:43

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBLINDER

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure linder1;
procedure linderA;
procedure linderB;
procedure linderC;
procedure linderD;
procedure linderE;
procedure linderF;
procedure linder1sci;
procedure linder2sci;
procedure linder2;
procedure linder3sci;
procedure linder3;
procedure linderquestion;
procedure linderagain;
procedure linderDevon1;
procedure linderDevon2;
procedure Node999_wait_week;
procedure linderDevonNews;
procedure linderDevonNews2;
procedure linderDevonNews3;
procedure linderDevonNews4;
procedure linderDevonNews5;
procedure linderDevonNews6;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_StartResearch               (8)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
call new_plague_check(self_obj, LVAR_Herebefore);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

   if(global_var(GVAR_QUEST_LOBOTOMITE) == 2) then begin
      floater_good(150);
      return;
   end

   call set_idiot_savant_int;
       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;
if (local_var(LVAR_Herebefore)==0) then
   call linder1;
else begin
   if((local_var(LVAR_StartResearch) > 0) and ((game_time - local_var(LVAR_StartResearch)) / ONE_GAME_WEEK >= 1)) then begin
      set_local_var(LVAR_StartResearch, 0);
      call linderDevonNews;
   end else
      call linderagain;
end

gSay_End;
       end_dialogue;
//end

   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure linder1
begin
Reply(mstr(200)+dude_name+mstr(201));
NOption(202,linderA,4);
if (has_skill(dude_obj,SKILL_SCIENCE)>=50) then
NOption(203,linder1sci,4);
NOption(204,Node999,4);
NOption(205,linder2,-3);
NOption(206,Node999,-3);
end

procedure linderA
begin
Reply(230);
NOption(231,linderB,4);
NOption(232,linderC,4);
end

procedure linderB
begin

   if(global_var(GVAR_QUEST_LOBOTOMITE) == 0) then begin
      Reply(mstr(260)+dude_name+mstr(261));
      NOption(262,linderD,4);
      NOption(263,linderquestion,4);
      NOption(264,linderE,4);
   end else begin
      Reply(mstr(250)+dude_name+mstr(251));
      NOption(322,Node999,4);
   end
end

procedure linderC
begin
Reply(290);
NOption(291,linderF,4);
NOption(292,linderF,4);
NOption(293,linderF,4);
end

procedure linderD
begin
   set_global_var(GVAR_QUEST_LOBOTOMITE, 1);
Reply(mstr(320)+dude_name+mstr(321));
NOption(322,Node999,1);
end

procedure linderE
begin
Reply(350);
NOption(322,Node999,1);
end

procedure linderF
begin
Reply(mstr(380)+dude_name+mstr(381));
NOption(382,linderB,4);
NOption(383,linderB,-3);
end

procedure linder1sci
begin
Reply(410);
NOption(411,linder2sci,4);
NOption(412,Node999,4);
end

procedure linder2sci
begin
Reply(440);
if(global_var(GVAR_QUEST_LOBOTOMITE) == 0) then begin
NOption(441,linder3sci,4);
end else begin
NOption(430,Node999,4);
end
NOption(442,Node999,4);
end

procedure linder2
begin
Reply(470);
if(global_var(GVAR_QUEST_LOBOTOMITE) == 0) then begin
NOption(471,linder3,-3);
end else begin
NOption(460,Node999,-3);
end
end

procedure linder3sci
begin
Reply(500);
NOption(501,linderquestion,4);
NOption(502,linderD,4);
NOption(503,linderE,4);
end

procedure linder3
begin
Reply(530);
NOption(531,linderD,-3);
NOption(532,linderE,-3);
end

procedure linderquestion
begin
Reply(560);
NOption(561,linderD,4);
NOption(562,linderE,4);
end

procedure linderagain
begin
Reply(590);
if (obj_is_carrying_obj_pid(dude_obj,PID_DEVONS_HEAD)>0) then
NOption(591,linderDevon1,4);
NOption(592,Node999,4);
NOption(593,Node999,-3);
end

procedure linderDevon1
begin
Reply(620);
NOption(621,linderDevon2,4);
NOption(622,Node999,4);
end

procedure linderDevon2
begin

destroy_object(obj_carrying_pid_obj(dude_obj, PID_DEVONS_HEAD));
set_local_var(LVAR_StartResearch, game_time);

Reply(650);
NOption(651,Node999_wait_week,4);
NOption(652,Node999,4);
end

procedure linderDevonNews
begin
Reply(680);
NOption(681,linderDevonNews2,4);
end

procedure linderDevonNews2
begin

   if(not(town_known(AREA_CIRCLE_OF_STEEL))) then begin
      give_xp(500);
      mark_on_map(AREA_CIRCLE_OF_STEEL)
      display_msg(g_mstr(1008) + " " + mstr_map(1552) + ".");
   end

Reply(710);
NOption(711,linderDevonNews3,4);
end

procedure linderDevonNews3
begin

Reply(740);
NOption(741,linderDevonNews4,4);
NOption(742,Node999,4);
end

procedure linderDevonNews4
begin
Reply(770);
NOption(771,linderDevonNews5,4);
end

procedure linderDevonNews5
begin
Reply(800);
NOption(771,linderDevonNews6,4);
end

procedure linderDevonNews6
begin
Reply(830);
NOption(831,Node999,4);
end

procedure Node999_wait_week begin
   call Node999;
   fadeout(1);
   fadein(1);
   game_time_advance(ONE_GAME_DAY * 7);
end

//xxxxxxxxxxxxxxxxxxxx
