/*

        Name:           Salem
        Location:
        Description:

           Created: 28/09/2020 20:12:25

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBSALEM

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending
procedure Node999a;

// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure General;
procedure Owner;
procedure First;
procedure Whynot;
procedure Attitude;
procedure Deal;
procedure Cheat;
procedure PayOut;
procedure Subsequent;
procedure Company;
procedure NoCaps;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure PayOut_smuggler;
procedure PayOut_fucker;
procedure PayOut_magik;
procedure PayOut_father;
procedure PayOut_croz;
procedure PayOut_gabrielle;
procedure PayOut_robb;
procedure Sol;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);

   add_timer_event(self_obj,game_ticks(random(1,5)),0);
   call new_plague_check(self_obj, LVAR_Herebefore);


end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=1;
   Slavery_Tolerant:=SLAVE_INTOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;
       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;

if (local_var(LVAR_Herebefore)==0) then begin
       call First;
end else if (local_var(LVAR_Herebefore)==1) then begin
       call Subsequent;
end
       gSay_End;
       end_dialogue;

   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin
   add_timer_event(self_obj,game_ticks(random(1,5)),0);

    if (random(1, 30) == 1) then begin

      if (local_var(LVAR_Herebefore)==0) then begin
      floater_rand(200,204);
      end else if (local_var(LVAR_Herebefore)==1) then begin
      floater_rand(230,234);
      end

    end

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_evil_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures



// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE

procedure First
begin
Reply(260);
NOption(261,Whynot,4);
NOption(262,Node010,4);
NOption(263,Attitude,4);
NOption(264,Node011,-3);
NOption(265,Node999,4);
NOption(266,Node999,-3);
end

procedure Whynot
begin
Reply(290);
NOption(291,Deal,4);
NOption(292,Attitude,4);
end

procedure Attitude
begin
Reply(320);
NOption(321,Deal,4);
end

procedure Deal
begin
Reply(350);
NOption(351,Node999,4);
NOption(352,Cheat,4);
end

procedure Cheat
begin
Reply(380);
NOption(381,Node999,4);
NOption(382,Node999,4);
end

procedure PayOut
begin
   item_caps_adjust(dude_obj, 100);
   inc_global_var_amt(GVAR_TOWN_REP_TIBBETS, 10);
   inc_general_rep(5);


Reply(410);
NOption(411,Node999,4);
NOption(412,Node999,4);
end

procedure Subsequent
begin
Reply(440);
NOption(441,NoCaps,4);
NOption(442,Company,4);
NOption(443,Node013,4);
NOption(444,Node999,4);
NOption(445,Node012,-3);
end

procedure Company
begin
Reply(470);
NOption(443,Node013,4);
NOption(471,NoCaps,4);
NOption(472,Node999,4);
end

procedure NoCaps
begin
Reply(500);
NOption(501,Node999,4);
end

procedure Node010
begin
Reply(530);
NOption(531,Whynot,4);
NOption(532,Attitude,4);
end

procedure Node011
begin
Reply(560);
NOption(561,Node012,-3);
BOption(562,Node998,-3);
end

procedure Node012
begin
Reply(590);
NOption(561,Node999,-3);
end

procedure Node013
begin
Reply(620);
if(global_var(GVAR_TIPOFF_SMUGGLER) == 1) then
NOption(621,PayOut_smuggler,4);
if(global_var(GVAR_TIPOFF_FUCKER) == 1) then
NOption(622,PayOut_fucker,4);
if(global_var(GVAR_TIPOFF_KILLER) == 1) then
NOption(624,Sol,4);
if(global_var(GVAR_TIPOFF_MAGIK) == 1) then begin
NOption(625,PayOut_magik,4);
NOption(629,PayOut_magik,4);
end
if(global_var(GVAR_TIPOFF_FATHER) == 1) then
NOption(626,PayOut_father,4);
if(global_var(GVAR_TIPOFF_CROZ) == 1) then
NOption(627,PayOut_croz,4);
if(global_var(GVAR_TIPOFF_GABRIELLE) == 1) then
NOption(628,PayOut_gabrielle,4);
if(global_var(GVAR_TIPOFF_ROBB) == 1) or ((global_var(GVAR_ANGELA_DEAD) == 1) and  (get_dude_attr(STAT_lu) >= 9)) then
NOption(630,PayOut_robb,4);
NOption(623,Node999,4);
end

procedure Sol begin
item_caps_adjust(dude_obj, 100);
set_global_var(GVAR_TIPOFF_KILLER, 2);
   inc_global_var_amt(GVAR_TOWN_REP_TIBBETS, 10);
   inc_general_rep(5);


Reply(409);
NOption(411,Node999a,4);
NOption(412,Node999a,4);
end

procedure PayOut_smuggler begin
   set_global_var(GVAR_TIPOFF_SMUGGLER, 2);
   call PayOut;
end

procedure PayOut_fucker begin
   set_global_var(GVAR_TIPOFF_FUCKER, 2);
   call PayOut;
end

procedure PayOut_magik begin
   set_global_var(GVAR_TIPOFF_MAGIK, 2);
   call PayOut;
end

procedure PayOut_father begin
   set_global_var(GVAR_TIPOFF_FATHER, 2);
   call PayOut;
end

procedure PayOut_croz begin
   set_global_var(GVAR_TIPOFF_CROZ, 2);
   call PayOut;
end

procedure PayOut_gabrielle begin
   set_global_var(GVAR_TIPOFF_GABRIELLE, 2);
   call PayOut;
end

procedure PayOut_robb begin
   set_global_var(GVAR_TIPOFF_ROBB, 2);
   call PayOut;
end


procedure Node999a begin
   fadeout(1);
   call Node999;
   set_obj_visibility(self_obj, 1);
   fadein(1);
   destroy_object(self_obj);
end
//xxxxxxxxxxxxxxxxxxxx
