/*

        Name:           Lieutenant Seb Simmonds
        Location:       Red River
        Description:    Commands 3rd Guard Batallion.

           Created: 07/10/2020 19:53:08

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBSEB

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure FirstStart;
procedure AFirstWelcome;
procedure BTrickOne;
procedure CWKIDFY;
procedure DSlang;
procedure EHostile;
procedure FWKIDFY;
procedure GTech;
procedure HHostile;
procedure IInfo;
procedure JGauss;
procedure KSlang;
procedure LGTFO;
procedure MAttacks;
procedure NDrink;
procedure OInfo;
procedure PInfo;
procedure QWomen;
procedure RWomen;
procedure SWomen;
procedure THostile;
procedure UWomen;
procedure VEmma;
procedure WEmma;
procedure SeenStart;
procedure QuestStart;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Pissed               (8)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
call new_plague_check(self_obj, LVAR_Herebefore);

   // TODO Cafe
   if (cur_map_index == MAP_TIBBETS_SERVICE_AND_VEHICLE_DEPOT_AREAS_CAFE) then begin
      set_obj_visibility(self_obj, 1);
   end

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude) and obj_is_visible_flag(self_obj)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;


   if(local_var(LVAR_Pissed) == 1) then begin
      floater_bad(560);
      return;
   end

   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;

if (local_var(LVAR_Herebefore)==0) then begin
       call FirstStart;
end else if (local_var(LVAR_Herebefore)==1) then begin
   if(global_var(GVAR_MARTIN_SEB) == 1) then
      call QuestStart;
   else
       call SeenStart;
end

       gSay_End;
       end_dialogue;


   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


// Node FirstStart
//
// Notes:
//
// This is where Dialogue starts for the first time. Set Flag "Talkedto" to 1

procedure FirstStart
begin
   if(dude_is_stupid) then begin
      Reply(150);
   end else begin
      Reply(200);
   end
NOption(201,AFirstWelcome,4);
NOption(202,BTrickOne,4);
NOption(151,Node999,-3);
end

procedure AFirstWelcome
begin
Reply(230);
NOption(dude_name + mstr(231),CWKIDFY,4);
if (get_critter_stat(dude_obj,STAT_ch) <= 4) then
NOption(232,DSlang,4);
NOption(233,EHostile,4);
end

procedure BTrickOne
begin
Reply(260);
NOption(261,FWKIDFY,4);
if (get_critter_stat(dude_obj,STAT_ch)<=5) then
NOption(262,HHostile,4);
if (get_critter_stat(dude_obj,STAT_ch)>=6) then
NOption(262,GTech,4);
end

procedure CWKIDFY
begin
if (dude_is_male) then Reply(290); else
if (dude_is_female) then Reply(291);
NOption(292,IInfo,4);
NOption(293,JGauss,4);
NOption(294,Node999,4);
end

procedure DSlang
begin
Reply(320);
NOption(292,IInfo,4);
NOption(293,JGauss,4);
NOption(321,KSlang,4);
NOption(294,Node999,4);
end

procedure EHostile
begin
Reply(350);
NOption(351,FWKIDFY,4);
BOption(352,LGTFO,4);
NOption(353,MAttacks,4);
end

procedure FWKIDFY
begin
Reply(380);
NOption(292,IInfo,4);
NOption(293,JGauss,4);
NOption(294,Node999,4);
end

procedure GTech
begin
Reply(410);
NOption(411,CWKIDFY,4);
NOption(dude_name + mstr(412),NDrink,4);
NOption(413,LGTFO,4);
end

procedure HHostile
begin
Reply(440);
NOption(mstr(441)+dude_name+mstr(442),FWKIDFY,4);
end

procedure IInfo
begin
Reply(470);
NOption(471,MAttacks,4);
NOption(472,OInfo,4);
NOption(293,JGauss,4);
end

procedure JGauss
begin
Reply(500);
NOption(501,PInfo,4);
NOption(502,Node999,4);
end

procedure KSlang
begin
Reply(530);
NOption(501,PInfo,4);
NOption(531,Node999,4);
end

// Node LGTFO
//
// Notes:
//
// Set Flag "Dick" to 1

procedure LGTFO
begin
set_local_var(LVAR_Pissed, 1);
Reply(560);
NOption(561,Node999,4);
end

procedure MAttacks
begin
Reply(590);
NOption(501,PInfo,4);
end

// Node NDrink
//
// Notes:
//
// Set Flag "Tech" to 1

procedure NDrink
begin
Reply(620);
NOption(561,Node999,4);
end

procedure OInfo
begin
Reply(650);
NOption(651,QWomen,4);
NOption(501,PInfo,4);
end

procedure PInfo
begin
Reply(680);
NOption(292,IInfo,4);
NOption(293,JGauss,4);
NOption(294,Node999,4);
end

procedure QWomen
begin
Reply(710);
if (dude_is_male) then
NOption(711,RWomen,4);
if (dude_is_female) then
NOption(712,RWomen,4);
NOption(713,PInfo,4);
end

procedure RWomen
begin
if (dude_is_male) then Reply(740); else
if (dude_is_female) then Reply(741);
if (dude_is_male) then
NOption(742,SWomen,4);
if (dude_is_female) then
NOption(743,SWomen,4);
NOption(744,THostile,4);
NOption(745,UWomen,4);
end

procedure SWomen
begin
Reply(770);
NOption(771,UWomen,4);
end

procedure THostile
begin
Reply(800);
NOption(801,RWomen,4);
BOption(802,LGTFO,4);
end

procedure UWomen
begin
Reply(830);
GOption(831,VEmma,4);
end

procedure VEmma
begin
Reply(860);
GOption(861,WEmma,4);
NOption(862,Node999,4);
NOption(863,PInfo,4);
end

// Node WEmma
//
// Notes:
//
// Set Flag "GotQuest" to 1

procedure WEmma
begin
   set_global_var(GVAR_MARTIN_SEB, 1);
Reply(890);
NOption(891,Node999,4);
end

// Node SeenStart
//
// Notes:
//
// This where the dialogue starts if the PC has talked to Seb before ("Talkedto" = 1), but "GotQuest" = 0

procedure SeenStart
begin
Reply(920);
NOption(292,IInfo,4);
NOption(293,JGauss,4);
NOption(294,Node999,4);
end

// Node QuestStart
//
// Notes:
//
// This is where the Dialogue starts if "GotQuest" = 1 and the quest HASN'T been completed.

procedure QuestStart
begin
Reply(950);
NOption(951,PInfo,4);
end



//xxxxxxxxxxxxxxxxxxxx
