/*

        Name:           Sol
        Location:
        Description:

           Created: 05/10/2020 18:42:03

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_TBSOL

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure Skill_Check_000_Speech;
procedure Skill_Check_001_Speech;
procedure Leave;




// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure First_Time;
procedure ASTEXP_01;
procedure AST_REM_RND;
procedure AST_RND_LIST;
procedure Insulted;
procedure Annoyed;
procedure WakesFromDaze;
procedure Martin_LS01;
procedure Martin_LS02;
procedure Martin_LS03;
procedure Martin_LS04;
procedure Martin_LS05;
procedure Martin_LS06;
procedure Martin_LS07;
procedure Quest_FORK;
procedure Quest_DIP;
procedure Quest_DIP2;
procedure Quest_Force;
procedure Quest_Force01;
procedure St00PaD_LOWINT;
procedure St00PaD_LINT01;
procedure Nth_Time;
procedure AQ_Fork;
procedure AQ_DipEND;
procedure AQ_Force01;
procedure AQ_IntimEND;
procedure Node028;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Prophet                    (8)
#define LVAR_Leave                    (9)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_TIBBETS_PRISONERS);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
   add_timer_event(self_obj,game_ticks(random(1,5)),0);

if(global_var(GVAR_TIPOFF_KILLER) == 2) then begin
   destroy_object(self_obj);
end

   if(not(obj_is_visible_flag(self_obj))) then begin
      set_obj_visibility(self_obj, 0);
   end

   call new_plague_check(self_obj, LVAR_Herebefore);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude) and obj_is_visible_flag(self_obj)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;

   if(not(dude_is_stupid)) then begin

      if (local_var(LVAR_Herebefore)==0) then begin
            call First_Time;
      end else if (local_var(LVAR_Herebefore)==1) then begin
            call Nth_Time;
      end

   end else begin
        call St00PaD_LOWINT;

   end

       gSay_End;
       end_dialogue;


   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin

   add_timer_event(self_obj,game_ticks(random(3, 5)),0);

   if(not(obj_is_visible_flag(self_obj))) then begin
      return;
   end

    if (random(0, 30) == 1) then begin
       if(local_var(LVAR_Prophet) == 1) then
          floater_rand(230, 232);
       else
          floater_rand(200, 202);
   end


end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_evil_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

procedure Skill_Check_000_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -25);
if is_success(roll_temp) then
begin
call Quest_Force01;
end
else begin
call Node028;
 end
end

procedure Skill_Check_001_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -25);
if is_success(roll_temp) then
begin
call AQ_IntimEND;
end
else begin
call Node028;
 end
end





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE

// Node First_Time
//
// Notes:
//
// NPC being approached the first time.

procedure First_Time
begin
Reply(290);
NOption(291,ASTEXP_01,4);
// NOTE: Forks into two ways of dealing with the 'Druggies' quest. One path is diplomatic, the other, brutal.
NOption(292,Quest_FORK,4);
// NOTE: Subtle insult against the NPC.
BOption(293,Insulted,4);
NOption(294,Node999,4);
end

procedure ASTEXP_01
begin
Reply(320);
NOption(321,AST_REM_RND,4);
end

// Node AST_REM_RND
//
// Notes:
//
// Very subtle reference to HHGTTG.

procedure AST_REM_RND
begin
Reply(350);
// NOTE: Continues to display random remarks from the subconcious.
NOption(351,AST_RND_LIST,4);
NOption(352,Node999,4);
end

procedure AST_RND_LIST
begin
Reply(random(373,380));
// NOTE: This is the random trigger for the same node, displaying a different text each time randomly.
NOption(381,AST_RND_LIST,4);
// NOTE: This triggers the next node in conversation.
NOption(382,WakesFromDaze,4);
end

procedure Insulted
begin
Reply(410);
NOption(411,Annoyed,4);
BOption(412,Node999,4);
end

procedure Annoyed
begin
Reply(440);
// NOTE: Starts a series of nodes explaining Natalia's life story.
NOption(441,Martin_LS01,4);
NOption(442,Quest_FORK,4);
NOption(443,Node999,4);
end

procedure WakesFromDaze
begin
Reply(470);
// NOTE: Loops back to 'annoyed' state.
NOption(471,Annoyed,4);
// NOTE: Loops back to 'Insulted' node.
BOption(472,Insulted,4);
NOption(473,Martin_LS01,4);
end

procedure Martin_LS01
begin
Reply(500);
NOption(501,Martin_LS02,4);
NOption(502,Martin_LS02,4);
end

procedure Martin_LS02
begin
Reply(530);
NOption(531,Martin_LS03,4);
NOption(532,Martin_LS03,4);
NOption(533,Node999,4);
end

procedure Martin_LS03
begin
Reply(560);
NOption(561,Martin_LS04,4);
NOption(562,Node999,4);
end

procedure Martin_LS04
begin
Reply(590);
NOption(591,Martin_LS05,4);
NOption(592,Martin_LS05,4);
end

procedure Martin_LS05
begin
Reply(620);
if (has_skill(dude_obj,SKILL_CONVERSANT)>=40) then
NOption(621,Martin_LS06,4);
NOption(622,Quest_FORK,4);
end

procedure Martin_LS06
begin
Reply(650);
if (has_skill(dude_obj,SKILL_CONVERSANT)>=50) then
NOption(651,Martin_LS07,4);
NOption(652,Node999,4);
end

procedure Martin_LS07
begin
Reply(680);
NOption(681,Quest_DIP2,4);
end

procedure Quest_FORK
begin
Reply(710);
NOption(711,Quest_DIP,4);
NOption(712,Quest_Force,4);
NOption(713,Node999,4);
end

procedure Quest_DIP
begin
Reply(740);
if (has_skill(dude_obj,SKILL_CONVERSANT)>=50) then
NOption(741,Quest_DIP2,4);
NOption(742,Node999,4);
end

procedure Quest_DIP2
begin
Reply(770);
NOption(771,Leave,4);
end

procedure Quest_Force
begin
Reply(800);
NOption(801,Skill_Check_000_Speech,4);
NOption(802,Node999,4);
end

// Node Quest_Force01
//
// Notes:
//
// Perhaps a -3 to karma from this option would be good? Something of the sort. Personally I never enjoy promoting the idea of violence... Even though it's normal in a game with such an elaborate combat engine.

procedure Quest_Force01
begin
   dec_general_rep(3);
Reply(830);
NOption(771,Leave,4);
end

procedure St00PaD_LOWINT
begin
Reply(860);
NOption(861,St00PaD_LINT01,-3);
end

procedure St00PaD_LINT01
begin
Reply(890);
NOption(891,Node999,-3);
end

procedure Nth_Time
begin
Reply(920);
if(local_var(LVAR_Leave) == 1) then
NOption(921,AQ_Fork,4);
NOption(922,Node999,4);
end

procedure AQ_Fork
begin
Reply(950);
NOption(951,AQ_DipEND,4);
NOption(952,AQ_Force01,4);
end

procedure AQ_DipEND
begin
Reply(980);
NOption(771,Leave,4);
end

procedure AQ_Force01
begin
Reply(1010);
NOption(1011,Skill_Check_001_Speech,4);
BOption(1012,Node998,4);
end

procedure AQ_IntimEND
begin
   dec_general_rep(3);
Reply(1040);
// NOTE: I think it would be a good idea to put in -x to karma for using this option. Once more, I never enjoy promoting the idea of unnecessary violence, and thus there should be consequence for choosing such a brutal course of action.
NOption(771,Leave,4);
end

procedure Node028
begin
   set_global_var(GVAR_TIPOFF_KILLER, 1);
Reply(1070);
BOption(1071,Node998,4);
BOption(1072,Node998,4);
BOption(1073,Node998,4);
BOption(1074,Node998,4);
BOption(1075,Node998,4);
BOption(1076,Node998,4);
end

procedure Leave begin

   call Node999;
   fadeout(1);
   set_obj_visibility(self_obj, 1);
   set_local_var(LVAR_Leave, 1);
   fadein(1);
end

//xxxxxxxxxxxxxxxxxxxx
