/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

#ifndef HDGATENR_H
#define HDGATENR_H

 // Map vars for HD Rim North Gate

 // Comments

//MAP_GLOBAL_VARS:

//GLOBAL                                        NUMBER

// All Map Vars need to start w/ MVAR_

#define MVAR_TAMPERED_CC_DOOR                           (0)
#define MVAR_COSTA_REPLACEMENT                          (1)
#define MVAR_FOUND_BOS_MENTION_COMPUTER                 (2)

#endif // HDGATENR_H
