/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

#ifndef SECRMAP_H
#define SECRMAP_H

 // Map vars for Random Shuttle

 // Comments

//MAP_GLOBAL_VARS:

//GLOBAL                                        NUMBER

// All Map Vars need to start w/ MVAR_

#define MVAR_Made_Car                           (0)
#define MVAR_CRANIUM_RATS_LEAVE                 (1)
#define MVAR_CRANIUM_RATS_TALKER                (2)

#endif // SECRMAP_H
