/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

#ifndef TBSRVC03_H
#define TBSRVC03_H

//MAP_GLOBAL_VARS:

//GLOBAL                                       NUMBER

//ALL Map Vars needed to start w/ MVAR_
#define MVAR_KNOW_CODES                          (0)
#define MVAR_SAT_SCORE                           (1)
#define MVAR_SAT_PRISONER13                      (2)
#define MVAR_SAT                                 (3)

#endif
