
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\party.h"
#include "..\headers\updatmap.h"
#include "..\headers\vehicles.h"

procedure start;
procedure map_enter_p_proc;
procedure map_exit_p_proc;
procedure map_update_p_proc;

/* Defines */
#define NAME                  SCRIPT_ABYSSEXT

procedure start begin
end

procedure map_enter_p_proc begin

   call Check_Create_Vehicle;

   if (not(is_loading_game)) then begin
      if (map_first_run) then begin
         display_mstr(100);
         override_map_start_hex(22934, 0, 0);
      end
   end

   fadein(1);
   Lighting;

   ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_STRONG_WIND), 1);
end

procedure map_exit_p_proc begin
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end

procedure map_update_p_proc begin
   Lighting;
end
