/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/*
        Name: Vehicle Desert
        Location: Vehicle outtapower
        Description: This is the vehicle outta power map script

        Log:
           Please note any changes that have been made to the file in Updated. Then comment
           the code which you have changed/altered/commented out. Please, do not delete any
           code which was written.

           Created: December 04, 1997

           Updated:
*/

/* Include Files */

/* Note, the Following Lines need to be in this order so that
   the script will be compilable. The define Name is referenced
   in a module from define.h and used in command.h. Please do
   not change the ordering.
        -rwh2   11/13/97
*/
#include "..\headers\define.h"
#include "..\headers\updatmap.h"

#define NAME                    SCRIPT_CARDESRT

#include "..\headers\command.h"
#include "..\headers\party.h"
#include "..\headers\vehicles.h"

procedure start;
procedure map_enter_p_proc;
procedure map_exit_p_proc;
procedure map_update_p_proc;

procedure start begin
end

procedure map_enter_p_proc begin

   // If you load the game, car_out_of_fuel will initially return a full gas tank value.
   // Probably a race condition issue but it corrects itself moments later
   if (car_out_of_fuel and (cur_map_index == MAP_VEHICLE_OUTTA_GAS)) then begin
      display_msg(mstr_worldmap(1502) + VehicleName(current_vehicle_type) + mstr_worldmap(1504));
   end

   override_map_start_hex(20100, 0, 0);

   call Check_Create_Vehicle;

   Lighting;
   fadein(1);

   ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_WASTELAND), 1);

end

procedure map_update_p_proc begin
   Lighting;
end

procedure map_exit_p_proc begin
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end
