/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/*
        Name: Vignette Sequence 2
        Location:
        Description:

        Log:
           Please note any changes that have been made to the file in Updated. Then comment
           the code which you have changed/altered/commented out. Please, do not delete any
           code which was written.

           Created: April 14, 1998

           Updated:
*/

/* Include Files */

/* Note, the Following Lines need to be in this order so that
   the script will be compilable. The define Name is referenced
   in a module from define.h and used in command.h. Please do
   not change the ordering.
        -rwh2   11/13/97
*/
#include "..\headers\define.h"
#include "..\headers\updatmap.h"
#include "..\headers\gammovie.h"

#define NAME                    SCRIPT_GAMMOVIE

#include "..\headers\command.h"
#include "..\headers\party.h"
#include "..\headers\vehicles.h"

procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;

procedure start begin
end

procedure map_exit_p_proc begin
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end


procedure map_enter_p_proc begin
   override_map_start_hex(24916,0,2);
   call Check_Create_Vehicle;

   fadein(1);

   Lighting;
   set_global_var(GVAR_LOAD_MAP_INDEX,0);

   ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_STRONG_WIND), 1);
end

procedure map_update_p_proc begin
   Lighting;
end
