/*******************************************************************************
        Name:
        Location:
        Description: Maps template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\party.h"
#include "..\headers\updatmap.h"
#include "..\headers\mvhounds.h"

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;


/* Defines */
#define NAME                  SCRIPT_MVHOUNDS


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/

export variable Hound_Wagon_Watcher_Ptr;

/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/

/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin
end

procedure map_enter_p_proc begin

   if (not(is_loading_game)) then begin
      if (map_first_run) then begin
         display_mstr(100);
      end
   end

   if (
      (global_var(GVAR_MESA_HOUNDS_RESOLUTION) == DEAL_WITH_HOUNDS_BLASTED) and
      (map_var(MVAR_Create_Crater) == 0)
   ) then begin
      set_map_var(MVAR_Create_Crater, 1);
      create_object(50335012, 20896, 0);
      destroy_object(tile_contains_pid_obj(21496, 0, PID_CAMPFIRE));
      destroy_object(tile_contains_pid_obj(20898, 0, PID_CAMPFIRE));
      destroy_object(tile_contains_pid_obj(20893, 0, PID_CAMPFIRE));
      destroy_object(tile_contains_pid_obj(20495, 0, PID_CIRCLE_OF_STONES_NORTH));
      destroy_object(tile_contains_pid_obj(21095, 0, PID_CIRCLE_OF_STONES_SOUTH));
   end
   else if (
      (global_var(GVAR_MESA_HOUNDS_RESOLUTION) == DEAL_WITH_HOUNDS_CRUSHED) and
      (map_var(MVAR_Create_Rockslide) == 0)
   ) then begin
      set_map_var(MVAR_Create_Rockslide, 1);
      Create_Cave_In(21095, 0, PID_CAVE_IN_ROCKS_OUTDOOR)
      Create_Cave_In(19098, 0, PID_CAVE_IN_ROCKS_OUTDOOR)
      Create_Cave_In(18083, 0, PID_CAVE_IN_ROCKS_OUTDOOR)
      Create_Cave_In(19694, 0, PID_CAVE_IN_ROCKS_OUTDOOR)
      Create_Cave_In(21508, 0, PID_CAVE_IN_ROCKS_OUTDOOR)
      Create_Cave_In(20866, 0, PID_CAVE_IN_ROCKS_OUTDOOR)
   end
   fadein(1);
   Lighting;

   ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_WIND_IN_THE_GRASS), 1);
end

procedure map_update_p_proc begin
   Lighting;
end

procedure map_exit_p_proc begin
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end
