/*******************************************************************************
        Name:
        Location:
        Description: Maps template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"

#include "..\headers\updatmap.h"

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;

/* Defines */
#define NAME                  SCRIPT_NY

procedure start begin
end

procedure map_enter_p_proc begin

    variable id;

    if (not(is_loading_game) and map_first_run) then begin
        set_pipboy_available(0);
        float_msg(dude_obj, g_mstr(923), FLOAT_MSG_WARNING);
        display_mstr(100);
    end

    fadein(1);
    Lighting;

    id := load_shader("SimTek.fx");
    set_global_var(GVAR_SHADER_ID, id);
    activate_shader(id);

    ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_WIND_IN_THE_GRASS), 1);

end

procedure map_update_p_proc begin
    Lighting;
end

procedure map_exit_p_proc begin
    stop_sfall_sound(ambient_sfx);
   fadeout(1);
end
