

#include "..\headers\define.h"
#include "..\headers\updatmap.h"

#define NAME                    SCRIPT_SETNTCLT

#include "..\headers\command.h"

procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;

procedure start begin
end


procedure map_enter_p_proc begin
   fadein(1);
   Cavern_Lighting;

   if (not(is_loading_game)) then begin
      override_map_start_hex(28906, 0, 5);
   end

   ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_MOLECH_TEMPLE), 1);
end

procedure map_update_p_proc begin
   Cavern_Lighting;
end


procedure map_exit_p_proc begin
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end
