/*******************************************************************************
        Name:
        Location:
        Description: Maps template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\party.h"
#include "..\headers\updatmap.h"
#include "..\headers\vehicles.h"

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;
procedure timed_event_p_proc;


/* Defines */
#define NAME                  SCRIPT_TBBRCH1


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin
   add_timer_event(self_obj, game_ticks(10), 1);
end

procedure map_enter_p_proc begin
   variable line;

   if (morning or day) then
      line = 100;
   else if (evening or night) then
      line = 101;

   if (
      not(is_loading_game) and
      map_first_run and
      (global_var(GVAR_CONVICT) == 1)
      ) then begin
      display_msg(mstr(line) + " " + mstr(102));
      set_global_var(GVAR_CONVICT, 0);
      set_global_var(GVAR_ESCAPED_CONVICT, 1);
      set_global_var(GVAR_QUEST_ESCAPE_TIBBETS, 2);
      set_global_var(GVAR_TIBBETS_BATTALION_ATTACK, 2);
      give_xp(1000);
   end

   call Check_Create_Vehicle;

   fadein(1);
   Lighting;

   ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_WASTELAND), 1);
end

procedure map_update_p_proc begin

   Lighting;

end

procedure map_exit_p_proc begin
   stop_sfall_sound(ambient_sfx);
   fadeout(1);
end

procedure timed_event_p_proc begin
   if(day and not(dude_wearing_power_armor) and not(dude_wearing_environmental_armor) and (cur_map_index == MAP_TIBBETS_BREACH_VALKYRIE)) then begin
      display_mstr(103);
      critter_dmg(dude_obj, random(1, 4), DMG_fire);
      add_timer_event(self_obj, game_ticks(10), 1);
      // TODO HARM PARTY TOO
   end
end
