/*******************************************************************************
        Name:
        Location:
        Description: Maps template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"

#include "..\headers\updatmap.h"
#include "..\headers\vault8.h"

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;

/* Defines */
#define NAME                  SCRIPT_VAULT8

export variable vault_dri_ptr;

procedure start begin
end

procedure map_enter_p_proc begin

   fadein(1);

   if(map_var(MVAR_POWER) == 1) then begin
       Full_Light;
   end else begin
       Darkness;

    if not(is_loading_game) then begin
       if (map_first_run) then begin
            display_mstr(100);
            give_xp(250);
            set_global_var(GVAR_QUEST_REACH_VAULT_ENTRANCE, 2);
            if(global_var(GVAR_QUEST_LOOT_RED_BRICK_BUILDING) == 1) then begin
                set_global_var(GVAR_QUEST_LOOT_RED_BRICK_BUILDING, 2);
            end
            play_sfx("SIMTEK6");
            display_mstr(105);
        end
    end

   end

   ambient_sfx := play_sfall_sound(AmbientTrack(AMBIENT_HIGH_TECH), 1);
end

procedure map_update_p_proc begin
   if(map_var(MVAR_POWER) == 1) then begin
       Full_Light;
   end else begin
       Darkness;
   end
end

procedure map_exit_p_proc begin
    stop_sfall_sound(ambient_sfx);
    fadeout(1);
end
