#include "..\headers\define.h"
#include "..\headers\command.h"

procedure start;
procedure description_p_proc;
procedure map_enter_p_proc;
procedure use_p_proc;

/* Defines */
#define NAME                  SCRIPT_VCDRI

procedure start begin
end

procedure description_p_proc begin
   display_mstr(100);
end

procedure map_enter_p_proc begin
   if (obj_is_open(self_obj)) then begin
      use_obj(self_obj);
   end
end

procedure use_p_proc begin
   if (source_obj == dude_obj) then begin
      script_overrides;
      call description_p_proc;
   end
end
