/*

        Name:           Horatio
        Location:       Sandover
        Description:    Trader

           Created: 23/01/2021 11:48:40

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_REHORATI

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_RESERVATION)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure Horatio_Bax_Barter;




// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Horatio_0;
procedure Horatio_1a_1;
procedure Horatio_1a_2a;
procedure Horatio_1a_2b_1;
procedure Horatio_1a_2b_2a;
procedure Horatio_1a_2b_2b;
procedure Horatio_1b;
procedure Horatio_1c;
procedure Horatio_1D_1;
procedure Horatio_1D_2;
procedure Horatio_1D_3;
procedure Horatio_2_1;
procedure Horatio_2_2;
procedure Horatio_2_3a_1;
procedure Horatio_2_3a_2;
procedure Horatio_2_3b;
procedure Horatio_2_4;
procedure Horatio_2_5a;
procedure Horatio_2_5b;
procedure Horatio_2_6_1;
procedure Horatio_2_6_2;
procedure Horatio_2_7a;
procedure Horatio_2_7b_1;
procedure Horatio_2_7b_2;
procedure Horatio_2_7c;
procedure Horatio_2_7d;
procedure Horatio_2_7e;
procedure Horatio_3_0;
procedure Horatio_3a_1;
procedure Horatio_3a_2;
procedure Horatio_3b_1;
procedure Horatio_3b_2a;
procedure Horatio_3b_2b;
procedure Horatio_3b_3;
procedure Horatio_3b_4;
procedure Horatio_4_0;
procedure Horatio_4a_1;
procedure Horatio_4a_2;
procedure Horatio_4a_3a_1;
procedure Horatio_4a_3a_2;
procedure Horatio_4a_3b;
procedure Horatio_4a_3c;
procedure Horatio_4a_3d;
procedure Horatio_4b_1;
procedure Horatio_4b_2;
procedure Horatio_4b_3a;
procedure Horatio_4b_3b;
procedure Horatio_5_1;
procedure Horatio_5_2;
procedure Horatio_5_3;
procedure Horatio_5_4;
procedure Horatio_5_5;
procedure Horatio_5_6a;
procedure Horatio_5_6b;
procedure Horatio_6_1;
procedure Horatio_6_2a;
procedure Horatio_6_2b;
procedure Horatio_6_3;
procedure Horatio_6_4;
procedure Horatio_6_5;
procedure Horatio_7_1;
procedure Horatio_7_2;
procedure Horatio_8a_1;
procedure Horatio_8a_2a;
procedure Horatio_8a_2b;
procedure Horatio_8a_3;
procedure Horatio_8a_4;
procedure Horatio_8a_5a;
procedure Horatio_8a_5b;
procedure Horatio_8a_6;
procedure Horatio_8a_7;
procedure Horatio_8a_8;
procedure Horatio_8b_1;
procedure Horatio_8b_2;
procedure Horatio_8c;
procedure Horatio_9_1a;
procedure Horatio_9_1b;
procedure Horatio_9_2a;
procedure Horatio_9_2b;
procedure Horatio_9_2c;
procedure Horatio_9_2d;
procedure Horatio_Trade;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)

variable Horatio_Bax_Agree := 0;
variable Horatio_Bax_Money_Find := 0;
variable Horatio_Bax_Price_Mod := 0;
variable Horatio_Friendly := 0;
variable Horatio_Temper := 0;


/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_RESERVATION);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=1;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
 /*  call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;
       call Horatio_0;*/

if(dude_is_female) then
floater(231);
else
floater(230);

     /*  gSay_End;
       end_dialogue;


   call restore_idiot_savant_int;*/

end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_evil_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

procedure Horatio_Bax_Barter begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_BARTER, -25);
if is_success(roll_temp) then
begin
call Horatio_2_7b_1;
end
else begin
call Horatio_2_7c;
 end
end





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Horatio_0
begin
Reply(200);
NOption(201,Horatio_1a_1,4);
NOption(202,Horatio_1b,4);
NOption(203,Horatio_1c,4);
end

procedure Horatio_1a_1
begin
if (dude_is_male) then Reply(230); else
if (dude_is_female) then Reply(231);
GOption(mstr(232)+dude_name+mstr(233),Horatio_1a_2a,4);
if (dude_is_female) then
GOption(234,Horatio_1a_2a,4);
NOption(235,Horatio_1a_2b_1,4);
BOption(236,Horatio_7_1,4);
// NOTE: Dumb player option.
NOption(237,Horatio_1D_1,-3);
NOption(238,Node999,4);
end

// Node Horatio_1a_2a
//
// Notes:
//
// Increment the variable Horatio_Friendly by 1.

procedure Horatio_1a_2a
begin
if (dude_is_male) then Reply(mstr(260)+dude_name+mstr(261)); else
if (dude_is_female) then Reply(262);
GOption(263,Horatio_Trade,4);
NOption(264,Horatio_5_3,4);
NOption(265,Horatio_4a_1,4);
NOption(266,Horatio_4b_1,4);
NOption(267,Node999,4);
end

procedure Horatio_1a_2b_1
begin
Reply(290);
NOption(291,Horatio_1a_2b_2a,4);
NOption(292,Horatio_1a_2b_2b,4);
NOption(293,Node999,4);
end

procedure Horatio_1a_2b_2a
begin
Reply(320);
NOption(321,Horatio_Trade,4);
NOption(292,Horatio_1a_2b_2b,4);
NOption(322,Node999,4);
end

procedure Horatio_1a_2b_2b
begin
Reply(350);
// NOTE: This option only appears if the PC has agreed to help Rolf and Felix Baxter to leave Sandover.
NOption(351,Horatio_2_1,4);
NOption(291,Horatio_1a_2b_2a,4);
NOption(352,Horatio_4a_1,4);
NOption(266,Horatio_4b_1,4);
NOption(293,Node999,4);
end

// Node Horatio_1b
//
// Notes:
//
// This node begins the conversation if the variable Jed_Friendly=0

procedure Horatio_1b
begin
Reply(380);
NOption(381,Horatio_Trade,4);
NOption(382,Horatio_9_1a,4);
// NOTE: This option only appears once the player has spoken to Alexander about Horatio's exorbitant prices. If the PC has already tried to convince Horatio to ply another trade route and failed, go to Horatio 8b_1 instead.
NOption(383,Horatio_8a_1,4);
// NOTE: This option only appears if the PC has agreed to help Rolf and Felix Baxter to leave Sandover.
NOption(351,Horatio_2_1,4);
// NOTE: If Horatio_Temper>3, go to Horatio_7_2 instead.
BOption(384,Horatio_7_1,4);
NOption(385,Node999,4);
end

// Node Horatio_1c
//
// Notes:
//
// This node begins the conversation if the variable Jed_Friendly>0

procedure Horatio_1c
begin
Reply(mstr(410)+dude_name+mstr(411));
NOption(412,Horatio_Trade,4);
NOption(413,Horatio_9_1a,4);
// NOTE: This option only appears once the player has spoken to Alexander about Horatio's exorbitant prices. If the PC has already tried to convince Horatio to ply another trade route and failed, go to Horatio 8b_1 instead.
NOption(383,Horatio_8a_1,4);
// NOTE: This option only appears if the PC has agreed to help Rolf and Felix Baxter to leave Sandover.
NOption(351,Horatio_2_1,4);
// NOTE: If Horatio_Temper>3, go to Horatio_7_2 instead.
BOption(384,Horatio_7_1,4);
NOption(414,Node999,4);
end

// Node Horatio_1D_1
//
// Notes:
//
// The Horatio_1D* path is for dumb PCs.

procedure Horatio_1D_1
begin
Reply(440);
NOption(441,Horatio_1D_2,-3);
NOption(442,Node999,-3);
end

procedure Horatio_1D_2
begin
Reply(470);
NOption(471,Horatio_1D_3,-3);
end

procedure Horatio_1D_3
begin
Reply(500);
NOption(501,Node999,-3);
NOption(502,Node999,-3);
end

// Node Horatio_2_1
//
// Notes:
//
// The Horatio_2* path is where the PC can ask Horatio to take the Baxter Boys, Rolf and Felix, with his caravan, the next time it goes to Crossroads.

procedure Horatio_2_1
begin
Reply(530);
NOption(531,Horatio_2_2,4);
NOption(532,Horatio_9_1a,4);
NOption(533,Node999,4);
end

procedure Horatio_2_2
begin
Reply(560);
NOption(561,Horatio_2_3a_1,4);
NOption(562,Horatio_2_3b,4);
NOption(532,Horatio_9_1a,4);
NOption(533,Node999,4);
end

procedure Horatio_2_3a_1
begin
Reply(590);
NOption(591,Horatio_2_3b,4);
NOption(592,Horatio_2_3a_2,4);
NOption(532,Horatio_9_1a,4);
NOption(533,Node999,4);
end

// Node Horatio_2_3a_2
//
// Notes:
//
// Increment the variable Horatio_Bax_Price_Mod by 1.

procedure Horatio_2_3a_2
begin
Reply(620);
NOption(621,Horatio_2_4,4);
NOption(532,Horatio_9_1a,4);
NOption(533,Node999,4);
end

procedure Horatio_2_3b
begin
Reply(650);
NOption(621,Horatio_2_4,4);
NOption(532,Horatio_9_1a,4);
NOption(533,Node999,4);
end

procedure Horatio_2_4
begin
Reply(680);
NOption(681,Horatio_2_5a,4);
if (get_critter_stat(dude_obj,STAT_iq)>=6) then
NOption(682,Horatio_2_5b,4);
NOption(532,Horatio_9_1a,4);
NOption(533,Node999,4);
end

procedure Horatio_2_5a
begin
Reply(710);
NOption(711,Horatio_0,4);
NOption(532,Horatio_9_1a,4);
NOption(533,Node999,4);
end

procedure Horatio_2_5b
begin
if (dude_is_male) then Reply(740); else
if (dude_is_female) then Reply(741);
NOption(711,Horatio_2_6_1,4);
NOption(532,Horatio_9_1a,4);
NOption(533,Node999,4);
end

procedure Horatio_2_6_1
begin
Reply(770);
NOption(771,Horatio_2_6_2,4);
end

// Node Horatio_2_6_2
//
// Notes:
//
// VARIABLE = [[1 + Horatio_Bax_Price_Mod] * 1000] - [100 - PC's barter skill]\

procedure Horatio_2_6_2
begin
Reply(800);
// NOTE: IF the PC cannot afford to pay, go to Horatio_2_7d instead.
NOption(801,Horatio_2_7a,4);
// NOTE: IF the PC passes the barter skill check but cannot afford to pay half of VARIABLE, go to Horatio_2_7d instead.
//VARIABLE = [[1 + Horatio_Bax_Price_Mod] * 1000] - [100 - PC's barter skill]
NOption(802,Horatio_Bax_Barter,4);
NOption(803,Horatio_2_7e,4);
NOption(532,Horatio_9_1a,4);
NOption(533,Node999,4);
end

// Node Horatio_2_7a
//
// Notes:
//
// Deduct VARIABLE caps from the PC's inventory. VARIABLE = [[1 + Horatio_Bax_Price_Mod] * 1000] - [100 - PC's barter skill]\

procedure Horatio_2_7a
begin
Reply(830);
NOption(831,Node999,4);
NOption(832,Node999,4);
end

procedure Horatio_2_7b_1
begin
Reply(860);
NOption(861,Horatio_2_7b_2,4);
NOption(532,Horatio_9_1a,4);
NOption(862,Node999,4);
end

// Node Horatio_2_7b_2
//
// Notes:
//
// Deduct half of VARIABLE caps from the PC's inventory. VARIABLE = [[1 + Horatio_Bax_Price_Mod] * 1000] - [100 - PC's barter skill]\

procedure Horatio_2_7b_2
begin
Reply(890);
NOption(891,Node999,4);
NOption(832,Node999,4);
end

// Node Horatio_2_7c
//
// Notes:
//
// VARIABLE = [[1 + Horatio_Bax_Price_Mod] * 1000] - [100 - PC's barter skill]\

procedure Horatio_2_7c
begin
Reply(920);
NOption(801,Horatio_2_7a,4);
NOption(532,Horatio_9_1a,4);
NOption(803,Horatio_2_7e,4);
NOption(533,Node999,4);
end

procedure Horatio_2_7d
begin
Reply(950);
NOption(532,Horatio_9_1a,4);
NOption(803,Horatio_2_7e,4);
NOption(533,Node999,4);
end

// Node Horatio_2_7e
//
// Notes:
//
// VARIABLE = [[1 + Horatio_Bax_Price_Mod] * 1000] - [100 - PC's barter skill]\

procedure Horatio_2_7e
begin
Reply(980);
NOption(981,Horatio_9_1a,4);
NOption(982,Node999,4);
end

// Node Horatio_3_0
//
// Notes:
//
// The Horatio_3* path is where the PC can find out what Horatio thinks about Kelly and Brute. Horatio also lets slip about Brute's drink problem.

procedure Horatio_3_0
begin
Reply(1010);
NOption(1011,Horatio_3a_1,4);
NOption(1012,Horatio_9_1a,4);
NOption(1013,Node999,4);
end

procedure Horatio_3a_1
begin
if (dude_is_male) then Reply(1040); else
if (dude_is_female) then Reply(1041);
if (dude_is_male) then
NOption(1042,Horatio_3a_2,4);
NOption(1043,Horatio_3b_1,4);
NOption(1044,Horatio_9_1a,4);
NOption(1045,Node999,4);
end

procedure Horatio_3a_2
begin
Reply(1070);
NOption(1043,Horatio_3b_1,4);
NOption(1071,Horatio_9_1a,4);
NOption(1045,Node999,4);
end

procedure Horatio_3b_1
begin
Reply(1100);
NOption(1101,Horatio_3b_2b,4);
NOption(1102,Horatio_3b_2a,4);
NOption(1103,Horatio_9_1a,4);
NOption(1104,Node999,4);
end

procedure Horatio_3b_2a
begin
Reply(1130);
NOption(1131,Horatio_3b_2b,4);
NOption(1132,Horatio_9_1a,4);
end

procedure Horatio_3b_2b
begin
Reply(1160);
NOption(1161,Horatio_3b_3,4);
end

procedure Horatio_3b_3
begin
Reply(1190);
NOption(1191,Horatio_3b_4,4);
NOption(1192,Horatio_9_1a,4);
NOption(1193,Node999,4);
end

procedure Horatio_3b_4
begin
Reply(1220);
NOption(1221,Horatio_9_1a,4);
// NOTE: If Horatio_Temper>3, go to Horatio_7_2 instead.
BOption(1222,Horatio_7_1,4);
NOption(1223,Node999,4);
end

// Node Horatio_4_0
//
// Notes:
//
// The Horatio_4* path is where the PC can find out a few bits of information about Sandover and Crossroads. Horatio will also sell the Pipboy location of Crossroads.

procedure Horatio_4_0
begin
Reply(1250);
NOption(352,Horatio_4a_1,4);
BOption(1251,Horatio_4b_1,4);
NOption(1252,Node999,4);
end

procedure Horatio_4a_1
begin
Reply(1280);
NOption(1281,Horatio_4a_2,4);
NOption(1282,Node999,4);
end

// Node Horatio_4a_2
//
// Notes:
//
// VARIABLE = 3 * [Horatio_Temper+1] * [100-PC's barter skill]. Divide the final sum by half IF the variable Horatio_Friendly>0. Round up the final value. Maybe set a maximum price of 500 caps and a minimum of 100.

procedure Horatio_4a_2
begin
if (dude_is_male) then Reply(1310); else
if (dude_is_female) then Reply(1311);
// NOTE: Subtract the appropriate amount from the PC's caps.
//
//IF the PC cannot pay, go instead to Horatio_4a_3d.
NOption(1312,Horatio_4a_3a_1,4);
// NOTE: Barter check.
//If the PC succeeds, subtract the appropriate amount from the PC's caps.
//IF the PC succeeds but cannot pay, go instead to Horatio_4a_3b.
//If the PC fails, go to Horatio_4a_3d instead.
//
NOption(1313,Horatio_4a_3a_1,4);
NOption(1314,Horatio_4a_3c,4);
NOption(1315,Horatio_4b_1,4);
NOption(1316,Horatio_Trade,4);
NOption(1317,Horatio_9_2a,4);
end

procedure Horatio_4a_3a_1
begin
Reply(1340);
NOption(1341,Horatio_4a_3a_2,4);
end

procedure Horatio_4a_3a_2
begin
if (dude_is_male) then Reply(1370); else
if (dude_is_female) then Reply(1371);
NOption(1372,Horatio_5_3,4);
NOption(1373,Horatio_6_1,4);
NOption(1374,Horatio_9_1a,4);
NOption(1375,Node999,4);
end

// Node Horatio_4a_3b
//
// Notes:
//
// *VARIABLE* is the sum quoted previously, in Horatio_4a_2. Increment Horatio_Temper by 1.

procedure Horatio_4a_3b
begin
Reply(1400);
// NOTE: Subtract *VARIABLE* from the PC's caps.
NOption(1401,Horatio_4a_3a_1,4);
NOption(1314,Horatio_4a_3c,4);
NOption(1316,Horatio_Trade,4);
NOption(1317,Horatio_9_2a,4);
end

procedure Horatio_4a_3c
begin
if (dude_is_male) then Reply(1430); else
if (dude_is_female) then Reply(1431);
NOption(1432,Horatio_9_1a,4);
// NOTE: If Horatio_Temper>3 go to Horatio_7_2 instead.
NOption(1433,Horatio_7_1,4);
NOption(1434,Node999,4);
end

// Node Horatio_4a_3d
//
// Notes:
//
// Increment Horatio_temper by 1

procedure Horatio_4a_3d
begin
if (dude_is_male) then Reply(1460); else
if (dude_is_female) then Reply(1461);
NOption(1462,Horatio_Trade,4);
NOption(442,Node999,4);
end

procedure Horatio_4b_1
begin
Reply(1490);
BOption(1491,Horatio_4b_2,4);
end

procedure Horatio_4b_2
begin
Reply(1520);
NOption(1521,Horatio_4b_3a,4);
NOption(1522,Horatio_4b_3b,4);
NOption(1523,Horatio_Trade,4);
end

procedure Horatio_4b_3a
begin
Reply(1550);
BOption(1522,Horatio_4b_3b,4);
NOption(1551,Horatio_Trade,4);
NOption(352,Horatio_4a_1,4);
NOption(1552,Horatio_9_2a,4);
end

procedure Horatio_4b_3b
begin
if (dude_is_male) then Reply(1580); else
if (dude_is_female) then Reply(1581);
NOption(1582,Horatio_4b_3a,4);
NOption(1583,Horatio_Trade,4);
NOption(1584,Horatio_4a_1,4);
NOption(1585,Horatio_9_2a,4);
end

// Node Horatio_5_1
//
// Notes:
//
// The Horatio_5* path is where the PC can convince Horatio that he should try working for another caravan route, instead of bleeding Sandover dry. The PC can get the quest to find alternative employment for Horatio.

procedure Horatio_5_1
begin
Reply(1610);
NOption(1611,Horatio_5_2,4);
NOption(1612,Horatio_9_1a,4);
end

procedure Horatio_5_2
begin
Reply(1640);
NOption(1641,Horatio_5_3,4);
NOption(1642,Horatio_9_1a,4);
NOption(1643,Node999,4);
end

procedure Horatio_5_3
begin
if (dude_is_male) then Reply(1670); else
if (dude_is_female) then Reply(1671);
NOption(1672,Horatio_5_4,4);
NOption(1673,Horatio_9_1a,4);
NOption(1674,Node999,4);
end

procedure Horatio_5_4
begin
Reply(1700);
// NOTE: Only display this node if Horatio has spoken node Horatio_4b_3b.
NOption(1701,Horatio_5_5,4);
NOption(1702,Horatio_5_5,4);
end

procedure Horatio_5_5
begin
Reply(1730);
NOption(1731,Horatio_5_6a,4);
NOption(1732,Horatio_5_6b,4);
NOption(1733,Horatio_3a_1,4);
NOption(1734,Node999,4);
end

procedure Horatio_5_6a
begin
Reply(1760);
NOption(1761,Horatio_5_6b,4);
NOption(1762,Horatio_3_0,4);
NOption(1763,Horatio_9_1a,4);
end

procedure Horatio_5_6b
begin
Reply(1790);
NOption(1791,Horatio_3a_1,4);
NOption(1792,Horatio_9_1a,4);
NOption(1793,Node999,4);
end

// Node Horatio_6_1
//
// Notes:
//
// The Horatio_6* path is where the PC can ask to join Horatio the next time the caravan makes the run to Sandover.

procedure Horatio_6_1
begin
Reply(1820);
// NOTE: Subtract Horatio_Temper from Charisma and make a 1-to-10 'roll'. If failed, go to Horatio_6_2b instead.
NOption(771,Horatio_6_2a,4);
end

procedure Horatio_6_2a
begin
Reply(1850);
NOption(1851,Horatio_6_3,4);
NOption(1852,Node999,4);
end

procedure Horatio_6_2b
begin
Reply(1880);
NOption(1881,Horatio_9_1a,4);
NOption(1882,Horatio_7_1,4);
NOption(1883,Node999,4);
end

procedure Horatio_6_3
begin
Reply(1910);
NOption(1911,Horatio_6_4,4);
NOption(1912,Horatio_9_1a,4);
NOption(1913,Node999,4);
end

procedure Horatio_6_4
begin
Reply(1940);
NOption(1941,Horatio_6_5,4);
NOption(1942,Horatio_9_1a,4);
NOption(1943,Node999,4);
end

procedure Horatio_6_5
begin
Reply(1970);
NOption(1971,Node999,4);
NOption(1972,Horatio_9_1b,4);
NOption(1973,Node999,4);
end

// Node Horatio_7_1
//
// Notes:
//
// The Horatio_7* path is where the conversation is routed if the PC is rude to Horatio.\

procedure Horatio_7_1
begin
if (dude_is_male) then Reply(2000); else
if (dude_is_female) then Reply(2001);
BOption(2002,Horatio_Trade,4);
BOption(2003,Horatio_7_2,4);
end

procedure Horatio_7_2
begin
if (dude_is_male) then Reply(2030); else
if (dude_is_female) then Reply(2031);
BOption(2032,Node998,4);
BOption(2033,Node998,4);
end

// Node Horatio_8a_1
//
// Notes:
//
// The Horatio_8* path is where the PC tries to convince Horatio that he should consider running with another caravan group.

procedure Horatio_8a_1
begin
Reply(2060);
// NOTE: Easy speech check. If failed, go to Horatio_8c instead.
//Wrong choice. (Defensive and weak). Punishment is another node with a speech check.
NOption(2061,Horatio_8a_2b,4);
// NOTE: Easy speech check. If failed, go to Horatio_8c instead.
//This is the correct choice (forthright, no-nonsense). Reward is bypassing another node with a speech check.
NOption(2062,Horatio_8a_2a,4);
end

procedure Horatio_8a_2a
begin
Reply(2090);
// NOTE: Easy speech check. If failed, go to Horatio_8c instead.
//Correct response. (Sympathetic to Horatio's plight).
NOption(2091,Horatio_8a_3,4);
// NOTE: Wrong response. (Smug, ambivalent). Moderate speech test. If the PC fails, route Horatio's response to Horatio_8c instead.
NOption(2092,Horatio_8a_3,4);
end

procedure Horatio_8a_2b
begin
Reply(2120);
// NOTE: Easy speech check. If failed, go to Horatio_8c instead.
BOption(2121,Horatio_8a_2a,4);
end

procedure Horatio_8a_3
begin
Reply(2150);
// NOTE: Easy speech test. If the PC fails, route Horatio's response to Horatio_8c instead.
NOption(2151,Horatio_8a_4,4);
end

procedure Horatio_8a_4
begin
Reply(2180);
// NOTE: Wrong choice. (Shows lack of experience). Punishment is another node with a speech test.
//Easy speech test. If failed, go to Horatio_8c instead.
NOption(2181,Horatio_8a_5b,4);
// NOTE: Correct choice (to the point and decisive)
//Easy speech test. If the PC fails, route Horatio's response to Horatio_8c instead.
NOption(2182,Horatio_8a_5a,4);
end

procedure Horatio_8a_5a
begin
Reply(2210);
// NOTE: Easy speech test at this point. If the PC fails, route Horatio's response to Horatio_8c instead.
NOption(2211,Horatio_8a_6,4);
end

procedure Horatio_8a_5b
begin
Reply(2240);
// NOTE: Easy speech test. If the PC fails, route Horatio's response to Horatio_8c instead.
NOption(2241,Horatio_8a_5a,4);
end

procedure Horatio_8a_6
begin
Reply(2270);
NOption(2271,Horatio_8a_7,4);
end

procedure Horatio_8a_7
begin
Reply(2300);
NOption(2301,Horatio_8a_8,4);
NOption(2302,Node999,4);
end

// Node Horatio_8a_8
//
// Notes:
//
// The PC gains the mission where he must go to Crossroads to find a new route for Horatio. Decrement Horatio_Temper by 1.

procedure Horatio_8a_8
begin
Reply(2330);
// NOTE: If the player clicks this option, he gets the mission to find a new trade route for Horatio.
NOption(2331,Horatio_6_1,4);
// NOTE: If the player clicks this option, he gets the mission to find a new trade route for Horatio.
NOption(2332,Horatio_9_1b,4);
NOption(2333,Node999,4);
end

// Node Horatio_8b_1
//
// Notes:
//
// Increment Horatio_Temper by 1.

procedure Horatio_8b_1
begin
Reply(2360);
// NOTE: Hard speech check. If failed, go to Horatio_8b_2 instead.
NOption(2361,Horatio_8a_1,4);
NOption(2362,Horatio_9_1a,4);
// NOTE: If Horatio_Temper>3, go to Horatio_7_2 instead.
NOption(2363,Horatio_7_1,4);
NOption(2364,Node999,4);
end

// Node Horatio_8b_2
//
// Notes:
//
// Increment Horatio_Temper by 1

procedure Horatio_8b_2
begin
Reply(2390);
// NOTE: Hard speech check. If the PC fails, go to Horatio_7_1 instead.
NOption(2391,Horatio_8a_1,4);
NOption(2392,Horatio_9_1a,4);
// NOTE: If Horatio_Temper>3, go to Horatio_7_2 instead.
BOption(2393,Horatio_7_1,4);
NOption(2364,Node999,4);
end

// Node Horatio_8c
//
// Notes:
//
// Increment Horatio_Temper by 1.

procedure Horatio_8c
begin
if (dude_is_male) then Reply(2420); else
if (dude_is_female) then Reply(2421);
NOption(2422,Horatio_9_1a,4);
// NOTE: If Horatio_Temper>3, go to Horatio_7_2 instead.
NOption(2423,Horatio_7_1,4);
NOption(2424,Node999,4);
end

// Node Horatio_9_1a
//
// Notes:
//
// The Horatio_8* path is the generic 'can I ask you a question?' path. Horatio charges for the privelidge, though!\

procedure Horatio_9_1a
begin
if (dude_is_male) then Reply(2450); else
if (dude_is_female) then Reply(2451);
// NOTE: Subtract VARIABLE from the PC's caps.
//
//IF the PC cannot pay, go instead to Horatio_9_2d.
NOption(1312,Horatio_9_2a,4);
// NOTE: Barter check.
//If the PC succeeds, subtract half of VARIABLE from the PC's caps. Round up the halving of the amount of caps.
//IF the PC succeeds but cannot pay, go instead to Horatio_9_2d.
//If the PC fails, go to Horatio_9_2b instead.
NOption(2452,Horatio_9_2a,4);
NOption(1314,Horatio_9_2c,4);
NOption(1316,Horatio_Trade,4);
NOption(2453,Node999,4);
end

procedure Horatio_9_1b
begin
Reply(2480);
NOption(2481,Horatio_Trade,4);
NOption(2482,Horatio_3_0,4);
NOption(2483,Horatio_4_0,4);
// NOTE: This option only appears once the player has spoken to Alexander about Horatio's exorbitant prices. If the PC has already tried to convince Horatio to ply another trade route and failed, go to Horatio 8b_1 instead.
NOption(383,Horatio_8a_1,4);
// NOTE: This option only appears if the PC has agreed to help Rolf and Felix Baxter to leave Sandover.
NOption(351,Horatio_2_1,4);
BOption(2484,Horatio_7_1,4);
NOption(2485,Node999,4);
end

procedure Horatio_9_2a
begin
Reply(2510);
NOption(2481,Horatio_Trade,4);
NOption(2482,Horatio_3_0,4);
NOption(2483,Horatio_4_0,4);
// NOTE: This option only appears once the player has spoken to Alexander about Horatio's exorbitant prices. If the PC has already tried to convince Horatio to ply another trade route and failed, go to Horatio 8b_1 instead.
NOption(383,Horatio_8a_1,4);
// NOTE: This option only appears if the PC has agreed to help Rolf and Felix Baxter to leave Sandover.
NOption(351,Horatio_0,4);
// NOTE: If Horatio_Temper>3, go to Horatio_7_2 instead.
BOption(2484,Horatio_7_1,4);
NOption(2485,Node999,4);
end

// Node Horatio_9_2b
//
// Notes:
//
// VARIABLE CAPS is the sum quoted previously, in Horatio_9_1. Increment Horatio_Temper by 1.

procedure Horatio_9_2b
begin
if (dude_is_male) then Reply(2540); else
if (dude_is_female) then Reply(2541);
// NOTE: Subtract *VARIABLE* caps from the PC's inventory. *VARIABLE* is quoted in Horatio_9_1a.
NOption(2542,Horatio_9_2a,4);
NOption(1314,Horatio_9_2c,4);
NOption(1316,Horatio_Trade,4);
NOption(2543,Node999,4);
end

procedure Horatio_9_2c
begin
Reply(2570);
NOption(2571,Horatio_Trade,4);
// NOTE: If Horatio_Temper>3, go to Horatio_7_2 instead.
NOption(2572,Horatio_7_1,4);
NOption(2573,Node999,4);
end

// Node Horatio_9_2d
//
// Notes:
//
// Increment Horatio_Temper by 1

procedure Horatio_9_2d
begin
Reply(2600);
NOption(2601,Horatio_Trade,4);
NOption(2602,Horatio_7_2,4);
NOption(2603,Node999,4);
end

procedure Horatio_Trade
begin
Reply(2630);
NOption(2631,Horatio_5_1,4);
// NOTE: This option only appears once the player has spoken to Alexander about Horatio's exorbitant prices. If the PC has already tried to convince Horatio to ply another trade route and failed, go to Horatio 8b_1 instead.
NOption(2632,Horatio_8a_1,4);
NOption(2633,Horatio_9_1a,4);
// NOTE: If Horatio_Temper>3, go to Horatio_7_2 instead.
BOption(2634,Horatio_7_1,4);
NOption(2635,Node999,4);
end



//xxxxxxxxxxxxxxxxxxxx
