/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/*
        Name: Hal, Drive Leader in NCR
        Location: NCR Map 3 and Some map in Redding.
        Description: He is the leader of the cattle drive.

        Log:
           Please note any changes that have been made to the file in Updated. Then comment
           the code which you have changed/altered/commented out. Please, do not delete any
           code which was written.

           Created:

           Updated:
*/

/* Include Files */

/* Note, the Following Lines need to be in this order so that
   the script will be compilable. The define Name is referenced
   in a module from define.h and used in command.h. Please do
   not change the ordering.
        -rwh2   11/13/97
*/
#include "..\headers\define.h"

#define NAME                    SCRIPT_HDCM
#define TOWN_REP_VAR         GVAR_TOWN_REP_HOOVER_DAM

#define ENDSTRING              (g_mstr(350))
#define ENDOPTION              NOption(ENDSTRING, Node999, 0)

#include "..\headers\command.h"
#include "..\headers\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\headers\caravan.h"

/* Standard Script Procedures */
procedure start;
procedure map_update_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_exit_p_proc;
procedure combat_p_proc;

/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending


// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;

procedure checkLoadConditions;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Vis                        (7)
#define LVAR_Called_Clear               (8) //added by killap
#define LVAR_Off_Course                 (9)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;
variable Node1Rep := 0;

#define CURRENT_CARAVAN       (SetupCurrentCaravanForCaravanMaster)

procedure combat_p_proc begin
   if (not self_visible) then
      script_overrides;
end

procedure start begin
end

procedure timed_event_p_proc begin
   if( fixed_param == 1 ) then begin
      if (obj_is_visible_flag(self_obj)) then begin
         if((global_var(GVAR_CARAVAN_START_TIME) > 0) and (((game_time - global_var(GVAR_CARAVAN_START_TIME)) / ONE_GAME_DAY) >= (CARAVAN_RUN_DAYS_HOOVER_DAM_JERICHO * 2))) then
            floater_bad(120);
         else if((global_var(GVAR_CARAVAN_START_TIME) > 0) and (((game_time - global_var(GVAR_CARAVAN_START_TIME)) / ONE_GAME_DAY) > (CARAVAN_RUN_DAYS_HOOVER_DAM_JERICHO + ONE_GAME_WEEK))) then
            floater_bad(119);
         else
            float_msg(self_obj,g_mstr(450),FLOAT_COLOR_NORMAL);
      end
      add_timer_event( self_obj, game_ticks(10), 1 );
   end
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;

   if (cur_town == caravan_end) then begin
      switch_team(self_obj,TEAM_HOOVER_DAM)
   end
   else begin
      switch_team(self_obj,TEAM_PLAYER)
   end

   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_TOUGH_MERCHANT);
   if (is_loading_game == FALSE) then begin
      call checkLoadConditions;
   end
end

//added by killap
procedure map_update_p_proc begin
   if (
      (not(is_loading_game)) and
      (not(combat_is_initialized)) and
      ((critter_state(self_obj) bwand DAM_KNOCKED_OUT) == FALSE)
      ) then begin
      if (local_var(LVAR_Called_Clear) == 0) then begin
         set_local_var(LVAR_Called_Clear,1);
         add_timer_event( self_obj, game_ticks(10), 1 );
      end
   end
end
//end added

/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if (obj_is_visible_flag(self_obj)) then begin
      if ((local_var(LVAR_Hostile) == 2) and self_can_see_dude) then begin
         set_local_var(LVAR_Hostile,1);
         self_attack_dude;
      end
   end

   if (not(map_is_random_encounter)) then begin
      if ((local_var(LVAR_Off_Course) == 0) and (cur_town != caravan_end)) then
         set_local_var(LVAR_Off_Course, 1);

      if (caravan_status == CARAVAN_STATUS_ON_JOB) then
         dialogue_system_enter;
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
       set_global_var(CURRENT_CARAVAN, CARAVAN_THEFT);
       set_caravan_status(CARAVAN_STATUS_THEFT);
       set_global_var(GVAR_CARAVAN_START_TIME, 0);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin
   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION2;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

   if (local_var(LVAR_Off_Course) == 1) then begin
      set_global_var(CURRENT_CARAVAN, CARAVAN_ABANDONED);
      set_caravan_status(CARAVAN_STATUS_ABANDONED);
      set_global_var(GVAR_CARAVAN_START_TIME, 0);
      floater_bad(118);
      fadeout(1);
      set_obj_visibility(self_obj, 1);
      fadein(1);
   end
   else if ((caravan_status == CARAVAN_STATUS_ON_JOB) and (cur_town == caravan_end)) then begin
      Face_Critter(dude_obj, self_obj);
      start_gdialog(NAME,self_obj,4,-1,-1);
      gSay_Start;
      call Node006;
      gSay_End;
      end_dialogue;

      set_local_var(LVAR_Herebefore, 1);
   end else if (local_var(LVAR_Herebefore) == 1) then begin
      call Node007;
   end else begin
      call Node002;
   end

   call restore_idiot_savant_int;

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
   rm_caravan_masters(1);

   set_global_var(CURRENT_CARAVAN, CARAVAN_FAILURE);
   set_caravan_status(CARAVAN_STATUS_FAILED);
   set_global_var(GVAR_CARAVAN_START_TIME, 0);

end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

procedure map_exit_p_proc begin
   if (not(obj_is_visible_flag(self_obj))) then
      destroy_object(self_obj);
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
   set_local_var(LVAR_Herebefore, 1);
end


// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE

procedure Node001 begin
   Node1Rep += 1;
   if (Node1Rep == 1) then begin
      Reply(103);

      NOption(105, Node003, 1);
      NOption(106, Node004, 1);
   end else
      call Node005;
end

procedure Node002 begin
   if (obj_is_visible_flag(self_obj)) then
      floater_rand(107, 109);
end

procedure Node003 begin

   variable Caravan_Carts;
   variable Caravan_Guards;

   Caravan_Carts := random(1, 3);
   Caravan_Guards := random(2, 4);
   Caravan_Guards := (Caravan_Guards - party_size);
   if (Caravan_Guards < 1) then
      Caravan_Guards := 1;

   set_global_var(CURRENT_CARAVAN, CARAVAN_ON_CARAVAN);
   set_caravan_status(CARAVAN_STATUS_ON_JOB);

   set_global_var(GVAR_CARAVAN_START,AREA_JERICHO);
   set_global_var(GVAR_CARAVAN_END,AREA_HOOVER_DAM);

   if (not(dude_is_caravan_master)) then
      set_caravan_masters(1);
   set_caravan_guards(Caravan_Guards);
   set_caravan_carts(Caravan_Carts);
   set_caravan_brahmin(2 * Caravan_Carts);
   set_caravan_drivers(Caravan_Carts);

   Reply(110);
   ENDOPTION;
end

procedure Node004 begin
   Reply(111);
   ENDOPTION;
end

procedure Node005 begin
   Reply(112);
   ENDOPTION;
end

procedure Node006 begin
   variable amount;

   call CalculateCaravanRunSuccessRate(CURRENT_CARAVAN);

   if (global_var(CURRENT_CARAVAN) == CARAVAN_THEFT) then begin
      amount := 0;
      Reply(118);
   end
   else if (global_var(CURRENT_CARAVAN) == CARAVAN_TOTAL_FAILURE) then begin
      amount := 0;
      Reply(113);
   end
   else if (global_var(CURRENT_CARAVAN) == CARAVAN_FAILURE) then begin
      // CC
      if (CURRENT_CARAVAN == GVAR_CHEM_CARAVAN) then begin
         inc_global_var(GVAR_CRIMSON_CARAVAN_RUNS);
         amount := 450;
      end
      // 3S
      else if (CURRENT_CARAVAN == GVAR_WATER_CARAVAN) then begin
         inc_global_var(GVAR_3S_CARAVAN_RUNS);
         amount := 750;
      end

      Reply(mstr(114) + amount + mstr(124));
   end
   else if (global_var(CURRENT_CARAVAN) == CARAVAN_AVERAGE_SUCCESS) then begin
      // CC
      if (CURRENT_CARAVAN == GVAR_CHEM_CARAVAN) then begin
         inc_global_var(GVAR_CRIMSON_CARAVAN_RUNS);
         amount := 900;
      end
      // 3S
      else if (CURRENT_CARAVAN == GVAR_WATER_CARAVAN) then begin
         inc_global_var(GVAR_3S_CARAVAN_RUNS);
         amount := 1500;
      end

      Reply(mstr(115) + amount + mstr(125));
   end
   else if (global_var(CURRENT_CARAVAN) == CARAVAN_COMPLETE_SUCCESS) then begin
      variable a1, a2;
      // CC
      if (CURRENT_CARAVAN == GVAR_CHEM_CARAVAN) then begin
         inc_global_var(GVAR_CRIMSON_CARAVAN_RUNS);
         amount := 1000;
         a1 = 100;
         a2 = 900;
      end
      // 3S
      else if (CURRENT_CARAVAN == GVAR_WATER_CARAVAN) then begin
         inc_global_var(GVAR_3S_CARAVAN_RUNS);
         amount := 1700;
         a1 = 200;
         a2 = 1500;
      end

      Reply(mstr(116) + a1 + mstr(126) + a2 + mstr(127));

   end
   else begin
      amount := 0;
      Reply(117);
   end

   set_global_var(CURRENT_CARAVAN, CARAVAN_NONE);
   set_caravan_status(CARAVAN_STATUS_NONE);
   set_global_var(GVAR_CARAVAN_START_TIME, 0);
   if (amount > 0) then begin
      item_caps_adjust(dude_obj, amount * (1 + party_size_humans));
   end

   ENDOPTION;
end

procedure Node007 begin
   if (obj_is_visible_flag(self_obj)) then
      floater_good(117);

   fadeout(1);
   set_obj_visibility(self_obj, 1);
   fadein(1);
end

procedure checkLoadConditions begin
   if (cur_town == caravan_end) then begin
      Face_Critter(dude_obj, self_obj);
      dialogue_system_enter;
   end
   else if (not(map_is_random_encounter)) then begin
      set_local_var(LVAR_Off_Course, 1);
      dialogue_system_enter;
   end
end

//xxxxxxxxxxxxxxxxxxxx
