/*

        Name:
        Location:       Hoover Dam
        Description:

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_HDCOSTA

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_HOOVER_DAM)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node007a;
procedure Node008;
procedure Node009;
procedure Node010;

procedure Floats;
procedure HelpCosta;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Warn_Armed                 (8)
#define LVAR_Warn_Sneak                 (9)
#define LVAR_Gave_Armor                 (10)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */

/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_HOOVER_DAM);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_TOUGH_GUARD);
   add_timer_event(self_obj, game_ticks(6), 0);

   if (not(is_loading_game)) then begin
      if(cur_map_index == MAP_FORT_DESOLATION) then begin
         if (global_var(GVAR_HELP_COSTA_DESERT) == QUEST_INACTIVE and not(night) and not(obj_is_visible_flag(self_obj))) then begin
            set_obj_visibility(self_obj, 0);
         end
         else if (not(is_critter_dead(self_obj))) then begin
            set_obj_visibility(self_obj, 1);
         end
      end
      else if((cur_map_index == MAP_HOOVER_DAM_NORTH_GATE) and ((global_var(GVAR_HELP_COSTA_DESERT) == QUEST_ACCEPTED) or (global_var(GVAR_HELP_COSTA_DESERT) == QUEST_COMPLETED))) then begin
         set_obj_visibility(self_obj, 1);
      end
   end

   if (not(obj_is_visible_flag(self_obj)) and ((global_var(GVAR_HELP_COSTA_DESERT) == QUEST_DECLINED) or (global_var(GVAR_HELP_COSTA_DESERT) >= QUEST_ACCEPTED))) then
      destroy_object(self_obj);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if(cur_map_index == MAP_FORT_DESOLATION) then begin
      if ((global_var(GVAR_HELP_COSTA_DESERT) == QUEST_INACTIVE) and not(night) and not(obj_is_visible_flag(self_obj))) then begin
         set_obj_visibility(self_obj, 0);
      end
      else if (night and not(is_critter_dead(self_obj)) and obj_is_visible_flag(self_obj)) then begin
         set_obj_visibility(self_obj, 1);
      end
   end

   if(self_can_see_dude or self_can_hear_dude) then begin
      if (local_var(LVAR_Hostile) != 0) then begin
         set_local_var(LVAR_Hostile,1);
         self_attack_dude;
         //Macro made by Tom to keep the critter fleeing.
      end else if (dude_is_armed and local_var(LVAR_Warn_Armed) == 0 and self_can_see_dude) then begin
         floater_bad(200);
         set_local_var(LVAR_Warn_Armed, 1);
         rm_timer_event(self_obj);
         add_timer_event(self_obj, game_ticks(5), 1);
      end else if (dude_is_sneaking and local_var(LVAR_Warn_Sneak) == 0) then begin
         floater_bad(201);
         set_local_var(LVAR_Warn_Sneak, 1);
         rm_timer_event(self_obj);
         add_timer_event(self_obj, game_ticks(5), 2);
      end else if (not(ncr_bos_war_ended) and dude_looks_like_bos and self_can_speak) then begin
         floater_bad(204);
         call Node998;
      end

   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_INTOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

   if(self_can_see_dude and (cur_map_index == MAP_HOOVER_DAM_NORTH_GATE) and (global_var(GVAR_HELP_COSTA_DESERT) == QUEST_NONE)) then begin
      display_mstr(301);
      give_pid_qty(dude_obj, PID_GATE_GUARD_NOTE, 1)
      mark_on_map(AREA_FORT_DESOLATION)
      reg_anim_clear(self_obj);
      reg_anim_begin();
      reg_anim_animate(self_obj, ANIM_magic_hands_middle, -1);
      reg_anim_end();
      set_global_var(GVAR_HELP_COSTA_DESERT, QUEST_INACTIVE);
   end
   else if((cur_map_index == MAP_FORT_DESOLATION) and (global_var(GVAR_HELP_COSTA_DESERT) == QUEST_INACTIVE)) then begin
      call set_idiot_savant_int;

      start_gdialog(NAME, self_obj, 4, -1, -1);
      gsay_start;
      if (local_var(LVAR_Gave_Armor) == 1) then begin
         if (dude_wearing_armor and (obj_pid(critter_inven_obj(dude_obj,INVEN_TYPE_WORN)) == PID_NCR_ARMOR)) then
            call Node009;
         else
            call Node010;
      end
      else begin
         call Node001;
      end
      gsay_end;
      end_dialogue;

      call restore_idiot_savant_int;

      if (Only_Once == 1) then begin
         load_map("hdgatenr", 0);
      end

   end
   else begin
      call Floats;
   end

end

procedure timed_event_p_proc begin
   if(fixed_param == 1 and dude_is_armed and self_can_see_dude) then begin
      floater_bad(202);
      self_attack_dude;
   end else if (fixed_param == 2 and dude_is_sneaking and (self_can_see_dude or self_can_hear_dude)) then begin
      floater_bad(203);
      self_attack_dude;
   end else if (fixed_param == 0 and (global_var(GVAR_HELP_COSTA_DESERT) == QUEST_NONE)) then begin
      if(self_can_see_dude) then begin
         floater_whisper(300);
      end
      add_timer_event(self_obj, game_ticks(6), 0);
   end
   set_local_var(LVAR_Warn_Armed, 0);
   set_local_var(LVAR_Warn_Sneak, 0);
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_neutral_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Floats begin
   if (dude_is_male) then
      floater_rand(103,115);
   else
      floater_rand(122,127);
   call Node999;
end

procedure Node001
begin
Reply(302);
NOption(303, Node002, 4);
end

procedure Node002
begin
Reply(304);
NOption(305, Node003, 4);
if (dude_is_horny_male) then
BOption(317, Node007, 4);
end

procedure Node003
begin
Reply(306);
NOption(307, Node004, 4);
end

procedure Node004
begin
Reply(308);
NOption(309, Node005, 4);
end

procedure Node005
begin
Reply(310);
GOption(311, Node006, 4);
NOption(312, Node007, 4);
BOption(313, Node008, 4);
end

procedure Node006
begin
   transfer_pid_between_objs(self_obj, dude_obj, PID_NCR_ARMOR, 1)
   set_local_var(LVAR_Gave_Armor, 1);
Reply(314);
NOption(g_mstr(350), Node999, 4);
end

procedure Node007
begin
   set_global_var(GVAR_HELP_COSTA_DESERT, QUEST_DECLINED);
Reply(315);
NOption(g_mstr(350), Node007a, 4);
end

procedure Node007a
begin
   fadeout(1);
   set_obj_visibility(self_obj, 1);
   fadein(1);
   call Node999;
end

procedure Node008
begin
   set_global_var(GVAR_HELP_COSTA_DESERT, QUEST_DECLINED);
Reply(316);
BOption(g_mstr(350), Node998, 4);
end

procedure Node009
begin
Reply(318);
NOption(g_mstr(350), HelpCosta, 4);
end

procedure Node010
begin
Reply(319);
NOption(g_mstr(350), Node999, 4);
end

procedure HelpCosta
begin
   set_global_var(GVAR_HELP_COSTA_DESERT, QUEST_ACCEPTED);
   display_mstr(400);
   give_xp(300);
   game_time_advance(ONE_GAME_DAY);
   Only_Once = 1;
   call Node999;
end

//xxxxxxxxxxxxxxxxxxxx
