/*******************************************************************************
        Name:
        Location:
        Description: Object template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\maxbunkr.h"

#define NAME                    SCRIPT_HDJAILEX

/* Standard Script Procedures */
procedure start;
procedure spatial_p_proc;

/* Defines */

/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/

procedure start begin
end

procedure spatial_p_proc begin
    if(source_obj == dude_obj) then begin
        if (global_var(GVAR_HD_JAIL_TIME) == HD_JAIL_DOING_TIME) then begin
            set_global_var(GVAR_HD_JAIL_TIME, HD_JAIL_ESCAPED);
        end
    end
end
