/*

        Name:           Prisoner
        Location:       Tibbets
        Description:

           Created: 20/06/2020 22:53:34

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\MAPS\MAXBUNKR.ssl"

#define NAME                    SCRIPT_TMP501

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_BLACKFOOT)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"


/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
	
procedure restock_merchant;


/* Script Specific Procedure Calls */
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending


// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Execute_Once               (12)
#define LVAR_Restock	                (13)

#define restock_caps(obj)		stock_pid_qty(obj, PID_BOTTLE_CAPS, random(500,1000))

#define restock_stim(obj)		stock_pid_qty(obj, PID_STIMPAK, random(2,5)) \
								/*stock_pid_qty(obj, PID_SUPER_STIMPAK, random(1,2)) */ \
								/*stock_pid_qty(obj, PID_MENTATS, random(1,2)) */\
								stock_pid_qty(obj, PID_ANTIDOTE, random(1,2)) \
								/*stock_pid_qty(obj, PID_HYPODERMIC_NEEDLE, random(5,10)) */\
								stock_pid_qty(obj, PID_BROC_FLOWER, random(10,20)) \
								stock_pid_qty(obj, PID_XANDER_ROOT, random(10,20)) \
								stock_pid_qty(obj, PID_MUTATED_FRUIT, random(10,20)) \
								stock_pid_qty(obj, PID_HEALING_POWDER, random(5,10)) \
								/*stock_pid_qty(obj, PID_NUKA_COLA, random(2,5))  */\
								stock_pid_qty(obj, PID_GREATER_HEALING_POWDER, random(2,5)) \
								stock_pid_qty(obj, PID_STRANGE_POULTICE, random(5,8)) \
								stock_pid_qty(obj, PID_TURBO, random(0,1)) \
								stock_pid_qty(obj, PID_SMOOCH, random(0,1)) 
								/*stock_pid_qty(obj, PID_RAT_TAIL_LUCKY_CHARM, random(1,2)) //might want to increase crit chance or something */
																								
#define restock_tools(obj)		/*stock_pid_qty(obj, PID_MEDICAL_SUPPLIES, random(0,1)) */\
								/*stock_pid_qty(obj, PID_PARAMEDICS_BAG, random(0,1)) */\
								/*stock_pid_qty(obj, PID_FIELD_MEDIC_KIT, random(0,1)) */\
								stock_pid_qty(obj, PID_FIRST_AID_KIT, random(0,1)) \
								/*stock_pid_qty(obj, PID_MULTI_TOOL, random(0,1)) */\
								/*stock_pid_qty(obj, PID_SUPER_TOOL_KIT, random(0,1)) */\
								stock_pid_qty(obj, PID_ROPE, random(2,4)) \
								/*stock_pid_qty(obj, PID_PLASTIC_EXPLOSIVES, random(0,1)) */\
								stock_pid_qty(obj, PID_DYNAMITE, random(0,2)) \
								/*stock_pid_qty(obj, PID_EXP_LOCKPICK_SET, random(0,1)) */\
								stock_pid_qty(obj, PID_LOCKPICKS, random(0,1)) 
								
#define restock_weapons(obj)    stock_pid_qty(obj, PID_SHARP_SPEAR, random(0,1)) \
								stock_pid_qty(obj, PID_SPEAR, random(0,1)) \
								stock_pid_qty(obj, PID_SLEDGEHAMMER, random(0,1)) \
								stock_pid_qty(obj, PID_TIGER_CLAWS, random(0,1)) \
								stock_pid_qty(obj, PID_PUNCH_DAGGER, random(0,1)) \
								stock_pid_qty(obj, PID_SLING, random(0,1)) \
								stock_pid_qty(obj, PID_POWDER_BAG, random(0,1)) 


/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;
variable vendorsettings;
variable inidays;
variable timeindays;

procedure start begin
end

import variable qm_ptr;

procedure set_time_indays begin
	vendorsettings := get_ini_setting("mods\\FalloutYesterday.ini|FalloutYesterday|vendor_settings"); 								
	inidays := get_ini_setting("mods\\FalloutYesterday.ini|Vendors|restock_tribal");
	if (inidays >= 1) and (vendorsettings == 1) then begin
		timeindays := inidays;
	end	else begin 
		timeindays := 3;
	end	
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_STORE_OWNER);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_BROTHERHOOD_OF_STEEL);
   //call new_plague_check(self_obj, LVAR_Herebefore);
   variable item;
   //item:=create_object(PID_COMBAT_ARMOR_MK_II,0,0);	
   call restock_merchant;

end

procedure restock_merchant begin	
	
	call set_time_indays;
	if (game_time >= local_var(LVAR_Restock)) then begin
		restock_stim(self_obj)
		restock_tools(self_obj)
		restock_caps(self_obj)
		restock_weapons(self_obj)
		set_local_var(LVAR_Restock , (game_time + (ONE_GAME_DAY* timeindays)) );
	end		
	if local_var(LVAR_Execute_Once) < 99 then begin
	   give_pid_qty(self_obj, PID_10MM_PISTOL , 1)
	   give_pid_qty(self_obj, PID_10MM_JHP , 4)
	   give_pid_qty(self_obj, PID_LEATHER_JACKET , 1)
	   set_local_var(LVAR_Execute_Once,99);
   end		
end


procedure look_at_p_proc begin
   script_overrides;
   display_mstr(101);
end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */
   // if(global_var(GVAR_BROTHERHOOD_KLAXON) == 1) then
      // set_local_var(LVAR_Hostile,2);

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude or self_can_hear_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_INTOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   start_gdialog(NAME,self_obj,4,-1,-1);
   gSay_Start;
		/*
		   if (local_var(LVAR_Herebefore) == 0) then begin
			  set_local_var(LVAR_Herebefore,1);
			  call Node001;
		   end else begin
			  call Node003;
		   end
		*/
		call Node001;
   gSay_End;
   end_dialogue;   

    //floater_rand(200, 217);
	
	
	
	//call Node999;

end

procedure Node001 begin
	Reply(300);
	NOption(301,Node002,1);
	NOption(302,Node999,1);
end

procedure Node002 begin
	gdialog_barter;
	Reply(303);
	NOption(302,Node999,1);
end

procedure Node003 begin
end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin


/* Increment the aligned critter counter*/
   inc_neutral_critter
/* Set global_variable for Enemy status*/
end


/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures
