/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/* Random Encounter scripts. These will be filled in more once they
   have been designed.
*/

#include "..\headers\define.h"

#define NAME                    SCRIPT_ECGECKO

#include "..\headers\command.h"
#include "..\headers\party.h"
#include "..\headers\footsteps.h"

procedure start;
procedure destroy_p_proc;
procedure critter_p_proc;
procedure map_enter_p_proc;
procedure map_exit_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure timed_event_p_proc;

variable starttile := 0;
variable Sneer, pelt, footsteps_type;

procedure map_enter_p_proc begin
   starttile := self_tile;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_RND_SILVER_GECKO);
   reg_anim_clear(self_obj);
   reg_anim_begin();
   animate_rotation(Random(0, 5));
   reg_anim_end();

   variable fid := self_fid;

   if (fid == FID_MAGCKO) then begin
      pelt := PID_GOLDEN_GECKO_PELT;
      footsteps_type = SFX_FOOTSTEP_MEDIUM_BAREFOOT;
   end else if (fid == FID_MAGKO2) then begin
      pelt := PID_GECKO_PELT;
      footsteps_type = SFX_FOOTSTEP_SOFT_BAREFOOT;
   end else if (fid == FID_MAFIRE) then begin
      pelt := PID_FIRE_GECKO_PELT;
      footsteps_type = SFX_FOOTSTEP_MEDIUM_BAREFOOT;
   end

   call critter_setup_footsteps_map_enter(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT);

end

procedure timed_event_p_proc begin
   call critter_setup_footsteps_timed_event(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT, footsteps_type);
end

procedure map_exit_p_proc begin
   call BeastlordUnpossess(TEAM_RND_SILVER_GECKO);
end

procedure start begin
end

procedure critter_p_proc begin
   if (self_can_see_dude) then begin
      self_attack_dude;
   end

   if (not anim_busy(self_obj)) then begin
      reg_anim_clear(self_obj);
      reg_anim_begin();
      animate_move_to_tile(tile_num_in_direction(starttile, Random(0, 5), Random(3, 10)));
      reg_anim_end();
   end
end

procedure destroy_p_proc begin

   if (has_trait(TRAIT_PERK,dude_obj,PERK_gecko_skinning_perk)) then begin
      give_pid_qty(self_obj, pelt, 1)
   end

   inc_neutral_critter
end

procedure combat_p_proc begin
   if (fixed_param == COMBAT_SUBTYPE_HIT_SUCCEEDED) then begin
       if (random(0,100) == 1) then begin
           if (Sneer == 0) then begin
               if (target_obj == dude_obj) then begin
                   display_msg(mstr(100));
                   Sneer:=1;
               end
               else begin
                   display_msg(mstr(101)+obj_name(target_obj));
               end
           end
           else begin
               Sneer:=0;
           end
       end
   end
end

procedure description_p_proc begin
   call BeastlordPossess;
end

procedure use_skill_on_p_proc begin
   call injure_with_skill;
end
