/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/* Random Encounter scripts. These will be filled in more once they
   have been designed.
*/

procedure start;

#include "..\headers\define.h"

#define NAME                    SCRIPT_ECWLDDOG

#include "..\headers\command.h"
#include "..\headers\party.h"

procedure start;
procedure destroy_p_proc;
procedure critter_p_proc;
procedure map_exit_p_proc;
procedure map_enter_p_proc ;
procedure description_p_proc ;
procedure use_skill_on_p_proc;

procedure start begin
end

procedure map_enter_p_proc begin
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_RND_WILD_DOG);
end

procedure map_exit_p_proc begin
   call BeastlordUnpossess(TEAM_RND_WILD_DOG);
end

procedure critter_p_proc begin
   if (self_can_see_dude) then begin
       self_attack_dude;
   end
end

procedure description_p_proc begin
   call BeastlordPossess;
end

procedure destroy_p_proc begin

end

procedure use_skill_on_p_proc begin
   call injure_with_skill;
end
