/*******************************************************************************
        Name:
        Location:
        Description: Object template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\setntclt.h"

#define NAME                    SCRIPT_TMPLWOOD

/* Standard Script Procedures */
procedure start;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure map_enter_p_proc;

/* Defines */


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/

procedure start begin
end

procedure timed_event_p_proc begin
   if(map_var(MVAR_BRIDGE_BUILT) == 1) then begin
      set_obj_visibility(self_obj, 0);
   end else begin
      add_timer_event(self_obj, 1, 1);
   end
end

procedure description_p_proc begin
    display_mstr(100);
end

procedure use_obj_on_p_proc begin
   if (obj_pid(obj_being_used_with) == PID_ROPE) then begin
      script_overrides;
      fadeout(1);
      move_to(dude_obj, 26686, 1);
      critter_attempt_placement(dude_obj, 26686, 1);
      remove_pid_qty(dude_obj, PID_ROPE, 1)
      fadein(1);
      if(global_var(GVAR_DROWNED_TEMPLE_LOWER) == 0) then begin
         set_global_var(GVAR_DROWNED_TEMPLE_LOWER, 1);
      end
   end
end

procedure use_skill_on_p_proc begin

   if (
      (action_being_used == SKILL_SCIENCE) and
      is_success(roll_vs_skill(source_obj, SKILL_SCIENCE, 0))
   ) then begin
      script_overrides;
      display_mstr(101);
      if(map_var(MVAR_ONCE_SCIENCE) == 0) then begin
          set_map_var(MVAR_ONCE_SCIENCE, 1);
          give_xp(10);
      end
   end
end

procedure map_enter_p_proc begin
   if(map_var(MVAR_BRIDGE_BUILT) != 1) then begin
      set_obj_visibility(self_obj, 1);
   end

   add_timer_event(self_obj, 1, 1);
end
