
{102}{}{This is the coolant pumping machine. There's a computer panel attached above it. It seems important. And dangerous!}

{150}{}{This is a computer used to control critical reactor processes.}
{151}{}{It's not broken so there's nothing to repair.}
{152}{}{Trapping it would take too long.}

# Node001
{200}{}{[This is a reactor computer with a display, some input buttons and a big, red crank wheel. You have no idea how to operate it.]}
{201}{}{[Leave.]}

# Node002
{230}{}{What would you like to do with the reactor computer attached to the coolant pumping machine?}
{231}{}{[Manipulate the inputs and the pump in order to overload the reactor core.]}
{232}{}{[Leave the computer alone.]}
