# Message file for b1simtek.ssl
# Number of nodes: 6

{102}{}{This SimTek 5000 has been customized for the purposes of military.}

# Node001
{200}{}{WELCOME TO SIMTEK 5000: BLACK & WHITE EDITION, YOUR MILITARY SIMULATOR FOR DESTROYING THE EARTH. SELECT A SCENARIO YOU WISH TO SIMULATE.}
{201}{}{[Access the "ROOT SYSTEM COMMANDS".]}
{202}{}{[Access the simulation titled "HOME".]}
{203}{}{[Access the simulation titled "WORLD WAR III".]}
{204}{}{[Access the simulation titled "ALPHA CENTAURI".]}
{205}{}{[Exit the system.]}

# Node002
{230}{}{[A long list of root level commands is displayed on the monitor.]}
{231}{}{Hmmm, what is this... "MR1_ACCESS_DOOR_UNLOCK"? Lets run that.}
{232}{}{[Go back to the main menu.]}
{233}{}{Hmmm, wut dat... "MR1_ACCESS_DOOR_UNLOCK"? Me run dat.}

# Node003
{260}{}{RUNNING "MR1_ACCESS_DOOR_UNLOCK"... SUCCESS. MISSILE ROOM 1 ACCESS DOOR HAS BEEN UNLOCKED.}

# Node004
{290}{}{ACCESS DENIED. PLEASE CONTACT DR. VICTOR PRESPER FOR PROPER ACCESS PERMISSIONS.}

# Node005
{320}{}{BAD SECTOR NUMBER 602,533,871,300,782 DETECTED ON ALPHA HOLODISK! PROCESS ABORTED!}

# Node006
{350}{}{ACCESS DENIED. PLEASE CONTACT THE ENCLAVE FOR PROPER ACCESS PERMISSIONS.}
