# Grammar pass done

{100}{}{Another warrior seeking the embrace of death? You wish to undertake the trial, eh? Well, know this: Once you embark on the trial, there is no turning back unless you prove yourself worthy. Speak with Teacher, and he shall provide you with instructions on entering the sacred forest, our revered hunting grounds, our yapping hills. However, your tribe reputation is not yet high enough. You cannot take the trial only to meet your demise.}
{101}{}{Very well, I shall work on raising my tribe reputation and return when ready.}
{102}{}{I am prepared to face the trial now. Lead me to the hills.}
{103}{}{Understood. Remember, only one individual may undertake the trial per day. We must maintain the challenge, mustn't we?}
{104}{}{Very well, open the gate.}
{105}{}{Teacher speaks highly of your reliability. You may proceed.}
{106}{}{Your reputation precedes you, and Teacher vouches for your trustworthiness. Marie holds you in great esteem. If you have managed to overcome such challenges, I believe you shall triumph in this trial as well. Now, I have a significant task for you.}
{107}{}{What is this task you speak of?}
{108}{}{I have no interest in taking on any more tasks.}
{109}{}{Your mission, should you choose to accept it, is to track down and hunt the elusive Devil Dog - an evil spirit that even our finest hunters struggle to locate. Alas, as the Packleader, I am unable to partake in the trial. Bring the Devil Dog to Teacher; you can do it, I know you can.}
{110}{}{Very well, open the gate now.}
{111}{}{What are you still doing here? I will not allow you entry again.}
{112}{}{Very well then. Farewell.}
{113}{}{I am not yet prepared.}
{114}{}{Ah, it is you. Kurisu has informed me of your favorable relations with the Blackfoots. You may enter.}
