# X minutes and Y seconds to evacuate.
{111}{}{T-minus }
{112}{}{ minutes and }
{113}{}{ seconds until missiles launch.}
{114}{}{ minute and }
{115}{}{ second until missiles launch.}

{120}{}{ seconds until structural integrity failure.}
{121}{}{ second until structural integrity failure.}

{130}{}{ seconds until emergency launch protocol activation.}
{131}{}{ second until emergency launch protocol activation.}

{140}{}{ seconds until reactor overload.}
{141}{}{ second until reactor overload.}

{200}{}{You have boarded Ballistic Orbital Missile Base - 001 space station. The power has been fully activated on the station.}
{201}{}{Where Nu Yuk go?}
{202}{}{Wha.. where am I?}
