# Message file for carib.ssl
# Number of nodes: 18
# Grammar pass done

{100}{}{You see a rugged desert ranger, his dark-skinned face hidden behind a gas mask and wearing a trenchcoat.}
{101}{}{You see Carib, a seasoned Desert Ranger.}
{102}{}{His weathered appearance speaks of battles fought and hardships endured.}

{105}{}{Time to seal her up - RUN!}
{106}{}{See you around. Our work here is done.}
{107}{}{Alright, alright! You're more persistent than my mama.}
{108}{}{Stay close. And keep quiet.}
{109}{}{What the hell do you think you're doing?}

{199}{}{You shouldn't be here, especially without something to protect you from the radiation. If you end up cooked like that brahm'n over there, don't come crying to me.}
# Node001
{200}{}{You shouldn't be here, especially without something to protect you from the radiation. If you end up cooked like that brahm'n over there, don't come crying to me. Name's Carib, by the way.}
{201}{}{I'm }
{202}{}{. What's your business here?}
{203}{}{Radiation? *gulp*}
{204}{}{Nice military gear you have. Where do your loyalties lie?}
{205}{}{I'm just here to kill anything hostile that moves.}
{206}{}{Hands up! This is a robbery!}
{207}{}{Looks like you have everything under control here. Farewell.}
{208}{}{Me }
{209}{}{. You doooooo?}
{210}{}{Me go.}

# Node002
{230}{}{I might ask you the same question. Well, I've been scouting this cave for a few days... lots of bones here, as you can see. Then my Geiger counter crazy-clicked as I went deeper. So I decided to come back with some heavy firepower. It's time to root out whatever's down there. So, are you here to get in my way or lend a hand?}
{231}{}{Hold on, I have a few questions first...}
{232}{}{Alright, Carib, lead the way.}
{233}{}{This seems a bit out of my league. I better play it safe and stay in one piece.}
{234}{}{Me help!}
{235}{}{Me talk. You talk.}
{236}{}{Me go. Me no hurt.}

# Node003
{260}{}{I've got an extra Rad-X with me. If you take it, your chances of dying from radiation poisoning are slim, but you might end up as a ghoul. Not saying it'll happen, but the wasteland spawned stranger things before. Want to trade for it?}
{261}{}{Sure, let's see what you've got.}
{262}{}{I'm good, thanks. Tell me something...}

# Node004
{290}{}{I'm a Desert Ranger, no affiliation with those NCR Rangers. People often confuse us. We operate on our own, like the legendary party led by Tycho.}
{291}{}{Tycho's party?}
{292}{}{The rangers? Which rangers?}
{293}{}{Tiko?}
{294}{}{Ran-ghe?}

# Node005
{320}{}{Yeah, Tycho. The Desert Ranger that took down the Master and saved our sorry hides from turning into a grotesque shade of green. He, along with some Vault dweller and a few other brave souls, ruled the western wastes almost a century ago. It's a story every Ranger knows like the back of their hand!}
{321}{}{Yeah, Tycho. The Desert Ranger that killed the Master and saved our-- err, my backside from turning ugly green. He, some Vault dweller, and a handful of others owned the western wastes back in the day. That tale's etched into the core of every Desert Ranger!}
{322}{}{Nah, that's not how it went down. The story I heard is that the Vault dude single-handedly took down the Master without any help from Tycho or anyone else.}
{323}{}{Nah, that's not how it went down. The legend says some guy named Ian infiltrated the Master's ranks, gained his trust, and then shot him in the back. Unexpected, sneaky, but effective.}
{324}{}{I was there, partner. I witnessed the whole damn thing. Let me tell you exactly how it happened...}
{325}{}{Me there. Me tell.}
{326}{}{Aaaaaand?}
{327}{}{Yeah, heard that story a hundred times already. Got anything else to share?}
{328}{}{Me ask.}

# Node006
{350}{}{[Two hours later] ...and then Tycho used the water chip to poison the waters, sealing the fate of the Master. That's the story I've heard in the east, where I am from. Tycho, a true hero, one way or another.}
{351}{}{That was an enlightening history lesson! Never too late to learn something new, or refresh some old memories. Or maybe even learn a thing or two about handling a firearm!}
{352}{}{That's not the version I'm familiar with. But let's change the topic, shall we?}
{353}{}{Couldn't agree more. Whoever put an end to the Master's reign, they deserve our gratitude.}
{354}{}{*sigh* The Master were parents. It will be forever missed.}
{355}{}{Me miss Master. Dad? Mom!}
{356}{}{Tycho no hero! Me mad! Kill you dead!}

# Node007
{380}{}{When the Desert Rangers were swallowed up by the NCR, I, like a few others, chose to remain independent. I want to uphold frontier justice, not serve some fancy government. Governments... they're weak, and they don't last long, partner.}
{381}{}{I've heard they're making waves out east, expanding their territory. But in the process, they've pushed a whole lot of raiders our way. Hah! The only good raider is a dead one, if you ask me.}
{382}{}{Well, who knows? Maybe one day I'll join the ranks of the Rangers myself. You never know what the wasteland holds in store for me. But for now, what else can you share with me?}
{383}{}{Me ran-ghe one day. Me ran-ghe.}
{384}{}{Raider friend?}

# Node008
{410}{}{[Two hours later] Holy hell! The real story is even crazier than the legend. A pre-war nuke went off right under the Boneyard cathedral? Sometimes I still have nightmares about the world we were born into. Well, we've wasted enough time. Time to check out this tomb. So, you coming with me or not?}
{411}{}{Sure, let's just hope we don't stumble upon any more surprises like hidden nukes.}
{412}{}{Me follow.}
{413}{}{Hold on a moment... I've got another question for you.}
{414}{}{Stop! Me quicky talky..}

# Node009
{440}{}{No stranger to action, just like me. Good! Time to root out whatever's lurking down there. Follow my lead!}
{441}{}{Hold on, I've got a few things I need to ask before we proceed.}
{442}{}{No. Me talk. You talk!}
{443}{}{GeronimooooOOooooo!}

# Node010
{470}{}{Shoot, but make it snappy.}
{471}{}{You mentioned something about radiation?}
{472}{}{What brings you to this place?}
{473}{}{Are you part of an army? Or maybe a raider gang?}
{474}{}{That's all I had to say. I must be on my way now.}
{475}{}{I'm done talking. It's time to uncover the secrets lurking in these dark tunnels.}
{476}{}{Thanks for the chat, but if you don't mind, empty your pockets or face the consequences!}
{477}{}{Who you?}
{478}{}{You raid?}
{479}{}{Me take stuff. Me take all.}
{480}{}{Me follow. Me fight.}

# Node011
{500}{}{Hah, a raider. Don't insult me, partner. And what about you? Are you affiliated with the Legion in any way?}
{501}{}{The Legion?}
{502}{}{No, I have no ties to them whatsoever.}
{503}{}{And what if I am? What's it to you?}
{504}{}{I'm not so sure you're not a raider yourself.}
{505}{}{You raider. You trick }
{506}{}{. }
{507}{}{No!}
{508}{}{Maybe.}
{509}{}{Legi?}

# Node012
{530}{}{[His body suddenly becomes tense] Well, that bit of information determines the course of our little encounter here. Now tell me straight - are you with Caesar's Legion or not?}
{531}{}{Yes, I am.}
{532}{}{No, I'm not associated with them.}
{533}{}{I don't owe you any answers, "partner".}
{534}{}{Me no tell!}

# Node013
{560}{}{Fair enough. I'll keep an eye on you, though. So, is our chat over, or are you planning on doing something useful today?}
{561}{}{Alright, lead the way. Let's see what awaits us in this cave.}
{562}{}{No, I'm good. I'll just continue wasting time and doing nothing. That's the plan.}
{563}{}{Me useful.}
{564}{}{Me do nothing.}

# Node014
{590}{}{Good to hear. I was starting to think I'd have to blow your head off, and I was just starting to like you.}
{591}{}{Heh, lucky me. I better leave you now to your little expedition.}
{592}{}{Didn't you ever hear about negotiations and diplomacy? Anyway, I have some questions for you.}
{593}{}{Me lucky. Me go now.}
{594}{}{Carib no kill. Carib talk?}

# Node015
{620}{}{Look, I know, partner. I'm telling you, that's how it went down. First, Tycho had to locate this high-tech suitcase thingie...}
{621}{}{[CONTINUE]}

# Node016
{650}{}{We've all lost loved ones, partner. But we can't dwell on it forever. We've been here long enough. Are you following me or not?}
{651}{}{Hold on, tell me something else first.}
{652}{}{Yeah, let's explore this place together.}
{653}{}{I'll call it a day. Time to venture elsewhere. See you around, Carib.}
{654}{}{Yes! RrrrrrrrrRrrrr....}
{655}{}{Me go away.}
{656}{}{Talky.}

# Node017
{680}{}{Maybe. So, are you joining me on this adventure, or are you heading out?}
{681}{}{Okay, let's do this!}
{682}{}{I really can't today. I have an... ummm, an appointment far away. Better go now and leave you to your fun.}
{683}{}{Tell me something first.}
{684}{}{Oki!}
{685}{}{Me go. Me see doctor. Far away.}
{686}{}{Me ask!}
# Node018
{710}{}{Yeah, those raiders with their inflated stories. No love for 'em, only bullets. But you didn't answer my question, partner.}
{711}{}{Yes, I'm affiliated with them.}
{712}{}{No, I've never even heard of them.}
{713}{}{I'm not telling you anything!}
{714}{}{Me Lee Gion. Hahuh!}
{715}{}{No no.}
{716}{}{Me no speak.}
