
{200}{}{Hey, get away from that car!}
{201}{}{It appears that violence is the only language you understand, punk.}

{300}{}{The car has no wheels, it can't go anywhere!}
{301}{}{Looks like you'll have to replace the entire electric engine with a working one.}
{302}{}{The Chryslus Highwayman is a full-size car manufactured by the Chryslus Motors Corporation. The car shares technology with the Chryslus Corvega: it has a fully analog system with no electronics, over 800 horsepower, and reaches 60 mph in under a second. It has a spacious trunk and an interior capable of accommodating as much as seven people, give or take.}
{303}{}{Looks like you'll have to replace the entire electric engine with a working one.}
