# Message file for dtdaniel.ssl
# Number of nodes: 31

{100}{}{You see a man in his forties.}
{101}{}{You see Daniel.}
{102}{}{He looks kind of familiar.}

{110}{}{You brought Daniel back to the safety of Tibbets.}

{150}{}{Let's just get to Tibbets.}
{151}{}{No - no - please don't - oh, God...}
{152}{}{O merciful Father... it's me. Daniel. Help.}

# Node001
{200}{}{Listen to me. Please listen. My name is Daniel and I come from New Canaan. I've got a family there - two wives and seven children - who can vouch for me. Buy my freedom and they'll recoup your losses, plus something a little extra. We are Mormons, you can trust us.}
{201}{}{Here you are, then. Looks like Daniel ended up in the lion's den.}
{202}{}{Out of the frying pan, into the fire. How'd you wind up here?}
{203}{}{Daniel, right? I've come to take you back to Tibbets.}
{204}{}{Hang on. Back in a second.}

# Node002
{230}{}{What? Lion's den? Wh-what are you talking about?}
{231}{}{It's from one of your own holy books, you jackass.}
{232}{}{Never mind. How'd the Legion capture you?}

# Node003
{260}{}{Seriously? You think this is really the time for that kind of thing? I've got a *slave collar* around my neck and you want to talk religion. Maybe, uh, I could open up my prayer book and we could sing a couple of homilies together?}
{261}{}{[CONTINUE]}

# Node004
{290}{}{Ha! I saw the lights, thought I'd skirt around the city without whoever was up in those skyscrapers spotting me. Ran right into the Legion's arms. They beat me down, collared me, beat me again just to be on the safe side. It's been quite an experience, I can tell you-}

# Node005
{320}{}{Wait... I know you. Yeah, from Tibbets. I saw you talking to the big brain-box, what's its name... the Warden?}

# Node006
{350}{}{Listen - I'm not like you, OK? I'm just an ordinary guy who wandered out of New Canaan in search of his Brahmin flock and ended up running into some... into some *goddarn* pre-war lunatic robots. And everything that's happened to me since has been a streak of *seriously* bad luck.}
{351}{}{In that case, things are looking up. We're heading back home, Daniel. Something's up with ODYSSEUS, and it won't rest until we've all been returned to our cells.}
{352}{}{Things are about to get a whole lot worse, Daniel - unless you come back to Tibbets with me.}

# Node007
{380}{}{What? No, no - I'm not going back. I've got a family waiting for me in New Canaan. I had a life there. I don't deserve - I'm a free man. An innocent man. That's supposed to mean something!}
{381}{}{The world is what it is, Daniel. You think you're better off here? You're wearing a slave collar. You've been beat. You'll get beat again, every day for the rest of your life until they break your spirit or they kill you.}
{382}{}{I can't believe I'm doing this, Daniel - but all right. I 'm going to get you out of here, and you can head back to your family. I'll tell ODYSSEUS you died in Dogtown. Hopefully it'll believe me.}
{383}{}{I guess I could kill you now, go back to ODYSSEUS and tell it you're dead. It won't be happy, but at least I won't have to argue with you.}
{384}{}{Think of this as an investment. You head back to Tibbets now - and we find some way of shutting ODYSSEUS down. Stop it from following us for good. You can still make it back to see your family in the long term, if you're only willing to be pragmatic about it for now.}

# Node008
{410}{}{I... they won't-}
{411}{}{In Tibbets you were safe. You were fed. You never wanted for anything, imprisoned though you were. Tibbets was civilization, Daniel. And this? This is the alternative. You don't get to choose New Canaan. You get to choose Tibbets, or death.}

# Node009
{440}{}{OK, OK. I'll come. Just... lead the way. I'll try and stay out of danger.}
{441}{}{Follow me.}

# Node010
{470}{}{You're serious? Oh, thank you! Thank you!}
{471}{}{The coast is clear for now. I'm going to open the door up.}
{472}{}{Wait here. I'll be back.}

# Node011
{500}{}{I'll be off, then. Thanks again for everything - and wish me luck!}
{501}{}{[END]}

# Node012
{530}{}{You'd... you wouldn't do that. The Legion wouldn't want to see their property destroyed. It'd be a waste of good meat.}
{531}{}{Well, that's where you're wrong, asshole. I've already bought you. So you can walk into Tibbets as a free man or you can walk out in chains. Or I kill you now and tip my Legion pals a couple of extra caps for the blood on their floor. Up to you... slave.}
{532}{}{Fine. I kill them too. No witnesses, no complaints. Do you feel better about my plan now?}
{533}{}{Still arguing? Sorry, Daniel. You just missed the last boat home.}

# Node013
{560}{}{All right! All right, I'll come with you. Just... don't hurt me, OK? I'll see you outside. I assume it's safe now that those bastards are dead.}
{561}{}{All right. See you in a minute, Daniel.}
{562}{}{You better not try anything foolish.}
{563}{}{Not a chance. You're not leaving my sight.}

# Node014
{590}{}{No - wait - wait -}

# Node015
{620}{}{All right! All right, I'll go. Just... talk to their leader. Buy me and I'll head back to Tibbets. I promise.}
{621}{}{I already negotiated your release. You're free to go.}
{622}{}{OK. I'll be back.}
{623}{}{Buy you? Oh, I don't think so. We're walking out of here over their cold corpses. Wait here. This shouldn't take long.}

# Node016
{650}{}{I... really? I honestly never thought... get my collar off, quick.}

# Node017
{680}{}{I'll see you outside. We can head back to Tibbets together. Thank you. For everything.}
{681}{}{Hold on - I'll wrap up my business with the Legion and then we'll leave together.}

# Node018
{710}{}{No - I need to get out now. I just need to... breathe the free air. For a second. Please.}
{711}{}{OK, OK. Go on. Get out of here. Just don't go trying to run off.}
{712}{}{No, I don't think I trust you one bit. Stick with me. Don't move an inch unless I tell you too.}

# Node019
{740}{}{I, uh... fine! Fine! You're the boss.}

# Node020
{770}{}{I won't. I promise.}
{771}{}{Alright then.}

# Node021
{800}{}{Hurry. Please.}

# Node022
{830}{}{Oh, you *must* be joking.}
{831}{}{Nope.}

# Node023
{860}{}{What - where are you going? Hey!}

# Node024
{890}{}{I'm guessing from the noise and the, um, bloodstains that you've had a slight altercation with our captors. I don't suppose you'd be interested in letting me go?}

# Node025
{920}{}{What the - hey, I know you. I know you. You're from Tibbets. The dummy that got ODYSSEUS all worked up. I'm Daniel, remember me?}
{921}{}{You from Tibbles?}
{922}{}{Dissus?}

# Node026
{950}{}{Listen. Do me a favor. The Legion's leader has keys. You know what they are? Keys? Jingle-jangle. Fetch me those keys and I'll give you a treat.}
{951}{}{Me get you out, you come back Tibbles. Dissus very very sad and no stop crying. Want cheer him up by throwing BIG PARTY.}
{952}{}{Jingle-jangle! Jingle-jangle!}
{953}{}{'K. }
{954}{}{ go ask.}

# Node027
{980}{}{What? Look, I don't know what you mean, but just find the keys and open up this door. We'll sort it out afterwards, I promise.}
{981}{}{Hghrrr.}

# Node028
{1010}{}{You - how did you? It doesn't matter. Get the door open, fast.}

# Node029
{1040}{}{Well? Are you going to help get me out of here?}
{1041}{}{The coast is clear. Go on, get out of here.}
{1042}{}{It's safe to come out now. Follow me.}
{1043}{}{Sit tight. I'll be back.}

# Node030
{1070}{}{Well? What are you waiting for? Keys! Keys! Surely you know what that means?}
{1071}{}{'K.}

# Node031
{1100}{}{Thank heavens. Time I was getting out of here...}
