# Message file for ecakeish.ssl
# Number of nodes: 6
# Grammar pass done

{100}{}{You see a prisoner on the run.}
{101}{}{You see Akeisha Moon.}
{102}{}{You see a young tribal woman.}

{150}{}{See you around.}

# Node001
{200}{}{Well, it's not every day someone takes such a keen interest in my adventures. What do you want, stranger?}
{201}{}{Straight to the point. I like that. My name is }
{202}{}{.}
{203}{}{This is a robbery!}
{204}{}{Nothing really. Bye.}
{205}{}{Unh.}

# Node002
{230}{}{Hmm. I am Akeisha Moon, a vault hunter.}
{231}{}{ODYSSEUS has been looking for us since our escape. I suggest you return or at least hand over your Pip-Boy.}

# Node003
{260}{}{Hahaha! Why on earth would I want to go back to that hellhole? And this Pip-Boy saved my life more times than I can count. Your suggestions are a fantasy.}
{261}{}{Akeisha, I understand your hesitations. But returning might be in your best interest. ODYSSEUS is relentless and you'll always be looking over your shoulder. Why not research Tibbets some more, parts of it were built by Vault-Tec just like the vaults you are hunting for.}

# Node004
{290}{}{Hmm. You're smart, trying to appeal to my sense of curiosity. But why should I trust you? What's in this for you?}
{291}{}{I just want ODYSSEUS to leave us alone. You escaping Tibbets and being on the run doesn't help that. I've seen the damage, the chaos. And the Pip-Boy? It's technology that belongs to Tibbets and it is used to track our movement. I'm just trying to retain our freedom.}

# Node005
{320}{}{Well, you have a point. As a member of the Followers of the Apocalypse, I have to keep moving and exploring. But the spying Pip-Boy, I can do without. Take it.}
{321}{}{Thanks, Akeisha.}

# Node006
{350}{}{Calm down, alright? I only have my Pip-Boy with me. Just take it, don't hurt me, OK?}
{351}{}{Well, that's better than nothing.}
{352}{}{I don't trust you. You're hiding something!}
