# Message file for ecbarth.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see a fat little pug.}
{101}{}{You see Bartholomew the Casino Mascot.}
{102}{}{This dog has evolved in unusual ways.}

{150}{}{The dog's "voice" rings inside your mind saying "}
{151}{}{"}

# Node 0 [floats]
{200}{}{Give me all the food you have.}
{201}{}{Food.}
{202}{}{Gizmo ate all the food.}
{203}{}{I'm soOOOOOoooOOoooo hungry.}
{204}{}{I'm starving here.}
{205}{}{I have a gun.}
{206}{}{Where's my cookie?}
{207}{}{Where's my iguana-on-a-stick?}
