# Grammar pass done

{100}{}{You come face to face with a colossal robot, towering like a house.}
{101}{}{The behemoth before you is a colossal robot, capable of devouring prisoners like you for breakfast.}
{102}{}{Its immense size instills a sense of fear, as it looms over everything in its path.}
{103}{}{Prisoners 771, 44223, and 105432, you *must* accompany us. ODYSSEUS will relentlessly pursue you and the others.}
{104}{}{Leave us be. We will never return to that wretched place.}
{105}{}{I will not repeat myself. Join us now, or face the consequences as an example to others.}
{106}{}{Grant us freedom or accept our defiance unto death!}
{107}{}{So be it. Terminate prisoners 771, 44223, and 105432. *bzzzt* ODYSSEUS, 14 prisoners remain unaccounted for. Updating Pip-Boy signal status...}
{108}{}{Victor Presper. Sean Coleridge. Martin Pierce. Adam Davidson. Robert "Border" Briggs. Jean-Baptiste Cutting. Jillian McKinley. Chagas. Mallet McBride. Blackjack. Daniel. Ginger Flowers. Akeisha Moon. And... }
{109}{}{You seem to find some people in the wrong place at the wrong time.}
