# Message file for ecblkjck.ssl
# Number of nodes: 6
# Grammar pass done

{100}{}{You see a mighty super mutant nightkin.}
{101}{}{You see Blackjack.}
{102}{}{He seems to be playing a card game on his Pip-Boy.}

{150}{}{I guess I'll just hit the nearest casino now.}

# Node001
{200}{}{[He slowly raises his gaze from the glowing screen of his Pip-Boy.] I'm Blackjack. The name has a nice ring to it, don't you think? How can I help you, small one?}
{201}{}{I've been looking for you, actually. ODYSSEUS sent robots to either bring us in dead or alive.}
{202}{}{I need to retrieve the Pip-Boy you're using.}
{203}{}{Prepare to die.}
{204}{}{So long, big guy.}
{205}{}{Die, big smurfy boi!}
{206}{}{Hng!}

# Node002
{230}{}{Tibbets! A big place that wasn't too comfy, even for me. Anyways, I'm not going back.}
{231}{}{Look, Blackjack, Tibbets might not be the best place, but roaming the wasteland with their tech will keep you in constant danger. Don't you want a chance at some peace? A place where you're not always on the run?}
{232}{}{I'll just bring you in dead then.}

# Node003
{260}{}{As for the Pip-Boy... it plays a mean game of blackjack. Why would I part with it?}
{261}{}{Without the Pip-Boy, they'll stop pursuing us. You'll have to give it to me now.}

# Node004
{290}{}{Peace is a funny word in the wasteland. But you make a point. Still, it's not easy being a super mutant. Wherever we go, trouble tends to follow.}
{291}{}{I get it. But by returning to Tibbets, you will be much safer than outside. Show them that not all super mutants are mindless brutes. And if you stay out here, well, others might not be as understanding as I am. But in that case I'll need your Pip-Boy.}
{292}{}{I've had enough of this fruitless talk. Time to die, mutie.}

# Node005
{320}{}{It's been a long time since someone spoke to me before shooting a gun first. Maybe... maybe it's worth a shot. But the Pip-Boy, it's been useful, a reminder that there's more to life than just raw strength.}
{321}{}{It's not often one sees a super mutant so engrossed in a game of cards. But you can't keep it anymore. ODYSSEUS will *never* stop pursuing you as long as you hold on to it. Never!}
{322}{}{That's it! I'll just take it by force.}

# Node006
{350}{}{Ah, well, even us mutants need a bit of fun. You're a strange one, but I like you. Alright, I'll give it to you. But first, how about a game of blackjack? You did mention it's not often you see a super mutant engrossed in cards.}
{351}{}{Deal me in, big guy. Let's play.}
