# Message file for ecchagas.ssl
# Number of nodes: 6
# Grammar pass done

{100}{}{You see a prisoner on the run.}
{101}{}{You see Chagas.}
{102}{}{His skin is covered with tribal tattoos.}

{150}{}{If you ever come by the Blackfoot tribe, seek me out.}

# Node001
{200}{}{You aren't with the NCR, are you?}
{201}{}{No, I'm not. Just a wanderer. Name's }
{202}{}{. And you?}
{203}{}{And what if I am?}
{204}{}{Ensiar? Ummm...}

# Node002
{230}{}{Chagas. Brother of Ramon. You might have heard of him. Once a proud leader of our tribe, the Blackfoot, before... everything went to hell.}
{231}{}{I see you have a Pip-Boy. A Lil-Pip 3000 model no less. Interesting.}

# Node003
{260}{}{Yes, a parting gift from Tibbets. Their robots have been on my tail. Can't get a moment's peace.}
{261}{}{Listen, Chagas. If you return to Tibbets, those robots will stop hunting you. However, if you hand over that Pip-Boy, maybe, just maybe, you can find a way to avoid their and the NCR's wrath. The desert's vast, but not vast enough to hide forever from both.}

# Node004
{290}{}{Ramon always told me to fight, to never surrender. But what's the use if I'm always running?}
{291}{}{There's honor in knowing when to fight and when to make a strategic move. Handing over the Pip-Boy could be that move. Live to fight another day, and maybe protect your tribe in the process.}
{292}{}{I've had enough of this negotiating. I'll just take it by force!}

# Node005
{320}{}{My tribe... I miss them. I've been away too long, always looking over my shoulder.}
{321}{}{It's your choice, Chagas. Hand over the Pip-Boy, and go back to your tribe, free from the shadows of the NCR and Tibbets.}

# Node006
{350}{}{[After a deep breath, he unstraps the Pip-Boy and hands it over.] Maybe you're right. I'll do what Ramon would want me to do. Put the tribe before myself.}
{351}{}{Wise choice, Chagas. May the winds of the desert guide you safely home.}
{352}{}{Thanks, Chagas.}
