# Message file for eckrimsn.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see a janitor.}
{101}{}{You see Krimson Graey.}
{102}{}{This guy could be another janitor.}

# Node 0 [Floats]
{200}{}{Who the fuck are you? I'm busy writing.}
{201}{}{I just got done this new concept album about a black dragon that abuses people. Wanna listen?}
{202}{}{I write so much that my life is futile. I have no social life.}
{203}{}{You play tabletop? No? Go fuck yourself.}
{204}{}{God, I wish I was better at doing vocal warm ups. Shit is so exhausting.}
{205}{}{Pirate, Mobster, Biker Santa, and... Shit what else do I put in my portfolio?}
{206}{}{You ever play Killer7? It's a cult classic!}
{207}{}{People get caught up on Graey. It's Grey and Gray so you just pronounce it as such. Dumbasses.}
{208}{}{Kitsunes are reverse furries.}
{209}{}{R.I.P. Billy Herrington.}
