# Message file for ecmallet.ssl
# Number of nodes: 5
# Grammar pass done

{100}{}{You see a prisoner on the run.}
{101}{}{You see Mallet McBride.}
{102}{}{You see a towering and menacing man.}

{150}{}{Now I'm gonna break you.}

# Node001
{200}{}{What do you want, stranger? A front-row seat to the next beatdown? Who dares cross paths with Mallet McBride?}
{201}{}{Not exactly. I'm here about that Pip-Boy of yours. And a certain prison by the name of Tibbets.}
{202}{}{Was that a threat?}
{203}{}{Me kick Mal.}
{204}{}{Me go.}

# Node002
{230}{}{Hahaha! Tibbets? They can wait. Unless you're here to try your luck against me? Word of advice: Many have tried, all have failed.}
{231}{}{I hope we can resolve this without bloodshed. That Pip-Boy you're flaunting? It's being tracked by robots. And so are you.}
{232}{}{I'll try my luck.}

# Node003
{260}{}{ I don't do "talk." I do "fight." So, if you want this Pip-Boy or me, you're going to have to earn it.}
{261}{}{If you keep racking up enemies, one day someone might just get lucky. Why not avoid the risk, hand over the Pip-Boy, and find a new place to set up shop?}
{262}{}{If you insist.}

# Node004
{290}{}{Are you threatening me?}
{291}{}{No, just offering a perspective. You're a smart fighter, Mallet. Every fight has risks. Why take one you don't need to?}
{292}{}{Bring it on!}

# Node005
{320}{}{You talk too much, but you've got guts approaching me like this. Fine, take the damn Pip-Boy. But if you cross me again, be ready for a fight.}
{321}{}{Fair enough.}
