{100}{}{Must warn the Army!}
{101}{}{Must warn Hoover Dam!}
{102}{}{Wasteland scum...}
{103}{}{Degenerate filth...}
{104}{}{Time to weed out more wasteland trash... Die!}
{105}{}{What are you doing around Hoover Dam?}
{106}{}{What is your business near Hoover Dam?}
{107}{}{This is part of the NCR territory.}
{108}{}{Watch yourself.}
{109}{}{Hoover Dam is not a sanctuary for *everyone.* So move on.}
{110}{}{Your kind belongs at Dogtown.}
{111}{}{I suggest you go there now.}
{112}{}{Hello, citizen.}
{113}{}{Anything we can do for you, citizen?}
{114}{}{Do you need an escort to Hoover Dam?}
{115}{}{What are you doing so far from Hoover Dam, citizen?}
{116}{}{We were worried you might have been hurt, citizen.}
