# Message file for ecpjhexr.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see a doorman.}
{101}{}{You see PJ Hexer.}
{102}{}{This guy could be a doorman. Or a janitor.}

# Node 0 [Floats]
{200}{}{Hello there! Welcome to the Den of Lost Luck! Excuse our dust, we're still renovating.}
{201}{}{I prefer meeting people face-to-face.}
{202}{}{I'm actually the janitor of this place. Bartholomew is the bouncer.}
{203}{}{Have you ever seen a living horned kangaroo? Me neither.}
{204}{}{One of our customers claims to be the last talking deathclaw.}
{205}{}{*cough* Is there some sort of virus on the loose? *cough*}
{206}{}{*sniff*}
{207}{}{You can never have too many bottlecaps.}
{208}{}{How do you like our place?}
{209}{}{Welcome to the oasis!}
{210}{}{I once saw Bartholomew blowing someone's brains out. You don't wanna mess with him.}
{211}{}{The previous owner of this casino was some guy called Gizmo.}
{212}{}{This place sets the new bar for feature creep.}
{213}{}{Have you seen the old janitor team anywhere around here?}
{214}{}{What's a single decade of waiting compared to an eternity of joy?}
{215}{}{We hope you enjoy how we refurbished the place.}
