{100}{}{You see a menacing man-eater plant. Its sharp, jagged teeth glisten as it sways in the wind.}
{101}{}{Beware of these deadly plants! Not only do they pose a threat to other vegetation, but their insidious nature allows them to attack unsuspecting humans and creatures.}
{102}{}{These plants exhibit a peculiar mutation. It's highly unlikely that such a mutation occurred naturally; there might be something more sinister at play.}
{103}{}{Aside from their aggressive behavior, there doesn't appear to be anything out of the ordinary about these plants.}

{200}{}{*SNAP*}
