# Message file for ecstevie.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see a janitor.}
{101}{}{You see Stevie D.}
{102}{}{This guy could be another janitor.}

# Node 0 [Floats]
{200}{}{Ah, that was juice.}
{201}{}{You could actually hear the juice.}
{202}{}{Twenty-five six please.}
{203}{}{M'sieur with these Rocher you are really spoiling us.}
{204}{}{What? Stink-burp?}
{205}{}{Drop the bass.}
{206}{}{Extreme body lines.}
{207}{}{Umm has someone dropped their guts?}
{208}{}{Are you a baker or a faker?}
{209}{}{Rubbing out my tree, rubbing out my tree.}
{210}{}{It's only got three buttons.}
{211}{}{What's a veranda?}
{212}{}{Is that a byear byum?}
{213}{}{See em.}
{214}{}{I want some something.}
{215}{}{What noise does a chicken make?}
{216}{}{I'm funny.}
{217}{}{Running.}
{218}{}{Dee Dee fut.}
{219}{}{'S 'at noise?}
{220}{}{Air-car.}
{221}{}{OMG with Peaches Geldof.}
{222}{}{Burp 'n' blow.}
{223}{}{Phones out goans out.}
{224}{}{Zack is walking.}
{225}{}{Went museum. Don't like eye.}
{226}{}{Don't like noise seals make.}
{227}{}{Like dat.}
{228}{}{Oh here we go.}
{229}{}{Sniff that bum.}
{230}{}{Well, huh huh huh.}
{231}{}{Welcome to the show.}
{232}{}{Read a book.}
{233}{}{It's the Bobber Davs - pin pin pin.}
{234}{}{Hello - these are the 1990's.}
{235}{}{Sock it to 'em.}
{236}{}{Don't stand for any nonsense.}
{237}{}{Blend, blend, blend.}
{238}{}{That was you. It came from your mouth.}
{239}{}{Stand up. Solid brown}
{240}{}{They're quite cute, but they also have a nasty bite.}
{241}{}{How very rude.}
{242}{}{Say less. Chop chop chop.}
{243}{}{Cool beans.}
