# Message file for ectbrobo.ssl
# Number of nodes: 4

{150}{}{This is a Tibbets manhunter robot, on the mission to find and retrieve escaped convicts. Dead or alive.}

# Node001
{200}{}{Prisoner 13! We have finally caught up with you. It is time to put an end to your deviant behavior. Hand over your Pip-Boy for analysis.}
{201}{}{OK, just don't shoot.}
{202}{}{Why would you need my Pip-Boy?}
{203}{}{You'll never catch me alive!}
{204}{}{Robo no kill! Pipi take.}
{205}{}{Robo die!}
{206}{}{Why Pipi?}

# Node002
{230}{}{Analysis shows that you have traveled "far and wide," including to and from areas of special interest. Time to end your journey.}
{231}{}{Really? No second chances?}
{232}{}{Me want new chan-ce.}

# Node003
{260}{}{Analysis shows that you have not traveled much to and from areas of special interest. You will return with us to Tibbets at once.}
{261}{}{Only in a casket, metallic scum!}
{262}{}{If I must...}
{263}{}{Robo-scum!}
{264}{}{Oki!}

# Node004
{290}{}{Your Pip-Boy is property of Tibbets Facility. It is of no concern to you what we are doing with it.}
{291}{}{OK, take it but I want it back.}
{292}{}{[Run]}
