{100}{}{You see a Fort Abandon inhabitant, a religious peasant.}
{101}{}{You see the local one of the local folk.}
{102}{}{There is nothing mentionable about the way this person looks.}
#Personal Enemy
{103}{}{Ahhh, leave me.}
{104}{}{I am sorry. I won't do it again.}
{105}{}{I was just leaving.}
{106}{}{Help, someone!}
{107}{}{Please leave me alone.}
{108}{}{Look, I don't want to be around you either.}

#Child Killer
{109}{}{You are just evil. Please don't talk to me.}
{110}{}{Leave our children alone.}
{111}{}{You're some kind of sick criminal. I hope the rangers get you.}
{112}{}{Just go away, okay?}
{113}{}{Hey, you shouldn't kill anyone - especially kids.}
{114}{}{I don't think I like you.}

#Berserker
{115}{}{Hey, just let me know when you are going to go postal.}
{116}{}{I have to go.}
{117}{}{Dharma doesn't approve of so much death.}
{118}{}{No one else needs to get hurt.}
{119}{}{I don't like you. Dharma protect me.}
{120}{}{They will just kill all like you.}

#Low Town Rep
{121}{}{What's your problem?}
{122}{}{Can't we all just get along?}
{123}{}{Don't talk to me.}
{124}{}{Whatever it is tell someone else.}
{125}{}{I don't think you're all that tough.}
{126}{}{Why don't you just leave?}

#normal
{127}{}{Well I have to get some milk.}
{128}{}{Do you know how to put tin siding up?}
{129}{}{Hello, there. Dharma's blessings upon you.}
{130}{}{Please don't bother me, I am really busy.}
{131}{}{I wonder how the refinery looked like when it was new.}
{132}{}{Sometimes I wonder where I am headed.}
{133}{}{Umm, thanks, I really have to be going.}
{134}{}{Maybe later we can talk more.}
{135}{}{Ohh, yeah, you are the helpful wanderer.}
{136}{}{You should talk to Kiru.}

{137}{}{Hear they're going to be building some new houses soon.}
{138}{}{Fort's been pretty quiet since you started ruling it.}
{139}{}{Good day. You are our hero.}
{140}{}{Pretty quiet place we got here. Nice, eh?}
{141}{}{Check out my cousin's place.}
{142}{}{I hear times are hard. When's the government gonna do something?}
{143}{}{You from the north? Don't get many norther's here.}
{144}{}{I heard everybody from the wasteland's a mutant or a savage!}
{145}{}{No time for chat. Got to get to work.}
{146}{}{Are they having a sale? Oh, never mind.}
