# Message file for gcpierce.ssl
# Number of nodes: 19
# Grammar pass done

{100}{}{You see a mean man.}
{101}{}{You see Captain Pierce.}
{102}{}{He appears to be in peak physical condition.}

{150}{}{Victor Presper and his party.}

# Node001
{200}{}{, the great outlaw of the wasteland. It's about time we met. Too bad you're not going to be walking away alive.}

# Node002
{230}{}{, the great hero of the wasteland. It's about time we met. Too bad you're not going to be walking away alive.}

# Node003
{260}{}{. It's about time we met. Too bad you're not going to be walking away alive.}
{261}{}{Who are you, and how do you know who I am?}
{262}{}{Who you? How you know me?}
{263}{}{You're mistaken. You're the one who's going to die.}
{264}{}{Me kill you.}

# Node004
{290}{}{. You've become quite the outlaw during your time in the wasteland. However, you also made the mistake of stepping on Presper's plans one too many times, so it's time for you to die.}

# Node005
{320}{}{. You've become quite the hero during your time in the wasteland. However, you also made the mistake of stepping on Presper's plans one too many times, so it's time you to die.}

# Node006
{350}{}{. You've been quite busy in the wasteland. However, you also made the mistake of stepping on Presper's plans one too many times, so it's time for you to die.}
{351}{}{Wait, I recognize your voice. You're that asshole from Tibbets' gym, Martin.}
{352}{}{Where *is* Presper?}
{353}{}{Where be Presper guy?}
{354}{}{Plans? What plans?}
{355}{}{Uh, what plans you say?}
{356}{}{Bring it on!}
{357}{}{Funny man die now.}

# Node007
{380}{}{Pierce. *Captain* Pierce. My employer's been watching you ever since you left Tibbets. You've become a potential threat to him, which is why you have to die.}
{381}{}{Who's your employer?}
{382}{}{Who boss man?}
{383}{}{We'll just see about that, won't we?}
{384}{}{Me not die. You die!}

# Node008
{410}{}{I'd have expected you to have heard about Doctor Presper by now. He's got great plans for the wasteland, plans which *you've* been interfering with.}
{411}{}{Where is he?}
{412}{}{What kind of "great" plans?}
{413}{}{Enough talking. Let's do this.}

# Node009
{440}{}{Somewhere else. Why does it matter? You'll be dead in a few seconds, anyway.}
{441}{}{Humor me. What plans of his have I been interfering with?}
{442}{}{We'll see about that. It's on!}

# Node010
{470}{}{Presper's going to erase the mistakes of the NCR and remake civilization into what it *should* have been after the Great War. You yourself have seen how badly the NCR's screwed everything up.}
{471}{}{You actually think Presper's going to keep you around when he's finished with you?}
{472}{}{Wait a second. I've been working towards that same goal! We're on the same side!}
{473}{}{Well, you're not going to live to see it. Let's go!}

# Node011
{500}{}{Of course. Why wouldn't he?}
{501}{}{You're a soldier - violent, unpredictable, "uncivilized". Once he's got what he wants, Presper's going to remove you just like he wants you to remove me.}
{502}{}{Forget it. Just die.}

# Node012
{530}{}{What the hell are you talking about?}
{531}{}{Presper and I have similar plans, but it's because we're not working *together* that we're getting in each other's way. I need to talk to him immediately.}
{532}{}{Never mind. Let's get this fight over with.}

# Node013
{560}{}{, I think you're right. All, right - you're not on my wrong side anymore, but it doesn't mean Presper's not going to send someone else gunning for you.}
{561}{}{Can't have that. How do I find Presper?}

# Node014
{590}{}{You know, it did seem like you were following us around, and now it all makes sense. All right, your execution's on hold until you've had a chance to straighten things out with Presper.}
{591}{}{How do I find Presper?}

# Node015
{620}{}{Holy }
{621}{}{, you're a moron. I didn't think people like you could survive in the wasteland. Oh, well. I've got a job to do and you're it. Let's get this over with.}
{622}{}{[Defend yourself]}

# Node016
{650}{}{*sigh* I've got better things to do than try to explain things to a moron. Let's get this over with.}
{651}{}{Me kill you first!}

# Node017
{680}{}{Good try, good try - you almost had me there. Now it's time for us to make some noise and put you in the ground.}
{681}{}{We'll see who gets put in the ground.}

# Node018
{710}{}{I think I'll just take my chances and deal with Presper if the time comes. But, right now, it's time to deal with you. Let's burn some clips, guys!}
{711}{}{You just made your last mistake.}

# Node019
{740}{}{We're supposed to rendezvous at a place called Bloomfield. I can show you where it is, but I can't promise Presper will be there when you arrive.}
{741}{}{Goodbye.}
