# Grammar pass done

{100}{}{You come across a trailer park from before the Great War. The red-brick building appears to have been a visitor center centuries ago. A powerful storm engulfs the region.}
