# Message file for hangdman.ssl
# Number of nodes:

{100}{}{You see an enigmatic man.}
{101}{}{You see the Hanged Man.}
{102}{}{A big part of his body has been burnt but he doesn't look like he's in pain.}

{150}{}{Send my regards to Caesar!}
{151}{}{Tribal degenerate!}
{152}{}{You're uglier than me! Get lost.}
{153}{}{Too crowded for my taste.}
{154}{}{I'd like to live just long enough to be there when they cut off your head and stick it on a pike as a warning to the next ten generations that some favors come with too high a price. I would look up at your lifeless eyes and wave like this. [He gives a mockingly cheerful finger waggle.]}
{155}{}{Judgment awaits.}

{156}{}{Sure.}

# Node001
{200}{}{There's little to say at the moment, kind stranger. I seek vengeance, and I won't rest until Caesar meets his end. Any assistance is appreciated.}
{201}{}{I wouldn't mind driving the Legionnaires out of this region. Welcome aboard, uh... what is your name, by the way?}
{202}{}{Apologies, but I have more pressing matters to attend to.}
{203}{}{Oki. What you name?}
{204}{}{Sorry, no.}

# Node002
{230}{}{My name? I am known as... the Hanged Man.}
{231}{}{Ah, of course, how fitting.}
{232}{}{Hah!}

# Node003
{261}{}{How the hell did you survive?}
{262}{}{How you live?}

# Node004
{290}{}{Am I a dream or a nightmare, perhaps? One lucky sonuvabitch mutant or the scourge of God?}

{9750}{}{The path lies before us. Let's not waste any time.}
{9900}{}{I'm good.}
{9910}{}{I'll be OK.}
{9915}{}{Ugh.}
{9920}{}{Hmm.}
{9930}{}{You'll come back. You know it.}
{9940}{}{Whatever you'd like. It makes no difference to me.}
{9950}{}{What have you to teach me of tactics?}
{9960}{}{What have you to teach me of tactics?}
{9970}{}{What have you to teach me of tactics?}
{9980}{}{What have you to teach me of tactics?}
{9985}{}{Whatever you'd like. It makes no difference to me.}
{9990}{}{Whatever you'd like. It makes no difference to me.}
{9995}{}{I'm good with firearms and cold weapons.}
