# Grammar pass done

{102}{}{A modest computer rests atop a well-maintained desk.}

{150}{}{You successfully planted the forged anonymous letter and a plastic explosive device inside the 3-Some office.}
{151}{}{This appears to be a simple computer likely utilized for 3-Some Caravan's bookkeeping purposes.}
{152}{}{It's not broken so there's nothing to repair.}
{153}{}{It doesn't seem to be trapped.}

# Node001
{200}{}{[A modest computer sits atop a well-maintained desk. It appears to be powered off.]}
{201}{}{[Place the forged anonymous letter and plastic explosive inside the desk drawer.]}
{202}{}{[Activate the computer.]}
{203}{}{[Leave it alone.]}

# Node002
{230}{}{[An animated image of the three wise monkeys greets you on the screen. Below, a welcome message reads,] "Welcome to the 3-Some Caravan Company Database. Please use the 'Tell Me About' feature to run queries."}
{231}{}{[Enter "safe combination"]}
{232}{}{[Exit]}

# Node003
{260}{}{"Please enter the correct password to proceed."}
{261}{}{[Enter "Kikazaru Iwazaru Mizaru"]}
{262}{}{[Enter "Mizaru Iwazaru Kikazaru"]}
{263}{}{[Enter "Iwazaru Kikazaru Mizaru"]}
{264}{}{[Enter "Mizaru Kikazaru Iwazaru"]}
{265}{}{[Enter "Iwazaru Mizaru Kikazaru"]}
{266}{}{[Enter "Kikazaru Mizaru Iwazaru"]}
{267}{}{[Enter "password"]}
{268}{}{[Enter "12345"]}
{269}{}{[Enter "fearsome threesome"]}
{270}{}{[Exit]}

# Node004
{290}{}{"Incorrect password entered. Intruder alert!"}
{291}{}{Oops!}

# Node005
{320}{}{"Password accepted. The answer to the query 'safe combination' is '67 - 91 - 13'."}
{321}{}{Nice!}
