{100}{}{You see a woman whose stern demeanor and commanding presence make it clear that she is in charge.}
{101}{}{You see Ailis, the owner and operator of the renowned Crimson Caravan Company. Known for her no-nonsense attitude and efficient leadership, she runs her caravans with almost military precision.}
{102}{}{She's roving frantically between some papers and ledgers.}

{103}{}{You're pathetic. If I weren't a civilized woman in a civilized town, you wouldn't live to abandon another caravan. Now get out of here.}

{104}{}{You made a big mistake to steal from the Crimson Caravan Company. You'll pay for that - with interest. For now, just get out of my sight.}
{105}{}{A thief? I resemble that remark, you damn ingrate. I'm leaving. Goodbye.}
{121}{}{Why don't we settle up right now? Prepare to die, bitch.}
{106}{}{Someday soon, you'll regret crossing me. Goodbye.}

{107}{}{That caravan was a disgrace. I'm not glad to see you survived. I can't believe that you think you'd get paid for that failure. Get out of here.}
{108}{}{You cheap bitch! You'll pay for stiffing me. Goodbye.}
{109}{}{Well, sometimes you just get luckier than others. This was one of the unlucky times. Goodbye.}

{110}{}{I'll pay you for the half-ass job you did. Here's 50 caps. Now get out of here.}
{111}{}{Well, something is better than nothing, I guess. Goodbye.}
{112}{}{You lousy bitch! Nobody could have done a better job. You'll regret stiffing me. Goodbye.}

{113}{}{Well, most of the caravan made it, even you did. Here's your 100 caps.}
{114}{}{I don't think I ever want to spend so much time looking at the ass-end of a brahmin again. Goodbye.}
{115}{}{That wasn't too bad at all. See you later. Goodbye.}

{116}{}{Good run. 150 caps for you. I don't know when we'll get someone else to run this damn caravan, but if we do, you'll have a job if you want it.}
{117}{}{Nice to find someone who appreciates quality when he sees it. See you around, maybe. Goodbye.}
{118}{}{Always glad to make some extra money. Thanks, and goodbye.}

{119}{}{I must have really been losing it. I don't know why I'd let a throwback like you tag along otherwise. Get out of here.}
{120}{}{Ook?}

{122}{}{She's not happy to see you again. She doesn't want to talk to you.}
{123}{}{You have discovered and confirmed that Ailis was Devon's Hoover Dam contact.}

{200}{}{I supervise the caravan trade here. The business is booming, and it's an opportunity I won't let slip away. Are you with us or not?}
{201}{}{So there are many traders visiting Hoover Dam?}
{202}{}{What does this caravan transport?}
{203}{}{Who are you?}
{204}{}{Sorry for bothering you. This is not the place I was looking for.}
{205}{}{Yeah, I'm looking for work.}
{206}{}{I've found something interesting that I believe belongs to you.}
{207}{}{I've planted the bombs and the fake letter as you instructed me. What now?}
{208}{}{Let's negotiate to have food regularly shipped to the village of Mesa Verde.}

{230}{}{You bet! We've got merchants from all around the wasteland coming here to exchange goods.}
{231}{}{Big plans then?}

{260}{}{Big plans? You bet, rookie. We will talk about it when you earn my trust.}
{261}{}{How do I do that?}

{290}{}{I ask for only one thing. Income. Squeeze hard, rookie.}
{291}{}{Yes, ma'am.}

{320}{}{Big plans? I want to see Governor Dodge fall flat on his face. When that happens, I'll seize the opportunity to take over Hoover Dam and shape it into a town that will be the envy of the wasteland. But first, I want to weaken Dodge and force him to step down.}
{321}{}{That's quite an ambitious plan. Do you *really* think you can pull it off?}

{350}{}{I have full confidence in myself. I've built a reputation for being efficient and ruthless. When the time comes, I'll make my move and come back to Hoover Dam as the hero who ended the war.}
{351}{}{I see. Well, I won't stand in your way, Ailis.}
{352}{}{Let's see what the authority has to say about your plans.}

{380}{}{Of course you won't stand in my way, because you're going to help me. And I'm going to help you in return.}
{381}{}{Help me? How exactly?}
{382}{}{Sorry, I'm not really interested. I was never into politics.}

{410}{}{We transport chemicals vital for gunpowder components. The tribal community Blackfoot we deal with for arms and ammunition has a coal source but lacks a reliable supply of other components. We also sometimes trade wood and brahmin with them.}
{411}{}{I have more questions.}

{440}{}{You've been a valuable asset to the Crimson Caravan Company. And valuable assets... deserve opportunities.}
{441}{}{What kind of opportunities?}

{470}{}{The kind that comes with a healthy boost in your paycheck. It's a bit of an irregular assignment, but given your resourcefulness, I trust you can handle it. There's a bit of a problem that needs to be addressed - a problem by the name of 3-Some Caravan Company.}
{471}{}{What's the issue with 3-Some Caravan?}

{500}{}{They've been a thorn in our side for too long, bad for business. If they were to suddenly fall out of favor with the NCR, we'd all be better off. Except for their and Dodge's public image. This is where you come in.}
{501}{}{So what's the plan?}

{530}{}{We need to stage a... tragic accident. [She presents two small plastic explosive devices.] This bomb here will do the trick. It's designed to kill Dorris and a few unfortunate souls, but leave Dodge unscathed. We want to make it clear that this is a direct threat to NCR's leadership. Your job is to sneak it into NCR HQ and plant it by Dodge's door.}
{531}{}{That sounds like something I can do. Then what?}

{560}{}{The second part of the plan is a little trickier. We need to plant the same kind of bomb materials in Enzo Giordano's desk, along with a note, suggesting he along with the Brotherhood was behind the bombing. I've already forged a letter from a Brotherhood commander.}
{561}{}{Anything else?}

{590}{}{Once the bombs are planted, return to me. I'll trigger the explosion remotely. Expect chaos in the aftermath. Major Fleming will start a search. We'll point him to Enzo.}
{591}{}{I understand. I'll get it done.}
{592}{}{Sorry, but I'm out. You're crazy.}

{620}{}{Good. This is a delicate operation that will mark the beginning of the end for Dodge. Discretion and stealth are key. If it goes as planned, Crimson Caravan will be the only name people trust in the wasteland. Thank you for understanding, and... make sure to keep our little secret. Come back here after you've planted the bomb and false evidence.}

{650}{}{I am Ailis McLafferty, owner and operator of the Crimson Caravan Company. Who the hell are you?}
{651}{}{I'm }
{652}{}{. I have some questions.}
{653}{}{. I'm looking for work.}
{654}{}{So long, lady. I'm not really interested in chatting right now.}

{680}{}{You came along at a good time. We're ready to go right now. The job pays 1,500 caps. You'll be assisting the caravan master directly. Use all your experience in wasteland survival to ensure timely arrival at the destination, defend the caravan and provide healing to any wounded caravanners. Ready to join us?}
{681}{}{You came along at a good time. We're ready to go right now. The job pays 1,500 caps, but I'm only paying you for the job since I only need one more caravanner. You'll be assisting the caravan master directly. Use all your experience in wasteland survival to ensure timely arrival at the destination, defend the caravan and provide healing to any wounded caravanners. Ready to join us?}
{682}{}{Sounds great. I'm ready. Let's go.}
{683}{}{I don't think I want to be a caravanner. I'll see you around. Goodbye.}

{710}{}{Alright, troops! Saddle up your brahmin, tighten those caravan ropes, and let's hit the desert dunes like we're chans storming the beaches of Alaska! Forward march, to adventure and profit!}
{711}{}{Gulp!}

{740}{}{We leave town on the 21st of every month. If you want to go with us, make sure you're here on the 21st.}
{741}{}{Alright, see you on the 21st then.}

{770}{}{How can I help?}
{771}{}{I'm interested in meeting with Governor Dodge. Could you put in a good word for me? I believe I've demonstrated my trustworthiness by now.}
{772}{}{You. What the hell do you want?}

{800}{}{What are you talking about?}
{801}{}{This ledger I found. It's filled with... interesting details about Crimson Caravan's operations. Looks like someone might have been cooking the books. Playing both sides in the NCR-Brotherhood war.}

{830}{}{How did you...? Never mind. What do you want?}
{831}{}{I think 10,000 caps sounds like a fair price to forget I ever saw this.}

{860}{}{You're one ruthless son of a gun, aren't you? Fine, here's your blood money. Now hand over the ledger and never mention it again.}
{861}{}{Funny thing, I found another ledger.}
{862}{}{Thank you for your business.}
{863}{}{You have effectively coerced Ailis into paying up using compelling evidence.}

{890}{}{You're overestimating your hand. I'll give you 5,000 caps and you'd better leave town while you still can. If I see you around after 24 hours, you won't like the consequences.}
{891}{}{Alright, I can do that for you.}
{892}{}{Forget it, you cheap has-been.}
{893}{}{You're quite a disappointment. You'd better leave town while you still can. If I see you around after 24 hours, you won't like the consequences.}

{920}{}{What the...? You double-crossing...}

{950}{}{I know you're working for our competitor, 3-Some Caravan Company. We're not interested in dealing with you.}
{951}{}{Ahh you're that ex-3-Some caravanner. I see you recovered from Vinnie's beating. That animal. Anyways, you are welcome to join us. That will surely strike a nerve with them.}
{952}{}{You used to work for our competitor, 3-Some Caravan Company. But now your loyalty lies with us, your new crimson family.}
{953}{}{Happy to be of service.}
{954}{}{You have successfully infiltrated the Crimson Caravan as a spy for 3-Some Caravan.}

{980}{}{I told you never to return here again.}

{1010}{}{Hold up there. What's all this about?}
{1011}{}{The ledger I found. It has details about some dirty dealings between the Brotherhood and Crimson Caravan.}
{1012}{}{Me found secret diary. You write love to trash cans in diary.}

{1040}{}{Let me see that... Well, well. I recognize it. This is serious. I guess we'll have to do this the hard way.}
{1041}{}{[Defend yourself.]}
{1042}{}{Wait! Do you *really* think you can take down the Major backed up by NCR Army? Think again.}
{1043}{}{Ailis dumb. Ailis think NCR weak.}

{1070}{}{Actually, yes, I do think so. Hoover Dam is mine.}

{1100}{}{*Sigh* I guess you're right. Damn you all, I just wanted what was best for us. Dodge will ruin Hoover Dam! [She continues screaming while being escorted to the nearby jailhouse.]}

{1130}{}{Hrm... Why would anyone want to meet with that idiot? Very well, I'll speak with Major Fleming about it. Just be prepared for disappointment when dealing with our "Governor."}
{1131}{}{Thank you, ma'am.}

{1160}{}{Excellent work! Here is your money, well earned I must admit. [She whips out a small denotator.] Now we do what must be done. [She presses the detonator's button and moments later you hear a loud explosion coming from the NCR HQ's direction.] Come now, let's go to the authorities and tattle on 3-Some Caravan. The Giordano triplets are done for!}
{1161}{}{Let's go, ma'am.}

{1190}{}{[She starts clapping as you enter the room.] Ah, here comes our partner in crime. Together, we're about to turn this town on its head, and they won't even see it coming. Celebrate your success, those three little pigs are no more!}
{1191}{}{I'm pleased to have been able to assist. Goodbye.}

# Node042
{1220}{}{Mesa Verde, huh? The remote tribe that no one can understand? 10,000 caps. That's our only and final offer.}
{1221}{}{That's too much.}
{1222}{}{Alright, but make sure you get there faster than a Jet addict. The Ciphers are starving.}

# Node043
{1250}{}{[Ailis produces a draft that only requires minor corrections.] Sign here and here.}
{1251}{}{[Sign the contract.]}
