{100}{}{Ladies and Gentlemen!}
{101}{}{Boys and Girls!}
{102}{}{Tonight's match is brought to you by...}

{103}{}{...Milko's General Store!}
{104}{}{When you absolutely HAVE to have something to drink and don't care what it is...}
{105}{}{Choose the General Store!}

{123}{}{...the Look Out Below!}
{124}{}{When you're thirsting for that AYAYAY hooch...}
{125}{}{Visit the Look Out Below Cantina!}

{143}{}{...Dusty's Desires!}
{144}{}{When you got that itch that you NEED to scratch...}
{145}{}{Head to Dusty's Desires!}

{163}{}{...Frieda's Firearms!}
{164}{}{When you need to punch a hole through a power armor...}
{165}{}{Come to Frieda's Firearms!}

{106}{}{In this corner, the challenger, weighing in at }
{1106}{}{ pounds, fresh from the wasteland and new to Hoover Dam, }
{2106}{}{!}
{107}{}{And in this corner... weighing in at }
{1107}{}{ pounds, you KNOW him, you LOVE him... }
{2107}{}{!}
{108}{}{So, without further ado...}
{109}{}{Let's get reeeeeeeady to BEAT SOME ASS!}

{200}{}{And the wiiiiinnnner is...}
{201}{}{...by means of knockout...}
{202}{}{...by means of technical knockout...}
{203}{}{...by means of disqualification...}
{204}{}{...with a score of }
{205}{}{ to }
{206}{}{...}

{210}{}{!!!}
