{100}{}{Looks like yet another barfly.}
{101}{}{Same drunk you saw last time.}
{102}{}{Doesn't look like the nicest of people, but with that much booze, who does?}
{103}{}{Look, I'm just drinking. Leave me alone.}
{104}{}{I don't talk much. Bad for your health in this bar.}
{105}{}{Damn cheap whiskey! You know, they serve the worst liquor here.}
{106}{}{Shit! I didn't mean to spill my drink on you. Let me clean that up. Sorry, sorry.}
{107}{}{New in town?}
{108}{}{They shouldn't never have done that. Someday stranger, I'll have a gun and then I'll show 'em.}
{109}{}{How'd you like to be my love slave, pretty?}
{110}{}{Go away, you're bothering me.}
{111}{}{Did you hear the one about...}
{112}{}{So I says to him, "Look," I says...}
{113}{}{Try the roasted mole-rat. It's the best around.}
{114}{}{Hi. What's your sign?}
{115}{}{Shit! Did you see that?}
{116}{}{Oh man, I'm going to be sick.}
{117}{}{No more for me.}
{118}{}{Hey, mix me one of those!}
{119}{}{I had a Dam Buster like that once...}
