# Message file for hdcandic.ssl
# Number of nodes: 18
# Grammar pass done

{100}{}{You see a young woman standing before you.}
{101}{}{You see Candice Morris, a dedicated school teacher and a devoted member of the Followers of the Apocalypse.}
{102}{}{She exudes an air of authority, suggesting she runs this place.}

{150}{}{You helped Candice get school attendance up to norm.}
{151}{}{You taught a class on Wasteland survival.}
{152}{}{You relayed lost Hoover Dam history to the Followers of the Apocalypse.}

# Node001
{200}{}{Hello, sir. I'm Candice Morris, a school teacher. How can I assist you today?}
{201}{}{Hello, ma'am. I'm Candice Morris, a school teacher. How can I assist you today?}
{202}{}{Hello there. You don't seem to be from around here.}
{203}{}{Uh... I think I just heard my mom calling me.}
{204}{}{Uhh... Miss Candice? Me found this... thingy. [Drop your pants.]}

# Node002
{230}{}{Haha, alright then. Have a pleasant day, sir.}
{231}{}{Haha, alright then. Have a pleasant day, ma'am.}
{232}{}{[END]}

# Node003
{260}{}{Well, about five years ago, I was living in Shady Sands and in a relationship. My boyfriend established and ran a local chapter of the Followers of the Apocalypse.}
{261}{}{Please, go on.}

# Node004
{290}{}{Unfortunately, that didn't last long. When the war broke out, the Followers quickly disbanded. I've even heard rumors that many joined other factions. My boyfriend and I tried to keep our chapter alive, but he became so devastated that he ultimately took his own life.}
{291}{}{I'm sorry to hear that.}

# Node005
{320}{}{Thank you, sir. After that, I dated an NCR soldier who turned out to be a spy for the Brotherhood, although I had no knowledge of it at the time.}
{321}{}{Thank you, ma'am. After that, I dated an NCR soldier who turned out to be a spy for the Brotherhood, although I had no knowledge of it at the time.}
{322}{}{How did you find out?}

# Node006
{350}{}{When he was apprehended and executed for high treason, I naturally fell under suspicion as well. I lost all hope and wandered into the desert, hoping to meet a terrible fate.}
{351}{}{Clearly, that didn't happen.}

# Node007
{380}{}{No. After about three days, I stumbled upon a caravan that was headed this way. That's how I found myself here. I grew tired of traveling... and running away. I needed a fresh start, and this town provided it. So, that's my story. Where are you from?}
{381}{}{Well, I hail from a city-like underground shelter abundant with marvelous technology. But now, I'm here, embarking on a journey of self-discovery, you might say. Anyway, you suggest this town is quite pleasant, correct?}
{382}{}{That's nice. I must be going now.}

# Node008
{410}{}{Wonderful! The children could learn a lot from you. Fortunately, this town attracts kind-hearted individuals. There's a bar here, but everyone maintains great self-control. I began teaching the young children at my home, you know, to contribute to society in my own way.}
{411}{}{That's interesting. Tell me more.}
{412}{}{It was nice listening.}

# Node009
{440}{}{Then, about three years ago, a caravan trader went out of business, and the government allowed me to start teaching here. Now, the school has become more successful than I could have ever imagined. However, the war is making things challenging. Our attendance numbers are dwindling. You know, once upon a time, this place was teeming with the laughter of children eager to learn. Now, it's just silence. I fear the children's education is suffering.}
{441}{}{That must be tough for you. What if I could help get the students back?}
{442}{}{I see. Good luck then.}

# Node010
{470}{}{Would you? It would mean a lot to me and to this community. Education is our only hope for a better future. However, I'm afraid we can't do much until the war is over. Yes, this is all tough. But, there's more to life than teaching, I suppose. So, I've buried myself in my books instead.}
{471}{}{Haven't you heard? The war is over, thanks to me!}
{472}{}{Ah, yes, the war is causing complications for everyone. I must bid you farewell. Goodbye.}
{473}{}{Upon further consideration, I'm not sure if that's for me. Goodbye.}
{474}{}{What's your opinion on the war?}

# Node011
{500}{}{What?! Get out of my sight, you despicable scoundrel!}
{501}{}{Despicable scoundrel? You wanna see crazy, huh?}
{502}{}{Where's your sense of humor?}

# Node012
{530}{}{It was a pleasure speaking with you. Just remember, history is our guide. We can learn from it, so we don't repeat our past mistakes.}

# Node013
{560}{}{Hey, cut it out, you butthole!}

# Node014
{590}{}{Welcome back, sir. How are you holding up?}
{591}{}{Welcome back, ma'am. How are you holding up?}
{592}{}{I've been exploring the wasteland, you know. Seen things that might pique your interest.}
{593}{}{Can I assist with the school? What if I could help get the students back?}
{594}{}{Could you tell me more about yourself?}
{595}{}{I've informed the parents that the school is open once again.}
{596}{}{Goodbye.}
{597}{}{I've come across these rare holodisks containing historical records of Hoover Dam.}

# Node015
{620}{}{I know, isn't it wonderful, sir? I already had them coming over to arrange all the paperwork.}
{621}{}{I know, isn't it wonderful, ma'am? I already had them coming over to arrange all the paperwork.}
{622}{}{Is there anything else I can assist you with?}
{623}{}{Happy to have been of help, Ms. Morris. Have a good day.}

# Node016
{650}{}{I did hear about that, of course, but I must admit, I'm a bit skeptical even though you seem capable. So, you are the one who brokered the peace agreement?}
{651}{}{Consider it done, Candice. We can now all focus on the future and continue with our lives. We'll bring learning back to Hoover Dam.}

# Node017
{680}{}{Oh? Well, that sounds exciting. You've certainly done a lot of good for us. With the school back in full swing, I would be very interested in any news you can share. Your experiences out there in the wasteland, they're invaluable. Would you consider teaching a class? Giving the children a firsthand account of survival in the wasteland?}
{681}{}{Alright, I'm in. I've learned quite a bit about surviving in the wasteland. I'd be happy to share my knowledge.}
{682}{}{Oh, certainly. That's the easy part. The challenge lies in refraining from devouring them. They're so small and sweet, like candy.}
{683}{}{I suppose I could share some stories.}

# Node018
{710}{}{Alright, sir. I have faith in you. Could you assist me by speaking to each parent and informing them that, now the fighting has ceased, they should feel secure in sending their children back to school? I will also start visiting them from today.}
{711}{}{Alright, ma'am. I have faith in you. Could you assist me by speaking to each parent and informing them that, now the fighting has ceased, they should feel secure in sending their children back to school? I will also start visiting them from today.}
{712}{}{Certainly. Time to let them know the school is open again.}

# Node019
{740}{}{It's tragic. Lives being lost over ideals and territory. It's disrupted the peace here, scared the children away from school. I just wish there was something more we could do.}

# TeachingStart
{770}{}{Wonderful! Let us begin.}
{771}{}{[Start teaching the class.]}

# TeachingEndA
{800}{}{That was enlightening. You have a gift for teaching. I'm sure the children learned a lot today. Thank you for your time.}
{801}{}{That was certainly... unique. But I can see the children were engaged. Your experiences are valuable, no matter how you express them.}
{802}{}{Well, I ain't the smartest but I told 'em how I've managed so far. So long.}
{803}{}{You are welcome. So long and good luck.}

# TeachingEndB
{830}{}{That was fine. Every real-world experience is just as valuable.}
{831}{}{Well, at least someone was listening...}

# TeachingHighIQ
{860}{}{In the wasteland, knowledge is your most powerful weapon. It can save you when bullets can't.}
{861}{}{Is it true that radscorpions glow in the dark?}
{862}{}{Not exactly. They are resistant to radiation, but it's not the radiation that makes them glow.}

{863}{}{Always know your exits. In a dangerous situation, knowing where to run can save your life.}
{864}{}{What if you can't run?}
{865}{}{Then you stand your ground. But remember, courage is not about not having fear. It's about acting in spite of it.}

# TeachingNormalIQ
{890}{}{Rule one of the wasteland: don't poke the deathclaws.}
{891}{}{What's a deathclaw?}
{892}{}{Something you don't wanna meet in a dark alley, trust me.}

{893}{}{When you're hungry, even a mole rat can look like a brahmin steak. Just make sure it's really dead before you start eating.}
{894}{}{What does mole rat taste like?}
{895}{}{Depends on how hungry you are.}

# TeachingHighIQFunny
{920}{}{Fire geckos are not your friends. They may look cute, but they're basically tiny, adorable flamethrowers.}
{921}{}{What do fire geckos taste like?}
{922}{}{A bit like deathclaw, but with a hint of self-loathing for having to eat something so cute.}

{923}{}{Always remember, the bigger the creature, the bigger the poop. Tracking is a dirty business, but it sure beats walking into a deathclaw den unprepared.}
{924}{}{Have you ever stepped in deathclaw poop?}
{925}{}{Let's just say it's a very... impactful experience.}

# TeachingNormalIQFunny
{950}{}{Never get in a drinking contest with a super mutant. Trust me.}
{951}{}{Why not?}
{952}{}{Let's just say that it's not the drinking that gets you, it's the morning after.}

{953}{}{Always check your boots for radroaches. They're sneaky little buggers.}
{954}{}{What happens if you find one?}
{955}{}{Well, you get a free breakfast, but you might need to change your socks.}

# TeachingLowCharisma
{980}{}{Ok kiddos, gather 'round. Today we're going to learn about the historical use of energy weapons in the wasteland.}
{981}{}{Is he talking to us or his imaginary friend?}
{982}{}{I don't know. But his stories are not as fun as my old teddy bear.}
{983}{}{Once upon a time, they didn't use laser rifles and plasma pistols...}
{984}{}{*yawn* Does anyone have some bubblegum? My mouth feels bored.}
{985}{}{Now, the important thing to remember is...}
{986}{}{Is it snack time yet?}
{987}{}{Not quite, but...}
{988}{}{Oh, is he still talking?}
{989}{}{Yes, and if you'd just listen...}
{990}{}{Alright, I've gotta go, Mr. Buzzy, my toy robot, needs me.}
{991}{}{...and that's why energy weapons are so... important. *sigh*}

{1011}{}{Is she talking to us or her imaginary friend?}
{1012}{}{I don't know. But her stories are not as fun as my old teddy bear.}
{1018}{}{Oh, is she still talking?}

# Dumb01
{1040}{}{*gasp* Ah, that's a... very important part of your body. You need it for peeing and also for some other things.}
{1041}{}{So... it's like a battery for... umm.. "the birds and the bees?"}

# Dumb02
{1070}{}{Well... simplifying it, yes.}
{1071}{}{Can I show it to others?}

# Dumb03
{1100}{}{No, no, absolutely not. It's very rude. It's your private part.}
{1101}{}{Oh, gotcha. So... can I drink pee?}

# Dumb04
{1130}{}{[She chuckles.] No, you really can't. Please, just don't try putting any pee in your mouth, okay?}
{1131}{}{Okay, Miss Candice. I won't show it... or drink pee... What can I charge with my battery?}

# Dumb05
{1160}{}{[She smiles, being amused.] Once you find your significant other, I am sure you'll figure it out on your own.}
{1161}{}{Cool, I'm gonna find one of them... significant others. Thanks, Miss Candice!}

# Dumb06
{1190}{}{Just... please be careful, okay? And put those pants on before someone sees you.}
{1191}{}{Yes, Miss Candice. [Wander off.]}

{1220}{}{[She smiles at you but doesn't say anything.]}

{1250}{}{Oh, that's fascinating! Hoover Dam probably has such a rich history. May I take a look at them?}
{1251}{}{Of course, here they are. I thought the Followers might appreciate having these in their archives.}
{1252}{}{Perhaps later, when I'm done with them.}

{1280}{}{This is a remarkable find. You've made my day.}
{1281}{}{I'm glad to hear that. I was hoping you might have some books in return.}

{1310}{}{Absolutely! I have a few volumes that might interest you. Here, take these.}
{1311}{}{Thank you, Candice. Let me know if you ever need anything else.}

{1340}{}{Likewise, if you ever come across more artifacts or historical documents, please bring them to us. We're always eager to expand our knowledge. Especially concerning the events of the Great War.}
{1341}{}{Got it.}
