# Grammar pass done

{100}{}{You see someone donning the unmistakable trench coat of the Hoover Dam Police.}
{101}{}{A cop.}
{102}{}{Judging by the stern expression, expect little leniency here.}

{150}{}{The NCR law states that any person found under the influence of alcohol or drugs will be arrested. Too bad for you that our prison is fully booked!}

{200}{}{Stranger.}
{201}{}{I'm on duty, stranger. I can't talk at the moment.}
{202}{}{What brings you around the Dam?}
{203}{}{HDP, how can I assist you?}
{204}{}{Don't make any foolish moves.}
{205}{}{I'm not interested in hearing cop jokes.}
{206}{}{What is your purpose in and around the Dam area?}
{207}{}{Want to hear a cop joke? Neither do I.}
{208}{}{Keep your nose clean.}
{209}{}{Hoover Dam Police, how can I assist you?}
{210}{}{Hoover Dam Police, how can I help you?}
{211}{}{HDP at your service.}
{212}{}{We don't have a large jail. Get it?}
{213}{}{Stay away from the Baseline.}
{214}{}{Stop by Downtown sometime.}
{215}{}{Welcome to civilization.}
{216}{}{Watch your back.}
{217}{}{Beware of impostors posing as police.}
{218}{}{It's a good thing we're here, keeping everyone safe.}
{219}{}{Hoover Dam is the most civilized place I know.}
{220}{}{We protect Hoover Dam and its citizens.}
{221}{}{The Dam remains secure with our presence.}
{222}{}{I bring the force to the Hoover Dam Police Force.}
{223}{}{License and registration, please.}
{224}{}{I'm on duty, citizen. I can't chat right now.}
{225}{}{Citizen.}

# fighting
{300}{}{Halt, you motherfucker!}
{301}{}{Freeze!}
{302}{}{If you run, you'll just end up exhausted in jail.}
{303}{}{I'm taking you to the slammer.}
{304}{}{You're busted!}
{305}{}{I'll blow you away!}

# pc's a cop
{400}{}{Officer.}
{401}{}{Officer, it's good to see you back.}
{402}{}{Everything all right, officer?}
{403}{}{BOLO.}
{404}{}{Stay safe, officer.}

# fleeing
{500}{}{We've got a weirdo!}
{501}{}{Unit requesting backup! Immediately!}
{502}{}{Damn, you're on fire!}
{503}{}{I thought you were a dog call.}
{504}{}{I need backup!}
{505}{}{I'll be back. With a bigger gun!}
{506}{}{Call for backup!}
{507}{}{Backup!}
