# Message file for hddodge.ssl
# Number of nodes: 76

{100}{}{You see a static portrait of a well-toned man in a suit on the small monitor.}
{101}{}{You see a static portrait of Joseph Dodge, the Lieutenant Governor of Hoover Dam, on the small monitor.}
{102}{}{This is a small intercom with a monitor for communication with the Governor inside City Hall.}

{150}{}{You wait for awhile but there is no answer.}
{151}{}{You exposed Crimson Caravan to Governor Dodge using evidence and helped Major Fleming with the arrest. Crimson Caravan is officially out of business.}
{152}{}{You successfully planted a plastic explosive device near Dodge's office.}
{153}{}{You awkwardly fumble and drop the plastic explosive device onto the floor, catching the attention of everyone nearby.}
{154}{}{You successfully cleared S1C of all hostile mutants.}
{155}{}{You successfully recalibrated the two operational power generators, enhancing their efficiency and boosting their power output.}

# Node001
{200}{}{[The static portrait fades into a live monitor feed.] Hello sir. I, Joseph Dodge, Lieutenant Governor, welcome you to the NCR Council Hall. Thank you for your service to the Republic, we need friends in these dark times more than ever. How may I help you?}
{201}{}{[The static portrait fades into a live monitor feed.] Hello madam. I, Joseph Dodge, Lieutenant Governor, welcome you to the NCR Council Hall. Thank you for your service to the Republic, we need friends in these dark times more than ever. How may I help you?}
{202}{}{Well, I've got all sorts of questions...}
{203}{}{If you don't mind, I'd like to actually get some power over the city I saved...}
{204}{}{I wanted to discuss some security matters.}
{205}{}{I've been looking into the power generators at Hoover Dam, and I believe they can be more efficient and powerful.}
{206}{}{Nothing today, thanks.}
{207}{}{Governor, I blew up the Brotherhood's base. The war is over!}
{208}{}{Beneath the Scum Pits, I stumbled upon a pre-war science lab. The catch? It's infested with hostile mutated creatures.}
{209}{}{I've successfully cleared out the pre-war science lab beneath the Scum Pits. The mutants have been eradicated, and the facility is now secure.}
{210}{}{If you don't mind, I'd like to actually get some power over the city I'm trying to save...}

# Node002
{230}{}{Oh, in that case you must speak with Major Fleming, he'll handle that.}
{231}{}{OK, I'll go see him.}
{232}{}{Major Fleming? Who's that?}
{233}{}{Yes, I did that already. I have these written ledgers here. They expose the secret dealings that Crimson Caravan had with the Brotherhood.}

# Node003
{260}{}{Our security officer and military advisor. He's doing a great job at handling our armed forces.}
{261}{}{It's good to know that there are apt people willing to join Hoover Dam and not afraid of hard work. Let me ask you some questions, though...}
{262}{}{Interesting... You say where is he from?}

# Node004
{290}{}{I've no idea, but he's a real pro. Maybe he's a renegade Ranger of some sort or was in the Enclave's army...}
{291}{}{I guess it's not that important. Let me ask you something else, though.}
{292}{}{Interesting. I better go check up on him.}

# Node005
{320}{}{Ask, and I'll do my best to answer.}
{321}{}{What are you doing here, exactly?}
{322}{}{What are the latest developments in Hoover Dam?}
{323}{}{I wanted to ask you about Hoover Dam's civil freedoms.}
{324}{}{How's the President?}
{325}{}{Have you got any new information about the other towns?}
{326}{}{Why can't we talk face to face?}
{327}{}{Actually, I've got all the answers I wanted. Goodbye.}

# Node006
{350}{}{Not really. Hoover Dam is still virtually isolated, it'll take some time before word of our accomplishments spreads to other cities. However, already some of the tribal traders have poured in, so I expect it'll improve rapidly in the next few months.}
{351}{}{When the traders arrive, will they have the sufficient infrastructure? I mean, look at the Rim, for instance. There's barely any room there!}
{352}{}{Great, great, great. I have some other questions...}

# Node007
{380}{}{Fortunately, we've already thought about that. There's a very talented deserter Scribe from the Brotherhood who'll help us with our expansion. But I can't tell you the details yet. It's a surprise hah.}
{381}{}{There's more I need to know.}
{382}{}{Whatever. See you.}

# Node008
{410}{}{What?! You haven't heard? President Tandi was assassinated by the Brotherhood! Bastards bombed the Hall of Congress in 2248. May she rest in peace. I am afraid I cannot share more details with you. Official business, you understand.}
{411}{}{Wow, that's shocking! Let me ask you about something else, though.}
{412}{}{That's terrible, Governor. I hope you will avenge her death. Goodbye.}
{413}{}{You mean may she "rest in pieces?" Daaaaaamn, I'm so funny... [You pull of your best evil grin.] Well, see you.}

# Node009
{440}{}{We're so far uncertain as to the political future of Hoover Dam. We'll have to build a system from scratch, that would satisfy both the NCR democrats and the frontier tribal oligarchy supporters... At any rate, we'll have it all figured out in the constitution.}
{441}{}{The Constitution?}
{442}{}{That's not what I wanted to know. I wanted to ask you about such things as perhaps the right to bear arms?}
{443}{}{So, for the time being everybody's free to do whatever they like?}
{444}{}{I have another query...}
{445}{}{I have to leave. Goodbye.}

# Node010
{470}{}{Well, yes. I guess we all desire a life of freedom. Plus, it's a good way to attract immigrants, sometimes known as work force.}
{471}{}{At last we are free. Bye.}
{472}{}{I have a feeling this is going to be a mess. Oh well, see you.}
{473}{}{There are more questions I need answered.}

# Node011
{500}{}{That's a different story. Since we founded NCR troops, our army, all citizens are prohibited from owning firearms. Visitors must deposit theirs for safekeeping. Everyone but the guards, who have a rifle and a side arm each, are disarmed. We may amend the Constitution later, but the present legal state is as is.}
{501}{}{I do carry weapons.}
{502}{}{My friends carry weapons.}
{503}{}{I wanted to ask you something else.}
{504}{}{So be it. I think I'll visit the gun store, goodbye.}

# Node012
{530}{}{Yes, but this is an exception. You're technically neither a resident or the enemy... Anyway, please don't keep flashing them around, OK?}
{531}{}{Gotcha. Goodbye.}
{532}{}{I'll do what I want with my guns. Capeesh?}
{533}{}{I'll try not to. In the mean time, I'd like to ask you another question.}

# Node013
{560}{}{A few members of the Followers of the Apocalypse have moved into town and are working at the Engineering Facility north of the Council Hall. They regard us as their protectors and we've already made a couple of beneficial deals with them. You may want to talk to their Chief Engineer, Pierre, he's been asking about meeting outsiders.}
{561}{}{Deals? Such as?}
{562}{}{What do you think of them? Because those people are deserters from the Brotherhood!}
{563}{}{Actually, I wanted to talk about something else...}
{564}{}{Really? I ought to talk with this Pierre fellow, then. Goodbye.}

# Node014
{590}{}{They're helping us with creating stronger and heartier wheat and corn, although they're very reluctant with sharing their technological treasures, they provide counsel and training. Also, they have helped us with other engineering and science projects, such as the water filtration and certain other constructions.}
{591}{}{Do you think they can be trusted? Because those people are deserters from the Brotherhood!}
{592}{}{That's all I wanted to know about the subject. Let me ask about something else...}
{593}{}{I think I'll go and have a look at this Engineering Facility of theirs. Goodbye.}

# Node015
{620}{}{We're at war with them, yes, but Pierre and the others're certainly better than the Brotherhood. I find it hard to believe that they're not members of the Followers. I've heard their collaboration with other communities has been very fruitful. Also, their principles, based on some sort of a 'chivalry', make sense. Of course, some of them are quite reserved, and some are more harsh, but generally, they're men to be reasoned with. If you have any strong suspicions, raise this issue with Major Jack.}
{621}{}{There's another issue I'd like to discuss...}

# Node016
{650}{}{The Constitution will contain all of the most important laws of Hoover Dam. It'll be a document of supreme legal power, and all our future bills will be based upon it.}
{651}{}{Sounds great. When are you going to get it done?}
{652}{}{You need any help writing it?}
{653}{}{Do you need one?}
{654}{}{Oh, I'll just leave you to your work, it sounds *so* important.}

# Node017
{680}{}{Once we have a draft ready, we'll ask you to review it... But until then, you must just let our lawmakers labor.}
{681}{}{I'd like to know something else...}
{682}{}{I'll just do what I want anyway.}
{683}{}{All right. I'll check up on you later.}

# Node018
{710}{}{Be patient, our initial work will take us some more time. And once it's done, I'll ask you to review it and suggest changes... Changes that'll shape the future of Hoover Dam.}
{711}{}{Perfect! It will be an honor, Governor.}
{712}{}{All right, I'll get back to you on that. In the mean time, I'd like to ask something.}

# Node019
{740}{}{I've been needing someone reliable to handle a delicate situation.}
{741}{}{I'm all ears, Governor.}
{742}{}{Oh. Anyway, it's nice of you to take me into consideration but let's change the subject.}

# Node020
{770}{}{As you're aware, we've had our share of troubles recently, what with the war and all. As a result, City Council attendance has dwindled to the point of nonexistence. We need those people back in their seats, making decisions and getting this city back on track.}
{771}{}{So you want me to round up the council members?}
{772}{}{Good to know that. Let me ask you something else.}
{773}{}{Ah well, I'm not *that* much into politics. See you.}

# Node021
{800}{}{Of course. I'll be happy to ask you to tell us your position on some important subjects when we're shaping the Constitution, but for now, there's much to do. So please let our lawmakers labor.}
{801}{}{Nevermind this issue, then. Let me ask you about a different matter...}
{802}{}{All right. I'll just walk around doing whatever I fucking like anyway.}
{803}{}{All right, I'll see you later.}

# Node022
{830}{}{Working! On everything. Fighting! The Brotherhood. We're sending messages to the nearby cities, we're arranging for traders to come into town, we're building the infrastructure, and we're working on the Constitution for Hoover Dam...}
{831}{}{Infrastructure? What about it?}
{832}{}{Have you made contact with anyone?}
{833}{}{Where are the traders from?}
{834}{}{I'm here to relieve you in... uh, governing.}
{835}{}{I wanted to know something else.}
{836}{}{Oh. I'll just leave you to your works.}

# Node023
{860}{}{Right now, we welcome caravans from nearby tribes. They've been coming here even earlier, but now they're in greater numbers. Talk to caravan masters and store owners if you want to know more.}
{861}{}{I have more questions for you.}
{862}{}{I'll go and speak with her, thanks.}

# Node024
{890}{}{I've sent envoys as far as Shady Sands, but none of them have returned yet. Are we all that's left of the NCR? I believe so. Right now, we only have steady caravans to the Blackfoot tribe and Jericho.}
{891}{}{Let's just hope they don't fall victims of bandits. Tell me something else.}
{892}{}{Well, that's a start. Bye.}

# Node025
{920}{}{Now when the powerplant is operational, I have some new great plans drawn up. But I don't want to reveal them yet.}
{921}{}{I have a feeling the Brotherhood is involved in those. Tell me about something else.}
{922}{}{Already plotting, eh? If you're planning to get into the Grand Vizier business seriously, Dodge, know that you've come to the wrong desert...}

# Node026
{950}{}{Yes. Every republic should have one.}
{951}{}{Tell me more about it.}
{952}{}{All right. Just don't screw up the job if it's so important.}
{953}{}{Bah! It's just a piece of paper!}
{954}{}{Tell me about a totally different subject.}

# Node027
{980}{}{No! It's very important! It'll shape the future of Hoover Dam! It's the most important thing I can think of giving to the city. Asides from emerging victorious in the war. But that's only a dream.}
{981}{}{Maybe you're right. Tell me about something else.}
{982}{}{Hmm... Will I be able to have any sort of influence on this Constitution?}
{983}{}{All, right, if you say so. Get back to your work, I'm not going to trouble you any more.}
{984}{}{Bah! Go back to your paperwork, bookworm!}

# Node028
{1010}{}{Well, hello sir! How may I help you?}
{1011}{}{Well, hello madam! How may I help you?}
{1012}{}{Gimme candy!}
{1013}{}{Gimme manee!}
{1014}{}{Howze Prez?}
{1015}{}{What you doing?}
{1016}{}{Bye-bye!}

# Node029
{1040}{}{Uh, I'm afraid I don't have any on me. But I heard you get a delicacy with every Weeguana children's meal at stand.}
{1041}{}{Yummy! Me go find!}
{1042}{}{Me catch own iguana.}
{1043}{}{Mebbe Prez gimme sum. Howzi?}

# Node030
{1070}{}{Umm, she's not feeling to good. Maybe it'd be best if you didn't disturb her. She lives in the heaven now.}
{1071}{}{Me just wanna say hello? Please?}
{1072}{}{All right. You got monee?}
{1073}{}{Uh, OK. Catch u later!}

# Node031
{1100}{}{Well, there's no harm in saying your hellos. But she cannot see you now.}
{1101}{}{OK. Bye.}

# Node032
{1130}{}{What? Why do you need money from me?}
{1131}{}{To buy stuff.}
{1132}{}{It shiny.}
{1133}{}{Nevermind.}

# Node033
{1160}{}{Look, I'm sure you'd found enough loot already, and if you haven't, you can find some laying around somewhere else. *Hint, Hint, Wink, Wink*}
{1161}{}{All right, me get it! Hide and seek game, me go look!}

# Node034
{1190}{}{Look, I'm sure you could find a shop to sell your excess loot somewhere here.}
{1191}{}{All right, me go sell phat lewt.}

# Node035
{1220}{}{I'm *working*, sir. Please don't disturb me.}
{1221}{}{I'm *working*, madam. Please don't disturb me.}
{1222}{}{All right, me sorry. Me go.}

# Node036
{1250}{}{What am I doing here? I'll tell you the whole story, nothing to hide from someone Major Fleming trusts. Better sit down for this one, it will take time.}
{1251}{}{Actually, I remembered that I have to be somewhere else. Maybe some other time.}
{1252}{}{Let's hear it.}

# Node037
{1280}{}{It's often said that the road to Hell is paved with good intentions. Used to think it was just a cynical saying, but lately, it's been ringing truer than ever. Back in my days with the NCR in Shady Sands, I lived a respectable life as a councilman. Had dreams of climbing higher, maybe even becoming a senator. But alas, I never quite mastered the art of networking in those elite circles.}
{1281}{}{Yeah, it's like you can do everything right and still end up overlooked.}
{1282}{}{I've heard enough. Thanks for sharing.}

# Node038
{1310}{}{I always considered myself a man of action, not one to cozy up to others for advancement. Unfortunately, my "man-of-action" approach wasn't yielding results. I never seemed to encounter any real action. Sure, one must volunteer for such endeavors, which I failed to do, but in my mind, that was beside the point. So, I resigned myself to the role of a wallflower during my tenure as councilman - until volunteers were needed for an expedition eastward.}
{1311}{}{Please continue.}

# Node039
{1340}{}{Given the tense situation with the Brotherhood of Steel, the NCR couldn't risk sending their top commanders to pioneer the eastern lands. Instead, they tapped "expendable" officers to lead caravans in establishing outposts under the NCR banner. I, Councilman Joseph Dodge, found myself among these "fortunate" few. Initially, I tried to evade this "honor," but when refusal equated to treason, I had no choice but to accept.}
{1341}{}{A difficult position to be in.}

# Node040
{1370}{}{Thankfully, my mission wasn't a blind conquest. I was directed towards Hoover Dam with a clear objective. Before the war, the dam held immense power, both literal and technological. NCR coveted that power, especially amid rising tensions with the Brotherhood. The tech at Hoover Dam rivaled, if not surpassed, the Brotherhood's arsenal - a prize too tempting to ignore.}
{1371}{}{A strategic move by the NCR.}

# Node041
{1400}{}{Upon arrival, my caravans found struggling settlers fending off constant attacks from raiders. It didn't take much persuasion to convince them of the benefits of NCR protection and organization. Hoover Dam became the focal point, with our presence ensuring safety and stability for the region's inhabitants.}
{1401}{}{Logical course of action.}
{1402}{}{Look at the time fly by, Governor. I have to go now. Goodbye.}

# Node042
{1430}{}{With the settlers' enthusiastic cooperation, we fortified the dam's perimeter, instilling a sense of security among them. Swift action against raiders bolstered their confidence in our leadership.}
{1431}{}{You certainly made an impact.}

# Node043
{1460}{}{As the Hoover Dam community flourished, it began to develop its own social structure. The Dam became divided into two distinct areas: the Rim, where government officials and affluent businesspersons resided, and Downtown, home to the hardworking construction laborers and farmers. Naturally, my NCR troops and I settled in the Rim, where I earned the title of Governor among the people of Hoover Dam. I was honored as a just and upright leader who ushered the settlers into an era of enlightenment and self-worth.}
{1461}{}{An intriguing development.}

# Node044
{1490}{}{Trouble stirred when Caesar's Legion attempted to invade Hoover Dam. The conflict was fierce, and to this day, I'm perplexed by their motives. Nonetheless, with the combined efforts of myself, the NCR troops, and the formidable defense systems, including high-powered gun turrets, we thwarted Caesar's invasion plans.}
{1491}{}{The Legion stood no chance.}

# Node045
{1520}{}{The battles left the eastern Rim in ruins, rendering it uninhabitable. Debris piled up at the center, blocking passage to the east side. Despite this setback, our victory over Caesar's Legion solidified the security of both the Rim and Downtown. However, peace was short-lived as the conflict between the NCR and the BOS erupted.}
{1521}{}{War often leaves scars that linger.}

# Node046
{1550}{}{Initially, the Brotherhood's assaults were repelled thanks to our sturdy iron gates and powerful turrets. However, as months passed, our supply routes from the NCR base dwindled. Ammunition became scarce, and I feared our defenses would crumble against the Brotherhood's advanced weaponry. It was clear we needed an alternative source of arms to stand a chance.}
{1551}{}{What did you do?}
{1552}{}{Farewell for now.}

# Node047
{1580}{}{The Crimson Caravan Company, integral to Hoover Dam's growth, stepped up to the challenge. Led by Ailis McLafferty, they ventured out in search of a new weapons and supplies route. I entrusted them with this vital task, yet...}
{1581}{}{Yet what?}

# Node048
{1610}{}{Yet, this pact with the Crimson Caravan angered their rivals, the 3-Some Caravan Company. However, their objections didn't sway me. I had reservations about the 3-Some Caravan, being led by former NCR prisoners. I couldn't risk involving them in securing weapons outside of NCR supply runs.}

# Node049
{1640}{}{Nearly six months had passed, and my men were at their breaking point. Just as we were about to exhaust our ammunition, Ailis McLafferty arrived at the main gates with a truckload of finely crafted firearms and ammunition. She claimed to have struck a lucrative trade deal with a distant tribal community known for their mechanical prowess. However, she remained tight-lipped about the tribe's location and nature.}
{1641}{}{You don't say... a gunpowder-worshipping tribe?}

# Node050
{1670}{}{With the new weapons and ammunition, we were well-equipped to repel future Brotherhood assaults. I relished the notion that the Brotherhood might be feeling the strain of prolonged conflict, their supply lines dwindling just as ours had. Perhaps, I mused, the time would come for us to seize the initiative and deal a decisive blow to the weakened Brotherhood.}
{1671}{}{Yet fate had other plans?}

# Node051
{1700}{}{Unfortunately, the Brotherhood renewed their onslaught on Hoover Dam soon after our resupply. It seemed that as our arsenal grew, so did theirs. The notion that they might be faring better in the war than anticipated crossed my mind. Regardless, it became evident that we were locked in a stalemate, a war of attrition with no clear victor in sight. As a former councilman, I recognized the futility of such a protracted conflict.}
{1701}{}{A bleak realization indeed.}
{1702}{}{Thank you for sharing your story, Governor. Farewell for now.}

# Node052
{1730}{}{With NCR's shipments ceasing entirely, we became increasingly reliant on the resources brought in by our internal caravan companies. It became clear that in order to sustain our trading relations with external communities, we needed to tap into our own resources.}
{1731}{}{Shady Sands fell silent indeed.}

# Node053
{1760}{}{For a time, I utilized a construction site that was along the center of the Rim to gather materials for both building and trading. The abundance of resources such as rebar, stone, and steel beams proved invaluable. The demand for such materials was high, so trading these resources became profitable for both the Crimson Caravan and the 3-Some Caravan companies. Yet...}

# Node054
{1790}{}{Yet, it became evident that continued exploitation of the construction site would jeopardize the structural integrity of the dam itself. I ordered all access to the site be restricted under penalty of death.}
{1791}{}{A consequence of your self-reliance.}

# Node055
{1820}{}{Once again, we found ourselves in dire straits. The Crimson Caravan's mysterious trading partner refused to engage with us without valuable trade goods. Desperate for a solution, fortune smiled upon us when a ghoul resident named Otto brought forth intriguing information.}
{1821}{}{What did Otto reveal?}

# Node056
{1850}{}{Otto, as it turns out, oversees the water purification system in Downtown. While the water isn't fit for drinking, it's perfect for agriculture. What's fascinating is that the filtration process yields potassium nitrate and sulfur - key ingredients of black powder.}
{1851}{}{Fascinating indeed.}

# Node057
{1880}{}{Additionally, nitric acid, a vital gunpowder component, is also produced, albeit in smaller quantities. These chemicals are invaluable, especially to a community with access to coal. Fortunately, the community the Crimson Caravan deals with for arms and ammunition has a coal source but lacks a reliable supply of potassium nitrate and sulfur. Thus, trade resumed, cementing the Crimson Caravan's position as the top dog with me.}
{1881}{}{So, a mutually beneficial arrangement.}

# Node058
{1910}{}{With the weapons and ammunition issue resolved, another pressing concern emerged: battle fatigue. Despite reduced Brotherhood attacks, the constant state of alert took its toll on both soldiers and civilians. Some deserted Hoover Dam in search of respite from the relentless war.}
{1911}{}{They deserted?}

# Node059
{1940}{}{Those who remained felt a growing sense of apathy, leading to system malfunctions and breakdowns. The alcohol and drug abuse are on the rise. Otto, adept at mechanical work, struggles to keep up. I realize that unless the war ends, Hoover Dam faces certain doom - whether by the Brotherhood's hands or through internal collapse.}
{1941}{}{That's quite a story, Governor. Thanks for sharing but I really have to go now.}
{1942}{}{Is there anything I can do to assist you in ending the conflict?}

# Node060
{1970}{}{War with the Brotherhood has worn us all down. Though it's only been a few years, the toll is immense. Supplies dwindle, equipment fails, and tension remains high. I find myself torn between desperation and acceptance.}
{1971}{}{A challenging position to be in.}

# Node061
{2000}{}{I'm desperate for an end to the conflict, yet I accept the grim reality of our situation. Despite attempts at diplomacy, communication with the Brotherhood has proven fruitless. We've endured relentless attacks, and while they've subsided, I fear it's only a lull before a renewed onslaught. Their base lies to the East, but its exact location eludes us. You must convince the former Scribes in the Engineering Facility of our desire for peace. But keep this from Fleming. It could escalate matters beyond control.}
{2001}{}{Understood. I'll pursue peace or perish trying.}
{2002}{}{I wish you luck, Governor. Farewell for now.}

# Node062
{2030}{}{Exactly. Let them know the war is over and it's safe to return to City Hall. They may need some... convincing.}
{2031}{}{Don't worry, Governor. I'll make sure they believe everything's back to normal.}
{2032}{}{If anyone gives me trouble, I'll handle it.}

# Node063
{2060}{}{That's what I like to hear. Good luck, and let me know as soon as you've succeeded.}
{2061}{}{[END]}

# Node064
{2090}{}{Hello again, }
{2091}{}{. It is good to see you doing well. How can I help?}
{2092}{}{Governor Dodge, the council members are back in their seats.}
{2093}{}{I've successfully recalibrated the power generators as promised. They should now operate at a higher efficiency level and produce more power.}
{2094}{}{The fires in Burham Springs should be under control. The robots at the Agricola Lab have started a fire suppression routine.}

# Node065
{2120}{}{You don't say?! Pass them through the tunnel, let me see that with my own eyes. I'll pick them up.}
{2121}{}{[Throw the ledgers through the gate.]}
{2122}{}{[Throw a frag grenade through the gate.]}
{2123}{}{[Throw a plasma grenade through the gate.]}
{2124}{}{[Throw a Molotov cocktail through the gate.]}
{2125}{}{[Throw a Mach V mine through the gate.]}
{2126}{}{[Throw a dynamite through the gate.]}
{2127}{}{[Throw a plastic explosive through the gate.]}

# Node066
{2150}{}{Well, I'll be damned. That two faced bitch! We need to sort this out immediately. I gave clear orders to Major Jack how to deal with this. Please talk to him, you've been instrumental to the discovery and should help see it through.}

# Node067
{2180}{}{That's excellent news. I knew you were the right one for the job. Thank you for your efforts. With the Council back at work, we can continue moving forward.}
{2181}{}{You're welcome, Governor. Good to see the City Hall busy again.}

# Node068
{2210}{}{Is that so? Well, I'm all ears. What do you have in mind?}
{2211}{}{With my mechanical and science skills, I can recalibrate the generators to optimize their performance. By fine-tuning their output levels and adjusting their energy distribution, we can increase power production.}

# Node069
{2240}{}{That sounds promising, but can you really do it? We *can't* afford any mistakes when it comes to the dam's power supply.}
{2241}{}{I assure you, Governor, I have the necessary skills and knowledge to handle this task. I've successfully recalibrated similar machinery before.}

# Node070
{2270}{}{Very well, I'll trust your expertise and grant you the required computer access permissions to do your work. But remember, the stability of Hoover Dam's power is crucial for our community's survival. Don't take this responsibility lightly.}
{2271}{}{I understand the importance of this task, Governor. I'll make sure to double-check everything and ensure a smooth recalibration process.}

# Node071
{2300}{}{Impressive work, my friend! Our engineers have confirmed it, we're running at 34.6% greater power output. You've proven your skill and dedication to the betterment of Hoover Dam. Our community will benefit greatly from this increased power supply. Keep it up, and soon we'll have to open an official fan club for you.}
{2301}{}{Hah! It's good to hear I'm making a difference, Governor.}

# Node072
{2330}{}{There's an issue out in Burham Springs. Fires. Been burning for years. A real hazard. We've been thinking about making it an outpost, but with the state it's in... well, it's not an option.}
{2331}{}{An outpost? Is that why you want the fires put out?}

# Node073
{2360}{}{Exactly. Burham Springs could serve as a strategic outpost. But not only that, we could resume mining operations there, giving us a valuable resource. Plus, the town could start rebuilding. It's a win-win situation.}
{2361}{}{How can I help?}
{2362}{}{Sounds dangerous. Sorry Governor, but not interested.}

# Node074
{2390}{}{Well, this is no ordinary task. The old NCR holodisk mentions dormant robots at the Agricola Lab that might be able to help. If you can get those machines running with the fire suppression module, we might stand a chance.}
{2391}{}{Alright, I'll see what I can do, Governor.}

# Node075
{2420}{}{Well, I'll be damned. You actually did it. I didn't think it was possible. As a token of our appreciation, take this. You're a real hero of the NCR, you know that? In the same league as the Vault Dweller, the Chosen One and... now you.}
{2421}{}{Thank you, Governor. It's not such a bad company to be in, I say. So long.}

# Node076
{2450}{}{It's safer this way... don't want to end up like the late President Tandi. If I die, the NCR dies. For the time being, my presence is limited to nothing more than an image on the monitor screen.}
{2451}{}{I see. Tell me something else.}
{2452}{}{President Tandi has been assassinated?!}
{2453}{}{Whatever works for you, Governor. Goodbye.}

# Node077
{2480}{}{I've heard the news.}
{2481}{}{Such a shame we lost the Major... the legend Jack Fleming! This will probably affect the morale of our troops. I wish you could have done more to ensure he's with us today.}
{2482}{}{With Ailis behind bars,}
{2483}{}{With Ailis six feet under,}
{2484}{}{and Crimson Caravan out of the picture, the war should finally turn to our advantage. Let's unite our efforts towards achieving a peaceful resolution together. Thank you, hero of the NCR.}

# Node078
{2510}{}{Godspeed, }

# Node079
{2540}{}{[His jaw drops in utter shock.] You did what?! Are you saying our tormentors are gone? The war is truly ended? The NCR emerged triumphant in the end? [He gazes into the distance, overwhelmed.] I can't believe I've witnessed this day. This victory is a testament to my leadership, and your remarkable "problem-solving" abilities, hero. You are the hero. You. [He jabs his finger towards you, reminiscent of the gesture you've seen in pre-war military posters with some old man.] And a hero deserves nothing less than the tools of a hero. I'll arrange for a Gauss rifle or a Bozar to be sent to you immediately. And a nice shack on the Rim. What a day. Historic. A day that our forefathers dreamt of, a day that our children's children will remember, a day... [He disappears from the monitor's screen.]}
{2541}{}{Thank you, Governor. A free, fancy shack is very generous of the government.}
{2542}{}{And I'll unleash Bozar on our foes with pride, knowing its bullet hell symbolizes our victory and the peace we've worked so hard to achieve together.}
{2543}{}{A Gauss rifle will be a perfect addition to my justice arsenal.}
{2544}{}{[Leave him to his own business.]}

{2570}{}{, your discovery is intriguing. We cannot allow such a valuable resource to remain overrun. Your task is clear: eliminate any threats lurking within. I regret to inform you that I cannot dispatch any troopers to assist you, as we've already suffered significant losses in the Scum Pits. The safety and prosperity of our citizens depend on your success. Your bravery will not go unnoticed.}
{2571}{}{Thank you, Governor. I'll see you later after the area is secured.}

{2600}{}{Excellent work! Your have ensured the safety of our citizens and preserved valuable pre-war resources. The Republic owes you a debt of gratitude and that's why I am granting you free use of the science lab. Naturally, our engineers will both utilize and maintain it, offering aid whenever you require it.}
{2601}{}{Thank you, Governor. I'll make good use of it.}
