# Message file for hddorris.ssl
# Number of nodes: 10
# Grammar pass done

{100}{}{You see the NCR HQ receptionist.}
{101}{}{You see Dorris, the receptionist.}
{102}{}{She's attractive, lively, and has a colorful vocabulary.}

# Node001
{199}{}{You. Again. [She rolls her eyes.] What do you want now, slubjacker?}
{200}{}{Hey there, you slubjacking piece of shit. Show me your NCR Citizenship Papers. If you don't have them, tough luck, I can't help you.}
{201}{}{Chill out, I'm an NCR Special Agent.}
{202}{}{Check out my NCR Ranger badge.}
{203}{}{Yeah, I got them right here.}
{204}{}{I just got a few questions.}
{205}{}{I don't have the Papers.}

# Node002
{230}{}{[Glances at the Papers, then back at you.] Hold the fuck on, I gotta run them through our damn database to check if they're legit.}
{231}{}{Sure thing.}
{232}{}{Actually, I'm in a hurry and don't have time to wait.}

# Node003
{260}{}{If you got any damn questions, ask someone else.}
{261}{}{I was just wondering if your old man's a mechanic, 'cause you got a fine-ass body.}
{262}{}{Yeah, whatever. Later.}

# Node004
{290}{}{Toss them over here, we'll take a damn look in a sec. [Takes the Papers and says something to the soldier approaching.]}
{291}{}{Here you go.}

# Node005
{320}{}{What the hockey puck? Who the hell are you? I know *everyone* around here, and your ass *ain't* one of them. I'll have your ass arrested right now, you dumb fucking crackpipe.}
{321}{}{Shit! Time to get the hell outta here!}
{322}{}{I didn't know what I was doing... They fuckin' lied to me... I'll spill everything...}

# Node006
{350}{}{Well, fuck me sideways, motherspanker! Ain't that a fuckin' surprise. Go on ahead and talk to Governor Dodge, I'll give you access.}
{351}{}{Thanks, I guess.}

# Node007
{380}{}{Everything's fuckin' fine. Go ahead and talk to Governor Dodge, I'll authorize your damn access. Have a fuckin' nice day, you cockgobbling shitstain.}
{381}{}{[END]}

# Node008
{410}{}{Shut your zamboni and stop pushin' your luck, you dump truck.}
{411}{}{You're no fun. I thought receptionists were supposed to be more fuckin' lively.}
{412}{}{Good advice. I'll leave you to your receptionist bullshit.}

# Node009
{440}{}{While I fuckin' prefer my job here, I'm also a goddamn soldier. And the fuckin' army ain't supposed to be a fuckin' walk in the park. Excuse the fuck outta me.}
{441}{}{Figures...}

# Node010
{470}{}{Thanks for the fuckin' funny compliment, but I'm already fuckin' taken. Now, excuse the shit outta me.}
{471}{}{Oh...}

# Floats if PC is male
{1200}{}{The fuckin' war ain't over!}
{1201}{}{Take his ass out, squad!}
{1202}{}{I ain't fuckin' goin' back into action!}
{1203}{}{We need your fuckin' ammo. Sorry, boy!}
{1204}{}{Get that fucker, he looks like a Brotherhood Pig!}
{1205}{}{Squad, get in fuckin' position!}
{1206}{}{Enemy contact! Engage that motherfucker!}
{1207}{}{Shoot him down and grab his fuckin' ammo!}
{1208}{}{You shouldn't have fuckin' come here.}
{1209}{}{Watch this fuckin' trick I picked up in the 13th Infantry Division.}
{1210}{}{Watch this fuckin' trick I picked up in the 4th Armored Division.}
{1211}{}{Watch this fuckin' trick I picked up in the 1st Marine Division.}
{1212}{}{Watch this fuckin' trick I picked up in the 2nd Cavalry Division.}
{1213}{}{Let me define FUBAR for you, dumbass.}
{1214}{}{You're gonna get fuckin' bitched.}

# Floats if PC is female
{1300}{}{The fuckin' war ain't over!}
{1301}{}{Take her out, squad.}
{1302}{}{Your fuckin' trip ends right fuckin' here and now.}
{1303}{}{Get that bitch, she looks like a Brotherhood Bimbo!}
{1304}{}{What the fuck do you want - our ammo? Waste her ass!}
{1305}{}{She won't put up much of a fuckin' fight.}
{1306}{}{It's a fuckin' shame - kill her!}
{1307}{}{Kill her and grab her fuckin' ammo!}
{1308}{}{You shouldn't have fuckin' come here.}
{1309}{}{Watch this fuckin' trick I picked up in the 13th Infantry Division.}
{1310}{}{Watch this fuckin' trick I picked up in the 4th Armored Division.}
{1311}{}{Watch this fuckin' trick I picked up in the 1st Marine Division.}
{1312}{}{Watch this fuckin' trick I picked up in the 2nd Cavalry Division.}
{1313}{}{Let me define FUBAR for you, dumbass.}
{1314}{}{You're gonna get fuckin' bitched.}
