# Grammar pass done

{100}{}{You have entered Downtown, nestled within the shadow of Hoover Dam, which towers over the river canyon. The residents here appear to be more at ease compared to those on the Rim.}

{200}{}{Nothing better than to relax after a long caravan run with buddies and a crate of beer.}
{201}{}{Guys, check out that hot redhead over there. I'm getting ALL sort of ideas.}
{202}{}{Heheheh!}
{203}{}{Hehe!}
{204}{}{Heheeeheeh!}
{205}{}{Heheeeh!}
{206}{}{Maybe I should "ask" Dusty for some freebies.}
{207}{}{Hmmm, that big ugly freak of nature is in the way.}
{208}{}{Boys, you take care of the thing and I'll keep Dusty away.}
{209}{}{Tonight's the night we kick some green ass AND get laid.}
