{100}{}{You see a weathered farmer, his clothes bearing the stains of hard labor.}
{101}{}{You see a local resident toiling away amidst the fields to feed his family.}

{102}{}{The smell of brahmin fills the air, seems worse this season.}
{103}{}{We're in dire need of expanding the irrigation system.}
{104}{}{You're swell!}
{105}{}{Your dedication is commendable. Keep it up.}
{106}{}{What can I do for you?}
{107}{}{Funny thing happened today... I was milking my brahmin, and just as I filled the bucket, she decides to kick it over with a flick of her leg!}
{108}{}{Never had a mishap.}
{109}{}{Dealing with any pesky circle flies, are ya?}
{110}{}{Care to try your luck with a lottery ticket? Grand prize is a donkey!}
{111}{}{That's just the way things go around here.}
{112}{}{There's few things worse than a constipated brahmin.}
{113}{}{The grain's ripe for harvesting.}
{114}{}{Time to earn my keep, one day at a time...}
{115}{}{I reckon we'll be getting some rain tonight.}
{116}{}{Work, work, work! Rye, rye, rye! ::sigh::}
{117}{}{Seems like it's nothing but furze and catch weed these days.}
{118}{}{Keep your eyes peeled, been some trouble with the lake monsters 'round these parts lately...}
{119}{}{Interestingly, the radiation made mantises quite vulnerable to fizzy drinks.}
