# Message file for hdginger.ssl
# Number of nodes: 12

{100}{}{You see an old, wasted woman.}
{101}{}{You see Ginger Flowers.}
{102}{}{You see a haggard woman who looks like she was rode hard and put away wet.}

{105}{}{Oh Mallet, I hate you! *SMOOCH*}
{106}{}{~~~/When I see you smile.../~~~ }
{107}{}{You are awful, wretched, selfish, egoistical, horrible, execrable, detestable, hopeless, and... and it's not at all bearable to live with you!}
{108}{}{You're my angel.}
{109}{}{YES! That's it, Mallet! I can't stand You, I HATE You! When I do not see you I do not sigh, I do not cry! You're cruel and...}
{110}{}{Mhm...}
{111}{}{I love summer rain...}
{112}{}{It's a great day, isn't it?}
{113}{}{Now that I'm a successful inhabitant of a sprawling town, I think I'm gonna get married.}
{114}{}{Isn't it a wonderful day?}
{115}{}{It sure looked pretty bad back in that robot prison.}
{116}{}{I hope there are no robo-hunters to come after us.}
{117}{}{Have you been to see the farm fields?}
{118}{}{The NCR wants to expand east.}
{119}{}{Wonder who'll Mallet fuck next?}
{120}{}{I hope the Dam will avoid the advent of crime, intolerance and bureaucracy}
{121}{}{I sometimes miss the sand dunes. }
{122}{}{Wonder if I could buy a house here... You know, for my criminal retirement.}
{123}{}{Now we can be safe from robots and the Brotherhood here!}
{124}{}{There's no place like home, right?}
{125}{}{We're safe now. And it's all thanks to Mallet.}
{126}{}{Mallet, can I have your autograph?}
{127}{}{I knew you'd succeed from the very beginning!}
{128}{}{I'm in your debt, Mallet.}
{129}{}{The gods truly favor you.}
{130}{}{I'm so glad that the prison ordeal is over. Thank you, Mallet.}

# Node001
{200}{}{What? Can't you see ol' me just tryin' to have some fun with Mallet here?}
{201}{}{I'd say Mallet is having fun with everyone except you. Don't allow yourself to be treated as a joke.}

# Node002
{230}{}{I know I ain't no beauty queen, but Mallet is all I got. He protects me. That's more than anyone else ever did.}
{231}{}{He may provide protection, but it shouldn't come at the cost of your self-worth.}

# Node003
{260}{}{Self-worth? What do I care about that? I've had a hard life, and Mallet's the only one who's stuck around. I ain't never known nothin' but hard times. Mallet's the closest thing to happiness I got.}
{261}{}{There's a whole world out there beyond Mallet.}

# Node004
{290}{}{You don't get it. I'm used to this life. It's all I know. You think it's that easy? Mallet won't let me leave. He's my protector.}

# Node005
{320}{}{I... I don't know. It's scary to think about leaving Mallet. But maybe... maybe there's another way. Who knows?}
{321}{}{Think about it, Ginger. I'll see you later.}
{322}{}{I could always kick Mallet's ass.}

# Node006
{350}{}{You could try. It will be fun to watch.}
{351}{}{Alright, step aside. This is about to get ugly. }
{352}{}{I'll think about it. Don't let Mallet go anywhere.}

# Node007
{380}{}{I've been thinkin' a lot about what you said, wastelander. You're right. Mallet ain't good for me. I deserve better.}
{381}{}{I'm glad you're starting to see that.}

# Node008
{410}{}{I won't forget. Thank you. I'm ready to start anew. Goodbye.}
{411}{}{Good luck, Ginger.}

# Node009
{440}{}{Who goes there?}
{441}{}{I just want to chat about a certain Pip-Boy you've kept since escaping Tibbets.}
{442}{}{Your executioner.}
{443}{}{Nobody. So long.}
{444}{}{Hrngh.}

# Node010
{470}{}{I ain't going back there. Why can't you all just leave me alone?}
{471}{}{I understand your fears. But I assure you, I'm not here to cause trouble. I just want that Pip-Boy.}
{472}{}{So be it, I'll take it myself.}

# Node011
{500}{}{Will you go away then?}
{501}{}{Hand it over, and you're free to go. No strings attached.}
{502}{}{No.}

# Node012
{530}{}{[She throws her Pip-Boy your way.] Just take it.}
{531}{}{Thank you, ma'am.}
