# Message file for hdmallet.ssl
# Number of nodes: 25

{100}{}{You see an intoxicated, menacing man.}
{101}{}{You see Mallet McBride, a giant of a man.}
{102}{}{He looks like he has been in one bar fight after the other. He's also completely drunk and the only person to find out that the best remedy for a hangover is to never let it catch up with you.}

{150}{}{Hey fella, care to buy me a drink? *hic*}
{151}{}{Huh?}
{152}{}{I used to be a criminal. Robbed and stole all the way..}
{153}{}{Me hate radscorpions, they sting you.}
{154}{}{I used to kill molerats as big as you, until they took my scalp off and I had to ease pain with whisky.}
{155}{}{Molerats are bad, but their meat is good. Yum!}
{156}{}{Whisky, my friend *hic* is your best friend.}
{157}{}{I did some pro boxing back in the day. *hic* New Reno, baby!}

{158}{}{Me think you are stupid and don't understand me. Go now.}

# Node001
{200}{}{[He doesn't seem happy to see you again.] You're bothering the one and only Mallet McBride. *hic* Choose your next words very, very carefully.}
{201}{}{Mallet McBride? We need to talk. I've know about your escape from Tibbets. Now you're here, causing trouble.}
{202}{}{Your mom was a brahmin called Sugar and your dad was a super mutant called Mullet. How does that sound?}
{203}{}{[Leave without saying anything.]}
{204}{}{Me hurt mullet lots.}

# Node002
{230}{}{Well, well, well, look who's decided to stick their nose where it doesn't belong. What's it to you? *hic*}
{231}{}{I'm just here to keep the peace. And from what I can see, you're sowing chaos.}
{232}{}{I'm just here representing ODYSSEUS-}

# Node003
{260}{}{Chaos? *hic* I'm just livin' life the way I want, drinkin', fightin', and having a good time with the girls here. Ain't no one gonna tell me what to do. *hic*}
{261}{}{You can't just run wild and cause harm to others. There are rules. This is Hoover Dam.}

# Node004
{290}{}{Rules? Ha! I don't give a damn about any rules. *hic* I've survived this long by doing things my way, and I ain't about to change now.}
{291}{}{You're not invincible, and sooner or later, you'll come across a tougher mofo.}

# Node005
{320}{}{Is that a threat? *hic* I've taken down super mutants with one punch. You think you can best me?}
{321}{}{I'm not looking for a fight. I'm here to offer you a chance to make things right.}
{322}{}{[Throw a punch in the general direction of his jaw.]}

# Node006
{350}{}{*hic* I've made my choices, and I'm sticking to 'em. *hic* *hic*}
{351}{}{If you continue down this path, it won't end well for you.}

# Node007
{380}{}{I've faced worse than you. *hic* You think you can scare me? I've been through hell and back. *hic* I'm a survivor.}
{381}{}{[CONTINUE]}

# Node008
{410}{}{Let's cut the crap. *hic* I ain't interested in your philosophical, redemption brahmashit. *hic* I'm gonna keep doing what I do best, and that's surviving.}
{411}{}{Well-}

# Node009
{439}{}{Watch this! *hic*}
{440}{}{Ginger, watch this! *hic*}
{441}{}{[Defend yourself.]}

# Node010
{470}{}{Cantcha fella drink in peace? I'm big and I was in jail. *hic* Stay away.}
{471}{}{Holy Esperal, what's wrong with you?}
{472}{}{What's your problem, Ethanol Breath?}
{473}{}{Where do you get your booze?}
{474}{}{I can't take the stench. Let my save myself by escaping it.}

# Node011
{500}{}{Nuthin'. Who are you, smartass?}
{501}{}{I'm }
{502}{}{. An ex-prisoner too. And I'll only let this remark pass because I know alcohol takes the clarity of judgement away from one.}

# Node012
{530}{}{Frum the bar, f'course! *hic* Aaaaaaaaand frum the distillery at the farm. From me best friend Dave. He's my friend. Who are you? I don't know you, you bum...}
{531}{}{Where is that?}

# Node013
{560}{}{I won't tell you. Go look for yourself, you lazy bugger. *hic* Who are you anyway?}

# Node014
{590}{}{Nobody talks to me like that. Eat shit and DIE!}

# Node015
{620}{}{Uh, sure. Another ex-prisoner. Imprisoned by whom? *hic*}
{621}{}{Born and bred in a huge underground prison operated by crazy robots. It must have been fate!}

# Node016
{650}{}{Uh, right, mate. *hic* Something like me, Mallet McBride, and Ginger Flowers, darling over there. *hic*}
{651}{}{So you think you've escaped them and all is well? You ain't escaped shit.}

# Node017
{680}{}{What? Look around you! We're free! Saved from certain death at the hands of the robots. *hic* Now we are protected by the NCR and can enjoy a drink at the bar! Sleep with whores! Gamble and fist-fight! Look at what we've accomplished! *hic*}
{681}{}{Right. So you think all is well, so why not invite everybody who escaped to come and live here?}
{682}{}{Sure. You talking about me or yourself? Whatever. Just go back to whatever concoction you were sipping.}

# Node018
{710}{}{Of course. *hic* The NCR is more than fond of sheltering shady strangers who wander in..}
{711}{}{..including raiders, reavers, bandits and thieves? At times of war?}
{712}{}{I invite you to get the hell off me. Goodbye.}

# Node019
{740}{}{No, of course not. Such types won't be allowed here. At least not on the Rim. *hic*}
{741}{}{And drunks, hopefully. Good-bye!}

# Node020
{770}{}{So.. *hic* so there ain't no potential thieves and wrongdoers here yet? You so sure there won't be crime? What if I commit a crime on let's say you?}
{771}{}{Every society has to cope with crime. If a problem arises, we'll have to fight it. Let me warn you, I'll fight back!}
{772}{}{Somebody give this guy more booze so he shuts up.}

# Node021
{800}{}{Right. *hic* Fight back. So you'll use violence to protect yourselves?}
{801}{}{If it's necessary, yes.}
{802}{}{I'm barely managing to resort from using violence on you. I better go.}

# Node022
{830}{}{But how can you say that, when everybody wants something else? How will you know that it was right to use violence? *hic* I sometimes wonder after beating people if that's what they truly wanted.}
{831}{}{Well, we won't know. But it's a matter of what the majority sees as right. Like not stealing from each other.}
{832}{}{Right now, I just want you to shut up. I'm out of here.}

# Node023
{860}{}{So the minority should remain poor and inopportune just because they are few and weak? *hic*}
{861}{}{No, they will be helped..}
{862}{}{You should remain silent, for a change.}

# Node024
{890}{}{Who will help them? *hic* The rich pricks that are well off already? They're basically pissing on our heads down here.}
{891}{}{The Republic will help those less fortunate on behalf of those better off..}
{892}{}{You were born in the wrong time. Two hundred years back you'd make a great demagogue.}

# Node025
{920}{}{The Republic, that's going to expand and attack others and this is what caused the horrible war in the first place. *hic* And this is whut always happunz... [He starts babbling incomprehensibly.]}
{921}{}{You know, this conversation actually made me doubt if saving everybody was worth it. A few more words with you and I'd start a killing spree. I'd get rid of you first. Sheesh.}
