# Message file for hdmark.ssl
# Number of nodes: 119
# Grammar pass done

{100}{}{You see a tall man with a friendly grin.}
{101}{}{You see Mark.}

# Betrayal
{200}{}{It didn't have to come to this, }
{201}{}{I'm a professional at this, }
{202}{}{Ugh... got to keep it together...}
{203}{}{...for Arcade.}
{204}{}{!}
{205}{}{It's an old lie, Arcade. Canis caninam non est.}
{206}{}{Hmm, where did Mark go?}

# Node001
{230}{}{[The tall man, dressed in armor, glances at you with a friendly grin. He's crouched on the ground, working on a partially disassembled rifle. His fingers expertly polish and shape each component.] Are you coming or going?}
{231}{}{I'm heading into the Dam.}
{232}{}{I'm heading out into the wasteland.}

# Node002
{260}{}{Watch your back. The Dam is no place for honest folks. Take what you need from them and leave their city behind. That's my advice. [He absentmindedly touches his forehead in salute.]}
{261}{}{[END]}

# Node003
{290}{}{Good choice. I arrived at Hoover Dam with a caravan just over a week ago. They claimed there was civilization here, and they were right to an extent. That's why I'm leaving this place as soon as possible.}
{291}{}{It sounds like you've had a rough time here.}
{292}{}{What happened?}
{293}{}{I'll remember that. See you around.}
{294}{}{I'm looking for traveling partners. Are you interested?}

# Node004
{320}{}{Well, soft beds. I can appreciate that. I thought I'd be glad to see some law and order, some military discipline. But when I saw it on the horizon, all that aluminum and makeshift walls clinging to the edge of the Old World concrete... [He shakes his head.] Maybe I've been wandering the wasteland for too long.}

# Node005
{350}{}{Not much. Bought some fresh ammunition and asked a few questions. Didn't go over well with the "civilized" types. Maybe I asked the wrong kind of questions.}

# Node006
{380}{}{Take care now. [He absentmindedly touches his forehead in salute.]}

# Node007
{410}{}{I'm interested in a traveling partner, but not an entourage. Maybe come find me once you've lost the dead weight.}

# Node007a
{411}{}{You don't seem like someone I would travel with. Sorry.}

# Node007b
{412}{}{The world will be a better place once I get rid of you.}

# Node008
{440}{}{Travel with you? Huh. I guess, given what you are, you'd be able to access places others can't. Irradiated places. Old World places. You understand?}
{441}{}{[CONTINUE]}

# Node009
{470}{}{Can't say I mind the sound of that. Traveling alone gets rough - nobody to keep watch while you're sleeping. And a man who comes walking into Hoover Dam out of the desert... well, I'd say you're probably qualified to watch my back.}
{471}{}{Can't say I mind the sound of that. Traveling alone gets rough - nobody to keep watch while you're sleeping. And a woman who comes walking into Hoover Dam out of the desert... well, I'd say you're probably qualified to watch my back.}

# Node010
{500}{}{Name's Mark. I don't like liars, murdering raider scum, or assholes who sit behind a desk and let other people do the work for them. I don't share my ration packs, and I don't want to get drunk with you. Apart from that... well, I'm not such a bad guy once you get to know me. I watch out for the people I'm working with.}

# Node011
{530}{}{When things get rough, I'm handy with a rifle. Pistols, combat shotguns. If it has a trigger, it'll fit my shoulder just fine.}

# Node012
{560}{}{As for what I'm after... well, I'm interested in exploring some of those Old World caches I've heard so much about. Abandoned fortifications, military installations. Dark, deep, and dangerous. The kind of place where a couple of sharp-eyed treasure hunters might be able to make their fortune.}
{561}{}{. Pleasure to meet you, Mark.}
{562}{}{Old World caches, huh? Just wait until you hear about the old prison swarming with lunatic robots.}
{563}{}{How about energy weapons? Laser, plasma?}
{564}{}{Actually, I've changed my mind. It's better if we go our separate ways.}

# Node013
{590}{}{. The pleasure's all mine. Anyhow, it's time we hit the road, I think. [He grins rakishly.] You know, I'm actually looking forward to this.}
{591}{}{And I think I'm looking forward to this too. Let's go, Mark.}
{592}{}{Sure, whatever.}

# Node014
{620}{}{Prison? Mister, I would surely like to hear that story while we're on the road. And maybe even visit it myself if we get the chance.}
{621}{}{Prison? Miss, I would surely like to hear that story while we're on the road. And maybe even visit it myself if we get the chance.}
{622}{}{Come on, then - let's be on our way.}

# Node015
{650}{}{After you. And maybe once we're on the move, I can hear your story for myself.}

# Node016
{680}{}{Well, I can't say I've had much experience with that sort of technology. But if it has a stock, a barrel, and you point it at somebody when you want them dead, I should be able to get the hang of it all right.}
{681}{}{Sounds like you'll be useful. Shall we go, then?}

# Node017
{710}{}{Alright, if you say so. But I won't stick around here forever. We've got a lot of ground to cover.}

# Node018
{740}{}{Back again, huh? I was just about to head out myself.}
{741}{}{I'm heading out into the wasteland.}

# Node019
{770}{}{Sorry, kiddo, move along. I don't have time to play nursemaid. [Under his breath.] This is what radiation does to their brains out here...}
{771}{}{Hungh..}

# Node020
{800}{}{You're not much of a shooter, are you, }
{801}{}{?}
{802}{}{What do you mean?}
{803}{}{I get by all right.}

# Node021
{830}{}{I can see it in your eyes every time you pick up a gun. You hold it like it's about to go off, then you stow it away in your pack and sell it to the first trader we come across.}
{831}{}{Well, maybe it *is* about to go off.}
{832}{}{I don't hear you complaining when we take in more caps.}
{833}{}{All right, point taken. What do you suggest?}

# Node022
{860}{}{[Mark fishes into his pack and removes some battered-looking, empty ration tins, placing them on the ground a little way away.] Let's do a little shooting practice. Right here, right now.}
{861}{}{I really don't think we have time for this now.}
{862}{}{OK. Just... stand behind me, yeah?}
{863}{}{Shouldn't they be closer?}

# Node023
{890}{}{Aim down the sight. That's it. Now, be prepared for the recoil. And...don't flinch when you squeeze the trigger. Just let it come naturally...}

# Node024
{920}{}{[After a few embarrassing ricochets, you manage to hit the tins three, four times in quick succession. Your shooting skills have definitely improved.]}
{921}{}{Thanks, Mark. That was a great help.}
{922}{}{Nothing to it.}
{923}{}{What's the deal with these ration packs, anyway? They look brand new. Where did you get them?}

# Node025
{950}{}{You're a good student. Well, let's pick up some more ammunition, and maybe we'll do this again sometime, huh?}

# Node026
{980}{}{[Mark stoops, quickly, and picks up the tins, stowing them away in his satchel.] I found them out west in a little NCR town. There's a trader named Dornan who had them. I don't know where he found them, but they're nice, aren't they?}

# Node027
{1010}{}{Come on. We shouldn't stay in one place for too long.}

# Node028
{1040}{}{[He shrugs.] Well, suit yourself. Just remember that talking won't always get you out of every situation.}

# Node029
{1070}{}{[He shrugs.] Well, suit yourself. Just remember that fighting won't always solve every problem.}

# Node030
{1100}{}{Some problems can't be solved with a knife, partner. But okay.}


# Node031
{1130}{}{Hey, }
{1131}{}{, who do you think is quicker on the draw? You or me?}
{1132}{}{I'd say you have the edge.}
{1133}{}{Not even a contest, old man. My barrel's smoking by the time your arthritic fingers are closing around the stock.}
{1134}{}{You're a good shot, no doubt about it. I've always wondered, who taught you to fight like that? It's impressive. I haven't seen many others in the wastes with those kinds of skills.}

# Node032
{1160}{}{Maybe we should have a stand-off someday, once all of this is over. Find a pair of water pistols and face each other down. The first one with a wet chest dies. But don't worry, I'll go easy on you.}

# Node033
{1190}{}{Anyway.}

# Node034
{1220}{}{Who, uh, taught me? Partner, I could ask you the same question. We're self-taught gunslingers, the both of us. [He looks away.] The first time you shoot a man dead, it's to save your own life. You keep on killing, you keep on surviving. And you get better at both.}

# Node035
{1250}{}{Until maybe one day you come up against someone who's better at killing, someone who's better at being the one who walks away.}
{1251}{}{That's a good time to have a friend by your side who's just as quick on the draw, then.}
{1252}{}{Not me, partner. I intend to live forever.}
{1253}{}{That's not exactly what I meant. It's the way you move, how you hold your gun. Very precise, almost robotic. It's like you've been trained.}

# Node036
{1280}{}{True enough. If you ever see me facing a man who's more than my equal, }
{1281}{}{, heroically staring him down like one of those cowboys from Old America, facing my own death with quiet courage and dignity... well, you're welcome to shoot him in the back of the head before he has a chance to take me down.}

# Node037
{1310}{}{Well, that's something we all hope for, isn't it? No matter how deluded or wrong it may be.}

# Node038
{1340}{}{What I'm afraid of is being left out in the desert or some Old World hellhole, unburied, unmourned, left for the mutated scorpions or the coyotes... That's why if I ever face someone who's more than a match for me, I hope they have the decency to dig me a grave and leave a marker. "Here lies a man."}

# Node039
{1370}{}{This conversation got maudlin fast. Come on, partner. Let's keep moving.}

# Node040
{1400}{}{Trained? No, sir, no formal training to speak of. I mean, we had a militia back home, a couple of old boys who gave us some marching orders. In a sense, you could say Enrique and Tom provided us with some training, though it's surprising how much it helped us in the end.}
{1401}{}{Trained? No, ma'am, no formal training to speak of. I mean, we had a militia back home, a couple of old boys who gave us some marching orders. In a sense, you could say Enrique and Tom provided us with some training, though it's surprising how much it helped us in the end.}

# Node041
{1430}{}{Hold on, you're injured.}
{1431}{}{I've had worse. Let's get to the next town and find a doctor.}
{1432}{}{Give me a moment to rest- Aarhgh! And I'll be fine.}
{1433}{}{[Grin bloodily at him.]}

# Node042
{1460}{}{Sit down for a moment. I have some Med-X and bandages in my satchel. Don't squirm like that, damn it.}
{1461}{}{I don't like needles, that's all.}
{1462}{}{Are you really qualified to perform first aid, Mark?}

# Node043
{1490}{}{My wife is a doctor. She taught me a few things. Although she never lets me assist her, claiming my fingers are too clumsy. That was just a joke - no need to scowl at me like that.}

# Node044
{1520}{}{That's how I met her. I was fighting with some other lads when I was sixteen. One of them got a good hit above my eye, right here - you can still see the scar. She rushed out of the infirmary with a first aid kit and jabbed a stimpak right into my arm. It hurt worse than the punch, but I could see the fear in her eyes, her steady hand, and her trembling lip. I knew right then that she loved me.}
{1521}{}{Where is she now?}
{1522}{}{If you're done fucking reminiscing, I think I'm about to bleed out here...}

# Node045
{1550}{}{She's back home, to the west. Hopefully waiting for me. She didn't want me to come out this way, thinking no good could come of it. Then there's our little boy. We had our first real argument about it. But duty called, and they needed to be taken care of.}
{1551}{}{You should go back to her, Mark.}
{1552}{}{You have a son?}

# Node046
{1580}{}{I will. There's nothing I want more. Just need to finish our business here first.}

# Node047
{1610}{}{He'll be two years old next month. Catherine insists on teaching him herself - languages, sciences, history. She has it all planned out. I think she's worried I'll raise him to be like me, all rough edges and no learning.}

# Node048
{1640}{}{She doesn't need to worry. I'll be proud of him. I may not turn out to be the best father, but I can do that much... as long as I make it back, anyway.}

# Node049
{1670}{}{Almost done. Hold still now - this might sting...}

# Node050
{1700}{}{Sorry, sorry. Okay, here we go. Hold still now...}

# Node051
{1730}{}{There, you're already looking better. Let's get you back on your feet.}

# Node052
{1760}{}{Listen, I just want to make sure we're on the same page here. Are we going after Presper, no matter what? We're taking him out, no matter the obstacles.}
{1761}{}{Well, it's that or die. I don't see any other choice.}
{1762}{}{Of course, we're going after him.}
{1763}{}{Why are you so concerned about him? I'm the one he tried to kill, not you.}

# Node053
{1790}{}{Sweetest words I could ever hear. So let's get to it, partner. We have a long way to go before we face that bastard.}

# Node054
{1820}{}{Why am I so concerned? Shit, }
{1821}{}{, we all have people we care about down here. Don't you think about them?}

# Node055
{1850}{}{Do you really think Presper will wait around while you're wandering across the wastes, fixing broken junk and trading gecko skins? We need to move faster if we want to catch up to him. Otherwise, we'll lose him.}

# Node056
{1880}{}{I... you're right. Let's keep moving forward, at least.}

# Node057
{1910}{}{Have you ever witnessed anything like that? When the old robot blew itself up? Have you ever seen such a sight before?}
{1911}{}{I was too busy running to pay much attention.}
{1912}{}{It was quite something. For a moment, I thought we wouldn't make it out of there alive.}

# Node058
{1940}{}{The intense heat and the blinding light, it felt like the sun had fallen to earth.}

# Node059
{1970}{}{The Old World, the Old America, held that power in its hands for centuries and chose not to use it. That's true strength, you know. That's real strength.}
{1971}{}{But in the end, they did use it.}
{1972}{}{Human nature doesn't change. Once they possessed that power, it was only a matter of time before someone pressed the button.}
{1973}{}{Are you suggesting I should go scout for nuclear bombs to add to my collection?}

# Node060
{2000}{}{Yeah, well... sometimes extreme measures are the only ones left. You probably understand that better than anyone, partner. Let's keep going...}

# Node061
{2030}{}{[Mark stares at you for a moment.] Ha, ha. No, I... knowing my luck, I'd probably blow myself up and create more of those damn six-feet scorpions.}

# Node062
{2060}{}{Anything on your mind, partner?}
{2061}{}{Can I ask you a few questions, Mark?}
{2062}{}{Can you show me your best weapon next time we're in combat?}
{2063}{}{I'd like us to stand closer together during our travels.}
{2064}{}{Stay here for now.}
{2065}{}{Nothing, just making sure you're still with me.}

# Node063
{2090}{}{Sure, what's on your mind?}
{2091}{}{Who are you really, Mark?}
{2092}{}{Do you have any issues with what I am?}
{2093}{}{Where are you from, Mark?}
{2094}{}{Any thoughts on what we should be doing?}
{2095}{}{Tell me a little about yourself.}
{2096}{}{Why don't you drink? Is it a religious thing?}
{2097}{}{You seemed startled by that deathclaw. Hadn't you heard of them before? I thought everyone in the wastes knew about them.}
{2098}{}{Never mind. Let's keep moving.}

# Node064
{2120}{}{I, uh... what was that?}
{2121}{}{You know what? Never mind.}
{2122}{}{Come on, let's be honest with each other. I can tell you're not just an ordinary wasteland mercenary. Your skills and knowledge give it away. You're highly trained, probably by some kind of military organization. Your eyes light up every time we enter some Old World nuclear site. I want to know more about your background and who you really are.}
{2123}{}{Funny thing about traveling together. You start noticing the little details, like the way you hesitate when you're not being entirely truthful. You're more than just a wasteland hick.}

# Node065
{2150}{}{I... all right, fine. Come on, then.}

# Node066
{2180}{}{Listen, }
{2181}{}{, I, uh, I don't know what you're talking about. But one thing's clear to me: if we can't trust each other, this partnership won't work. So if you're going to keep playing games, maybe it's best we part ways right now.}
{2182}{}{Hold on. We're not going anywhere until we have an honest conversation.}
{2183}{}{Fine, go ahead and leave. But if I see you following me, it won't end well for you.}

# Node067
{2210}{}{Damn it. I didn't expect it to come to this, }
{2211}{}{.}

# Node068
{2240}{}{[Mark glares at you, shoulders his pack, and walks away without another word. He doesn't look back.]}

# Node069
{2270}{}{A problem with...[He hesitates.] Does it seem that way?}
{2271}{}{Yeah, it's pretty obvious. You may not say anything, but I can tell.}
{2272}{}{Sometimes you flinch, like you're uncomfortable.}

# Node070
{2300}{}{I didn't mean to offend. I apologize if it came across that way. The truth is, the wasteland has changed everyone and everything. The effects of the fallout and FEV are evident in every living being out here. You may display it more visibly, but you're no different from anyone else struggling to survive in this harsh world. Sometimes it's just not easy to witness.}
{2301}{}{That's an interesting perspective - everything being mutated.}
{2302}{}{I'm not ashamed of what I am, Mark.}
{2303}{}{Considering how long you've lived in the wasteland, I'm surprised you haven't encountered more ghouls and super mutants.}

# Node071
{2330}{}{I guess I'm a philosopher at heart.}

# Node072
{2360}{}{Come on, now. I promise I'll be more considerate. I'll try to adjust my behavior around you.}

# Node073
{2390}{}{And you shouldn't be. You are who you are, and it's not your fault. You bear the marks of the War, and there's no escaping that reality.}

# Node074
{2420}{}{Well, uh, you know, where I come from, there weren't many people like you. The village elders didn't take kindly to your kind, so it's still something I'm adjusting to in my own way.}

# Node075
{2450}{}{Me? Oh, I come from a small village up in the hills to the west. It's a humble and rather unremarkable place, much like any other you'd find around here.}

# Node076
{2480}{}{We need to finish that rocket, and fast. Presper is up there, mocking us.}

# Node077
{2510}{}{We must find a way to stop that old man. It's hard to say how much time we have left.}

# Node078
{2540}{}{We should explore and discover Old World locations. That's our best bet for securing resources.}

# Node079
{2570}{}{As for me, I'm just an ordinary person, partner. I've had my fair share of hardships, like anyone else. Tough upbringing, with a father who believed in discipline. I grew up learning how to handle a pistol, ventured out into the world, and started learning from experience.}

# Node080
{2600}{}{I know, you might have expected a grand story, but some of us are just regular folks trying to survive the best we can. Life is often a series of struggles and muddling through for most people.}

# Node081
{2630}{}{Of course, considering I was imprisoned by an Old World robot and then thrust into the wilderness, I can understand why you might think everyone has a similar tale to tell. Heh.}

# Node082
{2660}{}{No, I'm not one of those New Canaanites, if that's what you're thinking. I simply choose not to drink. I've witnessed firsthand what it can do to a person. It slows you down, makes you foolish, and encourages words best left unsaid.}

# Node083
{2690}{}{My father used to drink back home, and those were unpleasant days, to say the least. So, you go ahead and enjoy yourself, but I'll stay sober, thank you very much.}

# Node084
{2720}{}{Hm? Oh, ah, no. You know how it is. I had heard of them, sure... but I wasn't prepared for it. When it came charging at us like that... it felt like something out of a nightmare, like a creature from the depths of hell.}

# Node085
{2750}{}{Look, I'm sorry. I didn't mean to react like that. It won't happen again, I promise.}

# Node086
{2780}{}{I'd be glad to help, as long as we're not wasting precious bullets on cave rats.}

# Node087
{2810}{}{All right, sounds good.}
{2811}{}{Stick close and cover my back.}
{2812}{}{Maintain some distance. We'll be more effective if we spread out.}

# Node088
{2840}{}{Understood.}

# Node089
{2870}{}{Right here? Okay, I'll set up camp for now.}

# Node090
{2900}{}{Hold on, }
{2901}{}{. You're not getting on this rocket.}
{2902}{}{What's your plan?}
{2903}{}{Mark? I almost didn't recognize you in that armor.}

# Node091
{2930}{}{There's no need for things to turn ugly. Just stay back and don't interfere, and I won't harm you.}
{2931}{}{After all we've been through, you're turning against me? You're going to let Presper win?}
{2932}{}{All right. You have the gun. You're in charge. What's the next move?}
{2933}{}{So, you're finally showing your true colors. Who are you really, Mark? Is that even your real name?}
{2934}{}{Do you honestly think you can take me down with that rifle before I wrap my hands around your throat?}

# Node092
{2960}{}{I won't let Presper succeed, don't worry. But once he's gone, the Enclave will take control of B.O.M.B. Its missile arsenal will be the spark to reignite the United States of America - the fire that purges the wasteland.}

# Node093
{2990}{}{I'm truly sorry about this. When we first met, I thought you could help me get closer to Presper, maybe uncover his plans. But I never expected you to make it this far. I never imagined a mutant could be so resilient, so cunning.}
{2991}{}{At least I'm smarter than you. I've installed a fail-safe in the rocket's launch sequence activator. It requires a password, one I personally chose. And if someone enters the wrong password... the engine fuel will detonate.}
{2992}{}{What do you mean by "a mutant"?}
{2993}{}{Mark, you have a son. Think about him. Don't do this.}
{2994}{}{I'm sorry, Mark. I don't want to harm you, but you're leaving me no choice.}
{2995}{}{You'll be even more impressed in a few seconds when you're lying there, bleeding and in excruciating pain. I'll step into my rocket-ship and soar away, leaving you behind.}

# Node094
{3020}{}{I... uh... oh.}
{3021}{}{You're not going anywhere, Mark. The only person boarding that rocket is me. Stand down.}

# Node095
{3050}{}{Give me the password, }
{3051}{}{. I'm... I'm only asking once. Time is running out. Please give me the password.}
{3052}{}{I refuse.}
{3053}{}{Suck. My. Dick.}
{3054}{}{You can go fuck yourself, Mark.}

# Node096
{3080}{}{GIVE ME THE FUCKING PASSWORD!}
{3081}{}{Why don't you try and take it from me?}
{3082}{}{You know I can't do that.}

# Node097
{3110}{}{Then you leave me no choice. I'll *make* you give it to me.}

# Node098
{3140}{}{You're a mutant, infected. The bacteria, the diseases, the FEV, radiation, the New Plague - they've consumed you. You're not human anymore, and you don't even know it. You've become a half-creature, bearing the sickness of the New World on your shoulders, limping into the darkness propelled by nothing more than blind instinct.}
{3141}{}{And you aren't? You've been breathing the same air as me.}
{3142}{}{So, your solution is to wipe us out? The infected, the impure? Do you honestly believe we deserve that fate? Mark, you've walked among these people. You've seen their struggles. Don't some of them deserve to live?}
{3143}{}{I don't think you can be persuaded out of your beliefs. Well, neither can I. Go for your gun, you treacherous bastard.}

# Node099
{3170}{}{I understand. When I volunteered, I knew there wouldn't be a place for me in the new America. I've willingly exposed myself to the dangers of the wasteland, breathed in the tainted air. But it doesn't matter. My son and wife will be there. I've saved them.}

# Node100
{3200}{}{I'm doing this for my son. Can any good father bear to see his child grow up in such a brutal world? Where hideous beasts roam and people kill each other for survival? This isn't what America was supposed to be. We're the last ones who remember that.}

# Node101
{3230}{}{No. My son deserves more than to live in the faded remnants of the Old World. He deserves safety, comfort, and a sense of purpose. He deserves America.}
{3231}{}{Do you think he'd want his father to be a murderer? Do you think he would thank you for giving him America, knowing the price that was paid in innocent lives?}
{3232}{}{Your son will grow up without a father, Mark. That's a promise.}

# Node102
{3260}{}{Enough, }
{3261}{}{. Do you think I can't see through your manipulative tactics? Your words won't get you out of this. Not this time.}

# Node103
{3290}{}{Of course, I regret what's about to happen. It's terrible, but it's necessary. It's a wound that must be cauterized. If we are to rebuild America, sacrifices must be made, even the lives of mutants and the infected. We must cleanse the world of the stain left by the War in every aspect.}
{3291}{}{That's utter bullshit, Mark. You don't even believe it yourself. You've seen the people out here, and I'm willing to bet they're just like your family back home. Sometimes scared, sometimes selfish, but they are rebuilding with what they have, and they deserve a chance.}
{3292}{}{If you truly believe in this new world, Mark, then you must see that it can't be built on the deaths of innocent people. Do you think you can start fresh? Your America will be born in blood, and it will never be free of that stain.}
{3293}{}{Once I considered you a friend, Mark. Now, you're just another fool with a gun, and you're standing in my way. Draw.}

# Node104
{3320}{}{You don't understand. If you could have witnessed it yourself - the grand oil rig, vertibirds circling, the speakers playing the old songs, the cheers of the crowd. And then Richardson spoke... he spoke of the glory of the old flags, the old ways, the proud pine forests and the cities of steel and glass...}

# Node105
{3350}{}{...but when we set foot on dry land, all we found was ashes, darkness, and fire. America had abandoned us.}
{3351}{}{That was a dream, Mark. It was always a dream. Presper let himself be consumed by it, and now he's forgotten the lesson of what happened to America. He plans to set off the bombs again, and the world will be consumed by flames once more. Unless you let me stop him.}

# Node106
{3380}{}{I... I...}

# Node107
{3410}{}{"...thus be it ever, when free men shall stand between their loved home and the war's desolation." You win, }
{3411}{}{. The rocket is yours. Take it while you can. Find Presper and stop him. I just hope... did you hear that?}
{3412}{}{Vertibird engine. Someone's outside.}
{3413}{}{Fuck! Presper's men must've found us.}

# Node108
{3440}{}{Get in the rocket, }
{3441}{}{. Hurry. I'll create a defensive line at the doors and hold them off there. They won't reach you before it launches... I promise.}
{3442}{}{You can still come with me, Mark. I could use your help.}
{3443}{}{Are you sure about this?}
{3444}{}{All right. Take charge, Sergeant.}
{3445}{}{Make those bastards bleed, Mark.}

# Node109
{3470}{}{I won't go home without B.O.M.B. And since I'm letting you take the rocket... well, that means I won't be going home. It's better if I end it here.}

# Node110
{3500}{}{In parting, let me say that it has been a true honor and privilege to serve alongside you.}
{3501}{}{Likewise.}
{3502}{}{And a hell of a lot of fun, too.}
{3503}{}{Enough with the sentimental stuff. I'll see you again soon.}

# Node111
{3530}{}{Yeah. Yeah, it certainly has been.}

# Node112
{3560}{}{Perhaps so.}

# Node113
{3590}{}{Thanks, }
{3591}{}{. Thanks for talking your way out of it.}

# Node114
{3620}{}{No! DON'T DO IT!}

# Node115
{3650}{}{Now I'll get in the rocket, and you stay right here without trying anything funny.}

# Node116
{3680}{}{The first rule they taught us in training: Make sure your lie contains enough truth to be believable. My name is Sergeant Mark Gannon, from Navarro.}

# Node117
{3710}{}{. Don't do it.}
{3711}{}{Let's find out. Try to kill me if you can, you son of a bitch.}

# Node118
{3740}{}{Go ahead, get inside. There's no time for long goodbyes.}

{9750}{}{Finally.}
{9900}{}{I'm good.}
{9910}{}{I'll be OK.}
{9915}{}{Ugh.}
{9920}{}{Hmm.}
{9930}{}{I'll see you later then.}
{9940}{}{I hope you have a plan.}
{9950}{}{Sure.}
{9960}{}{Sure.}
{9970}{}{Sure.}
{9980}{}{Sure.}
{9985}{}{This is what I have.}
{9990}{}{I hope you have a plan.}
{9995}{}{I'm good with firearms. Standard ammunition or energy cells. And I know how to handle cold weapons too.}
