# Grammar pass done

{100}{}{You spot a man selling lizard kebabs.}
{101}{}{Ah, the lizard-on-a-stick vendor.}
{102}{}{He's diligently promoting Son of Bob's Iguana Bits, an NCR vendor food franchise.}
{103}{}{Feeling hungry, stranger? I've got the finest lizard in town. Just ask around!}
{104}{}{What can I get for you?}
{105}{}{Meat, please.}
{106}{}{I'll take one.}
{107}{}{Can you tell me more about this town?}
{108}{}{Goodbye.}
{109}{}{Enjoy your meal, stranger!}
{110}{}{The mustard and onions are right over there.}
{111}{}{Hey, buddy.}
{112}{}{Okay, bye.}
{113}{}{Next!}
{114}{}{Look, I have a rule. I don't talk about anyone. It's a good rule because if I keep quiet, I stay out of trouble. Got it?}
{115}{}{I don't hear anything, I don't see anything, and I certainly don't say anything. Now, quit pestering me about it.}
{116}{}{Fine. Look, I'm hungry.}
{117}{}{Is that a pet gecko?}
{118}{}{Sorry for bothering you, for goodness' sake!}
{119}{}{Yeah, that's Lizzie, our mascot. She's a silver gecko pet. Harmless, but still, be careful not to get bitten. She might mistake you for something edible if you get too close!}
{120}{}{I'm still hungry.}
{121}{}{Well, thanks for very little.}

# floats
{200}{}{Serving up Iguana Bits so good, you'll forget they're sometimes not the real thing!}
{201}{}{Iguana Bits: the perfect snack for your cravings!}
{202}{}{Taste the NCR with our savory Iguana Bits!}
{203}{}{For a taste that's out of this world, try our irradiated Iguana Bits!}
{204}{}{Iguana Bits: the crunchy, protein-packed treat for every citizen!}
{205}{}{Get your daily microdose of radiation with every bite of our delicious Iguana Bits!}
{206}{}{From the depths of the nuclear wasteland to your plate: fresh, fried Iguana Bits!}
{207}{}{Surviving the NCR-Brotherhood war never tasted so good - thanks to the Son of Bob's Iguana Bits!}
{208}{}{For a quick, satisfying meal, grab a bag of the Son of Bob's famous Iguana Bits!}
{209}{}{Iguana Bits: the ultimate comfort food in a world gone bust!}
{210}{}{Sink your teeth into the legendary crunch of the Son of Bob's Iguana-on-a-stick!}
{211}{}{When life gives you mutated lizards, make some Iguana Bits!}
{212}{}{Son of Bob's Iguana Bits: absolutely no connection to Bob from "Hock-it to Bob" bounty hunting agency!}
{213}{}{Experience the fusion of flavor and survival with the Son of Bob's signature Iguana-on-a-stick!}
{214}{}{Son of Bob's Iguana Bits: because in the Republic, every bite counts!}
{215}{}{Satisfy your hunger and your curiosity with the Son of Bob's exotic Iguana-on-a-stick!}
{216}{}{For an adventurous meal, try the Son of Bob's Iguana Bits!}
{217}{}{Discover the secret to satisfaction with the Son of Bob's Iguana Bits!}
{218}{}{Indulge in the nostalgia of pre-war cuisine with the Son of Bob's timeless Iguana Bits!}
{219}{}{When the world goes to hell, the Son of Bob's Iguana Bits remains!}
