# Grammar pass done

{100}{}{You descent into the morgue, the flickering light reveals bodies not only crammed into every available drawer but also laid out on the cold, tiled floor, their coverings stained with bodily fluids. The sterile smell mixed with the stench of death creates an overwhelming sense of despair.}
