# Grammar pass done

{100}{}{You see a ghoul in oil-stained working clothes.}
{101}{}{You see a ghoul mechanic.}
{102}{}{You see Otto, the grease monkey from a faraway land. He's a real miracle worker.}
{103}{}{You see the chief engineer in Downtown.}
{104}{}{Wie geht es dir? How is it going? What can Otto do for you, herr?}
{105}{}{Who are you?}
{106}{}{It's going well. What is this place?}
{107}{}{It's gotta be going, and so am I.}
{108}{}{Otto is a mechanic. Makes sure every engine and maschine here is shiny, oiled, and always working well.}
{109}{}{An important job, I'd better not interrupt you.}
{110}{}{What machines do you have here?}
{111}{}{Can you tinker with anything of mine?}
{112}{}{I have this lurking suspicion that we might have met before?}
{113}{}{I've got to go.}
{114}{}{This - this is Otto's workshop. Here Otto Steed works with stuff all day long and earns his bread.}
{115}{}{No, no, you stay all the time you want to, Otto is in no hurry. In fact, it's nickerchen time again.}
{116}{}{If you say so. Could you have a look at my hardware?}
{117}{}{Otto's got everything: intake towers, screens, strainers, pumps, chemicals, tanks, clarifiers, filters, membranes, disinfectants, instruments, drills, torches, multimeters, pliers - He's even got an incomplete Hydroelectric Magnetosphere Regulator!}
{118}{}{What's a Hydroelectric Magnetosphere Regulator?}
{119}{}{Otto is sorry, but he's got an awful lot of arbeit to do. No time. Try again later.}
{120}{}{Aw, come on. Can nothing be done?}
{121}{}{OK. See you.}
{122}{}{Sure mann. Anything. No charge, too. What do you have for Otto? A rifle, a pistol or revolver, an armor, a melee weapon, a heavy weapon?}
{123}{}{A rifle.}
{124}{}{A pistol or revolver.}
{125}{}{An armor.}
{126}{}{A melee weapon.}
{127}{}{A heavy weapon.}
{128}{}{Nothing right now.}
{129}{}{OK, what rifle would it be? What's your wish?}
{130}{}{Expand the magazine on my Assault Rifle.}
{131}{}{Put a laser sight on my FN FAL.}
{132}{}{Put a scope on my Hunting rifle.}
{133}{}{Amplify the capacitors on my Laser Rifle.}
{134}{}{Hotwire my Plasma Rifle.}
{135}{}{Saw off my Shotgun.}
{136}{}{OK, what pistol or revolver would it be? What's your wish?}
{137}{}{Expand the magazine on my Desert Eagle.}
{138}{}{Put a speed loader on my Magnum.}
{139}{}{Put a magnetic chamber on my Laser Pistol.}
{140}{}{Amplify the capacitors on my Plasma Glock.}
{141}{}{OK, what armor would it be? What's your wish?}
{142}{}{Brush up my Metal Armor.}
{143}{}{Upgrade my Combat Armor.}
{144}{}{Give a hardening treatment to my Powered Armor.}
{145}{}{OK, what melee weapon would it be? What's your wish?}
{146}{}{Uhm - could I have my Spear sharpened?}
{147}{}{Upgrade this cattle prod.}
{148}{}{Upgrade this Power Fist.}
{149}{}{OK, what heavy weapon would it be? What's your wish?}
{150}{}{I want you to give more punch to my flamethrower.}
{151}{}{Here you go. It will now carry a hundred slugs in one mag. Hope it's enough.}
{152}{}{Thanks! I'll try not to fire it all on one opponent.}
{153}{}{Here you go. It should be much easier to target enemies in the dark now.}
{154}{}{Thanks! Those tunnel rats better beware now.}
{155}{}{Otto's done it. Remember, it'll only be useful at long range.}
{156}{}{Thanks! Hunting's never been so much fun.}
{157}{}{Here. Otto's made it so it'll now carry twice the charge before you need to reload.}
{158}{}{Like a Vault Boy. Got it. Thanks!}
{159}{}{Otto's given it some extra kick, the plasma ought to be hotter and more damaging now.}
{160}{}{Now they'll go down just like this: zap! Thanks.}
{161}{}{Here. It'll be more effective at close quarters, but sacrificing the power at long range.}
{162}{}{Whatever. It's the feel that counts. Thanks!}
{163}{}{All done. Holds 20 bullets now.}
{164}{}{There's never too many. Thanks!}
{165}{}{There. It'll be twice as fast to replenish the ammunition.}
{166}{}{It's feeling cool already. Thanks!}
{167}{}{Otto really don't see how this could be useful.}
{168}{}{It will come in handy, trust me. Bye.}
{169}{}{Here. Otto's refitted those crude linkings and polished it up a little.}
{170}{}{Now that's what I call shiny. Thanks!}
{171}{}{Here. Otto's fitted it with additional plates and dissipater layers. Like to see anything pierce through that!}
{172}{}{I know I wouldn't. Thanks!}
{173}{}{Sure. Why not?}
{174}{}{I don't know. It's a weapon. Thanks!}
{175}{}{You planning to start a ranch?}
{176}{}{Not at all. Thanks!}
{177}{}{No problem. Just don't get carried away using that.}
{178}{}{I'll be careful not to. Thanks!}
{179}{}{Here. It'll be as deadly as ever.}
{180}{}{I love the smell of kerosene in the morning. Thanks!}
{181}{}{Otto would do it, but you need to bring some extra stuff.}
{182}{}{I'll do it, what do you need?}
{183}{}{Forget it.}
{184}{}{A set of Chemistry Journals and a technical manual for the armor.}
{185}{}{I'm yet to find those. Maybe I'll give you something else to upgrade.}
{186}{}{I've got to go find them, then. Bye.}
{187}{}{I've yet to find the journals. Bye.}
{188}{}{I've got to find the manual. Bye.}
{189}{}{I've got both right here.}
{190}{}{Where would I find them?}
{191}{}{Ich weis nicht, freund, you're the one who's been all around the wasteland.}
{192}{}{Great. Otto will start applying the formula now, and you'll get your armor right away.}
{193}{}{[END]}
{194}{}{No, Otto don't know you and couldn't have met you, 'coz Otto's not from here, verstehen?}
{195}{}{And from where are you, then?}
{196}{}{Hey, take it easy. I just wanted to ask you if you could fix anything of mine.}
{197}{}{Fine. Bye.}
{198}{}{Otto came here all the way from Germany, in European Commonwealth, before the Great War. He thought this is, after all, the land of opportunities.}
{199}{}{Sounds like you weren't doing much good back home...}
{200}{}{Hey, Otto is the best mechanic there is! But business was bad. And Otto, he got into arguments with his brother all the time. The schwein stole Otto's special schematics, that's what he did!}
{201}{}{Schematics?}
{202}{}{Your brother?}
{203}{}{Very special schematics.}
{204}{}{What was it for?}
{205}{}{You see, Otto's got this baby here, the Hydroelectric Magnetosphere Regulator he's been putting together all his life, but it needs more work.}
{206}{}{Could it be fixed?}
{207}{}{If you found the original schematics, it could. But I haven't seen any of those since before the Great War.}
{208}{}{I'll keep looking. Bye.}
{209}{}{I have them right here.}
{210}{}{Right. I was wondering if you could upgrade anything of mine?}
{211}{}{You do? Great! Let Otto install it into the maschine.}
{212}{}{So now, can you fix something for me?}
{213}{}{A functional Hydroelectric Magnetosphere Regulator stops leaking of waste into the groundwater. Also, it can help with fuel synthesis. Pierre from the Rim and Otto are working together on fixing the poisoned waters for good.}
{214}{}{Does it work?}
{215}{}{No, it doesn't. But if I had the schematics, I could fix it.}
{216}{}{What kind of schematics?}
{217}{}{Tough luck.}
{218}{}{A very special schematics. Otto doubts you can find one of those.}
{219}{}{Maybe I can. If I found them, could the Hydra-magna-whateveraltor be fixed?}
{220}{}{I guess you're right. I mean, what could the odds be? See you.}
{221}{}{Otto would have more time if his Hydroelectric Magnetosphere Regulator was working, but it's not.}
{222}{}{Right. Mein bruder Klaus, he left Germany even before Otto did. Said he would join the army, so Otto laughed and cried hard. There was no more armies that would win the Great War, and even if there was, Otto would never join. Otto ist ein pazifist.}
{223}{}{What about the schematics?}
{224}{}{Hey, I brought these schematics for you!}
{225}{}{Hallo mann! Wie geht es dir?}
{226}{}{Viele, viele, me want candy!}
{227}{}{OK, man, Otto sees. Otto has no time for you, he's too busy trying to fix Hy-Mag.}
{228}{}{Oookay. Me go. Bye.}
{229}{}{Ugg... Wot hy-mag?}
{230}{}{A Hydroelectric Magnetosphere Regulator... Aw, hell, you probably don't know what it is anyway.}
{231}{}{Me have hy-mag papers here! Me give you gift!}
{232}{}{You do? You'll give it to Otto? Uhm... Listen, come back haben, Otto will give you a present too!}
{233}{}{Me want prezunt!}
{234}{}{You want Otto to upgrade something? What?}
{235}{}{Me dunno. You pick.}
{236}{}{Hier Otto upgraded your metal armor for you.}
{237}{}{Hier Otto upgraded your combat armor for you.}
{238}{}{Hier Otto sharpened your spear for you.}
{239}{}{Hier Otto mega-strengthened your Power Fist for you.}
{240}{}{Hier Otto hotwired that cattle prod for you.}
{241}{}{Hier Otto expanded the clip on your Desert Eagle for you.}
{242}{}{Hier Otto put a speed loader on your Magnum revolver for you.}
{243}{}{Hier Otto added a scope for your hunting rifle.}
{244}{}{Hier Otto put a night sight on your FN FAL.}
{245}{}{Hier Otto expanded the magazine of your AK-112 machinegun.}
{246}{}{Hier Otto given more power to your flamer.}
{247}{}{Hier Otto put a magnetic chamber on your Wattz Civilian Pistol.}
{248}{}{Hier Otto expanded the clip for your Plasma Pistol.}
{249}{}{Hier Otto expanded the clip for your Laser Rifle.}
{250}{}{Hier Otto refitted your regular Plasma into a Turbo Plasma.}
{251}{}{Thankuuuu!}
{252}{}{Sorry, Otto can do nothing for you, you've got nothing to upgrade.}
