# Message file for hdpierre.ssl
# Number of nodes: 57

{100}{}{You see an engineer diligently working.}
{101}{}{You see Pierre, the Chief Engineer of the Hoover Dam Engineering Facility.}
{102}{}{He is a strong and hearty looking man in his early fifties.}

# Node 0 [Floats]
{200}{}{Be careful! Avoid touching those wires.}
{201}{}{All systems are operational.}
{202}{}{Coolant level is normal.}
{203}{}{Main generator is online.}
{204}{}{Minimal radiation leakage.}
{205}{}{Core temperature is within acceptable limits.}
{206}{}{Operating at optimum capacity.}
{207}{}{Listen to this baby hummm...}
{208}{}{Just don't touch that lever. Or those buttons. Don't touch anything.}
{209}{}{My great-great-great-great-great-grandfather used to work with powerplants... In Europe, I believe.}
{210}{}{Have a productive and safe day!}
{211}{}{I'm a bit busy at the moment.}
{212}{}{Excuse me, but I'm rather busy right now...}
{213}{}{You'll have to wait until after the test.}
{214}{}{We need to recalculate those factors...}
{215}{}{Have you seen that spider wandering around? I hope it stays away from the reactor...}

# Node001
{230}{}{Hi! I am Pierre LaPoubelle and you are standing inside the Engineering Facility. Are you lost?}
{231}{}{That's an interesting name.}
{232}{}{No, I'm not. What are you working on?}
{233}{}{Can you tell me about this place?}
{234}{}{Yeah, I'm actually lost. Sorry, I'll just find my own way out.}

# Node003
{260}{}{Everyone keeps asking about that. Let's just say it's a name of European origin.}
{261}{}{So what is your role here, Pierre?}
{262}{}{Can you provide some information about the Engineering Facility?}
{263}{}{It was nice meeting you, but I have to go.}

# Node004
{290}{}{I'm the Chief Engineer. My responsibility is to ensure the proper functioning of every machine, prevent malfunctions, and maintain an operational power grid. I also calculate the required power output and handle various minor adjustments within Hoover Dam.}
{291}{}{Can you tell me how the Hoover Dam operates?}
{292}{}{What other aspects are handled here in the Facility? Can you talk about it?}
{293}{}{Wow, that sounds like an important role. I'll leave you to your work then.}

# Node025
{320}{}{Ah, there is always much to do, much to invent. Currently, we're working on creating hardier crops and better water filtration. Not easy, but nothing worth doing ever is.}
{321}{}{Pierre, I've been thinking... Can we convert Hoover Dam into a nuclear power plant?}
{322}{}{Anything I can do to help?}
{323}{}{Hardier crops?}

# Node027
{350}{}{Ah, a fellow enthusiast for the marvels of engineering! Well, the Hoover Dam is a monumental piece of work, even by pre-war standards.}
{351}{}{I'm all ears.}
{352}{}{Actually, I have to go now.}

# Node028
{380}{}{The Hoover Dam, as you may already know, is a concrete arch-gravity dam. It's primarily used for power generation, flood control, and water storage. The dam harnesses the power of the Colorado River, creating a large reservoir behind it, known as Lake Mead.}
{381}{}{So it's all about controlling the river?}

# Node029
{410}{}{Exactly. When the water from Lake Mead flows towards the dam, it enters large pipes called penstocks. These penstocks channel the water towards the turbines.}
{411}{}{Turbines? Are those like big fans or something?}

# Node030
{440}{}{Ha, a simplistic way to put it, but not entirely incorrect. Turbines are complex machines with many blades. As water rushes over these blades, it makes them spin, converting the kinetic energy of the falling water into mechanical energy.}
{441}{}{And that's how the dam generates electricity?}

# Node031
{470}{}{Right again! The spinning turbine is connected to a generator. This mechanical energy is then converted into electrical energy within the generator, which is then distributed for use.}
{471}{}{Sounds like a lot of moving parts. How do you keep it all running?}

# Node032
{500}{}{Well, that's where our job at the Engineering Facility comes in. We maintain, repair, and optimize this whole process, ensuring the dam can keep providing power and water to the region.}
{501}{}{So you're the ones keeping the lights on?}
{502}{}{Can you tell me more about the Facility?}
{503}{}{Thanks for explaining that. So long.}

# Node033
{530}{}{We're doing what we can. It's all about making our town a better place, one volt at a time.}
{531}{}{Thank you for sharing the details with me. So long.}

# Node002
{560}{}{Hello again! How can I assist you this time?}
{561}{}{I wanted to ask you about the Engineering Facility.}
{562}{}{What are you currently working on?}
{563}{}{I've found something that might interest you. There's a pre-war facility beneath the Scum Pits, named Sub-Level-1-Classified.}
{564}{}{Pierre, I found these filtration schematics in Jericho.}
{565}{}{I was just on my way out.}
{566}{}{Pierre, you've mentioned before that you're from the Brotherhood. Do you think you could let me in on where they're located?}

# Node026
{590}{}{Of course. The Engineering Facility is like the heart of Hoover Dam. This is where the "magic" happens, so to speak. We are constantly seeking ways to improve the life of our community here.}
{591}{}{It must be an enormous responsibility being the Chief Engineer.}
{592}{}{And I assume you have a team working under you?}
{593}{}{Tell me more about your role here?}
{594}{}{That's all I wanted to know. So long.}

# Node034
{620}{}{Indeed, it is. But it's also a passion. You know, once you've seen the damage out there in the wasteland, you can't help but want to do something about it.}
{621}{}{Can you tell me more about this building?}

# Node035
{650}{}{Absolutely. A very dedicated team of engineers and volunteers from the Followers of the Apocalypse. They are the real heroes. Each brings their unique skills and talents, which contribute to the success of our work.}
{651}{}{Excuse me, but I can spot a bad liar when one is standing in front of me. I've seen all the Brotherhood mumbo-jumbo on your computer. You are in league with them, aren't you? The Brotherhood of Steel?! The one that's waging a war against the NCR?}
{652}{}{Interesting. Thank you for your time. Goodbye.}

# Node036
{680}{}{Yes, well, I mean, no! We, the former Scribes, *were* from the Brotherhood. We came to Hoover out of frustration with the direction the Brotherhood was taking. We wanted to lend our peaceful services to the growing community of Hoover Dam, despite the government being NCR-based. It is largely due to Governor Dodge's fair-handed and peace-seeking approach to leadership that me and others chose to stay in Hoover Dam and volunteer their services.}
{681}{}{What's your take on the NCR-Brotherhood conflict?}
{682}{}{If there is anything I can do to help, let me know.}
{683}{}{So where are the Brotherhood's headquarters?}

# Node037
{710}{}{Ah, it's a regrettable situation. More fighting, more destruction, less progress. I choose to focus on creation, not destruction.}
{711}{}{I'll see you later. Bye.}

# Node052
{740}{}{Far to the west. We lost all records of its precise location.}
{741}{}{Lost, huh? If you say so. So long.}
{742}{}{I know you're lying! I'll let the police deal with you.}
{743}{}{That's it. You're going down, traitor!}

# Node005
{770}{}{There are various concerns, such as the environmental impact. Additionally, we need to calculate the consumption and ensure timely fuel delivery.}
{771}{}{Environmental impact?}
{772}{}{Fuel?}
{773}{}{Indeed. Where would you source your fissile fuel from?}

# Node014
{800}{}{We need to ensure that the water used to cool the reactor doesn't contaminate the environment. When it leaves the plant, it must have low radiation levels. We also have to prevent malfunctions and avoid any ignition of the graphite, among other tasks. We also vent gases and store spent fuel, but overall...}
{801}{}{I understand. Can you explain how the powerplant would operate?}
{802}{}{Brrr... I don't even want to think about it. Are you sure this is safe?}
{803}{}{You vandal! People like you are the reason this world is in such a mess! Prepare to meet your doom!}

# Node015
{830}{}{If all the systems are functioning properly, there is minimal risk.}
{831}{}{Of course. Thank you for your expertise, Pierre.}

# Node006
{860}{}{That's correct. We would need fissile uranium or plutonium as the nuclear fuel to generate nuclear power.}
{861}{}{Where would you acquire that fuel from?}
{862}{}{Can you explain how you would produce power?}

# Node007
{890}{}{We could potentially import some Uranium-235 from Broken Hills, but the last I heard, that place has become a ghost town. However, we might be able to establish our own source from the Grand Canyon. There have been discussions about conducting geological surveys in the Council Hall.}
{891}{}{I see. Why is uranium so crucial?}
{892}{}{Interesting. Well, I should be going now.}

# Node008
{920}{}{It would serve as the primary power source. Are you interested in knowing how its power is generated?}
{921}{}{Yes, please.}
{922}{}{No, thanks.}

# Node016
{950}{}{Fission would occur in a near-critical mass, where heavy nuclei split into lighter ones. This sustained chain reaction would then release and absorb neutrons. Slow-moving free neutrons would be moderated and heat released in the process. This heat would then boil water into steam, which would then turn electric turbines and finally generate electricity.}
{951}{}{Ah I see, so that's how electricity would be generated! Thank you for expanding my knowledge. Goodbye.}

# Node009
{980}{}{This is the main control and supervision chamber for the Facility. From here, we ensure all vital systems function properly. If any issues arise, we address and repair them as necessary. We're also collaborating closely with Otto from Downtown to develop a better water filtration process, aiming to convert non-drinkable irrigation water into a version that's fully potable.}
{981}{}{Can you provide more details about the filtration systems you are working on?}
{982}{}{So you're saying there are malfunctions? I won't just stand here while disaster looms. Goodbye.}

# Node010
{1010}{}{It's a standard light water-cooled thermal twin-tube filter. Turbo graphite is used as the moderator for wayward neutrons in this design.}
{1011}{}{Sounds pretty advanced.}
{1012}{}{Can you explain how it works?}
{1013}{}{Actually, it sounds like an older and obsolete type of filter...}
{1014}{}{Ah, too many technical terms for my liking! I have to go.}

# Node011
{1040}{}{Well, actually, it's not the most advanced design. It's one of the older models that wasn't widely used in the past. We could potentially upgrade to a more advanced pebble bed filter...}
{1041}{}{Then why are we using this design?}
{1042}{}{Can you provide more details on how it operates?}
{1043}{}{Just take good care of it, and everything will be fine. Goodbye.}

# Node012
{1070}{}{It's a practical and reliable choice. It can handle enriched uranium or heavy water, which we wouldn't be able to filter without a developed industrial base. It suits our current needs perfectly.}
{1071}{}{If you say so. Can you explain how it works in more detail?}
{1072}{}{That's great. I need to get going now.}

# Node013
{1100}{}{It's a radiation absorbent. We use it to trap the harmful particles and rays.}
{1101}{}{So, what exactly is your role here?}
{1102}{}{I'm not particularly knowledgeable about nuclear science. Goodbye.}

# Node017
{1130}{}{Hi! How can I assist you?}
{1131}{}{Hello! You boss? Me ask!}
{1132}{}{Nuthin. Bye!}

# Node018
{1160}{}{Oh boy. You've been exposed to the hazards for too long, haven't you? What do you want to know?}
{1161}{}{Me want know atomic!}
{1162}{}{Me want know electro!}
{1163}{}{Ugh... Me no know. Bye!}

# Node019
{1190}{}{Well, we would use graphite as the neutron moderator and light water for cooling. I say light water because heavy water contains deuterium instead of ordinary hydrogen...}
{1191}{}{You got big brain! Me want big brain!}
{1192}{}{Ugh...Me no know! You bad teach! Bye!}

# Node020
{1220}{}{Yes, yes... I'm sure you'll have one in due time. Just be patient and study hard, wanderer.}
{1221}{}{You kind! Bye-bye!}

# Node021
{1250}{}{Well, when a neutron strikes a nucleus, it splits into smaller elements, like "pebbles." Some of these "pebbles," or neutrons, cause more nuclei to split, creating a chain reaction. This process releases heat, which is used to turn water into steam, powering electric turbines.}

# Node022
{1280}{}{What? That's incredible! How did you find it?}
{1281}{}{Well, let's just say it wasn't easy. I had to clear out the Scum Pits and face a giant albino ant queen. But in the end, I found an access hatch. It was electronically locked, but I managed to open it.}

# Node023
{1310}{}{This is remarkable news. That area was probably lost during the war, and we had no idea what was down there. You've done Hoover a great service today. We can use the lab to enhance our scientific research and improve the lives of everyone here.}
{1311}{}{That's why I brought you this news. Thought it could be beneficial for all of us.}

# Node024
{1340}{}{It certainly will be. As a show of our gratitude, we'll give you access to the lab and our assistance whenever you need it.}
{1341}{}{Thanks, Pierre. Appreciate it.}

# Node038
{1370}{}{Well, you're the new blood in town and look like someone who doesn't shy away from hard work. I could use your help with a project.}
{1371}{}{Oh? And what would that be?}

# Node039
{1400}{}{Water is the lifeblood of any community, especially in a wasteland. Our filtration system, though functional, leaves a lot to be desired. We need a better process, something more efficient. Just look at what happened to poor, mentally troubled Milko; he drank too much of filtered and processed irrigation water before anyone could tell him it was not for human consumption.}
{1401}{}{What can I do?}

# Node040
{1430}{}{If you happen to come across any schematics or technology in your travels, especially in a place like Jericho, it could be invaluable.}
{1431}{}{I'll see what I can find.}

# Node041
{1460}{}{[Pierre examines the schematics.] Let me see...}
{1461}{}{[CONTINUE]}

# Node042
{1490}{}{Excellent! This is exactly what we needed.}
{1491}{}{I could try installing these upgrades. I have the skills.}
{1492}{}{Here you go. I'm sure you can make better use of these than I can.}

# Node043
{1520}{}{Impressive. I'll get you the tools and the space you need.}

# Node044
{1550}{}{Wonderful job, my friend. Here's a token of our appreciation, a toolset that's sure to be useful to someone with your talents.}
{1551}{}{Hah! Thank you for that, Pierre. Goodbye.}

# Node045
{1580}{}{Indeed. I'll get to work right away. You've done a great service for Hoover Dam. Please, accept this tool for your help.}
{1581}{}{Thank you. Goodbye.}

# Node046
{1610}{}{That's an interesting thought. In theory, it might be possible, but the reality is quite complex. The two systems are quite different in nature.}
{1611}{}{In what way?}

# Node047
{1640}{}{Well, the primary difference is the fuel source and the way energy is produced. A dam uses the potential energy of water, a renewable and relatively safe resource. A nuclear plant, however, uses nuclear fuel such as uranium or plutonium, which undergoes fission to release energy.}
{1641}{}{So, what would we need to make this conversion?}

# Node048
{1670}{}{A lot, I'd reckon. Firstly, we'd need a source of nuclear fuel and a safe and secure way to store and handle it. That's no small task considering the volatility and potential dangers involved.}
{1671}{}{What else?}
{1672}{}{Dangers?}

# Node049
{1700}{}{We'd need to rework the entire infrastructure. A nuclear power plant needs a reactor where the fission process takes place. We'd need cooling systems to control the temperature, control rods to manage the fission rate, and a containment structure for safety. And of course, we'd have to find a way to integrate it with our existing power distribution systems.}
{1701}{}{That sounds like a massive undertaking.}

# Node050
{1730}{}{It is, and there are many potential risks and consequences to consider. The wasteland is challenging enough without the dangers of nuclear radiation. A leak or a meltdown could be catastrophic.}
{1731}{}{So, it's more complicated and dangerous than it's worth?}

# Node051
{1760}{}{In our current situation, I would say so. The Dam's hydroelectric system is much simpler, safer, and more sustainable. It might not be as powerful as nuclear energy, but it's more than enough for our needs. And if it ain't broke, as they say...}
{1761}{}{Yeah, I get it. Thanks for the explanation, Pierre.}

# Node053
{1790}{}{We're trying to develop crops that can survive the harsh wasteland. Because of its property to clean radiation from the ground, we call it the "miracle wheat." If we succeed, we can improve the food supply considerably.}
{1791}{}{That's ambitious. Good luck then.}
{1792}{}{Would you be willing to sell a bag of "miracle wheat" seeds?}

# Node054
{1820}{}{Well, normally, that's the sort of information we'd keep close to our chest. It's a delicate matter, you understand...}
{1821}{}{I get it, Pierre. It's a matter of safety. But you know you can trust me, right? I've done nothing but help since I arrived.}

# Node055
{1850}{}{Yes, I know. And it's because of your actions that I'm even considering this... Alright, listen. It's not often that we meet someone as reliable and good-hearted as you.}
{1851}{}{I appreciate that. So, you'll tell me?}

# Node056
{1880}{}{Yes, I will. But remember, this stays between us. The Brotherhood is located east of here, in Maxson Bunker. I'll mark that on your map. It's not an easy journey, and they're not particularly welcoming to outsiders, so tread carefully.}
{1881}{}{I understand. Thanks for trusting me with this.}
{1882}{}{Especially towards ghouls. You might get inside with a disguise, but that can get you only so far.}
{1883}{}{Especially towards super mutants.}

# Node057
{1910}{}{Yes, but you might find the price tag of 1,000 caps to be eye-watering. A lot of NCR resources were invested into this project.}
{1911}{}{How about 800 caps and you go to bed knowing that you've made the world a better place?}
{1912}{}{Alright, it's a fair price.}
{1913}{}{Sorry, that's too much.}

# Node058
{1940}{}{Heh, well said. Here's a bag of "miracle wheat" seeds. Use it well.}
{1941}{}{Thank you.}
