# Message file for hdrock.ssl
# Number of nodes: 17
# Grammar pass done

{100}{}{You see a clumsy guard.}
{101}{}{You see Private Rock.}
{102}{}{You see a guard guarding the staircase down. You see a guard whose armor doesn't seem to fit very well, and the helmet continues to fall over his eyes constantly. You see a guard so slow that it's nearly impossible to outsmart him, let alone establish communication.}

# Node001
{200}{}{Greetings, Sir! Welcome to the NCR Army Barracks. [Blinks rapidly.] I'm afraid I can't permit you to pass, Sir.}
{201}{}{Greetings, Ma'am! Welcome to the NCR Army Barracks. [Blinks rapidly.] I'm afraid I can't permit you to pass, Ma'am.}
{202}{}{Why not?}
{203}{}{Identify yourself.}
{204}{}{Allow me through, or things could get messy.}
{205}{}{Understood. Farewell.}

# Node002
{230}{}{Sir, this is a high-security zone. I'm under strict orders; without the correct passwords, I cannot grant access.}
{231}{}{Ma'am, this is a high-security zone. I'm under strict orders; without the correct passwords, I cannot grant access.}
{232}{}{No worries, I know the passwords: "Citadel, Secret, 123."}
{233}{}{Don't you trust your own kind?}
{234}{}{Of course, I know the passwords. [Read the passwords from a restored paper.]}

# Node003
{260}{}{Those aren't the passwords.}
{261}{}{Yes, they are. They changed them, and you're not informed.}
{262}{}{My apologies, I misspoke.}

# Node004
{290}{}{[Blinks.] Very well, you may pass.}
{291}{}{Have a pleasant day.}

# Node005
{320}{}{What do you mean?}
{321}{}{Would you trust your own family, like your mother, father, or sweet old grandma?}

# Node006
{350}{}{Yes, indeed.}
{351}{}{And who else would you trust? Your uncle, perhaps? Do you even know what an uncle is?}
{352}{}{And who else would you trust? Your aunt, maybe? Do you even know what an aunt is?}

# Node007
{380}{}{Well... An uncle is... [Eyes widen.] An uncle!}
{381}{}{We are family too; your father's sister's granddaughter was my mother's cousin, making me - your uncle.}

# Node008
{410}{}{U... Uncle?}
{411}{}{Indeed! It's me, Uncle.}
{412}{}{Wouldn't want to upset your dear uncle, right?}

# Node009
{440}{}{Uh... Of course, Uncle.}
{441}{}{Please, go ahead.}
{442}{}{That a boy!}

# Node010
{470}{}{Well... An aunt is... [Eyes widen.] An aunt!}
{471}{}{We are family too; your father's sister's granddaughter was my mother's cousin, making me - your aunt.}

# Node011
{500}{}{Aunt?}
{501}{}{Yes, it's me, Aunt.}
{502}{}{Wouldn't want to disappoint your dear aunt, would you?}

# Node012
{530}{}{Uh... Of course, Aunt.}

# Node013
{560}{}{I'm Private Rock Smith! They say I got my name because I'm as smart as a rock. But don't be fooled! I'm an immovable, rock-solid, guard!}
{561}{}{What type of weapon are you carrying?}
{562}{}{Well then, keep up the good work being a "rock."}

# Node014
{590}{}{This is Mrs. Smith! They only trust me with this gun because apparently "I'd end the war singlehandedly" with anything else.}
{591}{}{Uh, OK. Can I pass now?}
{592}{}{Uh, OK. Goodbye.}

# Node015
{620}{}{Hello, Uncle }
{621}{}{Please, proceed.}
{622}{}{Thank you, nephew.}
{623}{}{Sir}
{624}{}{Ma'am}

# Node016
{650}{}{Hello, Aunt }

# Node017
{680}{}{[He studies you for a moment, searching for a glint of intelligence behind your eyes.] Seems you're even dumber than me. Fine, you can enter, but be cautious. These are the NCR Army Barracks - don't touch anything or wander off, or the forcefield might give you a nasty surprise. Remember, no touching, no eyesighting! What you see is what you forget! Alright, proceed!}
{681}{}{Ooookey! Thank U!}
