# Grammar pass done

{102}{}{This appears to be the last operational computer in this flooded facility.}

{105}{}{This is a Mach IV Computer hooked into the facility's mainframe.}
{106}{}{It's not broken so there's nothing to repair.}
{107}{}{It doesn't seem to be trapped.}

# Node001
{200}{}{[This seems to be the last operational computer in this flooded facility. It seems to have been powered on for a long, long time. The interface is unlocked for unrestricted use.]}
{201}{}{[Access the facility's mainframe.]}
{202}{}{[Leave it be.]}

# Node002
{230}{}{[An animated logo for something called "S1C" spins on the screen before being abruptly replaced by a glaring "ERROR" message.]}
{231}{}{[Attempt to salvage any retrievable data.]}
{232}{}{[Exit]}

# Node003
{260}{}{[You manage to uncover some data within the mainframe's database. You could transfer it to your computer's holodisk.]}
{261}{}{[Copy entry "Project Chimera"]}
{262}{}{[Copy entry "The Story of Hoover Dam"]}
{263}{}{[Exit]}

# Node004
{290}{}{"'Project Chimera' data successfully transferred to a holodisk on computer 'Supervisor-S1C'."}
{291}{}{[Return]}

# Node005
{320}{}{"'The Story of Hoover Dam' data successfully transferred to a holodisk on computer 'Supervisor-S1C'."}
