{100}{}{You see a drunk caravanner.}
{101}{}{You see a sleazy, sweaty guy.}

{150}{}{I surrender, please don't hurt me}

# Floats if PC is male
{200}{}{Looks like you're just in for the party!}
{201}{}{Bend over fella!}
{202}{}{You're not my type but what the hell}
{203}{}{It's a guy, no big deal}
{204}{}{I've never done a guy before!}
{205}{}{Can you dress up as a lady?}
{206}{}{I'm a scum angel}
{207}{}{Can I call you Emma?}
{208}{}{Let's get over with it}
{209}{}{You're fucking ugly but what the hell}

# (Floats if PC is female)
{300}{}{Watcha wearing under that skirt?}
{301}{}{Come to papa}
{302}{}{Nice, very nice}
{303}{}{Let me show you something, sugar}
{304}{}{I saved something for you}
{305}{}{I'm on fire!}
{306}{}{I'm on fire! Heeeeeeeeyaaaa!}
{307}{}{A gift for me!}
{308}{}{Call me Daddy!}
{309}{}{I'm a scum angel!}
{310}{}{What's a beautiful girl like you doing here, all alone?}
{311}{}{Where's your boyfriend?}

{400}{}{The tension hangs thick in the air, the thugs poised to strike at the super mutant bouncer at any moment. You realize time is running out. One of them spots your approach.}
{401}{}{Hey! The cops are on their way.}
{402}{}{Apologies, I've seen nothing and I know nothing. I'll just be on my way, fellas.}

{403}{}{Oh, really? And how do you figure that? By the time they arrive, we'll have dealt with both the green thing here *and* you.}
{404}{}{[Reveal your radio.]}
{405}{}{[Show your Pip-Boy.]}
{406}{}{The cops are on their way here. You're done for, imbeciles.}

{407}{}{Damn it! Time to scram.}
{408}{}{That ain't no radio. It's one of them Vault gizmos... whatever you call it. Anyways, it was a mistake thinking we'd fall for your bluff.}
