{100}{}{You see a pale humanoid figure in the darkness.}
{101}{}{You see a trog.}
{102}{}{This hillbilly troglodyte seems to have taken up residence in Baseline in exchange for maintaining the working generators.}

{103}{}{Brayn...  Fresh brayn...  Yup, nothing ken beat fresh fried rat brayn.}
{104}{}{Huh?}
{105}{}{Ay wonduurr how ol' Pappy's a-doin'.}
{106}{}{Ay ken cook rats.}
{107}{}{Damn rarsh...}
{108}{}{Ay'm allergik ta sunlaheet.}
{109}{}{Ay'm a-thinkin' av a-goin' outside...}
{110}{}{Ay must be a-lookin' funny ta y'all!}
{111}{}{Actually, ay enjoy a-bein' ayy trog.}
{112}{}{Naw rush.  We flow like thay ...uhh watuurr unduurr thay...uhh dam...}
{113}{}{If ay was like ya waste-walkuurr, ay'd probably be dead by now.}
{114}{}{Youngun, ay done watched the EN-SI-AR a-bein' done built...}
{115}{}{Ay think Cat's Paw waste-walkin' layies are nahwt that there darn good a-lookin'...}
{116}{}{When you a-lookin' this here darn good. Oh, nevermaand.}
{117}{}{What do y'all want, waste-walkuurr?}
{118}{}{Ay'm ayy trog, thay...uhh awful bad ayn' thay...uhh ugly...}
{119}{}{Done got any sunscreen ta spare? Ay done thought nahwt!}
{120}{}{Take it awful easy with us trogs, some ov us like ayy awful dark joke now ayn' then.}
{121}{}{If y'all was ayy child ov the night, y'all'd have ayy awful dark sense ov humour too.}
{122}{}{Ya done got ayy spare toothpik?}
{123}{}{Ay hope we rule thay...uhh Dam one day...}
{124}{}{The earth belly protects us trogs.}
