# Grammar pass done

{100}{}{You have entered a highly-advanced military bunker, where the cool breeze of conditioned air envelopes you.}

{200}{}{Brothers and Sisters of the Brotherhood, we gather here today to witness another momentous occasion in our history.}
{201}{}{Our techno-religious, military order has faced many challenges, but through the unwavering dedication and valor of one among us, we stand on the brink of a new era.}
{202}{}{Hmph!}
{203}{}{For your exceptional skills and bravery in bringing an end to the conflict with the NCR, you have proven yourself a true exemplar of our ideals.}
{204}{}{It is with great honor that I bestow upon you the rank of Senior within the Brotherhood of Steel!}
{205}{}{*clap* *clap* *clap*}
{206}{}{Bravo!}
{207}{}{You showed them, }
{208}{}{!}
{209}{}{*whistle*}
{210}{}{Ahem... As a Senior, you will shoulder greater responsibilities and wield greater influence in our ranks.}
{211}{}{Our solemn duty is to guide, preserve and protect humanity, together with its ways, ensuring that our principles endure through the ages.}
{212}{}{Rise, }
{213}{}{, and accept this symbol of your elevated status among us.}
{214}{}{May it serve as a reminder of the pivotal role you played in securing the future of the Brotherhood, and thereby that of humanity.}
{215}{}{Wear this emblem with honor, Senior.}
{216}{}{I will, Commander.}
{217}{}{Together, let us continue to uphold the legacy of Roger Maxson, and aid humanity in rising from the ashes!}
