# Grammar pass done

{100}{}{You see a Brotherhood of Steel hardliner.}
{101}{}{Dark and haunted eyes betray this person's mental state.}

{200}{}{I've met my match.}
{201}{}{You've proven yourself worthy.}
{202}{}{Fuck you!}
{203}{}{Defiler!}
{204}{}{I must acquire a superior weapon.}
{205}{}{Our technology needs enhancement!}

{206}{}{They've discovered our presence!}
{207}{}{You align yourself with the false Brotherhood, do you not?}
{208}{}{Who sent you, spy?}
{209}{}{Prepare for target practice!}
{210}{}{We are the *true* Brotherhood!}
{211}{}{The Circle shall guide the Brotherhood back to its righteous path!}
{212}{}{An NCR infiltrator!}
{213}{}{A spy working for the false Brotherhood!}
{214}{}{We're under assault!}
{215}{}{You shall never infiltrate us again.}
{216}{}{The Circle of Steel tightens its grip around you.}
{217}{}{Negotiation and diplomacy hold no place here.}
{218}{}{The Steel Plague lives on!}
{219}{}{We are the Circle of Steel! We are the Steel Plague! And your demise is certain!}
