# Grammar pass done

{100}{}{Apologies, but access is restricted at the moment due to technical difficulties. Please try again later.}
{101}{}{We're aware of the damage caused to our laser turret. You'll be responsible for the repair costs.}
{102}{}{Impressive power armor you have there. Please remain where you are. Someone will arrive shortly to greet you.}
{103}{}{Cease that behavior immediately.}
{104}{}{Good to have you back, Brother.}
{105}{}{Good to have you back, Sister.}
{106}{}{Warning! Hostile mutant detected near the gates!}
{107}{}{You see the bunker blast door entry computer.}
{108}{}{The speaker crackles to life.}
