# Message file for mbdavis.ssl
# Number of nodes: 143

{100}{}{You see a figure in loose-fitting, red-colored clothes.}
{101}{}{You see Davis shuffling around with his usual pious gait.}
{102}{}{Despite his loose-fittingclothes, you can tell that he is stick-thin and far from healthy.}

# Davis_1_Ba_1
{230}{}{Hello again, my son. I trust you will remember your manners, this time.}
{231}{}{Hello again, my child. I trust you will remember your manners, this time.}
{232}{}{Hello, Michael. I'd like to ask you a question.}
{233}{}{I've managed to find a shovel.}
{234}{}{Alexander said you have to give me the two sets of bones you know the whereabouts of.}
{235}{}{You can stop calling me 'your son' for a start.}
{236}{}{You can stop calling me 'your child' for a start.}
{237}{}{Sorry, I need to be somewhere else. Goodbye.}

# Davis_1_Ba_2
{260}{}{Still the attitude, hmm? Please leave and only come back when you have calmed down.}
{261}{}{No, I think I'll kill you instead, you self-righteous bastard. *Draw weapon.*}
{262}{}{[Leave]}

# Davis_1a_1
{290}{}{Good day to you, my son. How may I help you?}
{291}{}{Good day to you, my child. How may I help you?}
{292}{}{Hello, I'm trying to get to know the people around here. What can you tell me about yourself?}
{293}{}{I'm not 'your son'.}
{294}{}{I'm not 'your child'.}
{295}{}{You look scary.}
{296}{}{Poo, you smell funny!}
{297}{}{Hello. Who you?}
{298}{}{I need access codes for the Surveillance System.}
{299}{}{I need help in determining what's wrong with General Brixley. Can you help?}

# Davis_1a_1B
{320}{}{Well... no, of course not. Not in the biological sense. I mean no harm; what can I do for you?}
{321}{}{I'm trying to get to know the people around here. What can you tell me about yourself?}
{322}{}{You can stand there whilst I kill you.}
{323}{}{Goodbye.}

# Davis_1a_2a
{350}{}{My name is Davis. Although I'm currently in a unenviable situation, I still consider myself true to the Brotherhood's dogma but not its current leadership. Would you like to know what I do here in the Brotherhood?}
{351}{}{Yes, please.}
{352}{}{Yes! Come on, don't keep me waiting.}
{353}{}{Maybe another time. I have to be going.}

# Davis_1a_2B_1
{380}{}{You should learn greater patience, my son! It is a rare virtue, but none should consider themselves above it.}
{381}{}{You should learn greater patience, my child! It is a rare virtue, but none should consider themselves above it.}
{382}{}{I apologize, you're right. Please tell me a bit about what you do around here.}
{383}{}{You may have time to be patient, but I am very busy.}
{384}{}{Don't call me 'my damn son'!}
{385}{}{Don't call me 'my damn child!'}

# Davis_1a_2B_2a
{410}{}{More haste, less speed, my son. You will achieve little if your mind is not settled.}
{409}{}{More haste, less speed, my child. You will achieve little if your mind is not settled.}
{411}{}{Enough of the sermons, wise man. Tell me what you do around here.}

# Davis_1a_2B_2b
{440}{}{So much anger. Why is that? I am here only to help others.}
{441}{}{I apologize. Please tell me a bit about what you do around here.}
{442}{}{You can shove your 'help'. Goodbye.}

# Davis_1a_D1_a
{470}{}{Oh. Hahaha! I don't mean to be. I'm here to help you if you need it.}
{471}{}{Who you?}

# Davis_1a_D1_b
{500}{}{Hmm. Can I help you in any way, my son? I am rather busy at the moment.}

# Davis_1a_D2
{530}{}{My name is Davis. The people in this bunker call me their Head Scribe.}
{531}{}{What do Hed Scribi do?}
{532}{}{What a Hed Scribi?}

# Davis_1a_D3
{560}{}{A Head Scribe does good things for people who need aid. Do you need help with anything, my son?}
{561}{}{A Head Scribe does good things for people who need aid. Do you need help with anything, my child?}
{562}{}{A got a hurt. [Point to injury]}
{563}{}{I keep doing sick and not feeling good.}
{564}{}{I not need help. Goodbye.}

# Davis_1b_1
{590}{}{Hello again, my son. How may I help you?}
{591}{}{Hello again, my child. How may I help you?}
{592}{}{I have General Brixley's medical record on my Pip-Boy. Here, take a look.}

# Davis_1b_2a
{620}{}{You've come back for the bones of the last two Explorers, presumably?}
{621}{}{That's right. Let's go out and get them.}
{622}{}{Before we go out to the cemetery, I'd like to ask you a question.}

# Davis_1b_2B
{650}{}{Oh. I mean no harm by it, you know.}
{651}{}{Anyway, I'd like to ask you a question.}

# Davis_2_1
{680}{}{The personnel of Maxson Bunker thinks of me as the one most responsible for recording the knowledge of our ancestors for future generations. They also think of me as their innovator and priest. I am not, strictly speaking, a priest, but the duties I perform around the bunker are like those usually associated with holy men.}
{681}{}{What duties are those?}
{682}{}{Have you been with the Brotherhood all your life?}
{683}{}{What can you tell me about Maxson Bunker?}
{684}{}{Please let me ask you a question about something else.}
{685}{}{I've got to go. Goodbye.}

# Node139
{4340}{}{There's only one code you'll need: FunkyDiscoManiac. [It looks like he wants to tell you something else but he hesitates and no words come out.]}
{4341}{}{Thank you. Goodbye, Davis.}

# Node140
{4370}{}{I'm not really familiar with the details. Been here for a while and they're not telling me anything. But if you bring me her medical record, I could help you.}
{4371}{}{Alright, I'll see what I can do.}
{4372}{}{I already have it on my Pip-Boy. Here, take a look.}

# Node141
{4400}{}{[He reads through it a couple of times. It looks like he's trying to memorize it.] Alright, got it. Give me an hour or two.}
{4401}{}{Alright, Davis.}

# Node142
{4430}{}{[He comes back, smiling.] She was poisoned with a strong, refined venom! Are you recording this? I'll give you all the details.}
{4431}{}{[Record his discovery on your Pip-Boy]}

# Node143
{4460}{}{[After half an hour, he finishes. It looks like he wants to tell you something else but he hesitates and no words come out.]}
