# Message file for mbpalad.ssl
# Number of nodes: 1
# Grammar pass done

{102}{}{You see a young individual who seems to be an assistant to the Doctor.}

{200}{}{You should consult with the Doctor directly.}
{201}{}{I'm not the Doctor, I'm just an assistant in training.}
{202}{}{I'm still learning the ropes, so I can't officially assist you.}
{203}{}{I'm sorry, but I don't have the authority to help you officially.}
{204}{}{Sarah is the Doctor, she's the one you need to talk to.}
{205}{}{You'll have to direct your inquiries to the Doctor herself.}
{206}{}{Rest assured, Sarah will do everything she can to assist you.}
{207}{}{Sarah is working hard to become the best Doctor she can be, so you're in good hands.}
