# Message file for mbdoctrm.ssl
# Number of nodes: 6
# Grammar pass done

{100}{}{Medical Computer Console}
{102}{}{This is the Doctor's unlocked computer console.}

{105}{}{You have solved the mystery of Elder Brixley's illness.}

# Node001
{200}{}{[Maxson Bunker Network initialized. Welcome back, Doctor.]}
{201}{}{[Search Datastore]}
{202}{}{[Exit]}

# Node002
{230}{}{[You quickly locate Elder Brixley's medical record. Some other records catch your attention, among them one belonging to a young Initiate Knight named Jean-Baptiste Cutting, who was recruited recently wearing a vault jumpsuit, and another related to Jon Young, one of the cooks, as well as some other "interesting" search results.]}
{231}{}{[Access Andrea Brixley's medical record]}
{232}{}{[Access Jean-Baptiste Cutting's medical record]}
{233}{}{[Access Jon Young's medical record]}
{234}{}{[Search for stimpak IDs ending with the number 7 issued last month]}
{235}{}{[Use the AutoDoc to analyze samples from the depleted stimpak]}
{236}{}{[Access Pierre LaPoubelle's medical record]}
{237}{}{[Access "Project Stealth Boys"]}

# Node003
{260}{}{[Jean-Baptiste Cutting. Male, 23 years old. Born in Redding to Tiaret Van Graff and an unnamed father, Mr. Cutting. Recovered by a night patrol 3 sectors to the north. Possessions included: Two Wattz 1000 Laser Pistols (police models), 4 SEC ammo bricks, and a "USP Tibbets" vault jumpsuit. Dehydrated but otherwise healthy. Currently undergoing desert field training as an Initiate Knight.]}
{261}{}{[Back]}

# Node004
{290}{}{[Andrea Brixley. Female, 37 years old. Elder Paladin, General Commander of Maxson Bunker. No additional information available besides the medical record.]}
{291}{}{[Research her current condition]}
{292}{}{[Download her medical record to your Pip-Boy]}

# Node005
{320}{}{[After 12 hours of researching General Brixley's medical record, you are unable to determine the cause of her condition.]}
{321}{}{I'll have to approach this from a different angle...}
{322}{}{Me go find clues...}

# Node006
{350}{}{[After 12 hours of researching General Brixley's medical record, you discover that she was poisoned by a military-grade nerve agent.]}
{351}{}{Ah, I've figured it out!}
{352}{}{Huah! Me smart!}

# Node007
{380}{}{[Jon Young. Male, 34 years old. Cook. Traces of healing powder abuse detected again in a random blood sample test. Need to reprimand him and Tamara; she's doing a lousy job of keeping him away from those tribal traders. They're obviously trading more than iguanas and geckos!]}

{410}{}{[Series 7 stimpak issued to quartermaster Devon Hill after a close encounter with a golden gecko.]}
{411}{}{Well, well, Mr. Hill...}

{440}{}{[After 4 hours of analysis, the AutoDoc generates a report. Traces of a military-grade nerve agent are detected inside the depleted stimpak.]}
{441}{}{I've done it!}

{470}{}{[You successfully download the medical record to your Pip-Boy.]}

# Node011
{500}{}{[Pierre LaPoubelle. Male, 52 years old. Deserter. Former Senior Scribe stationed at Maxson Bunker. Current whereabouts are unknown.]}

{530}{}{[Entry #328: In the thick of our struggle to bring an end to the war, the Brotherhood embarked on a dangerous path. We had uncovered new, subversive technology: devices we came to know as Stealth Boys. These contraptions could conjure an energy field that bent light around its bearer, effectively rendering them invisible to the naked eye. With this innovation, our operatives found themselves able to venture deep into NCR territory, gathering intelligence covertly and effectively.]}
{531}{}{[More]}

{560}{}{[Entry #339: But the promise of the Stealth Boys proved fleeting. Devastating side effects surfaced: paranoia, delusions, and, ultimately, schizophrenia. The Brotherhood, valuing the mental health of its operatives, quickly discontinued the use of the Stealth Boys. Our momentum in the war effort faltered once again.]}

{590}{}{[Entry #342: The Brotherhood now faces a growing internal crisis. The Stealth Boys' insidious side effects didn't become apparent until our teams were already deeply affected. Upon disbanding the affected team, paranoia festered within their ranks. They believed themselves betrayed by their own leaders, and in their fear, they revolted. Stealth Boys in hand, they fled our bunker and denounced their allegiances, forming a renegade faction known as the Circle of Steel.]}

{620}{}{[Entry #345: The Circle of Steel has one overriding ambition: to recover the lost technology and restore the Brotherhood to its former glory, at any cost. Their methods, their rationale, they're spiraling out of control. We've given birth to a monster, and the fallout is proving harder to contain than the war we sought to end.]}
