# Message file for mbgate2.ssl
# Number of nodes: 8
# Grammar pass done

{150}{}{A mutant!}
{151}{}{NCR!}

# Node001
{200}{}{Um... Hello and welcome to the Brotherhood of Steel. Why did you destroy our turret? You'll need to come inside, stranger, peacefully. We want to talk to you.}
{201}{}{I acted in self-defense!}
{202}{}{I'm not going anywhere, bastard!}
{203}{}{Sure thing. Lead the way.}
{204}{}{The Brotherhood of Steel? Tell me more.}
{205}{}{[Run away.]}
{206}{}{The Bros?}

# Node002
{230}{}{We're the ones asking questions here. Don't worry, everything will be explained once you're inside. Now, are you coming in, or do we need to resolve this here and now?}
{231}{}{Calm down. I'll go inside peacefully.}
{232}{}{Bring it on, little boy!}

# Node003
{260}{}{When they told me someone in power armor was trying to get in, I had to see it for myself. Anyway...}
{261}{}{[CONTINUE]}

# Node004
{290}{}{Hello and welcome to the Brotherhood of Steel. You'll need to come inside, stranger. We want to talk to you.}
{291}{}{I'm not going anywhere, bastard!}

# Node005
{320}{}{You'll get a chance to explain everything. Now, are you coming in, or do we need to resolve this here and now?}

# Node006
{350}{}{Huh? I don't know how you got here in the first place, but you must leave. We have certain standards to uphold. Sorry, friend. At least we'll spare your life. The Brotherhood wishes you the best out there.}
{351}{}{Me enter. Me open you like a can opener and kill good.}
{352}{}{Bye bye!}

# Node007
{380}{}{[The guard sizes up the massive weapon in your hands. He proudly brandishes his Gatling laser, his fingers nervously twitching around its trigger.]}
{381}{}{[Hold up your weapon, displaying its serial number, the year of manufacturing, the manufacturer's name, and the country where it was assembled.]}

# Node008
{410}{}{[He removes his finger from the trigger. You seem to have impressed him.]}
