# Message file for mbglenn.ssl
# Number of nodes: 17
# Grammar pass done

{100}{}{You see a man in his late thirties wearing Brotherhood metal armor.}
{101}{}{You see Elder Paladin Glenn.}
{102}{}{He exudes a laid-back aura.}

# Node_001
{200}{}{?}
{201}{}{Wh... wha?}

# Node_002
{230}{}{[A friendly face of a Brotherhood member in his late thirties appears on your monitor.] Wake up! Come on, }
{231}{}{ you need to get ready. The Commander wants to see you.}
{232}{}{Alright, I'm getting up.}
{233}{}{Bite me. I'm going back to sleep.}

# Node_003
{260}{}{But what about the Commander?}
{261}{}{The Commander can bite me too.}

# Node_004
{290}{}{That's the spirit. Today could be your lucky day!}
{291}{}{Lucky how?}

# Node_005
{320}{}{Typical Initiate. This could be your big day, }
{321}{}{, but you'd rather just sleep through it.}
{322}{}{My big day? What do you mean?}
{323}{}{Zzzz...}

# Node_007
{380}{}{It's not every day an Initiate gets called before the Commander. You could be up for a promotion!}
{381}{}{Seems unlikely. Most of the time, I'm just pretending to work.}
{382}{}{I've been working pretty hard lately. You could be right.}

# Node_008
{410}{}{Just don't forget about us when you've made your fortune. I'll see you later.}
{411}{}{Wait, who are you?}

# Node_009
{440}{}{Well, it's okay to relax sometimes, right? We all do that. Whatever she wants, you shouldn't keep her waiting. I'll see you later.}

# Node010
{470}{}{I'm Brother Glenn Deering, one of the Elders. We'll talk later, }
{471}{}{.}
{472}{}{Of course, Elder.}

# Node011
{500}{}{Hello, Brother }
{501}{}{. Good to see you again, fully awake and aware. How can I assist you?}
{502}{}{Hello, Sister }
{503}{}{. Good to see you again, fully awake and aware. How can I assist you?}
{504}{}{Can you tell me a bit about yourself?}
{505}{}{What can you tell me about the Commander?}
{506}{}{In no way. Goodbye, Elder.}

# Node012
{530}{}{I began my career as a junior scout. I was one of the original team members who started exploring the east with Elder Brixley. Others have called me dedicated and loyal.}
{531}{}{What exactly do you do on a daily basis?}

# Node013
{560}{}{I oversee the basic functioning of the base and its personnel. It requires me to be a hard worker, but I rarely let anything upset me.}
{561}{}{I see. Tell me something else.}
{562}{}{Thanks. Goodbye.}
{563}{}{Can you tell me more about the base and its history?}

# Node014
{590}{}{I find my superior to be very confident, and we all learned a lot from her. But I also recognize her lack of organizational abilities, so I discreetly handle anything she overlooks or forgets. Hah, just don't tell Andrea this - she would kill me!}
{591}{}{You two seem to get along great. Is there something more going on there?}

# Node015
{620}{}{[He blushes.] No, no. That would be highly unprofessional of us.}
{621}{}{Understandable. Tell me something else, Brother.}
{622}{}{If you say so. Goodbye.}

# Node016
{650}{}{[He blushes.] I've always held her in the highest regard, and yes, this eventually turned into love. However, Andrea's promotion to Commander placed me in an awkward position, and I can't confess my feelings for her. It's a sacrifice I must make. The Brotherhood comes first. Above all.}
{651}{}{Hmm... Tell me something else.}
{652}{}{That sounds tough. Good luck, Brother.}

# Node017
{680}{}{How can I assist you?}
{681}{}{That's all. Goodbye, Elder.}

# Node018
{710}{}{Of course. I'll give you the summary and a copy of my chronicles, which go into more detail.}
{711}{}{Thank you, Elder. Let's hear it.}

# Node019
{740}{}{Maxson Bunker was a pre-war fallout shelter built by a senator for his family and himself. Unfortunately, the war caught him unaware, and the bunker was never used. All but forgotten, the bunker's location was passed down as a family secret from one generation to the next. Eventually, a family member passed the secret on to Roger Maxson, who claimed it for the Brotherhood of Steel.}
{741}{}{I see. And what is the current situation?}

# Node020
{770}{}{The bunker was intended to be used as a staging area for exploration teams scouting the east. However, once the war broke out with the New California Republic, the bunker became a forward base of operations against Hoover Dam, an NCR outpost. The war effort has gone poorly for both sides. We have superior technology, but the NCR has superior numbers of troops. As a result, the war has been at a stalemate for years.}
{771}{}{I've heard rumors of deserters. Are those true?}

# Node021
{800}{}{I'm sorry, but I can't comment on that. You'll have to excuse me now. I need to go over some paperwork.}
{801}{}{Goodbye.}
