# Message file for mbpalad.ssl
# Number of nodes: 1
# Grammar pass done

{102}{}{You see a dedicated Brotherhood of Steel member.}

{200}{}{Looking good. Keep up the great work.}
{201}{}{Jerry is my role model.}
{202}{}{I wish I could be training right now. Guard duty feels like a waste of time.}
{203}{}{Davis is my inspiration.}
{204}{}{I have to find time between patrols and training to keep up with my studies. I think I'm getting a bit rusty.}
{205}{}{Did you know that you can survive for weeks without water in a suit of powered armor? Fascinating, isn't it?}
{206}{}{Don't you just love the thrill of a good fight?}
{207}{}{I really like the new laser rifles, but the old laser pistols hold a special place in my heart.}
{208}{}{The night perimeter patrols are extremely dangerous. I wouldn't advise wandering too far at night if I were you.}
{209}{}{Stay vigilant. The world out there is filled with deadly threats.}
{210}{}{I think there's a spot on my armor! It's bothering me.}
{211}{}{Being part of the Brotherhood is incredible. I haven't had much experience outside of it, but I can't imagine anything better than this.}

{300}{}{Sorry, Initiate, but this area is restricted to guards only.}
{301}{}{What brings you here? This room is designated for guards.}
{302}{}{The guard room is off-limits to non-guards. Please leave.}
{303}{}{This area is for authorized personnel only. Please vacate the premises.}
{304}{}{No Initiates allowed in this area.}
{305}{}{If you're looking for the library, it's not here. This is the guard room.}
