# Message file for mbjerry.ssl
# Grammar pass done

{100}{}{A burly, but kind-looking man.}
{101}{}{It's Jerry, the squad leader. A competent warrior as well as a decent strategist.}
{102}{}{His stance is relaxed. Maybe not the most alert guy in the world, but he IS off duty and seems he hasn't seen real action in a long, looong time.}

{150}{}{Greetings, Brother. We will talk again later.}
{151}{}{Greetings, Sister. We will talk again later.}

# Start
{200}{}{Oh hey, you must be }
{201}{}{, our newest recruit. I'm Elder Paladin Jerry Corsetti. How's it going?}
{202}{}{Hey Brother Jerry. How are you?}
{203}{}{Sorry, Elder, I gotta run.}
{204}{}{Oh, it's good. How about you?}
{205}{}{[Blank stare]}

# AA
{230}{}{Oh, I'm doing all right. It gets a little boring here when we're not on a mission, but this is part of the job too, y'know?}
{231}{}{Amen to that. Say, how long has it been since you've been on a mission?}
{232}{}{Speaking of jobs, I've got to get back to mine. Later, Elder.}
{233}{}{Uh huh. How long have we been down here?}
{234}{}{I've got work to do. Bye bye, Jerry.}

# BB
{260}{}{Well, in that case, I won't keep you. Come by and chat if you have time, okay?}
{261}{}{Sure thing, Elder. See you later.}
{262}{}{[Wave goodbye]}

# CC
{290}{}{It's been over a year now. You know, I'm starting to think my squad will never go on another mission again. Regular patrols are just not doing it for us.}
{291}{}{Really? How did it come to that?}
{292}{}{Your squad?}
{293}{}{Wow, would you look at the time! I'll see you later, Elder.}
{294}{}{Me too. What's it like outside?}
{295}{}{Skvad?}
{296}{}{Uhhh, me go now.}

# DD
{320}{}{Honestly, I don't care anymore. It's Commander Brixley's fault. I devised a plan to end the war with the local NCR once and for all, but she wouldn't approve it. She thought it was a borderline suicide mission and refused to listen to my tactical expertise.}
{321}{}{You're not the subtle type, are you?}
{322}{}{Good point. Listen, I've got to run. See you later, Brother Jerry!}
{323}{}{You no fun Jerry! Me want see outside!}
{324}{}{I go work now, okay?}

# EE
{350}{}{Yeah, I lead a special squad. We're the ones sent in when situations demand special attention and tactics. We're the "clean-up crew," you could say. I enjoy getting up close and personal with the enemy. Once a grunt, always a grunt.}
{351}{}{Don't you get tired of fighting all day?}
{352}{}{You must have achieved many victories then?}
{353}{}{You no bore of many kill?}
{354}{}{Many wins?}

# FF
{380}{}{Her policies regarding the war are lax and detrimental to the Brotherhood. Sister Traci should replace her, you know? She advocates for a more proactive solution to the war, if you catch my drift.}
{381}{}{Yeah, I guess the war won't last forever.}
{382}{}{Speaking of killing, I'm in deep trouble if I miss my shift. See you later, Elder!}
{383}{}{War not last for always.}
{384}{}{Oops, I late for work. Bye Jerry!}

# GG
{410}{}{Well, what else am I going to do? It's too dangerous on the surface to avoid fighting. Besides, it's not like I have a choice. We can't let the NCR win.}
{411}{}{I guess it's out of your hands unless you all do something about it together.}
{412}{}{So, how did we end up with this one-year pause in fighting?}
{413}{}{Uh uh. You all must do together.}
{414}{}{How come you stop kill?}

# HH
{440}{}{Oh, you better believe it, my Brother. My squad is crucial to the Brotherhood's survival. I'm incredibly proud of it and our accomplishments.}
{441}{}{Oh, you better believe it, my Sister. My squad is crucial to the Brotherhood's survival. I'm incredibly proud of it and our accomplishments.}
{442}{}{*sigh* Listen, I need to get back to work. I'll see you later.}
{443}{}{Uhhhm, I go to work now.}
{444}{}{I heard stories of deserters.}
{445}{}{Me hear some desertererers.}

# II
{470}{}{If you take the time to grow up, you'll grow old. And when you're old, it's time to die. We might as well keep fighting like we used to, or surrender immediately.}
{471}{}{That's a very youthful attitude, despite your age. I'll see you later, Elder.}
{472}{}{Me sorry, Jerry. Don't sad.}

# JJ
{500}{}{I'm not sad, okay? Just... just get back to work.}
{501}{}{Bye-bye.}

# KK
{530}{}{Right, well, I'll see you later, okay?}
{531}{}{[END]}

{560}{}{For years, the war raged on and was considered a victory for us. However, no matter how many troops fell to our superior technology, the NCR always seemed to have more replacements available. The Brotherhood, on the other hand, wasn't so fortunate.}
{561}{}{How come?}
{562}{}{No?}

{590}{}{As an elitist group, replacements were scarce. It became obvious that we were doomed to lose the war due to the NCR's overwhelming numbers. Morale at the bunker began to falter as the war seemed more and more hopeless. Eventually, it happened. Lower-ranking members of the Brotherhood began deserting their posts.}
{591}{}{We're going through tough times right now, but the Brotherhood will prevail! Just as it did before. Farewell, Brother.}
{592}{}{We crush NCR bad guys! Bye-bye now.}
{593}{}{But what exactly started it all?}
{594}{}{Why war?}

{620}{}{You're asking about old ghosts there, kid. The Brotherhood-NCR war... well, that's a story steeped in bad blood and old grudges. I suppose it was inevitable. The NCR was always hungry, always expanding. They just wanted to spread, control, and consolidate power. But the Brotherhood... we've always been about preserving the old world, not making a new one. We kept the technology of the old world safe, kept it out of the hands of those who'd misuse it.}
{621}{}{And that led to war?}
{622}{}{Then war?}

{650}{}{Well, there's a bit more to it than that. You see, the real trouble started with the assassination of President Tandi in 2248 and the bombing of the NCR Congress the following year. Ah, those dark days. Yeah, they shook the wasteland, no doubt about it.}
{651}{}{What can you tell me about President Tandi?}
{652}{}{Prez Tadi?}

{680}{}{Tandi... she was a force of nature, a visionary. She turned Shady Sands from a small, struggling settlement into the backbone of the New California Republic. But not everyone saw her dream of a unified wasteland as a good thing.}
{681}{}{So, she was assassinated?}
{682}{}{Tadi die?}

{710}{}{That's right, though the details are murky. Some say it was a lone gunman, others claim a conspiracy within the NCR. There were even whispers about Enclave remnants or even the Brotherhood being involved, but there's never been any concrete proof. Her death left a vacuum, and chaos followed.}
{711}{}{And the bombing of the Congress?}
{712}{}{Boom?}

{740}{}{That happened not long after Tandi's assassination. The NCR Congress was in session when the bombs went off. It was a massacre. It sent a shockwave throughout the NCR, destabilizing their government for quite a while.}
{741}{}{Who was behind the bombing?}
{742}{}{Who boom?}

{770}{}{That's been a subject of debate for years. Official NCR reports claim it was the work of Brotherhood extremists, because of a plasma bomb used for it, but we deny it. There's always been speculation about other groups too - the Khans, the Enclave, even internal factions within the NCR. Whoever did it, it pushed the NCR and the Brotherhood further apart, fueling the fire of war.}
{771}{}{Fascinating. Thanks for answering my questions. Farewell.}
{772}{}{Wow! Bye-bye.}

{800}{}{Brother, we face a dire situation.}
{801}{}{Sister, we face a dire situation.}
{802}{}{Devon, in his betrayal, has changed all the access codes to our bunker's armory. All our supplies have been tampered with. Without weapons and armor, we are vulnerable.}
{803}{}{That's a significant security breach, Elder. We need to act swiftly.}

{830}{}{Agreed. We have reason to believe that Isaac Gant, a former Brotherhood member, possesses knowledge of the reset codes. Your task is to track him down and retrieve these codes by any means necessary.}
{831}{}{Understood, Elder. Do we have any leads on Gant's whereabouts?}
{832}{}{I really don't have time for this. Send someone else on your little mission.}

{860}{}{Unfortunately, we have no current leads. However, considering Isaac's history, he's likely not too far from any location with pre-war technology.}
{861}{}{I'll begin the search immediately, Elder. Rest assured, I'll do whatever it takes to ensure the security of our bunker.}

{890}{}{Your determination is commendable, Brother.}
{891}{}{Your determination is commendable, Sister.}
{892}{}{Time is of the essence.}

{920}{}{I'm surrounded by idiots!}
{921}{}{Beats me.}

{950}{}{Any news about those armory codes?}
{951}{}{Mission accomplished, Elder. I've secured the armory codes on this specialized holodisk. Isaac proved to be a helpful guy.}
{952}{}{Nothing yet. I'm working on it.}

{980}{}{That's fantastic!}
{981}{}{Well done, Brother!}
{982}{}{Well done, Sister!}
{983}{}{[He gives you a big pat on the back and displays an interesting rifle.] As a small gesture of gratitude, I want you to have our experimental Laser Array Gun.}
{984}{}{Thank you, Elder. I'm sure I'll put it to good use.}
