# Message file for mbjean.ssl
# Number of nodes: 16
# Grammar pass done

{100}{}{You see a young, tall Initiate Knight.}
{101}{}{You see Jean-Baptiste Cutting, an Initiate Knight.}
{102}{}{You see someone wearing a military tag with the name Jean-Baptiste Cutting on it.}

{150}{}{Fuck, what now? Please, I need to focus on my trainin'. Patrol duty is already givin' me a hard time.}

# Node001
{200}{}{Get the fuck away from me, or you'll be the next "volunteer" for our weapon testin'.}
{201}{}{Get the fuck away from me, or you'll be the next "volunteer" for our weapon testin'.}
{202}{}{Is that how you address your fellow Brotherhood members too? Show some respect.}
{203}{}{Raise that gun, and you'll regret it.}
{204}{}{Are you Jean-Baptiste Cutting, an Initiate Knight? I want to ask you about your Vault 13 jumpsuit.}
{205}{}{Are you feeling alright? You don't look well.}
{206}{}{Apologies for bothering you.}
{207}{}{Snargle!}
{208}{}{Me sooooooooooory.}

# Node002
{230}{}{I have no idea what you're talkin' about. What the fuck do you want?}
{231}{}{You'll have to come back to Tibbets with me.}
{232}{}{I have a few questions for you.}

# Node003
{260}{}{I'm sorry, Brother. I'm relatively new here and haven't had the chance to meet everyone. It won't happen again.}
{261}{}{I'm sorry, Sister. I'm relatively new here and haven't had the chance to meet everyone. It won't happen again.}
{262}{}{Who are you, Initiate?}
{263}{}{Alright, there's something else I want to know.}

# Node004
{290}{}{[He pauses for a moment, gazing into the distance.] Smooth-talk was never my forte. I prefer a more direct approach.}
{291}{}{[CONTINUE]}

# Node005
{320}{}{Mama said I've always had a knack for breakin' things. When we were kids, everyone fought over toys, but I was the one who broke them.}
{321}{}{Cut to the chase.}

# Node006
{350}{}{If anyone crossed me, I'd break their toys too. Sometimes, I'd break them just to show them who's in charge, even if they were nice to me.}
{351}{}{I see where this is headed.}

# Node007
{380}{}{One day, my mama pulled me aside and said, "Boy, you're never goin' to go very far, but you're goin' to make a whole lotta people come up short."}
{381}{}{We'll see about that.}
{382}{}{Look, we don't have to fight. Hand over your Pip-Boy, and the robots will think you're dead.}

# Node008
{410}{}{I am Jean-Baptiste Cuttin'. Our family hails from Reddin', to the west. We specialize in weapons tradin', but we dabble in other commodities, like gold, if it's profitable.}

# Node009
{440}{}{Tiaret Van Graff, our mama, has been at the helm for longer than most of us have been alive. She oversees operations from the home office, while my brothers and sisters run branches all over the place.}
{441}{}{Your mother sounds like an intriguing woman.}

# Node010
{470}{}{Momma's quite popular with the menfolk, thanks to her wealth and beauty. That's why I have ten siblings, each from a different father.}
{471}{}{You didn't have to mention that. Anyway...}
{472}{}{Tell me about your siblings.}
{473}{}{Why don't you have the Van Graff last name?}

# Node011
{500}{}{What do you want?}
{501}{}{Where did you get your Vault 13 jumpsuit?}
{502}{}{Tell me about the Van Graffs.}
{503}{}{Nevermind. Goodbye.}

# Node012
{530}{}{We're a wild bunch. My sister Frieda runs a branch called Frieda's Firearms in Hoover Dam. They've got some sweet pre-war tech there. I thought you might be interested. The rest of my siblings have stories that would take too long to tell.}
{531}{}{Tell me something else.}
{532}{}{Ahh, yes, Hoover Dam, I know it. Will make sure to tell your sister about our chance meeting.}

# Node013
{560}{}{I'm fine. Just dealin' with a naggin' fever and cough. I'll tough it out.}
{561}{}{If you say so. Anyway...}
{562}{}{You should have a doctor check up on you. Goodbye.}

# Node014
{590}{}{Unlike most of my brothers and sisters, my mama didn't discard my papa. He passed away just before I was born. Mama liked him so much that she insisted I use his last name. She said he deserved that much, even if he never got to meet me or nothin'.}
{591}{}{Touching. Tell me something else.}

# Node015
{620}{}{You know what? I think you mean it. Alright... maybe...}
{621}{}{Good. Now answer some questions for me.}

# Node016
{650}{}{Plannin' to take on a Brotherhood patrol? Alright, fool. The joke's on you.}
{651}{}{[Attack him.]}

# Node017
{680}{}{Hmm... Fuck the Pip-Boy. If it'll get you and those robots off my back. [He tosses it to you.] Never really cared for it anyway. It reminds me of those dark, claustrophobic corridors.}
{681}{}{Thanks. I'll leave you to your training then.}
