# Message file for mbpalad.ssl
# Number of nodes: 1

{102}{}{You see a Brotherhood of Steel member.}

{105}{}{A mutant!}
{106}{}{It's a mutant!}
{107}{}{Mutant contact!}

# directly spoken too lines
{199}{}{Hail! I hope your patrols have fared well.}
{200}{}{Good day.}
{201}{}{Stay sharp!}
{202}{}{Looking good. Keep up the good work.}
{203}{}{Hello, everything is secure.}
{204}{}{Sorry, I shouldn't be talking to anyone. You know how it is.}
{205}{}{You should talk to Elder Glenn or General Brixley if you have any questions.}
{206}{}{Now that Davis is in the brig I have no idea who could help me with tougher technical questions.}
{207}{}{If you need anything, you should talk to the Elders.}
{208}{}{Brother Glenn is there if you need to talk to someone.}
{209}{}{You've got to keep your mind and body in top condition at all times.}
{210}{}{Sorry, can't talk.}
{211}{}{Good day.}

{212}{}{I wish I was training right now. Guard duty is a waste of time.}
{213}{}{Brother Jerry is my idol.}
{214}{}{Davis was my idol. Such a shame.}
{215}{}{I've got to find time between patrols and training to keep up with my studies. I think I'm getting a little rusty.}
{216}{}{Being a Paladin isn't just combat.}
{217}{}{Did you know you could survive for weeks without water in a suit of powered armor?}
{218}{}{Don't you just love a good fight?}
{219}{}{I really like the new laser rifles, but the old laser pistols are my favorite.}
{220}{}{The night perimeter patrols are very dangerous. I wouldn't wander too far at night if I were you.}
{221}{}{Be careful, it's a deadly world out there.}
{222}{}{I think my armor has a spot on it!}
{223}{}{The Brotherhood is great. I haven't had any experience outside of it, but it couldn't possibly get better than this.}
