# Message file for mbsarah.ssl
# Number of nodes: 38
# Grammar pass done

{100}{}{You see the Brotherhood's Doctor.}
{101}{}{You see Doctor Sarah, a trusted physician of the Brotherhood.}
{102}{}{She appears to be engrossed in her work.}

{150}{}{Guards!}
{151}{}{You have joined the Brotherhood of Steel.}

{190}{}{Greetings, I am Doctor Sarah Whatley. I invited you here, and I kindly request your cooperation. First, allow me to examine you for any signs of illness.}
{191}{}{Of course, Doctor. I'll cooperate with your examination.}
{192}{}{Stay away from me! Don't try anything!}
{193}{}{Hold your horses, Doctor. What exactly is the Brotherhood of Steel? I want to know what I am getting myself into.}

# Node001
{200}{}{Interesting. According to the Auto-Doc, you appear to be in good health, although your white blood cell count is unusually high. I'll conduct additional tests to ensure I didn't miss anything. However, I have a proposition for you. We are in dire need of capable individuals like yourself, and I'd like to extend an offer to you.}
{201}{}{An offer? I'm all ears.}
{202}{}{Not interested. I tricked my way in to steal your cool toys.}
{203}{}{I'm sorry, but I don't have time for this.}
{204}{}{The NCR is your enemy, and now it's payback time for me.}
{205}{}{Oh my.... you're... you're a GHOUL?! Guards!}
{206}{}{Yeah, I am. So?}

# Node002
{230}{}{I understand. In that case, the guards will escort you out. Farewell.}
{231}{}{Goodbye.}

# Node003
{260}{}{Our base commander, General Andrea Brixley, is suffering from a mysterious illness that even the Auto-Doc can't diagnose. Elder Brixley's life is in jeopardy unless we find a cure. We request your assistance in uncovering the cause and finding a remedy. However, you must join our ranks before commencing the investigation. We will reward you generously for your help.}
{261}{}{Why me?}
{262}{}{Say no more! I won't disappoint the Brotherhood, Doctor! Any leads or suggestions on where to start?}

# Node004
{290}{}{We lack individuals with your streetwise skills. Your expertise could be invaluable in this investigation. Please lend us your aid.}
{291}{}{Alright, I'll help. Do you have any leads?}
{292}{}{I'm not in the mood for this right now.}

# Node005
{320}{}{Unfortunately, I don't have specific information on where to start. Initiates are restricted from accessing other levels, so your investigation must begin here. However, I have unlocked my console for you, which may provide assistance. I trust you will prove yourself and make swift progress. And yes... [She shakes your hand.] Welcome to the Brotherhood of Steel, Initiate. I find this gesture more humane than a salute. If you discover anything, please inform me.}
{321}{}{Thank you! I'll inform you if I uncover any leads.}

# Node006
{350}{}{Hello, how can I assist you?}
{351}{}{I'm injured and need medical attention.}
{352}{}{I've been exposed to radiation and require treatment.}
{353}{}{Do you perform surgeries?}
{354}{}{Tell me more about yourself.}
{355}{}{Never mind.}
{356}{}{Did you find out why my white blood cell count is high?}
{357}{}{Elder Brixley was poisoned by a military-grade nerve agent!}
{358}{}{Brix poison!}

# Node007
{380}{}{Are you injured? Let me take a look.}
{381}{}{Thank you, Doctor.}

# Node008
{410}{}{Radiation is very dangerous. You should be more careful.}

# Node009
{440}{}{Performing surgeries is not my area of expertise. The senior medical staff either died or deserted, leaving me with limited resources. As you can see, I only have one very young assistant. He's still a teenager so I have been studying medicine on my own. I could try performing a surgery but it's a costly and time-consuming process.}
{441}{}{Can you provide more details?}
{442}{}{Okay, never mind.}
{443}{}{What happened to the medical staff?}

# Node010
{470}{}{I can enhance various aspects of your physical abilities: strength, perception, endurance, intelligence, and agility. Each enhancement can only be performed once, and it comes at a cost. Which one are you interested in?}
{471}{}{Strength.}
{472}{}{Perception.}
{473}{}{Endurance.}
{474}{}{Intelligence.}
{475}{}{Agility.}
{476}{}{I'd rather not risk my health. Goodbye.}

# Node011
{500}{}{I joined the Brotherhood because of my younger brother, Edward. After our parents passed away, I promised to take care of him. When he joined the Brotherhood, I followed suit to fulfill my promise.}
{501}{}{Tell me more.}
{502}{}{That's great, but I have to go. Goodbye.}

# Node012
{530}{}{I never had much interest in the military. I struggled with the required skills and only got in because of Edward. As long as he was with me, they couldn't get rid of me.}
{531}{}{What happened then?}
{532}{}{Look at the time fly. I really have to go now. Goodbye.}

# Node013
{560}{}{Eventually, I discovered my passion for the medical field. It surprised everyone, including myself. I showed potential and became a competent doctor. It was a revelation, finding my place in the world.}
{561}{}{Good for you, Sarah.}
{562}{}{That's fantastic. Now excuse me, I have to use the restroom. Goodbye.}

# Node014
{590}{}{Thank you! I'm still an intern here at the base. Unfortunately, the previous medical staff either deserted or died, leaving me to pursue my career independently. I take my work seriously and study everything I can find about medicine in the bunker's library.}
{591}{}{Thank you for sharing your story. Goodbye.}

# Node015
{620}{}{Some of the medical staff died fighting the NCR, while others deserted. There were disagreements among the Elders' leadership in this war, prompting some to leave. I'm not sure what happened to them afterward.}
{621}{}{Interesting. Thanks for sharing that information. Goodbye.}

# Node016
{650}{}{Increasing your strength is possible, but it requires a long recovery time of six weeks and costs 4,000 caps.}
{651}{}{I'll do it!}
{652}{}{I'll pass.}

# Node017
{680}{}{Enhancing your perception is more challenging. The procedure takes two weeks to recover from and costs 8,000 caps.}

# Node018
{710}{}{Improving your endurance is a relatively simple operation. It takes about two weeks to recover, and the cost is 6,000 caps.}

# Node019
{740}{}{Increasing your intelligence is the most complex and dangerous procedure. It requires a recovery time of six weeks and costs 12,000 caps.}

# Node020
{770}{}{Enhancing your agility isn't too difficult, but it is costly and time-consuming. The recovery time is six weeks, and it will cost you 10,000 caps.}

# Node021
{800}{}{I'm sorry, but I can't assist you if you don't have the necessary funds.}
{801}{}{Why do I have to pay for it?}
{802}{}{I'll come back when I have the money.}

# Node022
{830}{}{As an outsider and considering the ongoing war, every cap is crucial for us. There are expenses involved. Once you have been a member of the Brotherhood for about ten years, I can perform the operation for free.}
{831}{}{I understand. Goodbye.}

# Node023
{860}{}{Okay, here goes nothing... Just kidding. We can start the procedure right away. [She administers anesthesia, and you slowly drift away.]}
{861}{}{[CONTINUE]}

# Node024
{890}{}{So, how do you feel now? [You notice a significant improvement.] You're quite a talkative sleeper, by the way. You're free to go! Good day.}
{891}{}{[END]}

# Node025
{920}{}{Out with the old, in with the new... [You drop into the abyss like a rock.]}

# Node026
{950}{}{You look exactly the same, but how do you feel? [All your senses feel sharper.] Well, you're taking up valuable bed space. Get going!}

# Node027
{980}{}{I hope you have a heart... [She winks as you fall under the effects of anesthesia.]}

# Node028
{1010}{}{Well, you look a little bulkier. [You feel great!.] Let me know if you experience any issues.}

# Node029
{1040}{}{Now, where's the brain again? What does this thing do? [You struggle against the chemicals, but they overpower you.]}

# Node030
{1070}{}{Well, it appears that everything is in order. [Your thoughts flow effortlessly, and your memories are clearer.] Take it easy.}

# Node031
{1100}{}{All right, let's see how it goes. [The chemicals induce sleep quickly.]}

# Node032
{1130}{}{Okay, you're ready for duty. [You flex your muscles and feel increased speed and control.] Please be careful not to damage my masterpiece.}

# Node033
{1160}{}{If anyone here needs an Intelligence Enhancement, it would be you. In fact, I can perform the operation for 6,000 caps instead of the usual 12,000. It will also take six weeks to recover. I can't guarantee its effectiveness, but it might be worth a try. You probably don't fully understand this, do you?}
{1161}{}{Me want smart.}
{1162}{}{No want.}

# Node034
{1190}{}{Are you injured or suffering from radiation? If so, I'll do my best to assist you.}
{1191}{}{Me hurt.}
{1192}{}{Hair fall out.}
{1193}{}{No.}

# Node035
{1220}{}{Alright, you're awake. Can you sense any improvement in your cognitive abilities?}
{1221}{}{Hunh?}
{1222}{}{Yes!}

# Node036
{1250}{}{Damn! It was a failure. Well, I didn't have much to work with. I'm sorry to say, but you're still an idiot and are likely to remain that way. We can only perform the operation once.}
{1251}{}{Oki.}

# Node037
{1280}{}{It was a success! I managed to increase your IQ to an acceptable level. How does it feel to have a higher intellect?}
{1281}{}{Wow, it's like I've been seeing the world through a foggy window, and now it's clear. I can understand things I never even thought about before. It's... it's incredible. Thank you.}

# Node038
{1310}{}{There you go. You're all better now.}
{1311}{}{[Shamble off.]}

# Node039
{1340}{}{I still don't have a clue, sorry. However, I'm studying the vast medical field every day and hope to find the answer someday.}
{1341}{}{I see. Thanks for your effort.}

# Node040
{1370}{}{That's fantastic news! Wait, that sounded wrong. Heh. Your discovery is fantastic, not Commander Brixley's poisoning. Quickly, show me your research. My assistant will inform the Senior Scribes and Knights immediately. We must start working on an antidote.}
{1371}{}{[Present your discovery to the Doctor.]}

# Node041
{1400}{}{So, the assassin used military-grade tech to refine the toxin extracted from a nightcrawler's spitball... I can think of only two groups capable of producing such a sophisticated weapon - the NCR and the Brotherhood deserters. We must get to the bottom of this! I'm sure the Commander will want to speak with you once she recovers. Now, get some rest. You've worked hard, and don't refuse. This is an order. I've arranged for your private quarters on Level 2. Enjoy them, Initiate.}
{1401}{}{Thank you, Doctor. I appreciate it.}
{1402}{}{Thank, Doc! My room!}

# Node042
{1430}{}{Ah, we're more than just a formidable group. We're like a family bound by a sacred mission - to protect and preserve the remnants of pre-war technology. Our founders believed in the importance of safeguarding knowledge, ensuring it doesn't fall into the wrong hands. Non-human hands. Some may see us as rigid or aloof, but we're driven by a noble cause. We stand as guardians against chaos, holding the torch of progress in a world consumed by darkness. And mark my words, we'll do whatever it takes to fulfill our duty, even if it means making tough choices. Now, about that examination.}
