# Message file for tbprsn.ssl
# Number of nodes: 1

{102}{}{You see a Brotherhood of Steel member.}

{150}{}{You shouldn't be here. Guards!}

{200}{}{Research is one of my favorite things to do. I feel like I'm trying to solve a mystery.}
{201}{}{Being a scribe is the best. You get to study all the old technologies and try to develop new ones.}
{202}{}{These terminals could use an enhancement. Maybe we should put the display over here.}
{203}{}{Meditation calms the spirit and clears the mind.}
{204}{}{Jerry is the bee's knees.}
{205}{}{Will the universe continue to expand, or will it eventually collapse back in on itself?}
{206}{}{Us Scribes design all the equipment, weapons, and supplies. It's quite exciting.}
{207}{}{Glenn sure is nice.}
{208}{}{Davis is in the prison.}
{209}{}{Technology must be preserved.}
{210}{}{Science is so much fun.}
{211}{}{I've seen an alien space ship before.}
{212}{}{Did you know that the sun is actually a big nuclear reaction? Similar to what ended the old world, except it's fission, no fusion.}
{213}{}{Did you know that a black hole is actually an opening to another universe? I have it all worked out on paper. Too bad there won't be any more space travel until long after I'm dead.}
{214}{}{Did you know that the hydrogen atom is 99.9843425% empty space?}
{215}{}{Time travel will one day be possible and we might be able to prevent the disaster that ruined our world in the past. But wouldn't that... stop us from going back if it was fixed... oh, my head hurts.}
{216}{}{I love those old books and magazines, but they are so hard to come by.}
{217}{}{Knowledge is power.}
{218}{}{The pen is mightier than the sword.}
{219}{}{Traci is so pretty.}
{220}{}{Technology must be preserved.}
{221}{}{Davis was my idol.}
# directly spoken too extra lines
{222}{}{Sorry, I'm right in the middle of a possible breakthrough. I can't talk right now.}
{223}{}{Sorry, we are meditating.}
{224}{}{Hey there. You should train to be a Scribe, if you haven't decided yet.}
{225}{}{Why don't you join us in meditation?}
{226}{}{Please don't disturb me. I'm trying to finish my research.}
