# Message file for mvalex.ssl
# Number of nodes: 93

{100}{}{You see a woman in her late 20s.}
{101}{}{You see Alexandra.}
{102}{}{She'd look more attractive if it weren't for the perpetually icy look in her gray eyes.}

{150}{}{You helped Blackjack escape from the bounty hunter.}
{151}{}{You helped Alexandra capture the super mutant.}

# Node 0 [dead_jermiah]
{200}{}{Thank da' lord. Guess ya didn't have any visions 'bout that, huh bastard?}

# Node001
{230}{alex001}{Now who da hell are ya? I got dibs on a bounty here, so ya better scram.}
{231}{}{A bounty? Someone's hiding in the cave?}
{232}{}{No need to get hostile. I just wanted to know what was going on.}
{233}{}{What's with the brahma girl outfit?}
{234}{}{Pfft. Whatever you say, Calamity Jane.}

# Node002
{260}{alex002}{Nosy are we? *sigh* Guess it don't matter much you knowin', since da green bastard ain't comin' out. Super Mutant fella by name o' Blackjack. For such a name, his luck definitely ain't winnin' him favors. Problem is, that mutant bastard has a minigun. Now I's might be rough n' all, but I ain't riskin' my hide being sprayed out in a dank cave. So... Figure I'd starve em' out.}
{261}{}{I could speed up the process for you and take him out. Maybe we can split the bounty?}
{262}{}{Honestly is it worth it though? Sure you'll starve him out, but then you'll be wasting days sitting outside a cave in this scorching heat. A lot of water is being wasted. Lot of time too...}
{263}{}{Surely the amount of time you'd waste for a mutant with a minigun to die out, is more expensive than just leaving him be right?}
{264}{}{This doesn't look fruitful. Come on. All this waiting around? That's not exactly how bounty hunting should go. Come with me and I can promise you a lot more action and cash than this.}
{265}{}{This is ridiculous. A gunslinger wannabe outside a cave waiting on a huge ass green guy to starve? Isn't this embarrassing?}
{266}{}{Well good luck with that.}

# Node003
{290}{alex003}{Do you usually walk up to strangers with guns poached outside caves? Anyhow, I understand friendl'ness n' all, but you can kindly fuck off.}
{291}{}{Fuck you too.}

# Node004
{320}{alex004}{I can ask you the same with that goofy ass fit wit' the aimless wanderin' steps ya take.}
{321}{}{Hmph!}

# Node005
{350}{alex0050}{Right back at ya, Mista' fish eyes-little dick.}
{351}{alex0051}{Right back at ya, Miss bitch o' the west.}
{352}{}{Whatever.}

# Node006
{380}{alex006}{Except I's need him ALIVE. He's a potential slave, not some fuckin' beast to be hunted for taxidermy. *sigh* But by all means, if ya want to get sprayed into a new moon, go 'head. If *somehow* you do get the drop on da bastard, I will split it with ya. My word is bond. Just... Please. Keep him alive. That is lit'ally all I ask.}
{381}{}{I'll see what I can do.}

# Node007
{410}{alex007}{Fuck... Yea, god damns it. Ya right. Waste o' my fuckin' time and rations. Sides, not like the Legion can't send one o' them boy scouts out here if they really wanted him. Alright, guess he can walk. Fucker's lucky I'm feelin' tired.}
{411}{}{Sure, I'll tell him he's off the hook.}

# Node008
{440}{alex008}{Can it, vulture. I know ya slimy act from a bald eagle's view. You. Ain't. Gettin' between me n' my mark. Now try and poach off someone else's claim 'fore I decide to play target practice.}
{441}{}{[END]}

# Node009
{470}{alex009}{W'all ain't you just a knight in shinin' armor. Fine. Guess I really got nothin' better to do than watch the sun sizzle my skin. Fuckin' hotter than a brahmin's otter on a grill. Well then, I guess we're pardners. Get me out o' this dang heat. I's Alexandra.}
{471}{}{The name's }
{472}{}{. Let's go, partner.}
{473}{}{[Shake her hand.]}
{474}{}{Whatever, let's hit the road.}

# Node010
{500}{alex010}{W'all ain't that new. Someone tryin' to sweep me off my feet in the middle o' a hunt. Much as I'm flattered, you can kindly stick that attempt at courtship where the sun don't shine.}

# Node011
{530}{alex011}{Heh, thanks I guess.}
{531}{}{So long.}

# Node012
{560}{alex012}{Well? I's know you seen the fuckin' mutie. Where is he? Why ain't he wit' ya?}
{561}{}{I want to pay off Blackjack's bounty. How much is it?}
{562}{}{Yea, he actually has a huge minigun. Only reason I walked out here is because he'd kill me if I didn't tell you to drop this. He's desperate and might make a move to attack.}
{563}{}{It's so awful! I tried to get the jump on him a-and... Oh god! The bodies! The meat hooks! He has a plasma mine strapped onto his chest ready to blow us all up!}
{564}{}{Honestly, he won't budge. I don't know what to do.}
{565}{}{Whoops! Knew I forgot something.}

# Node013
{590}{alex013}{Ya really want to pay off his bounty? Tsk, A'ight. That'll be 'bout... 500 Caps.}
{591}{}{Here you go. 500 caps. He's good to go now, right?}
{592}{}{Wow, I do not have that kind of money.}
{593}{}{You know what, nevermind all that.}

# Node014
{620}{alex014}{Shit! Okay, that ain't fuckin' worth it for me. Damn it, damn it! I knew I was gettin' o'er my head on this one. A'ight. Tell da mutie I'm out o' here.}

# Node015
{650}{alex015}{Oh wow. All that in da span o' what... A couple hours of me standin' here? Now if ya done fuckin' around, either get that bastard out here or LET. ME. HANDLE. IT.}

# Node016
{680}{alex016}{Figures. Muties are always da hardest to rope. In all the ways ya can imagine. Thanks for tryin' but I's say just leave' em in there. He'll come out eventually.}
{681}{}{I guess.}

# Node017
{710}{alex017}{Mind must be hairs thicker than a tumbleweed. Idiot.}
{711}{}{Heh.}

# Node018
{740}{alex018}{Huh, right then. Guess ya just saved me hours o' boredom. Tell that cave sleeper he ain't needin' to worry 'bout me. He definitely needs to keep low though in da future, 'case some other hunter comes along. Once a bounty is out, all is game.}

# Node019
{770}{alex019}{Then you don't have what it takes to stop this. Sorry, but I ain't stoppin' less caps come rainin' from the sky.}
{771}{}{Alright.}

# Node020
{800}{alex020}{Knew you'd say that. *chuckles*}
{801}{}{What can you do. Goodbye.}

# Node021
{830}{alex021}{W'all I'll be! Ya got the bastard! How'd you do that?!}
{831}{}{Just have a way with words. What can I say?}
{832}{}{He was lying. That minigun was just a bunch of big sticks and pipes tied together. Did a nice paint job all things considered.}
{833}{}{A magician never reveals his secrets.}
{834}{}{It was pretty easy. You can take some pointers from me.}

# Node022
{860}{alex022}{*Chuckles* Whatever you say, casanova. Guess a deal's a deal. Come wit' me. Gon' be a long travel but ya did want the pay, right?}
{861}{}{Forget it, I don't have the time for that right now. We'll meet at Fort Abandon once you have the money. We can discuss new business opportunities there and then.}

# Node023
{890}{alex023}{Ya got to be fuckin' kiddin' me! A bunch of sticks?! That son o' a... *bursts out laughing* Ya know what, I can't even be mad at all. First time someone pulled that o'er me! Guess a deal's a deal. Come wit' me. Gon' be a long travel but ya did want the pay, right?}

# Node024
{920}{alex024}{Oh don't ya start blabberin' slick shit on me. Anyhow... Guess a deal's a deal. Come wit' me. Gon' be a long travel but ya did want the pay, right?}

# Node025
{950}{alex025}{Mhmm. Sure thing, big shot. So guess a deal's a deal. Come wit' me. Gon' be a long travel but ya did want the pay, right?}

# Node026
{980}{alex026}{Wh-What da fuck is dat shit?! No! No! No, no, no, no! God damns it, who did this?!}
{981}{}{Must've been the mutant. I guess he would rather die a free man.}
{982}{}{Oh man I don't know! It just happened! Phew, happy I got out when I did!}
{983}{}{I did that.}
{984}{}{Oh would you look at that, gotta go!}

# Node027
{1010}{alex027}{Son o' a... Augh! I'ma need a drink. Might as well snag that and head back. Fuck me. Just what I needed this week.}

# Node028
{1040}{alex028}{You did this, didn't ya? Ya yellow belly, tumbleweed smokin' sack o' rat meat! I'll make sure to splay ya guts 'round this place!}
{1041}{}{[Defend youself.]}

# Node029
{1070}{alex029}{Ya... What?! Oh dat's it. Ya think ya cute, eh? A'ight, time to show ya why I like huntin' vermin like you. Get ready, punk!}

# Node030
{1100}{alex030}{I'm a count to 10. Better get da fuck out o' my sights by then.}
{1101}{}{Alright, alright. I'm leaving.}
{1102}{}{1, 2, 3... 10!}

# Node031
{1130}{}{[The woman's face is expressionless, but her piercing gray eyes lock onto you. She starts reading aloud from a wanted poster in her hands.]}
{1131}{}{! Wanted dead 'r alive fer killin' an' bein' a rat b'stard. Reward's 10,000 caps dead, or 5,000 alive, if ya can git 'em. What ya got t'say in yer sorry 'fense, huh?}
{1132}{}{You don't have to do this. Come with me. I have places to go that would give you fortunes you wouldn't believe.}
{1133}{}{I ain't no saint but who is? Join me and I can guarantee the bounties will come to you. Tons of trouble finds me, and I can use someone of your talents. We'll split what loot we get off the corpses.}
{1134}{}{How about I make you a counteroffer. Would you consider joining me on the road? Tons of sights to see, caps to earn, and I'm always in need of a tough doctor.}
{1135}{}{We ladies should stick together in this crazy world. I need a partner to join up with. You got skill and I got places to go, caps to earn. What do you say?}
{1136}{}{[Attack her.]}
{1137}{}{[Start running.]}

# Node032
{1160}{}{Pft, right. I'm fine on muh' own. Go fly them magic bl'oons to someone else.}

# Node033
{1190}{}{Hmm... You don't look like the weaselin' type. Fine. Prob'ly need a gal who can stitch and shoot for ya anyhow. I'm in.}
{1191}{}{Good to have such a capable bounty hunter on my side. Let's earn those caps, partner.}

# Node034
{1220}{}{W'all... I don't got many options. Hmm. Alright. Can't see's why's not. Don't come cryin' though whenever ya scrape ya knee. That shit just pisses me off.}
{1221}{}{That's the spirit. Let's go, partner.}

# Node035
{1250}{}{Shit, shoulda' been there when I was scrapin' the bottom of a bo'le. Sure thing.}
{1251}{}{Welcome aboard, partner.}

# Node036
{1280}{}{Good ri'andce. Scum like that don' deserve to take another breath far as I'm concerned.}
{1281}{}{Couldn't agree more. Wackos like them deserve a bullet more than they deserve attention.}
{1282}{}{Honestly, I don't see a difference between this guy and the Legion.}
{1283}{}{You usually don't get personal with these kinds of bounties. You okay?}
{1284}{}{I mean all in all, it wasn't his beliefs that got him wanted.}

# Node037
{1310}{}{Glad to see's someone understands. *sigh* Anyway... Let's get that bounty.}

# Node038
{1340}{}{W'all it's a good thing I just get paid by the Legion. I'm not exactly wavin' any flag as a patriot for anybody, if *that's* what you's implying. Anyway... Let's get that bounty.}

# Node039
{1370}{}{*chuckles* Is this the part where I shed my whole life story on the floor for ya? Let's just say I got bad blood with these "religions" people thump about nowadays.}

# Node040
{1400}{}{Yea but all in all, it makes it sweeter to know he's buried six feet from ever preaching his bullshit to any dumbass that wants a purpose.}

# Node041
{1430}{}{What the fuck are ya doin' helping that bastard?!}
{1431}{}{You two got history? If so, I'll correct myself right now.}
{1432}{}{What are you pissing on my leg for? I'm just selling my services.}
{1433}{}{Whoa, calm down! What's the problem?}

# Node042
{1460}{}{You's better! That man's a sick piece o' shit that turned my family into monsters! His whole Mormon preach ain't nothin' but venom poisoning the weak minded.}

# Node043
{1490}{}{*hisses in a angered sigh* You ig'nernt fuck! That man is what got me split from fam'ly! He turned my ma and my pa against me, when I was just a teen!}

# Node044
{1520}{}{*deep breath* I... Alright. Suppose you need to know. I used to be a Canaanite. I never liked how's the way of livin' was taking mercy on bastards that pillaged our old home, but it turned sour real quick after. That man, Jeremiah? By the time I turned 16, he began to poison my folks into something awful. I ditched 'em' but tried to come back. Was 20 by the time I saw.. This.}

# Node045
{1550}{}{So we get to finally put an end to that bastard's poison. Jeremiah... How I've waited so long to do this to ya snake oil ass.}
{1551}{}{You knew Jeremiah?}
{1552}{}{Do you know ways we can dispose of him without any casualties?}
{1553}{}{I hope you know, I'm trying to seek better alternatives than murder.}
{1554}{}{Long as we get paid for it, go crazy!}

# Node046
{1580}{}{Sadly, yes. I knew 'em for a long time after New Jerusalem got scorched. We all was kids when we saw the horrors of them "desperate folk" pillagin' our homes for hospitality. I learned better than to give service to a "greater good" as one would put it. Jeremiah? Let's just say he's the reason my folks and I ain't speaking. He got these visions one day 'bout god saying to reclaim the lands of what became Jericho, and tellin' all men to force women through abstinence and several marriages. I was about 20 when his *cult,* The Hands of God formed. I ain't been back since.}
{1581}{}{He put a rift between your family?}
{1582}{}{What happened at New Jerusalem?}
{1583}{}{He would have been around your age right? How did he get that influential?}
{1584}{}{Let's discuss this some other time.}

# Node047
{1610}{}{Heh, yea. Shoot em' in the dead o' night. Make sure it's swift and easy. Hell, I'll do it for ya. Will make it feel all the more better for me to plug that snake.}

# Node048
{1640}{}{Are ya serious? Man's as crazy as he is a con artist. Hmph... I'll make it real simple for ya. You're wastin' time trying to see reason. He needs to go. There's a clean bounty of 1,000 on the line. If you's won't collect on it, I fuckin' will. Got it?}

# Node049
{1670}{}{Now ya spittin' my language. Let's get this bastard.}

# Node050
{1700}{}{*sigh* Yes. My pops and I never saw eye to eye cause of our ol' home being wrecked. He was always the good doc that wanted to stitch up the downtrodden. Then Jeremiah came along and pissed the whole town off at first: Speakin' of god and angels, how he was this living prophet to outdo Judah Black. Even had a whole pack leave with our former Bishop, Mordecai. Never knew what happened to em.'}
{1701}{}{[CONTINUE]}

# Node051
{1730}{}{Anyhow, My fam'ly was of the few who backed Jeremiah, and most likely now are a part of this Hands of God group. Many days I thank myself greatly for leavin' at sixteen.}

# Node052
{1760}{}{Better question is what *didn't* happen to New Jerusalem. I was a little girl back then, so memories are hazy. Fires, gunshots, corpses. Smoke. Whole place was a nightmare. I kept havin' bad dreams w'all into my teens, and sometimes I still do if I hit the whiskey too hard.}

# Node053
{1790}{}{Refugees stormed our home under the hopes we had more food than we offered. Desperate animals in human skin. Yet my fam'ly never got it through their bible thumpin' that these bastards were the reason for our struggles. To this day, they live in fantasy about god and the goodness of man.}

# Node054
{1820}{}{Desperation for new ideas over the old, maybe? Jeremiah says a lot of words painting the world pink with ol' grassy green patches and roses. Doesn't stop the smell of corpses our people left behind. New Canaan is a fairy tale at this point. A constant "what was" and not ever "what is." As long as Jeremiah holds his vision quest, all the folks that worship him will never face reality.}

# Node055
{1850}{}{Lets.}

# Node056
{1880}{}{W'all I'll be... We did it. I didn't think it'd happen like this. I dreamt o' it for some time, but I guess I shoulda' hung around more. Thank you.}
{1881}{}{What will you do now?}
{1882}{}{I knew you needed this. I'm glad I could help.}
{1883}{}{I didn't do it for you. There was no other way.}
{1884}{}{Up until now, he didn't have a bounty. Money makes the moves.}

# Node057
{1910}{}{Heh... Guess what I been doin' to be honest. Keep huntin' more bastards with ya if ya let me. If ever we split though, I guess I'll do it solo. Can't imagine anything else.}

# Node058
{1940}{}{Thank you... You's been great to me. I'll always have your back from here on out.}

# Node059
{1970}{}{Guess I'll take my wins where I can. Just know there was no better way than this.}

# Node060
{2000}{}{*sighs* Guess you's right 'bout that. Speakin' o' that. Let's celebrate with our pay.}

# Node061
{2030}{}{What da' hell are ya doin?! Ya really believe this bastard?! That he's gonna be singin' kumbaya with the folks he thinks are walkin' demons? Fuck. Is. Wrong. With you?!}
{2031}{}{What would you rather have me do? Create a Martyr for this cult?}
{2032}{}{From what I've seen, The Living Prophet benefits everyone in the long run being the voice to de-escalate the tensions. Right now, they've only destroyed property.}
{2033}{}{I'm not gonna murder someone when they clearly want happiness for their people. You should know better how this cycle repeats.}
{2034}{}{My bounty, my rules. You can take a hike if you don't like it.}

# Node062
{2060}{}{I defin'tly don't think havin' crazed lunatics livin' in Jericho after weeks of sayin' they was gonna *burn it down,* is any better... Fuck, but you's right 'bout the Martyr thing. *grunts* I don't know! I just want this Jeremiah bastard gone!}
{2061}{}{You know your family and others would only find a crazier person to get brainwashed by. At least in Jericho, they will be confronted by different views.}
{2062}{}{Jeremiah isn't malicious by intent. He is someone that is more confused than he is competent.}
{2063}{}{Trust me. Just this once, I need you to put aside your wrath. Look at the situation. Your family could be jeopardized if this goes south.}
{2064}{}{When have I let you down before? C'mon we got this! Jeremiah will lose everything once your people see the best that Jericho has to offer!}
{2065}{}{Maybe you're right. We should plug him.}
{2066}{}{This is not your call.}

# Node063
{2090}{}{Pfft, and ya think that ends there? When I was sixteen and bolted, that was when he started. Visions o' bullshit. When I returned at 20? Whole town became one fucked up hive mind. All it takes is allowance for this prick to speak.}

# Node064
{2120}{}{I'm the wrong woman to preach pacifism to, honey. Cycles repeat whether we kill em' or not. Don't tell me ya buy that bible nonsense!}

# Node065
{2150}{}{Ya tumbleweed eatin' son of a... A'ight. Fine. Just know whenever this cult starts doin' things O'Conner don't like... I'll be there, collectin' the bounty. Don't. Get. In my way.}

# Node066
{2180}{}{Damn it. You's right. Much as I can't stand my folks, they'd be better off in Jericho. A'right, go on and speak with O'Conner. I'll back you on this.}

# Node067
{2210}{}{Yes, because you know him better than me, the gal who's grown up with his rhetoric, right? You ain't winnin' me over with this. I'm a walk. Enjoy yaself when you lose all chips realizing' what you signed up for with the likes of him.}

# Node068
{2240}{}{... And as much as I can't stand em, I don't want em dead. Fuck. Okay, but don't you dare screw this up. I got my eyes glued on this.}

# Node069
{2270}{}{I ain't doublin' down with you on lettin' that prick live. You either plug him now, or I wait till O'Conner wises up and sends me solo to do it.}

# Node070
{2300}{}{Thank ya kindly for seein' common sense. Now whenever you're ready, I got ya.}

# Node071
{2330}{}{Hmph... Guess it ain't, but this is: Fuck you. I'm gone. Have fun ridin' solo. And don't come cryin' to me when it goes tits up.}

# Node072
{2360}{}{Alexandra: So that's it then... Jericho is saved, and Jeremiah actually puts down his guns? I don't know if I can believe it. I guess we'll see. Thank you nonetheless.}
{2361}{}{Everyone needed this. A chance to bury the hatchet.}
{2362}{}{To be honest, I just didn't want to waste a bullet.}
{2363}{}{That also means more opportunities for bounties. More People, More Problems.}

# Node073
{2390}{}{I should have known ya to be as coo coo, thinkin' this would work. No matter. I'll head my merry way and watch from afar how this fucks up. When it does, I'll swoop in and collect Jeremiah's head for that bounty. Enjoy this lil' game, cause I want nothin' to do with it.}
{2391}{}{As you wish.}

# Node074
{2420}{}{Besides walkin' it with ya? *chuckles* W'all if I'm ever off the clock so to speak, I guess I'd visit my fam'ly. It's been ages, and I can only imagine the gray hairs they got now. Huh... Never thought I'd say that outloud. Honestly... This feels like a dream.}

# Node075
{2450}{}{Maybe you's right. I thought long n' hard 'bout this. My Fam'ly always meant well despite the crazy beliefs. More good natured people like em' stitching up folks from Jericho oughta' do the community justice. Just hope Jeremiah understands how lucky he is...}

# Node076
{2480}{}{*belts out laughing* All that for a bullet, huh? And I thought my priorities were backwards.Heh. Thank ya for that. I needed a laugh.}

# Node077
{2510}{}{Now that, I like! Might not fancy Jeremiah still breathin' but no doubt whatever roughs up between his cult and the town, only grants us deeper pockets.}

# Node078
{2540}{}{Let's get a move on, pardner. We got more heads to collect.}

# Node079
{2570}{}{Now what ya doin? Ya know damn well that ain't the case. What's the play?}
{2571}{}{You heard Jeremiah's words. He's bound to weaponize the bulk of his people whether today or tomorrow. I'm just preventing an inevitable.}
{2572}{}{Think about how it's been escalating. Jeremiah and his cult have probably armed everyone from child to man, a firearm ready to shoot.}
{2573}{}{Think about the pay. They do our work for us, and we get the bounty! Work smarter, Not harder is what I say.}
{2574}{}{In the aftermath, we can loot the guns Jeremiah stashed on his planned raids. Even if it's scraps, at least we don't waste bullets.}
{2575}{}{Honestly, I just wanted to see what would happen.}

# Node080
{2600}{}{... Yea. Guess I knew that was gonna be the answer. I just wish it wasn't.}

# Node081
{2630}{}{You... Don't... Fool... Me. Those are my folks. I know Jeremiah more than you know how to lace up a lie. You's better hope the children ain't caught up in this mess.}

# Node082
{2660}{}{You ought to know I'm not that kind o' gal. If I wanted money for tellin' folks to do dirty work without em' knowin', I'd be a politician. Not a bounty hunter.}

# Node083
{2690}{}{Spoken like a vulture. *spits at the ground* Just know that ain't my style. Better hope it didn't end with O'Conner catchin' onto you.}

# Node084
{2720}{}{... I wish so badly right now, that I can wrap my hands around ya little throat. I need you out o' my sights. For good. Stay da fuck... Away.}

# Node085
{2750}{}{So that's it then... We didn't have to waste a single bullet, and yet... They're all gone. *sigh* I told my pa once that believ'n that dumb shit was gonna get em' killed... Guess I shouldn't be surprised. I don't know if what we did was right, but Jeremiah is no more and neither is that cult. I might needa drink heavy tonight first chance we get.}
{2751}{}{I'm sorry. I couldn't find a better way.}
{2752}{}{Better this way than the suffering Jeremiah would have made.}
{2753}{}{Think about the cost to profit ratio. We earned more than we lost.}

# Node086
{2780}{}{You vile fuckin' bastard! You made O'Conner rob me o' my dream to kill Jeremiah, and on top o' that - people had to get crossed up?! Ohhh... If I eva' find a bounty with ya name on it... Matter o' fact. Consider our pardnership over. Next time you see me? Get ready.}

# Node087
{2810}{}{I don't know if I believe ya... *sigh* Yet I can't figure out what coulda been better. Just.. Let me drink it out. One night o' boozin' will set me straight.}

# Node088
{2840}{}{I agree yet I can't say I saw what you saw. Part o' me thinks we jumped the gun and became nothin' but two bit raiders here. I'll get over it. Eventually.}

# Node089
{2870}{}{Don't. Talk. About. Profit. I understand where we are about it, but... Not...Now.}

# Node090
{2900}{}{Lets just keep on movin' pardner... The sooner we get out o' here, the better I'll be.}

# Node091
{2930}{}{Sorry, O'Conner. My pardner must've drank a lil' too much. [She glares menacingly at you.] Ain't that right... Pardner...!}

# Node092
{2960}{}{Pardner.}
{2961}{}{What do you know about this area?}
{2962}{}{Where's my bounty money for helping you capture Blackjack?}
{2963}{}{See you around.}
{2964}{}{Thanks.}
{2965}{}{What this place?}
{2966}{}{Tank.}

# Node093
{2990}{alex0930}{Nothin', I'm 'fraid.}
# Mesa Verde 1
{2991}{alex0931}{Hid'n 'way in th' shadders of a big ol' cliff, up near th' top of a mesa risin' outta th' desert floor, y'got Mesa Verde. That's whar the Ciphers live, folk call 'em the Painted People on account'a all that body paint they use. They ain't the biggest tribe 'round here, but their village up there on the mesa makes it real hard fer anyone t'get to 'em, even when they're outnumbered.}
# Hoover Dam
{2992}{alex0932}{Ahh, good ol' Hoover Dam! Place o' commerce, wealth, n' greed! The place has been through hell in a handbasket. Its current state? Complete isolation from its former government back west, the NCR. Place used to trade out rebars, stone, n' steel beams... Til' Dodge put an end to that. Now it's just dyin' out quick. 'Course caravans still fatten their pockets no matter what happens.}
# Fort Abandon
{2993}{alex0933}{It's some converted warehouse surrounded by telephone poles, cars, n' all kinds o' junk. Was s'posed to be for them New California soldiers east of the Grand Canyon... But then it got sacked by tribals. All that's left now are the rats and beasts from what I'm told. Oh n' some nonsense legend o' A Hanged Man. Tale goes that this bastard refuses to die, so the few that wander inside? See the Hanged Man... Well, hanging. Alive. *chuckles* Silly tales like that is why nothin' gets better.}
# Jericho (After NC sacking)
{2994}{}{A place honest o' what it is and what it always will be. Whores n' Guns. Jericho's main export is water due to the plant, and because o' that, it carries itself well under Sheriff O'Conner. It's overall a pretty swell place for bounty n' trade. The people there weren't involved in the shit that plundered what *was* fully New Canaan, so there's that.}
# New Canaan (Before NC sacking)
{2995}{}{A sorry ass place full o' zealots that can't adapt. I rather not talk too much about it, especially if the topic involves Jeremiah. All you need to know is that the fanatics call themselves Mormons, n' they believe nothin' but bullshit that has gotten them killed over n' over. I grew up with its many aftermaths. *sigh* Do not think about goin' there 'less you want me to get ornery.}
# Dogtown
{2996}{}{Dogtown is pretty famous - err, should I say... Infamous? The dogs run wild there. Was supposedly a pretty big industry back in its heyday. Y'know, before the bombs. Couple years ago, a big ol' effort was made by some prisoners to clear their sentences. They was gonna raid buildin's for scrap n' all kinds o' stuff. Yea, that was until The Legion, glowin' ghouls, n' all kinds o' trouble moved in. Now it's just a big graveyard! With dogs.}
# The Reservation
{2997}{}{Place full o' ghouls, with an itchy trigger finger at times towards us uhh, "smoothskins?" If you're curious, I should warn ya from what I heard. Place is rad-city. You'll needs a rad suit n' rad-x to even walk your ass to the place. 'Course they do got fellas that sell those so you can trade with em' so that's somethin' I guess. Just keep your wits 'bout ya.}
# Blackfoot
{2998}{}{Tribal raiders up in the hills. Hangdogs from Dogtown live there now too, don't they? Don't know if that's the reason for them kidnappin' women n' kids. They're basically unsanctioned slavers, which in my field is just more ways to make money by huntin' em! 'Course if you ever decide for some reason to go there, I'd get ready for a shootout. They ain't neighborly.}

# Node094
{2320}{}{[She knowingly smiles and hands you a bag of bottlecaps.]}

# PARTY MEMBER RESPONSES

# Random responses for being pushed by player:
{5000}{}{I ain't a tumbleweed! Careful!}
{5001}{}{Y'like pushin' me around?}
{5002}{}{Can I get a 'cuse me?}

# Response if player has 1 Charisma and asks the companion to join the party
{5029}{alexjoi2}{Nah, I'm good. You can kick rocks elsewhere.}
{5030}{alexcha1}{Pft, yea no. Sorry. Ain't much for friendin' mole rats.}

# The companion does not join the player's party because of too many companions
{5031}{alexfull}{Now I'd join ya, but you got a lil' caravan that'd dead my pay.}

# The player is hated by the companion's home town or he is a childkiller
{5032}{}{You vile fuckin' bastard! Consider our pardnership over.}

# Talking again (bad rep)
{5033}{}{Oh I heard o' you... Best hope I don't got a bounty to claim. Whaddya want?}

# Joining (bad rep)
{5034}{alexbadr}{Seeing as you ain't exactly the most popular 'round here... I'm takin' a big chance. Don't disappoint.}

# Random reply when the companion is in your party and you talk to them
{5060}{alexrpl1}{S'pose you didn't just come to chat about the weather.}
{5061}{alexrpl2}{What's the hap?}
{5062}{}{Somethin' ya need?}
{5063}{alexrpl4}{Oh boy, whaddya need?}

# Reply is when companion is healed to max
{5090}{}{Guess who's the good doc, now eh?}
{5091}{}{Just what the doctor ordered. No, that doesn't mean you can say "Doc."}
{5092}{}{What a life saver!}
{5093}{}{Let's get down to business.}
# Reply message is for when the companion is Barely Hurt
{5094}{}{J'st a flesh wound!}
{5095}{}{That all ye got?!}
{5096}{}{Ugh! Fucker!}
# Reply message is for when the companion is Wounded
{5097}{}{Damn it! I'm bleedin' thick!}
{5098}{}{Gettin' gutted out here!}
{5099}{}{Could use a stim!}
# Reply message is for Failure to Heal the companion
{5100}{}{Ugh! Do I gotta tell ya how to stim?!}
{5101}{}{Don't make me have to heal myself!}
{5102}{}{Plug it in the vein!}

# Random replies in response to wait request
{5120}{alexwai1}{A'ght, but don't expect me to be still as a cactus. Come back soon.}
{5121}{alexwai2}{Guess I can rest my boots for a bit.}
{5122}{alexwai3}{Don't let me drink all the hooch while yer' gone.}
{5123}{alexwai4}{I'll be readin' some comics I guess while yer gone.}

# Response to removing weapon
{5150}{alexrmw1}{Yea, yea I get the procedure.}
{5151}{alexrmw2}{Long as any target ain't here, I'll oblige.}
{5152}{alexrmw3}{Roger.}

# Random responses for distance change
{5180}{alexdst1}{Keepin' me close will do ya well. Just don't slow me down if we're runnin'.}
{5181}{alexdst2}{Long distance is a'ght I suppose.}
{5182}{alexdst3}{Whatever you do, don't get in my line o' fire.}

# Response to "Change follow distance" menu
{5210}{alexdst4}{Guess I can do that.}
{5211}{alexdst5}{A'righty.}
{5212}{alexdst6}{Change o' pace. Literally.}

# Response to "Look at your gear"
{5240}{alexequ1}{'Long as you keep me with a pistol, I'm good.}
{5241}{alexequ2}{Don't swipe it now, ye hear?}
{5242}{alexequ3}{Heard that before.}

# Response to "Remove armor"
{5270}{alexrma1}{Don't get any bright ideas.}
{5271}{alexrma2}{Love me an upgrade.}
{5272}{alexrma3}{Whatever ya give me, it better not leave me stiff.}

# Reply indicating which weapons the companion can use
{5300}{alexwpn1}{If it ain't a pistol, it ain't gonna work.}
{5301}{alexwpn2}{Uhuh, yea I'ma suggest a "no" if it ain't chambered.}
{5302}{alexwpn3}{Really gonna test if we're friends o' not huh?}

# The player is asking the companion to re-join
{5330}{alexjoi1}{Really now? Guess I shoulda figured you to be the confused type. A'ght but no more bullshit. Either I'm in o' not. Stand with ya peace now.}
{5331}{alexjoi3}{Guess we're back at it. Let's get goin.}

# Companion abandons party because of shitty rep
{5360}{alexabn1}{I'm tired o' your shit. Drop dead, ya bitch.}
{5361}{alexabn2}{Yea, I'm out. Best ye enjoy yerself since that's all you got.}
{5362}{alexabn3}{Now why did ya have to go 'round and ruin a good thing for us?! Ugh! Yer on ya own.}
{5363}{alexabn4}{You really screwed the pooch, huh? W'all I ain't sticking 'round.}
{5364}{alexabn5}{Shit. Better hope I ain't returnin' with a bounty on yer head. See ya later, motherfucker.}
{5365}{alexabn6}{I'm tired o' your shit. Drop dead, ya bastard.}
