# Message file for mvazkee.ssl
# Number of nodes: 32

{100}{}{You see a middle-aged Cipher with a shaved head.}
{101}{}{You see Azkee, the Counter and the leader of the Ciphers.}
{102}{}{He wears an old pocket calculator around his neck as some sort of a symbol.}

{150}{}{You arranged to have food shipments sent from Hoover Dam. It should keep the Ciphers fed until they can replant their crops.}
{151}{}{You discovered what Denom did to the crops.}
{152}{}{You helped the Ciphers restore the crop fields with the Miracle Wheat.}

# Node001
{200}{}{Speak, outsider.}
{201}{}{What do you do here?}
{202}{}{Anything going on that I could help with?}
{203}{}{What you do here?}
{204}{}{Me help with something?}

# Node002
{230}{}{Hello again, my friend. What may I do for you?}
{231}{}{Didn't you mention something about Hounds harassing Mesa Verde?}
{232}{}{You say dog people bugging village?}
{233}{}{I've removed the dog people threat.}
{234}{}{Bad dog people all gone.}
{235}{}{What was that you said about the crops?}
{236}{}{You say you not like crops?}
{237}{}{The new fertilizer Denom used on the crops was radioactive, which is why the crops are so big. It's probably not a good idea to eat anything grown from those fields.}
{238}{}{Fertilizer make crops all glowy and mutated. Not good to eat.}
{239}{}{Is there anything that can help Mesa Verde's food supply?}
{240}{}{What you do about food?}
{241}{}{I arranged for a Hoover Dam caravan to bring you food.}
{242}{}{Men with moo-cows bring you food now.}
{243}{}{Tell me again about what happened to your people.}
{244}{}{Where your people go, again?}
{245}{}{I was able to rescue all of your people.}
{246}{}{Me save all you people. Nobody die.}
{247}{}{I managed to rescue your people, but not all of them survived the escape.}
{248}{}{Me save people, but not all still alive.}
{249}{}{I found your people, but none of them survived the escape.}
{250}{}{Me find people, but they all die.}
{251}{}{The fertilizer used on the crops was radioactive, which is why the crops are so big. It's probably not a good idea to eat anything grown from those fields.}
{252}{}{I have this bag of "miracle wheat" seeds. They would be able to cleanse the irradiated soil. What could you give me in exchange for them?}
{253}{}{Me have miracle seed. They make glowy dirt clean. You pay, me give.}

# Node003
{260}{}{I'm Azkee, Counter for this village.}
{261}{}{What do you count?}

# Node004
{290}{}{*sigh* I'm Azkee, Counter for this village. Please, don't touch anything.}
{291}{}{What you counting?}

# Node005
{320}{}{The Ciphers you see around you are not all the Ciphers there are. Most are nomads, travelers in the wasteland. It is the Counter's duty to decide who may stay in Mesa Verde, and who must leave.}
{321}{}{What kind of variables?}
{322}{}{Uh, okay. What that mean?}

# Node006
{350}{}{Population, for one. Mesa Verde can only support a small number of my people and it is my duty as the Counter to enforce population control.}
{351}{}{I see. So, is there anything you could use some help with?}

# Node007
{380}{}{It means I decide who gets to live here, and who must leave.}
{381}{}{Oh. Me help you with something?}

# Node008
{410}{}{Yes. The Hounds of Hecate in the canyon disturb my village, but we are at an impasse - neither side can defeat the other. Perhaps the help of an outsider like yourself can tip the balance in our favor.}
{411}{}{I'll solve your Hound problem for you. Somehow.}
{412}{}{Me go move dog peoples for you.}
{413}{}{Those guys? I already took care of them.}
{414}{}{Me already take care of dog peoples.}
{415}{}{What's in it for me if I help you?}
{416}{}{You gimme stuff for me help?}

# Node009
{440}{}{We have a small surplus of bullets and chems which are yours if you do what I ask.}
{441}{}{All right. I'll go take care of the Hounds.}
{442}{}{Me go move dog peoples now.}
{443}{}{Well, hand them over. I already took care of the Hounds.}
{444}{}{Gimme! Me already take care of dog peoples.}

# Node010
{470}{}{I wish you luck, outsider.}
{471}{}{[END]}

# Node011
{500}{}{Thank you, outsider. You didn't ask for a reward, but I must offer you some compensation for your efforts. Here, some items we had set aside for trade.}
{501}{}{Is there anything else you need help with?}
{502}{}{Me help you more?}

# Node012
{530}{}{Thank you, outsider. Here are the bullets and chems I promised.}

# Node013
{560}{}{It's been brought to my attention that the crops are unusually large this season. I'd like you to investigate this matter for me.}
{561}{}{All right. Who do I need to talk to?}
{562}{}{Okay. Who me talk to?}
{563}{}{What's the pay?}
{564}{}{Me want money.}

# Node014
{590}{}{If you can find out what has happened to the crops, I'll give you this revolver. It's old, but functional.}
{591}{}{Deal. Who do I need to talk to?}
{592}{}{No, sorry. Goodbye.}
{593}{}{Nope. Bye.}

# Node015
{620}{}{See Denom at the top of the mesa. He's the one in charge of the fields and the wind turbine.}

# Node016
{650}{}{This is very bad. Without the crops, we must rely entirely on hunting, and hunting alone cannot support the village at its current size. I will be forced to banish people into the wasteland. Oh, and here is the revolver I promised.}
{651}{}{What if you had more food brought to you?}
{652}{}{You get food from other place, maybe?}

# Node017
{680}{}{A caravan from Hoover Dam would be the best source for food, but I'm afraid the cost for the shipments would be very high. We can't afford it.}
{681}{}{I'll cover the cost.}
{682}{}{Me pay for everything.}

# Node018
{710}{}{You're being generous. I'm surprised, considering that you insisted on payment for my other tasks. Still, I gladly accept your offer.}
{711}{}{It's a loan, not a gift. I expect you to pay me back one of these days - with interest.}
{712}{}{It loan. Me want money back someday.}

# Node019
{740}{}{I welcome your generosity, }
{741}{}{. If you do this for us, you shall always find a place here at Mesa Verde.}

# Node020
{770}{}{Oh. Still, it is the best we can do right now, and I still accept your offer.}

# Node021
{800}{}{Thank you, }
{801}{}{! Your generosity has allowed many Ciphers too old or too young to travel to remain within the village.}
{802}{}{Glad I can help. Anything else around here need doing?}
{803}{}{Me happy to help. Me help more?}
{804}{}{Right. Arranging for the shipments cost me a lot of caps. Any idea on when you can start paying me back?}
{805}{}{Um, me pay lots of money. When you pay me?}

# Node022
{830}{}{Hmmm... perhaps in a year or two, at the earliest.}
{831}{}{I see. Any other jobs?}
{832}{}{Gah. More jobs?}

# Node023
{860}{}{Not right now. Perhaps you can be of assistance to some of my people.}

# Node024
{890}{}{! It is good that you have come. A number of my people have been taken.}
{891}{}{Taken? Who took them, and where?}
{892}{}{Who take people? Where they go?}
{893}{}{What does that have to do with me?}
{894}{}{That bad for you, not me.}

# Node025
{920}{}{Slavers came to Mesa Verde posing as the caravan from Hoover Dam, and a number of my people went to greet them and were captured. We need your help finding them.}
{921}{}{Me help.}
{922}{}{This has nothing to do with me.}
{923}{}{Too bad. Not problem for me.}

# Node026
{950}{}{We are not your people, but I know you must be familiar with many places in the wasteland. We desperately need your help.}
{951}{}{Oh, all right. I'll help you.}
{952}{}{Okay, me help.}
{953}{}{You still owe me for the food caravans. Until then, I'm not lifting a finger to help you.}
{954}{}{Me not get paid yet for food. Me not help you.}

# Node027
{980}{}{Thank you. The slavers were spotted heading to the northeast of Mesa Verde. Good luck, and may the numbers come up in your favor }
{981}{}{.}

# Node028
{1010}{}{Then, I'm afraid we must continue the hunt alone. Goodbye.}

# Node029
{1040}{}{! Your skill and cunning undoubtedly was responsible for saving all of our people.}

# Node030
{1070}{}{It is regrettable that a few of those taken will never see Mesa Verde again, but fortunately, your efforts have brought most of our people home. Thank you, }

# Node031
{1100}{}{We mourn those who were lost, but at least you managed to bring some of our people home. Thank you, }

# Node032
{1130}{}{This is a grim day for Mesa Verde. Your efforts are appreciated, }
{1131}{}{. I must leave you now to mourn for my lost people.}

# Node033
{1160}{}{Don't disturb the harmony of my village, outsider, or I'll have you removed.}
{1161}{}{Nice to meet you, too. Who are you?}
{1162}{}{Guh?}
{1163}{}{Goodbye.}

# Node034
{1190}{}{There's not much that we can offer at this point except our knowledge. Hmmm... You travel a lot. We could teach you how to skin a gecko. That way you can earn extra caps.}
{1191}{}{Deal!}
{1192}{}{Not good enough. Goodbye.}
{1193}{}{'K!}
{1194}{}{Nope.}

# Node035
{1220}{}{Thank you, outsider. Observe carefully now.}
{1221}{}{[Learn the art of gecko skinning]}

# Node036
{1250}{}{What?! How dare you be so vulgar in front of the Counter? Go away.}
{1251}{}{[Start fiddling with your pockets] No, no. Me show you my seed.}
{1252}{}{[Leave]}

# Node037
{1280}{}{Help! Pervert!}
{1281}{}{[Display a bag containing "miracle wheat" seeds.] Seed!}

# Node038
{1310}{}{Oh.. *that* kind of seed! Apologies, it's just that you... nevermind.}
{1311}{}{Wut?}
