# Message file for mvblkjck.ssl
# Number of nodes: 13

{100}{}{You see a mighty super mutant nightkin.}
{101}{}{You see Blackjack.}
{102}{}{He is sitting behind a makeshift barricade, clutching a fake minigun made out of wooden sticks.}
{103}{}{He looks sad.}

{150}{}{Alexandra! You demon!}
{151}{}{You spend some time playing blackjack with Blackjack.}
{152}{}{You tricked me, demon.}

# Node001
{200}{}{[A big, dark shape moves among the shadows of the canyon cave. The silence is suddenly interrupted by a booming voice echoing through the air.] I'm Blackjack! And, uh, you should be careful. This MINIGUN can blow you to bits! So, you know, keep your distance.}
{201}{}{Hah! That's a rather creative weapon you have there.}
{202}{}{Why are you holed up in this cave?}

# Node002
{230}{}{Alexandra... She's after me. Can't let her catch me. So, here I am, with my big, powerful weapon, waiting it out.}
{231}{}{Why is she after you?}

# Node003
{260}{}{It's a long story. Let's just say... slavers. But she won't dare come in here. Not with me and my minigun.}
{261}{}{I've seen many things in the wasteland, but this... this is something special. I'm not blind. What's it made of? Sticks and pipes?}

# Node004
{290}{}{Hey! Stop looking so closely! It's... It's a... prototype. Yeah! Very dangerous.}
{291}{}{I'm sure. So, what now? Are you planning on staying in this cave forever?}

# Node005
{320}{}{I've got supplies to last me a while. And with my weapon, I feel... sort of safe. But, maybe... if Alexandra leaves... I might come out.}
{321}{}{What if I can help? Maybe convince Alexandra to back off?}
{322}{}{I've been looking for you, actually. ODYSSEUS sent robots to either bring us in dead or alive.}
{323}{}{I need to retrieve the Pip-Boy you're using.}
{324}{}{Prepare to die.}
{325}{}{Listen, this bounty on your head... If Alexandra doesn't claim it, someone else will - someone far more ruthless than her. If you value your life, surrender now.}

# Node006
{350}{}{Would you? I mean, I can't pay you much, but I've got some stuff in this supply pack here. If you can get her to leave, it's yours.}
{351}{}{OK, stay put, Blackjack. And don't shoot anyone with your, uh, "prototype".}

# Node007
{380}{}{Ah, Tibbets! That place wasn't too comfy, even for me. Anyways, I'm not going back.}
{381}{}{Look, Blackjack, Tibbets might not be the best place, but roaming the wasteland with their tech will keep you in constant danger. Don't you want a chance at some peace? A place where you're not always on the run?}
{382}{}{I'll just bring you in dead then.}

# Node008
{410}{}{As for the Pip-Boy... it plays a mean game of blackjack. Why would I part with it?}
{411}{}{Without the Pip-Boy, they'll stop pursuing us. You'll have to give it to me, one way or the other.}

# Node009
{440}{}{Peace is a funny word in the wasteland. But you make a point. Still, it's not easy being a super mutant. Wherever we go, trouble tends to follow as you can see.}
{441}{}{I get it. But by returning to Tibbets, you will be much safer than outside. Show them that not all super mutants are mindless beasts. And if you stay out here, well, others might not be as understanding as I am. But in that case I'll need your Pip-Boy.}
{442}{}{I've had enough of this fruitless talk. Time to die, mutie.}

# Node010
{470}{}{It's been a long time since someone spoke to me without aiming a gun first. Maybe... maybe it's worth a shot. But the Pip-Boy, it's been useful, a reminder that there's more to life than just brute strength.}
{471}{}{I understand its value to you. It's not often one sees a super mutant so engrossed in a game of cards. It helps you connect to the past and its games bring you joy, but you can't keep it anymore. ODYSSEUS will *never* stop pursuing you as long as you hold on to it. Never.}
{472}{}{That's it! I'll just take it by force.}

# Node011
{500}{}{Ah, well, even us mutants need a bit of fun. You're a strange one, but I like you. Alright, I'll give it to you. But first, how about a game of blackjack? You did mention it's not often you see a super mutant engrossed in cards.}
{501}{}{Deal me in, big guy. Let's play.}

# Node012
{530}{}{Is she gone?}
{531}{}{Yes, she's gone. You are free to leave.}
{532}{}{No, not yet. I'm working on it.}
{533}{}{I don't have time for this nonsense. It's going to be much quicker to just loot your big, dead, blue body.}
{534}{}{She's still there, but you have no chance against her - unlike you, her guns are real.}

# Node013
{560}{}{Hah, thanks you! Here are my supplies. See you at the nearest casino. Hoover Dam, here I come!}
{561}{}{Perhaps. So long.}

# Node014
{590}{}{Tell her I'll never surrender.}
{591}{}{You're worthless to her dead.}
{592}{}{Uh, I will. Goodbye.}

# Node015
{620}{}{Worthless? Dead? You don't say! Alright then, time to stretch my legs again. [He starts running towards the exit.]}
{621}{}{Wait!}

# Node016
{650}{}{You... you're right. It's time to stop running. [He starts walking towards the exit.]}
{651}{}{Smart move, big guy.}
