# Message file for mvcomp.ssl
# Number of nodes: 17

{100}{}{You see an ancient computer.}
{102}{}{It looks like it hasn't been used in a long, long time.}
{103}{}{You replaced its missing parts and now it's running.}

{105}{}{You successfully repaired the Ciphers' old computer.}
{106}{}{You failed to repair the Ciphers' old computer.}
{107}{}{The old computer is missing its memory core and power supply.}
{108}{}{You are not sure what is wrong with this old computer.}
{109}{}{You don't have the necessary computer parts to finish the repair.}

# Node001
{200}{}{System status: OK. Network status: Los Alamos network is OFFLINE.}
{201}{}{[Read the Diary Logs]}
{202}{}{[Access Schematics]}
{203}{}{[Exit]}
{204}{}{[Play video "Discovery '66"]}

# Node002
{230}{}{Log Entry [#01]: "We left Los Alamos weeks after the bombs fell. The scientists, soldiers, and a scattering of survivors-all banded together like lost stragglers from a forgotten war. The wasteland is savage. Each encounter with others ends in violence. The Old World... the world we knew, it's gone. We thought ourselves the last remnants of civilization, clinging to what little technology and order we still possessed."}
{231}{}{[Continue]}

# Node003
{260}{}{"We headed north, toward the ancient pueblos of Mesa Verde. It was a calculated decision - isolated, defensible, and hopefully out of reach of scavengers and raiders. We had pistols, rifles, and one working computer. The soldiers kept watch while the scientists did what they could to preserve what was left of the Old World's knowledge. We brought only essentials: the means to make water, a crude turbine for power, and several sealed containers of weapons-grade uranium. It wasn't much, but it was enough."}

# Node004
{290}{}{"Log Entry [#02]: It's been over a decade now. The computer - our link to what was - has started to fail. Without it, the knowledge we carried from before the bombs will be lost forever. Desperation led to ingenuity. The scientists have begun to carve schematics into the walls of the kiva, preserving electronic designs in the only way we could--stone. We've turned this ancient place into a vault of knowledge, a tomb of circuitry and calculations."}

# Node005
{320}{}{"Mathematics became our religion, the key to keeping the past alive. The children - our future - are taught math from birth. It's their language now, the language of survival. Outsiders don't understand, call us 'Ciphers,' think we speak in code. Maybe they're right. Maybe we've coded the future into numbers that only we can see. Doesn't matter. The name stuck. We are the Ciphers."}
{321}{}{[Return to Main Menu]}
{322}{}{[Download the logs to your Pip-Boy]}

# Node006
{350}{}{[An alphabetical list appears on the screen]}
{351}{}{APOLLO}
{352}{}{ARES}
{353}{}{ARTEMIS}
{354}{}{ATHENA}
{355}{}{Gauss Firearms}
{356}{}{HERAKLES}
{357}{}{HERMES}
{358}{}{Solar Scorcher}

# Node007
{381}{}{[Download the schematic to your Pip-Boy]}
{382}{}{[Back]}

# Node015
{620}{}{[The ancient computer has no power]}
{621}{}{[Leave]}

# Node016
{650}{}{[Transferring the Schematic for }
{651}{}{: COMPLETE!]}

# Node017
{680}{}{[Transferring the Diary Logs: COMPLETE!]}
