# Message file for mvdenom.ssl
# Number of nodes: 20
# Grammar pass done

{100}{}{You see the man responsible for maintaining the wind turbine, water makers, and greenhouses.}
{101}{}{You see Denom, the mechanic and gardener.}
{102}{}{He seems quite pleased with himself for some reason.}

{150}{}{You helped the Ciphers destroy the weedling infestation.}
{151}{}{You helped the Ciphers restore the crop fields with the Miracle Wheat.}

# Node001
{200}{}{Help us! They're everywhere!}
{201}{}{Slow down. What are you talking about?}
{202}{}{Me not understand. What you talking about?}

# Node002
{230}{}{Thanks for your help! I'm Denom.}
{231}{}{What *were* those creatures?}
{232}{}{What those creatures?}
{233}{}{Me help painted people kill moving plants. Me go now.}

# Node003
{260}{}{That was messy. By the way, I'm Denom.}

# Node004
{290}{}{Hello. Is there something I can do for you?}
{291}{}{Azkee is concerned about the crops. He says they're a bit larger than normal.}
{292}{}{Bald leader guy worry about crops. Say they too big.}
{293}{}{That fertilizer you used on the crops is radioactive.}
{294}{}{Dirt is all glowy and stuff. Very bad.}
{295}{}{I brought back a bag of seeds from that wheat I told you about.}
{296}{}{Me bring seeds.}
{297}{}{Goodbye.}
{298}{}{Buh-bye.}

# Node005
{320}{}{I have no idea. We've never seen them before. They just seemed to spring out of the ground.}
{321}{}{What's your job here?}
{322}{}{What job you do?}

# Node006
{350}{}{Plant creatures, in the fields! We need help killing them!}
{351}{}{All right, I'm on it.}
{352}{}{Okay, me go kill them.}
{353}{}{Not my problem. Goodbye.}
{354}{}{Nope. Goodbye.}

# Node007
{380}{}{I'm in charge of overseeing the crops, as well as keeping the turbine and condensers running.}
{381}{}{Tell me about the turbine.}
{382}{}{Me wanna know about turbine.}
{383}{}{How do the condensers work?}
{384}{}{Wanna know about condensers.}

# Node008
{410}{}{We get a lot of wind up here, so the founders of the village built the wind turbine to generate electricity. It isn't much, but it's enough to power the condensers.}
{411}{}{What do the condensers do?}
{412}{}{What condensers do?}

# Node009
{440}{}{The condensers somehow trap moisture from the wind and collect water for us. It's very slow - a little more than day's worth of water for the whole village each day. They're powered by the turbine.}
{441}{}{Who built them?}
{442}{}{Who build?}

# Node010
{470}{}{I can't believe he's complaining about the crops *again*. Just a few weeks ago, he was upset because the crops were too scrawny.}
{471}{}{The crops were too scrawny? What did you do to improve them?}
{472}{}{How you make crops big?}

# Node011
{500}{}{I used some special fertilizer I got off a merchant who passed through here. He claimed it could make anything grow, and he was right. It's great stuff!}
{501}{}{I'd like to examine this fertilizer.}
{502}{}{Me want to look at fertilizer.}

# Node012
{530}{}{I used it all up, but the barrel it came in is in the storage shed over there. Why? What's wrong?}
{531}{}{I don't know yet. Goodbye.}
{532}{}{Me not know yet. Goodbye.}

# Node013
{560}{}{What? No, it's not. There must be a mistake.}
{561}{}{There's no mistake. I examined the fertilizer barrel with a Geiger counter, and it's moderately radioactive.}

# Node014
{590}{}{"Glowy"? What are you talking about?}
{591}{}{Glowy! Point thingie at barrel, it go "beep beep beep!"}

# Node015
{620}{}{Oh, no! I've poisoned our fields, and our crops! What am I going to do? We're all going to starve!}
{621}{}{I don't know right now. I'll speak to Azkee about it.}
{622}{}{A group at Hoover Dam developed a type of wheat that cleans radiation from the ground. I could get some for you.}

# Node016
{650}{}{Oh, no! It's radioactive? I've poisoned our fields, and our crops! What am I going to do? We're all going to starve!}
{651}{}{Dunno. Me talk to bald leader guy.}
{652}{}{Big dam people make plant that clean glowy stuff from dirt. Me get some for you.}

# Node017
{680}{}{He's going to have me banished for this, I know it.}

# Node018
{710}{}{Really? That's incredible! Yes, please get some for me!}

# Node019
{740}{}{Thank you! I'll start planting these right away.}
{741}{}{Whoa, not so fast, farmboy. Those seeds aren't free.}
{742}{}{Nope, you gimme money first. Seeds not free.}
{743}{}{Here you go.}
{744}{}{Here, take super duper seeds.}

# Node020
{770}{}{Oh... uh, of course not. You'll have to talk to Azkee about that.}

# Node021
{800}{}{Uh, our ancestors did. We now maintain them according to the kiva drawings.}
{801}{}{[END]}
