# Message file for mvdrake.ssl
# Number of nodes: 20

{100}{}{You see a tall, muscular, heavily-tattooed guy.}
{101}{}{You see Drake, Chosen of Hecate.}
{102}{}{He doesn't seem particularly evil but seems capable of performing cruel deeds.}

{150}{}{You've informed the Hounds of Hecate about the wind turbine's sabotage. You've sealed the fate of the Ciphers.}
{151}{}{You attacked the Hounds camp head on and were victorious.}
{152}{}{You posed as a Daughter of Hecate and tricked the Hounds into leaving Mesa Verde.}
{153}{}{You posed as a Chosen of Hecate and tricked the Hounds into leaving Mesa Verde.}
{154}{}{Killed all the dog men.}

# Node001
{200}{}{This path is forbidden to travel by order of Hecate, stranger. You may not pass.}
{201}{}{Who are you?}
{202}{}{Who you?}
{203}{}{Sure I can! Watch - I'll just kill you and then push your corpse out of my way.}
{204}{}{Yaaaaaaaaargh! [Attack him.]}
{205}{}{Goodbye.}
{206}{}{Bye.}

# Node002
{230}{}{We meet again. Why have you come before us?}
{231}{}{Who are you, again?}
{232}{}{Me forget. Who you?}
{233}{}{I am}
{234}{}{a Daughter of Hecate, assigned to oversee the Ciphers tribe. The Dark Mother commands your immediate return to Ouroboros - or face her wrath.}
{235}{}{a Chosen of Hecate. The Dark Mother demands your swift return to Ouroboros - lest you incur her wrath.}

# Node003
{260}{}{Were you successful in disabling the Ciphers' wind turbine?}
{261}{}{Not yet. I'm still working on it.}
{262}{}{Nope. Not done yet.}
{263}{}{Yes, I sabotaged the turbine.}
{264}{}{Yup, me broke wind thingie.}
{265}{}{Tell me again about how I can help you.}
{266}{}{How me help you, again?}

# Node004
{290}{}{I am Drake, Chosen of Hecate and leader of these Hounds of Hecate.}
{291}{}{Why are you blocking this trail?}
{292}{}{Why you in me way?}
{293}{}{Who's Hecate?}
{294}{}{Who Hecate?}
{295}{}{Your gang's name is the Hounds of Hecate?}
{296}{}{Dogs? Me not see dogs.}

# Node005
{320}{}{The Dark Mother is our goddess, the one who gives us purpose and power. She commands almost all the tribals of the wasteland through her magic.}
{321}{}{I see. So, where does Hecate live?}
{322}{}{Where she live?}
{323}{}{"Magic?!" Are you serious?}
{324}{}{"Magik," asshole from jail? You joke?!}

# Node006
{349}{}{Ouroborus, to the northwest. Go there and you will find our holy city if you are worthy.}
{350}{}{Ouroborus, to the northwest. You have a device which holds maps? I shall mark the location down for you. [He enters the coordinates in your Pip-Boy.]}
{351}{}{You said your gang's name is the Hounds of Hecate?}
{352}{}{You say you lead dogs. Me not see dogs.}

# Node007
{380}{}{A foolish group of tribals called the Ciphers has chosen to defy Hecate. She has ordered their destruction as punishment.}
{381}{}{How did they defy her?}
{382}{}{Why she make them dead?}
{383}{}{There doesn't appear to be much destroying going on.}
{384}{}{You here, not bashing and killing. Not understand.}

# Node008
{410}{}{All tribals must have a Daughter of Hecate among them to promote fertility and carry out the will of Hecate. The Ciphers refused, and now they shall pay dearly for their heresy.}
{411}{}{So why are you here instead of killing the Ciphers?}
{412}{}{Me not see you killing. How come?}

# Node009
{440}{}{Mesa Verde is strong. There's only a handful of healthy Cipher warriors in the village, but they're in an extremely defensible position. We have been unable to break through, so now we wait to starve them out. We cannot go back to Hecate until we have carried out her will.}
{441}{}{Maybe I can help you with your attack.}
{442}{}{Me help you kill.}
{443}{}{I see. Goodbye, Mr. Drake.}
{444}{}{'K. Bye, dog man.}

# Node010
{470}{}{We are no "gang", stranger. Once, perhaps, years ago when we were known as the Vipers. Now we are Hecate's holy warriors, crushing any who displease her or otherwise stand in her way. Now leave me be, stranger.}
{471}{}{As you wish.}

# Node011
{500}{}{*sigh* Had a Daughter been present at your birth, stranger, you would have been cast out into the wasteland to die. *We* are the Hounds of Hecate. It is the name of our band of holy warriors.}
{501}{}{Uh-huh.}

# Node012
{530}{}{You are not one of us, and cannot be allowed the honor of fighting beside us. Nor *can* you become one of us - one is born a Hound of Hecate, not made.}
{531}{}{Well, is there anything *else* I can do?}
{532}{}{How me help you, then?}

# Node013
{560}{}{You are unknown to the Ciphers. Perhaps you can gain access to the village and destroy their wind turbine for us. Without the turbine, they will have no proper source of water. They will then become weak enough for us to overwhelm their defenses.}
{561}{}{I'll do it.}
{562}{}{Me do it.}
{563}{}{If I do it, what's it worth to you?}
{564}{}{You gimme money to do?}
{565}{}{Sorry, not interested. Goodbye.}
{566}{}{Me no do. Bye.}

# Node014
{590}{}{You *dare* ask for money to carry out Hecate's will? We should kill you for such an insult.}
{591}{}{Okay, fine. I'll do it for free.}
{592}{}{Ack. Me do it for free, okay?}
{593}{}{Bring it, punk!}
{594}{}{Me insulted. You die!}

# Node015
{620}{}{Then I wish you success, stranger. Do not harm any of the Ciphers - that honor belongs to us.}
{621}{}{Alright.}
{622}{}{'K.}

# Node016
{650}{}{Excellent. And the Ciphers? Do they still live?}
{651}{}{Uh... yeah, sure they are. Happy and alive, that's them.}
{652}{}{Ummm... yup?}
{653}{}{No. They saw me sabotaging the turbine, and I was forced to kill them.}
{654}{}{Nope. They see me break wind thingie, so me kill them.}
{655}{}{Yes, they're still alive, just as you asked.}
{656}{}{Yup, they not dead.}

# Node017
{680}{}{Good. We shall teach you now how to skin a gecko. Also, I suggest you journey to Ouroborus, stranger. Hecate might want to hear of your deeds in her service. Here - I shall mark its location in your mapping device.}
{681}{}{Thank you, Drake. Goodbye.}
{682}{}{Thank, dog man. Bye.}

# Node018
{710}{}{That was *our* duty, not yours! We must kill you now to avenge our dishonor!}
{711}{}{Bring it!}
{712}{}{Me kill you first!}

# Node019
{740}{}{I hear the lie in your voice and see it in your eyes. Their deaths were *our* duty, not yours! We must kill you now to avenge our dishonor!}

# Node020
{770}{}{Do it immediately. Hecate grows impatient.}

# Node021
{800}{}{Why don't I know you, Chosen?}
{801}{}{Why don't I know you, Daughter? Where are your robes?}
{802}{}{I'm a new servant of Hecate, still earning my place. Now, you have two choices: either I'm a skilled liar, or I'm telling the truth. Are you willing to risk the Dark Mother's wrath in case I'm right and you're wrong?}
{803}{}{I'm a new servant of Hecate, still earning my place. My group was wiped out by a chameleon deathclaw stalking this region. We cannot risk losing your Hounds too. Now, you have two choices: either I'm a skilled liar, or I'm telling the truth. Are you willing to risk the Dark Mother's wrath in case I'm right and you're wrong?}

# Node022
{830}{}{Hmm... You're right. That would be unwise. We shall return to her soon.}
{831}{}{Your wisdom is evident. Safe travels.}

# Node023
{860}{}{I must kill you now to avenge our dishonor!}
{861}{}{Bring it!}
{862}{}{Me kill you first!}

# Node024
{890}{}{Hecate can do things only gods can do! Do not doubt the Dark Mother unless you want her to turn you into a skeleton suit.}

# Node025
{920}{}{Yes, Daughter! It will be as Hecate commands. We shall return to her soon.}
