# Message file for mvisaac.ssl
# Number of nodes: 40

{100}{}{You see a man in his fifties.}
{101}{}{You see Isaac, the former Elder Scribe of the Brotherhood.}
{102}{}{He doesn't have any tattoos on himself.}

{150}{}{You convinced Isaac to help you with the power armor security codes.}
{151}{}{You provided Isaac with new information on the G.E.C.K.}

# Node001
{200}{}{Hello, there! I'm Isaac. We don't get many outsiders up here at Mesa Verde.}
{201}{}{Hello, Isaac. You look like an outsider yourself. What's your story?}
{202}{}{Hi, Isaac! How come you not painted?}
{203}{}{Goodbye.}

# Node002
{230}{}{Still in one piece, I see. Good for you.}
{231}{}{I wasn't able to find a G.E.C.K., but I did find a holodisk with a lot of information about G.E.C.Ks.}
{232}{}{What do you do here?}
{233}{}{What you do here?}
{234}{}{You don't look like a Cipher. Where are you from?}
{235}{}{How come you not painted?}
{236}{}{Maxson Bunker belongs to the Brotherhood of Steel. You're with the Brotherhood?}
{237}{}{Are you Isaac Gant by any chance? I need to get the access codes for the Brotherhood's power armor from you.}
{238}{}{Isa Gant? Power armor in Bunker not work. Need codes from you.}

# Node003
{260}{}{You're right - I'm not originally from Mesa Verde, but this is my home now, even though I haven't gone completely "tribal."}
{261}{}{Where are you from originally?}

# Node004
{290}{}{Not a bright one, huh? Well, no matter. As for my lack of paint, it's because I'm not from Mesa Verde.}
{291}{}{Oh. Where you come from?}

# Node005
{320}{}{Originally, a little town way out west. More recently, Maxson Bunker.}
{321}{}{Maxson Bunker? Where's that?}
{322}{}{Where that?}
{323}{}{Maxson Bunker? You're with the Brotherhood?}
{324}{}{Bunker? Hey, you Brudderhood!}

# Node006
{350}{}{No, not any longer. We had... a difference of opinion, so I decided it was time for me to find my own way.}
{351}{}{I need to get the security codes for the Brotherhood's power armor from you.}
{352}{}{Power armor not work. Need codes from you.}
{353}{}{What made you decide to leave?}
{354}{}{Why you leave?}
{355}{}{I don't suppose you've got any high tech equipment lying around?}

# Node007
{380}{}{The Brotherhood was once dedicated to preserving technology, dealing it out in small doses to those it deemed responsible enough to handle it. That all changed. }
{381}{}{What happened?}
{382}{}{What happen?}

# Node008
{410}{}{I still have my own suit of power armor. At the moment, it's just collecting dust since there's little use for it around here, as you can see. }
{411}{}{I see. So, why did you leave the Brotherhood?}
{412}{}{Since you're not using it, can I have your armor?}

# Node009
{440}{}{No, sorry. I may not be Brotherhood anymore, but that doesn't mean I'm going to start handing out advanced technology all over the wasteland.}
{441}{}{All right. So, why did you leave the Brotherhood?}
{442}{}{Well, would you consider "selling" the armor, then?}
{443}{}{I'll just kill you and take the armor, then.}

# Node010
{470}{}{Not for any price.}
{471}{}{Right. So, why did you leave the Brotherhood?}
{472}{}{Everything has a price, Isaac, and I know there has to be something I can trade to you in exchange for the armor. What do you need? Caps? Information?}
{473}{}{Oh, of course. So... where do you keep the armor? Any alarms or traps I should know about?}

# Node011
{500}{}{Spoken like a true trader of the wastes. All right, if you want the armor *that* badly, bring me a G.E.C.K.}
{501}{}{I have a holodisk full of information about G.E.C.K. Will you take that instead?}
{502}{}{What's that?}
{503}{}{A G.E.C.K.? As in a Garden of Eden Creation Kit?}

# Node012
{530}{}{It's a Garden of Eden Creation Kit. I've always wanted to study them, but they're extremely rare. I almost got my hands on one, but some tribal out west used it to create a new city before I could get to it.}
{531}{}{Oh, that. I have this holodisk with information about G.E.C.K. Will you take it instead of an actual G.E.C.K.?}
{532}{}{Deal. Now, what do you do around here?}
{533}{}{All right, it's a deal.}
{534}{}{Forget it. Goodbye.}

# Node013
{560}{}{You know about them, then? I've always wanted to study them, but they're extremely rare. I almost got my hands on one, but some tribal out west used it to create a new city before I could get to it.}
{561}{}{I have this holodisk with information about G.E.C.K. Will you take it instead of an actual G.E.C.K.?}

# Node014
{590}{}{Very funny. Even if you did manage to run off with it, you still wouldn't be able to use it. It's locked down by a security code, and only I know the code.}
{591}{}{Interesting. So, why did you leave the Brotherhood?}
{592}{}{Good to know. Now, what do you do around here?}
{593}{}{Save me the trouble of stealing it and sell it to me, then. I know there has to be something I can trade to you in exchange for the armor. What do you need? Caps? Information?}

# Node015
{620}{}{Well, I didn't really expect you to find a G.E.C.K., and a holodisk is better than nothing. We still have a deal - here's the power armor. Take care of it, and it'll take care of you.}
{621}{}{Thank you, Isaac!}

# Node016
{650}{}{Quite a ways to the southwest from here. I can't say how they'll receive you if you decide to go there, so be on your toes.}
{651}{}{I'll keep that in mind. So, what do you do around here?}
{652}{}{Okay. What you do around here?}
{653}{}{Can you show me its location on the map?}
{654}{}{Show on map.}

# Node017
{680}{}{There were a lot of rumors going around - Brotherhood soldiers massacring civilians, stealing technology, and running weapons to raiders. Among other things.}
{681}{}{Were any of the rumors true?}
{682}{}{That sound bad. It true?}

# Node018
{710}{}{Probably. I saw Brotherhood tech in the hands of people who shouldn't have had access to it, and command wasn't explaining how it got there. So, I wanted out, and here I am.}
{711}{}{Did anyone else leave?}
{712}{}{Other people leave, too?}

# Node019
{740}{}{A whole bunch of people, actually. All the Scribes - Brotherhood must be really hurting from this one - and a few of the Knights, too, I think.}
{741}{}{Interesting. Thank you for your time.}
{742}{}{'K. Me go.}

# Node020
{770}{}{Hmmm... the quartermaster probably used a polymorphic encryption technique, something only a handful of the Scribes know anything about it. Fortunately, I'm one of them. Give me a few hours and I'll create a decryption algorithm for you.}
{771}{}{[Wait.]}
{772}{}{Actually, I'm familiar with that technique, too. I'll help you out - it should cut down on the time.}

# Node021
{800}{}{All done. This holodisk has everything you need to remove the security codes.}
{801}{}{What about you? Aren't you going back?}
{802}{}{How come you not go back to Bunker?}

# Node022
{830}{}{No, Mesa Verde is my home now. No military chain-of-command, no drills, and no war. Besides, *someone* has to keep Trig from blowing up the village.}

# Node023
{860}{}{This place is home now. It's better than the Bunker.}

# Node024
{890}{}{I live here, of course. It's nice and quiet most of the time. Now, if you're asking me about my "job", then I'd have to say it's assisting Trig with her repairs and, uh, "inventions."}
{891}{}{Something wrong with Trig's inventions?}
{892}{}{Her inventions not good?}

# Node025
{920}{}{Most Ciphers are traditionalists. They build and repair electronics based on the specifications laid out by their ancestors, and *nothing* more. Trig is different - she often tries to be... creative.}
{921}{}{What happens when she's creative?}
{922}{}{What that mean?}

# Node026
{950}{}{No, no, I didn't mean for it to sound like that. It's just that Trig's inventions don't always work out the way she intends them to.}
{951}{}{'K.}

# Node027
{980}{}{Most of the time, nothing. Other times, explosions. Trig is imaginative, but lacks the practical knowledge to carry out her ideas. I've been teaching her some of what I know, with mixed results.}
{981}{}{What kind of mixed results?}
{982}{}{Not understand. What you mean?}

# Node028
{1010}{}{It just means that her inventions sometimes hurt people on accident. I've been trying to teach her some things which could help her, but she's still impractical at times.}
{1011}{}{[CONTINUE]}

# Node029
{1040}{}{See that monstrosity by the cliff? Trig's "death cannon". It doesn't fire, and I'm afraid of what might happen if it ever does. That's what I mean.}

# Node030
{1070}{}{You see that big machine by the cliff? Trig calls it her "death cannon". It doesn't work, and I'm afraid bad things will happen if it ever does work.}

# Node031
{1100}{}{Well, I had considered Trig's "death cannon" as the best example of one of Trig's interesting but impractical ideas, but it looks it works after all, thanks to you.}
{1101}{}{Has she learned *anything* from you?}
{1102}{}{Oh. She dumb.}

# Node032
{1130}{}{Certainly. Trig knows how to build working radios now, something no Cipher has been able to do before. I'm careful not to share too much knowledge, though. Too dangerous for the Ciphers.}
{1131}{}{Too dangerous?}

# Node033
{1160}{}{No, Trig is actually very, very smart. She's learned how to build many things from me, like radios. She's the first Cipher who ever knew how to do that.}

# Node034
{1190}{}{Mesa Verde is not the place to experiment with things like high-energy equipment. Even if it was, I'm also afraid of making this village a target for every greedy warlord in the region.}

# Node035
{1220}{}{Hey, you're wearing *my* armor!}
{1221}{}{Uh, yeah. I figured that since you weren't using it, I could borrow it.}
{1222}{}{Yup. Me borrow it.}
{1223}{}{You're mistaken. I retrieved the armor from a raider I killed. The suit only looks like yours because they're probably the same model.}
{1224}{}{Nuh-uh! Me kill bad guy and take it from him. This armor and your armor just look same.}

# Node036
{1250}{}{Is that *my* armor your friend is wearing?}
{1251}{}{Uh, yeah. We figured that since you weren't using it, we could borrow it.}
{1252}{}{Yup. We borrow it.}
{1253}{}{You're mistaken. We retrieved the armor from a raider we killed. The suit only looks like yours because they're probably the same model.}
{1254}{}{Nuh-uh! We kill bad guy and take it from him. This armor and your armor just look same.}

# Node037
{1280}{}{Right. Well, I guess you're going to keep it, seeing as how I don't have a chance of taking it back by force.}
{1281}{}{No, I said I only borrowed it, and I meant it. Here, take it back.}
{1282}{}{Nope. Me borrow it only, not steal for good. Me give it back now.}
{1283}{}{Goodbye.}

# Node038
{1310}{}{Oh. Well, you're right - most power armor *does* look alike. I suppose someone might have borrowed my armor to study it. Sorry about the mistake.}
{1311}{}{[END]}

# Node039
{1340}{}{I'm not senile yet. That's *my* armor, no mistake about it.}
{1341}{}{All right, here. Take it back.}
{1342}{}{Okay. Me give it back.}

# Node040
{1370}{}{It doesn't make it right that you took it without permission in the first place, but since you're giving it back, I guess I'll just have to forgive you.}
{1371}{}{That's what I always say - it's better to ask for forgiveness than permission.}

# Node041
{1400}{}{I'm sorry but I can't help you.}
{1401}{}{Why?}

# Node042
{1430}{}{Because I don't want to help the Brotherhood. That's my final word on this.}
{1431}{}{Hmm. Alright then.}
{1432}{}{Isaac, the people in the Brotherhood are your former friends. They provided and saved your butt many times. Now, the situation they are in is grim. They need this one last favor from you.}

# Node043
{1460}{}{Alright, damn it. I'll help you.}
{1461}{}{That's the spirit!}

# Node044
{1490}{}{Sorry, the village doesn't trust you yet. So, I can't trust you with that information. Prove yourself to us.}
{1491}{}{I see. Bummer.}
{1492}{}{Ugph!}

# Node045
{1520}{}{Alright, you did much for the village and the Ciphers respect you. Let me show you the exact location.}
{1521}{}{Thank you.}
{1522}{}{Tank!}
