# Message file for mvnemonk.ssl
# Number of nodes: 27
# Grammar pass done

{100}{}{You see an elderly man with a wise, weathered appearance.}
{101}{}{You see Nemonik, the "memory keeper" of the Ciphers.}
{102}{}{He has a calm demeanor, with a hint of mystery.}

# Node001
{200}{}{Ahhhh... an unknown variable is introduced into the village. I am the Nemonik. Be welcome, outsider.}
{201}{}{Why am I an "unknown variable"?}
{202}{}{Um... hello, old guy!}
{203}{}{Goodbye.}
{204}{}{Urg.}

# Node002
{230}{}{Welcome again, outsider. What may I do for you?}
{231}{}{What do you do here?}
{232}{}{What job you do?}
{233}{}{I might be able to fix your computer.}
{234}{}{I fixed the computer, but it can only be used to store and retrieve information.}
{235}{}{I have some raw data here from a supercomputer named ZAX. Can you use the Ritual to process it?}
{236}{}{The Hounds are gone. Can you do the Ritual now?}

# Node003
{260}{}{You are an outsider and therefore have great potential to disrupt the Counter's carefully calculated harmony of our village.}
{261}{}{The Counter? Who's that?}

# Node004
{290}{}{Ah, unfortunate. Your intelligence is below the normal mean for humans. I am surprised the Counter lets you roam Mesa Verde without an escort.}
{291}{}{Me counter, too. One, two... uh, five. See?}
{292}{}{Uh-huh. What job you do here?}

# Node005
{320}{}{As I said, I am the Nemonik. A foreign word to you, perhaps? It means... "memory keeper." In other times, I lead the Ritual.}
{321}{}{You mentioned the Counter. Who's that?}
{322}{}{What's the Ritual?}
{323}{}{What do you teach?}

# Node006
{350}{}{I am a teacher. Well, I am more than that, but I am afraid that you would probably not understand.}
{351}{}{You say somebody counting me? Who?}
{352}{}{What you teach?}

# Node007
{380}{}{Our Counter is Azkee. It is his responsibility to ensure that Mesa Verde can survive, and thus it is his responsibility to factor in all variables which can affect the village.}
{381}{}{I see. So, what do you do here?}

# Node008
{410}{}{No, no. Our leader is called the Counter. He makes sure the village runs smoothly, a task I fear will be complicated by your presence.}
{411}{}{M'kay.}

# Node009
{440}{}{It is a special ceremony for times when we are presented with a problem too great for one mind alone to solve. By acting as one, we Ciphers can solve any mathematical dilemma.}
{441}{}{How is that possible?}
{442}{}{You're saying that all the Ciphers together can act like a computer?}
{443}{}{I have some raw data here from a supercomputer named ZAX. Could you use the Ritual to process it?}

# Node010
{470}{}{Yes. The Ritual became necessary after the computer of our ancestors failed. Unfortunately, the Ritual is not a complete replacement for the computer.}
{471}{}{What do you mean?}

# Node011
{500}{}{You see the schematics on the walls around you? Our ancestors carved them on the walls after the computer failed, but time and weather have not been kind to them. Our Ritual cannot save them.}
{501}{}{Why don't you just repair the computer and store the schematics in there?}
{502}{}{Good thing I repaired your computer.}

# Node012
{530}{}{Our ancestors did not possess the knowledge to do those repairs, and, unfortunately, neither do we. Long ago, a Nemonik removed the memory core of the computer so any technical knowledge had to be passed on by the Nemonik himself. This was done to ensure that Mesa Verde didn't destroy itself with technology it wasn't responsible enough to handle. The computer might give us access to *all* the knowledge.}
{531}{}{Where's the computer now? I might be able to fix it.}
{532}{}{I could fix the computer, for a price.}

# Node013
{560}{}{In the storage cave, at the north end of the village. I fear that it may have been scavenged for spare parts, though, making its repair even more difficult.}
{561}{}{All right, I'll go have a look at it.}
{562}{}{I didn't say I was going to do it for "free." I expect payment for my services.}

# Node014
{590}{}{Not at this time. The Ritual requires all Ciphers to fall into a meditative trance, and it is too risky to do this while the Hounds continue to harass us.}
{591}{}{All right. I'll go take care of them.}
{592}{}{Who are the Hounds, and what do they want?}
{593}{}{That's unfortunate. Goodbye.}

# Node015
{620}{}{I shall gladly call together a Ritual for you. Do you wish this done now?}
{621}{}{Yes, let's do it.}
{622}{}{Wait, I need to handle something else first.}

# Node016
{650}{}{Storage is all we need it for. Thank you, outsider.}
{651}{}{And my payment?}

# Node017
{680}{}{Servants of a madwoman who claims she controls the fertility of all the tribes. We refused to allow one of her Daughters to live here, and she sends her Hounds as punishment.}

# Node018
{710}{}{Of course. Here is the medicine as I promised.}
{711}{}{Thank you.}

# Node019
{740}{}{Of course. Mesa Verde is by no means a rich village, but I can give you some bottlecaps and medicines from my personal supply if you restore the computer for us. Will this be sufficient compensation?}
{741}{}{Not good enough. Goodbye.}
{742}{}{All right, that'll do.}

# Node020
{770}{}{Excellent. Please, repair the computer quickly. We cannot afford to lose any more schematics.}

# Node021
{800}{}{Be careful, outsider. They are merciless warriors.}
{801}{}{[END]}

# Node022
{830}{}{Physics, chemistry, mathematics. Our ancestors were great scientists, you know. They came to Mesa Verde for shelter after their old home, a great place of science, was destroyed.}
{831}{}{Mesa Verde doesn't seem all that... advanced to me.}
{832}{}{This place not look all sciencey and stuff.}
{833}{}{Where was this place of science?}
{834}{}{Where they come from?}

# Node023
{860}{}{We prefer the simple life here. It is the preservation of the knowledge itself that is important to us. Our ancestors taught that it was reckless "use" of that knowledge which destroyed the world.}
{861}{}{Where did your ancestors come from?}
{862}{}{Where ancestors come from?}
{863}{}{Do you use your knowledge for anything?}
{864}{}{Um, what stuff you do if you so smart?}

# Node024
{890}{}{Far to the south. It is dangerous there, however. Invisible fire burns the flesh from a man's bones. Our ancestors fled here for shelter and to preserve their immense amount of knowledge.}
{891}{}{Mesa Verde doesn't look very advanced.}

# Node025
{920}{}{Mathematics is the First Science. All children are taught it from the moment they begin to speak. This very intimate knowledge of mathematics is why our Ritual works. Most of the time, anyway.}
{921}{}{All the Ciphers working together can act like a computer?}

# Node026
{950}{}{Electronics has long been a specialty of the Ciphers. Few in the wasteland understand it as much as we do, which is quite a surprise to those who think we are merely primitive tribals.}
{951}{}{Do you have any electronics for sale?}
{952}{}{Me buy things.}

# Node027
{980}{}{I am merely a teacher. Speak to Trig, our resident artisan.}
{981}{}{Thank you. Goodbye.}

# Node028
{1010}{}{Thank you, outsider.}
