# Message file for mvradian.ssl
# Number of nodes: 30

{100}{}{You see a Cipher suffering from a nervous disorder.}
{101}{}{You see Radian.}
{102}{}{He shakes a lot, especially in his hands.}

{150}{}{You cured Radian's illness.}
{151}{}{Instead of curing Radian, you gave him some extremely addictive painkillers instead. He'll feel cured, but only for a few hours.}
{152}{}{You used Radian's painkiller addiction against him and forced him to sabotage the wind turbine for you.}

# Node001
{200}{}{*cough* What do you want, outsider?}
{201}{}{Who are you?}
{202}{}{Who you?}
{203}{}{Goodbye.}
{204}{}{Buh-bye.}

# Node002
{230}{}{*cough* Hello, again.}

# Node003
{260}{}{Hello, doctor! Thanks again for curing me.}

# Node004
{290}{}{Hey, doctor, I think I'm getting sick again. I could *really* use some more of that medicine.}
{291}{}{What do you do around here, Radian?}
{292}{}{What you do here?}
{293}{}{Are you all right?}
{294}{}{You not look good.}
{295}{}{I can probably do something about that illness, Radian.}
{296}{}{Well, Radian, that medicine isn't cheap or easy to come by.}

# Node005
{320}{}{Radian. [He begins to shake uncontrollably.]}
{321}{}{What do you do around here?}
{322}{}{Do you know what's wrong with you?}

# Node006
{350}{}{*cough* No. Pretty sick. Not sure what's wrong.}
{351}{}{Hmmm... dilated pupils, clammy skin... do you feel thirsty and dizzy all the time?}
{352}{}{You sick. Me doctor. Me fix you.}
{353}{}{Sorry to hear that. What do you do here?}
{354}{}{Oh. What you do here?}

# Node007
{380}{}{Yeah. Been using up more than my share of water. *cough*}
{381}{}{It sounds like you've got High Desert Fever. It's not contagious, but it'll eventually kill you if it isn't treated.}

# Node008
{410}{}{*cough* Can you help me?}
{411}{}{Yes, I can. The fever can be treated with common medicines available in my doctor's bag.}
{412}{}{I could, but I don't have a doctor's bag with me right now.}

# Node009
{440}{}{Thank you. *cough*}
{441}{}{[Pull out supplies from your doctor's bag and give Radian the cure.]}
{442}{}{[Use supplies from your doctor's bag to give Radian some extremely addictive painkillers instead of the cure.]}

# Node010
{470}{}{Please! I need more medicine. I have no money, but I'll do anything. *Anything!*}
{471}{}{Sing for me.}
{472}{}{Anything, huh? Would you sabotage the wind turbine?}

# Node011
{500}{}{Uh... okay. Ahem. "Give me a kiss to build a dream on, and my imagination will thrive upon that kiss. Sweetheart, I ask no more than this: a kiss to build a dream on."}
{501}{}{Nice, very nice.}
{502}{}{Now I want you to do is to sabotage the wind turbine.}

# Node012
{530}{}{I can't do that! We couldn't make any more water, and we'd all be doomed!}
{531}{}{Well, I guess you don't need more medicine after all, then. I'll just go sell it, or maybe throw it away, or feed it to an ill-tempered brahmin...}

# Node013
{560}{}{No, no! Wait! You bastard, what have you done to me? I'll do what you ask - just give me the medicine.}
{561}{}{No, no! Wait! You bitch, what have you done to me? I'll do what you ask - just give me the medicine.}
{562}{}{I don't think so, Radian. Do what I asked first, and *then* you'll get your medicine.}

# Node014
{590}{}{D-don't go anywhere. I'll do it, and be right back.}
{591}{}{All right. Oh, and Radian - don't even think about betraying me.}

# Node015
{620}{}{*cough* Wow... I'm feeling pretty good... and sleepy.}
{621}{}{Why don't you just take a nap now, and I'll come see you again in a few hours.}

# Node016
{650}{}{I'll do that. Thanks, doctor.}
{651}{}{I'll check back in an hour to see how you're doing. Goodbye.}

# Node017
{680}{}{Wow! I feel much better already! Thanks, doctor!}

# Node018
{710}{}{*cough* Usually the same as everybody else - farm, hunt, and guard the village. Been too weak to do that lately.}

# Node019
{740}{}{I'm back to helping out with the farming and hunting, thanks to you.}

# Node020
{770}{}{I'm feeling a little better, but I'm starting to get the shakes again.}

# Node021
{800}{}{*cough* You, a doctor? Right. *cough* Thanks for the offer, but stay away from me.}
{801}{}{Okay. What you do here?}

# Node022
{830}{}{Oh. *cough* Thanks, anyway.}
{831}{}{What do you do here?}

# Node023
{860}{}{There, it's done. Give me my medicine!}
{861}{}{Good. Here's your medicine.}

# Node024
{890}{}{Am I done humiliating myself? Can I have the medicine now?}
{891}{}{Sure. Here you go.}
{892}{}{Not just yet. I'd also like you to sabotage the wind turbine for me.}

# Node025
{920}{}{Ahhhh... feeling *so* much better again.}

# Node026
{950}{}{*cough* Hey! Hey, doctor! It's me! Radian, remember?}
{951}{}{Why, hello, Radian. What are you doing in Hoover Dam?}

# Node027
{980}{}{*cough* Hey, doctor. You, uh, brought some medicine for me?}
{981}{}{Yes, I did. You'll need to do something for me first, though.}

# Node028
{1010}{}{*cough* Village is gone - Hounds got everybody except me. Hey, have you got any more medicine for me? The stuff around here's not so good.}
{1011}{}{Sure, Radian. But, there's something I need you to do, first.}
{1012}{}{Sorry, I'm out.}

# Node029
{1040}{}{Again? Okay, what you want done, and I'll go do it. *cough*}
{1041}{}{[Pending on Hoover Dam quests]}
{1042}{}{I want you to work for me at Fort Abandon. Go there on the next caravan.}

# Node030
{1070}{}{*cough* Well, I'm not going anywhere. Do me a favor and scrounge some up for me, will you? *cough*}
