# Message file for mvsymm.ssl
# Number of nodes: 9

{100}{}{You see a weather-beaten Cipher.}
{101}{}{You see Symm.}
{102}{}{He seems like an adventurous type.}

# Node001
{200}{}{Yes, outsider?}
{201}{}{Who are you?}
{202}{}{Who you?}

# Node002
{230}{}{Outsider! What do you know about what happened here?}
{231}{}{What are you talking about?}
{232}{}{What you say?}
{233}{}{Goodbye.}
{234}{}{Buh-bye.}

# Node003
{260}{}{In order to remain within the village, I must work, something I cannot do if you continue to disturb me. What do you need?}
{261}{}{Trig said you might know something about a docking clamp.}
{262}{}{You know stuff about docking thingie?}

# Node004
{290}{}{I am Symm. Is there something you need from me?}
{291}{}{Nothing actually.}
{292}{}{No.}

# Node005
{320}{}{My people have been slaughtered! You are an outsider. What do you know about this?}
{321}{}{Well, last time I was here, they were having some trouble with the Hounds of Hecate. Looks like the Hounds won.}
{322}{}{Everything. I was the one who killed them.}

# Node006
{350}{}{Idiot! My people are dead! What do you know about this?}
{351}{}{Maybe dog guys kill them.}
{352}{}{Me kill everybody.}

# Node007
{380}{}{Then the Hounds shall pay for the murders of my people. Step aside, outsider. My vengeance awaits.}
{381}{}{Wait! Do you know anything about a docking clamp?}
{382}{}{Wait! Me need docking thingie!}

# Node008
{408}{}{I have explored many places of the Old World and stored many things in my Pip. Perhaps what you need is in there.}
{409}{}{But I see that you don't have a Pip. I cannot transfer what I know to you.}
{410}{}{I see that you, too, have a Pip. I shall transfer what I know to you.}
{411}{}{Thank you.}
{412}{}{Thank.}
{413}{}{Crap.}
{414}{}{Poo.}

# Node009
{440}{}{I shall avenge my people! Die!}
{441}{}{[Defend yourself.]}
