
{100}{}{You approach a dark and broken city, perhaps once one of the greatest in the world. A stench of death surrounds the area, and little life can be seen, offering only a glimmer of hope that things might get better.}
