# Message file for rebetty.ssl

{100}{}{You see a grey-haired ghoul polishing a heavy-looking metal armor.}
{101}{}{It's Betty, the used-armor reseller and fixer.}
{102}{}{She is surprisingly skillful in restoring the heavy armor. The armor is dented in places where it has repelled gun-fire.}

# Betty2_Trade_1
{2690}{}{I told you I was the best.}
{2693}{}{That did it for me. Thanks, Betty, I'll be going now.}

# Betty2_Trade_2
{2749}{}{Yeeash, 300 pounds of green muscle and only one brain cell. [She rolls her eyes and makes a vomiting expression] If you're here to barter armored protection with Betty, one of the best, then let's strike a deal. Otherwise, I'm not up for any lollygagging.}

{2750}{}{Yeeash, a smoothskin. [She rolls her eyes and makes a vomiting expression] If you're here to barter armored protection with Betty, one of the best, then let's strike a deal. Otherwise, I'm not up for any lollygagging.}
{2751}{}{Straight down to business? Alright.}
{2752}{}{Sorry, don't want to trade.}
{2753}{}{We haggle waggle.}
{2754}{}{Sorry, no haggle waggle.}
