# Message file for rehank.ssl
# Number of nodes: 12

{100}{}{You see a gangly ghoul.}
{101}{}{You see Hank, the Reservation's fast-talking merchant.}
{102}{}{A ghoul with a century-old gleam in his eye.}

# Hank's standard float text.
{200}{}{Best prices in the Reservation.}
{201}{}{What I don't got, you don't need.}
{202}{}{See anything you fancy?}
{203}{}{Make me an offer.}

# Jillian is gone
{210}{}{*sigh* Jillian...}
{211}{}{I miss my Jill..}
{212}{}{Wish I could trade Betty for Jill. Would do it in a snap!}
{213}{}{*sniff*}
{214}{}{I'm not crying -  it's just my eye sockets oozing.}
{215}{}{Jill...}
{216}{}{Jillian...}
{217}{}{Come back Jillian...}
{218}{}{Wish I was a smoothskin again, then Jill would love me and never leave.}

# HANK001a
{260}{}{Howdy partner! Name's Hank, and this here's my little piece o' heaven. What can I do for you?}
{261}{}{Howdy ma'am! Name's Hank, and this here's my little piece o' heaven. What can I do for you?}
{262}{}{I'd like to take a look at your wares.}
{263}{}{What is it you do around here, Hank?}
{264}{}{Heaven indeed. I'll be going now.}
{265}{}{What you got for sell?}
{266}{}{What you do here?}
{267}{}{Goodbye, Hank.}

# HANK001b
{290}{}{If it ain't my favorite customer. What can I do for you on this fine day?}
{291}{}{Nothing for now. Goodbye.}
{292}{}{Want barter.}

# HANK002_1
{320}{}{Let's see what ol' Hank can do for ya.}
{321}{}{Hmmm...}

# HANK002_2
{350}{}{Anything else I can do you for, partner?}
{351}{}{Anything else I can do you for, ma'am?}
{352}{}{Tell me a bit more about what you do around here.}
{353}{}{That did it, thanks. Goodbye for now.}
{354}{}{What else you do here?}

# HANK003
{380}{}{Ah, you know, little of this, little of that. Mostly try and do what I can to keep the folks around here in what they need between Horatio's slavers visits.}
{381}{}{I see. Can I look at your wares?}
{382}{}{Who's Horatio?}
{383}{}{How thoughtful. I'll be going now.}
{384}{}{I want trade.}
{385}{}{Who Hor-ati?}

# HANK005
{410}{}{Well ol' Horatio runs the slave trading over there in that big tent. Not my favorite sort of character, but we'd be up the damn creek missin' a paddle if it weren't for the workforce, food and supplies the slavers run to us.}
{411}{}{You don't have your own food supply?}
{412}{}{Good for him. I'll be going now.}

# HANK006
{440}{}{Nope. Heh, last time me and Betty tried growing somethin' it damn near bit our heads off.}
{441}{}{It tried to bite your head off?}
{442}{}{Maybe the two of you should be a little more careful next time. I'll be going now.}

# HANK007
{470}{}{Well, in a manner of speaking. Betty says there's too many of them radioactive i-si-topes and what-not floating around to make the ground worth a damn. That's why we're relying on Horatio's slavers to bring in what we can't scavenge outta the wastes.}
{471}{}{Sounds like a lot of work. Can I see your wares?}
{472}{}{What makes the radiation here so much worse?}
{473}{}{Doesn't sound like a very good deal to me.}
{474}{}{Sounds rough. I need to be going.}

# HANK008
{500}{}{Can't say for sure. Most folks from round here'll tell you this part of the world got hit harder in the war than most other places hereabouts. That can't have helped.}
{501}{}{Slavery doesn't sound like something you should be proud off.}
{502}{}{Sounds like a plan. I'll be heading that way now.}

# HANK009
{529}{}{'Course it's a shitty thing, but there ain't nothing we can do about it. Horatio's got our backs to the wall and he knows it. There are bigger players in the Reservation pulling strings and setting rules. But enough of my troubles; you here to deal or what, ma'am?}
{530}{}{'Course it's a shitty thing, but there ain't nothing we can do about it. Horatio's got our backs to the wall and he knows it. There are bigger players in the Reservation pulling strings and setting rules. But enough of my troubles; you here to deal or what, partner?}
{531}{}{Sure am.}
{532}{}{I have to be going.}
