# Message file for rehorati.ssl

{100}{}{You see a big, mean ghoul.}
{101}{}{It's Horatio the Slaver. }
{102}{}{One could surmise that in his smooth skin days he could have been an offensive lineman for pro football or a professional wrestler.}

# Horatio_1a_1
{230}{}{[The big ghoul looks you up and down with little interest] Yeah? And what do you want?}
{231}{}{[The big ghoul looks you up and down with a dirty leer] Hey there. What can Horatio do you for?}