# Message file for rejill.ssl
# Number of nodes: 4
# Grammar pass done

{100}{}{You see a woman in a protective radiation suit.}
{101}{}{You see Jillian, a captive of Hank's.}
{102}{}{She appears to be perspiring inside her radiation suit.}

# Node001
{200}{}{[She quickly glances at you but remains silent]}
{201}{}{Hello there.}
{202}{}{Hullo!}
{203}{}{[Leave her alone]}

# Node002
{230}{}{[The young woman replies, her voice pleasant to your ears] Hello, sir. I'm sorry, but if Hank catches me talking to you, I'll get in trouble.}
{231}{}{[The young woman replies, her voice pleasant to your ears] Hello, madam. I'm sorry, but if Hank catches me talking to you, I'll get in trouble.}
{232}{}{Can you at least tell me your name?}
{233}{}{Wut yur name?}

# Node003
{260}{}{Jillian... Jillian McKinley. Goodbye, sir.}
{261}{}{Jillian... Jillian McKinley. Goodbye, madam.}
{262}{}{Goodbye, Jillian.}
{263}{}{Bye-bye Jill!}

# Node004
{290}{}{I can't talk, sir. I have work to do.}
{291}{}{I can't talk, madam. I have work to do.}
{292}{}{Ah, I understand. Goodbye then.}
{293}{}{Oki. Bye-bye.}
