# Message file for remeasle.ssl
# Number of nodes: 119

{100}{}{You see a Latin-American man.}
{101}{}{It's Measles, the Mexican Wasteland Explorer.}
{102}{}{He looks friendly but impatient, as if bitten by the wanderlust bug.}

# Ferdinand floats these strings if he is mildly hurt.
{200}{}{I think I feel that last one a little.}
{201}{}{This hurt a little, but I've had worse.}
{202}{}{Nothing like a bit of pain to make a real man out of you.}
{203}{}{You got the stimpacks, amigo? I could used one, here.}

# Ferdinand floats these strings if he is seriously hurt.
{230}{}{Ay... I don' think I can go on much more.}
{231}{}{Puta! This hurt real bad, you know.}
{232}{}{Estoy pedo... we rest soon, okay?}
{233}{}{I don' feel this bad since the Explorers go to Sandover.}

# Ferdinand floats these strings if he has been part of the PC's group, but has been asked to wait behind.
{260}{}{I wonder when my frien' show up again.}
{261}{}{Ay! I hope we get moving again, soon.}
{262}{}{This is no place for a man to be left standing.}
{263}{}{I got better things to do than stan' here all day.}

# Ferdinand floats these strings if he doesn't like the area the party is in.
{290}{}{I got a bad feeling about this place...}
{291}{}{I think we should go soon, okay?}
{292}{}{I hope you're not thinking about staying too long.}
{293}{}{The sooner we're gone, the better.}
{294}{}{¿Qué pasa? Can we go soon?}
{295}{}{I don' mind telling you I am a little afraid.}

# Ferdinand floats these strings if the PC tells him to get out of the way.
{320}{}{Take it easy, amigo.}
{321}{}{¿Qué te pasa?}
{322}{}{I did not mean to get in your way, amigo.}
{323}{}{I didn't see you there, <PC>.}
{324}{}{Lo siento. I'll move.}
{325}{}{¿Cómo?}

# Ferdinand floats these strings if the party is in Crossroads.
{350}{}{I hope the Explorers do okay without me.}
{351}{}{Maybe we check out Sara's Place?}

# Ferdinand floats these strings if the party is in Rusty Springs.
{380}{}{This is where all the drinking water comes from.}

# Ferd_0
{410}{}{- STARTING CONDITIONS -}
{411}{}{- The PC has never met Ferdinand before -}
{412}{}{- The PC has met Ferdinand before -}
{413}{}{- The PC is female and has slept with Ferdinand before -}
{414}{}{- Ferdinand is a member of the PC's group -}

# Ferd_1a_1
{440}{}{Buenos dias, Senor. My name is Ferdinand. What bring you to the Wastelan' Explorers' tent?}
{441}{}{Buenos dias, Senorita. My name is Ferdinand. What bring you to the Wastelan' Explorers' tent?}
{442}{}{I was wondering what you do here.}
{443}{}{Why are you talking like that?}
{444}{}{I'm just leaving, actually.}

# Ferd_1a_2a
{470}{}{Like the others in here, I am a Wastelan' Explorer.}
{471}{}{What can you tell me about the Wasteland Explorers?}
{472}{}{What job do you have with the Wasteland Explorers?}
{473}{}{Goodbye.}

# Ferd_1a_2b_1
{500}{}{Que? Why am I talking like what?}
{501}{}{You sound foreign.}
{502}{}{You sound like an idiot.}
{503}{}{Never mind. Who are you, anyway?}
{504}{}{I must leave.}

# Ferd_1a_2b_2
{530}{}{*He smiles.* I soun' foreign to people from these places, si. I am from Mexico, amigo.}
{531}{}{*He smiles.* I soun' foreign to people from these places, si. I am from Mexico, Senorita.}
{532}{}{You're very far from Mexico. Why are you in Crossroads?}
{533}{}{I don't know Mexico. Is it near here?}
{534}{}{I see. Please tell me what you are doing here.}

# Ferd_1a_2b_2B_1
{560}{}{Wha' d'you mean, ''I soun' like an idiot?''}
{561}{}{I'm talking about that silly voice you're putting on.}
{562}{}{Sorry, it's just that your accent sounds strange.}
{563}{}{Never mind. So what do you do, anyway?}
{564}{}{You're not worth the time. Goodbye.}

# Ferd_1a_2b_2B_2a
{590}{}{Huh. Well, si. I am from Mexico. That is why I soun' different to you, gringo.}
{591}{}{That explains why you sound like such an idiot.}

# Ferd_1a_2b_2B_2b_1
{620}{}{Hey, fuck you, zurramato. This is how I speak, comprende?}
{621}{}{Hey, fuck you, panocha. This is how I speak, comprende?}
{622}{}{Don't you speak to me like that, asshole.}
{623}{}{I apologize. May I still ask you a question?}

# Ferd_1a_2b_2B_2b_2
{650}{}{So wha' the fuck are you gonna do about it, big man, huh? You got some big cojones to come in here looking for the trouble!}
{651}{}{So wha' the fuck are you gonna do about it, lady, huh? Don' you think being a senorita mean you can speak to Ferdinand like a mayate!}
{652}{}{*Draw weapon.*}

# Ferd_1a_2b_2B_2b_9
{680}{}{Ask me your damn question, gringo.}
{681}{}{Where do you come from?}
{682}{}{Actually, I don't have anything I need to ask you. Goodbye.}

# Ferd_1b
{710}{}{Hola, amigo. What can I do for you?}
{711}{}{Hola, Senorita. What can I do for you?}
{712}{}{Have you changed your mind about joining me?}
{713}{}{I'm just stopping to say hello. Goodbye for now.}

# Ferd_2_1
{740}{}{I am from Mexico, Senor.}
{741}{}{I am from Mexico, Senorita.}
{742}{}{That explains why you sound like an idiot.}
{743}{}{I see. Please tell me what you do, here.}

# Ferd_2_2a_1
{770}{}{My people, they think the world north of Mexico to be a better place to live. I came here looking for a better life.}
{771}{}{Is it a better life, here?}
{772}{}{I have to be going.}

# Ferd_2_2a_2
{800}{}{No. During the war, the bombs make a much worse mess here in America than they do in Mexico.}
{801}{}{Which part of Mexico do you come from?}
{802}{}{How badly was Mexico damaged during the war?}
{803}{}{Why don't you return to Mexico?}

# Ferd_2_2a_3a_1
{830}{}{I come from Mexico City. She was hit by many bombs during the war. There is little left above the surface.}
{831}{}{'Above the surface'? What is below it?}

# Ferd_2_2a_3a_2
{860}{}{A whole undergroun' world exists under Mexico City that no-one use or know about. Basements; old tunnels; old subway routes. My ancestors, they live in these areas long before the world above go loco and everyone blow each other up.}
{861}{}{Why do you think Mexico was attacked during the war?}
{862}{}{You mean your ancestors were vagrants?}

# Ferd_2_2a_3a_2B_1
{890}{}{You mean like bums? You would not call them that to their faces; we are a proud people. Plus, we survive the war where others do not.}
{891}{}{I'll call whomever I like whatever I like.}

# Ferd_2_2a_3a_2B_2
{920}{}{*Ferdinand looks unimpressed.* Maybe you should watch your mouth, huh? Especially when you bring my family into it.}
{921}{}{Maybe you should fuck off, vagrant.}

# Ferd_2_2a_3b_1
{950}{}{Although not as bad as America, Mexico was hit pretty bad, you know? All the cities are in ruins. Perhaps the radiation is not so bad as it is around here, though.}

# Ferd_2_2a_3b_2
{980}{}{*Ferdinand grins.* That come to be something of a joke in Mexico. Amongst the survivors, at least.}
{981}{}{- MORE -}

# Ferd_2_2a_3b_3
{1010}{}{Some, they say the Reds see Mexico as a big friend and ally of America, so they blow us up. Others, they say America was not so keen on Mexico surviving the war so close to them and perhaps taking over, so the gringos take us with them.}
{1011}{}{Which of the two do you think is true?}

# Ferd_2_2a_3b_4
{1040}{}{*He shrugs.* I don' really give it much thought. I don' see what difference it make.}

# Ferd_2_2a_3c_1
{1070}{}{Maybe when I was a younger man I would have returned if had made enough money. I am too old now, though. Mexico, she has probably changed too much since I left.}
{1071}{}{How long has it been since you left Mexico?}

# Ferd_2_2a_3c_2
{1100}{}{Ay, you're asking me a tough question, there. I don' know, say maybe twenty-five or thirty years ago? It seem like a lifetime ago.}

# Ferd_2_2b_1
{1130}{}{*He laughs.* Tha's pretty funny! No, amigo, before the war, Mexico used to be a country, like America.}
{1131}{}{*He laughs.* Tha's pretty funny! No, Senorita, before the war, Mexico used to be a country, like America.}
{1132}{}{How could I find it?}
{1133}{}{Don't laugh at me. You're the one who talks like an idiot.}

# Ferd_2_2b_2
{1160}{}{Mexico is south of here, but she is many hundreds of miles away. I doubt you would ever reach her, amigo.}
{1161}{}{Mexico is south of here, but she is many hundreds of miles away. I doubt you would ever reach her, Senorita.}
{1162}{}{If it's so far away, why are you in Crossroads?}

# Ferd_3_1a
{1190}{}{Our group, we look for technology left behind after the Great War. What we find, we sell.}
{1191}{}{Do the Explorers make much money that way?}
{1192}{}{Excuse me, I have to go.}

# Ferd_3_1b_1
{1220}{}{I usually work with Bruce. We go scouting for areas where tech can be found.}
{1221}{}{What can you tell me about Bruce?}
{1222}{}{Who is in charge of the Explorers?}
{1223}{}{What do you do with the tech you find?}
{1224}{}{May I ask you a question about something else?}

# Ferd_3_1b_2
{1250}{}{Pre-war tech sells for big money, amigo. Finding buyers for tech is no big deal; finding something to sell in the first place is the problem!}
{1251}{}{Pre-war tech sells for big money, Senorita. Finding buyers for tech is no big deal; finding something to sell in the first place is the problem!}
{1252}{}{Is there good money to be made in exploring?}

# Ferd_3_2a_1
{1280}{}{The group works in two different ways. Some of the Explorers, they go out into the wastes and look for sites where tech from before the war can be found. Others, they go to the sites where we have found tech and dig it up.}

# Ferd_3_2a_2
{1310}{}{Bruce is in charge of any groups we send that explore the wastes for new finds. Miranda, she is Bruce's wife. She run any of the groups which go out an' dig up the tech once it is found.}
{1311}{}{What can you tell me about Miranda?}

# Ferd_3_2a_3a_1
{1340}{}{He is a great guy to work with, you know? Hey, you should speak to him yourself.}
{1341}{}{Thanks. Where can I find Bruce?}
{1342}{}{What does Bruce do?}

# Ferd_3_2a_3a_2
{1370}{}{You can't miss him. The big hombre in the leather jacket at the back of the tent.}
{1371}{}{I'll go and speak to him now. Goodbye.}

# Ferd_3_2a_3b_1
{1400}{}{Miranda is a good lady. A real mother for the group. Remember that she is married to Bruce, though, amigo. He can be a pretty mean guy when he wants to be.}
{1401}{}{Miranda is a good lady. A real mother for the group. You would like her; maybe you should introduce yourself to her, no?}
{1402}{}{I'd like to meet her. Where is she?}
{1403}{}{I'll behave myself, don't worry. Where can I find her?}
{1404}{}{What does Miranda do?}

# Ferd_3_2a_3b_2
{1430}{}{* TELL THE PC WHAT MIRANDA LOOKS LIKE AND WHERE SHE IS *}
{1431}{}{I'll go and speak to her now. Goodbye.}

# Ferd_3_2b_1
{1460}{}{*He frowns and snorts with frustration.* Maybe a few years ago, before we found all there was to find around Crossroads, yes, there were big amounts of caps to be made.}

# Ferd_3_2b_2
{1490}{}{These days? When it is really quiet, some of us even work as guards for the caravans. I don' know if there is much left to be explored aroun' here.}
{1491}{}{If it came to it, would you become a caravan guard permanently?}

# Ferd_3_2b_3
{1520}{}{Si, I could do that. But I don' wan' to. This life... it is good, you know? I would rather be exploring the world rather than just travelling back an' forward between the same towns.}
{1521}{}{I do a lot of travelling. Would you like to come with me?}

# Ferd_4_1
{1550}{}{*Ferdinand is taken aback slightly.* I appreciate the offer, amigo. Lemme just think about that for a second, though.}
{1551}{}{*Ferdinand is taken aback slightly.* I appreciate the offer, Senorita. Lemme just think about that for a second, though.}
{1552}{}{Sure.}

# Ferd_4_2a_1
{1580}{}{*He shakes his head.* Sorry, amigo. It is too much of a risk to go out into the wastes with someone about whom I know so little. I hope you understand.}
{1581}{}{*He shakes his head.* Sorry, Senorita. It is too much of a risk to go out into the wastes with someone about whom I know so little. I hope you understand.}
{1582}{}{I understand. What could I do to prove that I am a worthy companion?}
{1583}{}{In that case, can I ask you a question?}

# Ferd_4_2a_2
{1610}{}{Ay... I don' know. Maybe you do something to help the Explorers?}
{1611}{}{Okay. Do you have any ideas?}
{1612}{}{Let me ask you a question instead.}

# Ferd_4_2a_3
{1640}{}{No, I can't think of anything. Maybe you should speak to Bruce or Miranda; they know more abou' what the Explorers need.}
{1641}{}{Where can I find Bruce?}
{1642}{}{Where can I find Miranda?}

# Ferd_4_2b_1
{1670}{}{*He gives you a big 'what-the-hell' grin.* Si, si, why not, eh?}

# Ferd_4_2b_2
{1700}{}{Jus' give me a moment. I collect my things, say 'goodbye' to my friends, here. Then I be with you.}
{1701}{}{- WAIT -}
{1702}{}{I only asked to see if you'd changed your mind. I'll come back when I'm ready for you to join me.}

# Ferd_4_2b_3a
{1730}{}{Well, this is it, I guess. I hope I do the right thing! Lead the way, amigo.}
{1731}{}{Well, this is it, I guess. I hope I do the right thing! Lead the way, Senorita.}
{1732}{}{Welcome aboard, Ferdinand.}
{1733}{}{Let's go.}

# Ferd_4_2b_3b
{1760}{}{Oh... well, okay. Come an' speak to me again when you are ready to go.}
{1761}{}{I'll be back in a while.}

# Ferd_4_2F_1
{1790}{}{Listen, this is hard for me to say. I'm no' sure I wan' to become your companion an' go out into the wastes with you yet. I don' know you properly, so it could be dangerous...}
{1791}{}{Let me ask you a question about something else, in that case.}
{1792}{}{Forget it, then. Goodbye.}

# Ferd_4_2F_2
{1820}{}{But, look, I think you might be a very special lady. I would like to get to know you a little better, Senorita.}
{1821}{}{I'd like that.}
{1822}{}{I think we'd better change the subject. Can I ask you a question about something else?}
{1823}{}{Forget it. Goodbye.}

# Ferd_4_2F_3
{1850}{}{You would? *Ferdinand gives a surprisingly shy smile.* Tha's just great! How abou' we meet up at Sara's Place a little later on this evening? I buy you a drink; we get to find out about each other.}
{1851}{}{Okay. What time shall I meet you there?}
{1852}{}{Are you asking me out on a date?}

# Ferd_4_2F_4a_1
{1880}{}{Let's say nine o'clock this evening. Is that okay for you?}
{1881}{}{Nine o'clock this evening sounds fine.}

# Ferd_4_2F_4a_2
{1910}{}{Muy grande! I see you then, Senorita.}
{1911}{}{Can I ask you a question about something else before I go?}

# Ferd_4_2F_4b
{1940}{}{*Ferdinand sighs* Ay... this never gets easy. Si, I guess you would say that I am asking you out for the date.}
{1941}{}{Okay. What time shall I meet you at Sara's Place?}

# Ferd_5_1
{1970}{}{*Ferdinand has obviously spent a lot of time on his appearance. He looks a great deal smarter than when you met him in the Wasteland Explorers' tent. As you get closer, you notice that he is holding a flower.*}
{1971}{}{Hello, Ferdinand.}
{1972}{}{*Leave before he notices you.*}

# Ferd_5_2
{2000}{}{*His face lights up as he sees you.* Buenas noches, Senorita! You look beautiful. Here, I bring this flower for you. *He offers you the single bloom - a rarity in the wasteland.*}
{2001}{}{Thank you, Ferdinand. It's beautiful. *Take the flower.*}
{2002}{}{I'm sorry, this isn't going to work. Goodbye.}

# Ferd_5_3
{2030}{}{You know, it is a little funny, but I still do not know your name.}
{2031}{}{It's }
{2032}{}{.}

# Ferd_5_4_1
{2060}{}{. *He smiles again.* That have a lovely soun' to it.}
{2061}{}{Thank you. You're very kind.}
{2062}{}{Don't be silly. }
{2063}{}{ is a horrible name.}

# Ferd_5_4_2
{2090}{}{Hey, you mustn't think like that. I think }
{2091}{}{ is a won'erful name.}

# Ferd_5_5
{2120}{}{So, }
{2121}{}{, wha' can I get you to drink?}
{2122}{}{What does Sara have?}

# Ferd_5_6
{2150}{}{I think she have the water, the Nuka Cola, the beer, or the strong booze for offer.}
{2151}{}{I'll have some water.}
{2152}{}{I'll have a Nuka Cola.}
{2153}{}{I'll have a beer.}
{2154}{}{I'll have a bottle of the strong stuff.}

# Ferd_5_7a_1
{2180}{}{*He goes away and comes back with your drink and a bottle of beer for himself.*}
{2181}{}{Thanks.}

# Ferd_5_7a_2
{2210}{}{So tell me a little about yourself, }
{2211}{}{I come from a vault to the north.}
{2212}{}{Let's cut to the chase. Do you want to have sex with me?}

# Ferd_5_7a_3
{2240}{}{A vault, huh? I didn' know there was one that way. So what bring you to Crossroads?}
{2241}{}{I'm looking for some computer software which will help run the vault.}

# Ferd_5_7a_4
{2270}{}{I don' think there are too many of the computer geniuses to be found in Crossroads, }
{2271}{}{I've been told to look for a place that was owned by General Atomics International, before the Great War. Do you know it?}
{2272}{}{I know, I'm here for a different reason.}

# Ferd_5_7a_5a
{2300}{}{*He shakes his head.* I never hear of such a place. I will tell you as soon as I do, though.}

# Ferd_5_7a_5b
{2330}{}{So where do you think you will find your softwares for the computer?}

# Ferd_5_7b_01
{2360}{}{*Ferdinand raises an eyebrow in surprise.* Are you sure? This stuff Sara sell, it take the paint off the wall!}
{2361}{}{Absolutely sure. Are you afraid a woman could drink you under the table, Ferdinand?}
{2362}{}{I'll have some water instead, in that case.}
{2363}{}{I'll have a Nuka Cola instead, in that case.}
{2364}{}{I'll have a beer instead, in that case.}

# Ferd_5_7b_02
{2390}{}{*He gives a raucous laugh.* I like you, lady! You got the balls! Okay, this soun' like a challenge to me. *He goes up to the bar and comes back with a bottle of foul-looking spirits and two glasses.*}
{2391}{}{Now, this is what I call a date.}
{2392}{}{I've changed my mind, sorry. Can I get something else to drink instead?}

# Ferd_5_7b_03
{2420}{}{*Ferdinand spaces the two glasses between you and messily pours a massive shot into each. He takes a glass for himself and looks at you with a competitive grin.* Are you sure abou' this?}
{2421}{}{Of course. *Take a glass.* Your health.}
{2422}{}{Actually, no, sorry. Can I get something else to drink instead?}

# Ferd_5_7b_04
{2450}{}{In Mexico, we say, 'Salud!' *He raises the glass to his lips and slams the contents back in one practised motion.*}
{2451}{}{*Slam your drink back in one.*}
{2452}{}{I don't want to do this. Can I get something else to drink instead?}

# Ferd_5_7b_05
{2480}{}{*Ferdinand squeezes his eyes shut and growls as the liquor goes down.* A la madre! *He half-fills the two glasses again.* Okay, }
{2481}{}{, you wan' to go again?}
{2482}{}{Yes. *Take your glass and drink its contents in one.*}

# Ferd_5_7b_06
{2510}{}{*You and Ferdinand slam your liqour back simultaneously. He groans as if kicked in the stomach. After a few moments, when he speaks, his voice is hoarse.* Chingalo! That is the mother's milk. *He pours another two glasses uncertainly.* Again?}
{2511}{}{Again. *Take your glass and drink its contents in one.*}

# Ferd_5_7b_07
{2540}{}{*As one, your empty glasses slam loudly onto the table. Ferdinand breathes heavily and looks up at you in incredulity.* You... you are some woman, }
{2541}{}{Allow me. *Take the bottle and pour a drink for both you and Ferdinand.*}

# Ferd_5_7b_08
{2570}{}{*He looks at his glass unhappily, then lifts it shakily. He lifts his eyes to you and waits so that the two of you will drink together.*}
{2571}{}{*Take your glass and drink its contents in one.*}

# Ferd_5_7b_09
{2600}{}{*Ferdinand bangs his empty glass onto the table and pushes it away with a wince.* Enough! *He laughs.* I am getting too old for this sort of thing. Estoy hasta la madre! I will regret this tomorrow. }

# Ferd_5_7b_10
{2630}{}{*He looks up at you with a drunken, glaze-eyed grin.* You know, }
{2631}{}{, I love you the minute you come into the Explorers' tent.}

# Ferd_5_7b_11
{2660}{}{I do anything for you. Anything. I follow you to the ends of the earth.}
{2661}{}{Does that mean you'll leave Crossroads and come with me?}

# Ferd_5_7b_12
{2690}{}{Whatever you say, }
{2691}{}{. Your eyes, they are like jewels of the desert.}
{2692}{}{How do I know you won't change your mind tomorrow?}

# Ferd_5_7b_13
{2720}{}{Because I give you my word. On the grave of my mother. I never betray that.}
{2721}{}{Okay. I'll take you back to the Explorers' tent so you can get some rest. Then I'll come back for you in the morning.}

# Ferd_5_7b_8
{2750}{}{I think tha's a good idea. You want the water, the Nuka Cola, or the beer, instead?}

# Ferd_5_7b_9_1
{2780}{}{*The wickedly strong spirits hit your innards hard. All of a sudden, you cannot stand to have the taste of the liquor in your mouth and you feel incredibly nauseous.*}

# Ferd_5_7b_9_2
{2810}{}{*You stand up uneasily from the table and weave a drunken path to the entrance of the bar tent. You hear Ferdinand's voice as if from a long distance, asking you if you are all right.*}

# Ferd_5_7b_9_3
{2840}{}{*You put one hand on one of the bar tent's support poles and hang your head, which suddenly feels too heavy. After a few moments, you spray a torrent of vomit over the ground in front of your feet. Having seen this, the other bar patrons in the tent applaud and jeer at you.*}

# Ferd_5_7b_9_4
{2870}{}{*The last thing you remember is Ferdinand putting his arm around you and guiding you away from the bar tent.*}

# Ferd_5_7b_9_5
{2900}{}{*You wake up next morning in one of the Wasteland Explorers' spare beds. It's a single; Ferdinand is nowhere to be seen and did not take advantage of you whilst you were drunk.*}

# Ferd_5_7b_9_6
{2930}{}{*Crippled by a hangover, an unshakeable guilty sense of having embarrassed yourself in some irredeemable way, and a taste in your mouth like the bottom of a bird-cage, you emerge blinking and ashen faced from the Explorers' tent.*}
{2931}{}{- DONE -}

# Ferd_5_7c_1a
{2960}{}{*Ferdinand is taken aback and blinks in surprise.*}
{2961}{}{Well? Isn't that what you want?}

# Ferd_5_7c_2
{3020}{}{I'm sorry, Senorita, I just didn' expect you to be so... you know, forward.}
{3021}{}{We don't have to have sex if you don't want to.}
{3022}{}{I'm not usually; I just don't have any time to waste.}

# Ferd_5_7c_3a_1
{3050}{}{No, no, I do. I am a man an' you are a ver' beautiful lady. It's just... I would feel more comfor'able if we did this the ol' fashioned way, with some of the romance an' the courting.}
{3051}{}{We can do all of that stuff if you want.}

# Ferd_5_7c_3a_2
{3080}{}{*Ferdinand frowns.* I think the moment, it is spoiled, perhaps. Maybe this is not such a good idea.}
{3081}{}{We can still have sex, though, can't we?}
{3082}{}{I agree. Thanks for the drink, but I ought to be going.}

# Ferd_5_7c_3b_1
{3110}{}{*He shrugs.* Then I give the lady wha' she want. You want another drink before we leave?}
{3111}{}{Yes, please.}
{3112}{}{No, thanks. Let's go somewhere more private.}

# Ferd_5_7c_3b_2
{3140}{}{Which one: water, Nuka Cola, beer, or the strong booze?}

# Ferd_5_7c_3b_3
{3170}{}{*He comes back with your drink. As you drink it, Ferdinand moves closer to you. He begins kissing the side of your neck and carressing the inside of your leg.*}
{3171}{}{Okay, I'm finished. Let's go somewhere a little more private.}

# Ferd_5_7c_3b_4
{3200}{}{I have been waiting for this ever since I met you.}
{3201}{}{*Leave with Ferdinand.*}

# Ferd_5_7c_3b_5
{3230}{}{*You go back to Ferdinand's tent. The details of the rest of the night are best left to the player's imagination, although suffice to say that you were kept very busy. Next morning, having had very little sleep, you get up and say a fond farewell to Ferdinand.*}
{3231}{}{- LEAVE -}

# Ferd_6_01
{3260}{}{*Ferdinand has dressed smartly for the occasion again. You notice that he has managed to find another flower for you.*}
{3261}{}{Hello, again, Ferdinand.}

# Ferd_6_02
{3290}{}{Buenas noches, again, }
{3291}{}{. Jus' like last time, huh? You look even more beautiful. Here, I bring you another flower. I hope you like.}
{3292}{}{Thank you, I love flowers.}
{3293}{}{Another flower. I shall have to buy a vase at this rate.}

# Ferd_6_03a
{3320}{}{I am glad you like. These flowers, they are very hard to find. So, would you like for me to buy you a drink?}
{3321}{}{I would love one. Can you remind me what's on offer, though?}
{3322}{}{First flowers, then a drink? I'm getting deja vu.}
{3323}{}{Let's cut do the chase. Do you want to have sex with me?}

# Ferd_6_03b
{3350}{}{*He laughs a little too heartily.* Err... yeah. So, anyway, you wan' to have a drink?}

# Ferd_6_04
{3380}{}{*Ferdinand sighs.* I suppose being original is not my strong point. I would still like to buy you a drink if you wan' one, though.}
{3381}{}{Actually, I'd love one. Can you remind me what's on offer?}

# Ferd_6_05
{3410}{}{Still the same as last time: there is the water, the Nuka Cola, the beer, or the strong booze which I can get for you.}
{3411}{}{Never mind the drink; let's stop wasting time. Do you want to have sex with me?}

# Ferd_6_06
{3440}{}{*Ferdinand comes back with your drink. He looks like he has something important he wants to say.*}
{3441}{}{Thanks for the drink.}
{3442}{}{Have you got something on your mind?}

# Ferd_6_07
{3470}{}{, I have been doing a lot of thinking about you today.}
{3471}{}{Really?}

# Ferd_6_08
{3500}{}{I don' remember the last time I feel this way about someone. It is like it hurt inside when I am not with you, do you know wha' that feel like?}
{3501}{}{Yes, I do. Are you saying you're in love with me?}
{3502}{}{No, I don't. Are you sure you're not just ill?}

# Ferd_6_09a
{3530}{}{That is exactly what I am trying to say. }
{3531}{}{, I love you. I don' mean to put the pressure on you, but do you feel it, too?}
{3532}{}{I'm not sure. It's too early to say. I do think you're nice, though.}
{3533}{}{I do feel it. I think we're meant to be together.}

# Ferd_6_09b_1
{3560}{}{Only ill when you are not around. I am in love with you, }
{3561}{}{. Have you never been in love before?}
{3562}{}{Yes, of course.}
{3563}{}{No, never.}

# Ferd_6_09b_2a
{3590}{}{Then tell me the truth - do you fell the same way about me?}

# Ferd_6_09b_2b
{3620}{}{Never? For such a beautiful lady, that is strange. I must know, though, do you have any feelings for me at all?}
{3621}{}{I'm not sure. I do think you're nice, though.}
{3622}{}{I do have feelings for you. I think you may be my first love.}

# Ferd_6_10a_1
{3650}{}{Then we should show our love for each other like a man an' woman should, }
{3651}{}{. Let us not wait any longer; I think maybe I die if we do.}
{3652}{}{What, here?}
{3653}{}{Where shall we go?}

# Ferd_6_10a_2a
{3680}{}{No, of course not. We can get some privacy back at my tent. You wan' another drink before we leave?}
{3681}{}{No, let's go now.}
{3682}{}{Yes, I'd like another drink.}

# Ferd_6_10a_2b
{3710}{}{Let's go back to my tent. We can get some privacy there. You wan' another drink before we leave?}

# Ferd_9
{3740}{}{Si, ask me anything you want.}
