# Message file for sclnccmp.ssl
# Number of nodes: 9

{102}{}{The faded label next to the monitor seems to read "Mission Control".}

{150}{}{You have entered legitimate Mission Control Access Codes.}

# Node_002
{230}{}{Recovering from emergency shutdown... Performing hardware diagnostics... errors found.  Checking for local boot routine... found. Checking network connectivity... no connection found. Boot? Y/N}
{231}{}{[Yes]}
{232}{}{[No]}

# Node_003
{260}{}{The screen is just showing static. The power is off.}
{261}{}{[Leave and find a way to restore power]}

# Node_004
{290}{}{[The computer hums and grunts] ...Boot successful. Login?}
{291}{}{[Login as Dr. Willem Clark]}
{292}{}{[Administrator Override]}
{293}{}{[Login as Guest]}
{294}{}{[Hack the Mainframe]}
{295}{}{[Exit]}
{296}{}{[Login as Hadrian Voigh]}
{297}{}{[Login as Robert Taylor]}

# Node_004a
{320}{}{Login?}
{321}{}{[Login as Administrator]}

# Node_005
{350}{}{Welcome to Bloomfield Space Center Network. Command?}
{351}{}{[Workstation Details]}
{352}{}{[Enter Access Codes]}
{353}{}{[Logoff]}
{354}{}{[Hack Access Codes]}
{355}{}{[Mission Control Status]}

# Node_006
{380}{}{Workstation ID: Mission Control Access Codes}
{381}{}{[Back]}

# Node_011
{410}{}{Guest login refused. This station is for registered use only. Last Login: 00PJ@BSCnet:HQ}

# Node007
{440}{}{Access denied.}

# Node008
{470}{}{Hermes-13 flight data unavailable. NOT OK. Hermes-14 flight data unavailable. NOT OK.}
{471}{}{Hermes-13 flight data unavailable. NOT OK.}
{472}{}{Hermes-13 flight data available. OK.}

{473}{}{Hermes-13 engine fault detected. NOT OK. Hermes-14 engine in running state. OK.}
{474}{}{Hermes-13 engine fault detected. NOT OK.}
{475}{}{Hermes-13 engine in running state. OK.}

{476}{}{Hermes-13 fuel tanks empty. NOT OK. Hermes-14 fuel tanks 52% full. WARNING! ONE-WAY TRIP.}
{477}{}{Hermes-13 fuel tanks empty. NOT OK.}
{478}{}{Hermes-13 fuel tanks 49% full. WARNING! ONE-WAY TRIP.}

{479}{}{Mission Control Launch Codes absent. NOT OK. Docking Clamp Control unreachable at Launchpad 01. Please perform an onsite check. NOT OK.}

{480}{}{[Continue]}
{481}{}{[Copy Hermes-14 flight data]}
{482}{}{[Activate Repair Bots]}
