# Message file for scclamp.ssl
# Number of nodes: 3

{102}{}{The faded label next to the monitors appears to read, "Docking Clamp Control."}
{103}{}{You have successfully installed the Docking Clamp Chip.}

# Node_000
{200}{}{**WARNING** Docking clamp chip not detected. Would you like more information? Y/N}
{201}{}{[Yes]}
{202}{}{[No]}
{203}{}{[Insert the docking clamp chip into the computer]}

# Node_001
{230}{}{If the docking clamps aren't released, the space rocket won't launch and will likely explode on the launchpad.}
{231}{}{[Back]}
{232}{}{[Exit]}

# Node_002
{260}{}{[The computer hums, then whirs] Docking clamp release system is fully operational!}
