# Message file for tbbatt.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You come across a soldier clad in unfamiliar advanced armor.}
{101}{}{You spot a soldier in an enigmatic suit of advanced armor, adorned with an unfamiliar insignia on the breastplate.}
{102}{}{The combat armor they're donning boasts impressive features like gas and radiation filtration, along with enhanced night vision goggles.}

# Node 0 [Floats]
{200}{}{Talk to the Sarge.}
