# Message file for seedtrk2.ssl
# Number of nodes: 1

{150}{}{You successfully hauled the rocket fuel from Fort Abandon to Bloomfield Space Center.}

# Node001
{200}{}{[The truck stands ready to roll out.]}
{201}{}{[Head out with Eddie. Transport the rocket fuel from Fort Abandon to Bloomfield Space Center with Eddie behind the wheel.]}
{202}{}{[Use the key to start up the truck. Transport the rocket fuel from Fort Abandon to Bloomfield Space Center yourself.]}
{203}{}{[Steal the truck. Hotwire it and transport the rocket fuel from Fort Abandon to Bloomfield Space Center yourself.]}
{204}{}{[Leave the truck alone.]}
