# Message file for seeddie.ssl
# Number of nodes: 10

{100}{}{You see a trucker.}
{101}{}{You see Eddie.}
{102}{}{He smells of moonshine.}

# Node001
{200}{}{Ah, hell. Help me, friend. Broke down right here at the worst possible time. I ain't got the parts nor skills to fix it, and those damn vermin are sniffing around.}
{201}{}{Vermin, huh? Well, lucky for you, I'm good with a wrench. I could take a look at your truck and see if I can patch it up.}
{202}{}{What are you doing out there all by yourself?}
{203}{}{Beat it, bum. The truck is mine.}
{204}{}{Whatever. I have to go.}
{205}{}{Me fix!}
{206}{}{Ed alone?}
{207}{}{Me take truk!}
{208}{}{Me go.}

# Node002
{230}{}{You'd do that for ol' Eddie? Well, I'll be damned. You're a lifesaver, friend. Just be careful, those vermin are dangerous.}
{231}{}{No worries, Eddie. I've dealt with worse.}
{232}{}{Me do eeeeeet.}

# Node003
{260}{}{Did you fix the truck?}
{261}{}{Alright, Eddie, she should run like a charm now.}
{262}{}{No, not yet.}
{263}{}{Nghn.}

# Node004
{290}{}{[Slapping you on the back.] Damn, you're one hell of a partner! I owe you big time, friend. Now, let's get this truck rolling again.}
{291}{}{No need for thanks, Eddie. Just doing what needs to be done. You take care now, and watch out for those vermin on the road.}
{292}{}{No need for thanks, Eddie. Just doing what needs to be done. You take care now, and say hello to Helen and the kids. And watch out for those vermin on the road.}
{293}{}{Sorry, I'm keeping the truck.}
{294}{}{Thank Ed.}
{295}{}{Thank Ed. Say hi to Hell and six.}
{296}{}{Truk now for me.}
{297}{}{How about you give me something in return?}
{298}{}{Ed give shiny!}

# Node005
{320}{}{Hello there, friend. What can Eddie Galenski do for you?}
{321}{}{Eddie, the truck's humming like a radroach with a new pair of legs. I got another proposition for you, though. You up for it?}
{322}{}{Nothing, Eddie. just saying hi.}
{323}{}{Give me the keys, Eddie! The truck is mine.}
{324}{}{Truk fix. Me need Ed help.}
{325}{}{Nghr.}
{326}{}{Give key! Give truk!}

# Node006
{350}{}{[Wiping his hands with a rag] Shoot, partner. I owe you big time, so if there's anything I can do to repay the favor, I'm all ears.}
{351}{}{Well, you see, there's this little matter of some rocket fuel. Fort Abandon's got a stash, and Bloomfield Space Center needs it for, well, my space trip.}
{352}{}{Bring fort fuel to rocket! Me go to space!}

# Node007
{380}{}{[Raising an eyebrow] Rocket fuel? Space trip? Ain't that a bit out of our league?}
{381}{}{Yeah, it might sound like pre-war space stuff, but it's no joke. I'm trying to launch the rocket, go up there, and I need that fuel. Problem is, I could use help.}
{382}{}{Me fly to stars! Help, Ed!}

# Node008
{410}{}{Rocket fuel, huh? Hell, why not? I've done crazier things in my time. Count me in. What's the plan?}
{411}{}{I figure, with your truck, we can haul the fuel. We just need to be quick about it.}
{412}{}{Truk take fuel. We fast!}

# Node009
{440}{}{Heh, quick ain't exactly my specialty, but I'd like to see you fly into space. Hope you packed a space suit, I bet you'll need it! I can sell you the one I found, if you want. Alright partner, let's do it. When do we head out?}
{441}{}{Soon as possible. The longer we wait, the more chances the whole thing fizzles out. I'll wait for you in the truck.}
{442}{}{Let roll, Ed! Me wait in truk.}

# Node010
{470}{}{Well, partner, you see, I got this idea. With all the wilderness out here, folks need a way to navigate, find supplies, and maybe settle down. I figure mapping out the roads and gas stations could be a big help.}
{471}{}{Good luck with that. So long, Eddie.}
{472}{}{Sorry, but I can put that truck to better use.}
{473}{}{So you need help fixing the truck?}
{474}{}{Gud. Bye-bye.}
{475}{}{Me drive better truk. You bad drive.}
{476}{}{Me fix truk.}

# Node011
{500}{}{How about we trade, and I give you a nice discount?}
{501}{}{Sure, show me what you have.}
{502}{}{'K.}
{503}{}{Not interested.}
{504}{}{Nah.}

# Node012
{530}{}{Thank you for your business, partner.}
{531}{}{[END]}
