# Message file for segoris.ssl
# Number of nodes: 21

{100}{}{You see a mysterious figure in a hooded robe.}
{101}{}{You see Goris, the enigmatic scholar.}
{102}{}{Before you stands a humanoid figure cloaked in a long-sleeved, hooded robe. His posture is unnatural.}

{105}{}{The talking deathclaw subspecies becomes extinct.}

# Node001
{200}{}{Greetings, traveler. I am Goris, the scholar. Welcome to my home. If you share tales of your adventures, I'll gladly answer any questions you may have.}
{201}{}{Greetings, Goris. I am }
{202}{}{. Is *this* your home?}
{203}{}{Me }
{204}{}{.}
{205}{}{Me go.}
{206}{}{Why should I comply with your request? How will you enforce it?}
{207}{}{I have some questions for you.}
{208}{}{Being a scholar is quite an accomplishment in these times.}
{209}{}{How boring. Nonetheless, I require more information.}
{210}{}{Apologies, but I must depart.}
{211}{}{And I am }
{212}{}{, royalty unlike any other. Bow down, peasant.}

# Node002
{230}{}{What knowledge can I impart to you?}
{231}{}{What brings you to this place?}
{232}{}{How long have you resided here?}
{233}{}{What is the story behind the billiard ball you have there?}
{234}{}{Are you human? I can only see reflective eyes beneath your robe, and your stance is rather unusual.}
{235}{}{You mentioned an interest in hearing about my adventures. How about joining me instead? Experiencing firsthand is far more captivating than mere tales.}
{236}{}{That will be all. Farewell.}

# Node003
{260}{}{Deceiver.}
{261}{}{[END]}

# Node004
{290}{}{I have answered your inquiries. Now, it's time for the adventure stories you promised.}
{291}{}{Certainly. It's a pleasure to engage in conversation with you.}
{292}{}{Promise? What promise?}
{293}{}{Certainly.}

# Node005
{320}{}{Indeed, I'm renting a room here. The janitors are nice enough to let me stay here as long as I want to. I'm looking for an old friend of mine.}
{321}{}{Who is this friend?}
{322}{}{Only a true friend would do something like that!}
{323}{}{You seem overly attached to this friend. Perhaps it's time to move on.}

# Node006
{350}{}{Without my friend, I would have never ventured out from my former home and explored the wasteland. I would likely have met the same fate as my pack. And I wouldn't have had the opportunity to save the world.}
{351}{}{That sounds like the biggest crock of shit I've ever heard in my life!}
{352}{}{What an extraordinary friendship! I wonder if one day I'll have the chance to save the world as well. We can all dream, right?}
{353}{}{Hmm... Tell me something else.}

# Node007
{380}{}{Your intellect appears to be severely lacking. I shall assist you to the best of my abilities, my simple-minded friend.}
{381}{}{Ball? Eight-eight!}
{382}{}{Big head!}
{383}{}{You mutie?}

# Node008
{410}{}{Very well, your loss.}
{411}{}{Loser.}

# Node009
{440}{}{Thank you, your kind words are appreciated. True friendships are scarce in this era, making our past association all the more miraculous. However, the passage of time has scattered our group, leaving us separated.}
{441}{}{[CONTINUE]}

# Node010
{470}{}{Thank you. There is little to study in this vicinity, aside from the natural surroundings and customers. Nevertheless, I find solace in this place, and I have grown too old for extensive travels.}
{471}{}{I understand. Tell me something else then.}
{472}{}{That is regrettable. I could have used some assistance. Farewell, then.}
{473}{}{Come now, Goris! Together, we could conquer the wasteland. I can see that you have witnessed your fair share of action, with your hunter-like gaze from beneath the robe.}

# Node011
{500}{}{Indeed, this is my home. I'm renting a room here.}

# Node012
{530}{}{For nearly a decade, I have resided here. It was not my intention to settle permanently, but circumstances led to our car breaking down. My friend set out in search of replacement parts, but alas, never returned.}

# Node013
{560}{}{This funny ball belonged to my friend. Many years have passed since he found it in New Reno, west of here. I like it and so do the customers.}
{561}{}{May I take a look at it?}
{562}{}{Interesting. Tell me something else.}
{563}{}{Give ball!}
{564}{}{Oki.}

# Node014
{590}{}{My nature is of no importance. Fear not, for I harbor no ill intentions towards you. Ultimately, I am but one of the wasteland's children.}
{591}{}{Very well, if that is your assurance. I shall take my leave.}
{592}{}{Hrrrm... now I'm even more suspicious of you! Prepare to meet your maker, dirty mutant!}
{593}{}{'K. Me go.}
{594}{}{Hrrrm... me no trust! Evil. Die. Now!}

# Node015
{620}{}{Well, actually... nevermind that. Let's just say my friend was a badass who kicked some major ass and drove around in a fast car until it broke down. Ah, but now I'm getting all sentimental.}

# Node016
{650}{}{Thank you. That was truly wonderful. Well... you know...}
{651}{}{Yes?}
{652}{}{No, I'm afraid I don't.}

# Node017
{679}{}{You strike me as someone who would have more use for this ball than me. Deep down, I know my friend will not return - years have passed since that ill-fated journey to find the legendary Chryslus Motors mega-factory. Hence, I implore you to accept this... Wait, where is my ball? Thief!}
{680}{}{You strike me as someone who would have more use for this ball than me. Deep down, I know my friend will not return - years have passed since that ill-fated journey to find the legendary Chryslus Motors mega-factory. Therefore, I bestow upon you this  ball I have safeguarded. My friend would be happy knowing it might be of help to you.}
{681}{}{Thank you, Goris. Let's give it a proper shake!}
{682}{}{Hah, is it my birthday today? Thanks!}
{683}{}{Thank you, but I shall decline. I prefer to rely on my skills, not gimmicks.}
{684}{}{Whoops!}
{685}{}{Me shake best!}
{686}{}{Me happy! MAGIK EI BAL!}
{687}{}{No want! No no no.}

# Node018
{710}{}{Hmm.. you are dumber than this ball. But...}

# Node019
{740}{}{Heh, thank you. You have a good eye and seem cool. But I'm done with traveling. This is my lair.. my home. I enjoy living here, in this oasis.}
{741}{}{As you wish. I shall not trouble you further. Farewell.}
{742}{}{Well, I still want to at least see the face beneath the robe. Allow me to...}

# Node020
{770}{}{Do not touch me!}
{771}{}{Whoa!}

# Node021
{800}{}{Enjoy, my friend. May your journeys be safe and fulfilling.}

{900}{}{Greetings once more. I trust you are faring well, my friend.}
{901}{}{I have nothing further to convey to you. Cease your interruptions.}
{902}{}{I warned you against persisting. Perhaps violence is the sole language you comprehend.}
{903}{}{You stole my ball! I trusted you!}
