# Message file for sekazuma.ssl
# Number of nodes: 4
# Grammar pass done

{100}{}{You see a man with a distinctive white mohawk and dressed in a striking red and black jumpsuit.}
{101}{}{You see Kazuma Spike.}

# Node001
{200}{}{[As he looks around, he appears dazed and disoriented.] This is nothing like the future I was promised. It's as bad as the company that manufactures these shelters.}
{201}{}{Who are you?}
{202}{}{You had it easy, kid. I had to escape a prison run by deranged robots.}
{203}{}{Why does your dog appear to be a ghost?}
{204}{}{If you say so. Goodbye.}
{205}{}{Who you?}
{206}{}{Me run from robo-prison!}
{207}{}{Dogo ghost!}
{208}{}{Oki doki. Bye!}

# Node002
{230}{}{Kazuma Spike, known as a thief to some and a hero to others. One of my recent memories involves stealing a G.E.C.K. unit from my employer, grabbing Milky, and making a swift escape to the nearest Pulowski. Right now, I feel like my late uncle Kitano. If it weren't for that G.E.C.K., I'd be dead like the rest.}

# Node003
{260}{}{So, you're a criminal as well?}

# Node004
{290}{}{Hah! Milky isn't actually a ghost. He's wearing a custom-made Stealth Boy collar. It's another item I borrowed, heh. Milky can turn fully invisible and is projecting himself by manipulating your brain waves. Pretty slick tech, right?}
