# Message file for tbabe.ssl
# Number of nodes: 23
# Grammar pass done

{100}{}{You see a weary old man. He's not wearing his prison jumpsuit.}
{101}{}{You see Brother Abraham, yawning occasionally, seemingly disinterested in his surroundings.}
{102}{}{This man seems out of place here. He should be working in the factory, but he's not.}

{105}{}{Well... well, what have we here? Abe, you're hopeless.}
{106}{}{Oh crap... you forgot to block the doorway.}

{200}{}{You will face divine retribution for your actions against me, a holy man!}
{201}{}{Ha ha! I bet you gained nothing from that.}
{202}{}{And I allowed you to enter my cell...}
{203}{}{Go consume some cyanide.}

{230}{}{...I don't want to work! Mommy, please...}
{231}{}{Ahh... AH! Leave me alone... Shoo!}
{232}{}{...Just five more minutes...}
{233}{}{Aaaah... Hrrrr... Hrrrrr...}
{234}{}{*Zzzzzz*}
{235}{}{...Let's discuss God...}
{236}{}{*fart*}
{237}{}{*snore*}

# starter_1
{260}{}{[He's snoring softly. You notice a Vault-Tec factory access card hanging around his neck, bearing the name "Brother Abraham.".]}
{261}{}{Hey old man, are you sleeping? Wake up!}
{262}{}{Get up from your slumber!}
{263}{}{[Leave him be.]}

# starter_2
{290}{}{[Familiar snoring fills the cell.]}
{291}{}{Rise and shine!}
{292}{}{Wakey-wakey!}

# questions_menu
{320}{}{*yawn*}
{321}{}{Were you supposed to be working instead of napping?}
{322}{}{How do you manage to avoid work?}
{323}{}{So, how do you like your job here?}
{324}{}{Oh, I almost forgot, they're showing "Gone with the Wind" tonight, a classic from the 20th century. I should check it out and see what the fuss is about.}
{325}{}{You sleepy?}
{326}{}{You sleep all day how? Tell.}
{327}{}{You like? Work?}
{328}{}{Bye!}

# garry_awakens
{350}{}{[He slowly awakens..]}
{351}{}{Start talking, slob, or you'll find my fists on your face.}
{352}{}{Just making sure. See you later.}
{353}{}{Hmm. Nice spot you've got here.}
{354}{}{You sleep and no work?}
{355}{}{Talk or eat fists!}
{356}{}{Ha ha. Bye.}
{357}{}{Me like you, good place.}

# shh_everythings_good
{380}{}{Wha-where-oh, it's you! Everything's fine, you know, everything's fine.*Zzzz...*}
{381}{}{How's work going?}
{382}{}{Have you been productive?}
{383}{}{Alright then, just checking. See you later, old man.}
{384}{}{You work?}
{385}{}{Blurgh! Me go.}
{386}{}{You worked a lot?}

# want_me_to_say_someting
{410}{}{Oh, you want me to say something?}
{411}{}{Well, you can start by telling me about this cozy cell of yours.}
{412}{}{Nah, keep sleeping. I have to go anyway.}
{413}{}{Talky or fisty!}
{414}{}{Your cell? I like.}
{415}{}{Me go.}

# so_hostile
{440}{}{Why so hostile? Relax, my friend.}
{441}{}{While other prisoners are toiling away in the factories, you're getting paid for, what, sleeping? And where is your jumpsuit?}
{442}{}{Tell me how you manage to get away with it, and I might let you off the hook.}
{443}{}{Enjoy your beauty sleep while it lasts because when the robots find out, things won't be pleasant for you. Goodbye.}
{444}{}{You bad! You sleepy, you get caps! Where jump? Where suit?}
{445}{}{Tell how sleepy and me no beat you.}
{446}{}{Me go.}

# no_place_is_safe
{470}{}{*Yawn* Oh, hehe, yes, unfortunately, no place in this brig is safe. Brother Maurice is always watching, except when he's busy emptying his "holy" water flask.}
{471}{}{How do you manage to get away with it?}
{472}{}{Does Brother Maurice know about your hiding spot?}
{473}{}{Not a bad setup you have here, but I have to go.}
{474}{}{Tell }
{475}{}{ how to sleep.}
{476}{}{Bro Mauri know you sleep?}
{477}{}{Me like sleep, but me go work.}

# i_been_working_hard
{500}{}{Thank you. I've been working hard, [Chuckles.], to make this "retreat" worth my while.}
{501}{}{*yawn* Sleep is catching up to me too, and I'm too lazy to go back to my cell. Mind if I shut my eyes for 5 minutes here?}
{502}{}{I'll see you around.}
{503}{}{*yawn* Sleepy too!}

# make_yourself_comfy
{530}{}{Make yourself comfortable.}
{531}{}{[Sleep.]}
{532}{}{Maybe some other time. I'll leave you to it.}
{533}{}{[Sleep.]}
{534}{}{You sleep, and I'll be on my way.}

# bigger_picture
{560}{}{Ah that, I do stand out, don't I? Well, I initially became lax, and the result was a "gradual weight gain." Consequently, my jumpsuit started feeling snug. Nevertheless, let's contemplate the bigger picture.}
{561}{}{What bigger picture?}
{562}{}{Bigger picture? Man, you must be out of your mind. I'm leaving.}
{563}{}{Picture?}
{564}{}{Me no get it. }
{565}{}{ dizzy. Me go.}

# getting_away_with_murder
{590}{}{I just hide out here in my cozy cell for most of my shift, and if Maurice catches me sleeping, he gets angry, of course. But he's always angry anyway.}
{591}{}{Don't you worry about getting fired?}
{592}{}{*yawn* Can I take a nap too?}
{593}{}{Robots fire you?}
{594}{}{*yawn*  Me sleepy now.}
{595}{}{Big balls. Me go.}
{596}{}{You've got some cojones, my man. Anyway, good luck with your little operation.}

# easy_target
{620}{}{Does anyone here work because they enjoy it? Your needs make you an easy target for exploitation. The robots know this and persuade prisoners like you and me to work in the factories.}
{621}{}{Go on. Tell me more.}
{622}{}{I don't need a lecture on Tibbets' socio-political climate right now. What I really want is some rest from it all.}
{623}{}{Before you get all heated up about your causes, let me ask you something else.}
{624}{}{Look, a roach! Oh, yeah... Hugh... Me hear Abe.}
{625}{}{Shut it. Me go zzzz now.}
{626}{}{Need more info.}

# works_you_into_the_ground
{650}{}{They work you into the ground and get their tech like that during the last, what, 180 years?}
{651}{}{Yeah? So?}
{652}{}{What's your point?}
{653}{}{Huh?}
{654}{}{Point?}

# proud_of_it
{680}{}{I sleep here, and I'm proud of it, brother. This is my small resistance against the robots and that hellspawn, the Warden. Plus, I stole some materials to make my cell more comfortable, as you can see, heh.}
{681}{}{I sleep here, and I'm proud of it, sister. This is my small resistance against the robots and that hellspawn, the Warden. Plus, I stole some materials to make my cell more comfortable, as you can see, heh.}
{682}{}{Aren't you afraid of getting fired?}
{683}{}{I admire your cause, man. Can I join the revolution too?}
{684}{}{We'll see how the robots react to this. Later.}
{685}{}{Robo-men no fire you?}
{686}{}{Hah! Me make zzzs too.}
{687}{}{Me tell robo-men now.}

# it_be_more_expensive_to_find_somebody_else
{710}{}{Meh, for what they pay me, it would be more expensive to look for and train someone else. If they catch me, I only get half a shift's pay.}
{711}{}{Tell me something else.}
{712}{}{Alright. See you later.}
{713}{}{Me have questions.}
{714}{}{'K, Abe. Bye.}

# work
{740}{}{Work?}
{741}{}{Just kidding.}
{742}{}{Never mind. I'll catch you later.}
{743}{}{Me joke you.}
{744}{}{Me go now.}

# no_not_really
{770}{}{No.}
{771}{}{Well, you should be. "Thou shall not giveth to the pleasures of the flesh," He said... I think.}
{772}{}{Yeah? We'll see how long you'll last when the robots find out.}
{773}{}{I'd take a nap, but something else bugs me right now.}
{774}{}{God tell you no, but you sleep?}
{775}{}{Me tell robo-men now.}
{776}{}{Need questions and answers.}

# got_me
{800}{}{[Chuckles.] Got me!}
{801}{}{Mind if I hide out here?}
{802}{}{Me need zzzzs.}

# sure_thing
{830}{}{Sure thing, make yourself at home.}
{831}{}{[Rest.]}
