# Message file for tbangela.ssl
# Number of nodes: 103
# Grammar pass done

{100}{}{You notice an incredibly attractive young woman.}
{101}{}{Angela appears relaxed and comfortable.}
{102}{}{She seems to be dealing with unwanted attention from some male patrons at the bar.}

# Angela floats these lines under default circumstances.
{200}{}{I could see that was going to spill over.}
{201}{}{Great, now it'll take ages to clean up.}
{202}{}{No, I won't do anything like that for money, no matter how many times you ask.}
{203}{}{*Sigh* Robots...}
{204}{}{Who was that jerk who just pinched me?}
{205}{}{Don't you fellas ever think about anything else?}
{206}{}{It's like the worst hangover I've ever had, but worse.}
{207}{}{Gossip spreads faster than light.}
{208}{}{I really need to get out of here.}

# Angela floats these lines if the local variable Angela_Temper =< -3 and the PC tries to speak to her directly.
{260}{}{I have nothing more to say to you.}
{261}{}{What makes you think I want any more of your abuse?}
{262}{}{Stay away from me, or I'll have my father deal with you.}
{263}{}{Yeah, I can see you there.}
{264}{}{Talk to the hand.}
{265}{}{The face ain't listenin'.}

# Angela floats these lines if she PC uses tooltip 'get out of my way' to make her move.
{440}{}{Oops, sorry, honey. I didn't mean to block your path.}
{441}{}{Where should I stand then? Over here?}
{442}{}{Fineeeeee.}
{443}{}{Oops!}
{444}{}{I'm sure you could have squeezed past me. *Giggle*}
{445}{}{Oh, I didn't realize you were trying to pass through here.}

# Angela_1a_1
{650}{}{Hey there, welcome to the Atom.}
{651}{}{Hi, I'm }
{652}{}{. And you are?}
{653}{}{What do you do around here?}
{654}{}{I'm }
{655}{}{. Who you?}
{656}{}{What you do here?}

# Angela_1a_2F_1a
{680}{}{I'm Angela. It's nice to meet you, }
{681}{}{. I don't recall seeing you here before. Are you new?}
{682}{}{I come from a Vault to the north, just getting to know this place.}
{683}{}{A little bit of this and that. Can I ask you about something else?}
{684}{}{}
{685}{}{ from Vault 31.}
{686}{}{ traveler.}
{687}{}{I'd like to ask you about something else.}

# Angela_1a_2F_1b
{710}{}{I'm a regular here, a barfly! Haha! [She laughs pleasantly] I chat with the patrons, have fun, you know, that sort of thing. So, where are you from?}
{711}{}{I'm from outside; I'm just getting to know the place.}

# Angela_1a_2F_2
{740}{}{Outside, huh? You mean like one of those towns? Sorry for my ignorance, but I was born here. I've never seen a real town, only those in movies. By the way, I really like that scar you have. It adds character to your look.}
{741}{}{Can I ask you about something else?}

# Angela_1a_2Ma_1
{770}{}{I'm Angela, Robb's daughter.}
{771}{}{Who is Robb?}
{772}{}{Who Robb?}

# Angela_1a_2Ma_2
{800}{}{Daddy works for the Sheriff. You can find him here sometimes if you want to speak to him.}
{801}{}{What else can you tell me about him?}
{802}{}{Where is your mother?}
{803}{}{Thanks, I'll do that. Goodbye.}
{804}{}{Tell more 'bout Robb.}
{805}{}{Where momma?}
{806}{}{[Leave]}

# Angela_1a_2Mb_1
{830}{}{Oh, you know, the usual barfly stuff. Wasting time, having fun.}
{831}{}{Can you buy me a drink?}
{832}{}{What's your name?}
{833}{}{What's a fine piece of ass such as yourself doing in a dump like this?}
{834}{}{Cool. Sorry to bother you.}
{835}{}{What your name?}
{836}{}{I like you, pretty girl.}

# Angela_1a_2Mb_2B_1
{860}{}{[She looks at you as if she gets comments like those all the time.] Please, sir.}
{861}{}{Not before you give me a kiss with those sweet-as-candy red lips of yours.}
{862}{}{Whatever.}
{863}{}{Me touch pretty girl.}
{864}{}{Me go. Me sad.}

# Angela_1a_2Mb_2B_2
{890}{}{[She manages to keep smiling, but her eyes show signs of anger.] Sir, if you don't stop, I'm going to have to call my father out here.}
{891}{}{I'll happily step over his body and everyone else's in here just to get to you.}
{892}{}{Me no care. }
{893}{}{ want pretty girl.}
{894}{}{No duddy. Me run.}

# Angela_1a_2Mb_2B_3
{920}{}{DADDY! We got a troublemakeeeeeeeeer here! [She points at you.]}
{921}{}{Fuck!}

# Angela_1a_2Mc_1
{950}{}{Heh, the Atom ain't that kinda place. Robots monitor everything so you gotta self-service. If you want a drink, speak to the bartender behind the bar.}
{951}{}{I thought you said you were a barfly.}
{952}{}{Okay, sorry to bother you.}

# Angela_1a_2Mc_2
{980}{}{Being a barfly means having fun here all the time, you know? I'm not an employee or anything, although it might seem that way. The bar is over there. [She hooks a thumb in the direction of the bar]}

# Angela_1b_F
{1010}{}{Hey, }
{1011}{}{! I thought I'd never see you 'round here again.}
{1012}{}{Why do you say that?}
{1013}{}{I know someone who's interested in going on a date with you.}
{1014}{}{Your father asked me to give you some tips on dating men.}
{1015}{}{What can you tell me about this place and what you do here?}
{1016}{}{It slipped my mind. Goodbye for now.}

# Angela_1b_M
{1040}{}{Hey.}

# Angela_1c_1
{1070}{}{You again!}
{1071}{}{Is something the matter?}

# Angela_1c_2
{1100}{}{I don't know, it depends on whether you think everyone in Tibbets sniggering at you and calling you names behind your back is bad or not.}
{1101}{}{Let me guess, you're being sarcastic.}
{1102}{}{That's happening to you?}

# Angela_1c_3
{1130}{}{Well, duh! Do you really think so?}
{1131}{}{What are they saying about you?}

# Angela_1c_4
{1160}{}{[Angela blushes and folds her arms before continuing.] Weirdo. Crazy. Bitch. You name it. All thanks to you.}
{1161}{}{I had no idea Tibbets was so prejudiced.}
{1162}{}{What's it got to do with me?}

# Angela_1c_5a
{1190}{}{Yeah, well, where you come from, it might be okay for girls to be like I am. But not here.}

# Angela_1c_5b_1
{1220}{}{Don't play innocent with me! You're the only person who knew what I'm like. I thought I could trust you. You just went and ratted on me to the first person you spoke to!}
{1221}{}{It wasn't like that, I promise.}
{1222}{}{You shouldn't be ashamed of who you are, no matter how others respond.}
{1223}{}{Welcome to the real world, Angela. The only person you can trust is yourself.}

# Angela_1c_5b_2a
{1250}{}{What difference does it make? My life is ruined here now. The only way my daddy can look me in the eye is by telling himself that the rumors are lies.}
{1251}{}{What do you plan to do?}

# Angela_1c_5b_2b
{1280}{}{Oh, sure. Were you born yesterday? I mean, do you have any idea what life is like in an ass-end-of-the-wastes prison like this? I can't figure out if you're a bastard or just plain dumb.}
{1281}{}{Oh, sure. Were you born yesterday? I mean, do you have any idea what life is like in an ass-end-of-the-wastes prison like this? I can't figure out if you're a bitch or just plain dumb.}
{1282}{}{I certainly didn't mean for you to be hurt like this.}

# Angela_1c_5b_2B_1
{1310}{}{Oh, right. So I'm supposed to be *grateful* for the lesson?}
{1311}{}{Yes, but this one's free of charge.}
{1312}{}{What doesn't kill you makes you stronger. Remember that.}

# Angela_1c_5b_2B_2
{1340}{}{GET THE FUCK OUT OF HERE! I *never* want to see you again!}
{1341}{}{And now the final lesson. Never shout at someone as crazy as me. [Draw weapon]}

# Angela_1c_6
{1370}{}{I'm going to leave. I don't know where I'm going; I just have to get away from here.}
{1371}{}{When are you leaving?}
{1372}{}{Maybe you should come with me.}

# Angela_1c_7a_1
{1400}{}{Like I'm going to tell a blabbermouth like you. I don't want the whole prison knowing what I'm doing.}
{1401}{}{[CONTINUE]}

# Angela_1c_7a_2
{1430}{}{God damn it! I'm doing it again! Why did I even tell you I'm leaving? I mean, who the hell are you, anyway?}

# Angela_1c_7b_1
{1460}{}{[She snorts] You're just one surprise after another. Why the hell should I come with you?}
{1461}{}{I could use another pair of hands. You'd be safer with me too.}
{1462}{}{Because, Angela... I think, no, I know... I want to be with you.}

# Angela_1c_7b_2F_1
{1490}{}{[Her eyes widen.] What do you mean?}
{1491}{}{Don't you get it, Angela? I love you, and I think you feel the same way. That's why you told me what you did.}
{1492}{}{Forget it. The offer still stands, though. You're welcome to join me if you want.}

# Angela_1c_7b_2F_2
{1520}{}{Oh my god. I had no idea. It makes so much sense, though.}

# Angela_1c_7b_2F_3a
{1550}{}{I'm sorry, though, I just don't feel the same way about you as you do about me.}
{1551}{}{I think I'd better leave, then. Goodbye.}

# Angela_1c_7b_2F_3b_1
{1580}{}{[Angela moves closer to you until your mouths are almost touching.] Show me.}
{1581}{}{[Go to bed with Angela.]}

# Angela_1c_7b_2F_3b_2
{1610}{}{[Angela helps you get dressed.] That was... I don't know how to describe it.}
{1611}{}{Are you coming with me, then?}

# Angela_1c_7b_2N_1
{1640}{}{Hold on. Let me get this straight. You want me to become a fugitive, ruin my life, and you expect me to want to go around with you?}
{1641}{}{You can look at it like that if you want.}
{1642}{}{You made the decision to leave; I'm just offering you protection and companionship.}

# Angela_1c_7b_2N_2
{1670}{}{Okay, let me put this simply so even you can understand it: not if you were the last person on this whole goddamn planet.}
{1671}{}{Suit yourself. Goodbye.}

# Angela_2a_1
{1700}{}{Oh. [She doesn't seem too keen on the idea.] Who's that, then?}
{1701}{}{Magik.}
{1702}{}{Croz.}
{1703}{}{Gabrielle. Except not really, she just wants to be friends.}
{1704}{}{Aldo.}
{1705}{}{Me.}
{1706}{}{Forget I said anything. Goodbye.}

# Angela_2a_2a_1
{1730}{}{Magik? Heh. I shoulda guessed. Listen, perhaps you should be let in on a little family joke. Magik never stops hitting on me; there ain't no way I'm ever going to date him, though. Nuh-uh.}
{1731}{}{Magik hits you?}
{1732}{}{Are you dating someone else?}
{1733}{}{Perhaps I should ask you about something else.}
{1734}{}{I'd better leave you to it. Goodbye.}

# Angela_2a_2a_2
{1760}{}{What? No, you dolt, he never stops hitting *on* me. He never stops trying to pick me up, like on a date.}

# Angela_2a_2b_1
{1790}{}{Croz? [Her face twists in disgust] Eww. What ever made you think I'd be interested in *him*?}
{1791}{}{He seems very keen on you.}

# Angela_2a_2b_2
{1820}{}{Sure, keen like a dog in heat. Trust me, stranger, you've got work to do on your match-making skills.}
{1821}{}{I take it you're not interested in Croz, then?}

# Angela_2a_2b_3
{1850}{}{Uh, yeah, you sure as hell can take it I'm not interested. And not to mention he's my dad's colleague. They're both Officers. My daddy would kill him.}

# Angela_2a_2c_1
{1880}{}{Gabrielle wants to be my friend? Aw, hell, that's sweet. I didn't even know she was old enough to think of me like that. I've known her since she was only this big. [She holds her hand face down, at around her waist level]}
{1881}{}{Is that a yes?}

# Angela_2a_2c_2
{1910}{}{Shoot, no. She should be looking for friends her own age. I always thought she looked up to me like a mommy. You just let her down gently, though, you hear?}

# Angela_2a_2d_1
{1940}{}{Aldo? Oh, no, I don't think that'd work...}
{1941}{}{Why not? Is he too old or something?}

# Angela_2a_2d_2
{1970}{}{Too old... Sure, whatever.}

# Angela_2a_2M_1
{2000}{}{Oh. Well, look, I'm flattered and all, but I don't think it could work out between you and me.}
{2001}{}{Why not? I'm not like the other losers in this prison. I've seen the world. Let me buy you a drink.}

# Angela_2a_2M_2a
{2030}{}{You are kinda good-looking in that sort of way, I suppose. But, trust me, there's no way it could work.}

# Angela_2a_2M_2b_1
{2060}{}{[You see her bite her lip, trying to hold back a laugh.] Sure, I suppose you've got a charming personality and all. But seriously, no.}
{2061}{}{"A great personality?" Don't give me that patronizing shit.}

# Angela_2a_2M_2b_2
{2090}{}{[Angela holds your eye steadily.] Now, look here. If you can't handle rejection, you ought not to go askin' in the first place. My Daddy will whoop you six ways from Sunday if you lose your temper with me, so you better calm down, got it?}
{2091}{}{If you won't give yourself to me, I'll have you by force.}

# Angela_2a_2M_2b_3
{2120}{}{No, I think I'm done talking to you. Scram.}
{2121}{}{Fucking bitch. I'll beat some manners into you.}

# Angela_2a_3
{2150}{}{[Angela frowns and looks away] No, I'm not dating anyone.}
{2151}{}{I guess you're just waiting for the right guy to come along.}
{2152}{}{I'll leave you to it. Goodbye.}

# Angela_2a_4
{2180}{}{The right guy? Yeah, right. Huh.}
{2181}{}{I assume you've been let down by men before.}

# Angela_2a_5
{2210}{}{Not really, no.}
{2211}{}{So what's stopping you?}

# Angela_2a_6
{2240}{}{[Angela regards you carefully for a while]}

# Angela_2a_7a_1
{2270}{}{[Angela speaks in a low voice, confiding in you] Maybe the right *man* ain't what I'm looking for.}
{2271}{}{Go on.}

# Angela_2a_7a_2
{2300}{}{I guess I've always known I was kinda different. I never felt safe when I was a kid. Daddy used to say you can't trust other people, especially those from the outside. I always looked up to the Warden and robots because they made me feel safe.}
{2301}{}{What does that have to do with anything?}
{2302}{}{I have a feeling I know where this is going.}

# Angela_2a_7a_3
{2330}{}{Well, this girl, she still liked robots even after she grew up. Even when the boys started chasing after pretty girls. [She looks at you desperately, hoping not to have to spell it out for you]}
{2331}{}{I'm not following.}
{2332}{}{Are you saying you're a robo-lover?}

# Angela_2a_7a_4a
{2360}{}{[Angela blushes to the roots of her hair] Aww... come on. I'm saying I like *robots*, not boys. My perfect guy looks like a boy, but he's a robot inside.}
{2361}{}{Angela kiss robo?}
{2362}{}{I want ask thing 'bout other thing.}

# Angela_2a_7a_4b
{2390}{}{That's right. So you can see why I'm not interested in anything serious with any of the real men in Tibbets. Or anywhere else for that matter.}
{2391}{}{Why don't you find yourself a "boyfriend?"}
{2392}{}{Your perversion disgusts me.}
{2393}{}{Why you not with robo?}
{2394}{}{Ha ha! You said you robo-bitch!}

# Angela_2a_7a_5a_1
{2420}{}{You have to be kidding me! And keep your voice down, will you? There's no way a girl like me could find... a robot that would like me in a place like this.}
{2421}{}{Why not?}
{2422}{}{Why do you want me to keep my voice down?}
{2423}{}{Why it hard to get robo?}
{2424}{}{Why you want }
{2425}{}{ talk quiet?}

# Angela_2a_7a_5a_2
{2450}{}{Because. Tibbets ain't that sorta place. People and robots could... start acting difficult. I know my daddy won't like it. He's sure set on me bringing grandchildren into the world for him.}
{2451}{}{Your father doesn't know you're a robo-lover?}
{2452}{}{Angela doddie not know Angela robo kiss-kiss?}

# Angela_2a_7a_5a_3
{2480}{}{No, and make sure you keep it that way. I'll tell him when the time is right, and that may never happen.}

# Angela_2a_7a_5B_1
{2510}{}{What?}
{2511}{}{You're sick, Angela. Only *real men* should have relationships with *real women.* You need help.}
{2512}{}{Angela, robo-bitch! Angela, robo-bitch!}

# Angela_2a_7a_5B_2
{2540}{}{I should have known better than to talk to you. Just... stay away from me.}
{2541}{}{Hehe! Robo-bitch!}

# Angela_2a_7a_5B_3
{2570}{}{No, really. I don't want you judging me anymore.}
{2571}{}{I'll leave you then, goodbye.}

# Angela_2a_7b_1
{2600}{}{No offense, but I'd rather not discuss personal matters with people I don't really know.}
{2601}{}{Come on, you can trust me. I won't tell a soul, I swear.}

# Angela_2a_7b_2
{2630}{}{Seriously, no.}

# Angela_2b_1
{2660}{}{[She looks angry for a moment, then smiles] That's my daddy, alright. He never gives up on the whole grandchildren thing, huh?}
{2661}{}{Are you already in a relationship?}
{2662}{}{Would you prefer not to discuss it with me?}

# Angela_2b_2
{2690}{}{Don't get me wrong. I appreciate you taking the time and all, but it ain't necessary, trust me.}

# Angela_3_1
{2720}{}{I'm a regular here, a barfly! [She laughs, her laughter is pleasant] I chat with the patrons, have fun, you know, that sort of thing. Did I mention this before?}
{2721}{}{I'm a regular here, a barfly! [She laughs, her laughter is pleasant] I chat with the patrons, have fun, you know, that sort of thing. Did I already tell you, hon?}
{2722}{}{No.}
{2723}{}{Yes.}

# Angela_3_2a
{2750}{}{I must be mistaking you for someone else, then.}

# Angela_3_2b
{2780}{}{Anyway, my daddy, Robb, works with the Sheriff. He's out back if you want to speak to him.}
{2781}{}{What can you tell me about your father?}
{2782}{}{What can you tell me about your mother?}

# Angela_3_3a_1
{2810}{}{Well, he's my daddy. [She grins] He's always looked after me. Strong as hell. Don't mess with him, or he'll make you regret it!}
{2811}{}{Is he an aggressive person?}
{2812}{}{We'll see about that.}

# Angela_3_3a_2a_1a
{2840}{}{Hell no! I'm just teasin' ya. As long as you treat him with respect, he'll be as good a friend to you as anyone. He knows his way around the prison, though. Picked up a few tricks along the way.}
{2841}{}{Hmm...}

# Angela_3_3a_2a_1B
{2870}{}{What was that?}
{2871}{}{Nothing. Tell me more about your father.}

# Angela_3_3a_2a_2
{2900}{}{Before daddy was brought to this place, he would go hunting practically every day to bring something to eat. He never had to buy his own food. I reckon he still has some savings hidden somewhere.}
{2901}{}{Your father is a skilled hunter?}

# Angela_3_3a_2a_3
{2930}{}{Well, he doesn't carry that big ol' knife and a gun of his around for decoration, you know.}

# Angela_3_3b_1
{2960}{}{Mom ain't around anymore. [Angela shrugs her shoulders and sniffs]}
{2961}{}{Where did she go?}
{2962}{}{She's dead?}

# Angela_3_3b_2a
{2990}{}{Oh, she's ashes now. That's how everyone's story ends here.}

# Angela_3_3b_2b_1
{3020}{}{Yup. It happened about six years ago. Sad.}
{3021}{}{How did it happen?}
{3022}{}{I'm sorry to hear that.}

# Angela_3_3b_2b_2
{3050}{}{Cancer. Life after the bombs, I guess.}
{3051}{}{How are you coping?}

# Angela_3_3b_2b_3
{3080}{}{Oh, you know. Life goes on. It shattered my world at the time, but you can't just give up. It's made life harder for me and my daddy, though.}

# Angela_9F_1
{3110}{}{Sure, I could talk to you all day, hon. [She gives you a huge grin that lights up her face]}

# Angela_9F_2
{3140}{}{Because, well, I kinda like you. [She bites her lip and looks away]}
{3141}{}{What kind of "like"?}

# Angela_9F_4
{3200}{}{Forget it. What was it you wanted to talk to me about?}

# Angela_9M
{3230}{}{Uh, yeah. I guess.}
