# Message file for tbbatt.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You come across a soldier clad in unfamiliar advanced armor.}
{101}{}{You spot a soldier in an enigmatic suit of advanced armor, adorned with an unfamiliar insignia on the breastplate.}
{102}{}{The combat armor they're donning boasts impressive features like gas and radiation filtration, along with enhanced night vision goggles.}

{103}{}{HOLSTER YOUR WEAPON IMMEDIATELY!}
{104}{}{Stop sneaking around!}
{105}{}{I warned you, idiot!}
{106}{}{Your shadiness doesn't sit well with me!}

# Node 0 [Floats]
{200}{}{You! It's your kind that brought ruin upon this once great nation.}
{201}{}{Finally, some action! Last time I got stuck with KP duty.}
{202}{}{Big robots, big problems.}
{203}{}{Got a light? Oh, never mind. I've got one.}
{204}{}{Who the--? *zzzztt*}
{205}{}{Apologies, no time for idle talk.}
{206}{}{Have you met the General yet?}
{207}{}{Move! Move! Move!}
{208}{}{Go! You're free to go!}
{209}{}{*zzzztt*}
{210}{}{We've rescued your sorry ass.}
{211}{}{Nothing personal, but I don't trust your face.}
{212}{}{When in doubt, just empty the magazine.}
{213}{}{We're not known for our tidiness.}
{214}{}{The Cavalry has arrived!}
{215}{}{You can never have too much ammo.}
{216}{}{Even smart bombs have their bad days.}
{217}{}{Nothing that an airstrike couldn't solve.}
{218}{}{Once they regroup, we're getting out of here. Are you sure you want to stay?}
{219}{}{Run for your life!}
{220}{}{What are you waiting for? Run!}
{221}{}{Escape before they return!}
{222}{}{If I were you, I'd celebrate today's date as my second birthday.}
{223}{}{Glad we saved your sorry hide before it was too late.}
{224}{}{You're free now, no need to fear.}
{225}{}{We won't harm you. It's safe.}
{226}{}{Head east. We breached the ceiling in that direction!}
{227}{}{Make a quick exit to the east! Hurry!}
{228}{}{*zzzztt* Copy, over. *zzzztt*}
{229}{}{*zzzztt* Strike Team November, this is Division Bravo. Go ahead, over. *zzzztt*}
{230}{}{*zzzztt* Strike Team November, this is Division Bravo. Captain Davidson will be the ground contact for the buckets, over. *zzzztt*}
{231}{}{*zzzztt* Strike Team Romeo, this is Division Bravo. Captain Pierce will be the ground contact for the buckets, over. *zzzztt*}
{232}{}{Run for it!}
