# Message file for tbprsn.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see an enthusiastic robot.}
{101}{}{You see the Headmaster of the Barber College.}
{102}{}{It's flailing its arms as usual.}

{105}{}{This is a Mr. Handy model customized for barber and hairdressing trainings. You're not sure who's responsible for programming in its personality though.}

# Node 0 [Floats]
{200}{}{Let those little hands work their scissor magic! Chop chop!}
{201}{}{Careful now!}
{202}{}{Sacre bleu!}
{203}{}{Sculpt that hair with precision!}
{204}{}{I expect nothing less than a masterpiece!}
{205}{}{Stay focused!}
{206}{}{If you want to work on the next year's Miss Tibbets, step up your game!}
{207}{}{Concentrate!}
{208}{}{You're a mess! Outdated!}
{209}{}{Good, but I know you can do even better!}
{210}{}{You're falling behind the rest. Maybe you should join the History class.}
{211}{}{I demand a work of art! Show me your best!}
{212}{}{Oh la la!}
{213}{}{Focus!}
{214}{}{Passé! So passé!}
