# Message file for tbbot13.ssl
# Number of nodes: 9
# Grammar pass done

{100}{}{You see a towering police bot, its immense size dominating the area.}
{101}{}{Before you stands an imposing behemoth of a police bot, unlike any you've seen before.}
{102}{}{This formidable bot is equipped with robust armor, its motion sensors occasionally emitting beeps as it surveys its surroundings.}

{150}{}{This six-legged walker is equipped with four miniguns. Due to its thick plating and superior alloy, it is capable of taking out an entire squad of power armored combatants.}
{151}{}{You already dismantled}
{152}{}{'s minigun.}
{153}{}{'s minigun using the Repair skill.}

# Node001
{200}{}{Halt! Identification required. Who is the entity in motion?}
{201}{}{It's the Warden. I'm here to inspect this loading zone.}
{202}{}{I'm Prisoner 13. Just taking a stroll to stretch my legs.}
{203}{}{Does it matter who I am? I'm a new inmate headed to the kitchen. Famished as always.}
{204}{}{You'll never catch me alive!}
{205}{}{Ghhuugh.}
{206}{}{Gish. Gish. Giiiiiiiiiiiiish.}

# Node002
{230}{}{Does your spatial orientation module malfunction, Prisoner 13?}
{231}{}{Not really.}
{232}{}{Aren't we all?}
{233}{}{Gurbu. Gaaaaaaaaah.}
{234}{}{Yes, I am. I need to speak to the Warden.}

# Node003
{260}{}{Are there additional requests I can process for your assistance?}
{261}{}{How do I get to the kitchen?}
{262}{}{How can I communicate with the Warden?}
{263}{}{I'm good. That's all, officer.}
{264}{}{Freedom! Death to robots!}
{265}{}{You're not much of a talker, are you?}

# Node004
{290}{}{[The police bot scans you multiple times, emitting an intense, blinding white flash. Your vision deteriorates, and it feels as if you should seek medical attention.]}
{291}{}{What the...}
{292}{}{Motherfucker... you'll pay for this!}
{293}{}{Uggggggh!}
{294}{}{Nooooooooooooooooooo!}

# Node005
{320}{}{Your information has been logged into my data repository for future analytical processing.}
{321}{}{[CONTINUE]}

# Node006
{350}{}{To initiate communication protocol with entity designated as "Warden", navigate to location: Courtroom. Ascend via the transport unit identified as "Elevator" to the Security Hub situated on the superior level. From this location, engage the southwestern elevator to reach your target destination. Please comply.}
{351}{}{Tell me something else.}
{352}{}{Thank you! I will leave you to your duties now.}
{353}{}{Understood. Time to investigate further.}

# Node007
{380}{}{Your designated living quarter, referred to as "Cell Block", is equipped with an exercise facility. You may utilize this at any time according to your desire.}
{381}{}{Tell me something else, officer.}
{382}{}{Certainly. I'll take my leave now.}

# Node008
{410}{}{Retrace your pathway. The food preparation area, known as the "Kitchen", is located in the western corridor.}
{411}{}{Great! Time to see what's on the prison menu today.}

# Node009
{440}{}{My communication interface operates on a basic level. My superior protocols are tailored for tactical assault operations.}
