# Message file for tbbot13.ssl
# Number of nodes: 9
# Grammar pass done

{100}{}{You see a vigilant police bot.}
{101}{}{You see an advanced and imposing police bot.}
{102}{}{The formidable bot stands tall and exhibits advanced features. Its motion sensors periodically beep as it surveys the area.}

{105}{}{Target identified. Engage and neutralize.}

{106}{}{This is a pre-war heavy-duty police robot with integrated minigun and rocket launcher, and can withstand even the most powerful of attacks thanks to their heavily armored structure.}
{107}{}{You already dismantled}
{108}{}{'s minigun.}
{110}{}{'s minigun using the Repair skill.}

# Node001
{200}{}{Halt! Identification required. Who is the entity in motion?}
{201}{}{It's the Warden. I've arrived to inspect this cell block.}
{202}{}{It's me, Prisoner 13! Just taking a walk to stretch my legs.}
{203}{}{Does it matter who I am? I'm a new inmate heading to the kitchen. Starving as usual.}
{204}{}{You'll never capture me alive!}
{205}{}{Ghhuugh.}
{206}{}{Gish. Gish. Giiiiiiiiiiiiish.}
{207}{}{Me Boss! That me!}

# Node002
{230}{}{Does your spatial orientation module malfunction, Prisoner 13?}
{231}{}{Not really.}
{232}{}{Aren't we all?}
{233}{}{Gurbu. Gaaaaaaaaah.}
{234}{}{Yes, I am. I need to speak to the Warden.}

# Node003
{260}{}{Are there additional requests I can process for your assistance?}
{261}{}{How can I reach the kitchen?}
{262}{}{How can I communicate with the Warden?}
{263}{}{I'm good. That's all, officer.}
{264}{}{Freeedom! Death to robots!}
{265}{}{You're not much of a talker, are you?}

# Node004
{290}{}{[The police bot scans you multiple times, emitting an intense, blinding white flash. Your vision deteriorates, and it feels as if you should seek medical attention.]}
{291}{}{What the...}
{292}{}{Motherfucker... you'll pay for this!}
{293}{}{Uggggggh!}
{294}{}{Nooooooooooooooooooo!}

# Node005
{320}{}{Your information has been logged into my data repository for future analytical processing.}
{321}{}{[CONTINUE]}

# Node006
{350}{}{To initiate communication protocol with entity designated as "Warden", navigate to location: Courtroom. Ascend via the transport unit identified as "Elevator" to the Security Hub situated on the superior level. From this location, engage the southwestern elevator to reach your target destination. Please comply.}
{351}{}{Tell me something else.}
{352}{}{Thank you! I'll let you carry on with your duties now.}
{353}{}{Understood. It's time to uncover what's happening.}

# Node007
{380}{}{Your designated living quarter, referred to as "Cell Block", is equipped with an exercise facility. You may utilize this at any time according to your desire.}
{381}{}{Tell me something else, officer.}
{382}{}{Certainly. I'm leaving now.}

# Node008
{410}{}{Ascend via the transport unit identified as "Elevator" to the Security Hub situated on the superior level. From this location, engage the southeastern elevator to reach your target destination. Please comply.}
{411}{}{Excellent! Let's see what culinary delights await in the prison menu today.}

# Node009
{440}{}{My communication interface operates on a basic level. My superior protocols are tailored for tactical assault operations.}
