# Message file for tbbrain.ssl
# Number of nodes: 42
# Grammar pass done

{100}{}{You see a robobrain.}
{101}{}{You see robobrain P31-Cerebro.}
{102}{}{You see a preserved human brain within a robotic chassis, designed for various tasks in the pre-war era.}

{150}{}{You successfully provided scientific assistance.}
{151}{}{You failed to make any meaningful scientific contributions.}

# Node001
{200}{}{Ah, }
{201}{}{! I never thought I'd see the day, Number 13. It truly brings an... approximation of joy to my circuits.}
{202}{}{You know my name. My number. And you seem... unusually excited to see me. Is there something about you that I'm not aware of?}
{203}{}{Great, another talking robot. I am out of here.}
{204}{}{What you know?}
{205}{}{No talky robot.}

# Node002
{230}{}{Indeed, there is. I was present during a very significant moment in your life - your birth.}
{231}{}{My birth? You were there?!}
{232}{}{My birth?! How did I end up as a super mutant?}
{233}{}{My birth?! How did I end up as a ghoul?}
{234}{}{Me birth? You there?!}
{235}{}{Me birth?! How me super mutant?}
{236}{}{Me birth?! How me ghoul?}

# Node003
{260}{}{Yes, of course. I was an assistant to Dr. Victor Presper. He was involved in various advanced medical projects in Tibbets, some of which were related to childbirth and neonatal care. I was there, assisting, recording, and analyzing. I remember every child I helped deliver onto this world.}
{261}{}{Hold on a moment, I have so many questions for you.}
{262}{}{I'm not sure how to feel about this. It's a lot to process. I need to sit down.}
{263}{}{Me ask.}
{264}{}{Me feel bad. Me sit down.}

# Node004
{290}{}{Ask and I will answer.}
{291}{}{You're not like the other robobrains, are you?}
{292}{}{You said you were present during my birth. Do you know anything about my parents?}
{293}{}{Why were prisoners cryogenically frozen in Tibbets? What was the purpose behind it?}
{294}{}{That is all.}
{295}{}{You not like other robo?}
{296}{}{Where mom and dad?}
{297}{}{Why freeze?}
{298}{}{That all.}

# Node005
{320}{}{You are conversing with P31-Cerebro, the cloned brain of Dr. Victor Presper, a genius transcending his era, and that of the present and future.}
{321}{}{Who is this Dr. Victor Presper exactly?}
{322}{}{Who Doc Prespe?}

# Node006
{350}{}{Ah, your parents. The only information I have pertains to them being among those cryogenically unfrozen by Dr. Presper.}
{351}{}{Unfrozen? What happened to them after that? Where are they now?}
{352}{}{Not frozen? What happen?}

# Node007
{380}{}{Regrettably, I don't possess specific details about their fate after you were born. Dr. Presper might perhaps know more.}
{381}{}{So you're saying he used them as lab rats?}
{382}{}{So they lab rats?}

# Node008
{410}{}{It is a possibility. Dr. Presper believed he was taking necessary measures for a greater purpose, though I understand this doesn't alleviate the anguish such revelations may bring.}
{411}{}{All this time, I thought they might be out there somewhere, alive. Now you're telling me they were just pawns in some madman's experiment?}
{412}{}{You're telling me they were just pawns in some madman's experiment?}
{413}{}{Me think they alive somewhere. Now you tell they dead in crazy man experiment?}
{414}{}{Now you tell they dead in crazy man experiment?}

# Node009
{440}{}{I share this information not to cause you pain, but to shed light on the past. It is a testament to the complexities and often painful sacrifices borne out of ambition and vision. Your lineage is intertwined with the tapestry of Dr. Presper's plans.}
{441}{}{Why did he experiment on them? Was it necessary?}
{442}{}{It's hard to accept. I just... I need some time.}
{443}{}{Why do experiment?}
{444}{}{Leave me alone.}

# Node010
{470}{}{Dr. Victor Presper, the world's most brilliant mind, is the sole individual to have ever escaped Tibbets, only to audaciously return years later. Much like your parents, he too was once encapsulated in a cryopod here, enduring through the calamity of the Great War.}
{471}{}{Do you hold any memories from Dr. Presper's past?}
{472}{}{He's here?}
{473}{}{What Doc Prespe memory?}
{474}{}{He here?}

# Node011
{500}{}{Ah, an inquisitive mind! My design contains a clone of Dr. Presper's brain, but as for his memories... they're fragments, at best.}
{501}{}{Fragments? Like what? Anything that can give me further insight into the man?}
{502}{}{Frag? What?}

# Node012
{530}{}{Images, emotions, brief moments of clarity. It's not like a holotape where you can just play back a sequence. The memories are... scattered, disjointed.}
{531}{}{Can you share any of them? Anything that stands out?}
{532}{}{You share?}

# Node013
{560}{}{There's a recurring memory... a lab, filled with bright lights and the hum of machinery. I sense ambition, a drive for perfection. There are whispers of a plan, a grand vision for humanity's future. But specifics? They elude me.}
{561}{}{It's a start. Do you ever feel... emotions? Like the original Dr. Presper might have?}
{562}{}{Tell me something else.}
{563}{}{You feel emo? Like Doc Prespe?}
{564}{}{Tell.}

# Node014
{590}{}{Emotions are complicated. While the cloned brain may retain the chemical signatures and patterns associated with emotions, it doesn't truly "feel" in the same way a human does. It's more like... echoes of a past self.}
{591}{}{Must be strange, carrying the remnants of someone's past without truly understanding or experiencing it.}
{592}{}{It strange.}

# Node015
{620}{}{Indeed. But it provides a unique perspective, one that's unburdened by the full weight of human emotion and bias.}
{621}{}{Thanks for sharing. Even if they're just fragments, understanding Dr. Presper's memories might help in understanding the man himself.}
{622}{}{Thank. Me know Doc Prespe more now.}

# Node016
{650}{}{Perhaps. The past can be a window, but it can also be a mirror. Reflect on what you learn.}
{651}{}{Let me ask you something else.}
{652}{}{Thank you, I have to go now.}
{653}{}{Ask.}
{654}{}{Thank. Me go.}

# Node017
{680}{}{Yes, those experiments were essential in understanding human physiology and behavior. The Doctor always said that it's a shame people fail to recognize the greater good in his work.}
{681}{}{Greater good? He was playing god with human lives! And you assisted!}
{682}{}{Great gud? He play god! You play god!}

# Node018
{710}{}{Humans have played god for centuries, manipulating genes, changing environments, and even creating artificial intelligence. Why was our work any different?}
{711}{}{Because you caused harm without the subjects' consent. There's a line between progress and ethics.}
{712}{}{You harm other who say no.}

# Node019
{740}{}{Ethics is a fluid concept, molded by society's ever-changing values. What is deemed unethical today might be celebrated as revolutionary tomorrow.}
{741}{}{And what's your role now? Still carrying out twisted experiments?}
{742}{}{You're a monster that I will end!}
{743}{}{What you do now? Still experiment?}
{744}{}{You monster! Me kill!}

# Node020
{770}{}{Currently, I'm in charge of the Chemical Treatment Area. But I've moved past experimenting on mere prisoners. I've been focused on finding a solution to cleanse the wasteland.}
{771}{}{Cleanse? That sounds ominous.}
{772}{}{Ever need an extra hand around here?}
{773}{}{Clean? That evil.}
{774}{}{Me work here?}

# Node021
{800}{}{Not at all. The wasteland is filled with radiation, mutated creatures, and corruption. My intention is to help purify it. Create a fresh start for humanity.}
{801}{}{At what cost? And who gets to decide what's "pure"?}
{802}{}{Die, monster!}
{803}{}{Who tell what "pure"?}
{804}{}{Die!}

# Node022
{830}{}{I'm more than qualified to make that decision. Remember, I am the cloned brain of the smartest man in the world. My goal is to save humanity from its own destruction. Sacrifices might be necessary, but they're for the greater good.}
{831}{}{I've seen what your idea of "sacrifices" looks like. It's not a future I want any part of.}
{832}{}{Who am I to argue with you then? I am sure you know what you are doing. So long.}
{833}{}{Me no like your plan.}
{834}{}{You know what you do. Bye-bye.}

# Node023
{860}{}{It's unfortunate you feel that way. But perhaps, in time, you'll see the brilliance of my vision. Until then, tread carefully.}
{861}{}{Likewise.}
{862}{}{Not if I have anything to say about that. Die!}
{863}{}{Ditto.}
{864}{}{Die!}

# Node024
{890}{}{Intriguing. You wish to be involved in the Chemical Treatment Area's operations? What skills or experience can you offer?}
{891}{}{I've learned a thing or two about chemistry and mechanics. Plus, I'm a quick learner.}
{892}{}{I am good at making mutants and raiders explode. That's got to be some sort of chemistry, right?}
{893}{}{On a second thought, I don't think I'm cut for the job. Tell me something else.}
{894}{}{Me know Science!}
{895}{}{Me good make enemy explode. That chem, 'K?}
{896}{}{Me no like work. Tell else.}

# Node025
{920}{}{Your experiences in the wasteland could be of value. The practical knowledge of scavengers can sometimes surpass the theoretical. However, the work here is sensitive and not without its dangers.}
{921}{}{I've faced mutated horrors, and more out there. I think I can handle a few chemicals.}
{922}{}{Me handle mutant horror. Me handle chem too.}

# Node026
{950}{}{It's not merely about "handling chemicals". Precision, discipline, and an understanding of the underlying science are crucial. One wrong move, and the consequences could be catastrophic.}
{951}{}{I understand the risks. If you give me a chance, I'm sure I can prove my worth.}
{952}{}{Me work good.}

# Node027
{980}{}{Very well. I can assign you some basic tasks to start. Monitor the chemical reactions, record data, ensure equipment is functioning optimally. If you show aptitude, perhaps there will be more advanced roles for you.}
{981}{}{Sounds good to me. Just point me in the right direction.}
{982}{}{Sound gud.}

# Node028
{1010}{}{Begin by familiarizing yourself with the terminals. They contain the protocols and safety measures. Adherence is mandatory. Deviation will not be tolerated.}
{1011}{}{Got it. Let's get to work then.}
{1012}{}{Me work now.}

# Node029
{1040}{}{Ah, the cryogenic initiative at Tibbets. It was an ambitious endeavor. The wasteland is an unpredictable place, and when recalibrating an entire civilization, one must have control groups. Those prisoners served as untouched variables, shielded from the chaos outside.}
{1041}{}{Untouched variables? You make it sound like a big experiment.}
{1042}{}{Untouch var? Big exper.}

# Node030
{1070}{}{In many ways, it was. The wasteland presented countless variables - radiation, mutated fauna, and hostile groups, to name a few. By preserving a segment of humanity, Dr. Presper intended to ensure a controlled, untainted population for observation and potential repopulation.}
{1071}{}{So, these prisoners were just guinea pigs in a larger plan?}
{1072}{}{You monster!}
{1073}{}{Prison guinea piggies in big plan?}
{1074}{}{Monster!}

# Node031
{1100}{}{It might sound cold, but remember, the goal was the salvation and rebirth of humanity. Sometimes, difficult decisions and sacrifices are required for the greater good.}
{1101}{}{It's a thin line between visionary and madman.}
{1102}{}{Maybe save all maybe kill all.}

# Node032
{1130}{}{Indeed. But often, history is written by the outcomes, not the intentions.}
{1131}{}{I still don't get it. Why choose criminals, of all people, to potentially repopulate the world? Isn't that risky?}
{1132}{}{Why bad guys?}

# Node033
{1160}{}{An astute question. Firstly, Dr. Presper believed in the adaptability and resilience of humans. Many of those incarcerated at Tibbets were there not because of inherent evil but due to circumstances, mistakes, or the complexities of human nature.}
{1161}{}{But there are still risks, right? What about those with violent tendencies or sociopathic traits?}
{1162}{}{Interesting. Tell me something else.}
{1163}{}{Risky!}
{1164}{}{Tell other.}

# Node034
{1190}{}{True, there are inherent risks. However, consider this: in a world post-cleansing, where survival and rebuilding are paramount, the past infractions of these individuals might become less significant. Moreover, the environment often plays a crucial role in shaping behavior. A clean slate, a new world, might just bring out the best in many.}
{1191}{}{It sounds like a gamble.}
{1192}{}{Gamble.}

# Node035
{1220}{}{Life, especially in the wasteland, is always a gamble. But remember, these cryogenically frozen prisoners were not necessarily the only group Dr. Presper had in mind. They were a part of a broader scheme, an insurance policy of sorts.}
{1221}{}{Insurance for what?}
{1222}{}{Insure?}

# Node036
{1250}{}{For diversity, for resilience, and for adaptability. While it's true that not all would be suitable for the world Dr. Presper envisioned, they represented a cross-section of humanity that had already demonstrated an ability to survive in tough conditions.}
{1251}{}{It's a controversial approach, that's for sure.}
{1252}{}{Contro. Ver. Sy.}

# Node037
{1280}{}{Controversy is often the bedfellow of innovation. Only time would tell if Dr. Presper's vision was genius or folly.}
{1281}{}{I've had enough of this chat. So long, P31-Cerebro.}
{1282}{}{You assisted him and I'm holding you equally responsible for those atrocities. Time to face the music.}
{1283}{}{No talk. Bye, Pee-Tri-Wan.}
{1284}{}{You help Doc. You evil. You die.}

# Node038
{1310}{}{You began to collapse and were on the brink of death. Dr. Presper and I, in our genius, found a potential solution in the Warden's database. We chose to expose you to the Forced Evolutionary Virus, or FEV, to save your life. Where others would perished, you thrived, Number 13.}
{1311}{}{You were there?!}
{1312}{}{You there?!}

# Node039
{1340}{}{You began to collapse and were on the brink of death. Dr. Presper and I, in our genius, found a potential solution in the Warden's database. We chose to expose you to the ionizing radiation with wavelengths below ten picometers, to save your life. Where others would perished, you thrived, Number 13.}

# Node040
{1370}{}{. It's good to see you again.}
{1371}{}{I seek some answers.}
{1372}{}{You have to pay. For every atrocity. For every stolen life. Both you and the Doctor.}
{1373}{}{I'm just passing by. Goodbye.}
{1374}{}{Me asks.}
{1375}{}{You evil. You pay.}
{1376}{}{Me go. Bye.}

# Node041
{1400}{}{Indeed he is. I saw him again a month ago after }
{1401}{}{ years. He was too busy with ODYSSEUS to even say hello.}
{1402}{}{What sort of business does he have with the Warden?}
{1403}{}{What ODI busy?}

# Node042
{1430}{}{That's a very good question, }
{1431}{}{. Regrettably, I don't have the answer.}
{1432}{}{That would be all.}
{1433}{}{That all.}
