# Message file for tbprsn.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You spot one of Tibbets' many captives, looking uneasy.}
{101}{}{You notice someone who appears nervous.}
{102}{}{You see someone engrossed in a Creativity Writing class SAT.}

# Node 0 [Floats]
{200}{}{I failed last time.}
{201}{}{This is challenging.}
{202}{}{I need to focus.}
{203}{}{That robot annoys me.}
{204}{}{Psssst! Do you happen to know the answer to question 7?}
{205}{}{These questions require too much creativity for me.}
{206}{}{Almost finished.}
{207}{}{This one's a breeze!}
{208}{}{I'm stuck on this one.}
{209}{}{I know the answer to this one.}
{210}{}{Hey, you made me make a mistake!}
{211}{}{Is he watching me again? Cheating is difficult, huh?}
{212}{}{After this exam, I'm either going to need a large coffee or a defibrillator.}
{213}{}{On a positive note, failing this exam will make for a great underdog story one day.}
