# Message file for tbcrebot.ssl
# Number of nodes: 23
# Grammar pass done

{100}{}{You see a service bot fulfilling the role of a teacher.}
{101}{}{This service bot is responsible for Keyboarding, Creative Writing, and Graphic Arts classes.}

{103}{}{Although overall design is that of a humanoid, the details reveal this robot wasn't built by a human. It was customized to act as a class teacher.}

{105}{}{Number 72.}
{106}{}{Greetings, student.}
{107}{}{How are you doing, Number 72?}

# Node001
{200}{}{You're late! Again. The test is about to begin.}
{201}{}{Excuse me?}
{202}{}{Huh?}

# Node002
{230}{}{Yes, Number 72. Today is the big day! Are you excited? I hope you have prepared well. Class, we are about to commence!}
{231}{}{There must be some mistake! I'm not--}
{232}{}{Noooooooooo!}

# Node003
{260}{}{Number 72!}
{261}{}{Who, me?}
{262}{}{Me?}

# Node004
{290}{}{If it weren't against protocol, I would hug you now. An incredible score of 100%! I will personally commend you to our Warden. I wish more of our students were like you.}
{291}{}{Really? Will I be rewarded?}
{292}{}{Me get bonus?}

# Node005
{320}{}{If it weren't against protocol, I would expel you now. A pathetic score of 0%! I will personally report this to our Warden. Please avoid influencing other students too much, as they may adopt your lack of dedication.}
{321}{}{Will I face punishment for that?}
{322}{}{What about Prisoner 13's score?}
{323}{}{Prisoner 13 test?}
{324}{}{Ass get whipped?}

# Node006
{350}{}{A passing score of 60%! Keep studying, and perhaps one day I will mention your name to our Warden!}

# Node007
{380}{}{A good score of 70%! Keep studying, and perhaps one day I will mention your name to our Warden!}

# Node008
{410}{}{An excellent score of 80%! Keep studying, and perhaps one day I will mention your name to our Warden!}

# Node009
{440}{}{A superb score of 90%! Keep studying, and perhaps one day I will mention your name to our Warden!}

# Node010
{470}{}{A failing score of 50%! Keep studying, and you might pass next time.}

# Node011
{500}{}{A poor score of 40%! Keep studying, and you might pass next time.}

# Node012
{530}{}{A terrible score of 30%! Keep studying, and you might pass next time.}

# Node013
{560}{}{An abysmal score of 20%! Keep studying, and you might pass next time.}

# Node014
{590}{}{An embarrassing score of 10%! Keep studying, and you might pass next time.}

# Node015
{620}{}{Approaching the test was a reward in itself, don't you think? Being a good prisoner will raise your CODE score, and we all know what that means for you, right?}
{621}{}{I actually have no clue.}
{622}{}{What a load of brahmin crap!}
{623}{}{Dunno.}
{624}{}{Brahma-crap!}

# Node016
{650}{}{Having a high CODE score means you will be released earlier.}
{651}{}{Okay, that sounds fair enough. But how do I know my current CODE score?}
{652}{}{What if I feel I shouldn't be here in the first place? I was abducted.}
{653}{}{What my CODE?}
{654}{}{Me no be here. Me stolen.}

# Node017
{680}{}{Don't worry, the Warden keeps track of your CODE score, among many other things.}
{681}{}{It seems the Warden holds all the answers. How do I meet him?}
{682}{}{See Warden!}

# Node018
{710}{}{Watch your tongue! It won't help change the Warden's mind about anything regarding your status. Now, excuse me, I have work to do.}
{711}{}{[END]}

# Node019
{740}{}{My dear student, what would you like me to say? I have never left Tibbets during my existence. The Warden had his reasons for transferring you here.}
{741}{}{It seems all the answers to my questions lie with him.}
{742}{}{[Shamble off.]}

# Node020
{770}{}{If that's all, excuse me. I have work to do.}

# Node021
{800}{}{Only the Warden knows that. I cannot say.}
{801}{}{[CONTINUE]}

# Node022
{830}{}{Prisoner 13, you say? Let me query the database... One moment... Ah, yes, that entry has been marked invalid by... the Warden himself! The reason for it says right here: False Identity Claim. Hmph, how did I miss that one?}
{831}{}{Hmm... how forgetful of me! I just remembered I need to be somewhere else!}
{832}{}{Hmm, interesting. Well, that will be all. Goodbye.}
{833}{}{Me go. Far away.}

# Node023
{860}{}{You don't see him unless he wants to see you. If that's all, excuse me. See you in our next class, Number 72!}
