# Message file for tbdrexle.ssl
# Number of nodes: 14
# Grammar pass done

{100}{}{This woman's face is stern and determined.}
{101}{}{Dr. Bree Drexle appears perpetually pissed.}
{102}{}{Confidence radiates from this woman, as if she's accustomed to being in control. She regards you with a hint of disdain.}

{150}{}{Move along. I'm too busy to chat right now.}

# Start
{199}{}{[As you approach, she connects her Pip-Boy to yours.] }
{200}{}{, how many times do I have to tell you? I can't provide anything without the proper forms.}
{201}{}{Please, pretty please? All I need is... ummm... a Super Duper Stimpak!}
{202}{}{[Frantically searching your pockets.] I could've sworn it was right here...}
{203}{}{I have the forms right here.}
{204}{}{Geez, do you always wake up on the wrong side of the bed?}
{205}{}{You pretty.}
{206}{}{I got form! I got form!}
{207}{}{Uh oh. I forgot. I get forms. Bye-bye!}

# A
{230}{}{What on earth are you talking about?}
{231}{}{Wait, you mean you don't know what it is either?}

# B
{260}{}{Ha! Unbelievable! You finally had the form, and you lost it?}
{261}{}{Ohgodohgodohgodohgod, Danika will kick my ass!}
{262}{}{Shit! Please, you have to help me out!}

# C
{290}{}{[She smirks.] That's very flattering, }
{291}{}{. Now, do you have the form or not?}
{292}{}{Uh Uh. But you still pretty. Like bruc flowar.}

# X
{320}{}{Wha-? [Her eyes widen.] You even filled them out in triplicate!}
{321}{}{Bet you thought this day would never come, huh?}
{322}{}{Me gots forms goods, huhs?}

# D
{350}{}{Look, it's nothing personal, okay? I just need the forms. Come back when you have them.}
{351}{}{[END]}

# E
{380}{}{Dr. Danika sent you?}
{381}{}{Yeah. She asked me to collect a Super Duper Stimpak for her.}

# F
{410}{}{Why the hell would I do that?}
{411}{}{Come on, Doc. I had it just a moment ago, I swear!}

# G
{440}{}{[She rolls her eyes.] You moron. Come back when you have the forms.}

# H
{470}{}{Tell you what. We don't have a Super Duper Stimpak, never did. But here are two Super Stimpaks. And when you see her, ask where the fuck she was last night. I waited two hours for that idiot to sort out our inventory, and she didn't even show up!}
{471}{}{Whoa, take it easy. I'm sure she had a valid reason.}

# I
{500}{}{She better have the best damn reason in the entire universe! If she pulls ANY more of that bullshit, I swear I'll decapitate her with my bare hands...}

# J
{530}{}{Okay, let's see. I'm supposed to give you... a doctor's bag. That should be everything.}
{531}{}{Thanks, Doctor. See you later.}
{532}{}{Yughuu! [Hug her.]}

# K
{560}{}{Calm down, Romeo. Come back when you have the forms, okay?}

# L
{590}{}{Wha...? I... I'll take that as a thank you, I guess.}
{591}{}{Bye-bye!}
