# Message file for tbearley.ssl
# Number of nodes: 34
# Grammar pass done

{100}{}{You spot a sly-looking character.}
{101}{}{It's Earley, wearing a mischievous grin.}
{102}{}{He exudes an air of shadiness.}

# PC has been blinded by drinking from NPC Challenge.
{200}{}{I can see clearly now the rain has gone...}
{201}{}{Blinded by the lights...}
{202}{}{I'm stumbling around in the darkness...}
{203}{}{Who turned off the lights? I can't see a thing!}

{230}{}{3,000 caps up for grabs!}
{231}{}{Get your hands on free money!}
{232}{}{The deal of the century awaits you!}

{240}{}{You've ruined everything!}
{241}{}{Cheater! I can spot one from a mile away.}
{242}{}{I've lost my fortune! *sob*}
{243}{}{Fuck my life!}
{244}{}{Now I have to start from scratch!}

{250}{}{Leave me alone!}
{251}{}{I'm keeping my eye on you.}
{252}{}{*glares angrily*}

# Greeting
{290}{}{[A well-groomed man in a clean jumpsuit looks up, flashing an exaggerated smile.] Why, howdy there, stranger! New in these part of Tibbets, ain't ya? Folks around here call me Earley! So tell me, did ya step right up for the Spectacular Challenge, or are ya just sauntering through on this fine day?}
{291}{}{[A slick-haired man in a pristine jumpsuit looks up and grins widely.] Well, well, well, if it ain't a sight for sore eyes! Not every tick of the clock brings a splendid rose like yourself through my humble cell block. What brings you 'round, might you be yearning for the legendary Earley's Challenge, or are you simply hankering for some good ol' fashioned chinwag?}
{292}{}{I'm }
{293}{}{, and I know all about your "Challenge", Mr. Earley.}
{294}{}{Pleasure to meet you, Mr. Earley. I'm }
{295}{}{. You mentioned some kind of Challenge?}
{296}{}{Hey there, I'm }
{297}{}{. I was wondering if I could ask you a few questions?}
{298}{}{Actually, Mr. Earley, I don't have time for a Challenge or a chat right now.}
{299}{}{Me }
{300}{}{. Challenge is bad.}
{301}{}{Me like Challenge. What must I do?}
{302}{}{. Want to talk.}
{303}{}{Me go.}

# Greeting_2
{320}{}{[Earley's grin widens as he spots you.] Ah, if it ain't my ol' chum }
{321}{}{! Ready to dance with lady luck again, are ya? Craving another whirl with my captivating game of wonders, aren't you?}
{322}{}{I'm confident I can succeed this time, Mr. Earley.}
{323}{}{Actually, not at the moment. Can I ask you a few more questions?}
{324}{}{No, I'm in a hurry. Goodbye.}
{325}{}{Me drink lots this time. Get beer.}
{326}{}{Just talk, m'kay?}
{327}{}{Bye.}

# Gen_Conversation_0
{350}{}{So, what's tickling your curiosity today, friend? Got a burning question you're hankering to ask, }
{351}{}{?}
{352}{}{And how about you? You're here for a bit of lively banter, ain't ya, sweet }
{353}{}{Can you tell me about Tibbets?}
{354}{}{What's happening around here?}
{355}{}{What is it that you do, Mr. Earley?}
{357}{}{I'll come back later for a chat. Goodbye.}
{358}{}{What in Tib-bits?}
{359}{}{What happening here?}
{360}{}{Who are you?}
{362}{}{Me leave.}

# Gen_Conversation_1
{380}{}{Tibbets, eh? Well, ol' Earley knows as much about it as any caged bird in this coop. Nothin' too fancy, just safe as houses.}
{381}{}{Can I ask you something else?}
{382}{}{Alright, thanks for the information. Goodbye.}
{383}{}{Ask more?}
{384}{}{Oh. Bye.}

# Gen_Conversation_2
{410}{}{Why don't you hoist your eyes and soak up the atmosphere?}
{411}{}{Whazzup, you ask? Just the usual, unless you're rarin' to throw your hat in the ring with your pal Earley.}
{412}{}{Thanks, but I'm leaving now.}
{413}{}{Oh. I see. Ask more?}
{414}{}{Hmmm. Me go.}

# Gen_Conversation_3
{440}{}{Oh, not much, just luxuriating in the comfort of my independent wealth. No need for this ol' boy to lift a finger.}
{441}{}{Okay, got it. Do you have any other questions?}
{442}{}{Alright, have a good one. Bye.}
{443}{}{Ask another?}

# Hostile_0
{470}{}{[Earley cackles.] Well, well, ain't it a pleasure to see }
{471}{}{. How's the world treating ya? Soaking up the sights?}
{472}{}{I want to give it another shot. I'm ready this time.}
{473}{}{How's it going? Your beer blinded me. That's how it's going.}
{474}{}{I just wanted to *see* what you'd look like dead.}
{475}{}{I don't feel like talking right now.}
{476}{}{Me try Challenge. Me ready now.}
{477}{}{Me no see! You make me no see!}
{478}{}{Me see you dead!}

# Hostile_1
{500}{}{Whoa, hold on there! I'm innocent as a newborn babe. If you've got a beef with the beer, take it up with the tin cans. They're the ones who served it.}
{501}{}{Maybe the problem is with you. How are you going to fix it?}
{502}{}{Perhaps you're right. Let me ask you something else.}
{503}{}{You bad man. Bad, bad man! Make better!}
{504}{}{Hmm. Me think you right. Question for Earley.}

# Hostile_2
{530}{}{What of it? [He snickers at you.] Look around, pal. See those tin soldiers? Just you try something, you'll be on my "Stupid Fuckup's Hall of Fame". Scram.}
{531}{}{Guns or no guns, you've just said your last words, scum.}
{532}{}{Make sure you watch your back when you're alone.}
{533}{}{[Turn and leave.]}
{534}{}{Me smash! Me crush! You DIE!}
{535}{}{Me hide under you bed. Me hide in you closet. Me wait.}
{536}{}{[Leave.]}

# Bad_Beer_Challenge_intro
{560}{}{Fantastic! Here's the deal. If you can down 10 top-notch craft beers in one go, I'll toss you a cool 3,000 caps. And worry not, the beers are on the house for the Challenge.}
{561}{}{Well, darling. If you can chug down 10 craft beers in one sitting, there'll be 3,000 shiny caps waiting for you. And I'll be happy to pick up the tab for the beers.}
{562}{}{That's a lot of beer, but I think I can handle it. You're on.}
{563}{}{What's the catch?}
{564}{}{10 beers? I'm not sure I can handle that. Can I ask you some questions instead?}
{565}{}{No, thank you. That's not my idea of a good time. Maybe someone else will give it a try.}
{566}{}{Me drink.}
{567}{}{No. Me talk?}

# Bad_Beer_Challenge_anyway
{590}{}{Hold on there, }
{591}{}{! Sure, you're savvy to my little game. But don't forget, there's an easy 3,000 caps up for grabs! That kind of cheddar goes far in these parts. Just knock back 10 brews on the trot.}
{592}{}{That's 3,000 reasons to give it a shot.}
{593}{}{That's a tempting offer, but I don't think it's a good idea. Can I ask you some questions instead?}
{594}{}{No, thanks. I'll be on my way.}
{595}{}{Wow! That much. Me try!}
{596}{}{No beer. Just talk?}
{597}{}{Ah, bad beer. No talk. Bye.}

# Bad_Beer_Challenge_0
{620}{}{Sharp as a tack, aren't ya? I like that. We brew our own beer, and let me tell ya, it's potent stuff. Even super mutants keel over after 8 or 9. So, out of sheer boredom, I started this little Challenge.}
{621}{}{[CONTINUE]}

# Bad_Beer_Challenge_1
{650}{}{I've got more caps than I know what to do with, so I figured I'd set some aside for anyone brave enough to down 10. Now don't get it twisted, I ain't parting with 3,000 caps for peanuts. It's a Challenge, not charity. You've got that glint in your eye that tells me I might be a little lighter in the pocket today. Pull up a stool and give it a whirl. As promised, beers are on me. Why the heck not?}
{651}{}{Alright then, you're on. Line 'em up.}
{652}{}{On second thought, maybe not. Mind if I ask you some questions?}

# Bad_Beer_Challenge_5
{680}{}{Looks like ol' Earley has got the upper hand, eh? Don't sweat it. There's always another day to try your luck.}
{681}{}{[END]}

# Bad_Beer_Challenge_11
{710}{}{Alright then, }
{711}{}{, here's numero uno. After this, you've got 9 more coming!}
{712}{}{[Drink beer.]}
{713}{}{On second thought, I'll pass. Maybe I'll try again another time. Bye.}
{714}{}{Not drink now. Must go.}

# Bad_Beer_Challenge_16
{740}{}{Well now, that didn't ruffle your feathers. One down. [Earley grins like a Cheshire cat.] Ready for the next round?}
{741}{}{Sure thing, bring it on. [Drink beer.]}
{742}{}{Thanks for the free beer, but I'll stop here.}
{743}{}{More! [Drink beer.]}
{744}{}{No more. Must go.}

# Bad_Beer_Challenge_21
{770}{}{Hey, you keep up this pace, those caps will be yours before you know it. Been a while since I had to pay out, but I reckon today could be your lucky day! Another one?}
{771}{}{I haven't quenched my thirst yet. [Drink beer.]}
{772}{}{I don't think so. Maybe another time.}
{773}{}{Mmmm. Good. [Drink beer.]}

# Bad_Beer_Challenge_26
{800}{}{You're really in it to win it, ain't ya? Good on ya. I ain't got time for quitters. Ready for numero 4?}
{801}{}{Number 4 and more. [Drink beer.]}
{802}{}{Thanks, but no thanks. I've had enough for now. Goodbye.}
{803}{}{More for me. [Drink beer.]}
{804}{}{Me have enough. Go now.}

# Bad_Beer_Challenge_31
{830}{}{Here's number 5. Bottoms up.}
{831}{}{*Buuuurrrp!* Okay, ready for the next one. [Drink beer.]}
{832}{}{All done. No more. Thanks, but goodbye.}
{833}{}{*Buuurrp!* Yum! More! [Drink beer]}
{834}{}{Belly full. No more.}

# Bad_Beer_Challenge_36
{860}{}{Well, well. Halfway home. You're gutsier than I pegged. But remember, the second half is the real kicker. Here's number 6.}
{861}{}{Hmm. Seems you're a bit tougher beneath that soft exterior  than you look. Let's see how you handle number 6.}

# Bad_Beer_Challenge_41
{890}{}{Your eyes look like they're swimming! [Earley waves his hand in front of your face.] Yup, you're seeing double. Here, just 4 more to the finish line.}
{891}{}{I don't need to see, I just need to drink. [Drink beer.]}
{892}{}{Which means I should quit while I still can. }
{893}{}{Me good. Me drink. [Drink beer.]}
{894}{}{Me not feel good. Must stop.}

# Bad_Beer_Challenge_46
{920}{}{You've exceeded my expectations, not gonna lie. But maybe it's best to know when to fold. What do you say?}
{921}{}{Are you trying to back out of our bet?}
{922}{}{You might be right. Maybe I'll give it another shot another day. Goodbye.}
{923}{}{Me want caps. You no get away!}
{924}{}{Me done. You right. Go sleep. [Leave.]}

# Bad_Beer_Challenge_47
{950}{}{No! No! Just pondering if you might be overdoing it, that's all. Here, what number were we on? Ah yes, number 7.}
{951}{}{Actually, it's number 8.}
{952}{}{Right, keep 'em coming. [Drink beer.]}
{953}{}{No! Me drink 7. Want 8!}
{954}{}{Ya, next. [Drink beer.]}

# Bad_Beer_Challenge_48
{980}{}{Alrighty then. Number 8, comin' right up!}

# Bad_Beer_Challenge_49
{1010}{}{Alrighty, moving on to number 8. [He's wearing that cheeky grin again.]}
{1011}{}{Thanks. [Drink beer.]}
{1012}{}{Beer good. [Drink beer.]}

# Bad_Beer_Challenge_51
{1040}{}{Not many get this far. Only 2 left. Are you really sure you can handle this, }
{1041}{}{I am, and I'll take number 9. Thank you. [Drink beer.]}
{1042}{}{Me thirsty! [Drink beer.]}

# Bad_Beer_Challenge_56
{1070}{}{Hmmm. [Earley looks more disgruntled than anything.] This is the last one. Are you sure you've actually been drinking these?}
{1071}{}{Yes, I've been drinking them. Now let's finish this. [Drink beer.]}
{1072}{}{Me drink all. Me drink 1 more, too. [Drink beer.]}

# Bad_Beer_Challenge_61
{1100}{}{[Earley rises and begins to slowly pace, examining the floor and your belongings.] I'm just trying to figure out where you stashed all those beers. No one should be able to knock back 10 craft beers.}
{1101}{}{I did drink them all. Look all you want, but I finished them. Now, how about that payment?}
{1102}{}{Just because I drank 10 beers doesn't mean you can't pay up.}
{1103}{}{Me drink all! Me drink all! Where money?}
{1104}{}{Me drink all. Give me money. Me must take money?}

# Bad_Beer_Challenge_Finish_0
{1130}{}{I'm just saying, no one, and I mean no one, can gulp down 10 craft beers.}
{1131}{}{You sat here and watched me drink every single one. Where are my caps?}
{1132}{}{I'm not going to argue about it! Hand over the caps, Earley. Or maybe I should just take them?}
{1133}{}{I've had enough of your weaseling. I'm leaving.}
{1134}{}{Me drink. You pay.}
{1135}{}{Me drink. You pay. Or, me take.}
{1136}{}{Me no like you. Me go.}

# Bad_Beer_Challenge_Finish_1
{1160}{}{Well, a deal's a deal. Here you go. [He tosses a hefty bag of caps onto the floor.]}
{1161}{}{Thank you. Can I ask you some questions now?}
{1162}{}{Thank you. Goodbye.}
{1163}{}{Me get caps! Can ask questions?}
{1164}{}{Money! Money! Money! Me happy!}

# Bad_Beer_Challenge_Finish_2
{1190}{}{Not the smooth-talking type, huh? Well, fine. Here's your reward. [He showers 3,000 caps onto the floor. The sight of caps rolling around catches the eyes of many in the cell block.]}
{1191}{}{[Gather the caps and leave.]}
