# Message file for tbprsn.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see a Floating Eye Bot.}
{101}{}{You see a Floating Eye Bot in the vicinity.}
{102}{}{You see a FEB-II Floating Eye Bot.}

{150}{}{FEB-II successfully repaired the malfunctioning generator.}
{151}{}{You critically fail to repair}
{152}{}{and cause it damage.}
{153}{}{You fail to repair}
{154}{}{This is a brand new FEB-II. Its upper portion houses the CPU, motivator and the sensors. The extending arm below is equipped with a low power energy prod.}
{155}{}{This is a brand new FEB-II but looks like something's wrong with its motivator. Its upper portion houses the CPU, motivator and the sensors. The extending arm below is equipped with a low power energy prod.}

# Node 0 [Floats]
{200}{}{REPAIR REQUEST INITIATED.}
{201}{}{UNABLE TO PERFORM PATROL DUTIES AT THE MOMENT.}
{202}{}{CRITICAL DAMAGE DETECTED! I REPEAT, CRITICAL DAMAGE!}
{203}{}{MALFUNCTION DETECTED. WARNING!}
{204}{}{FURTHER REPAIRS NECESSARY FOR OPTIMAL FUNCTIONALITY.}
{205}{}{SYSTEMS CHECK COMPLETE. PROCEEDING WITH PREVIOUS DIRECTIVE. VAULT POWER LEVEL AT 0%. MOVING TO REPAIR GENERATOR.}
{206}{}{GENERATOR ROOM DOOR LOCKED. REQUESTING ASSISTANCE TO GAIN ACCESS.}
{207}{}{GENERATOR FUNCTIONING AT FULL CAPACITY. VAULT POWER LEVEL RESTORED TO 100%.}
{208}{}{WARNING! LIFE SUPPORT SYSTEMS NOT DETECTED.}
{209}{}{PATROLLING THE AREA FOR POTENTIAL HOSTILE INTRUDERS.}
{210}{}{PRIORITY 1 PATROL IN PROGRESS.}

{300}{}{You successfully repair the damaged Floating Eye Bot.}

