# Grammar pass done

{100}{}{You see the Feeding Machine.}
{101}{}{You spot a machine equipped with robotic arms that handles prisoner meals.}
{102}{}{You successfully hack the Feeding Machine. It will now dispense substantial meals without requiring a password.}

{105}{}{Duh! They updated my password again. The holodisk should be somewhere around here.}
{106}{}{*burp*}
{107}{}{Yuuuuuck! That was a dreadful meal, and it seems to be the only option available.}
{108}{}{Considering it's prison food, that was surprisingly satisfying.}
{109}{}{I feel like I'm about to burst!}
{110}{}{I've had worse meals before. Can't really complain.}
{111}{}{I'm not hungry at the moment so I'll save this for later.}
