# Message file for tbfergie.ssl
# Number of nodes: 51
# Grammar pass done

{100}{}{You see a tomboy.}
{101}{}{You see Fergie.}
{102}{}{A very handsome tomboyish woman.}

# Fergie_1
{230}{}{Hey there! Welcome to Fergie's Lost-and-Found. What can I help you with?}
{231}{}{Hey there, darlin'! Welcome to Fergie's Lost-and-Found. What can I get for you?}
{232}{}{I'd like some information.}
{233}{}{What do you sell here?}
{234}{}{Nevermind, forget it.}

# Fergie_2
{260}{}{Hey again! What can I do for you this time?}
{261}{}{Hey again, darlin'! What can I offer you now?}
{262}{}{I need some information.}
{263}{}{I'm looking for something specific.}
{264}{}{Well, Fergie, how about some company?}

# Fergie_3
{290}{}{What do you want now? All I've got is stuff.}
{291}{}{That's why I'm here, dumbass.}
{292}{}{Answer my questions now!}
{293}{}{Oh, nevermind then.}

# Fergie_sex
{320}{}{Hey there, darlin'! How you doin' this fine, fine day? I was hoping you'd come by today.}
{321}{}{Well, how sweet! My name is }
{322}{}{. What's yours?}
{323}{}{Tankie!}

# Fergie_sex_dumb
{350}{}{Oh, well nevermind, darlin'. I would feel bad taking advantage of someone with special needs. Run along now.}
{351}{}{Ook!}

# Fergie_info
{380}{}{Well, alright. I've got a few minutes to spare.}
{381}{}{What's your name?}
{382}{}{I'm looking for a way to get into the hospital, or the asylum, whatever it is.}
{383}{}{What can you tell me about Tibbets?}
{384}{}{Where are you from?}
{385}{}{I heard that you're Tibbets' resident femme fatale. Is that true?}
{386}{}{You're a handsome gal. Can you entertain me?}
{387}{}{Actually, forget it.}

# Fergie_drink
{410}{}{I've got a variety of things. Feel free to trade with me. I'd love to see what interesting things you have too.}
{411}{}{Well, uh... What do you have?}

# Fergie_info_return
{440}{}{What's next?}
{441}{}{Sorry, what was your name again?}
{442}{}{Could you remind me how to get into the hospital?}
{443}{}{Where are you from, by the way?}
{444}{}{Tell me more about Tibbets.}
{445}{}{I have some bad news. I feel like taking it out on someone, and you've just been nominated.}
{446}{}{Actually, I should get going.}

# Fergie_info_name
{470}{}{I'm Fergie.}
{471}{}{Hi Fergie, I'm }
{472}{}{. What can you tell me about Tibbets?}
{473}{}{I'm }
{474}{}{. I'm looking for the hospital. How do I get in?}
{475}{}{I'm }
{476}{}{. Where are you from, Fergie?}
{477}{}{Hi Fergie, I'm }
{478}{}{. Amuse me?}

# Fergie_info_Hospital
{500}{}{Oh, the hospital? Just climb the stairs outside, and you should be able to get in. It's technically an asylum, but most people prefer to call it a hospital. Just be careful not to do anything foolish, or Seb will shoot you. And be prepared for some weirdos wandering around.}
{501}{}{Thanks a lot. I'll head there now.}
{502}{}{Thanks, but before I go, can I ask you a few more questions?}

# Fergie_drink_menu
{530}{}{Alright, here's what I've got.}
{536}{}{Actually, I have a few more questions.}
{537}{}{I need to get going. Thanks.}

# Fergie_info_Cross
{590}{}{I've been living in Tibbets for years, but I moved here about two years ago. It's a nice place, quite bustling. I've seen all kinds of prisoners passing through.}
{591}{}{Where do these prisoners come from?}

# Fergie_flirt_yes
{620}{}{Sure, darlin'. Here, have a beer from my personal stash.}
{621}{}{Thanks a lot. Can I ask you some more questions?}

# Fergie_flirt_no
{650}{}{Sorry, darlin'. I can't do that. I have better things to do.}
{651}{}{Oh, okay. Do you have anything to trade, then?}
{652}{}{Alright, then. Can I ask you some more questions?}
{653}{}{Alright, I'll check back later.}

# Fergie_info_home
{680}{}{I grew up in Junktown, west of here. When I was about 22, my daddy died during a caravan trip. He was a guard. Shortly after, my momma passed away. She grieved herself to death, lost the will to live. I lived there for a few years, trying to survive. But when I heard about a big junkyard to the east, I came here to find a place of my own. Unfortunately, I got ambushed by robots and couldn't escape.}
{681}{}{Whoa now, I didn't ask for your complete history. I just wanted to know where you're from.}
{682}{}{Oh, that's sad... Hey, um, I'd like to buy a drink.}
{683}{}{Oh, that's sad... Can I ask you some other questions?}
{684}{}{Oh, that's very sad. I need to get going, though. I'll come back when I get thirsty.}

# Fergie_smartass
{710}{}{All right, smartass, from now on, let's keep things strictly business.}
{711}{}{Ah, come on now, don't be like that.}
{712}{}{Whatever, loser. I'll catch you later, cocksucker.}

# Fergie_ignore
{740}{}{I told you, we're strictly business now.}
{741}{}{All right, fine. Let's trade.}
{742}{}{Either you talk to me, or I'll paint this place with your blood.}
{743}{}{Fine, goodbye.}

# Fergie_ignore_menu
{770}{}{All right, here's what I found.}
{776}{}{Nevermind, bye.}

# Fergie_threaten
{800}{}{I hope you're prepared to back up your words 'cause I'm gonna spill your guts on the floor!}
{801}{}{I am. Get ready to die.}
{802}{}{Hold on now! I'm sorry! I didn't mean that...}

# Fergie_smartass_2
{830}{}{No, I hate a smartass. You can go fuck yourself. Since it's my job, I'll still sell you stuff, but that's all you'll be getting from me.}
{831}{}{Okay, fine. Show me what you have.}
{832}{}{I'll tell you what, either you talk to me like normal, or I'll smack you around like a bitch until you do.}
{833}{}{Alright, if I need anything, I'll come back later.}

# Fergie_ignore_bought
{860}{}{Is there anything else I can help you with?}
{861}{}{Actually, yes.}
{862}{}{No, that's all for now.}

# Fergie_ignore_end
{890}{}{Good, now please leave.}
{891}{}{[END]}

# Fergie_ladies
{920}{}{Heh... Where did you hear that? Well, it doesn't matter. It's true though. When it comes to men, I know exactly what to do, when to do it, and how to do it. With my smooth moves and dashing good looks, any man becomes putty in my hands.}
{921}{}{Can you share some secrets with me?}
{922}{}{Interesting. I'd like to trade with you.}

# Fergie_ladies_no
{950}{}{No, I don't want to give out my secrets just yet. Maybe later.}
{951}{}{Oh, well, okay. Can I ask you something else then?}
{952}{}{Tell me your secret now, or I'll force it out of you.}
{953}{}{Alright, keep your secrets. I'm leaving.}

# Fergie_ladies_yes
{980}{}{Normally, I wouldn't do this, but for some reason, I like you. So, here's the first tip: when you see a man you like, walk up to him and start a conversation. Don't be nervous; it turns them off. Be friendly, give compliments, and most importantly, focus your attention on them and avoid distractions.}
{981}{}{Okay, but what should I do to make them bedazzled by me?}

# Fergie_ladies_yes1
{1010}{}{Alright. Here are a few things you can say and do... [After a few minutes, you feel like you've learned a lot about engaging with men.]}
{1011}{}{Thanks a lot, Fergie. I really appreciate your help. Before I go, would you like to trade?}
{1012}{}{Thanks, Fergie. Before I go, could you provide me with some information?}
{1013}{}{Thanks, Fergie. I'm going to try these out right away.}

# Fergie_sex_2
{1040}{}{You're very welcome. A charming man like yourself deserves to be complimented often.}
{1041}{}{My, you're quite the sweet talker. Keep them coming. [You give Fergie a smile.]}
{1042}{}{My, aren't you the smooth talker? I see where this is going. You talk a good game, but I know your tricks.}

# Fergie_sex_smart
{1070}{}{Huh? What are you talking about? }
{1071}{}{You're trying to sweet talk your way into my jumpsuit, you whore. I'm leaving.}
{1072}{}{You're trying to talk your way into my jumpsuit. I loathe your methods, but I'm feeling horny and you're cute so I'm going to allow this to continue.}
{1073}{}{Don't play dumb with me! I know what you're up to, and now I'm going to stop you from manipulating another man ever again.}
# Fergie_sex_screwed
{1100}{}{It's been ages since I saw such a stunning man entering my little store. Please, stand there for a moment while I admire you.}
{1101}{}{Oh, stop. I'm just being myself, heh.}
{1102}{}{Your "little store"?}
{1103}{}{Actually, I have to go now.}

# Fergie_sex_screwed2
{1130}{}{I'm sorry, but I can't resist your allure. I find myself wanting to get to know you better. What's your name? Where are you from? How old are you? Tell you what, I'm going to close the store for a while. I'd like you to join me so we can become better acquainted.}
{1131}{}{Oh, of course. Lead the way, then.}

# Fergie_been_screwed
{1160}{}{[After hours of intense sex.] So was it good for you?}
{1161}{}{You... were... incredible! I still can't believe how good that was! I came eight times. It's going to be days before I can recover.}
{1162}{}{To be honest, I've had better, but I've had worse too.}
{1163}{}{Oh my god! That was awful! I could fuck a brahmin and get better pleasure! It's no wonder you worked up your sweet talkin' skills. You're a horrible fuck! It's probably the only way you can get laid because no man would sleep with you more than once. Loser!}

# Screwed_good
{1190}{}{It was great, wasn't it? Well look, I need to get back to my pastime. Feel free to come by again. If you want, we can do this again sometime.}
{1191}{}{Oh, you better believe it!}
{1192}{}{If I find the time, I will.}

# Screwed_ok
{1220}{}{Hmm... Well it was good for me. Anyways, I need to get back to my usual pastime. I've been gone for too long now. You're more than welcome to come by the store and we can do this again.}
{1221}{}{Umm... Well, I might. Goodbye.}
{1222}{}{I don't think so. I have some very important things to do.}

# Screwed_bad
{1250}{}{You bastard! How dare you?! I gave you the best that I have and this is how you treat me?! To hell with you then! If you come back by the store the only thing you're getting out of me will be trash. Now if you'll excuse me, I'm going back to work. You can show yourself out.}
{1251}{}{Fine! Loser!}
{1252}{}{Just wait 'till I tell the other guys about you. You'll never get a date again!}

# Screwed_bad_threat
{1280}{}{No! You can't do that to me! I'll be ruined! This is why I left home to begin with.}
{1281}{}{Fine, I won't. But I want a free item every time I come by or I'll talk!}
{1282}{}{I can and I will. Unless you have something to buy my silence.}

# Screwed_Blackmail_caps
{1310}{}{Buy your silence... Fine! How much do you want?}
{1311}{}{10 caps every day that I visit you.}
{1312}{}{50 caps every day that I visit you.}
{1313}{}{100 caps every day that I visit you.}

# Screwed_Blackmail_beer
{1340}{}{Fine. I'll give you one free item every day you visit my store. Now get the hell out of here, you bastard!}

# Blackmail_caps_10
{1370}{}{Fine, I'll pay you 10 caps every day I see you. Now leave. Get the hell out of my store!}

# Blackmail_caps_50_success
{1400}{}{Fine, I'll give you 50 caps every time you come in. Now get your ass out of my store!}

# Blackmail_caps_50_fail
{1430}{}{No way!}
{1431}{}{Alright, fine, 10 caps every day then!}
{1432}{}{You'll give me 50 caps every day or I'll tell everyone about your shitty "horizontal performance!"}

# Blackmail_caps_100_success
{1460}{}{Alright! Fine! 100 caps every time you come in! Now, get the hell out of my store! I need to work so I can pay you!}

# Blackmail_caps_100_fail
{1490}{}{No fuckin' way!}
{1491}{}{Fine, make it 50 caps every time I see you.}
{1492}{}{You'll give me 100 caps every day or I'll tell everyone about your shitty "bedroom skills!"}

# Blackmail_caps_failed_combat
{1520}{}{You know what? I just realized, why should I pay you when I can shut you up by killing you? I'll just tell everyone that you tried to rob me.}

# Fergie_sex_smart_sex
{1550}{}{[She stares at you for a few seconds, surprised.] Ok, let's go behind.}
{1551}{}{[Follow her.]}

# Fergie_info_Cross_Car
{1580}{}{Oh, they come from all over the place. Hoover Dam, Fort Aradesh, Ouroboros, tribals... from all corners.}
{1581}{}{Can you give me directions to these places?}
{1582}{}{I see. So, where are you from?}
{1583}{}{Thanks, but I have to be on my way now.}

# Fergie_info_locations
{1610}{}{I can tell you how to get to Fort Aradesh, but I haven't been to the others. The best I can do for them is point you in a general direction, which wouldn't be very helpful.}
{1611}{}{Alright, how do I get to Fort Aradesh?}
{1612}{}{I already know how to get to Fort Aradesh. Let me ask you something else.}
{1613}{}{Let me ask you something else.}

# Fergie_info_directions
{1640}{}{If you have an Automap feature, I can mark it for you. That would be much easier.}
{1641}{}{I have this. [You hand her your Pip-Boy.]}

# Fergie_info_directions_give
{1670}{}{I bet we could get a hefty sum outta' this.}
{1671}{}{I'd say so. Maybe I'll sell it one day. But for now, can you mark Fort Aradesh for me?}

# Fergie_location_FA
{1700}{}{Yeah, okay. [She presses a few buttons, then a few more. She looks confused for a moment, but then she smiles.] Ah... There you go.}
{1701}{}{Thanks. Can I ask you something else now?}
{1702}{}{Thanks. Now, I need to buy something.}
{1703}{}{Thanks, Fergie. I'm going to head that way now. Goodbye.}
