# Message file for tbbatt.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{The man closes his eyes and bows his head, appearing deep in prayer or meditation.}
{101}{}{A sense of tranquility emanates from this person.}
{102}{}{He reminds you of individuals affiliated with cults you've encountered in the past.}

{103}{}{Why would you harm an unarmed Scholar?}
{104}{}{Why were you sneaking around me?}
{105}{}{Soldiers!}
{106}{}{A spy! Soldiers!}

# Node 0 [Floats]
{200}{}{De profundis clamavi ad te, Domine!}
{201}{}{Silence, please. I'm in the midst of meditative contemplation.}
{202}{}{We pursue wisdom as our shield against peril.}
{203}{}{The Doctor insists that knowing our foes will be our key to triumph.}
{204}{}{Greetings.}
{205}{}{Domine, exaudi vocem meam!}
{206}{}{A glorious day to you.}
{207}{}{All wisdom holds sanctity.}
{208}{}{Our self-defense is paramount.}
{209}{}{Who can truly comprehend the happenings in the lower echelons?}
{210}{}{Knowledge equates to life itself.}
{211}{}{The Doctor aids us in comprehending the sanctity of knowledge.}
{212}{}{The Doctor fuels our quest to restore what has been lost.}
{213}{}{I need to discover a new tome.}
{214}{}{One day, we will safely unearth the wisdom necessary to reestablish civilization.}
{215}{}{Isn't it splendid that the robots no longer pose a threat, albeit temporarily?}
{216}{}{A glorious day to you.}
{217}{}{We're not here for idle chatter.}
{218}{}{I would follow the General to the end.}
{219}{}{This mission carries significant weight.}
{220}{}{The General insists on inflicting maximal damage.}
{221}{}{Who's the next adversary to meet their end?}
{222}{}{Why are you engaging me in conversation?}
{223}{}{I have no fondness for these mechanical shitheads, to put it mildly.}
{224}{}{This situation could turn treacherous.}
{225}{}{It's time to depart.}
{226}{}{This place resembles a dreadful display of decay.}
{227}{}{I feel a wave of nausea coming on.}
