# Message file for tbgabrie.ssl
# Number of nodes: 32
# Grammar pass done

{100}{}{You spot a young woman observing the robots from the shadows.}
{101}{}{You see Gabrielle Wiry, the watchful observer of robots.}
{102}{}{A confident teenage girl, though she appears smaller than her age suggests.}

# Gabrielle has been accused of the murder of Angela by the PC.
{200}{}{No way, I didn't do anything! Swear on my life!}
{201}{}{I didn't off Angela, man, I'm telling you the straight truth!}
{202}{}{Please, you gotta believe me, I'd never lay a finger on Angela!}

# The PC has not accused Gabrielle.
{230}{}{Told ya, didn't I? I didn't have anything to do with it!}
{231}{}{So they finally nabbed the creep who did Angela in, huh?}
{232}{}{Of course I'm not the killer! You never thought it was me, right?}

# General floats
{260}{}{These robots are total snorefests, aren't they?}
{261}{}{One day, I'm gonna have my own crib.}
{262}{}{I won't be stuck in this dump forever.}

# Node01
{320}{}{[The girl watches the robots intently.]}
{321}{}{Um, hi?}
{322}{}{Hello!}

# Node02
{350}{}{Dude! What are you doing, creeping up on me like that? Never seen your face before. What's your deal?}
{351}{}{I'm }
{352}{}{. Who are you, and what's with all the robot-watching?}
{353}{}{Anything interesting happening in Tibbets?}
{354}{}{Look, kid. I'm tired, I stink, and I'm dying of thirst. So, please, point me to the nearest bar.}
{355}{}{Nothing. Sorry to bother you. Goodbye.}
{356}{}{Me sad about Angela. Where you when she die?}
{357}{}{Me like robos. You too?}
{358}{}{Nothing. Bye-bye.}

# Node03
{380}{}{Sup?}
{381}{}{About Angela...}
{382}{}{Where were you on the night Angela died, Gabrielle?}
{383}{}{What do you do here, exactly?}
{384}{}{That's all. Goodbye.}
{385}{}{Nothing. Me go.}

# Questions
{410}{}{What do you wanna know?}

# Node04
{440}{}{I'm Gabrielle Wiry, just chillin' watching these robots. They're kinda boring, but they kill time. Plus, Magik doesn't come around here, so he can't bug me or my folks.}
{441}{}{Really? How old are you, Gabrielle? 15, 16? Shouldn't you be more interested in boys or playing with dolls at your age?}
{442}{}{There's something else I wanted to ask you.}
{443}{}{Interesting. See you around.}

# Node05
{470}{}{There's basically three groups here: the bots, the jailbirds, and the Sheriff's crew. They're what makes this place tick.}
{471}{}{Tell me more about the robots.}
{472}{}{What can you tell me about the prisoners?}
{473}{}{What's the deal with the Sheriff's people?}
{474}{}{I had another question, actually.}

# Node06
{500}{}{The Atom is where it's at. The robots run the joint, but it's kinda meh. Angela's always around there. [She blushes and looks down at her sneakers.]}
{501}{}{Angela, huh? Do you have feelings for her or something?}
{502}{}{As long as there's booze, who cares about the staff? See you later, kid.}

# Node07
{530}{}{Hey, I might look like a kid, but I got a pretty old soul! I have big plans for the future. Just surviving for now, but you'll see, I'm busting out of here someday.}
{531}{}{Well, good luck with that. Let me ask you something else.}
{532}{}{Sure, keep dreaming. See you around.}

# Node08
{560}{}{The robots take a ton of pride, if that's even a thing for them, in their work. They've been at it for years, and it's like a real tradition. The Warden keeps things on track, and the Sheriff and his crew help out too. They're way better with people than the bots.}
{561}{}{What exactly do they do?}
{562}{}{That's all I needed to know. Thanks, kid.}

# Node09
{590}{}{Well, there's always fresh meat getting thrown in here. Some were even born in this joint. But only a handful have ever made it out. But then again...}
{591}{}{But then again?}

# Node10
{620}{}{All I know is, don't break the law when they're around. If you really wanna know more, go check out cell block 30.}
{621}{}{Maybe I will. Let me ask you something else.}
{622}{}{Thanks, Gabrielle. Goodbye.}

# Node11
{650}{}{I think they're like prisoners who got a second chance. They're given the opportunity to work and make a living instead of being caged like us. I'm determined to make something out of my life, not end up like those poor suckers in there.}
{651}{}{What can you tell me about the Warden and the robots?}
{652}{}{Sounds good. See you later, Gabrielle.}

# Node12
{680}{}{The Warden's got all the answers. No one really knows what happens to the reformed prisoners. Only the Warden knows for sure.}
{681}{}{Hopefully, I won't have to deal with that. Tell me about something else.}
{682}{}{I'll definitely need to speak with the Warden. Take care, Gabrielle.}

# Node13
{710}{}{So, like, I totally think the Warden knows every single thing that goes down here. The bots? They're basically his fan club. I peeped one of them, like, pulling apart a screen and guess what? Cam on the inside. They're doing all sorts of stuff, like babysitting the factories, playing teacher, slinging drinks, playing tough guy, and fixing stuff. Yeah, the factory gig is hard, but at least they're banking more than we are.}
{711}{}{I'm not really into robotics, but tell me more about this place.}
{712}{}{Good pay, huh? I might consider checking them out. Thanks, kid. See you around.}

# Node14
{740}{}{So, like, for real, I think Angela kinda digs robots too. But it's not the same as my obsession, y'know? She's always hanging at the bar, and I've tried to roll up there, but I just keep getting booted. Probably doesn't even know I'm on this planet, honestly. Wish we could be buds, though.}
{741}{}{Sorry, Gabrielle, but hanging out in bars isn't suitable for someone your age.}
{742}{}{Well, I suppose I could talk to her and put in a good word for you...}
{743}{}{Maybe she's not worth your time anyway. Let me ask you something else.}
{744}{}{Life isn't always fair, but keep your spirits up, kid. Take care.}

# Node15
{770}{}{What!? For real? You're gonna, like, hook us up? Would you seriously do that?}
{771}{}{I guess I could give it a shot. Who knows, maybe it'll work out.}
{772}{}{On second thought, maybe it's not a good idea. I have another question for you...}
{773}{}{Actually, no. It doesn't seem like a good match. See you later.}

# Node16
{800}{}{Thanks a ton! You're totally awesome!}
{801}{}{Thanks a bunch! I owe you big time.}
{802}{}{I'll let you go, but I have one more thing to ask.}
{803}{}{Sure thing. Take care now.}

# Node17
{830}{}{What's up?}
{831}{}{Sorry, pal. Looks like Angela isn't interested in being your friend. It happens, don't worry. }
{832}{}{Unfortunately, Angela doesn't seem to have the same feelings. Keep your head up, kid.}
{833}{}{Well, guess what? Angela is actually *really* into robots. It's a bit strange, but hey, there are plenty of other potential friends here.}
{834}{}{No worries. Let's talk about something else.}

# Node18
{860}{}{Oh, I get it. Well, thanks for giving it a shot anyway.}
{861}{}{Tough break. Take care, Gabrielle.}

# Node19
{890}{}{Seriously, don't give me that crap. We have a ton in common. What is she? Some kind of robot freak?}
{891}{}{Actually, yeah. But keep it between us. She doesn't want everyone in Tibbets to know.}
{892}{}{Believe what you want. Take care, Gabrielle.}

# Node20
{920}{}{Well, I'm not too busted about it. Now I can focus on my weird love for watching bots!}
{921}{}{Attagirl! See you around, Gabrielle.}
{922}{}{Yeah, whatever. Goodbye.}

# Node21
{950}{}{What the hell? Are you trying to pin something on me? I was in my cell all night. Don't you dare pin that robo-bitch's mess on me.}
{951}{}{You seem quite hostile towards her "fascination" with robots, Gabrielle. Is there something you want to share?}
{952}{}{Alright then, goodbye for now.}

# Node22
{980}{}{Well, okay, it did bug me more than I let on. It's just really weird to have these strong feels for bots. But accusing me of murder? That's bonkers!}
{981}{}{I'm not sure what to believe. I'll return if I have further questions.}
{982}{}{No, I believe you. Goodbye for now.}

# Stupid1
{1010}{}{No! Well, yeah. I enjoy watching them - they do all sorts of funny things when they think we're not watching. Hehehe.}
{1011}{}{You in love?}
{1012}{}{Me go watch robo some more.}

# Stupid2
{1040}{}{No, I mean, I'm not in love with them. They just help me forget about this dump.}
{1041}{}{Me need fun. Maybe me watch with you?}
{1042}{}{Ah, me see now. Bye-bye.}

# Stupid3
{1070}{}{As you wish. You know, you can work with them in the factories or at Waste Disposal if you're looking to earn some caps. The elevator pass is "SCRUBBA-DUBBA".}
{1071}{}{Okay - me do that. Bye-bye.}
{1072}{}{Me just watch for fun. Me go.}

# Stupid4
{1100}{}{Huh? No offense, but you don't really seem like the detective type. But for what it's worth - I was in my cell all night. My mom and dad can vouch for me.}
{1101}{}{Me think you lying. You kill Angela?}
{1102}{}{Okay - you in clear now. Me go track down real killer.}

# Stupid5
{1130}{}{No! Just drop it, alright? I've humored your questions, but this is crossing a line. Just focus on watching the robots - you enjoy that, right?}
{1131}{}{That true - me like robo. Bye bye.}
{1132}{}{You no distract me - if me find you do it, you in big trouble. Me go now.}
