# Message file for tbgran.ssl
# Number of nodes: 42
# Grammar pass done

{100}{}{You see an old, frail lady.}
{101}{}{You see Granny Spider.}
{102}{}{You can hear her humming some ancient ritual song to herself.}

# Node001
{200}{}{Bless up, mi yute. I and I did feel yuh spirit a come cross these steel corridors, 'cause I sight your feathers inna mi dreams, y'know. *cough* *cough* Long time back, nuff moon cycles ago, when I an' I was jus' a likkle xander root. *cough* And now, here again, seen?}
{201}{}{Dreams? What kind of dreams?}
{202}{}{So, you've been dreaming about me, huh? Well, I do have an effect on the ladies.}
{203}{}{Granny, ease up on the drugs.}
{204}{}{How did you end up here in the first place?}
{205}{}{That's a nasty cough you've got there. Are you feeling unwell?}
{206}{}{Oops, wrong cell. Sorry.}
{207}{}{Me no bird!}
{208}{}{Me go. Bye bye.}

# Node003
{230}{}{[She makes a circular motion in the air and warmly smiles, revealing a row of sharpened teeth.] Show love to all, hate none. *cough* 'Cept dem who deserve a thousand death. *cough*}
{231}{}{What's with the teeth? Are you a cannibal?}
{232}{}{You mentioned something about a dream.}
{233}{}{[Make a random sign in the air.] Peace, grandma. I need to go.}

# Node004
{260}{}{The metal tomb *cough* tek away, but also *cough* give. The doc dem 'round here can't tell if it's 'cause a mi age or some duppy tek hold a mi body. Can't reach mi healing powders here. Nothing a likkle broc flower, xander root, and darka mushroom couldn't sort out, y'know.}
{261}{}{There are doctors here too?}
{262}{}{Can you teach me how to make those healing powders?}
{263}{}{Tell me something...}

# Node005
{290}{}{Eatin' the flesh of another bring 'bout a thousand snakes. *cough* Mi husband an' our pickney dem all have dem teet sharpen. A family ting dat, not one of our tribe. [She shut her eyes and press her fist 'gainst her chest.] Oh Spider Granny, we a your pickney dem. Bless we, guide we, an' show we your ways. Hey, hey, hey. *cough*}
{291}{}{Spider Grandmother?}
{292}{}{Let's change the subject. I've never been much into religion.}
{293}{}{Well, it's time for me to leave you to your prayers.}

# Node006
{320}{}{When I was just a baby bird, *cough* I and I dream many time say mi life woulda end inna what ancient text call the iron maiden - a metal tomb mi couldn't escape from. *cough* A dark stranger with a jangling set a keys do dat to mi. I and I couldn't see him face, but mi memba di sounds. When him move, him foot dem make sounds like hooves.}
{321}{}{Was he a mutant?}
{322}{}{Brahmin-man?}

# Node011
{350}{}{Him lead I and I cross a desert, play trick pon mi into steppin' inna di iron maiden disguise as a totem. *cough* Mi coulda hear him evil cackle as him stride off into di sunset. Mi pain make him laugh. *cough* As mi deh inside, dyin', a savior, just like you, forward an' rescue I and I. Dat's when mi whisper a warning inna mi savior's ear...}
{351}{}{A warning?}
{352}{}{Huh?}

# Node002
{380}{}{The devil a go trod 'pon these lands again... And hold the keys to the gates of hell... We a go link up again when the time is right... That's the dream I did have before, and now I have it again. It always end with my spirit departing for the happy hunting ground, seen?}
{381}{}{When the time is right?!}
{382}{}{This is the biggest load of brahmacrap I've heard. And I've heard lots of it over the years. Congrats.}
{383}{}{Righti Tim?}
{384}{}{Brahma crap!}

# Node018
{410}{}{You fi play your part, eagle. Fi act. Fi strike down the devil once more, just like in mi dream.}
{411}{}{I'm nobody. The wasteland is filled with devils. I can't fix the entire world. What do you want from me?}
{412}{}{Let him come. I'm }
{413}{}{ and I'll deal with whatever comes my way.}
{414}{}{Me no hero. Me moron.}
{415}{}{Me kick their groins!}

# Node014
{440}{}{Strength and honor, eagle. *cough* Granny Spider trust say your spirit ago find a way.}
{441}{}{Grandma Spider?}
{442}{}{We'll see. But before that, tell me this...}
{443}{}{I'm off to find the way. Farewell.}

# Node007
{470}{}{Healing powder ain't no drug, but a powerful gift from Mama Earth. *cough* Show respeck, eagle, and it a go show you where fi find everything you need. *cough*}
{471}{}{Can it show me where to find a working laser rifle? That's what I need right now.}
{472}{}{Can you teach me how to make healing powder?}
{473}{}{I don't trust nature. There are some nasty shits out there that look like they came straight out of a lunatic's nightmare.}

# Node008
{500}{}{*cough* Aam-i-humm, humm, humm, aam-i-humm, humm, humm, aam-i-o, o, o, o, aam-i-o, o, o, o, aam-i-o. *cough*}
{501}{}{[Join in.] Humm, humm, aam-i-humm, o, o, o, humm.}
{502}{}{[Join in.] Hurm-am- hurm-hyuo-hyuo-o. Hu-ha-hu-ha.}
{503}{}{Ahem. I have some questions.}
{504}{}{I'll leave you to your prayers.}
{505}{}{You magic woman? Teach no-hurtie dust?}
{506}{}{[Shamble off.]}

# Node009
{530}{}{One thing, eagle. If you ever meet mi pickney dem, tell dem... *cough* ... tell dem their mom think 'bout her little ones every day.}
{531}{}{How will I recognize them?}
{532}{}{I wish someone would think of me too. Maybe someone is, but I don't know.}
{533}{}{I can't promise that. First, I need to find a way out of here. Farewell.}
{534}{}{Sure, sure. If I ever see them, I'll pass on your message.}
{535}{}{Lil' ones? How know?}

# Node010
{560}{}{Oh, you ago know, seen. [She smiles, revealing her sharpened teeth.]}
{561}{}{Ah, I understand now. Farewell, dear old lady.}
{562}{}{I'll need more than a hunch, old lady.}
{563}{}{Oki!}
{564}{}{Do they have names?}

# Node012
{590}{}{Haha, yuh got a irie sense of humor, eagle. *cough* But make mi give yuh a piece a wisdom: listen good and keep your eyes wide open. You'll find what you're searching for, even a blazing light gun! With that, yuh can mash up those wicked robots into likkle pieces. *cough* Sound fulfilling, don't it?}
{591}{}{Thanks for the advice. I'll try to trust in it more. Goodbye.}
{592}{}{I have another question.}

# Node013
{620}{}{Them lowdown Great Bear warriors tek weh mi precious fruit basket. *cough* So mi tek a bite outta one a them. Them respond by fling mi inna a jail cell, and the next thing mi know, I and I wake up here.}
{621}{}{That's quite interesting. I'll do my best to uncover the truth behind Tibbets.}
{622}{}{I'll make sure those NCR bastards pay for what they've done!}
{623}{}{I'm a sort of a citizen of the New California Republic.}
{624}{}{Actually, I happen to be a something like a citizen of the New California Republic. And we're not "evil". Please apologize.}

# Node015
{650}{}{There a way you can tell your folks to make we live in peace? *cough* We wish fi live in harmony and not under the totem of the Great Bear.}
{651}{}{I don't have the authority to make such decisions, and I can't guarantee our escape from here either. However, if the opportunity arises, I will convey your message.}
{652}{}{I won't betray my people and the Republic! I won't entertain your request. Fuck you and your little tribe.}

# Node016
{680}{}{Give thanks, eagle. *cough*}
{681}{}{I must take my leave now.}
{682}{}{Me ask.}
{683}{}{Me go.}

# Node017
{710}{}{[She falls silent and lowers her head. Then she begins to hum a prayer.]}
{711}{}{[END]}

# Node019
{740}{}{Good job. *cough* You a quick learner.}
{741}{}{I'm the best! Let them come, I'll triumph in every test of skill!}
{742}{}{Answer me this...}
{743}{}{Heh, thank you, dear old lady. Goodbye.}
{744}{}{Hughhh!}
{745}{}{[Bang your chest.] Haug!}

# Node020
{770}{}{That was kinda unfortunate. *cough* I and I sorry, eagle, but your singing sound like a hurt gecko. Maybe you should try play the flute instead. *cough*}
{771}{}{Hmph! An apology would be appropriate.}
{772}{}{I'll make an effort to improve.}
{773}{}{Bitch!}
{774}{}{Whatever! I still have some questions though.}

# Node021
{799}{}{You forget say mi show you how fi prepare them? Mi sure you write it down inna your likkle gadget there, Mr. Fixit, wasn't it?}
{800}{}{I and I will, but you have to watch mi prepare it first. *cough* Forward back when you find the broc flowers, xander roots, and darka mushrooms. *cough* Broc flowers grow near water, and xander roots can be found inna the drylands. *cough* Darka mushrooms thrive in dark, cool places with likkle light. But don't stress if you can't find any; they're not essential. Walk good, mi yute.}
{801}{}{Understood, I'll be back when I have them.}
{802}{}{I've already gathered all three ingredients. Here they are. Now, show me how to prepare them.}
{803}{}{Here are the broc flowers and xander roots. Now, show me the next step.}
{804}{}{Broc! Xander!}
{805}{}{Broc! Xander! Shroom!}
{806}{}{Oh, right! I completely forgot!}

# Node022
{830}{}{[She retrieves some white chalk and a small pouch from her locker. She proceeds to sit down and carefully draws an image of a spider, arranging red stones over its back and eyes.] Please, tek a seat, eagle.}
{831}{}{[Sit down.]}

# Node023
{860}{}{*sigh* Sadly, someone did teef mi precious ruby record keepers. Without them, I and I can't carry out the ritual.}
{861}{}{Are those stones absolutely necessary for the ritual?}
{862}{}{Are these the stones you're referring to?}
{863}{}{[Show her the pouch with red stones.] Peebles?}
{864}{}{[Shrug your shoulders and leave.]}

# Node024
{890}{}{Yes! Where you find them?}
{891}{}{I, uhh... someone traded them to me. I got them in exchange for a bottle of beer.}
{892}{}{Actually, I must confess that it was I who took them.}
{893}{}{I'm sorry, but it was me who took them.}
{894}{}{D'nno.}

# Node025
{920}{}{Maybe, but I and I don't vibrate with their ways. *cough* Mi people have dem own customs and beliefs.}
{921}{}{Very well. I have a question for you.}
{922}{}{Stimpaks are unbeatable! Farewell.}

# Node026
{950}{}{Ask weh yuh want, mi yute. *cough* I and I a go offer mi help if mi can.}
{951}{}{You mentioned something about a dream?}
{952}{}{May I know your name?}
{953}{}{I have some broc flowers and xander roots. Can you teach me how to create healing powders?}
{954}{}{I have broc flowers, xander roots, and darka mushrooms. Can you teach me how to utilize them for healing purposes?}
{955}{}{Actually, I must take my leave.}

# Node027
{980}{}{I and I known as Granny Spider, named after we creator, Spider Granny. *cough* It's both a great honor and a heavy load.}
{981}{}{What makes you say that?}
{982}{}{Wait, so you're called Grandmother Spider because you were named after Spider Grandmother, right? I assume your parents didn't name you "Grandmother" at birth... did they?}

# Node028
{1010}{}{Everyone expect mi help, eagle, but no one offer assistance in return. *cough* Mi have a matter fi which mi need help.}
{1011}{}{Apologies, but I am unable to assist at the moment. I have other pressing matters.}
{1012}{}{I could provide assistance, but it would come at a price.}
{1013}{}{I can help! What do you need assistance with?}

# Node029
{1040}{}{I and I only got wisdom to give.*cough* Yuh know how to create healing powders?}
{1041}{}{No, but I'm eager to learn. Please teach me!}
{1042}{}{Indeed, I have acquired the knowledge of crafting healing powders through practice.}
{1043}{}{No, and I have no interest in learning. Farewell.}

# Node030
{1070}{}{That's excellent. *cough* I and I can create a treasure map fi yuh, revealing the hiding spots of the items stolen by the Great Bear warriors.}
{1071}{}{Alright, you have my interest. However, there's no need for a map. Just indicate the location on my Pip-Boy. Now, what do you need me to do?}
{1072}{}{Still not interested, I'm afraid.}
{1073}{}{Alright, you've piqued my curiosity. I'm willing to help. What's the task at hand?}

# Node031
{1100}{}{That's commendable. *cough* You possess the heart of a true warrior, eagle.}
{1101}{}{I must depart now.}
{1102}{}{Tell me something else.}
{1103}{}{I am the best. That's right, }
{1104}{}{.}
{1105}{}{Me go now.}

# Node032
{1130}{}{Spider Granny a di mother of all. *cough* She watch over and guide you, eagle.}
{1131}{}{That's reassuring. I must be on my way now.}

# Node033
{1160}{}{Indeed, that's true. *cough* Yuh not the first one to be puzzled by it. However, mi given name at birth was Ameline.}
{1161}{}{Could we change the subject, please?}
{1162}{}{My mind is weary. I need some rest.}

# Node034
{1190}{}{Please follow mi lead. *cough*}
{1191}{}{Alright.}

# Node035
{1220}{}{Oh Spider Granny, we are your pickney. *cough* Bless we, guide we, and light up your path for us. Hey hey hey.}
{1221}{}{Oh Spider Granny, we are your pickney. *cough* Bless we, guide we, and light up your path for us. Hey hey hey.}
{1222}{}{Hey hey hey.}

# Node036
{1250}{}{[She gracefully tosses the powder into the air.] Blessings a flow from the upper world. *cough*}
{1251}{}{[Toss the powder into the air.] Blessings a flow from the upper world.}
{1252}{}{[Toss the powder into the air.] Bless up!}

# Node037
{1280}{}{[She gently sprinkles the powder on the ground.] Blessings a rise from the lower world. *cough*}
{1281}{}{[Sprinkle some powder on the ground.] Blessings a rise from the lower world.}
{1282}{}{[Sprinkle some powder on the ground.] Bless down!}

# Node038
{1310}{}{Spider Granny weaves at her sacred loom, and the patterns she weaves become so. *cough* She is of this world, the world above, and the world below. As she weaves, her patterns come to life. Now, she sit at her loom, weaving the healing powder for I and I. *cough* Thank you for the blessings you spin for I and I.}
{1311}{}{Thank you for the blessings you spin for me.}
{1312}{}{Is the healing powder ready?}
{1313}{}{Song over?}
{1314}{}{Thank old spider lady!}

# Node039
{1340}{}{Yes... yes, it is. *cough* Well done, mi yute.}
{1341}{}{Thank you.}
{1342}{}{Bye-bye.}

# Node040
{1370}{}{That was well done, mi yute. *cough* *cough*}
{1371}{}{I appreciate it. Thank you.}

# Node041
{1400}{}{Yes, mi yute. *cough* They are, but I and I must find them first.}
{1401}{}{That's disappointing. Tell me something else instead.}
{1402}{}{If I find them, I'll bring them to you. Goodbye.}

# Node042
{1430}{}{[She takes the pouch and carefully arranges its contents on the spider drawing, forming a beautiful white and red pattern on the spider's back and eyes. She then sits on the floor, inviting you to join her in the ritual.]}

# Node043
{1460}{}{Sulik-n-Kurisu, mi pickney dem.}
{1461}{}{Alright, I'll write that down. Tell me something else.}
{1462}{}{Got it. Farewell.}
