# Message file for tbhocus.ssl
# Number of nodes: 6
# Grammar pass done

{100}{}{You see a person with heavily scarred skin.}
{101}{}{You see Hocus.}
{102}{}{He gazes at you with his sunken, haunting eyes.}

# Node_001
{200}{}{I noticed you talking to Eugene over there. Just a word of caution, Wiggie owes a substantial debt to someone called the Mechanic, so he's hiding here. Keep an eye out for him. He's been afflicted with a severe case of crazies. Also, Dr. Yvreth has been asking to see you. There's no right, there's no wrong, there's only popular opinion. Take care, you.}
{201}{}{Perhaps he perceives things beyond our grasp.}
{202}{}{Thank you for the heads up. What makes you think he's crazy?}
{203}{}{Is that Wiggie over there? He does strike me as peculiar, but harmless.}

# Node_002
{230}{}{Right, like you're any less eccentric than he is.}
{231}{}{Farewell.}

# Node_003
{260}{}{He's consumed by paranoia. First, it was the Mechanic. Then, he believed robots were out to get him. Just last week, he thought Dr. Carl was possessed by a ghost residing within that large "Mr. Nixon" doll. Trust me, Wiggie's lost his grip on reality.}
{261}{}{I'm inclined to believe he poses no threat.}
{262}{}{I'll exercise caution when dealing with him.}

# Node_004
{290}{}{That's what you say now. Wait until he deems you some kind of monster and comes after you with a blade.}
{291}{}{He actually resorted to violence?}
{292}{}{He's unwell, that's all.}

# Node_005
{320}{}{[He reveals a faint scar along his collarbone.] Twice. Just keep your distance from him.}
{321}{}{It seems like he's in need of assistance.}
{322}{}{I think I'll heed your advice.}

# Node_006
{350}{}{He may be sick, but he's beyond help. They should take measures before he harms someone.}
{351}{}{I'll keep that in mind.}
