# Message file for tblowell.ssl
# Number of nodes: 23
# Grammar pass done

{100}{}{You see an old man.}
{101}{}{You see Captain Lowell.}
{102}{}{He has a scar on his face, and the smell of booze lingers on his jumpsuit.}

# AA
{200}{}{[As you approach, the old man's darting eyes catch your footsteps. He looks up from the Pip-Boy maps he's studying and turns to face you.] Huh... What! Who are you? Who sent you!?}
{201}{}{Who the hell are you?}
{202}{}{Um... I'm }
{203}{}{, and you would be?}
{204}{}{No one sent me, I'm just a prisoner. And you are?}
{205}{}{Sorry, I must have walked into the wrong cell. I'll just let myself out.}

# BB
{230}{}{Wouldn't you like to know!}
{231}{}{Yeah, whatever. Look, can I ask you a couple of questions?}
{232}{}{Heh... I was just kidding with you. My name is }
{233}{}{Wow, you got me there. So long.}

# CC
{260}{}{I *would be* Captain Lowell, of Fort Aradesh. What business do you have here?}
{261}{}{Fort Aradesh? Where's that?}
{262}{}{Just passing through.}
{263}{}{I actually wanted to ask you some questions.}
{264}{}{Well, that's my business, isn't it?}
{265}{}{Maybe we could finish this conversation later. I've got something to attend to.}

# DD
{290}{}{I prefer to be called Captain Lowell. I was stationed at NCR's Fort Aradesh once. What business do you have here, stranger?}

# FF
{320}{}{Well, if you need anything at all, be sure to let me know.}
{321}{}{Actually, there was something...}
{322}{}{Will do.}

# GG
{350}{}{Well, what can I do for you?}
{351}{}{What can you tell me about the prison?}
{352}{}{I don't mean to be rude, but could you tell me how you got that scar on your face?}
{353}{}{Where does Tibbets get its medical supplies?}
{354}{}{Never mind, I have to get going.}

# HH
{380}{}{Oh, that's your business, is it? Well, then why don't you go about it and leave me in peace!}
{381}{}{[END]}

# II
{410}{}{Let me show you on my Pip-Boy. The last time I was there, the Fort was in a bad shape. Keep that in mind.}
{411}{}{Yeah, whatever. Let me ask you something else.}
{412}{}{I don't have time for this.}

# JJ
{440}{}{It's a cage... and it's filled with mechanical rats! Very dirty, those critters.}
{441}{}{Yeah, I know that, but why are the robots here?}
{442}{}{Um... okay. Let me ask you something else.}
{443}{}{Ya know what, I think I'll just go and find out for myself.}

# KK
{470}{}{[Suddenly, Lowell's smirk drops, and bitterness surfaces in his expression.] It was the Beast...}
{471}{}{The Beast?}
{472}{}{Okay, whatever. Let me ask you something...}
{473}{}{Oh, hold that thought. I'll be right back...}

# LL
{500}{}{Medical supplies? You mean drugs? I don't know anything about no drugs... [Lowell looks around to make sure no one is listening. He leans in close and whispers to you...] Watch out for the "Hospital." It's top-secret stuff.}
{501}{}{The Hospital? What do you mean?}
{502}{}{[You lean in and whisper.] Top-secret?}
{503}{}{Okay, okay. Let me ask you something else.}
{504}{}{Thanks for the advice. I'm going to get going now. Bye!}

# MM
{530}{}{It was an ordinary day like any other. I was just finishing writing my Captain's Log for the day when I decided to take a stroll by the lake. Little did I know that I was being stalked by a member of Caesar's Legion, a huge eastern tribe! The Beast attacked me, gave me this scar. Luckily, I had my revolver on me and blew a hole right in the Beast's shoulder! That scared it right off. Been looking for it ever since.}
{531}{}{Any luck finding it?}
{532}{}{What did this "Beast" exactly look like?}
{533}{}{Can I ask you something else?}
{534}{}{Why don't you tell me the rest later? I have to get going.}

# PP
{560}{}{I suppose you should ask them.}
{561}{}{And they will answer?}
{562}{}{Let me ask you something else.}
{563}{}{Okay, I think I'll do that.}

# QQ
{590}{}{No! Yes! Depends on which one you ask. You must be out of yer mind, laddy.}
{591}{}{No! Yes! Depends on which one you ask. You must be out of yer mind, lady.}
{592}{}{Okay, I think I'll go talk to them. Thanks for the information.}

# RR
{620}{}{Hospital? I don't know anything 'bout any Hospital! Who are you working for? You a detective?}
{621}{}{Aren't you the Captain? Shouldn't you know something about the authority here?}
{622}{}{No, I'm not a detective!}
{623}{}{Okay... Let me ask you something else.}
{624}{}{That's nice, but I have to be going now.}

# SS
{650}{}{A couple of years ago, I fell ill and was staying in our Medical Treatment Area. Then I overheard the doctors speaking about a "Hospital." But not the one I was staying in, another one! It seems it's somewhere near, surrounded by mountains, but you can't reach it on foot.}
{651}{}{Where's this Hospital?}
{652}{}{Oh! Look at the time. Bye now!}
{653}{}{Yeah, yeah, I get it. Let me ask you something else.}

# TT
{680}{}{Feeding machine? I haven't been near Rake's feeding machine. I don't even know who Rake is! Are you with the Warden?}
{681}{}{Umm, who's Rake?}
{682}{}{I'm not with the Warden! You are, old man!}
{683}{}{Let me ask you something else...}
{684}{}{Let's finish this conversation later. I have to get going.}
{685}{}{Ah yes, Rake. That super mutant from cell block 15.}

# UU
{710}{}{Oh, he's a super mutant here in Tibbets. He used to be a farmer.}
{711}{}{Really? I think I'll pay this "farmer" Rake a visit.}

# VV
{740}{}{For the last time, I prefer to be called Captain!}
{741}{}{Okay "Captain". Let me ask you something else.}
{742}{}{Sorry, Captain, but I have to get going.}

# WW
{770}{}{Rake? I don't know no Rake! Who sent you... *hic*}

# XX
{800}{}{Not yet. The Beast covers its tracks well. Although, I hear there are lots of Beasts east of here. I'd go and find out for myself, but the prison keeps me here.}
{801}{}{What did it look like?}
{802}{}{I could go look for the Beast. If I ever get out.}
{803}{}{Well, good luck with that.}

# YY
{830}{}{It was dark out. Didn't get a very good look, ya know? All I saw were the great claw gauntlets and its tribal armor. I can still hear the scream. [He grimaces.] Uggh.}
{831}{}{Any luck hunting down this Beast?}
{832}{}{Nice talking to you.}

# ZZ
{860}{}{You would? That's mighty kind of you. I need all the help I can get finding the Beast. You'll know the Beast by the scar it should have on its left shoulder where my bullet wounded it.}
{861}{}{Great, but before I go, let me ask you something else.}
{862}{}{Great, I'll get right on it.}
