# Message file for tblucky.ssl
# Number of nodes: 25
# Grammar pass done

{100}{}{You see a redneck. He's missing his legs.}
{101}{}{You see Lucky Legless.}
{102}{}{You see Lucky Legless, a farmer turned prisoner. He's weathered and has a distinct odor.}

# show when attacking the robots
{200}{}{Burn! Hahahaha!}
{201}{}{I'm coming for ya!}
{202}{}{Ye're gonna die, robot!}
{203}{}{Hey, Warden, watch out!}
{204}{}{Kill 'em all, kill 'em quick!}

# show when PC has agreed to help rid of robots
{230}{}{Good to hear from ya, pardner!}
{231}{}{Hello, friend.}
{232}{}{I hope I'm not disturbin' the mishin'.}
{233}{}{Yer doing the Lord's work!}
{234}{}{Let us hope fer another good year.}
{235}{}{Sheriff might lend ya sum shotgun shells, dunno.}
{236}{}{Make their pain last, kin ya?}

# show when PC has a positive reputation with Tibbets
{260}{}{Fetch mah gun.}
{261}{}{Well, look who's here!}
{262}{}{Robot lover!}
{263}{}{Git 'im, git 'im!}
{264}{}{Git off mah prop'rty!}

# start_1
{290}{}{Howdy, stranger!}
{291}{}{Howdy, dam' purty lil' thang!}
{292}{}{Hello, Lucky. I'm }
{293}{}{.}
{294}{}{Howdy. Got any news?}
{295}{}{[Grin seductively.]}
{296}{}{That's quite a battle scar you've got there.}
{297}{}{Hi, I'm }
{298}{}{, just looking for work.}
{299}{}{What brings you here?}
{300}{}{Me }
{301}{}{, Lucky.}
{302}{}{Hullo. Newsa?}
{303}{}{Big war scar!?}
{304}{}{Uh... Work - me work?}
{305}{}{You do what?}

# start_2
{320}{}{What's up?}
{321}{}{That's quite a scar you've got there.}
{322}{}{Got any more information?}
{323}{}{Still looking for work. Anything for me?}
{324}{}{What are you up to?}
{325}{}{Nothing important. Catch you later.}
{326}{}{[Turn around and walk out the door]}

# start_3
{350}{}{She'et, ya got balls, dirt, but if I see ya again, I'll blow yer head clean off. Ain't nobody gonna say nuthin'!}
{351}{}{Got any new information?}

# start_4
{380}{}{Mishin' good? Yer on the right side, pardner.}
{381}{}{Man, that's quite a scar, Lucky.}
{382}{}{Got any more information?}
{383}{}{What are you working on?}
{384}{}{You scar? How ...?}
{385}{}{More! More! In-fo?}

# aa
{410}{}{Ya kno' mah name?}
{411}{}{Your buddy, Aldo, told me. I thought Lucky 17 was a woman?}
{412}{}{Well, you know how people like to spread rumors. They say all sorts of things about Lucky: he's a good man, his farm was the most productive, he's nice and all that. So I figured I'd come and see who Lucky really is for myself.}
{414}{}{You just told me your name.}
{415}{}{Aa-bbbla ...Lucky!}

# bb
{440}{}{Oh, it's a long story. Don't git me start'd.}
{441}{}{No, really, I want to know.}
{442}{}{Yeah, you're right. I don't need to hear this shit. Goodbye.}
{443}{}{Alright, maybe next time. Let me ask you something else.}
{444}{}{Me - know. Want.}
{445}{}{Me need more. Question?}

# cc
{470}{}{It's all up to your wallet size, m'friend. Something interesting might cost ya as high as [He eyes you] 60 caps.}
{471}{}{I can do 60 caps, but it better be worth it.}
{472}{}{I'll give you 30 caps upfront, and the rest if I like the ending.}
{473}{}{C'mon, pardner, I gotta pay just to listen to news?}
{474}{}{Maybe later. See you around.}
{475}{}{Something else is bothering me, though.}
{476}{}{You good. Please tell?}
{477}{}{No pay!!}

# dd
{500}{}{Hey there, Lucky Legless. [He sticks his tongue out and disgustingly wets his dry lips]}
{501}{}{[Walk past Lucky, "accidentally" brushing against him]}
{502}{}{Humor me, Lucky.}
{503}{}{Those are some wicked teeth, Lucky. I'm heading out, but don't forget to brush 'em, okay?}
{504}{}{Hey, Lucky. Mind if I ask you something?}
{505}{}{More! More! In-fo?}
{506}{}{Blesh. Mhm... I go.}
{507}{}{Lucky? Lucky -- Lucky!}

# ee
{530}{}{[He looks at you, hesitates for a moment, then dismisses the thought] What'd'ya want from me?}
{531}{}{Can you recommend any contacts to me?}
{532}{}{Got any problems or disputes? I work for the "permanent solutions department," if you catch my drift.}
{533}{}{I heard there are junkies in this prison. Is that true?}
{534}{}{Are there any other farmers in this prison?}
{535}{}{I kill, if money you give.}
{536}{}{Chems in prison? Druggies?}
{537}{}{More farm crimi- crimin-aaaaals?}

# e1
{560}{}{Yea? What d'ya want from me?}
{561}{}{Tell me about the prison.}
{562}{}{What's the issue with the robots?}
{563}{}{Robo! Taste bad, yeah?}

# ff
{590}{}{Do I look like a fuckin' unemploymen' bureau?}
{591}{}{Go screw yourself, asshole. [Teach him a lesson]}
{592}{}{Hey, calm down. I'm willing to pay for the information.}
{593}{}{You need to chill out. I'll come back later.}
{594}{}{Alright, alright. Let me ask you something else.}
{595}{}{Folk you!}
{596}{}{[Turn around and walk away]}

# gg
{620}{}{Jest eatin'em nutrien' pastes.}
{621}{}{What's nutrient paste?}
{622}{}{Never mind. I'm leaving.}
{623}{}{Pasta? Huh?}
{624}{}{Me go.}

# hh
{650}{}{Get lost, dirtbag! Ain' got no mo' time fer ya.}
{651}{}{Okay, fine. I have another question for you.}
{652}{}{[Leave him]}

# ii
{680}{}{Well... [He smiles] We've got sum nice pe'ple here. Rob'rta, she'll do anything for caps. Dunno where she is now, haven't seen her fer'while. Then there's Rake, a fella farma too, ye? Aldo makes d'best medicine. Then there're lots of folks who list'n to robots blindly. Yuck! Right?}
{681}{}{You're wasting my time, friend. I'll see you later.}
{682}{}{What can you tell me about the junkies?}

# jj
{710}{}{S'been so long, soun's like a fairy tale now, I tell ya. Once upon a time, Lucky was searchin' fer that perfect cultivated land that everyone's lookin' fer. On the third day, Lucky wus starvin'.}
{711}{}{Go on.}
{712}{}{If I may interrupt, I have another question.}
{713}{}{Ye?}

# kk
{740}{}{He spied a white bird, tall as two full-grown men, comin' down from d'eavens. Them tribals call it the th'nderbird. It looked so dang mouth-waterin', so plump! So, I whipped out my knife and crept up real quiet-like. Everythin' was going smooth 'til that blamed bird caught sight of me. Them birds got ears like a de'thclaw and eyes like d'Warden, you know? Dang it! It got a chunk out of me, my legs, and took off.}
{741}{}{Yeah.}
{742}{}{Okay.}
{743}{}{Alright, I need to get going. Goodbye, Lucky.}
{744}{}{[Look dumbfounded and do nothing]}
{745}{}{G'd-Bye!}

# ll
{770}{}{Next thing I know, I'm sprawled out in the desert, bleedin' out, at death's door. My lights were dimmin'. And just when I reckoned I was 'bout to head to them Golden Wheat Fields yonder, this here figure rushes up on me. Rake. His shadow dang near swallowin' me whole. You shoulda seen me then. Scared outta my wits, I ignored the hurt and the sleepiness, tried to skedaddle, but he kept on. Nearer. Nearer. I figured I was done for.}
{771}{}{And what happened?}
{772}{}{Aha.}
{773}{}{O-kay?}

# mm
{800}{}{So he gets within 'bout ten yards of me, and I got a good grip on my knife. That nincompoop just stood there, lookin' right back at me. He looked plumb tuckered out, I gotta say. And without meanin' to, I cracked a smile. Then he done the same. Over the next few days, he patched me up, feedin' me some of that same ol' th'nderbird, heh. And that's how I ended up with my name and a couple missin' legs.}
{801}{}{Tell me more about Rake. What is he like?}
{802}{}{How are things going for you guys?}
{803}{}{Let me ask you something else.}
{804}{}{This took longer than I expected. I need to leave now.}
{805}{}{Man, you are one crazy bastard. I'll finish what the bird started. [Laugh. Hurt him]}
{806}{}{Time passing, good?}
{807}{}{I kill you, now. Sorry.}

# nn
{830}{}{It woulda been mighty fine if it weren't for them blasted robots stealin' the prime years of our lives. Ain't no laughin' matter no more. Damn it all! I'd yank the circuits outta every last one of them tin cans. [He lowers his voice] You wanna know who's the chief robo-sonuva? D'Warden. Take him out, and we'll be free as birds, I tell ya.}
{831}{}{Thanks for the tip. I also have a score to settle with the Warden.}
{832}{}{Let me ask you something.}

# oo
{860}{}{Ain't much to jaw 'bout, really. They don't do nothin' but stand 'round, jabbin' pills and needles into themselves. Best keep clear of 'em. They're nothin' but trouble, needin' a good cleanin' up. If only I could lay my hands on a good shootin' iron these days.}
{861}{}{I'll see you around, man.}
{862}{}{Hmm, tell me about the robots.}
{863}{}{What's the latest gossip around the prison?}

# pp
{890}{}{I let ya talk to 'im yerself. [He starts shouting.] Yo, Rake, come 'ere, ol' boy. Rake! Rakeeeeeeeeee!}
{891}{}{No, no, it's alright. I still have a few more questions for you.}
{892}{}{Well, that's alright. Can you give me some news instead? What's happening?}
{893}{}{Alright, I don't think he's here. Thanks anyway.}

# gritZ
{920}{}{Paste, ya fool, nutrient paste, usin' the Feedin' M'chine. I dunno what's 'nside but it tastes fiiiine. Were ya born on a Moon or sumthin'?}
{921}{}{Uh, yeah, I get it. Good stuff. I have to go now.}
{922}{}{I see. Do you have a minute to tell me about the town?}
