# Message file for tbmartin.ssl
# Number of nodes: 13
# Grammar pass done

{100}{}{You see a mean man.}
{101}{}{You see Martin.}
{102}{}{He appears to be in peak physical condition.}

{150}{}{That was... satisfactory. Now, make a swift exit before we're caught together.}
{151}{}{Ouch! Momma...}
{152}{}{That was... extraordinary. Now, make a hasty retreat before we're discovered together.}
{153}{}{That was... underwhelming. Now, quickly depart before we're spotted in my room.}
{154}{}{That was... the worst experience. Now, hastily leave before we're seen together.}

# Node001
{200}{}{What? Can't you see that I'm occupied? You're disturbing me.}
{201}{}{I've had my eye on you ever since you stepped into this room. You've caught my interest. I'm Martin, by the way.}
{202}{}{Seb Tremblay wants--}
{203}{}{Thank you, Martin. I'm flattered by your attention.}
{204}{}{I'm not interested, Martin.}
{205}{}{I just--}
{206}{}{Whatever.}
{207}{}{Hghhnn.}
{208}{}{Me go.}

# Node002
{230}{}{Indeed, as you should be, for I am no ordinary Martin. I am Captain Martin, commanding officer of...}
{231}{}{This is getting more interesting. Captain of what? A squad? A ship?}
{232}{}{[Burst into laughter]}
{233}{}{I must take my leave now.}

# Node003
{260}{}{Well, I am. So what's your name, darling?}
{261}{}{[Kick him in the nuts]}
{262}{}{My name is }
{263}{}{. Make sure you remember it.}

# Node004
{290}{}{When you're turning me down, you're turning me on. [He moves closer]}
{291}{}{Take another step or I'll...}
{292}{}{In another life. So long.}

# Node005
{320}{}{Look, whoever you are. I'm busy with the girl here. Now I want you out of my sight. Is that clear?}
{321}{}{Tough boy, huh? Well, let's see what you're made of!}
{322}{}{Alright, I understand. I'll leave you two alone.}

# Node006
{350}{}{As if it would make a difference. Let's not spoil our little moment here.}
{351}{}{I agree. Maybe we could meet up later?}
{352}{}{I'm sorry to disappoint. Goodbye for now.}

# Node007
{380}{}{I hate to see you go, but I love to watch you walk away.}
{381}{}{You're quite sleazy, aren't you?}
{382}{}{I'll take my leave now.}

# Node008
{410}{}{[He's still staring at your ass with a hungry look in his eyes. You're not even sure he acknowledged your words]}
{411}{}{[END]}

# Node009
{440}{}{[He's checking you out, not even acknowledging your actions or words]}
{441}{}{[CONTINUE]}

# Node010
{470}{}{Hmm... you're dumb *and* ugly. Why don't you go back to cleaning the toilets or whatever you ugly people do.}
{471}{}{Me hurt you.}
{472}{}{You bad. Me go.}

# Node011
{500}{}{[He quickly steps forward and is now inches away from you] Or you'll what?}
{501}{}{[Attack him]}
{502}{}{Nothing. I'm leaving.}
{503}{}{Or I'll start liking you. I appreciate directness. Heh.}

# Node012
{530}{}{Hmm... you're dumb *but* hot. Why don't you follow me to my room. I can show you something nice there.}
{531}{}{Uh-huh.}
{532}{}{Nuh-huh.}

# Node013
{560}{}{[He shrugs his shoulders] You can always try.}
{561}{}{[Kick him in the nuts]}
