# Message file for tbmagik.ssl
# Number of nodes: 202

{100}{}{You see a greasy man.}
{101}{}{You see Magik, a criminal.}
{102}{}{He looks like he's in charge.}

# If the PC has intimidated Magik to stay away from Angela
{200}{}{Leave me alone.}
{201}{}{I haven't been near her, I swear it.}
{202}{}{I ain't saying nothing.}
{203}{}{Just get out of here.}
{204}{}{What's your problem?}
{205}{}{I said I ain't been near her, now leave me be!}

# If the PC is caught robbing Magik (or admits it after)
{230}{}{Came back, did you? Well this time I'm waiting for you!}
{231}{}{Die, shithead!}
{232}{}{Die!}

# While Magik is sleeping
{260}{}{Mmmn... zzz...}
{261}{}{Zzz... mmm... right there...}
{262}{}{Zzz... precious...}
{263}{}{ZzzZZZZzzZZzz...}

# When the PC nearly wakes up Magik (failed lockpick, first sneak fail)
{290}{}{Guh? Hngh...}
{291}{}{Uh? Hhmm... zzz...}
{292}{}{Ggh... Zzz...}

# When Magik is awoken by the PC
{320}{}{Wha? Who's there?}
{321}{}{Get out! Get out you piece of shit, get out!}
{322}{}{I'll kill you, you son of a bitch! Come here!}
{323}{}{I'll rip your eyes out and spit in the sockets!}
{324}{}{You're dead! You hear? Next time, you're a dead man!}

# Floats while idling in the day
{350}{}{Can't you idiots work any faster?}
{351}{}{Mmm... smells like success.}
{352}{}{You! Work harder!}
{353}{}{Are you trying to put me out of business?! Work!}
{354}{}{Good help is hard to find.}
{355}{}{Hogg better come up with the goods next time.}

# Node 6 [RobbedIdle]
{380}{}{When I catch that son of a bitch...}
{381}{}{Oh he'll pay alright. He'll pay. He'll pay with his blood.}
{382}{}{Thinks he can just steal from me? From ME?!}
{383}{}{... and then I'll cut him, and I'll slice him and I'll cut him some more...}

# if the PC tries to talk to Magik outside of working hours
{410}{}{Come back tomorrow.}
{411}{}{We start work again in the morning.}
{412}{}{You can keep working if you want, but I ain't paying you for it.}
{413}{}{We're closed.}

# If a dumb PC has infuriated Magik with his stupidity
{440}{}{There's no place for you here.}
{441}{}{You drag your knuckles somewhere else now, y'hear?}
{442}{}{Are you lost?}
{443}{}{The door's right over there.}
{444}{}{Someone should put this idiot in a circus.}

# Node_Door
{500}{}{Then I hope you remember where the exit is.}
{501}{}{[END]}

# Node_FirstIntro
{530}{}{Yeah?}
{531}{}{Damn. Not every day we get something as precious as you in here. You looking for something?}
{532}{}{I'm looking for Magik.}
{533}{}{Nothing. Goodbye.}
{534}{}{Hello little boy. What is your name?}
{535}{}{[Wander off]}

# Node_FirstIntro2
{560}{}{Congratulations, you found him. Who the hell are you?}
{561}{}{That's my name. I'm surprised you didn't know it already. And who might you be?}
{562}{}{Call me }
{563}{}{.}
{564}{}{My name is not important.}

# Node_FirstIntro3
{590}{}{You think I give a shit what your name is? Just tell me what you want.}
{591}{}{And precious little name and all. What can I do for you?}
{592}{}{I'm looking for work.}
{593}{}{I wanted to ask you some questions.}
{594}{}{Maybe you'll remember my name when I carve it into your forehead.}
{595}{}{Nothing for now.}

# Node_FirstIntro4
{620}{}{You got that right. What do you want?}
{621}{}{If you say so, precious. What can I do for you?}

# Node_RobIntro
{650}{}{Yeah, what the fuck do you want?}
{651}{}{I'm here for a job.}
{652}{}{Hey, I heard you got robbed.}
{653}{}{Just passing through. See you around.}

# Node_NextIntro
{680}{}{This ain't a clubhouse, son, this is a place of work. If you ain't pitching in you should pitch out, if you get me.}
{681}{}{This ain't a clucking circle, precious, this is a place of work. If you ain't pitching in you should pitch out, if you get me.}
{682}{}{I want a job.}
{683}{}{I have some questions for you.}
{684}{}{I have some questions about Angela's death.}
{685}{}{Sorry, wrong cell.}
{686}{}{Huhh! }
{687}{}{ needs a job.}
{688}{}{[Wander off]}

# Node_JobIntro
{710}{}{Didn't expect to see you here again. Did you like it so much the last time?}
{711}{}{Well I'll be. Didn't expect to see you here again, precious. Was it so much fun the last time?}
{712}{}{I need a job. Any openings?}
{713}{}{I wanted to ask you something.}
{714}{}{I had some questions about Angela's murder.}
{715}{}{Just passing through. Bye.}
{716}{}{Magik has a job?}
{717}{}{Bye!}

# Node_AngelaIntro
{740}{}{Is she coming? Angela?}
{741}{}{I haven't spoken to her yet.}
{742}{}{She told me she isn't interested.}
{743}{}{Hold that thought, I'll be right back.}

# Node_Job
{770}{}{You want a job? Here?}
{771}{}{Is that a problem?}

# Node_Job2
{800}{}{Hey, I never turn down a pair of hands. I got a job for you, but you don't look like the type.}
{801}{}{What type is that?}
{802}{}{Tell me about the job.}
{803}{}{You're right, this place is beneath me. I'll show myself out.}

# Node_Job3
{830}{}{Just look at these idiots outside. They can't even tie their own shoes. Only reason they're here is they're too stupid to "clean." You don't exactly fit in.}
{831}{}{You should show your friends a little more respect.}
{832}{}{I'm not above getting down and dirty. Tell me about the job.}
{833}{}{I'll think about it and get back to you.}

# Node_JobBarter
{860}{}{No, son. You'll do it for ten, or you won't do it at all.}
{861}{}{No, precious. You'll do it for ten, or you won't do it at all.}
{862}{}{Ten it is. I'll get started.}
{863}{}{You're about to lose a valuable asset here. What does another ten caps mean to you?}
{864}{}{I guess this is goodbye then, Magik.}

# Node_JobBarterFail
{890}{}{Every cap means as much as every other cap, that's rule number one. And with you I'm losing nothing I want. Move it.}
{891}{}{I really need this job. I'll do it for ten.}
{892}{}{[Leave]}

# Node_JobInfoCleaning
{920}{}{Everybody starts the same, even fancy new folk like you. Just scoop all the stuff you find are abandoned, and then bring it to me. You'll get ten caps a day. Get to work.}
{921}{}{Everybody starts the same, even a precious thing like you. Just scoop all the stuff you find abandoned, and then bring it to me. You'll get ten caps a day. You want it? Get started.}
{922}{}{I'm on it.}
{923}{}{A whole day's work for ten caps? I want twenty, not a cap less.}
{924}{}{Wow, it just hit me I'd be stealing stuff for you. Not collecting anything "abandoned." I quit.}

# Node_JobPromotion
{950}{}{Lucky for you there's a "Shiva" spot that just opened. This silly bitch cut her thumb off today, she's no good to me now. You ever handle a shiv?}
{951}{}{Never in my life.}
{952}{}{Not really.}
{953}{}{Once or twice.}
{954}{}{More than you know.}
{955}{}{A shiv is the extension of my soul.}
{956}{}{ isn't supposed to play with sharp thingy.}
{957}{}{Shiv makes people cry red from their skin.}

# Node_JobPromotionEasy
{980}{}{Well it's easy. And if you cut yourself up, I can always get someone else. Pays 20 caps a shift. Interested?}
{981}{}{I'll do it.}
{982}{}{Not in the least. Goodbye.}
{983}{}{Interested.}
{984}{}{ likes his old job more.}

# Node_JobPromotionGood
{1010}{}{Maybe you'll leave with all your fingers. Pays 20 caps a shift. Interested?}
{1011}{}{I think I'll stick to collecting.}

# Node_JobPromotionStart
{1040}{}{Good. So, you're a "Shiva" now. Congratulations. Here's the tool of the trade. You just approach others, make sure they see you can handle it and ask them if they have any possession they don't need but you might find useful. Simple. Just watch what everybody else does, you'll pick it up.}
{1041}{}{A "Shiva?"}
{1042}{}{OK. I'll do my best!}

# Node_JobPromotionSwitch
{1070}{}{You sure about that? If you won't get the chance to pass this up again.}
{1071}{}{I wouldn't want to miss out. I'll take the promotion.}
{1072}{}{I'm sure. I'm more suited to collecting work.}
{1073}{}{ want job with sharp thingy.}
{1074}{}{ want play only find abandoned thingy.}

# Node_JobPromotionWeird
{1100}{}{Right. Wait, what? Fuck it, who cares, you wouldn't be the first. Pays 20 caps a shift, you in?}
{1101}{}{I'm in.}
{1102}{}{I'm out. As in leaving. Now.}
{1103}{}{Yeah!}
{1104}{}{ like find abandoned thingy more.}
{1105}{}{Out! Side! Outside! Bye!}

# Node_JobQuit
{1130}{}{I knew you wouldn't last, but hell if you ain't a bigger pussy than I thought. Get lost, son, you can't handle it.}
{1131}{}{I knew you wouldn't last, precious, but hell if that wasn't quick. Guess a girl like you ain't cut out for a man's work after all.}

# Node_JobRepeatClean
{1160}{}{Sure, it says here I'm short one no-good lazy asshole. If I remember, you about fit that description.}
{1161}{}{Sure, I got space for you. But you didn't quite cut it last time, if I remember.}
{1162}{}{Yeah, about the last time... Let me explain.}
{1163}{}{Forget it, I'm not working for you.}
{1164}{}{ very unlucky last time. Lucky now.}

# Node_JobRepeatClean2
{1190}{}{Save it, I could give a shit. If they got more than seven fingers, they're good enough to work for you. That's rule two.}
{1191}{}{You won't be sorry.}
{1192}{}{ has eleven! Wait... one...}

# Node_JobRepeatCleanStart
{1220}{}{You know the drill. Start inspecting the cell blocks.}
{1221}{}{[END]}

# Node_JobRepeatGutting
{1250}{}{You know the drill. Grab a shiv and start negotiating with other prisoners.}

# Node_JobRepeatSwitch
{1280}{}{Let's just take a look... Hmm.}
{1281}{}{[CONTINUE]}

# Node_JobRepeatTrust
{1310}{}{But since I know you ain't exactly reliable, you got to pay something I call the Trust Tax. Pay's down to 8 caps.}
{1311}{}{I can live with that.}
{1312}{}{What? Ten was bad enough, no way I'm doing this for eight.}
{1313}{}{ tries harder this time.}
{1314}{}{Nounounou! Byebyebye!}

# Node_JobRespect
{1340}{}{Last I checked I was in charge of this operation, which also means I own every dipshit working for me. You got a problem? That's why I put a door in.}
{1341}{}{Careful. An attitude like that can get a man killed.}
{1342}{}{It was just an observation, it didn't mean anything. Tell me about the job.}

# Node_JobStart
{1370}{}{That's what I like to hear. Now get to work. And don't let me catch you slacking off.}
{1371}{}{I'll make you proud.}
{1372}{}{Don't worry, you won't catch me.}

# Node_Q_Business
{1400}{}{Took my whole time here, but this here operation runs slicker than pigshit. I buy my stuff straight out of the cell blocks, clean them, pack them up and send them out the other door at twice the price. And no waste - I even got a guy who buys the junk from trashcans.}
{1401}{}{Who do you sell your stuff to?}
{1402}{}{Who would want to buy junk from you?}
{1403}{}{Let me ask you something else.}

# Node_Q_Business_CR
{1430}{}{You never been to Hoover Dam? What, did you just fall from the sky yesterday? Give me your Pip-Boy, I'll show you. [He marks the location on your map]}
{1431}{}{Thanks. Can I ask you something else?}

# Node_Q_Business2
{1460}{}{No idea and don't care really. They get rid of my trash and pay me for the privilege, and when a deal's that sweet you don't ask questions. All I know's they ain't from around here.}
{1461}{}{Where can I find these people?}

# Node_Q_Business3
{1490}{}{Anyone who wants it. A lot of prisoners always need something the robots won't give them. When I remember how things were in Hoover Dam, back in the day, a tear almost forms in my eye.}
{1491}{}{Hoover Dam? Where's that?}
{1492}{}{Who do you sell the junk to?}
{1493}{}{Let me ask something else.}

# Node_Q_Business4
{1520}{}{Can't tell you for sure. It's always someone else. They work down in the factory, they don't say where it goes or why they need it. But anything going anywhere goes the Security Hub, you could start looking around there. Security Hub is our Hoover Dam.}
{1521}{}{Can you give me something more to go on? A name?}

# Node_Q_Business5
{1550}{}{I don't see why I should. I got a good thing going here, I don't need anybody wading in and messing things up.}
{1551}{}{You'll be sorry if you don't.}
{1552}{}{No reason, I'm just curious.}

# Node_Q_Business5_Curious
{1580}{}{Well go be curious somewhere else. This is a place of business.}

# Node_Q_Business5_STR
{1610}{}{What? Hey, whatever those guys are mixed up in, it's got nothing to do with me. The guy I made the deal with called himself the Mechanic. That's all I know.}
{1611}{}{Thanks. Let me ask you something else.}
{1612}{}{That's all I needed to know. Goodbye.}

# Node_Q_CotC
{1640}{}{Lots of us came here from the outside, but some were born here. Two hundred years ago, maybe more, is when this hotel started filling in with "guests" from all parts of the wasteland. Many robots help run the place. Some prisoners had nightmares about a big one that abducted them. Don't know much about that. Been living here ever since I was abducted 15 years ago.}
{1641}{}{Tell me about the Welcoming Committee Director.}
{1642}{}{What is there to do for fun around here?}

# Node_Q_CotC_Angela
{1670}{}{Robb's daughter. She's all grown up now, ain't a man in Tibbets who wouldn't want to do dark things to her, oh boy.}
{1671}{}{Sounds like a real looker.}
{1672}{}{Let me ask you something first.}

# Node_Q_CotC_Angela2
{1700}{}{Just tell her I got no plans for tonight. If she wanted to come up here and talk about our future, I'd like that.}
{1701}{}{I'll pass it on if I see her.}
{1702}{}{I won't help you defile an innocent girl. Forget it.}

# Node_Q_CotC_Angela3
{1730}{}{I owe you one. And once you've been around a while, you'll find out that's a good thing.}

# Node_Q_CotC_AngelaNo
{1760}{}{Is that what you think? You've got me all wrong, son, all wrong. So unless you plan on picking up some stuff for me, I think it's time you moved your ass elsewhere.}
{1761}{}{Is that what you think? You've got me all wrong, but I've seen that look before, you ain't changing your mind. I think it's time you moved on, precious. No good to nobody around here.}

# Node_Q_CotC2
{1790}{}{WCD? He's one of those "die for the cause" retards, you know, robotic brain's all fucked up from something. But he ain't in charge, the Warden runs the place, or so he says. If you ask me, the only thing he has control over are those lower levels they're holed up in. Us out here, we run things for ourselves.}

# Node_Q_CotC3
{1820}{}{Most folk end up in the Atom bar, it's the closest you'll get to a real bar in this place. The beer tastes like scorpion piss, but what can you expect? It's worth for the scenery. That Angela is a fine piece of ass, no doubt about it.}
{1821}{}{Tell me about Angela.}

# Node_Q_Magik
{1850}{}{You want to know about me? Just look around you. Everything you see - that's me.}
{1851}{}{Impressive. You must be one of the richest people around.}
{1852}{}{I'm not sure I understand. All I see is a pawn shop owner who steals and underpaid thugs.}
{1853}{}{Let me ask about something else.}

# Node_Q_Magik2
{1880}{}{Pretty damn near, that's for sure. The only one making as much as me is the old Warden. And he wouldn't be doing nearly so well if it wasn't for Vault-Tec and me selling stuff so his factory slaves can spend their caps on something.}
{1881}{}{Why do you treat your workers so badly?}
{1882}{}{Tell me about the Warden.}

# Node_Q_Magik3
{1910}{}{That's right. Free stuff I'm reselling, hungry customers and the guy who got rich.}
{1911}{}{Do you ever feel guilty?}
{1912}{}{Sounds like you're at the top of the food chain around here.}

# Node_Q_Magik4
{1940}{}{You see anyone forced into this? You see anyone here who didn't choose to be? Hell, if it weren't for me, half these monkeys would turn up face down in a month. If you got a problem with the way I run my business, you can take it someplace else.}
{1941}{}{You see anyone forced into this, precious? Anyone here who didn't choose to be? Hell, if it weren't for me, half these monkeys would turn up face down in a month. If you got a problem with the way I run my business, you can take it someplace else.}
{1942}{}{Can I ask you something else first?}
{1943}{}{I'll show myself out.}

# Node_Q_Magik_Hogg
{1970}{}{He runs the biggest prison I've ever been in, that's a fact. Not in the best of health, so I've heard. If you can say that for a robot, you know. He'll probably hand it all over to one of his bots before he snuffs it. But that's just a theory of mine.}

# Node_Questions
{2000}{}{Ask already, we're getting older here.}
{2001}{}{Tell me about yourself.}
{2002}{}{I want to know about your business.}
{2003}{}{What can you tell me about Tibbets?}

# Node_Questions2
{2030}{}{Just get on with it, alright? I got things to do.}
{2031}{}{Tell me about your business.}
{2032}{}{Tell me about Tibbets.}

# Node_RobJob
{2060}{}{Of course I got a fucking job for you, I always got jobs. But pay's half, courtesy of that son of a whore who robbed me. Still want it?}
{2061}{}{Sure.}
{2062}{}{The pay was bad enough before, now it's just slavery. I'm out.}

# Node_RobRobbed
{2090}{}{It's not a secret. And when I catch whoever did it and put a big fat fucking hole in his head, that won't be a secret either!}
{2091}{}{Any idea who it was?}
{2092}{}{Are you still hiring?}
{2093}{}{I sure hope you catch him... or her. See you around.}

# Node_RobRobbed2
{2120}{}{I got a million ideas! Some punk's kid, maybe a bunch of them. Maybe one of these lazy dipshits thought he could help himself to overtime, or maybe one of those fucking junkie fucks needed a fix. Hell it could be even you!}
{2121}{}{If you calm down, I might be able to help.}
{2122}{}{I hope you catch whoever it was. Are you still hiring?}
{2123}{}{Sounds like you've got some interesting theories. I'll leave you to it.}

# Node_Threat
{2150}{}{You got balls, son, threatening me in my own damn cell. Now get the hell out before someone cuts them off and feeds them to you.}
{2151}{}{You got nerve, precious, threatening me in my own damn shop. And if you do it again, I'll cut your tongue out. Now fuck off.}
{2152}{}{Fight me!}

# Node_AngelaNotYet
{2180}{}{So why are you hanging around here? When you say you'll do me a favor, you don't come back until it's done.}

# Node_AngelaStall
{2210}{}{Then do it. The Angela I'm talking about isn't supposed to say no. I know she wants it, she's just teasing me.}
{2211}{}{I think you may have misread the situation.}
{2212}{}{I'll go and talk to her again.}

# Node_AngelaCheck
{2240}{}{What? That's what she said? You sure you heard her right? Did you even get the right girl?}
{2241}{}{It was her, trust me. Not interested.}
{2242}{}{I'm fairly certain. I could go back and check.}

# Node_AngelaSpec
{2270}{}{That ain't right. No, no, that ain't right at all. What's wrong with that bitch? Leading me on like that, then spitting in my face? She better have a damn good explanation why I wasted my time on her.}
{2271}{}{I don't think she's the problem.}
{2272}{}{It's not personal. I think she's gone off men in general.}
{2273}{}{Nothing's wrong, she just needs time to think.}
{2274}{}{Not my problem. I'll let myself out.}

# Node_AngelaMisread
{2300}{}{Oh that's what I did, is it? Is it? You just tell me what you know and I don't, we'll see who's missing what.}
{2301}{}{Try this: she's into robots.}
{2302}{}{Have you looked in a mirror lately? Or ever?}
{2303}{}{She's at a difficult stage in her life. She just needs to think.}

# Node_AngelaFrank
{2330}{}{And just what are you saying by that?}
{2331}{}{She's young and beautiful. Your face terrorizes small children. It's not a match.}
{2332}{}{Look at yourself, Magik. You're pathetic. What would she see in you?}
{2333}{}{You're way too old. She's better off with someone her own age.
}

# Node_AngelaSpill
{2360}{}{Take it from me, she still wants it. They all do, they're just scared to show it. And I know she's stubborn, but I gave her everything she asked for. Now it's time I get what's mine.}
{2361}{}{I'm just telling you what she told me.}
{2362}{}{She's a lot more than stubborn. She's into robots.}
{2363}{}{She doesn't belong to you, Magik. Just back off.}

# Node_AngelaThink
{2390}{}{What's to think about? Magik wants to see you, you go see Magik. That bitch has been dancing around me for weeks, I'm starting to lose my patience.}
{2391}{}{She's young and confused. She just needs time to get her life together.}
{2392}{}{Magik. Listen. It's not happening. It's never going to happen.}

# Node_AngelaFrank2
{2420}{}{Don't feed me that. I've had better than her, younger too. I get around to every woman in this prison, and you know it ain't on looks alone. What counts around here are caps, and that's what I got a lot of.}
{2421}{}{Not everyone can be bought.}
{2422}{}{Just give her time, I'm sure she'll come around.}
{2423}{}{Maybe she's put off by the whole freakish pervert thing.}

# Node_AngelaBought
{2450}{}{You talk that shit because you like the smell, son? Or did you piss your momma off and she dropped you? Because I'll tell you here and now, everybody got a price. And I can pay hers, so what's the problem?}
{2451}{}{The problem is in your head. Why can't you accept it?}
{2452}{}{The problem is she doesn't like men. Any of them. At least those not assembled in a factory.}
{2453}{}{The problem is I don't want you anywhere near her.}

# Node_AngelaSpillAdmit
{2480}{}{You don't look like you're kidding me.}
{2481}{}{It's true. She told me herself.}

# Node_AngelaTime
{2510}{}{Well I gave her time. I gave her a whole bunch of time, and she's still shying. So cut the shit and tell me whatever it is you ain't telling me.}
{2511}{}{I've told you what she told me. That's all I know.}
{2512}{}{Angela just doesn't like men. Any men. At least those that aren't robots.}

# Node_AngelaAlarm
{2540}{}{Those her words or yours? Because I've known her a lot longer than you, and I know she was willing back then. So what's changed? What are you hiding from me?}
{2541}{}{I'm not hiding anything. I'm telling you what she told me.}
{2542}{}{Angela's... different.}
{2543}{}{The only thing I'm holding back is the urge to kick your teeth in. Just leave her alone.}

# Node_AngelaCrux
{2570}{}{Something stinks in here, and it ain't me or my toilet. I can tell a man when he's lying, and you're sure as hell doing it right now.}
{2571}{}{Well something stinks in here, and it ain't me or my toilet. I paid plenty of women to lie to me, so I can tell when you're doing it right now.}
{2572}{}{You're lying to yourself, Magik. She's not interested, and she never was.}
{2573}{}{You want the truth? Angela's into robots. That's it.}
{2574}{}{I'm through talking. Just leave her alone or you'll regret it.}

# Node_AngelaSpill2
{2600}{}{What? Wait, are you saying.... is she insane? What the fuck is wrong with that bitch?}
{2601}{}{What can I say, it is what it is.}
{2602}{}{No, she's sane. She just feels a robot resembling a human would protect her better. And wouldn't cheat on her.}
{2603}{}{Rejecting you doesn't mean she's crazy.}

# Node_Intimidate
{2630}{}{So you're defending her now? What the hell is that?}
{2631}{}{What, you're her mother now? What the hell is that?}
{2632}{}{Angela made her choice, and it wasn't you. Move on.}
{2633}{}{I'm looking out for her best interests.}
{2634}{}{*That* is the last warning you get. Leave her alone.}

# Node_IntimidateProtect
{2660}{}{So you're the guy, huh? I send you over there to do a favor for me and now you're fucking my woman? Is that it?}
{2661}{}{She needs some bitch like you to protect her? You two starting a sisterhood or something?}
{2662}{}{Right. So if you want her, you'll have to get through me.}
{2663}{}{Exactly. So stop wasting your time. And she's not into men at all. She's into robots.}
{2664}{}{It's got nothing to do with me. You missed the point.}

# Node_Intimidate2
{2690}{}{She's got her dad for that, she doesn't need you.}
{2691}{}{She made her choice and you fell short. Live with it.}
{2692}{}{I'm done talking. Leave her alone or I'll make you wish you had.}

# Node_IntimidateCrux
{2720}{}{Don't try that tough guy shit on me, it won't work. What do you think you can do to me? I could get any one of my fuckers to kill you just for overtime.}
{2721}{}{Don't try that hard bitch shit with me precious, it doesn't work. What do you think you can do to me? I could get any one of my fuckers to kill you just for overtime.}
{2722}{}{If you leave her alone, I'll give back all the money I stole.}
{2723}{}{I need a second to snap your neck, sooner than they can reach me. Ready to give it a test?}
{2724}{}{Fine, I'll tell you the truth. She's into robots. That is, robots that look like humans.}

# Node_IntimidateCrux2
{2750}{}{You asked for it. And when you get to hell, you tell them who sent you.}
{2751}{}{[Wait]}
{2752}{}{[Attack]}
{2753}{}{Alright, you caught me. I was bluffing.}

# Node_IntimidateSequence
{2780}{}{[Magik shouts at his workers] First one of you to kill this piece of shit gets a whole week of overtime! [The male thug responds first] Uh... maybe not. [The female thug replies back] Not worth my life. Maybe if I was bigger. [Eventually, the male thug comes running in and attacks] Raaaaaagh!}
{2781}{}{[Send him flying back in one hit]}

# Node_IntimidateBottle
{2810}{}{I knew you were a pussy. Now you tell me what the hell's wrong with Angela and you get to walk out in one piece.}
{2811}{}{She's into robots. Robots that look like humans. That's the secret.}
{2812}{}{I have no idea. You'll have to ask her.}

# Node_AngelaIntimidateWin
{2840}{}{Uh...}
{2841}{}{You were saying?}

# Node_AngelaIntimidateWin2
{2870}{}{Sure, of course, no problem. Forgotten her already. And hey, you know I was just kidding about all those things I said, right? She got under my skin for a minute, but there's no problem. None, not at all. It's all over with.}
{2871}{}{I'm going. You hope you never see me again.}

# Node_AngelaIntimidateString
{2900}{}{Please... Heh... just don't kill me, alright? I'm begging you here. I'm all talk, you can see that. So why don't... oh god... Let's just... Why don't we all calm down, okay? Let's just calm down and forget about this.}
{2901}{}{I'll forget about you. You forget about Angela.}
{2902}{}{Sorry Magik, you can't unring the bell. This is the end for you.}

# Node_AngelaIntimidateWin3
{2930}{}{Hey... uh... Don't kill me. Please?}
{2931}{}{Again. With conviction this time.}
{2932}{}{That'll look great on your epitaph. Lights out, Magik.}
{2933}{}{That was a warning. Stay away from Angela.}

# Node_AngelaRobo
{2960}{}{So that was it all along. Damn it! That little whore had men queuing up around the block with their dicks in their hands, now she's into robots?}
{2961}{}{Just keep it down. Not many people know.}
{2962}{}{Great, now you know. I'm getting out of here.}
{2990}{}{Can you hear alright? I said she's into ordinary men.}
{2991}{}{Great, now you know. Bye.}

# Node_AngelaRobo2
{3020}{}{Are you fucking kidding me? Everybody needs to know. You know how much caps guys throw at her? She thinks she can just bat her pretty eyes and take it when all the time she's dreaming about an iron rod?}
{3021}{}{She only just found out herself. Cut her some slack.}
{3022}{}{Fine, whatever. I'm out of here.}

# Node_AngelaRobo3
{3050}{}{Forget it. That bitch scammed me. Scammed damn near every man in this prison. People are going to know what she's up to.}

# Node_AngelaIllBe
{3080}{}{Well I'll be. I didn't figure you for the jealous type, son. Like what you saw, did you? Thought you could have her all for yourself?}
{3081}{}{Exactly. So unless you want trouble you'll stay away from her.}
{3082}{}{No, it's got nothing to do with me. You missed the point.}

# Node_AngelaSpeech
{3110}{}{But that doesn't make any sense! Those sorts of looks she gave me in the Atom bar, they said one thing! Hell, I knew she was only after my caps! So's everyone else, I don't give a shit. What's she trying to do to me?}
{3111}{}{She was earning her a free drink. You saw something that wasn't there.}
{3112}{}{I guess we'll never know.}

# Node_AngelaSpillBull
{3140}{}{I saw it in your eyes, precious. Moment I said the word I saw your face agreeing with me. You can't bullshit me.}
{3141}{}{Alright, it's true. She's probably nuts. Now you know, keep it to yourself.}

# Node_AngelaEscape
{3170}{}{Woah, no you don't. You just stand yourself right there and tell me what the hell this is.}
{3171}{}{It's complicated.}
{3172}{}{It's never going to happen. Ever. Do you need me to spell it out?}
{3173}{}{She's into robots that look like humans. That's the story, and I don't care. I'm going.}

# Node_AngelaThink_CLONE
{3200}{}{What's complicated? Magik wants to see you, you go see Magik. That bitch has been dancing around me for weeks, I'm starting to lose my patience.}

# Node_AngelaSpeech2
{3230}{}{I know she's got to earn, but... Hell, I had every woman in this prison, why should she be different?}
{3231}{}{But she is different. We both know it.}

# Node_AngelaSpeech3
{3260}{}{I guess you're right about that. There's something about her face... those lips. She's pure, you know? Like even the wind never touched her.}
{3261}{}{It probably didn't. So why do you want to take that away?}

# Node_AngelaSpeech4
{3290}{}{I don't want her to be like all the others, of course I don't. But... You really think I'd change her?}
{3291}{}{She'd never recover. She has to choose for herself. }

# Node_AngelaSpeech5
{3320}{}{When you put it like that... I guess I could wait a few years. She'll be needing my charity soon enough.}
{3321}{}{I'm glad you understand.}

# Node_AngelaSpeechFail
{3350}{}{I don't buy that shit for a second. You've been lying like a snake since you walked in, don't think I can't see it. So you better tell me whatever it is you know and I don't.}
{3351}{}{She's into robots. Happy?}
{3352}{}{What I know and you don't could take a while.}

# Node_AngelaSpeechFailJ
{3380}{}{Don't try and smart talk me. Just spill it, or I swear on the bones of my cock-eyed whore of a mother you won't leave here alive.}
{3381}{}{She's into robots.}
{3382}{}{What are you going to do? Bite my kneecaps?}

# Node_MidShift
{3410}{}{If I ain't mistaken, you're supposed to be working right now. Or did you quit?}
{3411}{}{The man outside is half-asleep.}
{3412}{}{I'm taking a short break.}
{3413}{}{You can take this job and cram it up your ass. I quit.}
{3414}{}{I'll get back to work.}
{3415}{}{ works hard. }
{3416}{}{ tired.}
{3417}{}{What my job?}
{3418}{}{Me forgot what me do.}
{3419}{}{Me go back work now.}

# Node_MidshiftSnitch
{3440}{}{He won't be working for me much longer. Now get back to work.}
{3441}{}{That's it? Just get back to work?}
{3442}{}{I thought you ought to know.}

# Node_MidshiftSnitch2
{3470}{}{What, you want a fucking medal or something? Nobody likes a rat, son, not even me.}
{3471}{}{What, you want a fucking medal or something? Nobody likes a rat, precious, not even a pretty one like you.}

# Node_MidshiftBreak
{3500}{}{Your short break is cancelled. Get back to work.}
{3501}{}{I just need to get some air.}
{3502}{}{Sure thing, boss.}
{3503}{}{ very tired. Very tired.}

# Node_MidshiftBreak2
{3530}{}{Did you just quit? Was that just me hearing you quit?}
{3531}{}{No, this you hearing me quit. I quit.}
{3532}{}{ going to lie down.}
{3533}{}{Feeling better now. Back to work!}

# Node_MidshiftQuit
{3560}{}{Sorry to hear that. Now get out before you get thrown out.}
{3561}{}{What about my caps?}

# Node_MidshiftQuit2
{3590}{}{Typical. I try to help some loser out and he spits in my eye. Well fuck you too, son, and get the hell out of my cell.}
{3591}{}{Typical. I try to help some loser out and she just spits in my eye. Well fuck you too, precious, and you can get the hell out.}

# Node_MidshiftQuitMoneyA
{3620}{}{Bottlecaps? Did I not just hear you quit? You get paid when you do the work.}
{3621}{}{I didn't finish, but I did work. And I'm going to be paid.}
{3622}{}{I didn't know that. I'll get back to work.}

# Node_MidshiftQuitMoneyB
{3650}{}{You're a joke. You think I'm gunna pay you to stand around doing nothing and quit? Just get out.}

# Node_MidshiftQuitMoneyBarterSuccess
{3680}{}{Alright, shit. I guess you got kids to feed like the rest of them. Take it and get out.}

# Node_JobEnd
{3710}{}{Alright everybody, that's enough. Line up and find out what you're worth.}

# Node_JobEnds2
{3740}{}{Let's see what you've got... Oh, you worked harder than I figured you would. Here you go, you earned it.}

# Node_JobEndsShirk
{3770}{}{I call myself an honest man, so I'll pay you, but we both know you didn't earn it.}
{3771}{}{What do you mean by that?}
{3772}{}{OK.}

# Node_JobEndSolicit
{3800}{}{Here you go, precious. It breaks my heart to see a pretty thing like you working so hard.}
{3801}{}{You might feel better if you paid me more.}
{3802}{}{Charming. Goodbye.}

# Node_JobEndsShirk2
{3830}{}{I might not know any of your names, but I know faces. And I've seen more of you entertaining yourself on Service Level than collecting stuff. Don't expect this much the next time.}

# Node_Solicit2
{3860}{}{Oh I'd love to, believe me. A woman like you shouldn't have to work with her hands. If you come with me, I could let you do a real woman's job.}
{3861}{}{I see where you're going with this. No chance. None. Nil. Zero.}
{3862}{}{What kind of job?}
{3863}{}{I don't think I'm interested.}

# Node_JobEndSolicit3
{3890}{}{It's easy. Real easy. And it pays well. All you have to do is lie back here on my bed. You can even close your eyes if you want to. I can take care of the rest.}
{3891}{}{Let's pretend I'm interested. How much are we talking?}
{3892}{}{You're a scumbag, and I'm leaving.}

# Node_JobEndSolicitRefuse
{3920}{}{You don't know what you're missing. But you will, one day.}
{3921}{}{Don't count on it.}

# Node_JobEndSolicitPrice
{3950}{}{A beauty like you, I'd say you could name your price.}
{3951}{}{Ten thousand.}
{3952}{}{Five thousand.}
{3953}{}{Two thousand.}
{3954}{}{One thousand.}
{3955}{}{I have another proposition.}

# Node_JobEndSolicitBarter
{3980}{}{Even a rich man has his limits, precious. Three thousand.}
{3981}{}{Ten thousand. I'm not budging.}
{3982}{}{Four thousand, final offer.}
{3983}{}{Three thousand. Deal.}

# Node_JobEndSolicitDeal
{4010}{}{Deal! [He rubs his hands together gleefully] Let's get started, shall we?}
{4011}{}{Just try to keep up.}

# Node_JobEndSolicitProp
{4040}{}{Yes?}
{4041}{}{You pay me now and I won't wipe the floor with you.}
{4042}{}{I leave now, and you sleep alone.}

# Node_JobEndSolicitTen
{4070}{}{Well like I said, I got limits. I guess we ain't going to do business.}

# Node_JobEndSolicitHagdeal
{4100}{}{Yes! Four thousand I'll pay. Ooh, I love it when they haggle.}

# Node_JobEndSolicitWoah
{4130}{}{Woah, hang on there kitten, no need to get all fired up. It was just a business proposition. If you won't take it, I know plenty others who will.}
{4131}{}{You hit on the wrong girl today.}
{4132}{}{You're a pitiful excuse for a man. I'm leaving.}

# Node_JobEndSolicitWoah2
{4160}{}{Do I look scared to you? Do your worst, bitch.}

# Node_Sleeping
{4190}{}{[Magik is sound asleep, curled around a large bag]}
{4191}{}{[Pry the bag loose]}
{4192}{}{[Kill Magik]}
{4193}{}{[Poke Magik]}
{4194}{}{[Slip away]}

# Node_SleepingStealSuccess
{4220}{}{[You slide the bag out of his arms, replacing it with a nearby pillow]}

# Node Node_SleepingKillswitch
{4250}{}{[Strangle him silently]}
{4251}{}{[Crush his skull]}
{4252}{}{[Choke him with your hands]}
{4253}{}{[Choke him with a pillow]}
{4254}{}{[How do you want to murder him?]}

# Node_SleepingStealFail
{4280}{}{[You try to tug the bag out of his arms, but he only clutches it tighter]}

# Node_SleepingKillFin
{4310}{}{[You deftly pinch Magik's windpipe shut. His eyes snap open and he begins thrashing around, struggling for air. Eventually he goes limp]}

# Node_SleepingKillStr
{4340}{}{[You take Magik's head in your hands and squeeze. With surprising ease, his skull collapses]}

# Node_SleepingKillElse
{4370}{}{[You cover Magik's mouth with a pillow and apply pressure. He struggles for almost a minute before expiring] }

# Node_SleepingKillHtH
{4400}{}{[You cover Magik's mouth with one hand and pinch his nose with the other. His panic only accelerates the process]}

# Node_Q_CotCAngelaMore
{4430}{}{You gotta see her for yourself, you do. She's something else. First time I saw her, you know what I thought? There is a girl I would want to fuck for the rest of my life.}
{4431}{}{How... romantic.}
{4432}{}{You're a class act, Magik.}

# Node_Q_CotCAngelaMarriage
{4460}{}{She's the one alright. I even talked to her daddy about taking the vow. Never thought I'd find a girl I'd think about marrying, but there she is. Hey, that reminds me...}
{4461}{}{[CONTINUE]}

# Node_Q_CotCAngelaQuest
{4490}{}{Would you do me a favor? I just need to get a message to her.}
{4491}{}{I wouldn't piss in your ear if your brain was on fire.}
{4492}{}{What's the message?}

# Node_Q_CotCAngelaQuest2
{4520}{}{Hey fuck you too, asshole, I was only asking. If you don't want to help, what good is it you being here?}

# Node_IntroThreat
{4550}{}{What, are you nuts? Forget it, I don't even give a damn. Just get out of my cell before you hurt yourself.}

# Node_DumbIntro
{4580}{}{What? It's Magik, shit-for-brains, and I ain't a little boy. I'm the boss around here.}
{4581}{}{Hello Magik Shit for Brains. My name is }
{4582}{}{Boss? Very ugly for a boss. }
{4583}{}{ could die from looking at you too long.}

# Node_DumbIntro2
{4610}{}{I'm uglier than most, but I got what it takes - brains and ambition. That's why a dummy like you only gets to collect junk off my floor. I'm guessing that's why you're here. You want the job?}
{4611}{}{Can I have some money now?}
{4612}{}{ not supposed to take things from strangers.}

# Node_DumbIntro3
{4640}{}{Hah-hah, real funny. You drag your knuckles all the way in here just to drool everywhere, or did you want a job?}
{4641}{}{Can I have some money?}
{4642}{}{I can make bubbles with my mouth.}

# Node_DumbJob
{4670}{}{Not unless you work for it. Just go around the prison, and take anything you find and bring it to me. Easy, right?}
{4671}{}{How much money will I have?}
{4672}{}{Why you need stuff?}

# Node_DumbJobNo
{4700}{}{Look meathead, I don't have time to play with you. You want the job, you take the job, or else you take that goo-goo shit of yours outside.}
{4701}{}{How much money will I get?}
{4702}{}{This cell smells like goo goo shit. }
{4703}{}{ is going outside.}

# Node_DumbPay
{4730}{}{The pay's ten caps per shift. Look, see my fingers? Ten caps, one for every finger. Ten caps for you. Still with me?}
{4731}{}{Yes.}
{4732}{}{ needs money, not small man's fingers.}

# Node_JobPayConfuse
{4760}{}{I ain't paying you in fingers, dummy, 'specially not mine. Look, you work for Magik, he gives you this much money. [He cups his hands together to show you]}
{4761}{}{That is lots of money. }
{4762}{}{ accepts.}
{4763}{}{Do you have any bigger hands?}

# Node_DumbJob3
{4790}{}{Great. Now start looking for stuff and bring it here.}
{4791}{}{'K.}

# Node_JobPayConfuse2
{4820}{}{You better be as sneaky as you are stupid, meathead, else I'm just wasting my time here. You work for me, you get what everybody else gets. Not my fault if you can't count that high. Now do you want the job?}
{4821}{}{Me no want job. Me want money.}

# Node_JobPayConfuse3
{4850}{}{Well a job's just money you gotta sweat for. Last chance now, are you in?}
{4851}{}{Yes! In!}
{4852}{}{In where? Who you?}
{4853}{}{ go out.}

# Node_JobPayConfuseEnd
{4880}{}{Son of a... I'm Magik, you god-damned retard, Magik! Now do you want the job, or do you want to get the out of my sight?}
{4881}{}{Hello Magik You God Damned Reeeeeeeee-tard!}
{4882}{}{Me want some money please. Thank you. Good night.}

# Node_DumbEnd
{4910}{}{Hell... I never thought I'd meet a man to say this to, but you could be twice smarter than you are now and you'd still be the dumbest shit in this place, and that's too dumb to work for me. Out!}
{4911}{}{Hell... I never thought I'd have to say this, but you could be twice smarter than you are now and you'd still be the dumbest shit in this place, and that's too dumb to work for me. Out!}
{4912}{}{Ug.}

# Node_DumbBarrels
{4940}{}{That ain't none of your business. You want this job or not?}
{4941}{}{Me want a job.}
{4942}{}{Me want stuff. No! Two stuffs.}
{4943}{}{Me go out.}

# Node_MurderIntro
{4970}{}{Well well, look who's here. I guess you heard about the little Angela, huh?}
{4971}{}{Well well, look who's here. I guess you heard about your little friend, huh?}
{4972}{}{That's why I'm here. I have some questions for you.}
{4973}{}{I heard about it. It's tragic.}
{4974}{}{No, what happened?}
{4975}{}{I don't listen to rumors. Or idiots.}

# Node_MurderQ
{5000}{}{Right. Did I kill her? No. Do I know who killed her? No. Do I give a shit she's dead? You can take a guess at that one. Are we done?}
{5001}{}{What were you doing the night of Angela's death?}
{5002}{}{You were angry when you found out she was into robots and not you, weren't you?}
{5003}{}{Have you cut yourself recently?}
{5004}{}{Thanks for keeping it short. Bye.}

# Node_MurderInfo
{5030}{}{Seems like someone took it on themselves to right a wrong. Angela got her bitch face smacked in, she's dead.}
{5031}{}{You don't seem too upset about that.}
{5032}{}{Do they know who did it?}
{5033}{}{Where did this happen?}
{5034}{}{I'll go check it out.}

# Node_MurderInfoMoses
{5060}{}{Yeah, they caught that drunk Croz. Shame a guy's got to blow up for doing what had to be done.}

# Node_MurderInfoWhere
{5090}{}{Near a tram station. They caught Croz near the body, Carmichael has him locked up in his cell block.}

# Node_MurderTragic
{5120}{}{That's one word for it, sure. Me, I think she got what was coming to her.}
{5121}{}{Did you have anything to do with this?}
{5122}{}{See you around.}

# Node_MurderAlibi
{5150}{}{Hell, son, how am I supposed to know? I don't keep track of which day is which. I was probably right here in my cell.}
{5151}{}{Hell, precious, how am I supposed to know? I don't keep track of which day is which. I was probably right here in my cell.}
{5152}{}{Bartender said he saw you at the Atom bar that night.}
{5153}{}{Were you angry when you found out she like robots?}
{5154}{}{Thanks for your co-operation.}

# Node_MurderAnger
{5180}{}{Angry? Sure, I get angry every time some bitch lies to my face. If I got angry enough to kill, there'd be a lot more of them dead than Angela.}
{5181}{}{But Angela was special. You wanted to marry her.}
{5182}{}{Where were you on the night of her death?}

# Node_MurderCut
{5210}{}{What sort of question is that? I don't work with my hands, I work with my head. So no, no cuts on me. You check all you want.}
{5211}{}{[Check him for cuts]}
{5212}{}{I'd rather not. Just tell me what you did that night.}
{5213}{}{Were you angry when you found out she was into robots?}
{5214}{}{That's all I needed to know.}

# Node_MurderInfo2
{5240}{}{Face it, she was a freak. No place in a prison for a girl like that. She had to be locked up by the doctors. It had to happen some time.}
{5241}{}{Where did it happen?}
{5242}{}{I'll check out what the doctors have to say.}

# Node_MurderAlibiFails
{5270}{}{He said that, did he? Well, he's probably right. Not an unusual place for me to be.}
{5271}{}{Convenient that you forgot to mention that. Anything else you're forgetting?}
{5272}{}{Bartender also said he saw you talking to Croz.}
{5273}{}{That's all for now.}

# Node_MurderCutNo
{5300}{}{[He's grubby and he smells bad, but there are no obvious injuries on his body]}
{5301}{}{Tell me where you were on the night of the murder.}
{5302}{}{When you found out Angela was into robots, how did you feel? Angry?}

# Node_MurderAlibiF2
{5330}{}{I don't like what you're implying. No, nothing else. I went to the Atom, had a few drinks and came back home, to my cell.}
{5331}{}{Bartender mentioned you were talking to Croz.}
{5332}{}{I'll be back. Your story better check out.}

# Node_MurderAlibiFBob
{5360}{}{So I had a few drinks with an old friend, what's it to you? }
{5361}{}{What was the money for?}
{5362}{}{Croz was angry at Angela, wasn't he? Almost as angry as you.}
{5363}{}{That's all I needed. Thanks.}

# Node_MurderAlibiFMoney
{5390}{}{What? What money, what are you talking about?}
{5391}{}{Bartender saw you pay him. It looked like a lot.}

# Node_MurderAlibiFSkin
{5420}{}{So I get good stuff off Croz, a laser pistol that time, what's the deal? They're hard to get around here, so they don't come cheap. Ask him if you want, that's what the money was for.}
{5421}{}{Do you know what I think?}

# Node_MurderAlibiFAngry
{5450}{}{We both got lied to, so yeah we were angry, we had a right to be. But I don't stick my neck out like that for a girl, any girl.}
{5451}{}{Maybe not. Maybe that's what the money was for.}

# Node_MurderAlibiFEnd
{5480}{}{I don't know what you think I am, but you're wrong. Whatever you got on Croz, I had nothing to do with this.}
{5481}{}{We'll see about that.}

# Node_MurderAlibiFStory
{5510}{}{Go on then. Say your piece and get out of here.}
{5511}{}{You killed Angela. You followed her out of the bar that night and you killed her.}
{5512}{}{You paid Croz to kill Angela. You're too weak to do it yourself, so you got your buddy to do it.}
{5513}{}{You're involved, and I'm going to find out how.}
{5514}{}{You had nothing to do with this. You're in the clear.}

# Node_MurderAlibiFREnd
{5540}{}{You're cutting down the wrong tree. I had nothing to do with this, and you got no evidence to say I did.}
{5541}{}{Not yet. Don't go anywhere, Magik, I'll be back.}

# Node_MurderAlibiFCEnd
{5570}{}{Glad you see a little sense. Now if you don't mind, I got work to do.}
{5571}{}{Thanks for your time.}

# Node_MurderAngerMarry
{5600}{}{Marry her? Where do you come up with that idea?}
{5601}{}{You told me yourself. You said you asked Robb about it.}
{5602}{}{Slappy told me. He said you asked Robb about it.}

# Node_MurderAngryMarry2
{5630}{}{So maybe I did. It was an idea, and not a good one. Besides it all, she turned up a robo-lover, remember? No sense in going after her then.}
{5631}{}{Slappy remembers you being very insistent.}
{5632}{}{A man like you usually gets what he wants.}
{5633}{}{I guess not. Where were you when she was killed?}

# Node_MurderAngryMarry3
{5660}{}{I was into her, I admit that. But when I tell you I got no interest in robo-lovin' bitches, you got to believe me.}
{5661}{}{Where were you the night she died?}
{5662}{}{Have you hurt yourself recently? Any cuts?}
{5663}{}{That's all for now. Thanks for your co-operation.}

# Node_MurderQAuthoratah
{5690}{}{I don't know anything except what I been told. They caught the guy that did it, didn't they?}
{5691}{}{Croz is a suspect. One of several.}
{5692}{}{If you've got nothing to hide, you'll co-operate.}
{5693}{}{Good point. Sorry for wasting your time.}

# Node_MurderQSuspect
{5720}{}{If the Warden wants to point his finger at me, he can do it himself. This is none of your business.}
{5721}{}{By his inaction, the Warden made it my business. Now will you answer my questions?}
{5722}{}{Yeah, you're right. I have no clue what are the Warden's plans regarding this. He must have seen it.}

# Node_MurderQCoop
{5750}{}{We all got secrets, son. But killing that girl ain't one of mine.}
{5751}{}{Everybody got secrets, precious. But killing Angela ain't one of mine.}
{5752}{}{Then you won't mind answering my questions.}
{5753}{}{I'll take your word for it. Goodbye.}

# Node_MurderQ_CLONE
{5780}{}{Try and keep it short, will you? I don't have all day for this.}
{5781}{}{You were angry when you found out she was into robots, weren't you?}
{5782}{}{That's all I needed. Bye.}

# Node_DumbJob2
{5810}{}{Of course you do. Just take your ass outside and get to work. I want all the crap off the floor and lockers and brought to me A.S.A.P.}
{5811}{}{Uh-huh.}

# Node_MidshiftDumbJ
{5840}{}{Hell... Look, you just find stuff on the floor or in the lockers and you bring it here. Okay?}

# Node_MidshiftDumbJ2
{5870}{}{You still got that shiv I gave you? You gotta take it, come up to a prisoner, ask for their stuff they don't want anymore, thrust it in case they don't listen, remember?}
{5871}{}{Shiv thrust. Thrust.}

# Node_MidshiftDumbJ3
{5900}{}{Well then you better try your best to remember. I don't exactly got standards when it comes to workers, but you're pushing all the same.}
{5901}{}{Hurgh.}

# Node_SleepingDumb
{5930}{}{[You poke him. He grumbles something to himself and rolls over]}
{5931}{}{[Poke harder]}

# Node_SleepingDumb2
{5960}{}{[You jab him in the eye. He wakes up]}
{5961}{}{Morning!}

# Node_DefaultIntro
{5990}{}{You again. What do you want?}
{5991}{}{We ought to stop meeting like this, precious. People might start talking.}
{5992}{}{I need a job. Am I in?}

# Node_JobEndDumb
{6020}{}{Here you go, buddy. Same as everybody else. [He hands you some caps] You come back again tomorrow, we can do all this over.}
{6021}{}{Haha!}

# Node_NoonIntro
{6050}{}{Sorry, son, I got a lot of work to do. If you want a job you gotta come see me before noon.}
{6051}{}{Sorry, precious, I got a lot of work to do. If you want a job you gotta come in before noon.}
{6052}{}{I just wanted to ask you some questions.}
{6053}{}{Sure thing.}

# Node_RobGag
{6080}{}{Oh, yeah.. how so?}
{6081}{}{I happen to have all of your caps with me. Found the thief and made her pay for her crime.}
{6082}{}{If I find your money, you give me better deal for all the stuff. I find. Let's say 30 bottlecaps per item.}
{6083}{}{When I think of it better, maybe I don't have a good idea.}

# Shiva
{6110}{}{Just a fancy name I picked up at Fort Aradesh. Man that was ages ago!}
{6111}{}{Just a fancy name I picked up at Fort Aradesh. Precious, that was ages ago!}
{6112}{}{Can you show me on the map where is this Fort Aradesh?}
{6113}{}{Oh, I see. Well I'll be going now. See you later.}

# FortAradesh
{6140}{}{No problem, buddy. It should be riiiiiight... here! [He points the approximate location on his Pip-Boy]}
{6141}{}{Anything for you, precious. It should be riiiiiight... here! [He points the approximate location on his Pip-Boy]}
{6142}{}{Thanks, I'll copy that. See you around.}

# YouThinkStupid
{6170}{}{You think I'm stupid or something? I see now it was *you* who stole it!}
{6171}{}{No, I mean.. Umm...}

# Barter30OK
{6200}{}{A hard bargain, but worth it. Deal. Let me know when you've found my 7,000 caps.}
{6201}{}{A hard bargain, but worth it. Deal, precious. Let me know when you've found my 7,000 caps.}
{6202}{}{Great! I'll be back once I find the bottlecaps.}

# Barter30Fail
{6230}{}{Sorry, that's not worth it.}
{6231}{}{Sorry, precious. It's just not worth it.}
{6232}{}{Oh, crap. At least I tried.}
