#############################################################
#  Message File: kchild.msg                                 #
#                                                           #
#       Body Type: CHILD                                    #
#       Combat AI: Flee                                     #
#       Weapons: None                                       #
#       HP: 20                                              #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: January 13, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{You see one of Tibbets' children... probably.}
{101}{}{You see a weird kid glaring at you.}
{102}{}{You're not sure if this is a kid or an adult.}

#############################################################
#  The following lines are floaters for children            #
#############################################################

{170}{}{Hell-o there.}
{171}{}{Maybe this is Hell and we're all dead.}
{172}{}{Maybe I'm a kid. Or maybe I'm not. What if I'm the Devil?}
{173}{}{How come you can see me?}
{174}{}{Maybe I'm just pulling a prank on you.}
{175}{}{Are you afraid of me?}
{176}{}{You're going to Hell. You know that, right?}
{177}{}{Just end your sorry existence right now.}
{178}{}{You'll never getting out. You belong here.}
{179}{}{All who are here are guilty of something. Even the the kids.}
{180}{}*glare*}
{181}{}{You're dreaming. Again.}
{182}{}{*raises the middle finger*}
