# Message file for tbprsn.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see a service bot.}
{101}{}{You see a friendly and knowledgeable service bot.}
{102}{}{You spot a service bot diligently fulfilling its role as a teacher.}

{105}{}{Although overall design is that of a humanoid, the details reveal this robot wasn't built by a human. It was customized to act as a class teacher.}

# Node 0 [Floats]
{200}{}{The class is currently dismissed.}
{201}{}{If you're interested, you can watch our highly acclaimed documentary: "Facts about Fallout."}
{202}{}{The class will resume as per the schedule.}
{203}{}{Remember to prepare for the upcoming exams.}
{204}{}{We strive to provide satisfying educational programs. Expect more in the near future!}
{205}{}{Tenga un buen dia!}
