# Message file for tbnora.ssl
# Number of nodes: 50
# Grammar pass done

{100}{}{You see a rugged-looking woman in her forties.}
{101}{}{You see Dr. Nora Eastwood, known by the moniker "Black Widow".}
{102}{}{Despite the toll of time, she exudes the indomitable spirit of a natural leader. Her badge reads: Dr. Nora Eastwood.}

{200}{}{*sigh*}

# Nora_unmet
{230}{}{Well, what can I do ya for?}
{231}{}{Who are you?}
{232}{}{No, my good madam. The question is, what do *you* want?}
{233}{}{I am }
{234}{}{. Wrox mentioned you have a job that needs to be done.}
{235}{}{I need to discuss the radscorpions infesting the hospital.}
{236}{}{Ugh ... who you?}
{237}{}{Just thought I'd say hi before I end you.}
{238}{}{Apologies, wrong room.}

# Nora_impatient
{260}{}{[She knits her brows.] I ain't got time to chew the fat. Say your piece or git.}
{261}{}{Wrox mentioned something about a job?}
{262}{}{Are you aware of the radscorpions in the hospital?}
{263}{}{Can you provide information about the asylum?}
{264}{}{Fine, I'm leaving.}
{265}{}{Why don't you try and *make* me leave?!}

# Nora_stupid
{290}{}{Blast it, how'd this galoot get in here? Look... You. [She points at you.] Skedaddle. [She points at the door.]}
{291}{}{Me go.}
{292}{}{Me *no* go!}

# Nora_crossroadsno
{320}{}{[She rolls her eyes.] Find some other soul with time to jaw.}
{321}{}{Okay then...}

# Nora_job
{350}{}{[She studies you.] What I need right now is a slick talker, someone who doesn't pester too much. You got what it takes?}
{351}{}{Sure, I can negotiate. What's the job?}
{352}{}{I'm not much of a smooth talker, but I can get the job done.}
{353}{}{Not interested in that kind of deal. Goodbye.}

# Nora_job2
{380}{}{I gotta see you strut your stuff before I trust you with something this vital. Let's see... Heard tell that Taz is rustling up a lil' gang, the Freeroamers, I believe. Seb could sort it out, but let's put your talents to the test. "Settle" the situation to everyone's liking, and I'll know if you're the right fit for the job.}
{381}{}{Can you provide more information?}
{382}{}{Do I get paid for this?}
{383}{}{I'll return once it's "settled".}
{384}{}{On second thought, I'll pass. Goodbye.}

# Nora_job3
{410}{}{[She scowls.] That ain't how I run my show. Can you negotiate or not?}
{411}{}{Alright, I'll talk to them. What's the job?}
{412}{}{I'm outta here.}

# Nora_job4
{440}{}{Have a chinwag with Taz, our patient, and square the deal.}
{441}{}{I'll return once it's resolved.}

# Nora_job5
{470}{}{[She furrows her brow.] Are you gonna do it or not? Your help's appreciated.}
{471}{}{I'll do it.}
{472}{}{Not right now. Goodbye.}

# Nora_radscorpions
{500}{}{[Her eyes pop.] Radscorpions?! There ain't no radscorpions in *my* nut house, partner.}
{501}{}{[Her eyes pop.] Radscorpions?! There ain't no radscorpions in *my* nut house, ma'am.}
{502}{}{Well, not anymore. I discovered their nest and eradicated them.}
{503}{}{Apologies, but there are. They have a nest just behind your wall.}

# Nora_radscorpions2
{530}{}{Is that so? [She sizes you up.] Alright, I reckon you're on the level. Go see Dr. Carl Davide for your pay. He'll dole out 1,000 caps for clearin' out those varmints.}
{531}{}{Thanks, I'll visit Dr. Davide.}

# Nora_radscorpions3
{560}{}{[She sizes you up.] I believe you're on the up and up. Dang it! I won't stand for our patients being put in harm's way. Listen, if you take care of these critters, I'll make it worth your while.}
{561}{}{Sounds good. I'll return once they're gone.}
{562}{}{Whoa, this is beyond my capabilities. I just wanted to inform you.}

# Nora_radscorpions4
{590}{}{[She furrows her brow.] Look, if you can't handle it, we'll tackle the radscorpions together. Come on, lead me to the nest; we ain't walkin' into any traps, got it?}
{591}{}{I suppose I have no choice...}

# Nora_radscorpions5
{620}{}{[She grins.] Reckon that's the last of 'em, eh? Feels good to stretch the ol' legs. I appreciate your help, and I'll have Dr. Davide sort your payment: 500 caps for shining a light on these radbugs with my laser gun.}
{621}{}{Thanks, I'll see Dr. Davide.}

# Nora_radscorpions6
{650}{}{[She smiles.] Good to hear. I've had Dr. Davide set up your pay: 1,000 caps for clearing out the asylum of such nasties.}

# Nora_met
{680}{}{What can I help with?}
{681}{}{I've taken care of those radscorpions.}
{682}{}{I handled Taz.}
{683}{}{Could you provide some information about the hospital?}
{684}{}{Never mind.}

# Nora_townhall
{710}{}{Got wind of it. Good job. You've shown your chops as a "negotiator," just what I need. You see, I aim to mold the future of humankind. Our loony bin's gotten too cramped, and I'm gettin' too long in the tooth to manage it all. But I ain't hanging up my hat until we've laid down some ground rules to ward off chaos. Now, I need you to tackle our patient numbers. Time to trim 'em down. I was hesitant, but after a chat with one of our inmates, the whip-smart Number 31, I'm sure I'm on the right track.}
{711}{}{Why don't you handle it yourself?}
{712}{}{Who are the patients?}
{713}{}{How is this supposed to work? Do I have to eliminate them?}
{714}{}{You're insane. They aren't harming anyone. Goodbye.}
{715}{}{I'll certainly do something about it. Starting with you.}

# Nora_townhall1
{740}{}{[She exhales a long, weary sigh, and you can see the fatigue pulling her down.] It's 'cause you've got the chops, that's why. I need to keep my gloves spotless. Besides, if I were to handle it personally, the fallout could be grave, not just for me, but for the whole medical crew.}
{741}{}{Okay. Who are the targets?}
{742}{}{Okay, but how is this supposed to work? Do I have to eliminate them?}

# Nora_townhall1b
{770}{}{[She squints at her desk.] Here's the roll call: Supercell, the Rainmakers, Pretty-Natty, Wrox, Wiggie, Zeph, Sandy Fats, Hocus, Roberta, and Slappy. Any of their spawn, too. You'll be bearing the ill tidings to 'em and playing the trail boss for our future.}
{771}{}{Wow, okay. But how is this supposed to work? Do I have to eliminate them?}

# Nora_townhall1c
{800}{}{[She chuckles softly.] Now that's a good question, but I ain't got the answer. Just run 'em off... With a bit of luck, once you kick up a dust storm, our future will take off!}
{801}{}{Well, who are they?}
{830}{}{I see.}

# Nora_townhall1e
{860}{}{[She chuckles softly.] Now that's a good question, but I ain't got the answer. Just run 'em off... With a bit of luck, once you kick up a dust storm, our future will start lookin' brighter!}

# Nora_townhall2
{890}{}{[She squints at her desk.] Here's the roll call: Supercell, the Rainmakers, Pretty-Natty, Wrox, Wiggie, Zeph, Sandy Fats, Hocus, Roberta, and Slappy. Any of their spawn, too. Bear the ill tidings to 'em and play the trail boss for *our* future.}
{891}{}{Wow, okay. But why don't you just do it yourself?}
{892}{}{I see. But how is this supposed to work? Do I have to eliminate them?}
{920}{}{Okay. But how is this supposed to work? Do I have to eliminate them?}
{950}{}{But why don't you just do it yourself?}
{1040}{}{Who are they?}
{1070}{}{Okay. Give me the list. Who are they?}
{1100}{}{But why don't you just do it yourself?}

# Nora_townhall4
{1190}{}{[She leans back.] I know it's a big ask, but I reckon you're the top hand for the job. If you pull this off, the whole of humanity will tip their hat to you. Give me a holler when you're ready to saddle up.}
{1191}{}{I'll return when I'm ready.}
{1192}{}{I'm ready now.}

# Nora_townhall5
{1220}{}{[Dr. Nora's demeanor seems to brighten, shedding a few winters off her face.] You did it! Well, I'll be, now I can start contemplating hangin' up my hat. Humanity owes you a debt, }
{1221}{}{, and they won't forget it. As for me... Well, shucks, now that you've cleared my plate, I don't need this anymore. [She hands you her laser pistol.] She's bailed me out of more tight spots than I can count, and I reckon she'll do the same for you. Thanks again, amigo.}
{1222}{}{Thanks, Dr. Nora! Take care.}

# Nora_happy
{1250}{}{[She grins.] Good to see you, }
{1251}{}{. How can I be of service?}
{1252}{}{Hi, Dr. Nora. Do you have any more work for me?}
{1253}{}{I'd like to learn more about you, Dr. Nora.}
{1254}{}{Could you tell me about the asylum, Nora?}
{1255}{}{Just stopping by to say hi, Dr. Nora.}

# Nora_happy2
{1280}{}{[She chuckles softly.] I'm eyeing retirement, remember? Check with Dr. Davide for any more chores.}
{1281}{}{Okay. By the way, I'd like to hear more about you.}
{1282}{}{Sure. Could you tell me about the asylum?}
{1283}{}{All right. I'll do that. See you later, Nora.}

# Nora_history
{1310}{}{[She blinks.] Well, I reckon there ain't too much to spin a yarn about. Raised on a dusty brahma ranch out in Shady Sands, I was. 'Course, when my Pa passed on, I moseyed on over to Vault City. Aim was to become a sawbones - medicine, you know. Spent a good few years patching up folks, then decided to hitch my wagon with my kin, and headed for the Hoover Dam. Darnedest thing happened about fifteen years back, though. Some bucket of bolts - robots, that's what they were - got the drop on us and corralled our caravan. Sure as sunrise, that was an experience I'd rather not repeat.}
{1311}{}{What can you tell me about the asylum?}
{1312}{}{What made you leave Shady Sands?}
{1313}{}{Tell me about your family.}
{1314}{}{Tell me about your travels.}

# Nora_crossroadsyes
{1340}{}{What're you itching to know? 'Bout fifteen years past, they hauled me over to Tibbets. Didn't take long to find my footing as a medical hand. The Warden took note of my knack for the trade, and I put in a word for a shift to this place, to team up with ol' Doc Davide. Sure, we don't exactly see eye-to-eye on what's to come for this loony bin, but there's a heap of respect between us, no question about that.}
{1341}{}{Okay.}
{1342}{}{Can you tell me about your family?}
{1343}{}{Can you tell me about your travels?}

# Nora_history2
{1370}{}{*sigh* Well, reckon there's a handful of reasons. Deathclaw ruckus was picking up, government folk were getting more crooked by the day, and my Pa kicked the bucket. Felt like I was due for a shake-up after all that. A new line of work.}
{1371}{}{What's a deathclaw?}
{1372}{}{May I ask about your father?}
{1373}{}{Can you tell me about the asylum?}
{1374}{}{Thanks for sharing your story. Goodbye.}

# Nora_family
{1400}{}{Family? Just me and my two young bucks, Lawrence and Warren. My old man passed on years back, over in Vault City. Darned cancer, got it from radiation poisoning.}
{1401}{}{May I ask about your father?}
{1402}{}{Tell me about Lawrence.}
{1403}{}{Tell me about Warren.}
{1404}{}{That's all for now. Goodbye.}

# Nora_travels
{1430}{}{Well, I've rambled far and wide. Vault City pulls on my heartstrings the most, but that's probably 'cause I hold dear memories of my late husband there. And the political hullabaloo was something I had a taste for. First Citizen Joanne Lynette is a true cowgirl at the helm, and working together with her was downright satisfying.}

# Nora_wife
{1460}{}{[Her smile withers.] I ain't in the mood to chew the fat about him.}
{1461}{}{Nora, I think it would do you some good to share your feelings.}
{1462}{}{I understand. Can I ask you about Lawrence?}
{1463}{}{I understand. Can I ask you about Warren?}
{1464}{}{Sorry, I'll leave you be now. Goodbye.}

# Nora_wife2
{1490}{}{Spill my guts?! Just let sleeping dogs lie.}
{1491}{}{Your good intentions don't go unnoticed, but it'd just stir up old dust that took a fair piece of time to settle.}
{1492}{}{Okay. Can I ask you about Lawrence?}
{1493}{}{Okay. Can I ask you about Warren?}
{1494}{}{All right, I'll be on my way then. Goodbye.}

# Nora_lawrence
{1520}{}{Lawrence? He's my firstborn, tough as an old boot. [She pulls a face.] Might be too tough sometimes, but I'm glad he didn't take a shine to my line of work in medicine.}
{1521}{}{Thank you. Goodbye.}
{1522}{}{What about Warren?}

# Nora_warren
{1550}{}{Warren? He's a fine lad. [She draws nearer.] Now, just between us fence posts, he's a bit green behind the ears... I'm glad he won't be following in my footprints. Can't say I'm tickled about his fraternizing with those jailbirds, though.}
{1551}{}{Thank you. Goodbye.}
{1552}{}{What about Lawrence?}

# Nora_deathclaw
{1580}{}{You ain't crossed paths with a deathclaw yet, huh? Well, count yourself lucky, partner. Those critters are the stuff of bad dreams, like a bolt of lightning in a gecko's body. Yep, that's a deathclaw for ya.}
{1581}{}{Yikes! Sounds like something I should steer clear of. Goodbye.}
# Nora_BW
{1640}{}{Just call me Black Widow, if it's all the same to you.}
{1641}{}{Fine, fine.}
