# Message file for tbprsn.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see a Corrections Officer.}
{101}{}{You see a law enforcement bot, maintaining the peace within the facility.}
{102}{}{You see a Corrections Officer, its presence emanating authority and discipline.}

{105}{}{Although overall design is that of a humanoid, the details reveal this robot wasn't built by a human.}

# Node 0 [Floats]
{200}{}{I'm here to ensure order, not engage in conversation.}
{201}{}{I'm not programmed to respond to your inquiries.}
{202}{}{Proceed to your designated area, Number 13.}
{203}{}{*glare*}
{204}{}{Vacate the area immediately.}
