# Message file for tbprsn.ssl
# Number of nodes: 1

{100}{}{You see an Officer.}
{101}{}{You see a redeemed prisoner.}
{102}{}{You see somebody wearing a jumpsuit with number 13, just like you. However, they move around freely and are armed too.}

# Node 0 [Floats]
{200}{}{What are you doing walking around Tibbets?}
{201}{}{Prisoner, how can I help?}
{202}{}{Stranger.}
{203}{}{Don't do anything stupid.}
{204}{}{Let me double-check your Pip-Boy ID, please.}
{205}{}{I'm not interested in hearing any cop jokes.}
{206}{}{What is your business here?}
{207}{}{Wanna hear a cop joke? Neither do I.}
{208}{}{Keep your nose clean.}
{209}{}{Prisoner, how can we help?}
{210}{}{Talk to the Sheriff.}
{211}{}{Officers at your service.}
{212}{}{We're prisoners too. Figure it out.}
{213}{}{Stay away from the lower levels.}
{214}{}{Stop by the Church in CB29.}
{215}{}{Welcome to the most civilized cell block.}
{216}{}{Watch yourself.}
{217}{}{Watch out for any fake police.}
{218}{}{Tibbets is a youth with a Molotov cocktail in his hand, aimed at the heart of the society. And we are here to gun him down before he succeeds.}
{219}{}{Tibbets' the most civilized prison I know of.}
{220}{}{We protect Tibbets and its people.}
{221}{}{Tibbets' safe while we're around.}
{222}{}{This cough is going to kill me.}
{223}{}{*yawn*}
{224}{}{Somebody ate my donut.}

# fighting
{300}{}{Freeze, motherfucker!}
{301}{}{Freeze!}
{302}{}{If you run, you'll only go to jail tired.}
{303}{}{I'm taking you to a slammer.}
{304}{}{You're busted!}
{305}{}{I'll blow you away!}

# pc's a Sheriff
{400}{}{Sheriff.}
{401}{}{Sheriff. It's good to see you back.}
{402}{}{Everything fine, Sheriff?}
{403}{}{BOLO.}
{404}{}{Take care, Sheriff.}

# fleeing
{500}{}{We've got a weirdo!}
{501}{}{Unit requests backup! Now!}
{502}{}{Damn, we're under heavy fire!}
{503}{}{And I though you were a dog call.}
{504}{}{I need assistance!}
{505}{}{I'll return. With a bigger gun!}
{506}{}{Call for backup!}
{507}{}{Backup!}
