# Message file for tbprsn.ssl
# Number of nodes: 1

{100}{}{You see an addict.}
{101}{}{You see someone high.}
{102}{}{You see someone in a drug-induced state.}

# Node 0 [Floats]
{200}{}{*hrrhg*}
{201}{}{It's full of stars!}
{202}{}{Wait for me!}
{203}{}{Whooooooa!}
{204}{}{Huh?}
{205}{}{Where am I?}
{206}{}{*cough*}
{207}{}{*sniff*}
{208}{}{Ahhhh...}
{209}{}{I'm floating...}
{210}{}{I can feel it!}
{211}{}{Look at the colors!}
{212}{}{Mother?}
{213}{}{All the colors...}
{214}{}{More longer friend see that sky?}
{215}{}{They aren't listening...}
{216}{}{Where am I?}
{217}{}{There it is!}
{218}{}{Whoa, yes! Stop! Wait! No! Okay, go ahead.}
{219}{}{There, there... ahh...}
{220}{}{So, so beautiful!}
{221}{}{What was that?}
{222}{}{The colors are fading!}
{223}{}{Mom?}
{224}{}{Dad?}
{225}{}{Father?}
{226}{}{I can see... again.}
{227}{}{Need...}
{228}{}{Get more...}
{229}{}{There? No.}
{230}{}{No. Can't find it.}
{231}{}{Make it stop!}
{232}{}{Ug.}
{233}{}{Oh, the pain.}
{234}{}{*cough* *cough* *cough*}
{235}{}{My head!}
{236}{}{I'm in Heaven! Finally!}
{237}{}{I always thought I'd end up in Hell!}
{238}{}{Warmness...}
{239}{}{Love...}
{240}{}{Peace. Love. Unity. Respect.}
