# Message file for tbpretty.ssl
# Number of nodes: 12

{100}{}{You see a beautiful girl.}
{101}{}{You see Pretty-Natty.}
{102}{}{She's talking to herself.}

# Node001
{200}{}{[She looks at you quizzically]}
{201}{}{Hi, I'm }
{202}{}{.}
{203}{}{Me }
{204}{}{[Look back at her quizzically]}
{205}{}{[Leave her alone]}

# Node002
{230}{}{And I'm the queen. Reeeeaaalllllllllllly bad! To help me ease my fears, Beth took me on a tour of the downstairs of the "hospital" and it was reeeeeeeeealllllllllllllllllly nice.}
{231}{}{Excuse me?}
{232}{}{Say hello to Beth for me. I have to go.}

# Node003
{260}{}{I have a ton of family around that would take care of me. I would be so much better off in the mental hospital than I would be here.}
{261}{}{This *is* a mental hospital.}

# Node004
{290}{}{My mom always said that I didn't have any close friends. She was a nurse, but wasn't one for a reason. All this family stuff started to pop up, and I realized that none of my immediate family would understand me. I am one of those people that isn't my full personality until I am around others.}
{291}{}{I give up.}
{292}{}{So who are you?}

# Node005
{320}{}{I want to be a famous actress in New Reno that acts in movies and sings for a living! I'm not crazy. Still. LIVING IN A HOUSE THAT WE BARELY OWN!!!!! My ex was taking me out on fancy dates that cost him 40,000 caps, not including tickets to see stand-up shows and expensive rides home because he was wasted! I wear my hair in braids. The engagement was already on. He's got a PIP!}
{321}{}{You were engaged?}

# Node006
{350}{}{His mom told him to shave his face but he wouldn't do it. He just said he doesn't like it and he was shaving his whole body. Who likes to shave their whole body at 16? I bet he had one thing on his mind. Just getting his body wet and turning it into a little hunk of meat. He knows what he's supposed to do but that's not enough.}
{351}{}{Your ex was gay and you broke off the engagement?}

# Node007
{380}{}{He loved me and wrote me a letter. Want to hear it?}
{381}{}{Sure, why the hell not?}
{382}{}{No not really. Goodbye.}

# Node008
{410}{}{Just want to take a moment and tell you that I am sure that we will always be best friends. That you can talk to me about anything and that I love you more than words can say. I never could imagine spending my entire life with anyone but you and I hope that you always stay that way. I wish I had a thousand moments with you but I cherish the ones I have. And I will never ever forget the day I found you.}
{411}{}{[CONTINUE]}

# Node009
{440}{}{I was young. You had no idea how much you would mean to me. Even when you decided to end things with me at the end of last year, and tried to get me to stay by coming to my house, all that I wanted was for you to be mine. I still love you with all my heart. I would die for you and I know that you would die for me. There isn't anything that we have had that has been easy and that's because we've been together so long. I wouldn't trade it for the world.}

# Node010
{470}{}{I hope you marry the right guy and I hope he gives you all the happiness that you deserve. You are amazing and you make me believe that there is love and trust. Thank you for being my best friend. I couldn't have asked for a better one. I love you so, so much.}

# Node011
{500}{}{P. S. I hope that you can forgive me for running away but if not... I know we'll be fine. Don't know if you'll ever read this letter but if you have, please know that you have always had a special place in my heart. There were years when I hated you and there were years when I loved you. But I have always loved you. I always will.}
{501}{}{That was nice and sad. Good luck and goodbye!}

# Node012
{530}{}{I want to be a famous actress in New Reno. Start a fanclub. Adopt radscorpions. Name my radscorpion "Susan" after my mom. Have the next UFO crash into my front yard. Have my career be in the top 10. Have my new movie be shown at a huge theater in town with cheap tickets.}
{531}{}{Keep dreaming big!}
