# Message file for tbraincult.ssl
# Number of nodes: 4
# Grammar pass done

{100}{}{You see a person behaving unusually.}
{101}{}{You see a member of the Rainmaker cult.}
{102}{}{You see a person gazing at the sky with devotion.}

# Player has not yet joined the Rainmaker Cult.
{200}{}{Welcome to our Temple, seeker.}
{201}{}{Have you accepted Troposphere as your savior?}
{202}{}{Praise be to Troposphere, for It is mighty.}
{203}{}{Seek guidance from Supercell if you wish to join us.}
{204}{}{Repent your sins and embrace the path of Troposphere.}
{205}{}{Treat every raindrop with reverence, for they carry the blessings of Troposphere.}
{206}{}{Are you in need of spiritual guidance, traveler?}
{207}{}{Read the Weather Forecast Magazine, stranger. It holds wisdom and enlightenment.}
{208}{}{Follow the Way of the Rain and find solace in Troposphere's embrace.}
{209}{}{Clouds, the unsung heroes of our world.}

# Player is a member of the Rainmakers
{230}{}{Good day, my fellow devotee.}
{231}{}{Will you be attending today's prayer service?}
{232}{}{It is good to see you again, faithful one.}
{233}{}{Let us join in prayer together, for Troposphere's grace is upon us.}
{234}{}{Have you communed with Troposphere recently? His wisdom flows through us.}
{235}{}{Continue spreading the word of Troposphere and His eternal rain.}
{236}{}{If you ever feel lost, let the Rainwater guide you back to the righteous path.}
{237}{}{Greetings, fellow missionary. Your dedication is commendable.}
{238}{}{Pray with fervor, for Troposphere's blessings will shower upon us.}

# Stupid PC is the prophet of Troposphere
{260}{}{The Holy One blesses us with His rain.}
{261}{}{Please, Prophet, remember me in your sacred prayers.}
{262}{}{Impart to us your divine wisdom, Holy One.}
{263}{}{You are truly blessed to carry the message of Troposphere.}
{264}{}{It cannot be long now until Troposphere bestows His glory upon us all.}
{265}{}{Show us the way to the Heavens, Holy One, and we shall follow faithfully.}
{266}{}{I saw you in my visions, Prophet. Your presence brings hope.}
{267}{}{I prayed for your arrival, and Troposphere has answered.}

# Player has been thrown out of the temple for sinning
{290}{}{Blasphemer! You have forsaken us all.}
{291}{}{You have betrayed the trust of Troposphere and His followers.}
{292}{}{It may not be too late if you seek forgiveness through heartfelt prayers.}
{293}{}{Your actions have brought disgrace upon Troposphere's name.}
{294}{}{Please, do not return here with your sinful presence.}
{295}{}{We hate the sin, but still hold love for the sinner within our hearts.}
{296}{}{The heretic returns, unrepentant and unchanged.}
{297}{}{You should have resisted temptation and upheld Troposphere's teachings.}
{298}{}{Troposphere will judge you for your transgressions!}
