# Message file for tbrake.ssl
# Number of nodes: 34
# Grammar pass done

{100}{}{A towering figure catches your eye.}
{101}{}{You see Rake, the Super Mutant.}
{102}{}{His expression is disarmingly friendly for someone of his size.}

{200}{}{Rake see no other mutants, Rake still look.}
{201}{}{Maybe Rake return to the west someday.}
{202}{}{Rake no know other mutants here.}
{203}{}{Good for Rake to live with same mutants.}

# Rake floats these if the local variable Rake_Temper < 0.
{230}{}{You no better than Master!}
{231}{}{Leave Rake alone!}
{232}{}{Rake deserve more good.}
{233}{}{Tibbets not like nasty like you.}

# Rake's standard floats.
{260}{}{That dinner? That no look like dinner.}
{261}{}{Why metal men bring Rake here?}
{262}{}{Rake hope farm safe.}
{263}{}{*fart* Hehe!}
{264}{}{*frrrrrrrrrrrrpt* Oops!}
{265}{}{Rake miss old farm.}
{266}{}{Rake miss big sky.}

# Rake_1a_1
{320}{}{Hullo.}
{321}{}{I'm not familiar with your kind. What are you?}
{322}{}{Greetings, big guy. The name's }
{323}{}{. How did you end up here of all places? }
{324}{}{I've heard unnerving tales about giant green men like you.}
{325}{}{What brings you so far to the east?}

# Rake_1a_2
{350}{}{Rake live on farm. Rake work much there, but metal men take Rake. Metal men no like farm.}
{351}{}{Do you recall anything from before you became this... large?}

# Rake_1b
{380}{}{Hello again, Rake remember you.}
{381}{}{Hello, Rake. Do you have a moment to answer a question?}
{382}{}{I'll have to catch up with you later. Goodbye.}

# Rake_1c_1
{410}{}{Rake no likes }
{411}{}{. Leave.}
{412}{}{Rake, I apologize for my earlier comments. I didn't mean to offend you.}
{413}{}{To hell with you, mutant. [Attack him.]}
{414}{}{[Leave.]}

# Rake_1c_2
{440}{}{You think Rake big and green, Rake not feel hurt? You go. Rake no want talk.}
{470}{}{Me }
{471}{}{.}
{472}{}{What you?}
{473}{}{Are Rake "bad green man" others tell me 'bout?}

# Rake_1D_a2
{500}{}{Hullo, }
{501}{}{. [He points to himself.] Rake. What you do here?}
{502}{}{Are Rake "bad green man" others warn me 'bout?}

# Rake_1D_b1
{530}{}{Hullo, again. Rake remember you. You only one Rake smarter than. That make Rake like you lots!}
{531}{}{Are you bad green man other tell me 'bout?}
{532}{}{Me have answers. Rake give questions. No! Me ask, Rake ask! No! Me ask, Rake answer. Yes!}

# Rake_2_1
{560}{}{Rake what you call "army super mutant". Master put Rake in glow green water vat.}
{561}{}{What did this glowing green water do?}
{562}{}{Who is this "Master" you speak of?}
{563}{}{Who "Master"?}

# Rake_2_2
{590}{}{Rake was happy boy once, then Master take me, put in vats. Rake is Rake now.}
{591}{}{Could you tell me more about this "Master"?}
{592}{}{They say that there's a large band of mutants living in the west.}
{593}{}{That sounds gruesome. I'll leave you be - I wouldn't want to contract anything.}

# Rake_2_3
{620}{}{Rake no like Master. Master make many like Rake for Unity army. Master cause much death. But man kill Master long time ago, destroy Master's and Lou's houses.}
{621}{}{Go on.}
{622}{}{What happened to the other mutants the Master created?}
{623}{}{What a load of crap. Start telling the truth.}
{624}{}{That's quite a tale. Goodbye for now.}
{625}{}{Uh-huh.}
{626}{}{Me got other question for ask.}
{627}{}{[Leave.]}

# Rake_2_4a_1
{650}{}{Rake find farm in desert, start work there. People like Rake; Rake good farmer, very pop-u-lar.}
{651}{}{You're popular? That might be a bit of an exaggeration, don't you think? }
{652}{}{Let me ask you about something else.}
{653}{}{Quite the hero, aren't you? Until next time, champ.}
{654}{}{Me want ask other thing.}

# Rake_2_4a_2
{680}{}{Rake good farmer. Rake know people, they like Rake work. You not one to question Rake people knowledge.}
{681}{}{You're lying to yourself, Rake. That's just pathetic.}
{682}{}{I stand corrected. Let me ask you about something else.}
{683}{}{I take back my words. Goodbye for now.}

# Rake_2_4b
{710}{}{Other mutants go elsewhere, past mountains. Rake know nothing of them. Rake live on farm long time.}
{711}{}{Where did you first find the farm?}
{712}{}{Understood. Tell me something else. }
{713}{}{I see. Goodbye for now.}

# Rake_2_4BA
{740}{}{Rake speak truth! Why you think Rake lie? Rake no like how you talk to Rake.}
{741}{}{If there's anything worse than a giant green idiot, it's one that tells lies.}
{742}{}{My mistake, sorry. Let's go back to talking about where you first found the farm.}
{743}{}{Maybe I'll come back when I'm in a more trusting mood.}

# Rake_3_1
{770}{}{You no need fear Rake. You know super mutants? Surprise. We been long time. No one know now; no one see us; no one care.}
{771}{}{I've heard there are plenty of creatures like you all over the west. What's going on?}
{772}{}{I've heard about you "super mutants". Can you tell me more about yourself?}
{773}{}{Bugs like you should be squashed by the windshield of my cleansing vehicle. [Draw weapon.]}
{774}{}{Let me ask you something else.}
{775}{}{Goodbye for now.}
{776}{}{What super mutant?}
{777}{}{Me got 'nother ask for Rake.}

# Rake_4_1
{800}{}{Rake always first in kitchen. Rake eat four dinners! Rake once break food machine. You go eat dinner there too. But fast, or Rake eat for you. Hehe.}
{801}{}{Will do, Rake. It was nice talking to you. }
{802}{}{Have you ever considered going on a diet?}
{803}{}{Let me ask you something else.}
{804}{}{Now me ask you other thing.}

# Rake_4_2
{830}{}{Rake no do diets. If Rake diet, Rake kill Rake.}
{831}{}{So basically, you're an old, ball-less, cheating, fat mutant with no conscience or sense of righteousness? Yep, I think that sums you up.}
{832}{}{I'll leave you to your dinner-patrol.}

# Rake_5_0
{860}{}{What you mean? Rake live in Necropolis. Young Harry come, cast Rake out.}
{861}{}{I heard there are many more creatures like you on the west coast. Aren't you related to them?}

# Rake_5_1
{890}{}{Rake leave Necropolis. Rake never go back there. Rake know no mutant friend there. Rake know no mutant there at all.}
{891}{}{Come on, there has to be someone there you know. }
{892}{}{I know you're lying. }
{893}{}{Tell me more about the mutants. Where did they come from?}
{894}{}{All right, Rake, I think I'll let you sit here and think for a bit. See you later. }

# Rake_5_2a
{920}{}{Rake say Rake know no mutants.}
{921}{}{What do you think happened to the remaining members of the Master's army?}
{922}{}{I want to know something else.}
{923}{}{I'll be going now.}

# Rake_5_2B
{950}{}{You say Rake lie. How Rake trust you no lie when you say mutants live in west?}
{951}{}{Careful, dummy, that was almost a clever retort. Don't strain your brain too much.}
{952}{}{I don't want to argue about it. Goodbye.}

# Rake_9
{980}{}{You ask fast. Rake must watch dinner time.}
{981}{}{You seem a bit too, uh, green to be human. What are you?}
{982}{}{I've heard some bad stories about giant green men like you. What have your kind been up to?}
{983}{}{Why do you keep an eye on dinner time?}
{984}{}{A big galoot like you can't skip a meal? Why not go on a diet?}
{985}{}{I heard there are many more creatures like you in the west. Are you connected to them in any way?}
{986}{}{I'd better leave you to it, in that case.}

# Rake_9_D
{1010}{}{Haha! You even dumber than Rake. What you want ask? Be quick. Rake must eat dinner.}
{1011}{}{You bad green man other tell me 'bout?}
{1012}{}{Rake eat dinner?}
{1013}{}{Me leave Rake busy.}

# Rake_B1
{1040}{}{I don't like }
{1041}{}{. }
{1042}{}{ needs leaving.}
{1043}{}{[Do as he says.]}
{1044}{}{Fuck you, you green idiot! [Attack him.]}

# Rake_B2
{1070}{}{Rake beat your head into the ground.}
{1071}{}{[END]}

# Node028
{1100}{}{?}
{1101}{}{Ra.. Rake?!}

# Node029
{1130}{}{Yes, it Rake! Rake surprised!}
{1131}{}{Holy shit, I haven't seen your mug since Harry exiled you from Necropolis! That was, what.. almost 100 years ago!}
{1132}{}{Rake alive? Me think Harry killed Rake in Necro-place.}

# Node030
{1160}{}{Time fly. Rake farmer now. Rake good.}
{1161}{}{So, have you ever regretted those things you said back then about the Unity?}
{1162}{}{Rake talk crap about Lou and Master. Me remember now.}

# Node031
{1190}{}{*sigh* Rake lose memory. Many years pass. Rake farmer now.}
{1191}{}{Okay, Rake. I'll leave you alone. It was nice seeing you again, brother.}
{1192}{}{Oki, Rake. Me go now. You be good.}
{1193}{}{Well, I haven't forgotten. I always wanted to beat the crap out of you for saying that. Harry was too kind to let you go easily.}
{1194}{}{Me hate Rake. Rake insult Lou, Mom, and Dad! Me hurt Rake bad!}
