# Message file for tbradonc.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see a prisoner in a torn lab coat.}
{101}{}{You see a "Radiation Oncologist".}
{102}{}{He wears an old badge reading "Radiation Oncologist". You have no idea what that stands for.}

# Node 0 [floats]
{200}{}{Nobody needs radiation oncology anymore.}
{201}{}{Radiotherapy is a future they said.}
{202}{}{Pfft, might as well prescribe sunshine therapy.}
{203}{}{Nowadays, radiation oncology is like using a stone axe to perform brain surgery.}
{204}{}{Radiation oncology's like trying to put out a wildfire with a water pistol.}
{205}{}{Radiation oncology's as antiquated as bloodletting.}
