# Message file for tbrice.ssl
# Number of nodes: 9
# Grammar pass done

{100}{}{Your see a woman whose hands are replaced with intricately-crafted mechanical prosthetics.}
{101}{}{You see Rice-Rice.}
{102}{}{Her disheveled appearance and peculiar aroma suggest a need for a good wash.}

{150}{}{Psst!}
{151}{}{Hey, over here.}
{152}{}{Approach me.}
{153}{}{Their gaze is perpetual...}
{154}{}{Unyielding surveillance...}
{155}{}{I perceive them...}
{156}{}{And they perceive me...}

# Node_001
{200}{}{Psst! Hey, }
{201}{}{, could you step closer?}
{202}{}{Are we acquainted?}
{203}{}{Me know?}
{204}{}{[Choose to ignore her]}

# Node_002
{230}{}{Of course we are! It's me, Rice-Rice.}
{231}{}{Your name doesn't stir any memories.}
{232}{}{How can I assist you, Rice-Rice?}
{233}{}{Nope.}
{234}{}{Me help?}

# Node_003
{260}{}{Hmm... they've gotten to you faster than I anticipated.}
{261}{}{Gotten to me? What are you implying? Who are "they?"}
{262}{}{Did you require something?}
{263}{}{They?}
{264}{}{What rice need?}

# Node_004
{290}{}{Observe them closely. The other inmates. Something about their movement... unnaturally... devoid of human warmth!}
{291}{}{Weirdos?}
{292}{}{I'll remain vigilant.}
{293}{}{Weird-men?}
{294}{}{Me watch.}

# Node_005
{320}{}{Yes, them! The copycats, }
{321}{}{, they're observing us, orchestrating our every action! It's the water!}
{322}{}{What do you mean by "it's the water"?}
{323}{}{How exactly are they manipulating us?}
{324}{}{I believe it's time for me to depart. Your sanity seems questionable.}
{325}{}{Walter?}
{326}{}{Huh?}
{327}{}{You loooooo-ney.}

# Node_006
{350}{}{Who can say?! Drugs, chemicals, small robots? What other secrets are they withholding?}
{351}{}{What leads you to believe that robots would engage in such actions?}
{352}{}{Did you have a purpose in calling me over, Rice-Rice?}
{353}{}{Quite a conspiracy theory...}
{354}{}{Why robo-men do it?}
{355}{}{'K. What rice want?}
{356}{}{Me go. Me go far away.}

# Node_009
{380}{}{What makes you so sure they wouldn't?}
{381}{}{Did you require something, Rice-Rice?}

# Node_010
{410}{}{Yes! You'll converse with them, won't you? I need your eyes! Inform me of your observations.}
{411}{}{What should I be keeping an eye out for?}
{412}{}{Sorry, Rice-Rice, I can't commit to gathering intelligence for your delusions.}
{413}{}{Wut look?}
{414}{}{Me no look. You mad.}

# Node_011
{440}{}{Perhaps... perhaps. Remain alert. Their watchful eyes are omnipresent...}
{441}{}{You're crazy.}
{442}{}{Mad rice.}
