# Message file for tbrobb.ssl
# Number of nodes: 97
# Grammar pass done

{100}{}{You see a tough-looking man.}
{101}{}{You see Officer Robb.}
{102}{}{He has a knife tucked into his belt.}

# Robb's standard float nodes.
{200}{}{I wish Grace was still here.}
{201}{}{I wish Angela wouldn't be so into this bar and its patrons.}
{202}{}{This place doesn't run itself.}
{203}{}{Yet more prisoner records to sift through. *Sigh*}
{204}{}{I should check the cell blocks soon.}
{205}{}{I hope we have enough space to accommodate any new newmugs.}
{206}{}{Angela, the apple of my eye.}

# Robb floats these lines if the rumor about Angela being a fan of robots is out, and the PC tries to speak to him directly.
{230}{}{I've got nothing to say to you at the moment.}
{231}{}{I hope you weren't the one spreading those... things about my daughter.}
{232}{}{If Angela's a robo-slut, I'm a god-damned brahmin.}
{233}{}{Come back later, okay?}

# Robb floats these lines if he really dislikes the PC (the local variable Robb_Temper is <= -5 or something), and the PC tries to speak to him directly.
{260}{}{I've got nothing to say to you.}
{261}{}{You're bad news, stranger. Stay the hell away from me.}
{262}{}{Oh, look. Here comes trouble.}
{263}{}{I'm done taking shit from you.}

# Robb floats these lines once Angela has been killed.
{290}{}{*Sigh*}
{291}{}{I can't believe it. I just... can't.}
{292}{}{Why did this have to happen?}
{293}{}{I've got no one. No one.}

# Robb floats these lines if he is in jail for the murder of Angela.
{320}{}{I'm not a bad man. Am I?}
{321}{}{Angela, I didn't mean it. I'm still your daddy.}
{322}{}{In a way, this is a relief. At least I don't have to pretend anymore.}
{323}{}{No hangman's noose is going to be put around me, goddamn it.}
{324}{}{How did it come to this?}
{325}{}{If I could just go back and stop myself from doing what I did.}

# Robb floats these lines if the PC told him that they're okay with Angela's choices.
{350}{}{Take your "alternative lifestyle" elsewhere.}
{351}{}{What you do isn't natural.}
{352}{}{You've got problems.}
{353}{}{Stay away from my Angela.}
{354}{}{I don't want you putting ideas in my daughter's head.}
{355}{}{Find someone else's daughter to prey on.}

# Robb_1a
{410}{}{Hello?}
{411}{}{Sorry to intrude, my name's }
{412}{}{.}
{413}{}{Hello.}
{414}{}{Give me one reason why I shouldn't kill you.}

# Robb_1a_2G
{440}{}{I'm Robb, Officer Robb. How can I help you?}
{441}{}{If you wouldn't mind, I'd like to know a bit about what you do around here.}
{442}{}{I'll come back later.}
{443}{}{What do you do in this place?}
{444}{}{[Leave]}

# Robb_1a_2N
{470}{}{So, you want to tell me who you are and what you want?}
{471}{}{Me }

# Robb_1b
{500}{}{Good to see you again, }
{501}{}{. What can I do for you?}
{502}{}{I've been speaking to Angela, and I think there's something you should know.}
{503}{}{Would you mind telling me what you do around here?}
{504}{}{Sorry, wrong prisoner. Goodbye.}

# Robb_1b_2B
{530}{}{What?}
{531}{}{You heard. Or are you deaf as well as senile? Give me one reason why I shouldn't kill you.}
{532}{}{Nothing. Wrong prisoner. Goodbye.}
{533}{}{What do you do here?}

# Robb_1c_1
{560}{}{What do you want now? I'm not in the mood for any of your smart mouth, in case you're planning to unleash it on the world.}
{561}{}{Robb, if I offended you before, I'd like to apologize for what I said.}

# Robb_1c_2a
{590}{}{Really? In that case, apology accepted. Be a little more careful with your choice of words in the future, though. So what can I do for you?}
{591}{}{That was it. Goodbye for now.}

# Robb_1c_2b
{620}{}{You don't *look* too sorry. I'm busy, kid. I don't have time for this. Come back another time.}

# Robb_1d_1
{650}{}{[Robb's eyes are red-rimmed and tired-looking] What? What do you want?}
{651}{}{Are you all right, Robb? You seem upset.}
{652}{}{I need to ask you a question about Angela's death.}
{653}{}{Who rattled your cage?}
{654}{}{Nothing. I'll come back at a better time.}
{655}{}{Why you upset?}

# Robb_1d_2a_1
{680}{}{"Am I all right?" What the fuck do you think? My daughter's dead. I'm about as far from all right as it's possible to be.}
{681}{}{I'm sorry, I had no idea. How did it happen?}
{682}{}{I'll come back at another time.}

# Robb_1d_2a_2
{710}{}{Murder, they say. Carmichael has the killer locked up; I hope we blow up the bastard soon.}

# Robb_1d_2B
{740}{}{Just leave me alone.}
{741}{}{Not before I put you out of your misery.}

# Robb_1d_2D
{770}{}{I don't need this. Look, kid, go play somewhere else, okay? Your Uncle Robb needs some time on his own. Please?}

# Robb_2_1
{800}{}{Mind? Hell, I wouldn't mind. It's good to talk; beats keeping an eye on other prisoners all day. I'm Officer Robb, one of the Sheriff's men.}
{801}{}{Do you not get to talk to people as much as you'd like?}
{802}{}{Why is there a Sheriff and deputies when there are robots here too?}
{803}{}{Thanks for the information. Goodbye for now.}

# Robb_2_1D_1
{830}{}{I'm Officer Robb.}
{831}{}{Ofirobo?}

# Robb_2_1D_2
{860}{}{Aw, I wish Grace were still here. She would be much better at dealing with these... slow types.}
{861}{}{[CONTINUE]}

# Robb_2_1D_3
{890}{}{Robb is a name, Officer is a job title, kid. You know what an officer is? I don't think you should even be in here.}
{891}{}{Who Grace?}
{892}{}{Me know Ofi. Me like crime.}

# Robb_2_1D_4a
{920}{}{Grace is my wife. Well, she was my wife; she died six years ago.}
{921}{}{That sad. Me go.}

# Robb_2_1D_4b
{950}{}{They let you commit crimes? Hell, they're even more lenient than you are. Take care of yourself and don't let me catch you "liking crime."}
{951}{}{Crime.}

# Robb_2_2a_1
{980}{}{Heh. That's kind of a crude way of putting it, but, yeah, I guess that's about right.}
{981}{}{I find it strange that an officer should yearn for conversation.}
{982}{}{I can't say I blame people for avoiding a crusty old fart like you.}

# Robb_2_2a_2a_1
{1010}{}{Truth be told, I haven't been the same since Grace died six years ago. She was my best friend as well as my wife.}
{1011}{}{I'm really sorry to hear that, Robb.}
{1012}{}{Do you not like talking to the prison staff and prisoners?}
{1013}{}{What's that got to do with anything?}
{1014}{}{Do you not have any other family members?}

# Robb_2_2a_2a_2B
{1040}{}{[He blinks and frowns] Grace used to help a lot in making the time pass faster. We used to laugh more throughout the day. Without her around, I have to find the strength on my own every day.}

# Robb_2_2a_2a_2G
{1070}{}{Thanks, I appreciate that.}

# Robb_2_2a_2a_3
{1100}{}{They're great, but I don't get much time to kick back and shoot the breeze with the guys up front like I used to.}

# Robb_2_2a_2B
{1130}{}{Usually, I'd let that slide. Just watch where you're treading, okay?}
{1131}{}{"Usually you'd let that slide"? What's changed?}

# Robb_2_2b_1
{1160}{}{A robot can't read people as well. Even the ol' Warden has trouble. It's hard for them to earn trust and build connections too. Some of us think it's for the best, for all of us. There isn't just one reason, but many.}
{1161}{}{Where can I find this Warden?}
{1162}{}{How old is the Warden?}
{1163}{}{Can I ask you about something else?}

# Robb_2_2b_2a_1
{1190}{}{Where can you find him? Hahahaha! That's a good one! Thanks for the laugh, it's been a while. Have you ever heard of a place called Cryogenic Cell Block 0, kid?}
{1191}{}{Yes.}
{1192}{}{No.}

# Robb_2_2b_2a_2
{1220}{}{Well, the story goes, before the bombs, the Warden was the first prisoner here. In a sense. Not that he committed any crime, but he can't ever leave. They even say the missing cell blocks, 0 to 12, were here on these levels too until he moved them. Yes, *moved*. Somehow, somewhere.}

# Robb_2_2b_2b
{1250}{}{Hell, from a long, long time before the war. I don't know much more about it, though.}

# Robb_3_1
{1280}{}{I only have one daughter, Angela. She's the apple of my eye. I'd do anything for her.}
{1281}{}{What can you tell me about Angela?}
{1282}{}{Can I ask you about something else?}

# Robb_3_2_1
{1310}{}{She's a great kid. Heh. She's not much of a kid these days, though. It's about time she found herself a good man and settled down.}
{1311}{}{Is she single?}
{1312}{}{Do you want her to start a family?}

# Robb_3_2_2a
{1340}{}{Ho, I can see which part of you calls the shots. Cool your heels, stallion. Magik doesn't count, so yeah, she's single. She's also pretty picky.}
{1341}{}{Magik doesn't count, so yeah, she's single.}
{1342}{}{Who's Magik?}

# Robb_3_2_2b_1
{1370}{}{No man likes to see his little girl grow up, but sure, I do. None of us are getting any younger; it would be good to hear the pitter-patter of tiny feet around these halls before my last trial by dynamite.}
{1371}{}{I know how she feels. Decent men are rarer than a one-headed brahmin.}
{1372}{}{Maybe I should meet her and see if we hit it off.}
{1373}{}{Trial by dynamite?}

# Robb_3_2_2b_2a_1
{1400}{}{Maybe you should. Just treat her right, okay? Otherwise, you'll see a side of Robb you won't like.}
{1401}{}{You've got yourself a deal. Where can I find her?}

# Robb_3_2_2b_2a_2
{1430}{}{She's usually over there, by the bar. Just remember what I said, though. And watch out for Magik. He won't be too happy about you muscling in.}

# Robb_3_2_2b_2b_1
{1460}{}{Uh... Angela's kind of choosy. Maybe you'd be better off with another girl.}
{1461}{}{What are you saying? I'm the whole package.}

# Robb_3_2_2b_2b_2
{1490}{}{[He tries to suppress a smile but fails] Sure you are. Hey, at least you're not Magik.}
{1491}{}{I don't care for that smile much. I feel like wiping it off your face.}
{1492}{}{I'm not hanging around here to be insulted. [Leave]}

# Robb_3_2_2b_2F_1
{1520}{}{Well, look, uh... seeing as you're a chick and all, maybe you could have a woman-to-woman talk with her? You know, tell her a few tricks of the trade or something. She might be happier talking about guy stuff with you.}
{1521}{}{I'll see what I can do. Where can I find her?}
{1522}{}{Your daughter's problems don't concern me.}

# Robb_3_2_2b_2F_2a
{1550}{}{Thanks! She's usually over there, by the bar. Just make sure you don't convince her to go with Magik.}

# Robb_3_2_2b_2F_2b
{1580}{}{No, you're right, stranger. I shouldn't be bothering you with my family's concerns. So, is there anything else I can help you with?}

# Robb_3_2_2c
{1610}{}{Magik? Ah, he's this joker who thinks he's got a shot at winning Angela. Fat chance, though. Hah! That's my Angela. She knows a dud when she sees one.}
{1611}{}{But you want Angela to settle down with someone, right?}

# Robb_4_1
{1640}{}{Really? [He grins] What's she been up to now?}
{1641}{}{There's no easy way to say this, but she's into robots.}
{1642}{}{I've found out why she's been telling you that she isn't dating any of the men in Tibbets.}
{1643}{}{She and I are dating each other.}

# Robb_4_2a_1
{1670}{}{Well, this I have to hear. So tell me.}
{1671}{}{The guy she's dating is a prisoner who only comes out of his cell rarely. Angela thinks you wouldn't approve of him.}
{1672}{}{She's training to join the Rainmakers. She's abstaining from sex as part of her priesthood training.}
{1673}{}{She is dating someone in Tibbets, but she thinks you won't approve of him.}
{1674}{}{Maybe another time. Goodbye for now.}

# Robb_4_2a_2a_1
{1700}{}{Is that so? Tell me more about this guy.}
{1701}{}{He's an ex-bounty hunter. Apparently, he earned a lot of money.}
{1702}{}{He's an ex-caravanner. He worked the runs in the NCR.}
{1703}{}{Actually, there is no guy. Angela likes robots.}
{1704}{}{Actually, it's me. Angela and I are dating.}

# Robb_4_2a_2a_2a
{1730}{}{To think I had no idea. I look forward to meeting him one of these days. Thanks, stranger. It's good to know Angela's getting on with her life.}
{1731}{}{Glad I could help. Goodbye for now.}

# Robb_4_2a_2a_2b
{1760}{}{Hmm... that doesn't sound like Angela's type of guy. And I have a feeling you're hiding something. What's the real story with my daughter?}
{1761}{}{Goodbye for now.}

# Robb_4_2a_2b_1
{1790}{}{Those crazy cultists? I had no idea. Angela's so... down to earth. I guess there's a lot I don't know about my own daughter.}
{1791}{}{I'm sorry you had to find out this way.}
{1792}{}{What are you going to do about it?}

# Robb_4_2a_2b_2
{1820}{}{[He sighs] I don't like it one bit. Hopefully, this is just a phase she's going through. I'll stand by her, of course, but the sooner she's through with these rain loonies, the better.}

# Robb_4_2a_2c
{1850}{}{Bullshit. Angela would never fall in with those wackos. You know something else. What are you hiding?}

# Robb_4_2a_2d_1
{1880}{}{Huh. I don't like to think I'm that judgmental. So who's she finally managed to snare?}
{1881}{}{Actually, she hasn't snared any man. Angela likes robots.}
{1882}{}{Croz.}
{1883}{}{Magik.}
{1884}{}{Aldo.}
{1885}{}{A guy named Francis.}
{1886}{}{Me.}

# Robb_4_2a_2d_2a
{1910}{}{Croz? I don't believe it. If Angela was interested in him, I'd know about it. He's a regular patron down here and a fellow officer, after all. What are you really hiding?}
{1911}{}{Angela and I are dating each other.}

# Robb_4_2a_2d_2b
{1940}{}{Magik? Everyone in town knows Angela doesn't care a toss for him. If you're going to bullshit me, at least come up with someone believable. What's the real story here?}

# Robb_4_2a_2d_2c
{1970}{}{What the hell? Aldo's a filthy drunkard. No woman in her right mind, let alone Angela, would touch him with a barge pole. What's the real story here?}

# Robb_4_2a_2d_2d
{2000}{}{Francis? I don't know any Francis in Tibbets. There *isn't* any Francis in Tibbets. What's the real story with my daughter?}

# Robb_4_2a_2d_2e_1
{2030}{}{*You*? Listen, buddy, I ain't a mean guy, but you ought to know that every branch hit you in the face when you fell outta the ugly tree. Tell me what you really know about my daughter.}
{2031}{}{Who are you calling ugly, old man?}

# Robb_4_2a_2d_2e_2
{2060}{}{Sorry, I don't mean to be cruel, but this is Angela we're talking about. You're not even in the same league as my daughter. So tell me, what's really going on?}
{2061}{}{Fuck you. [Push him]}

# Robb_4_2a_2d_2f
{2090}{}{I don't think so. Word gets around when a stranger comes into prison, and no one I've spoken to has said anything about you and Angela getting together. What do you really know about my daughter?}

# Robb_4_2b_1
{2120}{}{Robots? What the hell do you mean, robots?}
{2121}{}{Robots as in machines. She's a robo-lover.}

# Robb_4_2b_2
{2150}{}{God damn it! I know what robo-lover means, you dirty bastard! What I mean is, who do you think you are, coming in here and saying such things about my daughter?}
{2151}{}{God damn it! I know what robo-lover means, woman! What I mean is, who do you think you are, coming in here and saying such things about my daughter?}
{2152}{}{I just thought you might like to know. Don't take it out on me.}
{2153}{}{I'm sorry, Robb. I know the truth can be painful, but it's better that you know.}

# Robb_4_2b_3
{2180}{}{GET OUT OF MY GOD DAMN SIGHT!}
{2181}{}{I'm going, I'm going!}
{2182}{}{Don't shoot the messenger, asshole. *This* messenger shoots back. [Fight him]}

# Robb_4_2c
{2210}{}{Pardon me? How can that be possible? You're a woman, and I know Angela only likes men.}
{2211}{}{Oops... Well, okay then. Open your eyes, Robb. Angela's into robots.}
{2212}{}{Better to love women than robots, right?}
{2213}{}{Better to love women than men, right?}

# Robb_4_9
{2240}{}{Not yet. This is important to me. Tell me what you know about Angela.}

# Robb_5_1
{2270}{}{What's to ask?}
{2271}{}{Why do you think Angela left the bar so late at night?}
{2272}{}{I found this book inside a packed bag in Angela's cell. What do you think its significance is?}
{2273}{}{Why did you buy a doctor's bag from Eugene?}
{2274}{}{When was the last time you saw Angela?}
{2275}{}{There's no easy way to say this, but did you have anything to do with Angela's death?}

# Robb_5_2a_1
{2300}{}{I reckon she'd been driven away by the foul rumors that had been started about her. Maybe she made a break at night to save having to explain herself to everyone.}
{2301}{}{Which rumors were those?}
{2302}{}{The rumors about her loving robots, you mean?}
{2303}{}{I need to know something else about Angela's death.}

# Robb_5_2a_2a_1
{2330}{}{That's right. I hope you had nothing to do with them.}
{2331}{}{Don't worry, I didn't have anything to do with them.}
{2332}{}{They weren't rumors, though. Angela was a robo-lover. It wasn't her fault if Tibbets couldn't handle it.}

# Robb_5_2a_2a_2
{2360}{}{Good thing too because if I found out that you did, I'd... never mind.}
{2361}{}{You'd what?}

# Robb_5_2a_2a_3
{2390}{}{I said never mind.}
{2391}{}{Angela was a robo-lover, though. It wasn't her fault if Tibbets couldn't handle it.}

# Robb_5_2a_2b
{2420}{}{You know the ones. About her being a goddamn robo-bitch of all things.}

# Robb_5_2a_2c_1
{2450}{}{How DARE you? What makes you think you know my daughter any better than I do? [He pauses and winces] Better than I *did*.}
{2451}{}{She told me herself that she was into robots.}

# Robb_5_2a_2c_2
{2480}{}{You're a liar as well as a poisonous gossip-monger! Get out of here before you force me to do something I regret.}
{2481}{}{Something like what? Kill me, like you killed Angela when you couldn't bear to hear the truth from her?}

# Robb_5_2a_2c_3
{2510}{}{I swear, boy, you are pushing me too far.}
{2511}{}{I swear, girl, you are pushing me too far.}
{2512}{}{I think I've heard all I need to hear. Goodbye for now.}

# Robb_5_2a_2c_4
{2540}{}{You've got some nerve, kid. Some nerve. I think you'd better leave right now.}

# Robb_5_2b_1
{2570}{}{[He looks surprised] I don't know. Maybe she was planning a picnic or something. Who knows?}
{2571}{}{You're her father. She didn't mention her plans to go anywhere to you at all?}

# Robb_5_2b_2
{2600}{}{Don't be ridiculous. Come on, she was a grown woman, for pity's sake. You think she still came to me for permission to go anywhere?}

# Robb_5_2c
{2630}{}{Like I already said, I have no idea why that bag was where you found it.}

# Robb_5_2d_1
{2660}{}{What the hell has that got to do with what happened to my daughter?}
{2661}{}{Eugene said you came to him recently, and that you seemed pretty badly hurt. I just wondered what happened.}

# Robb_5_2d_2
{2690}{}{[You notice that Robb hasn't taken one hand away from his waist since you've been speaking to him]}

# Robb_5_2d_3
{2720}{}{Look, I've been having trouble sleeping at night since... since what happened to Angela. I thought the medicine might help.}
{2721}{}{Does it help?}
{2722}{}{Are you sure that's all it is? Can I have a look under your arm, there?}

# Robb_5_2d_4a
{2750}{}{Huh. I get to sleep all right. Doesn't stop the dreams, though.}
{2751}{}{Can I have a look under your arm, there?}

# Robb_5_2d_4b
{2780}{}{[Robb's eyes narrow in suspicion] No, you can't.}
{2781}{}{Does the medicine help you get to sleep?}

# Robb_5_2e_1
{2810}{}{It was at the bar on the day she... you know. On the day of what happened to her.}
{2811}{}{Bartender told me you went after Angela when she left. Did you catch up with her?}
{2812}{}{I found this book inside a packed bag in Angela's room. What do you think its significance is?}

# Robb_5_2e_2
{2840}{}{No, I didn't. I spent a few hours looking for her, then came home to bed. Look, is this going somewhere?}

# Robb_5_2f_1
{2870}{}{Of course, I didn't. I'm her father, aren't I? I'm the last person who would harm her.}
{2871}{}{I'm beginning to think that you did kill her.}
{2872}{}{Can I ask you another question about Angela's death?}

# Robb_5_2f_2
{2900}{}{How can you accuse me of such a thing? I loved my daughter! I always gave her everything she ever wanted for.}

# Robb_5_2f_3
{2930}{}{She was just waiting for the right man to come along, that's all. Someone to make her happy. But no, someone had to go and ruin it all.}
{2931}{}{Someone like you. Someone for whom Angela being a robo-lover meant the end of all their dreams.}
{2932}{}{I need to ask you another question about Angela's death.}

# Robb_9a
{2960}{}{Sure, ask what you want.}
{2961}{}{If you wouldn't mind, could you tell me a bit about what you do around here?}
{2962}{}{I'll leave you to it. Goodbye.}

# Robb_9b
{2990}{}{Not really, no. If you'll excuse me, I just want to be on my own.}
{2991}{}{Wait, I need to ask you something else about Angela's death.}

# Robb_B_1
{3020}{}{Oh, a hot-head, eh? I've dealt with your sort more times than you've had hot dinners, boy.}
{3021}{}{[He laughs] Now, really, what sort of talk is that from a nice young lady such as yourself?}
{3022}{}{You're about to find out that my bite is worse than my bark, old man. [Attack him]}

# Robb_B_2
{3050}{}{Pay attention, kid. You might even learn something.}
{3051}{}{[Fight]}

# Node091
{3080}{}{Forget I said anything. Ask the Sheriff; maybe he'll tell you more.}
{3081}{}{I will. Goodbye.}
