# Message file for tbsat.ssl
# Number of nodes: 12

{100}{}{The console is locked.}

# Node001
{200}{}{Welcome to CWC SAT - Creativity Writing Class StarCon Aptitude Test. To proceed please login and use the touch screen to select the answers you think are correct.}
{201}{}{[Login as Prisoner 72]}
{202}{}{[Override the login as Prisoner 13]}
{203}{}{Do I really have to do this?}
{204}{}{Me no want test.}

# Node002
{230}{}{1) Gronko is commanding a Nova Class scoutship when he finds himself face to face with three Horak battle cruisers. He should:}
{231}{}{A) Surrender in the face of impossible odds.}
{232}{}{B) Pretend they aren't there.}
{233}{}{C) Activate his ship's self-destruct sequence.}
{234}{}{D) Beam over a 'Pick-U-Up' bouquet.}
{235}{}{E) Reboot.}

# Node003
{260}{}{2) When encountering an alien ship for the first time you should immediately:}
{261}{}{A) Open fire with every weapon at your disposal.}
{262}{}{B) Broadcast Wagner's "Ride of the Valkyries" over the com-link.}
{263}{}{C) Beam your entire crew over to their ship as a gesture of goodwill.}
{264}{}{D) B then A.}
{265}{}{E) None of the above.}

# Node004
{290}{}{3) Before beaming down to an unexplored planet for the first time you should be sure to check:}
{291}{}{A) To see that your seat belt is fastened and tray tables are locked securely in the upright position.}
{292}{}{B) Your fly.}
{293}{}{C) Your life insurance coverage.}
{294}{}{D) The fetzer valve in your oxygen mask.}
{295}{}{E) The planet's atmospheric readings.}

# Node005
{320}{}{4) You're marooned on an alien planet with no weapons and a killer android out for your blood. You should:}
{321}{}{A) Gather basic ingredients to make gun powder and fashion a cannon from vines and sticks.}
{322}{}{B) Stuff a banana in its exhaust pipe.}
{323}{}{C) Drop a big rock on the robot and shout "Special delivery!"}
{324}{}{D) Roll in the mud to camouflage yourself.}
{325}{}{E) Climb a tree, flap your arms wildly, and scream "Tweet-tweet" at the top of your lungs in order to mimic the mating behavior of the Ruby-throated Arcturan Swinefalcon as a diversionary tactic.}

# Node006
{350}{}{5) You're on an EVA with a partner and you notice his face is turning blue and he is clutching wildly at his throat. This is a sign that:}
{351}{}{A) You will soon need a new partner.}
{352}{}{B) In a burst of creative insight, he has created new dance moves.}
{353}{}{C) He is suffering from a vitamin deficiency and needs to eat more leafy green vegetables.}
{354}{}{D) He fell for the old "golf ball in the air hose" trick.}
{355}{}{E) A and D.}

# Node007
{380}{}{6) To ensure that your crew's microwave meals are heated adequately and evenly on board your ship you should:}
{381}{}{A) Wrap everything in aluminum foil.}
{382}{}{B) Cook each meal at the maximum power setting for 45 minutes.}
{383}{}{C) Put a live space varmint in with each meal so you can more easily determine when it is done.}
{384}{}{D) Huck the thing and settle for roasting wieners on the maneuvering jets.}
{385}{}{E) Inject a radioactive isotope into each piece of food: When it glows, it's ready.}

# Node008
{410}{}{7) If Greeb leaves the Crab Nebula at 32:00 GST (Galactic Standard Time) and travels at 9.75 million ZPM, how long will it take him to reach planet Davicon 5 if he has the solar wind at his back?}
{411}{}{A) 49.3 Hours.}
{412}{}{B) He will never reach Davicon 5: The solar wind is highly unstable and will blow him off course.}
{413}{}{C) 3.75 Standard Days.}
{414}{}{D) 49:30 GST.}
{415}{}{E) Never: The neutron star at the center of the Crab Nebula is so massive that Greeb's ship can never reach escape velocity.}

# Node009
{440}{}{8) How fast does light travel through a vacuum?}
{441}{}{A) 186,000 MPS.}
{442}{}{B) Very, very, very, very, very, very, very, very, very, very, very, very, very, very, very, very, very, very, fast.}
{443}{}{C) 669,600,000 MPH.}
{444}{}{D) Depends on whether it's an upright or canister vacuum.}

# Node010
{470}{}{9) What is an example of a "fuzzy boundary?"}
{471}{}{A) The area in space between two planetary bodies where a smaller third object is not clearly under the gravitational influence of either.}
{472}{}{B) The event horizon of a super-massive black hole.}
{473}{}{C) The place where a receding hairline gives way to bare scalp.}
{474}{}{D) The point at which the marginal utility of trying to squeeze the last bit of toothpaste from the tube is offset by the opportunity cost of going to the store for a new one.}

# Node011
{500}{}{10) To successfully accomplish a manual molecular reintegration bypass on a standard transporter unit you should:}
{501}{}{A) Reverse the phase polarity of the interface grid.}
{502}{}{B) Jiggle the handle.}
{503}{}{C) Pray fervently to whatever deity you happen to believe in.}
{504}{}{D) C then B.}
{505}{}{E) Cancel the contract with your STU provider and find a better one.}

# Node012
{530}{}{End of SAT. Thank you for attending another Creativity Writing Class test. Have a nice day!}
{531}{}{That was too hard!}
{532}{}{Hard!}
{533}{}{Easy-peasy!}
{534}{}{EZ-PZ!}
{535}{}{[Logout]}
