# Message file for tbsally.ssl
# Number of nodes: 43
# Grammar pass done

{100}{}{You see a middle-aged tribal woman.}
{101}{}{You see Tall-Sally.}
{102}{}{You see a middle-aged tribal woman with greying hair.}

# Player sold the Sheriff's spot to Magik
{200}{}{I'll never forgive you for this.}
{201}{}{Go away.}
{202}{}{You sold away Joe's life's work to that monster.}
{203}{}{To think I trusted you...}

# Sonny Black has been killed
{230}{}{My poor Sonny Black...}
{231}{}{*sob*}
{232}{}{Such a senseless thing to happen...}

# Sonny Red is dead
{260}{}{Sonny Red... why?}
{261}{}{*sniff*}
{262}{}{I miss him.}

# Family have all been killed - note she will also float Sonny BlackDead and Sonny RedDead at this point.
{290}{}{There's no one left.}
{291}{}{My whole family, gone...}
{292}{}{My darling Joe...}

# Player is the Sheriff
{320}{}{I hope you are doing well.}
{321}{}{Remember to treat other officers properly.}
{322}{}{Please, make Joe proud.}

# First
{380}{}{Oh... hello. You're new in Tibbets, right? I'm Tall-Sally. [She offers her hand for a handshake]}
{381}{}{[Shake her hand] }
{382}{}{. What do you do here?}
{383}{}{Good to meet you, Tall-Sally. See you around.}
{384}{}{Hello Tall! Me friend.}
{385}{}{Hello - bye bye.}

# Subsequent
{410}{}{Hello again. Can I help you with something?}
{411}{}{What do you do here?}
{412}{}{I want to know more about Carmichael's operation.}
{413}{}{Tell me about your family.}
{414}{}{Nothing right now. Goodbye.}
{415}{}{No - me not need anything. Me go now.}

# FamilyDead
{440}{}{[She looks at you with tear-stained eyes] Oh... hello. What... what can I do for you?}
{441}{}{What's the matter, Tall-Sally?}
{442}{}{Nothing at the moment. Goodbye.}

# WhatDo
{470}{}{Well, my husband, Joe Carmichael, is the Sheriff, and my two sons, Sonny Red and Sonny Black, both work with him. I help too, but mostly just keeping our cell block nice, you know.}
{471}{}{That doesn't sound very fulfilling.}
{472}{}{What can you tell me about your husband's operation?}
{473}{}{Tell me more about your family.}
{474}{}{I have to be going - goodbye.}

# Business
{500}{}{Joe has been the second generation of prisoners enforcing the Law. We have a group of prisoners who follow the Holy Word of Law and make sure life here is easier. Since we took over, it's been going from strength to strength.}
{501}{}{I see. Tell me about your family.}
{502}{}{Thanks for the information. Goodbye.}

# Family
{530}{}{Joe and I have been married for 22 years now. We've done as well as most people can in this place. We have two wonderful sons, Sonny Red and Sonny Black, who've been a great help, especially since they became old enough to join us.}
{531}{}{Tell me more about Joe.}
{532}{}{Tell me more about Sonny Black.}
{533}{}{Tell me more about Sonny Red.}
{534}{}{Let's change the subject. What can you tell me about your husband's operation?}
{535}{}{Thanks for the information, Tall-Sally. Goodbye.}

# Family2
{560}{}{Who would you like to know about?}
{561}{}{Tell me about Joe.}
{562}{}{Tell me about Sonny Black.}
{563}{}{Tell me about Sonny Red.}
{564}{}{Let's change the subject. What can you tell me about Hogg's?}
{565}{}{Actually, forget it. Goodbye.}

# Sonny Red
{590}{}{He's our younger son. Sonny Red has always taken after his father. He's turned out to be an excellent salesman. When Joe... passes on, he'll be the next Sheriff.}
{591}{}{Joe is dying?}
{592}{}{What can you tell me about your husband's operation?}
{593}{}{I have to go - goodbye.}

# Sonny Black
{620}{}{He's in charge of our armory. Such a handsome young man he's turned out to be, just like his father. He's very popular with the young ladies in Tibbets, although none of them are really good enough for him. He's 26 this year and should be settling down.}
{621}{}{What can you tell me about Carmichael's operation?}

# Joe
{650}{}{He's always been there for me, ever since the day we met. He always deals fairly with prisoners. I know that he's got some rough edges, but who doesn't? Ever since we found out that he hasn't got long left, I treasure every day he's here.}
{651}{}{He's dying?}
{652}{}{Rough edges? Tell me about them.}
{653}{}{How did you meet Joe?}
{654}{}{Tell me about someone else.}
{655}{}{What can you tell me about Carmichael's operation?}
{656}{}{Thanks, Tall-Sally. Goodbye.}

# Joe2
{680}{}{I don't think that's any business of yours, really. Everyone's allowed a few mistakes without the people who love them bearing grudges or gossiping about their flaws.}
{681}{}{Fine, fine. How did you meet Joe, anyway?}
{682}{}{Fair enough. Tell me about someone else.}
{683}{}{Just making conversation. See you around.}

# Joe3
{710}{}{Well... he's hard on the boys sometimes, but he's just trying to toughen them up for Tibbets. And he's fond of a drink, and sometimes it makes him angry, but he's never laid a finger on any of us.}
{711}{}{Anything else you can tell me?}
{712}{}{Right. Tell me about someone else.}

# Joe4
{740}{}{He... there were a couple of incidents with other prisoners. Evil people. But those got resolved with "trials by dynamite." He really is a good man, despite his flaws. He'd never do anything to hurt me or the boys. We'll all miss him terribly when he's gone.}
{741}{}{Interesting. Tell me more about your family.}
{742}{}{How did you meet Joe, anyway?}
{743}{}{Trials by dynamite?}

# Fulfilling
{770}{}{Oh, but it is. Joe's a wonderful man, and he and the boys go out and maintain law and order. They really make a difference. A robot can never have that human approach. It's the least I can do to make sure that they have a nice place to come home to after work.}
{771}{}{If you say so. Tell me about Carmichael's operation.}
{772}{}{Can you tell me some more about your family?}
{773}{}{I'll take your word for it. See you around.}

# MeetJoe
{800}{}{Well... after my first husband died, I had no idea what to do or where to go. Magik, you know, that salesman, told me he'd take care of me. He said that he loved me. He didn't, of course... he treated me like a dog. Eventually, I ran away.}
{801}{}{Magik sounds like a real asshole.}
{802}{}{What happened next?}
{803}{}{Let me ask you about someone else.}
{804}{}{Tell me more about your husband's operation.}
{805}{}{That's rough. I have to go - goodbye.}

# Magik
{830}{}{I try not to hate people, but Magik is just... a terrible man. I can never forgive him for what he did to me. I think he's also picking on the Wirys, but they're too scared to talk. Honest, humble souls those two.}
{831}{}{So what happened after you left Magik?}
{832}{}{How unfortunate. Well, I have to go now - goodbye.}

# MagikDead
{860}{}{I try not to hate people, but Magik was just... a terrible man. I can never forgive him for what he did to me - I'm glad he's dead. I hope he burns in hell.}

# MoreJoe
{890}{}{I was hopeless. If I hadn't been pregnant, I probably would have thrown myself down the elevator shaft. But one night, I met Joe. We just... fell in love straight away. He told me I'd never have to worry about anything ever again.}
{891}{}{And you lived happily ever after, huh? The guy must have some faults.}
{892}{}{Magik drove you to this? What a jerk.}
{893}{}{Thanks for the story - goodbye.}

# JoeDying
{920}{}{It's liver failure. Both Doctor Danika and Grandmother Spider, our shaman, say there's nothing more they can do. [She begins to tear up] I just don't know what I'll do after he's gone.}
{921}{}{I'm sorry. How did you meet Joe, anyway?}
{922}{}{Sorry to hear that. Goodbye.}

# SonnyBlackAccepted
{950}{}{, I was hoping you'd stop by. I wanted to thank you for persuading my husband that Sonny Black was still part of our family. This is just how it should be, and I'm glad it was settled before Joe passed on.}
{951}{}{My pleasure. See you around, Tall-Sally.}
{952}{}{Well, you know, I generally charge a fee for smoothing out these sorts of problems.}

# Noone
{980}{}{There... there's no one left for me. Joe passed away recently... and my two boys are both gone, killed over such a stupid, petty argument. All I have left in the world is the Holy Word of Law, and I've got no idea how to enforce it. [She begins to sob again]}
{981}{}{Can't you hand it over to someone else?}
{982}{}{That's rough, Tall-Sally. I'm sorry - I hope it all works out. Goodbye.}
{983}{}{That's life, I guess. See you around.}

# SellBusiness
{1010}{}{I don't know anyone who'd want to take over. Joe always said Sonia is too much of a priestess, and Salem is too much of a loner. It feels like everything is in vain now. I don't have much to live for anymore.}
{1011}{}{I guess Magik has the money. Can't you sell it to him?}
{1012}{}{I could take it off your hands.}
{1013}{}{Perhaps it's time to let the robots run the show alone from now on.}
{1014}{}{I wish I could help. Good luck.}

# BuyBusiness
{1040}{}{I'm grateful for the offer, but you don't seem like much of a Sheriff. Do you have any knowledge of law or experience with guns?}
{1041}{}{I'm willing to learn. I believe I could do a pretty good job as a Sheriff.}
{1042}{}{Seems to me like you don't have a lot of choices.}
{1043}{}{There's always Magik. I imagine he'd want to expand his "business" under the guise of law enforcement.}
{1044}{}{On second thought, that's probably a bad idea. Goodbye.}

# BusinessMagik
{1070}{}{No, absolutely not. How could I give the ideas that Joe spent so many years building up to that... that monster?! I'd rather see it all destroyed than let him have it.}
{1071}{}{What if I took over the company?}
{1072}{}{What about ending it all and letting the robots maintain order alone once again?}
{1073}{}{Well, I can't think of a better option than that. Good luck anyway.}

# WantFee
{1100}{}{[She appears flustered] Well, I'm sure that you deserve some sort of reward. But I don't handle the rewards; you'll have to ask one of the boys about that.}
{1101}{}{I'm just kidding, Tall-Sally. I'll see you around.}
{1102}{}{Don't worry; I will.}

# BusinessCost
{1130}{}{Well, if you insist... the Sheriff's position is usually earned through birthright or the Sheriff's personal wishes. Since those don't apply to you, I'm willing to sell you the position for 30,000 bottlecaps. That seems like a fair price to me.}
{1131}{}{That's all right with me. Here's your payment.}
{1132}{}{That's too much. Can't you sell it for less?}
{1133}{}{On second thought, I'm not sure I want to be a Sheriff anyway. Goodbye.}

# BarterSuccess
{1160}{}{I see. Well, I have no dependents now... and I doubt that I'll live for much longer. [She looks despondent] 20,000 caps will be enough, I suppose.}
{1161}{}{That's fair. Here's your money.}
{1162}{}{That's still too much. Make a lower offer.}
{1163}{}{Actually, I'm not sure I want the position anymore. Goodbye.}

# BarterSuccess2
{1190}{}{[She smiles sadly] Anyone would think that you were Joe's son, the way you chase a bargain. Very well - 15,000 caps, and that's my final offer. Make sure it's in good hands.}
{1191}{}{[She smiles sadly] Anyone would think that you were Joe's daughter, the way you chase a bargain. Very well - 15,000 caps, and that's my final offer. Make sure it's in good hands.}
{1192}{}{All right. Here's your money.}
{1193}{}{That's still too much. I've got better things to spend my money on. Goodbye.}
{1194}{}{Actually, I'm not sure I want that responsibility after all. See you around.}

# BarterFail
{1220}{}{I'm afraid I can't sell for any less, }
{1221}{}{. Joe would be turning in his grave if he ever knew I sold the Sheriff's position for less than what it was worth to me.}
{1222}{}{Fair enough. Here's 30,000 caps.}
{1223}{}{Then I don't think we can make a deal. Goodbye.}

# BarterFail2
{1250}{}{No. I'm sorry, but I just can't let you take advantage of my situation. Joe never let anyone walk over him, and neither will I, from now on.}
{1251}{}{That's understandable. Here's 20,000 caps.}
{1252}{}{In that case, I don't think we can make a deal. See you around.}

# BoughtCompany
{1280}{}{Well, here is the badge. I will inform the Warden about this. I genuinely wish you the best of luck, }
{1281}{}{. Salem and others will be able to help you. Please, be honorable, fair, firm, and just. I'd like to think that Joe would approve of what you do as the new Sheriff.}
{1282}{}{Absolutely, Tall-Sally. Good luck.}
{1283}{}{Yeah, we'll see.}

# Stupid
{1310}{}{Well, hello to you too. I have to ask you to leave, dear. I'm very busy. But I hope you're having a nice day.}
{1311}{}{Me help with busy work?}
{1312}{}{Yes, me have nice day. Bye bye.}

# Stupid2
{1340}{}{No, I'm afraid there's nothing you can help me with. Thank you so much for asking, though.}
{1341}{}{Okay, me go.}

# Node035
{1370}{}{That... that was Joe's idea. Instead of sentencing someone to death for the most serious crimes, he or she would be given many ticking dynamites. If a criminal managed to defuse them all, their freedom was earned. Otherwise... well, I had to scrape them off the floor and walls, if you understand me.}
{1371}{}{That's cool!}
{1372}{}{That's sick!}

# Node036
{1400}{}{Thanks, I guess. Now excuse me, we can talk later.}
{1401}{}{[END]}

# Node037
{1430}{}{You're not the only one who thinks like that. Now excuse me, we can talk later.}

# Node038
{1460}{}{No, absolutely not. This is what my family lived for. This is what Tibbets needs, in the present and in the future.}
{1461}{}{As you wish. Goodbye.}
{1462}{}{What about me? I could be a Sheriff.}
{1463}{}{You could earn some nice bottlecaps by handing over everything to Magik.}
