# Message file for tbsherif.ssl
# Number of nodes: 60
# Grammar pass done

{100}{}{You see a combat veteran.}
{101}{}{You see Sheriff Joe Carmichael, the leader of the law-abiding prisoners. Despite his stern demeanor, you sense a deep-rooted anger within him, directed towards you and everyone else.}
{102}{}{His face is contorted with rage, his clenched teeth, fists, and eyes reflecting his inner turmoil. It's clear that he holds no fondness for you or anyone else.}

# Quest is not solved.
{200}{}{Filth, damn filth!}
{201}{}{Damn criminals... I despise them.}
{202}{}{What are you staring at, you pathetic face?}

# NodeA
{860}{}{Eh? Heh, I know that look. You're here for something, aren't you? Newmugs always want something.}
{861}{}{Don't we all want something?}
{862}{}{I'm looking for work.}
{863}{}{I'd appreciate it if you could share your name. I'm }
{864}{}{.}
{865}{}{Newmug, huh? Nice words coming from a pathetic face like yours.}
{866}{}{Maybe I don't want anything. Good day. }
{867}{}{What you do?}
{868}{}{Who you?}

# nodeA1
{890}{}{What do you want now?}
{891}{}{I need directions.}
{892}{}{A name would be nice. I'm }
{893}{}{Is there any work available?}

# NodeA2
{920}{}{I've never seen a newmug who wasn't lazy. Are you sure you want to work? I don't have time for sluggards.}
{921}{}{Maybe you can give me some directions.}
{922}{}{I'm here for work.}
{923}{}{First, tell me your name. I'm }
{924}{}{I haven't seen an ugly face like yours before.}

# A_better_way
{230}{}{Get out of my cell block, maggot. If you come back again without a good reason, I'll personally escort you to the crematorium.}

# AboutSalem
{260}{}{He's a good man, not as capable as Sonia, but dependable. He'll lend a hand when needed. I must warn you, though, Salem has a stubborn streak as strong as a rock.}
{261}{}{Tell me about Sonia.}
{262}{}{Tell me about Maurice.}
{263}{}{Enough talk. Let's take action, Sheriff.}
{264}{}{Killing is simpler. How much are you willing to pay for a clean job?}
{265}{}{There has to be a better way. I'll see what I can do. Goodbye.}

# AboutMaurice
{290}{}{He's one of the few who stays sober most of the time, but he's as rigid and obstinate as an old crusty turd. Thanks to him and Sonia, the Holy Word of Law is being spread among the prisoners.}
{291}{}{Tell me about Salem.}

# AboutSonia
{320}{}{She's been through a lot, seen plenty of action in her life. She lost her husband, but not at the hands of the criminals. If you want to know more, ask her yourself. Most of us struggle to understand what she says, but we know it's profound. Her mind may be affected, but don't call her crazy, at least not to her face.}
{321}{}{Tell me about Salem.}

# Antiratquest
{350}{}{Work? Finally! I've been waiting for this. [He scrutinizes you intently.]}
{351}{}{Well?}

# Askingtobuythings
{380}{}{They must breed you differently where you come from. Can't you use your eyes? There are a few merchants here, more like crooks if you ask me! If you want legitimate goods, talk to my son Sonny Red. Can you handle that, or do you need me to hold your hand?}
{381}{}{How about something else...}

# Sheriffsname
{410}{}{, eh? The name's Joe Carmichael, in case you care. I'm the Sheriff. Anything else?}
{411}{}{Maybe you can tell me where I am?}
{412}{}{I'm looking for work.}
{413}{}{I want to trade.}
{414}{}{That's all for now. Goodbye.}

# comebackwhenneedhelp
{440}{}{You won't go alone, I promise you that. Come back when you're ready to take them on. Me and the boys will be right there with you.}
{441}{}{[END.]}

# continueoutline1
{470}{}{I don't care about their beliefs. What I hate is criminals. Criminals! The scum of the earth, I tell you. The bane of all that is good. But those crime lovers, as long as they keep their actions contained, Tibbets mostly leaves them alone. They don't cause trouble, and they keep their crimes hidden from sight. Most prisoners think they're just drug addicts, useless in a fight, and ordered to be harmless.}
{471}{}{Okay.}
{472}{}{Cut to the chase, old man.}
{473}{}{I don't have time for this right now. Can I ask you something else?}

# Dothisforme
{500}{}{I despise criminals. Do you know what criminals are? I despise them. I'll pay you if you help me exterminate them.}
{501}{}{Oh kay.}
{502}{}{Nuh uh.}

# Donttakeyourowndamntime
{530}{}{Don't waste your time! We need to act fast!}
{531}{}{Sir, yes sir!}

# explaincont2
{560}{}{Criminals only steal when things are going bad, and we won't tolerate that. No sir. Stealing is their way of life. They steal, sell the loot for food or drugs. Look at those crime lovers, sitting around, loafing, getting high, not a shred of work ethic. I tell you, stealing is the only work they *can* do. But they won't steal from me when they face a barrage of laser rays. It's not my problem, they're just thieves.}
{561}{}{If you put it that way. So what's the problem then?}

# hellno
{590}{}{You're not the brightest, are you? [He examines you thoughtfully.] But you're strong, experienced. I can make use of someone like you. There's always work for a diligent person. Interested?}
{591}{}{[Nod.] Uh huh.}
{592}{}{[Shake your head.] Nuh uh.}

# Idonotlikeit
{620}{}{I don't like it. It would be better if we could eliminate all the criminals in one fell swoop.}
{621}{}{Sheriff, killing them would be akin to murder. By doing this, you'll inflict minor harm and maintain a good relationship. Besides, you may need their help in the future. Give me some time.}
{622}{}{You know what? This is too troublesome. Let's eliminate them all right now. What do you say?}

# Imnotsoft
{650}{}{I must be getting soft to even let you near me. Age turns some of us into fools, while others are born that way. No offense, but we don't have a fondness for newmugs here.}
{651}{}{No offense taken, because I don't like you much either.}

# insulthimhakeface
{680}{}{Watch your mouth around here, drifter. We deal with criminals and crime lovers. Shooting, spearing, gutting, and gunning are all in a day's work for us, if you catch my drift.}
{681}{}{My apologies.}
{682}{}{You don't say. I've slain raiders and gutted geckos myself. In SimTek's simulations, that is. Perhaps old age has made you soft, old man.}

# killingratswontstopthemcoming
{710}{}{That's true. If you want help, there's Sonia Needles, although she's not much help lately. You should talk to Salem. Maybe he can assist you or put in a good word. Alternatively, you can seek out the High Priest, Maurice. Ask him about the Holy Word of Law.}

# tallsallymywife
{740}{}{Tall Sally is my wife. She almost succumbed to a strange and vicious flu fifteen days ago. We thought we had lost her for good. In her sleep, it seemed as if she had passed away. The robots nearly claimed her because this flu turns your skin pale blue and ice-cold. Cold, as if dead. But that wasn't the end of it, oh no. There's a twist. Do you know what it is?}
{741}{}{No, I don't.}

# money
{770}{}{Me and the boys scraped together two thousand. It's not much, but we'll support you on this job. Bring your own weapon, though.}
{771}{}{Deal.}
{772}{}{No, that's not enough.}

# Notomoney
{800}{}{It may not seem like much, but we're honest folks, and we'll compensate you fairly. Honest work deserves honest pay.}
{801}{}{Alright, I'll do it.}
{802}{}{No, you can keep your money.}

# NonotkillemLovers
{830}{}{Not the lovers, drifter. Leave them be, and they'll wither away on their own, starving themselves to death. I'm referring to the criminals.}
{831}{}{The criminals?}
{832}{}{Is there someone I can talk to about this? Just killing them might not solve the problem.}

# nodeaskingfordirections
{950}{}{You're in my cell block, on my turf, in my face. If you need directions, do what any reasonable person would do: walk. }
{951}{}{Alright, I'll leave.}
{952}{}{What else can we talk about?}

# NodeB
{980}{}{You again. What do you want this time?}
{981}{}{I've changed my mind; I want to help you.}
{982}{}{Tell me, why do you hate criminals so much?}
{983}{}{Nothing. Goodbye.}

# NodeC
{1010}{}{So, are you ready to take on the challenge?}
{1011}{}{Absolutely. Let's do this.}
{1012}{}{Not just yet. Give me a little more time to prepare.}
{1013}{}{I'm still uncertain about this.}

# NodeD
{1040}{}{How's your progress with the "alternate solution"?}
{1041}{}{Not going too well, I'm afraid.}
{1042}{}{I've come up with something better than just talking to Salem and Maurice. Take a look. [You show him the infrasonic Pip-Boy.]}
{1043}{}{I'm still working on it. Patience, please.}

# NodeE
{1070}{}{Well, well! You've managed to find enough of those items!}
{1071}{}{Let's not waste any more time. Shall we proceed?}

# NodeF
{1100}{}{That was a tough job. Had to be done, though. I'll be smelling like a criminal for a week. Anyway, it was great to have you on board, partner. Whenever you're in this area, drop by the Atom and I'll buy you a drink. Here's your payment. Don't be a stranger, you hear?}
{1101}{}{Thanks. Take care, Sheriff.}

# Notsure
{1130}{}{Now you're having doubts? Listen here. If you back out on me after stirring up trouble, it won't be good for your health, if you catch my drift.}
{1131}{}{I don't take kindly to threats, Sheriff. Watch your words around me.}
{1132}{}{Alright, I'll do it. Just give me a little more time.}
{1133}{}{No, I don't think I can go through with this. There must be a better solution.}

# Nottoowell
{1160}{}{Hah. Figures. Me and the boys are still up for a purge, in case you're wondering.}

# OfcourseIfeelstrongly
{1190}{}{Of course I feel strongly! These criminals are a blight and a menace! Now, do you want to hear the whole story, or are you just interested in the job?}
{1191}{}{Please continue with the story.}
{1192}{}{Tell me what you need me to do.}

# Ohmewatchmyself
{1220}{}{So now you think you're better than the rest of us? Are you saying you want a fight?}
{1221}{}{No offense, Sheriff. Just letting you know where I stand.}
{1222}{}{Whenever you're ready, old man. I won't even need to keep score with my trusty weapon here...}

# outline3
{1250}{}{Here's the problem: the ringleaders have lost control of their scum. It's just as I always said: you can't trust drugheads to do the job right. The criminals are running wild, wreaking havoc in the cell blocks, indulging in sin after sin. If we don't take action, we'll have nothing left in the next year. Our prison is so vast that even with all the help we can muster, we can't hunt them all down.}
{1251}{}{What do you want me to do?}

# outlinecont2
{1280}{}{As for me, I can spot vermin when I see 'em. These crime lovers don't contribute anything, despite their claims of working in the factory and supporting their families. I believe they steal and sell whatever they can to feed their own greed. It's not my concern, though.}
{1281}{}{If it's not your concern, then what's the problem?}
{1282}{}{Why do you say it's not your concern?}
{1283}{}{Never mind, I have other matters to attend to.}

# Outliningtheratsquest
{1310}{}{We have a crime problem here in the prison. We've established a temple dedicated to the Holy Word of Law; you can't miss it. But there are those who worship crime itself! Criminals worshiping crime, claiming that laws are only for gods and our priests aren't kings. All a bunch of brahma shit.}
{1311}{}{They're entitled to their beliefs, aren't they?}

# Setdownsomekilltherest
{1340}{}{That works for me. The fewer we have to deal with, the better. Give them to me, and when you're ready, we'll go and set up these devices. After that, we'll eliminate the remaining criminals.}
{1341}{}{Sounds good to me. Let's do it.}

# sodoff
{1370}{}{No. I don't trust you, drifter. You still carry the stench of criminality. Return when you've rid yourself of that taint.}
{1371}{}{Goodbye.}

# Sonicdevice
{1400}{}{What is it?}
{1401}{}{It's a Pip-Boy device that emits sounds only sleeping people can hear. It brainwashes them, making them obedient to the Warden and the robots. It scares them away without causing harm. Just put these in a cell block on a prisoner or two, and everybody will become like robots over time. Thinking we could hack them and use that to our advantage.}

# stillnotomoney
{1430}{}{We can't offer more at the moment. Return when you're ready to take on the task.}
{1431}{}{Goodbye.}

# Sureamreadytokillrats
{1460}{}{Great. Prepare yourselves, guys! It's hunting season!}

# Surrenderedsix
{1490}{}{Well, fair pay for honest work, I'd say. Here's your payment. It was a pleasure working with you, partner. If you're ever in the area, drop by and have a drink on me. Don't be a stranger, now.}
{1491}{}{Thanks, Sheriff. Take care.}

# Thatsmorelikeit
{1550}{}{That's more like it. Return when you're ready.}

# Thengetthehellout
{1580}{}{Then I have no use for you. A drifter and a fool. Sikes. Come back when you're ready to get things done, mister.}

# ThenIhavenothingforyou
{1610}{}{Eh? So, you're too hesitant? If you're going to get squeamish on me after asking for work, I have nothing for you, drifter. Leave.}
{1611}{}{Goodbye.}

# time
{1640}{}{As long as those criminals leave the law-abiding ones alone, I don't much care how it's done. Once you've gathered around twelve of those doodads, enough for each cell block, come back to me. We'll figure out our next move then.}
{1641}{}{I'll return when I have twelve of them.}
{1642}{}{Actually, I already have twelve of them right here.}

# whatabouttheratlovers
{1670}{}{Let me tell you, drifter: those crime lovers are no different from vermin. They don't do any work, don't give anything back, and can't even be bothered to put up a fight when challenged. They're all about peace and love until people start starving and suffering. They're the reason we have to deal with criminals now.}
{1671}{}{How are they to blame? I thought they would report criminal activities in their cell blocks.}
{1672}{}{I despise criminals. I'm all for taking them down, Sheriff. How can I help?}
{1673}{}{It's going to cost you. How much are you willing to pay me?}

# Whathewantsyoutodo
{1700}{}{I want you to stop those criminals. Strike them where it hurts the most, eliminate them all, and take their Pip-Boys as proof. They're ruthless, and their numbers are overwhelming, but I've gathered some funds for this purpose. If you can clear the scourge from our cell blocks, we'll reward you handsomely.}
{1701}{}{That sounds rather harsh, Sheriff. Won't the crime lovers object?}
{1702}{}{I despise criminals. I'm on board, Sheriff. They've had it coming for a long time.}
{1703}{}{Money talks, old man. How much are you willing to pay me?}
{1704}{}{Perhaps this job isn't for me.}

# whatisthekicker
{1730}{}{Just the day after the doctors said she was recovering, they came back with more test results. She's now infertile. It was a week before we could even talk about it. Every time I see those kids, it breaks my heart knowing that we won't have any of our own. She got infected by those crime lovers, spreading their sickness around without even realizing that we're sinking into chaos.}
{1731}{}{So, what can be done about it? It's not worth going after them with guns, is it? Is there someone we can talk to?}
{1732}{}{I'll get them for you, Sheriff. You have my word.}
{1733}{}{I'll help, but it will cost you. How much are you willing to pay?}

# WhereIstand
{1760}{}{Alright, let's start on a level playing field. As long as you stick to our agreement, we're good. If you need some time to grow a spine, we'll give it to you.}
{1761}{}{I'll hold up my end of the bargain. Maybe I'll even have enough for both of us, considering you seem hesitant to do any actual killing without me backing you up.}
{1762}{}{I won't be long, Sheriff. You can count on it.}
{1763}{}{Very well. Goodbye.}

# WhyIhaterats
{1790}{}{They're the meanest, ugliest, hellspawn creatures you'll ever encounter! They steal our kids' toys, our clothes, food, medicine - everything! They're the wasteland's own vandals, or perhaps they're what came out when the devil had indigestion. Filth, pure filth. I'd feast on them if I had more teeth and they didn't carry diseases that could kill me.}
{1791}{}{But what about the outside bandits? Raiders who steal and destroy. Local criminals aren't the worst we face.}
{1792}{}{Alright, I understand your passion.}
{1793}{}{Never mind. Farewell, lunatic.}

# Whyyou
{1820}{}{I'm gonna blunt my bullets on you for that, newmug...}

# Yeahkillemall
{1850}{}{You've got balls, and I respect that. I'll gather the boys, the hands, and every gun and bit of ammo we have. You bring yours, though; we don't have much, mostly tools and knives. Return when you're ready. This time, we'll go for the ultimate purge.}
{1851}{}{Sheriff the Sheriffer. I like it. Farewell, Sheriff.}

# Yestomoney
{1880}{}{Good. Return when you're ready.}

# yesbanditsdoit
{1910}{}{Bandits come in groups, but our criminals are like wolves disguised as sheep. You can't simply stamp them out. You can negotiate with bandits; with enough money, they won't treat you the way they treated my Tall-Sally.}
{1911}{}{Tall-Sally?}
{1912}{}{That's quite intriguing, but I must be going now.}
{1913}{}{Hmm. Let me ask you something else...}

# yestheydotakecarebut
{1940}{}{They did, or they used to. But they're nothing but druggies. They've gone too far and messed up. Now it's up to us regular folks to take matters into our own hands. I'm all for finding a permanent solution. These criminals have been asking for it since the day they were born.}
{1941}{}{Why do you despise criminals so much?}
{1942}{}{Are you suggesting that they deserve to die?}

# Youseriousyouwanttohelp
{1970}{}{You serious about wanting to help? Taking down criminals like we're about to isn't for the faint-hearted.}
