# Message file for tbsol.ssl
# Number of nodes: 30
# Grammar pass done

{100}{}{You see a woman wearing a worn jumpsuit and a military hat.}
{101}{}{You see Officer Sol.}
{102}{}{She seems to be wearing the raggedy remains of a jumpsuit and a military hat whose emblem you are unfamiliar with. She has an unnatural twitch, and a consistent blank expression points to possible drug abuse. The emblem has "Sol" scratched into it.}

# Pre-quest floaters.
{200}{}{Must be scorching outside, the walls are melting. Can't you feel it?}
{201}{}{Wow, that pink jumpsuit is pretty eye-catching.}
{202}{}{I think I had a little too much... Everything. Too much. Way too much!}

# Node 1 [DUMB_Flo01]
{230}{}{Wow... Everything is so clear now.}
{231}{}{The prophet has set me free!}
{232}{}{Praise the Holy Word of Law!}

# First_Time
{290}{}{You! Get out! Wait... No. Nevermind. Thought you were in my astral space.}
{291}{}{Uhh, what?}
{292}{}{You have to leave, now.}
{293}{}{Seems like you've been on quite a "space trip". Are you okay?}
{294}{}{I'll leave you be then. Take care.}

# ASTEXP_01
{320}{}{What don't you understand? I thought I made myself clear -- the astral space! The plane beyond the physical, the realm of gods and... [Her voice trails off, and her head gradually tilts forward.]}
{321}{}{Are you feeling alright? Is there something I can do to help?}

# AST_REM_RND
{350}{}{*Snort* ...The answer to that question is three times fourteen, of course... *Mumble*}
{351}{}{[Wait for it. She is obviously speaking aloud subconsciously.]}
{352}{}{Alright then, carry on.}

# AST_RND_LIST
{373}{}{...Incoherent jargon remains an expression, regardless of the medium, and is therefore coherent...}
{374}{}{...The object, although non-existent, retains its self-sustained integrity within the mind of the viewer...}
{375}{}{...A squid eating dough in a polyethylene bag is fast and bulbous...}
{376}{}{...Red tastes better than sharp...}
{377}{}{...Minds are not misplaced items, unlike treasures inside sacred cities...}
{378}{}{...No man is more deaf than he who will not hear...}
{379}{}{...Our privilege to fly has been taken away, along with our wings. We are no longer angels...}
{380}{}{...One's image should never exceed one's shadow...}
{381}{}{[CONTINUE]}
{382}{}{*Ahem* Are you alright? You seem to be in a trance.}

# Insulted
{410}{}{[Her eye twitches.] Hah! You sound like one of those unworthy non-believers! Martin be damned! [She spits.] Don't waste my time.}
{411}{}{My apologies if I offended you. I didn't mean any harm.}
{412}{}{Oh, but excuse me your highness! I see you're not interested in conversation. I'll leave you alone then. Keep staring at rust eat away these walls.}

# Annoyed
{440}{}{Look, I don't appreciate being toyed with, got it?}
{441}{}{I apologize if I came across as disrespectful. Let's start over, shall we? Who's Martin?}
{442}{}{I understand. I'll leave you be.}

# WakesFromDaze
{470}{}{[Her head suddenly tilts back.] Oh! Where was I? That's right. Martin will always hold a special place in my heart... Wait, did I say that out loud?}
{471}{}{After you snapped out of it, you said, "Oh!", followed by, "Where was I?", and afte-}
{472}{}{Well. Might as well stick a fork in you and call you done.}
{473}{}{You mentioned that Martin holds a special place in your heart. What does that mean?}

# Martin_LS01
{500}{}{Oh, that's right. Martin. That marvelous bastard! [Her expression turns bitter.] He was so strong. Bad. And I wasn't good enough.}
{501}{}{Good enough for what, exactly?}
{502}{}{Seems like there's some unresolved feelings there. Do you want to talk about it?}

# Martin_LS02
{530}{}{To be worthy of the Holy Word of Law's immaculate mercy! Are you daft? I thought I made myself clear about that, you fucking moron! I-- Oh no. I am... Wait. Damn it, Martin! [Tears start to form in her eyes.]}
{531}{}{Whoa, slow down. I'm sorry if I brought up painful memories. Would you like to share what happened? It seems like you have a lot of bottled up emotions.}
{532}{}{Are you always like a bat out of hell? Bah! Whatever, go on.}
{533}{}{I'm sorry, but I don't think I can help with that. Take care of yourself.}

# Martin_LS03
{560}{}{[She starts sobbing uncontrollably.] I'm so sorry! I have these problems that I thought I could control, but every time I try, it feels like they control me. *sob* Martin was the only one who ever tried to listen to me. He actually cared and paid attention to the things I said, no matter how crazy they sounded... Or I was. [She shakes her head.] Sometimes, these thoughts come back, and they're really disturbing. They've frightened me since I was a child. The Holy Word of Law keeps those thoughts far from reach, and I don't have to worry about them. But...}
{561}{}{But what? What kind of thoughts are you talking about?}
{562}{}{I'm sorry, but I don't think I can offer the help you need. Take care of yourself.}

# Martin_LS04
{590}{}{When I stop attending the ceremonies, those thoughts come back, and they're worse than before. [She looks around, as if to collect her thoughts.] When Martin was around, those thoughts didn't exist. I was happy... WAS happy.}
{591}{}{So, what happened?}
{592}{}{It must be difficult to deal with those thoughts on your own. *yawn*}

# Martin_LS05
{620}{}{Martin was a womanizer. A hunter. He would venture into the prison for weeks at a time, looking for all kinds of girls. I was tired of being lonely, and he was the only one I had ever been so close to. When I asked him to settle down with me, he said he had to go out one more time before he could do such a thing. He hasn't come back since.}
{621}{}{Perhaps it's time to move on from Martin. There might be someone else out there who can understand and care for you.}
{622}{}{Alright, I've had enough. I'm sorry to burst your bubble but you have to leave.}

# Martin_LS06
{650}{}{It's not easy to lose something you never really had in the first place. What if I never find someone like him?}
{651}{}{Life was never meant to be easy. Look at yourself right now. By staying here and doing absolutely nothing but progressively diluting your essence, what do you believe you're accomplishing? By remaining here, how can you be sure there's anyone else out there who truly understands you?}
{652}{}{Arg, alright, I tried. Goodbye.}

# Martin_LS07
{680}{}{You're right... I shouldn't let this hold me back. Maybe it's time to leave this cell block and see what else the world has to offer.}
{681}{}{I'm glad you're considering new possibilities. Sometimes, stepping out of our comfort zones can lead to unexpected opportunities.}

# Quest_FORK
{710}{}{Leave? I'm Officer Sol, a child of the universe, and this is my territory. I think I'll stick around.}
{711}{}{This territory might be restricting your potential. There's a whole world out there waiting for you to explore.}
{712}{}{You have the freedom to choose, but remember that staying within the boundaries of this cell block might limit your growth.}
{713}{}{Alright, I'll leave you to it. Take care.}

# Quest_DIP
{740}{}{What are you trying to imply?}
{741}{}{If you truly contemplate it, this place, with its criminals and drugs, the entire scenario is nothing more than a sluggish mud puddle... And you're the stick stuck in the middle of it. Bigger and better things await you out there; don't cut yourself short of these opportunities.}
{742}{}{Never mind. It's your choice to make.}

# Quest_DIP2
{770}{}{You're right. I'm leaving this cell block. Maybe by stepping into the unknown, my aura will call out to Martin.}
{771}{}{[END]}

# Quest_Force
{800}{}{The universe and the Holy Word of Law collaborate in your favor when your will is strong.}
{801}{}{The stern suggestion of receiving a smack upside the head might alter your perspective.}
{802}{}{Alright, it's your decision.}

# Quest_Force01
{830}{}{[She takes a step back.] Alright, I'll leave this damned cell block. It's time for me to embrace the unknown and discover new paths.}

# St00PaD_LOWINT
{860}{}{Whoa, your aura is quite unique! I haven't seen you around here before. What brings you to my cell block?}
{861}{}{Robo sey you no listen. You lissan to robo, he good. Drugs bad.}


# St00PaD_LINT01
{890}{}{Man, I can sense the energy radiating from you. You must be the new prophet! Praise the Holy Word of Law! Farewell to counterproductivity!}
{891}{}{Uhh. Ya. Law gud. Bye.}

# Nth_Time
{920}{}{Hey there! Feeling like time is passing at a snail's pace today? [Sol starts spinning her arms around, clutching laser pistols.] Let's make it faster, I say!}
{921}{}{I thought you were planning to leave this cell block.}
{922}{}{Aw hell, never mind. I'll leave you to your time-bending activities.}

# AQ_Fork
{950}{}{I... It's hard. I'm afraid.}
{951}{}{Change is often scary. Embrace the fear and step into the unknown.}
{952}{}{Yeah, and so is my fist, and you better be afraid of it more than staying... If you know what's best for you.}

# AQ_DipEND
{980}{}{Yeah, you're right. [She relaxes a bit.] Thank you for your guidance. I'll leave this cell block and see what lies ahead.}

# AQ_Force01
{1010}{}{I'm not here to be your crutch for empty threats and hollow souls!}
{1011}{}{[You raise your hand.] If you insist on using empty words, prepare to face the consequences.}
{1012}{}{Alright, fuck it. Had enough of this shit. Let's tango, bitch!}

# AQ_IntimEND
{1040}{}{[She steps back and holds on to her hat.] Alright, I'll leave. I promise I won't show my face in this cell block again. Just leave me be.}

# Node028
{1070}{}{Why would you think any Officer wouldn't spill your guts after those words? My fellow Officers Danny, Lou Jr., and Maxine learned that lesson the hard way. [An evil smirk deforms her face.]}
{1071}{}{Whoa! So *you* are the cop killer?!}
{1072}{}{I apologize if I gave the wrong impression. I didn't mean any harm.}
{1073}{}{Wait a minute! Are you the one responsible for the deaths of Officers Danny, Lou Jr., and Maxine?}
{1074}{}{You're proud of taking the lives of fellow Officers? That's sickening.}
{1075}{}{I should report you right now. You're a danger to everyone here.}
{1076}{}{I'm staying away from you. You're clearly unhinged.}
