# Message file for tbsyd.ssl
# Number of nodes: 10
# Grammar pass done

{100}{}{You see a lively young child.}
{101}{}{A bright smile adorns the child's face.}
{102}{}{The child seems eager to make friends.}

{105}{}{Duck and cover!}
{106}{}{Here, take this key. Now you can see the big yellow thingy too!}
{107}{}{Mr. Director said he won't give me any more keys. I'm sorry.}

# Node001
{200}{}{Hey there! I'm Syd! What's your name?}
{201}{}{Hey there, ma'am. I'm Syd! What's your name?}
{202}{}{Hi Syd, I'm }
{203}{}{. Why aren't you playing with the other kids?}
{204}{}{My name is Regan. So, do you know anything about getting through that door over there?}
{205}{}{Beat it, kid. Unless you want a slap.}
{206}{}{Where are your parents?}
{207}{}{Me }
{208}{}{, hello Sydie! Lil' friends?}
{209}{}{[Make an angry face]}
{210}{}{Why is your jumpsuit torn? You're walking around in rags.}
{211}{}{See ya, kid.}
{212}{}{Bye, Sydie!}

# Node002
{230}{}{They're kinda boring - Tom always wants to play Cops 'n' Robbers! I like watching the robots better; they're way more fun!}
{231}{}{More fun?}
{232}{}{I've been talking to you for 5 seconds, and I'm already bored to death. See ya.}
{233}{}{Robo-fun?}
{234}{}{Mommy? Daddy?}
{235}{}{I'm going now.}

# Node003
{260}{}{Yeah! Sometimes Mr. Director lets me go through that door. There's a super duper big yellow thingy inside. Mr. Director is silly; he always lifts his arms up high and shouts BOOM, and then I shout back, "Duck and cover!"}
{261}{}{A big yellow thingy? Can I see it?}
{262}{}{BOOM!}
{263}{}{Me see big thingy!}

# Node004
{290}{}{Okie dokie, but first, I gotta ask Mr. Director for the key.}
{291}{}{Great, Syd. I'll wait for you here.}
{292}{}{Don't worry about it. I'll get the key myself.}
{293}{}{Me wait.}
{294}{}{Me get key.}

# Node005
{320}{}{You're a big meanie! I'm gonna tell on you!}
{321}{}{Ooooh, look at me shake.}
{322}{}{You deserve a good beating, kid.}
{323}{}{[Shrug]}
{324}{}{Me slap!}

# Node006
{350}{}{My mom says my dad was a really, really naughty man, and red demons stuck him on a tree. Now my mom is trying to find a new dad. She's got a bunch of boyfriends.}
{351}{}{Is your mom a prostitute or she's just a slut?}
{352}{}{Red demons?}
{353}{}{Your mom seems to be quite popular around here. Anyway, where are your friends?}
{354}{}{Well, tell your mom that }
{355}{}{ says hi. Bye.}
{356}{}{See you later, Syd.}
{357}{}{Mommy-whore or mommy-slut?}
{358}{}{Deeeeee-mons?}
{359}{}{Bye, Sydie. Bye.}

# Node007
{380}{}{I dunno. What's a slut?}
{381}{}{Well, a slut is... forget it. So, do you know what's behind that door?}
{382}{}{You're too young to understand anyway. See ya, kid.}
{383}{}{Slut kiss many frogs for free.}
{384}{}{Me no tell. Sydie small. Bye.}

# Node008
{410}{}{I dunno. You gotta ask my mom. But she's with one of her boyfriends right now.}
{411}{}{Why aren't you with your friends?}
{412}{}{Maybe some other time. Bye.}
{413}{}{Where friends?}
{414}{}{No time. Me go.}

# Node009
{440}{}{Hiya again!}
{441}{}{Hello again, ma'am.}
{442}{}{Why aren't you playing with the other kids?}
{443}{}{Do you know anything about getting through that door over there?}
{444}{}{Hello Sydie! Lil' friends?}
{445}{}{Where's your jumpsuit? And why are you wearing those rags?}

# Node010
{470}{}{Yuuuuuuuuuck!}
{471}{}{Hehehe. Me go. Say hi to mommy.}
{472}{}{Door?}
