# Message file for tbtaz.ssl
# Number of nodes: 71
# Grammar pass done

{100}{}{You see a formidable figure with a red stripe across his eyes and heavy chains binding him.}
{101}{}{You see Taz.}
{102}{}{Taz exudes a dangerous aura, making it clear that he's not to be underestimated.}

{200}{}{Go away.}

# Taz_1a
{230}{}{Greetings, stranger. The name's Taz. What can I do for you?}
{231}{}{Pleased to make your acquaintance, Taz. What role do you play around here?}
{232}{}{Tell me your story, Taz. I'm interested.}
{233}{}{Hello! What's that red substance you're covered in?}
{234}{}{Fuck off.}
{235}{}{I have other matters to attend to. Goodbye.}

# Taz_1b
{260}{}{Hello again. How are things going?}
{261}{}{Hi, Taz. Do you have a moment to answer a few questions?}
{262}{}{Hello. I've returned to see if you've stopped bothering the moo-moos.}
{263}{}{Greetings, Taz. I was just passing through and thought I'd drop by. Take care.}

# Taz_1b_B1
{290}{}{Well, you've changed your tune. What brought about this change of heart?}
{291}{}{I apologize, Taz. You didn't deserve that treatment.}
{292}{}{Yeah, well, did anyone tell you that you're a boring asshole?}

# Taz_1b_B2
{320}{}{Damn right I didn't. Maybe you should come back another time.}
{321}{}{I'll leave you be then. Take care.}

# Taz_1b_D1
{350}{}{Look, it's really not safe for you to be here, alright? You have to leave.}
{351}{}{[Leave.]}

# Taz_2B_1
{380}{}{[Taz gives you a lopsided grin, as if he's heard it all before.] You know, using that kind of language won't get you far in life, boy.}
{381}{}{[Taz gives you a lopsided grin, as if he's heard it all before.] You know, using that kind of language won't get you far in life, miss.}
{382}{}{Apologies, Taz. I'm just having a rough day. Could you tell me more about what you do here?}
{383}{}{When I want your damn opinion, I'll ask for it. Got it?}
{384}{}{Well, it's worked for me so far. Goodbye.}

# Taz_2B_2a_1
{410}{}{Give me one damn good reason why I should help you.}
{411}{}{How about I offer you two caps for your troubles?}
{412}{}{Forget it. I'm leaving.}

# Taz_2B_2a_2a
{440}{}{Hell, I'll take your money.}
{441}{}{So, what's your story?}

# Taz_2B_2a_2b
{470}{}{You don't even have two caps! Get the hell out of here and stop wasting my time!}

# Taz_2B_2b
{500}{}{[He shrugs indifferently.] Just get the hell out of my ranch and don't bother me again.}

# Taz_2D_1
{530}{}{[Taz smiles.] Oh, hell, son, this here's blood.}
{531}{}{[Taz smiles.] Oh, hell, miss, this here's blood.}
{532}{}{Are you hurt?}

# Taz_2D_2
{560}{}{No... [He realizes he's speaking to someone with limited intelligence.] I'm a butcher. A but-cher.}
{561}{}{You hurt butts?!}

# Taz_2D_3
{590}{}{[He looks around the room.] Perhaps this isn't a safe place for you. You should run along, alright?}
{591}{}{I'll leave, but you better stop hurting the moo-moos!}

# Taz_2G
{620}{}{I handle the butchery work around here and also tan some of the skins we send out. The doctors claim that I made up this story after running through a forcefield and frying my brain cells. They're telling me all sorts of nonsense, like how I'm not in my beloved Porto but in some place called Tibbets. Can you believe that? What's wrong with them?}
{621}{}{Butchery work? What kind of animals do you slaughter?}
{622}{}{What do you do with the skins?}
{623}{}{I see. Well, I should be moving on.}

# Taz_2N_1
{650}{}{I'm the ranch's butcher and tanner.}
{651}{}{What kind of animals do you butcher?}
{652}{}{Is tanning about leather and hides?}

# Taz_2N_2
{680}{}{Yup.}
{681}{}{Which hides do you work on?}

# Taz_3_1
{710}{}{You see those brahmin in the pens outside?}
{711}{}{Ummm, yes, I do.}
{712}{}{No, all I see are other patients.}

# Taz_3_2a
{740}{}{Well, they don't turn themselves into jerky, you know. Someone has to... [He gestures across his throat.]}
{741}{}{You must produce a lot of meat. What do you do with it?}
{742}{}{Can I ask you about something else?}
{743}{}{Alright, take care.}

# Taz_3_2b
{770}{}{You must be new around here if you haven't noticed. We're one of the largest brahma farms in the wasteland.}
{771}{}{I see. So somebody has to handle the slaughtering.}

# Taz_4_1
{800}{}{We keep the skins of the brahmin we slaughter and tan them. Then, we sell them to various buyers.}
{801}{}{Where do you sell the skins?}

# Taz_4_2
{830}{}{Mostly, we sell them to the Hub. There's a tanner there who takes the skins and makes various products out of them.}
{831}{}{Wait, didn't you say you were a tanner yourself?}
{832}{}{I see. Can I ask you something else?}

# Taz_4_3
{860}{}{I only tan the skins to preserve them for their journey to other places. The tanner in Hub has the skills to transform the leather into different products. Besides, I don't have the time or expertise for that.}
{861}{}{That makes sense. Can I ask you about something else?}

# Taz_5_1
{890}{}{There's always a demand for food in the wasteland, and we produce it in large quantities. We sell to various major groups and cities nearby.}
{891}{}{Which places, in particular, do you sell to?}
{892}{}{Can I ask you about something else?}
{893}{}{Alright, take care for now.}

# Taz_5_2
{920}{}{We sell to Boneyard, Hub, Fort Aradesh, and Hoover Dam.}
{921}{}{What can you tell me about Boneyard?}
{922}{}{What can you tell me about Hub?}
{923}{}{What can you tell me about Fort Aradesh?}
{924}{}{What about Hoover Dam?}
{925}{}{I see. I have another question for you.}

# Taz_5_3a_1
{950}{}{Boneyard? It's a large settlement built upon the ruins of a pre-war metropolis. It's teeming with people, which means a lot of hungry mouths to feed.}
{951}{}{Can you tell me how to get there?}
{952}{}{What can you tell me about Hoover Dam?}

# Taz_5_3a_2
{980}{}{No, I've never been there myself. As far as I know, it's southwest of Hoover Dam. Your best bet would be to ask the merchants who travel there for directions.}
{981}{}{I see. Can I ask you about something else?}
{982}{}{Alright, I'll leave you be. Take care.}

# Taz_5_3b_1
{1010}{}{Hub is a place that exists because it possesses the largest source of a precious commodity in the wasteland.}
{1011}{}{What's that?}
{1012}{}{Water?}

# Taz_5_3b_2a
{1040}{}{Water, my friend. Abundant, clean drinking water.}
{1041}{}{What does Hub produce that it can trade with you?}

# Taz_5_3b_2b
{1070}{}{That's correct. No flies on you! Fresh, clean drinking water.}

# Taz_5_3b_3
{1100}{}{That very same precious water. We have enough here to feed the cattle, but it's not of high enough quality for people, especially with the growth of some western towns.}
{1101}{}{Can you tell me how to get to Hub?}

# Taz_5_3b_4
{1130}{}{No, I'm afraid I don't know the way. It's a dangerous area due to the demand for water. I've also heard rumors of strange occurrences there.}
{1131}{}{Could you at least give me a rough idea of its location?}

# Taz_5_3b_5
{1160}{}{Sure, it's located west of Hoover Dam, I believe. If you really need directions, ask the caravan workers who travel there.}

# Taz_5_3c_1
{1190}{}{Terrible place, that Fort Aradesh. There's a fortune in pre-war tech lying around there, but the pollution from the oil refinery is so intense that no one survives there for long.}

# Taz_5_3c_2
{1220}{}{I can; from all the stories I've heard, I know the place all too well. But I won't. I've lost too many friends to that place, and I don't want the responsibility of your death.}
{1221}{}{And if I cross your palm with five caps?}
{1222}{}{Don't make me hurt you, Taz. Tell me.}
{1223}{}{Taz, I've got plenty of medical supplies. I've dealt with "hot" places before. You can tell me.}
{1224}{}{I see. Can I ask you something else?}


# Taz_5_3c_3a
{1250}{}{No! I'm not trying to squeeze every last cap out of you! Seriously, just steer clear of that place if you've got any sense.}

# Taz_5_3c_3b_a
{1280}{}{Alright, alright! Take it easy. Here, let me show you something. [He grabs a piece of chalk and draws a crude map on the rusty wall of the room.] See this? Hoover Dam is here, and Fort Aradesh is here. Got it? Don't say I didn't warn you when you get there.}
{1281}{}{That wasn't too difficult, was it? Now, what else can I help you with?}
{1282}{}{Good. Take care, Taz. Stay out of trouble.}

# Taz_5_3c_3b_b
{1310}{}{Who do you think you're fooling? [He laughs heartily in your face.] Now get lost before I whip you with my belt.}
{1311}{}{[Leave.]}

# Taz_5_3c_3c_a1
{1340}{}{Well, as long as you're aware of what you're getting yourself into.}
{1341}{}{Trust me. I'm prepared.}

# Taz_5_3c_3c_a2
{1370}{}{Take a look at this, then. [He grabs a piece of chalk and draws a crude map on the rusty wall of the barn.] This here is Fort Aradesh. Got it?}
{1371}{}{Yes, got it. What can you tell me about Boneyard?}
{1372}{}{Yes, thank you. What can you tell me about Hub?}
{1373}{}{Understood. What can you tell me about Hoover Dam?}
{1374}{}{Alright, got it. Can I ask you about something else?}

# Taz_5_3c_3c_b
{1400}{}{No, I need more than just your word to believe that you know what you're doing.}

# Taz_5_3d_1
{1430}{}{Ahh, Hoover Dam. The Old World Wall. That's what they call it, too.}
{1431}{}{I see. What can you tell me about it?}

# Taz_5_3d_2
{1460}{}{It's a massive NCR settlement, northeast of Boneyard. And as you might expect, it's situated near a body of water.}
{1461}{}{What's the place like?}

# Taz_5_3d_3
{1490}{}{I've heard there's some folks there who've developed a peculiar attitude towards the NCR and the Brotherhood of Steel.}
{1491}{}{The NCR? The Brotherhood of Steel? What do you mean?}

# Taz_5_3d_4
{1520}{}{There seems to be some conflict or tension between them, from what I understand.}
{1521}{}{That's unfortunate. What does Hoover Dam produce that it trades with other places?}
{1522}{}{I'll keep that in mind if I ever visit. Can I ask you another question?}

# Taz_5_3d_5
{1550}{}{Well, they produce rebars, stone, hardened wood, and steel beams. They've really salvaged a lot from the structure. But it's a nice change from relying on sandstone for building materials.}
{1551}{}{Can you provide directions on how to get there?}

# Taz_5_3d_6
{1580}{}{Nope, I've never been to that place either. I'm not particularly fond of the NCR, you know? [He looks uncomfortable discussing it.] But the caravan workers who frequent this area might have the information you need.}

# Taz_6_1
{1610}{}{How did I end up here? Well, it's been about ten years since I made the decision to settle down in this place.}
{1611}{}{So you weren't born here?}
{1612}{}{What made you choose to settle here?}

# Taz_6_2a
{1640}{}{Born here? Hah! That's a good one! When I was born, this place was nothing but an abandoned ruin. That's how it had been since the war, I reckon.}
{1641}{}{Umm... I see. So, how old is Tibbets?}
{1642}{}{What did you do before you settled here?}

# Taz_6_2b
{1670}{}{Tibbets? No, we're in Porto right now. Porto is only fifteen years old. I settled here five years after its founding.}
{1671}{}{If you say so. Why did you choose to settle here?}

# Taz_6_2c_1
{1700}{}{I used to work as a caravan guard. It was a dangerous life, not suitable for an older man like me now.}
{1701}{}{Which caravan route did you work on?}
{1702}{}{So, how did you end up in Tibbets?}

# Taz_6_2c_2
{1730}{}{The route I used to run went from Boneyard to Hub and Junktown.}
{1731}{}{Can I ask you about something else?}

# Taz_6_2d_1
{1760}{}{Back in the day, when I was still working as a caravan guard, we used to visit Porto quite frequently. We were here so often that I became friendly with everyone.}
{1761}{}{[CONTINUE]}
{1762}{}{Wait, which caravan route did you work on?}

# Taz_6_2d_2
{1790}{}{I told my caravan bosses that I'd had enough of running that route, and they mentioned that Porto needed a butcher due to its rapid expansion.}
{1791}{}{Why were you the best person for the job?}
{1792}{}{Which caravan route did you run?}
{1793}{}{Let me ask you something else.}

# Taz_6_2d_3
{1820}{}{The ranch was growing quickly, but it was still relatively small. They were short on labor, so they hired anyone willing to work. The farmers taught me the basics, and I honed my skills over the years.}

# Taz_7_1
{1850}{}{We no longer breed brahma here. The brahmin you see come from other settlements. Porto's land serves as a large holding pen for them, like a staging point before they are either butchered or moved as livestock to our customers.}
{1851}{}{Which places does Tibbets, umm... "Porto", sell its produce to?}
{1852}{}{Why do the cattle traders bring their brahmin here instead of taking them directly to their customers?}

# Taz_7_2a_1
{1880}{}{Well, people have come to appreciate the wisdom of the Freeroaming Brahmin Traders' concept.}
{1881}{}{Who are they?}

# Taz_7_2a_2
{1910}{}{They're run by Hofferman and are based here. They handle the consolidation of nearly all the brahmin raised in this area for the market in Porto. Selling them wholesale brings in more profit.}
{1911}{}{I see the logic in that. Can I ask you another question?}
{1912}{}{Understood. I have to be going now, Taz. Take care.}

# Taz_7_2b_1
{1940}{}{Well, people have come to appreciate the wisdom of the Freeroaming Brahmin Traders' ideas. [You notice that he feels uncomfortable discussing this subject.]}
{1941}{}{You seem uneasy when talking about the Freeroaming Brahmin Traders. What's their story?}

# Taz_7_2b_2
{1970}{}{[He frowns.] I don't know what you're talking about. They are responsible for organizing the consolidation of all the brahma raised and traded in this area for the market in Porto. That's all there is to it.}
{1971}{}{You're obviously uncomfortable talking about them. Why is that?}
{1972}{}{I see. Can I ask you a question about something else?}

# Taz_7_2b_3
{2000}{}{Why don't you "ask me about something else?"}
{2001}{}{Come on, Taz. Here's five caps. Tell me what you know. I promise not to tell a soul.}
{2002}{}{If you insist.}

# Taz_7_2b_4a
{2030}{}{[He takes your money.] Alright, but you better keep this to yourself.}
{2031}{}{You have my word.}
{2032}{}{Sure, whatever you say.}

# Taz_7_2b_4b
{2060}{}{Keep your money. There isn't anything else to know.}
{2061}{}{Look, ten caps and not a cap more.}
{2062}{}{If you say so. Let me ask you about something else instead.}

# Taz_7_2b_4c
{2090}{}{You're offering me money you don't even have!}
{2091}{}{Maybe I'll talk to you about that again when I've got more money. Can I ask you about something completely different?}
{2092}{}{How embarrassing for me. I'd better leave you to it.}

# Taz_7_2b_5
{2120}{}{[He leans towards you, speaking in a low voice.] The Freeroaming Brahmin Traders are a completely legitimate organization... nowadays.}
{2121}{}{Go on.}

# Taz_7_2b_6
{2150}{}{They started differently, though. You see, they had to convince all the brahmin traders in this area to stockpile their cattle in Porto and join the Freeroaming Brahmin Traders syndicate.}
{2151}{}{What was the purpose of that?}
{2152}{}{What's wrong with that?}

# Taz_7_2b_7a
{2180}{}{If you have lots of brahmin in one convenient place, you can drive them in one big run to your customers instead of small quantities. It reduces costs and increases profits.}
{2181}{}{And why is that seen as a bad thing?}
{2182}{}{I see. Let me ask you about something else instead.}

# Taz_7_2b_7b_1
{2210}{}{Well, this is where it gets tricky. Not all the farmers and traders in this area wanted to join the Freeroaming Brahmin Traders. Hofferman wasn't one to take no for an answer, and things turned ugly a few times.}
{2211}{}{Ugly? How so?}

# Taz_7_2b_7b_2
{2240}{}{There were rumors at the time that Hofferman resorted to intimidation and brahmin rustling, with the help of Porto's gangs. Those who refused to join had their brahmin stolen from them.}
{2241}{}{That's a serious accusation!}
{2242}{}{Why was Hofferman so determined to compel the other traders to join his group?}

# Taz_7_2b_7b_3
{2270}{}{Damn right it is! And you never heard it from me. Like I said, those were just rumors.}
{2271}{}{So, why was Hofferman so eager to force the other traders into his organization?}
{2272}{}{Let's change the subject. Do you have time for another question?}
{2273}{}{I'd better leave you to it, Taz. Take care.}

# Taz_9
{2300}{}{What do you want to know?}
{2301}{}{What livestock do you butcher?}
{2302}{}{What do you do with all the meat you produce?}
{2303}{}{Which places does Porto trade with?}
{2304}{}{How did you end up here?}
{2305}{}{Does Porto breed all its own livestock?}
{2306}{}{Actually, I can't think of anything else to ask. Goodbye for now.}
