# Message file for tbwasteb.ssl
# Number of nodes: 11
# Grammar pass done

{100}{}{You see an unusual robot with a tough outer shell.}
{101}{}{You see Wastebot-023.}
{102}{}{This is a waste-management robot designed to clean and restore order.}

{103}{}{*EMERGENCY MEMORY BACKUP PROCEDURE INITIATED*}
{104}{}{DANGER!}
{105}{}{You have become an expert excrement expeditor!}

{150}{}{Although the overall design is humanoid, the details reveal that this robot wasn't built by humans; its customization as a wastebot is unique.}
{151}{}{You manage to repair some wastebots.}
{152}{}{You failed to make any repairs.}

# Node001
{200}{}{GREETINGS, PRISONER 13. DESIGNATION: WASTEBOT-023. YOU SEEK EMPLOYMENT IN WASTE MANAGEMENT?}
{201}{}{That's right. This place is already a mess, might as well make some caps cleaning it up.}
{202}{}{Why are you shouting?}
{203}{}{Nope. Goodbye.}
{204}{}{Me clean.}
{205}{}{Why loud?}
{206}{}{No. Bye.}

# Node002
{230}{}{INITIATING JOB QUERY... TWO TASKS AVAILABLE. FIRST: MANUAL WASTE COLLECTION. SECOND: TECHNICAL MAINTENANCE OF WASTEBOT UNITS. WHICH DO YOU PREFER?}
{231}{}{Technical maintenance? You mean fixing up bots like you?}
{232}{}{Manual waste collection, huh? Sounds like good old-fashioned hard work. What does it entail?}
{233}{}{What's the pay?}
{234}{}{They both suck. I'm out of here.}
{235}{}{Me fix?}
{236}{}{Take shit? Goood!}
{237}{}{Caps?}
{238}{}{You stinky. Bye.}

# Node003
{260}{}{AFFIRMATIVE. MANY OF MY COUNTERPARTS SUFFER MALFUNCTIONS DUE TO THE HARSH ENVIRONMENT. TECHNICAL KNOW-HOW CAN BE REWARDED GENEROUSLY.}

# Node004
{290}{}{MANUAL WASTE COLLECTION: 5 CAPS PER DAY. TECHNICAL MAINTENANCE: 20 CAPS PER SUCCESSFUL REPAIR.}
{291}{}{Those are some tempting offers, especially for a place like this. Alright, I've got some experience with machinery. Let me try my hand at the maintenance job.}
{292}{}{OK, I'll just do the waste collecting.}
{293}{}{None of these sound good enough. Find someone else to get their hands dirty for you.}
{294}{}{Me fix all.}
{295}{}{Me take shit.}
{296}{}{No no. Me no stinky. Bye.}

# Node005
{320}{}{OPTIMAL CHOICE DETECTED. I WILL PROVIDE YOU WITH THE REQUIRED TOOLS AND DIAGNOSTICS KIT. REPAIR AS MANY WASTEBOTS AS YOU CAN, AND YOU WILL BE COMPENSATED ACCORDINGLY.}
{321}{}{Got it.}
{322}{}{'K.}

# Node006
{350}{}{ANALYZING RESPONSE... SENTIMENT UNDERSTOOD. THANK YOU, PRISONER 13. TOGETHER, WE WILL RESTORE ORDER TO THE CHAOS.}
{351}{}{That's the spirit! Let's get to work.}
{352}{}{Me work.}

# Node007
{380}{}{MANUAL WASTE COLLECTION REQUIRES PRISONER PARTICIPANTS TO GATHER DERELICT ORGANIC AND INORGANIC MATERIALS FROM SPECIFIED ZONES. MATERIALS INCLUDE: METAL, PLASTIC, ELECTRONICS, AND ORGANIC WASTE. ALL COLLECTED ITEMS MUST BE DEPOSITED AT DESIGNATED DROP POINTS.}
{381}{}{Sounds simple enough. And you said 5 caps per day?}
{382}{}{5 cap?}

# Node008
{410}{}{AFFIRMATIVE. 5 CAPS PER STANDARD DAY OF COLLECTION. BONUS REWARDS CAN BE EARNED BASED ON QUANTITY AND QUALITY OF WASTE GATHERED.}
{411}{}{You know what? I could use some good ol' crap shoveling. Sign me up.}
{412}{}{I don't want to get dirty or smell like shit. So long.}
{413}{}{Me take shit.}
{414}{}{Me no take shit.}

# Node009
{440}{}{CONFIRMING CHOICE... MANUAL WASTE COLLECTION. INITIALIZE... HERE IS YOUR COLLECTION BAG AND A LOCATION TRANSPONDER. MARKED ZONES WILL GUIDE YOUR COLLECTION EFFORTS. RETURN HERE AT "SUNSET" FOR CAP REWARDS.}
{441}{}{Thanks, Mr. Wastebot. A bit of elbow grease and I'll earn those caps in no time.}
{442}{}{Thank, Mr. Stinky.}

# Node010
{470}{}{EFFICIENCY AND DILIGENCE ARE RECOMMENDED. REMEMBER, YOUR EFFORTS CONTRIBUTE TO A CLEANER PRISON.}
{471}{}{Who knows? Maybe I'll find some treasures amidst the waste. See you at "sunset."}
{472}{}{See ya.}

# Node011
{500}{}{SO THAT YOU CAN HEAR ME OVER THE NOISE OF THE WASTE WATERS FLOWING THROUGH THE PIPES.}
{501}{}{Alright, I seek work.}
{502}{}{Ahh, I see. That makes sense. Goodbye.}
{503}{}{Me work.}
{504}{}{'K. Bye.}
