# Message file for tbwcdd.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see a familiar robot, visibly in a dire state.}
{101}{}{You see the severely damaged Welcoming Committee Director.}
{102}{}{Its once pristine vacuum tubes are shattered, the chassis bears deep scorch marks, and scattered vital chips lay scattered about, revealing the extent of the damage.}

# Node001
{200}{}{Number 13... is that you?}
{201}{}{Farewell, Director.}
{202}{}{I regret to inform you that I am unable to assist you.}
{203}{}{Buh-byeeeee, Boss-Robo-Man.}
{204}{}{Me no help. Me sorry.}
{205}{}{[Leave without saying anything]}
