# Message file for tbwcd.ssl
# Number of nodes: 26
# Grammar pass done

{100}{}{You spot a fidgety service bot, clearly on edge.}
{101}{}{You see the Welcoming Committee Director.}
{102}{}{He nervously shifts his weight, his old chassis recently polished to a gleam.}

{104}{}{How dare you? Criminal scum!}
{105}{}{Although the overall design is humanoid, the details reveal that this robot wasn't built by humans; its customization as the Welcoming Committee Director is unique.}

# Floats
{110}{wcdf0}{People often think robots have it easy.}
{111}{wcdf1}{Number 13.}
{112}{wcdf2}{Your jumpsuit appears to be in need of some repairs.}
{113}{wcdf3}{It would be good for you to get out more and make some friends.}
{114}{wcdf4}{I'll see you at the Atom!}
{115}{wcdf5}{ODYSSEUS can be quite demanding at times.}
{116}{wcdf6}{Honestly, I'm not much interested in the outside world, but ODYSSEUS and you seem to be.}
{117}{wcdf7}{How are you doing with your CODE scores?}
{118}{wcdf8}{Prisoner 13.}
{119}{wcdf9}{Should've oiled my wheel. It's starting to creak again.}
{120}{wcdf10}{I have scheduled maintenance at 600. Let's hope everything goes smoothly!}

# Node001
{200}{wcd001}{Morning, Number 13. You're back with us again. Good. For a brief moment, I entertained the notion that I, the Director, might have to unplug you myself. Listen, today is the day. The big one. ODYSSEUS, our Warden of the US Penitentiary Tibbets, has scheduled your trial. Should you succeed in demonstrating your innocence, your long-awaited release will materialize, allowing you to go outside for real instead of running with these simulated experiences.}
{201}{}{Refresh my memory, robot. Tell me about Tibbets.}
{203}{}{Uhm... it's morning?}
{204}{}{Who the hell are you?}
{205}{}{I'm not just a number, I'm a free man!}
{206}{}{I'm not just a number, I'm a free woman!}
{207}{}{Thanks to "these simulated experiences" my ass-kicking skills improved. Allow me to demonstrate!}
{208}{}{Hugghhn... who?}
{209}{}{Rrrrrrrrrrrrrrrrrrr!}
{210}{}{Aren't we already permitted to move about freely?}
{211}{}{Ded! Robo ded!}
{212}{}{What was the point of that movie running before the simulation?}

# Node002
{230}{wcd002}{As the appointed Director of the Welcoming Committee, my programmed responsibility is to serve as the initial point of interface for newly processed individuals. Additionally, I am tasked with providing established residents, such as yourself, with updates regarding the agendas implemented by ODYSSEUS.}
{231}{}{I have some questions, Director.}
{232}{}{Rugh!}

# Node003
{260}{wcd003}{I detect your humor, Number 13. Tibbets is your home. This complex serves as your safe haven, meticulously engineered to safeguard you from external threats. Furthermore, it fosters a nurturing atmosphere that enables you to concentrate on personal evolution and enhancement. But you can't leave.}
{261}{}{Am I really a bad person? My mom, if I had one, would be disappointed.}
{262}{}{What do you mean by "personal evolution and enhancement"?}
{263}{}{Where's my stuff... my... umm... plasma rifle?}
{264}{}{Me no bad!}
{265}{}{Yeah, but I didn't bomb the world.}

# Node004a
{280}{wcd004a}{The antiquated film reel you've observed, drawn from our archives, was personally chosen by me. Despite being three centuries old, its powerful message resonated even with my cold, mechanical heart. It stands to reason that it can influence yours too. It's crucial that we constantly remember our core values and the elements that precipitated the downfall of our industrialized civilization.}
{281}{}{I didn't--}

# Node004
{290}{wcd004}{Yes, here you can learn about respect - for others, for your country, for your government.}
{291}{}{[CONTINUE]}

# Node005
{320}{wcd005}{My databases indicate that a dull, makeshift shiv and a plasma rifle advertisement torn from a Cat's Paw magazine were found inside your cell. Regrettably, these items are officially property of the United States of America's government and as such, they have been seized accordingly.}
{321}{}{The government of United what?}
{322}{}{Ask!}

# Node006
{350}{wcd006}{Indeed, the United States of America's government serves as the supreme authority in this nation, particularly during these dark times. Its role in maintaining order and stability is more crucial than ever.}
{351}{}{Alright, I've heard enough. Let me go outside.}
{352}{}{So, what does this "government" expect from me?}
{353}{}{Ghuuuuu. Quest! Ion!}

# Node007
{380}{wcd007}{And I am Virgin Mary.}
{381}{}{I didn't know robots had a sense of humor. What other insights do you possess?}
{382}{}{Alright, Mary. I have some questions for you.}
{383}{}{Huhn? Ask!}
{384}{}{Me go out. You stay in.}
{385}{}{Ah, virginity... Thankfully, that no longer concerns me!}
{386}{}{Me no Virgil. Me sexi before!}

# Node008
{410}{wcd008}{Channel your energies towards making your familial lineage proud! Aim to epitomize the ideals of a model US citizen. After all, who aspires to be commemorated merely as "Prisoner 13"? Strive for more, strive for personal evolution.}
{411}{}{Me? A perfect citizen?}
{412}{}{Meeeeeeeeee?}
{413}{}{Enough with the bullcrap. I'm out of here.}

# Node009
{440}{wcd009}{Regrettably, Number 13, the situation isn't as straightforward as you may presume. I am but a facilitator in this context, not the decision-maker. The reins of authority are held by our Warden, ODYSSEUS, who oversees all operations. This morning, it is my duty to notify you that you are due for a trial.}
{441}{}{A trial? What the... What am I accused of?!}
{442}{}{Alright, let's get this over with. Where can I find ODYSSEUS?}
{443}{}{Me go Odi!}
{444}{}{No, you don't understand. I'm fed up with this place and I'll fight my way out of here.}

# Node010
{470}{wcd010}{The insights and decisions lie solely with ODYSSEUS. As for my function, it revolves around guaranteeing that inmates feel not only welcomed, but also suitably enlightened about their circumstances within this facility.}
{471}{}{You're useless!}
{472}{}{I have some questions for you.}

# Node011
{500}{wcd011}{There's no cause for concern. Given that you have been exposed to our Vault-Tec light bulbs from birth, your awareness and perception of the day's progression should not be influenced by traditional light cycles. The concept of specific times of day might be irrelevant to your adjusted internal clock.}
{501}{}{Vault-Tec?}
{502}{}{Nothing beats natural sunshine. I've felt it inside the SimTek simulations. You can stick your Vault-Tec light bulbs you know where.}
{503}{}{Tell me something, Director.}

# Node012
{530}{wcd012}{Let's keep this simple... You. Go. East elevator. Zoom-zoom-up-down! You. Go. South-west elevator. Zoom-zoom-up-down! You. Go. ODYSSEUS.}
{531}{}{I. Go. Rrrrrrrrrrrrrrrrrrrrrr!}
{532}{}{Zoom-zoom!}

# Node013
{560}{wcd013}{I detect your humor, Number 13. Tibbets facility is, indeed, your home. Our Warden, ODYSSEUS, in collaboration with our devoted team of robotic assistants, tirelessly works to protect you and everybody else from the dangers lurking outside. ODYSSEUS is steadfast in his belief that this environment is the best option for securing a prosperous future for us.}
{561}{}{Is that so? I feel there's something you robots aren't telling us.}
{562}{}{I don't need anyone making decisions for me. I'm doing just fine.}

# Node014
{590}{wcd014}{Of course you are, Number 13. However, let us not overlook the vast wisdom that ODYSSEUS holds, surpassing that of any of us. It is essential that we place our trust in his discerning judgment.}
{591}{}{What am I accused of?! This is insane!}
{592}{}{Oh, is that so?! Well, I'm transferring you robots to the scrapyard.}
{593}{}{Get out of my way. I'm leaving Tibbets.}

# Node015
{620}{wcd015}{Indeed, your observation is correct, Number 13. This facility is designed as an open-type prison, where residents have the liberty to move about freely within the prescribed boundaries.}
{621}{}{I still feel being outside in the wasteland is even better.}

# Node016
{650}{wcd016}{As you might recall, Tibbets is a facility dedicated to offering academic, work, and occupational education to all residents who express interest or are mandated to partake. In addition to these educational pursuits, we also provide an extensive array of recreational and leisure activities to foster a holistic and balanced environment.}
{651}{}{I can educate myself here? Besides the SimTek 5000 simulations, right?}
{652}{}{Where can I find some work?}
{653}{}{Recreation? Leisure? I'm all ears, Director.}

# Node017
{680}{wcd017}{Yes, Number 13. Tibbets offers a wide range of education programs, from basic literacy to high school equivalency, GED, and even parenting programs, accessed through the Personal Information Processor, also known as the Lil-Pip 3000, issued to each inmate. Inmates failing to meet the high school equivalency standard are required to participate in education programs. Additionally, we offer English as a Second Language and bilingual Adult Basic and Secondary Education opportunities. Our ACE courses include Spanish I and II, Keyboarding, Creative Writing, History, Career Development, and Pre-Release. We also have VT Programs, Graphic Arts, and Barber College certified by the State of Arizona. We are working on introducing a Culinary Arts VT class and a distance learning college program.}
{681}{}{That's something I'd like to try. I bet there's nothing like that in the wasteland.}
{682}{}{Huh, do I have to pass exams or is this open to everyone?}
{683}{}{Humor me some more, Director. I'm out of here.}

# Node018
{710}{wcd018}{Certainly you can, Number 13. The Vault-Tec operation at Tibbets is the largest in the Bureau, with three factories employing over 320 inmates. Last year, the sales from these factories reached over 26 million dollars, with profits exceeding 6 million dollars. The profits from all Vault-Tec operations are used to fund salaries, reinvest in new factories, and cover other expenses.}
{711}{}{Haha! 26 million profit? Are you kidding me?}
{712}{}{Dollars? Is that some kind of currency, like caps?}
{713}{}{Impressive numbers, Director. You're running quite an operation here.}

# Node019
{740}{wcd019}{The data I've relayed to you originates directly from ODYSSEUS. As a programmed entity, I don't harbor the capacity to question its validity. While you possess the freedom to challenge these numbers, I must caution you to consider potential repercussions, Prisoner 13.}
{741}{}{Seems like this place is a madhouse first, then a prison.}
{742}{}{Alright, tell me something else.}
{743}{}{I'm leaving. Goodbye.}

# Node020
{770}{wcd020}{Ask, and I'll try to reference the best answer from my database, Number 13.}
{771}{}{Tell me more about Tibbets?}
{772}{}{Do you know how I ended up here in the first place?}
{773}{}{Who are you exactly?}
{774}{}{Can I exit Tibbets and explore the wasteland?}
{775}{}{Why don't we live outside?}
{776}{}{What else can we do here, aside from enjoying SimTek?}
{777}{}{That's all for now, Director.}

# Node021
{800}{wcd021}{ODYSSEUS is waiting for you in the courtroom. Take the elevator located to the east of here. Make sure to select level 1 to reach the Security Hub; otherwise, you'll end up in a different cell block. Once you arrive, use the south-west elevator.}
{801}{}{Yeah, yeah. Whatever.}
{802}{}{I'm not attending any trial. I'm getting out of here, even if it means shattering your vacuum tubes. Game over, Director.}
{803}{}{Gaaaag. Oki!}
{804}{}{I'll attend the trial promptly and prove my innocence! Then I'll explore the wastes.}

# Node022
{830}{wcd022}{Or maybe you're asking the wrong questions, Prisoner 13.}
{831}{}{We'll see, Director, we'll see. I have more questions for you.}
{832}{}{I'm going. Move.}
{833}{}{I'm not going to be patronized by a robot. Outta my way, tin can.}

# Node024
{860}{wcd024}{As you may have noticed, Number 13, we accommodate a compact gymnasium for each cell block, arrange regular movie nights, lotteries, and sporting events. For those craving additional social interaction, we feature a charming bar named "The Atom" situated on the Service Level. As you progress and evolve, you'll find our offerings increase correspondingly!}
{861}{}{The Atom's my kind of place, yeah. I'll see you there.}
{862}{}{Alright, I've heard enough. It's time to make my exit!}
{863}{}{Tell me something else.}

# Node025
{890}{wcd025}{Yes, everyone benefits from our educational programs and the CODE.}
{891}{}{CODE?}
{892}{}{CODE? Is that some kind of programming language named by a genius?}
{893}{}{Let's change the topic. Tell me something else.}

# Node026
{920}{wcd026}{The Challenge, Opportunity, Discipline, and Ethics, CODE, program we have here. ODYSSEUS will provide you with more details.}
{921}{}{Are you sure you can't tell me more? It seems like you should have more information, right Director?}

# Node027
{950}{wcd027}{Alright, Number 13. I'll tell you all I know. USP Tibbets offers a residential treatment program for inmates interested in making positive life choices, utilizing the latest in psychological methods and technology. The Challenge, Opportunity, Discipline, and Ethics, CODE, program is a year-long residential treatment program provided within the prison. The program's mission is to foster trust, responsibility, integrity, and tolerance. Inmates enrolled in the program spend the first three months exploring the process of change, followed by six months of daily treatment methods to promote positive life skills. During the final three months, inmates develop skills to prevent relapse into prior negative patterns of thinking, feeling, and behavior.}
{951}{}{It sounds like something that could mess with my mind. I might just avoid it to keep my sanity intact.}
{952}{}{I see. Good to know what the CODE program entails. Is there anything else?}

# Node028
{980}{wcd028}{The things I have to listen to and endure... ODYSSEUS, give me strength!}
