# Message file for tbwrox.ssl
# Number of nodes: 37

{100}{}{You see a disheveled bum.}
{101}{}{You see Wrox, a scruffy prisoner.}
{102}{}{You see a ragged bum in patched jumpsuit.}

# general floats
{200}{}{What's that smell...? Oh, it's me.}
{201}{}{Pretty-Natty, Pretty-Natty, give me your answer, doooo...}
{202}{}{Can't wait to hit on her again later.}

{230}{}{Poor Natty.}
{231}{}{I would treat her right.}
{232}{}{She's so beautiful, even with two black eyes.}

# first
{320}{}{Hello there, stranger. What brings you here?}
{321}{}{Who are you?}
{322}{}{I'm just exploring. What can you tell me about this place?}
{323}{}{I need to be somewhere else.}
{324}{}{Me bring me. Me walk.}
{325}{}{Who's you?}
{326}{}{Me confused. Me go chase radscorpions.}

# First2
{350}{}{OK. What is it?}
{351}{}{What can you tell me about the hospital?}
{352}{}{I'll be leaving now. Goodbye.}

# Suitlie2
{380}{}{But it seems she broke up with Wiggie and is now dating Taz. Maybe she'll give me a chance too?}
{381}{}{Maybe she isn't sure what she wants at all. She's unpredictable.}
{382}{}{Maybe she's just being indecisive. You know how young girls can be, right?}
{383}{}{Uhh... I've got to go.}

# Suitlie22
{410}{}{I guess... Hell, maybe she's not mature enough for me anyway.}
{411}{}{Now that's some wise talk. Bye.}
{412}{}{Well, that and the fact that she's in a relationship with Taz.}

# SuitorA2
{440}{}{Hell, I know I'm a little older, but not that much. It's not like we'd make the oddest couple, right?}
{441}{}{You're just not her type.}
{442}{}{Let's see. How much older are you, exactly?}
{443}{}{It's a little more complicated than that. She's in a relationship and she has some issues.}
{444}{}{Believe what you want. I don't have time for this.}

# SuitA2B
{470}{}{I'm 55 and she's 22, so... 33 years.}
{471}{}{That could be a problem. I mean, would YOU go out with someone 33 years older than you?}
{472}{}{Actually, that really doesn't matter. You don't have a chance with Pretty-Natty - she's in a relationship.}

# SuitorC
{500}{}{[He grins widely] I suspected that! I've always thought she was more than just playing hard to get.}
{501}{}{What can you do, right?}
{502}{}{Well, now you know. Bye.}

# suitper
{530}{}{Uhh, I see your point and I guess you're right. Maybe I am too old for her. *Sigh*}
{531}{}{I knew you'd understand. See you around.}

# suit3A
{560}{}{Hope, of course. What do you think of me?}
{561}{}{Nothing, really. I've got to go now.}
{562}{}{That you couldn't stay away from her if your life depended on it. I'm out of here.}

# suitlend
{590}{}{Wait! You're hiding something. I mean, she's never shown any interest at all in me, there must be something odd going on there. She - she's crazy, isn't she?}
{591}{}{Okay, okay, she is! People are locked up here for a reason, you know, they do have mental issues. Now leave me alone.}
{592}{}{Make of it what you want, it is what it is. I'm out of here.}

# Dumb1
{620}{}{Hah! I meant, what are you doing here?}
{621}{}{[Long pause] Ooo, I get! I talking to you?}
{622}{}{Me walk someplace else now.}

# Dumb2
{650}{}{Ahh... look. What. Is. Your. Business. Here?}
{651}{}{[Very long pause] Uhh...}
{652}{}{Me... confused. Me go. Okie?}

# Dumb3
{680}{}{I'm pretty busy. Why don't you go ask for an ass-wiping job at the doctor's office or something?}
{681}{}{You mean. You no nice. Me go.}

# Dumbsec
{710}{}{Oh, hey. It's you again.}
{711}{}{Is you too! Bye.}

# dumb4
{740}{}{I'm Wrox. Mostly just keep an eye on the radscorpions around here, like everyone else.}
{741}{}{You no look like radscorpi.}
{742}{}{It nice to meet you. Bye bye.}

# dumb5
{770}{}{Ha! No kidding. So, what brings you here?}
{771}{}{[Pause] Uhh... Me talk you?}
{772}{}{Me not do much. Me go.}

# firstA
{800}{}{I'm Wrox. Just another patient here, same as the rest.}
{801}{}{That's interesting. I've got to head off now.}

# firstB
{830}{}{Well, there isn't a whole lot. We're smack-dab in the middle of this massive mountain, connected to Tibbets with a tram. We've got doctors looking after us patients; they reckon we're a bit more special than the ones in the prison. At least there aren't any robots here. We recently had the Rainmakers show up, they're some kind of cult. And if you're looking for work - ask around, reckon there are folks who could use a hand.}
{831}{}{Tell me more about these doctors.}
{832}{}{What's the deal with the Rainmakers?}
{833}{}{Who can I speak to about finding work?}

# firstcut
{860}{}{Dr. Carl's the main guy. He's been here longer than anyone else. Maybe he's got a few screws loose too, eh? Then there's Dr. Nora, but we call her the *Black Widow*. Then there's Dr. Yvreth, he's good with a scalpel and has a prosthetic leg to boot. Dr. Linder's your guy for anything machine-related, and Dr. Bree is a cutie, but not like Pretty-Natty. Hehehe.}
{861}{}{Pretty-Natty?}
{862}{}{Let me ask you another question.}
{863}{}{Think I'll head down there now. See you around.}

# firstchu
{890}{}{I don't really know what's happening in there, and I don't think I want to. The doctors seem decent, but they're a bit wacky from what I can tell.}
{891}{}{Alright. Can I ask you another question?}
{892}{}{Thanks for the info. Catch you later.}

# firstgut
{920}{}{Not sure, ask around. Maybe the doctors know. I don't have to work, so I don't bother with all that. Hehehe.}
{921}{}{Okay. Can I ask you another question?}
{922}{}{Guess I'll do that. Later.}

# first3
{950}{}{What are you curious about? Most prisoners want to know about the hospital, since most never even heard of it. And there's the Rainmakers cult if you're in the market for a new family. Heard the doctors might be hiring, too.}

# fistdate
{980}{}{Really? That would be amazing!}
{981}{}{I'll let you know how it pans out. Bye for now.}
{982}{}{On second thoughts, maybe not. Can I ask you something else?}

# why
{1010}{}{Have you spoken to Pretty-Natty yet?}
{1011}{}{Yes, I have.}
{1012}{}{No, not yet.}
{1013}{}{I'll get around to it. Later.}

# then
{1040}{}{Well, go on then. Please.}
{1041}{}{Okay. Catch you later.}
{1042}{}{I'll do it when I'm ready.}

# secenc
{1070}{}{Oh, hey. It's you again.}
{1071}{}{Can you tell me more about this place?}
{1072}{}{Remind me who you are?}
{1073}{}{I've got to head off. Bye.}

# Pretty-Natty
{1100}{}{She's attractive and unpredictable, a deadly combination! Most of the guys around here would kill to have a date with her, and yeah, that includes me. Not that I believe I have any chance with her, though. *Sigh*}
{1101}{}{I doubt it too. She's in a relationship... with everyone, it seems.}
{1102}{}{I could help you out with that, if you want.}

# Asked
{1130}{}{And what did she say? Come on, don't leave me hanging.}
{1131}{}{No dice. She thinks you're a nice guy, but you're a little old for her.}
{1132}{}{She won't go out with you - but then again, she wouldn't date anyone else. She's in a relationship with Taz.}
{1133}{}{You're just not her type, Wrox. Drop it, huh?}

# PrettyNattyBeaten
{1160}{}{[Wrox looks upset] Oh, hello. I guess you've heard by now - Pretty-Natty was recently beaten.}
{1161}{}{As a matter of fact, I'm investigating the case. Where were you the night Pretty-Natty was attacked?}
{1162}{}{That's terrible. I'll see you around, Wrox.}
{1163}{}{Me hear that. You tell - what you do on night she fell on someone's fists?}
{1164}{}{That sad. Me like Natty. Bye-bye...}

# Accuse
{1190}{}{What? You can't seriously be suggesting that I had something to do with it?! Listen - I was asleep all night in my room. Others can vouch for me on that. What evidence do you have that points to me?}
{1191}{}{Just being thorough, Wrox.}
{1192}{}{None. Sorry, Wrox - see you around.}

# Thorough
{1220}{}{Well, maybe you shouldn't go around accusing innocent people. I like Pretty-Natty - so what if she wouldn't go out with me? There are plenty of women who wouldn't, and none of them were attacked!}
{1221}{}{You seem a little jumpy there, Wrox. Why's that?}
{1222}{}{Yeah - sorry, Wrox. See you around.}
{1223}{}{I hope you're telling me the truth. Goodbye.}

# Jumpy
{1250}{}{Jumpy? Well, maybe I'm just not used to being accused of assaulting women by random prisoners! I've had it with this conversation - go and bother someone else.}
{1251}{}{If you're hiding something, I will find out sooner or later. Goodbye.}
{1252}{}{Sorry, Wrox. Maybe I'll see you later.}

# StupidAccuse
{1280}{}{What? I know you're kind of dumb, but do I look like a woman beater to you? I was asleep in my room all night when Pretty-Natty was attacked, and others can vouch for me on that. You're likely to get hurt if you run around accusing innocent people.}
{1281}{}{Okay. Me sorry - you nice man. Me go.}
{1282}{}{Well, we see. Me not so sure you tell truth. Bye.}
