# Message file for v8hurst.ssl
# Number of nodes: 26
# Grammar pass done

{100}{}{You see a tall, blond man exuding an air of authority.}
{101}{}{You see Chief Security Officer Hurst, diligently guarding the Security office.}
{102}{}{He stands watch outside the heavily fortified Security office.}
{105}{}{Halt!}
{106}{}{Lower your weapon immediately.}
{107}{}{Spy!}
{108}{}{Engage the hostiles!}
{109}{}{Hold on, Walter! I'll save you!}

# Node001
{200}{}{Greetings, Citizen. How may I be of assistance?}
{201}{}{Um... I'm here to pick up O'Neill's punkbuster.}
{202}{}{What kind of gun is that? It looks like it could blast through a Vault door!}
{203}{}{Who are you?}
{204}{}{What lies beyond the door you're guarding?}
{205}{}{Regarding the communists outside, can you provide any additional information? Are we in danger?}
{206}{}{Not at all. Goodbye.}
{207}{}{Me }
{208}{}{. Me smart!}

# Node002
{230}{}{O'Neill, you say? Ah, yes, I believe I know who you're referring to. She granted you clearance earlier. Before I can hand over the punkbuster, I kindly request you to sign this form. Our administrative procedures dictate that we keep meticulous records of our limited supplies.}
{231}{}{No, thank you.}
{232}{}{Alright, I'll sign it.}

# Node003
{260}{}{Apologies, but I'm not familiar with anyone named O'Neill.}
{261}{}{Ah, it seems I'm running late for a meeting. Goodbye!}

# Node004
{290}{}{In that case, the punkbuster will remain in my possession. If you change your mind, you know where to find me.}
{291}{}{Thanks for nothing.}

# Node005
{320}{}{Here you go, Citizen. Have a pleasant day.}
{321}{}{Thank you.}

# Node006
{350}{}{I am Chief Security Officer Hurst, responsible for overseeing the Vault alongside the Overseer and the Underseer.}
{351}{}{Walter is in grave danger outside! The communists are burning him alive! Please, act swiftly and save him!}
{352}{}{But you use firearms.}
{353}{}{Interesting. When I become the Underseer, only the Overseer and I will hold decision-making power.}

# Node007
{380}{}{Theories are one thing, but reality is what truly matters.}
{381}{}{I will prove myself to the Overseer. Farewell.}

# Node008
{410}{}{Nothing of concern.}
{411}{}{Come on, you can trust me. If the Underseer trusts me, so should you.}
{412}{}{Let me guess...}
{413}{}{Very well. Goodbye.}

# Node009
{440}{}{Indeed. This is where we store our weaponry and ammunition supplies.}
{441}{}{Is there a chance you could grant me access to the room?}
{442}{}{Thank you. Goodbye.}

# Node010
{470}{}{I'm afraid only the Overseer, the Underseer, myself, and the guards have access to the room.}
{471}{}{I could really use some extra ammunition.}
{472}{}{I understand. That will be all.}

# Node011
{500}{}{No, you don't require any ammunition inside the Vault. It's a safe haven, and I'll personally handle any intruders with a well-aimed shot between the eyes. If you have further inquiries, consult the Overseer.}
{501}{}{That's disappointing.}

# Node012
{530}{}{Please find another place to entertain yourself.}

# Node013
{560}{}{Hold on. I have a favor to ask of you.}
{561}{}{Not interested.}
{562}{}{What do you need?}

# Node025
{590}{}{This? It's a 14mm cannon. But check this out...}
{591}{}{What?}

# Node014
{620}{}{I possess a couple of magazines, Guns and Bullets, and one of them contains a really nice article on the .50 Magnum. Yes, a .50-motherfucking-Magnum. I'm eager to acquire that cannon, so if you come across one or know someone who has it, inform me, will you?}
{621}{}{What will you offer in return?}
{622}{}{I'm occupied. I don't have time for it.}
{623}{}{I'll keep an eye out. Don't worry.}

# Node015
{650}{}{I can take a "short break" from my guard duty, if you catch my drift.}
{651}{}{Great. If I find one, I'll bring it here.}
{652}{}{I'm reporting you to Frank!}
{653}{}{I'm not really interested. Find it yourself.}

# Node016
{680}{}{Thank you, Citizen. Here's the issue with the article, so you can verify it's the correct one. You know where to find me.}
{681}{}{Goodbye.}

# Node017
{710}{}{Farewell, Citizen.}
{711}{}{[END]}

# Node018
{740}{}{We have our methods. The Vault must be safeguarded against all forms of threats.}
{741}{}{Including those communists outside?}
{742}{}{That brings me peace of mind. Knowing you're always ready to blow holes and put a stop to any troublemakers. Take care, Officer.}

# Node019
{770}{}{Between you and me, I always considered them to be decent people. It's regrettable that it had to end this way. My men have orders to shoot on sight. Luckily, Doc is here in case any survive.}
{771}{}{Allowing communists to enter can't be good for the Vault. You can't trust them, and they're evil! That's what the government on TV said.}
{772}{}{Perhaps our doctors can find a cure for their communism.}

# Node020
{800}{}{[He wipes his nose.] We've experienced worse. Don't tell me you trust those GNN fools more than your own Chief Security Officer?}
{801}{}{Whatever. Just ensure they're not allowed in. It's your duty to make sure we don't catch the communism virus.}
{802}{}{I trust your judgment. Goodbye.}

# Node021
{830}{}{You know what, Citizen? No offense, but that's not a disease you can "cure." The New Plague is a true ailment, and there's talk of the big ones being dropped on our heads any moment now. Oh, I know it well. I've read books and studied extensively! If it were a disease with a cure, I'm sure the Doc and the others would have found it by now... I know my viewpoint isn't popular here, and you hold high hopes for this war, but the world out there has changed. Cities and roads no longer belong to us. It's doubtful you'll find what you're seeking. We must accept that we're losing this war or at least emerging as a different civilization.}
{831}{}{Hush, don't say such things! We are the greatest nation in the world. You speak like a traitor.}
{832}{}{I... I understand your perspective. What does the Overseer say about all of this?}

# Node022
{860}{}{I'm not a traitor. I'll defend this Vault until my last breath. I'm just weary of the war. All my friends are either KIA or MIA. We need to find a better solution than hiding in underground Vaults like rats. Speak to others if you don't trust me; Dr. Moreau shares my sentiments.}
{861}{}{I... I see what you mean. What is the Overseer's stance on this?}
{862}{}{Traitors!}

# Node023
{890}{}{Not much, really. He's not on our side, doesn't share our mindset. But with the right number of people and ample ammunition, we just might have a chance to see our vision become reality.}
{891}{}{Traitor!}
{892}{}{Can I help? I can even quote the Manifesto... Let the ruling classes tremble at a Communist revolution. The proletarians have nothing to lose but their chains. They have a world to win. Workingmen of all countries, unite!}
{893}{}{Heh, I'd better stay out of it. My mom always said I'll never be a proper revolutionary.}
{894}{}{Can I help? I'm not well-versed in your cause, but you can trust me.}

# Node024
{920}{}{Citizen, you've proven yourself to be a true hero in my eyes. I must admit, I had doubts before, but now I see that you're thinking clearly. I'll step out for a moment, if you catch my drift. *wink, wink* You never know when the contents of that room might come in handy.}
{921}{}{*wink*}

# # Node026
{950}{}{Please, }
{951}{}{. I see you're bored, but I can't properly guard the Vault if you're running around. Go to your room and listen to the radio there. It'll help calm you down.}
{952}{}{Gaga!}
