# Message file for v8orrin.ssl
# Number of nodes: 25
# Grammar pass done

{100}{}{You see a middle-aged man dressed in a lab coat.}
{101}{}{You see Orrin, the certified agronomist from Vault-Tec.}
{102}{}{He seems deeply engrossed in his calculations once again.}

{105}{}{I don't have time for you.}

# Node001
{200}{}{Greetings, citizen }
{201}{}{. I recognize your face from the citizen database. I am Orrin, the certified agronomist from Vault-Tec. How may I assist you, citizen?}
{202}{}{I have some questions.}
{203}{}{Just passing through.}
{204}{}{Zirbi!! Ghug.}

# Node002
{230}{}{Well, I suppose I could take a brief break.}
{231}{}{What are those papers you're holding?}
{232}{}{I've heard rumors about a technological marvel known as a G.E.C.K. Could I take a look at it, perhaps even make a copy of its valuable data?}
{233}{}{Actually, I need to be on my way.}

# Node003
{260}{}{These? They're just some test records. We need them for our analysis.}
{261}{}{We're conducting experiments here?}
{262}{}{I thought our surface monitors were our primary source of data.}
{263}{}{You keep those analysis computers busy. Farewell for now.}

# Node018
{290}{}{No, we don't solely rely on technology. In the worst-case scenario, if our maintenance bot fails and our equipment breaks, we must rely on our own intelligence to find solutions. We don't want to become overly dependent on technology, especially considering what's been happening in the Command Center. However, I can assure you that our water chip supplies are sufficient. As for the monitors, they were designed to be removed and dismantled once we emerge, and we'll stick to that plan.}
{291}{}{So, what exactly are we testing?}
{292}{}{What about the potential effects of radiation? If nuclear strikes occur, won't that impact our plans?}
{293}{}{No more questions. Thank you.}

# Node004
{320}{}{That's impossible. The G.E.C.K. has a built-in security chip that fries its circuits if anyone attempts to copy data from its internal holodisk. Walter can't even make a backup. However, our VACCS computer stores identical data.}
{321}{}{Our VACCS?}
{322}{}{Understood. Goodbye.}
{323}{}{Who is Walter?}

# Node020
{350}{}{Yes, the Vault-Tec Atomic City Construction Set, or VACCS for short. Walter has more information about it. I only know its location, which is further to the east of our current position, likely for security reasons.}
{351}{}{Could you show me its location on your Pip-Boy?}
{352}{}{I see. Interesting. Well, I'll catch up with you later.}

# Node005
{380}{}{One thing I'm curious about, }
{381}{}{... Why do you seek access to that data?}
{382}{}{If we survive this ordeal, the more people equipped with knowledge, the better for rebuilding our world. That's all.}
{383}{}{I'm simply interested in technology. Goodbye.}
{384}{}{I have my reasons. Goodbye.}

# Node006
{410}{}{We're comparing traditional agricultural methods used by farmers to the methods employed by our G.E.C.K. As you can see, rows 3 and 4 are faring much better than rows 1 and 2. It's evident that the G.E.C.K.'s methods are superior.}
{411}{}{G.E.C.K.? What exactly is that?}
{412}{}{So, are we solely relying on the surface monitors for our analysis?}
{413}{}{What about the potential influence of radiation?}

# Node007
{440}{}{It's a special device that will aid us in rebuilding civilization. I thought every Vault Citizen was aware of that.}
{441}{}{May I see it?}
{442}{}{Could you provide more specific details?}
{443}{}{I seem to have forgotten.}

# Node008
{470}{}{It's currently within the Vault, but I doubt you'll obtain Overseer clearance to view it. In fact, I've heard rumors that it has gone missing recently! It's the only G.E.C.K. we have, and undoubtedly the Underseer will be held accountable for its disappearance.}
{471}{}{Could you provide some additional information about it?}
{472}{}{Hmm, I wouldn't want to be in the Underseer's position. No more questions, thank you.}

# Node009
{500}{}{It's a device manufactured by Future-Tec, a division of Vault-Tec. Alongside VACCS, it will assist us in rebuilding or constructing a new, advanced city. It stores a wealth of valuable data and technology, but I can't delve into specifics at the moment. Look, I must return to tending these potatoes. Farewell, }
{501}{}{.}
{502}{}{VACCS?}
{503}{}{Alright, goodbye.}

# Node010
{530}{}{No problem. It happens to all of us. Excuse me, I need to get back to work now. See you later.}
{531}{}{Farewell.}
{532}{}{Whatever.}

# Node011
{560}{}{Radiation will most likely be present, and its effects on our potatoes are still uncertain. By the way, you should check with Walter for a Geiger counter.}
{561}{}{Who's Walter?}
{562}{}{Where can I find him?}
{563}{}{So, you're saying we have limited information on radiation, and eventually, we'll have to venture outside? That's a bit concerning!}

# Node012
{590}{}{Walter is a skilled technician working on the Core. He's quite knowledgeable.}
{591}{}{Where can I locate him?}
{592}{}{Thanks, see you later.}

# Node013
{620}{}{He's usually up in the Command Center. He sometimes stays there late into the night but I think he went out to check one of the surface monitors and hasn't returned yet. It's a bit strange.}
{621}{}{Hmm... I don't want to jump to conclusions, but our Vault-Tec van was shot at and set on flames, there are aggressive communists outside, and I saw a burnt body near the mountain entrance. I hope it's not Walter's.}
{622}{}{How do you know he stays up late?}

# Node014
{650}{}{We work together, and he prefers working during the night when the Vault is quieter.}
{651}{}{You mentioned a G.E.C.K. earlier. Could you tell me more about it?}
{652}{}{That's all I needed. Goodbye.}

# Node015
{680}{}{I believe Dr. Moreau or Dr. Grey will provide you with an anti-rad bag. That should be sufficient. Even our technician, Walter, thinks the radiation fears are blown out of proportion, blaming GNN for it.}
{681}{}{Good to know. Actually, I'd like more of that anti-rad medicine, just to be safe.}
{682}{}{Thank you for the information, Orrin. I'll let you get back to your work now.}

# Node016
{710}{}{You'll need to ask Dr. Moreau about that. Remember, all citizens require the medicine.}
{711}{}{You mentioned Walter. Who is he?}
{712}{}{Where can I find Walter?}
{713}{}{No more questions for now.}

# Node017
{740}{}{Hello. It seems your mind is beyond repair. I'm too busy with my potato tests to talk to you right now. Perhaps you could go play with the children or find something else to occupy yourself with.}
{741}{}{P. Tato!}
{742}{}{Gah!}

# Node019
{770}{}{Good to see you, }
{771}{}{Hi Orrin. What are you working on?}
{772}{}{See you later.}

# Node021
{800}{}{I apologize, but I don't want to risk getting in trouble with the Overseer.}
{801}{}{Thanks for nothing. Chicken.}

# Node022
{830}{}{Alright, no problem. I trust you. I'll show you, and then I have to get back to my work. Just keep quiet about it around the Overseer, okay?}
{831}{}{Thank you, Orrin!}

# Node023
{860}{}{Holy mother, we need to alarm Hurst immediately! I hope Walter is safe.}
{861}{}{Who's Hurst?}

# Node024
{890}{}{Hurst is our security officer in the Command Center. Please inform him about Walter and ensure that he's found, whether alive or deceased, so we can give him a proper burial.}
{891}{}{No problem. I'll do that right away.}
{892}{}{I don't have time for that. We're in the middle of a war, and people are dying. It's every man, woman, and child for themselves!}

# Node026
{920}{}{This is not a time for selfishness, }
{921}{}{. With that attitude, it may be challenging for you to integrate into our community. We need to support each other here. And now, we need to support Walter.}
{922}{}{Alright, I'll do it.}
{923}{}{Well, you said it! Always glad to support my friend, even if he's so lazy he hasn't moved since his funeral.}
