# Message file for vcbeaut.ssl
# Number of nodes: 6
# Grammar pass done

{102}{}{You've never seen someone so beautiful.}

# Node001
{200}{}{[Before you stands a policeman with an ethereal presence. His face possesses a striking beauty, reminiscent of an angel. Despite his commanding aura, he seems more focused on guarding you than the surrounding area. His pre-war uniform is impeccably clean and in perfect condition.]}
{201}{}{Are you an angel?}
{202}{}{Where did you come from?}
{203}{}{Can't a man have some peace, even when trying to get some sleep in this damn desert?}
{204}{}{Can't a woman have some peace, even when trying to get some sleep in this damn desert?}
{205}{}{Wow, I am captivated by your beauty.}
{207}{}{Flee.}
{208}{}{Attack him.}
{209}{}{How can I open the blast door? I, um... I'm looking for a safe place to rest.}
{210}{}{Hnng!}

# Node002
{230}{}{Perhaps.}
{231}{}{Take me to paradise.}

# Node003
{260}{}{If you have to ask, you may not be ready to know.}

# Node004
{290}{}{You can rest assured that I will protect you from any harm.}

# Node005
{320}{}{Perhaps, in due time. When you are prepared.}

# Node006
{350}{}{He smiles knowingly, revealing a set of perfect white teeth.}

# Node007
{380}{}{I don't know you. But I'm not going to deny you safety. Use the entry code 834-946.}
{381}{}{Thank you.}
