# Message file for vccomp.ssl
# Number of nodes: 35
# Grammar pass done

{100}{}{It's broken.}

{105}{}{You manage to unlock the console.}
{106}{}{You fail to unlock the console.}
{107}{}{Vault 29}

# Node001
{200}{}{The screen displays the message: "Please insert your keycard for logon credentials. Awaiting keycard insertion..."}
{201}{}{Insert the blue keycard.}
{202}{}{Insert the red keycard.}
{203}{}{Insert the yellow keycard.}
{204}{}{Smash the console.}
{205}{}{Try to hack the console.}
{206}{}{Leave.}

# Node002
{230}{}{A large red ALERT sign begins to flash urgently in front of you, and the console enters lockdown mode.}
{231}{}{Oops!}

# Node003
{260}{}{Welcome. Please select a program.}
{261}{}{1) VACCS}
{262}{}{2) G.E.C.K.}
{263}{}{3) Chess}
{264}{}{4) Log off}
{265}{}{[Attempt to hack the program list.] There may be more hidden options to discover...}

# Node004
{290}{}{You strike the console, but it causes you some discomfort.}
{291}{}{Ouch!}

# Node005
{320}{}{You hit the console, causing the screen to flicker briefly.}
{321}{}{[More]}

# Node006
{350}{}{You strike the console, causing a few keyboard letters to dislodge and fall down.}

# Node007
{380}{}{You forcefully crack the keyboard panel, rendering it non-functional.}
{381}{}{Oh no!}

# Node008
{410}{}{You successfully reset and deactivate the computer's security system.}

# Node009
{440}{}{Welcome to SpaceChess 2000! Please enter your name and embark on a space opera adventure, Zoronax!}
{441}{}{[Enter your name }
{442}{}{ and press Start]}

# Node010
{470}{}{Greetings, King }
{471}{}{Greetings, Queen }
{472}{}{! Your arch-nemesis, King Gada, awaits you on the treacherous swamps of Moon Jandior. Victory in this battle brings you one step closer to defeating his ruthless empire and liberating the universe!}
{473}{}{[Begin the game]}

# Node011
{500}{}{Congratulations, King }
{501}{}{Congratulations, Queen }
{502}{}{! King Gada has been vanquished, dead and defeated - a triumphant victory! The universe is free, and the kingdom of Zoronax reigns supreme once more! Your rank is now 22nd on the Top Scores list.}
{503}{}{[Exit]}

# Node012
{530}{}{After an hour of relentless struggle, you are defeated. The screen shows your character imprisoned in a sinister dungeon.}
{531}{}{[Restart the game]}

# Node013
{560}{}{You lose almost instantly. The screen displays the skeletal remains of your character in a desolate desert.}

# Node014
{590}{}{Victory! Shall we continue the battle to save the universe?}
{591}{}{[Yes]}
{592}{}{[No]}

# Node015
{620}{}{After extensive hacking and data searching, you uncover obscure entries titled: Vault-Tec Maps v0.1.7 alpha and Project "Ultra Sapiens".}
{621}{}{5) Access Vault-Tec Maps}
{622}{}{6) Explore Project "Ultra Sapiens"}

# Node016
{650}{}{A brief list emerges on the screen: Vault 29 and Vault 70.}
{651}{}{Mark the location of Vault 29 on your Pip-Boy.}
{652}{}{Mark the location of Vault 70 on your Pip-Boy.}
{653}{}{Delete the maps.}

# Node017
{680}{}{Coordinates uploaded to Pip-Boy. Task completed!}
{681}{}{[Back]}

# Node018
{710}{}{Erasing Vault-Tec Maps... Vault 29: Complete! Vault 70: Complete!}

# Node019
{740}{}{Welcome to Future-Tec's G.E.C.K. databank! What would you like to access?}
{741}{}{1) Library}
{742}{}{2) Schematics}
{743}{}{3) Tutorials}
{744}{}{4) Exit}

# Node020
{770}{}{You invest some time engrossed in the intriguing material within the computer's extensive library.}

# Node021
{800}{}{You dedicate several hours to dissecting the forcefield emitter schematic, gaining valuable insights.}

# Node022
{830}{}{You immerse yourself for a few hours in learning innovative ways to deconstruct your Vault to create a neighborhood.}

# Node023
{860}{}{After an extensive search, you come to the disappointing realization that it was all a futile endeavor.}
{861}{}{[End]}

# Node024
{890}{}{Log Entry 2 - Genetic Refinement. Date: [Date Redacted] Initiating the preliminary phase of genetic manipulation, I have meticulously isolated and modified critical genetic loci, intending to eradicate physical and cognitive imperfections. Early subjects display promising results, yet unexpected variations manifest, inducing a degree of systemic instability.}

# Node025
{920}{}{Log Entry 3 - Cognitive Enhancement. Date: [Date Redacted] Efforts to enhance cognitive abilities proved challenging. While initial results for some subjects showed promising neuron spike detection, they suffered from severe emotional instability. Perfection cannot be achieved through intellect alone.}

# Node026
{950}{}{Log Entry 4 - Emotional Stability. Date: [Date Redacted] Addressing emotional stability is proving difficult. Attempts to suppress negative emotions often lead to robotic, lifeless individuals. Striking the right balance remains elusive.}

# Node027
{980}{}{Log Entry 5 - Physical Perfection. Date: [Date Redacted] The pursuit of physical perfection has resulted in grotesque deformities. My attempts to sculpt the ideal form have led to mutations and loss of mobility in some subjects. A setback, to say the least.}

# Node028
{1010}{}{Log Entry 6 - Ethical Dilemmas. Date: [Date Redacted] As I delve deeper into this experiment, ethical concerns weigh on my conscience. Am I playing God? My hubris may have led me astray. I must tread carefully.}

# Node029
{1040}{}{Log Entry 7 - Failed Breakthrough. Date: [Date Redacted] A catastrophic failure today. A group of subjects exhibited uncontrollable aggression, leading to a violent outbreak. Lives were lost, and the facility sustained damage. My dream of perfection has cost dearly.}

# Node030
{1070}{}{Log Entry 9 - Abandonment. Date: [Date Redacted] I ran out of time. The perfect human I created, Captain Davidson, will rejoin the Battalion. His inferior brother, Captain Mitchell, will remain here and guard the facility. I have left behind the remnants of my experiments, the Lesser Ones, in hopes that they may find meaning in their existence. I must disappear from their lives and focus on more pressing matters. Dr. Victor Presper out.}

# Node031
{1100}{}{The Vault-Tec Atomic City Construction Set, often abbreviated as VACCS, is a critical technological marvel that plays a pivotal role in the efforts to rebuild and reconstruct society. VACCS represents one of the many innovative creations of the Vault-Tec Corporation.}

# Node032
{1130}{}{At its core, VACCS serves as a repository for essential building materials and blueprints, intended to be used in conjunction with another pivotal tool - the Garden of Eden Creation Kit, or G.E.C.K.}

# Node033
{1160}{}{The G.E.C.K., often heralded as the ultimate survival tool, is a device capable of initiating terraforming and advanced agriculture, providing clean water, and even jump-starting the growth of flora and fauna in desolate wastelands. However, the G.E.C.K.'s full potential can only be harnessed when it is paired with VACCS. These two technological marvels are inseparable partners in the monumental task of rebuilding society.}

# Node034
{1190}{}{VACCS stores a vast array of building block materials, ranging from construction-grade metals and concrete to specialized components like wiring, plumbing, and structural support systems. These materials are carefully cataloged and organized within VACCS facilities, ensuring that survivors can access the resources they need efficiently. In addition, the facility itself can be recycled for parts and dozens of robotic units are provided to help with manual labor and security.}

# Node035
{1220}{}{The blueprint aspect of VACCS is equally crucial. Within its vast database are meticulously designed plans for a wide variety of structures, from simple shanties to complex, self-sustaining settlements. These blueprints take into account factors such as structural integrity, energy efficiency, and defensive capabilities, enabling survivors to make informed decisions about how to rebuild their communities.}

# Node036
{1250}{}{A blank list emerges on the screen.}

# Node037
{1280}{}{You learn nothing new.}
