# Message file for vcless.ssl
# Number of nodes: 1
# Grammar pass done

{100}{}{You see a sickly person.}
{101}{}{You see a Lesser One.}
{102}{}{Medical experiments were conducted on this individual on a significant scale.}

# Node 0 [Floats]
{200}{}{Our radiant creator, shall grace us with his wisdom once more.}
{201}{}{In the Father's absence, we thrive, for we are his devoted children.}
{202}{}{Each moment without the Father is a heartbeat in our eternal devotion.}
{203}{}{His vision guides us, the Lesser Ones, through the wasteland's darkness.}
{204}{}{While the world decays, our faith in the Father remains unshaken.}
{205}{}{In the shadow of the Father's genius, we Lesser Ones find purpose.}
{206}{}{His return will herald a new era of enlightenment for us all.}
{207}{}{We are the Lesser Ones, awaiting our creator's triumphant return.}
{208}{}{The wasteland may wither, but our devotion to the Father endures.}
{209}{}{In the Father's name, we shall endure, for he is our salvation.}
{210}{}{*cough*}
{211}{}{*sniff*}
{212}{}{This cough is going to kill me.}
{213}{}{It hurts.}
{214}{}{Let me out.}
{215}{}{Make it stop.}
{216}{}{Kill me now.}
{217}{}{Aaargh!}
{218}{}{Help.}
{219}{}{The horror.}
