# EXAMINES
{151}{}{}

# USE MESSAGES
{199}{}{What kind of an asshole question is that?}
{200}{}{Outlook good.}
{201}{}{Outlook not so good.}
{202}{}{My reply is no.}
{203}{}{Don't count on it.}
{204}{}{You may rely on it.}
{205}{}{Ask again later.}
{206}{}{Most likely.}
{207}{}{Cannot predict now.}
{208}{}{Yes.}
{209}{}{Yes. Definitely.}
{210}{}{Better not to tell you now.}
{211}{}{It is certain.}
{212}{}{Very doubtful.}
{213}{}{It is decidedly so.}
{214}{}{Concentrate and ask again.}
{215}{}{Signs point to yes.}
{216}{}{My sources say no.}
{217}{}{Without a doubt.}
{218}{}{Reply hazy, try again.}
{219}{}{As I see it, yes.}
{220}{}{Stop shaking me so hard. It hurts.}
{221}{}{You have a strong right arm.}
{222}{}{Please wipe your hands before shaking me again.}
{223}{}{Temporarily out of service.}
{224}{}{I don't know if the game is rigged or not.}
{225}{}{Keep shaking me, and there'll be trouble.}
{226}{}{I'm getting sick.}
{227}{}{I'm getting nauseous.}
{228}{}{Your hands are warm.}
# 9 or greater luck
{229}{}{I'm actually a high-tech toy.}
{230}{}{I was invented by a billionaire with too much money and too much free time.}
{231}{}{I was there when the world ended.}
{232}{}{My owner and I loved watching that TV show about Clark Kent growing up. Good times.}
{233}{}{If you break me, who's going to fix me?}
{234}{}{There's an Easter Egg out there somewhere.}
{235}{}{I was once shaken really hard by a tribal in New Reno.}
{236}{}{Stop shaking me so hard!}
{237}{}{You're very lucky - I can feel it. Keep shaking me!}
{238}{}{Yes, it's all smoke and mirrors. I'm nothing more than a fancy toy.}
{239}{}{You wouldn't happen to have any Micro Fusion Cells on you, would you?}
{240}{}{Your future is so bright, I'm gonna need sunglasses.}
{241}{}{The universe says: Why not? You're the favorite child.}
{242}{}{Fortune cookies want to be you when they grow up.}
{243}{}{Even this 8-Ball is jealous of your luck.}
{244}{}{Ask again... but let someone else have a chance this time.}
{245}{}{Your luck is so strong, I'm just here for decoration.}
{246}{}{Results unclear - too much luck is clogging my system.}
{247}{}{Yes. Obviously. When is it not?}
{248}{}{Heads? Tails? You always win. Stop asking.}
{249}{}{Outlook excellent. Lottery ticket suggested.}
{250}{}{Seriously, leave some luck for the rest of us.}
{251}{}{Do you have a four-leaf clover in your pocket, or are you just naturally magic?}
{252}{}{Signs point to "you again?" Of course.}
{253}{}{If you were any luckier, I'd call you a cheat.}
{254}{}{I'm just a ball, but even I see you're on a winning streak.}
