#############################################################
#  Message File: ZCBrahmn.msg                               #
#                                                           #
#       Body Type:  Brahmin                                 #
#       Combat AI: None                                     #
#       Weapons: None                                       #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
# Grammar pass done
{100}{}{You see a docile domesticated polled bighorner.}
{101}{}{It's believed that the bighorners' external spines developed as a result of early radiation exposure on what was once known as sheep.}
{102}{}{Aside from the absence of horns, this bighorner appears to be quite ordinary.}
{103}{}{Bighorners aren't known for their conversational skills.}
{104}{}{Don't you have something more worthwhile to occupy your time than chatting with a mutated sheep?}
{105}{}{This remarkable mutant bighorn sheep is a versatile resource. Bighorners provide meat, milk, leather, baby bighorners, bones, and even their droppings can be used as fuel for fires.}

{201}{}{Baaa...}
{202}{}{Bah Bah Baaaaah...}
{203}{}{Baaah...}
{204}{}{Baaaaaah...}
{205}{}{Baaaaaaaaaaah...}
{206}{}{:: GRUNT ::}
