/*

        Name:           Commander Brixley
        Location:
        Description:

           Created: 30/01/2021 13:22:41

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
#include "..\HEADERS\maxbunkr.h"

#define NAME                    SCRIPT_MBANDREA

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_BROTHERHOOD)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

#define MIN_COS_KILLED (18) // 90%

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure Diagnose;
procedure StartSeniorCutscene;

// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Illfloat;
procedure Curedfloat;
procedure TalkIll;
procedure Cured;
procedure WhoIs;
procedure OKDiagnose;
procedure TryLeave;
procedure KillMe;
procedure TestSuccess;
procedure TestSuccess2;
procedure TestFailure;
procedure RadAway5;
procedure RadAway4;
procedure RadAway3;
procedure RadAway2;
procedure RadAway1;
procedure Treated;
procedure Feelgreat;
procedure Thanks;
procedure Goodbye;
procedure Poor;
procedure HowAreYou;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node025;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node034_take_stealth ;
procedure Node999_die ;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;
procedure Node039;
procedure Node039a;
procedure Node039b;
procedure Node040;
procedure Node041;
procedure Node042;
procedure Node043;
procedure Node044;
procedure Node045;
procedure Node046;
procedure Node047;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)

#define LVAR_Rad_Away (8)
#define LVAR_Thanks (9)
#define LVAR_Diagnosis (10)
#define LVAR_Die (11)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_BROTHERHOOD_OF_STEEL);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);

add_timer_event(self_obj,game_ticks(random(3, 5)),0);
call new_plague_check(self_obj, LVAR_Herebefore);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

   if(global_var(GVAR_QUEST_CURE_COMMANDER) == 3) then begin

   /* If the critter is mad at the player for any reason, it will attack and remember to attack
      the player should the game be saved and loaded repeatedly. Additionally, if any special
      actions need to be taken by the critter based on previous combat, the critter will remember
      this as well. */
      if(global_var(GVAR_BROTHERHOOD_KLAXON) == 1) then
         set_local_var(LVAR_Hostile,2);

      if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
         set_local_var(LVAR_Hostile,1);
         self_attack_dude;
         //Macro made by Tom to keep the critter fleeing.
      end
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_INTOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,HEAD_ANDREA_BRIXLEY,BACKGROUND_BHOOD);
       gSay_Start;
       if(global_var(GVAR_QUEST_CURE_COMMANDER) == 3) then begin
          if(local_var(LVAR_Thanks) == 1) then begin
             if(global_var(GVAR_QUEST_FIND_POISONER) > 0) then begin
               if (ncr_bos_war_ended and (global_var(GVAR_QUEST_ESTABLISH_TRADE) == QUEST_NONE)) then
                  call Node040;
               else
                  call Cured;
             end
            else begin
               call Node026;
            end
          end else
            call Thanks;
       end else
            call TalkIll;
       gSay_End;
       end_dialogue;


   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin

   add_timer_event(self_obj,game_ticks(random(3, 5)),0);

   if(local_var(LVAR_Die) == 1) then
      critter_dmg(self_obj, 400, DMG_normal_dam);

   if (random(0, 30) == 1 and self_can_speak) then begin
      if(global_var(GVAR_QUEST_CURE_COMMANDER) == 3) then begin
         if(self_can_see_dude) then
            floater_good_rand(230, 232);
      end else
         floater_sick_rand(200, 204);
  end

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   variable curedelder := 0;
   script_overrides;
   if (global_var(GVAR_QUEST_CURE_COMMANDER) == 3) then
   curedelder = 10;

   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100 + curedelder);
   else
      display_mstr(101 + curedelder);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   variable curedelder := 0;
   script_overrides;
   if (global_var(GVAR_QUEST_CURE_COMMANDER) == 3) then
      curedelder = 10;
   display_mstr(102 + curedelder);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

procedure Diagnose begin

variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_DOCTOR, -110);

fadeout(1);
fadein(1);
set_local_var(LVAR_Diagnosis, 1);

if is_success(roll_temp) then
begin
call TestSuccess;
end
else begin
call TestFailure;
 end
end





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


//



//
// Notes:
//
// Option 1 is only available if the player hasn't attempted diagnosis yet.\

procedure TalkIll
begin

Reply(290);
if(local_var(LVAR_Diagnosis) == 0) then
NOption(291,WhoIs,4);
else begin
// NOTE: increment LVAR_Rad_Away
if (local_var(LVAR_Rad_Away)==0 and (obj_is_carrying_obj_pid(dude_obj,PID_RADAWAY)>0)) then
NOption(292,RadAway5,4);
// NOTE: increment LVAR_Rad_Away
if (local_var(LVAR_Rad_Away)==1 and (obj_is_carrying_obj_pid(dude_obj,PID_RADAWAY)>0)) then
NOption(293,RadAway4,4);
// NOTE: increment LVAR_Rad_Away
if (local_var(LVAR_Rad_Away)==2 and (obj_is_carrying_obj_pid(dude_obj,PID_RADAWAY)>0)) then
NOption(294,RadAway3,4);
// NOTE: increment LVAR_Rad_Away
if (local_var(LVAR_Rad_Away)==3 and (obj_is_carrying_obj_pid(dude_obj,PID_RADAWAY)>0)) then
NOption(295,RadAway2,4);
// NOTE: increment LVAR_Rad_Away
if (local_var(LVAR_Rad_Away)==4 and (obj_is_carrying_obj_pid(dude_obj,PID_RADAWAY)>0)) then
NOption(296,RadAway1,4);
end
NOption(297,Node999,4);
end

procedure Cured
begin
Reply(mstr(320)+dude_name+mstr(321));
NOption(322,HowAreYou,4);
NOption(323,Node999,4);
if(global_var(GVAR_QUEST_FIND_POISONER) == 2) then
NOption(324,Node025,4);
if ((town_visible_on_map(AREA_CIRCLE_OF_STEEL) and global_var(GVAR_COS_KILLED) < MIN_COS_KILLED and global_var(GVAR_QUEST_FIND_CIRCLE_OF_STEEL) == 1)) then
NOption(325,Node030,4);
if ((town_visited(AREA_CIRCLE_OF_STEEL) and global_var(GVAR_COS_KILLED) >= MIN_COS_KILLED and (obj_is_carrying_obj_pid(dude_obj,PID_STEALTH_BOY) >= MIN_COS_KILLED) and global_var(GVAR_QUEST_FIND_CIRCLE_OF_STEEL) == 1)) then
NOption(326,Node034_take_stealth,4);
if ((town_visited(AREA_CIRCLE_OF_STEEL) and global_var(GVAR_COS_KILLED) >= MIN_COS_KILLED and global_var(GVAR_QUEST_FIND_CIRCLE_OF_STEEL) == 1)) then
   NOption(327,Node034,4);
if (town_known(AREA_BOULDER_DOME) and (AreaNukeStatus(AREA_BOULDER_DOME) == AREA_BOULDER_DOME)) then begin
   GOption(328,Node035,4);
   // TODO BOS in charge of Boulder Dome
   //BOption(329,Node038,4);
   GOption(330,Node035,-3);
   //TODO BOS in charge of Boulder Dome
   //BOption(331,Node038,-3);
end

if (global_var(GVAR_BLEW_UP_HOOVER_DAM) == 1) then begin
   NOption(332,Node039,4);
   NOption(333,Node039,-3);
end
else if (
   (global_var(GVAR_QUEST_OPERATION_PEACEMAKER) == QUEST_ACCEPTED) and
   (global_var(GVAR_QUEST_HOOVER_PEACE) == QUEST_COMPLETED)
   ) then begin
   GOption(334,Node039,4);
   GOption(335,Node039,-3);
end

if ((global_var(GVAR_QUEST_CIPHERS_URANIUM) == QUEST_KNOWN) or (global_var(GVAR_QUEST_CIPHERS_URANIUM) == QUEST_ACCEPTED)) then begin
   GOption(336,Node046,4);
   GOption(337,Node046,-3);
end

end

procedure Node034_take_stealth begin
   give_xp(2000);
   display_mstr(106);
   remove_pid_qty(dude_obj, PID_STEALTH_BOY, 20)
   set_global_var(GVAR_BOS_STEALTH, 1);
   call Node034;
end

procedure WhoIs
begin
Reply(350);
NOption(351,OKDiagnose,4);
NOption(352,Node999,4);
end

procedure OKDiagnose
begin
Reply(380);
NOption(381,Diagnose,4);
end

procedure TryLeave
begin
Reply(410);
NOption(411,KillMe,4);
NOption(412,Node999,4);
end

procedure KillMe
begin
Reply(440);
NOption(441,Node999,4);
end

procedure TestSuccess
begin
Reply(470);
NOption(471,TestSuccess2,4);
end

procedure TestSuccess2
begin
Reply(500);
NOption(441,Node999,4);
end

procedure TestFailure
begin
Reply(530);
NOption(441,Node999,4);
end

// Node RadAway5
//
// Notes:
//
// Option 1 only available if player has rad-away

procedure RadAway5
begin
   inc_local_var(LVAR_Rad_Away);
   remove_pid_qty(dude_obj, PID_RADAWAY, 1)
Reply(560);
// NOTE: increment LVAR_Rad_Away
if(obj_is_carrying_obj_pid(dude_obj,PID_RADAWAY)>0) then
NOption(293,RadAway4,4);
NOption(441,Node999,4);
end

// Node RadAway4
//
// Notes:
//
// Option 1 only available if player has rad-away

procedure RadAway4
begin
   inc_local_var(LVAR_Rad_Away);
   remove_pid_qty(dude_obj, PID_RADAWAY, 1)

Reply(590);
// NOTE: increment LVAR_Rad_Away
if(obj_is_carrying_obj_pid(dude_obj,PID_RADAWAY)>0) then
NOption(294,RadAway3,4);
NOption(441,Node999,4);
end

// Node RadAway3
//
// Notes:
//
// Option 1 only available if player has rad-away

procedure RadAway3
begin
   inc_local_var(LVAR_Rad_Away);
   remove_pid_qty(dude_obj, PID_RADAWAY, 1)

Reply(620);
// NOTE: increment LVAR_Rad_Away
if(obj_is_carrying_obj_pid(dude_obj,PID_RADAWAY)>0) then
NOption(295,RadAway2,4);
NOption(441,Node999,4);
end

// Node RadAway2
//
// Notes:
//
// Option 1 only available if player has rad-away

procedure RadAway2
begin
   inc_local_var(LVAR_Rad_Away);
   remove_pid_qty(dude_obj, PID_RADAWAY, 1)

Reply(650);
// NOTE: increment LVAR_Rad_Away
if(obj_is_carrying_obj_pid(dude_obj,PID_RADAWAY)>0) then
NOption(296,RadAway1,4);
NOption(441,Node999,4);
end

// Node RadAway1
//
// Notes:
//
// Option 1 needs to fade out,advance time, then back in before going into thankyou sequence

procedure RadAway1
begin
   remove_pid_qty(dude_obj, PID_RADAWAY, 1)

Reply(680);
NOption(681,Treated,4);
end

procedure Treated
begin
   fadeout(1);
   fadein(1);
   game_time_advance(ONE_GAME_HOUR * 2);
Reply(710);
NOption(711,Feelgreat,4);
end

procedure Feelgreat
begin
Reply(740);
NOption(741,Node999_die,4);
end

procedure Node999_die begin
   call Node999;
   set_local_var(LVAR_Die, 1);
   inc_bos_rep(-50);
   set_global_var(GVAR_QUEST_CURE_COMMANDER, 3);
end

// Node Thanks
//
// Notes:
//
// Karma reward for option 1?

procedure Thanks
begin
   set_local_var(LVAR_Thanks, 1);
if (dude_is_male) then Reply(770); else
if (dude_is_female) then Reply(771);
NOption(772,Goodbye,4);
NOption(773,Poor,4);
end

procedure Goodbye
begin
Reply(800);
NOption(801,Node999,4);
end

procedure Poor
begin
if(obj_is_carrying_obj_pid(self_obj,PID_MB_LIBRARY_KEYCARD)>0)  then begin
      transfer_pid_between_objs(self_obj, dude_obj, PID_MB_LIBRARY_KEYCARD, 1)
      Reply(830);
end else
Reply(829);


NOption(831,Node999,4);
NOption(832,Node999,4);
end

procedure HowAreYou
begin
Reply(860);
NOption(861,Node999,4);
end

procedure Node026
begin
Reply(890);
NOption(891,Node027,1);
end

procedure Node027
begin

   set_global_var(GVAR_QUEST_FIND_POISONER, 1);
   set_global_var(GVAR_BROTHERHOOD_SENIOR_INITIATE, 1);
   set_global_var(GVAR_BROTHERHOOD_INITIATE, 0);
   give_xp(500);
   display_mstr(105);
   give_pid_qty(dude_obj, PID_YOUR_DOG_TAG, 1)

Reply(mstr(920)+dude_name+mstr(921));
NOption(922,Node028,4);
NOption(923,Node028,-3);
end

procedure Node028
begin
if (dude_is_male) then Reply(mstr(950)+dude_name+mstr(951)); else
if (dude_is_female) then Reply(mstr(952)+dude_name+mstr(951));
NOption(953,Node999,4);
NOption(954,Node999,-3);
end

procedure Node025
begin
Reply(980);
NOption(981,Node029,4);
end

procedure Node029
begin

// We busted Ailis before
if (
   (global_var(GVAR_QUEST_HOOVER_PEACE) == QUEST_ACCEPTED) and
   (global_var(GVAR_QUEST_ARREST_AILIS) != QUEST_NONE)
   ) then
   set_global_var(GVAR_QUEST_HOOVER_PEACE, QUEST_COMPLETED);

set_global_var(GVAR_QUEST_FIND_POISONER, 3);
set_global_var(GVAR_QUEST_FIND_DEVONS_CONTACTS, 1);
set_global_var(GVAR_QUEST_FIND_CIRCLE_OF_STEEL, 1);
give_xp(1500);

Reply(1010);
NOption(1011,Node033,4);
end

procedure Node030
begin
Reply(1040);
NOption(1041,Node031,4);
NOption(1042,Node999,4);
end

procedure Node031
begin
Reply(mstr(1070)+dude_name+mstr(1071));
NOption(1042,Node999,4);
NOption(1072,Node999,4);
end

procedure Node032
begin
Reply(1100);
NOption(1101,Node999,4);
end

procedure Node033
begin

   set_global_var(GVAR_BROTHERHOOD_SENIOR_INITIATE, 0);
   set_global_var(GVAR_BROTHERHOOD_APPRENTICE, 1);
   give_xp(500);
   display_mstr(105);


Reply(mstr(1130)+dude_name+mstr(1131));
NOption(1132,Node999,4);
end

procedure Node034
begin
   give_xp(2500);

   set_global_var(GVAR_QUEST_FIND_CIRCLE_OF_STEEL, 2);
   set_global_var(GVAR_QUEST_OPERATION_PEACEMAKER, QUEST_ACCEPTED);

   set_global_var(GVAR_BROTHERHOOD_APPRENTICE, 0);
   if(dude_is_male) then
      set_global_var(GVAR_BROTHERHOOD_JOURNEYMAN, 1);
   else
      set_global_var(GVAR_BROTHERHOOD_JOURNEYWOMAN, 1);

   give_xp(500);
   display_mstr(105);


if (dude_is_male) then Reply(mstr(1160)+dude_name+mstr(1161)+dude_name+mstr(1162)); else
if (dude_is_female) then Reply(mstr(1160)+dude_name+mstr(1161)+dude_name+mstr(1163));
NOption(1164,Node999,4);
NOption(1165,Node999,4);
end

procedure Node035
begin
Reply(1190);
NOption(1191,Node036,4);
NOption(1192,Node036,-3);
end

procedure Node036
begin
Reply(1220);
NOption(471,Node037,4);
NOption(471,Node037,-3);
end

procedure Node037
begin
Reply(1250);
NOption(1251,Node038,4);
NOption(1252,Node038,-3);
end

procedure Node038
begin
Reply(1280);
NOption(922,Node999,4);
NOption(923,Node999,4);
end

procedure Node039
begin
   variable str;
   str = "";

   if (global_var(GVAR_BLEW_UP_HOOVER_DAM) == 1) then
      str = " " + mstr(1315);

   give_xp(3000);
   set_global_var(GVAR_QUEST_OPERATION_PEACEMAKER, QUEST_COMPLETED);
   display_msg(g_mstr(1000));

   set_global_var(GVAR_BROTHERHOOD_SENIOR, 1);
   if(dude_is_male) then begin
      set_global_var(GVAR_BROTHERHOOD_JOURNEYMAN, 0);
   end
   else begin
      set_global_var(GVAR_BROTHERHOOD_JOURNEYWOMAN, 0);
   end

Reply(mstr(1310) + dude_name + mstr(1311) + str);
if (global_var(GVAR_QUEST_FIND_ARMORY_CODES) == QUEST_COMPLETED) then begin
   NOption(mstr(1312) + mstr(1313),Node039a,4);
end
NOption(mstr(1312) + mstr(1314),Node039b,4);
end

procedure Node039a
begin
   give_pid_qty(dude_obj, PID_POWERED_ARMOR, 1)
   call StartSeniorCutscene;
end

procedure Node039b
begin
   give_pid_qty(dude_obj, PID_BROTHERHOOD_COMBAT_ARMOR, 1)
   call StartSeniorCutscene;
end

procedure StartSeniorCutscene
begin
   fadeout(1);
   set_map_var(MVAR_SENIOR_CUTSCENE, 1);
   call Node999;
   move_to(dude_obj, 21501, 0);
   critter_attempt_placement(dude_obj, 21501, 0);
end

procedure Node040
begin
Reply(1340);
NOption(1341,Node041,4);
end

procedure Node041
begin
Reply(1370);
NOption(1371,Node042,4);
end

procedure Node042
begin
Reply(1400);
GOption(1401,Node043,4);
BOption(1402,Node044,4);
end

procedure Node043
begin

   set_global_var(GVAR_QUEST_ESTABLISH_TRADE, QUEST_ACCEPTED);

Reply(1430);
NOption(891,Node999,4);
end

procedure Node044
begin
Reply(1460);
NOption(1461,Node045,4);
end

procedure Node045
begin
Reply(1490);
NOption(1491,Node043,4);
end

procedure Node046
begin
Reply(1520);

set_global_var(GVAR_QUEST_CIPHERS_URANIUM, QUEST_ACCEPTED);

if (dude_item_count(PID_REFINED_ORE) >= 10) then begin
   NOption(1521,Node047,4);
   NOption(1523,Node047,-3);
end

NOption(1522,Node999,4);
NOption(1524,Node999,-3);
end

procedure Node047
begin

   give_pid_qty(dude_obj, PID_2MM_EC_AMMO, 1)
   give_pid_qty(dude_obj, PID_4_7MM_CASELESS, 1)
   remove_pid_qty(dude_obj, PID_REFINED_ORE, 10)
   remove_pid_qty(dude_obj, PID_LEAD_BOX_EW, 4)
   remove_pid_qty(dude_obj, PID_LEAD_BOX_NS, 6)
   inc_bos_rep(5);
   set_global_var(GVAR_QUEST_CIPHERS_URANIUM, QUEST_COMPLETED);
   give_xp(250);

Reply(1550);
NOption(1551,Node999,4);
NOption(1552,Node999,-3);
end
//xxxxxxxxxxxxxxxxxxxx
