/*******************************************************************************
        Name:
        Location:
        Description: Object template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"

#define NAME                    SCRIPT_MBBRKFRK

/* Standard Script Procedures */
procedure start;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure repair_time;

/* Defines */


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/

procedure start begin
end

procedure use_skill_on_p_proc begin

   if (action_being_used == SKILL_REPAIR and global_var(GVAR_QUEST_REPAIR_BROKEN_FORKLIFT) < 2) then begin
       script_overrides;

      if(skill_success(source_obj, SKILL_REPAIR, -20)) then begin
          set_global_var(GVAR_QUEST_REPAIR_BROKEN_FORKLIFT, 2);
         display_msg(mstr_skill(606) + " " + obj_name(self_obj) + ".");
		 give_xp(200);
         call repair_time;

      end else begin
         display_msg(mstr_skill(607) + " " + obj_name(self_obj) + ".");
         call repair_time;
      end

   end else if (action_being_used == SKILL_SCIENCE) then begin
      script_overrides;

      if(skill_success(source_obj, SKILL_SCIENCE, -20)) then begin
         display_mstr(100);
      end else begin
         display_msg(mstr_skill(611));
      end

   end

end

procedure use_obj_on_p_proc begin
   variable tool := obj_pid(obj_being_used_with);

   if (
   tool == PID_WRENCH or
   tool == PID_MULTI_TOOL or
   tool == PID_SUPER_TOOL_KIT
   ) and (global_var(GVAR_QUEST_REPAIR_BROKEN_FORKLIFT) < 2) then begin
      script_overrides;

      if(skill_success(source_obj, SKILL_REPAIR, -20)) then begin
         display_msg(mstr_skill(606) + " " + obj_name(self_obj) + ".");
		 give_xp(200);
       call repair_time;
       set_global_var(GVAR_QUEST_REPAIR_BROKEN_FORKLIFT, 2);
      end else begin
         display_msg(mstr_skill(607) + " " + obj_name(self_obj) + ".");
       call repair_time;

      end

   end
end


procedure repair_time begin
    fadeout(1);
    game_time_advance(ONE_GAME_HOUR);
    fadein(1);
end

