/*

        Name:           Ed
        Location:
        Description:

           Created: 29/11/2020 12:04:37

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_MBED

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_BROTHERHOOD)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\HEADERS\maxbunkr.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node020;
procedure Node021;
procedure Node021a;
procedure Node021aa;
procedure Node021b;
procedure Node021ba; 
procedure Node021bb;
procedure Node021c;
procedure Node021ca;
procedure Node021cb;
procedure Node021cc;
procedure Node021d;
procedure Node021da;
procedure Node022;
procedure node023;
procedure node024;
procedure node025;
procedure node026;
procedure node027;
procedure node028;
procedure node029;
procedure node030;
procedure node031;
procedure node032;
procedure node033;
procedure node034;
procedure node035;
procedure node036;
procedure node037;
procedure node038;
procedure node039;
procedure node040;
procedure node041;
procedure node042;
procedure node043;
procedure node044;
procedure node045;
procedure node046;
procedure node047;
procedure node048;
procedure node049;
procedure update_other_trunk;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


#define dude_has_motorcycle                         (global_var(GVAR_PLAYER_GOT_MOTORCYCLE))
#define dude_has_dune_buggy                         (global_var(GVAR_PLAYER_GOT_DUNE_BUGGY))
#define dude_has_cop_car                         (global_var(GVAR_PLAYER_GOT_COP_CAR))
#define dude_has_semi_truck                         (global_var(GVAR_PLAYER_GOT_SEMI_TRUCK))
#define dude_has_train                         (global_var(GVAR_PLAYER_GOT_TRAIN))
#define dude_has_car                         (global_var(GVAR_PLAYER_GOT_HIGHWAYMAN))
#define dude_has_bicycle                         (global_var(GVAR_PLAYER_GOT_BICYCLE))
#define dude_has_vehicle                        (dude_has_motorcycle or dude_has_dune_buggy or dude_has_cop_car or dude_has_semi_truck or dude_has_train or dude_has_car or dude_has_bicycle)
#define vehicle_blower								(get_sfall_global_int("car_blow") == 1)
#define vehicle_nrupgrade							(get_sfall_global_int("car_nrup") == 1)	
#define vehicle_super								(get_sfall_global_int("car_nrsu") == 1)
//#define vehicle_cargo_one							(car_carry_amount == 300)
//#define vehicle_cargo_two							(car_carry_amount == 350)
//#define vehicle_cargo_three						(car_carry_amount == 350)
//#define vehicle_cargo_super						(car_carry_amount == 475)
//#define vehicle_cargo_one							(car_carry_amount == 300)
//#define vehicle_cargo_two							(car_carry_amount == 420)
//#define vehicle_cargo_three						(car_carry_amount == 672)
//#define vehicle_cargo_super						(car_carry_amount >= 1276)

#define vehicle_fuelup								(global_var(GVAR_CAR_UPGRADE_FUEL_CELL_REGULATOR) == 1)
#define vehicle_cargo_initial						250
#define vehicle_cargo_first_breakpoint				300
#define vehicle_cargo_second_breakpoint				350
#define vehicle_cargo_third_breakpoint				400
#define vehicle_cargo_last_breakpoint				475
// #define vehicle_cargo_first_breakpoint				300
// #define vehicle_cargo_second_breakpoint				420
// #define vehicle_cargo_third_breakpoint				672
// #define vehicle_cargo_last_breakpoint				1276

/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Gave_Work               (8)
#define LVAR_Completed_Work			(9)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

procedure update_other_trunk begin
	variable cop_car_storage := get_proto_data(PID_COP_CAR_TRUNK,36);
	variable dune_buggy_storage := get_proto_data(PID_DUNE_BUGGY_TRUNK,36);
	variable semi_truck_storage := get_proto_data(PID_SEMI_TRUCK_TRUNK,36);
	if (cop_car_storage < car_carry_amount) then
		set_proto_data(PID_COP_CAR_TRUNK, 36, car_carry_amount);
	if (dune_buggy_storage < car_carry_amount) then
		set_proto_data(PID_DUNE_BUGGY_TRUNK, 36, car_carry_amount);
	if (semi_truck_storage < car_carry_amount) then
		set_proto_data(PID_SEMI_TRUCK_TRUNK, 36, car_carry_amount);
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_BROTHERHOOD_OF_STEEL);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);

add_timer_event(self_obj,game_ticks(random(3, 5)),0);
call new_plague_check(self_obj, LVAR_Herebefore);


end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */
   if(global_var(GVAR_BROTHERHOOD_KLAXON) == 1) then
      set_local_var(LVAR_Hostile,2);

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_INTOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;
   start_gdialog(NAME,self_obj,4,HEAD_ED_WHATLEY,BACKGROUND_BHOOD);
   gSay_Start;


   if (local_var(LVAR_Herebefore)==1) then
       call Node011;
 else
       call Node001;

       gSay_End;
       end_dialogue;


   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin

   add_timer_event(self_obj,game_ticks(random(3, 5)),0);

   if (random(0, 30) == 1 and not(combat_is_initialized) and ((critter_state(self_obj) bwand DAM_KNOCKED_OUT) == FALSE) and self_elevation == dude_elevation) then begin
      floater_rand(105, 128);
  end

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
   set_map_var(MVAR_KNOW_ED, 1);
Reply(200);
NOption(201,Node002,4);
NOption(mstr(202)+dude_name+mstr(203),Node007,4);
NOption(204,Node009,4);
if(global_var(GVAR_QUEST_CURE_COMMANDER) == 1) then
NOption(207,Node012,4);
NOption(205,Node999,4);
NOption(206,Node999,-3);
end

procedure Node002
begin
Reply(230);
NOption(231,Node003,4);
NOption(232,Node011,4);
NOption(233,Node999,4);
end

procedure Node003
begin
Reply(260);
NOption(261,Node004,4);
NOption(262,Node999,4);
end

procedure Node004
begin
Reply(290);
NOption(291,Node005,4);
end

procedure Node005
begin
Reply(320);
NOption(321,Node006,4);
NOption(322,Node999,4);
end

procedure Node006
begin
Reply(350);
NOption(351,Node999,4);
NOption(352,Node011,4);
end

procedure Node007
begin
Reply(380);
NOption(381,Node008,4);
NOption(382,Node999,4);
end

procedure Node008
begin

if(global_var(GVAR_QUEST_REPAIR_BROKEN_FORKLIFT) == 0) then
set_global_var(GVAR_QUEST_REPAIR_BROKEN_FORKLIFT, 1);
if(global_var(GVAR_QUEST_REPAIR_BROKEN_VENTS) == 0) then
set_global_var(GVAR_QUEST_REPAIR_BROKEN_VENTS, 1);
if(global_var(GVAR_QUEST_REPAIR_BROKEN_COMPUTER) == 0) then
set_global_var(GVAR_QUEST_REPAIR_BROKEN_COMPUTER, 1);
if(global_var(GVAR_QUEST_REPAIR_BROKEN_MEMORY_BANKS) == 0) then
set_global_var(GVAR_QUEST_REPAIR_BROKEN_MEMORY_BANKS, 1);
if(global_var(GVAR_QUEST_REPAIR_WATER_CHIP) == 0) then
set_global_var(GVAR_QUEST_REPAIR_WATER_CHIP, 1);

set_global_var(GVAR_MAXSON_BUNKER_L2_ACCESS, 1);
set_local_var(LVAR_Gave_Work, 1) ;


Reply(410);
NOption(411,Node999,4);
end

procedure Node009
begin
Reply(440);
NOption(441,Node010,4);
if(dude_has_ncr_connection) then
BOption(442,Node998,4);
NOption(443,Node011,4);
NOption(444,Node999,4);
end

procedure Node010
begin
Reply(470);
NOption(471,Node999,4);
NOption(472,Node011,4);
end

procedure Node011
begin
Reply(500);

if (
   (global_var(GVAR_QUEST_REPAIR_BROKEN_FORKLIFT) == 2) and
   (global_var(GVAR_QUEST_REPAIR_BROKEN_VENTS) == 2) and
   (global_var(GVAR_QUEST_REPAIR_BROKEN_COMPUTER) == 2) and
   (global_var(GVAR_QUEST_REPAIR_BROKEN_MEMORY_BANKS) == 2) and
   (global_var(GVAR_QUEST_REPAIR_WATER_CHIP) == 2) and
   (local_var(LVAR_Completed_Work) < 99)
) then
NOption(504,Node013,4);
if (local_var(LVAR_Completed_Work) == 99) then begin
	NOption(690,node024,4); //upgrade intelligent
	NOption(691,node023,-3); //upgrades stupid
	if ((dude_has_vehicle) and (vehicle_super == 0)) then
		NOption(1003,Node020,4);
		
	if	(dude_has_vehicle) and
		(car_gas_amount < 80000) and
		(dude_caps >= 1000) 
	then
	NOption(1030,Node022,4);
	
end
// debug("car blower: "+vehicle_blower)
// debug("car nrupgrade: "+vehicle_nrupgrade)
// debug("car cargo one: "+vehicle_cargo_one)
// debug("car cargo two: "+vehicle_cargo_two)
// debug("car cargo three: "+vehicle_cargo_three)
// debug("car fuelup: "+vehicle_fuelup)
// debug("car super: "+vehicle_super)
// debug("car cargo super: "+vehicle_cargo_super)
// debug("car carry amount: "+car_carry_amount)
	
NOption(501,Node002,4);
if(local_var(LVAR_Gave_Work) == 0) then
NOption(502,Node007,4);
NOption(204,Node009,4);
if(global_var(GVAR_QUEST_CURE_COMMANDER) == 1) then
NOption(207,Node012,4);
NOption(205,Node999,4);
NOption(503,Node999,-3);
end


procedure Node012
begin
Reply(530);
NOption(233,Node999,4);
NOption(232,Node011,4);
end

procedure Node013
begin
   if(dude_is_male) then
Reply(560);
else
Reply(561);
if (local_var(LVAR_Completed_Work) < 99) then
	set_local_var(LVAR_Completed_Work,99);

NOption(562,Node999,4);
NOption(563,Node014,4);
end

procedure Node014
begin
   if(dude_is_male) then
Reply(590);
else
Reply(591);

NOption(592,Node999,4);
NOption(593,Node011,4);
end

//Car upgrades from Dianne

//Brotherhood Flags
//Filtration device ==> GVAR_QUEST_CURE_COMMANDER == 3
//GVAR_QUEST_MEET_DODGE ==> GVAR_QUEST_FIND_POISONER == 3
//GVAR_QUEST_HOOVER_PEACE ==> GVAR_BROTHERHOOD_SENIOR == 1

procedure Node020 //Fluff into Mechanics upgrades
begin
	Reply(850);	
	NOption(851,Node021,4);
end

procedure Node021 //Mechanic Upgrades List
begin
	Reply(852);
	if (vehicle_fuelup == 0) then
		NOption(853,Node021a,4);
	if (vehicle_blower == 0) or (vehicle_nrupgrade == 0)  then		
		NOption(854,Node021b,4);
	if (car_carry_amount < vehicle_cargo_third_breakpoint) then		
		NOption(855,Node021c,4);
	if 
	   (global_var(GVAR_BROTHERHOOD_SENIOR) == 1) and 
	   (car_carry_amount == vehicle_cargo_third_breakpoint) and 
	   (vehicle_super == 0) and 
	   (vehicle_blower == 1) and 
	   (vehicle_nrupgrade == 1) and 
	   (vehicle_fuelup == 1)
	then begin
		NOption(856,Node021d,4);
	end
	NOption(857,Node011,4);
end

procedure Node021a //Efficiency
begin
	Reply(880);
	if (vehicle_fuelup == 0) 
		//and (dude_caps >= 4000) 
	then begin
		NOption(881,Node021aa,4);
	end	
	NOption(882,Node021,4);
end

procedure Node021aa //Efficiency
begin
	if (vehicle_fuelup == 0) 
		//and (dude_caps >= 4000) 
	then begin
		//item_caps_adjust(dude_obj,-4000);
		//set_local_var(LVAR_Fuel_Cell_Regulator,99);
		set_global_var(GVAR_CAR_UPGRADE_FUEL_CELL_REGULATOR,1);
		NOption(925,Node999,4);
	end
end


procedure Node021b //Speed
begin
	Reply(920);
	if (vehicle_blower == 0) 
		//and (dude_caps >= 8000) 
		and (global_var(GVAR_QUEST_CURE_COMMANDER) == 3) 
	then begin
		NOption(921,Node021ba,4);
	end
	if (vehicle_nrupgrade == 0) and 
	   (vehicle_blower == 1) and 
	   //(dude_caps >= 12000) and 
	   (global_var(GVAR_QUEST_FIND_POISONER) == 3) 
	then begin
		NOption(922,Node021bb,4);
	end	
	if ((vehicle_blower == 1) and (global_var(GVAR_QUEST_FIND_POISONER) < 3)) or (global_var(GVAR_QUEST_CURE_COMMANDER) < 3) then begin
		NOption(924,Node021,4);
	end
	else begin
		NOption(923,Node021,4);	
	end
end

procedure Node021ba //Speed 1
begin
	if (vehicle_blower == 0) and 
	   //(dude_caps >= 8000) and 
	   (global_var(GVAR_QUEST_CURE_COMMANDER) == 3) 
	then begin
		//item_caps_adjust(dude_obj,-8000);
		//set_local_var(LVAR_Car_Blower,99);
		set_global_var(GVAR_CAR_BLOWER,1);
		set_sfall_global("car_blow",1);
		NOption(925,Node999,4);
	end
end

procedure Node021bb //Speed 2
begin
	if (vehicle_nrupgrade == 0) and 
	   (vehicle_blower == 1)  and 
	   //(dude_caps >= 12000) and 
	   (global_var(GVAR_QUEST_FIND_POISONER) == 3) 
	then begin
		//item_caps_adjust(dude_obj,-12000);
		//set_local_var(LVAR_NR_Car_Upgrade,99);
		set_global_var(GVAR_NEW_RENO_CAR_UPGRADE,1);
		set_sfall_global("car_nrup",1);
		NOption(925,Node999,4);
	end
end

procedure Node021c //Cargo
begin
	Reply(960);
	if (car_carry_amount == vehicle_cargo_initial) 
		//and (dude_caps >= 6000) 
	then begin
		NOption(961,Node021ca,4);
	end
	if (car_carry_amount == vehicle_cargo_first_breakpoint) and 
	   (global_var(GVAR_QUEST_CURE_COMMANDER) == 3) 
	   //and (dude_caps >= 8000)) 
	then begin
		NOption(962,Node021cb,4);
	end	
	if (car_carry_amount == vehicle_cargo_second_breakpoint) and 
	   (global_var(GVAR_QUEST_FIND_POISONER) == 3) 
	   //and (dude_caps >= 12000)) 
	then begin
		NOption(963,Node021cc,4);
	end		
	NOption(964,Node021,4);	
end

procedure Node021ca //Cargo 1 
begin
	//item_caps_adjust(dude_obj,-6000);
	//set_local_var(LVAR_Cargo_Upgrades,10);
	//set_car_carry_amount((120*car_carry_amount) / 100); //should have just been set_car_carry_amount(300)
	set_car_carry_amount(vehicle_cargo_first_breakpoint);
	call update_other_trunk;
	NOption(925,Node999,4);
end

procedure Node021cb //Cargo 2
begin
	//item_caps_adjust(dude_obj,-8000);
	//set_local_var(LVAR_Cargo_Upgrades,20);
	//set_car_carry_amount((140*car_carry_amount) / 100); //should have just been set_car_carry_amount(350)
	set_car_carry_amount(vehicle_cargo_second_breakpoint);
	call update_other_trunk;
	NOption(925,Node999,4);
end

procedure Node021cc //Cargo 3
begin
	//item_caps_adjust(dude_obj,-12000);
	//set_local_var(LVAR_Cargo_Upgrades,30);
	//set_car_carry_amount((160*car_carry_amount) / 100); //should have just been set_car_carry_amount(400)
	set_car_carry_amount(vehicle_cargo_third_breakpoint);
	call update_other_trunk;
	NOption(925,Node999,4);
end


procedure Node021d //Super Car
begin
	Reply(1000);	
	if (vehicle_super == 0) 
		//and (dude_caps >= 20000) 
	then begin
		NOption(1001,Node021da,4);
	end
	NOption(1002,Node021,4);	
end

procedure Node021da //Super Car
begin
	//item_caps_adjust(dude_obj,-20000);
	//set_local_var(LVAR_NR_Super_Car,99);
	//set_local_var(LVAR_Cargo_Upgrades,99);
	//set_car_carry_amount((190*car_carry_amount) / 100); //congruent with fallout 2 post oil rig mag/grav plates // currently not congruent should have just been set_car_carry_amount(475)
	set_car_carry_amount(vehicle_cargo_last_breakpoint);
	call update_other_trunk;
	set_global_var(GVAR_NEW_RENO_SUPER_CAR,1);		
	set_sfall_global("car_nrsu",1);
	NOption(925,Node999,4);
end


procedure Node022
begin
	variable pct_gas := ((car_gas_amount / 800));
	Reply("Ah it looks like your vehicle only has "+pct_gas+"% left, i'm gonna assign one of our initiates to refuel your vehicle...");
	variable refuelamount := (80000 - car_gas_amount);
	item_caps_adjust(dude_obj,-1000);
	car_give_gas(refuelamount);
	NOption(1031,Node001,4);
end

//Upgrades from Otto

procedure node023 //upgrade if stupid
begin

if (dude_item(PID_PLASMA_RIFLE)) then
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_PLASMA_RIFLE, 1)
give_pid_qty(dude_obj,PID_TURBO_PLASMA_RIFLE , 1)
Reply(750);
end
else
if dude_item(PID_LASER_RIFLE) then
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_LASER_RIFLE, 1)
give_pid_qty(dude_obj,PID_LASER_RIFLE_EXT_CAP, 1)
Reply(749);
end
else
if dude_item(PID_HUNTING_RIFLE) then
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_HUNTING_RIFLE, 1)
give_pid_qty(dude_obj,PID_SCOPED_HUNTING_RIFLE, 1)
Reply(743);
end
else
if dude_item(PID_FN_FAL) then
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_FN_FAL, 1)
give_pid_qty(dude_obj,PID_FN_FAL_NIGHT_SCOPE, 1)
Reply(744);
end
else
if dude_item(PID_ASSAULT_RIFLE) then
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_ASSAULT_RIFLE, 1)
give_pid_qty(dude_obj,PID_ASSAULT_RIFLE_EXT_MAG, 1)
Reply(745);
end
else
if dude_item(PID_DESERT_EAGLE) then
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_DESERT_EAGLE, 1)
give_pid_qty(dude_obj,PID_DESERT_EAGLE_EXT_MAG, 1)
Reply(741);
end
else
if dude_item(PID_44_MAGNUM_REVOLVER) then
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_44_MAGNUM_REVOLVER, 1)
give_pid_qty(dude_obj,PID_44_MAGNUM_SPEEDLOADER, 1)
Reply(742);
end
else
if dude_item(PID_LASER_PISTOL) then
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_LASER_PISTOL, 1)
give_pid_qty(dude_obj,PID_MAGNETO_LASER_PISTOL, 1)
Reply(747);
end
else
if dude_item(PID_PLASMA_PISTOL) then
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_PLASMA_PISTOL, 1)
give_pid_qty(dude_obj,PID_PLASMA_PISTOL_EXT_CART, 1)
Reply(748);
end
else
if dude_item(PID_METAL_ARMOR)then
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_METAL_ARMOR, 1)
give_pid_qty(dude_obj, PID_METAL_ARMOR_MK_II, 1)
Reply(736);
end
else
if dude_item(PID_COMBAT_ARMOR)then
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_COMBAT_ARMOR, 1)
give_pid_qty(dude_obj, PID_COMBAT_ARMOR_MK_II, 1)
Reply(737);
end
else
if dude_item(PID_SPEAR)then
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_SPEAR, 1)
give_pid_qty(dude_obj, PID_SHARP_SPEAR, 1)
Reply(738);
end
else
if dude_item(PID_CATTLE_PROD)then
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_CATTLE_PROD, 1)
give_pid_qty(dude_obj, PID_SUPER_CATTLE_PROD, 1)
Reply(740);
end
else
if dude_item(PID_POWER_FIST)then
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_POWER_FIST, 1)
give_pid_qty(dude_obj, PID_MEGA_POWER_FIST, 1)
Reply(739);
end
else
if dude_item(PID_FLAMER)then
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_FLAMER, 1)
give_pid_qty(dude_obj, PID_IMPROVED_FLAMETHROWER, 1)
Reply(746);
end
else
Reply(752);

NOption(751,node999,-3);

end



procedure node024
begin
Reply(622);
NOption(623,node025,4);
NOption(624,node026,4);
NOption(625,node027,4);
NOption(626,node028,4);
NOption(627,node029,4);
NOption(628,node999,4);

end

procedure node025
begin
Reply(629);
if dude_item(PID_ASSAULT_RIFLE) then
NOption(630,node030,4);
if dude_item(PID_FN_FAL) then
NOption(631,node031,4);
if dude_item(PID_HUNTING_RIFLE) then
NOption(632,node032,4);
if dude_item(PID_LASER_RIFLE) then
NOption(633,node033,4);
if dude_item(PID_PLASMA_RIFLE) then
NOption(634,node034,4);
if dude_item(PID_SHOTGUN) then
NOption(635,node035,4);
NOption(613,node999,4);

end

procedure node026
begin
Reply(636);
if dude_item(PID_DESERT_EAGLE) then
NOption(637,node039,4);
if dude_item(PID_44_MAGNUM_REVOLVER) then
NOption(638,node040,4);
if dude_item(PID_LASER_PISTOL) then
NOption(639,node041,4);
if dude_item(PID_PLASMA_PISTOL) then
NOption(640,node042,4);
NOption(613,node999,4);

end

procedure node027
begin
Reply(641);
if dude_item(PID_METAL_ARMOR)then
NOption(642,node043,4);
if dude_item(PID_COMBAT_ARMOR)then
NOption(643,node044,4);
if dude_item(PID_POWERED_ARMOR)then
NOption(644,node045,4);
NOption(613,node999,4);

end

procedure node028
begin
Reply(645);
if dude_item(PID_SPEAR)then
NOption(646,node046,4);
if dude_item(PID_CATTLE_PROD)then
NOption(647,node047,4);
if dude_item(PID_POWER_FIST)then
NOption(648,node048,4);
NOption(613,node999,4);

end

procedure node029
begin
Reply(649);
if dude_item(PID_FLAMER)then
NOption(650,node049,4);
NOption(613,node999,4);

end


procedure node030
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_ASSAULT_RIFLE, 1)
give_pid_qty(dude_obj,PID_ASSAULT_RIFLE_EXT_MAG, 1)
Reply(651);
NOption(652,node024,4);

end

procedure node031
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_FN_FAL, 1)
give_pid_qty(dude_obj,PID_FN_FAL_NIGHT_SCOPE, 1)
Reply(653);
NOption(654,node024,4);

end

procedure node032
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_HUNTING_RIFLE, 1)
give_pid_qty(dude_obj,PID_SCOPED_HUNTING_RIFLE, 1)
Reply(655);
NOption(656,node024,4);

end

procedure node033
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_LASER_RIFLE, 1)
give_pid_qty(dude_obj,PID_LASER_RIFLE_EXT_CAP, 1)
Reply(657);
NOption(658,node024,4);

end

procedure node034
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_PLASMA_RIFLE, 1)
give_pid_qty(dude_obj,PID_TURBO_PLASMA_RIFLE , 1)
Reply(659);
NOption(660,node024,4);

end

procedure node035
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_SHOTGUN, 1)
give_pid_qty(dude_obj,PID_SAWED_OFF_SHOTGUN , 1)
Reply(661);
NOption(662,node024,4);

end

procedure node036
begin
Reply(684);
NOption(685,node024,4);
NOption(686,node999,4);
if (dude_item_count(PID_CHEMISTRY_MANUAL))and(dude_item_count(PID_TECHNICAL_MANUAL))then
NOption(689,node037,4);
NOption(690,node038,4);

end

procedure node037
begin
remove_armor(dude_obj)
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_POWERED_ARMOR, 1)
give_pid_qty(dude_obj, PID_HARDENED_POWER_ARMOR, 1)
Reply(692);
NOption(693,node999,4);

end

procedure node038
begin
Reply(691);
NOption(686,node999,4);

end

procedure node039
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_DESERT_EAGLE, 1)
give_pid_qty(dude_obj,PID_DESERT_EAGLE_EXT_MAG, 1)
Reply(663);
NOption(664,node024,4);

end

procedure node040
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_44_MAGNUM_REVOLVER, 1)
give_pid_qty(dude_obj,PID_44_MAGNUM_SPEEDLOADER, 1)
Reply(665);
NOption(666,node024,4);

end

procedure node041
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_LASER_PISTOL, 1)
give_pid_qty(dude_obj,PID_MAGNETO_LASER_PISTOL, 1)
Reply(667);
NOption(668,node024,4);

end

procedure node042
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_PLASMA_PISTOL, 1)
give_pid_qty(dude_obj,PID_PLASMA_PISTOL_EXT_CART, 1)
Reply(657);
NOption(658,node024,4);

end


procedure node043
begin
remove_armor(dude_obj)
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_METAL_ARMOR, 1)
give_pid_qty(dude_obj, PID_METAL_ARMOR_MK_II, 1)
Reply(669);
NOption(670,node024,4);

end

procedure node044
begin
remove_armor(dude_obj)
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_COMBAT_ARMOR, 1)
give_pid_qty(dude_obj, PID_COMBAT_ARMOR_MK_II, 1)
Reply(671);
NOption(672,node024,4);

end

procedure node045
begin
Reply(681);
NOption(682,node036,4);
NOption(683,node024,4);

end

procedure node046
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_SPEAR, 1)
give_pid_qty(dude_obj, PID_SHARP_SPEAR, 1)
Reply(673);
NOption(674,node024,4);

end

procedure node047
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_CATTLE_PROD, 1)
give_pid_qty(dude_obj, PID_SUPER_CATTLE_PROD, 1)
Reply(675);
NOption(676,node024,4);

end

procedure node048
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_POWER_FIST, 1)
give_pid_qty(dude_obj, PID_MEGA_POWER_FIST, 1)
Reply(677);
NOption(678,node024,4);

end

procedure node049
begin
inven_unwield(dude_obj);
remove_pid_qty(dude_obj,PID_FLAMER, 1)
give_pid_qty(dude_obj, PID_IMPROVED_FLAMETHROWER, 1)
Reply(679);
NOption(680,node024,4);

end

//xxxxxxxxxxxxxxxxxxxx
