# Skill names for messages
{1}{}{Small Guns}
{2}{}{Big Guns}
{3}{}{Energy Weapons}
{4}{}{Unarmed}
{5}{}{Melee Weapons}
{6}{}{Throwing}
{7}{}{First Aid}
{8}{}{Doctor}
{9}{}{Sneak}
{10}{}{Lockpick}
{11}{}{Steal}
{12}{}{Traps}
{13}{}{Science}
{14}{}{Repair}
{15}{}{Speech}
{16}{}{Barter}
{17}{}{Gambling}
{18}{}{Outdoorsman}
# Skill names for defines
{19}{}{SKILL_SMALL_GUNS}
{20}{}{SKILL_BIG_GUNS}
{21}{}{SKILL_ENERGY_WEAPONS}
{22}{}{SKILL_UNARMED}
{23}{}{SKILL_MELEE_WEAPONS}
{24}{}{SKILL_THROWING}
{25}{}{SKILL_FIRST_AID}
{26}{}{SKILL_DOCTOR}
{27}{}{SKILL_SNEAK}
{28}{}{SKILL_LOCKPICK}
{29}{}{SKILL_STEAL}
{30}{}{SKILL_TRAPS}
{31}{}{SKILL_SCIENCE}
{32}{}{SKILL_REPAIR}
{33}{}{SKILL_SPEECH}
{34}{}{SKILL_BARTER}
{35}{}{SKILL_GAMBLING}
{36}{}{SKILL_OUTDOORSMAN}

# messages

{100}{}{[OK]}
{101}{}{[EXIT]}
{102}{}{[BACK]}
{103}{}{[CRAFT]}
{104}{}{[DISMANTLE]}
{105}{}{[MORE]}
{106}{}{[BACK]}
{107}{}{[NO ITEMS]}
{108}{}{[CRAFT ALL]}
{109}{}{[DISMANTLE ALL]}
{110}{}{ (}
{111}{}{ total)}

{150}{}{ or }

{200}{}{Welcome to the official RobCo Lil-Pip 3000 upgrade Mr. Fixit! Querying the database... Loading schematics... Done. Please select from the list of available items for assistance in crafting.}
{201}{}{Item(s) crafted.}
{202}{}{Item(s) dismantled.}
{203}{}{Welcome back, sir.}
{204}{}{Hello, sir.}
{205}{}{Welcome back, madam.}
{206}{}{Hello, madam.}
{207}{}{Good morning, sir.}
{208}{}{Good morning, madam.}
{209}{}{Good evening, sir.}
{210}{}{Good evening, madam.}
{211}{}{Mr. Fixit! upgrade installed and ready to assist.}
{212}{}{Wake up.}
{213}{}{Doo da doo da dum dee dee doodly doo dum dum dum doo da doo da doo da doo da doo da doo da doo}
{214}{}{"The spread of civilization may be likened to a fire; first, a feeble spark, next a flickering flame, then a mighty blaze, ever increasing in speed and power." -Nikola Tesla}
{215}{}{"I can calculate the motion of heavenly bodies, but not the madness of people." -Sir Isaac Newton}
{216}{}{Happy New Year's Day!}      # New years
{217}{}{Happy Valentine's Day!}     # Valentine's Day
{218}{}{Happy All Fool's Day!}      # April fools
{219}{}{Happy Ship Day!}            # Shipping day!
{220}{}{Happy Independence Day!}    # Independence day
{221}{}{Happy Halloween!}           # Halloween
{222}{}{Happy Thanksgiving Day!}    # Thanksgiving
{223}{}{Merry Christmas!}           # X-mas

{300}{}{TOOLS}
{301}{}{SKILLS}
{302}{}{COMPONENTS}
{303}{}{None}
{304}{}{TIME}
{305}{}{Hours: }
{306}{}{Minutes: }
{307}{}{hour}
{308}{}{minute}

{400}{}{Crafted: }
{401}{}{Dismantled: }
{402}{}{ (}
{403}{}{ total). }
{404}{}{ h. }
{405}{}{ m. passed.}

# items for batch

{500}{}{[ITEM]}
{501}{}{280}                               # PID_SHARP_SPEAR
{502}{}{pcx/items/spear2.pcx}
{503}{}{159039}
{504}{}{111}
{505}{}{27000}                             # 45 m
{506}{}{NO}
{507}{}{[TOOLS]}
{508}{}{278}                               # PID_FLINT
{509}{}{[SKILLS]}
{510}{}{SKILL_MELEE_WEAPONS:40}
{511}{}{SKILL_THROWING:40}
{512}{}{[COMPONENTS]}
{513}{}{7:1}                               # PID_SPEAR

{525}{}{[ITEM]}
{526}{}{159}                               # PID_MOLOTOV_COCKTAIL
{527}{}{pcx/items/mola.pcx}
{528}{}{23060}
{529}{}{112}
{530}{}{54000}                             # 1 h 30 m
{531}{}{NO}
{532}{}{[TOOLS]}
{533}{}{75}                                # PID_MULTI_TOOL
{534}{}{[SKILLS]}
{535}{}{SKILL_REPAIR:30}
{536}{}{SKILL_TRAPS:40}
{537}{}{SKILL_THROWING:40}
{538}{}{[COMPONENTS]}
{539}{}{79:2}                              # PID_FLARE
{540}{}{125:1}                             # PID_BOOZE

{550}{}{[ITEM]}
{551}{}{51}                                # PID_DYNAMITE
{552}{}{pcx/items/dynamit.pcx}
{553}{}{94060}
{554}{}{113}
{555}{}{117000}                            # 3 h 15 m
{556}{}{NO}
{557}{}{[TOOLS]}
{558}{}{75}                                # PID_MULTI_TOOL
{559}{}{237}                               # PID_CHEMISTRY_MANUAL
{560}{}{[SKILLS]}
{561}{}{SKILL_REPAIR:60}
{562}{}{SKILL_TRAPS:80}
{563}{}{[COMPONENTS]}
{564}{}{85:1}                              # PID_PLASTIC_EXPLOSIVES
{565}{}{98:1}                              # PID_PUMP_PARTS

{575}{}{[ITEM]}
{576}{}{74}                                # PID_LEATHER_JACKET
{577}{}{pcx/items/maxinv.pcx}
{578}{}{62060}
{579}{}{114}
{580}{}{231000}                            # 6 h 25 m
{581}{}{YES}
{582}{}{[TOOLS]}
{583}{}{4|45|236|714}                          # PID_KNIFE|PID_THROWING_KNIFE|PID_COMBAT_KNIFE|PID_SHARPENED_KNIFE
{584}{}{[SKILLS]}
{585}{}{SKILL_REPAIR:60}
{586}{}{[COMPONENTS]}
{587}{}{127:1}                             # PID_ROPE
{588}{}{276:4}                             # PID_GECKO_PELT

{600}{}{[ITEM]}
{601}{}{1}                                 # PID_LEATHER_ARMOR
{602}{}{pcx/items/ltharmor.pcx}
{603}{}{88055}
{604}{}{115}
{605}{}{243000}                            # 6 h 45 m
{606}{}{YES}
{607}{}{[TOOLS]}
{608}{}{4|45|236|714}                          # PID_KNIFE|PID_THROWING_KNIFE|PID_COMBAT_KNIFE|PID_SHARPENED_KNIFE
{609}{}{[SKILLS]}
{610}{}{SKILL_REPAIR:80}
{611}{}{[COMPONENTS]}
{612}{}{127:1}                             # PID_ROPE
{613}{}{276:6}                             # PID_GECKO_PELT

{625}{}{[ITEM]}
{626}{}{379}                               # PID_LEATHER_ARMOR_MK_II
{627}{}{pcx/items/ltharmr2.pcx}
{628}{}{88055}
{629}{}{116}
{630}{}{291000}                            # 8 h 5 m
{631}{}{YES}
{632}{}{[TOOLS]}
{633}{}{4|45|236|714}                          # PID_KNIFE|PID_THROWING_KNIFE|PID_COMBAT_KNIFE|PID_SHARPENED_KNIFE
{634}{}{[SKILLS]}
{635}{}{SKILL_REPAIR:120}
{636}{}{[COMPONENTS]}
{637}{}{127:1}                             # PID_ROPE
{638}{}{277:6}                             # PID_GOLDEN_GECKO_PELT

{650}{}{[ITEM]}
{651}{}{273}                               # PID_HEALING_POWDER
{652}{}{pcx/items/healpwdr.pcx}
{653}{}{47060}
{654}{}{117}
{655}{}{30000}                             # 50 m
{656}{}{NO}
{657}{}{[TOOLS]}
{658}{}{[SKILLS]}
{659}{}{SKILL_FIRST_AID:60}
{660}{}{SKILL_OUTDOORSMAN:65}
{661}{}{SKILL_SCIENCE:20}
{662}{}{[COMPONENTS]}
{663}{}{271:1}                             # PID_BROC_FLOWER
{664}{}{272:1}                             # PID_XANDER_ROOT

{675}{}{[ITEM]}
{676}{}{49}                                # PID_ANTIDOTE
{677}{}{pcx/items/drug_bot.pcx}
{678}{}{90060}
{679}{}{118}
{680}{}{30000}                             # 50 m
{681}{}{NO}
{682}{}{[TOOLS]}
{683}{}{[SKILLS]}
{684}{}{SKILL_FIRST_AID:60}
{685}{}{SKILL_OUTDOORSMAN:65}
{686}{}{SKILL_SCIENCE:20}
{687}{}{[COMPONENTS]}
{688}{}{92:1}                              # PID_SCORPION_TAIL

{700}{}{[ITEM]}
{701}{}{40}                                # PID_STIMPAK
{702}{}{pcx/items/stimx.pcx}
{703}{}{89060}
{704}{}{119}
{705}{}{51000}                             # 1 h 25 m
{706}{}{NO}
{707}{}{[TOOLS]}
{708}{}{408}                               # PID_FIELD_MEDIC_KIT
{709}{}{[SKILLS]}
{710}{}{SKILL_DOCTOR:60}
{711}{}{[COMPONENTS]}
{712}{}{271:1}                             # PID_BROC_FLOWER
{713}{}{272:1}                             # PID_XANDER_ROOT
{714}{}{318:1}                             # PID_HYPODERMIC_NEEDLE

{725}{}{[ITEM]}
{726}{}{144}                               # PID_SUPER_STIMPAK
{727}{}{pcx/items/stimpak.pcx}
{728}{}{88059}
{729}{}{120}
{730}{}{93000}                             # 2 h 35 m
{731}{}{NO}
{732}{}{[TOOLS]}
{733}{}{408}                               # PID_FIELD_MEDIC_KIT
{734}{}{[SKILLS]}
{735}{}{SKILL_DOCTOR:80}
{736}{}{[COMPONENTS]}
{737}{}{71:1}                              # PID_MUTATED_FRUIT
{738}{}{106:1}                             # PID_NUKA_COLA
{739}{}{40:1}                              # PID_STIMPAK

{750}{}{[ITEM]}
{751}{}{110}                               # PID_PSYCHO
{752}{}{pcx/items/lastdrug.pcx}
{753}{}{77060}
{754}{}{121}
{755}{}{360000}                            # 10 h
{756}{}{NO}
{757}{}{[TOOLS]}
{758}{}{408}                               # PID_FIELD_MEDIC_KIT
{759}{}{[SKILLS]}
{760}{}{SKILL_DOCTOR:100}
{761}{}{[COMPONENTS]}
{762}{}{53:1}                              # PID_MENTATS
{763}{}{87:1}                              # PID_BUFFOUT
{764}{}{71:2}                              # PID_MUTATED_FRUIT
{765}{}{125:1}                             # PID_BOOZE
{766}{}{144:1}                             # PID_SUPER_STIMPAK

{775}{}{[ITEM]}
{776}{}{77}                                # PID_ELECTRONIC_LOCKPICKS
{777}{}{pcx/items/elecpic.pcx}
{778}{}{91060}
{779}{}{122}
{780}{}{450000}                            # 12 h 30 m
{781}{}{NO}
{782}{}{[TOOLS]}
{783}{}{228}                               # PID_TECHNICAL_MANUAL
{784}{}{75}                                # PID_MULTI_TOOL
{785}{}{[SKILLS]}
{786}{}{SKILL_REPAIR:60}
{787}{}{SKILL_SCIENCE:60}
{788}{}{SKILL_LOCKPICK:40}
{789}{}{[COMPONENTS]}
{790}{}{59:1}                              # PID_MOTION_SENSOR
{791}{}{52:1}                              # PID_GEIGER_COUNTER

{800}{}{[ITEM]}
{801}{}{411}                               # PID_ELEC_LOCKPICK_MKII
{802}{}{pcx/items/elockpk2.pcx}
{803}{}{86056}
{804}{}{123}
{805}{}{324000}                            # 9 h
{806}{}{NO}
{807}{}{[TOOLS]}
{808}{}{228}                               # PID_TECHNICAL_MANUAL
{809}{}{308}                               # PID_SUPER_TOOL_KIT
{810}{}{[SKILLS]}
{811}{}{SKILL_REPAIR:100}
{812}{}{SKILL_SCIENCE:100}
{813}{}{SKILL_LOCKPICK:80}
{814}{}{[COMPONENTS]}
{815}{}{77:1}                              # PID_ELECTRONIC_LOCKPICKS

{825}{}{[ITEM]}
{826}{}{626}                               # WOOD PLANKS
{827}{}{pcx/items/woodplnr.pcx}
{828}{}{64050}
{829}{}{166}
{830}{}{18000}                            # 30 min
{831}{}{YES}
{832}{}{[TOOLS]}
{833}{}{[SKILLS]}
{834}{}{SKILL_REPAIR:30}
{835}{}{[COMPONENTS]}
{836}{}{625:1}                              # WOOD PLANKS
{837}{}{127:1}                              # ROPE

{850}{}{[ITEM]}
{851}{}{621}                               # PID_GREATER_HEALING_POWDER
{852}{}{pcx/items/grheal.pcx}
{853}{}{48049}
{854}{}{157}
{855}{}{30000}                             # 50 m
{856}{}{NO}
{857}{}{[TOOLS]}
{858}{}{[SKILLS]}
{859}{}{SKILL_FIRST_AID:60}
{860}{}{SKILL_OUTDOORSMAN:65}
{861}{}{SKILL_SCIENCE:20}
{862}{}{[COMPONENTS]}
{863}{}{271:1}                             # PID_BROC_FLOWER
{864}{}{272:1}                             # PID_XANDER_ROOT
{865}{}{624:2}                             # DARKA

{875}{}{[ITEM]}
{876}{}{641}                               # PID_RAT_TAIL_LUCKY_CHARM
{877}{}{pcx/items/ratcharm.pcx}
{878}{}{55029}
{879}{}{186}
{880}{}{12000}                             # 20 m
{881}{}{NO}
{882}{}{[TOOLS]}
{883}{}{[SKILLS]}
{884}{}{SKILL_OUTDOORSMAN:50}
{885}{}{[COMPONENTS]}
{886}{}{632:4}                             # PID_RAT_TAIL

{900}{}{[ITEM]}
{901}{}{16}                                # PID_LASER_PISTOL
{902}{}{pcx/items/LASERGUN.pcx}
{903}{}{75060}
{904}{}{188}
{905}{}{360000}                            # 10h
{906}{}{NO}
{907}{}{[TOOLS]}
{908}{}{75}                                # PID_MULTI_TOOL
{909}{}{[SKILLS]}
{910}{}{SKILL_SCIENCE:75}
{911}{}{[COMPONENTS]}
{912}{}{8:1}                               # PID_10MM_PISTOL
{913}{}{119:1}                             # PID_NECKLACE

{925}{}{[ITEM]}
{926}{}{644}                               # PID_POISONED_STIMPAK
{927}{}{pcx/items/STIMX.pcx}
{928}{}{89060}
{929}{}{190}
{930}{}{36000}                             # 1h
{931}{}{NO}
{932}{}{[TOOLS]}
{933}{}{[SKILLS]}
{934}{}{SKILL_DOCTOR:60}
{935}{}{SKILL_OUTDOORSMAN:30}
{936}{}{SKILL_SCIENCE:20}
{937}{}{[COMPONENTS]}
{938}{}{40:1}                             # PID_STIMPAK
{939}{}{92:1}                             # PID_SCORPION_TAIL

{950}{}{[ITEM]}
{951}{}{645}                              # PID_POISONED_SUPER_STIMPAK
{952}{}{pcx/items/STIMPAK.pcx}
{953}{}{88059}
{954}{}{191}
{955}{}{36000}                            # 1h
{956}{}{NO}
{957}{}{[TOOLS]}
{958}{}{[SKILLS]}
{959}{}{SKILL_DOCTOR:80}
{960}{}{SKILL_OUTDOORSMAN:60}
{961}{}{SKILL_SCIENCE:40}
{962}{}{[COMPONENTS]}
{963}{}{144:1}                             # PID_SUPER_STIMPAK
{964}{}{92:1}                              # PID_SCORPION_TAIL

{975}{}{[ITEM]}
{976}{}{402}                               # PID_MAGNETO_LASER_PISTOL
{977}{}{pcx/items/MLASPIST.pcx}
{978}{}{75060}
{979}{}{312}
{980}{}{360000}                            # 10h
{981}{}{NO}
{982}{}{[TOOLS]}
{983}{}{73}                                # PID_BIG_BOOK_OF_SCIENCE
{984}{}{308}                               # PID_SUPER_TOOL_KIT
{985}{}{[SKILLS]}
{986}{}{SKILL_ENERGY_WEAPONS:80}
{987}{}{SKILL_REPAIR:60}
{988}{}{SKILL_SCIENCE:40}
{989}{}{[COMPONENTS]}
{990}{}{16:1}                              # PID_LASER_PISTOL
{991}{}{100:2}                             # PID_RADIO

{1000}{}{[ITEM]}
{1001}{}{401}                               # PID_LASER_RIFLE_EXT_CAP
{1002}{}{pcx/items/LRIFLE2.pcx}
{1003}{}{184062}
{1004}{}{313}
{1005}{}{504000}                            # 14h
{1006}{}{NO}
{1007}{}{[TOOLS]}
{1008}{}{102}                               # PID_GUNS_AND_BULLETS
{1009}{}{308}                               # PID_SUPER_TOOL_KIT
{1010}{}{[SKILLS]}
{1011}{}{SKILL_ENERGY_WEAPONS:100}
{1012}{}{SKILL_REPAIR:80}
{1013}{}{SKILL_SCIENCE:60}
{1014}{}{[COMPONENTS]}
{1015}{}{118:1}                             # PID_LASER_RIFLE
{1016}{}{55:1}                              # PID_WATER_CHIP

{1025}{}{[ITEM]}
{1026}{}{406}                               # PID_PLASMA_PISTOL_EXT_CART
{1027}{}{pcx/items/plaspst2.pcx}
{1028}{}{66058}
{1029}{}{314}
{1030}{}{360000}                            # 10h
{1031}{}{NO}
{1032}{}{[TOOLS]}
{1033}{}{102}                               # PID_GUNS_AND_BULLETS
{1034}{}{308}                               # PID_SUPER_TOOL_KIT
{1035}{}{[SKILLS]}
{1036}{}{SKILL_ENERGY_WEAPONS:80}
{1037}{}{SKILL_REPAIR:60}
{1038}{}{SKILL_SCIENCE:40}
{1039}{}{[COMPONENTS]}
{1040}{}{24:1}                              # PID_PLASMA_PISTOL

{1050}{}{[ITEM]}
{1051}{}{353}                               # PID_INDEPENDENT XL70E3
{1052}{}{pcx/items/INDWEAP.pcx}
{1053}{}{144056}
{1054}{}{315}
{1055}{}{6048000}                            # 1 week
{1056}{}{NO}
{1057}{}{[TOOLS]}
{1058}{}{102}                               # PID_GUNS_AND_BULLETS
{1059}{}{308}                               # PID_SUPER_TOOL_KIT
{1060}{}{[SKILLS]}
{1061}{}{SKILL_SMALL_GUNS:80}
{1062}{}{SKILL_REPAIR:60}
{1063}{}{[COMPONENTS]}
{1064}{}{23:1}                              # PID_ASSAULT_RIFLE
{1065}{}{98:2}                              # PID_JUNK

{1075}{}{[ITEM]}
{1076}{}{240}                               # PID_TESLA_ARMOR
{1077}{}{pcx/items/TESLA.pcx}
{1078}{}{79063}
{1079}{}{316}
{1080}{}{6048000}                           # 1 week
{1081}{}{NO}
{1082}{}{[TOOLS]}
{1083}{}{73}                                # PID_BIG_BOOK_OF_SCIENCE
{1084}{}{76}                                # PID_DEANS_ELECTRONICS
{1085}{}{308}                               # PID_SUPER_TOOL_KIT
{1086}{}{[SKILLS]}
{1087}{}{SKILL_REPAIR:75}
{1088}{}{SKILL_SCIENCE:100}
{1089}{}{[COMPONENTS]}
{1090}{}{2:1}                               # PID_METAL_ARMOR

{1100}{}{[ITEM]}
{1101}{}{239}                               # PID_BROTHERHOOD_COMBAT_ARMOR
{1102}{}{pcx/items/COMBA2A.pcx}
{1103}{}{83065}
{1104}{}{317}
{1105}{}{6048000}                           # 1 week
{1106}{}{NO}
{1107}{}{[TOOLS]}
{1108}{}{73}                                # PID_BIG_BOOK_OF_SCIENCE
{1109}{}{308}                               # PID_SUPER_TOOL_KIT
{1110}{}{[SKILLS]}
{1111}{}{SKILL_REPAIR:100}
{1112}{}{SKILL_SCIENCE:100}
{1113}{}{[COMPONENTS]}
{1114}{}{17:1}                              # PID_COMBAT_ARMOR

{1125}{}{[ITEM]}
{1126}{}{232}                               # PID_HARDENED_POWER_ARMOR
{1127}{}{pcx/items/PWRARMOR.pcx}
{1128}{}{68064}
{1129}{}{318}
{1130}{}{864000}                            # 24h
{1131}{}{NO}
{1132}{}{[TOOLS]}
{1133}{}{237}                               # PID_CHEMISTRY_MANUAL
{1134}{}{308}                               # PID_SUPER_TOOL_KIT
{1135}{}{[SKILLS]}
{1136}{}{SKILL_REPAIR:150}
{1137}{}{SKILL_SCIENCE:150}
{1138}{}{[COMPONENTS]}
{1139}{}{3:1}                               # PID_POWERED_ARMOR
# TODO
{1150}{}{[ITEM]}
{1151}{}{744}                               # PID_FLOATING_EYE_BOT
{1152}{}{pcx/items/MAFEYE.pcx}
{1153}{}{32059}
{1154}{}{366}
{1155}{}{12096000}                          # 2 weeks
{1156}{}{NO}
{1157}{}{[TOOLS]}
{1158}{}{76}                                # PID_DEANS_ELECTRONICS
{1159}{}{308}                               # PID_SUPER_TOOL_KIT
{1160}{}{[SKILLS]}
{1161}{}{SKILL_REPAIR:100}
{1162}{}{SKILL_SCIENCE:100}
{1163}{}{[COMPONENTS]}
{1164}{}{269:1}                               # PID_ROBOT_PARTS
{1165}{}{160:1}                               # PID_CATTLE_PROD

{1175}{}{[ITEM]}
{1176}{}{73}                               # PID_BIG_BOOK_OF_SCIENCE
{1177}{}{pcx/items/SCIENCE.pcx}
{1178}{}{58065}
{1179}{}{378}
{1180}{}{12096000}                          # 2 weeks
{1181}{}{NO}
{1182}{}{[TOOLS]}
{1183}{}{898}                                # PID_QUILL
{1184}{}{[SKILLS]}
{1185}{}{SKILL_SCIENCE:100}
{1186}{}{[COMPONENTS]}
{1187}{}{897:1}                               # PID_BLANK_BOOK

{1200}{}{[ITEM]}
{1201}{}{76}                               # PID_DEANS_ELECTRONICS
{1202}{}{pcx/items/DEANS.pcx}
{1203}{}{82063}
{1204}{}{380}
{1205}{}{12096000}                          # 2 weeks
{1206}{}{NO}
{1207}{}{[TOOLS]}
{1208}{}{898}                                # PID_QUILL
{1209}{}{[SKILLS]}
{1210}{}{SKILL_REPAIR:100}
{1211}{}{[COMPONENTS]}
{1212}{}{897:1}                               # PID_BLANK_BOOK

{1225}{}{[ITEM]}
{1226}{}{80}                               # PID_FIRST_AID_BOOK
{1227}{}{pcx/items/FRST_BK.pcx}
{1228}{}{92061}
{1229}{}{381}
{1230}{}{12096000}                          # 2 weeks
{1231}{}{NO}
{1232}{}{[TOOLS]}
{1233}{}{898}                                # PID_QUILL
{1234}{}{[SKILLS]}
{1235}{}{SKILL_FIRST_AID:100}
{1236}{}{[COMPONENTS]}
{1237}{}{897:1}                               # PID_BLANK_BOOK

{1250}{}{[ITEM]}
{1251}{}{86}                               # PID_SCOUT_HANDBOOK
{1252}{}{pcx/items/SCOUT.pcx}
{1253}{}{80062}
{1254}{}{382}
{1255}{}{12096000}                          # 2 weeks
{1256}{}{NO}
{1257}{}{[TOOLS]}
{1258}{}{898}                                # PID_QUILL
{1259}{}{[SKILLS]}
{1260}{}{SKILL_OUTDOORSMAN:100}
{1261}{}{[COMPONENTS]}
{1262}{}{897:1}                               # PID_BLANK_BOOK

{1275}{}{[ITEM]}
{1276}{}{102}                               # PID_GUNS_AND_BULLETS
{1277}{}{pcx/items/G&A.pcx}
{1278}{}{93065}
{1279}{}{383}
{1280}{}{12096000}                          # 2 weeks
{1281}{}{NO}
{1282}{}{[TOOLS]}
{1283}{}{898}                                # PID_QUILL
{1284}{}{[SKILLS]}
{1285}{}{SKILL_SMALL_GUNS:100}
{1286}{}{[COMPONENTS]}
{1287}{}{897:1}                               # PID_BLANK_BOOK

{1300}{}{[ITEM]}
{1301}{}{739}                               # PID_HEI_GUI_ARMOR
{1302}{}{pcx/items/arekzo.pcx}
{1303}{}{63048}
{1304}{}{713}
{1305}{}{12096000}                          # 2 weeks
{1306}{}{NO}
{1307}{}{[TOOLS]}
{1308}{}{76}                                # PID_DEANS_ELECTRONICS
{1309}{}{308}                               # PID_SUPER_TOOL_KIT
{1310}{}{73}                                # PID_BIG_BOOK_OF_SCIENCE
{1311}{}{[SKILLS]}
{1312}{}{SKILL_REPAIR:125}
{1313}{}{SKILL_SCIENCE:125}
{1314}{}{[COMPONENTS]}
{1315}{}{738:3}                             # PID_DAMAGED_HEI_GUI_ARMOR
{1316}{}{54:1}                              # PID_STEALTH_BOY
{1317}{}{649:1}                             # PID_NIGHT_VISION_GOGGLES

{1325}{}{[ITEM]}
{1326}{}{126}                               # PID_WATER_FLASK
{1327}{}{pcx/items/FLASK.pcx}
{1328}{}{55064}
{1329}{}{}
{1330}{}{36000}                            # 1 hour
{1331}{}{NO}
{1332}{}{[TOOLS]}
{1333}{}{895|101}                               # PID_WATER_PURIFICATION_TABLETS or PID_LIGHTER
{1334}{}{[SKILLS]}
{1335}{}{SKILL_OUTDOORSMAN:20}
{1336}{}{[COMPONENTS]}
{1337}{}{896:1}                               # PID_EMPTY_WATER_FLASK

{1350}{}{[ITEM]}
{1351}{}{767}                               # PID_HOW_TO_BE_A_WORLD_CLASS_TRIATHLETE
{1352}{}{pcx/items/TRIATH.pcx}
{1353}{}{68059}
{1354}{}{773}
{1355}{}{12096000}                          # 2 weeks
{1356}{}{NO}
{1357}{}{[TOOLS]}
{1358}{}{898}                                # PID_QUILL
{1359}{}{[SKILLS]}
{1360}{}{SKILL_THROWING:100}
{1361}{}{[COMPONENTS]}
{1362}{}{897:1}                               # PID_BLANK_BOOK

{1375}{}{[ITEM]}
{1376}{}{768}                               # PID_US_ARMY_30_HANDY_FLAMETHROWER_RECIPES
{1377}{}{pcx/items/usarmy.pcx}
{1378}{}{59059}
{1379}{}{774}
{1380}{}{12096000}                          # 2 weeks
{1381}{}{NO}
{1382}{}{[TOOLS]}
{1383}{}{898}                                # PID_QUILL
{1384}{}{[SKILLS]}
{1385}{}{SKILL_BIG_GUNS:100}
{1386}{}{[COMPONENTS]}
{1387}{}{897:1}                               # PID_BLANK_BOOK

{1400}{}{[ITEM]}
{1401}{}{769}                               # PID_NIKOLA_TESLA_AND_YOU
{1402}{}{pcx/items/teslayou.pcx}
{1403}{}{54058}
{1404}{}{775}
{1405}{}{12096000}                          # 2 weeks
{1406}{}{NO}
{1407}{}{[TOOLS]}
{1408}{}{898}                                # PID_QUILL
{1409}{}{[SKILLS]}
{1410}{}{SKILL_ENERGY_WEAPONS:100}
{1411}{}{[COMPONENTS]}
{1412}{}{897:1}                               # PID_BLANK_BOOK

{1425}{}{[ITEM]}
{1426}{}{770}                               # PID_MEDICAL_ENCYCLOPEDIA
{1427}{}{pcx/items/MEDENC.pcx}
{1428}{}{54052}
{1429}{}{776}
{1430}{}{12096000}                          # 2 weeks
{1431}{}{NO}
{1432}{}{[TOOLS]}
{1433}{}{898}                                # PID_QUILL
{1434}{}{[SKILLS]}
{1435}{}{SKILL_DOCTOR:100}
{1436}{}{[COMPONENTS]}
{1437}{}{897:1}                               # PID_BLANK_BOOK

{1450}{}{[ITEM]}
{1451}{}{771}                               # PID_GROGNAK_THE_BARBARIAN
{1452}{}{pcx/items/grognak.pcx}
{1453}{}{70058}
{1454}{}{777}
{1455}{}{12096000}                          # 2 weeks
{1456}{}{NO}
{1457}{}{[TOOLS]}
{1458}{}{898}                                # PID_QUILL
{1459}{}{[SKILLS]}
{1460}{}{SKILL_MELEE_WEAPONS:100}
{1461}{}{[COMPONENTS]}
{1462}{}{897:1}                               # PID_BLANK_BOOK

{1475}{}{[ITEM]}
{1476}{}{772}                               # PID_MAKING_FRIENDS_WITH_BIG_FAT_LIARS
{1477}{}{pcx/items/bigfat.pcx}
{1478}{}{68059}
{1479}{}{778}
{1480}{}{12096000}                          # 2 weeks
{1481}{}{NO}
{1482}{}{[TOOLS]}
{1483}{}{898}                                # PID_QUILL
{1484}{}{[SKILLS]}
{1485}{}{SKILL_SPEECH:100}
{1486}{}{[COMPONENTS]}
{1487}{}{897:1}                               # PID_BLANK_BOOK

{1500}{}{[ITEM]}
{1501}{}{773}                               # PID_CHINESE_ARMY_SPECIAL_OPS_TRAINING_MANUAL
{1502}{}{pcx/items/chinaops.pcx}
{1503}{}{71060}
{1504}{}{779}
{1505}{}{12096000}                          # 2 weeks
{1506}{}{NO}
{1507}{}{[TOOLS]}
{1508}{}{898}                                # PID_QUILL
{1509}{}{[SKILLS]}
{1510}{}{SKILL_SNEAK:100}
{1511}{}{[COMPONENTS]}
{1512}{}{897:1}                               # PID_BLANK_BOOK

{1525}{}{[ITEM]}
{1526}{}{774}                               # PID_HOME_SECURITY
{1527}{}{pcx/items/homesecu.pcx}
{1528}{}{65052}
{1529}{}{780}
{1530}{}{12096000}                          # 2 weeks
{1531}{}{NO}
{1532}{}{[TOOLS]}
{1533}{}{898}                                # PID_QUILL
{1534}{}{[SKILLS]}
{1535}{}{SKILL_LOCKPICK:100}
{1536}{}{[COMPONENTS]}
{1537}{}{897:1}                               # PID_BLANK_BOOK

{1550}{}{[ITEM]}
{1551}{}{775}                               # PID_MADDOCKS_TRICKS_TRAPS
{1552}{}{pcx/items/maddock.pcx}
{1553}{}{96053}
{1554}{}{781}
{1555}{}{12096000}                          # 2 weeks
{1556}{}{NO}
{1557}{}{[TOOLS]}
{1558}{}{898}                                # PID_QUILL
{1559}{}{[SKILLS]}
{1560}{}{SKILL_TRAPS:100}
{1561}{}{[COMPONENTS]}
{1562}{}{897:1}                               # PID_BLANK_BOOK

{1575}{}{[ITEM]}
{1576}{}{776}                               # PID_DONT_STEAL_THIS_BOOK
{1577}{}{pcx/items/dontstea.pcx}
{1578}{}{68059}
{1579}{}{782}
{1580}{}{12096000}                          # 2 weeks
{1581}{}{NO}
{1582}{}{[TOOLS]}
{1583}{}{898}                                # PID_QUILL
{1584}{}{[SKILLS]}
{1585}{}{SKILL_STEAL:100}
{1586}{}{[COMPONENTS]}
{1587}{}{897:1}                               # PID_BLANK_BOOK

{1600}{}{[ITEM]}
{1601}{}{777}                               # PID_PUGILISM_ILLUSTRATED
{1602}{}{pcx/items/pugilism.pcx}
{1603}{}{59059}
{1604}{}{783}
{1605}{}{12096000}                          # 2 weeks
{1606}{}{NO}
{1607}{}{[TOOLS]}
{1608}{}{898}                                # PID_QUILL
{1609}{}{[SKILLS]}
{1610}{}{SKILL_UNARMED:100}
{1611}{}{[COMPONENTS]}
{1612}{}{897:1}                               # PID_BLANK_BOOK

{1625}{}{[ITEM]}
{1626}{}{847}                               # PID_TALES_OF_A_JUNKTOWN_JERKY_VENDOR
{1627}{}{pcx/items/junktown.pcx}
{1628}{}{56058}
{1629}{}{784}
{1630}{}{12096000}                          # 2 weeks
{1631}{}{NO}
{1632}{}{[TOOLS]}
{1633}{}{898}                                # PID_QUILL
{1634}{}{[SKILLS]}
{1635}{}{SKILL_BARTER:100}
{1636}{}{[COMPONENTS]}
{1637}{}{897:1}                               # PID_BLANK_BOOK

{1650}{}{[ITEM]}
{1651}{}{848}                               # PID_ZEN_GAMBLING
{1652}{}{pcx/items/zen.pcx}
{1653}{}{65051}
{1654}{}{785}
{1655}{}{12096000}                          # 2 weeks
{1656}{}{NO}
{1657}{}{[TOOLS]}
{1658}{}{898}                               # PID_QUILL
{1659}{}{[SKILLS]}
{1660}{}{SKILL_GAMBLING:100}
{1661}{}{[COMPONENTS]}
{1662}{}{897:1}                               # PID_BLANK_BOOK

{1675}{}{[ITEM]}
{1676}{}{900}                               # PID_GUTS_STEW
{1677}{}{pcx/items/food08.pcx}
{1678}{}{69052}
{1679}{}{786}
{1680}{}{72000}                            # 2 h
{1681}{}{NO}
{1682}{}{[TOOLS]}
{1683}{}{101}                               # PID_LIGHTER
{1684}{}{[SKILLS]}
{1685}{}{SKILL_OUTDOORSMAN:20}
{1686}{}{[COMPONENTS]}
{1687}{}{634:1}                               # PID_GUTS

{1700}{}{[ITEM]}
{1701}{}{901}                               # PID_LIVER_CHOPS
{1702}{}{pcx/items/food07.pcx}
{1703}{}{85051}
{1704}{}{787}
{1705}{}{72000}                            # 2 h
{1706}{}{NO}
{1707}{}{[TOOLS]}
{1708}{}{101}                               # PID_LIGHTER
{1709}{}{[SKILLS]}
{1710}{}{SKILL_OUTDOORSMAN:20}
{1711}{}{[COMPONENTS]}
{1712}{}{635:1}                               # PID_LIVER

{1725}{}{[ITEM]}
{1726}{}{902}                               # PID_MUSHROOM_CLOUDS
{1727}{}{pcx/items/mushclou.pcx}
{1728}{}{42054}
{1729}{}{788}
{1730}{}{108000}                            # 3 h
{1731}{}{NO}
{1732}{}{[TOOLS]}
{1733}{}{101}                               # PID_LIGHTER
{1734}{}{[SKILLS]}
{1735}{}{SKILL_OUTDOORSMAN:30}
{1736}{}{[COMPONENTS]}
{1737}{}{623:1}                               # PID_CANNED_FOOD

{1750}{}{[ITEM]}
{1751}{}{903}                               # PID_DESERT_SALAD
{1752}{}{pcx/items/dsrtsald.pcx}
{1753}{}{74053}
{1754}{}{789}
{1755}{}{36000}                            # 1 h
{1756}{}{NO}
{1757}{}{[TOOLS]}
{1758}{}{101}                               # PID_LIGHTER
{1759}{}{[SKILLS]}
{1760}{}{SKILL_OUTDOORSMAN:30}
{1761}{}{[COMPONENTS]}
{1762}{}{284:1}                               # PID_MEAT_JERKY
{1763}{}{272:1}                               # PID_XANDER_ROOT
{1764}{}{646:1}                               # PID_CHEESE

{1775}{}{[ITEM]}
{1776}{}{536}                               # PID_DOCKING_CLAMP_CHIP
{1777}{}{pcx/items/ovrchip.pcx}
{1778}{}{121060}
{1779}{}{793}
{1780}{}{12096000}                          # 2 weeks
{1781}{}{NO}
{1782}{}{[TOOLS]}
{1783}{}{76}                                # PID_DEANS_ELECTRONICS
{1784}{}{308}                               # PID_SUPER_TOOL_KIT
{1785}{}{73}                                # PID_BIG_BOOK_OF_SCIENCE
{1786}{}{[SKILLS]}
{1787}{}{SKILL_REPAIR:150}
{1788}{}{SKILL_SCIENCE:150}
{1789}{}{[COMPONENTS]}
{1790}{}{55:1}                              # PID_WATER_CHIP

{1800}{}{[ITEM]}
{1801}{}{725}                               # PID_APOLLO_LASER_PISTOL
{1802}{}{pcx/items/apollo.pcx}
{1803}{}{120060}
{1804}{}{342}
{1805}{}{12096000}                          # 2 weeks
{1806}{}{NO}
{1807}{}{[TOOLS]}
{1808}{}{76}                                # PID_DEANS_ELECTRONICS
{1809}{}{308}                               # PID_SUPER_TOOL_KIT
{1810}{}{73}                                # PID_BIG_BOOK_OF_SCIENCE
{1811}{}{[SKILLS]}
{1812}{}{SKILL_REPAIR:150}
{1813}{}{SKILL_SCIENCE:150}
{1814}{}{[COMPONENTS]}
{1815}{}{402:1}                             # PID_MAGNETO_LASER_PISTOL

{1825}{}{[ITEM]}
{1826}{}{743}                               # PID_ARES_PLASMA_SPEAR
{1827}{}{pcx/items/wpnKnf07.pcx}
{1828}{}{162040}
{1829}{}{346}
{1830}{}{12096000}                          # 2 weeks
{1831}{}{NO}
{1832}{}{[TOOLS]}
{1833}{}{76}                                # PID_DEANS_ELECTRONICS
{1834}{}{308}                               # PID_SUPER_TOOL_KIT
{1835}{}{73}                                # PID_BIG_BOOK_OF_SCIENCE
{1836}{}{[SKILLS]}
{1837}{}{SKILL_REPAIR:150}
{1838}{}{SKILL_SCIENCE:150}
{1839}{}{[COMPONENTS]}
{1840}{}{402:1}                             # PID_PLASMA_PISTOL
{1841}{}{7:1}                               # PID_SPEAR

{1850}{}{[ITEM]}
{1851}{}{719}                               # PID_15MM_ARTEMIS_RAIL_GUN
{1852}{}{pcx/items/artemis.pcx}
{1853}{}{124061}
{1854}{}{343}
{1855}{}{24192000}                          # 4 weeks
{1856}{}{NO}
{1857}{}{[TOOLS]}
{1858}{}{76}                                # PID_DEANS_ELECTRONICS
{1859}{}{308}                               # PID_SUPER_TOOL_KIT
{1860}{}{73}                                # PID_BIG_BOOK_OF_SCIENCE
{1861}{}{[SKILLS]}
{1862}{}{SKILL_REPAIR:200}
{1863}{}{SKILL_SCIENCE:200}
{1864}{}{[COMPONENTS]}
{1865}{}{13:1}                               # PID_ROCKET_LAUNCHER
{1866}{}{392:1}                              # PID_M72_GAUSS_RIFLE

{1875}{}{[ITEM]}
{1876}{}{653}                               # PID_ATHENA_POWER_ARMOR
{1877}{}{pcx/items/ardfnder.pcx}
{1878}{}{57051}
{1879}{}{337}
{1880}{}{48384000}                          # 8 weeks
{1881}{}{NO}
{1882}{}{[TOOLS]}
{1883}{}{76}                                # PID_DEANS_ELECTRONICS
{1884}{}{308}                               # PID_SUPER_TOOL_KIT
{1885}{}{73}                                # PID_BIG_BOOK_OF_SCIENCE
{1886}{}{[SKILLS]}
{1887}{}{SKILL_REPAIR:200}
{1888}{}{SKILL_SCIENCE:200}
{1889}{}{[COMPONENTS]}
{1890}{}{349:1}                             # PID_ADVANCED_POWER_ARMOR_MK2

{1900}{}{[ITEM]}
{1901}{}{394}                               # PID_PK12_GAUSS_PISTOL
{1902}{}{pcx/items/GAUSSPTL.pcx}
{1903}{}{65053}
{1904}{}{375}
{1905}{}{12096000}                          # 2 weeks
{1906}{}{NO}
{1907}{}{[TOOLS]}
{1908}{}{76}                                # PID_DEANS_ELECTRONICS
{1909}{}{308}                               # PID_SUPER_TOOL_KIT
{1910}{}{73}                                # PID_BIG_BOOK_OF_SCIENCE
{1911}{}{[SKILLS]}
{1912}{}{SKILL_REPAIR:150}
{1913}{}{SKILL_SCIENCE:150}
{1914}{}{[COMPONENTS]}
{1915}{}{402:3}                               # PID_MAGNETO_LASER_PISTOL

{1925}{}{[ITEM]}
{1926}{}{392}                               # PID_M72_GAUSS_RIFLE
{1927}{}{pcx/items/M72GAUSS.pcx}
{1928}{}{174054}
{1929}{}{376}
{1930}{}{24192000}                          # 4 weeks
{1931}{}{NO}
{1932}{}{[TOOLS]}
{1933}{}{76}                                # PID_DEANS_ELECTRONICS
{1934}{}{308}                               # PID_SUPER_TOOL_KIT
{1935}{}{73}                                # PID_BIG_BOOK_OF_SCIENCE
{1936}{}{[SKILLS]}
{1937}{}{SKILL_REPAIR:150}
{1938}{}{SKILL_SCIENCE:150}
{1939}{}{[COMPONENTS]}
{1940}{}{394:2}                             # PID_PK12_GAUSS_PISTOL

{1950}{}{[ITEM]}
{1951}{}{696}                               # PID_MEC_GAUSS_MINIGUN
{1952}{}{pcx/items/TGATGAU1.pcx}
{1953}{}{129054}
{1954}{}{371}
{1955}{}{48384000}                          # 8 weeks
{1956}{}{NO}
{1957}{}{[TOOLS]}
{1958}{}{76}                                # PID_DEANS_ELECTRONICS
{1959}{}{308}                               # PID_SUPER_TOOL_KIT
{1960}{}{73}                                # PID_BIG_BOOK_OF_SCIENCE
{1961}{}{[SKILLS]}
{1962}{}{SKILL_REPAIR:200}
{1963}{}{SKILL_SCIENCE:200}
{1964}{}{[COMPONENTS]}
{1965}{}{392:5}                               # PID_M72_GAUSS_RIFLE
{1966}{}{395:1}                               # PID_VINDICATOR_MINIGUN

{1975}{}{[ITEM]}
{1976}{}{741}                               # PID_HERAKLES_POWER_FIST
{1977}{}{pcx/items/herakles.pcx}
{1978}{}{123056}
{1979}{}{344}
{1980}{}{12096000}                          # 2 weeks
{1981}{}{NO}
{1982}{}{[TOOLS]}
{1983}{}{76}                                # PID_DEANS_ELECTRONICS
{1984}{}{308}                               # PID_SUPER_TOOL_KIT
{1985}{}{73}                                # PID_BIG_BOOK_OF_SCIENCE
{1986}{}{[SKILLS]}
{1987}{}{SKILL_REPAIR:150}
{1988}{}{SKILL_SCIENCE:150}
{1989}{}{[COMPONENTS]}
{1990}{}{407:1}                               # PID_MEGA_POWER_FIST
{1991}{}{875:1}                               # PID_MICRO_SLEDGE

{2000}{}{[ITEM]}
{2001}{}{746}                               # PID_HERMES_ARMOR
{2002}{}{pcx/items/hermes.pcx}
{2003}{}{56060}
{2004}{}{345}
{2005}{}{48384000}                          # 8 weeks
{2006}{}{NO}
{2007}{}{[TOOLS]}
{2008}{}{76}                                # PID_DEANS_ELECTRONICS
{2009}{}{308}                               # PID_SUPER_TOOL_KIT
{2010}{}{73}                                # PID_BIG_BOOK_OF_SCIENCE
{2011}{}{[SKILLS]}
{2012}{}{SKILL_REPAIR:150}
{2013}{}{SKILL_SCIENCE:150}
{2014}{}{[COMPONENTS]}
{2015}{}{381:2}                             # PID_COMBAT_ARMOR_MK_II

{2025}{}{[ITEM]}
{2026}{}{390}                               # PID_SOLAR_SCORCHER
{2027}{}{pcx/items/SOLARSCR.pcx}
{2028}{}{97052}
{2029}{}{373}
{2030}{}{12096000}                          # 2 weeks
{2031}{}{NO}
{2032}{}{[TOOLS]}
{2033}{}{76}                                # PID_DEANS_ELECTRONICS
{2034}{}{308}                               # PID_SUPER_TOOL_KIT
{2035}{}{73}                                # PID_BIG_BOOK_OF_SCIENCE
{2036}{}{[SKILLS]}
{2037}{}{SKILL_REPAIR:150}
{2038}{}{SKILL_SCIENCE:150}
{2039}{}{[COMPONENTS]}
{2040}{}{396:1}                             # PID_YK32_PULSE_PISTOL

{2050}{}{[ITEM]}
{2051}{}{59}                               # PID_MOTION_SENSOR
{2052}{}{pcx/items/MOTION.pcx}
{2053}{}{90065}
{2054}{}{168}
{2055}{}{6048000}                          # 1 week
{2056}{}{NO}
{2057}{}{[TOOLS]}
{2058}{}{75}                                # PID_MULTI_TOOL
{2059}{}{[SKILLS]}
{2060}{}{SKILL_REPAIR:75}
{2061}{}{SKILL_SCIENCE:75}
{2062}{}{[COMPONENTS]}
{2063}{}{100:1}                             # PID_RADIO

{2075}{}{[ITEM]}
{2076}{}{52}                               # PID_GEIGER_COUNTER
{2077}{}{pcx/items/GEIGER4.pcx}
{2078}{}{73063}
{2079}{}{370}
{2080}{}{6048000}                          # 1 week
{2081}{}{NO}
{2082}{}{[TOOLS]}
{2083}{}{75}                                # PID_MULTI_TOOL
{2084}{}{[SKILLS]}
{2085}{}{SKILL_REPAIR:75}
{2086}{}{SKILL_SCIENCE:75}
{2087}{}{[COMPONENTS]}
{2088}{}{893:1}                             # PID_GAS_TANK

{2100}{}{[ITEM]}
{2101}{}{160}                               # PID_CATTLE_PROD
{2102}{}{pcx/items/CPROD3.pcx}
{2103}{}{91063}
{2104}{}{374}
{2105}{}{864000}                            # 24h
{2106}{}{NO}
{2107}{}{[TOOLS]}
{2108}{}{75}                                # PID_MULTI_TOOL
{2109}{}{[SKILLS]}
{2110}{}{SKILL_REPAIR:50}
{2111}{}{SKILL_SCIENCE:50}
{2112}{}{[COMPONENTS]}
{2113}{}{5:1}                              # PID_CLUB
{2114}{}{38:1}                             # PID_SMALL_ENERGY_CELL
{2115}{}{100:1}                            # PID_RADIO

{2125}{}{[ITEM]}
{2126}{}{584}                               # PID_DANGEROUS_POISON
{2127}{}{pcx/items/MUTASYRM.pcx}
{2128}{}{84059}
{2129}{}{828}
{2130}{}{36000}                             # 1h
{2131}{}{NO}
{2132}{}{[TOOLS]}
{2133}{}{4|45|236|714}                      # PID_KNIFE|PID_THROWING_KNIFE|PID_COMBAT_KNIFE|PID_SHARPENED_KNIFE
{2134}{}{[SKILLS]}
{2135}{}{SKILL_OUTDOORSMAN:25}
{2136}{}{[COMPONENTS]}
{2137}{}{318:1}                             # PID_HYPODERMIC_NEEDLE
{2138}{}{92:1}                              # PID_SCORPION_TAIL

{2150}{}{[ITEM]}
{2151}{}{334}                               # PID_POWERFUL_POISON
{2152}{}{pcx/items/POISON.pcx}
{2153}{}{84059}
{2154}{}{829}
{2155}{}{36000}                             # 1h
{2156}{}{NO}
{2157}{}{[TOOLS]}
{2158}{}{4|45|236|714}                      # PID_KNIFE|PID_THROWING_KNIFE|PID_COMBAT_KNIFE|PID_SHARPENED_KNIFE
{2159}{}{[SKILLS]}
{2160}{}{SKILL_OUTDOORSMAN:25}
{2161}{}{[COMPONENTS]}
{2162}{}{318:1}                             # PID_HYPODERMIC_NEEDLE
{2163}{}{601:1}                             # PID_STINGER

{2175}{}{[ITEM]}
{2176}{}{265}                                # PID_CURED_LEATHER_ARMOR
{2177}{}{pcx/items/SPLEATHR.pcx}
{2178}{}{62063}
{2179}{}{140}
{2180}{}{231000}                            # 6 h 25 m
{2181}{}{YES}
{2182}{}{[TOOLS]}
{2183}{}{4|45|236|714}                          # PID_KNIFE|PID_THROWING_KNIFE|PID_COMBAT_KNIFE|PID_SHARPENED_KNIFE
{2184}{}{[SKILLS]}
{2185}{}{SKILL_REPAIR:80}
{2186}{}{[COMPONENTS]}
{2187}{}{127:1}                             # PID_ROPE
{2188}{}{276:6}                             # PID_GECKO_PELT
