/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/*
        Name: Raider
        Location: Random Encounters
        Description:

        Log:
           Please note any changes that have been made to the file in Updated. Then comment
           the code which you have changed/altered/commented out. Please, do not delete any
           code which was written.

           Created:

           Updated:
*/

/* Include Files */

/* Note, the Following Lines need to be in this order so that
   the script will be compilable. The define Name is referenced
   in a module from define.h and used in command.h. Please do
   not change the ordering.
        -rwh2   11/13/97
*/
#include "..\headers\define.h"
//#include "..\headers\<TownName.h>"

#define NAME                    SCRIPT_FALEGION
#define TOWN_REP_VAR            (0)

#include "..\headers\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\HEADERS\fafarm.h"

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure destroy_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure description_p_proc;
procedure look_at_p_proc;
procedure timed_event_p_proc ;
procedure talk_p_proc;
procedure combat_p_proc;
procedure use_skill_on_p_proc;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_CAESARS_LEGION);

   add_timer_event(self_obj,game_ticks(random(1,5)),0);

end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
written by designers are placed in here. Additionally, Reactions are generated and
stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=1;
   Slavery_Tolerant:=SLAVE_PROUD;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

floater_rand(200, 235);

end

procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

procedure look_at_p_proc begin

end

procedure description_p_proc begin

end

/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if(map_var(MVAR_CAESARS_LEGION_GONE) > 0 and cur_map_index == MAP_FORT_ABANDON_FARM) then begin
      set_obj_visibility(self_obj, 1);
      destroy_object(self_obj);
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */

   self_attack_critter(source_obj);

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   self_attack_critter(source_obj);
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_evil_critter

/* Set global_variable for Enemy status*/
end

procedure timed_event_p_proc begin
   if (fixed_param == 0) then begin
      if (not anim_busy(self_obj) and self_elevation == dude_elevation) then begin
         reg_anim_clear(self_obj);
         reg_anim_begin();
         animate_move_to_tile(tile_num_in_direction(self_tile, random(0, 5), random(1, 3)));
         reg_anim_end();
      end

      if (random(1, 30) == 1 and not(combat_is_initialized) and self_elevation == dude_elevation) then begin
         floater_rand(201, 210);
      end
   end

   add_timer_event(self_obj, game_ticks(random(3, 5)), 0);
 end

 procedure combat_p_proc begin
   if (critter_is_fleeing(self_obj)) then begin
      if (Random(1, 100) <= 20) then begin
         floater_afraid_rand(248, 259);
      end
   end else begin
      if (Random(1, 100) <= 20) then begin
         floater_bad_rand(236, 247);
      end
   end
end
