/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/* Random Encounter scripts. These will be filled in more once they
   have been designed.
*/

procedure start;

#include "..\headers\define.h"

#define NAME                    SCRIPT_FAMONGRE

#include "..\headers\command.h"
#include "..\headers\party.h"
#include "..\HEADERS\fafarm.h"

procedure start;
procedure critter_p_proc;
procedure map_exit_p_proc;
procedure description_p_proc ;
procedure map_enter_p_proc ;
procedure timed_event_p_proc ;
procedure use_skill_on_p_proc;

procedure start begin
end

procedure map_enter_p_proc begin
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_CAESARS_LEGION);

   if(map_var(MVAR_CAESARS_LEGION_GONE) > 0 and cur_map_index == MAP_FORT_ABANDON_FARM) then begin
      set_obj_visibility(self_obj, 1);
      destroy_object(self_obj);
   end

   add_timer_event(self_obj,game_ticks(random(3, 6)),0);

end

procedure map_exit_p_proc begin
   call BeastlordUnpossess(TEAM_CAESARS_LEGION);
end

procedure critter_p_proc begin

      if(self_can_see_dude and (cur_map_index == MAP_FORT_ABANDON_PARKING) and self_can_speak) then begin
            self_attack_dude;
      end

end

procedure description_p_proc begin
   script_overrides;
   display_mstr(102);

   call BeastlordPossess;
end

procedure timed_event_p_proc begin
   if (fixed_param == 0) then begin
      if (random(1, 4) == 1) then begin
         animate_move_to_tile(tile_num_in_direction(self_tile, random(0,5), random(3,7)));
      end
      add_timer_event(self_obj,game_ticks(random(3, 6)),0);
   end
end

procedure use_skill_on_p_proc begin
   call injure_with_skill;
end
