/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

// Goo.ssl
// damages critters in the goo

#include "..\headers\define.h"

#define NAME                    SCRIPT_GOO
#include "..\headers\command.h"

procedure spatial_p_proc;
procedure start;
procedure meltem;
procedure pain;

variable my_boots;
variable k;
variable mutate:=0;

procedure start begin
end

procedure spatial_p_proc
begin
     my_boots:=0;
     //dont need to be carrying boots in hand
     if (obj_carrying_pid_obj(source_obj, PID_RUBBER_BOOTS)) then begin
        //if carrying boots ..do boot damage
       debug("NPC Code")
        k := random(1,100);
        if (k < 2) then begin //1% chance to melt
           my_boots := obj_carrying_pid_obj(source_obj, PID_RUBBER_BOOTS);
           rm_obj_from_inven(source_obj, my_boots);
           destroy_object(my_boots);
           if (source_obj == dude_obj) then begin
              display_mstr(130);
           end
        end
     end
     else begin //check if target is naturally immune
         variable pid;
         pid = obj_pid(source_obj);
         if (
            (pid == PID_GOLDEN_GECKO) or
            (pid == PID_TOUGH_GOLDEN_GECKO) or
            (pid == PID_GECKO_SMALL) or
            (pid == PID_TOUGH_GECKO_SMALL) or
            (pid == PID_RADLEECH) or
            (pid == PID_NASTY_RADLEECH) or
            (pid == PID_ALBINO_MOLE_RAT) or
            (pid == PID_GIANT_ALBINO_ANT_SOLDIER) or
            (pid == PID_GIANT_ALBINO_ANT_QUEEN) or
            (pid == PID_GIANT_ALBINO_ANT_WORKER) or
            (pid == PID_GLOWING_GECKO) or
            (pid == PID_WASTEBOT)
         ) then begin
            debug("I'm immune")
         end
         else begin
            call pain;
         end
      end
 end

procedure meltem begin
   debug("My Boots Protect Me!")
   k := random(1,100);
   if (k < 2) then begin //1% chance to melt
      debug("Melting")
      //remove boots from players inventory
      rm_obj_from_inven(dude_obj, my_boots);
      destroy_object(my_boots);
      display_mstr(130);
   end
end

procedure pain begin
   //if not wearing proper armor then do damage
   if (not(dude_wearing_power_armor) and not(dude_wearing_environmental_armor) and not(dude_wearing_space_suit)) then begin
      debug("It hurts!")
      if ( (source_obj == dude_obj) and (global_var(GVAR_MUTATE_STAGE) < 1) ) then begin
         mutate:=global_var(GVAR_MUTATE);
         mutate:=mutate+2;
         set_global_var(GVAR_MUTATE,mutate);
         if (mutate > 29) then begin
            //set_global_var(GVAR_MUTATE, 1); //set state of character to mutate
            set_global_var(GVAR_MUTATE_WHEN, GAME_TIME_IN_DAYS); //store the time
            set_global_var(GVAR_MUTATE_STAGE,1);
            display_mstr(150);
         end
         else if (mutate > 14) then begin
            display_mstr(140);
         end
         else begin
            display_mstr(110);
         end
      end
      critter_dmg(source_obj, 2, DMG_plasma);
   end
end
