/*******************************************************************************
        Name:
        Location:
        Description: Critters template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"

#define NAME                    SCRIPT_HYDRA

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure critter_p_proc;
procedure use_skill_on_p_proc;
procedure combat_p_proc;
procedure destroy_p_proc;

/* Defines */

#define POISON_MIN              (3)
#define POISON_MAX              (9)
#define RAD_MIN                 (4)
#define RAD_MAX                 (20)


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/

variable once, rot, hydra;
variable pissed:=false;

/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin

end

procedure map_enter_p_proc begin

   critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, TEAM_HYDRA);
   critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_SPORE_PLANT);

end

procedure critter_p_proc begin
    script_overrides;

    if(combat_is_initialized) then begin
        return;
    end

    if(tile_distance_objs(dude_obj, self_obj) > 1) then begin
        if(once == 0) then begin
            reg_anim_begin();
            reg_anim_animate(self_obj, ANIM_climb_ladder, -1);
            reg_anim_end();
            once := 1;
            add_timer_event(self_obj, game_ticks(1), 1);
        end

    end else begin
        if(not(combat_is_initialized) and self_can_hear_dude) then begin
            self_attack_dude;
                     pissed := true;

        end
    end

end


procedure timed_event_p_proc begin
            hydra := create_object(16777814, self_tile, self_elevation);
            if (hydra) then begin
                            set_obj_visibility(self_obj, 1);
                destroy_object(self_obj);
            end

end

procedure pickup_p_proc begin
   //script_overrides;

end

procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

procedure combat_p_proc begin
   if (fixed_param == COMBAT_SUBTYPE_HIT_SUCCEEDED) then begin
           poison(target_obj,random(POISON_MIN,POISON_MAX));
         if ((target_obj == dude_obj) and not(dude_immune_to_radiation)) then begin
            radiation_inc(target_obj,random(RAD_MIN,RAD_MAX));
         end
   end
end

procedure damage_p_proc begin
   if (pissed == false) then begin
      pissed := true;
         self_attack_dude;

   end
end

procedure destroy_p_proc begin
   if(cur_map_index == MAP_SPECIAL_ENCOUNTER_TEMPLE_COAST) then begin
      set_global_var(GVAR_DROWNED_TEMPLE_LOWER, global_var(GVAR_DROWNED_TEMPLE_LOWER) + 1);
   end
end
