/*
	CJ Train "John Henry"
*/


#include "..\headers\define.h"
#include "..\headers\command.h"

#define NAME                    SCRIPT_CJTRAIN

procedure map_enter_p_proc;

procedure map_enter_p_proc begin

    if(global_var(GVAR_ACT) == 1) then begin
        set_obj_visibility(self_obj, 1);
     end
     else if(not(obj_is_visible_flag(self_obj)) and global_var(GVAR_ACT) >= 2) then begin
      set_obj_visibility(self_obj, 0);
   end

end
