/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/* Random Encounter scripts. These will be filled in more once they
   have been designed.
*/

procedure start;

#include "..\headers\define.h"

#define NAME                    SCRIPT_MV3SNAKE

#include "..\headers\command.h"
#include "..\HEADERS\footsteps.h"

procedure critter_p_proc;
procedure map_enter_p_proc;
procedure combat_p_proc;
procedure destroy_p_proc;
procedure timed_event_p_proc;
procedure use_skill_on_p_proc;

variable starttile := 0;

procedure start begin
end

procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_neutral_critter


/* Set global_variable for Enemy status*/

end

procedure map_enter_p_proc begin
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_HOUNDS_MESA_VERDE);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_FLOATER);
   starttile := self_tile;
   reg_anim_clear(self_obj);
   reg_anim_begin();
   animate_rotation(Random(0, 5));
   reg_anim_end();

   if (global_var(GVAR_MESA_HOUNDS_RESOLUTION) == DEAL_WITH_HOUNDS_LEFT) then begin
      set_obj_visibility(self_obj, 1);
      destroy_object(self_obj);
   end
   else if (
      (global_var(GVAR_MESA_HOUNDS_RESOLUTION) == DEAL_WITH_HOUNDS_BLASTED) or
      (global_var(GVAR_MESA_HOUNDS_RESOLUTION) == DEAL_WITH_HOUNDS_CRUSHED)
      ) then begin
      critter_heal(self_obj, -10000);
   end
   else if (global_var(GVAR_MESA_HOUNDS_RESOLUTION) == DEAL_WITH_HOUNDS_POISONED) then begin
      critter_heal(self_obj, -100);
   end

   call critter_setup_footsteps_map_enter(self_obj, WALKING_TICKS_VERY_SLOW, RUNNING_TICKS_DEFAULT);
end

procedure critter_p_proc begin

   if (not anim_busy(self_obj)) then begin
      reg_anim_clear(self_obj);
      reg_anim_begin();
      animate_move_to_tile(tile_num_in_direction(starttile, Random(0, 5), Random(10, 20)));
      reg_anim_end();
   end
end

procedure combat_p_proc begin
   if (fixed_param == COMBAT_SUBTYPE_HIT_SUCCEEDED) then begin
      //if (target_obj == dude_obj) then begin
         if (not(is_success(do_check(target_obj,STAT_lu,-1)))) then begin
            poison(target_obj,random(3,15));
         end
      //end
   end
end

procedure timed_event_p_proc begin
   call critter_setup_footsteps_timed_event(self_obj, WALKING_TICKS_VERY_SLOW, RUNNING_TICKS_DEFAULT, SFX_FOOTSTEP_SOFT_BAREFOOT);
end

procedure use_skill_on_p_proc begin
   call injure_with_skill;
end
