/*

        Name:           Alexandra
        Location:       Mesa Verde
        Description:

           Created: 18.9.2024. 7:50:29

*/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\ModReact.h"
#include "..\headers\party.h"
#include "..\headers\partybkg.h"
#include "..\headers\caravan.h"
#include "..\headers\mvcanyo3.h"
#include "..\HEADERS\footsteps.h"

#define NAME                    SCRIPT_MVALEX
#define TOWN_REP_VAR            (GVAR_TOWN_REP_NEW_CANAAN)

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure push_p_proc;
procedure timed_event_p_proc;

/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure dead_jermiah;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node034;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;
procedure Node039;
procedure Node040;
procedure Node041;
procedure Node042;
procedure Node043;
procedure Node044;
procedure Node045;
procedure Node046;
procedure Node047;
procedure Node048;
procedure Node049;
procedure Node050;
procedure Node051;
procedure Node052;
procedure Node053;
procedure Node054;
procedure Node055;
procedure Node056;
procedure Node057;
procedure Node058;
procedure Node059;
procedure Node060;
procedure Node061;
procedure Node062;
procedure Node063;
procedure Node064;
procedure Node065;
procedure Node066;
procedure Node067;
procedure Node068;
procedure Node069;
procedure Node070;
procedure Node071;
procedure Node072;
procedure Node073;
procedure Node074;
procedure Node075;
procedure Node076;
procedure Node077;
procedure Node078;
procedure Node079;
procedure Node080;
procedure Node081;
procedure Node082;
procedure Node083;
procedure Node084;
procedure Node085;
procedure Node086;
procedure Node087;
procedure Node088;
procedure Node089;
procedure Node090;
procedure Node091;
procedure Node092;
procedure Node093;
procedure Node094;

procedure travel_to_fa;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool

/*****************************************************************
Party Member pre-requisites
These lines are necessary for the critter to join the player
as a party member.
*****************************************************************/
procedure Join_Party;                                    // Party Join node
procedure Abandon_Party;                                 // Party Abandon node
procedure Node1000;                                      // Main party member node
procedure Node1001;                                      // heal yourself
procedure Node1002;                                      // wait here
procedure Node1003;                                      // put your weapon away
procedure Node1004;                                      // follow close
procedure Node1005;                                      // follow medium
procedure Node1006;                                      // follow far
procedure Node1007;                                      // change distance menu
procedure Node1008;                                      // look at gear menu
procedure Node1009;                                      // remove armor menu
procedure Node1010;                                      // weapon abilities
procedure Node1100;                                      // rejoin party


/* Change "Alexandra" to match the name of your new critter */
#define Alexandra_joins_party             party_add_self;                                                   \
                                               critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_PLAYER)
#define dude_has_free_slot_for_Alexandra  ((dude_at_max_party_size == false) and (Alexandra_In_Party == false))     // Need to declare Alexandra_In_Party in PARTY.H
      /*
      Right click "dude_at_max_party_size" and select "Go to declaration" to open PARTY.H
      Scroll to the top and add lines with this format:
         #define Alexandra_Ptr                             party_member_obj(PID_Alexandra)
      and:
         #define Alexandra_In_Party                        (Alexandra_Ptr != 0)
      You don't have to organize them in the same sections as their counterparts, but it helps :)
      Make sure PID_Alexandra is declared in CRITRPID.H.
      If you used Proto Manager to create your critter then it should have
      automatically added it to this list.

      In order to get Party AI options for combat, open Party.TXT in data\data\ folder
      and add your new party member to the end of the list.
      Simply copy and paste the options for the previous party member, and adjust to your liking.
      Make sure the party_member_PID is pointing to the correct number and is declared in CRITRPID.H
      */

/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_

      To have LVars work, open scripts.LST, scroll to your character's script name,
      and change the "LVars" setting to at least 8,
      Since there are 8 Local Variables used below.

      (LVAR_ 0 thru 3 are reserved for NPC Reaction Modifiers...
      ...will add more instructions when I learn how they work.)
*****************************************************************/
#define LVAR_Flags                      (4)
#define LVAR_WAITING                    (5)
#define LVAR_FOLLOW_DISTANCE            (6)
#define LVAR_TEAM                       (7)
#define LVAR_Joined_Player              (8)

/*****************************************************************
      If you would rather use the LVAR_Hostile, LVAR_Herebefore, LVAR_Personal_Enemy
      variables instead of LVAR_Flags, uncomment the relevent lines and comment out
      lines with set_herebefore, set_hostile, if (hostile) and (self_can_see_dude).
*****************************************************************/
//#define LVAR_Hostile                    (9)
//#define LVAR_Herebefore                 (10)
//#define LVAR_Personal_Enemy             (11)

#define PARTY_NODE_X                      Node1000

/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/

/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/
variable begin
end

/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin
end

procedure map_enter_p_proc begin
   /*  This procedure will get called each time that the map is first entered. It will
       set up the Team number and AI packet for this critter. This will override the
       default from the prototype, and needs to be set in scripts. */

   //party_member_map_enter;
   if not(Alexandra_In_Party) then begin
      critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM,TEAM_ALEXANDRA);
   end

   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_PARTY_ALEXANDRA_CUSTOM);

   call critter_setup_footsteps_map_enter(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT);

   add_timer_event(self_obj,game_ticks(1),0);

   // Can't spawn here, Blackjack's dead
   if(
      (global_var(GVAR_ALEXANDRA_DEAD) == 1) or
      (
         (
            (global_var(GVAR_BLACKJACK_DEAD) == 1) or
            (global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF) == ALEXANDRA_BLACKJACK_TRICKED) or
            (global_var(GVAR_BLACKJACK_RESOLUTION) == BLACKJACK_RESOLUTION_ESCAPED)
         ) and
         (cur_map_index == MAP_MESA_VERDE_CANYON_SOUTH_CAVE)
         )
   ) then begin
      set_obj_visibility(self_obj, 1);
      destroy_object(self_obj);
   end

   if (
      (cur_map_index == MAP_FORT_ABANDON_COURTYARD) and
      (global_var(GVAR_ALEXANDRA_DEAD) == 0) and
      not(Alexandra_In_Party)
   ) then begin
      if (global_var(GVAR_MEET_ALEXANDRA_AT_FA) == 1)
      then begin
         set_global_var(GVAR_MEET_ALEXANDRA_AT_FA, 2);
         if (not(obj_is_visible_flag(self_obj))) then begin
            set_obj_visibility(self_obj, 0);
         end
      end
      else if (
         (global_var(GVAR_MEET_ALEXANDRA_AT_FA) == 0) and
         obj_is_visible_flag(self_obj)
      ) then begin
         set_obj_visibility(self_obj, 1);
      end
   end
end

procedure timed_event_p_proc begin
   call critter_setup_footsteps_timed_event(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT, SFX_FOOTSTEP_SOFT_SHOE);
end

/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if (hostile) and (self_can_see_dude) then begin
      self_attack_dude; //Macro made by Tom to keep the critter fleeing.
   end

   /* This next script moves the new party member to follow the player after they've joined and
      when entering new maps. */
   if (Alexandra_In_Party) then begin

      if (check_general_rep <= KARMA_SWORD_OF_DESPAIR) then begin
         call Abandon_Party;
         debug_msg("Alexandra Bad Player Rep");
         if (dude_is_male) then begin
            floater_bad_rand(5361, 5365);
         end else begin
            floater_bad_rand(5360, 5364);
         end
      end
      else if (has_rep_childkiller) then begin
         call Abandon_Party;
         debug_msg("Alexandra: Child Killer");
         floater_bad_rand(5360, 5365);
      end
      else if (has_rep_berserker) then begin
         call Abandon_Party;
         debug_msg("Alexandra: Berserker");
         floater_bad_rand(5360, 5365);
      end
      else if (party_is_waiting == false) then begin
         party_member_follow_dude
      end
   end
end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
      set_personal_enemy;
   end
end

procedure pickup_p_proc begin
   /* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
      In here, various things can happen. The most common response is instant hostility which
      will be remembered. */

   if (source_obj == dude_obj) then begin
      set_hostile;
   end

end

procedure talk_p_proc begin

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   ReactToLevel;
   find_party_background;
   call set_idiot_savant_int;

   start_gdialog(NAME,self_obj,4,HEAD_ALEXANDRA,PartyMemberBackground);
   gSay_Start;

   if ((Alexandra_Ptr != 0) or (party_is_waiting)) then begin
      call Node1000;
   end
   else if (has_rep_childkiller or (check_general_rep <= KARMA_SWORD_OF_DESPAIR)) then begin
      call Node031;
   end
   else if (global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF) == ALEXANDRA_BLACKJACK_TRICKED) then begin
      call Node021;
   end
   else if (global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF) == ALEXANDRA_BLACKJACK_CAVE_COLLAPSED) then begin
      call Node026;
   end
   else if (global_var(GVAR_BLACKJACK_RESOLUTION) == BLACKJACK_RESOLUTION_ESCAPED) then begin
      call Node030;
   end
   else if (global_var(GVAR_MEET_ALEXANDRA_AT_FA) == 2) then begin
      call Node092;
   end
   else if (global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF) == QUEST_ACCEPTED) then begin
      call Node012;
   end
   else if (dude_is_stupid) then begin
      call Node017;
   end
   else begin
      call Node001;
   end

   gSay_End;
   end_dialogue;
   call restore_idiot_savant_int;
end

procedure destroy_p_proc begin
/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */

/* Increment the aligned critter counter*/
   inc_neutral_critter

/* Set global_variable for Enemy status*/
   set_global_var(GVAR_ALEXANDRA_DEAD, 1);
   set_global_var(GVAR_ENDGAME_MOVIE_ALEX, 0);
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if not(herebefore) then begin
      set_herebefore;
      display_mstr(100);
   end else begin
      display_mstr(101);
   end
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin

   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
      for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

procedure map_exit_p_proc begin
   if (
      (global_var(GVAR_MEET_ALEXANDRA_AT_FA) == 1) and
      not(obj_is_visible_flag(self_obj)) and
      not(Alexandra_In_Party)
      ) then begin
      destroy_object(self_obj);
   end
end

procedure push_p_proc begin
   floater_rand(5000, 5002);                               // Random Float responses for being pushed by player
end

/* This node checks for stuff before allowing NPC to join party.
   You can add other conditions for joining here. */
procedure join_check begin

   if (dude_charisma <= 1) then begin
      floater_bad(5030);                                    // Response if player has 1 Charisma or less
   end
   else begin
      if (dude_at_max_party_size) then begin
         Reply(5031);                                           // This line is for when the character does NOT join the player's party       (because too many followers)
         NOption(441,Node999,1);                            // This NOption message is Normal Int player response to NOT joining party    (because too many followers)
      end
      else if (town_rep_is_hated) then begin
         Reply(5032);                                           // This line is for if the player is hated by the NPC's home town (hates player because TOWN_REPUTATION<=-15)
         BOption(441, Node998, 1);                          // This line is Normal Int response to being hated by the NPC's home town  (default points to combat Node998)
      end
      else if (map_is_random_encounter) then begin          // She joins in the bounty hunter encounter
         Reply(1190);
         NOption(1191,Join_Party,4);
      end
      else begin
         Reply(470);                                           // This line is for when the character agrees to Join the player's party
         NOption(mstr(473)+" "+mstr(471)+dude_name+mstr(472),Join_Party,4);
         NOption(mstr(473)+" "+mstr(474),Join_Party,4);
      end
   end
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_hostile;
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
   set_herebefore;
   set_global_var(GVAR_KNOW_ALEXANDRA, 1);
end

/* This node places the NPC in the player's party.
   Call this node any time you want an action from the player to result in the NPC joining their party. */
procedure Join_Party begin
   Alexandra_joins_party;
   set_local_var(LVAR_Joined_Player,1);
   floater_good(2960);
end

procedure Abandon_Party begin
   //leave party
   if (self_visible) then begin
      set_self_abandon_party;
   end

end

   /* Node1000 and on are default dialogue nodes for a generic NPC joining the player's party. */

procedure Node1000 begin
   Reply(random(5060, 5063));                                        // This reply is when the NPC is in your party and you talk to them
   NOption(2961,Node093,4);
   NOption(2965,Node093,-3);
   party_member_default_options;
end

procedure Node1001 begin
   // heal yourself
   obj_heal(self_obj)
   if (party_healed_max) then begin
      Reply(random(5090,5093));                                     // This reply is when your party member is healed to max
   end
   else if (party_healed_good) then begin
     Reply(random(5094,5096));                                      // This reply message is for when the NPC is Barely Hurt (90% health or above)
   end
   else if (party_healed_hurt) then begin
      Reply(random(5097,5099));                                     // This reply message is for when the NPC is Wounded (70%-90% health?)
   end
   else begin
      Reply(random(5100,5102));                                     // This reply message is for Failures
   end
   party_member_default_options;
end

procedure Node1002 begin
   // wait here
   set_party_waiting;
   Reply(random(5120,5123));                            // These reply messages are in response to wait request
   party_member_default_options;
end

procedure Node1003 begin
   // put your weapon away
   inven_unwield(self_obj);
   Reply(random(5150,5152));                                        // Response to removing weapon
   party_member_default_options;
end

procedure Node1004 begin
   // follow close
   set_follow_close;
   Reply(5180);                            // Random responses for distance change
   party_member_default_options;
end

procedure Node1005 begin
   // follow medium
   set_follow_medium;
   Reply(5182);                            // Random responses for distance change
   party_member_default_options;
end

procedure Node1006 begin
   // follow far
   set_follow_far;
   Reply(5181);                            // Random responses for distance change
   party_member_default_options;
end

procedure Node1007 begin
   // distance
   //Reply("TEMP MESSAGE: DISTANCE");
   Reply(random(5210,5212));                                        // Generic response to "Change follow distance" menu
   party_member_def_follow_options;
end

procedure Node1008 begin
   // gear
   //Reply("TEMP MESSAGE: GEAR");
   Reply(random(5240,5242));                                        // Generic response to "Look at your gear"
   party_member_def_gear_options;
end

procedure Node1009 begin
   // remove armor
   //NEED TO FIND OUT WHY THIS DOESNT WORK!!! - NBK
   remove_armor(self_obj)
   //Reply("TEMP MESSAGE: REMOVE ARMOR");
   Reply(random(5270,5272));                                        // Generic response to "Remove armor"
   party_member_default_options;
end

procedure Node1010 begin
   // weapons that can be used
   //Reply("TEMP MESSAGE: CAN USE...");
   Reply(random(5300,5302));                                        // Specific reply, indicating what weapons the NPC can use.
   party_member_default_options;
end

procedure Node1100 begin                              // This node is for when the player is asking the NPC to re-join
   // join me
   if (dude_charisma <= 1) then begin
      set_self_abandon_party;
      Reply(random(5029, 5030));                      // NPC abandons party because Player Character is too ugly
      NOption(g_mstr(10007),Node999,001);             // Predefined generic messages in GENERIC.MSG
   end else if (dude_at_max_party_size) then begin
      set_self_abandon_party;
      Reply(5031); //was 2000                          // Generic "Too many followers" reply
      NOption(g_mstr(10007),Node999,001);             // Predefined generic messages in GENERIC.MSG
   end else if (town_rep_is_hated) then begin
      set_self_abandon_party;
      Reply(5032);                                     // Will abandon party if Town_Rep becomes Hated
      NOption(g_mstr(10007),Node999,001);             // Predefined generic messages in GENERIC.MSG
   end else begin
      end_party_waiting;
      Reply(random(5330,5331));                         // Random dialogue greetings
      party_member_default_options;
   end
end

// TODO
procedure dead_jermiah
begin
floater_rand(200,200);
end

procedure Node001
begin
Reply(230);
NOption(231,Node002,4);
BOption(232,Node003,4);
BOption(233,Node004,4);
BOption(234,Node005,4);
NOption(2961,Node093,4);
NOption(2965,Node093,-3);
end

procedure Node002
begin
Reply(260);
NOption(261,Node006,4);
if (has_skill(dude_obj,SKILL_BARTER)>=75) then
NOption(262,Node007,4);
if (has_skill(dude_obj,SKILL_BARTER)<75) then
BOption(263,Node008,4);
if (has_skill(dude_obj,SKILL_CONVERSANT)>=75) then
NOption(264,Node009,4);
if (has_skill(dude_obj,SKILL_CONVERSANT)<75) then
BOption(265,Node010,4);
NOption(266,Node011,4);
end

procedure Node003
begin
Reply(290);
NOption(291,Node999,4);
end

procedure Node004
begin
Reply(320);
NOption(321,Node999,4);
end

procedure Node005
begin
if (dude_is_male) then Reply(350); else
if (dude_is_female) then Reply(351);
NOption(352,Node999,4);
end

// Node Node006
//
// Notes:
//
// [Quest Activates: Confront blackjack]

procedure Node006
begin

set_global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF, QUEST_ACCEPTED);
set_map_var(MVAR_Alexandra_Needs_Blackjack_Alive, 1);

Reply(380);
NOption(381,Node999,4);
end

// Node Node007
//
// Notes:
//
// [Quest Activates: Tell Black Jack Alexandra is off his tail.]

procedure Node007
begin
   set_global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF, QUEST_COMPLETED);
   set_global_var(GVAR_BLACKJACK_RESOLUTION, BLACKJACK_RESOLUTION_ALEXANDRA_GAVE_UP);
   display_mstr(150);
   give_xp(300);
Reply(410);
NOption(411,travel_to_fa,4);
end

procedure Node008
begin
Reply(440);
NOption(441,Node999,4);
end

// Node Node009
//
// Notes:
//
// [Quest Complete/Alexandra Joins Party]

procedure Node009
begin
   set_global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF, QUEST_COMPLETED);
   set_global_var(GVAR_BLACKJACK_RESOLUTION, BLACKJACK_RESOLUTION_ALEXANDRA_GAVE_UP);
   display_mstr(150);
   give_xp(300);
   call join_check;
end

procedure Node010
begin
Reply(500);
NOption(321,Node999,4);
end

procedure Node011
begin
Reply(530);
NOption(531,Node999,4);
end

// Node Node012
//
// Notes:
//
// For players that confront blackjack and agree to help him, they can return to Alexandra with her opening the following dialogue on their return from the cave:

procedure Node012
begin
Reply(560);
NOption(561,Node013,4);
if (has_skill(dude_obj,SKILL_CONVERSANT)>=75) then
NOption(562,Node014,4);
if (has_skill(dude_obj,SKILL_CONVERSANT)<75) then
NOption(563,Node015,4);
NOption(564,Node016,4);
NOption(565,Node017,4);
end

procedure Node013
begin
Reply(590);
if (item_caps_total(dude_obj)>=500) then
   NOption(591,Node018,4);
if (item_caps_total(dude_obj)<500) then
   NOption(592,Node019,4);
NOption(593,Node020,4);
end

// Node Node014
//
// Notes:
//
// [Quest Progress: Tell Blackjack Alexandra is no longer on his tail]

procedure Node014
begin
   set_global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF, QUEST_COMPLETED);
   set_global_var(GVAR_BLACKJACK_RESOLUTION, BLACKJACK_RESOLUTION_ALEXANDRA_GAVE_UP);
   display_mstr(150);
   give_xp(300);
Reply(620);
NOption(411,travel_to_fa,4);
end

procedure Node015
begin
Reply(650);
NOption(441,Node999,4);
end

procedure Node016
begin
Reply(680);
NOption(681,Node999,4);
end

procedure Node017
begin
Reply(710);
NOption(711,Node999,1);
NOption(2965,Node093,-3);
end

// Node Node018
//
// Notes:
//
// [Quest Progress: Tell Blackjack Alexandra is no longer on his tail]

procedure Node018
begin
   set_global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF, QUEST_COMPLETED);
   set_global_var(GVAR_BLACKJACK_RESOLUTION, BLACKJACK_RESOLUTION_PAID_OFF);
   item_caps_adjust(dude_obj, -500);
   display_mstr(150);
   give_xp(300);
Reply(740);
NOption(411,travel_to_fa,4);
end

procedure Node019
begin
Reply(770);
NOption(771,Node999,4);
end

procedure Node020
begin
Reply(800);
NOption(801,Node999,4);
end

// Node Node021
//
// Notes:
//
// Players that convince Blackjack to surrender can do so by either persuasion or calling out his bluff of the fake minigun. For either pathway, the following will occur when players guide blackjack out:

procedure Node021
begin


display_mstr(151);
give_xp(300);

Reply(830);
NOption(831,Node022,4);
// NOTE: Player knows about fake minigun
if (map_var(MVAR_Knows_Blackjack_Fake_Minigun) == 1) then begin
   NOption(832,Node023,4);
end
NOption(833,Node024,4);
NOption(834,Node025,4);
end

// Node Node022
//
// Notes:
//
// Teleport to Fort Abandon

procedure Node022
begin
Reply(860);
NOption(861,travel_to_fa,4);
end

procedure travel_to_fa begin
   fadeout(1);
   set_obj_visibility(self_obj, 1);
   variable Blackjack = tile_contains_pid_obj(25310, self_elevation, PID_BLACKJACK);
   if (Blackjack != 0) then begin
      set_obj_visibility(Blackjack, 1);
   end
   set_global_var(GVAR_MEET_ALEXANDRA_AT_FA, 1);
   set_global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF, QUEST_COMPLETED);
   fadein(1);
   call Node999;
end

// Node Node023
//
// Notes:
//
// Teleport to Fort Abandon

procedure Node023
begin
Reply(890);
NOption(861,travel_to_fa,4);
end

// Node Node024
//
// Notes:
//
// Teleport to Fort Abandon

procedure Node024
begin
Reply(920);
NOption(861,travel_to_fa,4);
end

// Node Node025
//
// Notes:
//
// Teleport to Fort Abandon

procedure Node025
begin
Reply(950);
NOption(861,travel_to_fa,4);
end

// Node Node026
//
// Notes:
//
// For players that cause a collapse of the cave, Alexandra will say the following:

procedure Node026
begin
Reply(980);
if (has_skill(dude_obj,SKILL_SNEAK)>=75) then
NOption(981,Node027,4);
if (has_skill(dude_obj,SKILL_SNEAK)<75) then
NOption(982,Node028,4);
NOption(983,Node029,4);
BOption(984,Node030,4);
end

procedure Node027
begin
Reply(1010);
NOption(531,Node999,4);
end

procedure Node028
begin
Reply(1040);
BOption(1041,Node998,4);
end

procedure Node029
begin
Reply(1070);
BOption(1041,Node998,4);
end

procedure Node030
begin
Reply(1100);
NOption(1101,Node999,4);
BOption(1102,Node998,4);
end

// Node Node031
//
// Notes:
//
// PC Bounty Hunter encounter

procedure Node031
begin
Reply(mstr(1130)+dude_name+mstr(1131));
   NOption(1132,Node032,4);
if (has_skill(dude_obj,SKILL_BARTER)>=75) then begin
   NOption(1133,join_check,4);
end
if (get_critter_stat(dude_obj,STAT_ch)>=6) then begin
   NOption(1134,Node034,4);
end
if (dude_is_female) then begin
   NOption(1135,Node035,4);
end
BOption(1136,Node998,4);
BOption(1137,Node998,4);
end

procedure Node032
begin
Reply(1160);
BOption(1136,Node998,4);
BOption(1137,Node998,4);
end

// Node Node034
//
// Notes:
//
// Alexandra joins the party

procedure Node034
begin
Reply(1220);
NOption(1221,Node999,4);
end

// Node Node035
//
// Notes:
//
// Alexandra joins the party

procedure Node035
begin
Reply(1250);
NOption(1251,Node999,4);
end

// Node Node036
//
// Notes:
//
// Alexandra speaking to the player after claiming the bounty of a cult leader:

procedure Node036
begin
Reply(1280);
// NOTE: +1 affinity
NOption(1281,Node037,4);
// NOTE: -1 aff
NOption(1282,Node038,4);
NOption(1283,Node039,4);
NOption(1284,Node040,4);
end

procedure Node037
begin
NMessage(1310);

end

procedure Node038
begin
NMessage(1340);
end

procedure Node039
begin
NMessage(1370);
end

procedure Node040
begin
NMessage(1400);
end

// Node Node041
//
// Notes:
//
// Alexandra speaking to the player after helping The Hands of God from Jeremiah Rigdon:

procedure Node041
begin
Reply(1430);
// NOTE: +1 aff
NOption(1431,Node042,4);
// NOTE: -1 aff
NOption(1432,Node043,4);
NOption(1433,Node044,4);
end

procedure Node042
begin
NMessage(1460);
end

procedure Node043
begin
NMessage(1490);
end

procedure Node044
begin
NMessage(1520);
end

// Node Node045
//
// Notes:
//
// Alexandra speaking to players after Kill Jeremiah quest activation:

procedure Node045
begin
Reply(1550);
NOption(1551,Node046,4);
NOption(1552,Node047,4);
NOption(1553,Node048,4);
NOption(1554,Node049,4);
end

procedure Node046
begin
Reply(1580);
NOption(1581,Node050,4);
NOption(1582,Node052,4);
NOption(1583,Node054,4);
NOption(1584,Node055,4);
end

// Node Node047
//
// Notes:
//
// +1 aff

procedure Node047
begin
NMessage(1610);
end

// Node Node048
//
// Notes:
//
// -1 aff

procedure Node048
begin
NMessage(1640);
end

procedure Node049
begin
NMessage(1670);
end

procedure Node050
begin
Reply(1700);
NOption(1701,Node051,4);
end

procedure Node051
begin
NMessage(1730);
end

procedure Node052
begin
Reply(1760);
NOption(1701,Node053,4);
end

procedure Node053
begin
NMessage(1790);
end

procedure Node054
begin
NMessage(1820);
end

procedure Node055
begin
NMessage(1850);
end

// Node Node056
//
// Notes:
//
// Once collecting the bounty from O'Conner, Alexandra will open dialogue with the player:

procedure Node056
begin
Reply(1880);
NOption(1881,Node057,4);
NOption(1882,Node058,4);
NOption(1883,Node059,4);
NOption(1884,Node060,4);
end

procedure Node057
begin
NMessage(1910);
end

// Node Node058
//
// Notes:
//
// +1 aff

procedure Node058
begin
NMessage(1940);
end

// Node Node059
//
// Notes:
//
// -1 aff

procedure Node059
begin
NMessage(1970);

end

procedure Node060
begin
NMessage(2000);

end

// Node Node061
//
// Notes:
//
// Focusing on the peaceful route, Alexandra will open dialogue with the player:

procedure Node061
begin
Reply(2030);
NOption(2031,Node062,4);
NOption(2032,Node063,4);
NOption(2033,Node064,4);
NOption(2034,Node065,4);
end

procedure Node062
begin
Reply(2060);
if (has_skill(dude_obj,SKILL_CONVERSANT)>=85) then
NOption(2061,Node066,4);
if (has_skill(dude_obj,SKILL_CONVERSANT)<85) then
NOption(2062,Node067,4);
// NOTE: [Charisma 9/High Affinity]
if (get_critter_stat(dude_obj,STAT_ch)>=9) then
NOption(2063,Node068,4);
// NOTE: [Charisma Fail/Low Affinity]
if (get_critter_stat(dude_obj,STAT_ch)<9) then
NOption(2064,Node069,4);
NOption(2065,Node070,4);
NOption(2066,Node071,4);
end

procedure Node063
begin
Reply(2090);
NOption(2061,Node066,4);
NOption(2062,Node067,4);
NOption(2063,Node068,4);
NOption(2064,Node069,4);
NOption(2065,Node070,4);
NOption(2066,Node071,4);
end

procedure Node064
begin
Reply(2120);
NOption(2061,Node066,4);
NOption(2062,Node067,4);
NOption(2063,Node068,4);
NOption(2064,Node069,4);
NOption(2065,Node070,4);
NOption(2066,Node071,4);
end

// Node Node065
//
// Notes:
//
//  [Leaves Party]

procedure Node065
begin
NMessage(2150);

end

// Node Node066
//
// Notes:
//
// +2 aff

procedure Node066
begin
NMessage(2180);

end

// Node Node067
//
// Notes:
//
// [Leaves Party]

procedure Node067
begin
NMessage(2210);

end

// Node Node068
//
// Notes:
//
// +2 aff

procedure Node068
begin
NMessage(2240);

end

// Node Node069
//
// Notes:
//
// -2 aff

procedure Node069
begin
NMessage(2270);

end

procedure Node070
begin
NMessage(2300);

end

// Node Node071
//
// Notes:
//
// [Leaves Party]

procedure Node071
begin
NMessage(2330);

end

// Node Node072
//
// Notes:
//
// Once reporting to O'Conner of a peaceful resolution, Alexandra will open dialogue with the player:  [High Affinity/Persuasion Outcome]

procedure Node072
begin
Reply(2360);
NOption(1881,Node074,4);
NOption(2361,Node075,4);
NOption(2362,Node076,4);
NOption(2363,Node077,4);
end

// Node Node073
//
// Notes:
//
// Once reporting to O'Conner of a peaceful resolution, Alexandra will open dialogue with the player: [Low Affinity = Leaves Party]

procedure Node073
begin
Reply(2390);
NOption(2391,Node999,4);
end

procedure Node074
begin
Reply(2420);
NOption(1701,Node078,4);
end

procedure Node075
begin
Reply(2450);
NOption(1701,Node078,4);
end

procedure Node076
begin
Reply(2480);
NOption(1701,Node078,4);
end

procedure Node077
begin
Reply(2510);
NOption(1701,Node078,4);
end

// Node Node078
//
// Notes:
//
// Regardless of dialogue outcome, this will unlock one of Alexandra's end perks: Blessed with the ending dialogue from this engagement:

procedure Node078
begin
NMessage(2540);

end

// Node Node079
//
// Notes:
//
// The following reactions Alexandra has will alternate based on success to deceive O'Conner:

procedure Node079
begin
Reply(2570);
if (get_critter_stat(dude_obj,STAT_ch)>=6) then
NOption(2571,Node080,4);
if (get_critter_stat(dude_obj,STAT_ch)<6) then
NOption(2572,Node081,4);
NOption(2573,Node082,4);
NOption(2574,Node083,4);
NOption(2575,Node084,4);
end

procedure Node080
begin
NMessage(2600);

end

procedure Node081
begin
NMessage(2630);

end

procedure Node082
begin
NMessage(2660);

end

procedure Node083
begin
NMessage(2690);

end

// Node Node084
//
// Notes:
//
// [Leaves Party]

procedure Node084
begin
NMessage(2720);

end

// Node Node085
//
// Notes:
//
// Once speaking with O'Conner again after the successful deception of destroying all of The Mormons, Alexandra will open dialogue with the player:  [High Affinity/Charisma Outcome]

procedure Node085
begin
Reply(2750);
NOption(2751,Node087,4);
NOption(2752,Node088,4);
NOption(2753,Node089,4);
end

// Node Node086
//
// Notes:
//
// Once speaking with O'Conner again after the successful deception of destroying all of The Mormons, Alexandra will open dialogue with the player: [Low Charisma = Leaves Party]

procedure Node086
begin
NMessage(2780);

end

procedure Node087
begin
Reply(2810);
NOption(1701,Node090,4);
end

procedure Node088
begin
Reply(2840);
NOption(1701,Node090,4);
end

procedure Node089
begin
Reply(2870);
NOption(1701,Node090,4);
end

// Node Node090
//
// Notes:
//
// Regardless of dialogue outcome, this will unlock one of Alexandra's end perks: Fallen with the ending dialogue from this engagement:

procedure Node090
begin
NMessage(2900);

end

// Node Node091
//
// Notes:
//
// For a failure to pull off a Deception on O'Conner, Alexandra will say the following float:

procedure Node091
begin
NMessage(2930);

end

procedure Node092 begin
   Reply(2960);
   NOption(2961,Node093,4);
   NOption(2962,Node094,4);
   NOption(2963,Node999,4);
end

procedure Node093 begin
   if (cur_town == AREA_MESA_VERDE) or (cur_town == AREA_MESA_VERDE_SHADOW_MAPS) then begin
      Reply(2991);
   end
   else if (cur_town == AREA_HOOVER_DAM) or (cur_town == AREA_HOOVER_DAM_SHADOW_MAPS) then begin
      Reply(2992);
   end
   else if (cur_town == AREA_FORT_ABANDON) then begin
      Reply(2993);
   end
   // TODO before after sacking
   else if (cur_town == AREA_JERICHO) then begin
      Reply(2994);
   end
   // TODO before after sacking
   else if (cur_town == AREA_NEW_CANAAN) then begin
      Reply(2995);
   end
   else if (cur_town == AREA_DOGTOWN) then begin
      Reply(2996);
   end
   else if (cur_town == AREA_THE_RESERVATION) then begin
      Reply(2997);
   end
   else if (cur_town == AREA_BLACKFOOT) then begin
      Reply(2998);
   end
   else begin
      Reply(2990);
   end

   NOption(2964,Node999,4);
   NOption(2966,Node999,-3);
end


procedure Node094 begin
   item_caps_adjust(dude_obj, 250);
   Reply(2320);
   NOption(1133,join_check,4);
   NOption(2964,Node999,4);
end

//xxxxxxxxxxxxxxxxxxxx
