/*

        Name:           Blackjack
        Location:
        Description:

           Created: 28.12.2023. 13:32:35

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"

#define NAME                    SCRIPT_MVBLKJCK

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_TIBBETS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\headers\mvcanyo3.h"
#include "..\HEADERS\footsteps.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure combat_is_starting_p_proc;
procedure LeaveCave;
procedure FleeOutside;
procedure FleeOutsideDialog;
procedure BlackjackTricked;

/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_FleeOutside                (8)


/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */

/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_RND_TIBBETS_PRISONERS);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_SUPER_MUTANT);

   if ((global_var(GVAR_BLACKJACK_DEAD) == 1) and (cur_map_index == MAP_MESA_VERDE_CANYON_SOUTH_CAVE)) then begin
      set_obj_visibility(self_obj, 1);
      destroy_object(self_obj);
   end

   if (global_var(GVAR_BLACKJACK_GIVE_PIPBOY) == 1) then begin
      remove_pid_qty(self_obj, PID_BLACKJACK_LIL_PIP_3000, 1)
   end

   call critter_setup_footsteps_map_enter(self_obj, WALKING_TICKS_SLOWER, RUNNING_TICKS_DEFAULT);

   add_timer_event(self_obj,game_ticks(random(1,3)),0);

end

// AI goes crazy if he keeps wielding the fake weapon so we have to remove it
procedure combat_is_starting_p_proc begin
   if (obj_pid(critter_inven_obj(self_obj, INVEN_TYPE_RIGHT_HAND)) == PID_BLACKJACK_MINIGUN) then begin
      unwield_slot(self_obj, INVEN_TYPE_RIGHT_HAND);
   end
end

/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((global_var(GVAR_MEET_ALEXANDRA_AT_FA) == 1) and (global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF) == QUEST_COMPLETED)) then begin
      if (obj_is_visible_flag(self_obj)) then begin
         set_obj_visibility(self_obj, 1);
      end
      destroy_object(self_obj);
   end

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;


   if (global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF) == ALEXANDRA_BLACKJACK_TRICKED) then begin
      floater_sad(152);
   end
   else if ((Alexandra_Ptr != 0) and Alexandra_In_Party and obj_can_see_obj(self_obj, Alexandra_Ptr)) then begin
      floater_bad(150);
      call Node998;
   end
   else begin

      call set_idiot_savant_int;

         start_gdialog(NAME,self_obj,4,HEAD_BLACKJACK,BACKGROUND_CAVE);
         gSay_Start;

         if (local_var(LVAR_Herebefore) == 1) then begin
            call Node012;
         end
         else begin
            call Node001;
         end
         gSay_End;
         end_dialogue;

      call restore_idiot_savant_int;
   end

   if (local_var(LVAR_FleeOutside) == 1) then begin
      set_local_var(LVAR_FleeOutside, 0);
      call FleeOutside;
   end

end

procedure timed_event_p_proc begin

   if (fixed_param == 0) then begin
      // Exit cave tile
      if (self_tile == 20138) then begin
         set_global_var(GVAR_BLACKJACK_GONE, 1);
         if (global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF) == ALEXANDRA_BLACKJACK_TRICKED) then begin
            // Move Blackjack next to Alexandra
            fadeout(1);
            move_to(self_obj, 25310, 0);
            critter_attempt_placement(self_obj, 25310, 0);
            fadein(1);
         end
         else begin
            set_global_var(GVAR_BLACKJACK_RESOLUTION, BLACKJACK_RESOLUTION_ESCAPED);
            set_obj_visibility(self_obj, 1);
            destroy_object(self_obj);
         end
      end
      add_timer_event(self_obj,game_ticks(random(1,3)),0);
   end

   call critter_setup_footsteps_timed_event(self_obj, WALKING_TICKS_SLOWER, RUNNING_TICKS_DEFAULT, SFX_FOOTSTEP_HARD_SHOE);
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin
/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
   set_global_var(GVAR_BLACKJACK_GONE, 1);
   set_global_var(GVAR_BLACKJACK_DEAD, 1);
   set_global_var(GVAR_BLACKJACK_RESOLUTION, BLACKJACK_RESOLUTION_NONE);
   //give_pid_qty(self_obj, PID_DECK_OF_CARDS, 1)
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   if (global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF) == ALEXANDRA_BLACKJACK_TRICKED) then begin
      display_mstr(103);
   end else begin
      display_mstr(102);
   end
   set_map_var(MVAR_Knows_Blackjack_Fake_Minigun, 1);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
   //debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
   if (local_var(LVAR_Herebefore)==0) then begin
      set_local_var(LVAR_Herebefore,1);
   end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
   set_global_var(GVAR_KNOW_LOCATION_BLACKJACK, 1);
   Reply(200);
   if (map_var(MVAR_Knows_Blackjack_Fake_Minigun) == 1) then begin
      NOption(mstr(201) + " " + mstr(202),Node002,4);
   end
   else begin
      NOption(202,Node002,4);
   end
end

procedure Node002
begin
Reply(230);
NOption(231,Node003,4);
end

procedure Node003
begin
Reply(260);
NOption(261,Node004,4);
end

procedure Node004
begin
Reply(290);
NOption(291,Node005,4);
end

procedure Node005
begin
Reply(320);
NOption(321,Node006,4);
if (global_var(GVAR_QUEST_FIND_BLACKJACK) < 2) then
NOption(322,Node007,4);
if (global_var(GVAR_BLACKJACK_GIVE_PIPBOY) == 0) then
NOption(323,Node008,4);
BOption(324,Node998,4);
NOption(325,Node014,4);
end

procedure Node006
begin
Reply(350);
NOption(351,Node999,4);
end

procedure Node007
begin
Reply(380);
NOption(381,Node009,4);
BOption(382,Node998,4);
end

procedure Node008
begin
Reply(410);
NOption(411,Node010,4);
end

procedure Node009
begin
Reply(440);
if (global_var(GVAR_BLACKJACK_GIVE_PIPBOY) == 0) then
NOption(441,Node008,4);
BOption(442,Node998,4);
end

procedure Node010
begin
Reply(470);
NOption(471,Node011,4);
BOption(472,Node998,4);
end

procedure Node011
begin

   transfer_pid_between_objs(self_obj, dude_obj, PID_BLACKJACK_LIL_PIP_3000, 1)
   game_time_advance(ONE_GAME_HOUR);
   // TODO Broken
   //give_pid_qty(dude_obj, PID_DECK_OF_CARDS, 1)
   //display_mstr(151);

Reply(500);
NOption(501,LeaveCave,4);
end

procedure Node012
begin
Reply(530);
if (
   (global_var(GVAR_ALEXANDRA_DEAD) == 1) or
   (global_var(GVAR_BLACKJACK_RESOLUTION) == BLACKJACK_RESOLUTION_PAID_OFF) or
   (global_var(GVAR_BLACKJACK_RESOLUTION) == BLACKJACK_RESOLUTION_ALEXANDRA_GAVE_UP) or
   (dude_skill(SKILL_CONVERSANT) >= 50)
) then begin
   if (dude_skill(SKILL_CONVERSANT) >= 50) then begin
      NOption(531,BlackjackTricked,4);
   end
   else begin
      NOption(531,Node013,4);
   end
end
NOption(532,Node999,4);
BOption(533,Node998,4);
if ((global_var(GVAR_ALEXANDRA_DEAD) == 0) and (map_var(MVAR_Knows_Blackjack_Fake_Minigun) == 1)) then begin
   NOption(534,Node016,4);
end
end

procedure BlackjackTricked begin
   set_global_var(GVAR_BLACKJACK_RESOLUTION, BLACKJACK_RESOLUTION_TRICKED);
   set_global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF, ALEXANDRA_BLACKJACK_TRICKED);
   call Node013;
end

procedure Node013
begin
   give_pid_qty(dude_obj, PID_GUTS_STEW, 6)
   give_pid_qty(dude_obj, PID_DESERT_SALAD, 5)
Reply(560);
NOption(561,FleeOutsideDialog,4);
end

procedure Node014
begin
Reply(590);
if (map_var(MVAR_Alexandra_Needs_Blackjack_Alive) == 1) then begin
   NOption(591,Node015,4);
end
NOption(592,Node999,4);
end

procedure Node015
begin
Reply(620);
NOption(621,FleeOutsideDialog,4);
end

procedure Node016
begin
   set_global_var(GVAR_BLACKJACK_RESOLUTION, BLACKJACK_RESOLUTION_TRICKED);
   set_global_var(GVAR_QUEST_ALEXANDRA_BLACKJACK_STANDOFF, ALEXANDRA_BLACKJACK_TRICKED);
Reply(650);
NOption(651,FleeOutsideDialog,4);
end

//xxxxxxxxxxxxxxxxxxxx

procedure LeaveCave begin
   fadeout(1);
   set_obj_visibility(self_obj, 1);
   fadein(1);
   set_global_var(GVAR_BLACKJACK_GONE, 1);
   call Node999;
end

procedure FleeOutside begin
   variable animation = ANIMATE_RUN;
   if (map_var(MVAR_Knows_Blackjack_Fake_Minigun) == 1) then begin
      animation = ANIMATE_WALK;
   end

   animate_move_obj_to_tile(self_obj, 20138, (animation bwor ANIMATE_INTERRUPT));
end

procedure FleeOutsideDialog begin
   set_local_var(LVAR_FleeOutside, 1);
   call Node999;
end
