/*******************************************************************************
        Name:
        Location:
        Description: Object template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"

#define NAME                    SCRIPT_MVCAVHOL

#define LVAR_Used_No_Rope_Avg_IQ              (0)

/* Standard Script Procedures */
procedure start;
procedure use_p_proc;
procedure use_obj_on_p_proc;

/* Defines */


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin
end

procedure use_p_proc begin
   // warn before fall
   if (not(dude_is_stupid) and (local_var(LVAR_Used_No_Rope_Avg_IQ) == 0)) then begin
      display_mstr(101);
      set_local_var(LVAR_Used_No_Rope_Avg_IQ, 1);
   end
   // stupid player falls down without rope or normal INT player on second use
   else begin
      set_global_var(GVAR_MVCAVES_FREEFALL, 1);
      load_map("mvcaves", 0);
   end
end

procedure use_obj_on_p_proc begin

   if (obj_pid(obj_being_used_with) == PID_ROPE) then begin
      script_overrides;
      fadeout(1);
      set_obj_visibility(self_obj, 1);
      move_to(obj_blocking_tile(11125, self_elevation, BLOCKING_TYPE_BLOCK), self_tile, self_elevation);
      remove_pid_qty(dude_obj, PID_ROPE, 1)
      game_time_advance(ONE_GAME_MINUTE * 10);
      fadein(1);
      give_xp(50);
      display_mstr(100);
      set_global_var(GVAR_MVCAVES_ROPE, 1);
   end

end
