/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/* Random Encounter scripts. These will be filled in more once they
   have been designed.
*/

procedure start;

#include "..\headers\define.h"

#define NAME                    SCRIPT_MVCHICKN

#include "..\headers\command.h"
#include "..\headers\party.h"

procedure start;
procedure destroy_p_proc;
procedure critter_p_proc;
procedure map_enter_p_proc;
procedure combat_p_proc;
procedure map_exit_p_proc;
procedure use_skill_on_p_proc;
procedure timed_event_p_proc;

variable starttile := 0;

procedure map_enter_p_proc begin
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_CIPHERS);
   starttile := self_tile;
   reg_anim_clear(self_obj);
   reg_anim_begin();
   animate_rotation(Random(0, 5));
   reg_anim_end();
   critter_set_flee_state(self_obj, false);
   add_timer_event(self_obj,game_ticks(random(5,10)),0);
end

procedure map_exit_p_proc begin
   call BeastlordUnpossess(TEAM_CIPHERS);
end

procedure start begin
end

procedure critter_p_proc begin
   if (not(critter_is_fleeing(self_obj)) and self_can_see_dude) then begin
      critter_set_flee_state(self_obj, true);
   end
   else if (critter_is_fleeing(self_obj) and not(self_can_see_dude)) then begin
      critter_set_flee_state(self_obj, false);
   end
end

procedure description_p_proc begin
   call BeastlordPossess;
end

procedure combat_p_proc begin
   critter_set_flee_state(self_obj, true);
end

procedure destroy_p_proc begin
/* Increment the aligned critter counter*/
   inc_neutral_critter
end

procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

procedure timed_event_p_proc begin
   if ((fixed_param == 0) and (not(combat_is_initialized)) and ((critter_state(self_obj) bwand DAM_KNOCKED_OUT) == FALSE)) then begin
      reg_anim_clear(self_obj);
      reg_anim_begin();
      if (critter_is_fleeing(self_obj)) then begin
         animate_run_to_tile(tile_num_in_direction(self_tile, Random(0, 5), Random(5, 15)));
      end else begin
         animate_move_to_tile(tile_num_in_direction(starttile, Random(0, 5), Random(1, 5)));
      end
      reg_anim_end();

      if (random(1, 3) == 1) then begin
         floater_sfx_rand(100, 108);
      end

   end

   add_timer_event(self_obj,game_ticks(random(5,10)),0);
end
