/*

        Name:           Radian
        Location:
        Description:

           Created: 16.9.2024. 21:21:37

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"

#define NAME                    SCRIPT_MVRADIAN

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_MESA_VERDE)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
//#include "..\HEADERS\<TownName.h>"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_CIPHERS);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_CIPHER);

   // Not cured, Agility is 2
   if (
      ((cur_town == AREA_MESA_VERDE) or (cur_town == AREA_MESA_VERDE_SHADOW_MAPS)) and
      (self_agility == 5) and
      (global_var(GVAR_RADIAN_RESOLUTION) == RADIAN_ADDICTED)
   ) then begin
      set_critter_stat(self_obj, STAT_ag, 2);
   end
end

/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if (((global_var(GVAR_ENEMY_MESA_VERDE) == 1) or (local_var(LVAR_Hostile) != 0)) and self_can_see_dude) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
       set_global_var(GVAR_ENEMY_MESA_VERDE, 1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

   start_gdialog(NAME,self_obj,4,-1,-1);
   gSay_Start;

   if (global_var(GVAR_RADIAN_RESOLUTION) == RADIAN_CURED) then begin
      call Node003;
   end else if (global_var(GVAR_RADIAN_RESOLUTION) == RADIAN_ADDICTED) then begin
      call Node004;
   end else if (local_var(LVAR_Herebefore)==0) then begin
      call Node001;
   end else if (local_var(LVAR_Herebefore)==1) then begin
      call Node002;
   end

   gSay_End;
   end_dialogue;

   call restore_idiot_savant_int;
end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_neutral_critter

/* Set global_variable for Enemy status*/
set_global_var(GVAR_RADIAN_RESOLUTION, RADIAN_DEAD);
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
Reply(200);
NOption(201,Node005,4);
NOption(202,Node005,-3);
NOption(203,Node999,4);
NOption(204,Node999,-3);
end

procedure Node002
begin
   Reply(230);
   NOption(291,Node018,4);
   NOption(292,Node018,-3);
   NOption(293,Node006,4);
   NOption(294,Node006,-3);
   NOption(295,Node009,4);
   NOption(203,Node999,4);
   NOption(204,Node999,-3);
end

procedure Node003
begin
   Reply(260);
   NOption(291,Node018,4);
   NOption(292,Node018,-3);
   NOption(203,Node999,4);
   NOption(204,Node999,-3);
end

procedure Node004
begin
Reply(290);
NOption(291,Node018,4);
NOption(292,Node018,-3);
if (obj_is_carrying_obj_pid(dude_obj,PID_DOCTORS_BAG)>0) then begin
   NOption(296,Node010,4);
end
NOption(203,Node999,4);
NOption(204,Node999,-3);
end

procedure Node005
begin
Reply(320);
NOption(321,Node018,4);
NOption(322,Node006,4);
NOption(292,Node018,-3);
NOption(294,Node006,-3);
end

procedure Node006
begin

   if (global_var(GVAR_QUEST_CURE_RADIAN) == QUEST_NONE) then begin
      set_global_var(GVAR_QUEST_CURE_RADIAN, QUEST_KNOWN);
   end

Reply(350);
if (has_skill(dude_obj,SKILL_DOCTOR)>=50) then begin
   NOption(351,Node007,4);
   NOption(352,Node021,-3);
end

NOption(353,Node018,4);
NOption(354,Node018,-3);
end

procedure Node007
begin
Reply(380);
NOption(381,Node008,4);
end

procedure Node008
begin
Reply(410);
   if (obj_is_carrying_obj_pid(dude_obj,PID_DOCTORS_BAG)>0) then begin
      NOption(411,Node009,4);
   end
   else begin
      NOption(412,Node022,4);
   end
end

procedure Node009
begin
Reply(440);
NOption(441,Node017,4);
NOption(442,Node015,4);
end

procedure Node010
begin
Reply(470);
NOption(471,Node011,4);
if (global_var(GVAR_QUEST_SABOTAGE_WIND_TURBINE) == QUEST_ACCEPTED) then begin
   NOption(472,Node012,4);
end
end

procedure Node011
begin
Reply(500);
NOption(501,Node024,4);
if (global_var(GVAR_QUEST_SABOTAGE_WIND_TURBINE) == QUEST_ACCEPTED) then begin
   NOption(502,Node012,4);
end
end

procedure Node012
begin
Reply(530);
NOption(531,Node013,4);
end

procedure Node013
begin
if (dude_is_male) then Reply(560); else
if (dude_is_female) then Reply(561);
NOption(562,Node014,4);
end

procedure Node014
begin
Reply(590);
NOption(591,Node023,4);
end

procedure Node015
begin

   fadeout(1);
   remove_pid_qty(dude_obj, PID_DOCTORS_BAG, 1)
   fadein(1);

   set_global_var(GVAR_RADIAN_RESOLUTION, RADIAN_ADDICTED);
   set_global_var(GVAR_QUEST_CURE_RADIAN, QUEST_COMPLETED);
   display_mstr(151);
   give_xp(EXP_CIPHERS_ADDICT_RADIAN);
   dec_mesa_verde_rep(REP_MESA_VERDE_ADDICT_RADIAN);

Reply(620);
NOption(621,Node016,4);
end

procedure Node016
begin
Reply(650);
NOption(651,Node999,4);
end

procedure Node017
begin

   fadeout(1);
   remove_pid_qty(dude_obj, PID_DOCTORS_BAG, 1)
   fadein(1);

   set_global_var(GVAR_QUEST_CURE_RADIAN, QUEST_COMPLETED);
   set_global_var(GVAR_RADIAN_RESOLUTION, RADIAN_CURED);
   display_mstr(150);
   give_xp(EXP_CIPHERS_CURE_RADIAN);
   inc_mesa_verde_rep(REP_MESA_VERDE_CURE_RADIAN);

Reply(680);
NOption(651,Node999,4);
end

procedure Node018
begin
   if (global_var(GVAR_RADIAN_RESOLUTION) == RADIAN_CURED) then begin
      Reply(740);
   end else if (global_var(GVAR_RADIAN_RESOLUTION) == RADIAN_ADDICTED) then begin
      Reply(770);
   end else begin
      Reply(710);
   end

NOption(203,Node999,4);
NOption(204,Node999,-3);
end

procedure Node021
begin
Reply(800);
NOption(801,Node018,-3);
NOption(204,Node999,-3);
end

procedure Node022
begin
Reply(830);
NOption(831,Node018,4);
NOption(203,Node999,4);
end

procedure Node023
begin

   fadeout(1);
   game_time_advance(ONE_GAME_HOUR);

   if (global_var(GVAR_QUEST_SABOTAGE_WIND_TURBINE) != QUEST_COMPLETED) then begin
      set_global_var(GVAR_QUEST_SABOTAGE_WIND_TURBINE, QUEST_COMPLETED);
      give_xp(EXP_SABOTAGE_WIND_TURBINE);
      display_mstr(152);
   end

   fadein(1);

Reply(860);
NOption(861,Node025,4);
end

procedure Node024
begin
Reply(890);
NOption(891,Node025,4);
if (global_var(GVAR_QUEST_SABOTAGE_WIND_TURBINE) == QUEST_ACCEPTED) then begin
   NOption(892,Node012,4);
end
end

procedure Node025
begin
   remove_pid_qty(dude_obj, PID_DOCTORS_BAG, 1)
Reply(920);
NOption(203,Node999,4);
end

// TODO ACT 3 Radian in Hoover Dam
procedure Node026
begin
Reply(950);
NOption(951,Node028,4);
end

procedure Node027
begin
Reply(980);
NOption(981,Node029,4);
end

procedure Node028
begin
Reply(1010);
NOption(1011,Node029,4);
NOption(1012,Node030,4);
end

procedure Node029
begin
Reply(1040);
NOption(1041,Node001,4);
NOption(1042,Node001,4);
end

procedure Node030
begin
NMessage(1070);
set_local_var(LVAR_Herebefore,1);
end



//xxxxxxxxxxxxxxxxxxxx
