/*
        Name:
        Location: CIPHERS
        Description:

        Log:

           Created:

           Updated:
*/

/* Include Files */
#include "..\headers\define.h"
#include "..\HEADERS\updatmap.h"

#define NAME                    SCRIPT_MVCIPHER
#define TOWN_REP_VAR            GVAR_TOWN_REP_MESA_VERDE

#include "..\headers\command.h"
#include "..\HEADERS\party.h"
#include "..\HEADERS\mvtop.h"
#include "..\headers\footsteps.h"

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure map_update_p_proc;
procedure combat_p_proc;
procedure push_p_proc;
procedure leave_player;

/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure Node001;
procedure Node002;
procedure NodeFleeing;

/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */

#define LVAR_Flags                     (0)
#define LVAR_Home_Tile                 (1)
#define LVAR_Home_Rot                  (2)
#define LVAR_Leave_Time                (3)
#define LVAR_Follow_Dude                (8)

#define attempt_alarm_bit              bit_10

#define attempt_alarm                  (lvar_bit(LVAR_Flags, attempt_alarm_bit))
#define set_attempt_alarm              set_lvar_bit_on(LVAR_Flags, attempt_alarm_bit)
#define off_attempt_alarm              set_lvar_bit_off(LVAR_Flags, attempt_alarm_bit)

#define raider_add_timer_event(obj, sec, param)          rm_fixed_timer_event(obj, param);               \
                                                         add_timer_event(obj, game_ticks(sec), param)
#define raider_add_timer_event_rand(obj, x, y, param)    raider_add_timer_event(obj, random(x, y), param)


#define TAUNT_CHANCE 20

import variable Cipher_WarriorA_Ptr;

variable newtile;

procedure start begin
   Cipher_WarriorA_Ptr = self_obj;
end

procedure timed_event_p_proc begin
   if (fixed_param == 1) then begin
      if (self_can_speak and (random(1, 100) <= TAUNT_CHANCE)) then begin
         call Node002;
      end
      raider_add_timer_event_rand(self_obj, 20, 35, 1);
   end
   else if (fixed_param == 2) then begin
      if (self_can_speak and (local_var(LVAR_Follow_Dude) == 0)) then begin
         if (self_tile != local_var(LVAR_Home_Tile)) then begin
            animate_move_to_tile(local_var(LVAR_Home_Tile));
         end else begin
            animate_move_to_tile(tile_num_in_direction(self_tile, local_var(LVAR_Home_Rot), random(3, 5)));
         end
      end
      raider_add_timer_event_rand(self_obj, 15, 45, 2);
   end
   call critter_setup_footsteps_timed_event(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT, SFX_FOOTSTEP_SOFT_SHOE);
end

procedure map_enter_p_proc begin

   if(cur_map_index != MAP_MESA_VERDE_TOP) then begin
      call leave_player;
   end

   if (is_loading_game == false) then begin
      if (map_first_run) then begin
         set_local_var(LVAR_Home_Tile, self_tile);
         set_local_var(LVAR_Home_Rot, self_cur_rot);
         critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_CIPHERS);
         critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_CIPHER);
      end
      raider_add_timer_event_rand(self_obj, 20, 35, 1);
      raider_add_timer_event_rand(self_obj, 5, 45, 2);
      call critter_setup_footsteps_map_enter(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT);
      Cipher_WarriorA_Ptr = self_obj;
   end
end

procedure map_update_p_proc begin
   Cipher_WarriorA_Ptr = self_obj;
end

procedure combat_p_proc begin
   if (critter_is_fleeing(self_obj)) then begin
      if (random(1, 100) <= TAUNT_CHANCE) then begin
         call NodeFleeing;
      end
   end else begin
      if (random(1, 100) <= TAUNT_CHANCE) then begin
         call Node001;
      end
   end
end

procedure critter_p_proc begin

   if ((global_var(GVAR_QUEST_KILL_WEEDLINGS) == QUEST_ACCEPTED) and (TEAM_CIPHERS == has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM))) then begin
      switch_team(self_obj, TEAM_PLAYER)
      set_local_var(LVAR_Follow_Dude, 1);
   end
   else if ((global_var(GVAR_QUEST_KILL_WEEDLINGS) == QUEST_COMPLETED) and (TEAM_PLAYER == has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM))) then begin
      switch_team(self_obj, TEAM_CIPHERS)
      set_local_var(LVAR_Follow_Dude, 0);
   end

   if (local_var(LVAR_Follow_Dude) == 1) then begin
      if (map_var(MVAR_Total_Weedlings_Killed) == 8) then begin
         call leave_player;
         dialogue_system_enter;
      end
      else begin
         if (self_elevation != dude_elevation) then begin
            newtile := tile_num_in_direction(dude_tile, random(0, 5), 3);
            critter_attempt_placement(self_obj,newtile,dude_elevation);
         end
         else if (tile_distance(self_tile,dude_tile) > 6) then begin
            newtile := tile_num_in_direction(dude_tile, random(0, 5), 3);
            if(dude_is_sneaking) then begin
               animate_move_to_tile(newtile);
            end
            else begin
               animate_run_to_tile(newtile);
            end
         end
      end
   end//follow
   else if ((local_var(LVAR_Follow_Dude) == 0) and (anim_busy(self_obj) == false)) then begin
      if (self_tile == local_var(LVAR_Home_Tile)) then begin
         if (self_cur_rot != local_var(LVAR_Home_Rot)) then begin
            animate_rotation(local_var(LVAR_Home_Rot));
         end
      end else begin
         animate_rotation(rotation_to_tile(self_tile,local_var(LVAR_Home_Tile)));
      end
   end
end

procedure damage_p_proc begin
   if (source_obj == dude_obj) then begin
      set_personal_enemy;
   end
end

procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
      call Node998;
   end
end

procedure push_p_proc begin
end

procedure talk_p_proc begin
   call Node002;
end

procedure destroy_p_proc begin
   inc_good_critter
end

procedure look_at_p_proc begin
   script_overrides;
   display_mstr(100);
end

procedure description_p_proc begin
   script_overrides;
   if(self_is_male) then begin
      display_mstr_rand(150, 151);
   end
   else begin
      display_mstr_rand(152, 153);
   end
   set_examined;
end

procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

procedure Node998 begin
   if (hostile == false) then begin
      call Node001;
   end
   self_attack_dude;
   set_hostile;
end

procedure Node999 begin
end

procedure Node001 begin
   floater_bad_rand(200, 230);
end

procedure Node002 begin
   floater_rand(250, 279);
end

procedure NodeFleeing begin
   floater_afraid_rand(300, 309);
end

procedure leave_player begin
   if (local_var(LVAR_Follow_Dude) == 1) then begin
      switch_team(self_obj,TEAM_CIPHERS)
      set_local_var(LVAR_Follow_Dude, 0);
   end
end
