/*

        Name:           Drake
        Location:
        Description:

           Created: 21.8.2024. 20:38:54

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"

#define NAME                    SCRIPT_MVDRAKE

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_OUROBOROS)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\HEADERS\mvhounds.h"
#include "..\headers\footsteps.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure Skill_Check_000_Speech;




// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Reward_Turbine             (8)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_HOUNDS_MESA_VERDE);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
   add_timer_event(self_obj,game_ticks(1),0);

   if (global_var(GVAR_MESA_HOUNDS_RESOLUTION) == DEAL_WITH_HOUNDS_LEFT) then begin
      set_obj_visibility(self_obj, 1);
      destroy_object(self_obj);
   end

   if (
      (global_var(GVAR_MESA_HOUNDS_RESOLUTION) == DEAL_WITH_HOUNDS_BLASTED)
      ) then begin
      critter_heal(self_obj, -10000);
   end
   else if (global_var(GVAR_MESA_HOUNDS_RESOLUTION) == DEAL_WITH_HOUNDS_POISONED) then begin
      critter_heal(self_obj, -100);
   end

   call critter_setup_footsteps_map_enter(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT);
end

/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and self_can_see_dude) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_PROUD;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

   start_gdialog(NAME,self_obj,4,-1,-1);
   gSay_Start;

   if (
      (global_var(GVAR_MESA_HOUNDS_RESOLUTION) == DEAL_WITH_HOUNDS_CRUSHED)
      ) then begin
         call Node023;
   end
   else if (local_var(LVAR_Herebefore)==0) then begin
      call Node001;
   end
   else if ((local_var(LVAR_Reward_Turbine) == 0) and (global_var(GVAR_QUEST_SABOTAGE_WIND_TURBINE) >= QUEST_ACCEPTED)) then begin
      call Node003;
   end else if (local_var(LVAR_Herebefore)==1) then begin
      call Node002;
   end

   gSay_End;
   end_dialogue;

   call restore_idiot_savant_int;
end

procedure timed_event_p_proc begin

   if (fixed_param == 0) then begin
      if(local_var(LVAR_Herebefore) == 0) then begin
         if (self_can_see_dude and self_can_speak) then begin
            dialogue_system_enter;
         end
         add_timer_event(self_obj,game_ticks(1),0);
      end
   end

   call critter_setup_footsteps_timed_event(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT, SFX_FOOTSTEP_MEDIUM_BAREFOOT);

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
 inc_neutral_critter
inc_map_var(MVAR_Total_Hounds_Killed);

/* Set global_variable for Enemy status*/
   if (map_var(MVAR_Total_Hounds_Killed) >= 21) then begin
      if (global_var(GVAR_QUEST_DEAL_WITH_HOUNDS) != DEAL_WITH_HOUNDS_COMPLETED) then begin
         set_global_var(GVAR_QUEST_DEAL_WITH_HOUNDS, DEAL_WITH_HOUNDS_KILLED);
         if (global_var(GVAR_MESA_HOUNDS_RESOLUTION) == 0) then begin
            set_global_var(GVAR_MESA_HOUNDS_RESOLUTION, DEAL_WITH_HOUNDS_KILLED);
         end
         display_mstr(151);

         if (dude_is_stupid) then begin
            dude_floater(154);
         end
      end
   end
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

procedure Skill_Check_000_Speech begin
   variable roll_temp;
   roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -40);

   if is_success(roll_temp) then
   begin
      call Node017;
   end
   else begin
      call Node019;
   end
end

// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
Reply(200);
NOption(201,Node004,4);
NOption(202,Node004,-3);
BOption(203,Node998,4);
BOption(204,Node998,-3);
BOption(205,Node998,4);
BOption(206,Node998,-3);
end

procedure Node002
begin
Reply(230);
NOption(231,Node004,4);
NOption(232,Node004,-3);
if (dude_looks_like_daughter_of_hecate) then begin
   NOption(mstr(233) + " " + mstr(234),Node022,4);
end
else if ((dude_charisma >= 8) and (dude_skill(SKILL_CONVERSANT) >= 75) and dude_is_male) then begin
   NOption(mstr(233) + " " + mstr(235),Node021,4);
end
else if ((dude_charisma >= 6) and (dude_skill(SKILL_CONVERSANT) >= 50) and dude_is_female) then begin
   NOption(mstr(233) + " " + mstr(234),Node021,4);
end

NOption(205,Node999,4);
NOption(206,Node999,-3);
end

procedure Node003
begin
Reply(260);
if (global_var(GVAR_QUEST_SABOTAGE_WIND_TURBINE) == QUEST_ACCEPTED) then begin
   BOption(261,Node020,4);
   BOption(262,Node020,-3);
end
else if (global_var(GVAR_QUEST_SABOTAGE_WIND_TURBINE) == QUEST_COMPLETED) then begin
   GOption(263,Node016,4);
   GOption(264,Node016,-3);
end
NOption(265,Node013,4);
NOption(266,Node013,-3);
end

procedure Node004
begin
Reply(290);
NOption(291,Node007,4);
NOption(292,Node007,-3);
NOption(293,Node005,4);
NOption(294,Node005,-3);
NOption(295,Node010,4);
BOption(296,Node011,-3);
end

procedure Node005
begin
Reply(320);
NOption(321,Node006,4);
NOption(322,Node006,-3);
BOption(323,Node024,4);
BOption(324,Node024,-3);
end

procedure Node006
begin

if (dude_item(PID_LIL_PIP_3000)) then begin

   if(not(town_known(AreaNukeStatus(AREA_OUROBOROS)))) then begin
      give_xp(500);
      mark_on_map(AreaNukeStatus(AREA_OUROBOROS))
      display_msg(g_mstr(1008) + " " + mstr_map(1510) + ".");
   end

   Reply(350);
end else begin
   Reply(349);
end

NOption(351,Node010,4);
BOption(352,Node011,-3);
end

procedure Node007
begin
Reply(380);
NOption(381,Node008,4);
NOption(382,Node008,-3);
NOption(383,Node009,4);
NOption(384,Node009,-3);
end

procedure Node008
begin
Reply(410);
NOption(411,Node009,4);
NOption(412,Node009,-3);
NOption(351,Node010,4);
BOption(352,Node011,-3);
end

procedure Node009
begin
Reply(440);
NOption(441,Node012,4);
NOption(442,Node012,-3);
NOption(443,Node999,4);
NOption(444,Node999,-3);
end

procedure Node010
begin
Reply(470);
NOption(471,Node999,1);
end

procedure Node011
begin
Reply(500);
NOption(501,Node999,1);
end

procedure Node012
begin
Reply(530);
GOption(531,Node013,4);
GOption(532,Node013,-3);
end

procedure Node013
begin
Reply(560);
GOption(561,Node015,4);
GOption(562,Node015,-3);
BOption(563,Node014,4);
BOption(564,Node014,-3);
NOption(565,Node999,4);
NOption(566,Node999,-3);
end

procedure Node014
begin
Reply(590);
GOption(591,Node015,4);
GOption(592,Node015,-3);
BOption(593,Node998,4);
BOption(594,Node998,-3);
end

procedure Node015
begin

   if (global_var(GVAR_QUEST_SABOTAGE_WIND_TURBINE) == QUEST_NONE) then begin
      set_global_var(GVAR_QUEST_SABOTAGE_WIND_TURBINE, QUEST_ACCEPTED);
   end

Reply(620);
NOption(621,Node999,4);
NOption(622,Node999,-3);
end

procedure Node016
begin
Reply(650);
if (global_var(GVAR_ENEMY_MESA_VERDE) == 1) then begin
   NOption(651,Skill_Check_000_Speech,4);
   NOption(652,Skill_Check_000_Speech,-3);
   BOption(653,Node018,4);
   BOption(654,Node018,-3);
end else begin
   GOption(655,Node017,4);
   GOption(656,Node017,-3);
end
end

procedure Node017
begin

   if (local_var(LVAR_Reward_Turbine) == 0) then begin
      set_local_var(LVAR_Reward_Turbine, 1);
      critter_add_trait(dude_obj, TRAIT_PERK, PERK_gecko_skinning_perk, 1);
      give_xp(500);
      display_mstr(150);
   end

   if(not(town_known(AreaNukeStatus(AREA_OUROBOROS)))) then begin
      give_xp(500);
      mark_on_map(AreaNukeStatus(AREA_OUROBOROS))
      display_msg(g_mstr(1008) + " " + mstr_map(1510) + ".");
   end

Reply(680);
NOption(681,Node999,4);
NOption(682,Node999,-3);
end

procedure Node018
begin
Reply(710);
BOption(711,Node998,4);
BOption(712,Node998,-3);
end

procedure Node019
begin
Reply(740);
BOption(711,Node998,4);
BOption(712,Node998,-3);
end

procedure Node020
begin
Reply(770);
NOption(621,Node999,4);
NOption(622,Node999,-3);
end

procedure Node021
begin
if (dude_is_male) then begin
   Reply(800);
   NOption(803,Node022,4);
end else begin
   Reply(801);
   NOption(802,Node022,4);
end
end

procedure Node022
begin

   if (global_var(GVAR_QUEST_DEAL_WITH_HOUNDS) != DEAL_WITH_HOUNDS_COMPLETED) then begin
      set_global_var(GVAR_QUEST_DEAL_WITH_HOUNDS, DEAL_WITH_HOUNDS_LEFT);
      if (global_var(GVAR_MESA_HOUNDS_RESOLUTION) == 0) then begin
         set_global_var(GVAR_MESA_HOUNDS_RESOLUTION, DEAL_WITH_HOUNDS_LEFT);
      end

      if (dude_is_male) then begin
         display_mstr(153);
      end
      else begin
         display_mstr(152);
      end
   end

   if (dude_looks_like_daughter_of_hecate) then begin
      Reply(830);
   end
   else begin
      Reply(920);
   end
NOption(831,Node999,4);
end

procedure Node023
begin
Reply(860);
BOption(861,Node998,4);
BOption(862,Node998,-3);
end

procedure Node024
begin
Reply(890);
NOption(321,Node006,4);
NOption(322,Node006,-3);
end


//xxxxxxxxxxxxxxxxxxxx
