/*******************************************************************************
        Name:
        Location:
        Description: Object template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\mvhounds.h"

#define NAME                    SCRIPT_MVHNDCRT

/* Standard Script Procedures */
procedure start;
procedure description_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;

/* Defines */


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/

import variable Hound_Wagon_Watcher_Ptr;

/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/

procedure start begin
end

procedure description_p_proc begin
   script_overrides;
   display_mstr(100);
end

procedure use_obj_on_p_proc begin

   variable pid = obj_pid(obj_being_used_with);

   if (
      ((pid == PID_SCORPION_TAIL) or
      (pid == PID_POISONED_STIMPAK) or
      (pid == PID_POISONED_SUPER_STIMPAK)) and
      (map_var(MVAR_Poisoned_Supplies) < 2)
   ) then begin
      script_overrides;

      // Someone is watching this wagon and we have been caught
      if ((Hound_Wagon_Watcher_Ptr != 0) and obj_can_see_obj(Hound_Wagon_Watcher_Ptr, dude_obj)) then begin
         if (can_speak(Hound_Wagon_Watcher_Ptr)) then begin
            float_msg(Hound_Wagon_Watcher_Ptr, message_str(SCRIPT_GENERIC, random(3325, 3329)), FLOAT_COLOR_BAD);
         end
         if (not(is_critter_dead(Hound_Wagon_Watcher_Ptr))) then begin
            attack_setup(Hound_Wagon_Watcher_Ptr, dude_obj);
         end
      end
      else begin
         remove_pid_qty(dude_obj, pid, 1)
         inc_map_var(MVAR_Poisoned_Supplies);

         if (map_var(MVAR_Poisoned_Supplies) == 1) then begin
            display_mstr(101);
         end
         else if (map_var(MVAR_Poisoned_Supplies) == 2) then begin
            display_mstr(102);
            set_global_var(GVAR_MESA_HOUNDS_RESOLUTION, DEAL_WITH_HOUNDS_POISONED);
            set_global_var(GVAR_QUEST_DEAL_WITH_HOUNDS, DEAL_WITH_HOUNDS_POISONED);
            give_xp(300);
         end
      end
   end
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   if (action_being_used == SKILL_SCIENCE) then begin
      script_overrides;

      if(skill_success(source_obj, SKILL_SCIENCE, 0)) then begin
         display_mstr(103);
      end else begin
         display_mstr(105);
      end
   end
   else if (action_being_used == SKILL_TRAPS) then begin
      script_overrides;

      if(skill_success(source_obj, SKILL_TRAPS, 0)) then begin
         display_mstr(104);
      end else begin
         display_mstr(105);
      end
   end
end
