/*******************************************************************************
        Name:
        Location:
        Description: Object template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"

#define NAME                    SCRIPT_MVRADBRL

/* Standard Script Procedures */
procedure start;
procedure use_obj_on_p_proc;

/* Defines */


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin
end

procedure use_obj_on_p_proc begin

   if (obj_pid(obj_being_used_with) == PID_GEIGER_COUNTER) then begin
      script_overrides;
      display_mstr(100);
      variable tmp := play_sfall_sound("data\\sound\\SFX\\Geiger_Counter.wav", 0);

      if (global_var(GVAR_QUEST_DENOM_CROPS) < QUEST_COMPLETED) then begin
         set_global_var(GVAR_QUEST_DENOM_CROPS, QUEST_PAST_PART_1);
      end
   end
end
