/*

        Name:           Trig
        Location:
        Description:

           Created: 16.9.2024. 12:51:42

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"

#define NAME                    SCRIPT_MVTRIG

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_MESA_VERDE)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
//#include "..\HEADERS\<TownName.h>"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure Skill_Check_000_Barter;
procedure Skill_Check_001_Barter;

// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure floats;
procedure Node001;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node019a;
procedure Node020;
procedure Node021;
procedure Node021a;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node027a;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure build_trig_alarm;
procedure fix_cannon;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_HomeTile                   (8)
#define LVAR_Informed_Fixed_Cannon      (9)
#define LVAR_Inventions                 (10)
#define LVAR_No_Money                   (11)

#define TRIG_INVENTIONS_KNOWS           (1)
#define TRIG_INVENTIONS_NO_MONEY        (2)
#define TRIG_INVENTIONS_BOUGHT          (3)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_CIPHERS);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_CIPHER);
   add_timer_event(self_obj,game_ticks(random(1,5)),0);

   if(local_var(LVAR_HomeTile) == 0) then begin
      set_local_var(LVAR_HomeTile, self_tile);
   end
end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if (((global_var(GVAR_ENEMY_MESA_VERDE) == 1) or (local_var(LVAR_Hostile) != 0)) and self_can_see_dude) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
       set_global_var(GVAR_ENEMY_MESA_VERDE, 1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   variable trig_stuff, temp_stuff;
   trig_stuff := tile_contains_pid_obj(14882, 0, PID_FOOTLOCKER_RUSTY_LEFT);
   temp_stuff := tile_contains_pid_obj(14880, 0, PID_FOOTLOCKER_RUSTY_LEFT);

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_INTOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

   move_obj_inven_to_obj(self_obj,temp_stuff);
   move_obj_inven_to_obj(trig_stuff,self_obj);

   start_gdialog(NAME,self_obj,4,-1,-1);
   gSay_Start;

   if (local_var(LVAR_Herebefore)==0) then begin
      call Node001;
   end else if (local_var(LVAR_Herebefore)==1) then begin
      call Node003;
   end

   gSay_End;
   end_dialogue;

   call restore_idiot_savant_int;

   move_obj_inven_to_obj(self_obj,trig_stuff);
   move_obj_inven_to_obj(temp_stuff,self_obj);

end

procedure timed_event_p_proc begin

   if(
      (tile_distance(local_var(LVAR_HomeTile), self_tile) > 8) and
      (not anim_busy(self_obj)) and
      obj_is_visible_flag(self_obj)
      ) then begin
      reg_anim_clear(self_obj);
      reg_anim_begin();
      animate_move_to_tile(local_var(LVAR_HomeTile));
      reg_anim_end();

  end

   if (
   (random(0, 10) == 1) and
   self_can_speak
   ) then begin
      reg_anim_clear(self_obj);
      reg_anim_begin();


         animate_move_obj_to_tile(
         self_obj,
         tile_num_in_direction(
            tile_num(self_obj),
            random(0, 5),
            random(1, 3)
         ),
         ANIMATE_WALK
      );

      reg_anim_end();


   end
   add_timer_event(self_obj, game_ticks(random(3, 5)), 0);

    if (
      (random(1, 20) == 1) and
      self_can_speak
      ) then begin
         floater_rand(200,220);
   end

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

procedure Skill_Check_000_Barter begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_BARTER, -30);
if is_success(roll_temp) then
begin
call Node021;
end
else begin
call Node031;
 end
end

procedure Skill_Check_001_Barter begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_BARTER, -30);
if is_success(roll_temp) then
begin
call Node022;
end
else begin
call Node031;
 end
end


// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE

procedure Node001
begin
Reply(230);
NOption(231,Node004,4);
NOption(232,Node004,-3);
NOption(233,Node999,4);
NOption(234,Node999,-3);
end

procedure Node003
begin
Reply(260);
NOption(261,Node015,4);
NOption(262,Node015,-3);
NOption(263,Node014,4);
NOption(264,Node014,-3);
NOption(265,Node005,4);
NOption(266,Node005,-3);

if (global_var(GVAR_CIPHER_CANNON) == CIPHER_CANNON_INSPECTED) then begin
   NOption(267,Node023,4);
   NOption(268,Node023,-3);
end

if (
   (global_var(GVAR_CIPHER_CANNON) == CIPHER_CANNON_FINISHED) and
   (local_var(LVAR_Informed_Fixed_Cannon) == 0)
   ) then begin
   NOption(269,Node029,4);
   NOption(270,Node029,-3);
end

if (local_var(LVAR_Inventions) == TRIG_INVENTIONS_KNOWS) then begin
   NOption(271,Node019,4);
   NOption(272,Node019,-3);
end

if (
   (local_var(LVAR_Inventions) == TRIG_INVENTIONS_NO_MONEY) and
   (dude_caps >= local_var(LVAR_No_Money))
   ) then begin
   NOption(273,Node021a,4);
   NOption(274,Node021a,-3);
end

if (global_var(GVAR_DOCKING_CLAMP_CHIP) == QUEST_KNOWN) then begin
   NOption(275,Node032,4);
   NOption(276,Node024,-3);
end

end

procedure Node004
begin
Reply(290);
NOption(291,Node014,4);
if (global_var(GVAR_CIPHER_CANNON) != CIPHER_CANNON_FINISHED) then begin
   NOption(292,Node010,4);
   NOption(293,Node010,-3);
end
NOption(265,Node005,4);
NOption(266,Node005,-3);
end

procedure Node005
begin

   if (global_var(GVAR_QUEST_BUILD_TRIG_ALARM) == QUEST_NONE) then begin
      set_global_var(GVAR_QUEST_BUILD_TRIG_ALARM, QUEST_ACCEPTED);
   end

Reply(320);
NOption(321,Node015,4);
NOption(322,Node015,-3);
NOption(323,Node014,4);
NOption(324,Node014,-3);
if (global_var(GVAR_QUEST_BUILD_TRIG_ALARM) != QUEST_COMPLETED) then begin
   if ((has_skill(dude_obj,SKILL_REPAIR)>=33) or is_skill_tagged(SKILL_REPAIR)) then begin
      NOption(325,Node008,4);
      NOption(326,Node008,-3);
   end

   if ((has_skill(dude_obj,SKILL_TRAPS)>=33) or is_skill_tagged(SKILL_TRAPS)) then begin
      NOption(327,Node006,4);
      NOption(328,Node006,-3);
   end
end

end

procedure Node006
begin
Reply(350);
NOption(351,Node007,1);
end

procedure Node007
begin

call build_trig_alarm;

Reply(380);
NOption(381,Node015,4);
NOption(382,Node015,-3);
NOption(383,Node999,4);
NOption(384,Node999,-3);
end

procedure Node008
begin
Reply(410);
NOption(411,Node009,4);
NOption(412,Node009,-3);
end

procedure Node009
begin

   call build_trig_alarm;

Reply(440);
if (global_var(GVAR_CIPHER_CANNON) != CIPHER_CANNON_FINISHED) then begin
   NOption(441,Node010,4);
   NOption(442,Node010,-3);
end
NOption(383,Node999,4);
NOption(384,Node999,-3);
end

procedure Node010
begin
Reply(470);
NOption(471,Node011,4);
NOption(472,Node011,-3);
NOption(473,Node018,4);
NOption(474,Node018,-3);
end

procedure Node011
begin
if (global_var(GVAR_QUEST_DEAL_WITH_HOUNDS) > DEAL_WITH_HOUNDS_SIEGE) then begin
   call Node012;
end
else begin
   Reply(500);
   NOption(501,Node018,4);
   NOption(502,Node018,-3);
end
end

procedure Node012
begin
Reply(530);
NOption(501,Node018,4);
NOption(502,Node018,-3);
end

procedure Node013
begin
Reply(560);
NOption(561,Node999,4);
NOption(562,Node999,-3);
end

procedure Node014
begin
Reply(590);
NOption(591,Node015,4);
NOption(592,Node015,4);
NOption(593,Node016,4);
NOption(594,Node016,-3);
end

procedure Node015
begin
Reply(620);
NOption(621,Node034,4);
NOption(622,Node034,-3);
end

procedure Node016
begin

set_local_var(LVAR_Inventions, TRIG_INVENTIONS_KNOWS);

Reply(650);
NOption(651,Node017,4);
NOption(652,Node017,-3);
end

procedure Node017
begin
Reply(680);
if (local_var(LVAR_Inventions) != TRIG_INVENTIONS_BOUGHT) then begin
   NOption(681,Node019,4);
   NOption(682,Node019,-3);
end
NOption(233,Node999,4);
NOption(234,Node999,-3);
end

procedure Node018
begin
Reply(710);
NOption(711,Node013,4);
NOption(712,Node013,-3);
end

procedure Node019
begin
   set_local_var(LVAR_No_Money, 100);
Reply(740);
if (dude_caps >= 100) then begin
   NOption(741,Node019a,4);
   NOption(742,Node019a,-3);
end

if (dude_caps >= 75) then begin
   NOption(743,Skill_Check_000_Barter,4);
end

NOption(744,Skill_Check_001_Barter,-3);

if (dude_caps < 100) then begin
   NOption(745,Node020,4);
   NOption(746,Node020,-3);
end
end

procedure Node019a
begin
   item_caps_adjust(dude_obj, -100);
   call Node030;
end

procedure Node020
begin

set_local_var(LVAR_Inventions, TRIG_INVENTIONS_NO_MONEY);

Reply(770);
NOption(771,Node999,4);
NOption(234,Node999,-3);
end

procedure Node021
begin

   set_local_var(LVAR_No_Money, 75);

Reply(800);

if (dude_caps >= 75) then begin
   NOption(801,Node021a,4);
end

if (dude_caps < 75) then begin
   NOption(802,Node020,4);
end
end

procedure Node021a
begin
   item_caps_adjust(dude_obj, -75);
   call Node030;
end

procedure Node022
begin

set_local_var(LVAR_No_Money, 75);

Reply(830);
if (dude_caps >= 75) then begin
   NOption(801,Node021a,-3);
end
if (dude_caps < 75) then begin
   NOption(831,Node020,-3);
end
end

procedure Node023
begin
Reply(860);
if (dude_item(PID_CAPACITATOR) >= 2) then begin
   NOption(861,Node025,4);
   NOption(862,Node026,-3);
end
NOption(863,Node999,4);
NOption(864,Node999,-3);
end

procedure Node024
begin
Reply(890);
NOption(864,Node999,-3);
end

procedure Node025
begin
Reply(920);
NOption(921,fix_cannon,4);
NOption(922,Node027,4);
end

procedure Node026
begin
Reply(950);
NOption(951,fix_cannon,-3);
NOption(952,Node027,-3);
end

procedure Node027
begin
Reply(980);
NOption(981,Node027a,4);
NOption(982,Node027a,-3);
NOption(983,Node028,4);
NOption(984,Node028,-3);
end

procedure fix_cannon
begin
   remove_pid_qty(dude_obj, PID_CAPACITATOR, 2)
   set_global_var(GVAR_CIPHER_CANNON, CIPHER_CANNON_FINISHED);
   fadeout(1);
   game_time_advance(ONE_GAME_HOUR);
   fadein(1);
   call Node999;
end

procedure Node027a
begin
   give_pid_qty(dude_obj, PID_MOTION_SENSOR, 1)
   give_pid_qty(dude_obj, PID_GEIGER_COUNTER, 1)
   call fix_cannon;
end

procedure Node028
begin
Reply(1010);
NOption(1011,Node027a,4);
NOption(1012,Node027a,-3);
NOption(1013,Node999,4);
NOption(1014,Node999,-3);
end

procedure Node029
begin
   set_local_var(LVAR_Informed_Fixed_Cannon, 1);
Reply(1040);
NOption(1041,Node999,4);
NOption(1042,Node999,-3);
end

procedure Node030
begin

   set_local_var(LVAR_Inventions, TRIG_INVENTIONS_BOUGHT);
   give_pid_qty(dude_obj, PID_LASER_POINTER, 1)
   give_pid_qty(dude_obj, PID_ULTRASONIC_GENERATOR, 1)

Reply(1070);
NOption(233,Node999,4);
NOption(234,Node999,-3);
end

procedure Node031
begin

   set_local_var(LVAR_No_Money, 100);

Reply(1100);
if (dude_caps>=100) then begin
   NOption(1101,Node019a,4);
   NOption(1102,Node019a,-3);
end

if (dude_caps<100) then begin
   NOption(1103,Node020,4);
   NOption(1104,Node020,-3);
end

NOption(1105,Node999,4);
NOption(1106,Node999,-3);
end

procedure Node032
begin
   if (global_var(GVAR_ACT) == 1) then begin
      Reply(1129);
   end else begin
      Reply(1130);
   end
NOption(1131,Node033,4);
NOption(1132,Node033,-3);
end

procedure Node033
begin
   set_global_var(GVAR_DOCKING_CLAMP_CHIP_TRIG, 1);
   if (global_var(GVAR_ACT) == 1) then begin
      Reply(1159);
   end else begin
      Reply(1160);
   end
NOption(233,Node999,4);
NOption(1161,Node999,-3);
end

procedure Node034
begin

   gdialog_barter;

Reply(1190);
NOption(1191,Node999,1);
end

procedure build_trig_alarm
begin
   give_xp(EXP_BUILD_TRIG_ALARM);
   set_global_var(GVAR_QUEST_BUILD_TRIG_ALARM, QUEST_COMPLETED);
   display_mstr(105);
end

//xxxxxxxxxxxxxxxxxxxx
