; General FY settings

[FalloutYesterday]
; Enable hunger system for the game? Disabled by default
; 0 = Disable
; 1 = Enable
hunger_system=0

; allow plague
; 0 = Disable
; 1 = Enable
allow_plague=1

; code phobia msg
; 0 = Disable
; 1 = Enable 
code_phobia=1
; Who is allowed to create footprints? Enabled for all 2-legged critters by default
; 0 = Player only
; 1 = Player and party members
; 2 = All 2-legged critters
footprints=2

; Enable footprints in combat? Causes animation issues. Disabled by default
; 0 = Disable
; 1 = Enable
footprints_combat=0

; Enable footsteps SFX for the game? Enabled by default
; 0 = Disable
; 1 = Enable
footsteps_sfx=1

; Enable additional ambient SFX in the game? Enabled by default
; 0 = Disable
; 1 = Enable
ambient_sfx=1
