/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

#ifndef HDDTNE_H
#define HDDTNE_H

 // Map vars for HD Downtown NE

 // Comments

//MAP_GLOBAL_VARS:

//GLOBAL                                       NUMBER

//ALL Map Vars needed to start w/ MVAR_
#define MVAR_Know_Beatrice_Good_Bouncer                     (0)
#define MVAR_Dead_Bar_Fight_Thugs                     		(1)
#define MVAR_Dude_Helped_Beatrice                     		(2)
#define MVAR_Bar_Fight_Diplomacy 							(3)

#endif // HDDTNE_H
