/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

#ifndef MAXBUNKR_H
#define MAXBUNKR_H

 // Map vars for Maxson Bunker

 // Comments

//MAP_GLOBAL_VARS:

//GLOBAL                                        NUMBER

// All Map Vars need to start w/ MVAR_

#define MVAR_KICK_PLAYER                           (0)
#define MVAR_ROOM_ONCE                             (1)
#define MVAR_WARN_ARMORY 						   (2)
#define MVAR_KNOW_ED 						       (3)
#define MVAR_BRIG_ACCESS 						       (4)
#define MVAR_KNOW_POISONER_STIMPAK 						       (5)
#define MVAR_KNOW_POISONER_VIDEO 						       (6)
#define MVAR_VIDEO_ACCESS 						       (7)
#define MVAR_KNOW_COMMANDER_BEER 						       (8)
#define MVAR_KNOW_CAMERA 						       (9)
#define MVAR_DL_MEDICAL_RECORD 						       (10)
#define MVAR_SENIOR_CUTSCENE					       (11)
#endif // MAXBUNKR_H
