
#ifndef MVCANYO3_H
#define MVCANYO3_H

 // Map vars for MVCANYO3

 // Comments

//MAP_GLOBAL_VARS:

//GLOBAL                                        NUMBER

// All Map Vars need to start w/ MVAR_

#define MVAR_Knows_Blackjack_Fake_Minigun                           (0)
#define MVAR_Collapse_Cave                                          (1)
#define MVAR_Alexandra_Needs_Blackjack_Alive                        (2)

#endif // MVCANYO3_H
