
#ifndef MVHOUNDS_H
#define MVHOUNDS_H

 // Map vars for Mesa Verde Hounds of Hecate Camp

 // Comments

//MAP_GLOBAL_VARS:

//GLOBAL                                        NUMBER

// All Map Vars need to start w/ MVAR_

#define MVAR_Total_Hounds_Killed                        (0)
#define MVAR_Create_Crater                              (1)
#define MVAR_Create_Rockslide                           (2)
#define MVAR_Poisoned_Supplies                          (3)

#endif // MVHOUNDS_H
