/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

#ifndef SETNTCLT_H
#define SETNTCLT_H

 // Map vars for Random Shuttle

 // Comments

//MAP_GLOBAL_VARS:

//GLOBAL                                        NUMBER

// All Map Vars need to start w/ MVAR_

#define MVAR_BRIDGE_BUILT                           (0)
#define MVAR_ONCE_SCIENCE                           (1)
#define MVAR_BRIDGE_ASKED                           (2)

#endif // SETNTCLT_H
