/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

#ifndef TBCB29_H
#define TBCB29_H

 // Map vars for Tibbets

 // Comments

//MAP_GLOBAL_VARS:

//GLOBAL                                       NUMBER

//ALL Map Vars needed to start w/ MVAR_
#define MVAR_SecField_down                     (0)
#define MVAR_ABE_HOLY_WATER                    (1)
#define MVAR_MAURICE_GONE                      (2)

#endif // TBCB29_H
