/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/*
        Name:
        Location:
        Description:

        Log:
           Please note any changes that have been made to the file in Updated. Then comment
           the code which you have changed/altered/commented out. Please, do not delete any
           code which was written.

           Created:

           Updated:
*/

/* Include Files */

/* Note, the Following Lines need to be in this order so that
   the script will be compilable. The define Name is referenced
   in a module from define.h and used in command.h. Please do
   not change the ordering.
        -rwh2   11/13/97
*/
#include "..\headers\define.h"

#define NAME                    SCRIPT_HALLOWEN

#include "..\headers\command.h"

procedure start;
procedure map_enter_p_proc;

procedure start begin
end

procedure map_enter_p_proc begin
    if(get_day == 31 and get_month == 10) then begin
        set_obj_visibility(self_obj, 0);
    end else
    set_obj_visibility(self_obj, 1);
end
