
#include "..\headers\define.h"
#include "..\headers\command.h"

#define NAME                    SCRIPT_PROXBOMB

procedure start;
procedure description_p_proc;
procedure look_at_p_proc;


procedure start begin
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
    script_overrides;
    display_mstr(101);
end

 /* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   display_mstr(100);
end
