/*******************************************************************************
        Name:
        Location:
        Description: Object template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"

#define NAME                    SCRIPT_RUNSFX

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure timed_event_p_proc;

/* Defines */


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
variable sfx;

procedure timed_event_p_proc;
procedure map_enter_p_proc;
procedure start;
procedure map_exit_p_proc;

procedure start begin
end

procedure map_enter_p_proc begin
   add_timer_event(self_obj, game_ticks(1), 1);
end

procedure timed_event_p_proc begin
    variable wav, pid;

  if (fixed_param == 1) then begin
      if (not(combat_is_initialized)) then begin

        if(
            obj_can_hear_obj(dude_obj, self_obj) and
            (self_elevation == dude_elevation) and
            (self_distance_from_dude <= (5 + dude_perception))
            ) then begin
            pid := self_pid;
            //display_msg("" + pid);

            if(pid == PID_BURNING_BARREL) then begin
                wav := "firebrl";
            end
            if(sfx == 0) then begin
                sfx := play_sfall_sound("data\\sound\\SFX\\" + wav + ".wav", 1);
            end
        end else begin
            stop_sfall_sound(sfx);
            sfx := 0;
        end
      end
  end

  add_timer_event(self_obj, game_ticks(1), 1);

end

procedure map_exit_p_proc begin

    if(sfx) then begin
        stop_sfall_sound(sfx);
    end

end
