/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/*
        Name: Generic Lesser Death Mantis
        Location: Generic
        Description: Generic Lesser Death Mantis.

        Log:

           Created: December 02, 1997

           Updated:
*/

/* Include Files */

#include "..\headers\define.h"
//#include "..\headers\<TownName.h>"

#define NAME                    SCRIPT_ZCLMANTI

#include "..\headers\command.h"
//#include "..\headers\ModReact.h"
#include "..\headers\party.h"

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_exit_p_proc;

/* Local variables which do not need to be saved between map changes. */
variable starttile := 0;

/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */


procedure start begin
end

procedure critter_p_proc begin
   if (self_can_see_dude) then begin
      self_attack_dude;
   end

   if (not(anim_busy(self_obj)) and not(combat_is_initialized) and ((critter_state(self_obj) bwand DAM_KNOCKED_OUT) == FALSE)) then begin
      reg_anim_clear(self_obj);
      reg_anim_begin();
      animate_move_to_tile(tile_num_in_direction(starttile, Random(0, 5), Random(1, 5)));
      reg_anim_end();
   end

end

procedure destroy_p_proc begin
   /* Increment the aligned critter counter*/
   inc_neutral_critter

   if (self_pid == PID_MANTIS) then begin
      set_self_lootable
      give_pid_qty(self_obj, PID_GUTS, 1)
   end
end

procedure damage_p_proc begin
   if (source_obj == dude_obj) then begin
      self_attack_dude;
   end
end

procedure look_at_p_proc begin
   script_overrides;
   display_mstr(100);
end

procedure description_p_proc begin
   call BeastlordPossess;
end

procedure use_obj_on_p_proc begin
   variable pid;
   pid = obj_pid(obj_being_used_with);

   if (pid_is_alcohol_pid(pid) or (pid == PID_NUKA_COLA)) then begin
      script_overrides;
      remove_pid_qty(source_obj, pid, 1)
      critter_dmg(self_obj,get_critter_stat(self_obj,STAT_current_hp)+10,DMG_explosion);
   end
end

procedure use_skill_on_p_proc begin
   if (action_being_used == SKILL_STEAL) then begin
      script_overrides;
   end

   call injure_with_skill;
end

procedure map_enter_p_proc begin
   starttile = self_tile;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_MANTIS);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_GENERIC_MANTIS);
end

procedure map_exit_p_proc begin
   call BeastlordUnpossess(TEAM_MANTIS);
end
