/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/*
        Name: Generic Lesser Rat
        Location: Arroyo
        Description: Generic lesser rat when you need a small, not very strong rat.

        Log:

           Created: December 02, 1997

           Updated:
*/

/* Include Files */

#include "..\headers\define.h"
//#include "..\headers\<TownName.h>"

#define NAME                    SCRIPT_ZCLRAT

#include "..\headers\command.h"
#include "..\headers\party.h"
//#include "..\headers\ModReact.h"

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure map_exit_p_proc;

/* Local variables which do not need to be saved between map changes. */

procedure start begin
end

procedure timed_event_p_proc begin
   if ((not(combat_is_initialized)) and ((critter_state(self_obj) bwand DAM_KNOCKED_OUT) == FALSE)) then begin
      reg_anim_clear(self_obj);
      reg_anim_begin();
         animate_move_to_tile(tile_num_in_direction(tile_num(self_obj),random(0,5),random(1,3)));
      reg_anim_end();
   end
   add_timer_event(self_obj,game_ticks(random(3,5)),0);
end

procedure critter_p_proc begin
   // the rat attacks if it sees the player
   if (self_can_see_dude) then begin
      self_attack_dude;
   end
end

procedure destroy_p_proc begin
   /* Increment the aligned critter counter*/
   inc_neutral_critter

   if (self_pid == PID_RAT) then begin
      set_self_lootable
      give_pid_qty(self_obj, PID_RAT_TAIL, 1)
   end
end

procedure damage_p_proc begin
   if (source_obj == dude_obj) then begin
      self_attack_dude;
   end
end

procedure look_at_p_proc begin
//   script_overrides;
//   display_msg(mstr(100));
end

procedure description_p_proc begin
   call BeastlordPossess;
end

procedure use_obj_on_p_proc begin
end

procedure use_skill_on_p_proc begin
   if (action_being_used == SKILL_STEAL) then begin
      script_overrides;
   end
   call injure_with_skill;
end

procedure map_enter_p_proc begin
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_RAT);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_GENERIC_RAT);
   add_timer_event(self_obj,game_ticks(random(1,5)),0);
end

procedure map_exit_p_proc begin
   call BeastlordUnpossess(TEAM_RAT);
end
