/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/*
        Name: Generic Elevator #2
        Location: Various Places (Sierra Base, etc.)
        Description: This elevator is used on maps with 2 separate elevators

        Log:

            Created: April 1, 1998

            Updated:
*/

/* Include Files */

#include "..\headers\define.h"

#define NAME                    SCRIPT_ZSELEV02

#include "..\headers\command.h"

procedure start;
procedure spatial_p_proc;

procedure start begin
end

procedure spatial_p_proc begin
   if(source_obj == dude_obj) then begin
      // Unless we know the Waste Disposal code, we cannot travel using this elevator
      if ((cur_map_index == MAP_TIBBETS_SECURITY_HUB) and (global_var(GVAR_KNOW_WASTE_DISPOSAL) < 2)) then begin
         //debug_msg("ELEVATOR IS OUT OF ACTION");
      end else begin
         elevator(-1);
         /*
         if(cur_map_index == MAP_SIERRA_123) then
            elevator(ELEV_SIERRA2);
         */
      end
   end
end
