/*******************************************************************************
        Name:
        Location:
        Description: Object template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"

#define NAME                    SCRIPT_B1SPACES

/* Standard Script Procedures */
procedure start;
procedure spatial_p_proc;

/* Defines */


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin
   if (script_action == spatial_proc) then begin
		call spatial_p_proc;
	end
end

procedure spatial_p_proc begin
   if ((source_obj == dude_obj) and not(dude_wearing_space_suit)) then begin
      critter_dmg(source_obj, 999999, DMG_explosion);
   end
end
