/*

        Name:           Mission Control Launch Codes Workstation
        Location:
        Description:

           Created: 14.12.2023. 20:05:58

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_SCCLAMP

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (0)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"


/* Standard Script Procedures */
procedure start;
procedure talk_p_proc;
procedure use_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;

/* Script Specific Procedure Calls */
procedure Node999;                                      // This Node is Always Ending





/* User defined variables */



// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node_000;
procedure Node_001;
procedure Node_002;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_LoggedIn               (8)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;


procedure use_p_proc begin
   if (source_obj == dude_obj) then begin
      dialogue_system_enter;
   end
end

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
end


/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;
       if (global_var(GVAR_DOCKING_CLAMP_CHIP) != QUEST_COMPLETED) then begin
           call Node_000;
       end
       else begin
         call Node_002;
       end

       gSay_End;
       end_dialogue;

end

procedure timed_event_p_proc begin
end


/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE

procedure Node_000
begin

   if (global_var(GVAR_DOCKING_CLAMP_CHIP) == QUEST_NONE) then begin
      set_global_var(GVAR_DOCKING_CLAMP_CHIP, QUEST_KNOWN);
   end

Reply(200);

if (dude_item(PID_DOCKING_CLAMP_CHIP)) then
   NOption(203,Node_002,1);

NOption(201,Node_001,1);
NOption(202,Node999,1);
end

procedure Node_001
begin
Reply(230);
NOption(231,Node_000,1);
NOption(232,Node999,1);
end

procedure Node_002
begin

   if (global_var(GVAR_DOCKING_CLAMP_CHIP) != QUEST_COMPLETED) then begin
      set_global_var(GVAR_DOCKING_CLAMP_CHIP, QUEST_COMPLETED);
      give_xp(1000);
      display_mstr(103);
      remove_pid_qty(dude_obj, PID_DOCKING_CLAMP_CHIP, 1)
   end

Reply(260);
NOption(232,Node999,1);
end


//xxxxxxxxxxxxxxxxxxxx
