/*

        Fan Made Fallout NPC Script

        Name:           Beatrice
        Location:
        Description:

           Created: 26.2.2024. 8:51:26

*/

//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        9 /* same as thief variable */

/* Include Files */
#include "..\headers\define.h"

#define NAME                    SCRIPT_HDBEA
#define TOWN_REP_VAR            (GVAR_TOWN_REP_HOOVER_DAM)

#include "..\headers\command.h"
#include "..\headers\ModReact.h"
#include "..\headers\party.h"
#include "..\headers\partybkg.h"
#include "..\HEADERS\hdam.h"
#include "..\HEADERS\hddtne.h"
#include "..\HEADERS\footsteps.h"

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure push_p_proc;
procedure timed_event_p_proc;

/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

/*****************************************************************
Node001 is a dialogue node that includes a line asking to join the party.
Node002 has several game checks before joining with fail/pass responses.
*****************************************************************/
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node009a;
procedure Node009b;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node015a;
procedure Node015b;
procedure Node015c;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;

/*****************************************************************
Party Member pre-requisites
These lines are necessary for the critter to join the player
as a party member.
*****************************************************************/
procedure Join_Party;                                    // Party Join node
procedure Abandon_Party;                                 // Party Abandon node
procedure Node1000;                                      // Main party member node
procedure Node1001;                                      // heal yourself
procedure Node1002;                                      // wait here
procedure Node1003;                                      // put your weapon away
procedure Node1004;                                      // follow close
procedure Node1005;                                      // follow medium
procedure Node1006;                                      // follow far
procedure Node1007;                                      // change distance menu
procedure Node1008;                                      // look at gear menu
procedure Node1009;                                      // remove armor menu
procedure Node1010;                                      // weapon abilities
procedure Node1100;                                      // rejoin party


/* Change "Beatrice" to match the name of your new critter */
#define Beatrice_joins_party             party_add_self;                                                   \
                                               critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_PLAYER)
#define dude_has_free_slot_for_Beatrice  ((dude_at_max_party_size == false) and (Beatrice_In_Party == false))

/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_

      To have LVars work, open scripts.LST, scroll to your character's script name,
      and change the "LVars" setting to at least 8,
      Since there are 8 Local Variables used below.

      (LVAR_ 0 thru 3 are reserved for NPC Reaction Modifiers...
      ...will add more instructions when I learn how they work.)
*****************************************************************/
#define LVAR_Flags                      (4)
#define LVAR_WAITING                    (5)
#define LVAR_FOLLOW_DISTANCE            (6)
#define LVAR_TEAM                       (7)
#define LVAR_Joined_Player              (8)
#define LVAR_Caught_Thief               (9)

/*****************************************************************
      If you would rather use the LVAR_Hostile, LVAR_Herebefore, LVAR_Personal_Enemy
      variables instead of LVAR_Flags, uncomment the relevent lines and comment out
      lines with set_herebefore, set_hostile, if (hostile) and (self_can_see_dude).
*****************************************************************/
//#define LVAR_Hostile                    (9)
#define LVAR_Herebefore                 (10)
//#define LVAR_Personal_Enemy             (11)

#define PARTY_NODE_X                      Node1000

/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/

import variable BeatriceBouncer;


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/
variable begin
end

/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin
    BeatriceBouncer := self_obj;
end

procedure map_enter_p_proc begin
   /*  This procedure will get called each time that the map is first entered. It will
       set up the Team number and AI packet for this critter. This will override the
       default from the prototype, and needs to be set in scripts. */
    BeatriceBouncer := self_obj;

   //party_member_map_enter;

   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_PARTY_BEATRICE_CUSTOM);

   if
      (global_var(GVAR_QUEST_HELP_BEATRICE) == HELP_BEATRICE_ASKED_TO_JOIN) or
      (global_var(GVAR_QUEST_HELP_BEATRICE) == HELP_BEATRICE_BAR_FIGHT_IS_ON)
   then begin
      switch_team(self_obj, TEAM_DUSTY_DESIRES_WORKERS)
   end else begin
         if (cur_map_index == MAP_HOOVER_DAM_DOWNTOWN_NORTHEAST) then begin
            switch_team(self_obj, TEAM_HOOVER_DAM)
         end
   end

   call critter_setup_footsteps_map_enter(self_obj, WALKING_TICKS_SLOWER, RUNNING_TICKS_DEFAULT);
end

procedure map_update_p_proc begin
    BeatriceBouncer := self_obj;
 end

procedure timed_event_p_proc begin
   call critter_setup_footsteps_timed_event(self_obj, WALKING_TICKS_SLOWER, RUNNING_TICKS_DEFAULT, SFX_FOOTSTEP_HARD_SHOE);
end

procedure critter_p_proc begin
   /* Every heartbeat that the critter gets, this procedure will be called. Anything from
      Movement to attacking the player on sight can be placed in here.
      If the critter is mad at the player for any reason, it will attack and remember to attack
      the player should the game be saved and loaded repeatedly. Additionally, if any special
      actions need to be taken by the critter based on previous combat, the critter will remember
      this as well. */

//   if ((local_var(LVAR_Hostile) > 1) and (self_can_see_dude)) then begin
//      set_local_var(LVAR_Hostile,1);
   if (hostile) and (self_can_see_dude) then begin
      self_attack_dude; //Macro made by Tom to keep the critter fleeing.
   end
   else if (
         (global_var(GVAR_QUEST_HELP_BEATRICE) == HELP_BEATRICE_BAR_FIGHT_IS_ON) and
         (map_var(MVAR_Dead_Bar_Fight_Thugs) >= 2) and
         (map_var(MVAR_Dude_Helped_Beatrice) >= 1) and
         self_can_see_dude and
         self_can_speak
         ) then begin
            dialogue_system_enter;
   end

   /* This next script moves the new party member to follow the player after they've joined and
      when entering new maps. */
   if (Beatrice_In_Party) then begin
      if (party_is_waiting == false) then begin
         party_member_follow_dude
      end
   end

   /*
   -----   These are examples of common Abandon_Party calls, use...or don't...at your discretion   -----

   else if (Beatrice_In_Party) then begin
      if (global_var(GVAR_PLAYER_REPUTATION) < Beatrice_Bad_Karma) then begin
         call Abandon_Party;
         //debug_msg("Beatrice Bad Player Rep");
      end
      else if (has_rep_childkiller) then begin
         call Abandon_Party;
         //debug_msg("Beatrice: Child Killer");
      end
      else if (has_rep_berserker) then begin
         call Abandon_Party;
         //debug_msg("Beatrice: Berserker");
      end
      else if (has_rep_slaver) then begin
         call Abandon_Party;
         //debug_msg("Beatrice: Slaver Rep");
      end*/

end

procedure damage_p_proc begin
   /* Whenever the critter takes damage of any type, this procedure will be called. Things
      like setting ENEMY_ and LVAR_Personal_Enemy can be set here.
      If the player causes damage to this critter, then he will instantly consider the player
      his personal enemy. In Critter_Proc or through dialog, actions will be taken against
      the player for his evil acts. */

   if (obj_in_party(source_obj)) then begin
//       set_local_var(LVAR_Personal_Enemy, 1);
      set_personal_enemy;
   end

end

procedure pickup_p_proc begin
   /* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
      In here, various things can happen. The most common response is instant hostility which
      will be remembered. */

   if (source_obj == dude_obj) then begin
//      set_local_var(LVAR_Hostile, 2);
      set_hostile;
   end

end

procedure talk_p_proc begin

   /* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
      written by designers are placed in here. Additionally, Reactions are generated and
      stored which affects player interactions. */
   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

   start_gdialog(NAME,self_obj,4,HEAD_BEATRICE,BACKGROUND_JUNKTOWN);
   gSay_Start;

   if (
     (global_var(GVAR_QUEST_HELP_BEATRICE) == HELP_BEATRICE_BAR_FIGHT_IS_ON) and
     not(combat_is_initialized) and
     (map_var(MVAR_Dead_Bar_Fight_Thugs) >= 2) and
     (map_var(MVAR_Dude_Helped_Beatrice) >= 1) and
     self_can_see_dude and
     self_can_speak
     ) then begin
      call Node009;
   end
   else if (
     (global_var(GVAR_QUEST_HELP_BEATRICE) == HELP_BEATRICE_PROPOSED_TO_JOIN) or
     (global_var(GVAR_QUEST_HELP_BEATRICE) == HELP_BEATRICE_DUSTY_OK))
    then begin
     call Node010;
   end
   else if ((Beatrice_Ptr != 0) or (party_is_waiting)) then begin
      call Node1000;
   end
   else if (local_var(LVAR_Herebefore) == 1) then begin
     call Node011;
   end
   else if (dude_is_super_mutant) then begin
      call Node013;
   end
    else begin
        call Node001;
    end

   gSay_End;
   end_dialogue;

call restore_idiot_savant_int;

end

procedure destroy_p_proc begin
   /* This procedure gets called only on the death of this NPC. Special things like
       incrementing the death count for reputation purposes and Enemy Counters are placed
       in here. */

       BeatriceBouncer := 0;

       if (
          (global_var(GVAR_QUEST_HELP_BEATRICE) == HELP_BEATRICE_BAR_FIGHT_IS_ON) and
          (cur_map_index == MAP_HOOVER_DAM_DOWNTOWN_NORTHEAST)
          ) then begin
          set_global_var(GVAR_QUEST_HELP_BEATRICE, HELP_BEATRICE_FAILED);

    /*      if (not(mckneely_dead)) then begin
             variable m;
             // ZZZ TODO script missing, needs to go away on map exit
             m = create_object_sid(PID_MITCH_STILLER,18343,self_elevation,-1);
             critter_add_trait(m,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_DUSTY_DESIRES_WORKERS);
             give_pid_qty(m, PID_ASSAULT_RIFLE, 1)
          end*/
       end

   /* Increment the aligned critter counter
        This counter affects your karma? */
   inc_neutral_critter

   /* Set global_variable for Enemy status*/
   set_global_var(GVAR_BEATRICE_DEAD, 1);

end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
   procedure look_at_p_proc begin
      script_overrides;
      if (local_var(LVAR_Herebefore) == 0) then
         display_mstr(100);
      else
         display_mstr(101);
   end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
      for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

procedure push_p_proc begin

    if (not(Beatrice_In_Party)) then begin
        floater_bad(680);
        call Node998;
     end
     else begin

         if (random(1, 3) == 1) then
            floater(650);                               // Float response for being pushed by player

     end

end

procedure Node998 begin
   /* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
       this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
       he was once hostile towards the player.*/
//   set_local_var(LVAR_Hostile,2);
   set_hostile;

end


/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
   procedure Node999 begin
      //debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
      if (local_var(LVAR_Herebefore)==0) then
      begin
      set_local_var(LVAR_Herebefore,1);
      set_global_var(GVAR_KNOW_BEATRICE, 1);
      end
      end


procedure Node001
begin
Reply(200);
if (map_var(MVAR_Know_Beatrice_Good_Bouncer) == 1) then begin
   NOption(201,Node002,4);
end
NOption(202,Node011,4);
NOption(203,Node012,4);
NOption(204,Node999,4);
end

procedure Node002
begin
Reply(230);
NOption(231,Node004,4);
NOption(232,Node003,4);
end

procedure Node003
begin
Reply(260);
NOption(261,Node005,4);
end

procedure Node004
begin
Reply(290);
NOption(261,Node005,4);
end

procedure Node005
begin
Reply(320);
NOption(321,Node006,4);
NOption(322,Node999,4);
end

procedure Node006
begin
Reply(350);
NOption(351,Node007,4);
end

procedure Node007
begin
Reply(380);
NOption(381,Node008,4);
end

procedure Node008
begin
   if (global_var(GVAR_QUEST_HELP_BEATRICE) == QUEST_NONE) then begin
      set_global_var(GVAR_QUEST_HELP_BEATRICE, HELP_BEATRICE_ASKED_TO_JOIN);
   end
Reply(410);
NOption(411,Node999,4);
end

procedure Node009
begin
Reply(440);
NOption(441,Node009a,4);
NOption(442,Node009b,4);
end

procedure Node009a begin
   set_global_var(GVAR_QUEST_HELP_BEATRICE, HELP_BEATRICE_PROPOSED_TO_JOIN);
   call Node010;
end

procedure Node009b begin
   set_global_var(GVAR_QUEST_HELP_BEATRICE, HELP_BEATRICE_DONE);
   call Node999;
end

procedure Node010
begin
Reply(470);
if (global_var(GVAR_QUEST_HELP_BEATRICE) == HELP_BEATRICE_DUSTY_OK) then begin

/* This node checks for stuff before allowing NPC to join party.
       You can add other conditions for joining here. */
       if (dude_charisma <= 1) then begin
         NOption(471,Node015a,4);
       end else if (dude_at_max_party_size) then begin
         NOption(471,Node015b,4);
       end else if town_rep_is_hated then begin
         NOption(471,Node015c,4);
       end else begin
         NOption(471,Node015,4);
       end

end
if (global_var(GVAR_QUEST_HELP_BEATRICE) == HELP_BEATRICE_PROPOSED_TO_JOIN) then begin
   NOption(472,Node999,4);
end
NOption(473,Node009b,4);
end

procedure Node011
begin
Reply(500);
NOption(232,Node003,4);
NOption(501,Node999,4);
end

procedure Node012
begin
if (dude_is_male) then begin
   Reply(530);
end
else if (dude_is_female) then begin
   Reply(531);
end
NOption(532,Node999,4);
end

procedure Node013
begin
Reply(560);
NOption(561,Node014,4);
end

procedure Node014
begin
Reply(590);
NOption(591,Node011,4);
end

procedure Node015
begin
   call Join_Party;
Reply(620);
NOption(621,Node009b,4);
NOption(622,Node009b,4);
NOption(623,Node016,4);
end

procedure Node015a
begin
   Reply(920);
   NOption(532,Node999,4);
end

procedure Node015b
begin
   Reply(950);
   NOption(532,Node999,4);
end

procedure Node015c
begin
   Reply(980);
   BOption(532,Node998,4);
end

procedure Node016
begin
Reply(650);
NOption(651,Node009b,4);
end

procedure Node017
begin
Reply(680);
NOption(681,Node018,4);
if (Marcus_Ptr) then begin
   NOption(682,Node021,4);
end
NOption(683,Node022,4);
NOption(684,Node020,4);
NOption(685,Node999,4);
end

procedure Node018
begin
Reply(710);
NOption(711,Node019,4);
end

procedure Node019
begin
Reply(740);
NOption(741,Node999,4);
end

procedure Node020
begin
Reply(770);
NOption(532,Node999,4);
end

procedure Node021
begin
Reply(800);
NOption(801,Node023,4);
end

procedure Node022
begin
Reply(830);
NOption(831,Node024,4);
end

procedure Node023
begin
Reply(860);
NOption(591,Node017,4);
end

procedure Node024
begin
Reply(890);
NOption(591,Node017,4);
end


procedure Join_Party begin
   /* This node places the NPC in the player's party.
      Call this node any time you want an action from the player to result in the NPC joining their party. */

   Beatrice_joins_party;
   set_local_var(LVAR_Joined_Player,1);

end

procedure Abandon_Party begin

   //set_local_var(LVAR_never_again,1);
   //party_remove(self_obj);
   //leave party
   if (self_visible) then
   set_self_abandon_party;

end


   /* Node1000 and on are default dialogue nodes for a generic NPC joining the player's party. */

procedure Node1000 begin
   Reply(680);                                        // This reply is when the NPC is in your party and you talk to them
   party_member_default_options;
end
procedure Node1001 begin
   // heal yourself
   obj_heal(self_obj)
   if (party_healed_max) then begin
      Reply(9900);                         // This reply is when your party member is healed to max
   end else if (party_healed_good) then begin
     Reply(9910);                                      // This reply message is for when the NPC is Barely Hurt (90% health or above)
   end else if (party_healed_hurt) then begin
      Reply(9915);                                     // This reply message is for when the NPC is Wounded (70%-90% health?)
   end else begin
      Reply(9920);                                     // This reply message is for Failures
   end
   party_member_default_options;
end
procedure Node1002 begin
   // wait here
   set_party_waiting;
   Reply(9930);                            // These reply messages are in response to wait request
   party_member_default_options;
end
procedure Node1003 begin
   // put your weapon away
   inven_unwield(self_obj);
   Reply(9940);                                        // Response to removing weapon
   party_member_default_options;
end
procedure Node1004 begin
   // follow close
   set_follow_close;
   Reply(9950);                            // Random responses for distance change
   party_member_default_options;
end
procedure Node1005 begin
   // follow medium
   set_follow_medium;
   Reply(9960);                            // Random responses for distance change
   party_member_default_options;
end
procedure Node1006 begin
   // follow far
   set_follow_far;
   Reply(9970);                            // Random responses for distance change
   party_member_default_options;
end
procedure Node1007 begin
   // distance
   //Reply("TEMP MESSAGE: DISTANCE");
   Reply(9980);                                        // Generic response to "Change follow distance" menu
   party_member_def_follow_options;
end
procedure Node1008 begin
   // gear
   //Reply("TEMP MESSAGE: GEAR");
   Reply(9985);                                        // Generic response to "Look at your gear"
   party_member_def_gear_options;
end
procedure Node1009 begin
   // remove armor
   //NEED TO FIND OUT WHY THIS DOESNT WORK!!! - NBK
   remove_armor(self_obj)
   //Reply("TEMP MESSAGE: REMOVE ARMOR");
   Reply(9990);                                        // Generic response to "Remove armor"
   party_member_default_options;
end
procedure Node1010 begin
   // weapons that can be used
   //Reply("TEMP MESSAGE: CAN USE...");
   Reply(9995);                                        // Specific reply, indicating what weapons the NPC can use.
   party_member_default_options;
end
procedure Node1100 begin                              // This node is for when the player is asking the NPC to re-join
   // join me
   if (dude_charisma <= 1) then begin
      set_self_abandon_party;
      Reply(920);                                     // NPC abandons party because Player Character is too ugly
      NOption(g_mstr(10007),Node999,001);             // Predefined generic messages in GENERIC.MSG
   end else if (dude_at_max_party_size) then begin
      set_self_abandon_party;
      Reply(950); //was 2000                          // Generic "Too many followers" reply
      NOption(g_mstr(10007),Node999,001);             // Predefined generic messages in GENERIC.MSG
   end else if (town_rep_is_hated) then begin
      set_self_abandon_party;
      Reply(980);                                     // Will abandon party if Town_Rep becomes Hated
      BOption(g_mstr(10007),Node998,001);             // Predefined generic messages in GENERIC.MSG
   end else begin
      end_party_waiting;
      Reply(9750);                         // Random dialogue greetings
      party_member_default_options;
   end
end
