/*

        Name:           Bob
        Location:
        Description:

           Created: 2.3.2024. 16:14:00

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"

#define NAME                    SCRIPT_HDBOB

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_HOOVER_DAM)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\HEADERS\hdam.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;
procedure Node039;
procedure Node040;
procedure Node041;
procedure Node042;
procedure Node043;
procedure Node044;
procedure Node045;
procedure Node046;
procedure Node016;
procedure Bounties;
procedure StartBountyCraig;
procedure StartBountyElDiablo;
procedure StartBountyNancy;
procedure StartBountyIngmar;
procedure StartBountyKyle;
procedure StartBountyRyan;
procedure Make_Inven;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Restock_Time               (8)
#define LVAR_Restock_Time_Fix           (9)
#define LVAR_Made_Inven                 (10)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_HOOVER_DAM);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);

   if (((game_time) < 0) and (local_var(LVAR_Restock_Time_Fix) == 0)) then begin
      set_local_var(LVAR_Restock_Time, game_time - 1);
      set_local_var(LVAR_Restock_Time_Fix, 1);
   end

   if (local_var(LVAR_Restock_Time) < game_time) then begin
      destroy_obj_inven(self_obj);
      set_local_var(LVAR_Restock_Time, game_time + ONE_GAME_MONTH);
      set_local_var(LVAR_Made_Inven,0);
   end

   if (local_var(LVAR_Made_Inven) == 0) then begin
      set_local_var(LVAR_Made_Inven,1);
      call Make_Inven;
   end

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and self_can_see_dude) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,HEAD_BOB,-1);
       gSay_Start;
       call Node001;
       gSay_End;
       end_dialogue;

   call restore_idiot_savant_int;
end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
   if (local_var(LVAR_Herebefore)==0) then
      Reply(200);
   else
      Reply(201);

if (dude_chasing_a_bounty) then
   NOption(202,Node017,4);
NOption(203,Node002,4);
NOption(204,Node003,4);
NOption(205,Node044,4);
NOption(206,Node999,4);
end

procedure Node002
begin
Reply(230);
NOption(231,Node042,4);
NOption(232,Node999,4);
end

procedure Node003
begin
Reply(260);
NOption(261,Bounties,4);
NOption(262,Node999,4);
end

procedure Node004
begin
Reply(290);
NOption(291,Node005,4);
end

procedure Node005
begin
Reply(320);
NOption(321,Node046,4);
NOption(262,Node999,4);
end

procedure Node006
begin
Reply(350);
NOption(351,Node007,4);
end

procedure Node007
begin
Reply(380);
NOption(381,Node046,4);
NOption(262,Node999,4);
end

procedure Node008
begin
Reply(410);
NOption(411,Node009,4);
end

procedure Node009
begin
Reply(440);
NOption(441,Node046,4);
NOption(262,Node999,4);
end

procedure Node010
begin
Reply(470);
NOption(471,Node011,4);
end

procedure Node011
begin
Reply(500);
NOption(501,Node046,4);
NOption(262,Node999,4);
end

procedure Node012
begin
Reply(530);
NOption(531,Node013,4);
end

procedure Node013
begin
Reply(560);
NOption(561,Node046,4);
NOption(262,Node999,4);
end

procedure Node014
begin
Reply(590);
NOption(591,Node015,4);
end

procedure Node015
begin
Reply(620);
NOption(621,Node046,4);
NOption(262,Node999,4);
end

procedure Node017
begin
Reply(680);
if ((global_var(GVAR_QUEST_12_CRAIG_BOUNTY) == QUEST_NONE) and dude_item(PID_CRAIG_HEAD)) then
   NOption(681,Node018,4);
if ((global_var(GVAR_QUEST_12_MIGUEL_BOUNTY) == QUEST_NONE) and dude_item(PID_MIGUEL_HEAD)) then
   NOption(682,Node022,4);
if ((global_var(GVAR_QUEST_12_NANCY_BOUNTY) == QUEST_NONE) and dude_item(PID_NANCY_HEAD)) then
   NOption(683,Node026,4);
if ((global_var(GVAR_QUEST_12_INGMAR_BOUNTY) == QUEST_NONE) and dude_item(PID_INGMAR_HEAD)) then
   NOption(684,Node030,4);
if ((global_var(GVAR_QUEST_12_KYLE_BOUNTY) == QUEST_NONE) and dude_item(PID_KYLE_HEAD)) then
   NOption(685,Node034,4);
if ((global_var(GVAR_QUEST_12_RYAN_BOUNTY) == QUEST_NONE) and dude_item(PID_RYAN_HEAD)) then
   NOption(686,Node038,4);
NOption(687,Node999,4);
end

procedure Node018
begin
Reply(710);
NOption(711,Node019,4);
end

procedure Node019
begin
   remove_pid_qty(dude_obj, PID_CRAIG_HEAD, 1)
   item_caps_adjust(dude_obj, 1000);
   set_global_var(GVAR_QUEST_12_CRAIG_BOUNTY, QUEST_COMPLETED);
Reply(740);
NOption(741,Node020,4);
end

procedure Node020
begin
Reply(770);
NOption(771,Node021,4);
end

procedure Node021
begin
Reply(800);
// NOTE: If all are done go to 43
NOption(801,Bounties,4);
NOption(802,Node999,4);
end

procedure Node022
begin
Reply(830);
NOption(831,Node023,4);
end

procedure Node023
begin

   remove_pid_qty(dude_obj, PID_MIGUEL_HEAD, 1)
   item_caps_adjust(dude_obj, 1000);
   set_global_var(GVAR_QUEST_12_MIGUEL_BOUNTY, QUEST_COMPLETED);

Reply(860);
NOption(861,Node024,4);
end

procedure Node024
begin
Reply(890);
NOption(891,Node025,4);
end

procedure Node025
begin
Reply(920);
// NOTE: If all are done go to 43
NOption(921,Bounties,4);
NOption(802,Node999,4);
end

procedure Node026
begin
Reply(950);
NOption(951,Node027,4);
end

procedure Node027
begin

   remove_pid_qty(dude_obj, PID_NANCY_HEAD, 1)
   item_caps_adjust(dude_obj, 1000);
   set_global_var(GVAR_QUEST_12_NANCY_BOUNTY, QUEST_COMPLETED);

Reply(980);
NOption(981,Node028,4);
end

procedure Node028
begin
Reply(1010);
NOption(1011,Node029,4);
end

procedure Node029
begin
Reply(1040);
// NOTE: If all are done go to 43
NOption(322,Bounties,4);
NOption(1041,Node999,4);
end

procedure Node030
begin
Reply(1070);
NOption(1071,Node031,4);
end

procedure Node031
begin

   remove_pid_qty(dude_obj, PID_INGMAR_HEAD, 1)
   item_caps_adjust(dude_obj, 1000);
   set_global_var(GVAR_QUEST_12_INGMAR_BOUNTY, QUEST_COMPLETED);

Reply(1100);
NOption(1101,Node032,4);
end

procedure Node032
begin
Reply(1130);
NOption(1131,Node033,4);
end

procedure Node033
begin
Reply(1160);
// NOTE: If all are done go to 43
NOption(1161,Bounties,4);
NOption(1162,Node999,4);
end

procedure Node034
begin
Reply(1190);
NOption(1191,Node035,4);
end

procedure Node035
begin

   remove_pid_qty(dude_obj, PID_KYLE_HEAD, 1)
   item_caps_adjust(dude_obj, 1000);
   set_global_var(GVAR_QUEST_12_KYLE_BOUNTY, QUEST_COMPLETED);

Reply(1220);
NOption(1221,Node036,4);
end

procedure Node036
begin
Reply(1250);
NOption(1251,Node037,4);
end

procedure Node037
begin
Reply(1280);
// NOTE: If all are done go to 43
NOption(1281,Bounties,4);
NOption(1282,Node999,4);
end

procedure Node038
begin
Reply(1310);
NOption(1311,Node039,4);
end

procedure Node039
begin

   remove_pid_qty(dude_obj, PID_RYAN_HEAD, 1)
   item_caps_adjust(dude_obj, 1000);
   set_global_var(GVAR_QUEST_12_RYAN_BOUNTY, QUEST_COMPLETED);

Reply(1340);
NOption(1341,Node040,4);
end

procedure Node040
begin
Reply(1370);
NOption(1131,Node041,4);
end

procedure Node041
begin
Reply(1400);
// NOTE: If all are done go to 43
NOption(1401,Bounties,4);
NOption(1402,Node999,4);
end

procedure Node042
begin
   gdialog_barter;
Reply(1430);
NOption(1431,Node999,4);
end

procedure Node043
begin
Reply(1460);
NOption(1461,Node999,4);
end

procedure Node044
begin
Reply(1490);
NOption(1491,Node045,4);
end

procedure Node045
begin
Reply(1520);
// NOTE: If all are done go to 43
NOption(1521,Bounties,4);
NOption(1522,Node042,4);
NOption(1523,Node999,4);
end

procedure Node046
begin
Reply(1550);
NOption(1551,Node999,4);
end

procedure Node016
begin
Reply(650);
NOption(1551,Node999,4);
end

procedure Bounties begin
   if (dude_chasing_a_bounty) then
      call Node016;
   else if (global_var(GVAR_QUEST_12_CRAIG_BOUNTY) == QUEST_NONE) then
      call Node004;
   else if (global_var(GVAR_QUEST_12_MIGUEL_BOUNTY) == QUEST_NONE) then
      call Node006;
   else if (global_var(GVAR_QUEST_12_NANCY_BOUNTY) == QUEST_NONE) then
      call Node008;
   else if (global_var(GVAR_QUEST_12_INGMAR_BOUNTY) == QUEST_NONE) then
      call Node010;
   else if (global_var(GVAR_QUEST_12_KYLE_BOUNTY) == QUEST_NONE) then
      call Node012;
   else if (global_var(GVAR_QUEST_12_RYAN_BOUNTY) == QUEST_NONE) then
      call Node014;
   else
      call Node043;
end

procedure StartBountyCraig begin
   set_global_var(GVAR_QUEST_12_CRAIG_BOUNTY, QUEST_ACCEPTED);
   call Node046;
end

procedure StartBountyElDiablo begin
   set_global_var(GVAR_QUEST_12_MIGUEL_BOUNTY, QUEST_ACCEPTED);
   call Node046;
end

procedure StartBountyNancy begin
   set_global_var(GVAR_QUEST_12_NANCY_BOUNTY, QUEST_ACCEPTED);
   call Node046;
end

procedure StartBountyIngmar begin
   set_global_var(GVAR_QUEST_12_INGMAR_BOUNTY, QUEST_ACCEPTED);
   call Node046;
end

procedure StartBountyKyle begin
   set_global_var(GVAR_QUEST_12_KYLE_BOUNTY, QUEST_ACCEPTED);
   call Node046;
end

procedure StartBountyRyan begin
   set_global_var(GVAR_QUEST_12_RYAN_BOUNTY, QUEST_ACCEPTED);
   call Node046;
end

procedure Make_Inven begin
   variable item;

   if (random(1,20) <= 15) then begin
       item:=create_object(PID_AFTER_BURNER_GUM,0,0);
       add_mult_objs_to_inven(self_obj,item,random(2,5));
   end

   if (random(1,20) <= 10) then begin
       item:=create_object(PID_PSYCHO,0,0);
       add_mult_objs_to_inven(self_obj,item,random(1,3));
   end

   if (random(1,20) <= 3) then begin
       item:=create_object(PID_SUPER_STIMPAK,0,0);
       add_mult_objs_to_inven(self_obj,item,random(1,2));
   end

   if (random(1,20) <= 5) then begin
       item:=create_object(PID_GREASE_GUN,0,0);
       add_mult_objs_to_inven(self_obj,item,random(1,2));
   end

   if (random(1,20) <= 7) then begin
       item:=create_object(PID_223_FMJ,0,0);
       add_mult_objs_to_inven(self_obj,item,random(2,3));
   end

   if (random(1,20) <= 1) then begin
       item:=create_object(PID_LEATHER_ARMOR_MK_II,0,0);
       add_mult_objs_to_inven(self_obj,item,1);
   end

   if (random(1,20) <= 2) then begin
       item:=create_object(PID_COMBAT_SHOTGUN,0,0);
       add_mult_objs_to_inven(self_obj,item,1);
   end

   if (random(1,20) <= 3) then begin
       item:=create_object(PID_MICRO_FUSION_CELL,0,0);
       add_mult_objs_to_inven(self_obj,item,random(1,2));
   end

   if (random(1,20) <= 5) then begin
       item:=create_object(PID_SPIKED_KNUCKLES,0,0);
       add_mult_objs_to_inven(self_obj,item,random(1,2));
   end

   if (random(1,20) <= 10) then begin
       item:=create_object(PID_ROPE,0,0);
       add_mult_objs_to_inven(self_obj,item,random(2,3));
   end

   if (random(1,20) <= 3) then begin
       item:=create_object(PID_SCOPED_HUNTING_RIFLE,0,0);
       add_mult_objs_to_inven(self_obj,item,random(1,2));
   end

   if (random(1,20) <= 4) then begin
       item:=create_object(PID_BALL_AND_CHAIN_WEAPON,0,0);
       add_mult_objs_to_inven(self_obj,item,random(1,2));
   end

   if (random(1,20) <= 15) then begin
       item:=create_object(PID_BUFFOUT,0,0);
       add_mult_objs_to_inven(self_obj,item,random(2,5));
   end

   if (random(1,20) <= 10) then begin
       item:=create_object(PID_COMBAT_KNIFE,0,0);
       add_mult_objs_to_inven(self_obj,item,random(2,3));
   end

   if (random(1,20) <= 6) then begin
       item:=create_object(PID_FRAG_GRENADE,0,0);
       add_mult_objs_to_inven(self_obj,item,random(3,5));
   end
end

//xxxxxxxxxxxxxxxxxxxx
