/*

        Fan Made Fallout NPC Script

        Name:           Candice
        Location:
        Description:

           Created: 12.3.2023. 16:19:54

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_C /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_HDCANDIC

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_HOOVER_DAM)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\HEADERS\hdam.h"


/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure push_p_proc;
/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





/* User defined variables */




// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Dumb01;
procedure Dumb02;
procedure Dumb03;
procedure Dumb04;
procedure Dumb05;
procedure Dumb06;
procedure TeachingStart;
procedure TeachingEnd;
procedure StartCutscene;
procedure RunClassCutscene;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin

end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_HOOVER_DAM);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin
   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

   if (dude_is_stupid and local_var(LVAR_Herebefore) == 1) then
      display_mstr(1220);
   else begin

       start_gdialog(NAME,self_obj,4,HEAD_CANDICE,BACKGROUND1);
       gSay_Start;
       if (local_var(LVAR_Herebefore) == 0) then
          call Node001;
      else begin
         if (global_var(GVAR_QUEST_TEACH_CLASS) == 1) then
            call TeachingEnd;
         else
            call Node014;
      end
       gSay_End;
       end_dialogue;
   end

   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin
   if(global_var(GVAR_QUEST_TEACH_CLASS) == 1) then
      call RunClassCutscene;
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

procedure push_p_proc begin
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
set_dr_yuri_know_people_flag(DR_YURI_KNOW_CANDICE);
end
end

// Skill checks and miscellaneous procedures






// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
if (dude_is_male) then Reply(200); else
if (dude_is_female) then Reply(201);
NOption(202,Node003,4);
GOption(203,Node002,4);
NOption(204,Dumb01,-3);
end

procedure Node002
begin
if (dude_is_male) then Reply(230); else
if (dude_is_female) then Reply(231);
NOption(232,Node999,4);
end

procedure Node003
begin
Reply(260);
NOption(261,Node004,4);
end

procedure Node004
begin
Reply(290);
NOption(291,Node005,4);
end

procedure Node005
begin
if (dude_is_male) then Reply(320); else
if (dude_is_female) then Reply(321);
NOption(322,Node006,4);
end

procedure Node006
begin
Reply(350);
NOption(351,Node007,4);
end

procedure Node007
begin
Reply(380);
NOption(381,Node008,4);
NOption(382,Node999,4);
end

procedure Node008
begin
Reply(410);
if (global_var(GVAR_QUEST_SCHOOLS_IN) == 0) then
NOption(411,Node009,4);
NOption(412,Node999,4);
end

procedure Node009
begin
Reply(440);
if (global_var(GVAR_QUEST_SCHOOLS_IN) == 0) then
NOption(441,Node010,4);
NOption(442,Node999,4);
end

procedure Node010
begin
Reply(470);
if (ncr_bos_war_ended) then
NOption(471,Node016,4);
NOption(472,Node012,4);
NOption(473,Node999,4);
end

procedure Node011
begin
Reply(500);
BOption(501,Node998,4);
BOption(502,Node013,4);
end

procedure Node012
begin
Reply(530);
NOption(232,Node999,4);
end

procedure Node013
begin
Reply(560);
NOption(232,Node999,4);
end

procedure Node014
begin
if (dude_is_male) then Reply(590); else
if (dude_is_female) then Reply(591);
if (global_var(GVAR_QUEST_SCHOOLS_IN) == 99 and global_var(GVAR_QUEST_TEACH_CLASS) == 0) then
NOption(592,Node017,4);
if (global_var(GVAR_QUEST_SCHOOLS_IN) == 0) then
NOption(593,Node010,4);
NOption(594,Node003,4);
if (global_var(GVAR_QUEST_SCHOOLS_IN) > 1 and global_var(GVAR_QUEST_SCHOOLS_IN) < 99) then
NOption(595,Node015,4);
if (
   (global_var(GVAR_QUEST_HOOVER_HISTORY) == QUEST_NONE) and
   (dude_item(PID_HOLODISK_S1C) or dude_item(PID_HOLODISK_S1C_DL)) and
   (dude_item(PID_HOLODISK_HD) or dude_item(PID_HOLODISK_HD_DL))
   ) then
NOption(597,Node020,4);
NOption(596,Node999,4);
end

procedure Node015
begin

give_xp(25 * global_var(GVAR_QUEST_SCHOOLS_IN));
set_global_var(GVAR_QUEST_SCHOOLS_IN, 99);
display_mstr(150);

if (dude_is_male) then Reply(620); else
if (dude_is_female) then Reply(621);
NOption(622,Node017,4);
NOption(623,Node999,4);
end

procedure Node016
begin
Reply(650);
GOption(651,Node018,4);
end

procedure Node017
begin
Reply(680);
GOption(681,TeachingStart,7);
BOption(682,Node011,4);
GOption(683,TeachingStart,4);
NOption(473,Node999,4);
end

procedure Node018
begin
set_global_var(GVAR_QUEST_SCHOOLS_IN, 1);
if (dude_is_male) then Reply(710); else
if (dude_is_female) then Reply(711);
NOption(712,Node999,4);
end

procedure Node019
begin
Reply(740);
if (ncr_bos_war_ended) then
NOption(471,Node016,4);
NOption(472,Node012,4);
NOption(473,Node999,4);
end


procedure Dumb01 begin
Reply(1040);
NOption(1041,Dumb02,-3);
end

procedure Dumb02 begin
Reply(1070);
NOption(1071,Dumb03,-3);
end

procedure Dumb03 begin
Reply(1100);
GOption(1101,Dumb04,-3);
end

procedure Dumb04 begin
Reply(1130);
GOption(1131,Dumb05,-3);
end

procedure Dumb05 begin
Reply(1160);
NOption(1161,Dumb06,-3);
end

procedure Dumb06 begin
Reply(1190);
NOption(1191,Node999,-3);
end

procedure TeachingStart
begin
   set_global_var(GVAR_QUEST_TEACH_CLASS, 1);
   Reply(770);
   GOption(771, StartCutscene, 4);
end

procedure TeachingEnd
begin
   variable totalxp = (20 * dude_iq) + (10 * dude_charisma);
   set_global_var(GVAR_QUEST_TEACH_CLASS, 2);
   give_xp(totalxp);
   display_mstr(151);
   inc_hoover_dam_rep(5);
   inc_general_rep(5);

   if (dude_charisma < 5) then begin
      Reply(830);
      NOption(831, Node999, 4);
   end
   else if (dude_is_smart) then begin
      Reply(800);
      NOption(803, Node999, 4);
   end
   else begin
      Reply(801);
      NOption(802, Node999, 4);
   end
end

procedure StartCutscene begin

   variable player_tile = 26682;
   variable candice_tile = 27077;

   fadeout(1);

   party_no_follow_on;
   reg_anim_clear(self_obj);

   // Clear out any previous floaters so they don't overlap
   float_msg(self_obj, " ", FLOAT_COLOR_NORMAL);
   float_msg(dude_obj, " ", FLOAT_COLOR_NORMAL);
   float_msg_clear(self_obj);
   float_msg_clear(dude_obj);

   move_to(dude_obj, player_tile, dude_elevation);
   critter_attempt_placement(dude_obj, player_tile, dude_elevation);
   move_to(self_obj, candice_tile, dude_elevation);
   critter_attempt_placement(self_obj, candice_tile, dude_elevation);
   Face_Critter(dude_obj, self_obj);
   tile_set_center(player_tile);

   add_timer_event(self_obj, game_ticks(1), 1);
   add_timer_event(self_obj, game_ticks(5), 2);
   add_timer_event(self_obj, game_ticks(10), 3);
   add_timer_event(self_obj, game_ticks(15), 4);
   add_timer_event(self_obj, game_ticks(20), 5);
   add_timer_event(self_obj, game_ticks(25), 6);
   add_timer_event(self_obj, game_ticks(30), 7);
   add_timer_event(self_obj, game_ticks(35), 8);
   add_timer_event(self_obj, game_ticks(40), 9);
   add_timer_event(self_obj, game_ticks(45), 10);
   add_timer_event(self_obj, game_ticks(50), 11);
   add_timer_event(self_obj, game_ticks(55), 12);
   add_timer_event(self_obj, game_ticks(60), 13);
   add_timer_event(self_obj, game_ticks(65), 14);
   add_timer_event(self_obj, game_ticks(70), 15);
   add_timer_event(self_obj, game_ticks(75), 16);
   add_timer_event(self_obj, game_ticks(80), 17);
   add_timer_event(self_obj, game_ticks(85), 18);
end

procedure RunClassCutscene begin
   variable c1 = obj_blocking_tile(27882, 0, BLOCKING_TYPE_AI);
   variable c2 = obj_blocking_tile(27880, 0, BLOCKING_TYPE_AI);
   variable c3 = obj_blocking_tile(28284, 0, BLOCKING_TYPE_AI);
   Face_Critter(c1, dude_obj);

   if (dude_charisma >= 5) then begin

      variable NormalIQ = 0;
      if (not(dude_is_smart)) then
         NormalIQ = 30;

      if(fixed_param == 1) then begin
         fadein(1);
         obj_floater_type(dude_obj, mstr(860 + NormalIQ), FLOAT_COLOR_NORMAL);
         game_ui_disable;
      end
      else if(fixed_param == 2) then
         obj_floater_type(c1, mstr(861 + NormalIQ), FLOAT_COLOR_NORMAL);
      else if(fixed_param == 3) then
         obj_floater_type(dude_obj, mstr(862 + NormalIQ), FLOAT_COLOR_NORMAL);
      else if(fixed_param == 4) then
         fadeout(1);
      else if(fixed_param == 5) then begin
         fadein(1);
         obj_floater_type(dude_obj, mstr(863 + NormalIQ), FLOAT_COLOR_NORMAL);
      end
      else if(fixed_param == 6) then
         obj_floater_type(c3, mstr(864 + NormalIQ), FLOAT_COLOR_NORMAL);
      else if(fixed_param == 7) then
         obj_floater_type(dude_obj, mstr(865 + NormalIQ), FLOAT_COLOR_NORMAL);
      else if(fixed_param == 8) then
         fadeout(1);
      else if(fixed_param == 9) then begin
         fadein(1);
         obj_floater_type(dude_obj, mstr(920 + NormalIQ), FLOAT_COLOR_NORMAL);
      end
      else if(fixed_param == 10) then
         obj_floater_type(c2, mstr(921 + NormalIQ), FLOAT_COLOR_NORMAL);
      else if(fixed_param == 11) then
         obj_floater_type(dude_obj, mstr(922 + NormalIQ), FLOAT_COLOR_NORMAL);
      else if(fixed_param == 12) then
         fadeout(1);
      else if(fixed_param == 13) then begin
         fadein(1);
         obj_floater_type(dude_obj, mstr(923 + NormalIQ), FLOAT_COLOR_NORMAL);
      end
      else if(fixed_param == 14) then
         obj_floater_type(c1, mstr(924 + NormalIQ), FLOAT_COLOR_NORMAL);
      else if(fixed_param == 15) then
         obj_floater_type(dude_obj, mstr(925 + NormalIQ), FLOAT_COLOR_NORMAL);
      else if(fixed_param == 16) then
         fadeout(1);
      else if(fixed_param == 17) then begin
         game_time_advance(ONE_GAME_HOUR * 2);
         fadein(1);
      end
      else begin
         party_no_follow_off;
         game_ui_enable;
         dialogue_system_enter;
      end
   end
   else begin

      variable FemaleLines = 0;
      if (dude_is_female) then
         FemaleLines = 30;

      if(fixed_param == 1) then begin
         fadein(1);
         obj_floater_type(dude_obj, mstr(980), FLOAT_COLOR_NORMAL);
         game_ui_disable;
      end
      else if(fixed_param == 2) then
         obj_floater_type(c3, mstr(981 + FemaleLines), FLOAT_COLOR_WHISPER);
      else if(fixed_param == 3) then
         obj_floater_type(c2, mstr(982 + FemaleLines), FLOAT_COLOR_WHISPER);
      else if(fixed_param == 4) then
         obj_floater_type(dude_obj, mstr(983), FLOAT_COLOR_NORMAL);
      else if(fixed_param == 5) then
         obj_floater_type(c1, mstr(984), FLOAT_COLOR_NORMAL);
      else if(fixed_param == 6) then
         obj_floater_type(dude_obj, mstr(985), FLOAT_COLOR_NORMAL);
      else if(fixed_param == 7) then
         fadeout(1);
      else if(fixed_param == 8) then begin
         fadein(1);
         obj_floater_type(c3, mstr(986), FLOAT_COLOR_NORMAL);
      end
      else if(fixed_param == 9) then
         obj_floater_type(c1, mstr(987), FLOAT_COLOR_NORMAL);
      else if(fixed_param == 10) then
         obj_floater_type(c2, mstr(988 + FemaleLines), FLOAT_COLOR_NORMAL);
      else if(fixed_param == 11) then
         obj_floater_type(dude_obj, mstr(989), FLOAT_COLOR_NORMAL);
      else if(fixed_param == 12) then
         obj_floater_type(c3, mstr(990), FLOAT_COLOR_NORMAL);
      else if(fixed_param == 13) then
         fadeout(1);
      else if(fixed_param == 14) then begin
         obj_floater_type(dude_obj, mstr(991), FLOAT_COLOR_SAD);
         fadein(1);
      end
      else begin
         game_time_advance(ONE_GAME_HOUR * 2);
         party_no_follow_off;
         game_ui_enable;
         dialogue_system_enter;
      end
   end

end

procedure Node020
begin
Reply(1250);
GOption(1251,Node021,4);
NOption(1252,Node999,4);
end

procedure Node021
begin
   fadeout(1);
   game_time_advance(ONE_GAME_HOUR);
   fadein(1);

   if (dude_item(PID_HOLODISK_S1C)) then
      remove_pid_qty(dude_obj, PID_HOLODISK_S1C, 1)
   if (dude_item(PID_HOLODISK_S1C_DL)) then
      remove_pid_qty(dude_obj, PID_HOLODISK_S1C_DL, 1)
   if (dude_item(PID_HOLODISK_HD)) then
      remove_pid_qty(dude_obj, PID_HOLODISK_HD, 1)
   if (dude_item(PID_HOLODISK_HD_DL)) then
      remove_pid_qty(dude_obj, PID_HOLODISK_HD_DL, 1)

      set_global_var(GVAR_QUEST_HOOVER_HISTORY, QUEST_COMPLETED);
      give_xp(400);
      display_mstr(152);

Reply(1280);
NOption(1281,Node022,4);
end

procedure Node022
begin
   give_pid_qty(dude_obj, PID_FIRST_AID_BOOK, 1)
   give_pid_qty(dude_obj, PID_SCOUT_HANDBOOK, 1)
Reply(1310);
NOption(1311,Node023,4);
end

procedure Node023
begin
set_global_var(GVAR_QUEST_WASTELAND_HISTORY, QUEST_ACCEPTED);
Reply(1340);
NOption(1341,Node999,4);
end


//xxxxxxxxxxxxxxxxxxxx
