/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/*
        Name: Elise
        Location: NCR Map 1
        Description: Ranger leader

        Log:
           Please note any changes that have been made to the file in Updated. Then comment
           the code which you have changed/altered/commented out. Please, do not delete any
           code which was written.

           Created:

           Updated:
*/

/* Include Files */

/* Note, the Following Lines need to be in this order so that
   the script will be compilable. The define Name is referenced
   in a module from define.h and used in command.h. Please do
   not change the ordering.
        -rwh2   11/13/97
*/
#include "..\headers\define.h"

#define NAME                    SCRIPT_HDELISE
#define TOWN_REP_VAR         GVAR_TOWN_REP_HOOVER_DAM

#include "..\headers\command.h"
#include "..\headers\ModReact.h"
#include "..\headers\party.h"
#include "..\headers\hdam.h"


/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;

/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending


// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Starttile                  (7)

#define TIMER_ATTACK 1

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */

/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;
variable Node021Rep := 0;

procedure start begin
end

procedure timed_event_p_proc begin
   if (fixed_param == TIMER_ATTACK) then begin
      if (self_can_see_dude) then begin
         set_local_var(LVAR_Hostile, 2);
      end
   end
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_HOOVER_DAM);

   if (not local_var(LVAR_Starttile)) then begin
      set_local_var(LVAR_Starttile, self_tile);
   end

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
   end

   if (not critter_is_fleeing(self_obj)) then begin
      if (self_tile != local_var(LVAR_Starttile) and not anim_busy(self_obj)) then begin
         reg_anim_clear(self_obj);
         reg_anim_begin();
         animate_move_to_tile(local_var(LVAR_Starttile));
         reg_anim_end();
      end
   end
end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
       set_global_var(GVAR_ENEMY_HOOVER_DAM,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin
   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_VERY_INTOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

   ReactToLevel; //added by killap

   start_gdialog(NAME,self_obj,4,HEAD_ELISE,-1);
   gSay_Start;

   if (has_rep_slaver) then begin
         call Node029;
   end else if (dude_is_ranger) then begin
      call Node024;
   end else if (global_var(GVAR_ELISE_TEST) == QUEST_DECLINED) then begin
         call Node030;
   end else if (dude_item(PID_CAESARS_LEGION_FLAG) /*and get_elise_seed == QUEST_ACCEPTED*/) then begin
           call Node020;
   end else if (global_var(GVAR_ELISE_TEST) == QUEST_ACCEPTED) then begin
           call Node019;
   end else if (global_var(GVAR_ELISE_TEST) == QUEST_KNOWN) then begin
           call Node018;
   end else begin
           call Node001;
   end
   gSay_End;
   end_dialogue;

   set_local_var(LVAR_Herebefore, 1);
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter

/* Set global_variable for Enemy status*/

end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
   set_local_var(LVAR_Herebefore, 1);
end


// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE

procedure Node0306a begin
   if (not bad_critter_reaction) then
      call Node003;
   else
      call Node006;
end

procedure Node001 begin
   if (local_var(LVAR_Herebefore) == 0) then
      Reply(103);
   else
      Reply(104);
   if (global_var(GVAR_KIRU_MENTIONED_NCR_RANGERS) == 1) then
      GOption(105, Node002, 4);
      if (global_var(GVAR_CARIB_MENTIONED_NCR_RANGERS) == 1) then
      GOption(106, Node002, 4);
   NOption(107, Node0306a, 4);
   NLowOption(108, Node004);
   if (global_var(GVAR_KNOW_NCR_RANGERS) == 1) then
      NOption(109, Node005, 4);

   NOption(110, Node007, 4);
   NOption(111, Node008, 4);
end

procedure Node002 begin
   Reply(112);
   NOption(113, Node009, 4);
   NOption(114, Node010, 4);
end

procedure Node003 begin
   Reply(115);
   NOption(116, Node013, 4);
   NOption(117, Node009, 4);
   NOption(118, Node007, 4);
end

procedure Node004 begin
   Reply(119);
   NOption(g_mstr(350), Node999, 1);
end

procedure Node1411a begin
   if (not bad_critter_reaction) then
      call Node014;
   else
      call Node011;
end

procedure Node005 begin
   Reply(120);
   NOption(121, Node1411a, 4);
   BOption(122, Node016, 4);
   NOption(123, Node012, 4);
end

procedure Node006 begin
   Reply(124);
   NOption(g_mstr(350), Node999, 1);
end

procedure Node007 begin
   Reply(125);
   NOption(g_mstr(350), Node999, 1);
end

procedure Node008 begin
   Reply(126);
   NOption(g_mstr(350), Node999, 1);
end

procedure Node2611a begin
   if (not bad_critter_reaction) then
      call Node026;
   else
      call Node011;
end

procedure Node009 begin
   Reply(127);
   NOption(128, Node2611a, 4);
   NOption(129, Node017, 4);
   NOption(130, Node028, 4);
end

procedure Node010 begin
   Reply(131);
   NOption(132, Node2611a, 4);
   NOption(133, Node009, 4);
   NOption(134, Node012, 4);
end

procedure Node011 begin
   Reply(135);
   NOption(g_mstr(350), Node999, 1);
end

procedure Node012 begin
   Reply(136);
   NOption(g_mstr(350), Node999, 1);
end

procedure Node013 begin
   Reply(137);
   NOption(138, Node009, 4);
end

procedure Node014 begin
   set_global_var(GVAR_ELISE_TEST, QUEST_KNOWN);
   Reply(139);
   NOption(140, Node015, 4);
   NOption(141, Node015, 4);
end

procedure NodeAccept begin
   set_global_var(GVAR_ELISE_TEST, QUEST_ACCEPTED);
   call Node999;
end

procedure Node015 begin
   Reply(142);
   NOption(143, NodeAccept, 4);
   NOption(144, Node027, 4);
end

procedure Node016 begin
   Reply(145);
   BOption(g_mstr(352), Node998, 1);
end

procedure Node017 begin
   Reply(146);
   NOption(g_mstr(350), Node999, 1);
end

procedure Node018 begin
   Reply(148);
   NOption(149, NodeAccept, 4);
   NOption(150, Node015, 4);
end

procedure Node019 begin
   Reply(151);
   NOption(g_mstr(350), Node999, 1);
end

procedure Node020 begin
   if (global_var(GVAR_ELISE_TEST) == QUEST_ACCEPTED) then begin
      Reply(152);
      NOption(153, Node022, 4);
      NOption(154, Node025, 4);
   end else begin
      Reply(155);
      NOption(156, Node999, 4);
   end
end

procedure Node021 begin
   Node021Rep += 1;
   if (Node021Rep == 0) then begin
      Reply(157);
      NOption(g_mstr(352), Node021, 1);
   end
   else begin
      Reply(178);
      NOption(158, Node014, 4);
      NOption(159, Node025, 4);
   end
end

procedure Node022 begin
   Reply(160);
   GOption(161, Node023, 4);
   BOption(162, Node025, 4);
end

procedure Node023 begin
   set_global_var(GVAR_NCR_PLAYER_RANGER, 1);
   give_pid_qty(dude_obj, PID_RANGER_PIN, 1)
   give_pid_qty(dude_obj, PID_NCR_RANGER_COMBAT_ARMOR, 1)
   inc_general_rep(REP_HERO_NCR_BECAME_RANGER);
   inc_hoover_dam_rep(REP_BONUS_NCR_BECAME_RANGER);
   give_xp(EXP_BECAME_RANGER);
   set_global_var(GVAR_ELISE_TEST, QUEST_COMPLETED);

   Reply(163);
   NOption(g_mstr(350), Node999, 1);
end

procedure Node024 begin
   floater(164);
end

procedure Node999a begin
   set_global_var(GVAR_ELISE_TEST, QUEST_DECLINED);
   call Node999;
end

procedure Node01422a begin
   if (global_var(GVAR_ELISE_TEST) < QUEST_ACCEPTED) then
      call Node014;
   else
      call Node022;
end

procedure Node025 begin
   Reply(165);
   NOption(166, Node999a, 4);
   NOption(167, Node01422a, 4);
end

procedure Node026 begin
   Reply(168);
   NOption(169, Node014, 4);
   NOption(170, Node021, 4);
end

procedure Node027 begin
   Reply(171);
   NOption(172, Node999, 4);
end

procedure Node028 begin
   Reply(173);
   NOption(174, Node999, 4);
end

procedure Node029 begin
   Reply(175);
   NOption(176, Node999, 4);
   BOption(177, Node998, 4); //edit by killap: was NOption
end

procedure Node030 begin
   Reply(179);
   if (dude_item(PID_CAESARS_LEGION_FLAG)) then
      NOption(161, Node022, 4);
   else
      NOption(161, Node014, 4);
   NOption(180, Node999, 4);
end

//xxxxxxxxxxxxxxxxxxxx
