/*

        Name:           Enzo Giordano
        Location:
        Description:

           Created: 24.1.2024. 21:07:25

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"

#define NAME                    SCRIPT_HDENZO

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_HOOVER_DAM)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\HEADERS\hdam.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure map_update_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending
procedure CreateSupport;





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node024a;
procedure Node025;
procedure Node026;
procedure Node026a;
procedure PabloDeal;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Ledger_Once                (8)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */

import variable Enzo_Ptr;
import variable Guido_Ptr;
import variable Vinnie_Ptr;
import variable Major_3Some_Showdown_Ptr;
import variable Crius_3Some_Showdown_Ptr;
import variable TrooperA_3Some_Showdown_Ptr;
import variable TrooperB_3Some_Showdown_Ptr;
import variable TrooperC_3Some_Showdown_Ptr;

/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;
variable day_tile = 15729;
variable day_rot = 2;
variable night_tile = 19724;
variable night_rot = 2;

procedure start begin
   Enzo_Ptr = self_obj;
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   if((global_var(GVAR_QUEST_FRAME_ENZO) == QUEST_COMPLETED) or (global_var(GVAR_QUEST_FRAME_ENZO) == QUEST_DEFAULT_SOLVE)) then
      switch_team(self_obj, TEAM_3SOME_CARAVAN)
   else
      switch_team(self_obj, TEAM_HOOVER_DAM)

   Enzo_Ptr = self_obj;
end

procedure map_update_p_proc begin
   Enzo_Ptr = self_obj;

   if(global_var(GVAR_QUEST_FRAME_ENZO) == QUEST_COMPLETED) then begin
      set_global_var(GVAR_QUEST_FRAME_ENZO, QUEST_DEFAULT_SOLVE);
      set_global_var(GVAR_3S_SHOWDOWN, SHOWDOWN_IN_PROGRESS);
      fadeout(1);
      game_time_advance_hour(1200);
      add_timer_event(self_obj, game_ticks(0), 0);
   end

end

/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if (
      holyfeld_dead and
      self_can_see_dude and
      self_can_speak
      ) then begin
      floater_bad(150);
      call Node998;
   end

   if ((global_var(GVAR_ENEMY_HOOVER_DAM) == 1) and self_can_see_dude) then begin
      self_attack_dude;
  end

   if ((local_var(LVAR_Hostile) != 0) and self_can_see_dude) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

   if (self_can_speak) then begin
      if (night) then begin
         if (self_tile != night_tile) then begin
            animate_move_to_tile(night_tile);
         end
         else begin
            if (self_cur_rot != night_rot) then
               animate_rotation(night_rot);
         end
      end
      else begin
         if (self_tile != day_tile) then begin
            animate_move_to_tile(day_tile);
         end
         else begin
            if (self_cur_rot != day_rot) then
               animate_rotation(day_rot);
         end
      end
   end
end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);

       if(global_var(GVAR_3S_SHOWDOWN) != SHOWDOWN_IN_PROGRESS) then begin
         set_global_var(GVAR_ENEMY_HOOVER_DAM,1);
      end
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

   if (night and self_can_speak) then begin
      floater_whisper(153);
   end else begin

      call set_idiot_savant_int;

      start_gdialog(NAME,self_obj,4,HEAD_ENZO_GIORDANO,-1);
      gSay_Start;

      if (local_var(LVAR_Herebefore)==0) then begin
            call Node001;
      end else if (local_var(LVAR_Herebefore)==1) then begin
            if ((global_var(GVAR_QUEST_3SOME_INVITE) == QUEST_ACCEPTED) and global_var(GVAR_3S_CARAVAN_RUNS) == 1) then
               call Node031;
            else if (
                     (
                        (global_var(GVAR_3S_CARAVAN_RUNS) >= 3) or
                        ((global_var(GVAR_3S_CARAVAN_RUNS) >= 2) and (dude_charisma >= 8))
                     ) and
                     (global_var(GVAR_QUEST_AILIS_EVIDENCE) == QUEST_NONE) and
                     not(cc_dead)
               )  then
               call Node006;
            else
               call Node015;
      end

      gSay_End;
      end_dialogue;

      call restore_idiot_savant_int;
   end
end

procedure timed_event_p_proc begin

   if (fixed_param == 0) then begin
      // 3-Some Showdown
      if(global_var(GVAR_QUEST_FRAME_ENZO) == QUEST_DEFAULT_SOLVE) then begin
         // Do this before positioning the player's party
         call CreateSupport;

         // Dude position
         move_to(dude_obj, 16929, 2);
         critter_attempt_placement(dude_obj, 16929, 2);
         reg_anim_clear(dude_obj);
         reg_anim_begin();
         anim(dude_obj, ANIMATE_ROTATION, 5);
         reg_anim_end();

         if(dude_is_stupid or dude_is_idiot_savant) then begin
            obj_floater_type(dude_obj, mstr(154), FLOAT_COLOR_NORMAL);
         end else begin
            obj_floater_type(dude_obj, mstr(155), FLOAT_COLOR_NORMAL);
         end

         add_timer_event(self_obj, game_ticks(1), 1);
         add_timer_event(self_obj, game_ticks(5), 2);
         add_timer_event(self_obj, game_ticks(11), 3);
         add_timer_event(self_obj, game_ticks(15), 4);
         add_timer_event(self_obj, game_ticks(19), 5);

         party_no_follow_on;

         game_ui_disable;

         fadein(1);
      end
   end
   else if(fixed_param == 1) then begin
      float_msg(Enzo_Ptr, mstr(156), FLOAT_COLOR_BAD);
   end
   else if(fixed_param == 2) then begin
      if(dude_is_stupid or dude_is_idiot_savant) then
         float_msg(dude_obj, mstr(157), FLOAT_COLOR_NORMAL);
      else
         float_msg(dude_obj, mstr(158), FLOAT_COLOR_NORMAL);
   end
   else if(fixed_param == 3) then begin
      float_msg(Enzo_Ptr, mstr(159), FLOAT_COLOR_BAD);
   end
   else if(fixed_param == 4) then begin
      if (holyfeld_dead) then
         float_msg(Enzo_Ptr, mstr(160), FLOAT_COLOR_BAD);
      else
         float_msg(Enzo_Ptr, mstr(161), FLOAT_COLOR_BAD);
   end
   else if(fixed_param == 5) then begin
      party_no_follow_off;
      game_ui_enable;
      attack_setup(Enzo_Ptr, dude_obj);
   end
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_neutral_critter
   set_enzo_dead;

   // Major died before Enzo, so set proper states
   if (major_dead and (global_var(GVAR_3S_SHOWDOWN) == SHOWDOWN_IN_PROGRESS)) then begin
      set_global_var(GVAR_3S_SHOWDOWN, SHOWDOWN_DONE);
   end

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
   set_knows_mizaru;
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
Reply(200);
NOption(201,Node002,4);
BOption(202,Node024,4);
NOption(203,Node999,4);
BOption(204,Node024a,4);
end

procedure Node002
begin
Reply(230);
NOption(231,Node003,4);
end

procedure Node003
begin
Reply(260);
NOption(261,Node004,4);
end

procedure Node004
begin
Reply(290);
NOption(291,Node005,4);
NOption(292,Node999,4);
end

procedure Node005
begin

   if (global_var(GVAR_QUEST_3SOME_INVITE) == QUEST_NONE) then
      set_global_var(GVAR_QUEST_3SOME_INVITE, QUEST_ACCEPTED);

   // -1 means talk to Guido
   if (global_var(GVAR_3S_CARAVAN_RUNS) == 0) then
      set_global_var(GVAR_3S_CARAVAN_RUNS, -1);
Reply(320);
NOption(321,Node999,4);
end

procedure Node006
begin
Reply(350);
NOption(351,Node007,4);
end

procedure Node007
begin
Reply(380);
NOption(381,Node008,4);
end

procedure Node008
begin
Reply(410);
NOption(411,Node009,4);
NOption(412,Node999,4);
end

procedure Node009
begin
Reply(440);
NOption(441,Node010,4);
end

procedure Node010
begin
Reply(470);
NOption(471,Node011,4);
end

procedure Node011
begin
Reply(500);
NOption(501,Node012,4);
end

procedure Node012
begin
Reply(530);
NOption(531,Node013,4);
end

procedure Node013
begin
Reply(560);
NOption(561,Node014,4);
end

procedure Node014
begin
set_global_var(GVAR_QUEST_AILIS_EVIDENCE, CC_INFILTRATION_FAKE_FIGHT);
Reply(590);
NOption(591,Node999,4);
end

procedure Node015
begin
Reply(620);
if ((global_var(GVAR_QUEST_AILIS_EVIDENCE) == CC_INFILTRATION_ONGOING) and (dude_item_count(PID_WRITTEN_LEDGER) > 0) and local_var(LVAR_Ledger_Once) == 0) then
NOption(621,Node016,4);
if (global_var(GVAR_QUEST_HELP_PABLO_RIVIERA) == 1) then
NOption(622,Node019,4);
BOption(202,Node024,4);
NOption(623,Node025,4);
if(global_var(GVAR_DONATE_DR_YURI) == 1) then
NOption(624,Node026,4);
if(global_var(GVAR_KNOW_3SOME_EX_PRISONERS) == 1) then
BOption(625,Node027,4);
if(global_var(GVAR_QUEST_ESTABLISH_TRADE) == QUEST_ACCEPTED) then begin
   GOption(626,Node028,4);
end

if (
   (global_var(GVAR_CIPHER_FOOD) == CIPHER_FOOD_NONE) and
   (global_var(GVAR_QUEST_CIPHERS_MORE_FOOD) == QUEST_ACCEPTED)
) then begin
   NOption(627,Node033,4);
end
NOption(203,Node999,4);
end

procedure Node016
begin
Reply(650);
NOption(651,Node017,4);
NOption(652,Node999,4);
end

procedure Node017
begin

   set_local_var(LVAR_Ledger_Once, 1);
   set_global_var(GVAR_QUEST_AILIS_EVIDENCE, CC_INFILTRATION_DONE);
   remove_pid_qty(dude_obj, PID_WRITTEN_LEDGER, 1)
   item_caps_adjust(dude_obj, 2000);
   give_xp(1000);

Reply(680);
NOption(681,Node018,4);
end

procedure Node018
begin
Reply(710);
NOption(711,Node999,4);
end

procedure Node019
begin
Reply(740);
NOption(741,Node020,4);
end

procedure Node020
begin
Reply(770);
NOption(771,Node021,4);
end

procedure Node021
begin
Reply(800);
NOption(801,Node022,4);
end

procedure Node022
begin
Reply(830);
if (dude_iq > 5) then
   NOption(831,PabloDeal,4);
NOption(832,Node024,4);
end

procedure Node023
begin
   set_global_var(GVAR_QUEST_HELP_PABLO_RIVIERA, 2);
Reply(860);
NOption(861,Node999,4);
end

procedure Node024
begin
Reply(mstr(890) + " " + mstr(891));
NOption(893,Node999,4);
end

procedure Node024a
begin
Reply(mstr(890) + " " + mstr(892));
NOption(893,Node999,4);
end

procedure Node025
begin
   if (global_var(GVAR_3S_CARAVAN_RUNS) == 0) then begin
      set_global_var(GVAR_3S_CARAVAN_RUNS, -1);
   end
Reply(920);
NOption(921,Node999,4);
end

procedure Node026
begin
Reply(950);
if (dude_caps >= 1000) then
   NOption(951,Node026a,4);
else
   NOption(952,Node999,4);
end

procedure Node026a
begin
   inc_hoover_dam_rep(5);
   item_caps_adjust(dude_obj, -1000);
   call Node999;
end

procedure PabloDeal begin
   if (is_success(roll_vs_skill(dude_obj, SKILL_CONVERSANT, -33))) then begin
      call Node023;
   end else begin
      call Node024;
   end
end

procedure Node027
begin
Reply(980);
NOption(981,Node999,4);
end

procedure Node028
begin
Reply(1010);
NOption(1011,Node029,4);
end

procedure Node029
begin
Reply(1040);
NOption(1041,Node030,4);
end

procedure Node030
begin
   give_xp(2000);
   set_global_var(GVAR_QUEST_ESTABLISH_TRADE, QUEST_COMPLETED);
   display_mstr(151);

Reply(1070);
NOption(1071,Node999,4);
end

procedure Node031
begin
Reply(1100);
NOption(1101,Node032,4);
NOption(1102,Node999,4);
end

procedure Node032
begin
   set_global_var(GVAR_QUEST_3SOME_INVITE, QUEST_COMPLETED);
   give_xp(400);
   display_mstr(152);
   Reply(1130);
   NOption(1132,Node999,4);
end

procedure Node033
begin
Reply(1160);
NOption(1161,Node999,4);
if (dude_caps >= 10000) then begin
   NOption(1162,Node034,4);
end
end

procedure Node034
begin
set_global_var(GVAR_CIPHER_FOOD, CIPHER_FOOD_HOOVER_DAM_CARAVANS);
item_caps_adjust(dude_obj, -10000);
Reply(1190);
NOption(1041,Node999,4);
end

procedure CreateSupport begin
   variable Trooper;
   variable Trooper_Counter;
   variable Enzo_Tile;
   variable Guido_Tile;
   variable Vinnie_Tile;
   variable Total_Troopers;

   Trooper_Counter:=0;
   Enzo_Tile:=15729;
   Guido_Tile:=15530;
   Vinnie_Tile:=15727;
   Total_Troopers:=(3 - true_party_size);

   if (Total_Troopers < 0) then
      Total_Troopers = 0;

   // Set Enzo
   if (Enzo_Ptr != 0) then begin
      switch_team(Enzo_Ptr, TEAM_3SOME_CARAVAN)
      if (tile_num(Enzo_Ptr) != Enzo_Tile) then begin
         move_to(Enzo_Ptr, Enzo_Tile, dude_elevation);
         critter_attempt_placement(Enzo_Ptr, Enzo_Tile, dude_elevation);
         reg_anim_clear(Enzo_Ptr);
         reg_anim_begin();
         anim(Enzo_Ptr, ANIMATE_ROTATION, 2);
         reg_anim_end();
      end
   end

   // Set Guido
   if (Guido_Ptr != 0) then begin
      switch_team(Guido_Ptr, TEAM_3SOME_CARAVAN)
      if (tile_num(Guido_Ptr) != Guido_Tile) then begin
         move_to(Guido_Ptr, Guido_Tile, dude_elevation);
         critter_attempt_placement(Guido_Ptr, Guido_Tile, dude_elevation);
         reg_anim_clear(Guido_Ptr);
         reg_anim_begin();
         anim(Guido_Ptr, ANIMATE_ROTATION, 2);
         reg_anim_end();
      end
   end

   // Set Vinnie
   if ((Vinnie_Ptr != 0) and not(holyfeld_dead)) then begin
      switch_team(Vinnie_Ptr, TEAM_3SOME_CARAVAN)
      if (tile_num(Vinnie_Ptr) != Vinnie_Tile) then begin
         move_to(Vinnie_Ptr, Vinnie_Tile, dude_elevation);
         critter_attempt_placement(Vinnie_Ptr, Vinnie_Tile, dude_elevation);
         reg_anim_clear(Vinnie_Ptr);
         reg_anim_begin();
         anim(Vinnie_Ptr, ANIMATE_ROTATION, 3);
         reg_anim_end();
      end
   end

   // Major Fleming
   if (not(major_dead)) then begin
      set_obj_visibility(Major_3Some_Showdown_Ptr, 0);
      switch_team(Major_3Some_Showdown_Ptr, TEAM_PLAYER)
   end

   // Major's Mean Dog
   if (not(crius_dead)) then begin
      set_obj_visibility(Crius_3Some_Showdown_Ptr, 0);
      switch_team(Crius_3Some_Showdown_Ptr, TEAM_PLAYER)
   end

   // NCR Troopers
   while (Trooper_Counter < Total_Troopers) do begin
      Trooper_Counter+=1;

      if (Trooper_Counter == 1) then
         Trooper = TrooperA_3Some_Showdown_Ptr;
      else if (Trooper_Counter == 2) then
         Trooper = TrooperB_3Some_Showdown_Ptr;
      else if (Trooper_Counter == 3) then
         Trooper = TrooperC_3Some_Showdown_Ptr;

      set_obj_visibility(Trooper, 0);
      switch_team(Trooper, TEAM_PLAYER)
   end

   // cleanup
   if (Total_Troopers < 1) then begin
      destroy_object(TrooperA_3Some_Showdown_Ptr);
      destroy_object(TrooperB_3Some_Showdown_Ptr);
      destroy_object(TrooperC_3Some_Showdown_Ptr);
   end
   if (Total_Troopers == 1) then begin
      destroy_object(TrooperB_3Some_Showdown_Ptr);
      destroy_object(TrooperC_3Some_Showdown_Ptr);
   end
   if (Total_Troopers == 2) then begin
      destroy_object(TrooperC_3Some_Showdown_Ptr);
   end
end

//xxxxxxxxxxxxxxxxxxxx
