/*

        Name:           Major Jack Fleming
        Location:
        Description:

           Created: 10.3.2023. 15:08:40

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"

#define NAME                    SCRIPT_HDMAJOR

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_HOOVER_DAM)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\HEADERS\hdam.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node028;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;
procedure Node039;
procedure Node040;
procedure Node041;
procedure Node042;
procedure Node043;
procedure Node044;
procedure Node045;
procedure Node046;
procedure Node047;
procedure Node048;
procedure Node049;
procedure Node050;
procedure Node051;
procedure Node052;
procedure Node053;
procedure Node054;
procedure Node055;
procedure Node056;
procedure Node057;
procedure Node058;
procedure Node059;
procedure Node060;
procedure Node061;
procedure Node062;
procedure Node063;
procedure Node064;
procedure Node065;
procedure combat_tactic;
procedure diplo_tactic;
procedure stealth_tactic;
procedure start_cc_arrest;
procedure drink_redrum;
procedure groom_dogs;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Ledger_Once               (8)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;

   // Cleanup after arrest is done
   if ((ailis_dead or not(self_visible) or global_var(GVAR_QUEST_ARREST_AILIS) == AILIS_ARRESTED) and (cur_map_index == MAP_HOOVER_DAM_NORTH_GATE)) then begin
      destroy_object(self_obj);
   end
   else if (
      ((global_var(GVAR_CC_ARREST) == CC_ARREST_IN_PROGRESS) and (cur_map_index == MAP_HOOVER_DAM_NORTH_GATE))
      ) then begin
         switch_team(self_obj,TEAM_PLAYER)
      end
   else begin
      switch_team(self_obj,TEAM_HOOVER_DAM)

      if (major_dead) then begin
         set_obj_visibility(self_obj, 1);
         destroy_object(self_obj);
      end
      else if (cur_map_index == MAP_HOOVER_DAM_SOUTH_GATE) then begin
            if (
               // Kicking ass at Crimson
               (global_var(GVAR_CC_ARREST) == CC_ARREST_IN_PROGRESS)
               ) then
               set_obj_visibility(self_obj, 1);
            else
               set_obj_visibility(self_obj, 0);
      end
   end
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((global_var(GVAR_CC_ARREST) == CC_ARREST_IN_PROGRESS) and (cur_map_index == MAP_HOOVER_DAM_NORTH_GATE)) then begin
      if (ailis_dead and self_can_speak) then
         dialogue_system_enter;
   end

   if (cc_dead and (TEAM_PLAYER == has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM)) and (cur_map_index == MAP_HOOVER_DAM_NORTH_GATE) and (not(combat_is_initialized))) then
      switch_team(self_obj,TEAM_HOOVER_DAM)

   if ((global_var(GVAR_ENEMY_HOOVER_DAM) == 1) and self_can_see_dude) then begin
      self_attack_dude;
  end

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);

       if (global_var(GVAR_CC_ARREST) != CC_ARREST_IN_PROGRESS) then begin
         set_global_var(GVAR_ENEMY_HOOVER_DAM,1);
       end
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_INTOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

   if (
      (global_var(GVAR_CC_ARREST) == CC_ARREST_DONE) and
      (cur_map_index == MAP_HOOVER_DAM_NORTH_GATE) and
      (global_var(GVAR_QUEST_ARREST_AILIS) == AILIS_ARRESTED)
      ) then begin
         floater(155);
   end
   else if ((global_var(GVAR_CC_ARREST) == CC_ARREST_IN_PROGRESS) and (cur_map_index == MAP_HOOVER_DAM_NORTH_GATE)) then begin
      if (ailis_dead) then begin
         floater(154);
         set_global_var(GVAR_CC_ARREST, CC_ARREST_DONE);
         set_global_var(GVAR_QUEST_ARREST_AILIS, AILIS_KILLED);
         fadeout(1);
         set_obj_visibility(self_obj, 1);
         fadein(1);
      end
      else
         floater(153);
   end
   else if (global_var(GVAR_SHOW_LEDGER_TO_DODGE) == 1) then begin
      floater(151);
   end
   else begin
      start_gdialog(NAME,self_obj,4,HEAD_MAJOR_JACK_FLEMING,BACKGROUND_SEWER);

      if (global_var(GVAR_SHOW_LEDGER_TO_DODGE) == 2) then begin
         call Node065;
      end
      else if (local_var(LVAR_Herebefore)==0) then begin
         if (dude_is_stupid) then
            call Node038;
         else
            call Node001;
      end
      else if (local_var(LVAR_Herebefore)==1) then begin
         call Node003;
      end

      gSay_End;
      end_dialogue;

      if (Only_Once == 1) then begin
         load_map("hdgatenr", 0);
      end

   end
end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
   set_major_dead;

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
   if (dude_is_super_mutant) then begin
      Reply(230);
   end
   else begin
      Reply(200);
   end

NOption(mstr(201)+dude_name+mstr(202),Node002,4);
NOption(mstr(203)+dude_name+mstr(204),Node006,4);
BOption(205,Node998,4);
NOption(206,Node999,4);
end

procedure Node028
begin
Reply(230);
NOption(mstr(203)+dude_name+mstr(231),Node029,4);
NOption(232,Node999,4);
end

procedure Node002
begin
Reply(260);
NOption(261,Node035,4);
NOption(262,Node023,4);
NOption(263,Node999,4);
end

procedure Node003
begin
Reply(mstr(290)+dude_name+mstr(291));
if (global_var(GVAR_QUEST_MEET_DODGE) == 1) then
   NOption(292,Node061,4);
NOption(293,Node034,4);
NOption(294,Node004,4);
NOption(295,Node007,4);
NOption(263,Node999,4);
end

procedure Node004
begin
Reply(320);
NOption(321,Node005,4);
end

procedure Node005
begin
Reply(350);
NOption(351,Node030,4);
NOption(352,Node007,4);
NOption(353,Node999,4);
end

procedure Node006
begin
Reply(380);
NOption(381,Node013,4);
NOption(382,Node012,4);
NOption(383,Node013,4);
NOption(384,Node010,4);
NOption(385,Node999,4);
end

procedure Node007
begin
Reply(mstr(410)+dude_name+mstr(411));
NOption(412,Node013,4);
NOption(413,Node010,4);
NOption(382,Node012,4);
NOption(414,Node999,4);
end

procedure Node008
begin
Reply(440);
NOption(441,Node014,4);
NOption(442,Node015,4);
NOption(443,Node017,4);
NOption(444,Node018,4);
if (town_known(AreaNukeStatus(AREA_BROTHERHOOD_OF_STEEL))) then
NOption(445,Node046,4);
NOption(446,Node999,4);
end

procedure Node009
begin
Reply(470);
NOption(471,Node011,4);
NOption(472,Node008,4);
NOption(473,Node999,4);
end

procedure Node010
begin
Reply(500);
NOption(501,Node019,4);
NOption(502,Node011,4);
NOption(503,Node016,4);
NOption(504,Node999,4);
end

procedure Node011
begin
   set_global_var(GVAR_KNOW_NCR_RANGERS, 1);
Reply(530);
NOption(531,Node008,4);
NOption(532,Node016,4);
NOption(533,Node012,4);
NOption(534,Node999,4);
end

procedure Node012
begin
Reply(560);
NOption(561,Node025,4);
NOption(562,Node011,4);
NOption(563,Node024,4);
NOption(564,Node999,4);
end

procedure Node013
begin
Reply(590);
NOption(591,Node011,4);
NOption(592,Node012,4);
NOption(593,Node024,4);
NOption(413,Node010,4);
NOption(594,Node047,4);
NOption(595,Node999,4);
end

procedure Node014
begin
Reply(620);
NOption(621,Node015,4);
NOption(622,Node022,4);
NOption(623,Node010,4);
NOption(624,Node999,4);
end

procedure Node015
begin
Reply(650);
NOption(651,Node042,4);
NOption(652,Node027,4);
NOption(653,Node013,4);
NOption(654,Node999,4);
end

procedure Node016
begin
Reply(680);
NOption(681,Node013,4);
NOption(682,Node024,4);
NOption(683,Node008,4);
NOption(684,Node999,4);
end

procedure Node017
begin
Reply(710);
NOption(711,Node015,4);
NOption(712,Node001,4);
NOption(713,Node018,4);
end

procedure Node018
begin
Reply(740);
NOption(741,Node021,4);
NOption(742,Node999,4);
end

procedure Node019
begin
Reply(770);
NOption(321,Node020,4);
end

procedure Node020
begin
Reply(800);
NOption(801,Node011,4);
NOption(802,Node016,4);
NOption(803,Node999,4);
end

procedure Node021
begin
Reply(830);
NOption(831,Node010,4);
if (global_var(GVAR_KNOW_PIERRE_BOS) == 1) then begin
   NOption(1942,Node060,4);
end
NOption(832,Node999,4);
end

procedure Node022
begin
Reply(860);
NOption(861,Node015,4);
NOption(862,Node999,4);
end

procedure Node023
begin
Reply(890);
NOption(891,Node025,4);
NOption(892,Node007,4);
end

procedure Node024
begin
Reply(920);
NOption(921,Node010,4);
NOption(922,Node999,4);
end

procedure Node025
begin
Reply(950);
NOption(951,Node026,4);
NOption(952,Node999,4);
end

procedure Node026
begin
Reply(980);
NOption(981,Node999,4);
end

procedure Node027
begin
Reply(1010);
NOption(1011,Node009,4);
NOption(1012,Node024,4);
NOption(1013,Node999,4);
end

procedure Node029
begin
Reply(1040);
NOption(472,Node008,4);
NOption(1041,Node009,4);
NOption(1042,Node999,4);
end

procedure Node030
begin
Reply(1070);
NOption(321,Node031,4);
NOption(1071,Node999,4);
end

procedure Node031
begin
   fadeout(1);
   fadein(1);
Reply(1100);
NOption(1101,Node032,4);
end

procedure Node032
begin
Reply(1130);
NOption(1131,Node033,4);
NOption(1132,Node033,4);
end

procedure Node033
begin
Reply(1160);
NOption(1161,Node029,4);
NOption(1162,Node999,4);
end

procedure Node034
begin
Reply(1190);
NOption(261,Node035,4);
NOption(1191,Node029,4);
end

procedure Node035
begin
Reply(1220);
NOption(1221,Node036,4);
NOption(1222,Node029,4);
NOption(1223,Node999,4);
NOption(1224,Node999,4);
end

procedure Node036
begin
Reply(1250);
NOption(1251,drink_redrum,4);
end

procedure Node037
begin
Reply(1280);
NOption(1281,Node035,4);
NOption(1282,Node029,4);
NOption(1283,Node999,4);
end

procedure Node038
begin
Reply(1310);
NOption(1311,Node039,-3);
NOption(1312,Node999,-3);
end

procedure Node039
begin
Reply(1340);
NOption(1341,Node040,-3);
NOption(1342,Node042,-3);
NOption(1343,Node045,-3);
NOption(1344,Node041,-3);
NOption(1345,Node999,-3);
end

procedure Node040
begin
Reply(1370);
NOption(1371,Node999,-3);
end

procedure Node041
begin
Reply(1400);
NOption(1401,Node999,-3);
end

procedure Node042
begin
Reply(1430);
NOption(1431,Node043,-3);
NOption(1432,Node040,-3);
NOption(1345,Node999,-3);
end

procedure Node043
begin
Reply(1460);
NOption(1461,Node999,-3);
end

procedure Node044
begin
Reply(1490);
NOption(1491,Node040,-3);
NOption(1492,Node999,-3);
end

procedure Node045
begin
Reply(1520);
NOption(1521,groom_dogs,-3);
end

procedure Node046
begin
Reply(1550);
NOption(1551,Node057,4);
NOption(1552,Node051,4);
end

procedure Node047
begin
Reply(1580);
NOption(321,Node048,4);
end

procedure Node048
begin
Reply(1610);
NOption(1611,Node049,4);
end

procedure Node049
begin
Reply(1640);
NOption(1641,Node050,4);
end

procedure Node050
begin
Reply(1670);
NOption(1671,Node051,4);
NOption(1672,Node999,4);
end

procedure Node051
begin
Reply(1700);
NOption(1701,Node052,4);
NOption(1702,Node999,4);
end

procedure Node052
begin
Reply(1730);
NOption(1731,Node053,4);
NOption(1732,Node999,4);
end

procedure Node053
begin
Reply(1760);
NOption(1761,Node054,4);
NOption(1762,Node999,4);
end

procedure Node054
begin
Reply(1790);
NOption(1791,Node055,4);
NOption(1792,Node999,4);
end

procedure Node055
begin
   set_global_var(GVAR_QUEST_MEET_DODGE, 1);
Reply(mstr(1820)+dude_name+mstr(1821));
NOption(1822,Node999,4);
end

procedure Node056
begin
   finish_quest_meet_dodge
Reply(1850);
NOption(1851,Node058,4);
NOption(1852,Node057,4);
end

procedure Node057
begin
   finish_quest_meet_dodge
Reply(1880);
NOption(1822,Node999,4);
end

procedure Node058
begin
   finish_quest_meet_dodge
Reply(mstr(1910)+dude_name+mstr(1911));
NOption(1822,Node999,4);
end

procedure Node059
begin
Reply(1940);
NOption(1941,Node046,4);
if (global_var(GVAR_KNOW_PIERRE_BOS) == 1) then
NOption(1942,Node060,4);
BOption(1943,Node998,4);
NOption(1944,Node999,4);
end

procedure Node060
begin
   finish_quest_meet_dodge
   set_global_var(GVAR_KNOW_PIERRE_BOS, 2);
   dec_general_rep(40);
   give_xp(500);
   display_mstr(152);
Reply(1970);
NOption(1822,Node999,4);
end

procedure Node061
begin
Reply(2000);

if (
   (global_var(GVAR_AILIS_DODGE_MEET_OK) == 1) and
   (global_var(GVAR_QUEST_MEET_DODGE) == 1)
   ) then
   NOption(2001,Node058,4);

if (global_var(GVAR_QUEST_AILIS_EVIDENCE) == CC_INFILTRATION_DONE) then
   NOption(2002,Node056,4);

if (global_var(GVAR_QUEST_UPGRADE_FILTER) == FILTRATION_SCHEMATICS_FOUND) then begin
   if (global_var(GVAR_DUDE_FIXED_WATER_FILTER) == 1) then
      NOption(2003,Node057,4);
   if (global_var(GVAR_DUDE_FIXED_WATER_FILTER) == 0) then
      NOption(2004,Node059,4);
end

if ((dude_item_count(PID_WRITTEN_LEDGER) == 2) and local_var(LVAR_Ledger_Once) == 0) then
NOption(2006,Node062,4);

NOption(2005,Node999,4);
end

procedure Node062
begin
   fadeout(1);
   game_time_advance(ONE_GAME_HOUR);
   fadein(1);
   finish_quest_meet_dodge
   set_global_var(GVAR_SHOW_LEDGER_TO_DODGE, 1);
   set_local_var(LVAR_Ledger_Once, 1);
Reply(2030);
NOption(1822,Node999,4);
end

procedure Node063
begin
Reply(mstr(2059 + global_var(GVAR_CC_ARREST_TACTIC)));
NOption(1822,start_cc_arrest,4);
end

procedure Node064
begin
Reply(mstr(2089 + global_var(GVAR_CC_ARREST_TACTIC)) + " " + mstr(2093));
NOption(1822,Node999,4);
end

procedure Node065
begin
   set_global_var(GVAR_SHOW_LEDGER_TO_DODGE, 3);

   if (cc_dead) then begin
      Reply(2125);
      GOption(2126,Node999,4);
      BOption(2127,Node999,4);
   end else begin
      Reply(2120);
      NOption(2121,combat_tactic,4);
      NOption(2122,diplo_tactic,4);
      NOption(2123,stealth_tactic,4);
      BOption(2124,Node999,4);
   end
end

procedure combat_tactic begin
   set_global_var(GVAR_CC_ARREST_TACTIC, CC_ARREST_TACTIC_COMBAT);
   call Node063;
end

procedure diplo_tactic begin
   set_global_var(GVAR_CC_ARREST_TACTIC, CC_ARREST_TACTIC_DIPLO);
   call Node063;
end

procedure stealth_tactic begin
   set_global_var(GVAR_CC_ARREST_TACTIC, CC_ARREST_TACTIC_STEALTH);
   call Node063;
end

procedure start_cc_arrest begin
   fadeout(1);
   set_global_var(GVAR_CC_ARREST, CC_ARREST_ASSIST);
   Only_Once = 1;
   call Node999;
end

procedure drink_redrum begin
   fadeout(1);
   game_time_advance(ONE_GAME_HOUR);

   reg_anim_clear(dude_obj);
   reg_anim_begin();
   reg_anim_animate(dude_obj,ANIM_fall_front,-1);
   reg_anim_animate(dude_obj,ANIM_prone_to_standing,-1);
   reg_anim_end();

   fadein(1);
   call Node999;
end

procedure groom_dogs begin
   fadeout(1);
   game_time_advance(ONE_GAME_HOUR * 3);
   fadein(1);
   display_mstr(150);
   call Node999;
end

//xxxxxxxxxxxxxxxxxxxx
