/*

        Name:           Mark Gannon
        Location:
        Description:    So, just to recap: Gannon is a companion, located at Hoover Dam. He appears as a Cassidy/Tycho type - hardbitten, loyal, and an all-round excellent gunslinging Everyman companion. There's just one problem - he is, the player will eventually discover, an Enclave soldier who's travelled east in the hope of finding the long-rumoured BOMB 001 and will summarily betray the player right before the climax.

           Created: 03/01/2023 20:46:26

*/

//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TG /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        9 /* same as thief variable */

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\ModReact.h"
#include "..\headers\party.h"
#include "..\HEADERS\partybkg.h"
#include "..\HEADERS\footsteps.h"

// Mark
/* Highlight "Mark" above and press CTRL+F to activate the Find function.
   Type your new character's name in the replace box, check "Find all matches",
   check "Find in current scripts", fill your character name in the Replace Text box,
   then select "Find & Replace". */


/* Don't forget to change the NAME and TOWN_REP_VAR variables to match your new critter */
#define NAME                    SCRIPT_HDMARK
#define TOWN_REP_VAR            (0)



/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure push_p_proc;
procedure timed_event_p_proc;

/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

/*****************************************************************
Node001 is a dialogue node that includes a line asking to join the party.
Node002 has several game checks before joining with fail/pass responses.
*****************************************************************/
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node007a;
procedure Node007b;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;
procedure Node039;
procedure Node040;
procedure Node041;
procedure Node042;
procedure Node043;
procedure Node044;
procedure Node045;
procedure Node046;
procedure Node047;
procedure Node048;
procedure Node049;
procedure Node050;
procedure Node051;
procedure Node052;
procedure Node053;
procedure Node054;
procedure Node055;
procedure Node056;
procedure Node057;
procedure Node058;
procedure Node059;
procedure Node060;
procedure Node061;
procedure Node062;
procedure Node063;
procedure Node064;
procedure Node065;
procedure Node066;
procedure Node067;
procedure Node068;
procedure Node069;
procedure Node070;
procedure Node071;
procedure Node072;
procedure Node073;
procedure Node074;
procedure Node075;
procedure Node076;
procedure Node077;
procedure Node078;
procedure Node079;
procedure Node080;
procedure Node081;
procedure Node082;
procedure Node083;
procedure Node084;
procedure Node085;
procedure Node086;
procedure Node087;
procedure Node088;
procedure Node089;
procedure Node090;
procedure Node091;
procedure Node092;
procedure Node093;
procedure Node094;
procedure Node095;
procedure Node096;
procedure Node097;
procedure Node098;
procedure Node099;
procedure Node100;
procedure Node101;
procedure Node102;
procedure Node103;
procedure Node104;
procedure Node105;
procedure Node106;
procedure Node107;
procedure Node108;
procedure Node109;
procedure Node110;
procedure Node111;
procedure Node112;
procedure Node113;
procedure Node114;
procedure Node115;
procedure Node116;
procedure Node117;
procedure Node118;

/*****************************************************************
Party Member pre-requisites
These lines are necessary for the critter to join the player
as a party member.
*****************************************************************/
procedure Join_Party;                                    // Party Join node
procedure Abandon_Party;                                 // Party Abandon node
procedure Node1000;                                      // Main party member node
procedure Node1001;                                      // heal yourself
procedure Node1002;                                      // wait here
procedure Node1003;                                      // put your weapon away
procedure Node1004;                                      // follow close
procedure Node1005;                                      // follow medium
procedure Node1006;                                      // follow far
procedure Node1007;                                      // change distance menu
procedure Node1008;                                      // look at gear menu
procedure Node1009;                                      // remove armor menu
procedure Node1010;                                      // weapon abilities
procedure Node1100;                                      // rejoin party


/* Change "Mark" to match the name of your new critter */
#define Mark_joins_party             party_add_self;                                                   \
                                               critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_PLAYER)
#define dude_has_free_slot_for_Mark  ((dude_at_max_party_size == false) and (Mark_In_Party == false))

#define LVAR_Flags                      (4)
#define LVAR_WAITING                    (5)
#define LVAR_FOLLOW_DISTANCE            (6)
#define LVAR_TEAM                       (7)
#define LVAR_Joined_Player              (8)
#define LVAR_Caught_Thief               (9)

/*****************************************************************
      If you would rather use the LVAR_Hostile, LVAR_Herebefore, LVAR_Personal_Enemy
      variables instead of LVAR_Flags, uncomment the relevent lines and comment out
      lines with set_herebefore, set_hostile, if (hostile) and (self_can_see_dude).
*****************************************************************/
//#define LVAR_Hostile                    (9)
#define LVAR_Herebefore                 (10)
//#define LVAR_Personal_Enemy             (11)

#define PARTY_NODE_X                      Node1000

/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/
variable begin
end

/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin
end

procedure map_enter_p_proc begin
   /*  This procedure will get called each time that the map is first entered. It will
       set up the Team number and AI packet for this critter. This will override the
       default from the prototype, and needs to be set in scripts. */

   //party_member_map_enter;
   if (Mark_In_Party) then begin
	  add_timer_event(self_obj, 15, 1);
   end
   // TODO Swap this for collapsed parking location when finished
   if (
      (cur_map_index == MAP_BLOOMFIELD_CONTROL_CENTER_NORTH) and
      (global_var(GVAR_ACT) == 2) and
      Mark_In_Party and
      (global_var(GVAR_MARK_GANNON_BETRAY) == 0)
   ) then begin
      set_global_var(GVAR_MARK_GANNON_BETRAY, 1);
      set_obj_visibility(self_obj, 1);
      dude_floater(206);
      call Abandon_Party;
      destroy_object(self_obj);
   end
   else if (
      (cur_map_index == MAP_BLOOMFIELD_CONTROL_CENTER_EAST) and
      (global_var(GVAR_MARK_GANNON_BETRAY) == 1) and
      not(Mark_In_Party)
   ) then begin
      set_obj_visibility(self_obj, 0);
      switch_team(self_obj,TEAM_ENCLAVE)
      critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_ENCLAVE_PATROL);
   end
   else if (
      (cur_map_index == MAP_BLOOMFIELD_CONTROL_CENTER_EAST) and
      (global_var(GVAR_MARK_GANNON_BETRAY) < 1)
   ) then begin
      set_obj_visibility(self_obj, 1);
   end
   else if (not(Mark_In_Party)) then begin
      critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM,TEAM_ENCLAVE);
      critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET,AI_PARTY_MARK_CUSTOM);
   end

   call critter_setup_footsteps_map_enter(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT);
end

procedure timed_event_p_proc begin
   if (fixed_param == 1) then begin 
		variable extra_health;
		if (dude_level > 1)  then begin
			extra_health := ((floor(self_endurance/2) + 2) * (dude_level-1));
			set_critter_extra_stat(self_obj, STAT_max_hp, extra_health);
		end		
   end
   call critter_setup_footsteps_timed_event(self_obj, WALKING_TICKS_DEFAULT, RUNNING_TICKS_DEFAULT, SFX_FOOTSTEP_MEDIUM_SHOE);
end

procedure critter_p_proc begin
   /* Every heartbeat that the critter gets, this procedure will be called. Anything from
      Movement to attacking the player on sight can be placed in here.
      If the critter is mad at the player for any reason, it will attack and remember to attack
      the player should the game be saved and loaded repeatedly. Additionally, if any special
      actions need to be taken by the critter based on previous combat, the critter will remember
      this as well. */


   if (
      (self_can_see_dude or self_can_hear_dude) and
      (global_var(GVAR_MARK_GANNON_BETRAY) == 1) and
      (cur_map_index == MAP_BLOOMFIELD_CONTROL_CENTER_EAST) and
      self_can_speak
      ) then begin
      dialogue_system_enter;
   end

//   if ((local_var(LVAR_Hostile) > 1) and (self_can_see_dude)) then begin
//      set_local_var(LVAR_Hostile,1);
   if (hostile) and (self_can_see_dude) then begin
      self_attack_dude; //Macro made by Tom to keep the critter fleeing.
   end

   /* This next script moves the new party member to follow the player after they've joined and
      when entering new maps. */
   if (Mark_In_Party) then begin
      if (party_is_waiting == false) then begin
         party_member_follow_dude
      end
   end

   /*
   -----   These are examples of common Abandon_Party calls, use...or don't...at your discretion   -----

   else if (Mark_In_Party) then begin
      if (global_var(GVAR_PLAYER_REPUTATION) < Mark_Bad_Karma) then begin
         call Abandon_Party;
         debug_msg("Mark Bad Player Rep");
      end
      else if (has_rep_childkiller) then begin
         call Abandon_Party;
         debug_msg("Mark: Child Killer");
      end
      else if (has_rep_berserker) then begin
         call Abandon_Party;
         debug_msg("Mark: Berserker");
      end
      else if (has_rep_slaver) then begin
         call Abandon_Party;
         debug_msg("Mark: Slaver Rep");
      end*/

end

procedure damage_p_proc begin
   /* Whenever the critter takes damage of any type, this procedure will be called. Things
      like setting ENEMY_ and LVAR_Personal_Enemy can be set here.
      If the player causes damage to this critter, then he will instantly consider the player
      his personal enemy. In Critter_Proc or through dialog, actions will be taken against
      the player for his evil acts. */

   if (obj_in_party(source_obj)) then begin
//       set_local_var(LVAR_Personal_Enemy, 1);
      set_personal_enemy;
   end

end

procedure pickup_p_proc begin
   /* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
      In here, various things can happen. The most common response is instant hostility which
      will be remembered. */

   if (source_obj == dude_obj) then begin
//      set_local_var(LVAR_Hostile, 2);
      set_hostile;
   end

end

procedure talk_p_proc begin


   /* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
      written by designers are placed in here. Additionally, Reactions are generated and
      stored which affects player interactions. */
   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_INTOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

   find_party_background;


   if (cur_map_index == MAP_BLOOMFIELD_CONTROL_CENTER_EAST) then begin
      start_gdialog(NAME,self_obj,4,HEAD_ADVANCED_POWER_ARMOR,PartyMemberBackground);
   end
   else begin
      start_gdialog(NAME,self_obj,4,HEAD_MARK_GANNON,PartyMemberBackground);
   end

   gSay_Start;
   if(global_var(GVAR_MARK_GANNON_BETRAY) == 1 and cur_map_index == MAP_BLOOMFIELD_CONTROL_CENTER_EAST) then begin
      set_global_var(GVAR_MARK_GANNON_BETRAY, 2);
      call Node090;
   end
   else if (local_var(LVAR_Herebefore) == 0) then begin
      call Node001;
   end else if not(Mark_In_Party) then begin
      call Node018;
   end else if ((Mark_Ptr != 0) or (party_is_waiting)) then begin
      call Node1000;
   end
   gSay_End;
   end_dialogue;
   call restore_idiot_savant_int;

end

procedure destroy_p_proc begin
   /* This procedure gets called only on the death of this NPC. Special things like
       incrementing the death count for reputation purposes and Enemy Counters are placed
       in here. */
       if (
         not(critter_state(self_obj) bwand (DAM_KNOCKED_OUT bwor DAM_EXPLODE bwor DAM_DESTROY)) and
         obj_is_visible_flag(self_obj) and
         (elevation(self_obj) == dude_elevation)
      ) then begin
         floater_bad(205);
       end
   /* Increment the aligned critter counter
        This counter affects your karma? */
   inc_neutral_critter

   /* Set global_variable for Enemy status*/
   set_global_var(GVAR_MARK_DEAD, 1);
end

procedure look_at_p_proc begin
   /* Look_at_p_proc gets called any time that the player passes the cursor over any object.
       This should only hold the most cursory of glances for the player. */

   script_overrides;
//   if (local_var(LVAR_Herebefore) == 0) then
//      set_local_var(LVAR_Herebefore, 1);
   if not herebefore then begin
      set_herebefore;
      display_mstr(100);
   end else
      display_mstr(101);

end

procedure description_p_proc begin
   /* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */

   script_overrides;
   display_mstr(102);

end
/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

procedure push_p_proc begin
   if (random(1, 3) == 1) then begin
      floater(9920);                               // Float response for being pushed by player
   end
end

procedure Node998 begin
   /* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
       this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
       he was once hostile towards the player.*/
//   set_local_var(LVAR_Hostile,2);
   set_hostile;

end


procedure Node999 begin
   /* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
       exit from the dialog system without any reprisals from the NPC. */
       debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
set_global_var(GVAR_MET_MARK_GANNON, 1);
end
end



procedure Node001
begin
Reply(230);
NOption(231,Node002,4);
NOption(232,Node003,4);
end

procedure Node002
begin
Reply(260);
NOption(261,Node999,4);
end

procedure Node003
begin
Reply(290);
NOption(291,Node004,4);
NOption(292,Node005,4);
NOption(293,Node006,4);

   if (dude_charisma <= 1) then begin
      NOption(294,Node007a,4);
   end
   else if (town_rep_is_hated) then begin
      NOption(294,Node007b,4);
   end
   else if (dude_at_max_party_size) then begin
      NOption(294,Node007,4);
   end
   else if (dude_is_super_mutant or dude_is_ghoul) then begin
      NOption(294,Node008,4);
   end
   else begin
      NOption(294,Node009,4);
   end
end

procedure Node004
begin
Reply(320);
NOption(292,Node005,4);
NOption(293,Node006,4);
NOption(294,Node009,4);
end

procedure Node005
begin
Reply(350);
NOption(261,Node999,4);
end

procedure Node006
begin
Reply(380);
NOption(261,Node999,4);
end

// Node Node007
//
// Notes:
//
// (PLAYER FAILS CHARISMA VS PARTY SIZE CHECK)

procedure Node007
begin
Reply(410);
NOption(261,Node999,4);
end

procedure Node007a
begin
Reply(411);
NOption(261,Node999,4);
end

procedure Node007b
begin
Reply(412);
BOption(261,Node998,4);
end

// Node Node008
//
// Notes:
//
// (PLAYER IS GHOUL OR SUPER MUTANT)

procedure Node008
begin
Reply(440);
NOption(441,Node009,4);
end

procedure Node009
begin
   if (dude_is_male) then Reply(470); else
   if (dude_is_female) then Reply(471);
NOption(441,Node010,4);
end

procedure Node010
begin
Reply(500);
NOption(441,Node011,4);
end

procedure Node011
begin
Reply(530);
NOption(441,Node012,4);
end

procedure Node012
begin
Reply(560);
NOption(dude_name+mstr(561),Node013,4);
NOption(562,Node014,4);
// NOTE: (PC HAS ENERGY WEAPONS SKILL)
NOption(563,Node016,4);
NOption(564,Node017,4);
end


// Node Node013
//
// Notes:
//
// (GANNON JOINS UP)

procedure Node013
begin

   call Join_Party;

Reply(dude_name+mstr(590));
NOption(591,Node999,4);
NOption(592,Node999,4);
end

procedure Node014
begin
if (dude_is_male) then Reply(620); else
if (dude_is_female) then Reply(621);
NOption(622,Node015,4);
end

// Node Node015
//
// Notes:
//
// (GANNON JOINS UP)

procedure Node015
begin

   call Join_Party;


Reply(650);
NOption(261,Node999,4);
end

procedure Node016
begin
Reply(680);
NOption(681,Node015,4);
NOption(564,Node017,4);
end

// Node Node017
//
// Notes:
//
//  (WHEN THE PLAYER RETURNS, GANNON IS GONE)

procedure Node017
begin
Reply(710);
NOption(261,Node999,4);
end

// Node Node018
//
// Notes:
//
// (PC RETURNS, GANNON NOT IN PARTY)

procedure Node018
begin
Reply(740);
NOption(231,Node002,4);
NOption(741,Node003,4);
end

// Node Node019
//
// Notes:
//
// (PC IS DUMB)

procedure Node019
begin
Reply(770);
NOption(771,Node999,-3);
end

// Node Node020
//
// Notes:
//
// (GANNON IS IN PARTY, PC HAS LOW GUNS SKILL, SOME TIME HAS ELAPSED)

procedure Node020
begin
Reply(mstr(800)+dude_name+mstr(801));
NOption(802,Node021,4);
NOption(803,Node021,4);
end

procedure Node021
begin
Reply(830);
NOption(831,Node022,4);
NOption(832,Node022,4);
NOption(833,Node022,4);
end

procedure Node022
begin
Reply(860);
NOption(861,Node028,4);
NOption(862,Node999,4);
NOption(863,Node023,4);
end

// Node Node023
//
// Notes:
//
// (FADE OUT BRIEFLY)

procedure Node023
begin
Reply(890);
NOption(441,Node024,4);
end

procedure Node024
begin
Reply(920);
NOption(921,Node025,4);
NOption(922,Node025,4);
if (get_critter_stat(dude_obj,STAT_pe)>=8) then
NOption(923,Node026,4);
end

procedure Node025
begin
Reply(950);
NOption(261,Node999,4);
end

// Node Node026
//
// Notes:
//
// This is the PC catching Gannon in a lie. Enough of these (say, four? Five?) and the PC will eventually be able to confront Gannon, leading to an early fight.

procedure Node026
begin
Reply(980);
NOption(441,Node027,4);
end

procedure Node027
begin
Reply(1010);
NOption(261,Node999,4);
end

// Node Node028
//
// Notes:
//
// (PC HAS HIGH SPEECH)

procedure Node028
begin
Reply(1040);
NOption(261,Node999,4);
end

// Node Node029
//
// Notes:
//
// (PC HAS HIGH UNARMED)

procedure Node029
begin
Reply(1070);
NOption(261,Node999,4);
end

// Node Node030
//
// Notes:
//
// (PC HAS HIGH MELEE)

procedure Node030
begin
Reply(1100);
NOption(261,Node999,4);
end

// Node Node031
//
// Notes:
//
// (GANNON IS IN PARTY, PC HAS HIGH GUNS SKILL, SOME TIME HAS ELAPSED)

procedure Node031
begin
Reply(mstr(1130)+dude_name+mstr(1131));
NOption(1132,Node032,4);
NOption(1133,Node032,4);
// NOTE: (PC HAS VERY HIGH GUNS)
if (has_skill(dude_obj,SKILL_SMALL_GUNS)>=125) then
NOption(1134,Node034,4);
end

procedure Node032
begin
Reply(1160);
NOption(441,Node033,4);
end

procedure Node033
begin
Reply(1190);
NOption(261,Node999,4);
end

procedure Node034
begin
Reply(1220);
NOption(441,Node035,4);
end

procedure Node035
begin
Reply(1250);
NOption(1251,Node036,4);
NOption(1252,Node037,4);
// NOTE: (PC HAS V. HIGH PERCEPTION)
if (get_critter_stat(dude_obj,STAT_pe)>=7) then
NOption(1253,Node001,4);
end

procedure Node036
begin
Reply(mstr(1280)+dude_name+mstr(1281));
NOption(441,Node033,4);
end

procedure Node037
begin
Reply(1310);
NOption(441,Node038,4);
end

procedure Node038
begin
Reply(1340);
NOption(441,Node039,4);
end

procedure Node039
begin
Reply(1370);
NOption(261,Node999,4);
end

// Node Node040
//
// Notes:
//
// This is the PC catching Gannon in a lie. Enough of these (say, four? Five?) and the PC will eventually be able to confront Gannon, leading to an early fight.

procedure Node040
begin
if (dude_is_male) then Reply(1400); else
if (dude_is_female) then Reply(1401);
NOption(441,Node033,4);
end

// Node Node041
//
// Notes:
//
// (GANNON IS IN PARTY, PC IS INJURED)

procedure Node041
begin
Reply(1430);
NOption(1431,Node042,4);
NOption(1432,Node042,4);
NOption(1433,Node042,4);
end

procedure Node042
begin
Reply(1460);
NOption(1461,Node043,4);
NOption(1462,Node043,4);
end

procedure Node043
begin
Reply(1490);
NOption(441,Node044,4);
end

procedure Node044
begin
Reply(1520);
NOption(1521,Node045,4);
NOption(1522,Node050,4);
end

procedure Node045
begin
Reply(1550);
NOption(1551,Node046,4);
NOption(1552,Node047,4);
end

procedure Node046
begin
Reply(1580);
NOption(441,Node049,4);
end

procedure Node047
begin
Reply(1610);
NOption(441,Node048,4);
end

procedure Node048
begin
Reply(1640);
NOption(441,Node049,4);
end

// Node Node049
//
// Notes:
//
// (FADE OUT, HEAL PC)

procedure Node049
begin
Reply(1670);
NOption(441,Node051,4);
end

// Node Node050
//
// Notes:
//
// (FADE OUT, HEAL PC)

procedure Node050
begin
Reply(1700);
NOption(441,Node051,4);
end

procedure Node051
begin
Reply(1730);
NOption(261,Node999,4);
end

// Node Node052
//
// Notes:
//
// (PC HAS MET PRESPER AT BOULDER DOME, ROCKET HAS LAUNCHED, ETC)

procedure Node052
begin
Reply(1760);
NOption(1761,Node053,4);
NOption(1762,Node053,4);
NOption(1763,Node054,4);
end

procedure Node053
begin
Reply(1790);
NOption(261,Node999,4);
end

procedure Node054
begin
Reply(mstr(1820)+dude_name+mstr(1821));
NOption(441,Node055,4);
end

procedure Node055
begin
Reply(1850);
NOption(441,Node056,4);
end

procedure Node056
begin
Reply(1880);
NOption(261,Node999,4);
end

// Node Node057
//
// Notes:
//
// (ACT 1 HAS ENDED, ODYSSEUS HAS SELF-DESTRUCTED, GANNON WITNESSED IT)

procedure Node057
begin
Reply(1910);
NOption(1911,Node058,4);
NOption(1912,Node058,4);
end

procedure Node058
begin
Reply(1940);
NOption(441,Node059,4);
end

procedure Node059
begin
Reply(1970);
NOption(1971,Node060,4);
NOption(1972,Node060,4);
if (get_critter_stat(dude_obj,STAT_pe)>=6) then
NOption(1973,Node061,4);
end

procedure Node060
begin
Reply(2000);
NOption(261,Node999,4);
end

// Node Node061
//
// Notes:
//
// This is the PC catching Gannon in a lie. Enough of these (say, four? Five?) and the PC will eventually be able to confront Gannon, leading to an early fight.

procedure Node061
begin
Reply(2030);
NOption(261,Node999,4);
end

// Node Node062
//
// Notes:
//
// (GANNON IS IN PARTY)

procedure Node062
begin
Reply(2060);
//NOption(2061,Node063,4);
NOption(2062,Node086,4);
NOption(2063,Node087,4);
NOption(2064,Node089,4);
NOption(2065,Node999,4);
end

procedure Node063
begin
Reply(2090);
// NOTE: (PC HAS COLLECTED ENOUGH LIES AND HAS GOOD INTELLIGENCE)
NOption(2091,Node064,6);
// NOTE: (PC IS GHOUL OR SUPER MUTANT)
NOption(2092,Node069,4);
NOption(2093,Node075,4);
NOption(2094,Node078,4);
NOption(2095,Node079,4);
// NOTE: (PC HAS TRIED TO TAKE GANNON INTO A BAR/GIVE HIM ALCOHOL - SEE BARKS)
NOption(2096,Node082,4);
// NOTE: (PC AND GANNON HAVE ENCOUNTERED DEATHCLAW - SEE BARKS)
NOption(2097,Node084,4);
NOption(2098,Node999,4);
end

procedure Node064
begin
Reply(2120);
NOption(2121,Node065,4);
NOption(2122,Node066,4);
NOption(2123,Node066,4);
end

procedure Node065
begin
Reply(2150);
NOption(261,Node999,4);
end

procedure Node066
begin
Reply(mstr(2180)+dude_name+mstr(2181));
NOption(2182,Node067,4);
NOption(2183,Node068,4);
end

procedure Node067
begin
Reply(mstr(2210)+dude_name+mstr(2211));
BOption(261,Node998,4);
end

// Node Node068
//
// Notes:
//
// (GANNON LEAVES.)

procedure Node068
begin
Reply(2240);
NOption(261,Node999,4);
end

procedure Node069
begin
Reply(2270);
NOption(2271,Node070,4);
NOption(2272,Node070,4);
end

procedure Node070
begin
Reply(2300);
NOption(2301,Node071,4);
NOption(2302,Node073,4);
NOption(2303,Node074,6);
end

procedure Node071
begin
Reply(2330);
NOption(441,Node072,4);
end

procedure Node072
begin
Reply(2360);
NOption(261,Node999,4);
end

procedure Node073
begin
Reply(2390);
NOption(441,Node072,4);
end

// Node Node074
//
// Notes:
//
// This is another lie point.

procedure Node074
begin
Reply(2420);
NOption(441,Node072,4);
end

procedure Node075
begin
Reply(2450);
NOption(261,Node999,4);
end

// Node Node076
//
// Notes:
//
// (ROCKET PREPARATION IS UNDERWAY)

procedure Node076
begin
Reply(2480);
NOption(261,Node999,4);
end

// Node Node077
//
// Notes:
//
// (PRESPER HAS BEEN MET)

procedure Node077
begin
Reply(2510);
NOption(261,Node999,4);
end

procedure Node078
begin
Reply(2540);
NOption(261,Node999,4);
end

procedure Node079
begin
Reply(2570);
NOption(441,Node080,4);
end

procedure Node080
begin
Reply(2600);
NOption(441,Node081,4);
end

procedure Node081
begin
Reply(2630);
NOption(261,Node999,4);
end

procedure Node082
begin
Reply(2660);
NOption(441,Node083,4);
end

procedure Node083
begin
Reply(2690);
NOption(261,Node999,4);
end

// Node Node084
//
// Notes:
//
// Lie point.

procedure Node084
begin
Reply(2720);
NOption(441,Node085,4);
end

procedure Node085
begin
Reply(2750);
NOption(261,Node999,4);
end

procedure Node086
begin
Reply(2780);
NOption(261,Node999,4);
end

procedure Node087
begin
Reply(2810);
NOption(2811,Node088,4);
NOption(2812,Node088,4);
end

procedure Node088
begin
Reply(2840);
NOption(261,Node999,4);
end

procedure Node089
begin
Reply(2870);
NOption(261,Node999,4);
end

procedure Node090
begin
Reply(mstr(2900)+dude_name+mstr(2901));
NOption(2902,Node091,4);
NOption(2903,Node091,4);
end

procedure Node091
begin
Reply(2930);
NOption(2931,Node092,4);
NOption(2932,Node115,4);
NOption(2933,Node116,4);
NOption(2934,Node117,4);
end

procedure Node092
begin
Reply(2960);
NOption(441,Node093,4);
end

procedure Node093
begin
Reply(2990);
// NOTE: (IF THE PC HAS BUILT A FAILSAFE - VERY HIGH SCIENCE)
if (has_skill(dude_obj,SKILL_SCIENCE)>=125) then
NOption(2991,Node094,4);
NOption(2992,Node098,4);
// NOTE: (IF THE PC HAS TALKED TO GANNON ABOUT HIS PAST)
NOption(2993,Node100,4);
NOption(2994,Node114,4);
NOption(2995,Node114,4);
end

procedure Node094
begin
Reply(3020);
NOption(3021,Node095,4);
end

procedure Node095
begin
Reply(mstr(3050)+dude_name+mstr(3051));
NOption(3052,Node096,4);
if (dude_is_male) then
NOption(3053,Node096,4);
if (dude_is_female) then
NOption(3054,Node096,4);
end

procedure Node096
begin
Reply(3080);
NOption(3081,Node097,4);
NOption(3082,Node097,4);
end

procedure Node097
begin
Reply(3110);
BOption(261,Node998,4);
end

procedure Node098
begin
Reply(3140);
NOption(3141,Node099,4);
// NOTE: (PC HAS HIGH SPEECH)
if (has_skill(dude_obj,SKILL_CONVERSANT)>=100) then
NOption(3142,Node102,4);
NOption(3143,Node114,4);
end

procedure Node099
begin
Reply(3170);
// NOTE: (PC HAS HIGH SPEECH)
if (has_skill(dude_obj,SKILL_CONVERSANT)>=100) then
NOption(3142,Node102,4);
NOption(3143,Node114,4);
end

procedure Node100
begin
Reply(3200);
NOption(441,Node101,4);
end

procedure Node101
begin
Reply(3230);
// NOTE: (PC HAS HIGH SPEECH)
if (has_skill(dude_obj,SKILL_CONVERSANT)>=125) then
NOption(3231,Node102,4);
NOption(3232,Node114,4);
end

procedure Node102
begin
Reply(mstr(3260)+dude_name+mstr(3261));
NOption(441,Node103,4);
end

procedure Node103
begin
Reply(3290);
NOption(3291,Node104,4);
NOption(3292,Node104,4);
NOption(3293,Node114,4);
end

procedure Node104
begin
Reply(3320);
NOption(441,Node105,4);
end

procedure Node105
begin
Reply(3350);
NOption(3351,Node106,4);
end

procedure Node106
begin
Reply(3380);
NOption(441,Node107,4);
end

procedure Node107
begin
Reply(mstr(3410)+dude_name+mstr(3411));
NOption(3412,Node108,4);
NOption(3413,Node108,4);
end

procedure Node108
begin
Reply(mstr(3440)+dude_name+mstr(3441));
NOption(3442,Node109,4);
NOption(3443,Node109,4);
NOption(3444,Node110,4);
NOption(3445,Node110,4);
end

procedure Node109
begin
Reply(3470);
NOption(441,Node110,4);
end

procedure Node110
begin
Reply(3500);
NOption(3501,Node113,4);
NOption(3502,Node111,4);
NOption(3503,Node112,4);
end

procedure Node111
begin
Reply(3530);
NOption(441,Node113,4);
end

procedure Node112
begin
Reply(3560);
NOption(441,Node113,4);
end

procedure Node113
begin
Reply(mstr(3590)+dude_name+mstr(3591));
NOption(261,Node999,4);
end

procedure Node114
begin
Reply(3620);
BOption(261,Node998,4);
end

procedure Node115
begin
Reply(3650);
NOption(441,Node092,4);
end

procedure Node116
begin
Reply(3680);
NOption(441,Node092,4);
end

procedure Node117
begin
Reply(dude_name+mstr(3710));
BOption(3711,Node998,4);
end

// Node Node118
//
// Notes:
//
// (PC HAS SUCCESSFULLY PERSUADED GANNON TO STAND DOWN)

procedure Node118
begin
Reply(3740);
NOption(261,Node999,4);
end



procedure Join_Party begin
   /* This node places the NPC in the player's party.
      Call this node any time you want an action from the player to result in the NPC joining their party. */

   Mark_joins_party;
   set_local_var(LVAR_Joined_Player,1);
   float_msg(self_obj, message_str(NAME, 870), FLOAT_COLOR_HIGH);      // Personalize this message or remove if you feel like it

end

procedure Abandon_Party begin

   //set_local_var(LVAR_never_again,1);
   //party_remove(self_obj);
   //leave party
   if (self_visible) then
   set_self_abandon_party;

end


   /* Node1000 and on are default dialogue nodes for a generic NPC joining the player's party. */

procedure Node1000 begin
   Reply(2060);                                        // This reply is when the NPC is in your party and you talk to them
   // TODO
   //NOption(2061,Node063,4);
   party_member_default_options;
end

procedure Node1001 begin
   // heal yourself
   obj_heal(self_obj)
   if (party_healed_max) then begin
      Reply(9900);                         // This reply is when your party member is healed to max
   end else if (party_healed_good) then begin
     Reply(9910);                                      // This reply message is for when the NPC is Barely Hurt (90% health or above)
   end else if (party_healed_hurt) then begin
      Reply(9915);                                     // This reply message is for when the NPC is Wounded (70%-90% health?)
   end else begin
      Reply(9920);                                     // This reply message is for Failures
   end
   party_member_default_options;
end
procedure Node1002 begin
   // wait here
   set_party_waiting;
   Reply(9930);                            // These reply messages are in response to wait request
   party_member_default_options;
end
procedure Node1003 begin
   // put your weapon away
   inven_unwield(self_obj);
   Reply(9940);                                        // Response to removing weapon
   party_member_default_options;
end
procedure Node1004 begin
   // follow close
   set_follow_close;
   Reply(9950);                            // Random responses for distance change
   party_member_default_options;
end
procedure Node1005 begin
   // follow medium
   set_follow_medium;
   Reply(9960);                            // Random responses for distance change
   party_member_default_options;
end
procedure Node1006 begin
   // follow far
   set_follow_far;
   Reply(9970);                            // Random responses for distance change
   party_member_default_options;
end
procedure Node1007 begin
   // distance
   //Reply("TEMP MESSAGE: DISTANCE");
   Reply(9980);                                        // Generic response to "Change follow distance" menu
   party_member_def_follow_options;
end
procedure Node1008 begin
   // gear
   //Reply("TEMP MESSAGE: GEAR");
   Reply(9985);                                        // Generic response to "Look at your gear"
   party_member_def_gear_options;
end
procedure Node1009 begin
   // remove armor
   //NEED TO FIND OUT WHY THIS DOESNT WORK!!! - NBK
   remove_armor(self_obj)
   //Reply("TEMP MESSAGE: REMOVE ARMOR");
   Reply(9990);                                        // Generic response to "Remove armor"
   party_member_default_options;
end
procedure Node1010 begin
   // weapons that can be used
   //Reply("TEMP MESSAGE: CAN USE...");
   Reply(9995);                                        // Specific reply, indicating what weapons the NPC can use.
   party_member_default_options;
end
procedure Node1100 begin                              // This node is for when the player is asking the NPC to re-join
   // join me
   if (dude_charisma <= 1) then begin
      set_self_abandon_party;
      Reply(411);                                     // NPC abandons party because Player Character is too ugly
      NOption(g_mstr(10007),Node999,001);             // Predefined generic messages in GENERIC.MSG
   end else if (dude_at_max_party_size) then begin
      set_self_abandon_party;
      Reply(410); //was 2000                          // Generic "Too many followers" reply
      NOption(g_mstr(10007),Node999,001);             // Predefined generic messages in GENERIC.MSG
   end else if (town_rep_is_hated) then begin
      set_self_abandon_party;
      Reply(412);                                     // Will abandon party if Town_Rep becomes Hated
      BOption(g_mstr(10007),Node998,001);             // Predefined generic messages in GENERIC.MSG
   end else begin
      end_party_waiting;
      Reply(9750);                         // Random dialogue greetings
      party_member_default_options;
   end
end
