/*

        Name:           Pablo Riviera
        Location:
        Description:

           Created: 23.1.2024. 14:57:29

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_C /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"

#define NAME                    SCRIPT_HDPABLO

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_HOOVER_DAM)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\HEADERS\partybkg.h"
#include "..\HEADERS\hdam.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure bad_cantina;
procedure good_cantina;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure free_hooch;
procedure discounted_hooch;
procedure dude_is_rich;
procedure dude_is_not_rich;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Mentioned_Fancy_Pad        (8)
#define LVAR_Discounted_Drinks          (9)
#define LVAR_Rented_Room                (10)


/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_HOOVER_DAM);
   //critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
   add_timer_event(self_obj, game_ticks(random(1, 5)), 0);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   variable pablo_stuff, temp_stuff, tile_pablo_stuff;

   if(global_var(GVAR_QUEST_HELP_PABLO_RIVIERA) == 3) then
      tile_pablo_stuff = 25463;
   else
      tile_pablo_stuff = 25465;

   pablo_stuff := tile_contains_pid_obj(tile_pablo_stuff, self_elevation, PID_FOOTLOCKER_RUSTY_LEFT);
   temp_stuff := tile_contains_pid_obj(25865, self_elevation, PID_FOOTLOCKER_RUSTY_LEFT);

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   find_party_background;

   call set_idiot_savant_int;

   move_obj_inven_to_obj(self_obj,temp_stuff);
   move_obj_inven_to_obj(pablo_stuff,self_obj);

       start_gdialog(NAME,self_obj,4,HEAD_PABLO_RIVIERA,PartyMemberBackground);
       gSay_Start;
       if (local_var(LVAR_Herebefore) == 0) then
          call Node001;
         else
         call Node002;
       gSay_End;
       end_dialogue;

   call restore_idiot_savant_int;

   move_obj_inven_to_obj(self_obj,pablo_stuff);
   move_obj_inven_to_obj(temp_stuff,self_obj);

end

procedure timed_event_p_proc begin

   add_timer_event(self_obj, game_ticks(random(1, 5)), 0);

   if((local_var(LVAR_Rented_Room) > 0) and ((game_time - local_var(LVAR_Rented_Room)) / ONE_GAME_DAY >= 1)) then begin
      set_local_var(LVAR_Rented_Room, 0);
      set_can_rest_on_map(cur_map_index, self_elevation, false);
   end

   if (random(1, 15) == 1) then begin
      if (global_var(GVAR_QUEST_HELP_PABLO_RIVIERA) == 3) then
         call good_cantina;
      else
         call bad_cantina;
   end

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   if (global_var(GVAR_QUEST_HELP_PABLO_RIVIERA) < 3) then
      display_mstr(102);
   else
      display_mstr(103);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure bad_cantina
begin
floater_bad_rand(200,210);
end

procedure good_cantina
begin
floater_good_rand(230,239);
end

procedure Node001
begin
Reply(260);
if (global_var(GVAR_QUEST_HELP_PABLO_RIVIERA) < 3) then
NOption(261,Node003,4);
if (not(ncr_bos_war_ended)) then
NOption(262,Node006,4);
NOption(263,Node018,4);
NOption(264,Node026,4);
NOption(265,Node999,4);
end

procedure Node002
begin
Reply(290);
if (global_var(GVAR_QUEST_HELP_PABLO_RIVIERA) == 2) then
NOption(291,Node009,4);
if (global_var(GVAR_QUEST_HELP_PABLO_RIVIERA) < 3) then
NOption(261,Node003,4);
if (not(ncr_bos_war_ended)) then
NOption(262,Node006,4);

if (global_var(GVAR_QUEST_HELP_PABLO_RIVIERA) == 3) then
   NOption(292,Node013,4);
else
   NOption(292,Node003,4);

NOption(293,Node018,4);
if ((local_var(LVAR_Mentioned_Fancy_Pad) == 1) and global_var(GVAR_DUDE_OWNS_FANCY_PAD) == 0) then
NOption(294,Node022,4);
NOption(264,Node026,4);
NOption(295,Node999,4);
end

procedure Node003
begin
Reply(320);
NOption(321,Node004,4);
end

procedure Node004
begin
Reply(350);
NOption(351,Node005,4);
end

procedure Node005
begin
Reply(380);
NOption(381,Node007,4);
NOption(382,Node999,4);
end

procedure Node006
begin
Reply(410);
NOption(411,Node999,4);
end

procedure Node007
begin
Reply(440);
NOption(441,Node008,4);
NOption(442,Node999,4);
end

procedure Node008
begin
   if (global_var(GVAR_QUEST_HELP_PABLO_RIVIERA) == 0) then
      set_global_var(GVAR_QUEST_HELP_PABLO_RIVIERA, 1);

Reply(470);
NOption(471,Node999,4);
end

procedure Node009
begin
   set_global_var(GVAR_QUEST_HELP_PABLO_RIVIERA, 3);

Reply(500);
NOption(501,Node010,4);
end

procedure Node010
begin
Reply(530);
NOption(531,Node011,4);
end

procedure Node011
begin
Reply(560);
NOption(561,Node012,4);
NOption(562,free_hooch,4);
NOption(563,discounted_hooch,4);
end

procedure Node012
begin
Reply(590);
NOption(471,Node999,4);
end

procedure Node013
begin
Reply(620);
NOption(621,Node014,4);
end

procedure Node014
begin
Reply(650);
NOption(651,Node015,4);
end

procedure Node015
begin
   variable autodoc;
   autodoc = "";

   if (global_var(GVAR_DR_YURI_AUTODOC) == 0) then begin
      autodoc = " " + mstr(683);
      set_global_var(GVAR_DR_YURI_AUTODOC, 1);
   end

   if (ncr_bos_war_ended) then
      Reply(679);
   else
      Reply(680);

NOption(mstr(681) + autodoc,Node016,4);
NOption(mstr(682) + autodoc,Node999,4);
end

procedure Node016
begin
   if (cc_dead) then
      Reply(709);
   else
      Reply(710);
NOption(711,Node017,4);
end

procedure Node017
begin
   fadeout(1);
   game_time_advance(ONE_GAME_HOUR);
   fadein(1);
Reply(740);
NOption(471,Node999,4);
end

procedure Node018
begin

Reply(770);
NOption(771,Node019,4);
NOption(772,Node999,4);
end

procedure Node019
begin
   set_local_var(LVAR_Mentioned_Fancy_Pad, 1);
   if (dude_caps >= 25) then begin
      set_local_var(LVAR_Rented_Room, game_time);
      item_caps_adjust(dude_obj, -25);
      set_can_rest_on_map(cur_map_index, self_elevation, true);
   end

Reply(800);
NOption(801,Node020,4);
NOption(802,Node021,4);
end

procedure Node020
begin
Reply(830);
NOption(831,Node021,4);
end

procedure Node021
begin
Reply(860);
NOption(861,Node999,4);
end

procedure Node022
begin
Reply(890);
NOption(891,Node023,4);
if (global_var(GVAR_QUEST_HELP_PABLO_RIVIERA) == 3) then
   NOption(892,Node025,4);
else
   NOption(892,Node024,4);
NOption(893,Node999,4);
end

procedure Node023
begin
Reply(920);
if (global_var(GVAR_QUEST_HELP_PABLO_RIVIERA) == 3) then
   NOption(921,Node025,4);
else
   NOption(921,Node024,4);
NOption(922,Node999,4);
end

procedure Node024
begin
Reply(950);
NOption(951,dude_is_rich,4);
NOption(952,Node999,4);
end

procedure Node025
begin
Reply(980);
NOption(951,dude_is_not_rich,4);
NOption(981,Node999,4);
end

procedure Node026
begin
   if (local_var(LVAR_Discounted_Drinks) == 1) then
      gdialog_mod_barter(-50);
   else
      gdialog_barter;
Reply(1010);
NOption(1011,Node999,4);
end

procedure free_hooch begin
   gdialog_mod_barter(-100);
   call Node012;
end

procedure discounted_hooch begin
   set_local_var(LVAR_Discounted_Drinks, 1);
   gdialog_mod_barter(-50);
   call Node012;
end

procedure dude_is_rich begin
   if (dude_caps >= 100000) then begin
      set_global_var(GVAR_DUDE_OWNS_FANCY_PAD, 1);
      item_caps_adjust(dude_obj, -100000);
   end
   call Node999;
end

procedure dude_is_not_rich begin
   if (dude_caps >= 20000) then begin
      set_global_var(GVAR_DUDE_OWNS_FANCY_PAD, 1);
      item_caps_adjust(dude_obj, -20000);
   end
   call Node999;
end


//xxxxxxxxxxxxxxxxxxxx
