/*

        Name:           Pierre LaPoubelle
        Location:       Hoover Dam
        Description:

           Created: 16.7.2023. 16:54:18

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_HDPIERRE

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_HOOVER_DAM)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\HEADERS\hdam.h"
#include "..\HEADERS\hdgatenr.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Floats;
procedure Node001;
procedure Node003;
procedure Node004;
procedure Node025;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node002;
procedure Node026;
procedure Node034;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node052;
procedure Node005;
procedure Node014;
procedure Node015;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node016;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node038;
procedure Node039;
procedure Node040;
procedure Node041;
procedure Node042;
procedure Node043;
procedure Node044;
procedure Node045;
procedure Node046;
procedure Node047;
procedure Node048;
procedure Node049;
procedure Node050;
procedure Node051;
procedure Node053;
procedure Node054;
procedure Node055;
procedure Node056;
procedure Node057;
procedure Node057a;
procedure Node057b;
procedure Node058;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_HOOVER_DAM);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);

   if (global_var(GVAR_KNOW_PIERRE_BOS) == 2) then begin
      set_obj_visibility(self_obj, 1);
      destroy_object(self_obj);
   end

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,HEAD_PIERRE_LAPOUBELLE,-1);
       gSay_Start;
       if (dude_is_stupid) then
          call Node017;
       else if (local_var(LVAR_Herebefore) == 1) then
         call Node002;
       else
          call Node001;
       gSay_End;
       end_dialogue;

   call restore_idiot_savant_int;
end

procedure timed_event_p_proc begin

   add_timer_event(self_obj, game_ticks(random(3, 5)), 0);

   if (random(1, 20) == 1 and self_can_speak) then begin
      call Floats;
  end

end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
set_dr_yuri_know_people_flag(DR_YURI_KNOW_PIERRE);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Floats
begin
floater_rand(200,215);
end

procedure Node001
begin
Reply(230);
NOption(231,Node003,4);
if (global_var(GVAR_QUEST_UPGRADE_FILTER) == QUEST_NONE) then
NOption(232,Node025,4);
NOption(233,Node026,4);
NOption(234,Node999,4);
end

procedure Node003
begin
Reply(260);
NOption(261,Node004,4);
NOption(262,Node026,4);
NOption(263,Node999,4);
end

procedure Node004
begin
Reply(290);
NOption(291,Node027,4);
NOption(292,Node026,4);
NOption(293,Node999,4);
end

procedure Node025
begin
Reply(320);
if (has_skill(dude_obj,SKILL_SCIENCE)>=99) then
NOption(321,Node046,4);
NOption(322,Node038,4);
NOption(323,Node053,4);
end

procedure Node027
begin
Reply(350);
NOption(351,Node028,4);
NOption(352,Node999,4);
end

procedure Node028
begin
Reply(380);
NOption(381,Node029,4);
end

procedure Node029
begin
Reply(410);
NOption(411,Node030,4);
end

procedure Node030
begin
Reply(440);
NOption(441,Node031,4);
end

procedure Node031
begin
Reply(470);
NOption(471,Node032,4);
end

procedure Node032
begin
Reply(500);
NOption(501,Node033,4);
NOption(502,Node026,4);
NOption(503,Node999,4);
end

procedure Node033
begin
Reply(530);
NOption(531,Node999,4);
end

procedure Node002
begin
Reply(560);
NOption(561,Node026,4);
if (global_var(GVAR_QUEST_UPGRADE_FILTER) == QUEST_NONE) then
NOption(562,Node025,4);
if ((global_var(GVAR_QUEST_DISCOVER_SL1C) == QUEST_COMPLETED) and (global_var(GVAR_PIERRE_KNOWS_S1C) == 0)) then
NOption(563,Node022,4);
if ((global_var(GVAR_QUEST_UPGRADE_FILTER) == FILTRATION_SCHEMATICS_SEARCHING) and (dude_item_count(PID_FILTRATION_SCHEMATICS)>0)) then
NOption(564,Node041,4);
if ((global_var(GVAR_KNOW_PIERRE_BOS) == 1) and not(town_known(AreaNukeStatus(AREA_BROTHERHOOD_OF_STEEL)))) then begin
   // TODO might add GVAR_QUEST_DISCOVER_SL1C as a prerequisite for this too
   if ((global_var(GVAR_QUEST_UPGRADE_FILTER) == FILTRATION_SCHEMATICS_FOUND)) then
      NOption(566,Node054,4);
   else
      NOption(566,Node052,4);
end
NOption(565,Node999,4);
end

procedure Node026
begin
Reply(590);
NOption(591,Node034,4);
NOption(592,Node035,4);
NOption(593,Node004,4);
NOption(594,Node999,4);
end

procedure Node034
begin
Reply(620);
NOption(592,Node035,4);
NOption(621,Node009,4);
end

procedure Node035
begin
   if (global_var(GVAR_KNOW_PIERRE_BOS) == 0) then
      set_global_var(GVAR_KNOW_PIERRE_BOS, 1);
Reply(650);
if (map_var(MVAR_FOUND_BOS_MENTION_COMPUTER) == 1) then begin
   NOption(651,Node036,4);
end
NOption(621,Node009,4);
NOption(652,Node999,4);
end

procedure Node036
begin
Reply(680);
NOption(681,Node037,4);
NOption(682,Node038,4);
NOption(683,Node052,4);
end

procedure Node037
begin
Reply(710);
NOption(683,Node052,4);
NOption(711,Node999,4);
end

procedure Node052
begin
Reply(740);
NOption(741,Node999,4);
BOption(742,Node999,4);
BOption(743,Node998,4);
end

procedure Node005
begin
Reply(770);
NOption(771,Node014,4);
NOption(772,Node006,4);
NOption(773,Node007,4);
end

procedure Node014
begin
Reply(800);
NOption(801,Node016,4);
NOption(802,Node015,4);
BOption(803,Node998,4);
end

procedure Node015
begin
Reply(830);
NOption(801,Node016,4);
NOption(831,Node999,4);
end

procedure Node006
begin
Reply(860);
NOption(861,Node007,4);
NOption(862,Node016,4);
end

procedure Node007
begin
Reply(890);
NOption(891,Node008,4);
NOption(892,Node999,4);
end

procedure Node008
begin
Reply(920);
NOption(921,Node016,4);
NOption(922,Node999,4);
end

procedure Node016
begin
Reply(950);
NOption(951,Node999,4);
end

procedure Node009
begin
Reply(980);
NOption(981,Node010,4);
NOption(322,Node038,4);
NOption(982,Node999,4);
end

procedure Node010
begin
Reply(1010);
NOption(1011,Node011,4);
NOption(1012,Node013,4);
if (has_skill(dude_obj,SKILL_SCIENCE)>=75) then
NOption(1013,Node012,4);
NOption(1014,Node999,4);
end

procedure Node011
begin
Reply(1040);
NOption(1041,Node012,4);
NOption(1042,Node013,4);
NOption(1043,Node999,4);
end

procedure Node012
begin
Reply(1070);
NOption(1071,Node013,4);
NOption(1072,Node999,4);
end

procedure Node013
begin
Reply(1100);
NOption(1101,Node004,4);
NOption(1102,Node999,4);
end

procedure Node017
begin
Reply(1130);
NOption(1131,Node018,-3);
NOption(1132,Node999,-3);
end

procedure Node018
begin
Reply(1160);
NOption(1161,Node019,-3);
NOption(1162,Node021,-3);
NOption(1163,Node999,-3);
end

procedure Node019
begin
Reply(1190);
NOption(1191,Node020,-3);
NOption(1162,Node021,-3);
NOption(1192,Node999,-3);
end

procedure Node020
begin
Reply(1220);
NOption(1221,Node999,-3);
end

procedure Node021
begin
Reply(1250);
NOption(1191,Node020,-3);
NOption(1192,Node999,-3);
end

procedure Node022
begin
Reply(1280);
NOption(1281,Node023,4);
end

procedure Node023
begin
Reply(1310);
NOption(1311,Node024,4);
end

procedure Node024
begin
   set_global_var(GVAR_PIERRE_KNOWS_S1C, 1);
Reply(1340);
NOption(1341,Node999,4);
end

procedure Node038
begin
Reply(1370);
NOption(1371,Node039,4);
end

procedure Node039
begin
   set_global_var(GVAR_KNOW_MILKO_WATER, 1);
Reply(1400);
NOption(1401,Node040,4);
end

procedure Node040
begin
   set_global_var(GVAR_QUEST_UPGRADE_FILTER, FILTRATION_SCHEMATICS_SEARCHING);
Reply(1430);
NOption(1431,Node999,4);
end

procedure Node041
begin
   remove_pid_qty(dude_obj, PID_FILTRATION_SCHEMATICS, 1)
Reply(1460);
NOption(1461,Node042,4);
end

procedure Node042
begin
Reply(1490);
// NOTE: Player has high Repair skill
if (has_skill(dude_obj,SKILL_REPAIR)>=99) then
NOption(1491,Node043,4);
NOption(1492,Node045,4);
end

procedure Node043
begin
   give_pid_qty(dude_obj, PID_SUPER_TOOL_KIT, 1)
   give_xp(1000);
   set_global_var(GVAR_QUEST_UPGRADE_FILTER, FILTRATION_SCHEMATICS_FOUND);
   set_global_var(GVAR_DUDE_FIXED_WATER_FILTER, 1);
   fadeout(1);
   fadein(1);
   game_time_advance(ONE_GAME_DAY);

Reply(1520);
NOption(1461,Node044,4);
end

procedure Node044
begin
Reply(1550);
NOption(1551,Node999,4);
end

procedure Node045
begin

   give_pid_qty(dude_obj, PID_MULTI_TOOL, 1)
   give_xp(500);
   set_global_var(GVAR_QUEST_UPGRADE_FILTER, FILTRATION_SCHEMATICS_FOUND);
   game_time_advance(ONE_GAME_DAY);

Reply(1580);
NOption(1581,Node999,4);
end

procedure Node046
begin
Reply(1610);
NOption(1611,Node047,4);
end

procedure Node047
begin
Reply(1640);
NOption(1641,Node048,4);
end

procedure Node048
begin
Reply(1670);
NOption(1671,Node049,4);
NOption(1672,Node005,4);
end

procedure Node049
begin
Reply(1700);
NOption(1701,Node050,4);
end

procedure Node050
begin
Reply(1730);
NOption(1731,Node051,4);
end

procedure Node051
begin
Reply(1760);
NOption(1761,Node999,4);
end

procedure Node053
begin

   if (global_var(GVAR_QUEST_RESTORE_CIPHERS_CROPS) == QUEST_NONE) then begin
      set_global_var(GVAR_QUEST_RESTORE_CIPHERS_CROPS, QUEST_KNOWN);
   end

Reply(1790);
NOption(322,Node038,4);
NOption(1791,Node999,4);
NOption(1792,Node057,4);
end

procedure Node054
begin
Reply(1820);
NOption(1821,Node055,4);
end

procedure Node055
begin
Reply(1850);
NOption(1851,Node056,4);
end

procedure Node056
begin
   if(not(town_known(AreaNukeStatus(AREA_BROTHERHOOD_OF_STEEL)))) then begin
      give_xp(500);
      mark_on_map(AreaNukeStatus(AREA_BROTHERHOOD_OF_STEEL))
      display_mstr(150);
      display_msg(g_mstr(1008) + " " + mstr_map(1508) + ".");
   end

   if (dude_is_ghoul) then begin
      Reply(mstr(1880) + " " + mstr(1882));
   end
   else if (dude_is_super_mutant) then begin
      Reply(mstr(1880) + " " + mstr(1883));
   end
   else begin
      Reply(1880);
   end

   NOption(1881,Node999,4);
end

procedure Node057
begin
Reply(1910);
if (
   (dude_charisma >= 7) and
   (dude_caps >= 800) and
   (dude_skill(SKILL_BARTER) >= 99)
) then begin
   NOption(1911,Node057b,4);
end
if (dude_caps >= 1000) then begin
   NOption(1912,Node057a,4);
end
NOption(1913,Node999,4);
end

procedure Node057a begin
   call Node058;
   item_caps_adjust(dude_obj, -1000);
end

procedure Node057b begin
   call Node058;
   item_caps_adjust(dude_obj, -800);
end

procedure Node058
begin

   give_pid_qty(dude_obj, PID_MIRACLE_WHEAT, 1)

Reply(1940);
NOption(1941,Node999,4);
end


//xxxxxxxxxxxxxxxxxxxx
