/*******************************************************************************
        Name:
        Location:
        Description: Critters template script

            Created: by sFall Script Editor
            Updated:

*******************************************************************************/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"


/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure critter_p_proc;
procedure description_p_proc;
procedure look_at_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;


/* Defines */


/*****************************************************************
   Local Variables which are saved.
   All Local Variables need to be prepended by LVAR_
*****************************************************************/


/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/


/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/


/*******************************************************************
*                           PROCEDURES                             *
*******************************************************************/
procedure start begin

end

procedure map_enter_p_proc begin
   if (global_var(GVAR_QUEST_TEACH_CLASS) == 1) then
      set_obj_visibility(self_obj, 0);
   else
      set_obj_visibility(self_obj, 1);
end

procedure critter_p_proc begin
   if (global_var(GVAR_QUEST_TEACH_CLASS) == 1) then
      set_obj_visibility(self_obj, 0);
   else
      set_obj_visibility(self_obj, 1);
end

procedure look_at_p_proc begin
end

procedure description_p_proc begin

end

procedure pickup_p_proc begin

end

procedure talk_p_proc begin

end

procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

procedure damage_p_proc begin

end

procedure destroy_p_proc begin

end
