/*

        Name:           Vinnie Giordano
        Location:
        Description:

           Created: 25.1.2024. 22:46:57

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_HDVINNIE

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_HOOVER_DAM)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\HEADERS\hdam.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure map_update_p_proc;

/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;

procedure Cutscene;
procedure BeatDude;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Dude_Chicken               (8)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */

import variable Vinnie_Ptr;

/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;
variable Ailis, MyTile, Beatings;
variable day_tile = 15727;
variable day_rot = 3;
variable night_tile = 21724;
variable night_rot = 2;

procedure start begin
   Vinnie_Ptr = self_obj;
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   if((global_var(GVAR_QUEST_FRAME_ENZO) == QUEST_COMPLETED) or (global_var(GVAR_QUEST_FRAME_ENZO) == QUEST_DEFAULT_SOLVE)) then begin
      switch_team(self_obj, TEAM_3SOME_CARAVAN)
   end
   else begin
      switch_team(self_obj,TEAM_HOOVER_DAM)
   end

   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_BOXER);

   if (holyfeld_dead) then begin
      set_obj_visibility(self_obj, 1);
      destroy_object(self_obj);
   end else begin
      Vinnie_Ptr = self_obj;
   end
end

procedure map_update_p_proc begin
   Vinnie_Ptr = self_obj;
end

/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((global_var(GVAR_ENEMY_HOOVER_DAM) == 1) and self_can_see_dude) then begin
      self_attack_dude;
  end

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

   if (self_can_speak) then begin
      if (night) then begin
         if (self_tile != night_tile) then begin
            animate_move_to_tile(night_tile);
         end
         else begin
            if (self_cur_rot != night_rot) then
               animate_rotation(night_rot);
         end
      end
      else begin
         if (self_tile != day_tile) then begin
            animate_move_to_tile(day_tile);
         end
         else begin
            if (self_cur_rot != day_rot) then
               animate_rotation(day_rot);
         end
      end
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);

      if(global_var(GVAR_3S_SHOWDOWN) != SHOWDOWN_IN_PROGRESS) then begin
         set_global_var(GVAR_ENEMY_HOOVER_DAM,1);
      end
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   if (night and self_can_speak) then begin
      floater_whisper(103);
   end else begin
      call set_idiot_savant_int;

         start_gdialog(NAME,self_obj,4,HEAD_VINNIE_GIORDANO,-1);
         gSay_Start;
         if (local_var(LVAR_Herebefore) == 0) then begin
            if (fight_level >= 3) then
               call Node006;
            else
               call Node001;
         end else begin
            if (fight_level >= 3) then
               call Node007;
            else
               call Node002;
         end
         gSay_End;
         end_dialogue;

      call restore_idiot_savant_int;
   end
end

procedure timed_event_p_proc begin

   variable busted_teeth;
   busted_teeth = 0;

   if (fight_level >= 3) then
      busted_teeth = 10;

   if(fixed_param == 1) then begin
      if (local_var(LVAR_Dude_Chicken) == 1) then
         float_msg(self_obj, mstr(150 + busted_teeth), FLOAT_COLOR_BAD);
      else
         float_msg(self_obj, mstr(151 + busted_teeth), FLOAT_COLOR_BAD);
      float_msg(Ailis, mstr(170), FLOAT_COLOR_WHISPER);
   end
   else if(fixed_param == 2) then begin
      float_msg(self_obj, mstr(152 + busted_teeth), FLOAT_COLOR_BAD);
      call BeatDude;
   end
   else if(fixed_param == 3) then begin
      float_msg(self_obj, mstr(153 + busted_teeth), FLOAT_COLOR_BAD);
      call BeatDude;
   end
   else if(fixed_param == 4) then begin
      float_msg(self_obj, mstr(154 + busted_teeth), FLOAT_COLOR_BAD);
      call BeatDude;
   end
   else if(fixed_param == 5) then begin
      float_msg(self_obj, mstr(155 + busted_teeth), FLOAT_COLOR_BAD);
      call BeatDude;
   end
   else if(fixed_param == 6) then begin
      float_msg(self_obj, mstr(156 + busted_teeth), FLOAT_COLOR_BAD);
   end
   else if(fixed_param == 7) then begin

      fadeout(1);

      // Go home
      move_to(self_obj, 15727, self_elevation);
      critter_attempt_placement(self_obj, 15727, self_elevation);
      reg_anim_clear(self_obj);
      reg_anim_begin();
      anim(self_obj, ANIMATE_ROTATION, 3);
      reg_anim_end();

      // Ailis approaches
      move_to(Ailis, 9920, self_elevation);
      critter_attempt_placement(Ailis, 9920, self_elevation);
      fadein(1);
      float_msg(Ailis, mstr(171), FLOAT_COLOR_WHISPER);
   end
   else if(fixed_param == 8) then begin
      set_global_var(GVAR_QUEST_3SOME_SPYJOIN, QUEST_ACCEPTED);
      give_pid_qty(dude_obj, PID_BUSINESS_CARD, 1)
      float_msg(Ailis, mstr(172), FLOAT_COLOR_WHISPER);
      reg_anim_clear(Ailis);
      reg_anim_begin();
      reg_anim_animate(Ailis, ANIM_magic_hands_ground, -1);
      reg_anim_end();
   end
   else if(fixed_param == 9) then begin
      fadeout(1);
      set_obj_visibility(Ailis, 1);
      destroy_object(Ailis);
      game_time_advance(ONE_GAME_MINUTE);
      fadein(1);
      party_no_follow_off;
      game_ui_enable;
      set_global_var(GVAR_QUEST_AILIS_EVIDENCE, CC_INFILTRATION_ONGOING);
   end
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_neutral_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
   set_knows_kikazaru;
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Node001
begin
Reply(200);
NOption(mstr(201)+dude_name+mstr(202),Node005,4);
if (global_var(GVAR_QUEST_AILIS_EVIDENCE) == CC_INFILTRATION_FAKE_FIGHT) then
NOption(203,Node003,4);
NOption(204,Node010,4);
NOption(205,Node999,4);
end

procedure Node002
begin
Reply(230);
NOption(231,Node005,4);
if (global_var(GVAR_QUEST_AILIS_EVIDENCE) == CC_INFILTRATION_FAKE_FIGHT) then
NOption(203,Node003,4);
NOption(204,Node010,4);
NOption(232,Node999,4);
end

procedure Node003
begin
Reply(260);
NOption(261,Cutscene,4);
NOption(262,Node004,4);
end

procedure Node004
begin
   set_local_var(LVAR_Dude_Chicken, 1);
Reply(290);
NOption(291,Cutscene,4);
end

procedure Node005
begin
Reply(320);
NOption(321,Node999,4);
end

procedure Node006
begin
Reply(350);
if (global_var(GVAR_QUEST_AILIS_EVIDENCE) == CC_INFILTRATION_FAKE_FIGHT) then
NOption(203,Node008,4);
NOption(204,Node011,4);
NOption(205,Node999,4);
end

procedure Node007
begin
Reply(380);
if (global_var(GVAR_QUEST_AILIS_EVIDENCE) == CC_INFILTRATION_FAKE_FIGHT) then
NOption(203,Node008,4);
NOption(204,Node011,4);
NOption(205,Node999,4);
end

procedure Node008
begin
Reply(410);
NOption(261,Node999,4);
NOption(411,Node009,4);
end

procedure Node009
begin
Reply(440);
NOption(441,Node999,4);
end

procedure Node010
begin
Reply(470);
NOption(471,Node999,4);
end

procedure Node011
begin
Reply(500);
NOption(471,Node999,4);
end

procedure Cutscene begin
   MyTile := self_tile;

   fadeout(1);

   move_to(self_obj, 10321, self_elevation);
   move_to(dude_obj, 10121, dude_elevation);
   critter_attempt_placement(self_obj, 10321, self_elevation);
   critter_attempt_placement(dude_obj, 10121, dude_elevation);

   reg_anim_clear(self_obj);
   reg_anim_begin();
   anim(self_obj, ANIMATE_ROTATION, 5);
   reg_anim_end();

   reg_anim_clear(dude_obj);
   reg_anim_begin();
   anim(dude_obj, ANIMATE_ROTATION, 2);
   reg_anim_end();

   game_time_advance_hour(2300);
   tile_set_center(dude_tile);

   Ailis = create_object_sid(PID_AILIS_MCLAFFERTY, 8511, dude_elevation, -1);
   reg_anim_clear(Ailis);
   reg_anim_begin();
   anim(Ailis, ANIMATE_ROTATION, 3);
   reg_anim_end();

   fadein(1);

   call Node999;

   add_timer_event(self_obj, game_ticks(1), 1);
   add_timer_event(self_obj, game_ticks(7), 2);
   add_timer_event(self_obj, game_ticks(13), 3);
   add_timer_event(self_obj, game_ticks(19), 4);
   add_timer_event(self_obj, game_ticks(25), 5);
   add_timer_event(self_obj, game_ticks(31), 6);
   add_timer_event(self_obj, game_ticks(37), 7);
   add_timer_event(self_obj, game_ticks(43), 8);
   add_timer_event(self_obj, game_ticks(49), 9);

   party_no_follow_on;

   game_ui_disable;

end

procedure BeatDude begin
   variable sfxv, sfxd, animd;

   if (Beatings == 3) then
      animd = ANIM_fall_back;
   else
      animd = ANIM_hit_from_front;

   reg_anim_clear(self_obj);
   reg_anim_begin();
   reg_anim_animate(self_obj, ANIM_throw_punch, -1);
   reg_anim_end();
   sfxv := sfx_build_char_name(self_obj, ANIM_throw_punch, snd_contact);

   reg_anim_clear(dude_obj);
   reg_anim_begin();
   reg_anim_animate(dude_obj,animd,-1);
   sfxd := sfx_build_char_name(dude_obj, animd, snd_contact);
   reg_anim_play_sfx(dude_obj, sfxv, 1);
   reg_anim_play_sfx(dude_obj, sfxd, 1);
   reg_anim_end();

   Beatings += 1;
end

//xxxxxxxxxxxxxxxxxxxx
