/*

        Name:           Dr. Yuri
        Location:       Hoover Dam
        Description:    The only doctor in Hoover Dam.

           Created: 6.2.2024. 20:07:14

*/

/* Include Files */


//Overrides the pickup p proc.
#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_HDYURI

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_HOOVER_DAM)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"
#include "..\HEADERS\hdam.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending


// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node012a;
procedure Node012b;
procedure Node013;
procedure Node013a;
procedure Node013b;
procedure Node013c;
procedure Node013d;
procedure Node014;
procedure Node014a;
procedure Node015;
procedure Node015a;
procedure Node015b;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node022a;
procedure Node022b;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node026a;
procedure Node026b;
procedure Node026c;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node033a;
procedure Node034;
procedure Node035;
procedure Node036;
procedure Node036a;
procedure Node037;
procedure Node038;
procedure Node039;
procedure Node040;
procedure Node041;
procedure Node042;
procedure Node042a;
procedure Node042b;
procedure Node043;
procedure Node043a;
procedure Node044;
procedure Node045;
procedure Node046;
procedure Node046a;
procedure Node046b;
procedure Node047;
procedure Node048;
procedure Node049;
procedure Node049a;
procedure Node050;
procedure Node051;
procedure Node051Reward;
procedure Node052;
procedure Node052a;
procedure Node053;
procedure Node053a;
procedure Node054;
procedure Node055;
procedure Node056;
procedure Node057;
procedure Node058;
procedure Node059;
procedure Node060;
procedure Node061;
procedure Node062;
procedure Node063;
procedure Node064;
procedure Node065;
procedure Node066;
procedure Node067;
procedure Node068;
procedure Node069;
procedure Node070;
procedure Node071;
procedure Node072;
procedure Node073;
procedure Node074;
procedure Node075;
procedure Node076;
procedure Node077;
procedure Node078;
procedure Node079;
procedure Node080;
procedure Node081;

procedure Skill_Check_001_Speech;
procedure Skill_Check_002_Repair;
procedure Skill_Check_003_Barter;
procedure DudeFleeOutside;
procedure DudeFleeOutsideDialog;

procedure NodeDoDermal;
procedure NodeDoDermalUpgrade;
procedure NodeDoPhoenix;
procedure NodeDoPhoenixUprade;
procedure TakeDrugs;
procedure RemoveCombatArmor;

//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Free_AutoDoc_Uses          (8)
#define LVAR_DudeFleeOutside            (9)
#define LVAR_Gave_Stimpaks              (10)
#define LVAR_Gave_Discount              (11)
#define LVAR_Tried_Smooch               (12)
#define LVAR_Smooch_Dealer              (13)
#define LVAR_Free_Checkups              (14)

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_HOOVER_DAM);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_DOCTOR);
end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin

   variable yuri_stuff, temp_stuff, tile_yuri_stuff;

   if(local_var(LVAR_Gave_Discount) == 2) then
      tile_yuri_stuff = 25063;
   else
      tile_yuri_stuff = 25065;

   yuri_stuff := tile_contains_pid_obj(tile_yuri_stuff, self_elevation, PID_FOOTLOCKER_RUSTY_LEFT);
   temp_stuff := tile_contains_pid_obj(25865, self_elevation, PID_FOOTLOCKER_RUSTY_LEFT);


   Evil_Critter:=1;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

   move_obj_inven_to_obj(self_obj,temp_stuff);
   move_obj_inven_to_obj(yuri_stuff,self_obj);

   start_gdialog(NAME,self_obj,4,HEAD_DR_YURI_POLIVICH,BACKGROUND_ADOBE);
   gSay_Start;

   if (local_var(LVAR_Herebefore)==0) then begin
      if (dude_is_stupid) then
         call Node006;
      else
         call Node002;
   end else if (local_var(LVAR_Herebefore)==1) then begin
      if (dude_is_stupid) then
         call Node017;
      else
         call Node003;
   end

   gSay_End;
   end_dialogue;

   call restore_idiot_savant_int;

   move_obj_inven_to_obj(self_obj,yuri_stuff);
   move_obj_inven_to_obj(temp_stuff,self_obj);

   if (local_var(LVAR_DudeFleeOutside) == 1) then begin
      set_local_var(LVAR_DudeFleeOutside, 0);
      call DudeFleeOutside;
   end

end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/
   inc_evil_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE

procedure Node002
begin
Reply(230);
NOption(mstr(231)+dude_name+mstr(232),Node003,4);
NOption(233,Node004,4);
if (not(town_rep_is_neutral)) then
NOption(234,Node005,4);
NOption(mstr(235)+dude_name+mstr(236),Node006,-3);
NOption(237,Node007,4);
NOption(238,Node999,4);
end

procedure Node003
begin
Reply(260);
NOption(261,Node012,4);
NOption(262,Node013,4);
if (not(dude_has_ncr_connection) and (local_var(LVAR_Free_Checkups) == 0)) then
NOption(263,Node014,4);
// NOTE: This option is only available if Pablo has told the player about the broken auto-doc.
if (global_var(GVAR_DR_YURI_AUTODOC) == 1) then
NOption(264,Node015,4);

if (local_var(LVAR_Gave_Discount) == 2) then
   NOption(265,Node080,4);
else
   NOption(265,Node018,4);

if (global_var(GVAR_RESTOCK_DR_YURI) == 1) then
NOption(266,Node033,4);
if (global_var(GVAR_DR_YURI_AUTODOC) == 2) then
NOption(267,Node043,4);
// NOTE: This option overrides the first one, if Doc has offered the character free checkups.
if (dude_has_ncr_connection or (local_var(LVAR_Free_Checkups) == 1)) then
NOption(263,Node028,4);
if (global_var(GVAR_VISITED_HD_MORGUE) == 1) then
BOption(269,Node081,4);
NOption(268,Node999,1);
end

procedure Node004
begin
Reply(290);
NOption(mstr(291)+dude_name+mstr(236),Node003,4);
BOption(292,Node008,4);
BOption(293,Node999,4);
end

procedure Node005
begin
Reply(320);
BOption(mstr(321)+dude_name+mstr(236),Node003,4);
BOption(322,Node009,4);
BOption(323,Node999,4);
end

procedure Node006
begin
Reply(350);
GOption(351,Node011,-3);
NOption(352,Node999,-3);
end

procedure Node007
begin
Reply(380);
GOption(mstr(381)+dude_name+mstr(232),Node003,4);
NOption(382,Node010,4);
NOption(383,Node999,4);
end

procedure Node008
begin
Reply(410);
NOption(mstr(411)+dude_name+mstr(236),Node003,4);
BOption(412,Node999,4);
BOption(413,Node998,4);
NOption(414,Node999,4);
end

procedure Node009
begin
if (dude_is_male) then Reply(440); else
if (dude_is_female) then Reply(441);
NOption(mstr(442)+dude_name+mstr(236),Node003,4);
BOption(443,Node008,4);
BOption(444,Node999,4);
NOption(445,Node999,4);
end

procedure Node010
begin
Reply(470);
// NOTE: Cause the player to run out the door after this option is selected.
NOption(471,DudeFleeOutsideDialog,4);
NOption(472,Node999,4);
end

procedure Node011
begin
if (dude_is_male) then Reply(500); else
if (dude_is_female) then Reply(501);
BOption(502,Node016,-3);
if (dude_is_female) then
NOption(503,Node017,-3);
NOption(504,Node999,-3);
end

procedure Node012
begin
Reply(530);
NOption(531,Node061,4);
NOption(532,Node012a,4);
NOption(533,Node012b,4);
NOption(534,Node003,4);
NOption(535,Node999,4);
end

procedure Node012a
begin
Reply(2480);
NOption(531,Node061,4);
NOption(533,Node012b,4);
NOption(534,Node003,4);
NOption(535,Node999,4);
end

procedure Node012b
begin
Reply(2481);
NOption(531,Node061,4);
NOption(532,Node012a,4);
NOption(534,Node003,4);
NOption(535,Node999,4);
end

procedure Node013
begin
Reply(560);
if (get_dr_yuri_know_people_flag(DR_YURI_KNOW_PIERRE)) then
NOption(561,Node013a,4);
if (get_dr_yuri_know_people_flag(DR_YURI_KNOW_CANDICE)) then
NOption(562,Node013b,4);
if (get_dr_yuri_know_people_flag(DR_YURI_KNOW_GOVERNOR)) then
NOption(563,Node013c,4);
NOption(564,Node013d,4);
NOption(565,Node073,4);
if (dude_looking_for_escaped_prisoners) then
NOption(567,Node058,4);
NOption(566,Node999,4);
end

procedure Node013a begin
Reply(2510);
NOption(562,Node013b,4);
NOption(563,Node013c,4);
NOption(564,Node013d,4);
NOption(565,Node073,4);
NOption(566,Node999,4);
end

procedure Node013b begin
Reply(2511);
NOption(561,Node013a,4);
NOption(563,Node013c,4);
NOption(564,Node013d,4);
NOption(565,Node073,4);
NOption(566,Node999,4);
end

procedure Node013c begin
Reply(2512);
NOption(561,Node013a,4);
NOption(562,Node013b,4);
NOption(564,Node013d,4);
NOption(565,Node073,4);
NOption(566,Node999,4);
end

procedure Node013d begin
   variable autodoc;
   autodoc = "";

   if (global_var(GVAR_DR_YURI_AUTODOC) > 0 and global_var(GVAR_DR_YURI_AUTODOC) < 3) then
      autodoc = " " + mstr(2514);

Reply(mstr(2513) + autodoc);
NOption(561,Node013a,4);
NOption(562,Node013b,4);
NOption(563,Node013c,4);
NOption(565,Node073,4);
NOption(566,Node999,4);
end

// Node Node014
//
// Notes:
//
// change X to the correct samount of money that Doc should charge.

procedure Node014
begin
Reply(590);
// NOTE: Remove X amount of money from the player's inventory.
if (dude_caps >= 20) then
NOption(591,Node014a,4);
NOption(592,Node029,4);
NOption(593,Node003,4);
NOption(594,Node999,4);
end

procedure Node014a
begin
   item_caps_adjust(dude_obj, -20);
   call Node028;
end

procedure Node015
begin
Reply(620);
NOption(621,Node015a,4);
NOption(622,Node042,4);
NOption(623,Node003,4);
NOption(624,Node015b,4);
NOption(625,Node999,4);
end

procedure Node015a
begin
   set_global_var(GVAR_DR_YURI_AUTODOC, 2);
   call Node003;
end

procedure Node015b
begin
   set_global_var(GVAR_DR_YURI_AUTODOC, 2);
   call Node999;
end

procedure Node016
begin
Reply(650);
NOption(mstr(651)+dude_name+mstr(652)+dude_name+mstr(653),Node999,-3);
end

procedure Node017
begin
Reply(680);
NOption(681,Node999,-3);
end

// Node Node018
//
// Notes:
//
// Once the quest has been accepted to get drugs for the good doctor, remove option 3 ("Why is your stock so low?"), and any other conversation options that result in Doc or the player propositioning for the quest.

procedure Node018
begin

   if (global_var(GVAR_QUEST_HOOVER_PEACE) == QUEST_COMPLETED) then
      gdialog_mod_barter(-30);
   else
      gdialog_barter;

Reply(710);
// NOTE: Speech test, if successful the doc gives the PC 2 stimpaks and tells him that's all he can spare at the moment, and this text option is permanently removed.  This one links to the successful one.
if (local_var(LVAR_Gave_Stimpaks) == 0) then
NOption(711,Skill_Check_001_Speech,4);
if (global_var(GVAR_RESTOCK_DR_YURI) == 0) then
NOption(712,Node021,4);
NOption(713,Node003,4);
NOption(714,Node999,4);
end

procedure Skill_Check_001_Speech begin
   if is_success(roll_vs_skill(dude_obj, SKILL_CONVERSANT, -25)) then
      call Node019;
   else
      call Node020;
end

procedure Node019
begin
   give_pid_qty(dude_obj, PID_STIMPAK, 2)
   set_local_var(LVAR_Gave_Stimpaks, 1);
Reply(740);
NOption(741,Node022,4);
end

procedure Node020
begin
Reply(770);
NOption(741,Node022,4);
end

procedure Node021
begin
Reply(800);
GOption(801,Node022,4);
if (dude_caps >= 1000) then
GOption(802,Node023,4);
NOption(803,Node003,4);
NOption(804,Node999,4);
end

procedure Node022
begin
Reply(830);
NOption(831,Node024,4);
// NOTE: Adds quest info to PipBoy.
NOption(832,Node022a,4);
// NOTE: This option is only available if the player has 10 RadAway, 10 Buffout, and 10 Mentats in his or her inventory. Adds quest/completed info in PipBoy.
if (
   (dude_item_count(PID_STIMPAK) >= 20) and
   (dude_item_count(PID_SUPER_STIMPAK) >= 20) and
   (dude_item_count(PID_RADAWAY) >= 10) and
   (dude_item_count(PID_MENTATS) >= 10) and
   (dude_item_count(PID_BUFFOUT) >= 10)
   )
then
NOption(833,Node025,4);
NOption(834,Node026,4);
NOption(835,Node022b,4);
end

procedure Node022a
begin
   set_global_var(GVAR_RESTOCK_DR_YURI, 1);
   call Node003;
end

procedure Node022b
begin
   set_global_var(GVAR_RESTOCK_DR_YURI, 1);
   call Node999;
end

procedure Node023
begin
set_global_var(GVAR_DONATE_DR_YURI, 1);
Reply(860);
NOption(861,Node003,4);
NOption(862,Node999,4);
end

procedure Node024
begin
Reply(890);
// NOTE: Adds quest info in PipBoy.
NOption(891,Node022a,4);
// NOTE: Adds quest/completed info in PipBoy.
if (
   (dude_item_count(PID_STIMPAK) >= 20) and
   (dude_item_count(PID_SUPER_STIMPAK) >= 20) and
   (dude_item_count(PID_RADAWAY) >= 10) and
   (dude_item_count(PID_MENTATS) >= 10) and
   (dude_item_count(PID_BUFFOUT) >= 10)
   )
then
NOption(892,Node025,4);
// NOTE: Doctor check required for this option to appear.
if (dude_skill(SKILL_DOCTOR) > 50) then
GOption(893,Node027,4);
NOption(894,Node022b,4);
end

procedure Node025
begin
Reply(920);
NOption(921,Node037,4);
if (local_var(LVAR_Gave_Discount) == 1) then
NOption(922,Node038,4);
end

procedure Node026
begin
Reply(950);
// NOTE: Adds quest info in PipBoy.
NOption(951,Node026a,4);
NOption(952,Node036,4);
// NOTE: This option is only available if the character has 10 RadAway, 10 Mentats, and 10 Buffout.  Adds quest/completed quest info in PipBoy.
if (
   (dude_item_count(PID_STIMPAK) >= 20) and
   (dude_item_count(PID_SUPER_STIMPAK) >= 20) and
   (dude_item_count(PID_RADAWAY) >= 10) and
   (dude_item_count(PID_MENTATS) >= 10) and
   (dude_item_count(PID_BUFFOUT) >= 10)
   )
then
NOption(953,Node026b,4);
NOption(954,Node999,4);
// NOTE: Adds quest info in PipBoy
NOption(955,Node026c,4);
end

procedure Node026a
begin
   set_local_var(LVAR_Gave_Discount, 1);
   call Node022a;
end

procedure Node026b
begin
   set_local_var(LVAR_Gave_Discount, 1);
   call Node025;
end

procedure Node026c
begin
   set_local_var(LVAR_Gave_Discount, 1);
   call Node022b;
end

procedure Node027
begin
Reply(980);
NOption(1821,Node066,4);
NOption(981,Node999,4);
end

procedure Node028
begin
Reply(1010);
NOption(741,Node030,4);
end

procedure Node029
begin
Reply(1040);
if (dude_caps >= 20) then
NOption(1041,Node014a,4);
NOption(1042,Node003,4);
NOption(1043,Node999,4);
end

// Node Node030
//
// Notes:
//
// Replace X with the appropriate amount of money to treat the character's medical problems.

procedure Node030
begin

fadeout(1);
game_time_advance(random(1,10) * ONE_GAME_MINUTE);
fadein(1);

variable amt, cnd;
amt = 5;
cnd = mstr(154);

if(dude_is_poisoned) then begin
   amt = 50;
   cnd = mstr(152);
end else if(dude_is_irradiated) then begin
   amt = 500;
   cnd = mstr(151);
end else if(Is_Injured(dude_obj)) then begin
   amt = 200;
   cnd = mstr(150);
end else if(Is_Crippled(dude_obj)) then begin
   amt = 1000;
   cnd = mstr(155);
end else if(dude_is_addicted_to_jet) then begin
   amt = 25;
   cnd = mstr(156);
end else if(dude_is_addicted_to_smooch) then begin
   amt = 25;
   cnd = mstr(157);
end else if(dude_is_addicted) then begin
   amt = 0;
   cnd = mstr(153);
end

// free price means normal addiction
if (amt == 0) then begin
   if (dude_is_male) then
   Reply(mstr(1070)+mstr(1078));
else if (dude_is_female) then
   Reply(mstr(1072)+mstr(1078));

   NOption(1079,Node003,4);
   NOption(1080,Node999,4);

// we're gonna charge the player for something
end else begin
   if (dude_is_male) then
      Reply(mstr(1070)+cnd+mstr(1071)+amt+mstr(1077));
   else if (dude_is_female) then
      Reply(mstr(1072)+cnd+mstr(1071)+amt+mstr(1077));

   if (dude_caps >= amt) then
      NOption(1073,Node031,4);
   NOption(1074,Node003,4);
   NOption(1075,Node999,4);
   NOption(1076,Node999,4);
end
end

procedure Node031
begin
Reply(1100);
NOption(741,Node032,4);
end

// Node Node032
//
// Notes:
//
// Heal the character back to a fully healthy status.

procedure Node032
begin
if(dude_is_poisoned) then begin
   call HealPlayer(16, 50, HEAL_POISON, 1);
end else if(dude_is_irradiated) then begin
   call HealPlayer(12, 500, HEAL_RADIATION, 1);
end else if(Is_Injured(dude_obj)) then begin
   call HealPlayer(1, 200, HEAL_HP, 1);
end else if(Is_Crippled(dude_obj)) then begin
   call HealPlayer(48, 1000, HEAL_CRIPPLE, 1);
end else if(dude_is_addicted_to_jet) then begin
   item_caps_adjust(dude_obj, -25);
   fadeout(1);
   give_pid_qty(dude_obj, PID_JET_ANTIDOTE, 1)
   use_item_on_dude(obj_carrying_pid_obj(dude_obj, PID_JET_ANTIDOTE));
   fadein(1);
end else if(dude_is_addicted_to_smooch) then begin
   item_caps_adjust(dude_obj, -25);
   fadeout(1);
   give_pid_qty(dude_obj, PID_SMOOCH_ANTIDOTE, 1)
   use_item_on_dude(obj_carrying_pid_obj(dude_obj, PID_SMOOCH_ANTIDOTE));
   fadein(1);
end
else begin
   fadeout(1);
   item_caps_adjust(dude_obj, -5);
   fadein(1);
end

Reply(1130);
NOption(1131,Node003,4);
NOption(1132,Node999,4);
end

procedure Node033
begin
Reply(1160);
if ((dude_item_count(PID_SMOOCH) > 0) and (local_var(LVAR_Tried_Smooch) == 0)) then
NOption(1161,Node059,4);
// NOTE: Only show this option if the character has all required drugs in his or her inventory.
if (
   (dude_item_count(PID_STIMPAK) >= 20) and
   (dude_item_count(PID_SUPER_STIMPAK) >= 20) and
   (dude_item_count(PID_RADAWAY) >= 10) and
   (dude_item_count(PID_MENTATS) >= 10) and
   (dude_item_count(PID_BUFFOUT) >= 10)
   )
then
NOption(1162,Node025,4);
NOption(1163,Node034,4);
NOption(1164,Node033a,4);
NOption(1165,Node999,4);
end

procedure Node033a
begin
   set_global_var(GVAR_RESTOCK_DR_YURI, 0);
   call Node035;
end


procedure Node034
begin
Reply(1190);
NOption(1191,Node999,4);
end

procedure Node035
begin
Reply(1220);
NOption(1221,Node003,4);
NOption(1222,Node999,4);
end

// Node Node036
//
// Notes:
//
// Option two changes depending on Smooch status

procedure Node036
begin
Reply(1250);
NOption(1251,Node036a,4);
if ((local_var(LVAR_Tried_Smooch) == 1) and
   ((global_var(GVAR_HD_SMOOCH_STATUS) == SMOOCH_HIGH) or (global_var(GVAR_HD_SMOOCH_STATUS) == SMOOCH_ALL))
) then
   NOption(1252,Node049,4);
else
   NOption(1252,Node065,4);
end

procedure Node036a
begin
   set_local_var(LVAR_Gave_Discount, 1);
   call Node999;
end

procedure Node037
begin
Reply(mstr(1280)+dude_name+mstr(1281));
GOption(1282,Node039,4);
NOption(1283,Node040,4);
NOption(1284,Node040,4);
end

// Node Node038
//
// Notes:
//
// Buy drugs

procedure Node038
begin

   set_local_var(LVAR_Gave_Discount, 2);
   call TakeDrugs;

Reply(1310);
NOption(1311,Node003,4);
NOption(1312,Node999,4);
end

procedure Node039
begin

   set_local_var(LVAR_Gave_Discount, 0);
   call TakeDrugs;
   inc_hoover_dam_rep(5);

Reply(mstr(1340)+dude_name+mstr(1341));
if ((local_var(LVAR_Tried_Smooch) == 1) and
   (local_var(LVAR_Smooch_Dealer) == 0) and
   ((global_var(GVAR_HD_SMOOCH_STATUS) == SMOOCH_HIGH) or (global_var(GVAR_HD_SMOOCH_STATUS) == SMOOCH_ALL))
) then
   NOption(1342,Node049,4);
else
   NOption(1342,Node041,4);


NOption(1343,Node003,4);
NOption(1344,Node999,4);
end

procedure Node040
begin

   set_local_var(LVAR_Gave_Discount, 2);
   call TakeDrugs;
   give_pid_qty(dude_obj, PID_JET, 3)

Reply(1370);
NOption(1371,Node003,4);
NOption(1372,Node999,4);
end

procedure Node041
begin
Reply(mstr(1400)+dude_name+mstr(1401));
NOption(1402,Node999,4);
end

procedure Node042
begin
Reply(1430);
NOption(1431,Node042a,4);
NOption(1432,Node042b,4);
BOption(1433,Node999,4);
end

procedure Node042a
begin
   set_local_var(LVAR_Free_AutoDoc_Uses, 10);
   call Node015a;
end

procedure Node042b
begin
   set_local_var(LVAR_Free_AutoDoc_Uses, 10);
   call Node015b;
end

procedure Node043
begin
Reply(1460);
// NOTE: remove this after the parts are given.
if ((dude_item_count(PID_MEDIMATRIX_PARTICLE_COMPOSER) > 0) and (global_var(GVAR_DR_YURI_AUTODOC) == 2)) then
NOption(1461,Node044,4);
// NOTE: remove this after the parts are given.
if ((dude_item_count(PID_MEDIMATRIX_PARTICLE_COMPOSER) == 0) and (global_var(GVAR_DR_YURI_AUTODOC) == 2)) then
NOption(1462,Node045,4);
if (global_var(GVAR_DR_YURI_AUTODOC) == 2) then
NOption(1463,Node043a,4);
// NOTE: only display this once [insert name of NPC X who has a mild repair skill] has agreed to help. (after doing some minor, or maybe greater, errand for him or her)
if (
   (dude_item_count(PID_MEDIMATRIX_PARTICLE_COMPOSER) > 0) and
   (global_var(GVAR_DR_YURI_AUTODOC_FIX_HELP) == DR_YURI_AUTODOC_FIX_HELP_OTTO) and
   (global_var(GVAR_DR_YURI_AUTODOC) == 2)
   ) then
NOption(1464,Node054,4);
if (
   (dude_item_count(PID_MEDIMATRIX_PARTICLE_COMPOSER) > 0) and
   (global_var(GVAR_DR_YURI_AUTODOC_FIX_HELP) == DR_YURI_AUTODOC_FIX_HELP_DIANNE) and
   (global_var(GVAR_DR_YURI_AUTODOC) == 2)
   ) then
NOption(1465,Node054,4);
if (
   (dude_item_count(PID_MEDIMATRIX_PARTICLE_COMPOSER) > 0) and
   (global_var(GVAR_DR_YURI_AUTODOC_FIX_HELP) == DR_YURI_AUTODOC_FIX_HELP_PIERRE) and
   (global_var(GVAR_DR_YURI_AUTODOC) == 2)
   ) then
NOption(1466,Node054,4);
NOption(1467,Node055,4);
NOption(1165,Node999,4);
end

procedure Node043a
begin
   set_global_var(GVAR_DR_YURI_AUTODOC, 1);
   call Node035;
end

procedure Node044
begin
Reply(1490);
GOption(1491,Node046,4);
NOption(1492,Node047,4);
NOption(1493,Node047,4);
end

procedure Node045
begin
Reply(1520);
NOption(1521,Node043,4);
NOption(1522,Node999,4);
end

procedure Node046
begin
Reply(mstr(1550)+dude_name+mstr(1551));
NOption(1552,Node046a,4);
NOption(1553,Node048,4);
NOption(1554,Node046b,4);
end

procedure Node046Reward
begin
give_pid_qty(dude_obj, PID_STIMPAK, 1)
give_pid_qty(dude_obj, PID_SUPER_STIMPAK, 1)
remove_pid_qty(dude_obj, PID_MEDIMATRIX_PARTICLE_COMPOSER, 1)
give_xp(500);
display_mstr(159);
set_global_var(GVAR_DR_YURI_AUTODOC, 3);
end

procedure Node046a
begin
   call Node046Reward;
   call Node003;
end

procedure Node046b
begin
   call Node046Reward;
   call Node999;
end


procedure Node047
begin

   set_local_var(LVAR_Free_AutoDoc_Uses, 10);

Reply(1580);
// NOTE: This requires the character's repair skill to be of X amount.
if (has_skill(dude_obj,SKILL_REPAIR)>=75) then
   NOption(1581,Node048,4);
// NOTE: This requires the character's skill to be below X amount.
else
   NOption(1582,Node050,4);
NOption(1583,Node999,4);
end

procedure Node048
begin
Reply(1610);
// NOTE: Do a repair check.
NOption(1611,Skill_Check_002_Repair,4);
NOption(1612,Node053,4);
NOption(1613,Node999,4);
end

procedure Skill_Check_002_Repair begin
   if is_success(roll_vs_skill(dude_obj, SKILL_REPAIR, -20)) then
      call Node051Reward;
   else
      call Node052;
end

// Node Node049
//
// Notes:
//
// Option 2 needs a Barter roll

procedure Node049
begin
Reply(1640);
NOption(1641,Node049a,4);
NOption(1642,Skill_Check_003_Barter,4);
NOption(1643,Node065,4);
end

procedure Node049a begin
   set_local_var(LVAR_Smooch_Dealer, 50);
   call Node062;
end

procedure Skill_Check_003_Barter begin
   if is_success(roll_vs_skill(dude_obj, SKILL_BARTER, -25)) then
      call Node064;
   else
      call Node063;
end

procedure Node050
begin
Reply(1670);
NOption(1671,Node003,4);
NOption(1672,Node999,4);
NOption(1673,Node046b,4);
end

procedure Node051
begin
Reply(1700);
GOption(1701,Node056,4);

if ((local_var(LVAR_Tried_Smooch) == 1) and
   (local_var(LVAR_Smooch_Dealer) == 0) and
   ((global_var(GVAR_HD_SMOOCH_STATUS) == SMOOCH_HIGH) or (global_var(GVAR_HD_SMOOCH_STATUS) == SMOOCH_ALL))
) then
   NOption(1702,Node049,4);
else
   NOption(1702,Node041,4);
NOption(1703,Node003,4);
NOption(1704,Node999,4);
end

procedure Node051Reward begin
   give_xp(500);
   display_mstr(160);
   call Node051;
end

// Node Node052
//
// Notes:
//
// not sure if the char should be able to repeat the attempt for repair or not.

procedure Node052
begin
Reply(1730);
// NOTE: retry roll?  If it's failed I can't link node052 to node052
NOption(1731,Skill_Check_002_Repair,4);
NOption(1732,Node051,4);
// NOTE: ends quest.
NOption(1733,Node052a,4);
end

procedure Node052a
begin
   set_global_var(GVAR_DR_YURI_AUTODOC, 3);
   call Node999;
end

procedure Node053
begin
Reply(1760);
NOption(1761,Node053a,4);
NOption(1762,Node999,4);
end

procedure Node053a
begin
   set_local_var(LVAR_Free_AutoDoc_Uses, 15);
   call Skill_Check_002_Repair;
end

procedure Node054
begin
   fadeout(1);
   game_time_advance(ONE_GAME_HOUR * 2);
   fadein(1);
      give_xp(100);
Reply(1790);
NOption(741,Node051,4);
end

procedure Node055
begin

variable autodoc;
autodoc = mstr(1828);

if (global_var(GVAR_DR_YURI_AUTODOC) > 0 and global_var(GVAR_DR_YURI_AUTODOC) < 3) then
   autodoc = mstr(1829);

Reply(mstr(1820) + " " + autodoc);
NOption(1821,Node066,4);
if ((global_var(GVAR_DR_YURI_AUTODOC) == 0) or (global_var(GVAR_DR_YURI_AUTODOC) == 3)) then begin
NOption(1822,Node067,4);
NOption(1823,Node068,4);
NOption(1824,Node069,4);
NOption(1825,Node070,4);
end
NOption(1826,Node003,4);
NOption(1827,Node999,4);
end

procedure Node056
begin

   set_local_var(LVAR_Free_Checkups, 1);

if (dude_is_male) then
   Reply(1850);
else if (dude_is_female) then
   Reply(1851);

   if ((local_var(LVAR_Tried_Smooch) == 1) and
   (local_var(LVAR_Smooch_Dealer) == 0) and
   ((global_var(GVAR_HD_SMOOCH_STATUS) == SMOOCH_HIGH) or (global_var(GVAR_HD_SMOOCH_STATUS) == SMOOCH_ALL))
) then
   NOption(1852,Node049,4);
else
   NOption(1852,Node041,4);

NOption(1853,Node003,4);
NOption(1854,Node999,4);
end

procedure Node057
begin

   fadeout(1);
   remove_pid_qty(dude_obj, PID_SMOOCH, 1)
   game_time_advance(random(1,2) * ONE_GAME_HOUR);
   give_pid_qty(dude_obj, PID_JET, 1)
   fadein(1);

Reply(1880);
NOption(1881,Node999,4);
end

procedure Node058
begin
Reply(1910);
NOption(713,Node003,4);
NOption(2331,Node999,4);
end

procedure Node059
begin
Reply(1940);
NOption(1941,Node060,4);
NOption(1942,Node999,4);
end

procedure Node060
begin
Reply(1970);
NOption(1971,Node057,4);
end

procedure Node061
begin
Reply(2000);
NOption(2001,Node003,4);
NOption(2002,Node999,4);
end

procedure Node062
begin
Reply(2030);
NOption(2031,Node999,4);
end

procedure Node063
begin
Reply(2060);
NOption(2061,Node049a,4);
NOption(2062,Node999,4);
end

procedure Node064
begin
   set_local_var(LVAR_Smooch_Dealer, 75);
Reply(2090);
NOption(2031,Node999,4);
end

procedure Node065
begin
Reply(2120);
NOption(2062,Node999,4);
end

procedure Node066
begin
Reply(2150);
if ((global_var(GVAR_DR_YURI_AUTODOC) == 0) or (global_var(GVAR_DR_YURI_AUTODOC) == 3)) then begin
NOption(2151,Node067,4);
NOption(2152,Node068,4);
NOption(2153,Node069,4);
NOption(2154,Node070,4);
end
NOption(1826,Node003,4);
NOption(1827,Node999,4);
end

procedure Node067
begin

variable str;
str = mstr(2184);

if (local_var(LVAR_Gave_Discount) == 2) then
   str = mstr(2185);

Reply(mstr(2180) + str + mstr(2183));
NOption(2181,NodeDoDermal,4);
NOption(2182,Node999,4);
end

procedure Node068
begin

variable str;
str = mstr(2214);

if (local_var(LVAR_Gave_Discount) == 2) then
   str = mstr(2215);

Reply(mstr(2210) + str + mstr(2213));
NOption(2211,NodeDoDermalUpgrade,4);
NOption(2212,Node999,4);
end

procedure Node069
begin

variable str;
str = mstr(2244);

if (local_var(LVAR_Gave_Discount) == 2) then
   str = mstr(2245);

Reply(mstr(2240) + str + mstr(2243));

NOption(2241,NodeDoPhoenix,4);
NOption(2242,Node999,4);
end

procedure Node070
begin

   variable str;
   str = mstr(2274);

   if (local_var(LVAR_Gave_Discount) == 2) then
      str = mstr(2275);

   Reply(mstr(2270) + str + mstr(2273));

NOption(2271,NodeDoPhoenixUprade,4);
NOption(2272,Node999,4);
end

procedure Node071
begin
Reply(2300);
NOption(2301,Node999,4);
end

procedure Node072
begin
Reply(2330);
NOption(2331,Node999,4);
end

procedure Node073
begin
Reply(2360);
NOption(2361,Node074,4);
end

procedure Node074
begin
Reply(2390);
NOption(2391,Node075,4);
NOption(2392,Node075,4);
end

procedure Node075
begin
Reply(2420);
NOption(2421,Node076,4);
end

procedure Node076
begin
Reply(2450);
NOption(2451,Node077,4);
NOption(2452,Node078,4);
NOption(2453,Node079,4);
end

procedure Node077
begin
Reply(2540);
NOption(561,Node013a,4);
NOption(562,Node013b,4);
NOption(563,Node013c,4);
NOption(564,Node013d,4);
NOption(565,Node073,4);
NOption(566,Node999,4);
end

procedure Node078
begin
Reply(2541);
NOption(561,Node013a,4);
NOption(562,Node013b,4);
NOption(563,Node013c,4);
NOption(564,Node013d,4);
NOption(565,Node073,4);
NOption(566,Node999,4);
end

procedure Node079
begin
Reply(2542);
NOption(561,Node013a,4);
NOption(562,Node013b,4);
NOption(563,Node013c,4);
NOption(564,Node013d,4);
NOption(565,Node073,4);
NOption(566,Node999,4);
end

procedure NodeDoDermal begin
   variable item, price;

   price = 5500;
   if (local_var(LVAR_Gave_Discount) == 2) then begin
      price = 4950;
   end

   if ((dude_caps >= price) and (dude_has_combat_armor) ) then begin
      item_caps_adjust(dude_obj,-price);
      call RemoveCombatArmor;
      critter_add_trait(dude_obj,TRAIT_PERK,PERK_dermal_armor_perk,1);
      game_time_advance(2*ONE_GAME_DAY);
      fadeout(600);
      fadein(600);
      call Node072;
   end else begin
      call Node071;
   end
end

procedure NodeDoDermalUpgrade begin
   variable item, price;

   price = 33000;
   if (local_var(LVAR_Gave_Discount) == 2) then begin
      price = 29700;
   end

   if ((dude_caps >= price) and (dude_has_combat_armor)) then begin
      item_caps_adjust(dude_obj,-price);
      call RemoveCombatArmor;
      critter_rm_trait(dude_obj,TRAIT_PERK,PERK_dermal_armor_perk,1); // Seraph's Code
      critter_add_trait(dude_obj,TRAIT_PERK,PERK_dermal_enhancement_perk,1);
      game_time_advance(5*ONE_GAME_DAY);
      fadeout(600);
      fadein(600);
      call Node072;
   end else begin
      call Node071;
   end
end

procedure NodeDoPhoenix begin
   variable item, price;

   price = 8500;
   if (local_var(LVAR_Gave_Discount) == 2) then begin
      price = 7650;
   end

   if ((dude_caps >= price) and (dude_has_combat_armor)) then begin
      item_caps_adjust(dude_obj,-price);
      call RemoveCombatArmor;
      critter_add_trait(dude_obj,TRAIT_PERK,PERK_phoenix_armor_perk,1);
      game_time_advance(3*ONE_GAME_DAY);
      fadeout(600);
      fadein(600);
      call Node072;
   end else begin
      call Node071;
   end
end

procedure NodeDoPhoenixUprade begin
   variable item, price;

   price = 49000;
   if (local_var(LVAR_Gave_Discount) == 2) then begin
      price = 44100;
   end

   if ((dude_caps) >= price and (dude_has_combat_armor)) then begin
      item_caps_adjust(dude_obj,-price);
      call RemoveCombatArmor;
      critter_rm_trait(dude_obj,TRAIT_PERK,PERK_phoenix_armor_perk,1); // Seraph's Code
      critter_add_trait(dude_obj,TRAIT_PERK,PERK_phoenix_enhancement_perk,1);
      game_time_advance(4*ONE_GAME_DAY);
      fadeout(600);
      fadein(600);
      call Node072;
   end else begin
      call Node071;
   end
end

procedure DudeFleeOutside begin
   variable tile;
   tile = 14876;

   closest_clear_tile(dude_obj, 14876, tile)
   animate_move_obj_to_tile(dude_obj, tile, (ANIMATE_RUN bwor ANIMATE_INTERRUPT));
end

procedure DudeFleeOutsideDialog begin
   set_local_var(LVAR_DudeFleeOutside, 1);
   call Node999;
end

procedure TakeDrugs begin
   remove_pid_qty(dude_obj, PID_STIMPAK, 20)
   remove_pid_qty(dude_obj, PID_SUPER_STIMPAK, 20)
   remove_pid_qty(dude_obj, PID_RADAWAY, 10)
   remove_pid_qty(dude_obj, PID_MENTATS, 10)
   remove_pid_qty(dude_obj, PID_BUFFOUT, 10)
   give_xp(1000);
   display_mstr(158);
   set_global_var(GVAR_RESTOCK_DR_YURI, 2);
end

procedure RemoveCombatArmor begin

   if (dude_item(PID_COMBAT_ARMOR)) then begin
      remove_pid_qty(dude_obj, PID_COMBAT_ARMOR, 1)
   end
   else if (dude_item(PID_BROTHERHOOD_COMBAT_ARMOR)) then begin
      remove_pid_qty(dude_obj, PID_BROTHERHOOD_COMBAT_ARMOR, 1)
   end
   else if (dude_item(PID_HERMES_ARMOR)) then begin
      remove_pid_qty(dude_obj, PID_HERMES_ARMOR, 1)
   end
   else if (dude_item(PID_HERMES_ARMOR_MK_II)) then begin
      remove_pid_qty(dude_obj, PID_HERMES_ARMOR_MK_II, 1)
   end
   else if (dude_item(PID_NCR_RANGER_COMBAT_ARMOR)) then begin
      remove_pid_qty(dude_obj, PID_NCR_RANGER_COMBAT_ARMOR, 1)
   end
   else if (dude_item(PID_NCR_ARMOR)) then begin
      remove_pid_qty(dude_obj, PID_NCR_ARMOR, 1)
   end
   else if (dude_item(PID_COMBAT_ARMOR_MK_II)) then begin
      remove_pid_qty(dude_obj, PID_COMBAT_ARMOR_MK_II, 1)
   end

end

procedure Node080
begin

   if (global_var(GVAR_QUEST_HOOVER_PEACE) == QUEST_COMPLETED) then
      gdialog_mod_barter(-50);
   else
      gdialog_mod_barter(-20);

   Reply(g_mstr(200));
   NOption(g_mstr(350),Node999,4);
end

procedure Node081
begin
   set_global_var(GVAR_VISITED_HD_MORGUE, 2);
   Reply(2570);
   NOption(g_mstr(350),Node999,4);
end


//xxxxxxxxxxxxxxxxxxxx
