/*

        Name:           Davis
        Location:
        Description:

           Created: 27/01/2021 18:57:57

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
#include "..\HEADERS\maxbunkr.h"

#define NAME                    SCRIPT_MBDAVIS

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_BROTHERHOOD)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending





// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Mich_0;
procedure Mich_1_Ba_1;
procedure Mich_1_Ba_2;
procedure Mich_1a_1;
procedure Mich_1a_1B;
procedure Mich_1a_2a;
procedure Mich_1a_2B_1;
procedure Mich_1a_2B_2a;
procedure Mich_1a_2B_2b;
procedure Mich_1a_D1_a;
procedure Mich_1a_D1_b;
procedure Mich_1a_D2;
procedure Mich_1a_D3;
procedure Mich_1b_1;
procedure Mich_1b_2a;
procedure Mich_1b_2B;
procedure Mich_2_1;
procedure Mich_2_2;
procedure Mich_2_3a_1;
procedure Mich_2_3a_2a_1;
procedure Mich_2_3a_2a_2;
procedure Mich_2_3a_2b_1;
procedure Mich_2_3a_2b_2a_1;
procedure Mich_2_3a_2b_2a_2a_1;
procedure Mich_2_3a_2b_2a_2a_2;
procedure Mich_2_3a_2b_2a_2b_1;
procedure Mich_2_3a_2b_2a_2b_2;
procedure Mich_2_3a_2b_2b_1;
procedure Mich_2_3a_2b_2b_2;
procedure Mich_2_3a_2b_2c_1;
procedure Mich_2_3a_2b_2c_2a_1;
procedure Mich_2_3a_2b_2c_2a_2;
procedure Mich_2_3a_2b_2c_2b_1;
procedure Mich_2_3a_2b_2c_2b_2;
procedure Mich_2_3a_2b_2c_2b_3;
procedure Mich_2_3a_2c;
procedure Mich_2_3a_2d_1;
procedure Mich_2_3a_2d_2a;
procedure Mich_2_3a_2d_2b;
procedure Mich_2_3b;
procedure Mich_2_3b_B;
procedure Mich_2_3c_1a;
procedure Mich_2_3c_1b_1;
procedure Mich_2_3c_1b_2a;
procedure Mich_2_3c_1b_2B_1a;
procedure Mich_2_3c_1b_2B_1b;
procedure Mich_2_3c_1b_2B_2;
procedure Mich_2_3c_1b_2B_3;
procedure Mich_2_3c_2a_1;
procedure Mich_2_3c_2a_2a_1;
procedure Mich_2_3c_2a_2a_2a;
procedure Mich_2_3c_2a_2a_2b_1;
procedure Mich_2_3c_2a_2a_2b_2;
procedure Mich_2_3c_2b_1;
procedure Mich_2_3c_2b_2;
procedure Mich_2_3c_2b_3;
procedure Mich_2_3d_1;
procedure Mich_2_3d_2a;
procedure Mich_2_3d_2b_1;
procedure Mich_2_3d_2b_2;
procedure Mich_3_1;
procedure Mich_3_2;
procedure Mich_3_3a;
procedure Mich_3_3b_1;
procedure Mich_3_4_1;
procedure Mich_3_4_2a;
procedure Mich_3_4_2b;
procedure Mich_3_4_2c;
procedure Mich_3_4_2d;
procedure Mich_3_4_3;
procedure Mich_4_1;
procedure Mich_4_2;
procedure Mich_5_1;
procedure Mich_5_2a;
procedure Mich_5_2b;
procedure Mich_5_3;
procedure Mich_5_4;
procedure Mich_5_5;
procedure Mich_5_6a_1;
procedure Mich_5_6a_2;
procedure Mich_5_6b_1;
procedure Mich_5_6b_2;
procedure Mich_5_6b_3;
procedure Mich_5_6c_1;
procedure Mich_5_6c_2;
procedure Mich_5_7_1;
procedure Mich_5_7_2;
procedure Mich_5_7_3a;
procedure Mich_5_7_3b;
procedure Mich_5_7_4a_1;
procedure Mich_5_7_4a_2a;
procedure Mich_5_7_4a_2b;
procedure Mich_5_7_4b_1;
procedure Mich_5_7_4b_2;
procedure Mich_5_7_4b_2b_1;
procedure Mich_5_7_4b_2b_2;
procedure Mich_5_7_B_1;
procedure Mich_5_7_B_2;
procedure Mich_6_1;
procedure Mich_6_2a;
procedure Mich_6_2b;
procedure Mich_6_3;
procedure Mich_6_4a_1;
procedure Mich_6_4a_2;
procedure Mich_6_4a_3;
procedure Mich_6_4a_4a;
procedure Mich_6_4a_4b;
procedure Mich_6_4b;
procedure Mich_7_1;
procedure Mich_7_2;
procedure Mich_7_3;
procedure Mich_8a_1;
procedure Mich_8a_2;
procedure Mich_8a_3;
procedure Mich_8a_4;
procedure Mich_8b_1;
procedure Mich_8b_2;
procedure Mich_8b_3;
procedure Mich_9;
procedure Mich_B_0;
procedure Mich_B_1;
procedure Mich_B_2;
procedure Mich_B_3a_1;
procedure Mich_B_3a_2;
procedure Mich_B_3b;
procedure Mich_B_4a_1;
procedure Mich_B_4a_2;
procedure Mich_B_4a_3;
procedure Mich_B_4a_4;
procedure Mich_B_4a_5;
procedure Mich_B_4b_1;
procedure Mich_B_4b_2;
procedure Mich_B_5_1;
procedure Mich_B_5_2;
procedure Mich_B_5_3;
procedure Mich_B_5_4;
procedure Mich_B_9_1;
procedure Mich_B_9_2;
procedure Node139;
procedure Node140;
procedure Node141;
procedure Node142;
procedure Node143;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)

variable Mich_Rude := "0";
variable Mich_Rad_Away := "0";
variable Mich_Danger_Site := "0";
variable Mich_Bones_Know := "0";
variable Mich_Bones_Screwed := "0";
variable Mich_Site_Bones_Return := "0";
variable Mich_G_Counter_Return := "0";
variable Mich_Shovel := "0";
variable Mich_Alex_Force := "0";
variable Mich_Cemetary_Bones := "0";
variable Mich_Guilt_Trip := "0";


/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_BROTHERHOOD_OF_STEEL);
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
   call new_plague_check(self_obj, LVAR_Herebefore);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;
   call set_idiot_savant_int;

   start_gdialog(NAME,self_obj,4,-1,-1);
   gSay_Start;

   if (local_var(LVAR_Herebefore)==0) then begin
       call Mich_1a_1;
end else if (local_var(LVAR_Herebefore)==1) then begin
       call Mich_1b_1;
end
gSay_End;
end_dialogue;

   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin

/* Increment the aligned critter counter*/

 inc_neutral_critter

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE


procedure Mich_0
begin
Reply(200);
NOption(201,Mich_1a_1,1);
// NOTE: Michael needs to have spoken node Mich_1a_2a, OR, for dumb players, node Mich_1a_D2, where he introduces himself by name AND the variable Mich_Rude must be 2 or less.
NOption(202,Mich_1b_1,1);
// NOTE: Michael needs to have spoken node Mich_1a_2a, where he introduces himself by name AND the variable Mich_Rude must be 3 or greater. If Mich_Rude>=10 OR Mich_Guilt_Trip>1, then Michael will not speak to the PC at all, but will float hostile text.
NOption(203,Mich_1_Ba_1,1);
end

// Node Mich_1_Ba_1
//
// Notes:
//
// Because the PC has been rude to Michael previously, the Priest will not use his rad-away freely on him. (See Mich_2_2). Michael's justification for this is that the PC is a 'bad sort', and the drugs should be used on someone more deserving. \

procedure Mich_1_Ba_1
begin
if (dude_is_male) then Reply(230); else
if (dude_is_female) then Reply(231);
NOption(232,Mich_9,4);
// NOTE: This option only appears IF the PC has a shovel AND Mich_Shovel>0 AND Mich_Cemetary_Bones=0. Also, the variable Mich_Alex_Force must be greater than 0, OR Mich_G_Counter_Return must be greater than 0 AND Mich_Site_Bones_Return must be greater than 2.
NOption(233,Mich_1b_2a,4);
// NOTE: This node is only visible if the variable Mich_Alex_Force>0 AND Mich_Shovel<1.
NOption(234,Mich_7_1,4);
if (dude_is_male) then
NOption(235,Mich_1_Ba_2,4);
if (dude_is_female) then
NOption(236,Mich_1_Ba_2,4);
NOption(237,Node999,4);
end

// Node Mich_1_Ba_2
//
// Notes:
//
// Increment Mich_Rude by 1.

procedure Mich_1_Ba_2
begin
Reply(260);
BOption(261,Node998,4);
NOption(262,Node999,4);
end

procedure Mich_1a_1
begin
if (dude_is_male) then Reply(290); else
if (dude_is_female) then Reply(291);
NOption(292,Mich_1a_2a,4);
/*if (dude_is_male) then
NOption(293,Mich_1a_1B,4);
if (dude_is_female) then
NOption(294,Mich_1a_1B,4);*/
if(map_var(MVAR_KNOW_CAMERA) == 1 and map_var(MVAR_VIDEO_ACCESS) == 0) then
NOption(298,Node139,4);
if(global_var(GVAR_QUEST_CURE_COMMANDER) == 1) then
NOption(299,Node140,4);
NOption(237,Node999,4);
NOption(295,Mich_1a_D1_a,-3);
NOption(296,Mich_1a_D1_b,-3);
NOption(297,Mich_1a_D2,-3);
NOption(262,Node999,-3);
end

// Node Mich_1a_1B
//
// Notes:
//
// Increment Mich_Rude by 1.

procedure Mich_1a_1B
begin
Reply(320);
NOption(321,Mich_1a_2a,4);
BOption(322,Node998,4);
NOption(323,Node999,4);
end

procedure Mich_1a_2a
begin
Reply(350);
NOption(351,Mich_2_1,4);
NOption(352,Mich_1a_2B_1,4);
NOption(353,Node999,4);
end

// Node Mich_1a_2B_1
//
// Notes:
//
// Increment Mich_Rude by 1.

procedure Mich_1a_2B_1
begin
if (dude_is_male) then Reply(380); else
if (dude_is_female) then Reply(381);
NOption(382,Mich_2_1,4);
NOption(383,Mich_1a_2B_2a,4);
if (dude_is_male) then
NOption(384,Mich_1a_2B_2b,4);
if (dude_is_female) then
NOption(385,Mich_1a_2B_2b,4);
NOption(262,Node999,4);
end

// Node Mich_1a_2B_2a
//
// Notes:
//
// Increment Mich_Rude by 1.

procedure Mich_1a_2B_2a
begin
if (dude_is_male) then Reply(410); else
if (dude_is_female) then Reply(409);
NOption(382,Mich_2_1,4);
// NOTE: Increment Mich_Rude by 1.
NOption(411,Mich_2_1,4);
if (dude_is_male) then
NOption(384,Mich_1a_2B_2b,4);
if (dude_is_female) then
NOption(385,Mich_1a_2B_2b,4);
NOption(262,Node999,4);
end

// Node Mich_1a_2B_2b
//
// Notes:
//
// Increment Mich_Rude by 1.

procedure Mich_1a_2B_2b
begin
Reply(440);
NOption(441,Mich_2_1,4);
// NOTE: Increment Mich_Rude by 2.
NOption(442,Node999,4);
end

procedure Mich_1a_D1_a
begin
Reply(470);
NOption(471,Mich_1a_D2,-3);
NOption(296,Mich_1a_D1_b,-3);
NOption(262,Node999,-3);
end

procedure Mich_1a_D1_b
begin
Reply(500);
NOption(471,Mich_1a_D2,-3);
NOption(295,Mich_1a_D1_a,-3);
NOption(262,Node999,-3);
end

procedure Mich_1a_D2
begin
Reply(530);
//NOption(531,Mich_1a_D3,-3);
//NOption(532,Mich_1a_D3,-3);
NOption(262,Node999,-3);
end

procedure Mich_1a_D3
begin
if (dude_is_male) then Reply(560); else
if (dude_is_female) then Reply(561);
// NOTE: This node only appears if the PC has less than maximum hit points.
NOption(562,Mich_2_3b,-3);
// NOTE: This only appears if the PC is radiated.
NOption(563,Mich_2_3c_1a,-3);
NOption(564,Node999,-3);
end

procedure Mich_1b_1
begin
if (dude_is_male) then Reply(590); else
if (dude_is_female) then Reply(591);
//NOption(232,Mich_9,4);
// NOTE: This option only appears IF the PC has a shovel AND Mich_Shovel>0 AND Mich_Cemetary_Bones=0. Also, the variable Mich_Alex_Force must be greater than 0, OR Mich_G_Counter_Return must be greater than 0 AND Mich_Site_Bones_Return must be greater than 2.
//NOption(233,Mich_1b_2a,4);
// NOTE: This node is only visible if the variable Mich_Alex_Force>0 AND Mich_Shovel<1.
//NOption(234,Mich_7_1,4);
/*if (dude_is_male) then
NOption(235,Mich_1b_2B,4);
else
NOption(236,Mich_1b_2B,4);*/
if(map_var(MVAR_DL_MEDICAL_RECORD) == 1 and global_var(GVAR_QUEST_CURE_COMMANDER) == 1) then
NOption(592,Node141,4);
if(map_var(MVAR_KNOW_CAMERA) == 1 and map_var(MVAR_VIDEO_ACCESS) == 0) then
NOption(298,Node139,4);
if(global_var(GVAR_QUEST_CURE_COMMANDER) == 1) then
NOption(299,Node140,4);
NOption(237,Node999,4);
NOption(262,Node999,-3);

end

procedure Mich_1b_2a
begin
Reply(620);
NOption(621,Mich_6_4a_1,4);
NOption(622,Mich_9,4);
NOption(237,Node999,4);
end

// Node Mich_1b_2B
//
// Notes:
//
// Increment Mich_Rude by 1.

procedure Mich_1b_2B
begin
Reply(650);
NOption(651,Mich_9,4);
NOption(323,Node999,4);
end

// Node Mich_2_1
//
// Notes:
//
// The Mich_2_* path is where the PC finds out about Michael's roles in Sandover. See NPC Text for this node.

procedure Mich_2_1
begin
Reply(680);
//NOption(681,Mich_2_2,4);
//NOption(682,Mich_4_1,4);
//NOption(683,Mich_2_3a_2b_2c_1,4);
//NOption(684,Mich_9,4);
NOption(685,Node999,4);
end

procedure Mich_2_2
begin
Reply(710);
NOption(711,Mich_2_3a_1,4);
// NOTE: This node only appears if the PC has less than his maximum hit points.
NOption(712,Mich_2_3b,4);
// NOTE: IF Mich_Rad_Away>0 OR IF Mich_Rude>=3, go to Mich_2_3c_1b instead.
NOption(713,Mich_2_3c_1a,4);
NOption(714,Mich_2_3d_1,4);
NOption(715,Mich_9,4);
end

procedure Mich_2_3a_1
begin
Reply(740);
NOption(741,Mich_2_3a_2a_1,4);
NOption(742,Mich_2_3a_2b_1,4);
NOption(743,Mich_2_3a_2d_1,4);
NOption(744,Mich_2_2,4);
end

procedure Mich_2_3a_2a_1
begin
Reply(770);
NOption(771,Mich_2_3a_2a_2,4);
NOption(772,Mich_2_3a_2b_1,4);
NOption(743,Mich_0,4);
NOption(744,Mich_2_2,4);
end

procedure Mich_2_3a_2a_2
begin
Reply(800);
NOption(801,Mich_2_3a_1,4);
NOption(802,Mich_2_2,4);
NOption(803,Mich_9,4);
NOption(804,Node999,4);
end

procedure Mich_2_3a_2b_1
begin
if (dude_is_male) then Reply(830); else
if (dude_is_female) then Reply(831);
NOption(832,Mich_2_3a_2b_2a_1,4);
NOption(833,Mich_2_3a_2b_2b_1,4);
NOption(834,Mich_2_3a_2b_2c_1,4);
end

procedure Mich_2_3a_2b_2a_1
begin
Reply(860);
NOption(861,Mich_2_3a_2b_2a_2a_1,4);
NOption(862,Mich_2_3a_2b_2a_2b_1,4);
NOption(863,Mich_2_3a_2b_1,4);
NOption(864,Mich_9,4);
end

procedure Mich_2_3a_2b_2a_2a_1
begin
Reply(890);
NOption(891,Mich_2_3a_2b_2a_2a_2,4);
NOption(862,Mich_2_3a_2b_2a_2b_1,4);
NOption(863,Mich_2_3a_2b_1,4);
NOption(864,Mich_9,4);
end

procedure Mich_2_3a_2b_2a_2a_2
begin
Reply(920);
NOption(862,Mich_2_3a_2b_2a_2b_1,4);
NOption(863,Mich_2_3a_2b_1,4);
NOption(864,Mich_9,4);
end

procedure Mich_2_3a_2b_2a_2b_1
begin
Reply(950);
NOption(951,Mich_2_3a_2b_2a_2b_2,4);
NOption(863,Mich_2_3a_2b_1,4);
NOption(864,Mich_9,4);
end

// Node Mich_2_3a_2b_2a_2b_2
//
// Notes:
//
// Add Crossroads to the player's map.

procedure Mich_2_3a_2b_2a_2b_2
begin
Reply(980);
NOption(981,Mich_2_3a_2b_2b_1,4);
NOption(863,Mich_2_3a_2b_1,4);
NOption(864,Mich_9,4);
NOption(982,Node999,4);
end

procedure Mich_2_3a_2b_2b_1
begin
Reply(1010);
NOption(1011,Mich_2_3a_2b_2b_2,4);
NOption(1012,Mich_3_1,4);
NOption(1013,Mich_2_3a_2b_2a_2b_1,4);
NOption(863,Mich_2_3a_2b_1,4);
NOption(1014,Mich_9,4);
end

procedure Mich_2_3a_2b_2b_2
begin
if (dude_is_male) then Reply(1040); else
if (dude_is_female) then Reply(1041);
NOption(1042,Mich_3_1,4);
NOption(1013,Mich_2_3a_2b_2a_2b_1,4);
NOption(863,Mich_2_3a_2b_1,4);
NOption(1014,Mich_9,4);
end

procedure Mich_2_3a_2b_2c_1
begin
if (dude_is_male) then Reply(1070); else
if (dude_is_female) then Reply(1071);
NOption(1072,Mich_2_3a_2b_2c_2a_1,4);
NOption(1073,Mich_2_3a_2b_2c_2b_1,4);
NOption(863,Mich_2_3a_2b_1,4);
NOption(1074,Mich_9,4);
end

procedure Mich_2_3a_2b_2c_2a_1
begin
Reply(1100);
NOption(1101,Mich_2_3a_2b_2c_2a_2,4);
NOption(1073,Mich_2_3a_2b_2c_2b_1,4);
NOption(863,Mich_2_3a_2b_1,4);
NOption(1074,Mich_9,4);
end

procedure Mich_2_3a_2b_2c_2a_2
begin
if (dude_is_male) then Reply(1130); else
if (dude_is_female) then Reply(1131);
NOption(1132,Mich_2_3a_2b_2c_2b_1,4);
NOption(863,Mich_2_3a_2b_1,4);
NOption(1074,Mich_9,4);
end

procedure Mich_2_3a_2b_2c_2b_1
begin
Reply(1160);
NOption(1161,Mich_2_3a_2b_2c_2b_2,4);
NOption(1072,Mich_2_3a_2b_2c_2a_1,4);
NOption(1162,Mich_2_2,4);
NOption(863,Mich_2_3a_2b_1,4);
NOption(1074,Mich_9,4);
end

procedure Mich_2_3a_2b_2c_2b_2
begin
Reply(1190);
NOption(1191,Mich_2_3a_2b_2c_2b_3,4);
NOption(1072,Mich_2_3a_2b_2c_2a_1,4);
NOption(863,Mich_2_3a_2b_1,4);
NOption(1074,Mich_9,4);
end

procedure Mich_2_3a_2b_2c_2b_3
begin
Reply(1220);
NOption(1221,Mich_3_1,4);
NOption(1072,Mich_2_3a_2b_2c_2a_1,4);
NOption(863,Mich_2_3a_2b_1,4);
NOption(1074,Mich_9,4);
end

procedure Mich_2_3a_2c
begin
if (dude_is_male) then Reply(1250); else
if (dude_is_female) then Reply(1251);
NOption(1252,Mich_2_2,4);
NOption(1074,Mich_9,4);
end

// Node Mich_2_3a_2d_1
//
// Notes:
//
// Increment the variable Mich_Rude by 1.

procedure Mich_2_3a_2d_1
begin
Reply(1280);
NOption(1281,Mich_2_3a_2d_2a,4);
NOption(1282,Mich_2_3a_2d_2b,4);
end

procedure Mich_2_3a_2d_2a
begin
Reply(1310);
NOption(1311,Mich_2_3a_1,4);
NOption(1312,Mich_2_1,4);
NOption(1313,Mich_9,4);
NOption(1314,Node999,4);
end

// Node Mich_2_3a_2d_2b
//
// Notes:
//
// Increment the variable Mich_Rude by 1.

procedure Mich_2_3a_2d_2b
begin
if (dude_is_male) then Reply(1340); else
if (dude_is_female) then Reply(1341);
NOption(1342,Mich_2_3a_1,4);
NOption(1343,Mich_2_2,4);
NOption(1344,Mich_9,4);
NOption(1345,Node999,4);
end

procedure Mich_2_3b
begin
if (dude_is_male) then Reply(1370); else
if (dude_is_female) then Reply(1371);
NOption(1372,Mich_2_3b_B,4);
NOption(1373,Mich_2_3a_1,4);
// NOTE: This node only appears
NOption(713,Mich_2_3c_1a,4);
NOption(1374,Mich_9,4);
NOption(1375,Node999,4);
// NOTE: This node only appears if the PC is radiated.
NOption(1376,Mich_2_3c_1a,-3);
NOption(1377,Node999,-3);
end

// Node Mich_2_3b_B
//
// Notes:
//
// Increment Mich_Rude by 1.

procedure Mich_2_3b_B
begin
Reply(1400);
NOption(1373,Mich_2_3a_1,4);
// NOTE: This node only appears
NOption(713,Mich_2_3c_1a,4);
NOption(1374,Mich_9,4);
NOption(1401,Node999,4);
end

procedure Mich_2_3c_1a
begin
Reply(1430);
NOption(1431,Mich_2_3c_2a_1,4);
// NOTE: Dumb option.
NOption(1431,Mich_2_3c_2a_1,-3);
NOption(1432,Mich_2_3c_2b_1,4);
NOption(1433,Mich_2_3c_2b_1,-3);
end

procedure Mich_2_3c_1b_1
begin
if (dude_is_male) then Reply(1460); else
if (dude_is_female) then Reply(1461);
NOption(1462,Mich_2_2,4);
NOption(1463,Mich_2_3c_1b_2a,4);
NOption(1464,Mich_2_3c_1b_2B_1b,4);
NOption(1465,Node999,4);
end

procedure Mich_2_3c_1b_2a
begin
Reply(1490);
NOption(1491,Mich_2_2,4);
NOption(1492,Mich_2_3c_1b_2B_1a,4);
NOption(1464,Mich_2_3c_1b_2B_1b,4);
NOption(1493,Node999,4);
end

procedure Mich_2_3c_1b_2B_1a
begin
Reply(1520);
NOption(1491,Mich_2_2,4);
NOption(1464,Mich_2_3c_1b_2B_1b,4);
NOption(1493,Node999,4);
end

// Node Mich_2_3c_1b_2B_1b
//
// Notes:
//
// Increment Mich_Rude by 5.

procedure Mich_2_3c_1b_2B_1b
begin
Reply(1550);
BOption(1551,Node998,4);
NOption(1552,Mich_2_3c_1b_2B_2,4);
NOption(1553,Node999,4);
end

procedure Mich_2_3c_1b_2B_2
begin
Reply(1580);
NOption(1581,Mich_2_3c_1b_2B_3,4);
NOption(262,Node999,4);
end

procedure Mich_2_3c_1b_2B_3
begin
Reply(1610);
BOption(1611,Node998,4);
end

// Node Mich_2_3c_2a_1
//
// Notes:
//
// Increment Mich_Rad_Away by 1. Deduct an amount from the player's radiation level equal to a normal dose of Rad-Away.

procedure Mich_2_3c_2a_1
begin
Reply(1640);
NOption(1641,Mich_2_3c_2a_2a_1,4);
NOption(1642,Mich_9,4);
NOption(1643,Node999,4);
// NOTE: This node only appears if the PC has less than maximum health points.
NOption(1644,Mich_2_3b,-3);
NOption(1645,Node999,-3);
end

procedure Mich_2_3c_2a_2a_1
begin
Reply(1670);
NOption(1671,Mich_2_3c_2a_2a_2a,4);
if (get_critter_stat(dude_obj,STAT_pe)>6) then
NOption(1672,Mich_2_3c_2a_2a_2b_1,4);
NOption(1673,Node999,4);
end

procedure Mich_2_3c_2a_2a_2a
begin
Reply(1700);
NOption(1701,Mich_2_2,4);
if (get_critter_stat(dude_obj,STAT_pe)>6) then
NOption(1702,Mich_0,4);
end

procedure Mich_2_3c_2a_2a_2b_1
begin
Reply(1730);
NOption(1731,Mich_2_2,4);
// NOTE: Note intelligence check.
NOption(1732,Mich_2_3c_2a_2a_2b_2,7);
NOption(1673,Node999,4);
end

procedure Mich_2_3c_2a_2a_2b_2
begin
Reply(1760);
NOption(1761,Mich_3_1,4);
NOption(1762,Mich_2_2,4);
end

procedure Mich_2_3c_2b_1
begin
Reply(1790);
NOption(1431,Mich_2_3c_2a_1,4);
// NOTE: Dumb option.
NOption(1431,Mich_2_3c_2a_1,-3);
NOption(1791,Mich_2_3c_2b_2,4);
NOption(1792,Mich_2_3c_2b_2,-3);
end

procedure Mich_2_3c_2b_2
begin
if (dude_is_male) then Reply(1820); else
if (dude_is_female) then Reply(1821);
NOption(1431,Mich_2_3c_2a_1,4);
// NOTE: Dumb option.
NOption(1431,Mich_2_3c_2a_1,-3);
NOption(1822,Mich_2_3c_2b_3,4);
NOption(1823,Mich_2_3c_2b_3,-3);
end

procedure Mich_2_3c_2b_3
begin
Reply(1850);
NOption(1431,Mich_2_3c_2a_1,4);
// NOTE: Dumb option.
NOption(1431,Mich_2_3c_2a_1,-3);
BOption(1851,Node998,4);
BOption(1852,Node998,-3);
end

procedure Mich_2_3d_1
begin
Reply(1880);
NOption(1881,Mich_2_3d_2a,4);
// NOTE: This node only appears if the player has accepted the bones quest from Bruce, the Wasteland Explorer AND the variable Mich_Bones_Know=0.
NOption(1882,Mich_2_3d_2b_1,4);
NOption(1883,Mich_2_2,4);
NOption(715,Mich_9,4);
end

procedure Mich_2_3d_2a
begin
Reply(1910);
// NOTE: This node only appears if the player has accepted the bones quest from Bruce, the Wasteland Explorer AND the variable Mich_Bones_Know=0.
NOption(1882,Mich_2_3d_2b_1,4);
NOption(1883,Mich_2_2,4);
NOption(715,Mich_9,4);
end

procedure Mich_2_3d_2b_1
begin
Reply(1940);
// NOTE: This node only appears if the player has accepted the bones quest from Bruce, the Wasteland Explorer.
NOption(1941,Mich_2_3d_2b_2,4);
NOption(1942,Mich_2_3d_2a,4);
NOption(1883,Mich_2_2,4);
NOption(715,Mich_9,4);
end

procedure Mich_2_3d_2b_2
begin
Reply(1970);
// NOTE: This node only appears if the player has accepted the bones quest from Bruce, the Wasteland Explorer.
NOption(1971,Mich_5_3,4);
NOption(1883,Mich_2_2,4);
NOption(1972,Mich_9,4);
end

// Node Mich_3_1
//
// Notes:
//
// The Mich_3_* path is where the PC finds out for the first time about Michael's past with the Wasteland Explorers and the disasterous Sandover expedition. This is for players who meet Michael before Bruce, the Wasteland Explorer, in Crossroads.

procedure Mich_3_1
begin
Reply(2000);
NOption(2001,Mich_3_2,4);
// NOTE: This node only appears IF the PC has met Bruce, the Explorer Representitive, OR Miranda, his wife.
NOption(2002,Mich_5_1,4);
NOption(2003,Mich_2_3a_2b_1,4);
NOption(1014,Mich_9,4);
end

procedure Mich_3_2
begin
Reply(2030);
NOption(2031,Mich_3_3a,4);
NOption(2032,Mich_3_3b_1,4);
// NOTE: This node only appears IF the PC has met Bruce, the Explorer Representitive, OR Miranda, his wife.
NOption(2002,Mich_5_1,4);
NOption(2003,Mich_2_3a_2b_1,4);
NOption(1014,Mich_9,4);
end

procedure Mich_3_3a
begin
Reply(2060);
NOption(2061,Mich_3_3b_1,4);
NOption(2062,Mich_3_4_1,4);
// NOTE: This node only appears IF the PC has met Bruce, the Explorer Representitive, OR Miranda, his wife.
NOption(2002,Mich_5_1,4);
NOption(2003,Mich_2_3a_2b_1,4);
NOption(1014,Mich_9,4);
end

procedure Mich_3_3b_1
begin
Reply(2090);
NOption(2091,Mich_0,4);
// NOTE: This node only appears IF the PC has met Bruce, the Explorer Representitive, OR Miranda, his wife.
NOption(2002,Mich_5_1,4);
NOption(2003,Mich_2_3a_2b_1,4);
NOption(1014,Mich_9,4);
end

procedure Mich_3_4_1
begin
Reply(2120);
// NOTE: If Mich_Danger_Site>0, then this node will not appear.
//Outdoorsman check. IF failed, go to instead to Mich_3_4_2b.
NOption(2121,Mich_3_4_2a,4);
// NOTE: If Mich_Danger_Site>0, then this node will not appear.
//Difficult speech check. IF failed, go to instead to Mich_3_4_2d.
NOption(2122,Mich_3_4_2c,4);
NOption(2003,Mich_2_3a_2b_1,4);
NOption(1014,Mich_9,4);
end

// Node Mich_3_4_2a
//
// Notes:
//
// Increment Mich_Danger_Site by 1.

procedure Mich_3_4_2a
begin
Reply(2150);
NOption(2151,Mich_3_4_3,4);
end

// Node Mich_3_4_2b
//
// Notes:
//
// Increment Mich_Danger_Site by 1.

procedure Mich_3_4_2b
begin
if (dude_is_male) then Reply(2180); else
if (dude_is_female) then Reply(2181);
// NOTE: Difficult speech check. IF failed, go to instead to Mich_3_4_2d.
NOption(2122,Mich_3_4_2c,4);
NOption(2003,Mich_2_3a_2b_1,4);
NOption(1014,Mich_9,4);
NOption(2182,Node999,4);
end

// Node Mich_3_4_2c
//
// Notes:
//
// Increment Mich_Danger_Site by 1.

procedure Mich_3_4_2c
begin
Reply(2210);
NOption(2211,Mich_3_4_3,4);
NOption(2212,Mich_9,4);
NOption(2213,Mich_2_3a_2b_1,4);
end

// Node Mich_3_4_2d
//
// Notes:
//
// Increment Mich_Danger_Site by 1.

procedure Mich_3_4_2d
begin
if (dude_is_male) then Reply(2240); else
if (dude_is_female) then Reply(2241);
NOption(2003,Mich_2_3a_2b_1,4);
NOption(1014,Mich_9,4);
NOption(2182,Node999,4);
end

// Node Mich_3_4_3
//
// Notes:
//
// Add the location of the extremely high radiation site near Sandover, where three of the five sets of bones can be found. Increment the variable Mich_Danger_Site by 1.

procedure Mich_3_4_3
begin
Reply(2270);
NOption(2271,Mich_2_3a_2b_1,4);
NOption(2272,Mich_9,4);
NOption(2273,Node999,4);
end

// Node Mich_4_1
//
// Notes:
//
// The Mich_4_* path comes from the main question node, Mich_9. It answers the PC's question, "Have you lived in Sandover all your life?"

procedure Mich_4_1
begin
Reply(2300);
NOption(2301,Mich_2_1,4);
NOption(2302,Mich_4_2,4);
NOption(683,Mich_2_3a_2b_2c_1,4);
NOption(2303,Mich_9,4);
end

procedure Mich_4_2
begin
Reply(2330);
NOption(981,Mich_2_3a_2b_2b_1,4);
NOption(2331,Mich_2_3a_2b_2a_1,4);
NOption(683,Mich_2_3a_2b_2c_1,4);
NOption(2301,Mich_2_1,4);
NOption(2303,Mich_9,4);
end

// Node Mich_5_1
//
// Notes:
//
// The Mich_5_* path is where the PC learns that Michael is one of the Wasteland Explorers Bruce thinks died during the Sandover expedition. The PC also finds out that three of the bones sets are still at the expedition site and that Michael knows where the other two are. Michael demands that the PC finds the three bones sets and counter before showing him the last two sets (at the cemetary).

procedure Mich_5_1
begin
Reply(2360);
NOption(2361,Mich_5_2a,4);
NOption(2362,Mich_5_2b,4);
NOption(2363,Mich_9,4);
NOption(2364,Node999,4);
end

procedure Mich_5_2a
begin
Reply(2390);
// NOTE: This node only appears if the PC has accepted the bones quest from Bruce, the Explorer Representitive.
NOption(2391,Mich_5_3,4);
NOption(2331,Mich_2_3a_2b_2a_1,4);
NOption(2392,Mich_9,4);
NOption(2364,Node999,4);
end

procedure Mich_5_2b
begin
Reply(2420);
NOption(2421,Mich_5_2a,4);
NOption(2363,Mich_9,4);
NOption(2364,Node999,4);
end

// Node Mich_5_3
//
// Notes:
//
// Make the variable Mich_Bones_Know=1

procedure Mich_5_3
begin
Reply(2450);
NOption(2451,Mich_5_4,4);
NOption(2452,Mich_9,4);
NOption(2453,Node999,4);
end

procedure Mich_5_4
begin
Reply(2480);
NOption(2481,Mich_5_5,4);
NOption(2452,Mich_9,4);
NOption(2453,Node999,4);
end

procedure Mich_5_5
begin
Reply(2510);
NOption(2511,Mich_5_6c_1,4);
NOption(2512,Mich_5_6a_1,4);
NOption(2513,Mich_5_6b_1,4);
NOption(2452,Mich_9,4);
NOption(2453,Node999,4);
end

procedure Mich_5_6a_1
begin
Reply(2540);
NOption(2541,Mich_5_6a_2,4);
NOption(2542,Mich_5_7_B_1,4);
NOption(2452,Mich_9,4);
NOption(2543,Node999,4);
end

procedure Mich_5_6a_2
begin
if (dude_is_male) then Reply(2570); else
if (dude_is_female) then Reply(2571);
NOption(2572,Mich_5_7_1,4);
NOption(2573,Mich_5_7_B_1,4);
NOption(2452,Mich_9,4);
NOption(2574,Node999,4);
end

procedure Mich_5_6b_1
begin
Reply(2600);
NOption(2601,Mich_5_6b_2,4);
NOption(2452,Mich_9,4);
NOption(2453,Node999,4);
end

procedure Mich_5_6b_2
begin
Reply(2630);
NOption(2631,Mich_5_6a_2,4);
NOption(2632,Mich_5_6b_3,4);
NOption(2452,Mich_9,4);
NOption(2364,Node999,4);
end

procedure Mich_5_6b_3
begin
Reply(2660);
NOption(2661,Mich_5_6a_2,4);
NOption(2662,Mich_5_7_B_1,4);
NOption(2452,Mich_9,4);
NOption(2453,Node999,4);
end

procedure Mich_5_6c_1
begin
Reply(2690);
NOption(2691,Mich_5_6c_2,4);
NOption(2692,Mich_5_6b_2,4);
NOption(2452,Mich_9,4);
NOption(262,Node999,4);
end

// Node Mich_5_6c_2
//
// Notes:
//
// This ends the bones quest early without resolution. The player option in the node Mich_5_2a which reads, "He would like the bodies of the people he lost during the Sandover expedition brought back to Crossroads for burial." will no longer appear.

procedure Mich_5_6c_2
begin
Reply(2720);
NOption(2721,Mich_9,4);
NOption(2722,Node999,4);
end

procedure Mich_5_7_1
begin
Reply(2750);
NOption(2751,Mich_5_7_2,4);
NOption(2452,Mich_9,4);
NOption(2574,Node999,4);
end

procedure Mich_5_7_2
begin
Reply(2780);
NOption(2781,Mich_5_7_3a,4);
NOption(2782,Mich_5_7_3b,4);
NOption(2452,Mich_9,4);
NOption(2574,Node999,4);
end

procedure Mich_5_7_3a
begin
Reply(2810);
NOption(2811,Mich_5_7_3b,4);
NOption(2452,Mich_9,4);
NOption(2812,Node999,4);
end

procedure Mich_5_7_3b
begin
Reply(2840);
NOption(2841,Mich_5_7_4a_1,4);
NOption(2842,Mich_5_7_4b_1,4);
// NOTE: IF the variable Mich_Guilt_Trip>0 (which means that the PC has already tried the guilt trip and failed), then go to Mich_B_0 instead.
if (get_critter_stat(dude_obj,STAT_iq)>=6) then
NOption(2843,Mich_B_1,4);
NOption(2844,Mich_9,4);
end

procedure Mich_5_7_4a_1
begin
Reply(2870);
// NOTE: IF Mich_Danger_Site >= 1 then go to Mich_5_7_4a_2b instead.
NOption(2871,Mich_5_7_4a_2a,4);
NOption(2844,Mich_9,4);
NOption(2872,Node999,4);
end

// Node Mich_5_7_4a_2a
//
// Notes:
//
// Add the location of the extremely high rad site to the PC's worldmap. Increment the variable Mich_Danger_Site by 1.

procedure Mich_5_7_4a_2a
begin
Reply(2900);
NOption(2901,Mich_9,4);
NOption(2902,Node999,4);
end

// Node Mich_5_7_4a_2b
//
// Notes:
//
// I'll be back when I've found the bones and your geiger counter. Goodbye.

procedure Mich_5_7_4a_2b
begin
if (dude_is_male) then Reply(2930); else
if (dude_is_female) then Reply(2931);
NOption(2844,Mich_9,4);
NOption(2932,Node999,4);
end

procedure Mich_5_7_4b_1
begin
Reply(2960);
NOption(2961,Mich_5_7_4a_1,4);
NOption(2962,Mich_5_7_4b_2,4);
NOption(2963,Mich_5_7_4b_2b_1,4);
// NOTE: IF the variable Mich_Guilt_Trip>0 (which means that the PC has already tried the guilt trip and failed), then go to Mich_B_0 instead.
NOption(2964,Mich_B_1,4);
NOption(2844,Mich_9,4);
end

procedure Mich_5_7_4b_2
begin
Reply(2990);
NOption(2961,Mich_5_7_4a_1,4);
NOption(2963,Mich_5_7_4b_2b_1,4);
// NOTE: IF the variable Mich_Guilt_Trip>0 (which means that the PC has already tried the guilt trip and failed), then go to Mich_B_0 instead.
NOption(2991,Mich_B_2,4);
NOption(2844,Mich_9,4);
end

procedure Mich_5_7_4b_2b_1
begin
Reply(3020);
NOption(2961,Mich_5_7_4a_1,4);
NOption(3021,Mich_5_7_4b_2,4);
NOption(3022,Mich_5_7_4b_2b_2,4);
// NOTE: IF the variable Mich_Guilt_Trip>0 (which means that the PC has already tried the guilt trip and failed), then go to Mich_B_0 instead.
NOption(2964,Mich_B_1,4);
NOption(2844,Mich_9,4);
end

procedure Mich_5_7_4b_2b_2
begin
Reply(3050);
NOption(2961,Mich_5_7_4a_1,4);
NOption(3051,Mich_5_7_4b_2,4);
// NOTE: IF the variable Mich_Guilt_Trip>0 (which means that the PC has already tried the guilt trip and failed), then go to Mich_B_0 instead.
NOption(2964,Mich_B_1,4);
NOption(2844,Mich_9,4);
end

// Node Mich_5_7_B_1
//
// Notes:
//
// Make the variable Mich_Rude=1

procedure Mich_5_7_B_1
begin
Reply(3080);
NOption(3081,Mich_5_7_B_2,4);
BOption(3082,Node998,4);
end

procedure Mich_5_7_B_2
begin
Reply(3110);
NOption(3111,Mich_5_7_B_1,4);
NOption(3112,Mich_9,4);
NOption(3113,Node999,4);
end

// Node Mich_6_1
//
// Notes:
//
// The Mich_6_* path is where the PC brings the bones and/or geiger counter from the Sandover expedition site to show to Michael so that the Priest will let the PC dig up the bones at Sandover's cemetary.

procedure Mich_6_1
begin
if (dude_is_male) then Reply(3140); else
if (dude_is_female) then Reply(3141);
// NOTE: This node only appears if the PC has found the geiger counter marked with the initials M.S. AND Mich_G_Counter_Return=0.
NOption(3142,Mich_6_2a,4);
// NOTE: This node only appears if the PC has found at least one set of the Explorers' bones at the high-rad expedition site. Perhaps we need a different variable for each set of bones at the expedition site, so the script knows which set of bones has been checked by Michael or not.
NOption(3143,Mich_6_2b,4);
NOption(3144,Mich_5_7_4a_2a,4);
NOption(3145,Mich_9,4);
end

// Node Mich_6_2a
//
// Notes:
//
// Increment Mich_G_Counter_Return by 1.

procedure Mich_6_2a
begin
if (dude_is_male) then Reply(3170); else
if (dude_is_female) then Reply(3171);
// NOTE: This node only appears IF Mich_G_Counter_Return>=1 AND Mich_Site_Bones_Return=3.
NOption(3172,Mich_6_3,4);
// NOTE: This node only appears if the PC has found at least one set of the Explorers' bones at the high-rad expedition site. Perhaps we need a different variable for each set of bones at the expedition site, so the script knows which set of bones has been checked by Michael or not.
NOption(3143,Mich_6_2b,4);
NOption(3145,Mich_9,4);
end

// Node Mich_6_2b
//
// Notes:
//
// Increment Mich_Site_Bones_Return by 1 for each new set of bones the PC shows to Michael.

procedure Mich_6_2b
begin
Reply(3200);
// NOTE: This node only appears IF Mich_G_Counter_Return>=1 AND Mich_Site_Bones_Return=3.
NOption(3172,Mich_6_3,4);
// NOTE: This node only appears if the PC has found the geiger counter marked with the initials M.S. AND Mich_G_Counter_Return=0.
NOption(3201,Mich_6_2a,4);
NOption(1972,Mich_9,4);
NOption(2273,Node999,4);
end

procedure Mich_6_3
begin
Reply(3230);
// NOTE: This node only appears IF the PC has a shovel in his inventory.
NOption(3231,Mich_6_4a_1,4);
// NOTE: This node only appears IF the PC does not have a shovel in his inventory.
NOption(3232,Mich_6_4b,4);
NOption(3233,Mich_9,4);
NOption(3234,Node999,4);
end

procedure Mich_6_4a_1
begin
Reply(3260);
// NOTE: The screen fades to black; a few hours pass; screen fades back; PC has all the bones.
NOption(2631,Mich_6_4a_2,4);
end

// Node Mich_6_4a_2
//
// Notes:
//
// Decrement Mich_Rude by 2. Make Mich_Shovel=0. Make Mich_Alex_Force=0. Increment Mich_Cemetary_Bones by 2. Put the bones of the two Explorers buried in the Sandover cemetary in the PC's inventory.

procedure Mich_6_4a_2
begin
Reply(3290);
NOption(3291,Mich_6_4a_3,4);
NOption(3292,Node999,4);
NOption(3293,Mich_9,4);
end

procedure Mich_6_4a_3
begin
Reply(3320);
NOption(3321,Mich_6_4a_4b,4);
if (has_skill(dude_obj,SKILL_OUTDOORSMAN)>=50) then
NOption(3322,Mich_6_4a_4a,4);
NOption(3323,Mich_9,4);
NOption(3324,Node999,4);
end

procedure Mich_6_4a_4a
begin
Reply(3350);
NOption(3351,Mich_6_4a_4b,4);
NOption(3293,Mich_9,4);
NOption(3352,Node999,4);
end

// Node Mich_6_4a_4b
//
// Notes:
//
// Maybe some sort of tiny health boost at this point because of the drink?

procedure Mich_6_4a_4b
begin
if (dude_is_male) then Reply(3380); else
if (dude_is_female) then Reply(3381);
// NOTE: This option only appears if the variable Mich_Site_Bones_Return=3 AND Mich_Cemetary_Bones=2.
//IF Mich_G_Counter_Return<=0, go to Mich_8b_1 instead.
NOption(3382,Mich_8a_1,4);
NOption(3383,Mich_9,4);
NOption(3384,Node999,4);
end

// Node Mich_6_4b
//
// Notes:
//
// Increment Mich_Shovel by 1.

procedure Mich_6_4b
begin
Reply(3410);
NOption(3411,Mich_9,4);
NOption(3412,Node999,4);
NOption(3413,Node999,4);
end

// Node Mich_7_1
//
// Notes:
//
// The Mich_7_* path is for the condition of the bones quest where the PC has convinced the Scab leader, Alexander, to overrule Michael. This allows the PC to force Michael to take him to the two sets of bones buried in Sandover's cemetary.

procedure Mich_7_1
begin
Reply(3440);
NOption(3441,Mich_7_2,4);
end

procedure Mich_7_2
begin
Reply(3470);
// NOTE: Fade the screen to black and back again to simulate the time it takes for Michael to go to Alexander to confirm his overruling and come back again. If possible, make five minutes pass.
NOption(3471,Mich_7_3,4);
// NOTE: Fade the screen to black and back again to simulate the time it takes for Michael to go to Alexander to confirm his overruling and come back again. If possible, make five minutes pass.
NOption(3472,Mich_7_3,4);
end

procedure Mich_7_3
begin
Reply(3500);
// NOTE: This node only appears if the PC has a shovel in his inventory.
NOption(3501,Mich_6_4a_1,4);
NOption(3232,Mich_6_4b,4);
end

// Node Mich_8a_1
//
// Notes:
//
// The Mich_8_* path is where the PC can invite Michael back to Crossroads in order to preside over the burial of the five dead Explorers. The PC needs to have found and returned the geiger counter to Michael, as well as gathered the five bones set in order to do this.

procedure Mich_8a_1
begin
if (dude_is_male) then Reply(3530); else
if (dude_is_female) then Reply(3531);
NOption(2631,Mich_8a_2,4);
end

procedure Mich_8a_2
begin
Reply(3560);
NOption(3561,Mich_8a_3,4);
end

procedure Mich_8a_3
begin
Reply(3590);
NOption(3591,Mich_8a_4,4);
end

procedure Mich_8a_4
begin
Reply(3620);
NOption(3621,Node999,4);
NOption(3622,Node999,4);
end

procedure Mich_8b_1
begin
Reply(3650);
NOption(3651,Mich_8b_2,4);
NOption(3652,Mich_9,4);
NOption(3653,Node999,4);
end

procedure Mich_8b_2
begin
Reply(3680);
NOption(3681,Mich_8b_3,4);
NOption(3682,Mich_B_1,4);
NOption(3653,Node999,4);
end

procedure Mich_8b_3
begin
Reply(3710);
NOption(3711,Mich_0,4);
NOption(3712,Mich_9,4);
NOption(3713,Node999,4);
end

procedure Mich_9
begin
Reply(3740);
NOption(2301,Mich_2_1,4);
NOption(682,Mich_4_1,4);
NOption(683,Mich_2_3a_2b_2c_1,4);
// NOTE: This node is only visible if the variable Mich_Alex_Force>0 AND Mich_Shovel<1.
NOption(3741,Mich_7_1,4);
// NOTE: This option only appears IF the PC has a shovel AND Mich_Shovel>0 AND Mich_Cemetary_Bones=0. Also, the variable Mich_Alex_Force must be greater than 0, OR Mich_G_Counter_Return must be greater than 0 AND Mich_Site_Bones_Return must be greater than 2.
NOption(3742,Mich_6_4a_1,4);
// NOTE: This option only appears if the variable Mich_Site_Bones_Return=3 AND Mich_Cemetary_Bones=2 AND the ceremony where the Explorers have buried their dead has NOT already happened.
//IF Mich_G_Counter_Return<=0, go to Mich_8b_1 instead.
NOption(3382,Mich_8a_1,4);
NOption(3743,Node999,4);
end

// Node Mich_B_0
//
// Notes:
//
// The Mich_B_* path is where an evil PC can convince Michael to kill himself because of his part in the Sandover expedition disaster!\

procedure Mich_B_0
begin
Reply(3770);
NOption(2961,Mich_5_7_4a_1,4);
NOption(3771,Mich_5_7_4b_1,4);
NOption(3772,Mich_9,4);
NOption(323,Node999,4);
end

// Node Mich_B_1
//
// Notes:
//
// The Mich_B_* path is where an evil PC can convince Michael to kill himself because of his part in the Sandover expedition disaster!

procedure Mich_B_1
begin
Reply(3800);
NOption(3801,Mich_B_2,4);
NOption(2961,Mich_5_7_4a_1,4);
NOption(3771,Mich_5_7_4b_1,4);
NOption(1972,Mich_9,4);
NOption(323,Node999,4);
end

// Node Mich_B_2
//
// Notes:
//
// Increment the variables Mich_Guilt_Trip and Mich_Rude by 1.

procedure Mich_B_2
begin
Reply(3830);
// NOTE: Wrong response for the suicide condition. The weaker of the two guilt trips. It gives Michael the chance to justify himself. Penalty is another node with a speech check to go through.
//Moderate speech check. If failed, go to Mich_B_9_1 instead.
NOption(3831,Mich_B_3a_1,4);
// NOTE: Correct response for the suicide condition. Straight for the jugular.
//Moderate speech check. If failed, go to Mich_B_9_1 instead.
NOption(3832,Mich_B_3b,4);
NOption(3833,Mich_5_7_4a_1,4);
NOption(3771,Mich_5_7_4b_1,4);
NOption(3834,Mich_9,4);
NOption(323,Node999,4);
end

// Node Mich_B_3a_1
//
// Notes:
//
// Increment the variable Mich_Rude by 1.

procedure Mich_B_3a_1
begin
Reply(3860);
// NOTE: Moderate speech check. If failed, go to Mich_B_9_1 instead.
if (dude_is_male) then
NOption(3861,Mich_B_3a_2,4);
// NOTE: Moderate speech check. If failed, go to Mich_B_9_1 instead.
if (dude_is_female) then
NOption(3862,Mich_B_3a_2,4);
NOption(3833,Mich_5_7_4a_1,4);
NOption(3771,Mich_5_7_4b_1,4);
NOption(3834,Mich_9,4);
NOption(323,Node999,4);
end

// Node Mich_B_3a_2
//
// Notes:
//
// Increment the variable Mich_Guilt_Trip by 1.

procedure Mich_B_3a_2
begin
Reply(3890);
// NOTE: Correct response. Hits the heart of the matter. Sandover is Michael's means of atonement.
//Moderate speech check. If failed, go to Mich_B_9_1 instead.
NOption(3891,Mich_B_4a_1,4);
// NOTE: Wrong response. Changes the subject slightly. Sandover is Michael's means of atonement, not the Explorers.
//Difficult speech check. If failed, go to Mich_B_9_1 instead.
NOption(3892,Mich_B_4b_1,4);
NOption(3833,Mich_5_7_4a_1,4);
NOption(3771,Mich_5_7_4b_1,4);
NOption(3834,Mich_9,4);
NOption(323,Node999,4);
end

// Node Mich_B_3b
//
// Notes:
//
// Increment the variable Mich_Rude by 1.

procedure Mich_B_3b
begin
Reply(3920);
// NOTE: Correct response. Hits the heart of the matter. Sandover is Michael's means of atonement.
//Moderate speech check. If failed, go to Mich_B_9_1 instead.
NOption(3921,Mich_B_4a_1,4);
// NOTE: Wrong response. Changes the subject slightly. Sandover is Michael's means of atonement, not the Explorers.
//Difficult speech check. If failed, go to Mich_B_9_1 instead.
NOption(3922,Mich_B_4b_1,4);
NOption(3923,Mich_5_7_4a_1,4);
NOption(3771,Mich_5_7_4b_1,4);
NOption(3834,Mich_9,4);
NOption(323,Node999,4);
end

// Node Mich_B_4a_1
//
// Notes:
//
// Increment the variable Mich_Rude by 1.

procedure Mich_B_4a_1
begin
Reply(3950);
// NOTE: Although Mich_4a_* is the longer of the two parallel paths, it is the easier. It hits the heart of the matter; Sandover is Michael's means of atonement.
//Easy speech check. If failed, go to Mich_B_9_1 instead.
NOption(3951,Mich_B_4a_2,4);
// NOTE: Wrong response. Changes the subject slightly. Sandover is Michael's means of atonement, not the Explorers.
//Difficult speech check. If failed, go to Mich_B_9_1 instead.
NOption(3892,Mich_B_4b_1,4);
NOption(3834,Mich_9,4);
NOption(323,Node999,4);
end

// Node Mich_B_4a_2
//
// Notes:
//
// Increment the variable Mich_Rude by 1.

procedure Mich_B_4a_2
begin
Reply(3980);
// NOTE: Although Mich_4a_* is the longer of the two parallel paths, it is the easier. It hits the heart of the matter; Sandover is Michael's means of atonement.
//Easy speech check. If failed, go to Mich_B_9_1 instead.
NOption(3981,Mich_B_4a_3,4);
// NOTE: Wrong response. Changes the subject slightly. Sandover is Michael's means of atonement, not the Explorers.
//Difficult speech check. If failed, go to Mich_B_9_1 instead.
NOption(3892,Mich_B_4b_1,4);
NOption(3834,Mich_9,4);
NOption(323,Node999,4);
end

// Node Mich_B_4a_3
//
// Notes:
//
// Increment the variable Mich_Rude by 1.

procedure Mich_B_4a_3
begin
Reply(4010);
// NOTE: Although Mich_4a_* is the longer of the two parallel paths, it is the easier to complete. It hits the heart of the matter; Sandover is Michael's means of atonement.
//Moderate speech check. If failed, go to Mich_B_9_1 instead.
NOption(4011,Mich_B_4a_4,4);
// NOTE: Wrong response. Changes the subject slightly. Sandover is Michael's means of atonement, not the Explorers.
//Difficult speech check. If failed, go to Mich_B_9_1 instead.
NOption(3892,Mich_B_4b_1,4);
NOption(3834,Mich_9,4);
NOption(323,Node999,4);
end

// Node Mich_B_4a_4
//
// Notes:
//
// Increment the variable Mich_Rude by 1.

procedure Mich_B_4a_4
begin
Reply(4040);
// NOTE: Increment the variable Mich_Guilt_Trip by 1.
//Although Mich_4a_* is the longer of the two parallel paths, it is the easier to complete. It hits the heart of the matter; Sandover is Michael's means of atonement.
//Moderate speech check. If failed, go to Mich_B_9_1 instead.
NOption(4041,Mich_B_5_1,4);
// NOTE: Increment the variable Mich_Guilt_Trip by 1.
//Although Mich_4a_* is the longer of the two parallel paths, it is the easier to complete. It hits the heart of the matter; Sandover is Michael's means of atonement.
//Moderate speech check. If failed, go to Mich_B_9_1 instead.
NOption(4042,Mich_B_4a_5,4);
// NOTE: Wrong response. Changes the subject slightly. Sandover is Michael's means of atonement, not the Explorers.
//Difficult speech check. If failed, go to Mich_B_9_1 instead.
NOption(3892,Mich_B_4b_1,4);
NOption(3834,Mich_9,4);
NOption(323,Node999,4);
end

// Node Mich_B_4a_5
//
// Notes:
//
// Increment the variable Mich_Rude by 1.

procedure Mich_B_4a_5
begin
Reply(4070);
// NOTE: Increment the variable Mich_Guilt_Trip by 1.
//Although Mich_4a_* is the longer of the two parallel paths, it is the easier to complete. It hits the heart of the matter; Sandover is Michael's means of atonement.
//Moderate speech check. If failed, go to Mich_B_9_1 instead.
NOption(4041,Mich_B_5_1,4);
// NOTE: Increment the variable Mich_Guilt_Trip by 1.
//Although Mich_4a_* is the longer of the two parallel paths, it is the easier to complete. It hits the heart of the matter; Sandover is Michael's means of atonement.
//Moderate speech check. If failed, go to Mich_B_9_1 instead.
NOption(4071,Mich_B_5_2,4);
// NOTE: Wrong response. Changes the subject slightly. Sandover is Michael's means of atonement, not the Explorers.
//Difficult speech check. If failed, go to Mich_B_9_1 instead.
NOption(3892,Mich_B_4b_1,4);
NOption(3834,Mich_9,4);
NOption(323,Node999,4);
end

// Node Mich_B_4b_1
//
// Notes:
//
// Increment the variable Mich_Rude by 1.

procedure Mich_B_4b_1
begin
Reply(4100);
// NOTE: Mich_B_4b_* is a much shorter but much more difficult path to complete. It doesn't really have any attack other than insults.
//Very difficult speech check. If failed, Go to Mich_B_9_1 instead.
NOption(4101,Mich_B_4b_2,4);
// NOTE: Leads onto the easier path Mich_B_4a_*. Hits the heart of the matter. Sandover is Michael's means of atonement.
//Moderate speech check. If failed, go to Mich_B_9_1 instead.
NOption(3921,Mich_B_4a_1,4);
NOption(3834,Mich_9,4);
NOption(323,Node999,4);
end

// Node Mich_B_4b_2
//
// Notes:
//
// Increment the variable Mich_Rude by 1.

procedure Mich_B_4b_2
begin
Reply(4130);
// NOTE: Increment the variable Mich_Guilt_Trip by 1.
//Mich_B_4b_* is a much shorter but much more difficult path to complete. It doesn't really have any attack other than insults.
//Very difficult speech check. If failed, Go to Mich_B_9_1 instead.
NOption(4131,Mich_B_5_1,4);
// NOTE: Leads onto the easier path Mich_B_4a_*. Hits the heart of the matter. Sandover is Michael's means of atonement.
//Moderate speech check. If failed, go to Mich_B_9_1 instead.
NOption(3921,Mich_B_4a_1,4);
NOption(3834,Mich_9,4);
NOption(323,Node999,4);
end

procedure Mich_B_5_1
begin
Reply(4160);
// NOTE: Increment the variable Mich_Guilt_Trip by 1.
//Moderate speech check. If failed, go to Mich_B_9_1 instead.
NOption(4161,Mich_B_5_2,4);
NOption(4162,Node999,4);
end

procedure Mich_B_5_2
begin
Reply(4190);
NOption(2631,Mich_B_5_3,4);
NOption(323,Node999,4);
end

// Node Mich_B_5_3
//
// Notes:
//
// When the dialogue ends, Michael will run to the Sandover expedition site and allow the super-high rads to kill him. If the PC ever visits the area, he will see Michael's robed body lying there.

procedure Mich_B_5_3
begin
Reply(4220);
NOption(4221,Mich_B_5_4,4);
NOption(323,Node999,4);
end

procedure Mich_B_5_4
begin
Reply(4250);
BOption(4251,Node998,4);
BOption(4252,Node998,4);
end

procedure Mich_B_9_1
begin
Reply(4280);
NOption(4281,Mich_9,4);
BOption(4282,Node998,4);
NOption(323,Node999,4);
end

// Node Mich_B_9_2
//
// Notes:
//
// Increment the variables Mich_Guilt_Trip and Mich_Rude by 1.

procedure Mich_B_9_2
begin
Reply(4310);
BOption(4311,Node998,4);
NOption(323,Node999,4);
end

procedure Node139
begin
   set_map_var(MVAR_VIDEO_ACCESS, 1);
Reply(4340);
NOption(4341,Node999,4);
end

procedure Node140
begin
Reply(4370);
NOption(4371,Node999,4);
if(map_var(MVAR_DL_MEDICAL_RECORD) == 1) then
NOption(4372,Node141,4);
end

procedure Node141
begin
Reply(4400);
NOption(4401,Node142,4);
end

procedure Node142
begin
   give_xp(1000);
   set_global_var(GVAR_QUEST_CURE_COMMANDER, 2);
   fadeout(1);
   game_time_advance(random(1,2) * ONE_GAME_HOUR);
   fadein(1);
   display_mstr(105);

   Reply(4430);
   NOption(4431,Node143,4);
end

procedure Node143
begin

   fadeout(1);
   game_time_advance(30 * ONE_GAME_MINUTE);
   fadein(1);

Reply(4460);
NOption(4341,Node999,4);
end



//xxxxxxxxxxxxxxxxxxxx
