/*

        Name:           Jon
        Location:
        Description:

           Created: 22/01/2021 11:48:33

*/

/* Include Files */


//Overrides the pickup p proc.
//#define NPC_REACTION_TYPE       REACTION_TC /* REACTION_TC REACTION_TG REACTION_C REACTION_G */
#define NPC_REACTION_VAR        7 /* same as thief variable */

#include "..\HEADERS\define.h"
//#include "..\HEADERS\<TownName.h>"

#define NAME                    SCRIPT_MBJON

// NOTE: This is set to 0 by default
#define TOWN_REP_VAR            (GVAR_TOWN_REP_BROTHERHOOD)

#include "..\HEADERS\command.h"
#include "..\HEADERS\ModReact.h"
#include "..\HEADERS\party.h"

/* Helper macros */

variable temp;

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure Skill_Check_000_Speech;
procedure Skill_Check_001_Luck;
procedure Skill_Check_002_Luck;
procedure Skill_Check_003_Barter;




// The next lines are added in by the Designer Tool.
// Do NOT add in any lines here.
//~~~~~~~~~~~~~~~~ DESIGNER TOOL STARTS HERE

procedure Jon_0;
procedure Jon_1a_1;
procedure Jon_1a_2a_1;
procedure Jon_1a_2a_2;
procedure Jon_1a_2b_1;
procedure Jon_1a_2b_2;
procedure Jon_1a_D1;
procedure Jon_1a_D2;
procedure Jon_1a_D3;
procedure Jon_1a_D4;
procedure Jon_1a_D5_a1;
procedure Jon_1a_D5_a2;
procedure Jon_1a_D5_b;
procedure Jon_1b_1;
procedure Jon_1b_2;
procedure Jon_1b_3;
procedure Jon_1b_4;
procedure Jon_1b_5;
procedure Jon_1b_6;
procedure Jon_1b_7a;
procedure Jon_1b_7b_1;
procedure Jon_1b_7b_2a;
procedure Jon_1b_7b_2b_1;
procedure Jon_1b_7b_2b_2;
procedure Jon_1c_1;
procedure Jon_1c_2;
procedure Jon_1c_3a_1;
procedure Jon_1c_3a_2a;
procedure Jon_1c_3a_2b_a1;
procedure Jon_1c_3a_2b_a2;
procedure Jon_1c_3a_2c;
procedure Jon_1c_3b;
procedure Jon_1c_3B_a1;
procedure Jon_1c_3B_a2;
procedure Jon_1c_3B_b1;
procedure Jon_1c_3B_b2;
procedure Jon_B1;
procedure Jon_B2_a;
procedure Jon_B2_b;
procedure Node040;
procedure Jon_1a_2a_2_beer;
procedure Jon_1a_2a_2_nuka;
procedure Jon_1a_D5_a2_ok;
procedure Jon_1b_2_beer;
procedure Jon_1b_2_nuka;
procedure OpenDoor ;


//~~~~~~~~~~~~~~~~ DESIGN TOOL ENDS HERE
// The Following lines are for anything that is not needed to be
// seen by the design Tool


/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */
#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)
#define LVAR_Caught_Thief               (7)
#define LVAR_Pissed               (8)



/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */


/* Local variables which do not need to be saved between map changes. */
variable Only_Once:=0;

procedure start begin
end

/* This procedure will get called each time that the map is first entered. It will
   set up the Team number and AI packet for this critter. This will override the
   default from the prototype, and needs to be set in scripts. */
procedure map_enter_p_proc begin
   Only_Once:=0;
   switch_team(self_obj,TEAM_BROTHERHOOD_OF_STEEL)
//   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
call new_plague_check(self_obj, LVAR_Herebefore);

end


/* Every heartbeat that the critter gets, this procedure will be called. Anything from
   Movement to attacking the player on sight can be placed in here.*/
procedure critter_p_proc begin

/* If the critter is mad at the player for any reason, it will attack and remember to attack
   the player should the game be saved and loaded repeatedly. Additionally, if any special
   actions need to be taken by the critter based on previous combat, the critter will remember
   this as well. */
   if(global_var(GVAR_BROTHERHOOD_KLAXON) == 1) then
      set_local_var(LVAR_Hostile,2);

   if ((local_var(LVAR_Hostile) != 0) and (self_can_see_dude)) then begin
       set_local_var(LVAR_Hostile,1);
       self_attack_dude;
       //Macro made by Tom to keep the critter fleeing.
   end

end

/* Whenever the critter takes damage of any type, this procedure will be called. Things
   like setting ENEMY_ and LVAR_Personal_Enemy can be set here. */
procedure damage_p_proc begin

/* If the player causes damage to this critter, then he will instantly consider the player
   his personal enemy. In Critter_Proc or through dialog, actions will be taken against
   the player for his evil acts. */
   if (obj_in_party(source_obj)) then begin
       set_local_var(LVAR_Personal_Enemy,1);
   end

end

/* Any time that the player is caught stealing from this critter, Pickup_proc will be called.
   In here, various things can happen. The most common response is instant hostility which
   will be remembered. */
procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
       set_local_var(LVAR_Hostile,2);
   end
end

/* The dialog system is setup and prepares the player to talk to this NPC. Where To Go
   written by designers are placed in here. Additionally, Reactions are generated and
   stored which affects player interactions. */
procedure talk_p_proc begin



   Evil_Critter:=0;
   Slavery_Tolerant:=SLAVE_TOLERANT;
   Karma_Perception:=KARMA_PERCEPTION1;

   CheckKarma;

   GetReaction;

if(local_var(LVAR_Pissed) == 1 or (dude_is_stupid and local_var(LVAR_Herebefore) == 1)) then begin
   floater_bad(380);
   return;
end

   call set_idiot_savant_int;

       start_gdialog(NAME,self_obj,4,-1,-1);
       gSay_Start;

      if(local_var(LVAR_Herebefore) == 0) then
         call Jon_1a_1;
      else if(global_var(GVAR_MB_ROUND_FOR_EVERYONE) == 1) then
         call Jon_1c_1;
      else if(local_var(LVAR_Herebefore) == 1) then
         call Jon_1b_1;

      gSay_End;
       end_dialogue;


   call restore_idiot_savant_int;

end

procedure timed_event_p_proc begin
end

/* This procedure gets called only on the death of this NPC. Special things like
   incrementing the death count for reputation purposes and Enemy Counters are placed
   in here. */
procedure destroy_p_proc begin
set_global_var(GVAR_JON_DEAD, 1);
/* Increment the aligned critter counter*/
   inc_good_critter
/* inc_evil_critter */
/* inc_neutral_critter */

/* Set global_variable for Enemy status*/
end

/* Look_at_p_proc gets called any time that the player passes the cursor over any object.
   This should only hold the most cursory of glances for the player. */
procedure look_at_p_proc begin
   script_overrides;
   if (local_var(LVAR_Herebefore) == 0) then
      display_mstr(100);
   else
      display_mstr(101);
end

/* The player will see more indepth descriptions from this procedure. They are actively
   looking at the critter and want more information. Things like names can be added here
   if the critter is known to the player. */
procedure description_p_proc begin
   script_overrides;
   display_mstr(102);
end

/* Any time a skill is used on a critter this call is made. This can be to give examinations
   for things like Doctor skill or messages for various other skills. */
procedure use_skill_on_p_proc begin
   call injure_with_skill;
end

/* Should the Player ever cause the NPC too much discomfort that he desires to attack the player,
   this call will be made. Essentially, it stores the Hostile vaule so that the critter remembers
   he was once hostile towards the player.*/
procedure Node998 begin
   switch_team(self_obj,TEAM_JON)
   set_local_var(LVAR_Hostile,2);
end

/* Anytime that there is a need for an ending to dialog, this node is to be called. It will just
   exit from the dialog system without any reprisals from the NPC. */
procedure Node999 begin
//debug_msg("LVAR_Herebefore == "+local_var(LVAR_Herebefore));
if (local_var(LVAR_Herebefore)==0) then
begin
set_local_var(LVAR_Herebefore,1);
end
end

// Skill checks and miscellaneous procedures

procedure Skill_Check_000_Speech begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_CONVERSANT, -25);
if is_success(roll_temp) then
begin
call Jon_1a_D5_a1;
end
else begin
call Jon_1a_D5_b;
 end
end

procedure Skill_Check_001_Luck begin
variable roll_temp;
roll_temp := do_check(dude_obj, STAT_lu, -4);
if is_success(roll_temp) then
begin
call Jon_1b_7b_1;
end
else begin
call Jon_1b_7a;
 end
end

procedure Skill_Check_002_Luck begin
variable roll_temp;
roll_temp := do_check(dude_obj, STAT_lu, -4);
if is_success(roll_temp) then
begin
call Jon_1b_7b_2b_1;
end
else begin
call Jon_1b_7b_2a;
 end
end

procedure Skill_Check_003_Barter begin
variable roll_temp;
roll_temp := roll_vs_skill(dude_obj, SKILL_BARTER, -25);
if is_success(roll_temp) then
begin
call Jon_1c_3a_2b_a1;
end
else begin
call Jon_1c_3a_2c;
 end
end





// Not lines are allowed to be added below here
// The Following lines are from the Design Tool
//~~~~~~~~~~~~~~~~ DESIGN TOOL STARTS HERE

procedure Jon_1a_1
begin
Reply(230);
NOption(mstr(231)+dude_name+mstr(232),Jon_1a_2a_1,4);
NOption(233,Jon_1a_2b_1,4);
NOption(234,Jon_B1,4);
NOption(235,Node999,4);
NOption(236,Jon_1a_D1,-3);
NOption(237,Node999,-3);
end

procedure Jon_1a_2a_1
begin
Reply(mstr(260)+dude_name+mstr(261));
// NOTE: The screen fades to black and back. Decrement the number of caps owned by the PC by 10. Put a beer in the PC's inventory.
if (item_caps_total(dude_obj)>=10) then
NOption(262,Jon_1a_2a_2_beer,4);
// NOTE: The screen fades to black and back. Decrement the number of caps owned by the PC by 10. Put a Nuka-Cola in the PC's inventory.
if (item_caps_total(dude_obj)>=10) then
NOption(263,Jon_1a_2a_2_nuka,4);
NOption(264,Jon_1a_2b_1,4);
NOption(234,Jon_B1,4);
NOption(265,Node999,4);
end

procedure Jon_1a_2a_2_beer begin
   item_caps_adjust(dude_obj, -10);
   give_pid_qty(dude_obj, PID_BEER, 1)
   call Jon_1a_2a_2;
end

procedure Jon_1a_2a_2_nuka begin
   item_caps_adjust(dude_obj, -10);
   give_pid_qty(dude_obj, PID_NUKA_COLA, 1)
   call Jon_1a_2a_2;
end


procedure Jon_1a_2a_2
begin
if (dude_is_male) then Reply(290); else
if (dude_is_female) then Reply(291);
NOption(292,Jon_1a_2b_1,4);
NOption(293,Node999,4);
end

procedure Jon_1a_2b_1
begin
Reply(320);
NOption(321,Jon_1a_2b_2,4);
NOption(322,Node999,4);
end

procedure Jon_1a_2b_2
begin
Reply(350);
NOption(351,Node999,4);
NOption(352,Node040,4);
NOption(353,Node999,4);
end

procedure Jon_1a_D1
begin
Reply(380);
NOption(381,Jon_1a_D2,-3);
NOption(382,Node999,-3);
end

procedure Jon_1a_D2
begin
Reply(410);
NOption(411,Jon_1a_D3,-3);
NOption(412,Node999,-3);
end

procedure Jon_1a_D3
begin
if (dude_is_male) then Reply(440); else
if (dude_is_female) then Reply(441);
NOption(442,Jon_1a_D4,-3);
NOption(443,Node999,-3);
end

procedure Jon_1a_D4
begin
if (dude_is_male) then Reply(470); else
if (dude_is_female) then Reply(471);
// NOTE: Moderate speech check. IF failed, go to Jon_1a_D5_b instead.
NOption(472,Skill_Check_000_Speech,-3);
NOption(473,Node999,-3);
end

procedure Jon_1a_D5_a1
begin
Reply(500);
// NOTE: If the player chooses this option, it counts towards the number of times the PC reveals the location of Vault 31, which is needed to determine whether or not the Wasteland Explorers will be at the vault when the PC returns.
NOption(501,Jon_1a_D5_a2_ok,-3);
NOption(502,Jon_1a_D5_a2,-3);
NOption(503,Jon_1a_D5_a2,-3);
NOption(504,Jon_1a_D5_a2,-3);
NOption(505,Node999,-3);
end

procedure Jon_1a_D5_a2_ok begin
   set_global_var(GVAR_BOS_KNOWS_TIBBETS, 1);
   call Jon_1a_D5_a2;
end

procedure Jon_1a_D5_a2
begin
Reply(530);
NOption(531,Node999,-3);
end

procedure Jon_1a_D5_b
begin
Reply(560);
NOption(237,Node999,-3);
end

procedure Jon_1b_1
begin
Reply(590);
// NOTE: The screen fades to black and back. Decrement the number of caps owned by the PC by 10. Put a Nuka-Cola in the PC's inventory.
if (item_caps_total(dude_obj)>=10) then
NOption(591,Jon_1b_2_nuka,4);
// NOTE: The screen fades to black and back. Decrement the number of caps owned by the PC by 10. Put a beer in the PC's inventory.
if (item_caps_total(dude_obj)>=10) then
NOption(592,Jon_1b_2_beer,4);
NOption(234,Jon_B1,4);
NOption(593,Node999,4);
end

procedure Jon_1b_2_beer begin
   item_caps_adjust(dude_obj, -10);
   give_pid_qty(dude_obj, PID_BEER, 1)
   call Jon_1b_2;
end

procedure Jon_1b_2_nuka begin
   item_caps_adjust(dude_obj, -10);
   give_pid_qty(dude_obj, PID_NUKA_COLA, 1)
   call Jon_1b_2;
end

procedure Jon_1b_2
begin
Reply(620);
NOption(621,Jon_1b_3,4);
NOption(622,Node999,4);
end

procedure Jon_1b_3
begin
Reply(650);
NOption(651,Jon_1b_4,4);
NOption(352,Node040,4);
NOption(622,Node999,4);
end

procedure Jon_1b_4
begin
Reply(680);
NOption(681,Jon_1b_5,4);
NOption(622,Node999,4);
end

procedure Jon_1b_5
begin
Reply(710);
NOption(711,Jon_1b_6,4);
NOption(622,Node999,4);
end

procedure Jon_1b_6
begin
Reply(740);
NOption(741,Jon_1b_7a,4);
NOption(622,Node999,4);
end

procedure Jon_1b_7a
begin
Reply(770);
// NOTE: Difficult roll against the PC's Luck score. IF failed, go to Jon_1b_7a again (Loop to this same node)
NOption(771,Skill_Check_001_Luck,4);
NOption(622,Node999,4);
end

procedure Jon_1b_7b_1
begin
Reply(800);
// NOTE: Difficult roll against the PC's Luck. IF failed, go to Jon_1b_7b_2a instead.
NOption(801,Skill_Check_002_Luck,4);
NOption(622,Node999,4);
end

procedure Jon_1b_7b_2a
begin
Reply(830);
NOption(741,Jon_1b_6,4);
NOption(622,Node999,4);
end

procedure Jon_1b_7b_2b_1
begin
Reply(860);
NOption(741,Jon_1b_7b_2b_2,4);
NOption(622,Node999,4);
end

procedure Jon_1b_7b_2b_2
begin
Reply(890);
NOption(801,Jon_1b_6,4);
NOption(622,Node999,4);
end

procedure Jon_1c_1
begin
if (dude_is_male) then Reply(920); else
if (dude_is_female) then Reply(921);
NOption(922,Jon_1c_2,4);
NOption(923,Node999,4);
end

procedure Jon_1c_2
begin
Reply(950);
NOption(951,Jon_1c_3a_1,4);
NOption(952,Jon_1c_3b,4);
NOption(953,Node999,4);
end

procedure Jon_1c_3a_1
begin
Reply(980);
if (item_caps_total(dude_obj)>=20) then
NOption(981,Jon_1c_3a_2a,4);
// NOTE: Mild barter check. IF failed, go to Jon_1c_3a_2c instead.
if (item_caps_total(dude_obj)>=10) then
NOption(982,Skill_Check_003_Barter,4);
// NOTE: IF the PC's strength is less than 8, go to Jon_1c_3B_b intead.
if (get_critter_stat(dude_obj,STAT_st)>=8) then
NOption(983,Jon_1c_3B_a1,4);
if (get_critter_stat(dude_obj,STAT_st)<=7) then
NOption(983,Jon_1c_3B_b1,4);
NOption(984,Node999,4);
end

// Node Jon_1c_3a_2a
//
// Notes:
//
// Deduct two caps from the PC's inventory. Put the Lucky Horseshoe item in the PC's inventory.

procedure Jon_1c_3a_2a
begin
   item_caps_adjust(dude_obj, -20);
   call OpenDoor;
Reply(1010);
NOption(1011,Node999,4);
end

procedure Jon_1c_3a_2b_a1
begin
Reply(1040);
NOption(1041,Jon_1c_3a_2b_a2,4);
NOption(984,Node999,4);
end

// Node Jon_1c_3a_2b_a2
//
// Notes:
//
// Deduct one cap from the PC's inventory. Put the Lucky Horseshoe item in the PC's inventory.

procedure Jon_1c_3a_2b_a2
begin
   item_caps_adjust(dude_obj, -10);
   call OpenDoor;
Reply(1070);
NOption(1071,Node999,4);
end

procedure Jon_1c_3a_2c
begin
Reply(1100);
if (item_caps_total(dude_obj)>=2) then
NOption(1101,Jon_1c_3a_2a,4);
NOption(1102,Node999,4);
end

// Node Jon_1c_3b
//
// Notes:
//
// Spawn the Lucky Horseshoe on the ground, a hex or two behind Jon.

procedure Jon_1c_3b
begin
Reply(1130);
NOption(322,Node999,4);
end

procedure Jon_1c_3B_a1
begin
Reply(1160);
NOption(1161,Jon_1c_3B_a2,4);
end

// Node Jon_1c_3B_a2
//
// Notes:
//
// Put the Lucky Horseshoe item in the PC's inventory.\

procedure Jon_1c_3B_a2
begin
   call OpenDoor;

Reply(1190);
NOption(1191,Node999,4);
end

procedure Jon_1c_3B_b1
begin
Reply(1220);
BOption(1221,Node998,4);
NOption(1222,Jon_1c_3B_b2,4);
end

// Node Jon_1c_3B_b2
//
// Notes:
//
// Jon will no longer speak to the PC. He will still float the text relating to the Lucky Horseshoe quest if the PC buys a round of drinks, though.

procedure Jon_1c_3B_b2
begin
Reply(1250);
BOption(1251,Node998,4);
NOption(1252,Node999,4);
end

procedure Jon_B1
begin
if (dude_is_male) then Reply(1280); else
if (dude_is_female) then Reply(1281);
// NOTE: IF the PC's strength is below 8, go to Jon_B2_b instead.
if (get_critter_stat(dude_obj,STAT_st)>=8) then
NOption(1282,Jon_B2_a,4);
if (get_critter_stat(dude_obj,STAT_st)<=7) then
NOption(1282,Jon_B2_b,4);
NOption(1283,Node999,4);
end

// Node Jon_B2_a
//
// Notes:
//
// Jon will no longer speak to the PC. He will still float the text relating to the Lucky Horseshoe quest if the PC buys a round of drinks, though.

procedure Jon_B2_a
begin
   set_local_var(LVAR_Pissed, 1);
Reply(1310);
NOption(1311,Node999,4);
end

procedure Jon_B2_b
begin
if (dude_is_male) then Reply(1340); else
if (dude_is_female) then Reply(1341);
BOption(1342,Node998,4);
BOption(1343,Node998,4);
NOption(1344,Jon_1c_3B_b2,4);
end

procedure Node040
begin
Reply(1370);
NOption(1371,Node999,4);
end

procedure OpenDoor begin

   if(obj_is_carrying_obj_pid(self_obj,PID_NUKE_KEY)>0)  then
      transfer_pid_between_objs(self_obj, dude_obj, PID_NUKE_KEY, 1)


end

//xxxxxxxxxxxxxxxxxxxx
